- cfme/tests/infrastructure/test_delete_infra_object.py
* Remove tests is now handled correctly in the case that it does not
exist.
* Reliance on setup_infrastructure_providers is also removed and each
provider is tested and only setup if necessary.
> A few fixes to the delete obj tests

- scripts/template_upload_all.py
This changes the template uploader scripts to base the template name on the timestamp of the "checksums" file they are associated with. This should ensure template names are the same across providers.
> template_uploader name fix

- scripts/post_jenkins_result.py
Merging this will break trackerbot's graph rendering, since it doesn't yet understand the idea of "-1" for the number of tests (and in fact, the API currently turns those values to 0, so the flot JS div0 errors). But if I get buy-in (mainly from @psav) on the "-1 means the build failed" idea, I can get trackerbot patched up pretty quickly to deal with failed builds and then we can merge this.
> [WIP] Post results for failed builds

- artifactor/plugins/reporter.py
From a reporting PoV, skips are now treated as failures so that the
only_failed option in artifactor shows up skips and failures, not just
failures.
> Skips are now treated as failures

- cfme/tests/perf/test_ui_automate.py
- cfme/tests/perf/test_ui_cloud.py
- cfme/tests/perf/test_ui_configure.py
- cfme/tests/perf/test_ui_control.py
- cfme/tests/perf/test_ui_infrastructure.py
- cfme/tests/perf/test_ui_intelligence.py
- cfme/tests/perf/test_ui_optimize.py
- cfme/tests/perf/test_ui_services.py
- fixtures/perf.py
This fixture exposes all queries by enabling changing the log level for level_rails from info to debug.  This allows the perf UI tests to perform analysis of the number of queries per page render.
> Fixture for level_rails debug for perf ui tests

- utils/testgen.py
Currently, we get an error during collection when we run `py.test ... --use-provider rhevm`
> Pick random provider only if there are any available

- fixtures/parallelizer/__init__.py
- fixtures/single_appliance_sprout.py
When providers are having bad times, it can help to be able to raise the value.
> Configurable provisioning timeout for Sprout

- cfme/tests/infrastructure/test_customization_template.py
- markers/bz.py
- utils/bz.py
@jkrocil pointed out that the bug 1092951 resolved to 1083198 that is already closed (but for correct version) because they merged the system image type and customization template issue together. This enables to ignore particular bugs if such cases occur.
> Able to ignore some of bugs in BZ

- scripts/cleanup_old_vms.py
- utils/mgmt_system.py
* list_vm() uses Name tag if present (makes the cleanup script work again)
* cleanup script now checks for old `^i-` instances.
> EC2 Cleanup

- cfme/tests/cloud/test_instance_power_control.py
Removed a BZ fixed in 5.3, added a BZ that is still relevant in 5.3.z.
Old (removed):
https://bugzilla.redhat.com/show_bug.cgi?id=1115546
(5.3 clone is here actually https://bugzilla.redhat.com/show_bug.cgi?id=1135606 )
New:
https://bugzilla.redhat.com/show_bug.cgi?id=1183757
> Update RHOS-related BZ

- cfme/tests/cloud/test_cloud_timelines.py
This fixes RHOS6 timelines, but not sure yet if it should apply to all, awaiting further testing.
> Fix timelines

- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/remote.py
- fixtures/pytest_store.py
- fixtures/ui_coverage.py
- scripts/data/coverage/coverage_hook.rb
- scripts/data/coverage/coverage_merger.rb
- utils/appliance.py
This is working, but merits some discussion, and testing. Until we get PRT metadata support, PRT doesn't know that you need to add `--ui-coverage` to your pytest commandline to test this. This is *completely* untested in non-parallelized runs, but might work. I'd prefer to get feedback on parallelized sessions, though. :)
I moved all of the appliance-specific stuff over into IPAppliance, but I think that just made a bit of a mess. We definitely want to leave all of the public `IPAppliance.coverage*` methods on IPAppliance so it's easy to install coverage and collect reports, but all of the work should probably be done inside `fixtures.ui_coverage`.
`fixtures.ui_coverage` itself should have the work it's doing broken out into manageable functions, if for no other reason than to simplify …
> UI Coverage Parallel Appliance refactor

- cfme/automate/service_dialogs.py
- cfme/tests/automate/test_customization_paginator.py
SplitTable locator in service_dialogs updated
ServiceDialogs are now created with all the necessary fields/elements
customization_paginator test now works if other dialogs are present as well
---
Looking at the 5.2.z jenkins run, it failed on the locator as well, so verpicking doesn't seem necessary.
> Fix customization_paginator test 

- cfme/tests/perf/test_ui_automate.py
- cfme/tests/perf/test_ui_cloud.py
- cfme/tests/perf/test_ui_configure.py
- cfme/tests/perf/test_ui_control.py
- cfme/tests/perf/test_ui_infrastructure.py
- cfme/tests/perf/test_ui_intelligence.py
- cfme/tests/perf/test_ui_optimize.py
- cfme/tests/perf/test_ui_services.py
- fixtures/perf.py
- utils/pagestats.py
Reduces the total number of times these tests grep for the ui worker pid.  I set the scope to the module level rather than session incase the UI worker does fail, not all hope is lost of using the incorrect pid when it restarts, perhaps a few tests while the worker is restarted.
> ui_worker_pid fixture

- sprout/appliances/models.py
- sprout/appliances/tasks.py
- utils/mgmt_system.py
* limit number of concurrent template builds
* added some template methods in mgmt_system + longer timeouts for rhev-m and deleting after unsuccessful attempt
> Sprout - better RHEV-M handling

- sprout/appliances/models.py
- sprout/appliances/tasks.py
- utils/mgmt_system.py
By adding a temporary name, it is possible to recover from the timeout. The temporary name is passed to all the templatizing functions and all templates no matter what provider is used, it is however used only in RHEV-M, the rest is ignored.
*/me now finds mgmt_system quite cumbersome for such a complex process ...*
> [WIP] Add temporary name to the RHEV templates

- sprout/appliances/migrations/0008_appliance_uuid.py
- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/sprout.sh
- sprout/sprout/settings.py
- utils/mgmt_system.py
* Changed the appliances' status retrieval to use less requests
* We now store the UUIDs of the appliances, which makes the life easier. This also makes renaming better since we know what appliance is what.
> Sprout performance update + UUID

- cfme/tests/cloud/test_tenant.py
- cfme/tests/infrastructure/test_snapshot.py
- utils/testgen.py
Added require_fields to testgen parametrized tests to make it sure that the tests don't go crazy when some not-so-well specified provider will come in.
> Added require_fields to testgen parametrized tests

- cfme/automate/explorer.py
`Domain` object has `None` as a parent, not a `TreeNode` object - unlike `Namespace` obj for example - so we can't call `.navigate_tree()` on that.
> Fix automate domain navigation

- cfme/storage/managers.py
- cfme/tests/configure/test_db_backup_schedule.py
- cfme/tests/configure/test_register_appliance.py
- cfme/tests/configure/test_server_name.py
- cfme/web_ui/__init__.py
- markers/bz.py
List accordion (the one in left eg. in Provider details) was mistakenly caught by the form type locator, therefore failing everything. Now I have put a check in it that ensures there is a table in it.
I could have done this simply by filtering by `is_displayed` but I don't see that as a clean way to do it since each call to `is_displayed` is a slowdown.
I also found there were separate instances of `InfoBlock` in some places, found and fixed that too.
I also discovered the form type infoblock does not have to have the fieldset as the root element. I then had to add additional selenium call for the detection :(. But it works now.
> Fixed automatic InfoBlock type detection.

- utils/appliance.py
Also fixed ntp-clock-fix being run twice in a row.
> Appliance is now rebooted by default after a rhel update

- cfme/provisioning.py
Issue was that the templates headers changed from cloud to infra
the 'tenant' column is added in cloud. This gave an off by one error
where the internal header cache of the table didn't match what was on
the page. This has been fixed with an update cache call inside the
navigatation function. The fix may be supplanted by something better in
the coming days, but this should get things working again.
{{pytest: cfme/cloud/instance.py cfme/cloud/instance.py cfme/fixtures/tracer.py cfme/infrastructure/virtual_machines.py cfme/infrastructure/virtual_machines.py cfme/infrastructure/virtual_machines.py cfme/services/catalogs/cloud_catalog_item.py cfme/tests/infrastructure/test_cloud_init_provisioning.py cfme/tests/infrastructure/test_host_provisioning.py …
> Fix template not found issue

- cfme/cloud/provider.py
- cfme/infrastructure/provider.py
- fixtures/provider.py
* Skipping a provider when it fails to set up is now a little more
verbose and explains whether the test was skipped because the provider
failed to set up in this test, or in a previous one.
* Providers were failing to stats match when being setup using the
provider crud test because of a bug in the way non-db stats matching
was handled. A refresh of the UI was not performed for each
retry. This had two consequences:
* Stats matching generally took a lot longer than it needed to due to
the fact that first time the page is landed on, the counters will sit
at 0 for at least until the first RefreshTimer is activated.
* Stats matching was inaccurate as the counters would hold on their
current page value, until the a RefreshTimer timeout triggered a
refresh, causing the page to coincidentally …
> Multiple fixes to provider setup

- cfme/configure/configuration/__init__.py
- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/remote.py
- fixtures/single_appliance_sprout.py
Made the appliance deleting more verbose and more 'hardened'. Moved the responsibility of deleting the appliances from slaves to master (had to add a signal for that).
@seandst Can the appliance deletion somehow intercept the cov gathering process or whatever happens in the end? Because it deletes appliances right when the slave ends.
> Slight update on configuration; sprout client tweaks

- cfme/fixtures/login.py
- cfme/fixtures/pytest_selenium.py
If a jQuery erro bubbles up, it gets caught, browser gets killed (so it clears cookies and stuff) and it is tried again.
> Harden the blank page error detection

- fixtures/parallelizer/__init__.py
- sprout/appliances/models.py
This will write something like this when pool request is completed or timed out:
```
Fulfilled: True
Progress: 100%
Appliances:
s_appl_downstream-53z_150127_Fk8IAcd7:
datetime_leased: 2015-02-10T09:20:33.724988+00:00
id: 3809
ip_address: xxxx
leased_until: 2015-02-10T10:50:34.216523+00:00
marked_for_deletion: False
power_state: on
provider: xxxx
ready: True
status: The appliance is ready.
status_changed: 2015-02-10T09:20:45.142070+00:00
template_id: 873
template_name: xxxx
uuid: 7868ac12-c174-436c-8f1a-8e31b68e2547
s_appl_downstream-53z_150127_7QAxQQuy:
datetime_leased: 2015-02-10T09:20:33.725061+00:00
id: 3811
ip_address: xxxx
leased_until: 2015-02-10T10:50:34.228248+00:00
marked_for_deletion: False
power_state: on
provider: xxxx
ready: True
status: The appliance is ready. …
```
> Dump the pool info after request

- sprout/appliances/models.py
- sprout/appliances/tasks.py
* Log when appliance is given to a pool
* Run cleanup() method on providers when templates are deployed. Currently cleans up the floating IPs in RHOS
> Sprout - updates for better stability

- cfme/tests/perf/queue/test_queue.py
- utils/perf_message_stats.py
* Use a finalizer to clean up log files incase of exception.
* Round timings in total time graphs.
* Move opening of evm log file into evm_to_messages for consistency.
* Adding filters for Amazon and Openstack cloud providers for future use with cloud providers.
> Improvements to queue perf test

- sprout/appliances/tasks.py
Discovered recently with new 5.3 build - it has same version but new date. Shepherd however does not cehck date if the template has version. This should fix this.
> [NOTEST] Sprout - Shepherd now knows about multiple dates in one version

- cfme/js.py
- cfme/tests/test_appliance.py
- metaplugins/blockers.py
- metaplugins/skip.py
- utils/pytest_shortcuts.py
The Prototype framework was removed completely so the script needs to count with the fact that Ajax can be undefined. Then it returns just 0 if Ajax is not defined, making everything backwards-compatible
{{pytest: -m smoke -v --use-provider vsphere55}}
> Count with Prototype (Ajax) removed + do not test mingw package on 5.4

- cfme/dashboard.py
- cfme/login.py
- cfme/tests/test_login.py
- Automated clicking of the login button **does not work** on 5.4 and up,
so I employed a JS hack to get around it. We need to find a better solution,
but right now we need CI results more. :)
- I removed test_logout because test_login asserts that logout works; it's not
completely appropriate testing, but I got over it pretty quick
- I also threw in an `ensure_browser_open` so you don't have to manually open
a browser to login. Now you can just call `cfme.login.login_admin`
> login works for 5.4 and miq

- cfme/web_ui/menu.py
Menus have changed to a new style so in order to support them we need to
version pick the locators. Since we don't want to do that at import
time we create a dumb class to defer the version picking as a property
attribute. Future work would be to ensure that as much version picking
is done at the top level. However, there is due a new menu module which
will reduce the navigation overhead considerably.
> Menu fixes

- cfme/web_ui/toolbar.py
It seems the ``div`` has changed to a ``span`` for the ``tP`` element. Since we
already use the "don't care" attitude in another place in the codebase
this quick fix should get us there.
> Div -> Don't care

- fixtures/parallelizer/__init__.py
- fixtures/single_appliance_sprout.py
It is not 100% though on the sprout's side (the tasks do not know about each other so maybe some provisioning task will interfere with the deletion task), but it should work on most appliances from the pool.
> Try to delete pool on Sprout request timeout

- fixtures/parallelizer/__init__.py
The config options object was not serializable, since at heart it is a
dict and there only seemed to be one place where we used it and tried to
__getattr__ instead of __getitem__ as expected, I changed this.
> Parallelizer broke because $reasons

- utils/perf_message_stats.py
This corrects the "total time" charts for each message in which timing values were no longer ordered correctly.
> Sort messages by message id before placing them into ordered lists.

- cfme/web_ui/tabstrip.py
Eg. in `My Settings` and so. This is currently killing some tests.
> Found and fixed new type of tabstrip (for upstream)

- sprout/sprout/settings.py
* wrong task specified
* do the provider scaenge more often
> Sprout - fix settings

- cfme/configure/configuration/__init__.py
- cfme/web_ui/__init__.py
* Zones can have also space before :
* Tables did not normalize the spaces
> Fix Zones and table

- cfme/configure/configuration/__init__.py
Fixes #1642 
{{pytest: -v -k server_roles_changing }}
> Ignore storage options when setting roles and storage not enabled

- cfme/configure/configuration/__init__.py
`$j` is not defined there so it raises a `WebDriverException` about that. But since it works even without calling those JSs, it should give us all green on latest upstream smokes (and therefore automated template testing).
> Make the zone tests work on latest upstream

- fixtures/parallelizer/__init__.py
- fixtures/single_appliance_sprout.py
* pull the cfme_data's basic_info to runtime in multi appliance sprout
* use conf.runtime in single appliance sprout
{{pytest: -v -k vm_analysis --long-running}}
> Fix runtime config - fixes vddk_url problem

- cfme/tests/cloud/test_provisioning.py
- utils/mgmt_system/openstack.py
The volume provisioning tests seem to need some hardening.
> Wait for instance to disappear + longer volume delete timeout

- cfme/tests/cloud/test_cloud_timelines.py
The cloud timelines tests are currently being skipped because of an unresolved BZ. I'm trying to work around that BZ to ensure that the tests get run and not get skipped.
> Fix cloud timelines - Remove BZ blocker 

- sprout/appliances/models.py
- sprout/appliances/templates/appliances/_providers.html
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/views.py
**wip for not testing**
This will prevent people asking me *"why sprout does not give me an appliance?"* when they ask for them in the worst constellations when all providers that contain desired templates are full.
This will be updated in the future to take the shepherd into account.
> [WIP] Sprout - show slots at the My Appliances display

- cfme/tests/automate/test_common_methods.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_genealogy.py
- cfme/tests/infrastructure/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/infrastructure/test_retirement.py
- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/services/test_add_remove_vm_to_service.py
- cfme/tests/services/test_myservice.py
- cfme/tests/services/test_service_catalogs.py
- fixtures/templateloader.py
- utils/testgen.py
We can safeguard against missing tempaltes in providers by scavenging them and then taking it into account during parametrization phase. To save the load, the provider templates get loaded in the beginning.
{{pytest: -v --collect-only --use-provider complete --long-running --perf}}
> Templateloader for test collection

- cfme/fixtures/pytest_selenium.py
- cfme/login.py
I noticed we had a failure on test_login, this should help it.
> Make it possible to override ajax timeout time

- data/templates/test_report.html
Things like `<lambda>` were making the output unreadable. This should fix it
{{pytest: -v -k test_provision_from_template_with_attached_disks --long-running --use-provider rhos5 }}
> Artifactor report - escape the error messages

- cfme/tests/control/test_actions.py
- sprout/appliances/tasks.py
- utils/virtual_machines.py
This should make everything that does not provision VMs via CFME UI (+ sprout) pick the least used datastore for provision if it is vsphere and it has `allowed_datastores` in yaml.
> Use the datastore picking on (almost) everything in background

- cfme/configure/access_control.py
{{pytest: -v -k 'test_user_crud or test_group_crud or test_role_crud' --long-running}}
> Input conversions for access control

- cfme/tests/test_rest.py
`Cannot edit VM. Physical Memory Guaranteed cannot exceed Memory Size` - this started to appear, seems that just increasing the memory is enough, probably some template has changed.
> Address RHEV issue with memory

- cfme/tests/configure/test_visual_cloud.py
* Tests should use an OpenStack provider, as Amazon has no tenants
> Fix visual tests

- cfme/web_ui/__init__.py
- cfme/web_ui/paginator.py
- cfme/web_ui/tabstrip.py
* Tabstrip needed docs changes
* Paginator updated
* Added __add__ and __radd__ so that XPath chains using input can be created
{{pytest: cfme/tests/configure/test_visual_cloud.py}}
> Paginator and Tabstrip input conversions

- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/sprout/settings.py
* order the groups by their shepherd fulfillment status
* shepherd always provisions one appliance at time (per group), but runs more frequently
* shepherd now picks provider by its load
Also improved the `process_delayed_provisioning_tasks` which now looks in shepherd whether such appliance was provisioned on background.
> [WIP][NO TEST] Sprout - more fair shepherd generator

- utils/bz.py
* If we don't have upstream appliance, do not evaluate the upstream part of the `is_opened` (@jkrocil found this)
* Scavenge the "upstream version" from the bugzilla itself. Needs `product:` in yaml. Compatible with the older `upstream_version:` value in yaml.
> Bugzilla correct handling upstream

- fixtures/ssh_client.py
- utils/appliance.py
- utils/ssh.py
This does two major things:
- Pubkeys are supported
- Connection transports are reused
Those things provide two major benefits:
- SSH connections are made more quickly ones keys are installed
- Appliances using the same keys (parallel test run, for example) can easily SCP files *to each other*, which I need for speeding up UI Coverage reporting.
Additionally, the ssh_client gets its client from the pytest store now, and the IPAppliance class caches its ssh client in an attempt to support reusing the client.
Public key workflow, seen in `SSHClient.connect`, and `SSHClient.install_ssh_keys`:
1. When connecting, check to see if keys are installed (or currently being installed). If not, install them.
- Mark the keystate as installing so we don't try to install keys while we're installing keys …
> SSH connection reuse and pubkey auth support

- scripts/cleanup_old_vms.py
proposed change to jjb/utility.yaml:
command: |
python scripts/cleanup_old_vms.py -f --max-hours 4 '^test_', '^i-'
python scripts/cleanup_old_vms.py -f --max-hours 12 '^jenkins'
> Tweak cleanup vms

- utils/tests/test_wait.py
- utils/wait.py
Result should be like:
```
2015-03-18 11:35:01,694 [E] Could not complete function i_sleep_a_lot() at /home/mfalesni/git/cfme_tests/utils/tests/test_wait.py:17 in time, took 2.21 (utils/wait.py:107)
2015-03-18 11:35:01,702 [E] The last result of the call was: 2 (utils/wait.py:108)
```
{{pytest: utils/tests/test_wait.py -v}}
> wait_for dumps last result

- scripts/clone_template.py
- utils/appliance.py
*should not fail on appliance provision*
{{pytest: -v -k appliance_replication --long-running --use-provider vsphere55 }}
> Use vSphere datastore balancing everywhere

- cfme/infrastructure/virtual_machines.py
- cfme/js.py
- cfme/tests/cloud/test_tag_cloud.py
- cfme/web_ui/search.py
* Retirement date set using JS
* Fix search button locator
* test_tag_cloud used the toplevel locator which did not reset the view to the quadicons
{{pytest: -v -k '(vm_retire_extend or tag_cloud or search)' --long-running}}
> Jenkins fixes

- cfme/tests/cloud/test_instance_power_control.py
This is an old BZ that's no longer relevant.
@mfalesni In any case, this shouldn't be skipping in 54z - not sure what's going on:
```
Skipped: Skipping due to these blockers:
- Bugzilla bug https://bugzilla.redhat.com/show_bug.cgi?id=1122039 (or one of its copies)
```
This BZ is closed in 530 and there are no clones.
> Remove old BZ

- fixtures/parallelizer/__init__.py
We really *should* care, since this can potentially kill a slave in the
middle of its teardown, but for now this should address more (maybe all?)
of our weird jenkins stalls. I'll put proper shutdown handling in later.
> Don't care about slaves once they let us know they've finished.

- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/remote.py
- fixtures/pytest_store.py
The master will wait a polite amount of time for a slave to shut down,
set at 10 minutes for now. If more time than that goes by, the slave is
killed. Additionally, py.test will log not only that a slave is shutting down,
but that it has, in fact, shut down (or died).
I also got to remove some vestigial event ordering functionality that became
useless when we got everything parallel happening in master's runtestloop.
> Parallelizer doesn't block on slave shutdown, has better logging

- utils/virtual_machines.py
We've been getting some operation collisions, this logging should help tracking it down.
{{pytest: -v --use-provider rhevm33 --use-provider rhevm34 --use-provider rhevm35 -k 'vm_retire_extend' }}
> More logging in deploy_template shortcut to track down the RHEV errors

- cfme/fixtures/pytest_selenium.py
- cfme/web_ui/__init__.py
By introducing the check for rails errors in element(), force_navigate's efforts to kill browser were not possible to do because it detected the error in is_displayed() (which uses element()) and bailed out. Short term solution is to add _no_deeper=True to the function call, long term one is to unify and DRY the rails detection code.
> Fix element() masking the force_navigate effort

- cfme/fixtures/pytest_selenium.py
- cfme/js.py
- cfme/web_ui/__init__.py
Calendar web_ui element now uses set_angularjs_value in 5.4+
> Add set_angularjs_value to sel (5.4+ inputs)

- utils/blockers.py
- utils/bz.py
{{pytest: -v -k 'test_quadicon_terminate' --long-running}}
> Simplified BZ logic + no forceskip

- cfme/tests/cloud/test_provisioning.py
**WIP FOR NOT GOING ANOTHER ROUND OF TESTS - OK TO MERGE**
{{pytest: -v -k provision_from_template_with_attached_disks --long-running --use-provider rhos4 }}
> [WIP][OK TO MERGE] Openstack attach volume test fixed

- cfme/fixtures/login.py
Have seen that for some reason there was an issue where the browser was already logged in, but the logged_in fixture didn't detect it and raise a NoSuchElementException. This PR takes care of cases where jquery is present on the page, but where the login boxes are absent for some reason. In this case, we just recycle the browser.
{{pytest: -k test_login}}
> Adding strange detection for already logged in

- conftest.py
If the exception is not one that we explicitly generate then the second
argument may be missing. This caused issues in some runs and so to
mitigate we now check the length of the Exception arg to be 2 before
trying to access the port. If it's not present we just set port to None,
which doesn't harm anything.
> Protect against other exception types

- cfme/fixtures/pytest_selenium.py
{{pytest: -v -k "delete_infra_object or group_roles" --long-running }}
> Quit the browser on the rails exception to forget the session

- requirements.txt
After 1.2 is released, change it back to `python-bugzilla>=1.2.0`
> python-bugzilla - Use not-yet-released 1.2 from git

- cfme/tests/control/test_compliance.py
- conftest.py
- utils/appliance.py
{{pytest: cfme/tests/control/test_compliance.py -v --long-running --use-provider vsphere55 --use-provider rhevm33 }}
> Set timeout of the provisioned appliance and ensure we have browser_steal

- cfme/fixtures/pytest_selenium.py
I will try to recreate the conditions by using this very ugly meta data:
{{pytest: -v -k 'test_vm_control_policy_crud or test_delete_cluster or test_edit_storage_chargeback or test_add_delete_service_catalog or test_list_page_per_item or test_compressed_view or test_add_new_compute_chargeback or test_checkbox_dialog_element or test_service_dialog_duplicate_name or test_delete_compute_chargeback or test_set_retirement_date or test_provision_approval or test_rh_creds_validation or test_vm_compliance_policy_crud or test_assign_events_to_host_control_policy or test_collect_log_depot or test_radiobutton_dialog_element or test_tile_defaultview or test_delete_host or test_provider_refresh or test_vm_condition_crud or test_reorder_elements or test_expanded_view or test_list_defaultview or …
> Ignore jQuery errors

- cfme/tests/test_rest.py
- utils/api.py
{{pytest: -v -k "add_lifecycle_event or query_simple_collections" --long-running }}
> REST - Next round.

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/reports/test_report_chargeback.py
These tests automate the creation of chargeback reports that are filtered by either tags or owners.
> Test to create chargeback reports

- fixtures/blockers.py
- utils/blockers.py
I don't know how much will it like the fixture args (parametrized works), but it seems we don't use the ddynamic ones yet so it does not make troubles.
{{pytest: -v --long-running --list-blockers --collect-only }}
> [Bugzilla] List blockers on startup

- fixtures/pytest_store.py
I'd always intended to expose the store as `pytest.store`, but I never implemented the `pytest_namespace` hook :(
> expose the pytest store as pytest.store

- conftest.py
Funny thing, if you don't erase the evidence, the Appliance Police
will keep on arresting you. :( This fix forces the Appliance Police to
make a new check of the port availability everytime. We hadn't seen this
issue crop up before because most failures had been happening due to the
UI worker dying. This meant that 443 was still contactable and hence the
cache that the utils.net keeps, did not affect the Police.
If a port is uncontactable, because of network issues for example, then
the fact the port is unreachable was cached in the utils.net module and
because the force flag was absent was never rechecked and the cached
result just served up again and again. Thus continuing slaves just led
to them getting pulled over by the Appliance Police again for crimes
they hadn't committed.
> Force checking of ports in appliance policer

- sprout/appliances/migrations/0019_auto_20150430_1546.py
- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/sprout/settings.py
Groups can now be configured with an 'age' of template to be considered obsolete. If the template is older than that number of days, it won't be pulled from trackerbot. If the option for deleting is on, it will also delete such templates if they are not the latest (therefore the only) ones.
*This is the first (simpler) option of automatic deletion*
> [WIP][NO TEST] Sprout - Care about template age.

- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/hooks.py
- fixtures/pytest_store.py
- fixtures/update_appliance.py
This allows us to bring in additional update urls on an already configured appliance for testing.
This commit includes the beginnings of a parallelizer hooks system, which I'll likely be expanding over
time to keep myself sane.
> explicit update_urls handling outside of appliance configuration

- conftest.py
- fixtures/artifactor_plugin.py
Merkyl was not collecting logs and was returning Error 500 every
time. The following changes were made to get it working again:
* Merkyl was testing to see if the file existed. If it did, it would
replace the file and restart Merkyl. At the risk of missing something,
the setup now checks to see if the file is non-zero, and in that case,
replaces it with the _good_ version.
* The Merkyl workaround fix was taking place as a fixture. The setting
up of Merkyl was done as part of a pytest configure plugin. Hence the
files started tailing during configure and then the fixer came and
ironically broke everything by restarting Merkyl and ruining the
accessibility of the logs. We now reset up merkyl after restarting it.
> Fix Merkyl

- cfme/automate/explorer.py
The code for checked both Locked and Unlocked node trees was returning
an error if the match wasn't present. This was treated as True when
bool'd and hence was returning the wrong result when the query for
is_locked was being run.
{{pytest: -k test_domain_present}}
> Fixed Automate Domains Locked property

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_timelines.py
* Timelines tests continue to be problematic
* Recent change to cloud timelines test meant that if there were no
events, False was returned instead of 0. As a result, the wait_for
fail condition did not match as Falde != 0 and hence it believed an
event had been detected.
* Update infra timelines tests to follow same methodology, potentially
hardening them slightly
> Timelines fix

- cfme/tests/configure/test_default_views.py
Params in yaml needed to be altered based on appliance stream. Basically
verpicking. If this kind of solution is accepted, maybe we can make this
a feature of the yaml loader, but for now, this seems to work well enough.
Tests will fail, because there is an associated yaml change. However, if I merge it, without this change, it will also break current tests. So I'll wait until the change it merged.
> Fixed views collection params

- cfme/tests/distributed/test_appliance_replication.py
This adds a test to cover a gap in our distributed testing, which is the case where two appliances are in the same region, with one appliance connected to the database owned by the second appliance.
> External Database Appliance test

- cfme/configure/configuration/__init__.py
- cfme/tests/test_rest.py
- cfme/tests/test_utilization.py
Always unset roles when using the CM
Test no longer prints to stdout and always clears providers and C&U roles
{{pytest: -v -k test_utilization}}
> Fix utilization tests

- requirements.txt
Something they changed made our automation sad. Sticking to 2.7.0 until we solve this issue.
https://pytest.org/latest/changelog.html#compared-to-2-7-0
> [WIP][NO TEST] Temporary stick with pytest 2.7.0

- cfme/tests/infrastructure/test_esx_direct_host.py
- utils/version.py
It now ignores vSphere providers with version lesser than 5 and also if the version is not stated in the YAML at all.
> [WIP][NO TEST] Tweak ESX direct host test parametrizing

- cfme/infrastructure/repositories.py
- cfme/web_ui/__init__.py
* This test has changed from 5.3, 5.4 with the basic view now being
Quads instead of list based. I took the approach of working with what
is provided as the default, as opposed to changing the view to suit
the automation. This meant introducing some version sensitive lines
into the code base which are ugly, but unfortunately necessary.
* Added a new Quadicon dummy for repository
* Added docs for other undoc'd quads
{{pytest: -k cfme/tests/infrastructure/test_repositories.py}}
> Fixed Repository test

- utils/blockers.py
- utils/bz.py
- utils/version.py
It seems that with new version in release flags, it falls apart. This tries to incorporate the version fields once again. It now also takes fixed_in into account when testing.
*This is probably going to take a long time*
{{pytest: -v --collect-only --list-blockers}}
> Trying to mitigate some weirdness from BZ

- cfme/cloud/instance.py
- cfme/cloud/provider.py
The cloud provider code that navigates to the instance list did not count with instance count being zero. Now the nav function returns False when the number is zero so the code in instance module can react appropriately.
{{pytest: cfme/tests/cloud/test_cloud_timelines.py -v -k provider_event --long-running --use-provider rhos4-ga}}
> Extend corner-case with instance navigation

- cfme/tests/configure/test_default_views_cloud.py
{{pytest: -v -k 'test_expanded_view or test_compressed_view'}}
> Test cloud expanded and compressed views

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -v -k provider_refresh --long-running}}
> REST Refresh test also waits for the VM to appear

- cfme/tests/automate/test_buttons.py
- cfme/tests/configure/test_about_links.py
- cfme/tests/configure/test_docs.py
- cfme/tests/configure/test_server_roles.py
- cfme/tests/configure/test_session_timeout.py
- cfme/tests/configure/test_tag_category.py
- cfme/tests/configure/test_timeprofile.py
- cfme/tests/configure/test_version.py
- cfme/tests/configure/test_workers.py
- cfme/tests/configure/test_zones.py
- cfme/tests/services/test_catalog.py
- cfme/tests/test_login.py
This PR adds the @pytest.mark.sauce marker to a number of tests that don't require a provider be added to the appliance. This is intended to expand the coverage of the nightly sauce tests.
> Adding sauce markers to a bunch of configuration tests.

- fixtures/artifactor_plugin.py
- scripts/dockerbot/dockerbot.py
* We need a blank setup.py file to ensure that the project root is
recognised by pytest as the project root, else it messes up the
project locations for test naming.
* In PRT, Artifactor wasn't having a chance to finish before it was
killed so for short tests, this led to some tests never being
reported.
* Dockerbot didn't handle the TRACKERBOT environment variable outside of
the prtester mode. This was never normally needed but with the onset
of template loading from trackerbot at the start of the test run. This
became necessary.
> A few fixes

- cfme/tests/cloud_infra_common/test_tag_objects.py
- utils/providers.py
I noticed that sometimes the provider gets a bit clunky with the refresh. This - when the provider already exists and when requested - deletes the provider if an error happens during validation and then re-adds it.
> setup_a_provider - delete_failure

- cfme/tests/control/test_actions.py
- utils/virtual_machines.py
{{pytest: cfme/tests/control/test_actions.py -v --long-running}}
> deploy_template() shortcut allows for autoskip

- utils/mgmt_system/scvmm.py
This bit was missing, preventing the cleanup script from processing the SCVMM provider.
> SCMMM#vm_creation_time

- cfme/exceptions.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/test_utilization.py
- cfme/web_ui/flash.py
* flash module now raises its own type of exceptions
* some tests converted to skip on providers that fail to set up
{{pytest: cfme/tests/control/test_actions.py cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/test_utilization.py -v --long-running --use-provider rhevm35 --use-provider vsphere55 }}
> Flash messages exception; skip broken providers

- cfme/tests/automate/test_domain_priority.py
- cfme/tests/automate/test_method.py
- cfme/tests/automate/test_namespace.py
- cfme/tests/automate/test_vmware_methods.py
- utils/appliance.py
- utils/events.py
Removed default domain dependance for test
{{pytest: cfme/tests/automate/test_method.py cfme/tests/automate/test_namespace.py cfme/tests/automate/test_vmware_methods.py cfme/tests/infrastructure/test_vm_analysis.py --long-running}}
> Removed default domain dependance for test

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_snapshot.py
Use full template for snapshots
{{pytest: -k test_verify_revert_snapshot cfme/tests/infrastructure/test_snapshot.py --use-provider complete --long-running}}
> Use full template for snapshots

- cfme/tests/control/test_actions.py
- utils/mgmt_system/ec2.py
- utils/mgmt_system/openstack.py
- utils/providers.py
- utils/testgen.py
{{pytest: cfme/tests/control/test_actions.py -v --long-running --use-provider complete}}
> Extend actions/events testing with cloud providers

- cfme/tests/control/test_alerts.py
{{pytest: cfme/tests/control/test_alerts.py -v --long-running }}
> Alerts tests resurrected

- cfme/tests/distributed/test_appliance_replication.py
This hack aims to work around an issue with navigation when setting up workers for replication tests.
> Altering the navigation to workaround a selenium issue

- cfme/tests/configure/test_docs.py
- requirements.txt
- utils/version.py
also **Check Cloudforms version instead of CFME version in docs**
PyPDF2's `extract_text()` is very fragile and can't handle CFME PDFs. pdfminer is a bit harder to use but can extract all the text from the title page allowing us to check the version as well. And since some docs (like REST and SOAP) don't contain CFME version anywhere, we have to check for Cloudforms version instead.
{{pytest: cfme/tests/configure/test_docs.py -k test_contents -v }}
> Change PyPDF2 for pdfminer

- cfme/fixtures/pytest_selenium.py
This is what broke jenkins. It's caused by `test_vm_clone` tests not being able to find "Default" automate datastore.
**How to test:**
Rename the "Default" automation datastore to anything else... e.g. "Default_2"
Run: `py.test cfme/tests/services/test_catalog_item.py`
Expected: lots of FAILs, no ERRORs
I'll set this up to be tested on PRT as well but I've got no idea what's gonna happen without the Default --> Default_2 datastore rename.
{{pytest: cfme/tests/services/test_catalog_item.py -v }}
> Check for modal window before navigating

- cfme/tests/test_rest.py
When making these tests, I forgot to uncollect them where they don't work due to older API.
> Uncollect some REST tests for 5.3

- cfme/fixtures/pytest_selenium.py
- cfme/tests/control/test_actions.py
{{pytest: cfme/tests/control/test_actions.py cfme/tests/cloud_infra_common/test_tag_objects.py --long-running --use-provider complete -v}}
> ec2 tries VM refresh to trigger the events.

- cfme/tests/control/test_actions.py
- cfme/tests/control/test_alerts.py
- utils/events.py
I don't know whether will the event listener listen even in the docker conainer, but this is more to check whether all stuff works.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py cfme/tests/control/test_alerts.py cfme/tests/control/test_actions.py -v -m uses_event_listener --long-running --use-provider vsphere55 --event-testing}}
> When creating the AE QE event hook, copy the class to retain the schema

- markers/uncollect.py
`uncollectif` was failing when an item did not have callspec. Now it uses a function that guards against missing callspec so the KeyError is raised and caught.
> uncollectif is more verbose

- scripts/dockerbot/pytestbase/Dockerfile
py_test_base needed a few updates because of a pip incompatibility the
following changes were made:
* Move to using fedora21 as the new base
* Remove the custom git package install, as git2.1 is in Fedora21
* Install newer version of pip not packaged version
> Updated Docker file

- artifactor/plugins/reporter.py
`v2_key was not included in the build (cfme/tests/test_appliance.py:159)` yielded `py:159` which is not what we want. To test this PR, copy the regexp and throw texts with and without URLs on it.
> The URL regexp was eating more than it was permitted, I devised a simpler one

- utils/appliance.py
- utils/ports.py
- utils/ssh.py
- We picked up a new deprecation warning upstream, which broke the
method being used to get the db address. We already have a desire
to pull and parse yaml files from the appliance, so I made that work,
and used it here to get the DB address.
- IPAppliance.ssh_client is lazycached now, to promote reuse throughout
IPAppliance. The previous behavior is still supported by SSHClient's
call behavior, which is to return a copy of itself with updated kwargs
- fixed some unnecessary NOQAs in ports (If you think you have to NOQA,
spend some time and see if you can get around the problem)
> Pull db address from yamls instead of the rails console

- cfme/tests/automate/test_buttons.py
{{pytest: cfme/tests/automate/test_buttons.py -k button_avp_displayed --long-running -v}}
> Check if AV pairs dialog is displayed

- cfme/automate/explorer.py
This should not fail on the Automate stuff setting up.
{{pytest: -m uses_event_listener --event-testing -v --use-provider complete}}
> copy_to() counts with single domain (text only)

- cfme/intelligence/reports/widgets.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -v -k rss --long-running}}
> Widget refresh, longer timeout.

- cfme/fixtures/rest_api.py
- cfme/tests/infrastructure/test_vm_analysis.py
{{pytest: cfme/tests/infrastructure/test_vm_analysis.py -v -k REST --use-provider vsphere55 --long-running}}
> Ensure VM analysis REST client is from the current appliance.

- .gitignore
This just adds the .python-version file that pyenv generates to .gitignore.
> Adding pyenv's .python-version file to .gitignore

- utils/testgen.py
* Providers names were not being removed from the collection in certain
instances leading to a horrid mismatch between id and mgmt provieded
> Fixed collection issue

- cfme/tests/infrastructure/test_provisioning_dialog.py
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -k change_cpu_ram --long-running -v --use-provider rhevm34}}
> Version is no longer reliable source of CPU/RAM regexp choice

- cfme/fixtures/pytest_selenium.py
- cfme/tests/configure/test_update_appliances.py
- cfme/tests/infrastructure/test_vm_analysis.py
- conftest.py
- fixtures/pytest_store.py
- fixtures/ssh_client.py
- utils/appliance.py
- utils/db.py
* All references to cur_app.ssh_client() will force a new transport, by
removing the (), we can force it to use the cache. This should be safe
for all situations where new details are not supplied.
> Move all ssh_client calls to use the cache

- cfme/tests/cloud_infra_common/test_tag_objects.py
- utils/mgmt_system/virtualcenter.py
- utils/providers.py
- utils/virtual_machines.py
I noticed this ruined last build, that one of the vspheres was not responding therefore invoking SSLError.
{{pytest: cfme/tests/control/test_bugs.py -v --long-running}}
> setup_a_provider() skips on certain errors

- fixtures/rbac.py
RBAC truly disabled unless specified
{{pytest: -k test_provision_from_template}}
> RBAC truly disabled unless specified

- cfme/tests/control/test_compliance.py
- cfme/tests/infrastructure/test_vm_analysis.py
- utils/appliance.py
- utils/browser.py
- utils/db.py
* Since the address is the canonical source, either passed in at init or
grabbed from the store.base_url, there is no need for methods that
rely on the address, to also try to search for the base_url from the
store. This could cause confusions.
> IP Appliance updates for urls

- utils/testgen.py
In jenkins runs we were seeing rhos_uc being used as a valid provider,
but receiving the scvmm management object. This was because it was not
being overwritten in the loop with a blank object. The error was
manifesting because the type checking had no failsafe. This has now been
corrected and the provider is skipped if the type is not valid.
> Fixed another collections related issue

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_delete_default_group or test_delete_group_with_assigned_user'}}
> Group failure fixes

- utils/mgmt_system/exceptions.py
- utils/mgmt_system/openstack.py
* When the instance is deleted, it also tries to delete the associated floating IP.
* When an instance is created, it looks for free floating IPs in the pool, reusing them. There is a 'gap threshold' of 1 FIP because I did not discover any race condition prevention mechanism that would eg. raise an exception when you try to reassign an already assigned FIP. If there is 1 or 0 FIPs, it creates a new one, if there are 2 or more, it reuses one from them.
Test sample (`tail -f log/cfme.log` for the messages):
```python
from utils.providers import provider_factory
p = provider_factory(some_rhos)
vm = p.deploy_template("cirros", floating_ip_pool="public", network_name="private")
vm = p.deploy_template("cirros", floating_ip_pool="public", network_name="private")
vm = p.deploy_template("cirros", …
```
> Improved RHOS floating IP behaviour

- cfme/tests/services/test_service_catalogs.py
- fixtures/wait.py
- requirements.txt
- utils/api.py
- utils/tests/test_wait.py
- utils/wait.py
Also adds a new feature, `pytest.wait_for` wrapper. Usage in the newly written test. @psav has already seen it, @seandst ?
{{pytest: cfme/tests/services/test_service_catalogs.py -v --long-running -k rest}}
> Add the service catalog item ordering via REST.

- cfme/fixtures/pytest_selenium.py
wait_for_ajax was unknowingly squashing the UnexpectedAlertOpen
exception causing some navigations to fail.
If you don't believe me, try for naving to clouds_providers after you
have entered data into a new_cloud provider form.
> Bad squash, bad!

- sprout/appliances/models.py
The code that deletes the pool when pool is killed is placed in Appliance's .delete() method. That ensures that when the last appliance in the pool gets deleted, the pool gets deleted with it. However when we kill an unfinished pool and the appliances are salvaged, this obviously does not happen when the appliances are put in shepherd. So an additional check is required.
> [WIP][NO TEST] Sprout - Correctly delete pool after salvaging appliances

- cfme/web_ui/menu.py
{{pytest: -v --long-running -k crud}}
> Added grid resetters to most used places, because upstream uses list by default

- cfme/provisioning.py
Raise the ajax timeout for the selections around template selection for VM/Instance provisioning to 90 seconds.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -v --long-running}}
> Wait longer for template selection

- utils/log.py
There was some opposition against casting the message as string if it is not a string but it looks I had a good idea.
{{pytest: -v -k "test_display_name_unset_from_ui and instance"  --long-running}}
> Ensure the message is a string in art_log

- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/remote.py
It wasn't really necessary to use USR2 to tell the parallelizer workers to quit, considering SIGQUIT is a thing that already exists, so I switched the signal handler. While I was in there, I added the ability to break a slave out of its runtest loop and shut down.
> use SIGQUIT instead of USR2 to stop master/slaves

- cfme/common/provider.py
Apparently during provider unification, a return was forgotten, making some cloud tests fail because they expect boolean with success as a return value.
> load_all_provider_instances must return bool

- cfme/tests/configure/test_default_views_infra.py
The default navigation for infrastructure provider sets it to grid view so need to reset the views.
{{pytest: -v  cfme/tests/configure/test_default_views_infra.py  -k  'test_tile_defaultview or test_list_defaultview'}}
> Fix infra tile and list default view

- cfme/tests/cloud/test_instance_power_control.py
The module was providing no argnames to the testgen.parametrize
> Fix a collections issue in one module

- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/test_appliance.py
- scripts/data/enable-internal-db.rbt
- scripts/restore.py
- utils/appliance.py
- utils/db.py
scl_name added to utils.db, evern instance of 'postgresql92' that I
could find in the project was replaced with a call scl_name
> Handle the postgres version bump upstream

- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_host_drift_analysis.py
- cfme/web_ui/__init__.py
Host drift analysis fix - tag instead of rename …
Skip in 5.3 ( https://bugzilla.redhat.com/show_bug.cgi?id=1242655 )
> Host drift analysis fix - tag instead of rename

- artifactor/plugins/reporter.py
- data/templates/test_report.html
- fixtures/provider.py
- metaplugins/blockers.py
* Artifactor reporter plugin gains new hook (skip_test)
* Reporter plugin now configures test report with a table of blocked and
provider_error skips
* Report now includes checkboxes for show/hiding blocker and provider
skips
* Report now correctly handles reloading the page, before boxes that
were checked before a page reload were ignored when the page was
reloaded. This has been fixed.
* Blocker metaplugin now sends out to artifactor when a test has been
skipped due to a blocker
* Provider fixture now sends out to artifactor when a test has been
skipped dur to a provider setup failure
{{pytest: -k utils/tests/test_wait.py}}
> Added Provider and Blocker skip filters to reports

- artifactor/plugins/reporter.py
Move report back into artifacts, where jenkins expects it
This will break PRT legacy REPORT button
> Move report back into artifacts, where jenkins expects it

- sprout/appliances/models.py
- sprout/appliances/static/app-js/my_appliances.js
- sprout/appliances/tasks.py
- sprout/appliances/templates/appliances/my_appliances.html
* It now ignores the appliances that have bad power state.
* UI does not allow renaming appliances without UUID
* UUID refresh initiated after appliance provisioned.
* give_to_pool does better checking.
> [WIP][NO TEST] Sprout - Better appliance salvage; Forbid renaming appliances without UUID

- sprout/sprout/settings.py
Future versions of Django will get rid of TEMPLATE_* configuration values and will use the TEMPLATES dictionary exclusively. Now it writes a warning, so I just want it to shaddap.
*Not very important, will merge it together with some bigger update*
> [WIP][NO TEST] Sprout - Remove deprecated configuration value

- conftest.py
{{pytest: -v -k 'not dialog and not retire' cfme/tests/automate/ }}
> Removed old domain fixture

- cfme/tests/configure/test_analysis_profiles.py
- utils/blockers.py
- utils/bz.py
If you want to make the bug skip for stream that is not cloned in BZ, you can use keyword parameter forced_streams=[] which takes the stream names in form of downstream-54z and so. It will then always care about htat bug in that stream no matter what do the bug's versions state. Use with caution though...
> Able to override BZ stream detection in blocker

- cfme/fixtures/pytest_selenium.py
I noticed that this seems to happen sometimes. We can handle it. At least in force_navigate when we catch some sort of NoSuchElementException.
> force_navigate - Detect the event of logout.

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_timelines.py
The "ems_events" DB table has been replaced with the "event_streams" DB table in the upstream/5.5 build.These code changes have been made to address this.
> Add new events table

- sprout/appliances/tasks.py
They add `-alpha` to the version file in the appliance.
> [WIP][NO TEST] Sprout - Update the version mismatch detector

- utils/appliance.py
What was the issue? The problem was, that somewhere in the configuration function, a call to version.pick was done. Since the appliance object that we are calling it from is not pushed to the appliance stack, it actually runs the version.pick against some other appliance. The whole fix is to enclose the configure sequences with `with self.ipapp` that ensures version.pick uses the correct address.
*Side effects, aieeeee*
> Resolve the appliance configuration error

- cfme/cloud/instance.py
- utils/__init__.py
Introduced deferred_verpick, a classproperty creator that turns a verpick dictionaries into a classproperty so the verpicking happens only when the value is requested.
> Introduce deferred_verpick

- utils/appliance.py
To not have the gap in logs after templatized appliance is ran again, this will move the logs into a subdirectory for later inspection.
> [WIP][NO TEST] Update the template sealing process with log scrubbing

- cfme/tests/test_soap.py
Soap API was deprecated in v3.2 (5.4) and removed in v4.0 (5.5)
> disable soap tests for 5.5/upstream

- cfme/fixtures/pytest_selenium.py
- cfme/infrastructure/virtual_machines.py
- cfme/web_ui/flash.py
+ flash messages now only read the visible elements and to be sure, elements() does not fail when empty list passed.
{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --long-running }}
> Snapshot flash messages fixed

- utils/api.py
There was some guess logic involved and unfortunately in bad order in the if.
{{pytest: cfme/tests/test_rest.py -k provision -v --long-running}}
> Fix the REST client

- cfme/tests/infrastructure/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
So for starters, I know I need to sign the commit but it appears I failed to back up my key when I re-installed so I need to recreate it.  :\
I tested this out and it should be good to go for the most part.  It runs for 5.4 and does most of the skips on 5.5 but there does seem to be some issues, external to the PR, where the metadata blockers on test_provisioning_dialog/test_provisioning_schedule and test_disk_format_select trump what is marked in pytestmark.
Ultimately it should reduce the failures by ~25
> add rhev provision blocker

- cfme/tests/control/test_basic.py
{{pytest: cfme/tests/control/test_basic.py -v --long-running}}
> RUBY expression type no longer supported

- cfme/common/vm.py
- cfme/web_ui/flash.py
{{pytest: cfme/tests/infrastructure/test_retirement.py -v -k 'unset' --long-running}}
> Fix retirement flash message

- cfme/automate/explorer.py
- cfme/automate/service_dialogs.py
- cfme/cloud/instance.py
- cfme/common/vm.py
- cfme/configure/configuration/__init__.py
- cfme/fixtures/pytest_selenium.py
- cfme/tests/cloud_infra_common/test_genealogy.py
- cfme/tests/intelligence/reports/test_canned_corresponds.py
{{pytest: cfme/tests/infrastructure/test_snapshot.py cfme/tests/intelligence/test_chargeback_assignments.py cfme/tests/intelligence/reports/test_canned_corresponds.py cfme/tests/configure/test_analysis_profiles.py cfme/tests/automate/test_service_dialog.py cfme/tests/cloud_infra_common/test_genealogy.py -k 'snapshot_via_ae or assign_storage_tagged_datastores or providers_summary or vm_analysis_profile_crud or tagcontrol_dialog_element or genealogy_detected' -v --long-running}}
> Another load of jenkins fixes

- cfme/tests/test_login.py
Ensure clean session when testing the login. Improves reliability for template tester.
> Containt the login tests by restarting the browser

- cfme/common/vm.py
- cfme/tests/control/test_bugs.py
{{pytest: cfme/tests/control/test_bugs.py -v -k scope_windows_registry_stuck --long-running}}
> Fix test_scope_windows_registry_stuck

- cfme/common/vm.py
- utils/mgmt_system/__init__.py
On RHEV 3.4, you can;t ssh into a VM if the template you are cloning/starting has the cloud-init rpm and you don;t specifically pass in cloud-init customization.  :\  This should work around it for the automation, users manually creating any such VMs will just have to know what to do, use run once.  Also sneaking in some logic to help vm_analysis getting random errors deleting suspended vms.
> Fix rhev34 ci

- cfme/intelligence/reports/reports.py
Expected to fail, this just detects errors in the report generation straightforwardly.
{{pytest: cfme/tests/configure/test_visual_infra.py -v -k report_page_per_item --long-running}}
> Detect errors when generating a report

- cfme/fixtures/pytest_selenium.py
- cfme/tests/infrastructure/test_advanced_search_vms.py
- cfme/web_ui/form_buttons.py
{{pytest: cfme/tests/infrastructure/test_advanced_search_vms.py -v -k save_and_cancel_load --long-running }}
> Propagate ajax_wait param in custom click handlers

- cfme/infrastructure/datastore.py
- cfme/tests/infrastructure/test_delete_infra_object.py
* A new error was being raised which was not NoElementException this is
now handled
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py -k test_delete_datastore}}
> Fix the datastore deletion test

- cfme/tests/configure/test_visual_infra.py
{{pytest: cfme/tests/configure/test_visual_infra.py -v -k report_page_per_item --long-running}}
> BZ test_report_page_per_item because of report error

- cfme/tests/distributed/test_appliance_replication.py
This fixes a minor issue with restarting the postgres process that was causing some replication tests to fail.
> fixing postgresql service calls

- cfme/common/__init__.py
{{pytest: cfme/tests/control/test_actions.py -v --use-provider vsphere55 --long-running}}
> Fix the #tP locator to move somewhere else on 5.5+

- utils/tests/test_varmeth.py
- utils/varmeth.py
Originally an idea by Pete, I implemented it using descriptors. Allows us to perform certain actions slightly different way.
There is one possible future feature, to be able to specify that "this variant wants a callback to the default function" to be able to make eg. the default function do some significant logic and the variants could do some wrapping of that logic without copying code.
{{pytest: utils/tests/test_varmeth.py -v}}
> varmeth module

- cfme/web_ui/toolbar.py
The latest toolbar update did not take strings with '-s in it into an account. This simple fix tries to escape any of them before use.
{{pytest: cfme/tests/control/test_actions.py -v -k prevent --long-running }}
> Fix toolbar JS quoting

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_group_crud or test_group_duplicate_name or test_group_edit_tag or test_group_remove_tag or test_description_required_error_validation or test_delete_group_with_assigned_user or test_edit_sequence_usergroups or test_delete_roles_with_assigned_group'}}
> Added bz blocker 1276135 to group test cases

- utils/appliance.py
At least sublime text has issues with its python highlighter, because it looks for matching ), which is not there because it is not a python regexp. I have put a ) in the comment so it does not affect anything but it makes the syntax highlighting work again properly.
> Fix syntax highlighter confusion

- fixtures/parallelizer/__init__.py
- utils/appliance.py
We found the old test distributor did nasty things, namely it allowed
slaves to die when there was still work to do. The cause of this is
disproportionate testing of providers, some providers have many tests,
others have few.
To combat this we have now set a limit to the number of providers an
appliance can manage. Does this mean the appliance _can_ be asked by the
framework to use more? Yes! Is this a test distribution issue? No! The
problem is that some test_groups have tests which are not all destined
for the same provider. I have not yet looked into this. There are also
random tests, where we cannot predict what providers will be used.
However, we now set a limit and unless there are no others tests, the
appliance will be cleansed of its providers before we send more tests.
> New test distributor changes

- cfme/web_ui/__init__.py
- cfme/web_ui/paginator.py
Last modification of the paginator locators changed the target element from the 'li' to the one-level deeper 'span'. is_dimmed() checked the class attribute of the element for presence of the dimmed/disabled class, but that is only in the 'li', not in 'span', so I added a check that if it is a span, go one level up and check it there.
{{pytest: -k visual -v --long-running}}
> Fix the is_dimmed() function in paginator.

- sprout/appliances/tasks.py
- utils/appliance.py
- utils/log.py
- utils/ssh.py
* First, the logger_wrap decorator threw away results.
* SSH's open_sftp() needed some care in order to work properly.
* Added a separate yaml key for rhel7 updates
* Abstracted the work with repo files. Now the framework can read what products are set up as repos, their versions, if you add the same URL again it won't create a new repo, if you add an url that is an update for a product it will delete repos for the product that were there before, and so...
> Fix couple of things around update_rhel

- cfme/tests/cloud/test_provisioning.py
Properly format email
{{pytest: -k test_provision_from_template_using_rest}}
> Fix REST prov test

- cfme/tests/infrastructure/test_provisioning.py
- scripts/template_upload_scvmm.py
Just removed the lines that bypassed the scvmm crud operations.
{{pytest: -k test_provision_from_template --use-provider scvmm}}
> Removed continue flag when provider equaled scvmm

- cfme/web_ui/accordion.py
Fix for accordion, don't click second time if it is already active.
{{pytest: -k service --long-running }}
> Fix the active accordion

- cfme/tests/configure/test_access_control.py
This needs changing to the "role" ids rather than using the paths, but that's for another day
> Fix features

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vm_power_control.py
- cfme/web_ui/toolbar.py
Required couple of changes around:
* Add exists() to toolbar. It is also able to check greyedness in it.
* Fix the get-all_vms to try both title and data-original-title (>_<)
* Rewrite the asserts in the test to soft_asserts using exists()
* Documented the test.
* Toolbar did not work properly with the new grid view buttons, this adds yet another exception handler specific for the buttons.
Closes #2414
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py -v -k no_template_power_control --long-running }}
> Fix up the no template power control test

- cfme/tests/test_rest.py
Also modify the argument for rates.
{{pytest: cfme/tests/test_rest.py -k 'service' -v --long-running -v}}
> Fix for test_edit_service

- utils/log.py
When there are both yaml and eyaml files, it tries to print out a warning that it ignores the encrypted yaml during the import. However, as this is happening during the import, the module with the yaml is not loaded yet and the warning print gets delegated to artifactor, which will then also try loading the same config file (credentials), resulting in import error.
> Work around the importerror with yaml files

- cfme/automate/service_dialogs.py
- cfme/tests/automate/test_service_dialog.py
{{pytest: cfme/tests/automate/test_service_dialog.py -v -k reorder --long-running}}
> Fix reorder elements test to work with new trees

- cfme/tests/containers/test_provider_crud.py
addFinalizer needs callable and not the result of the call.
> Fix assert <built-in function callable>

- cfme/intelligence/reports/schedules.py
{{pytest:  -v --long-running cfme/tests/intelligence/reports/test_crud.py -k 'test_schedule_crud'}}
> Update schedule UI labels

- cfme/web_ui/toolbar.py
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -v --long-running}}
> toolbar: select either <i> or <img> when selecting a view 

- cfme/tests/infrastructure/test_advanced_search_host.py
- fixtures/browser.py
- utils/log.py
This also fixes several utf-8 decode problems in logging - this is required for other advanced search tests to pass
{{pytest: -v --long-running cfme/tests/infrastructure/test_advanced_search_host.py }}
> Mark advanced search tests as affected with bug 1283554

- cfme/tests/configure/test_display_settings.py
{{pytest: -v --long-running -k 'test_timezone_setting'}}
> test_timezone_setting: 5.5 displays timezone on Diagnotics Server page

- cfme/tests/infrastructure/test_infra_quota.py
{{pytest: cfme/tests/infrastructure/test_infra_quota.py --long-running -v}}
According to Tina Fitzgerald's response (bz 1287102) the tenant quota values are not overridden by tag values, so these tests shouldn't run on 5.5 and upstream.
> group_quota tests should only work on 5.4

- utils/__init__.py
- utils/log.py
- utils/tests/test_safe_string.py
Introduced a safe_string() function that is used in the art_log to polish the strings. Also added a test for it.
{{pytest: utils/tests/test_safe_string.py -v}}
> safe_string() introduced

- cfme/tests/automate/test_customization_paginator.py
- cfme/web_ui/paginator.py
Supersedes #2510.
Now handles 'Rows' prefix (e.g. in Saved Reports)
{{pytest: cfme/tests/automate/test_customization_paginator.py -v --long-running }}
> Paginator rewrite

- cfme/services/workloads.py
I did not realize that the destinatoins can b especified in YAMLs, so putting them back.
{{pytest: cfme/tests/configure/test_default_views_infra.py -v -k service --long-running}}
> Returned back some branches

- cfme/tests/services/test_orchestration_template.py
{{pytest: -v -k 'test_copy_template'}}
> remove bz blocker for copy orchestration template

- cfme/common/provider.py
- cfme/containers/provider.py
- cfme/infrastructure/provider.py
- cfme/infrastructure/pxe.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/containers/test_provider_crud.py
- cfme/tests/infrastructure/test_esx_direct_host.py
- cfme/tests/infrastructure/test_providers.py
- utils/api.py
- utils/appliance.py
- utils/varmeth.py
This commit focuses on the introduction of the REST API and variable
methods into the provider framework.
* Updated varmeth to use the default if method is explicitly set to None
* Added utc_time() method to IPAppliance to return the UTC time for the
appliance
* Updated REST API to recognise the "last_refresh_date" as a valid date
field
* Made REST module follow convention of supplying the current
appliance's REST API with a module rest_api() function
* Provider base gain some new methods:
* refresh_provider_relationships_ui() - this was a migration of the
original function, the original name is now used for the faster
default REST version.
* refresh_provider_relationships() - this is now REST by default
* last_refresh_date() - this uses the REST API to collect the
last_refresh_time. …
> API change proposal

- cfme/tests/cloud/test_instance_power_control.py
{{pytest: cfme/tests/cloud/test_instance_power_control.py -v -k terminate --long-running}}
> Verpick terminate message

- cfme/web_ui/toolbar.py
A strange situation occured where the locator for the sub actually
matched the main link element for the Timelines page. Subsequently when
we were trying to select the timelines toolbar for monitoring, the first
element being returned was actually the element from hte main nav, which
didn't have the 'idd' attribute. So we now see if multiple elements were
found, which one has the idd element.
{{pytest: -k timelines --use-provider vsphere55}}
> Fix toolbar name collision

- utils/providers.py
5.4 Doesn't support containers, so don't try to clear container providers on it.
> Don't clear containers on 5.4

- artifactor/__init__.py
- artifactor/plugins/reporter.py
- data/templates/test_report.html
- markers/composite.py
- utils/composite.py
Big changes here
* If supplied with the --composite-uncollect option we will now try to
contact jenkins with the data supplied in the composite.yaml. This is
option is only intended for cfme-qe.
* The --composite-job-name and --composite-template-name options are
overides only and should never usualy be supplied.
* If the option is passed we connect to the jenkins instance, download
the composite json files of the last runs and combine them to create a
composite build which can be reported on each time we run, giving
better results, or at least more accurate results.
* One major change in artifactor is the way that we use the artifacts
attribute. This has been modified to pump in an old artifacts to use
for combining. Currently this only works for the main report, thought
other reports …
> Added composite run option

- cfme/exceptions.py
{{pytest: cfme/tests/automate/ -v }}
> Make CandidateNotFound behave properly

- cfme/web_ui/menu.py
We can try to renavigate, that brings it back.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -v -k tag --long-running}}
> Work around the display selector disappearing

- cfme/web_ui/form_buttons.py
Replication worker credentials password change enable button has specific id, but it contains change_stored_password. I also fixed the indent in the function itself and added ajax wait in it to play safe in future.
It might fail, but the important thing is whether it passes through the process of setting replication worker password.
{{pytest: cfme/tests/distributed/test_appliance_replication.py -v --long-running}}
> Fix the change password for replication + small tweak

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_group_crud or test_group_edit_tag or test_delete_group_with_assigned_user or test_edit_sequence_usergroups or test_group_duplicate_name'}}
> remove bz blocker for group test cases

- scripts/sync_template_tracker.py
KeyError in the credentials file was causing all templates to be
disassociated from the providers which caused major headaches. This
fixes the error by moving all possible interactivity inside the
try/except clause and therefore guarding against a bad key discarding
all templates.
> Fixed template tracker to be slightly more robust

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k "test_assign_unassign_service_template_to_service_catalog" -v --long-running -v}}
> Fix service template assigning

- scripts/sync_template_tracker.py
yaycl is not thread safe, when trying to access the credentials conf
file with multiple threads, an empty dict was returned and in this case
it originally ended up disassociating the templates with the providers
and deleting the definitions.
> Fix for thread-unsafe yaycl

- cfme/tests/cloud/test_cloud_timelines.py
{{pytest: cfme/tests/cloud/test_cloud_timelines.py -v -k "not test_vm_event"}}
Found that a few tests that should be skipped are not being skipped because the BZ in question is now slated for a 5.6 release.The tests have been failing ever since the Release Flag was changed from 5.5 to 5.6.
BZ Blocker is being forced on test_provider_event() and test_azone_event() for the 5.5 stream for ec2 only through 'forced_streams'..So,those tests get skipped for ec2 only  on 5.4, 5.5.
The RHOS tests will not be impacted by this and will continue to be run.
> Force BZ Blocker on ec2 for CFME 5.5

- artifactor/plugins/reporter.py
This is caused by an internal design deficiency which does not enable us to use sets in the data, because JSON. Working aroudn by set()'ing it inside the template data generator.
{{pytest: cfme/tests/services/test_service_catalogs.py -k test_edit_catalog_after_deleting_provider -v --long-running --use-provider complete }}
> Remove the repeated blocker occurences

- cfme/cloud/provider.py
- utils/providers.py
{{pytest: cfme/tests/cloud/test_providers.py --use-provider 'rhos7-ga' -v}}
> openstack: set 'Non-SSL' security protocol by default

- utils/ports.py
This is a quick fix to invalidate the ssh_client cache instead of
setting the attribute to None. Setting to None does not allow the
ssh_client to retry the operation with the new port. This was probably
leftover from an earlier appliance makeup.
Proposal that we go through and actually make this fire a signal to
invalidate the proper cache settings, rather than just the SSH, ie, the
DB would probably need invalidating too to make things _right_.
> Fix ssh_client cache invalidation

- sprout/appliances/admin.py
- sprout/appliances/tasks.py
* Template deletion suggester kept spamming on version.
* django_object_actions apparently does not work entirely properly with newer admin, Groups were throwing 500.
> Sprout - Fix 500 and mute emails till the solution is found

- cfme/tests/infrastructure/test_host_analysis.py
{{pytest: cfme/tests/infrastructure/test_host_analysis.py --use-provider 'rhevm34' -v --long-running}}
> ssa: verify files and firewall rules on rhevm

- cfme/rest/__init__.py
- cfme/tests/infrastructure/test_vm_ownership.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/infrastructure/test_vm_ownership.py -k "TestVmOwnershipRESTAPI" -v --long-running}}
> Vm ownership migration

- scripts/template_tester.py
- utils/trackerbot.py
* added the 'request_type' paramater for get(api, request_type) to filter the templates
on provider type.
* templates. 'request_type' parameter has been added to parse.
* the 'provider_type' attribute is fetched from untested templates and exported as env..
* updated trackerbot.py to fetch the provider_type and return the template list to get(api, type)
> Prallelizing Template tester execution

- scripts/template_tester.py
* request_type needs to be --request_type to make it
as optional parameter rather positional arg (argparse)
* this fix is necessary for default jobs to run, without
any paramater/value for get(api)
> Fix optional parameter request_type for template_tester

- cfme/fixtures/pytest_selenium.py
- cfme/tests/infrastructure/test_datastore_analysis.py
{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py --use-provider 'vsphere55' -v --long-running}}
> Ssa datastore improvements: InfoBlock and soft_asserts

- scripts/post_jenkins_result.py
* right now, the post jenkins results are handled
only for template-tester. This patch addresses this problem by
including all the job names in post_jenkins_result.py
> Include all the provider Job names in post_jenkins_result

- scripts/appliance.py
- scripts/tests/test_appliance.py
- utils/appliance.py
I need to opt out with the sealing when using inside CFME because I do it in a different state machine. This also requires me to add some code that processes some known strings into actual values, like boolean. I changed it to run for booleans and none too. This code should be later extracted out into some tools if we find use for that. Added a small unit test for the argument processor.
> Add seal argument in templatize method, tweak appliance script

- cfme/configure/configuration/__init__.py
change p_type for 5.5 to select ByValue to use method select_by_value instead of incorrect working in this case select_by_visible_text
{{pytest: -v -k test_log_depot}}
> Fix incorrect behavior for dropdown selector in ftp test_log_depot 

- utils/providers.py
The right key name should be containers_providers
[ticket: n/a]
> Fix error for not existing container_providers

- fixtures/artifactor_plugin.py
this is a experiment to see why the workaround was added to begin with
> artifactor plugin: always assume we have a valid item.location

- conf/cfme_data.yaml.template
- fixtures/node_annotate.py
annotate test nodes from a csv metadata file that lists tiers and metadata
also add support for test tier selection via --tier
print early warnings when node annotation files are missing
dont allow tests that have no tiers when matching tiers
use item.get_marker and apply yapf
don't apply external node annotations if they already exist in code
> node metadata annotation and tier selection

- utils/bz.py
```
_________________________________________________________________ ERROR at setup of test_certificates_present __________________________________________________________________
item = <Function 'test_certificates_present'>
def pytest_runtest_setup(item):
>       run_plugins(item, plugin.SETUP)
markers/meta.py:167: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
markers/meta.py:160: in run_plugins
plug.function(**env)
../lib/python2.7/site-packages/kwargify.py:33: in wrapper
return wrapped(*pass_args)
metaplugins/blockers.py:86: in resolve_blockers
if blocker.blocks:
utils/blockers.py:156: in blocks
bug = self.data
utils/blockers.py:145: in data
self.bug_id, …
```
> check_fixed_in: make sure fixed_in is Version not a string

- cfme/fixtures/pytest_selenium.py
Remove all functions that are not used anywhere. I left some of those, because they might be useful, but there were some old-styled functions that can be replaced by a sleeker alternative (IMO)
> pytest_selenium.py: Cleanup

- scripts/cleanup_edomain_templates.py
- scripts/template_upload_rhevm.py
* added check delete status for the templates, and
wait until the template is deleted.
* make ssh connection to export domain(NFS) IP and
delete any empty directories to avoid 400 OVF Error.
* Added cleanup_edomain_templates.py, which searches for
old auto-tmp* on rhevm providers and deletes them.
> Fix the auto-tmp* cleanup for rhevm providers.

- requirements.txt
- scripts/dockerbot/check_prs.py
This sends messages about PR status change to RabbitMQ queue to be consumed by sopel bot and announced in the rooms.
RabbitMQ URL should be defined in ```docker.yaml```
> Add PRT side of bot integration

- cfme/cloud/instance.py
- cfme/tests/cloud/test_instance_power_control.py
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k "test_terminate_via_rest" -v --long-running}}
> Rest api terminate method for instances

- scripts/latest_template_tester_report.py
* check if any untested templates are available, if untested
providers are avialable then proceed with next template_tester job.
* if no untested template providers then, wait for the upload and
test to finish(if any pending).
> Add check for untested templates before wait.

- cfme/configure/configuration/__init__.py
- utils/db.py
- utils/signals.py
this is a workaround until cached_property itself provides a idempotent cached property
see https://github.com/pydanny/cached-property/issues/31
until cache invalidation is idempotent we need to catch attribute errors
when invalidating the instance cache, since invalidation on missing cache
triggers a attribute error
> idempotent cached property invalidation

- scripts/dockerbot/check_prs.py
- utils/trackerbot.py
* When Dockerbot was coded, one of two things happened, either:
1) psav didn't read the tastypie manual properly
2) Something changed in version 0.13.3
Either way, upgrading tastypie from 0.13.1 to 0.13.3 broke trackerbot
usage for PRT. 'Put'ing a resource without supplying all fields causes
unpredictable results. This worked in 0.13.1 and fails in 0.13.3. This
change adds the missing fields into every put in cfme_tests, all of
these tend to refer to PRT, which means that 1) is the most likely
cause of this.
> Fix Dockerbot API usage

- cfme/web_ui/listaccordion.py
Previous implementation could only retrieve links by ``//a[@title]``. Now you can optionally enable matching by the link text. I have also cleaned it up a little bit and let it use quoteattr.
> cfme/web_ui/listaccordion.py: Enable select by text

- cfme/tests/services/test_orchestration_template.py
{{pytest: -v -k 'test_name_required_error_validation or test_all_fields_required_error_validation or test_new_template_required_error_validation'}}
> Orchestration templates validation test cases

- cfme/tests/intelligence/test_chargeback.py
{{pytest:  -k "TestRatesViaREST"  -v --long-running}}
> [FIX] Nuke uncollect for rates on 5.4

- cfme/tests/infrastructure/test_config_management.py
{{pytest: -v -k 'test_config_manager_add_invalid_creds'}}
> Add bz blocker

- cfme/web_ui/__init__.py
- utils/__init__.py
{{pytest: cfme/tests/services/test_service_catalogs.py -v -k order_catalog_item --long-running}}
> Tree casts the path items as str

- utils/api.py
{{pytest: cfme/tests/intelligence/test_chargeback.py -k "TestRatesViaREST" -v --long-running}}
Add session and content-type header which is required for post method on the upstream, otherwise the response will be 500 Internal Server Error
> Fix for REST API actions - 500 Internal Server Error

- cfme/infrastructure/host.py
Host update used a workaround which called $j as jquery. $j is no longer present as an alias even inside 5.4 so it has no sense to keep it in the codebase.
> Remove legacy code - $j

- cfme/cloud/provider.py
- cfme/common/vm.py
- cfme/infrastructure/provider.py
- cfme/tests/infrastructure/test_instance_analysis.py
This also removes settings creds for host/datastore for RHOS
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py -k 'test_ssa_template' --use-provider='rhos7-ga' --long-running -v}}
> test_ssa_templates: skip 5.4 due to bz 1230248

- cfme/configure/tasks.py
- cfme/infrastructure/datastore.py
- cfme/provisioning.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/web_ui/__init__.py
- utils/appliance.py
This includes:
* appliance: allow waiting for web UI after reboot
* remove sel invocation and unclear wait for browser to open
* move is_vm_analysis_finished helper to cfme.configure.tasks
* use PagedTable/SplitPagedTable classes
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'vsphere55' -v --long-running -k "test_ssa_vm"}}
> SSA: prepare test_instance_analysis for FW 3.0

- docs/getting_started.rst
I discovered that some users install python dependencies not in virtualenv, but globally, because the step in which you should activate virtualenv is not described in Setup. I tried to fix that. What do you think @psav, @jkrocil, @mfalesni?
> Rearranged 'activate virtualenv action'

- cfme/tests/cloud/test_provisioning.py
- cfme/tests/services/test_add_remove_vm_to_service.py
- cfme/web_ui/__init__.py
During the % -> .format conversion, it was not regarded to the formatting of ruby code which contains {}.
There is possibly something left.
> Fix .format()'s handling of {}

- cfme/infrastructure/config_management.py
- cfme/tests/infrastructure/test_config_management.py
- utils/testgen.py
Several changes to configuration managers:
- added Satellite class
- added AnsibleTower class
- both classes inherits from ConfigManager class
- test generation added via testgen.config_managers
- existing tests updated - execute tests related to Ansible Tower on 5.6 or upstream
{{pytest: cfme/tests/infrastructure/test_config_management.py -v}}
> AnsibleTower / Satellite separate classes + testgen.config_managers

- utils/log.py
Only format when args is not empty.
More safe checking.
> Fix the log fix

- scripts/latest_template_tester_report.py
* the template_result.log is created/updated with failed steps from cfme.log.
the new temporary log file is created on remote machine(trackerbot), and appended
with each build log for failures. once template test is done
the file is attached to email and deleted from the remote
machine.
> include the logs for failed steps in template test report.

- cfme/cloud/stack.py
- cfme/dashboard.py
- cfme/fixtures/pytest_selenium.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/config_management.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider.py
- cfme/infrastructure/resource_pool.py
- cfme/services/catalogs/cloud_catalog_item.py
- cfme/web_ui/menu.py
- docs/guides/page_development.rst
- ui_navigate.py
Major changes to the menu library here, in order to support 5.6s new side based nav. This new nav not only is composed differently with new elements, but is triple layered, instead of being only double layered.
Summary of changes:
* Added a pending UINavigate() class to overide the original, this is to make the ui_navigate module a class, and not a singleton.
* Fixes to various object model files to get them to import in the correct way
* Branches are now not added on import, instead they are pushed into a deferral stack which is invoked the first time you call force_navigate(). This now makes force_navigate() the _ONLY_ way to
navigate and this function may very well move inside the menu module soon.
* The menu module has been reshaped to give a class based Menu() object. This is to …
> New menu system

- cfme/web_ui/__init__.py
A previous PR changed the Table handling, and reverse the direction of the ```in``` conditional. This restores the original functionality.
> Fixed table logic

- cfme/common/provider.py
- cfme/containers/provider.py
Tested `_num_db_generic('vms')` with vsphere6 and ec2, both worked. Container providers inherit BaseProvider so nothing will change there, Config Managers dont inherit BaseProvider so... no change there.
> Move _num_db_generic from containers.Provider to common.BaseProvider

- cfme/configure/settings.py
* Fixed a bug where we were casting the checkbox values to str this was
going to break the conversion to CFMECheckbox and would just have
resulted in a reverse back to bool, which seemed silly. It didn't seem
to harm anything, so I removed the casting to str for the checkboxes
* Moved a bunch of Input() class definitions to the Selector based
CFMECheckbox instead
{{pytest: cfme/tests/configure/test_visual_infra.py}}
> Pushed Input to CFMECheckbox and fixed a few bugs

- cfme/configure/settings.py
* In 5.6 Timeprofiles don't have a flash message on creation, we skip
the assertion if the bug is still open
{{pytest: cfme/tests/configure/test_timeprofile.py}}
> Fixed timeprofile by adding bug

- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/appliances/views.py
1) Clear the swap and ssh value on power off
2) Only scan and display powered on appliances
> [WIP][NOTEST] Sprout - Two tweaks to the swap nagger

- cfme/common/__init__.py
- cfme/common/provider.py
- cfme/common/vm.py
- utils/__init__.py
Introducing Summary and Comparable mixins. Comparable mixin serves as a automatic `__eq__` handling for object fields. Summary mixin serves as a convenient way to read object properties from its summray page, representing them in OOP way and it also injects some data into them so you can also read the image link and get the clickable link from it.
Example usage:
```python
from utils.provider import get_crud
from cfme.common.vm import BaseVM
p = get_crud('someprovider')
vm = BaseVM.factory('somevm', p)
print p.summary.smart_management.managed_by_zone 
print p.summary.smart_management.managed_by_zone.value
print p.summary.smart_management.my_company_tags[0].img
print p.summary.relationships.datastores
print p.summary.relationships.datastores.text_value
print …
```
> Summary and Comparable mixins

- docs/getting_started.rst
* there was newline missing after `code-block...` so the block was not visible in rendered document
* lowercase language definition to be consistent with the rest of documentation
> Fix code block syntax so it's visible in doc

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_log_depot_operation.py
add button for 5.6 into log collection page
{{pytest: cfme/tests/configure/ -k log_depot -v}}
> fix issue with save button for log_depot test

- fixtures/log.py
See: http://pastebin.test.redhat.com/374498
Encountered during test_db_migrate testing, #2976
> Log a warning when DB is not available instead of raising a KeyError exception

- utils/appliance.py
If postgres is left hanging and a restart of it is not initiated, the server gets into a funny state
> Fixed call to restart evm server rudely

- scripts/latest_template_tester_report.py
* pick the stream from cfme-data, the cfme-data is updated
with the stream names same as in trackerbot.
> change the stream to be inline with trackerbot & cfme-data

- cfme_test.sh
* Fixed loading of virtualenv for shells in tmux (`PYTHONPATH` and `PYTHONDONTWRITEBYTECODE` were not set)
* `sel_container.py` is now started in separate tmux window so it can be easily terminated/restarted (instead of launching it in the background)
* general cleanup and shellcheck fixes
> Fix virtualenv activation for shells in tmux, script cleanup

- cfme/web_ui/menu.py
This was an awesomely weird and bad bug. Owing to the deferred nature of
the menu instantiation, now happening inside force_navigate(), the
branch stack processing actually happens inside a test context. This
meant that if a LookupError happened inside the menu initialization(),
it would raise the exception, be caught as a test failure, and the
framework would continue testing, unaware that the branch stack hadn't
necessarily finished being processed. This change detects a LookupError,
and logs a warning. We also raise in the case of any other failures.
> Fixed menu lookup error

- cfme/tests/cloud_infra_common/test_retirement.py
fix retire with choosing 5.5 and 5.6 behaviour
{{pytest: cfme/tests/cloud_infra_common/ -k retirement_now -v}}
> fix retire with choosing 5.5 and 5.6 behaviour

- cfme/intelligence/reports/reports.py
- cfme/web_ui/__init__.py
For @nachandr : Please check this out, by using `.groups()` or `.find_group()` you should now be able to access the groups of the table. `.rows()` does not work because I did not modify that one, you have to go through `.groups()`. You also have to pass a `candu=True` option to the CustomReport or CannedSavedReport in order for the classes to pick up the correct table classes.
> C&U grouped tables support

- cfme/tests/test_login.py
55, 56 and upstream now have the same err flash message again. Thanks to @psav for catching this.
> Fix incorrect login text

- cfme/tests/automate/test_vmware_methods.py
- cfme/tests/cloud/test_stack.py
- cfme/tests/configure/test_db_backup_schedule.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_infra_quota.py
- fixtures/parallelizer/parallelizer_tester.py
- fixtures/rbac.py
- markers/uncollect.py
- utils/testgen.py
Fix uncollect when no data pass through to it (pytest 2.7.0 bug, issue #510)
Parametrize using testgen to utilize param check everywhere
Rename skip funcs to uncollect so their names match their purpose
> Fix uncollect when no data pass through to it (pytest 2.7.0 bug)

- cfme/common/__init__.py
- cfme/middleware/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/provider.py
- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_datasource.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_middleware_provider.py
- cfme/tests/middleware/test_middleware_server.py
* Added navigation feature for the pages `middleware servers` and `middleware deployments`.
* `servers` can navigate through `provider` page
* `deployments` can navigate through `provider` page [or] `provider >> server` page
* New test cases added for deployment page
* usage, 
```
MiddlewareProvider.deployments()  # lists all deployments
MiddlewareProvider.deployments(provider=_haw)  # lists all deployments from _haw provider
MiddlewareProvider.deployments(provider=_haw, server=_ser)  # lists all deployments from _haw provider >> _ser
MiddlewareProvider.servers()  # lists all servers
MiddlewareProvider.servers(provider=_haw)  # lists all servers from _haw provider
```
> Added feature, to navigate through provider for middleware servers, deployments

- cfme/middleware/provider.py
- cfme/web_ui/menu.py
- utils/providers.py
From #3049 middleware page supports for `Quadicon` icon.
* `provider.wait_for_delete()` works properly
> Middleware provider page code changes to Quadicon support

- cfme/cloud/instance.py
- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud/test_provisioning.py
- utils/providers.py
Better get this checked in.  Already lost it once.
Going to need help getting the right fields on the forms, but I think these are the fields azure will be using, at least in 5.6  I don't really care about 5.5
{{pytest: cfme/tests/cloud -k "test_provider_crud or test_instance_power_control" --use-provider azure }}
> First stab at integrating Azure into the providers code

- utils/virtual_machines.py
... leading to `AttributeError: 'exceptions.ValueError' object has no attribute 'format'`
> Typo in exception raising

- utils/ssh.py
* the recent changes in #3053 breaks ssh connection
while template upload. these scripts does not need
baseurl to be set. store.baseurl can be forced to
read only when there is no kwargs passed with non-default
ssh values.
> Fix ssh for usecases not involving appliance.

- cfme/fixtures/pytest_selenium.py
... to prevent e.g. `AttributeError: 'NoneType' object has no attribute 'text'`
> Handle None type returned by chained methods

- cfme/tests/configure/test_visual_cloud.py
* This occured because the menu became objectized and was my fault to
not fix this
{{pytest: cfme/tests/configure/test_visual_cloud.py -k test_start_page}}
> Fixed bug in module accessing

- cfme/common/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/provider.py
- cfme/middleware/server.py
- cfme/tests/cloud_infra_common/test_events.py
- cfme/tests/control/test_actions.py
- cfme/tests/control/test_bugs.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_middleware_provider.py
- cfme/tests/middleware/test_middleware_server.py
Added new function `validate_tags` in `Validatable` class and implemented across Middleware pages.
* Added support function for `validate_tags`
* Added tests (`test_tags`) for Middleware `Provider`, `Server` and `Deployment` pages
* For `Datasource` page test not included, blocks: https://github.com/ManageIQ/manageiq/issues/9211
{{pytest: cfme/tests/cloud_infra_common/test_events.py -v --long-running --use-provider nested-rhevm34}}
> Added 'validate_tags' to test tags across middleware pages

- cfme/tests/cloud/test_instance_power_control.py
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k "test_quadicon_terminate_cancel" -v --long-running}}
> Fix softassert condition in terminate_cancel

- cfme/tests/infrastructure/test_providers.py
This test is no longer required on 5.6 though we should probably write a
new test or adapt this one for testing the angular required fields stuff.
{{pytest: -k test_name_required_validation cfme/tests/infrastructure --use-provider vsphere55}}
> Added uncollect

- utils/testgen.py
In a recent PR #3125, the group_data object changed from a callable to a
dict. This is now reflected in testgen where it was used.
{{pytest: cfme/tests/integration/test_aws_iam_auth_and_roles.py --collect-only}}
> Fixed group data call

- cfme/tests/configure/test_server_roles.py
* git_owner and websocket are now added to the data yaml, and need to be
removed if not running on 5.6
{{pytest: cfme/tests/configure/test_server_roles.py}}
> Fixed server_roles

- fixtures/parallelizer/__init__.py
* In case of abrupt termination of the jenkins build,
the appliance pool is not deleted. this patch checks
for any old pool for jenkins job, and terminate them before
requesting for new pool.
> delete old appliance pool for jenkins job before new pool request.

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_server_roles.py
- utils/appliance.py
* Role setting is now done by SCP by default (could be riskier)
* Fixed another bug, where an SSH reconnect was being caused by the
set_yaml_config function for <= 5.5
> Fix role setting

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_delete_default_group or test_delete_group_with_assigned_user or test_delete_default_roles or test_delete_roles_with_assigned_group'}}
> Fix rbac flash messages

- cfme/services/requests.py
- cfme/tests/services/test_service_catalogs.py
{{pytest: cfme/tests/services/test_service_catalogs.py -k "test_order_catalog_item_via_rest" -v --long-running}}
> Fix for service catalog rest test and requests

- conftest.py
- docs/getting_started.rst
- fixtures/parallelizer/remote.py
- requirements.txt
- scripts/disable-bytecode.py
- setup.py
* create a dummy setup.py that can be used for editable install of the project folder
(removes the need to patch PYTHONPATH)
* disable bytecode in conftest for current process and subprocesses
(removes the need to set PYTHONDONTWRITEBYTECODE)
> Drop the need to patch the virtualenv activation script

- cfme/fixtures/pytest_selenium.py
- data/patches/miq_application.js.diff
- utils/appliance.py
Debounce has been introduced to 55z branch in 5.5.5.0. This will bump up our automation results on jenkins considerably.
Also:
- raises patch ver to 2
- removes md5 check from autofocus
{{pytest: -k "test_tag_crud or test_category_crud" --long-running -v }}
> Add patching to 5.5.5.0

- cfme/containers/container.py
- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/exceptions.py
- cfme/web_ui/__init__.py
- utils/__init__.py
Handle hiding of the table. Phase #1 involves the .rows() and the things that use it directly. The other things will eventually need this change too once needed.
{{pytest: cfme/tests/containers/test_relationships_tables.py -v --long-running}}
> Table + Containers - Handle hiding, and fixup containers code.

- utils/db.py
New upstream (and 5.7) will run new version of posgres. This is one of the 2 issues blocking upstream template testing right now.
> Add verpick for cfme57 postgres

- cfme/cloud/provider.py
- utils/providers.py
This is leftover from 2977.  It's a single line fix and works locally.  Nothing I can do about the location of these values until credentials allows for additional entries.
{{pytest: cfme/tests/cloud -k "test_provider_crud" --use-provider azure }}
> [FIX]  Found and added missing Azure Subscription ID reference

- utils/testgen.py
Previously the mark was applied correctly, however in the testgen
refactor this became broken. As the mark was applied outside of the
loop, merely running "through" testgen was enough to mark the
test. Unfortunately this was not accurate. This mark has now been moved
to be applied only if the "provider" parameter has actually been used
and hence the test has been properly parametrized.
Fixes #3171 
{{pytest: -m uses_testgen --collect-only --use-provider vsphere55}}
> Fix testgen mark application

- cfme/tests/control/test_bugs.py
test_folder_field_scope should be skipped or even deleted because 'VM Discovery' event was deleted.
https://bugzilla.redhat.com/show_bug.cgi?id=1238371
> Skip test_folder_field_scope because 'VM Discovery' event was deleted.

- cfme/services/catalogs/catalog_item.py
- utils/__init__.py
A string cast was added on the 13-Mar which effectively turned None into
"None". Since the UI doesn't have a "None", but only an "<Unassigned>"
or a "<No Dialog>" this was causing errors.
{{pytest: -k test_edit_service_template cfme/tests/services/test_rest_services.py --long-running --use-provider complete}}
> Fix catalog_item  None handling

- cfme/tests/infrastructure/test_vm_power_control.py
Both fixtures can't be processed during test run because of Failed: ScopeMismatch: You tried to access the 'class' scoped fixture 'provider' with a 'module' scoped request object, involved factories
> change fixtures scope to class because of ScopeMistmatch

- cfme/common/provider.py
Args were not matching on the TabStripForm constructor
{{pytest: -k test_provider_crud --use-provider vsphere55 cfme/tests/infrastructure/test_providers.py}}
> Fix validate button

- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
{{pytest: cfme/tests/cloud/test_providers.py -k provider_crud -v --use-provider rhos6-ga2}}
> Fixed a typo when checking AMQP credentials

- cfme/common/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/middleware/topology.py
- cfme/tests/middleware/test_middleware_provider.py
- cfme/web_ui/topology.py
Added new `Mixin` --> `TopologyMixin`. With this `Mixin` we can perform following actions,
* Get legends
* Get elements with filter support(optional)
* Get parents and children of an element
* Do actions on `Search box`, `Display Names`, `Legends`
* Perform `double_click` on an element
> Added support for middleware topology page

- cfme/common/__init__.py
- utils/tests/test_units.py
- utils/units.py
Sample usage:
```python
In [4]: from utils.providers import get_crud
In [5]: p = get_crud('provider')
In [6]: p.summary.properties.aggregate_host_cpus.value
Out[6]: 8
In [7]: p.summary.properties.aggregate_host_memory.value
Out[7]: Unit(464.0, 'G', 'B')
In [8]: p.summary.properties.aggregate_host_memory.value == '464 GB'
Out[8]: True
In [9]: p.summary.properties.aggregate_host_cpu_resources
Out[9]: '91.2 GHz'
In [10]: p.summary.properties.aggregate_host_cpu_resources.value
Out[10]: Unit(91.2, 'G', 'Hz')
In [11]: p.summary.properties.aggregate_host_memory.value > '400 GB'
Out[11]: True
```
So it is very easy to compare the numeric values. Even across the different prefixes.
The parsing also happens for the compared values.
> Introduce summary unit parsing

- cfme/common/provider.py
{{pytest: cfme/tests/containers/ --use-provider cm-env1}}
> provider.py fixes for CFME 5.6.1

- cfme/infrastructure/provider/rhevm.py
{{pytest: cfme/tests/cloud_infra_common/test_events.py -v -k events --use-provider nested-rhevm35}}
> Ensure the hostname gets entered when having C&U credentials for RHEV

- cfme/tests/services/test_iso_service_catalogs.py
{{pytest: -v --long-running  --use-provider nested-rhevm35 cfme/tests/services/test_iso_service_catalogs.py}}
> ISO provisioning for nested-rhevm35

- cfme/configure/configuration/__init__.py
- cfme/tests/integration/test_ipa_external.py
- utils/ext_auth.py
* the hostname is not correctly updated through
appliance_console, workaround is been added to the test.
* FQDN is a must for extrenal, which is included in the test.
> updated the external_auth_ipa test.

- cfme/infrastructure/datastore.py
* If accordion is not present, use InfoBlock
{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py -k test_run_datastore_analysis --use-provider vsphere55 --long-running}}
> Fixed relationship links with fallback

- cfme/cloud/instance.py
- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/common/provider.py
- cfme/common/vm.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/web_ui/tabstrip.py
- utils/virtual_machines.py
This is the short version now that most of the provisioning stuff is already in master.
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k "test_stop" --long-running --use-provider azure }}
> Initial Azure Power Control implementation - Revised

- scripts/dockerbot/sel_container.py
sel_container.py waited a hard 10 seconds for the VNC server to start in the container, this wasn't enough sometimes, so we now wait for the port first.
> Make sel_container wait more intelligently

- utils/trackerbot.py
Updated trackerbot script to include "upstream_stable" in stream parser.
* added "upstream_stable" to trackerbot stream_parser.
> Include upstream_stable in trackerbot stream parse.

- cfme/common/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/middleware/deployment_methods.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_provider_timelines.py
- cfme/web_ui/timelines.py
Used that TimelinesMixin in Hawkular provider. Added new test for hawkular timelines page. Moved general deployment functions into separate utility.
{{pytest: cfme/tests/middleware/test_provider_timelines.py cfme/tests/middleware/test_middleware_deployment.py -v --long-running --use-provider hawkular }}
> Added new mixin for Timelines.

- cfme/tests/configure/test_access_control.py
Fixing test_permissions_role_crud in rbac because its failing in upstream/downstream
{{pytest: -v -k 'test_permissions_role_crud'}}
> Fix test_permissions_role_crud in RBAC

- cfme/exceptions.py
- cfme/web_ui/menu.py
You will see straight away which menu item failed to be selected, you don't need to decode the error message. The original error message is included. Throws a different exception.
> More verbose menu navigation failures

- scripts/template_upload_rhevm.py
the rhevm api uri needs to include 'ovirt-engine' for version 4.0. so the api uri would look like: http://ip/ovirt-engine/api before it used to be http://ip/api
* added version parameter to providers.py.
* added version, to fetch rhevm api. as rhevm api uri changes based on version.
> added versioning for rhevm uploader.

- utils/providers.py
Fixing wait_for_no_providers_by_type() in utils/providers.py because test_utilization.py is failing.
{{pytest: -v -k 'test_metrics_collection' --long-running}}
> fixed wait_for_no_providers_by_type

- cfme/tests/infrastructure/test_timelines.py
The rest's add_event method supports only 'resource'. It skips all attributes if 'resources' (list) is passed. Fixed this issue.
{{pytest: cfme/tests/infrastructure/test_timelines.py}}
> Fixed broken timelines test 

- cfme/tests/containers/test_pods_prop_data_integrity.py
=============
The test asserts the total number of containers
{{pytest: cfme/tests/containers/test_pods_prop_data_integrity.py -v --use-provider container }}
> Added test_pods_prop_data_integrity.py

- cfme/tests/containers/test_pods_prop_data_integrity.py
{{pytest: cfme/tests/containers/test_pods_prop_data_integrity.py -v --use-provider container }}
> Patch that fixes line 25 in test_pods_prop_data_integrity.py

- cfme/tests/openstack/test_host_devices.py
Testing overcloud nodes, currently number greater than 0. 
We need to consider comparing the exact number of nodes. 
Looking for return the correct unit 
{{pytest:  cfme/tests/infrastructure/test_host_devices.py --use-provider tripleo}}
> test overcloud number of nodes

- cfme/tests/openstack/test_api_port.py
Openstack infra provider test: API port different than nothing. default is 5000
{{pytest: cfme/tests/infrastructure/test_api_port.py -v --use-provider tripleo }}
> Test infra port

- cfme/tests/infrastructure/test_advanced_search_host.py
- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/tests/infrastructure/test_advanced_search_vms.py
Fixing `setup_a_provider`call in advanced search tests.
Fixing `setup_a_provider` function so that it doesn't iterate over chars of "required_keys" when "required_keys" is a string, not list (in `all(key in providers_data[provider] for key in required_keys)`).
> fix provider setup in advanced search tests

- cfme/fixtures/pytest_selenium.py
- cfme/web_ui/history.py
- cfme/web_ui/toolbar.py
Purpose or intent
* Add history button handling
* Improve the escaping in toolbar module (&)
* Make the text() function in selenium work EVERY FREAKIN TIME
```python
from cfme.web_ui import history
history.history_items()  # Returns a list of all history items
history.select_history_item('Provider xyz summary')  # Selects by the history item text
history.select_nth_history_item(0)  # Or selects the history items based on the position, 0 is the latest
```
I hope it works in all screens, I made the locator quite generic.
@pavelzag Here it is. You should be able to cherrypick this commit to play with it and once this gets merged, you should be able to remoe that commit and rebase on top of `master`.
@mmojzis Sorry, we needed this quick :)
> History button | Improved toolbar escaping

- cfme/tests/openstack/test_relationships.py
Testing infra provider relationships properties
{{pytest: cfme/tests/infrastructure/test_relationships.py-v --use-provider tripleo }}
Currently all tests verify that the value bigger than 0, in the future we can either work with management system or combine this test with other integration tests (create tenant check if tenants list grown)
Testing assigned roles
Testing assigned tenants
Testing assigned zones
Testing templates (images) bigger than 5 default templates
Test number of stacks
> Test infra provider relationships

- cfme/tests/openstack/test_credentials_quad.py
A test that verifies that quad credentials are valid
{{pytest: cfme/tests/infrastructure/test_resources.py -v --use-provider tripleo}}
> Test quad credentials

- cfme/tests/containers/test_relationships_tables.py
Fixed test_relationships_tables.py to account for 2 pods missing replicators and "Unknown image source" as referenced in the opened bug. 
{{pytest: cfme/tests/containers/test_relationships_tables.py -v --use-provider container }}
> Patch that fixes test_relationships_tables.py

- cfme/tests/openstack/test_resources.py
Testing CPU and memory on openstack infra provider
{{pytest: cfme/tests/infrastructure/test_resources.py -v --use-provider tripleo}}
> test infra provider resources

- cfme/tests/openstack/test_host_hostname.py
Checking the smbios details of hostname in devices section
{{pytest: cfme/tests/infrastructure/test_host_hostname.py -v --use-provider tripleo}}
> test overcloud nodes hostname

- cfme/tests/openstack/test_host_assigned_zones.py
- cfme/tests/openstack/test_host_configuration.py
Testing openstack undercloud nodes configuration section, assigned zones which exists only in Compute node
{{pytest: cfme/tests/infrastructure/test_host_assigned_zones.py -v --use-provider tripleo}}
{{pytest: cfme/tests/infrastructure/test_host_configuration.py -v --use-provider tripleo}}
> Host configuration

- cfme/tests/openstack/test_host_role_type.py
A test that checks each undercloud node its role type in one of the possible roles: 
'Compute', Controller', 'BlockStorage', 'SwiftStorage', 'CephStorage'
{{pytest: cfme/tests/infrastructure/test_host_role_type.py -v --use-provider tripleo}}
> test undercloud node role type

- cfme/tests/openstack/test_roles_names.py
A test that compares the nodes names into pre defined list of roles, in case one name does not in that roles list the test will fail
{{pytest: cfme/tests/infrastructure/test_host_role_type.py cfme/tests/infrastructure/test_roles_names.py -v --use-provider tripleo }}
> Test roles nodes names

- docs/getting_started.rst
Clean/clear up the 'ReadTheDocs' Getting Started page.
There was a comment for the redhat-rpm-config package being for 'stripped down systems' - it looks like this package isn't included by default in Fed24 anymore so its a 'regular' prerequisite.
> Update package dependencies in getting_started

- cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -k "test_api_port_max_character_validation or test_name_max_character_validation or test_host_name_max_character_validation" }}
> Fix max character validation for infra provider

- cfme/tests/configure/test_tag.py
Fixing "ScopeMismatch: You tried to access the 'function' scoped fixture 'rest_api' with a 'module' scoped request object, involved factories"
> Fix rest_api scope

- cfme/tests/containers/test_relationships_tables.py
{{pytest: cfme/tests/containers/test_relationships_tables.py -v --use-provider container }}
> Fixed typo in test_relationships_tables.py

- utils/trackerbot.py
- utils/version.py
* added 5.7 version to version.py
* trackerbot.py streammatchers are updated with regex for 5.7
> update version regex for downstream-57z.

- cfme/cloud/provider/__init__.py
- cfme/common/provider.py
I found that the import statements were out-of-order according to the standards in the dev guide: 
http://cfme-tests.readthedocs.io/guides/dev_guide.html#code-style
Re-ordered the imports in two files relevant to my work, and am merging the small change separately.
Should not impact importing/functionality of the tests.
> Provider import order

- cfme/cloud/instance.py
- cfme/tests/cloud/test_instance_power_control.py
#Purpose or Intent
__Fixing__ test_vm_power_control.py and test_instance_power_control.py tests because they were failing
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k test_terminate --long-running}}
> Fixing Power action tests on 5.6+

- cfme/fixtures/pytest_selenium.py
* @removed changes the class which is required for proper multimethod
selection
* @removed has been removed from ByText and ByValue as it was causing
them to fail
> Remove @removed from class

- utils/version.py
* Including darga-3 in version, as darga-3 is versioned on top of 5.6.1,
version string is set to 5.6.1 for darga-3
> Inlcude darga-vstring in appliances.

- cfme/infrastructure/cluster.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/web_ui/__init__.py
Fixed timelines tests
Cluster and Host timelines tests often failed because just provisioned VM's often didn't have relationships for them. This issue appears mainly for RHEV providers. Appropriate BZ is submitted - 1373826.
I had to prepare the following workarounds due to that issue:
1. Correct cluster is discovered by vm's rest api now. The tests opened it via All Clusters page.
2. Correct host cannot be discovered via rest api. So, the tests use re-discover feature to get proper vm relationships.
{{pytest: cfme/tests/infrastructure/test_timelines.py}}
> fixed timelines tests for infrastructure providers

- cfme/rest/__init__.py
{{pytest: '''cfme/tests/intelligence/test_chargeback.py::TestRatesViaREST'' -v'}}
Fix reflecting changes in the API.
See https://bugzilla.redhat.com/show_bug.cgi?id=1366019
> Fix Chargeback Rate API tests

- cfme/cloud/provider/__init__.py
- cfme/common/provider.py
- cfme/tests/cloud/test_providers.py
{{pytest: cfme/tests/cloud/test_providers.py}}
Modify cloud provider module to use navmazing
Update test_providers to remove sel.force_navigate() calls
Add TODO's to the common provider module where navigation changes will need to be made.
Currently, master branch has 16/21 tests passing for cfme/test/cloud/test_providers().  JIRA card RHCFQE-625 written to capture failures.  Tested locally with the same pass rate on new navigation.
> Cloud Provider navmazing 

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
{{pytest: cfme/tests/control/test_basic.py -k test_alert_profile_crud --long-running}}
> Added support of Middleware Server Alert Profile

- cfme/infrastructure/cluster.py
- cfme/infrastructure/provider/__init__.py
- cfme/tests/infrastructure/test_cluster_analysis.py
- cfme/tests/infrastructure/test_delete_infra_object.py
- cfme/tests/infrastructure/test_timelines.py
1. Cluster requires provider now;
2. get_all_clusters moved to Provider object;
3. all usage places are fixed;
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py cfme/tests/infrastructure/test_timelines.py cfme/tests/infrastructure/test_cluster_analysis.py}}
This PR is based on PR - https://github.com/ManageIQ/integration_tests/pull/3440
> [WIPTEST] Cluster should require provider obj

- cfme/cloud/provider/__init__.py
Fixing rhos6-ga-ssl provider setup because it is currently failing: api_port gets replaced with some default value after we select "sec_protocol"
{{pytest: cfme/tests/cloud/test_providers.py::test_provider_crud --use-provider rhos6-ga-ssl}}
> fix for rhos6-ga-ssl setup

- cfme/tests/openstack/test_relationships.py
Since CFME version 5.6.2, infra provider does not include availability zones and tenants in infa provider relationships view
> remove AZ, tenants, templates condition

- cfme/infrastructure/datastore.py
- cfme/tests/configure/test_visual_infra.py
- cfme/tests/infrastructure/test_set_default_filter.py
changed Datastore object to use navmazing library instead of older nav approach
{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py cfme/tests/infrastructure/test_delete_infra_object.py cfme/tests/infrastructure/test_instance_analysis.py cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/configure/test_default_views_infra.py cfme/tests/configure/test_visual_infra.py cfme/tests/infrastructure/test_set_default_filter.py}}
> moved datastore to navmazing

- cfme/fixtures/pytest_selenium.py
- utils/deprecation.py
this one tries to correctly mark the classes that will go in fw 3.0 using removed_class from debt-collector
i didn't run a local test an will take a look at prt the next workday
{{pytest: cfme/tests/intelligence/reports/test_crud.py }}
> mark the selenum-fixture classes as deprecated

- cfme/fixtures/pytest_selenium.py
For empty string "arguments[0].innerText" in 5.6.2.1 returns None and whole script  "return arguments[0].textContent || arguments[0].innerText;" also returns None (Because arguments[0].textContent == "" and javascript returns last one arg if all OR statements if False)
> Add verification to text_content in pytest_selenium

- cfme/cloud/instance.py
- cfme/provisioning.py
- cfme/tests/cloud/test_provisioning.py
{{pytest : cfme/tests/cloud/test_provisioning.py -k "test_provision_from_template" --use-provider="gce_central"}}
> Gce ui api representation

- cfme/cloud/instance.py
- cfme/tests/cloud/test_instance_power_control.py
__Fixing__ azure power control tests because it is currently failing on test setup - fixture fails to prepare instance  with timeout 900
Soft_reboot is blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1379071 
{{pytest: cfme/tests/cloud/test_instance_power_control.py --use-provider azure --use-provider ec2east  --long-running }}
> [TEST]Azure power control fixes

- cfme/tests/cloud_infra_common/test_genealogy.py
{{pytest: cfme/tests/cloud_infra_common/test_genealogy.py::test_vm_genealogy_detected --use-provider="gce_central"}}
> change vm name for gce

- cfme/cloud/instance.py
- cfme/tests/cloud/test_instance_power_control.py
Purpose - New provider added to the test run + new naming
Adding GCE power control tests, as there were no power action tests before in our framework
{{pytest: cfme/tests/cloud/test_instance_power_control.py --use-provider gce_central --long-running }}
> adding GCE power controls

- cfme/tests/cloud/test_provisioning.py
Marking Provisioning tests
{{pytest:  --use-provider ec2east cfme/tests/cloud/test_provisioning.py::test_provision_from_template}}
> marking provision tests

- cfme/cloud/keypairs.py
- cfme/tests/cloud/test_keypairs.py
* KeyPair object now requires a provider
* Test has been updated to assign the provider to the KeyPair on
instantiation
* Form now chooses the provider instead of relying on a default
> Fix KeyPair test and objects

- cfme/tests/test_utilization.py
Updated the test generator so that tests are generated for all providers except rhev and vmware.
Also, see https://github.com/ManageIQ/integration_tests/pull/3483  , where tests have been added to verify specific performance metrics are collected for  rhev and vmware.
{{pytest: cfme/tests/test_utilization.py --use-provider complete}}
> generate tests for all providers except infra

- cfme/tests/test_utilization.py
Support for C&U collection for GCE has been introduced in 5.7. 
These code changes are to enable the test for GCE.
{{pytest: cfme/tests/test_utilization.py --use-provider complete}}
> Enable C&U collection for GCE

- cfme/tests/cloud_infra_common/test_vm_ownership.py
- utils/appliance/__init__.py
I found some kind an issue for this
https://github.com/ManageIQ/integration_tests/commit/ced20cc002f365301f0fad55a14807eb3f534d14#diff-1e8b179acb9ab9a36422fe2651bc0aa6R1645
if we use different from admin user (e.g. user_temp) in construction like this in tests
with user_temp:
...:     provider.load_details()
it login with this user, then makes logout, and login as admin
we have some tests about ownership. This thing make them failed
{{pytest: cfme/tests/cloud_infra_common/test_vm_ownership.py --use-provider="vsphere55"}}
> fix ownership tests

- cfme/containers/image.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_relationships_tables.py
- cfme/tests/containers/test_views_objects.py
{{pytest: cfme/tests/containers/test_relationships_tables.py cfme/tests/containers/test_views_objects.py -k "test_images_rel or test_images_views" --use-provider cm-env1}}
Refactoring Containers Images for navmazing. Removed some detail getters, tests can easily access the tables with InfoBlock.
Refactored the only tests using the Image class, tweaked the logic in test_relationships so that it more cleanly picks an assertion type, and lets a ValueType exception through - in case the UI actually changes and isn't supplying numeric values where it should.
UPDATE: Found tests_views_objects needs a new fixture and update to cfme_data. WIP until that's merged.
> CFME Container Image Navmazing conversion

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/test_download_report.py
- utils/appliance/__init__.py
{{ pytest: cfme/tests/intelligence/reports/test_crud.py  cfme/tests/intelligence/reports/test_canned_corresponds.py cfme/tests/intelligence/test_download_report.py -k "test_custom_report_crud or test_providers_summary or test_download_report_firefox" }}
> New navigation for reports

- cfme/fixtures/pytest_selenium.py
- utils/appliance/endpoints/ui.py
* upstream and > 5.7.0.3 versions are not patched with MiqQE JS anymore,
but force_navigate checks for .miqqe_version and quits webdriver if
its not matching current version. This patch addresses that problem,
by updating .miqqe_version file to vmdb location.
> update miqqe_version with current version for upstream/>5.7.0.3

- utils/appliance/__init__.py
* added darga-41 version string to configure method picker as darga41 needs to be configured as upstream appliance else it defaults to configure_cfme().
> added darga-41 version string to configure method picker.

- cfme/cloud/instance.py
- cfme/cloud/stack.py
- cfme/common/vm.py
- cfme/exceptions.py
- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/cloud/test_stack.py
- cfme/tests/configure/test_visual_cloud.py
{{pytest: cfme/tests/cloud/test_stack.py cfme/tests/cloud/test_delete_cloud_object.py cfme/tests/configure/test_visual_cloud.py}}
Integrate navmazing destinations into the cfme.cloud.stack module, and use those destinations test/cloud/test_stack.py
This includes some refactoring of the cloud tests that hit stacks, and some updates to vm methods to support refactoring and paramaterization of the delete tests.
Currently the test_delete_image() tests are failing, because clouds_images is no longer in the menu tree.
Marking WIP to address review comments and refactor some things from test into the object model.
> Cloud Stack Navmazing

- cfme/common/provider.py
Newer versions have ManageIQ instead CFME, this should cover the issue
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k 'provider_crud'}}
> Flash message fix for provider delete

- cfme/tests/infrastructure/test_provisioning.py
marking test + applying new vm_name generator
{{pytest: cfme/tests/infrastructure/test_provisioning.py -k "test_provision_from_template" --use-provider="scvmm" --use-provider="vsphere55" --long-running }}
> marking infrastucture provisioning

- cfme/provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
__Fixing__ scvmm/uncollecting not applicable and blocked tests.
marking and new name generator
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py --use-provider="scvmm" --use-provider="vsphere55" --long-running  }}
> fixing provisioning dialog tests

- fixtures/pytest_store.py
store.user is now no longer needed as it is replaced by the appliance
having a user of its own
> Remove store.user

- cfme/tests/services/test_different_dialogs_in_catalogs.py
> Automate BZ 1382765

- cfme/common/__init__.py
{{pytest: cfme/tests/control/test_actions.py::test_action_start_virtual_machine_after_stopping --long-running}}
__Fixing__ policy profile assigning because CheckboxTree has been replaced by BootstrapTreeview.
> Fix for policy profile assigning

- scripts/clone_template.py
- scripts/template_upload_rhos.py
* newer openstack versions (rhos9) uses the newer image api version (2.0)
the command line options changed for image v2.0, however we can still
use the commands in our scripts by specifying the api version we are using (1.0)
* this was affecting interop team to upload cfme images. this PR addresses that.
> specify glance api version in template uploader commands.

- cfme/common/provider.py
This adds a work around for bz1385436 where rhev c&u credential validation fails 50% of the time.  Basically added some retries until the validation succeeds and then finishes adding the provider.
> soften rhev candu validation due to bz1385436

- requirements.txt
pinning selenium to former release since selenium 3 started using marionette by default for local firefox.
> pinning selenium to former release

- cfme/provisioning.py
- cfme/tests/cloud/test_provisioning.py
Purpose
__Adding Preemtible VM's provision on GCE. It was implemented in product version 5.7.0.4
as feature is not critical and only for GCE - there's no need to parametrize it separately or write test for preemtible VM 
+adding new naming in cloud provisioning tests
{{pytest: cfme/tests/cloud/test_provisioning.py -k "test_provision_from_template" --use-provider="gce_central"  --long-running }}
> adding preemtible vms for gce

- cfme/tests/test_csrf.py
{{ pytest: cfme/tests/test_csrf.py }}
Fix downstream 5.6 test failure:
https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/downstream-56z-tests/1340/testReport/junit/cfme.tests/test_csrf/test_csrf_post/
Bug was fixed in 5.6, removing marker for blockers.
RHCFQE-1020
> Update test_csrf with new navigation, auto-test-fix

- cfme/infrastructure/pxe.py
{{pytest: cfme/tests/infrastructure/test_iso_datastore.py}}
Downstream-56z test failures due to duplicate navigation actions in the step to reach details.
The acc.tree() call hits the given provider's ISODatastore object. There is no pxe_image_type for ISO Datastore, and the table resulting from the existing accordion navigation cannot be clicked.
RHCFQE-1012
> Update infra.pxe ISODatastoreDetails navigation

- scripts/encrypt_conf.py
* script/encrypt.py always encrypts, which was of not much help when try to decrypt_yaml  credentials to    run tests locally.
*  scripts/encrypt now accepts params to -e encrypt, -d decrypt, --file conf file names. easy to decrypt/encrypt.
> updated encrypt file in script to accept params.

- cfme/web_ui/expression_editor.py
The expression editor was finding ">=" in the selector before finding ">" when ">" was provided as the key, resulting in unexpected filter results.
Use the exact argument to change the behavior to find an exact match, preventing selection of the wrong key.
The tests I found to be using this have other failures present, so it will be difficult to get relevant PRT results. These test failures are being addressed in separate branches, and many of the tests fail in part because of the behavior addressed in this PR.
Impacts RHCFQE-823 + 998
> Update web_ui.expression_editor, make count_form key an exact match

- cfme/containers/node.py
- cfme/containers/provider/__init__.py
- cfme/tests/containers/test_containers_default_views.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_relationships_tables.py
- cfme/tests/containers/test_views_objects.py
{{pytest: cfme/tests/containers/test_relationships_tables.py cfme/tests/containers/test_views_objects.py  --use-provider=cm-env1}}
Refactor cfme.container.node with navigation destinations, and modify anything that used previous navigation branches.
> Container node nav

- docs/getting_started.rst
Using a clean RHEL 7.2 install, the directions in the current 'Getting Started' produce 2 errors.
The cryptography package fails to build w/ AssertionError, and the docker package has an issue w/ pip.
This PR updates pip the address the docker package issue, and sets the 'no-cache-dir' when installing deps for force rebuild.
> FIX: 'Getting Started' instructions

- cfme/services/catalogs/catalog.py
- cfme/tests/services/test_catalog.py
- cfme/tests/test_ui_problems.py
{{ pytest: cfme/tests/services/test_catalog.py --use-provider=ec2-east }}
Replace the navigation branches and force_navigate() calls for services.catalogs.catalog with navmazing destinations and calls.
Rearranged imports in test_catalog to comply with coding standards because I'm weird like that.  No further changes to the test were required.
Added a version dictionary to catalog.py for the config button removal text, there are 4 unique button strings for 5.6 and 5.7 CFME.
> Navmazing: Service Catalog

- cfme/common/provider.py
- cfme/web_ui/flash.py
SSIA + see comments and https://bugzilla.redhat.com/show_bug.cgi?id=1375253
`flash.assert_success` makes sure there was at least one successful message, unlike `flash.assert_no_errors`. We should potentially gradually replace one with the other.
@dajohnso ^
{{pytest: cfme/tests/infrastructure/test_providers.py --use-provider nested-rhevm34 --use-provider rhvqe40 }}
> Fix RHEV C&U validation (workaround), add flash.assert_success

- cfme/web_ui/__init__.py
- widgetastic_patternfly.py
Required for compatibility passing objects with `__str__`
> BootstrapTreeview: Cast to string if not a known type

- cfme/automate/service_dialogs.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/services/test_catalog_item.py
- cfme/web_ui/__init__.py
{{ pytest: cfme/tests/services/test_catalog_item.py --use-provider=ec2-east }}
Refactor catalog item and catalog bundle navigation to use navigator/navmazing destinations.
Reworked the test a bit to cleanup, and to more efficiently use fixtures - moved catalog and dialog to module scope so they are re-used instead of recreated for every function.
> Service Catalog Item Navmazing

- utils/appliance/implementations/ui.py
wt was assign as the current wt instance to be used during the pre_navigate
and go functions of the CFMENavigateStep. The problem with this is that
after a quit() the widgetastic instance gets replaced, but this replacement
doesn't get propagated to the wt attribute.
> Fixing wt shortcut

- cfme/login.py
* Force navigate (which will be gone soon) calls the login function on
the current_user. If we are already logged in, this should not log us
out.
* This was happening because the navigate_to for hte LoginScreen was
placed BEFORE the check to see if we were already logged in as the
current user.
* This obviously then led to a logout happening to get us to hte
LoginScreen, from where a normal login occured.
> Fixed login for force navigate

- utils/log.py
1. We don't setup rootLogger. So, it is setup and inherited from different packages. F.e. I see such issue when use get_crud. Stdout/stderror is formatted by formatter definded in cinder client package.
2. From time to time I need to know how much time was some command run or measure the time between two commands.
So, I added default logging format in order to fix such issues.
> added timestamp to console logs

- cfme/tests/cloud_infra_common/test_power_control_rest.py
Fixing cloud tests where the desired action was performed on 'vms' collection instead of 'instances' collection and failed.
With this fix correct collection is selected - instances for cloud, vms for infra.
Update: PRT seems to be really fragile, I can't get it to pass reliably there. Narrowing test scope to see if it helps:
{{pytest: '''cfme/tests/cloud_infra_common/test_power_control_rest.py::test_start'' -v -k ''from_collection and not ec2west'''}}
> get correct collection - vms or instances

- cfme/tests/cloud_infra_common/test_retirement.py
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py::test_set_retirement_date --use-provider="gce_central"}}
> Fix gce name and add requirements

- cfme/tests/infrastructure/test_instance_analysis.py
This seems to work locally
{{pytest: -k test_ssa_template[vsphere55-fedora22-ext4] cfme/tests/infrastructure/test_instance_analysis.py --long-running --use-provider vsphere55}}
> Fix SSA vcenter ensure_browser_open()

- fixtures/parallelizer/__init__.py
- fixtures/parallelizer/remote.py
- utils/trackerbot.py
So, there was an issue where uncollection would mess up paralleizer if the slave was restarted after some tests passed earlier in the run. This fixes that.
> Fix uncollect

- cfme/common/vm.py
- cfme/tests/infrastructure/test_timelines.py
{{ pytest: cfme/tests/infrastructure/test_timelines.py }}
> fixed timelines tests for infra provider for 5.6.2.2

- cfme/containers/image_registry.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_views_objects.py
{{pytest: cfme/tests/containers/test_views_objects.py::test_imageregistry_views[cm-env1] --use-provider cm-env1}}
Refactor cfme.containers.image_registry with navigation destinations, and modify anything that used previous navigation branches.
> CFME Container Image Registry Navmazing conversion.

- cfme/containers/container.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_views_objects.py
{{pytest: cfme/tests/containers/test_views_objects.py::test_containers_views[cm-env1] --use-provider cm-env1}}
- Refactor cfme.containers.container with navigation destinations,
and modify anything that used previous navigation branches.
> CFME Container containers Navmazing conversion.

- cfme/web_ui/search.py
These button locators need to be anchor or button.
Expecting a single test case failure in test_advanced_search_providers for delete_after_save, expected and documented bug.
{{ pytest: cfme/tests/infrastructure/test_advanced_search_providers.py }}
> Update cfme.web_ui.search, button|anchor for apply/reset locators

- cfme/fixtures/smtp.py
- cfme/provisioning.py
- cfme/tests/infrastructure/test_provisioning.py
__Fixing__ provison test for infra providers. I assume, that it'd be better to verify by Request status. As last message get's updates from time to time
{{pytest: cfme/tests/infrastructure/test_provisioning.py --long-running --use-provider scvmm}}
> infrastructure providers provisioning fix in 5.7

- cfme/tests/containers/test_containers_main_pages_sort.py
Test main pages sort mechanism
{{pytest: cfme/tests/containers/test_containers_main_pages_sort.py -v --use-provider container }}
> Test main pages sort

- utils/appliance/__init__.py
5.6.3.0 contains the Miq.qe stuff already and we can ignore 5.5 and 5.7.0.1-5.7.0.3 -> we only need to patch 5.6.0, 5.6.1 and 5.6.2.
> Patch only below 5.6.3

- cfme/tests/containers/test_provider_configuration_menu.py
Test configuration menu under provider summary page
{{pytest: cfme/tests/containers/test_provider_configuration_menu.py -v --use-provider container }}
> test_provider_configuration_menu

- scripts/get_unregistered_vmware_files.py
- this patch is to list out all the files/folders on the
datastore which are not registered to any vm.
- right now this patch is not considering image template files
as registered files, so those will be listed as unregistered too.
templates needs to be filtered(wip).
> List all unregistered files on vmware datastores.

- artifactor/plugins/ostriz.py
- fixtures/artifactor_plugin.py
- markers/__init__.py
- markers/polarion.py
This is for marking unparametrized test cases so far. This will inject the "polarion" key in the JSON that gets sent into Ostříž. If no marker is provided, it is None, otherwise it is a list of Polarion test cases associated with the test.
@psav - your opinion?
> Add pytest.mark.polarion()

- cfme/tests/openstack/test_relationships.py
Since version 5.6.2 in infra provider there is no need to verify AZ and tenants
{{pytest: cfme/tests/infrastructure/test_host_role_type.py cfme/tests/infrastructure/test_roles_names.py -v --use-provider tripleo }}
> Removed tenants and AZ tests, templates fix

- cfme/tests/containers/test_basic_metrics.py
This is a basic test that checks if Metrics for OSE are up
{{pytest: cfme/tests/containers/test_basic_metrics.py -v --use-provider container }}
> Basic Metrics Test

- cfme/rest/__init__.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_cloud_service_catalogs.py
Fixing assert when service was successfully added on 5.7.x:
```
>       assert row.last_message.text == 'Request complete'
E       assert '[EVM] Servic... Successfully' == 'Request complete'
E         - [EVM] Service [blvFGPk3jh] Provisioned Successfully
E         + Request complete
```
Also fixing catalog item creation. Some tests are still failing so WIP.
{{pytest: '''cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_edit_service'' -v'}}
> Fix catalog item creation and success assertion for test_rest_services

- cfme/tests/containers/test_containers_default_project_replicators.py
{{pytest: cfme/tests/containers/test_containers_default_project_replicators.py -v --use-provider container }}
Fixing test_containers_default_project_replicators to work with Navmazing
> Navmazing fix for the containers_default_project_replicators test

- cfme/exceptions.py
- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/dballocator_methods.py
- cfme/tests/middleware/jdbc_driver_methods.py
- cfme/tests/middleware/test_middleware_datasource.py
- cfme/tests/middleware/test_middleware_drivers.py
- conf/cfme_data.yaml.template
Added new methods to allocate and deallocate database on request.
Usage:
properties = db_allocate('oracle12c')
db_deallocate(properties['uuid'])
> Added support of DBAllocator service in middleware provider tests.

- cfme/common/provider.py
- cfme/tests/containers/test_provider_configuration_menu.py
- cfme/tests/containers/test_summary_pages_links.py
- cfme/web_ui/__init__.py
Test summary pages links
{{pytest: cfme/tests/containers/test_summary_pages_links.py -v --use-provider container }}
> Test summary pages links

- cfme/common/vm.py
- cfme/tests/infrastructure/test_vm_power_control.py
__Fixing__ vm.py with temporary workaround as at the moment VM's Reload button brings us to all VM's page
and
__Adding__ with separate "check_power_option" test because it needs to be verified but shouldn't affect other tests
__N.B.__ I'll update testrun with different providers one by one
{{pytest: cfme/tests/infrastructure/  "-k test_power_options_from" --long-running --use-provider vsphere6-nested --use-provider scvmm}}
> fixing infrastucture providers power operations

- cfme/tests/infrastructure/test_config_management.py
This PR should disable Ansible Tower test cases for 5.7.0.9 streams due to this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1388928.
{{pytest: cfme/tests/infrastructure/test_config_management.py -v}}
> Failed to add ansible tower

- cfme/automate/explorer.py
Fixing test_schema_crud failures in 5.7.
The schema edit form requires a type in CFME 5.7, set a default if none is provided during init.
{{ pytest: cfme/tests/automate/test_class.py -k test_schema_crud}}
> Fix automate.test_class.test_schema_crud in 5.7

- cfme/tests/configure/test_server_roles.py
Jenkins 5.7 failure due to database_synchronization not being present in the server roles form in CFME 5.7.
Remove it from the all_possible_roles fixture depending on version.
{{ pytest: cfme/tests/configure/test_server_roles.py }}
> Update test_server_roles, database_synchronization removed in 5.7

- cfme/tests/infrastructure/test_config_management.py
The test_config_manager_detail_config_btn and test_config_manager_edit tests were failing in Jenkins with an Endpoint URL failure, related to propaged 5.7 bug 1393987.
Added the bug to the list of blockers for these two tests. Its possible this bug will effect the other tests as well, and should potentially be applied to all of them.
{{ pytest: cfme/tests/infrastructure/test_config_management.py }}
> Update infra.test_config_mgmt, add blocking bug

- cfme/configure/about.py
- cfme/tests/configure/test_version.py
The about screen drastically changed between CFME 5.6 and CFME 5.7. Wrote a get_detail() method to parse and return the given property.
{{ pytest: cfme/tests/configure/test_version.py }}
> Update config.about and config.test_version, adding get_detail

- cfme/intelligence/reports/reports.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/intelligence/reports/test_views.py
The 3 tests for the 3 types of report views were stuck into the configure.test_default_views_infra. Since the tests don't have anything to do with default views,  I moved them to the intelligence.report module and condensed the 3 into a paramaterized test and wrote a fixture for creating the report.
Added a delete function to CannedSavedReport
BZ 1396220 was written for 5.7 and upstream test failures, and added as a blocker. Test is not skipping:
```pytest
INFO:cfme:Calling metaplugin blockers(resolve_blockers) with meta signature ['blockers'] {}
INFO:cfme:Ignoring bug #1396220, appliance version not in bug release flag
INFO:cfme:Metaplugin blockers(resolve_blockers) with meta signature ['blockers'] {} has finished
``` …
> Move report view tests out of configure.test_default_views_infra

- cfme/fixtures/pytest_selenium.py
This log message has persisted in our codebase for too long and it's very misleading, as it will say did not appear as expected, when it completes successfully.
> Misleading log message BEGONE!

- conftest.py
Reverts ManageIQ/integration_tests#3815
Reverting due to Jenkins issues:
```
INTERNALERROR>   File "/home/jenkins/workspace/downstream-57z-tests/conftest.py", line 34, in pytest_configure
INTERNALERROR>     if store.current_appliance.version < '5.6':
INTERNALERROR>   File "/home/jenkins/shiningpanda/jobs/185abe92/virtualenvs/3b0c0aff/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
INTERNALERROR>     return getattr(self._get_current_object(), name)
INTERNALERROR>   File "/home/jenkins/shiningpanda/jobs/185abe92/virtualenvs/3b0c0aff/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
INTERNALERROR>     return self.__local()
INTERNALERROR>   File "/home/jenkins/workspace/downstream-57z-tests/utils/appliance/__init__.py", line 2243, in …
```
> Revert "Add a warning if running unsupported appliance"

- cfme/tests/configure/test_zones.py
Adding tests for zones to cover cases max length(50) of name and description and Z. As well as creating a zone duplicate name and description.
> Add test_zone_add_maxlength and test_zone_add_dupe test

- utils/appliance/__init__.py
this pr turns the `__hash__` methods of apliances to the propper hashing method using the builtin `hash` function instead of the jump over `md5`
> utils.appliance: just use python hashes for appliance

- scripts/clone_template.py
* deploy option is specified when local provider data is used.
interop team requested to write the ip to outfile by default.
this does not change cfmeqe deployments using clone_template.
> default ip write to outfile when local provider data is used.

- scripts/cleanup_old_vms.py
* Test, TEST, Jenkins, JENKINS, all of these needs to be included in deletion. This fix, ignores the case
while matching the vm names.
> ignore case in cleanup scripts.

- cfme/tests/infrastructure/test_provisioning_rest.py
__Fixing__ behavior when we are looking for template located on specific provider and ems data is missing for currently evaluated template.
__Note to reviewers__ provisioning of vm is timeouting on PRT, but the template was already selected, so the changed code works.
> skip template when ems record is missing

- cfme/tests/test_utilization.py
- cfme/tests/test_utilization_metrics.py
-------------------------------------------------
1)Added vsphere, rhevm providers to test_utilization_metrics.py.
2)Removed cloud providers from test_utilization.py
{{pytest: -v -k 'test_raw_metric or test_metrics_collection' --long-running}}
> Change test generator to generate tests for all relevant providers for C&U tests

- cfme/tests/cloud/test_provisioning.py
__Fixing__ test_provision_from_template[azure] - vm_size is now lower cased in CFME, but we still need it as is in yamls for scripts
{{pytest: cfme/tests/  "-k test_provision_from_template[azure]" --long-running --use-provider azure}}
> Azure vm_size became lower case in 5.6

- cfme/tests/containers/test_relationships_tables.py
{{pytest: cfme/tests/containers/test_relationships_tables.py -v --use-provider container }}
The names in the relationships table are not hardcoded anymore, so we check every value in the 
table regardless of its name.
> Modified test_relationships_tables.py to account for changes in CFME 5.7

- cfme/tests/test_ui_problems.py
- cfme/tests/webui/test_splitter.py
- cfme/web_ui/menu.py
- cfme/web_ui/mixins.py
- cfme/web_ui/splitter.py
{{pytest: cfme/tests/webui/test_splitter.py -v}}
Reworked pull splitter tests, because splitters ui was changed.
Deleted old splitters tests and methods.(broken_angular_select test is in same test file and it's not working so I told prt to test test_splitter.py only)
Added new splitters tests and methods.
Added webui folder in tests.
All the module changes are related to test_splitter only.
> Splitters UI tests rework

- utils/appliance/__init__.py
- utils/ext_auth.py
* updated ext_auth_openldap method. evm serverd service needs
to be restarted only for openldap and not for ipa uninstall.
> update disable ext_auth_openldap method.

- cfme/tests/distributed/test_appliance_replication.py
> disable distributed tests that depend on browser_steal

- cfme/tests/containers/test_containers_default_views.py
{{pytest: cfme/tests/containers/test_containers_default_views.py -v --use-provider container }}
Fixing test_containers_provider_default_view to work with Navmazing
> Test containers providers default view fix final1

- utils/appliance/__init__.py
- utils/appliance/implementations/ui.py
Both 5.6.z (5.6.3) and 5.7.0 (5.7.0.14) now contain ovirt_metrics-1.3.1.
> Remove ovirt patching; not necessary anymore

- cfme/tests/services/test_rest_services.py
- utils/api.py
* adding tests for deleting service dialogs over REST API
* adding possibility to specify HTTP method for action (e.g. DELETE, POST)
__Note to reviewers__: infinispinny and/or jquery ajax issue makes it impossible to test this reliably on PRT
> add REST API tests for service dialogs

- cfme/tests/automate/test_rest.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/test_rest.py
- utils/api.py
* Adding tests for automate and providers collections and for basic REST API functionality
* Removing redundant test `test_edit_user_password`
* Removing support for old REST API versions and old CFME versions
* Fixing behavior when entity doesn't contain "href" and contains "id"
__PRT outcome explained:__
* 5.7:
__1 failed__: timeout ->`Provider vsphere55 is behaving badly, marking it as bad.`
__6 errors__: `Exception: No providers could be set up matching the params`
* upstream:
`SproutException: Exception DoesNotExist raised! AppliancePool matching query does not exist.`
i.e. no problems caused by PR, can be approved and merged ;)
> New REST API tests

- requirements.txt
the more strict pin gives better control over the installed version and allows to move to new apis more graceful and controlled
> pin sentaku version more strictly

- cfme/tests/containers/test_summary_pages_links.py
{{pytest: cfme/tests/containers/test_summary_pages_links.py -v --use-provider container }}
Fix for /test_summary_pages_links.py: breadcrumbs names are calculated dynamically with and without prefix of 'Container'.
> Fix test summary pages links - breadcrumb names

- cfme/tests/containers/test_views_objects.py
py.test --use-provider container cfme/tests/containers/test_views_objects.py -v
Added comments with the relevant Polarion test cases' numbers.
> Fixed versioning and comments in test_views_objects.py

- cfme/web_ui/tabstrip.py
* Previously OrderedDict was honoured but a change a while back broke
the ordering. This commit fixes that.
{{pytest: cfme/tests/infrastructure/test_pxe_provisioning.py --use-provider vsphere55}}
> Fixed form filling order

- cfme/cloud/stack.py
- cfme/configure/settings.py
- cfme/exceptions.py
- cfme/intelligence/reports/reports.py
- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/service_catalogs.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/containers/test_containers_default_views.py
- cfme/tests/intelligence/reports/test_views.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
- cfme/tests/services/test_provision_stack.py
Provide a DefaultView class in configuration.settings, with navmazing destination and classmethods for get/set view.
Refactor tests to use navigation and getter/setter functions.
May impact PR #3807 @pavelzag 
PRT Results
* Upstream: last run failed to get appliance from stack, previous runs had infini-spinny
* 5.7: infini-spinny and failures outside of scope
* 5.6: test_provision_stack failures unrelated to navigation, known bugs.
I would prefer to address the test_provision_stack failures in a different PR. There are some shortfalls of the stack functions that don't account for paged grid/table views and fail to find the stack.
> Configuration.settings class for DefaultView

- cfme/base/ui.py
- cfme/configure/tasks.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_host_drift_analysis.py
Obviously some commit squashing to be done as this is tested.
providing tasks destinations for the tabs, refactoring tests to remove use of old destinations.
little bit of refactoring of the module methods.
{{ pytest: cfme/tests/control/test_actions.py --use-provider vsphere6-nested --long-running }}
**PRT Results**
Run #8908
* 5.6 Unrelated to navigation changes, should be addressed in different PR (snapshot tree parsing)
* 5.7 Spinny timeouts
* upstream: sprout failed to deliver appliance
> Configuration Tasks navigation destinations

- cfme/common/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/messaging.py
- cfme/middleware/server.py
- cfme/tests/middleware/random_methods.py
- cfme/tests/middleware/test_middleware_utilization.py
- cfme/web_ui/utilization.py
Adding query support for chart(utilization). Added test for middleware server charts.
Functions, for list of available have a look on `UtilizationMixin`
```
page.utilization.charts  # => '[ 'jvm_heap_usage_bytes','web_sessions','transactions']'
provider.utilization.jvm_heap_usage_bytes.list_data_chart()  # => returns data as list
page.utilization.jvm_heap_usage_bytes.list_data_table()  # => returns data as list
page.utilization.jvm_heap_usage_bytes.list_data_mgmt()  # => returns data as list
page.utilization.jvm_non_heap_usage_bytes.option.set_by_visible_text(op_interval='Daily')
page.utilization.jvm_non_heap_usage_bytes.legends
page.utilization.jvm_non_heap_usage_bytes.committed.set_active(active=False) # => Disables
page.utilization.jvm_non_heap_usage_bytes.committed.set_active(active=Tr …
```
> UtilizationMixin support for Monitoring >> Utilization page

- cfme/containers/provider/openshift.py
- cfme/tests/containers/test_static_custom_attributes.py
- utils/api.py
{{pytest: cfme/tests/containers/test_static_custom_attributes.py -v --use-provider cm-env2 }}
Added custom attributes CRUD functionality to openshift provider.
Added custom attributes CRUD tests.
> Added provider custom attributes functions and tests

- cfme/infrastructure/virtual_machines.py
RHCFQE-1415
Fixing snapshot name parsing for 5.6.
In 5.7 this was working, but in 5.7 the selector ends up getting the text of the entire snapshot tree. The text is newline delineated, so split and select the last item. The split returns a list that should contain a single item.
Also fix small typo in docstring for current_snapshot_description
{{ pytest: cfme/tests/control/test_actions.py --use-provider vsphere55 --long-running -k test_action_create_snapshot}}
Marked WIPTEST until I get pytest to actually collect the relevant functions.
> [1LP][RFR] Update infra.Vm.current_snapshot_name to parse snapshot name in 5.6

- cfme/infrastructure/host.py
host.power_off(), host.power_on() could not be invoked since there is a confirmation message.
Now with this change the host power controls handle confirm message and immediately invoke the power action
> [1LP][RFR] Handle confirmation alert in host power controls

- scripts/cleanup_old_vms.py
- scripts/sync_template_tracker.py
Credentials check is necessary when host_credentials are added to cfme_data, otherwise default to host_default credentials. Similarly, IP check is necessary for the providers in cleanup script, if IP is not reachable then there is no necessary to try invoking that provider.
> [1LP][RFR]added ip and host_credentials check in cleanup scripts.

- cfme/tests/cloud/test_provisioning.py
__Fixing__ cloud provisioning  because it is currently failing on instance.create call due to missing imports. 
Also affects #3913 
{{pytest: cfme/tests/cloud/test_provisioning.py --use-provider gce_central --long-running}}
> [1LP][RFR] fix after instance navmazing arrived

- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_vm_power_control.py
skip test_provider_add_with_bad_credentials for RHV because of bug 1399622
uncollect test_power_options_from_on for RHV because it's not fully supported
> [WIP] skip for a bug and uncollect for power options

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_timelines.py
Since timelines are completely redesigned, the timelines tests are also need to be updated.
So, I'm disabling timelines tests until those are fixed.
> [WIPTEST] disabling timelines for 5.7

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
{{ pytest: cfme/tests/services/test_rest_services.py --long-running }}
**PRT Results:** In run 9305 I saw failures that were unrelated to my changes, and were due to the request not succeeding or failing to submit. I would like to not address these failures in this PR, as the intent was to limit the scope of testing to only providers with relevant provisioning data in the YAML.
Jenkins failures against 5.7 were cropping up with the failure below.
The rhos_uc provider, along with other infra type providers, do not have the provisioning keys necessary to use the cfme.rest.services method.
Add a testgen/parametrize line to the start of the test to restrict testing to infra providers with the necessary provisioning keys.
If the RHOS team would like to have these REST tests executed against …
> [1LP][RFR] Update services.test_rest_services, require provisioning fields

- cfme/cloud/flavor.py
RHCFQE-1458
Adding new cloud model classes and navigation destination classes where necessary for cloud.flavor, cloud.tenant, and cloud.availability zone.
Looks like there is a complete lack of tests for flavor and availability zone, may add some basic tests to make sure the pages are navigable.
> [1LP][RFR] Add navigation destinations for cfme.cloud.flavor/availability_zones/tenant

- cfme/infrastructure/virtual_machines.py
- cfme/provisioning.py
- cfme/tests/infrastructure/test_infra_quota.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/services/test_operations.py
Since my changes made to virtual machines broke old infra provisioning navigation, I've had to quickly convert this remaing navigation to navmazing.
P.S. actually current provisioning destination and all provisioning related fixtures and functions have to be moved to appropriate vm's method. I've created a card about that and assigned it to myself.
> [1LP][RFR] replacing old infra provisioning by navmazing destination

- cfme/cloud/tenant.py
- cfme/exceptions.py
- cfme/tests/cloud/test_tenant.py
{{pytest: cfme/tests/cloud/test_tenant.py --use-provider rhos7-ga}}
Improving the create/delete methods for cloud.tenant and wrote a little CRUD test.
**PRT Results**
* 5.6: uncollected purposefully
* 5.7 and upstream: rhos7-ga is cleaning up the tenants, which is causing failures. create/delete are working as expected otherwise
> [RFR] cloud.tenant CRUD and test

- widgetastic_patternfly.py
Nandini noticed some errors which seem to come from accordion handling. Turns out I wrote it so it checks open and close separately. I removed the is_closed logic and replaced it with just a plain `not`.
> Simplify WT accordion openness detection

- cfme/provisioning.py
__Fixing__ test_tag in provisioning dialog tests. Tags tree was updated to Bootstraptreeview in 5.7
--
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py "-k test_tag"  --long-running}}
> [RFR]fix for test_tag

- utils/log.py
``service evmserverd status`` was throwing that in some instances.
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py::test_drift_analysis -v --use-provider vsphere55 --long-running}}
> [RFR][1L] Mitigate UnicodeEncodeError by applying safe-string() in that case

- cfme/cloud/tenant.py
Updating cloud.tenant.delete() to prevent 'result' not being set.
Added statement to catch invalid use - cancel delete from details page (UI doesn't prompt).
> [RFR] Fix return logic in cloud.tenant.delete()

- cfme/tests/test_db_migrate.py
- cfme/tests/test_db_restore.py
- utils/appliance/__init__.py
Enhance the DB migration test to be able to migrate bigger databases
Refactor/update utils.appliance
Update DB restore test
{{pytest: -k "test_db_migrate and scvmm_5620"}}
> [RFR][1LP] Extend DB migrate test, refactor appliance

- requirements.txt
- scripts/cleanup_old_vms.py
* added new arg parameters to the cleanup_old_vms script.
-l, --list: list vms of the specified "provider_type", by default --list is
set to False.
--provider-type: list of the provider type to list the vms, useful in case of gce,
azure, ec2 to get the insight into cost/vm listing.
usage: --provider-type ['gce'], --provider-type ['gce', ec2, 'azure', 'virtualcenter']
--output, optional filepath to list vms, by default its log/instance_list.log
usage:
python cleanup_old_vms -l provider_type 'ec2, gce, azure'
> [1LP][RFR] report azure gce ec2 vm lists.

- cfme/intelligence/reports/reports.py
__Fixing__ Navigation after report was ran because it is currently trying to read table from different tab which is incorrect. It should be doing before reading table, it was necessary to change tab before reading the table.
{{pytest: -k 'test_custom_vm_report' -v}}
> [RFR]Navigate to Saved reports before checking results table.

- cfme/tests/containers/test_basic_metrics.py
{{pytest: cfme/tests/containers/test_basic_metrics.py -v --use-provider cm-env2 }}
This fixes the Basic Metrics test that allows him to actually fail when the OSE is down
> [RFR] Test Basic Metrics - Fixed assertions

- cfme/rest/gen_data.py
- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/service_catalogs.py
- cfme/services/myservice.py
- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/services/test_add_remove_vm_to_service.py
- cfme/tests/services/test_cloud_service_catalogs.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
- cfme/tests/services/test_different_dialogs_in_catalogs.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_generic_service_catalogs.py
- cfme/tests/services/test_iso_service_catalogs.py
- cfme/tests/services/test_myservice.py
- cfme/tests/services/test_operations.py
- cfme/tests/services/test_provision_stack.py
- cfme/tests/services/test_pxe_service_catalogs.py
- cfme/tests/services/test_request.py
- cfme/tests/services/test_service_catalogs.py
- cfme/web_ui/flash.py
{{pytest: cfme/tests/services/ --long-running}}
PR 3894 updated CatalogItem class to take a provider object instead of the name.
Update callers to pass the object
PRT Results:
Lots of failures from form filling and flash message assertions, don't appear to be related to my changes but I'm debugging and trying to clean up the tests.
> [RFR] Update CatalogItem callers to pass a provider object

- cfme/tests/services/test_rest_services.py
Adding basic tests for "blueprints" collection.
{{pytest: '''cfme/tests/services/test_rest_services.py::TestBlueprintsRESTAPI'' -v'}}
> [RFR] REST API tests for blueprints

- cfme/cloud/availability_zone.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_visual_cloud.py
Added cloud.availability_zone class  and nav destinations.  There are no existing tests for availiabity_zones, I didn't write any.
Refactored tests that had lists of infra/cloud force_navigate lists for objects+navmazing.
*PRT Results*
* 5.6: 88% pass, default view settings for clouds.images are failing in automation working manually
* 5.7: 89% pass, same tests/skips.
I would like to handle these test fixes in a separate PR, they're unrelated to navigation changes.
> [RFR] Add Cloud Availiability Zone navigation, refactor tests for cloud/infra objects

- cfme/intelligence/reports/menus.py
- cfme/services/myservice.py
- cfme/tests/intelligence/reports/test_menus.py
- cfme/tests/webui/test_splitter.py
1. replaced force_navigate in several tests
{{pytest: --use-provider=vsphere55 cfme/tests/webui/test_splitter.py cfme/tests/intelligence/reports/test_menus.py }}
> [RFR] replaced force_navigate calls with navigate_to

- cfme/infrastructure/provider/__init__.py
The "above-5.7" verpick pointed to a bad relationship link.
{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py::test_validate_custom_rate_memory_usage_cost -v --long-running --use-provider vsphere55}}
> [RFR] Fix the relationship string for versions >euwe

- widgetastic_patternfly.py
This might fail but it should not fail on tree operations
{{pytest: cfme/tests/control/test_basic.py::test_policy_crud -k VMControlPolicy -v --long-running}}
> [RFR][1LP] BootstrapTreeview: Fix text matcher

- cfme/base/ui.py
- cfme/configure/access_control.py
- cfme/intelligence/chargeback.py
- cfme/tests/configure/test_access_control.py
Added new ChargebackView to chargeback, registered Navigation against Server.
Added Access Control Tenant navigation
Refactored tests accordingly
Using WIPTEST and RFR because of the priority push for force_navigate() removal.
{{ pytest: cfme/tests/configure/test_access_control.py -v --long-running }}
> [1LP][RFR] Access Control Tenant Nav

- cfme/cloud/instance/azure.py
force_navigate, other provider classes use select_provision_image, which navigates.
> [WIPTEST] Update cloud.instance.azure, image provision call in create

- cfme/tests/infrastructure/test_snapshot.py
Previously there were problems with snapshot tests not removing VM they
created on RHV golden environment, this should fix it.
Also, not removing the VM if it was already present, to make sure it doesn't break stable environments, where you always want to have that VM...
> [1LP][RFR] Moved finalizer to correct place

- cfme/containers/provider/__init__.py
- cfme/containers/provider/openshift.py
- cfme/tests/containers/test_reload_button_provider.py
{{pytest: cfme/tests/containers/test_reload_button_provider.py -v --use-provider cm-env2 }}
The test verifies data integrity of the fields in the Relationships table (while on provider summary page) after the reload button is clicked. 
Update: added new functionality to verify data integrity for images
> [RFR]Added test_reload_button_provider.py to test functionality of refresh button

- cfme/test_framework/sprout/client.py
- cfme/test_framework/sprout/plugin.py
- conftest.py
- fixtures/parallelizer/__init__.py
- requirements.txt
* decouple multi instance provisioning from the parallelizer
* unify single and multi instance provisioning
* simplify and streamline sprout provisioning codebase
* try to use only logging for ux
> [RFR] unify sprout provisioning

- cfme/web_ui/__init__.py
Add comment noting selenium bug that breaks FileInput in chrome
Change to passing os.path.abspath() of the filename instead of the raw string.
Poorly named branch, this doesn't 'fix' FileInput.
> [1LP][RFR] Update web_ui.FileInput._fill_file_input, pass file abspath

- widgetastic_patternfly.py
some of nav destinations use href instead of title.
This small patch fixes that issue.
{{pytest: --long-running cfme/tests/control/test_alerts.py:test_alert_vm_turned_on_more_than_twice_in_past_15_minutes}}
> [1LP][RFR] fix for href menu navigation

- markers/uncollect.py
SSIA
This change is necessary if we want to be able to collect / run tests with a limited subset of providers.
`py.test cfme/tests --use-provider ec2east --collect-only` will (without this fix) cause:
```
INTERNALERROR> Exception: Failed to uncollect test_power_options_from_on, best guess a fixture wasn't ready
```
> [1LP][RFR] Don't uncollect uncollected stuff

- widgetastic_patternfly.py
To heal all our `UnexpectedAlertPresentException` related sorrows. Tested manually.
> [RFR] Add alert handling when clicking last menu item

- cfme/tests/control/test_bugs.py
- widgetastic_manageiq.py
{{pytest: -v -k 'test_delete_all_actions_from_compliance_policy'}}
New test for Control which tests deleting all actions from a compliance policy. We should not allow a compliance policy to be saved if there are no actions on the compliance event (since you can't add/remove events from compliance policies). https://bugzilla.redhat.com/show_bug.cgi?id=1395965
> [1LP][RFR] New test test_delete_all_actions_from_compliance_policy

- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/infrastructure/test_provisioning_rest.py
- utils/appliance/__init__.py
- utils/virtual_machines.py
* Many cases where we were comparing to a mgmt_system object, instead of the provider object itself
* Deferred the loading of mgmtsystem classes until needed
* Moved some deployment args into a deployment_helper function, making the code in utils generic
> [RFR] Defer loading

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
Adding power operations tests for `/api/services` collection.
Reviving `test_set_service_owner` and `test_set_services_owner`
**PRT results**
all tests on upstream are failing on `ServiceDialog.create()` with `NoSuchElementException`. That's unrelated to changes in this PR.
> [1LP][RFR] REST API tests for services collection

- scripts/sync_template_tracker.py
- utils/providers.py
...to fix sync template tracker and any other scripts that might require all provider keys (wihtout filtering) with no access to an appliance.
> Add list_all_provider_keys

- cfme/exceptions.py
Going to use this in container.node widgetastic refactor
Not used anywhere yet, PRT results are pretty irrelevant.
> [RFR] Add NodeNotFound to cfme.exceptions

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
Adding tests for /api/orchestration_templates collection.
{{pytest: '''cfme/tests/services/test_rest_services.py::TestOrchestrationTemplatesRESTAPI'' -v'}}
**PRT results**
test_delete_orchestration_templates[from_detail] is expected to fail until https://bugzilla.redhat.com/show_bug.cgi?id=1414881 is fixed
> [1LP][RFR] REST API tests for orchestration templates

- requirements.txt
- scripts/ipappliance.py
Ensure that we getting nonzero exit from the process for any problem in
`call_appliance()` -- for example if the` IPAppliance` instantiantion fails,
it used to return 0 because an `Exception` there meant just thread exit,
without writing to the results.
Threads can be very cumbersome whereas futures are quite elegant way to
spin-up tasks on multiple threads. Let's use it to to make code hopefully more
readable and less error-prone.
> [1LP][WIP] ipappliance nonzero exit fix.

- cfme/tests/cloud/test_cloud_init_provisioning.py
- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud/test_provisioning.py
- cfme/tests/services/test_cloud_service_catalogs.py
- cfme/tests/services/test_orchestration_template.py
- cfme/tests/services/test_provision_stack.py
- utils/testgen.py
Starting to obliterate the class calls
{{pytest: --collect-only --use-provider complete}}
> [RFR] - Fix testgen refs

- cfme/infrastructure/provider/rhevm.py
This is to fix the failing rhev template tester job (where we sed in a provider without server_zone in yaml set). It shouldn't be pulled from yamls anyway - eventually, we should pull it from the appliance attached to the crud object - but this is a quickfix.
> [1LP][RFR] Add default server_zone to rhev providers

- cfme/containers/container.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/domain.py
- cfme/middleware/messaging.py
- cfme/middleware/server.py
- cfme/middleware/server_group.py
- scripts/refactoring/provider_move.py
this is about moving `cfme.*.provider{,.*}' over to `cfme.provider.*`
the change was implemented by letting rope lose on the codebase
> [1LP] [RFR] prepare refactoring script to do the providers move

- cfme/web_ui/expression_editor_widgetastic.py
{{pytest: -v -k "test_modify_vm_condition_expression" --long-running}}
__Added__ `VersionPick` into commit and discard buttons. Also `ExpressionEditor` has been converted to View.
> [1LP] [RFR] ExpressionEditor fix

- widgetastic_manageiq.py
No tests using this widget yet, PRT results are just smoke tests.
Updated PaginationPane.exists to just return self.is_displayed - I'm not sure why it wasn't this simple to begin with? Previous code raised exception on screens without paginator.
Updated _parse_pages() calculation of current page and page amount:
* Removed 'corner' cases of modulo and adding 1 (was necessary for page amount and missing)
* Changed to float division instead of integer (floored) division and used math.ceil to round up
I tested locally with:
* `.pages()` on a screen without pages
* `pages()` on a screen with 1 page
* `pages()` on a screen with multiple pages
* `exists` on a screen without paginator (False)
* `exists` on a screen with paginator (True)
> [1LP][RFR] Update widgetastic_miq.PaginationPane, bug fixes

- cfme/infrastructure/provider/__init__.py
Fix test that are using `vm_name` identifier string from `cfme/infrastructure/provider/__init__.py` and are failing with
`NoSuchElementException: Message: Element .//table/tbody/tr/td[1][@class="label"][normalize-space(.)="VMs and Instances"]/.. not found on page.`
**PRT results:**
relevant PASSED tests on 5.7:
cfme/tests/cloud_infra_common/test_power_control_rest.py::test_stop[vsphere55-cfrom_detail] PASSED
cfme/tests/cloud_infra_common/test_power_control_rest.py::test_start[vsphere55-from_detail] PASSED
cfme/tests/cloud_infra_common/test_power_control_rest.py::test_suspend[vsphere55-from_detail] PASSED
cfme/tests/cloud_infra_common/test_power_control_rest.py::test_reset_vm[vsphere55-from_detail] PASSED
cfme/tests/cloud_infra_common/test_power_control_rest.py::test_stop[vsphere55-from_col …
> [1LP][RFR] fix vm_name identifier string

- cfme/tests/services/test_service_catalogs.py
Fixing how catalog name is obtained in test_order_catalog_item_via_rest.
PRT is not cooperating, tests are failing or skipped there for various unrelated reasons, tested localy:
cfme/tests/services/test_service_catalogs.py::test_order_catalog_item_via_rest[vsphere6-nested] PASSED
====================================================================== 1 passed in 648.23 seconds
{{pytest: '''cfme/tests/services/test_service_catalogs.py::test_order_catalog_item_via_rest'' --runxfail --long-running -v'}}
> [1LP][RFR] fix test_order_catalog_item_via_rest

- cfme/control/explorer/actions.py
- cfme/control/explorer/alert_profiles.py
- cfme/control/explorer/alerts.py
- cfme/control/explorer/conditions.py
- cfme/tests/control/test_bugs.py
{{pytest: -v -k "test_control_identical_description"}}
__New test__ for Control. CFME should not allow to create policy, alerts, profiles, actions and others to be created if the item with the same description already exists.
Steps:
* Create an item
* Create the same item again
Result:  the item shouldn't be created.
> [1LP] [RFR] New test test_control_identical_descriptions

- cfme/tests/containers/test_containers_summary.py
{{pytest: cfme/tests/containers/test_containers_summary.py -v --use-provider cm-env1 }}
This should fix the objects duplication problem we have that is caused by successive providers removal and addition
> [RFR] Containers Summary Test, possible fix for objects duplication problem

- cfme/automate/__init__.py
Found cfme.automate was using `self.obj` in views, which DNE.
Changed to self.context['object'].
> [1LP][RFR] Update cfme.automate, move self.obj to self.context in views

- cfme/common/vm.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vm_power_control.py
__Fixing__ excessive navigation
+ __removin__ register_event as it's causing huge issues with testing machine performance and slowdowns test run in general. Events are not the main thing of this tests and without them tests run ~5times faster
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py  "-k not test_power_options_from and not test_guest" --use-provider vsphere55  --long-running}}
> [1LP][RFR] Optimizing navigation in infra VMs

- utils/trackerbot.py
- utils/version.py
Support 5.8 in trackerbot and version utils.
> [RFR] Update utils trackerbot and version for cfme 58

- cfme/cloud/stack.py
- cfme/tests/cloud/test_stack.py
The navigation for stack didn't cleanly handle exceptions when navigating to relationships that aren't populated.
Catch NoSuchElement and raise CandidateNotFound, and adjust tests accordingly to assert on the relationship link text if the navigation to the relationship link fails.
Passing tests locally so marking RFR, waiting on PRT run 10171
> [RFR] Update cloud.stack and test_stack, handle empty relationship

- utils/ssh.py
{{pytest: cfme/tests/cli/test_evmserverd.py::test_evmserverd_stop -v --long-running}}
> SSH .status: Ignore warning line for workers

- cfme/rest/gen_data.py
- cfme/tests/test_rest.py
Adding tests for /api/requests collection.
{{pytest:  cfme/tests/test_rest.py -v -k TestRequestsRESTAPI}}
> [1LP] [RFR] REST API tests for /api/requests

- cfme/tests/test_rest.py
Fixing issue described in https://github.com/ManageIQ/integration_tests/issues/4114
I believe `pytest_generate_tests` is not necessary as no test is parameterized with provider.
{{pytest: cfme/tests/test_rest.py -v}}
> [1LP] [RFR] Fix provider selection in test_rest.py

- cfme/cloud/instance/__init__.py
- cfme/cloud/instance/image.py
- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/services/test_provision_stack.py
Missed this in PR #4117 
Run 10177 - failures from ec2west failing to provision, or tests running without the provider actually being configured. Runs locally.
* 56z: 72% pass, unrelated bugs
* 57z: 54% pass, unrelated bugs
* Upstream: 67% pass, unrelated bug
> [RFR] Update Stack use, include provider for __init__

- cfme/tests/infrastructure/test_vm_power_control.py
Removing tests for power control using REST API that are superseded by tests in `cfme/tests/cloud_infra_common/test_power_control_rest.py` that do the same for both "from_detail" and "from_collection".
**PRT:** nothing to test since this PR is only removing tests.
> [1LP][RFR] remove redundant TestPowerControlRESTAPI tests

- widgetastic_manageiq.py
- widgetastic_patternfly.py
1. Two widgetastic views representing View Selector control are prepared. These are used to change view on many pages like Provider, Provider Details, VMs, etc.
One view ItemsToolBarViewSelector consists of buttons ("Grid View", "Tile View", "List View") and present on such pages like Infrastructure Providers.
Second view DetailsToolBarViewSelector contains two buttons ('Summary View', 'Dashboard View') and can be found on Provider Details page.
I haven't seen any other View Selector except there two.
I tested the views on Infra Providers and Infra Provider Details pages.
> [1LP] [RFR] widgetastic view control

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
__Fixing__ 
Navigation got screwed up when the widgetastic stuff got added.
Forms were not being provided correct data from yamls
__Extending__ 
Replaced Template JSON from DynamoDb (which is expensive) with plain old fashion test-asdf1243 which also allows the cleanup script to function properly against these VMs and not leave databases all over the place.
__NOTE__
This PR is not intended to fix everything.  It's simply to get the module back in service so that other broken items can be fixed in a timely manner.  The current version of this module in integration_tests CANNOT possibly work in any manner due to the above referenced fixes.
{{pytest: cfme/tests/services/test_provision_stack.py::test_provision_stack -v --use-provider ec2 }}
> [1LP] [RFR] Fixed Navigation, Replaced DynamoDB, Fixed bad forms

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
Fixing provider selection in `test_rest_services.py` to avoid fails like
```
def service_data(request, rest_api, a_provider, dialog, service_catalogs):
"""
The attempt to add the service entities via web
"""
template, host, datastore, iso_file, vlan, catalog_item_type = map(
>           a_provider.data.get("provisioning").get,
('template', 'host', 'datastore', 'iso_file', 'vlan', 'catalog_item_type'))
E       AttributeError: 'NoneType' object has no attribute 'get'
cfme/rest/gen_data.py:137: AttributeError
```
See https://github.com/ManageIQ/integration_tests/issues/4114
I hope I understood how `testgen` is working and that it's not necessary to use it in this module as no tests are parameterized with provider.
> [1LP] [RFR] Fix provider selection in test_rest_services.py

- cfme/tests/services/test_rest_services.py
Adding BZ check to workaround the issue reported in https://bugzilla.redhat.com/show_bug.cgi?id=1414881 and leaving the test useful.
{{pytest: cfme/tests/services/test_rest_services.py -v -k TestOrchestrationTemplatesRESTAPI --long-running}}
> [1LP] [RFR] fix test_delete_orchestration_templates test

- cfme/infrastructure/provider/openstack_infra.py
Tiny fix to allow the type_name to be compatible with entrypoints
**Note** Tests will fail until the yaml is updated also, nothing I can do about this. #ChickenAndEgg!
> [RFR] Change to allow entrypoints PR to work

- cfme/services/catalogs/orchestration_template.py
- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
- data/orchestration/aws_vm_template.json
- data/orchestration/azure_vm_template.json
- data/orchestration/openstack_vm_template.data
- utils/path.py
__Fixing__ 
https://projects.engineering.redhat.com/browse/RHCFQE-1693
Cleanup was busted.  Someone was trying to run a method on a string
https://projects.engineering.redhat.com/browse/RHCFQE-1712
Azure dying at template create
and
__Extending__ 
https://projects.engineering.redhat.com/browse/RHCFQE-1750
Extracted data to separate files as request in PR
Fixed all the missing Azure stack data entries
Fixed all the missing form field entries.
{{pytest: cfme/tests/services/test_provision_stack.py::test_provision_stack -v --use-provider azure }}
> [1LP][RFR] Refactored orchestration templates, fixed azure issues

- cfme/tests/services/test_rest_services.py
Adding new test for testing parent service functionality using REST API.
**PRT:**
http://10.16.4.32/trackerbot/pr/run/10317 is good looking, also tested locally.
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running -k TestServiceRESTAPI}}
> [1LP][RFR] REST API tests for parent service

- cfme/tests/infrastructure/test_providers.py
* refactoring existing REST API custom attribute tests (these were one of my first tests and I don't like them anymore :)
* adding new tests for testing adding "section" with bad value
{{pytest: '''cfme/tests/infrastructure/test_providers.py::TestProvidersRESTAPI'' -v'}}
> [1LP][RFR] REST API tests for custom attributes refactoring and new tests

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
Update test_retirement.test_set_and_unset_retirement_date_tomorrow, move to test_unset_retirement_date.
I'm scoping this commit for the changes that I would like to make to the test generation and fixtures.
I will address test updates, additions, fixes, etc in a separate commit to keep them reasonable in size. That being said I'm testing against all providers here for a baseline.
Various failures from timeouts during wait, azure missing a template, VM not found on provider.
Increased wait time for retirement in new commit, and covered an upstream change to the flash message. Otherwise I would prefer to leave additional test fixes to a 2nd PR to limit size/scope.
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py -v --long-running --use-provider complete }}
> [1LP][RFR] Update cloud_infra_common.test_retirement, ProviderFilter

- cfme/common/vm.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_delete_infra_object.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_host_drift_analysis.py
- cfme/tests/infrastructure/test_host_provisioning.py
- cfme/tests/infrastructure/test_individual_host_creds.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/openstack/infrastructure/test_hosts.py
Modify calls to instantiate to include a provider object if available
Intent is not to modify behavior at this point but to add provider as an argument for Host constructor and to pass it where available in the current code.
Failures unrelated to this specific change, but in general a very low pass rate for the included tests.
FIXES #4137
> [1LP][RFR] Update cfme.infra.host, add provider arg

- cfme/tests/test_rest.py
* checking http status of REST API requests where it makes sense
* grouping tests into classes
* adding brief description + metadata where missing
* spliting `test_*_delete_*` tests into variants `from_detail` with 'post' and 'delete' parameters and `from_collection` (where just POST is supported)
**PRT:**
unrelated failures during vm setup - `URLError: <urlopen error [Errno 104] Connection reset by peer>`
> [1LP][RFR] check http statuses and move tests into classes

- cfme/common/__init__.py
- cfme/containers/provider/openshift.py
- cfme/tests/containers/test_static_custom_attributes.py
{{pytest: cfme/tests/containers/test_static_custom_attributes.py -v --use-provider cm-env1 }}
> [1LP][RFR] Custom attributes - new tests

- cfme/fixtures/cli.py
- cfme/test_framework/sprout/client.py
- cfme/tests/cli/test_appliance_cli.py
- conftest.py
- fixtures/appliance.py
- utils/appliance/__init__.py
- utils/log_validator.py
Moved fixtures such as sprout provisioning, so new tests can call them rather then adding additional fixtures to each file.
> [RFR] Moved fixtures and adding new test coverage for appliance_console_cli

- scripts/ec2cleanup.py
Instance cleanup is done in cleanup_old_vms, refactor this script to just cleanup the IP's and volumes.
Tabulate the output data
I've tested script locally with success, though there was nothing to cleanup on the providers.
This is executed by the Jenkins 'cleanup-ec2' job.
> [RFR] Refactor ec2cleanup, remove instance cleanup

- cfme/control/explorer/policies.py
{{pytest: -v -k 'test_action_start_virtual_machine_after_stopping' --long-running --use-provider vpshere55}}
__Fixing__ assigning actions to events in policies.
> [1LP][RFR] Fix assigning actions to events in policies

- cfme/tests/configure/test_default_filters.py
'Global Filters' is no longer selectable. So, I removed it from the navigation.
> [WIPTEST] fixed two wrong navigate destinations

- utils/browser.py
* browser _is_alive function was silently killing the alert this left
some navigations on the wrong page, we shouldn't assume we can just
close the alert without creating some kind of havoc. Raising a new
kind of havoc just seems silly, so for now, we just let the original
havoc wreak.
{{pytest: cfme/tests/infrastructure/test_infra_quota.py --long-running --use-provider complete}}
> [RFR] Unexpected Alert Change

- cfme/rest/gen_data.py
- cfme/tests/infrastructure/test_rest_templates.py
* tests fix:
These tests often failed with errors like
`E           ValueError: No such 'vms' matching query {'name': 'test_rest_vm_CwrY'}!`
The reason is that the `mark_vm_as_template` function tried to preserved the original vm, which doesn't work on some providers and the vm is destroyed.
* "delete" tests expanded to test both POST and DELETE methods
There is a bug that prevents testing of delete with POST. I created two separate tests instead of one with parameters, because this way I'm able to block the test before fixtures are resolved (as opposed to `if BZ(...): pytest.skip(...)` for the affected test variant).
* add http response status checks
**PRT:**
tested on vsphere55 because of timeouts on rhevm36
{{pytest: cfme/tests/infrastructure/test_rest_templates.py -v --use-provider …
> [1LP][RFR] fix creating templates in test_rest_templates

- cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k TestProvidersRESTAPI}}
> [1LP][RFR] check response status code in REST API tests for custom attributes

- cfme/tests/test_rest.py
Adding test scenario that makes several automation requests in parallel, simulating user doing e.g.
```
curl <request1> &
curl <request2> &
...
```
> [1LP][RFR] create automation requests in parallel

- cfme/middleware/domain.py
- cfme/tests/middleware/server_methods.py
- cfme/web_ui/mixins.py
* Domain name is shown "Unnamed Domain" if not configured.
* Stopped Domain mode servers do not have Product field.
* There are UI element structure changes for Tags.
{{pytest: cfme/tests/middleware/test_middleware_tags.py -v --use-provider hawkular}}
> [1LP][RFR] Fixed failing middleware tests, caused by UI changes.

- cfme/tests/cloud/test_provisioning.py
Adding check that the http status code of the REST API response was "200".
{{pytest: cfme/tests/cloud/test_provisioning.py --use-provider gce_central -v -k test_provision_from_template_using_rest}}
> [1LP][RFR] check response status code in test_provision_from_template_using_rest

- cfme/tests/infrastructure/test_rest_automation_request.py
* adding tests testing "approve" and "deny" actions
* refactoring existing test
* HTTP response status checking
{{pytest: cfme/tests/infrastructure/test_rest_automation_request.py -v --use-provider scvmm2016}}
> [RFR] add automation_request REST API tests

- cfme/tests/infrastructure/test_provider_discovery.py
- utils/appliance/__init__.py
The provider.exists call was always false because the discovered provider doesn't have a matching name.
Added IPAppliance.managed_provider_names and used it to validate that each discovered provider's IP address was in a managed provider's name.
Tested locally against 5.6.4 and 5.7.1.1
> [1LP][RFR]Fix 57z test_provider_discovery

- cfme/tests/cloud/test_providers.py
Update credentials kwargs for gce form
{{ pytest: cfme/tests/cloud/test_providers.py -v --long-running -k test_provider_add_with_bad_credentials --use-provider gce_central }}
* 5.6 failure is due to a failure to connect to sprout appliance. Tests passed locally, re-running
> [RFR][1LP] Fix test_providers.test_prov_add_with_bad_creds

- cfme/tests/test_utilization_metrics.py
With the existing code and the  the condition checking before host_rising or vm_rising can be set to 
True ,this exception would be occasionally thrown.
Timed out waiting for metrics to be collected"
Since we just want to make sure metrics are being collected for VMs and hosts, the condition checking made through this PR should suffice.
> [RFR][1LP] Updating metrics collection fixture

- cfme/control/explorer/actions.py
- cfme/tests/control/test_actions.py
{{pytest: -v -k 'test_action_untag' --long-running}}
__Fixing__ test_action_untag. Action class didn't have `remove_tag` attribute.
> [RFR]Fix for test_action_untag

- cfme/tests/intelligence/reports/test_crud.py
check HTTP response status code
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k "test_run_report or test_import_report"}}
> [RFR][1LP] check response status code in test_crud

- cfme/common/vm.py
- cfme/tests/automate/test_common_methods.py
- cfme/tests/cloud_infra_common/test_retirement.py
- utils/timeutil.py
Some fairly heavy refactoring of the existing tests to fix some versioning issues, some assertion/verification issues, and to remove a really-bad-idea:tm:  `existing_vm` fixture.
* Make util.timeutil.parsetime format strings public
* Use the public parsetime format strings to define a version-picked class constant `RETIRE_DATE_FMT`
* Modify common.vm.BaseVM.retirement_date to not parse the retirement date in the UI and return as-is so that tests may verify it
* Use the classes's constant in test methods to generate a correctly formatted date for given offset
* Separate methods for verifying retirement state and retirement date
* Add tier marking to test cases
Re-running with set_retirement_date unblocked for 5.7.  Last run was successful with an unrelated upstream failure.
{{ pytest: …
> [1LP][RFR] Update test_retirement, remove existing_vm fixture

- cfme/rest/gen_data.py
- cfme/tests/configure/test_tag.py
* refactoring
* test also DELETE method
* reference categories with all supported means (id, href, name)
* add metadata where missing
{{pytest: cfme/tests/configure/test_tag.py -v -k TestTagsViaREST --use-provider rhevm36}}
> [RFR] refactoring; check response status code for test_tag

- cfme/tests/cloud/test_cloud_events.py
- cfme/tests/cloud_infra_common/test_events.py
- cfme/tests/control/test_alerts.py
- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_vm_power_control.py
- cfme/tests/services/test_myservice.py
- cfme/tests/services/test_service_catalogs.py
- fixtures/events.py
- fixtures/soft_assert.py
- utils/appliance/__init__.py
- utils/events.py
1.  added new azure events tests
2. moved event listener from fixture/events to utils/events and updated it
3. changed register_event fixture to support all event fields
4. updated all tests where register_event fixture was used.
P.S. this is the intermediate solution until everything is moved to collections. Afterwards, all objects like vms or providers will subscribe to event stream and provide all the events relevant to those objects.
related PRs: https://github.com/ManageIQ/wrapanapi/pull/87 , https://github.com/ManageIQ/wrapanapi/pull/75
{{pytest: --long-running cfme/tests/cloud_infra_common/test_events.py  cfme/tests/distributed/test_appliance_replication.py cfme/tests/infrastructure/test_host_analysis.py …
> [1LP][WIPTEST] new azure events and event listener

- cfme/tests/cloud/test_instance_power_control.py
check HTTP response status code
{{pytest: cfme/tests/cloud/test_instance_power_control.py -v -k rest}}
> [RFR][1LP] check response status code for test_terminate_via_rest

- cfme/tests/infrastructure/test_vm_retirement_rest.py
* refactoring
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py -v --use-provider rhevm36}}
> [1LP][RFR] check response status code in test_vm_retirement_rest

- cfme/rest/gen_data.py
- cfme/tests/cloud/test_providers.py
moving arbitration_profiles into gen_data
{{pytest: cfme/tests/cloud/test_providers.py -v -k REST}}
> [RFR] move arbitration_profiles to gen_data

- scripts/apishow.py
* add support for subcollections
* add possibility to add coverage info taken from cfme log file to each action (handy for review what's tested / automated)
Output example
```
...
=======
* users
Collection actions:
* edit OK
* query OK
* create OK
* delete OK
Collection entity actions:
* edit OK
* delete
POST OK
DELETE OK
...
```
with "OK" where the action is covered.
It's a standalone script, so PRT isn't necessary.
> [RFR][1LP] add support for subcollections and coverage info to apishow.py

- cfme/configure/configuration/__init__.py
- utils/appliance/__init__.py
* It appeared as if the get_yaml_config was being called way too often
in multiple places however it now looks it was just the role matching
calls that were the predominant cause. Everything else appears to be
cached already.
* Added a new is_storage_enabled method on the appliance object
* Use this when getting the roles
> [1LP][RFR] Optimize yaml config

- utils/browser.py
* If browser was None, then there would be an error on exiting the script
> [1LP][RFR] Fixed browser closing error

- cfme/tests/services/test_service_catalogs.py
check HTTP response status code
PRT:
on 5.8 and upstream, in cfme/services/catalogs/catalog.py:168 the `navigate_to(self, 'Add')` is not navigating to 'Add' for some reason. In any case it's not an issue that is supposed to be solved in this PR.
{{pytest:  cfme/tests/services/test_service_catalogs.py -v -k rest --long-running}}
> [1LP][RFR] check response status code for test_order_catalog_item_via_rest

- cfme/infrastructure/provider/__init__.py
adding checks for paginator to avoid BZ 1422449 block and adding 'Summary View' to Details (it was added in 5.8)
This is mainly for 5.8 - as InfraProviders received Dashboard/Summary views in provider details.
There's a NEEDINFO regarding CloudProviders in that BZ .  It is always good to have  additional checks
> [1LP][RFR]Fix and resetter for InfraProvider Details 

- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/infrastructure/resource_pool.py
- cfme/middleware/provider/hawkular.py
- utils/appliance/__init__.py
- utils/providers.py
This is required for Sprout provider scaenging functioning again, because managed_providers now returns crud objects which do not work by default on Sprout because Sprout's base_url is None, therefore get_or_create_current_appliance does not work.
> [1LP][RFR] utils/providers.py: Accept and propagate appliance= param

- widgetastic_manageiq.py
Pass parent attribute to browser.elements so that only checkboxes under
the given search_root parameter are discovered.
FIXES #4303 
Note that selected_text() has an issue as well that this does not resolve (at least specific to the Configure/Tasks screen)
> [1LP][RFR] Update widgetastic_miq, CheckboxSelect.checkboxes

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/configure/test_access_control.py
- setup.py
- utils/providers.py
This is a large change to the way providers are registered now
* Removed the add_provider_type method from the BaseProvider class
* Removed the add_base_type method from the BaseProvider class
* Added base_types as a function to the cfme.common.provider module
* Added provider_types as a function to the cfme.common.provider module
* Added entrypoints to the setup.py file
* Added load_setuptools_entrypoints to the utils.providers module
> [1LP][RFR] Entrypoints addition

- cfme/automate/__init__.py
- cfme/automate/explorer/__init__.py
- cfme/tests/automate/test_class.py
- cfme/tests/automate/test_domain.py
Automation results:
```
Appliance's streams: [5.8, downstream]
cfme/tests/automate/test_domain.py::test_domain_crud[enabled] PASSED
cfme/tests/automate/test_domain.py::test_domain_crud[disabled] PASSED
cfme/tests/automate/test_domain.py::test_domain_delete_from_table PASSED
cfme/tests/automate/test_domain.py::test_duplicate_domain_disallowed PASSED
cfme/tests/automate/test_class.py::test_class_crud[plain] PASSED
cfme/tests/automate/test_class.py::test_class_crud[nested_existing] PASSED
cfme/tests/automate/test_class.py::test_schema_crud[plain] PASSED
cfme/tests/automate/test_class.py::test_schema_crud[nested_existing] PASSED
cfme/tests/automate/test_class.py::test_duplicate_class_disallowed[plain] FAILED
cfme/tests/automate/test_class.py::test_duplicate_class_disallowed[nested_existing] …
```
> [1LP][RFR] Fix Automate tests for 5.8

- cfme/cloud/instance/__init__.py
* Instances were inheriting the base VM class' None for the TO_OPEN_EDIT
configuration step and hence were never getting to the right page
* This commit makes the link work, however an issue has been opened to
replace all this with the navmazing step
> [RFR] Fixed the open_edit method for instances

- cfme/tests/webui/test_splitter.py
* The test navigation for Utilization at least, relies on having access
to the zone attribute which the base class doesn't have
> [RFR] Fixed splitter test to use real Server instance

- cfme/base/ui.py
* Upstream extended the nav and has now seemingly reverted that change
{{pytest: -k test_domain_present}}
> [WIPTEST] Fixed E release on upstream

- cfme/base/ui.py
- cfme/configure/tasks.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_host_drift_analysis.py
This is working navigation and widget interaction for the tasks filters on each tab.
I would like to keep the scope of this PR small, and do Collections and moving all of the methods into proper TasksCollection & Tasks classes in another.
_Can ignore failures_
There is a failure in `test_host_drift_analysis` that occurs at a soft_assert on `test_host.equal_drift_results`.  The fix isn't obvious to me, and after spending a bit of time trying to debug I'm going to leave it off this PR. 3 failures, none to do with tasks widget changes.
The fix for the test failures here are in PR #4265, thanks @niyazRedhat
> [1LP][RFR] Widgetastic Elements for Configure.tasks

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/test_db_restore.py
- fixtures/log.py
- fixtures/provider.py
- sprout/appliances/tasks.py
- utils/appliance/__init__.py
- utils/appliance/implementations/ui.py
- utils/tests/test_ipappliance.py
This adds mapping between our classes and MiQ classes so that when we call `clear_providers` to delete for example all `InfraProviders`, it will look for all `InfraManager` providers and remove them. Until now, we only deleted known managed providers (part of this PR is also renaming the method to make its function 100% clear from the name) which is not sufficient when those are renamed. Same with checking with `.exists`.
It also removes `clear_providers_by_class` and keeps only `clear_providers` which becomes a `classmethod` -> the providers removed depend on which class you call it from. `InfraProvider.clear_providers()` will remove all infra providers, `CloudProvider.clear_providers()` will remove all cloud providers...
{{pytest: -k test_provider}}
> [1LP][RFR] Remove providers through rest & fix provider exists check for renamed providers

- scripts/template_upload_all.py
CFME 5.8 brings rhevm qcow2 images, which were erroneously matching this pattern, causing template upload to fail.
Explicitly match the rhevm.ova file, tested locally and the regex matches the correct image for 5.8.
> [NOTEST] Update template_upload_all for rhevm.ova image

- cfme/common/vm.py
wait_candu_data_available() didn't refresh vm details screen. This PR fixes it.
> [RFR] Fix wait_candu_data_available()

- cfme/tests/openstack/infrastructure/test_host_power_control.py
Set uncollection for host power control tests as they are relevant only for 5.7 and higher
> [RFR] uncollect infra host power tests for old version

- cfme/configure/configuration/__init__.py
- cfme/fixtures/base.py
- cfme/tests/cli/test_evmserverd.py
- cfme/tests/test_login.py
- conftest.py
> [1LP][RFR] Added appliance fixture

- cfme/configure/configuration/__init__.py
We must wait when new roles will be applied in the appliance. Otherwise if we call `get_server_roles()` immediately after `set_server_roles()` we will get not actual server roles. It should affect on all tests where default roles are changed. We have a hook which disables websocket server role https://github.com/ManageIQ/integration_tests/blob/master/conftest.py#L66. If we change server roles `get_server_roles()` will be called almost immediately in `ensure_websocket_role_disabled()`.
> [RFR] Fixed nasty bug in set_server_roles()

- cfme/rest/gen_data.py
- cfme/tests/test_rest.py
moving arbitration_rules data generation to `gen_data.py`
**PRT:**
due to a PRT issue no tests were run on upstream
{{pytest: cfme/tests/test_rest.py -v --use-provider vsphere6-nested}}
> [1LP][RFR] move arbitration_rules data generation to gen_data

- cfme/tests/cloud_infra_common/test_power_control_rest.py
Fixing the test_power_control_rest tests for scvmm provider.
PRT:
some test still randomly timeout on PRT even though I eventually increased the timeout to 4000 sec (66min!)
I've tried many times to have all tests passed, but I can't beat PRT :( Results combined from multiple runs will have to do.
downstream-56z: http://10.16.4.32/trackerbot/pr/run/10710#sN6Vs8lA
downstream-57z: http://10.16.4.32/trackerbot/pr/run/10800#UqvzTpPd
upstream: http://10.16.4.32/trackerbot/pr/run/10630#phezGfFH
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py -v --use-provider scvmm2016}}
> [1LP][RFR] fix test_power_control_rest for scvmm provider

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
* tests fixes
* refactoring
* check HTTP response statuses
**PRT:**
(updated 14:17 10.3.2017)
See run http://10.16.4.32/trackerbot/pr/run/11160
The only failed test is "TestServiceTemplateRESTAPI.test_delete_service_template_post" because BZ 1427338 is no longer blocker but the fix is not available in the tested version - this was solved by last commit.
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running --use-provider vsphere6-nested}}
> [1LP][RFR] test_rest_services fixes and refactoring

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_ntp_server.py
- utils/appliance/__init__.py
- utils/perf.py
Removing an older option that is no longer present in 5.6+
Removed get_yaml_file() as it is no longer used
> [1LP][RFR] Removed older option and simplified codebase

- cfme/web_ui/form_buttons.py
In 5.8 buttons are now wrapped in `miq_button` that contains the alt text we want. In button tag itself there's no alt, but we can get the text using `text()`.
> [WIPTEST][1LP] fixing button locators in 5.8

- cfme/tests/test_utilization.py
- cfme/tests/test_utilization_metrics.py
Fixes the tests and should also speed them up, as a by-product, since it's no longer going to run `clean_setup_provider` in func scope.
Tested locally; there were some skips and some failures but no more fixture setup errors.
> [RFR] Fix scope mismatch err

- cfme/cloud/availability_zone.py
- cfme/tests/cloud/test_cloud_timelines.py
1. fixed typo in cloud_timelines test
2. fixed azone issue, when Details destination didn't select appropriate azone
3. added OpenStack provider
{{pytest: --use-provider=azure cfme/tests/cloud/test_cloud_timelines.py}}
> [1LP][RFR]cloud timelines. missed changes

- cfme/cloud/tenant.py
- cfme/tests/cloud/test_tenant.py
Continuing #3942 added update test.
In test code a helper refresh provider function, since the delete and update requires a refresh provider before we query the tenant 'All' page
> [1LP][RFR] added update test in tenant CRUD

- fixtures/pytest_store.py
- utils/__init__.py
its abstraction was based on hiding errors and the only usages have better direct implementations
> [RFR] Cleanup: remove property or none

- cfme/middleware/domain.py
- cfme/tests/middleware/test_middleware_provider.py
changed displaying domain name, add provider error message fix
{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_duplicite_provider_creation -v --use-provider hawkular}}
> [1LP][RFR] Fixed failing tests according to new UI changes.

- widgetastic_manageiq.py
Found that when using SummaryTable for cloud.instances widgetastic refactor, and exception was raised because of logger being passed as a kwarg.
> [RFR] Pass args and kwargs in SummaryTable init

- widgetastic_manageiq.py
- widgetastic_patternfly.py
The view change buttons in cfme 56z don't have the proper patternfly markup. Add  Version picking to widgetastic_manageIQ's ItemsToolbarViewSelector
> [1LP][RFR] Patternfly ViewChangeButton widget for 56z

- cfme/tests/containers/test_cockpit.py
- cfme/tests/containers/test_cockpit_button_access.py
{{pytest: cfme/tests/containers/test_cockpit.py -v --use-provider cm-env1 }}
The test verifies the accessibility of the cockpit (Web Console) button on the master node, then logs in to cockpit. It will not work until the single sign-on bug is fixed.
> [1LP][RFR]Cockpit button accessibility/cockpit login

- cfme/tests/infrastructure/test_advanced_search_host.py
Tests were not running because of ScopeMismatch, so I changed scope from module to function.
> [1LP][RFR]Changed scope from module to function in hosts advanced search tests

- cfme/tests/test_rest.py
The test_query_simple_collections updated with collections added in 5.8.
{{pytest: -v -k test_query_simple_collections}}
> [1LP][RFR] update test_query_simple_collections with collections new in 5.8

- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/rhevm.py
Latest MIQ release adds two new form elements when configuring a rhevm infra provider:
* Verify TLS
* CA Certs
Cleanup some old form definitions that aren't needed for CFME 56z+, and support new fields.  Use 'None' values for versions lower than CFME 5.8 so that the form fill ignores them and doesn't generate exceptions for missing fields.
Tested locally against 56z, 57z, 58z
{{ pytest: cfme/tests/infrastructure/test_providers.py -k test_provider_crud --use-provider rhevm36 --long-running  }}
56z: Passed rhevm CRUD
57z: Passed rhevm CRUD
upstream: failed after the create, provider was added to appliance successfully.  outside of this scope. 
FIXES RHCFQE-2208
> [1LP][RFR] Fix infra.provider.rhevm, TLS support in create

- cfme/tests/test_rest.py
Streamlined TestArbitrationSettingsRESTAPI tests by moving settings creation to fixture.
{{pytest: -v -k TestArbitrationSettingsRESTAPI}}
> [1LP][RFR] streamline TestArbitrationSettingsRESTAPI tests by moving settings creation to fixture

- cfme/infrastructure/datastore.py
- cfme/infrastructure/networking.py
- cfme/optimize/utilization.py
- cfme/services/catalogs/service_catalogs.py
- cfme/services/workloads.py
- cfme/tests/webui/test_splitter.py
Added Utilization, InfraNetworking navigate_to.
Fixed uncollectif and blockers for test_pull_splitter_persistence
Added parametrized Bottlenecks, Utilization, InfraNetworking and deleted TemplatesImages.
Fixed Datastore navigate_to when there are no items in datastore and paginator is hidden.
> [1LP][RFR] Revisited test_pull_splitter_persistence

- cfme/services/catalogs/catalog_item.py
Some tests that are using `CatalogItem.create()` fails with
``E       AttributeError: 'FakeObject' object has no attribute 'label'``
or
``E           NoSuchElementException: Message: Element //select[@id='st_prov_type'] not found on page.`` (caused by not being at the correct page as a result of this bug)
Due to recent change in https://github.com/sshveta/cfme_tests/blob/0cced52f9442538272a2d503424422a1c2c18bcd/cfme/services/catalogs/catalog_item.py#L147
this needs to be changed as well.
> [1LP][RFR] fix for AttributeError: 'FakeObject' object has no attribute 'label'

- cfme/tests/test_rest.py
Adding new REST API test for resources hiding.
{{pytest: -v -k test_resources_hiding}}
> [1LP][RFR] new REST API test for resources hiding

- conftest.py
removes deprecated pytest options we used way back
> [1LP][RFR] remove the deprecated --tracer/--no-tracer pytest option

- cfme/tests/infrastructure/test_providers.py
Changing the way how custom attributes are deleted after test is finished. Now it's consistent with how it's done for entities in other collections.
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k TestProvidersRESTAPI}}
> [1LP][RFR] better way to cleanup custom attributes

- cfme/tests/intelligence/reports/test_canned_corresponds.py
__Adding tests__ for canned reports. At the moment, there are no tests checking content of canned reports.
Tests will be added continually to this PR.
Tests are suffering of __live environment changing__ too rapidly. That's why test won't pass checks. At the moment, we are in need of __static__ environment for testing this.
test_operations_vm_on:
Path to test: Operations > Virtual Machines > Online VMs (Powered On)
Queue report, get data from DB. Compare. _(suffering of moving sand on live providers)_
test_datastores_summary:
Path to test: Configuration Management > Storage > Datastores Summary
Queue report, get data from DB. Compare.
{{pytest: -k 'test_datastores_summary' --use-provider vsphere55 --use-provider scvmm --use-provider rhevm36 …
> [1LP][RFR] Canned reports tests

- cfme/tests/cloud/test_provisioning.py
* while working on making the test work on 5.6 I accidentally removed also the code limiting the test scope to EC2 provider only. This PR is adding the check back.
* sometimes `availability_zone_id` is missing in cloud_subnets and the test fails - making it more robust
{{pytest: -v -k test_ec2_manual_placement_using_rest --use-provider ec2west}}
> [1LP][RFR] fix the test scope of test_ec2_manual_placement_using_rest

- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_hawkular_crud -v --use-provider hawkular}}
> [1LP][RFR] Added new field 'sec_protocol' for Middleware Provider for 5.8 and upstream versions.

- cfme/automate/provisioning_dialogs.py
It was pointed to old menu
{{pytest: cfme/tests/automate/test_provisioning_dialogs.py -v --long-running}}
> [RFR] Fix Provisioning Dialogs navigation

- fixtures/parallelizer/remote.py
- utils/log.py
this switches logging in the worker processes to use a logfile prefixed with the process name
while a hack this allows much better comprehension of the logfiles
> [1LP][RFR] logging: start to use one logfile per parallel worker

- widgetastic_patternfly.py
BootStrapSwitch control is almost equal to checkbox but when I try to use CheckBox or other existing controls I experience different issues like I can change state but can't read value or vise versa.
After discussion with @mfalesni, we decided to create new widget instead of trying to change originial widgetastic's Checkbox or Input widgets.
It has been tested and used in PR #4387
It has been tested only against 5.7 but I'll fix all issues for 5.6/5.8 if I face somethying.
> [1LP][RFR] Widgetastic BootstrapSwitch control

- cfme/configure/settings.py
- cfme/tests/configure/test_timeprofile.py
Add button was changed with Save button in 5.8 so this is fix for it.
> [1LP][RFR]Fixed timeprofile tests for 5.8 version

- cfme/infrastructure/provider/virtualcenter.py
Many tests are now failing with
```
>       del deploy_args['username']
E       KeyError: 'username'
cfme/infrastructure/provider/virtualcenter.py:31: KeyError
```
> [RFR][1LP] fix KeyError: 'username' in virtualcenter.py

- widgetastic_manageiq.py
Some views like Manage Policies have DynaTree control with checkbox in 5.6.
Currently checkbox is not clicked when DynaTree's fill is called.
This small patch fixes that.
I didn't spend time implementing methods like check/uncheck/is_checked/etc since DynaTree is deprecated. I can make a better fix if it makes sense.
Limitation: fill doesn't check whether checkbox is already checked/not checked.
> [1LP][RFR] DynaTree fix to click checkbox if leaf contains checkbox

- cfme/base/ui.py
Rescoping to just fix browser quit, ssh_client fixtures fixed in PR #4451 
This was uncovered during testing of PR #4451 changes. In CFME 5.7.2 there was an overlay covering the login screen, triggering the call to `quit()` instead of `utils.browser.quit()`
FIXES RHCFQE-2293
> [1LP][RFR] Fix Browser quit() call in base.ui.LoginPage

- cfme/tests/control/test_actions.py
{{pytest: -v -k 'test_action_power_on_logged' --long-running --use-provider=vsphere6-nested}}
`ssh_client` fixture was removed and in this PR that fixture has been replaced by `appliance.ssh_client`.
> [1LP][RFR] Removed ssh_client fixture from test_actions.py

- cfme/containers/provider/openshift.py
Provide a default for sec_protocol from prov_config in case the key doesn't exist.
This is causing exceptions in upstream tests on Jenkins at the moment. Missing a YAML update @jkrocil?
upstream failure is an ssh_client assertion that's not at all related to this. all other smoke tests pass
> [RFR][1LP] Fix exception in containers.provider.openshift

- cfme/tests/cli/test_appliance_console.py
This is causing failures in template testing for upstream.
@lcouzens should check this out
{{ pytest: cfme/tests -m smoke --use-provider default }}
> [RFR][1LP] Update test_appliance_console, grep for MIQ+CFME

- fixtures/parallelizer/__init__.py
i couldn't locally replicate the conditions
this pr is in order to handle messages from workers we already disengaged with
> [RFR] parallelizer: handle messages from terminated workers

- cfme/tests/infrastructure/test_rest_automation_request.py
Enhancement to make sure that approval_state is not changed (request is automatically approved) for pending requests.
**PRT:** (before comment change)
http://10.16.4.32/trackerbot/pr/run/11691
{{pytest: -v -k test_create_pending_requests}}
> [RFR][1LP] automation request REST API - make sure approval_state is not changed

- cfme/tests/test_rest.py
New test for resource sorting by attributes using REST API.
{{pytest: -v -k test_sorting_by_attributes}}
> [1LP][RFR] resources sorting by attributes using REST API

- cfme/tests/cloud/test_instance_power_control.py
New REST API tests for /api/instances collection.
{{pytest: --long-running --use-provider rhos7-ga -v -k TestInstanceRESTAPI}}
> [1LP][RFR] new REST API tests for /api/instances

- cfme/fixtures/base.py
- conftest.py
this also tries to use the "appliance" fixture whenever possible for the moved code
> [1LP][RFR] move appliance fixup fixtures to fixtures.appliance

- cfme/tests/test_rest.py
New REST API tests for validation of file type and file content when adding new picture.
{{pytest: -v -k test_add_picture_invalid cfme/tests/test_rest.py}}
> [1LP][RFR] new REST API tests for new pictures validation

- cfme/tests/test_rest.py
New REST API tests for checking that the OPTIONS http method on Hosts and Clusters collection returns node_types.
{{pytest: -v -k test_http_options_node_types cfme/tests/test_rest.py}}
> [1LP][RFR] new REST API tests for Hosts and Clusters collections options

- cfme/tests/control/test_basic.py
Small refactoring in basic control tests. We should check types, not strings.
> [1LP][RFR] Strings comparing must be replaced by type checking

- cfme/tests/services/test_rest_services.py
New tests for copying orchestration templates using REST API.
{{pytest: -v --long-running -k copy_orchestration_templates}}
> [1LP][RFR] new tests for copying orchestration templates using REST API

- cfme/tests/cloud/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning.py
__Extending__ cloud provisioning asserts to check request status because wasn't doing that
and
__Removing__  LDAP auth setup as it's unused during these tests, which saves time
{{pytest: cfme/tests/ "-k test_provision_from_template" --use-provider ec2west --use-provider azure  --long-running}}
> [1LP][RFR]Extending cloud provisioning asserts + removing unused ldap setup

- cfme/containers/provider/__init__.py
- cfme/fixtures/vporizer.py
- cfme/intelligence/reports/reports.py
- cfme/tests/containers/test_reports.py
- conftest.py
{{pytest: cfme/tests/containers/test_reports.py -v --use-provider cm-env1}}
Added Container reports tests
- Added fixture vporizer to grabbing and manipulating VPOR db table. will be used later in more tests.
- Fix ContainerTestItem.pretty_id so support also objects without __name__ attrribute
> [1LP][RFR] Container reports tests

- cfme/tests/test_utilization_metrics.py
Fixing AttributeError for test_utilization_metrics.py. Tests fail due to 'db' attribute was duplicated for Db object.
{{ pytest: cfme/tests/test_utilization_metrics.py -k test_raw_metric_vm_memory --long-running
}}
> [1LP][RFR] Utilization_metrics tests AttributeError fix

- cfme/test_framework/appliance_police.py
- conftest.py
this pr is part of the conftest cleanup and moves the appliance police to a own plugin
> [1LP][RFR] move appliance police to a own pytest plugin

- utils/path.py
this is part of the utils move preparation,
by using imp.find_module we get independent of paths
> [1LP][RFR] ensure utils.path is independent of its own location

- cfme/tests/cli/test_appliance_console.py
Wish I had known about this for #4485.
'Enhancement' label ... sure.
{{ pytest: cfme/tests -m smoke --use-provider default }}
> [1LP][RFR] Fix product name setting in test_app_console

- cfme/services/catalogs/service_catalogs.py
- cfme/services/myservice.py
- cfme/tests/services/test_myservice.py
Fixed tree navigation, edited path label for finding 'All services' for 5.8 , and also add catalog step to find service in the tree.   
{{ pytest: cfme/tests/services/test_myservice.py -k test_download_file --long-running}}
> [1LP][RFR]Fix tree navigation in test_myservice.py tests

- cfme/containers/provider/__init__.py
- cfme/tests/containers/test_overview_data_integrity.py
- cfme/tests/containers/test_reload_button_provider.py
{{pytest: cfme/tests/containers/test_reload_button_provider.py -v --use-provider cm-env1}}
{{pytest: cfme/tests/containers/test_overview_data_integrity.py -v --use-provider cm-env1}}
Fixed the image registry issue for CFME 5.7 and 5.8. Image Registry is now included in validate_stats() function, along with other objects. The images are still tested separately.
> [1LP][RFR]Provider reload button/data_integrity image registry fix

- cfme/tests/control/test_bugs.py
{{pytest: -v -k 'test_check_compliance_history' --long-running}}
__Fixed__ scope mismatch in  test_check_compliance_history
> [1LP][RFR] Fixed test_check_compliance_history

- cfme/tests/test_rest.py
new REST API test for checking that OPTIONS http method returns supported subcollections for given collection.
{{pytest: -v -k test_http_options_subcollections cfme/tests/test_rest.py}}
> [1LP][RFR] new REST API test - OPTIONS returns supported subcollections

- fixtures/provider.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py -v --long-running --use-provider complete --provider-limit 1 -s}}
> [RFR] Testgen: Configurable provider limit for setting up providers

- cfme/test_framework/config.py
local test pending, can we print it and put it into a hall of shame
> [RFR] restore conf.runtime property that is used in sprout/artifactor

- cfme/tests/cloud_infra_common/test_power_control_rest.py
* reset is supported on scvmm in 5.8
* more robust checking for power state changes
* make sure we are always using /api/vms and not /api/instances even for cloud providers
**PRT results**:
OK apart from failures to create vm on providers (not these tests faults) and semi-expected `SoftAssertionError`s (timeouts when waiting for change states - this is unreliable hence soft asserts).
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py -v --use-provider scvmm}}
> [1LP][RFR] fix test_power_control_rest for scvmm and make testing more robust

- cfme/cloud/flavor.py
- cfme/exceptions.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
Still testing nav/widgets locally but its a pretty darn simple class.
remove flavor from test_tag objects, mixin needs refactoring for
widgets
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/configure/test_default_views_cloud.py cfme/tests/configure/test_visual_cloud.py --use-provider ec2west --long-running -v }}
added FlavorNotFound to cfme.exceptions
FIXES RHCFQE-2379
> [1LP][RFR] Update cloud.flavor, widgets and views

- scripts/template_upload_all.py
- scripts/template_upload_rhevm.py
- utils/version.py
Fix template_upload_all regex to capture build filenames with '.' in the version.
Also strip the trailing slash when comparing build URL's, to avoid silly failures.
Add verbosity to engine_image_uploader call in template_upload_rhevm to get more status information from the script in the event of a failure.
Changes tested locally against the euwe-2.1 build.
> [RFR] Jenkins Template Tester script updates

- cfme/tests/automate/test_service_dialog.py
- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/services/test_cloud_service_catalogs.py
- cfme/tests/services/test_iso_service_catalogs.py
- cfme/tests/services/test_pxe_service_catalogs.py
- cfme/tests/test_ui_problems.py
UPDATE:
I included tests fixes from https://github.com/ManageIQ/integration_tests/pull/4492 into this PR.
Sorry for the mess, I figured it will be easier to review/merge the PRs if it would be just tests fixes vs framework fixes.
The purpose of this PR is to fix calls to ``CatalogItem()``, ``ServiceCatalogs()`` and ``ServiceDialog.create()``.
This PR fixes **just the calls**, not all the other things that may be broken == tests are not expected to pass in PRT
> [RFR] fixes for service_catalogs

- scripts/dockerbot/pytestbase/post_result.py
* Unicode showing in the output.txt file caused the PRT send commands to
fall over. This guards against that.
> [1LP][RFR] Fixed PRT output

- fixtures/artifactor_plugin.py
I made a mistake - this fixes it, _param_name returns the param_name of the object, not the name of what the parameter should be to access the param_name
> [RFR] Fix the param_getter

- cfme/cloud/instance/azure.py
- cfme/cloud/instance/ec2.py
- cfme/cloud/instance/gce.py
- cfme/cloud/instance/openstack.py
- cfme/tests/cloud/test_instance_power_control.py
The power control tests fail when a deferred_verpick isn't picked on access because its defined for a class constant.
Thanks @mfalesni for the help brainstorming this change!
{{ pytest: cfme/tests/cloud/test_instance_power_control.py --long-running --use-provider azure -k test_power_options_from }}
Failures are either provider setup (GCE and EC2 access down at the moment, rhos7-ga+rhos8 unstable) or a VM not hitting the desired power state in time.
There is an Azure softassert failure against the available power options. Need to consult with FA owner for this. Its outside the scope of my intended fixes here.
> [1LP][RFR] Implement instance ui_powerstates_* as properties

- cfme/tests/cloud_infra_common/test_retirement.py
FIXES RHCFQE-2409
Add parameter to test_set_retirement_date to parametrize the warning interval.
Local tests passed so marking RFR.
Restricting PRT providers because of provisioning failure unrelated to the test.
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py -v --long-running -k test_set_retirement_date --use-provider ec2west --use-provider rhevm36 }}
> [1LP][RFR] Update test_retirement, parametrize warning interval

- utils/appliance/__init__.py
Previously configuration_details returns (None, None, None, None) if two appliances were provisioned from openstack because  server.ipaddress equal to 192.168.x.x
self.guid takes info from /var/www/miq/vmdb/GUID and server.guid from db 
Example with two appliances: 
You can see error in PRT run #12105 for 5.6
And no such error in PRT run with this fix #12110 for 5.6
> [1LP][RFR] appliance's configuration_details workaroud for openstack

- cfme/infrastructure/provider/rhevm.py
Provider type naming is changing all the time, so here's the latest dict that should hopefully work with all versions for some time
> [1LP][RFR]Change provider type for RHV

- cfme/rest/gen_data.py
- cfme/tests/configure/test_tag.py
- cfme/tests/services/test_rest_services.py
* fixes for things that broke after widgetastic conversion
* fixes for stuff that changed in recent 5.8
{{pytest: -v --long-running -k REST cfme/tests/configure/test_tag.py cfme/tests/services/test_rest_services.py}}
UPDATE 4/20:
the failing 'test_assign_unassign_service_template_to_service_catalog' will be fixed in separate PR
> [RFR] fix services tests after widgetastic conversion and recent changes in 5.8

- scripts/template_upload_all.py
- utils/trackerbot.py
Updated regex matchers in utils.trackerbot, missed this regex update when I re-enabled the upstream_euwe stream.
Added block to template upload to set stream name automatically from template name if the stream wasn't provided.  This is so that when templates are added to trackerbot for the first time, they have a stream set.
> [RFR] Update template_upload and trackerbot for streams

- artifactor/plugins/reporter.py
- cfme/tests/test_login.py
- fixtures/artifactor_plugin.py
This ensures requirements are sent to Ostriz
Test are marked with requirements, until now these were not being sent to Ostriz, we need this to be able to start grouping tests in reporting.
> [1LP][RFR] Requirements are now sent to Ostriz

- sprout/appliances/tasks.py
CFME experiences different issues when system time is incorrect.
Sprout currently doesn't fix time sync daemon after provisioning appliances. 
This PR will make sprout run setup for time sync daemon after provisioning.
> [RFR] sprout: setup time sync in appliances after provisioning

- cfme/tests/services/test_iso_service_catalogs.py
- cfme/tests/services/test_pxe_service_catalogs.py
{{pytest: -v --long-running --use-provider rhevm cfme/tests/services/test_pxe_service_catalogs.py }}
These tests will now use the fixture dialog and catalog . Removed extra code .
> [1LP][RFR]Removed extra code

- cfme/tests/infrastructure/test_provisioning_rest.py
Fix test so it respect the expected behavior described in https://bugzilla.redhat.com/show_bug.cgi?id=1437689
{{pytest: -v -k test_create_pending_provision_requests}}
> [1LP][RFR] fix the test_create_pending_provision_requests to respect expected behavior

- cfme/cloud/keypairs.py
- cfme/exceptions.py
- cfme/tests/cloud/test_keypairs.py
Convert cloud.keypairs to widgetastic
Update create/delete methods with some enhancements
Add more CRUD type tests and collect for CFME 5.8.
https://bugzilla.redhat.com/show_bug.cgi?id=1444520
This bug is causing some timeout failures, and I believe is why staleelementexceptions are happening even when it doesn't time out.  wrapping the wait_for after submitting the form in view.flush_widget_cache() calls.
FIXES RHCFQE-2423
> [1LP][RFR] Convert cloud.keypairs to widgetastic

- cfme/containers/provider/__init__.py
- cfme/fixtures/vporizer.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_static_custom_attributes.py
{{pytest: cfme/tests/containers/test_properties.py cfme/tests/containers/test_static_custom_attributes.py -v --use-provider cm-env1 }}
- Fix vporizer values RE extraction
- Fix test_properties
- Fix test_static_custom_attributes
> [RFR][1LP] General test fixes

- cfme/tests/automate/test_rest.py
Replacing the ``rest_api`` fixture with ``appliance.rest_api``
{{pytest: -v -k test_rest_search_automate}}
> [1LP][RFR] remove rest_api fixture from test_rest_search_automate

- cfme/tests/configure/test_rest_access_control.py
* replacing the `rest_api` fixture with `appliance.rest_api`
* edit tests enhancements
{{pytest: -v cfme/tests/configure/test_rest_access_control.py}}
> [RFR][1LP] remove rest_api fixture; enhancements for edit tests

- cfme/tests/control/test_rest_control.py
Replacing the ``rest_api`` fixture with ``appliance.rest_api``
{{pytest: -v cfme/tests/control/test_rest_control.py}}
> [RFR][1LP] remove rest_api fixture from test_rest_control

- cfme/tests/cloud_infra_common/test_power_control_rest.py
Replacing the ``rest_api`` fixture with ``appliance.rest_api``
{{pytest: -v cfme/tests/cloud_infra_common/test_power_control_rest.py}}
> [1LP][RFR] remove rest_api fixture from test_power_control_rest

- cfme/tests/configure/test_tag_category.py
* replacing the ``rest_api`` fixture with ``appliance.rest_api``
* ``test_edit_categories`` enhancements
{{pytest: -v -k TestCategoriesViaREST}}
> [1LP][RFR] remove rest_api fixture from test_tag_category

- cfme/containers/pod.py
- cfme/containers/provider/__init__.py
- cfme/containers/service.py
- cfme/tests/containers/test_configurable_menus.py
- cfme/tests/containers/test_reports.py
- cfme/tests/containers/test_start_page.py
{{pytest: cfme/tests/containers/test_start_page.py  cfme/tests/containers/test_reports.py cfme/tests/containers/test_configurable_menus.py -v --use-provider cm-env1 }}
- Added cfme/tests/containers/test_start_page.py - test_start_page
- Added cfme/tests/containers/test_reports.py - test_container_reports_base_on_options
- Few page match fixes
> [1LP][RFR] More containers tests

- cfme/rest/gen_data.py
I learned that even though the function executed by ``wait_for`` fails, by default the ``wait_for`` doesn't wait unless the returned value is `False` (i.e. not any false value like `None`, empty string, etc.).
Fixing this for `gen_data.py`
{{pytest: -v -k test_vm_scan}}
> [1LP][RFR] fix wait_for calls in gen_data.py

- cfme/tests/control/test_alerts.py
Close of SSH on finishing of test
{{ pytest: cfme/tests/control/test_alerts.py -k  test_alert_timeline_cpu --long-running --use-provider vsphere6-nested }}
> [1LP][RFR] Fixed SSH closing on one test

- cfme/rest/gen_data.py
- cfme/tests/services/test_rest_services.py
Fix for test_assign_unassign_service_template_to_service_catalog
{{pytest: -v --long-running cfme/tests/services/test_rest_services.py}}
> [1LP][RFR] fix the test_assign_unassign_service_template_to_service_catalog test

- cfme/tests/test_rest.py
Replacing the ``rest_api`` fixture with ``appliance.rest_api``
{{pytest: cfme/tests/test_rest.py -v}}
> [1LP][RFR] remove rest_api fixture from test_rest.py

- cfme/cloud/availability_zone.py
- cfme/exceptions.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_visual_cloud.py
Still draft, just structured 'All' view and added toolbar/entities views.
Following @izapolsk structure from providers because its awesome.
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/configure/test_default_views_cloud.py cfme/tests/configure/test_visual_cloud.py -k "Availability" --use-provider default --long-running -v }}
FIXES RHCFQE-2302
Restricted PRT to just run Availability Zone tests instead of everything in the included modules.
Run 12584 is a true positive result.
> [1LP][RFR] Convert clouds.availability_zone to Widgetastic

- fixtures/artifactor_plugin.py
- fixtures/browser.py
- fixtures/log.py
- utils/pytest_shortcuts.py
this fixes a condition that got introduced as pytest switched exception reprs from oldstyle classes to newstyle classes
our internal checks now get a TypeError instead of a AttributeError
i need help in triggering the conditions to see if the code is reached correctly
i reported pytest-dev/pytest#2398 up to pytest, but i expect the upstream solution to be documentation
> [RFR] collect and correct test report longrepr formatting

- utils/browser.py
that return was forgotten in the original code and it took until now to actually hit the condition
fortunately it only exits the thread that was supposed to exit graceful
> [RFR][1LP] browser wharf: actually stop the renew thread if docker_id is None

- cfme/tests/cloud/test_cloud_timelines.py
1. psav mentioned that we have to include rhos provider in cloud timelines tests
2.  timelines is enabled for EC2 in 5.8
> [1LP][RFR] cloud timelines for rhos and ec2 providers

- cfme/tests/containers/test_smart_management.py
{{pytest: cfme/tests/containers/test_smart_management.py -v --use-provider cm-env1 }}
Before the test starts the code remove all the previous smart management configuration
Add Smart management test for the following objects:
1) Template
2) Image Registry
3) Image
4) Node
5) Pod
6) Project
7) Containers Provider
The test choose random instance of object and do the following for each:
1) Navigate to smart management view
2) choose random category and tag
3) save configuration
4) verify configuration
> [1LP][RFR] Smart Management test

- utils/appliance/__init__.py
with 5.6 out of the picture the pick currently isn't necessary, its still sensible to keep the abstraction tho
> [1LP][RFR] remove postgresql service name version pick

- cfme/tests/services/test_generic_service_catalogs.py
Replacing the rest_api fixture with appliance.rest_api in test_generic_service_catalogs
{{pytest: -v -k TestServiceCatalogViaREST}}
> [1LP][RFR] remove rest_api fixture from test_generic_service_catalogs

- cfme/test_framework/sprout/client.py
- fixtures/appliance.py
Changes to appliance.py, removed try/finally as it would throw errors 'apps referenced before assignment' if no provisions where available. 
Also changed client.py to improve error message when no provisions are available from sprout.
> [RFR] Fix to appliance provisioning errors

- fixtures/provider.py
{{pytest: -v -k rhevm36 --use-provider rhevm36 --provider-limit 1 --long-running}}
> [RFR] provider-limit: Use managed_known_providers instead

- cfme/tests/services/test_rest_services.py
Replacing the rest_api fixture with appliance.rest_api in test_rest_services.
{{pytest: -v --long-running cfme/tests/services/test_rest_services.py}}
> [1LP][RFR] remove rest_api fixture from test_rest_services

- cfme/services/requests.py
- utils/appliance/implementations/ui.py
~~Try/except for class name vs object name when logging navigation~~
@mfalesni suggested using `inspect.isclass`, this is way better.
~~Maybe there's a more elegant way of handling this?~~
RHCFQE-2753
> [RFR] Update util.app.implem.ui, navigation logging

- cfme/tests/infrastructure/test_providers.py
__Updating tests__ to block provider_crud for scvmm while bug is being fixed.  CFME is returning temporary templates in addition to real templates.
https://bugzilla.redhat.com/show_bug.cgi?id=1450527
> [RFR]Block SCVMM providers from provider_crud due to BZ

- cfme/tests/infrastructure/test_providers.py
Fixing error when running pytests due to missing import:
```
================================================================================ ERRORS ================================================================================
________________________________________ ERROR at setup of Source/repos/cfme_tests/cfme/tests/infrastructure/test_providers.py _________________________________________
cfme/tests/infrastructure/test_providers.py:213: in <module>
@pytest.mark.meta(blockers=[BZ(1450527, unblock=lambda provider: provider.type != 'scvmm')])
E   NameError: name 'BZ' is not defined
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! …
```
> [RFR][1LP] adding BZ import to fix NameError

- fixtures/ui_coverage.py
- scripts/data/coverage/Gemfile.dev.rb
- scripts/data/coverage/coverage_gem.rb
- scripts/data/coverage/thing_toucher.rb
- utils/ssh.py
The miq/lib/ directory was removed, making the installation of coverage hook fail.
Moved the installation into vmdb/lib/ and modified the preinitializer to require_relative.
{{pytest: -v -m smoke --ui-coverage}}
> [1LP][RFR] Fix the coverage hook setup

- cfme/tests/infrastructure/test_providers.py
Replacing the `rest_api` fixture with `appliance.rest_api` in test_providers.
{{pytest: -v cfme/tests/infrastructure/test_providers.py -k TestProvidersRESTAPI}}
> [RFR] remove rest_api fixture from test_providers

- cfme/tests/infrastructure/test_rest_automation_request.py
Replacing the `rest_api` fixture with `appliance.rest_api` in test_rest_automation_request.
{{pytest: -v cfme/tests/infrastructure/test_rest_automation_request.py}}
> [1LP][RFR] remove rest_api fixture from test_rest_automation_request

- cfme/tests/infrastructure/test_vm_retirement_rest.py
Replacing the `rest_api` fixture with `appliance.rest_api` in test_vm_retirement_rest.
{{pytest: -v cfme/tests/infrastructure/test_vm_retirement_rest.py}}
> [1LP][RFR] remove rest_api fixture from test_vm_retirement_rest

- cfme/common/__init__.py
- cfme/tests/containers/test_properties.py
{{pytest: cfme/tests/containers/test_properties.py::test_pods_conditions -v --use-provider cm-env1 }}
In this PR I automated test id 9914 from Polarion, the test compare the values of each type of pod condition between openshift and CFME.
To make this test works i had to add new infa code on multi key summery tables.
For each multi-key table I set parent table and few child tables, the parent table will be the original table and each row of it will represented as child table. the parent table will have properties with the value of the name column of each line, in case on name column exist we get the most left value in each line and set it to be the property name.
for the following table:
table name: connection
|Name| IP | status |
|A |1.2.3.4 |Up |
|B |5.6.7.8 |Up |
|V |9.10.11.12|Down | …
> [RFR][1LP] Pod condition test

- cfme/tests/infrastructure/test_timelines.py
Replacing the `rest_api` fixture with `appliance.rest_api` in test_timelines.
{{pytest: -v -k TestVmEventRESTAPI}}
> [1LP][RFR] remove rest_api fixture from test_timelines

- cfme/rest/gen_data.py
- cfme/tests/configure/test_tag.py
* replacing the rest_api fixture with appliance.rest_api
* edit tests enhancements
{{pytest: -v --use-provider vsphere6-nested -k TestTagsViaREST}}
> [RFR] remove rest_api fixture from test_tag

- cfme/common/vm.py
- cfme/tests/control/test_alerts.py
- widgetastic_manageiq.py
{{pytest: -v -k 'test_alert_timeline_cpu' --long-running --use-provider vsphere6-nested}}
__Fixing__ test_alert_timeline_cpu, because the timeline was changed.
> [1LP][RFR] Fix for test_alert_timeline_cpu

- cfme/tests/test_appliance.py
- utils/appliance/__init__.py
Some tests should not be run against the podified image as they are not valid... this PR uncollects such tests.  I am sure there are more, this is a quick first past. 
This will not work in PRT as PRT has not podified appliance backing... so here are the results...
17:13:19 Appliance's streams: [5.8, downstream]
17:13:19 ============================= Running smoke tests ==============================
17:13:21 
17:14:11 cfme/tests/test_appliance.py::test_rpms_present[cfme] PASSED
17:14:12 cfme/tests/test_appliance.py::test_rpms_present[cfme-appliance] PASSED
17:14:14 cfme/tests/test_appliance.py::test_rpms_present[nfs-utils] PASSED
17:14:15 cfme/tests/test_appliance.py::test_rpms_present[libnfsidmap] PASSED
17:14:16 cfme/tests/test_appliance.py::test_rpms_present[ipmitool] PASSED
17:14:18 …
> [1LP][RFR] Uncollect tests that are not valid on a pod deployment

- cfme/tests/infrastructure/test_advanced_search_host.py
- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/tests/infrastructure/test_advanced_search_vms.py
- cfme/web_ui/expression_editor.py
- cfme/web_ui/search.py
alt-text for the advanced search buttons will be fixed here:
https://github.com/ManageIQ/manageiq-ui-classic/pull/367
The required bug has been fixed in 57z and 58z cloudforms, and is in upstream MIQ. With the announcement of EOL of version support of CFME 56z, this can now be merged.
https://bugzilla.redhat.com/show_bug.cgi?id=1380430
This fulfills the 'automate_bug' flag in the BZ and reverts to previous design using FormButton instead of specific locators for advanced search buttons.
Marginally better than current master/downstream-stable results against 58z.  Failures well outside the scope of what I'm trying to accomplish here, that should be addressed by focus area owner of CFME QE.
* 57z: 73% overall passing rate, test_adv_search_vms failing because search widget isn't rendered on …
> [1LP][RFR] Update Advanced Search buttons, BZ1380430

- cfme/tests/cloud/test_providers.py
* replacing the `rest_api` fixture with `appliance.rest_api`
* small enhancements
* ancient uncollectifs and blockers cleanup
* removed test valid for version < 5.4
* removed unnecessary "request" arguments
{{pytest: -v -k "test_hostname_max_character_validation or test_api_port_max_character_validation or TestProvidersRESTAPI" cfme/tests/cloud/test_providers.py}}
> [RFR][1LP] remove rest_api fixture from test_providers + cleanups

- cfme/tests/intelligence/test_chargeback.py
* replacing the `rest_api` fixture with `appliance.rest_api`
* edit tests enhancements
* fix `wait_for` test calls to really fail when result is empty 
{{pytest: -v -k TestRatesViaREST}}
> [RFR] remove rest_api fixture from test_chargeback + edit improvements

- cfme/tests/intelligence/reports/test_crud.py
* replacing the `rest_api` fixture with `appliance.rest_api`
* other minor improvements and fixes (like redefined builtin)
{{pytest: -v -k "test_run_report or test_import_report or test_custom_report_crud" cfme/tests/intelligence/reports/test_crud.py}}
> [RFR][1LP] remove rest_api fixture from test_crud; enhancements

- fixtures/log.py
currently py.test --setup-plan fail in log.py fixture because test_phase['call'] isn't defined.
This PR fixes that fixture to return 'skipped' if call isn't defined
> [RFR][1LP] py.test --setup-plan fix

- cfme/tests/cloud_infra_common/test_retirement.py
Test retirement of the S3 (instance-store) backed Amazon EC2 instances. These instances are creating using a public paravirtual AMI.
Instance-backed instances aren't terminated on retirement by default, so parametrize on a tagged and untagged instance, checking the power state after retirement accordingly.
Automates existing manual test case from Polarion.
Only comments have been changed since I got 100% passing on 57z 58z. The runs since then have seen an intermittent failure to deploy the test VM for the fixture on 1/3 tests.
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py -k "test_retirement_now" --use-provider ec2west --long-running -v }}
FIXES RHCFQE-2726
> [RFR][1LP] Add retirement tests for EC2 instances

- cfme/tests/infrastructure/test_timelines.py
SCVMM doesn't provide events to CFME. So, timelines tests always fail against it.
Shriver: Adding pytest line, default provider tag doesn't include scvmm
{{ pytest: cfme/tests/infrastructure/test_timelines.py --use-provider complete --long-running -v --collect-only}}
> [1LP][RFR] Excluding SCVMM from timelines tests

- requirements/frozen.txt
while debugging we found a rigger-lib thread unsafe detail that was fixed in the new release
> [RFR] update rigger to make artifactor more robust

- .gitignore
- cfme/scripting/ipyshell.py
- setup.py
You can run a customized and "ensured" ipython by:
* miq-ipython
* python -m cfme.scripting.ipyshell
That ensures the env is correct and then launches ipython and imports some of the most common things.
> [RFR][1LP] Support for customized ipython launcher.

- cfme/web_ui/form_buttons.py
In 5.8 the ``bChangeStoredPassword`` changed to ``vm.bChangeStoredPassword``
{{pytest: -v -k test_host_good_creds --use-provider rhevm36}}
> [1LP][RFR] fix change stored password locator

- fixtures/browser.py
by changing the restart sequence we will also reduce wharf-cycling
**IMPORTANT** locally untested
> [1LP][RFR] simplify browser restart on error

- cfme/tests/cli/test_evmserverd.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/services/test_service_catalogs.py
- cfme/tests/test_rest.py
- utils/wait.py
{{pytest: cfme/tests/cli/test_evmserverd.py cfme/tests/control/test_actions.py cfme/tests/infrastructure/test_instance_analysis.py cfme/tests/infrastructure/test_provider_discovery.py cfme/tests/intelligence/reports/test_crud.py cfme/tests/services/test_service_catalogs.py cfme/tests/test_rest.py}}
> [RFR][1LP] replace pytest.wait_for with wait_for_decorator

- cfme/tests/automate/test_buttons.py
- cfme/tests/configure/test_visual_cloud.py
- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/intelligence/test_chargeback.py
- cfme/tests/test_appliance.py
- fixtures/pytest_store.py
- fixtures/templateloader.py
- markers/uncollect.py
- scripts/refactoring/checkallimports.py
also fail if one tries to use store before the config is loaded
{{pytest:  --composite-uncollect --collect-only}}
```
cfme/tests/configure/test_visual_cloud.py  cfme/tests/infrastructure/test_vm_clone.py cfme/tests/intelligence/test_chargeback.py cfme/tests/test_appliance.py
```
> [1LP][RFR] remove import time requirement for appliance objects

- utils/browser.py
we did hit a few bugs due to poor properties of the implementation in selenium and it will keep breaking until its handled better
> [RFR][1LP] enforce remote webdriver keep_alive to be false

- scripts/dockerbot/dockerbot.py
- scripts/dockerbot/pytestbase/Dockerfile
this pr uses the docker entry-point to declare the ci command, this will decouple evolution of the docker image from the image executor
i need some idea to test this without affecting live trackerbot data
> [RFR][NOTEST] switch dockerbot to use an actual docker entrypoint

- cfme/tests/cloud/test_delete_cloud_object.py
{{pytest: -v -k test_delete_instance_appear_after_refresh  --long-running}}
Fixed non-unique test cases
> [RFR]Fixed non-unique test names

- cfme/tests/services/test_service_catalogs.py
removing the `rest_api` fixture
{{pytest: -v -k test_order_catalog_item_via_rest --long-running}}
> [1LP][RFR] remove rest_api fixture from test_service_catalogs

- cfme/tests/services/test_rest_services.py
* new test checking that VM added to service is also accessible using VMs subcollection.
Tested locally. This test depends on manageiq-client==0.3.0 which is in requirements/frozen.txt, but for some reason is not installed on PRT. It seems requirements are not being installed at all.
* also removing support for versions < 5.7
{{pytest: -v -k test_service_vm_subcollection --long-running}}
> [1LP][RFR] new REST API test for vms service subcollection; removing support for versions < 5.7

- cfme/infrastructure/deployment_roles.py
- cfme/tests/openstack/infrastructure/test_relationships.py
- cfme/tests/openstack/infrastructure/test_roles.py
Added an option to use DeploymentRoles class on applications with different Infra providers connected (Openstack, VMWare etc.)
{{ pytest: cfme/tests/openstack/infrastructure/test_roles.py --use-provider=rhos_uc }}
> [1LP][RFR] Deployment Roles workaround

- cfme/intelligence/reports/reports.py
This Fix deletes saved canned reports.
Due to parsetime it was failing.
{{pytest: --use-provider=vsphere55 cfme/tests/intelligence/reports/test_views.py}}
> [1LP][RFR] Fix delete canned saved reports 

- cfme/tests/infrastructure/test_vm_rest.py
removing the `rest_api` fixture from test_vm_rest
{{pytest: -v cfme/tests/infrastructure/test_vm_rest.py}}
> [1LP][RFR] remove rest_api fixture from test_vm_rest

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_timelines.py
* Gave timelines test cases unique names
* renamed wrongly called fixtures
> Renaming timelines test cases

- cfme/test_framework/pytest_plugin.py
- conftest.py
- setup.py
this has to work around a newly found pytest issue
this enables general use as package, currently editable installation is still needed
> [RFR][1LP] move conftest into pytest plugin

- cfme/tests/cloud_infra_common/test_power_control_rest.py
renaming names of the test cases to be unique
{{pytest: -v cfme/tests/cloud_infra_common/test_power_control_rest.py --use-provider vsphere65-nested}}
> Unique tests names in test_power_control_rest

- utils/appliance/implementations/ui.py
dismiss_any_alerts takes ~2s and is invoked on every step. By putting it inside the following try/except we only execute it when there is a possibility it actually happened. If there is an alert and you try to interact witha page, you get an exception, which we handle, currently we do nothing but this patch moves the alert check in there.
> [RFR] Superspeed

- cfme/tests/infrastructure/test_provisioning_rest.py
removing the `rest_api` fixture from test_provisioning_rest
{{pytest: -v cfme/tests/infrastructure/test_provisioning_rest.py --use-provider vsphere65-nested}}
> [1LP][RFR] remove rest_api fixture from test_provisioning_rest

- cfme/tests/infrastructure/test_rest_templates.py
removing the `res_api` fixture + old cruft
{{pytest: -v cfme/tests/infrastructure/test_rest_templates.py}}
> [1LP][RFR] remove rest_api fixture from test_rest_templates

- cfme/tests/test_appliance.py
The validation against rpm isn't necessary as far as I can tell, those ssl files are generated by the IPappliance object's configuration methods on deployment. Found during template testing of CFME, will fail against MIQ because it isn't delivered via rpm.
Didn't really mean to create this branch on the main repo, but its here now. I can delete now, or after we merge...
@jamesooden Thoughts?
{{ pytest: -m smoke }}
> [RFR][1LP] Update test_html5_ssl_files_present

- cfme/common/provider.py
- cfme/common/provider_views.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/tests/infrastructure/test_esx_direct_host.py
- cfme/tests/infrastructure/test_providers.py
- utils/providers.py
This PR contains 3 major changes.
1. I've moved Provider Credentials out of BaseProvider class and splitted them up to the bunch of Credentials classes. This change is introduced by PR #4511 (merged).
2. This PR introduces provider's endpoints approach. Part of provider's data belonging to endpoints was moved to appropriate Endpoints classes. Related data PR - cfme-qe-yamls/merge_requests/127
3. This PR also contains widgetastic Add and Edit views for Infrastructure providers and all related changes.
it also has related cfme data update request - PR 149
{{pytest: cfme/tests/infrastructure/test_esx_direct_host.py cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py }}
**note:** these changes are related only to infrastructure providers. cloud providers tests …
> [1LP][RFR] Creds + Endpoints + Add/Edit Infra Providers

- cfme/tests/configure/test_rest_access_control.py
- cfme/tests/configure/test_tag_category.py
- cfme/tests/infrastructure/test_rest_providers.py
fix `wait_for` calls to return False on failure. I mistakenly assumed that any false value means failure, but it's just False by default.
> [1LP][RFR] fix wait_for calls to return False on failure

- cfme/infrastructure/provider/__init__.py
test_providers.test_providers_discovery has been broken recently by one of widgetastic conversion PRs.
This PR should fix the issue.
{{pytest: cfme/tests/infrastructure/test_providers.py -k test_providers_discovery}}
> [RFR] fixed discovery test

- cfme/configure/configuration/__init__.py
- cfme/exceptions.py
- cfme/tests/configure/test_vmware_console_settings.py
Provide CRUD class for modifying VMware Console settings, and a test to test it.   These settings are under the main configuration page for CFME.
Note, this PR is based on PR:
https://github.com/ManageIQ/integration_tests/pull/4594 (Merged)
So the only thing to be reviewed is the stuff in the "Add support for configuring VMware Console Type" commit.   When PR 4594 gets merged and this PR rebased off of master, this will no longer be an issue.
> [1LP][RFR] RHCFQE-2646 VMware Console Type config

- cfme/configure/settings.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/web_ui/__init__.py
ButtonGroups control doesn't take into accout that settings page can have several labels with the same name. I've added fieldset property to make those tests work with buttons from correct fieldset
{{pytest: cfme/tests/configure/test_default_views_cloud.py}}
> [RFR][1LP] fix for test_default_views  tests

- cfme/scripting/quickstart.py
this prints all linking errors before exiting quickstart
> [RFR] quickstart: collect all link errors before exiting

- cfme/infrastructure/host.py
Some tests fail in jenkins with error KeyError: 'username'.
I cannot reproduce this locally. 
So, I'd like to temporarily add some logging in order to figure out where the issue is.
> [RFR] added some logging to debug tricky credentials case

- cfme/fixtures/base.py
Useful when debugging test collection.
{{pytest: --collect-only --no-provider-check}}
> [RFR][1LP] Add option to disable provider validity check

- scripts/template_upload_all.py
Planning a change to CI environment to use 'gce' instead of 'google' for provider_type in order to match trackerbot's types.
> [RFR] Update template_upload_all, change google to gce

- cfme/base/credential.py
__Fixing__ credentials.py Without `deepcopy` of the `conf.credentials` it's possible to change original object which will affect in other places where `conf.credentials` called with the same key.
> [RFR] Fix in credentials.py

- cfme/tests/cloud/test_instance_power_control.py
* remove `rest_api` fixture
* minor cleanups
{{pytest: -v -k TestInstanceRESTAPI --use-provider ec2west --long-running cfme/tests/cloud/test_instance_power_control.py}}
> [1LP][RFR] remove rest_api fixture from test_instance_power_control

- cfme/tests/cli/test_rake_evm_automate-53.py
Seems like pods do not necessarily keep the same behaviour as VMs.
> [1LP][RFR] RHCFQE-2943: Ensure it deletes the file in correct path.

- cfme/containers/container.py
- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/openshift.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/containers/template.py
- cfme/exceptions.py
- cfme/tests/containers/test_labels.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_relationships.py
- utils/ocp_cli.py
{{pytest: cfme/tests/containers/test_labels.py -v --use-provider cm-env1}}
- Added label tests
- Changed Pod, Replicator, Route, Service constructors to get project name as argument (Required to differentiate among objects with the same name)
- Added utils/ocp_cli.py util which provide ssh access to openshift provider
- Added functionality to get random instances of each containers object
- Added Labalable class to provide label CRUD functionality for containers objects
- Get image from table by ID instead of name/tag
> [RFR][1LP] Added Labels test

- cfme/infrastructure/config_management.py
There are ~ 7 tests failing in jenkins with NavigationError error.
This PR fixes those tests
{{pytest: cfme/tests/infrastructure/test_config_management.py}}
> [RFR] test_config_management fix

- cfme/tests/control/test_alerts.py
- cfme/tests/control/test_bugs.py
Purpose
=======
`test_vmware_alarm_selection_does_not_fail` should be stored in test_bugs.py.
{{pytest: -v -k 'test_vmware_alarm_selection_does_not_fail'}}
> [1LP][RFR] test_vmware_alarm_selection_does_not_fail moved to test_bugs.py

- cfme/configure/access_control.py
- utils/ext_auth.py
these changes were tested against pod locally.
{{ pytest: cfme/tests/integration/test_cfme_auth.py }}
> [RFR][1LP] adding pod support to ext auth code

- scripts/list_provider_vms.py
This simple script is for monitoring of active vms on providers.
Takes --tag and positional provider key options
tags correspond to those in cfme_data for management_system entries
Multiple tags are additive, not combination
Can specify tags and providers
Takes --outfile to write a tabulated report to a file, also writes it to
stdout along with progress updates
Lots of other things this _could_ do, but keeping it simple for now.
> [1LP][RFR] Script to list provider vms

- cfme/tests/openstack/infrastructure/test_provider.py
Minor changes because of 'endpoints' implementations
{{ pytest: cfme/tests/openstack/infrastructure/test_provider.py --use-provider rhos_uc }}
> [RFR] Openstack test_provider.py - fixed KeyError and typo

- cfme/cloud/instance/__init__.py
[BZ 1389299](https://bugzilla.redhat.com/show_bug.cgi?id=1389299) was fixed, so overridden `load_details()` and `get_detail()` methods can be removed from Instance object.
> [1LP][RFR] Removed overridden methods from Instance object

- artifactor/plugins/ostriz.py
Some of the build names in Ostriz have some trailing whitespace characters (mostly newlines), and this will hopefully strip that whitespace out.
> [WIP] Strip out whitespace in the build names before sending them to Ostriz

- fixtures/artifactor_plugin.py
- fixtures/browser.py
- fixtures/log.py
- utils/pytest_shortcuts.py
i believe this should fix an error we started to see - unfortunately i don't have a direct way to replicate it
> [1LP][RFR] remove report_safe_longrepr in favour of report.longreprtext #pytest3

- cfme/configure/configuration/__init__.py
- cfme/infrastructure/host.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/control/test_compliance.py
- fixtures/provider.py
- utils/appliance/__init__.py
__Fixing__ tests in cfme/tests/control/test_compliance.py.  Some core enhancements is required. After appliance rebooting the navigation is broken. I found a workaround in which you need just to close the browser to start the navigation cycle from the beginning.
{{pytest: -v -k 'test_check_package_presence' --long-running --use-provider vsphere6-nested}}
> [1LP][RFR] Fixed and refactored test_compliance.py

- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/provider/__init__.py
- cfme/containers/volume.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/tests/containers/test_containers_summary.py
- cfme/tests/containers/test_labels.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_relationships.py
- cfme/tests/containers/test_smart_management.py
- cfme/tests/containers/test_start_page.py
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py cfme/tests/containers/test_containers_summary.py cfme/tests/containers/test_properties.py cfme/tests/containers/test_labels.py cfme/tests/containers/test_relationships.py cfme/tests/containers/test_smart_management.py -v --use-provider cm-env1}}
This PR includes general fixes and changes in container tests / objects.
- Most of the errors that fixed in this PR caused by the recent change of the containers objects constructor that requires project name.
- Some tests changed to grab instance by get_random_instances instead of navigate_and_get_rows which is slower.
> [RFR] General fixes

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/configure/test_diagnostic_timelines.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/tests/intelligence/test_reports_with_timelines.py
- markers/manual.py
1. Added manual timelines tests.
There should be much more tests but the rest will be added later.
2. Fixed manual py test plugin to correctly collect/uncollect manual test cases.
The collection works in the following way now:
If --manual argument is added then pytest collects only manual test cases.
If --manual argument isn't added then pytest ignores all manual test cases.
> [1LP][RFR] manual timelines tests

- cfme/cloud/instance/__init__.py
- cfme/cloud/instance/azure.py
- cfme/cloud/instance/ec2.py
- cfme/cloud/instance/gce.py
- cfme/cloud/instance/openstack.py
- cfme/common/vm.py
- cfme/provisioning.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud/test_provisioning.py
Convert the cloud instances class to widgetastic by defining new views and widgets.
Part 1 here provides All, AllForProvider, Details, and Provisioning views and widgets.
I have a lot more code ready to follow this for the other instance pages.
Local testing works for the destinations/widgets added, along with the 2 modified tests. Will update with PRT results > 12214
{{ pytest: cfme/tests/cloud/test_instance_power_control.py cfme/tests/cloud/test_provisioning.py --use-provider ec2west --use-provider gce_central --long-running -v -k "not RESTAPI" }}
Run 12979 - 92% pass rate or better, 2 failing tests in 57z and 1 failing test in 58z. Not at all related to these changes.
Rebased recently, PRT re-running.
> [1LP][RFR] Cloud Instance Widget Conversion (Part 1)

- scripts/cleanup_old_vms.py
Refactor the cleanup_old_vms script to:
* Remove list mode - to be replaced by separate script
* Collect report data for deleted VMs, and write that to outfile
This way the script is more focused on cleanup, and reporting cleanup actions/results, and its use/function doesn't get convoluted.
I've been testing locally with combinations of singular and multiple text matchers with no issues so far, other than uncovering problem VM's that are in bad states and can't be cleaned up via normal calls.
> [RFR][1LP] Update cleanup_old_vms, detailed reporting
