- cfme/tests/cloud/test_provisioning.py
{{pytest: cfme/tests/cloud/test_provisioning.py -v -k with_boot_volume --long-running }}
> We need bootable volume here

- cfme/tests/configure/test_default_filters.py
{{pytest: -v -k 'test_servicetemplateandimages_defaultfilters or test_servicevmsandinstances_defaultfilters'}}
> bz blocker 1225145 for service default filters

- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_catalog_item.py
Last test(test_permissions_catalog_item_add) is marked with a bug . Test will fail.
> Catalog edit tag fix

- utils/providers.py
Should be little bit more conserving our resources.
{{pytest: cfme/tests/automate/test_domain_priority.py cfme/tests/automate/test_namespace.py cfme/tests/configure/test_default_filters.py cfme/tests/configure/test_default_views.py cfme/tests/configure/test_access_control.py cfme/tests/configure/test_visual_cloud.py cfme/tests/configure/test_visual_infra.py cfme/tests/control/test_bugs.py cfme/tests/infrastructure/test_advanced_search_host.py cfme/tests/infrastructure/test_advanced_search_providers.py cfme/tests/infrastructure/test_advanced_search_vms.py cfme/tests/integration/test_openldap_auth.py cfme/tests/integration/test_aws_iam_auth_and_roles.py cfme/tests/integration/test_ldap_auth_and_roles.py cfme/tests/integration/test_ipa_external.py …
> setup_a_provider does not setup a new provider if a suitable one already exists

- cfme/tests/intelligence/reports/test_canned_corresponds.py
> Fix cluster relationship test

- scripts/apishow.py
I've been using this script for some time and did not realize it is not in the repository yet :)
> [NO TEST] Script to show all API calls

- utils/appliance.py
This is to ensure that the RH domain is cloned over the top of Default
> Domain cloning for alternative domain in 53,54

- cfme/infrastructure/host.py
{{pytest: -v -k host_drift_analysis}}
> Fix host drift locator

- cfme/tests/cloud_infra_common/test_tag_objects.py
I noticed one test failed when it saw the tag already assigned. This is sort of WIP TEST PR to see what can I do with it.
> Try mitigating one issue I saw in logs

- cfme/configure/about.py
- cfme/tests/configure/test_docs.py
{{pytest: cfme/configure/about.py -k all_docs_present -v }}
> Fix documentation tests

- cfme/infrastructure/pxe.py
- cfme/tests/infrastructure/test_pxe.py
Also resolves #1070 (I hope. A better infoblock was devised meanwhile and it appears to be working)
> Try fixing PXE; Normalize infoblock

- cfme/fixtures/smtp.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py -k test_provision_from_template --long-running }}
> SMTP collector does not ruin the test if it dies

- cfme/tests/infrastructure/test_vm_analysis.py
- utils/api.py
{{pytest: cfme/tests/infrastructure/test_vm_analysis.py -k REST -v --long-running }}
> REST API - VM Analysis

- cfme/tests/configure/test_default_views_cloud.py
- cfme/web_ui/toolbar.py
{{pytest: -v -k 'test_details_view or test_exists_view'}}
> Test cloud exists and details mode

- utils/api.py
- utils/providers.py
* Update REST client
* Make it possible to avoid certain providers that might not behave well for `setup_a_provider`
{{pytest: cfme/tests/test_rest.py -v --long-running}}
> Couple of jenkins tweaks

- cfme/services/catalogs/orchestration_template.py
{{pytest: -v --long-running --use-provider=complete cfme/tests/services/test_provision_stack.py}}
> Modified to run for rhos6-ga

- conftest.py
- fixtures/portset.py
- fixtures/pytest_store.py
- utils/appliance.py
- utils/db.py
- utils/ports.py
- utils/ssh.py
*Slightly* ugly solution, I admit I don't like it but I consider it good for now. I somehow checked it in my environment, it seems to pick up the changes.
@petrblaho , can you pull this commit over my branch when you test it against an appliance deployed inside the OOO setup to see if it works properly?
> Enable port overriding.

- cfme/tests/configure/test_default_views_infra.py
{{pytest: -v -k 'test_details_view or test_exists_view'}}
> Test infra details and exist mode

- utils/api.py
{{pytest: cfme/tests/test_rest.py -v -k provider_crud}}
> REST - Fix loading actions

- artifactor/__init__.py
- artifactor/plugins/reporter.py
- data/templates/test_report_provider.html
{{pytest: -k test_provider_crud}}
> Specific Provider Reports

- cfme/tests/configure/test_docs.py
{{pytest: cfme/tests/configure/test_docs.py -k test_info -v }}
> Docs test blocker update

- utils/virtual_machines.py
This appeared on our rhos 5 setup recently, it got full.
{{pytest: -v -k rhos5 --use-provider rhos5}}
> deploy_template() also skips on OS's OverLimit; write skip on terminal

- cfme/tests/configure/test_default_views_infra.py
- cfme/web_ui/toolbar.py
{{pytest: -v -k 'test_hybrid_view or test_graph_view or test_tabular_view'}}
> Test hybrid,graph and tabular view

- cfme/tests/cloud/test_provisioning.py
For some reason, still largely unknown, the openstack tests were
receiving EC2 objects. At the moment, instead of diving into more
testgen/fixtures craziness, I just replaced the mechanisms, with
uncollectif as this seems to fix the issue.
> Fixes an odd collection issue

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_host_drift_analysis.py -k host_drift_analysis -v --long-running }}
> If Quadicon is not found, show what are the other ones

- cfme/tests/cloud/test_provisioning.py
The flavours are named the same in various providers. I was not checking for them before.
> Pick flavours properly

- artifactor/plugins/reporter.py
- data/templates/test_report.html
... so you can just click and go.
{{pytest: cfme/tests/automate/test_vmware_methods.py -v -k hotadd_disk}}
> Find and extract URLs in the report HTML

- cfme/automate/service_dialogs.py
- cfme/configure/configuration/__init__.py
- cfme/configure/settings.py
- cfme/tests/automate/test_method.py
- cfme/tests/automate/test_namespace.py
- cfme/tests/automate/test_vmware_methods.py
- cfme/tests/cloud/test_provisioning.py
- cfme/tests/cloud/test_stack.py
- cfme/web_ui/toolbar.py
Not a complete list, but these changes should make it work better. I noticed the 5.2 test exploded on proxy error, but an another one so it was probably not caught by the detector.
> Fixes for 5.2 stream.

- cfme/services/catalogs/catalog_item.py
{{pytest: cfme/tests/services/test_myservice.py -v -k edit_tags --use-provider vsphere55}}
> CatalogItem can work with non-Default domain

- utils/mgmt_system/openstack.py
* Added _generic_paginator method which will work for all OpenStack api
services that utilize the limit/marker method for pagination.
Unfortunately novaclient only seems to support the marker  kwarg
for servers and nothing else.
* Modified the _get_all_instances method to make use of the generic paginator.
* There is a list in the docs of edge cases we_may_ need to solve at a later date, depending on how things go.
{{pytest: -k test_provider_crud cfme/tests/cloud/test_providers.py}}
> Fixed pagination for OpenStack servers

- .gitignore
> Added SSH-related files and doc_data.yaml to .gitignore

- scripts/dockerbot/dockerbot.py
Add the nowait option to dockerbots cli interface
> Add the nowait option to dockerbots cli interface

- cfme/fixtures/pytest_selenium.py
- fixtures/browser.py
Taking screenshots is a function that can now be used by other systems
This function is now inside pytest_selenium module.
> Move taking a screenshot to a function

- fixtures/ssh_client.py
* Investigations led to the following being the most likely cause of the
recent PRT hangs.
* When a test run finishes, we fire off a call to destroy the appliance
* The appliance disappears and the main thread goes into Garbage
Collection
* It seems garbage collection drops into a thread handling routine which
just gums up the whole thing.
* New code tries to ensure all appliance ssh sessions are closed before
allowing the appliance to be destroyed.
> Paramiko issues leading to hanging PRT runs

- utils/api.py
{{pytest: cfme/tests/test_rest.py -k add_delete_service_catalog -v}}
> Update REST client with id/href behaviour

- cfme/control/import_export.py
- cfme/tests/control/test_export_policies.py
- cfme/tests/control/test_import_policies.py
I also learned the control explorer objects to work in context manager.
> Automate Policy profile export listing.

- cfme/tests/control/test_bugs.py
Disabled meta plugins for purpose. If the tests fail with timeouts, then it is all right.
{{pytest: cfme/tests/control/test_bugs.py -v -k folder_field_scope --long-running --disablemetaplugins blockers}}
> [BZ] Automate BZ 1209538

- scripts/dockerbot/check_prs.py
- scripts/dockerbot/dockerbot.py
* DKB now allows the --sprout-description cli arg
* PRT now sets the description to the TID(Task ID)
> Added Sprout description to dockerbot

- fixtures/ssh_client.py
- utils/ssh.py
- utils/tests/test_ssh_client.py
This might be terrible, but all the tests pass :)
Based on #2084
> Memoized SSHClient

- utils/testgen.py
{{pytest: --collect-only --use-provider=complete}}
> Fix testgen

- cfme/infrastructure/datastore.py
- cfme/tests/infrastructure/test_delete_infra_object.py
{{pytest: -v -k 'test_delete_datastore'}}
> Fix delete datastore

- cfme/configure/access_control.py
- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_role_crud or test_host_noquads or test_rolename_required_error_validation or test_rolename_duplicate_validation or test_delete_default_roles or test_edit_default_roles or test_delete_roles_with_assigned_group'}}
> Added few more role base test cases

- fixtures/nelson.py
Nelson gains yaml ability for metadata
> Nelson gains yaml ability for metadata

- cfme/tests/cloud/test_cloud_timelines.py
Support for ec2 events has been introduced in CFME 5.4.These code changes test the integration of ec2 events.
> Add support for ec2 events

- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/orchestration_template.py
- cfme/services/requests.py
- cfme/tests/services/test_provision_stack.py
I have commented out a line in request.py.
Please check if that impacts any other test.
I need to check for a test where request is supposed to fail and hence will show status = Error.
> Removetemplate stacktest

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
{{pytest: cfme/tests/control/test_basic.py --long-running}}
> Fix for 5.3

- scripts/appliance.py
- scripts/update_template.sh
- utils/appliance.py
Use it like this:
`scripts/update_template.sh providerkey appliancename -u onerepository -u secondrepository`
When this gets merged, I will probably point sprout to the templatize method since the code there is basically copied from sprout.
> Helper script to update and templatize an appliance.

- utils/providers.py
I noticed that the undeleted providers stuck in the tests so it was ruining the test setups.
> setup_a_provider now deletes badly behaving providers and remembers them.

- cfme/tests/automate/test_common_methods.py
- cfme/tests/automate/test_customization_paginator.py
- cfme/tests/automate/test_domain_priority.py
- cfme/tests/automate/test_smoke.py
- cfme/tests/automate/test_vmware_methods.py
- cfme/tests/cli/test_evmserverd.py
- cfme/tests/cli/test_rake_evm_automate-52.py
- cfme/tests/cli/test_rake_evm_automate-53.py
- cfme/tests/cloud_infra_common/__init__.py
- cfme/tests/cloud_infra_common/test_discovery.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/test_rest.py
Documenting of my tests or tests that I was touching significantly in recent times.
> [DOC] Test documentation (mfalesni)

- cfme/tests/infrastructure/test_provisioning_dialog.py
+ uncollect preallocated rhev disk test because our storage does not support that.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -v --long-running}}
> [DOC] Document prov dialog tests

- cfme/services/catalogs/catalog_item.py
{{pytest: -v --long-running cfme/tests/services/test_generic_service_catalogs.py }}
> Entry point made mandatory

- cfme/infrastructure/config_management.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_config_management.py
- cfme/web_ui/__init__.py
- cfme/web_ui/mixins.py
- cfme/web_ui/tabstrip.py
- conf/cfme_data.yaml.template
- utils/version.py
I'll be adding docs but it should be in a working state now.
> Init foreman + tests

- cfme/automate/service_dialogs.py
- cfme/tests/services/test_generic_service_catalogs.py
{{pytest: -v --long-running cfme/tests/services/test_generic_service_catalogs.py }}
> Text Box refresh problem fix

- cfme/services/requests.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py -k provision_approval -v --long-running}}
> Noticed it did not find the element although it should be there.

- cfme/tests/infrastructure/test_esx_direct_host.py
- cfme/versions.py
- cfme/web_ui/flash.py
- sprout/appliances/models.py
- utils/api.py
- utils/appliance.py
- utils/bz.py
- utils/mgmt_system/virtualcenter.py
- utils/ssh.py
- utils/version.py
I made a couple changes to `LooseVersion.get_version`, but then things got out of hand.
> LooseVersion -> Version, plus behavioral tweaks

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_delete_default_user'}}
> test delete default user

- utils/trackerbot.py
- utils/version.py
Newer version changes broke in a few places
> Fixed version in multiple places

- utils/version.py
> Fixed version cmp function

- cfme/tests/cloud/test_provisioning.py
- cfme/web_ui/flash.py
- fixtures/provider.py
- markers/uncollect.py
* Caching of module scoped fixtures was causing a big problem, this is
going to eventually lead to some other work
* Logging of uncollect was lying, terminology was bad
* Fixing versions for flash messages
> Fixed an issue and cleaned up some logging

- cfme/fixtures/pytest_selenium.py
- fixtures/page_screenshots.py
> ScreenShot feature

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_description_required_error_validation or test_delete_default_group or test_delete_group_with_assigned_user or test_edit_default_group'}}
> More group test cases

- cfme/infrastructure/config_management.py
- cfme/tests/infrastructure/test_config_management.py
{{pytest: -v cfme/tests/infrastructure/test_config_management.py}}
> Update of config management due to changes in 5.4.1.0

- scripts/template_upload_all.py
This updates the template uploader script to properly name the stable_nightly templates so they can be uploaded to the providers.
> adds handling for templates based on the miq stable nightly builds

- cfme/tests/control/test_bugs.py
{{pytest: cfme/tests/control/test_bugs.py -k invoke_custom_automation -v}}
> Automate BZ#1243357 - Invoke Custom Automation bug

- cfme/web_ui/__init__.py
* Correct detection of expandable items in dynatree.
* Ability to close the opened levels after reading into the original state (optional).
@akrzos ^^
{{pytest: cfme/tests/control/test_basic.py -v --long-running}}
> Couple of updates to cfme.web_ui.Tree:

- cfme/intelligence/reports/widgets.py
- cfme/tests/intelligence/test_dashboard.py
- fixtures/provider.py
- fixtures/widgets.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -v -k verify_rss_links --long-running}}
> Improved widgets logic

- cfme/services/catalogs/cloud_catalog_item.py
{{pytest: -v --long-running cfme/tests/services/test_cloud_service_catalogs.py }}
> Domain path changed

- cfme/infrastructure/provider.py
- cfme/infrastructure/virtual_machines.py
A cosmetic change, but helps debugging failed tests with random provider.
> Noticed missing attribute display on some objects in failed tests.

- cfme/tests/services/test_pxe_service_catalogs.py
{{pytest: -v --long-running cfme/tests/services/test_pxe_service_catalogs.py }}
> Increased request time

- cfme/tests/test_db_restore.py
- utils/appliance.py
This test is meant to take a DB backup of an appliance and to restore the DB on another appliance.
> Restore DB

- cfme/automate/explorer.py
- cfme/tests/cloud/test_provisioning.py
{{pytest: cfme/tests/automate/test_namespace.py cfme/tests/automate/test_method.py cfme/tests/cloud/test_provisioning.py}}
> Automate fix

- sprout/appliances/admin.py
- sprout/appliances/api.py
- sprout/appliances/migrations/0021_userappliancequota.py
- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/views.py
I decided to monkeypatch the django User model here.
> [NOTEST][WIP] Sprout - Add quotas for users

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_current_user_login_delete'}}
> Automate BZ#1090877- test current user login delete

- cfme/tests/test_utilization.py
Checking for all metrics is pointless atm as EmsCluster resource_type is always present (possibly a bug, couldnt confirm with devs, BZ tomorrow anyway).
This way we know if we are actually collecting real data.
> Fix metrics test

- cfme/fixtures/pytest_selenium.py
Originally part of os infra PR.
> It can happen that config is none. This fixes it.

- cfme/common/provider.py
> Small omission fix

- cfme/automate/simulation.py
{{pytest: cfme/tests/automate/test_domain_priority.py -v --long-running}}
> Better handling of simulate object is None

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_group_duplicate_name'}}
> Validate group duplication

- cfme/web_ui/menu.py
{{pytest: cfme/tests/test_ui_problems.py -v --long-running}}
> Try mitigating the #tP problem by waiting for it

- data/profile_relay_events.yaml
Some of them are still missing though.
This is most likely to fail, but if it does not fail on events setup, it is good to go.
{{pytest: -k power_control --event-testing --long-running -v }}
> Updated the events yaml with almost all events

- cfme/services/requests.py
- cfme/tests/infrastructure/test_provisioning.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py -k provision_approval -v --long-running}}
> Auto-approve request with edit

- cfme/cloud/instance.py
- cfme/tests/cloud_infra_common/test_events.py
{{pytest: cfme/tests/cloud_infra_common/test_events.py -v --disablemetaplugins blockers --long-running}}
> Automate BZ#1238371 - vm_create_complete

- artifactor/plugins/reporter.py
- data/templates/test_report.html
- fixtures/qa_contact.py
Ability to filter reports by username added
> Ability to filter reports by username added

- cfme/fixtures/pytest_selenium.py
- cfme/provisioning.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/cloud/test_provisioning.py}}
> None handling

- sprout/appliances/templates/appliances/_providers.html
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/templates/base.html
- sprout/appliances/views.py
* Select2 fancy `<select>` tags
* Legend is displayed only when some provisioning is not finished yet
* Provider info also shows number of shepherd appliances now.
> [WIP][NO TEST] Sprout - Couple of improvements

- utils/api.py
{{pytest: cfme/tests/test_rest.py -v --long-running}}
> Quickfix for REST API client

- cfme/fixtures/pytest_selenium.py
{{pytest: cfme/tests/automate/test_provisioning_dialogs.py cfme/tests/automate/test_service_dialog.py cfme/tests/automate/test_customization_paginator.py -v --long-running}}
> Support selectpicker type of Select

- cfme/automate/explorer.py
- cfme/infrastructure/pxe.py
- cfme/services/catalogs/orchestration_template.py
- cfme/web_ui/__init__.py
Fixes upstream ScriptBox usage
> Fixes upstream ScriptBox usage

- fixtures/qa_contact.py
This means skips get blame info
> Blamer now runs for all tests

- utils/mgmt_system/__init__.py
- utils/mgmt_system/base.py
- utils/mgmt_system/exceptions.py
- utils/mgmt_system/kubernetes.py
- utils/mgmt_system/openshift.py
- utils/mgmt_system/rest_client.py
- utils/providers.py
cfme_data + creds are already present in our repos
It cant do much yet but it can list the entities that CFME collects.
Example usage of the rest api client (pretty simple):
```
from utils import kubernetes_client
k = kubernetes_client.KubernetesClient.from_config('kubernetes')
k.get('pod')
k.get('replicationcontroller', name='busybox', namespace='default')
```
> Kubernetes API + container_mgmt initial commit

- cfme/tests/configure/test_default_views_cloud.py
{{pytest: -v cfme/tests/configure/test_default_views_cloud.py -k 'test_tile_defaultview or test_list_defaultview'}}
> Fix cloud tile and list views

- utils/mgmt_system/openstack.py
{{pytest: -v --long-running cfme/tests/services/test_provision_stack.py }}
> Rhos stack cleanupcode

- scripts/dockerbot/pytestbase/Dockerfile
> Updated req in dockerfile

- cfme/tests/infrastructure/test_snapshot.py
- data/ui/automate/test_create_snapshot_via_ae.rb
First PR after PTO, so be gentle with me :smiley: 
{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --long-running -k test_create_snapshot_via_ae }}
> Add test for BZ#1247664

- cfme/cloud/stack.py
- cfme/tests/cloud/test_delete_cloud_object.py
{{pytest: -v -k 'test_delete_stack'}}
> Automate delete stack object

- artifactor/__init__.py
- utils/artifactor_start.py
{{pytest: -k test_bad_password}}
> Move artifactor log into a separate dir

- cfme/infrastructure/provider.py
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py}}
> A variety of upstream jenkins fixes

- cfme/tests/infrastructure/test_infra_quota.py
Test group quota by tagging
1.Quota-Max Memory
2.Quota-Max Cpu
> Automate quota

- cfme/configure/access_control.py
- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_edit_sequence_usergroups'}}
> Automate Edit Sequence of user groups

- cfme/tests/control/test_actions.py
- cfme/tests/test_rest.py
- cfme/tests/test_soap.py
- utils/api.py
{{pytest: cfme/tests/control/test_actions.py cfme/tests/test_rest.py -v --long-running}}
> Some tweaks that might make jenkins happier

- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/fixtures/pytest_selenium.py
- cfme/infrastructure/provider.py
- cfme/web_ui/__init__.py
{{pytest: -k test_provider_crud}}
> Angular Select + Inputs

- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/infrastructure/provider.py
- cfme/web_ui/__init__.py
{{pytest: -k test_provider_crud}}
> Fixed AngularSelect

- docs/guides/tipsntricks.rst
> Document the latest SSH problems findings

- cfme/automate/service_dialogs.py
- cfme/configure/access_control.py
- cfme/configure/settings.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/automate/test_service_dialog.py -v --long-running }}
> Add AngularSelect-s

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_analysis_profiles.py
{{pytest: -v -k 'test_host_analysis_profile_crud'}}
> Automate copy analysis profiles

- cfme/automate/explorer.py
{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --long-running -k create_snapshot_via_ae }}
> Fix the AE copy single domain text locator

- cfme/configure/settings.py
- cfme/fixtures/pytest_selenium.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_visual_cloud.py -v --long-running }}
> Fix ButtonGroup to work with newer design

- cfme/tests/cloud/test_cloud_timelines.py
https://bugzilla.redhat.com/show_bug.cgi?id=1265404
> BZ blocker for BZ 1265404

- cfme/automate/buttons.py
- cfme/cloud/instance.py
- cfme/control/explorer.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/control/test_actions.py
- cfme/web_ui/__init__.py
- cfme/web_ui/tabstrip.py
{{pytest: cfme/tests/control/test_actions.py cfme/tests/services/test_myservice.py cfme/tests/automate/test_buttons.py cfme/tests/configure/test_visual_infra.py cfme/tests/automate/test_common_methods.py -v -k "action_untag or retire_service or button or report_page_per_item or retire_extend or prevent_event or create_snapshot or action_tag" --long-running}}
> Couple of jenkins fixes

- cfme/control/explorer.py
- cfme/tests/control/test_alerts.py
- cfme/web_ui/__init__.py
But the functionality of this form is broken though.
This PR can be considered good if it skips on 5.5.
> Update the manual email add button

- cfme/tests/configure/test_visual_cloud.py
- cfme/tests/configure/test_visual_infra.py
{{pytest: -v -k 'test_grid_page_per_item or test_tile_page_per_item or test_list_page_per_item or test_report_page_per_item or test_start_page'}}
> Added Bz blocker for visual settings

- cfme/tests/configure/test_display_settings.py
{{pytest: -v -k 'test_color_setting'}}
> Fix colour setting

- cfme/configure/configuration/__init__.py
{{pytest: cfme/tests/integration/test_ldap_auth_and_roles.py -v -k test_group_roles}}
> Fixed authentication_user_type select

- cfme/common/vm.py
- cfme/web_ui/__init__.py
- cfme/web_ui/form_buttons.py
{{pytest: cfme/tests/automate/test_common_methods.py -v -k retire_extend --long-running}}
> Fix retirement date setter

- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
{{pytest: -v -k 'test_exists_view'}}
> Remove BZ blockers

- cfme/tests/test_rest.py
@lehinevych - this might introduce a merge conflict but it should be pretty easy to resolve, it only involves renaming of couple of things.
> Fix REST fixture clash

- utils/testgen.py
{{pytest: -k test_provider_crud}}
> Added restricted version filtering

- cfme/tests/cloud/test_instance_power_control.py
{{pytest: cfme/tests/cloud/test_instance_power_control.py -v -k soft_reboot --long-running }}
> Fix test_soft_reboot

- cfme/intelligence/reports/widgets.py
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k rssfeedwidget_crud  --long-running}}
> Fix visibility_obj

- sprout/appliances/static/app-js/my_appliances.js
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/views.py
> [NO TEST] Sprout - Make it possible to specify expiration in the request

- cfme/__init__.py
- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/infrastructure/provider.py
- cfme/web_ui/__init__.py
- cfme/web_ui/menu.py
- cfme/web_ui/tabstrip.py
- fixtures/pytest_store.py
- utils/appliance.py
- utils/mgmt_system/__init__.py
- utils/mgmt_system/openstack_infra.py
- utils/providers.py
- utils/testgen.py
cc @petrblaho , @mcornea
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py -v -k provider_crud --use-provider tripleo --long-running }}
> [WIP] OS Infra integration

- cfme/intelligence/reports/dashboards.py
- cfme/intelligence/reports/ui_elements.py
I hope multidispatch can handle subclasses as well.
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k dashboard_crud --long-running}}
> Fix test_dashboard_crud

- utils/mgmt_system/__init__.py
> remove commited breakpoint :\

- cfme/fixtures/pytest_selenium.py
- cfme/intelligence/reports/ui_elements.py
- cfme/intelligence/reports/widgets.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k menuwidget_crud --long-running }}
> Fix MenuWidget

- artifactor/plugins/reporter.py
- data/templates/test_report.html
{{pytest: cfme/tests/integration/ }}
> Added top10 Exceptions

- cfme/fixtures/pytest_selenium.py
- utils/log.py
- utils/virtual_machines.py
There were some malformed %s-s and I could not longer watch it in the logs.
> Cleanup logging in virtual_machines.py

- cfme/services/catalogs/catalog_item.py
- cfme/web_ui/__init__.py
Issue was, that Angular Select didn't choose the item from list, mentioned during testing the Service Dialog creation.
{{pytest: cfme/tests/infrastructure/test_providers.py cfme/tests/services/test_catalog_item.py -v}}
> Minor fix for AngularSelect

- cfme/web_ui/accordion.py
{{pytest: cfme/tests/integration/ }}
> Fix accordion

- artifactor/plugins/reporter.py
- data/templates/test_report.html
{{pytest: cfme/tests/integration/ }}
> Fixed accuracy and traceback escaping

- cfme/infrastructure/host.py
{{pytest: cfme/tests/infrastructure/test_host.py -v -k multiple_host_good_creds --long-running}}
> Fix host form with angular select

- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/infrastructure/provider.py
- cfme/web_ui/menu.py
- utils/providers.py
Added basis for container providers addition
Added containers top container menu branches
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py -v -k provider_crud --use-provider default --long-running }}
> Providers refactor

- cfme/fixtures/pytest_selenium.py
- cfme/intelligence/reports/ui_elements.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k custom_report --long-running}}
> Fix get_value_by_text() to normalize spaces

- cfme/dashboard.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -v -k 'operation or widget' --long-running }}
> Support the new dashboard widgets

- cfme/infrastructure/host.py
{{pytest: -v -k 'test_multiple_host' }}
> Angular Select changes

- cfme/tests/services/test_orchestration_template.py
{{pytest: -v -k 'test_copy_template'}}
> Add bz blocker

- cfme/services/catalogs/catalog_item.py
{{pytest: -v -k 'test_delete_dialog_before_parent_item'}}
> Apply button fix for catalog item

- cfme/tests/configure/test_about_links.py
- cfme/tests/configure/test_analysis_profiles.py
{{pytest: -v -k  'test_vmanalysis_profile_description_validation  or  test_about_links'}}
> updated forcestream and added bz blocker

- cfme/automate/service_dialogs.py
{{pytest: -v -k 'test_textareabox_dialog_element'}}
> text area locater fix

- cfme/tests/configure/test_server_name.py
{{pytest: -v -k 'test_server_name'}}
> remove bz blocker for test server name

- sprout/appliances/tasks.py
> [NO TEST] Sprout - Paginate trackerbot

- cfme/exceptions.py
- cfme/web_ui/menu.py
- cfme/web_ui/toolbar.py
> Fixed toolbar

- cfme/automate/explorer.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/automate/test_class.py -v -k schema --long-running}}
> AE - Schema button change

- cfme/web_ui/menu.py
{{pytest: -k test_delete_host}}
> Fixed /start menu secondlevs

- cfme/fixtures/pytest_selenium.py
- cfme/intelligence/reports/ui_elements.py
{{pytest: cfme/tests/intelligence/reports/test_menus.py -v -k shuffle --long-running }}
> Update the menu tree editor in Reports

- cfme/web_ui/toolbar.py
Toolbars were broken for single buttons like Tile View and Refresh, this
fixes that.
{{pytest: cfme/tests/cloud/test_provisioning.py --long-running --use-provider rhos5 -k with_attached_disks}}
> Fixes toolbars again

- cfme/configure/access_control.py
Tenant support
{{pytest: -k test_group_crud}}
> Fixed tenant support

- cfme/intelligence/chargeback.py
SSIA. And I also removed one level of the nav tree because it is not necessary.
{{pytest: cfme/tests/intelligence/test_chargeback.py -v --long-running}}
> People are afraid of accordion.tree, so I fixed it

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/control/test_alerts.py -v -k test_alert_vm_turned_on_more_than_twice_in_past_15_minutes --long-running }}
> Fix mail locator

- cfme/web_ui/__init__.py
Attention! This will need some care later because if they are going to flip more infoblocks in that format, it is gonna break on eg. infoblock-by-image, or maybe .title
{{pytest: cfme/tests/configure/test_version.py -v --long-running}}
> Fix InfoBlock to work with yet another type

- cfme/common/provider.py
- cfme/common/vm.py
- cfme/tests/control/test_compliance.py
- docs/conf.py
- fixtures/events.py
- utils/mgmt_system/__init__.py
- utils/virtual_machines.py
{{pytest: --collect-only --use-provider=complete --long-running}}
> Fixing RTD with some imports

- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/web_ui/menu.py
- cfme/web_ui/toolbar.py
> [WIP] - Updating toolbar for 5.5.0.8+

- utils/virtual_machines.py
FYI this is not a "pass" PR, this will enable us to see the place where the error happened exactly.
{{pytest: cfme/tests/cloud_infra_common/test_discovery.py -v --long-running}}
> Do not throw away exceptions' stack during template deployment to see the issue.

- utils/tests/test_varmeth.py
- utils/varmeth.py
* Make sure nobody can eg. redefine default.
* Make an alias for default.
* Make multiple registratins of one function
{{pytest: utils/tests/test_varmeth.py -v}}
> Tweak the default registration for varmeth.

- cfme/services/requests.py
- utils/appliance.py
I picked up the changes @dajohnso put in.
{{pytest: cfme/tests/services/test_request.py -v --long-running }}
Closes #2386
> Fix Requests table

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/cloud_infra_common/test_tag_objects.py -v --long-running}}
> Fix quad title retriever

- cfme/web_ui/menu.py
This is to allow grafting onto the top level and expose some
functionality to help with that
> New menu func

- cfme/tests/infrastructure/test_vm_analysis.py
- fixtures/pytest_store.py
- fixtures/ssh_client.py
- utils/appliance.py
- utils/browser.py
- utils/ports.py
Dave told me there is some weirdness happening. I did some cleanup and will see what can I do with it.
{{pytest: cfme/tests/infrastructure/test_vm_analysis.py -v --long-running}}
> Clean up the appliance stack a bit

- cfme/web_ui/toolbar.py
{{pytest: -k test_expanded_view }}
> Toolbar fixes again

- cfme/common/vm.py
- cfme/web_ui/paginator.py
Works for both 5.4 and 5.5, no ver pick required.
> paginator tweaks

- cfme/services/catalogs/catalog_item.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'not test_provision' -v --long-running}}
> The REST API tests

- utils/api.py
> REST Client: Handle integers

- utils/api.py
> Support virtual attr expansion in REST client

- sprout/appliances/tasks.py
Until now, I was ignoring them in the Celery Flower viewer, but it was time to handle it and remove such failures from the task view.
> Sprout - Handle some common task errors

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/cloud/test_providers.py -v -k provider_crud --long-running}}
> Fix quadicon title getting

- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/containers/__init__.py
- cfme/containers/container.py
- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/provider.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/infrastructure/provider.py
- cfme/tests/containers/test_provider_crud.py
- fixtures/mgmt_system.py
- utils/mgmt_system/__init__.py
- utils/mgmt_system/kubernetes.py
- utils/mgmt_system/openshift.py
- utils/providers.py
- utils/testgen.py
{{pytest: -k 'provider_crud and not rest' -v}}
> Containers UI

- cfme/automate/explorer.py
- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/js.py
- cfme/tests/automate/test_namespace.py
- cfme/tests/configure/test_access_control.py
- cfme/web_ui/__init__.py
- cfme/web_ui/accordion.py
- cfme/web_ui/paginator.py
- requirements.txt
{{pytest: -m crud -v --long-running }}
> Tree -> javascript

- cfme/tests/test_appliance.py
Reverts RedHatQE/cfme_tests#2421
> Revert "Fixed certs for 5.5.0.10"

- cfme/tests/infrastructure/test_providers.py
{{pytest: -k test_provider_add_with_bad_credentials --long-running -v}}
> test_provider_add_with_bad_credentials

- cfme/intelligence/chargeback.py
{{pytest: cfme/tests/intelligence/test_chargeback_assignments.py}}
> Fixed assignments tree

- utils/ssh.py
> Handle SSH timeout to capture the received data before the timeout happened

- cfme/js.py
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/control/test_basic.py -k 'test_tag or basic' --use-provider vsphere55 --long-running}}
> Fix the jstree to work with trees that have no single root node

- fixtures/appliance_update.py
{{pytest: -m smoke --update-appliance -v}}
> Make it possible to update appliances from inside py.test run

- scripts/template_upload_scvmm.py
Here's the first draft.  It works everytime and has decent error checking.  I tried it with all the common mistakes.  NOTE:  Requires the new mgmtsystem\scvmm.py and the pending cfme_data.yaml.
> Initial Attempt.  It works.

- cfme/configure/access_control.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'not test_provision' -v --long-running}}
> Add more rest_api tests

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'rates' -v --long-running -v}}
> Add rate tests

- cfme/intelligence/chargeback.py
{{pytest: -k test_edit_compute_chargeback}}
> Fixed Rates Tree

- cfme/automate/service_dialogs.py
- cfme/exceptions.py
- cfme/js.py
- cfme/tests/automate/test_customization_paginator.py
- cfme/web_ui/__init__.py
* Fix the Service Dialog tree call
* Meaningful message if the Tree is not present
{{pytest: cfme/tests/automate/test_customization_paginator.py cfme/tests/automate/test_namespace.py -v --long-running }}
> Some tree fixes

- cfme/infrastructure/host.py
I took @psav's commit and added the Add button fix.
Closes #2450
{{pytest: -k test_button_on_host --disablemetaplugins blockers --long-running }}
> Fix add host from 55+

- cfme/automate/explorer.py
{{pytest: -k test_provision_from_template_with_attached_disks --use-provider complete}}
> Test provision fixes with tree node

- cfme/services/catalogs/myservice.py
verpick service retirement calendar
{{pytest: cfme/tests/services/test_myservice.py --long-running --disablemetaplugins blockers}}
> Fix date element name change

- cfme/web_ui/toolbar.py
{{pytest: cfme/tests/infrastructure/test_snapshot.py --long-running --use-provider vsphere55}}
> Fix snapshot buttons

- cfme/dashboard.py
{{pytest: cfme/tests/intelligence/test_dashboard.py}}
> Fix RSS test

- cfme/web_ui/toolbar.py
{{pytest: cfme/tests/configure/test_default_views_infra.py}}
> Fix TB button

- cfme/tests/infrastructure/test_advanced_search_vms.py
{{pytest: cfme/tests/infrastructure/test_advanced_search_vms.py -k test_filter_save_cancel --use-provider=complete}}
> Fixed advanced search sample

- utils/mgmt_system/__init__.py
> Take sprout templates in the account

- cfme/web_ui/accordion.py
{{pytest: cfme/tests/services/test_catalog_item.py -v --long-running }}
> Fix the locator to make it work on 5.4

- utils/appliance.py
{{pytest: utils/tests/test_ipappliance.py}}
> Fixed ipappliance

- cfme/services/catalogs/cloud_catalog_item.py
{{pytest: cfme/tests/test_rest.py -k test_edit_service_template --use-provider complete --long-running}}
> Fix service catalog accordion usage

- cfme/configure/configuration/__init__.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_db_backup_schedule.py cfme/tests/configure/test_log_depot_operation.py --long-running}}
> Fixed scheduling

- cfme/configure/about.py
{{pytest: cfme/tests/configure/test_docs.py}}
> Fix docs beginnings

- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
* We don't seem to be able to "click" the element at all with sel.click
so I did it this way
{{pytest: cfme/tests/configure/test_access_control.py cfme/tests/configure/test_log_depot_operation.py --long-running}}
> Stored password

- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/infrastructure/host.py
- cfme/web_ui/form_buttons.py
> Fixed more stored_pw issues

- cfme/js.py
- cfme/tests/automate/test_namespace.py
* Tree did not check properly for expandable items, now it should work properly.
* I did some touches to the namespace test, mainly for readability sake.
> Fix tree and namespace tests

- cfme/tests/cloud_infra_common/test_genealogy.py
> Fix test_vm_genealogy_detected

- cfme/tests/configure/test_access_control.py
{{pytest: cfme/tests/configure/test_access_control.py -k "edit_tag or remove_tag" }}
> Fix tag tests

- cfme/tests/configure/test_access_control.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_access_control.py -v -k "user_edit_tag or user_remove_tag or group_edit_tag or group_remove_tag" --long-running}}
> Fixup AC tags tests

- utils/api.py
{{pytest: cfme/tests/services/test_service_catalogs.py -k 'test_order_catalog_item_via_rest' -v --long-running -v}}
> Change the order of condition for processing the response

- cfme/services/catalogs/catalog.py
{{pytest: cfme/tests/test_ui_problems.py -v -k broken_angular_select --long-running }}
> Catalog can handle deletion without description

- cfme/cloud/instance.py
* Remove visible_tree
* Flatten the tree
* Make it a class
{{pytest: cfme/tests/configure/test_default_filters.py -v --long-running -k cloud }}
> repair the tree navs inside cfme.cloud.instance

- cfme/automate/explorer.py
- cfme/tests/automate/test_class.py
{{pytest: cfme/tests/automate/test_class.py::test_duplicate_class_disallowed}}
> test_class: allow omitting duplicate check

- cfme/automate/explorer.py
- cfme/tests/automate/test_method.py
{{pytest: cfme/tests/automate/test_method.py}}
> test_method: allow omitting duplicate check

- cfme/dashboard.py
- cfme/tests/test_csrf.py
- metaplugins/blockers.py
{{pytest: cfme/tests/test_csrf.py -v }}
> Fix 'Reset dashboard' button xpath and mark it as blocked

- cfme/tests/infrastructure/test_infra_quota.py
{{pytest: cfme/tests/infrastructure/test_infra_quota.py --long-running -v}}
> Add blocker for test_infra_quota

- cfme/automate/explorer.py
- cfme/tests/automate/test_domain_priority.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/automate/test_domain_priority.py -v --long-running }}
> Fix up schema editor for AE.

- cfme/dashboard.py
{{pytest:  -v --long-running cfme/tests/intelligence/test_dashboard.py -k 'test_widgets_operation'}}
> dashboard: fix locator for widget body

- sprout/appliances/migrations/0001_initial.py
- sprout/appliances/migrations/0002_delayedprovisiontask.py
- sprout/appliances/migrations/0003_auto_20141218_1534.py
- sprout/appliances/migrations/0009_appliancepool_provider.py
- sprout/appliances/migrations/0011_auto_20150212_0945.py
- sprout/appliances/migrations/0018_mismatchversionmailer.py
- sprout/appliances/migrations/0021_userappliancequota.py
- sprout/appliances/models.py
- sprout/appliances/views.py
- sprout/sprout/settings.py
Addressed most of the deprecation warnings for 1.10 and 2.0
> [WIP][NO TEST] Sprout - Updates for Django 1.9 + deprecation warnings

- cfme/infrastructure/virtual_machines.py
- cfme/services/workloads.py
- cfme/tests/configure/test_default_filters.py
Anything that had name visible_tree is eradicated.
{{pytest: cfme/tests/configure/test_default_filters.py -v --long-running}}
> visible_tree eradication.

- cfme/fixtures/pytest_selenium.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/web_ui/form_buttons.py
Fix change_stored_password to support angular link
Also:
* Tweak the host analysis test code
* Fixup the blocker
* Handle double alerts
{{pytest: cfme/tests/infrastructure/test_host_analysis.py -v --long-running }}
> Fix change_stored_password to support angular link

- cfme/tests/configure/test_docs.py
{{pytest: cfme/tests/configure/test_docs.py -k 'test_all_docs_present' -v --long-running }}
> test_docs: new doc link labels

- cfme/services/requests.py
{{pytest: cfme/tests/services/test_operations.py --long-running -v}}
> Fix requests button locators

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'tenants' -v --long-running -v}}
> Tenants rest api tests

- cfme/web_ui/paginator.py
{{pytest: cfme/tests/configure/test_visual_cloud.py -v --long-running }}
> paginator: use universal regexp to support some edge cases

- cfme/tests/test_rest.py
- utils/api.py
{{pytest: cfme/tests/test_rest.py -k 'report' -v --long-running -v}}
> Add test for reports

- cfme/infrastructure/pxe.py
{{pytest: -k test_pxe_provision_from_template cfme/tests/infrastructure/test_pxe_provisioning.py --use-provider vsphere55}}
> Fixed a func name

- cfme/common/provider.py
last_refreshed_date is not present until it has been updated
> Fixed a validate error

- cfme/tests/test_rest.py
- utils/api.py
{{pytest: cfme/tests/test_rest.py -k 'test_set_service_owner' -v --long-running -v}}
> Add rest api test for service

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'tag' -v --long-running -v}}
> Add rest api tests for tags

- utils/appliance.py
> Extend update regexp

- cfme/exceptions.py
- cfme/web_ui/paginator.py
- utils/providers.py
{{pytest: cfme/tests/test_utilization.py -k 'test_metrics_collection' -v --long-running}}
> providers: rec_total returns int value now

- data/templates/test_report.html
Just for @mfalesni .............
> Fixed the report js

- markers/meta.py
- utils/__init__.py
> remove old stale kwargify

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -k 'vm' -v --long-running -v}}
> VMs methods testing

- .gitignore
> .gitignore housekeeping

- artifactor/__init__.py
{{pytest: cfme/tests/configure/test_docs.py -v --composite-uncollect}}
> Fix the artifactor json dump to be merged

- artifactor/plugins/reporter.py
- utils/composite.py
{{pytest: -k test_contents cfme/tests/configure/test_docs.py --composite-uncollect}}
> Fix issue after adding new artifact system

- artifactor/__init__.py
- artifactor/plugins/filedump.py
- artifactor/plugins/logger.py
- artifactor/plugins/merkyl.py
- artifactor/plugins/video.py
- fixtures/artifactor_plugin.py
- fixtures/browser.py
- fixtures/qa_contact.py
- fixtures/screenshots.py
- utils/appliance.py
- utils/artifactor_start.py
{{pytest: cfme/tests/distributed/test_appliance_replication.py -v --long-running}}
> Take a screenshot when exiting an appliance CM with an error.

- artifactor/plugins/post_result.py
- artifactor/plugins/reporter.py
- utils/composite.py
* Needed to use the base old_artifacts to generate the composite json
* Needed to not be naughty and return the namespace changes for the
overall test result, not manipulate the dict directly
> Fixed the post_result plugin

- artifactor/plugins/filedump.py
Added backwards compatibility to filedump
> Please....the last change

- cfme/tests/test_rest.py
- utils/api.py
{{pytest: cfme/tests/test_rest.py -k "test_role_assign_and_unassign_feature" -v --long-running -v}}
> Add assign test for roles

- scripts/template_upload_all.py
Blair should probably look over this as well.
> Added scvmm details and regex

- scripts/cleanup_old_vms.py
The known conf race condition is probably happening also there. Also made the error show in the stdout.
> scripts/cleanup_old_vms.py: Fix process_provider_vms(()

- cfme/rest/__init__.py
- cfme/tests/services/test_generic_service_catalogs.py
- cfme/tests/test_rest.py
- utils/api.py
{{pytest: cfme/tests/services/test_generic_service_catalogs.py -k "TestServiceCatalogViaREST" -v --long-running -v}}
> Rest api rework structure, service catalogs collection

- cfme/tests/control/test_actions.py
- fixtures/browser.py
{{pytest: cfme/tests/control/test_actions.py -k 'test_action_initiate_smartstate_analysis' --use-provider 'vsphere55' -v --long-running -v}}
> Fix 'test_action_initiate_smartstate_analysis'

- cfme/rest/__init__.py
- cfme/tests/configure/test_tag_category.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/configure/test_access_control.py -k "TestCategoriesViaREST" -v --long-running -v}}
> Category collection

- cfme/provisioning.py
- cfme/tests/infrastructure/test_instance_analysis.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'vsphere55' -v --long-running}}
> SSA tests for infra instances

- cfme/configure/access_control.py
- cfme/tests/configure/test_access_control.py
New  test_superadmin_tenant_crud test.
{{pytest: cfme/tests/configure/test_access_control.py -v -k "superadmin_tenant"}}
> New Tenant and Project class + first multi tenancy test - test_superadmin_tenant_crud

- cfme/rest/__init__.py
- cfme/tests/configure/test_tag.py
- cfme/tests/test_rest.py
- utils/bz.py
{{pytest: cfme/tests/configure/test_tag.py -k "TestTagsViaREST" -v --long-running -v}}
> Tags collection

- scripts/cleanup_old_vms.py
The VM reaper picks the VMs to delete in parallel, thread per provider. I thought why not also delete per-provider?
> scripts/cleanup_old_vms.py: Also parallelize deleting

- cfme/tests/cli/test_evmserverd.py
- utils/ssh.py
> Fixup the EVM status getting + test tweaks

- cfme/rest/__init__.py
- cfme/tests/services/test_rest_services.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running}}
> Services rest api tests

- cfme/rest/__init__.py
- cfme/tests/configure/test_access_control.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/configure/test_access_control.py -k "TestRolesViaREST" -v --long-running}}
> roles collection of rest api

- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v --long-running}}
> Reports import and run

- cfme/cloud/stack.py
- cfme/configure/settings.py
- cfme/services/catalogs/orchestration_template.py
- cfme/services/requests.py
- cfme/tests/services/test_provision_stack.py
> Retire stack test automated

- cfme/configure/settings.py
- cfme/tests/services/test_provision_stack.py
Move to simple function for default views as an assist for #2573
> Move to simple function for default views

- scripts/template_upload_scvmm.py
This will permafix the upload credential issue without breaking other places that use the same credential file entries.
> Changed the way scvmm user is generated so the creds work everywhere

- cfme/tests/configure/test_access_control.py
Super admin can CRUD projects under tenant
{{pytest: cfme/tests/configure/test_access_control.py -v -k "test_superadmin_tenant_crud or test_superadmin_tenant_project_crud"}}
> Test name: test_superadmin_tenant_project_crud

- cfme/rest/__init__.py
- cfme/tests/services/test_rest_services.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running}}
> Service templates rest tests

- cfme/tests/services/test_rest_services.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/services/test_rest_services.py -k "TestServiceRESTAPI" -v --long-running}}
> Service owners REST API

- cfme/tests/infrastructure/test_vm_ownership.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/infrastructure/test_vm_ownership.py -k "TestVmOwnershipRESTAPI" -v --long-running}}
> Relocate vm owner test

- cfme/tests/infrastructure/test_provisioning_rest.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py  -v --long-running}}
> Provision via rest

- cfme/rest/__init__.py
- cfme/tests/infrastructure/test_rest_automation_request.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/infrastructure/test_rest_automation_request.py -v --long-running}}
> Automation request rest api

- cfme/tests/infrastructure/test_rest_providers.py
- cfme/tests/test_rest.py
{{pytest: cfme/tests/infrastructure/test_rest_providers.py -v --long-running}}
> Provider rest tests

- cfme/tests/configure/test_default_views_infra.py
{{pytest: -v -k 'test_hybrid_view or test_graph_view or test_tabular_view'}}
> Add bz blocker for view test cases

- cfme/rest/__init__.py
- cfme/tests/configure/test_access_control.py
- cfme/tests/configure/test_rest_access_control.py
{{pytest: cfme/tests/configure/test_rest_access_control.py -v --long-running}}
> Group and Users rest collection

- sprout/appliances/tasks.py
Appliance deletion is handled asynchronously, other deletiong waitings are synchronous because I did not want to interfere with the structure of the task.
> [WIP][NOTEST] Added waiting for deletion to Sprout

- scripts/dockerbot/check_prs.py
- scripts/dockerbot/dockerbot.py
Add '{{ streams: downstream-5.5, upstream }}' to PR's body
> [NOTEST] Allow filtering streams in PRT runs

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
Signed-off-by: dmisharo <dmisharo@redhat.com>
> Covering not automated test cases in Control

- scripts/dockerbot/check_prs.py
This reverts commit 47091a91ca94a649dced0ce129f7e9b09b947536.
> Use correct objects to get PR data

- cfme/tests/configure/test_tag.py
- utils/api.py
{{pytest: cfme/tests/configure/test_tag.py -k "test_assign_and_unassign_tag" -v --long-running }}
> Tags assigning

- cfme/tests/infrastructure/test_instance_analysis.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'rhevm34' -v --long-running}}
> SSA: allow testing multiple images on providers

- data/templates/template_tester_report.html
- scripts/latest_template_tester_report.py
Template tester test report
* Generates the html report if there is any template tested
within last 24 hours. This can be executed as the downstream
job for templatest_tester_ jobs in Jenkins.
* Email notification with this report attached will be configured
in the Jenkins job.
> Template tester report

- requirements.txt
- scripts/providers.py
- utils/__init__.py
Requires https://github.com/RedHatQE/mgmtsystem/pull/13 to be merged and released first.
> Add a script to control the floating IPs for RHOS instances.

- cfme/common/vm.py
- cfme/control/explorer.py
- cfme/control/snmp_form.py
- cfme/tests/control/test_alerts.py
- cfme/web_ui/__init__.py
- fixtures/snmp.py
- utils/providers.py
- utils/snmp_client.py
- utils/ssh.py
{{pytest: 'cfme/tests/control/test_alerts.py -v --long-running'}}
> Add a C&U-based alert test

- cfme/fixtures/pytest_selenium.py
- utils/browser.py
Supersedes #2684 
{{pytest: cfme/tests/control/test_import_policies.py -v}}
> Resolve the Selenium text-file handling problems for ever

- cfme/tests/configure/test_access_control.py
Test CRUD operations for CFME child tenants, where several levels of tenants are created. 
{{pytest: cfme/tests/configure/test_access_control.py -v -k "test_superadmin_child_tenant_crud"}}
> Test name:  test_superadmin_child_tenant_crud

- cfme/fixtures/storage.py
- scripts/install_netapp_lib.py
- utils/appliance.py
Before, the fixture that set up the tests called the script using subprocess, which is yikes. I moved the code in the appliance.py.
> utils/appliance.py: Move the Netapp setup in the class

- cfme/configure/configuration/__init__.py
- cfme/fixtures/pytest_selenium.py
- cfme/tests/configure/test_log_depot_operation.py
- fixtures/soft_assert.py
I also improved the test by adding soft asserts and more verbose error logging since that was not touched for ages.
> When unknown_unknown file faced, it is captured in logs

- sprout/appliances/tasks.py
- utils/appliance.py
* Disable swap for configured appliances.
* Consolidate hte templatizing code (Sprout now calls the generic method rather than doing it in the task).
"
> Disable swap for configured appliances.

- cfme/containers/__init__.py
- cfme/containers/pod.py
- cfme/containers/provider.py
> Fix containers

- cfme/rest/__init__.py
> Remove the skips in cfme/rest/__init__

- cfme/tests/infrastructure/test_instance_analysis.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'rhos7-ga' -v --long-running}}
> Add ssa tests for openstack VM

- cfme/tests/infrastructure/test_host_drift_analysis.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_host_drift_analysis.py --use-provider 'rhevm34' -v --long-running}}
> Ssa host drift: wait for tasks to complete

- utils/appliance.py
- utils/db.py
- utils/tests/test_ipappliance.py
So, in October, there was a split in database, splitting some information about providers to a separate table. This needed to be taken care of.
> Fix the managed providers retrieval

- cfme/tests/control/test_import_policies.py
- data/ui/control/invalid.yaml
> Implemented test import invalid yaml file in Control tab

- data/templates/template_tester_report.html
*  added another cell for the table row with
status passed/failed.
> added extra cell for status (passed/failed)

- cfme/tests/infrastructure/test_vm_retirement_rest.py
- utils/api.py
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py -v --long-running}}
> Retire vm via rest

- cfme/tests/infrastructure/test_provisioning_dialog.py
Provisioning is supposed to work.  Let's run it through and see what issues it has.  I have the three tuple items in cfme_data which it requires.  Is there anything else I'm supposed to change?
> Removed the Skip SCVMM filter.  Provision should work.

- scripts/dockerbot/pytestbase/get_keys.py
- scripts/dockerbot/pytestbase/setup.sh
- scripts/dockerbot/pytestbase/verify_commit.py
It seems trying twice is not helping, run Fj8cCYe5:
```
Running the command - try 1 of 5...
gpg: requesting key 245FFF93 from hkp server keys.gnupg.net
gpg: requesting key 4093CFFD from hkp server keys.gnupg.net
gpg: requesting key 43129149 from hkp server keys.gnupg.net
gpg: requesting key 7EBCD0CB from hkp server keys.gnupg.net
gpg: requesting key A51C6CDF from hkp server keys.gnupg.net
gpg: requesting key D8BA837E from hkp server keys.gnupg.net
gpg: requesting key 2F5B6E15 from hkp server keys.gnupg.net
gpg: requesting key B6808EF1 from hkp server keys.gnupg.net
gpg: requesting key 9CE17B57 from hkp server keys.gnupg.net
gpg: requesting key 7912E5B8 from hkp server keys.gnupg.net
gpg: requesting key 866F7558 from hkp server keys.gnupg.net
gpg: requesting key 6F2C7377 from hkp server …
```
> gpg: try up to 10 times to fetch keys

- cfme/tests/automate/test_vmware_methods.py
There was some domain mishap and also removed 5.2 support.
{{pytest: cfme/tests/automate/test_vmware_methods.py -v --disablemetaplugins blockers }}
> Fixup the test_vmware_methods.py

- cfme/tests/services/test_myservice.py
To ensure that browser is opened before tests
> Browser open method added

- scripts/latest_template_tester_report.py
Added 'wait_for' method to get all the images uploaded.
* wait for all the images to be uploaded on the
latest directory per stream.
* if there are no new images are added after wait
timeout, then it creates the report.
> Added 'wait_for' method to get all the images uploaded.

- cfme/rest/__init__.py
- cfme/tests/infrastructure/test_rest_templates.py
{{pytest: cfme/tests/infrastructure/test_rest_templates.py -v --long-running}}
> Templates via rest

- cfme/tests/infrastructure/test_vm_rest.py
{{pytest: cfme/tests/infrastructure/test_vm_rest.py -v --long-running }}
> Test delete vm via rest

- cfme/common/vm.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py -k 'test_ssa_files' --use-provider='rhevm34' --long-running -v}}
> SSA: scan files

- sprout/appliances/models.py
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/templatetags/appliances_extras.py
* Extend SCVMM power states
* Add Openstack error state
* A bit of eyecandy in the My Appliances view
Needs https://github.com/RedHatQE/mgmtsystem/pull/11 to be merged for unleashing the functionality. But does not depend on it.
> Sprout - Power state update

- cfme/web_ui/__init__.py
this also replaces a missuse of the method in Table Rows
> cmfw.web_ui - turn the convert_header helper method into a function

- cfme/web_ui/__init__.py
when we dont have the cache loaded, we dont want to update it either
> fix Table._update_cache - work when not cached

- cfme/tests/configure/test_log_depot_operation.py
add anon_ftp to permitted methods
> add anon_ftp to permitted methods

- cfme/web_ui/__init__.py
* Removed the Timelines object as it was
* Unreliable
* Replaced with jstimelines
* Updated docs to reflect modules in web_ui
> Removed Timelines, update docs

- cfme/intelligence/reports/dashboards.py
- cfme/tests/intelligence/reports/test_widgets.py
@psav, @lehinevych please review
> Attempt to fix test_widgets. Supersedes PR #2507

- cfme/intelligence/reports/ui_elements.py
{{pytest: cfme/tests/intelligence/reports/test_widgets.py  -k test_widgets_on_dashboard --long-running -v }}
> test_widgets_on_dashboard fix

- sprout/appliances/urls.py
- sprout/appliances/views.py
I will need to sync data from "old" sprout to "new" sprout.
> [WIP] Sprout - Integration api point

- cfme/common/vm.py
- cfme/web_ui/search.py
{{pytest: cfme/tests/cloud_infra_common/test_discovery.py --use-provider 'vsphere55' -v --long-running}}
> find_quadicon: speed up instance lookup using quick search

- scripts/template_upload_all.py
- utils/trackerbot.py
- utils/version.py
Update template uploader naming for downstream nightly
> Add 56z and downstream nightly name-matching

- scripts/cleanup_edomain_templates.py
- scripts/template_upload_rhevm.py
- utils/net.py
* the get_mgmt(provider).api is added
* added method 'is_pingable(ip)' to check if provider IP
is reachable, if not reachable then 'continue' to next
available provider.
* changed the edomain maintenance status, as edomain needs
to be in active state to access api data.
> get the api connection handle for provider with mgmt_system

- cfme/cloud/provider.py
- cfme/common/vm.py
- cfme/infrastructure/provider.py
{{pytest: cfme/tests/cloud_infra_common/test_discovery.py --use-provider 'vsphere55' -v --long-running}}
> find_quadicon: handle cloud instances and fix for archived/orphaned lookups

- cfme/tests/cloud_infra_common/test_tag_visibility.py
> Tag visibility testcases

- scripts/latest_template_tester_report.py
* added wait for images upload to 'latest' web  directory.
* added wait for templates upload on providers.
* wait will be ignored if there are untested 'providertemplates'.
> add check for missing images for latest templates per stream.

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_log_depot_operation.py
- utils/ftp.py
Change functionality to add anonymous log depot test. Use incoming folder, like upload, because this structure now using in cfme
> add anonymous log depot test

- fixtures/prov_filter.py
Disabled tag now skips provider
> Disabled tag now skips provider

- scripts/update_rhel.py
- scripts/update_template.sh
- utils/appliance.py
Needed some finishing touches.
> Final fixup of the update script

- cfme/tests/infrastructure/test_vm_retirement_rest.py
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py -v --long-running }}
> Fix uncollect condition and delete bz blocker

- cfme/tests/infrastructure/test_esx_direct_host.py
* Direct host tests were not using testgen as a result filtering and
test assignment would not honour --use-provider flags
* Tests are not testgen-ified and no longer rely on data from cfme_tests
or use the utils.providers.get_crud
> Testgen directhost

- cfme/web_ui/listaccordion.py
Required for @nachandr 's further work.
> cfme/web_ui/listaccordion.py: Enable checking of the selection status.

- cfme/tests/infrastructure/test_provisioning.py
* Fixed the typo for mgnt_system to mgmt_system
> Fix import mgmt_system module error in test_provision.

- utils/appliance.py
{{pytest: cfme/tests/distributed/test_appliance_replication.py -k test_external_database_appliance}}
> Fixed another cache invalidate

- cfme/automate/provisioning_dialogs.py
- cfme/services/catalogs/catalog.py
- cfme/services/catalogs/catalog_item.py
{{pytest: cfme/tests/services/test_service_catalogs.py -v -k no_template_catalog_item --use-provider vsphere55}}
> Catalog Item: Ensure it passes strings for deps.

- scripts/latest_template_tester_report.py
* added scvmm for proevider template test results.
> Include  scvmm providers in email reporting.

- scripts/cleanup_edomain_templates.py
* check for ovirt-engine service before connecting to the rhevm api.
> Add check for ovirt-engine service before connecting to rhevm api.

- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/service_catalogs.py
{{pytest: cfme/tests/services/test_service_catalogs.py -v - k "order_catalog_item or order_catalog_bundle" }}
> Fixup another multimethod woes

- cfme/tests/test_rest.py
{{pytest: cfme/tests/test_rest.py -v --long-running}}
> [FIX] Scan method

- cfme/web_ui/__init__.py
SortTable changed a bit.
{{pytest: cfme/tests/automate/test_provisioning_dialogs.py -v -k sorting}}
> [FIX] Fixup for 5.4.5.2

- cfme/dashboard.py
{{pytest: cfme/tests/intelligence/test_rss.py -k verify_rss_links }}
> Fix for test_verify_rss_links 

- cfme/tests/infrastructure/test_advanced_search_host.py
- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/tests/infrastructure/test_advanced_search_vms.py
- fixtures/browser.py
* Test that invokes an error triggers browser quit to secure the correct environment for next tests
* addfinalizer decorators
* pytest.sel instead of from cfme.fixtures import pytest_selenium as sel
> A couple of advanced search touches

- cfme/tests/infrastructure/test_instance_analysis.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py -k 'test_ssa_template' --use-provider='vsphere6-nested' --long-running -v}}
> SSA for templates

- scripts/latest_template_tester_report.py
* If new providers are updated while wait, then skip the
wait process.
> Skip wait, when untested providers are available.

- cfme/cloud/instance.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud_infra_common/test_power_control_rest.py
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py -v --long-running }}
> Power control tests for cloud and infra providers

- scripts/template_upload_all.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_scvmm.py
- scripts/template_upload_vsphere.py
* added thread for each script, to upload the template
on all the provders at the same time.
> Parallelize the template_upload on providers per provider_type.

- scripts/template_upload_scvmm.py
> [FIX] Remove Customization from Template Creation

- cfme/dashboard.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -k 'test_verify_rss_links or test_widgets_operation'}}
> fix getting widget _content_type

- scripts/clone_template.py
* add host_group attributes for deploy_args.
> Fix scvmm deploy template.

- utils/version.py
Until I figure how to make this a "rule" to account for any number, placing a hardcoded value there.
> utils/version.py: An additional number in suffix

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_db_backup_schedule.py
Change locator. Change wait mechanizm for db backup schedule
> [FIX] fix test schedule db backup.

- cfme/configure/tasks.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/virtual_machines.py
- cfme/provisioning.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/web_ui/__init__.py
- utils/appliance.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py -k "test_drift_analysis" --use-provider 'vsphere55' -v --long-running}}
> Ssa: check drift history for instances

- cfme/configure/tasks.py
- cfme/infrastructure/datastore.py
- cfme/provisioning.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/web_ui/__init__.py
- utils/appliance.py
- utils/bz.py
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'vsphere55' -v --long-running -k "test_ssa_vm"}}
> SSA: check services

- cfme/fixtures/tag.py
- cfme/tests/services/test_orchestration_template.py
{{pytest: -v -k 'test_edit_tags or test_remove_tags'}}
>  Test for Orchestration Template edit and remove tag 

- scripts/latest_template_tester_report.py
* added the new line for missing template to format the report.
> Add new line for missing template to format the report.

- utils/tests/test_version.py
- utils/version.py
* Suffixes now have much more programmatical approach to parse
* Added some unittests for utils/version.py
> utils/version.py: Streamline the suffix processing

- cfme/common/provider.py
- cfme/middleware/__init__.py
- cfme/middleware/provider.py
- cfme/tests/middleware/test_provider_crud.py
- cfme/web_ui/menu.py
- conf/cfme_data.yaml.template
- conf/credentials.yaml.template
- fixtures/mgmt_system.py
- scripts/dockerbot/dockerbot.py
- utils/providers.py
- utils/testgen.py
Account for discrepancy in Provider/Manager wording https://issues.jboss.org/browse/HAWKULAR-1062
> Add Hawkular provider support with improvements from psav and mfalesni

- data/utils/cfmedb_set_config.rbt
- utils/appliance.py
{{pytest: cfme/tests/configure/test_ntp_server.py}}
> Added new method for getting + setting yaml config on 5.6

- utils/log.py
When the formatter change occured, all the log calls were updated to be "conforming to the norm". However, the artifactor logger was optimized for the old way, and it was optimized so much it did not digest the *args at all. This tries to rectify the issue by doing the formatting on the client side. If we ever decide to do something special with the params inside artifactor, this will need to be changed. But I hope it won't be.
> Try fixing artifactor NOT logging things properly

- utils/providers.py
This will be useful in some CI setups that will require generating provider data based on the environment. With this extension, it will be possible to just place credentials in the cfme_data yaml, which will make the conf setup simple, just generate cfme_data.local.yaml. So these alternatives are possible right now:
```yaml
management_systems:
provider_key:
credentials: mycredentials  # Which will retrieve them from credentials.(e)yaml
```
Or:
```yaml
management_systems:
provider_key:
credentials:
username: foo
password: bar  # Credentials specified directly in the cfme_data
```
It should work for all credentials keys inside the provider's definition, I think I've replaced all the function calls that resolve it.
@rrasouli This might help you in your setup, you can make a script that will …
> utils/providers.py: Enable embedded credentials

- cfme/configure/configuration/__init__.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py}}
> Added Bootstrap Switch

- cfme/containers/provider.py
- cfme/tests/containers/test_provider_crud.py
CM ENV1 has been added to our yamls; this is a minimal fix just so that we can get containers automation running in jenkins again
> Minimal fix for containers crud

- cfme/tests/test_appliance.py
- utils/log.py
* test iptables is retired as iptables is no longer running, seems to
have been replaced by firewalld
* fixed log issue
* fixed issue with evmserverd start detection
> Fixed a few smoke tests

- cfme/infrastructure/provider.py
{{pytest: cfme/tests/infrastructure/test_providers.py -k test_provider_crud}}
> Fixed some element changes

- cfme/configure/configuration/__init__.py
{{pytest: cfme/tests/automate/test_common_methods.py -k test_vm_retire_extend}}
> Added fix for new server roles

- cfme/infrastructure/provider.py
- cfme/web_ui/menu.py
{{pytest: -k test_provider_crud cfme/tests/infrastructure/test_providers.py}}
> Fix for Hosts/Nodes filename change

- scripts/latest_template_tester_report.py
* changes done to this file, to be inline with groovy
scripts on cfme-qe-yamls. the groovy runs on master
node unlike other scripts and this change helps the
current groovy scripts to skip the slave node lookup.
> change the report format to handle master/slave config.

- cfme/dashboard.py
- cfme/web_ui/menu.py
This will get upstream testable again owning to older builds right now
> Fix for upstream

- cfme/middleware/provider.py
Added mgmt_system stats.
Used "_num_db_generic" inherited methods to query database.
{{pytest: cfme/tests/middleware/test_middleware_provider.py -v --use-provider complete }}
> Added new db query methods for middleware provider.

- cfme/cloud/instance.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud_infra_common/test_power_control_rest.py
- cfme/tests/infrastructure/test_vm_retirement_rest.py
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py -v --long-running}}
> Reset method and modify retirement

- cfme/tests/control/test_basic.py
> Fix for test_alert_crud

- cfme/infrastructure/provider.py
{{pytest: cfme/tests/infrastructure/test_providers.py -v --use-provider scvmm --use-provider rhevm35 --use-provider vsphere55-nested --use-provider rhos_uc --use-provider rhos7-ga}}
> Fix the Infra provider add form

- utils/appliance.py
* as mentioned in https://github.com/ManageIQ/manageiq/issues/8325
added wait for evmservered status before running any other commands,
tested recent templates on local env with this change.
> add check for evm service before running postgres commands.

- scripts/template_upload_all.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_vsphere.py
* users outside cfme-qe team can upload templates,
from any streams(upstream, downstream_542 etc..) on
any of their provider. the provider detail needs to
be specified in the yaml format to the jenkins-job
as text parameter(provider_data).
> upload cfme template to provider outside cfme-qe infra.

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_default_views_infra.py}}
> Fixed button group

- cfme/configure/configuration/__init__.py
{{pytest: cfme/tests/cloud_infra_common/test_tag_objects.py -k test_tag_item_through_details}}
> Fix tag UI changes

- cfme/dashboard.py
- cfme/web_ui/menu.py
* change the dropdown menu element.
* make ui changes inline with 5.6 latest version.
> Fix upstream UI changes.

- cfme/configure/tasks.py
- cfme/tests/control/test_actions.py
{{pytest: -k test_action_initiate_smartstate_analysis --long-running}}
> Fix tabs names

- cfme/tests/configure/test_zones.py
* Zone message changed from version 5.6+
> Fixed zone message

- cfme/tests/configure/test_visual_infra.py
* Function moved to be a class attribute
{{pytest: cfme/tests/configure/test_visual_infra.py}}
> Fixed start_page test

- cfme/tests/infrastructure/test_providers.py
* Flash message update for 5.6
{{pytest: -k test_add_cancelled_validation cfme/tests/infrastructure/test_providers.py}}
> Fixed flash message

- cfme/middleware/provider.py
Fixing failing tests by this commit.
> [WIP] Choose 'List View' of middleware providers before navigating into details.

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
@psav, @mfalesni please review
> New CRUD tests for Container Image policies

- cfme/common/__init__.py
- cfme/middleware/provider.py
- cfme/tests/middleware/test_middleware_provider.py
Added new class to validate Properties section in provider's UI, call validation in crud test.
> Added new class Validatabe to be extended by Middleware provider.

- scripts/clone_template.py
- scripts/template_upload_all.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_vsphere.py
* changes done to clone_template and upload
scripts to deploy the template upon template
upload successful.
> allow cfme template deploy on non cfmeqe providers.

- scripts/dockerbot/pytestbase/Dockerfile
> Update dependencies in Dockerfile

- cfme/tests/test_login.py
In 5.6 the new message is "Incorrect username or password".
> [FIX] - Fix flash message for incorrect login

- cfme/fixtures/pytest_selenium.py
- cfme/js.py
> Fix ajax in 5.5 and lower

- cfme/tests/test_appliance.py
> Fix test_evm_running

- cfme/tests/test_appliance.py
{{pytest: -k test_journald_running -v }}
> Add test_journald_running

- utils/__init__.py
this is part of the move to discard classproperty
> turn deferred_verpick into a descriptor

- scripts/clone_template.py
- scripts/template_upload_all.py
- scripts/template_upload_vsphere.py
* changed the provider_data arg to except the local file path
> update provider_data to read from file path.

- cfme/fixtures/pytest_selenium.py
- cfme/intelligence/reports/reports.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/configure/test_server_roles.py
- cfme/tests/configure/test_workers.py
- cfme/tests/control/test_import_policies.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/intelligence/test_download_report.py
{{pytest: cfme/tests/configure/test_log_depot_operation.py cfme/tests/configure/test_server_roles.py  cfme/tests/configure/test_workers.py  cfme/tests/control/test_import_policies.py cfme/tests/infrastructure/test_provisioning_dialog.py -v --long-running}}
> Nuke sel.go_to

- cfme/common/__init__.py
- cfme/services/catalogs/myservice.py
- cfme/tests/automate/test_buttons.py
- cfme/tests/cloud_infra_common/test_genealogy.py
- cfme/tests/cloud_infra_common/test_tag_visibility.py
- cfme/tests/cloud_infra_common/test_vm_ownership.py
- cfme/tests/configure/test_workers.py
- cfme/tests/infrastructure/test_config_management.py
- cfme/tests/infrastructure/test_set_default_filter.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/tests/infrastructure/test_vm_ownership.py
- cfme/tests/intelligence/test_chargeback_assignments.py
- cfme/tests/test_ui_problems.py
`assert False, "warning message" => "warning message"`
whereas
`assert (False, "warning message") => nothing; it's always True`
> Fix false positive asserts

- cfme/common/__init__.py
- cfme/middleware/__init__.py
- cfme/middleware/deployment.py
- cfme/middleware/provider.py
- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/web_ui/menu.py
* Added deployment page
* Added nav support for deployment and server page from provider
* Added tests for deployment
* Modified root middleware root menu to list `List View` all the time.
* Added `SummaryPage` class to give summary page table details
> Added deployment page and server menu nav in middleware

- cfme/cloud/provider.py
- cfme/common/provider.py
- utils/providers.py
{{pytest: -k test_provider_crud --use-provider=rhos7-ga}}
> Fix OpenStack AMQP

- cfme/cloud/provider.py
- cfme/common/provider.py
- utils/providers.py
{{pytest: cfme/tests/cloud/test_providers.py -k crud -v --use-provider gce}}
Blocker https://github.com/ManageIQ/manageiq/pull/2598 (https://bugzilla.redhat.com/show_bug.cgi?id=1326585)
> GCE provider

- cfme/web_ui/menu.py
{{pytest: -k test_provider_crud --use-provider rhos7-ga}}
> Fixed menu

- cfme/tests/cloud_infra_common/test_genealogy.py
> Fix geneaology typo

- sprout/appliances/models.py
- sprout/appliances/tasks.py
- sprout/sprout/log.py
- sprout/sprout/settings.py
Sprout now stores metadata where applicable and uses them to claim back appliances that were lost.
> [WIP][NOTEST] Sprout - Use metadata to salvage appliances

- scripts/template_upload_rhevm.py
* sometimes duplicate auto-tmp-{random alphanumeric} names created,
which caused the different temporary template picked while
creating the temporary vm, its a bug with existing format.
this patch is a fix for that issue.
> replace random aplhanumerica name for templates with template name.

- cfme/configure/configuration/__init__.py
- cfme/fixtures/pytest_selenium.py
- cfme/js.py
- data/patches/autofocus.js.diff
- data/patches/miq_application.js.diff
- utils/ssh.py
Update MiqQE checks, refactoring
Fix tag crud and category crud in 5.6
{{pytest: -k "test_alert_profile_crud or test_tag_crud or test_category_crud" --long-running -v }}
> Add js debounce check, fix tag crud and category crud

- dockerfiles/cfme_tests_img/Dockerfile
- dockerfiles/cfme_tests_img/xstartup
Dockerfile for automated builds of cfme_tests preconfigured workstation environment.
> [WIP] Dockerfile for cfme_tests environment

- dockerfiles/cfme_tests_img/Dockerfile
Including username to FOR directive, because automated build is failing.
> [WIP] Dockerfiles - changed FROM directive to have username in it

- cfme/__init__.py
- cfme/cloud/provider.py
- cfme/common/provider.py
- cfme/containers/provider.py
- cfme/infrastructure/provider.py
- cfme/web_ui/form_buttons.py
- cfme/web_ui/menu.py
Fix services menu in 56
{{pytest: -k "test_provider_crud and not edit and not rest" --use-provider complete }}
> Fix provider crud in 55 and 56

- scripts/cleanup_old_vms.py
* added method to check .vmx file modified
time. as the vmware python api does not
provider vm creation time attrib.
> check vm config modified time.

- cfme/middleware/datasource.py
- cfme/middleware/provider.py
- cfme/tests/middleware/test_middleware_datasource.py
Added new tests for listing them.
> Added new object for Middleware Datasources.

- cfme/tests/configure/test_log_depot_operation.py
Test log collect disabled button
{{pytest: cfme/tests/configure/ -k collect_unconfigured -v}}
> Test log collect disabled button

- cfme/tests/automate/test_vmware_methods.py
- cfme/tests/cloud/test_stack.py
- cfme/tests/configure/test_db_backup_schedule.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/infrastructure/test_infra_quota.py
- fixtures/parallelizer/parallelizer_tester.py
- fixtures/rbac.py
- markers/uncollect.py
- utils/providers.py
- utils/testgen.py
{{pytest: cfme/tests/infrastructure/ -k "test_provider_crud and not rest" --use-provider nested-rhevm35 }}
> Fix adding a rhevm prov with no c&u creds

- cfme/infrastructure/config_management.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
- cfme/web_ui/menu.py
{{pytest: cfme/tests/services/test_config_provider_servicecatalogs.py}}
> Ansible service integration

- cfme/tests/infrastructure/test_providers.py
- utils/blockers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k host_name_required_validation}}
> GH Blockers update, mark a test

- cfme/web_ui/__init__.py
Middleware has new system of putting IDs in the quads, so locators adjusted
> YAQT: Yet Another Quadicon Type

- cfme/tests/infrastructure/test_provider_discovery.py
New branch for provider discovery after major mess up with git commits, used more logical name.
{{pytest: cfme/tests/infrastructure/test_provider_discovery.py -v --use-provider complete}}
> Initial commit for new provider discovery

- cfme/middleware/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_server.py
> Added new testcase for Middleware Servers details page validation. 

- cfme/tests/configure/test_default_views_infra.py
{{pytest: -v -k 'test_hybrid_view or test_graph_view or test_tabular_view'}}
> Remove bz blocker

- cfme/configure/configuration/__init__.py
- cfme/provisioning.py
{{pytest: cfme/tests/infrastructure/test_provisioning.py -v -k test_provision_from_template}}
> Successful provisioning message text change

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_analysis_profiles.py -v -k test_analysis_profile_description_validation}}
> Fix DynamicTable

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
Added a new test for container image conditions.
> Test container image condition crud

- cfme/dashboard.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -v -k test_widgets_reorder}}
> Fix dashboard locators

- utils/appliance.py
* get_yaml_file() call replaced with get_yaml_config() as the file
doesn't exist on later appliances
> Changed address getter to use get_yaml_config

- data/qe_event_handler.xml
* fixes the test_evm_automate_convert failing to
find the file.
> add the qe_event_handler file to data directory.

- requirements.txt
We mention jupyter (ipython notebook) in the video sessions and its the recommended tool for debugging. It only makes sense to make it part of our requirements. It would also make the onboarding easier since some people reach out to us with questions regarding its installation...
> [WIP][NOTEST] Add jupyter to requirements

- cfme/tests/configure/test_visual_cloud.py
- cfme/web_ui/menu.py
{{pytest: cfme/tests/configure/test_visual_cloud.py -v -k test_start_page}}
> Fix menu check

- cfme/tests/cloud_infra_common/test_events.py
{{pytest: cfme/tests/cloud_infra_common/test_events.py -v --long-running --use-provider complete --event-testing}}
> Fix test_events.py

- cfme/infrastructure/pxe.py
{{pytest: cfme/tests/services/test_pxe_service_catalogs.py}}
> PXE UI change

- utils/ssh.py
* In a previous commit a mistake was made during a copy paste
> Fixed a bug where tuples were being created

- utils/appliance.py
* Why make a circular loop, when we can do this ;)
> Fixed a bad dep call

- cfme/web_ui/paginator.py
{{pytest: cfme/tests/automate/test_customization_paginator.py -v}}
> Fix paginator

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
> Fix retirement tests

- docs/getting_started.rst
- docs/guides/container.rst
- utils/appliance.py
- utils/quote.py
- utils/ssh.py
DONE:
* Prefixing with docker exec with proper quoting
* file upload and download via intermediate location
* Pass the fact it is running in container using env.yaml
> SSH container support

- cfme/web_ui/paginator.py
{{pytest: '''cfme/tests/infrastructure/test_providers.py::test_providers_discovery[vsphere55]'' -v'}}
> Fix paginator selector

- cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k "test_host_name_required_validation or test_name_required_validation or test_type_required_validation"}}
> Fix validation of omitted fields

- cfme/tests/configure/test_log_depot_operation.py
{{pytest: cfme/tests/configure/ -k collect_log_depot -v}}
> dynamic log depot machine

- cfme/cloud/provider.py
- cfme/tests/cloud/test_providers.py
{{pytest:  cfme/tests/cloud/test_providers.py -v -k test_region_required_validation}}
> Fix cloud provider form

- cfme/common/__init__.py
@jkandasa can you please check out if this keeps working? Thanks!
> Polish some of the MW team code

- cfme/web_ui/flash.py
Now when you do eg. `assert_message_match()` and if it does not match, it will modify the exception and do:
```
FlashMessageException: No matching flash message for 'asdf'
Present flash messages:
success: Infrastructure Provider "myprovider" was saved
```
{{pytest: cfme/tests/infrastructure/test_providers.py -v --use-provider complete}}
> On FlashMessageException dump all flash messages displayed

- utils/appliance.py
* this will avoid to NoneType Error Exception.
> return the appliance address if db is None

- fixtures/nelson.py
- requirements.txt
Reverts ManageIQ/integration_tests#3144
> Revert "Update Sphinx dependency"

- cfme/web_ui/menu.py
{{pytest: '''cfme/tests/containers/test_relationships_tables.py::test_services_rel[cm-env1-Nodes]'' -v'}}
> Fix Container Services menu navigation

- scripts/template_upload_all.py
* changes made to template_upload_all to sync the format
with CI team config.yaml.
> get stream from provider_data to sync with CI team format.

- cfme/infrastructure/pxe/__init__.py
- cfme/infrastructure/pxe/base.py
- cfme/infrastructure/pxe/db.py
- cfme/infrastructure/pxe/ui.py
first variant, requesting scruinity
> switch to sentaku 0.2.0 external implementations

- cfme/tests/test_db_migrate.py
- utils/appliance.py
Need to investigate this: http://pastebin.test.redhat.com/374498
Edit: KeyError exception on failure fixed by #2978 
{{pytest: -k test_db_migrate -v}}
> Add DB migrate test

- scripts/template_upload_rhevm.py
* for rhevm-image-uploader-3.6* rhevm-image-uploader command is
not available. changed the template uploader to pick the
command based on rhevm-image-uploader rpm version.
> execute engine-image-uploader based on rhevm-image-uploader version.

- cfme/dashboard.py
- cfme/web_ui/menu.py
Upstream nav needed some help, this work taks some of the ideas in
amavinag's branch and implements them slightly differently.
> Fixed nav upstream

- utils/__init__.py
To fix the error that @nachandr reported.
> Fix the attributize_string crippling the string on second pass

- cfme/web_ui/menu.py
The toplevel extra branches were not being added before the tack was processed
> [WIP][NOTEST] Fixed nav upstream ordering

- scripts/template_upload_rhevm.py
* updated the yamls with ssh creds tag for rhevm box,
this change will sync the uploader script to pick
new tag.
> updated template_upload_rhevm to sync ssh_creds in yamls.

- utils/update.py
> utils.update: use normal copy, deep copy was incorrect

- scripts/clone_template.py
* while template deploy, if appliance configure fails
collect anaconda-post.log.
> collect anaconda-post log if appliance configure fails.

- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/scvmm.py
- scripts/cleanup_old_vms.py
- scripts/sync_template_tracker.py
Thanks to @amavinag for the initial commit (leaving it in).
> Fix utils providers changes

- cfme/infrastructure/provider/scvmm.py
- scripts/cleanup_old_vms.py
- scripts/sync_template_tracker.py
* list_all_providers's functionality is included in list_providers(type=None)
and list_all_providers is removed.
* cleanup_old_vms, sync_template_tracker are updated with list_providers()
* mgmt_class is updated in infra/providers/scvmm.py
> sync the utils/providers.py changes to files in scripts dir.

- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/fixtures/configure_auth_mode.py
- cfme/tests/integration/test_openldap_auth.py
- cfme/web_ui/form_buttons.py
* retrieve & add ldap_group_look_for user
* check ldap user created in cfme after
first successful login.
> add opensldap tests for ldap group lookup.

- cfme/tests/intelligence/test_download_report.py
instead of raising at collection time
> download report test: use skip marker

- cfme/middleware/provider/__init__.py
- cfme/web_ui/__init__.py
To be able to search for Middleware Provider which has changed @title format and now contains the name alongside with hostname and status.
> Added one more search condition for Quadicon.

- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/server.py
This PR updating changes from https://github.com/ManageIQ/wrapanapi/pull/52
> Update mgmtsystem changes in middleware

- cfme/common/provider.py
- cfme/control/explorer.py
- cfme/fixtures/pytest_selenium.py
- cfme/infrastructure/provider/__init__.py
- cfme/web_ui/__init__.py
- utils/virtual_machines.py
YOu can either specify True to use the element and wait for it or you can specify a custom locator to be waited for.
{{pytest: cfme/tests/cloud_infra_common/test_events.py -v -k vm_create --use-provider complete }}
> Wait for form elements

- cfme/common/__init__.py
- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_server.py
Fixed possible bugs with setting attributes from kwargs['properties'], now it checks the existence of of attribute, as kwargs['properties'] can contain attributes like "name"  and "hostname", which are for MiQ internal use.
> Added new functionality of middleware server power operations, added test cases.

- cfme/common/__init__.py
> Ignore one kind of table for summaries

- cfme/tests/infrastructure/test_set_default_filter.py
{{pytest: cfme/tests/infrastructure/test_set_default_filter.py -v}}
> Fixes of test_set_default_filter for 5.6

- utils/log.py
to suppress its messages
{{pytest: --collectonly}}
> utils.log: adding a root handler to psphere is sufficient

- cfme/web_ui/menu.py
This allows new Menu objects to be created and use the "global"
stack. Ultimately there are some drawbacks but these are more
limitations on future enhancement than regressions
* You can't have a 5.5 and a 5.6 appliance in the same stack
* Menu needs total overhaul :) - but we knew that anyway
> Fixed menu multi use

- cfme/dashboard.py
* This was a nasty one, to do with a nav entry getting added to the
stack twice
> Fixed the navigation

- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/intelligence/reports/ui_elements.py
- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/cloud_catalog_item.py
- cfme/services/catalogs/orchestration_template.py
Fun fact, Select() can work with the fancy selects, but since the .locate() must return the select tag, it stopped working with the form wait.
Therefore I verpicked some of the most prominent errors in hte jenkins here.
> Verpick AngularSelect

- utils/browser.py
* remove thread locals
* introduce a browser manager
* begin to split browser creation into multiple semantically focussed functions
> beginning of the browser object split

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -k test_tag --use-provider vsphere55 --long-running}}
> Fix timed out error

- scripts/template_upload_all.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_scvmm.py
- scripts/template_upload_vsphere.py
- utils/trackerbot.py
* added image_url for template uploader.
* sync template to trackerbot as soon as
upload is successful, no need to wait until
sync template tracker is run.
> add image_url arg for template uploader.

- utils/providers.py
various cleanups that will help with the maintenance later on
> Provider util cleanup

- cfme/provisioning.py
{{pytest: cfme/tests/cloud/test_provisioning.py -k test_provision_from_template --use-provider rhos7-ga}}
> Changed provisioning form. Added AngularSelect for v5.5

- cfme/tests/cloud/test_provisioning.py
* vol test was not expanding the args for the format operation
> Fixed vol test

- cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -k test_providers_discovery}}
> Fixed clear infra providers finalizer

- utils/ssh.py
namedtuple() was good, but I saw a way to simplify the testing code. Old behaviour is kept. New behaviour just gets out of your way.
> Improved SSHResult

- cfme/web_ui/menu.py
Fix to add Overview menu in the menu.py
> Menu.py add overview

- fixtures/parallelizer/__init__.py
A rogue exception could have caused the problems we had. When I wrote this, I forgot to put the reset timer function in the finally block. Since an unexpected non-sprout exception is something potentially dangerous, doing a short timeout in that case to "wait" for the good state to come back..
> Parallelizer: Ensure the timer is always rescheudled

- scripts/template_upload_all.py
- scripts/template_upload_gce.py
- scripts/template_upload_rhos.py
* template_upload_all script is updated to include gce images. there will be jenkins
job for this change.
* change in rhos template sync.
> include gce image in upload_all script.

- cfme/common/__init__.py
- cfme/common/provider.py
- cfme/middleware/deployment.py
- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_middleware_provider.py
- cfme/tests/middleware/test_middleware_server.py
- cfme/tests/middleware/test_middleware_tags.py
- cfme/web_ui/mixins.py
- utils/providers.py
Changed Select to AngularSelect for tags input selects in mixins.
Added new test case to validate datasource tags.
IMPORTANT:  Changed Providers removing menu item text. It is changed to "Remove {} Providers" @psav @mfalesni 
Fixed failing topology test.
>  Refactored 'tags' validation. Moved all tags tests into single class.  Added new test case to validate datasource tags.

- cfme/services/catalogs/catalog_item.py
{{pytest: cfme/tests/services/test_service_catalogs.py -k test_order_catalog_item_via_rest --use-provider vsphere55 --long-running -v}}
> Fix selects in new catalog item form

- cfme/tests/infrastructure/test_datastore_analysis.py
{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py -k test_run_datastore_analysis --use-provider vsphere55 --long-running}}
> Version pick the string

- cfme/web_ui/__init__.py
> Shorten for field wait timeout to 10s

- cfme/tests/services/test_provision_stack.py
Stack name does not accept "_" .
Replacing test_ with test.
Jenkins provision stack test failure fix PR
> Stack name fix

- cfme/infrastructure/datastore.py
- cfme/tests/infrastructure/test_delete_infra_object.py
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py -k test_delete_datastore}}
> Add blocker, test optimization and locators fix 

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
{{pytest: cfme/tests/control/test_basic.py -k test_policies_copy --long-running}}
> New kinds of policies

- cfme/tests/configure/test_access_control.py
{{pytest: -v -k 'test_permissions_vm_provisioning or test_permission_edit'}}
> RBAC fixes

- cfme/cloud/provider/__init__.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/provider/__init__.py
@psav @rrasouli found this one, due to partial matching by defualt in angular select.
> Security protocol exact string matching

- cfme/tests/configure/test_visual_cloud.py
{{pytest: -v -k 'test_grid_page_per_item or test_tile_page_per_item or test_list_page_per_item'}}
> Cloud visual settings fix

- cfme/web_ui/menu.py
Added network menu navigation and removed 'Security Groups' as it has been moved in networks menu
> Menu fix-Added  networks

- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/hawkular.py
- utils/providers.py
Fixing a confusing name in the new provider modules
> Moved from using configloader to from_config

- fixtures/parallelizer/__init__.py
* progress reports (fixes #3000 by at least reporting and making the hangup noticable)
* gracefull exit on pool termination (fixes #3001)
> parallelizer: enhance sprout fulfillment

- sprout/appliances/tasks.py
Shut up the version mismatch detector.
> [WIP][NOTEST] Sprout - Treat the detected version

- cfme/web_ui/__init__.py
Simple change They're to They are
> [WIP][NOTEST]docufix final

- requirements.txt
> Fixed rhevm requirement

- cfme/exceptions.py
- cfme/middleware/datasource.py
- cfme/middleware/domain.py
- cfme/middleware/provider/hawkular.py
- cfme/middleware/server.py
- cfme/middleware/server_group.py
- cfme/tests/middleware/test_middleware_domain.py
- cfme/tests/middleware/test_middleware_server.py
- cfme/tests/middleware/test_middleware_server_group.py
- cfme/web_ui/menu.py
Adjusted Middleware Server code and tests to support Domain mode Servers. Added test cases.
> Added support of Middleware Server Group and Middleware Domain.

- utils/log.py
now uses stdlib facilities and a custom logfile
tbd: logging to stdio?
> [rfc] logging: restructure warning logging

- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_downloads.py
{{pytest: cfme/tests/middleware/test_middleware_downloads.py -v --use-provider hawkular}}
> Added more download tests for domains, domain server_groups and server group servers.

- cfme/control/explorer.py
- cfme/tests/control/test_basic.py
- cfme/web_ui/__init__.py
- cfme/web_ui/expression_editor.py
__Updating basic tests__ for feature Control because many new policy types have been added in CFME version 5.6.1.2
> Control basic tests refactoring

- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/domain.py
- cfme/middleware/server.py
- cfme/middleware/server_group.py
__Extending__ wrapanapi-hawkular api pr-64 along with https://github.com/ManageIQ/wrapanapi/pull/64
> sync with wrapanapi-hawkular api pr-64

- cfme/cloud/provider/__init__.py
- requirements.txt
- utils/appliance/__init__.py
- utils/appliance/endpoints/ui.py
This PR is the New Navigation that replaces #3325 it includes force_navigate like behaviour in the NavigateStep class
> New Navigation

- utils/virtual_machines.py
Added GCE support for deploy_templates through the framework.
The way we do this probably need to be re-worked but this is how it is
today. 
(Requires wrapanapi PR#65)
> fix gce template_deploy

- docs/guides/tipsntricks.rst
Adding tips and tricks for version pick
> Update version pick in tips and tricks

- cfme/tests/containers/test_data_integrity_for_topology.py
{{pytest: cfme/tests/containers/test_data_integrity_for_topology.py -v --use-provider container }}
> In CMFE - test data integrity for topology

- cfme/intelligence/reports/reports.py
- cfme/tests/test_utilization.py
- fixtures/db.py
- utils/appliance/__init__.py
- utils/db.py
- utils/perf.py
Removing some 5.5 supported functions and trying to cleanup some imports to db
> Removed imports to db module where unnecessary

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/test_utilization.py
- fixtures/mgmt_system.py
- fixtures/provider.py
- utils/providers.py
* Before provider types (the real types, infra, cloud etc....) were
baked into the system, hardwired so to speak. Now they are free!
* New provider types can be added with ease, by adding one file, and at
the moment editing another. Perhaps this will change soon too.
> Made the provider types entirely modular

- cfme/fixtures/pytest_selenium.py
- requirements.txt
- utils/deprecation.py
- utils/log.py
{{pytest:  cfme/tests/configure/test_server_name.py -s}}
this pr is primary for showing the noise-level
> mark deprecations in the pytest_selenium module

- cfme/tests/configure/test_docs.py
{{pytest: cfme/tests/configure/test_docs.py -k test_contents}}
> Fix docs content test. Added dict for content

- cfme/tests/configure/test_ntp_server.py
{{pytest: cfme/tests/configure/test_ntp_server.py -k test_ntp_conf_file_update_check }}
> Add new ntp config file. Bug fixing

- cfme/tests/cloud_infra_common/test_retirement.py
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py -v -k test_set_unset_retirement_date_tomorrow}}
> Change retirement set date test

- cfme/tests/containers/test_containers_projects_summary.py
{{pytest: cfme/tests/containers/test_containers_projects_summary.py -v --use-provider container }}
> Projects Summary Tests

- cfme/tests/containers/test_basic_metrics.py
This is a basic test that checks if Metrics for OSE are up
{{pytest: cfme/tests/containers/test_basic_metrics.py -v --use-provider container }}
> Basic Metrics Test

- cfme/cloud/provider/__init__.py
Fixing to use a new navmazing feature
> Moved to Attribute usage

- cfme/tests/configure/test_visual_cloud.py
- cfme/tests/configure/test_visual_infra.py
> Fix menu levels checks

- utils/bz.py
The string on copied bugs has changed, so added additional matcher
> Fix the changed string

- cfme/tests/containers/test_containers_properties.py
Fixed and added test_containers_properties.py and test_containers_services.py
{{pytest: cfme/tests/containers/test_containers_properties.py -v --use-provider container }}
> Added  test_containers_properties.py and test_containers_services.py

- cfme/cloud/provider/__init__.py
- utils/appliance/__init__.py
- utils/appliance/endpoints/ui.py
* navigate renamed to navigator in the ui.py module
* navigate_to added as a shortcut to navigator.navigate
> navmazing change

- cfme/middleware/provider/__init__.py
This gets middleware working in 5.7
> Get middleware working in 5.7

- cfme/common/vm.py
{{pytest: cfme/tests/cloud_infra_common/test_vm_ownership.py -k test_form_button_validation --use-provider vsphere55 }}
> Fix selector for vm ownership for upstream

- utils/appliance/__init__.py
Upreving the patching for 5.7 for the autofocus where changes just hit us
> Fixed patching

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_log_depot_operation.py
{{pytest:  cfme/tests/configure/test_log_depot_operation.py  -k test_collect_log_depot}}
> Fixing log collection for upstream 

- utils/browser.py
* introduces a factory concept
* steamline configuration overrides and browser
* distinct wharf factory
* defer all browser creation to the factory
> browser split part 2

- cfme/tests/containers/test_containers_properties.py
The test verifies data integrity in the Properties table for pods, routes, projects and services
{{pytest: cfme/tests/containers/test_containers_properties.py -v --use-provider container }}
> Added comments to test_containers_properties.py

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
{{pytest: -v --long-running --use-provider azure cfme/tests/services/test_provision_stack.py }}
> Azure stack provisioning

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
Implemented Azure default mode should be Incremental.
> Azure Mode defaults to Increamental

- cfme/middleware/__init__.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/web_ui/menu.py
Changed test cases, added new test for Restart.
Fixed Middleware Menu item names.
> Renamed Stop/Start/Redeploy deployment operations to Disable/Enable/Restart.

- utils/appliance/endpoints/ui.py
Extending navmazing implementation to add resetter support
> Added resetter support from navmazing 0.0.3

- utils/update.py
{{pytest: cfme/control/explorer.py cfme/infrastructure/config_management.py cfme/tests/automate/test_buttons.py cfme/tests/automate/test_class.py cfme/tests/automate/test_domain_priority.py cfme/tests/automate/test_instance.py cfme/tests/automate/test_method.py cfme/tests/automate/test_namespace.py cfme/tests/automate/test_provisioning_dialogs.py cfme/tests/automate/test_service_dialog.py cfme/tests/cli/test_rake_evm_automate-53.py cfme/tests/cloud/test_providers.py cfme/tests/cloud/test_provisioning.py cfme/tests/configure/test_access_control.py cfme/tests/configure/test_analysis_profiles.py cfme/tests/configure/test_tag.py cfme/tests/configure/test_tag_category.py cfme/tests/configure/test_timeprofile.py cfme/tests/configure/test_zones.py cfme/tests/control/test_alerts.py …
> with update: don't deepcopy, its too broken

- cfme/tests/configure/test_db_backup_schedule.py
Add dynamic vm for db backup (nfs, smb)
{{pytest: cfme/tests/configure/test_db_backup_schedule.py}}
> add dynamic vm to db backup test

- cfme/infrastructure/pxe.py
- cfme/tests/infrastructure/test_system_image_type.py
navmazing conversion of PXEServer
{{pytest: cfme/tests/infrastructure/test_pxe.py cfme/tests/infrastructure/test_system_image_type.py cfme/tests/infrastructure/test_iso_datastore.py cfme/tests/infrastructure/test_customization_template.py}}
> Navmazing conversion for PXEServer

- cfme/infrastructure/cluster.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/provider/__init__.py
- cfme/tests/configure/test_visual_infra.py
{{pytest: cfme/tests/infrastructure/test_providers.py}}
Updating infrastructure providers and common BaseProvider to use [navmazing](https://github.com/RedHatQE/navmazing).
I have commented on the prerequisite requirements concerning how 'safe' the tests should be in making sure only a single icon is checked.
> Provider navigation

- cfme/infrastructure/provider/__init__.py
Fixing infra import for class navmazing
> Fixed infra import

- cfme/middleware/messaging.py
- cfme/middleware/provider/hawkular.py
- cfme/tests/middleware/test_middleware_downloads.py
- cfme/tests/middleware/test_middleware_messagings.py
- cfme/web_ui/menu.py
> Messaging: Added support for MiddlewareMessaging. Fixed Menu Items for Middleware.

- cfme/tests/openstack/test_host_hostname.py
- cfme/tests/openstack/test_host_role_type.py
Fixing automation bugs found in automation run on local setup
> bug fixes found in automation run

- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
Extending Middleware Providers to provider navmazing functionality
@hhovsepy - this is going to be the new navigation system moving forward, we will provide full documentation and training shortly
{{pytest: cfme/tests/middleware/test_middleware_provider.py --use-provider=hawkular}}
> Added Middleware Destinations

- cfme/provisioning.py
Fixing provisioning form since it was pointing to wrong locator.
> Provisioning form fix

- utils/browser.py
> fix missed typo

- cfme/containers/provider/__init__.py
> Added navmazing for containers

- cfme/infrastructure/host.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/configure/test_default_filters.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/configure/test_visual_infra.py
- cfme/tests/infrastructure/test_advanced_search_host.py
- cfme/tests/infrastructure/test_host_provisioning.py
- cfme/tests/infrastructure/test_set_default_filter.py
- utils/appliance/__init__.py
With accordance to our plans to move all navigation to navmazing lib, I've moved Infrastructure/Host obj to the new navigation approach.
> [WIPTEST] moving Host to navmazing lib

- cfme/tests/cloud_infra_common/test_tag_visibility.py
{{pytest: cfme/tests/cloud_infra_common/test_tag_visibility.py}}
> fix scope mistmatch

- cfme/web_ui/expression_editor.py
{{pytest: cfme/tests/control/test_compliance.py -k test_check_files --use-provide vsphere55  --long-running}}
> Fix for expression editor

- cfme/common/provider.py
- cfme/infrastructure/provider/__init__.py
- utils/appliance/__init__.py
> Example Navigatable

- cfme/middleware/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/messaging.py
- cfme/tests/middleware/test_middleware_datasource.py
Moved get_server_name upper to be used in several classes.
> Fixed failing datasource tests.

- cfme/cloud/provider/__init__.py
- cfme/configure/configuration/__init__.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/host.py
- cfme/infrastructure/pxe.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
Fixing up with new Navigatable class
> Fixed all usages of CurrentAppliance

- cfme/automate/service_dialogs.py
Converted Service Dialog
{{pytest: cfme/tests/automate/test_service_dialog.py}}
> Converted Service Dialog

- cfme/configure/access_control.py
- cfme/tests/infrastructure/test_infra_quota.py
Automating tenant quota.
{{pytest: -v -k 'test_tenant_quota_max_cpu_check'}}
> Tenant quota beginning

- cfme/automate/buttons.py
- cfme/tests/automate/test_buttons.py
Navmazing conversion of Button and Button Group
{{pytest: cfme/tests/automate/test_buttons.py}}
> Converted Button and ButtonGroup

- cfme/infrastructure/resource_pool.py
- cfme/tests/configure/test_visual_infra.py
moved Infrastructure->ResourcePool obj to navmazing
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py cfme/tests/configure/test_default_views_infra.py cfme/tests/configure/test_visual_infra.py}}
> Resource Pool nav

- cfme/infrastructure/cluster.py
Fixing a nav link that was altered during navmazing conversion
> Fix nav link in clusters

- cfme/tests/automate/test_buttons.py
> Remove an old force_nav link

- cfme/tests/automate/test_customization_paginator.py
> Fixed a ServiceDialog navigation error

- cfme/automate/explorer.py
- cfme/js.py
- cfme/provisioning.py
- cfme/services/catalogs/cloud_catalog_item.py
- cfme/web_ui/__init__.py
- cfme/web_ui/accordion.py
If you are thinking about commenting on DRY and optimization, don't. I am aware of it and once the implementation works as I like I will DRY the stuff out ...
{{pytest: cfme/tests/automate/ -v }}
> BootstrapTreeview implementation, jsmin the wait_for_ajax

- cfme/infrastructure/host.py
Fix button
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py -k test_delete_host}}
> Fixed button name

- cfme/automate/provisioning_dialogs.py
- cfme/tests/automate/test_provisioning_dialogs.py
Converting provisioning_dialogs
{{pytest: cfme/tests/automate/test_provisioning_dialogs.py}}
> Converted provision dialogs

- cfme/tests/test_utilization_metrics.py
Adding tests to verify specific performance metrics are collected.
Added tests for rhev and vmware through this PR.
_
> Tests to verify the collection of performance metrics

- cfme/infrastructure/host.py
> Fixed Host link

- cfme/tests/configure/test_analysis_profiles.py
{{pytest: -v -k 'test_analysis_profile_duplicate_name or test_vmanalysis_profile_description_validation'}}
Fix vm analysis profile test failures
> Fix test analysis profiles

- cfme/tests/openstack/test_host_security.py
Testing the security section on infra provider nodes that currently includes users and groups
> Test hosts/nodes users and groups

- cfme/tests/openstack/test_host_cpu_resources.py
- cfme/tests/openstack/test_host_memory.py
This test purpose checking openstack infra provider hosts CPU and Memory resources. 
{{pytest: cfme/tests/infrastructure/test_host_memory.py cfme/tests/infrastructure/test_host_cpu_resources.py --use-provider rhos_uc}}
> test undercloud nodes resources

- cfme/tests/cloud/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -k "test_name_max_character_validation or test_hostname_max_character_validation or test_api_port_max_character_validation" }}
> Fix max value validation and removed unnecessary tests

- cfme/cloud/instance.py
- cfme/provisioning.py
- cfme/tests/cloud/test_provisioning.py
Purpose 
Fixing test_provisioning for azure/ec2 template provision.
{{pytest: cfme/tests/cloud/test_provisioning.py::test_provision_from_template --use-provider azure --use-provider ec2east}}
> [TEST]Fixing provisioning test

- cfme/common/provider.py
{{pytest: cfme/tests/infrastructure/test_providers.py -v -k crud --use-provider nested-rhevm34}}
> Work around the C&U credential validation issue

- cfme/tests/test_login.py
> Added example requirement

- cfme/tests/configure/test_access_control.py
- cfme/tests/infrastructure/test_infra_quota.py
- cfme/tests/infrastructure/test_snapshot.py
Add requirement mark to snapshot, quota and access control
> Add requirement marking

- fixtures/provider.py
> fixtures/provider.py: Make it work without trackerbot and clean it up

- cfme/tests/infrastructure/test_vm_migrate.py
> mark vm_migrate tests with the vm_migrate requirement marker

- cfme/infrastructure/cluster.py
- cfme/infrastructure/provider/__init__.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/configure/test_visual_infra.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/tests/openstack/test_roles_names.py
According to the plan to replace all old navigation calls by navmaging, I migrated Cluster to navmazing.
> moved cluster object to navmazing

- cfme/tests/distributed/test_appliance_replication.py
Updating distributed tests with the distributed requirement marker
> mark distributed tests with the distributed requirement marker

- cfme/cloud/provider/__init__.py
Locator is different for GCE region in 5.7
> GCE region fix

- cfme/intelligence/chargeback.py
- cfme/tests/intelligence/test_chargeback.py
{{pytest: cfme/tests/intelligence/test_chargeback.py }}
> Fix chargback. Add new items

- cfme/fixtures/pytest_selenium.py
- utils/deprecation.py
Reverts ManageIQ/integration_tests#3478
> Revert "mark the selenum-fixture classes as deprecated"

- cfme/tests/configure/test_zones.py
> Remove smoke from test_zone

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
- cfme/tests/intelligence/test_chargeback.py
- cfme/tests/intelligence/test_chargeback_assignments.py
- cfme/tests/test_utilization_metrics.py
Test requirement marking for Chargeback and C&U tests
> Test requirement marking for Chargeback and C&U tests

- cfme/intelligence/reports/dashboards.py
- cfme/tests/intelligence/reports/test_widgets.py
{{pytest: -v -k 'test_dashboard_crud'}}
Added navmazing for dashboards
> Navmazing for dashboards

- cfme/common/provider.py
{{pytest: -k test_provider_crud }}
Integrate navmazing into the common provider class.
@pavelzag has tested this patch with additional updates where the common create is called.
> Update cfme.common.provider with navmazing

- cfme/tests/infrastructure/test_datastore_analysis.py
{{ pytest: cfme/tests/infrastructure/test_datastore_analysis.py }}
> Added blocker to test_datastore_analysis

- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud_infra_common/test_discovery.py
- cfme/tests/cloud_infra_common/test_genealogy.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_rest_providers.py
- cfme/tests/intelligence/reports/test_canned_corresponds.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/intelligence/reports/test_report_corresponds.py
Added test_requirement marks for my tests.
> Added test_requirements marks to my tests.

- cfme/tests/configure/test_log_depot_operation.py
{{ pytest: cfme/tests/configure/test_log_depot_operation.py }}
> Add blocker to log depot

- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/tests/openstack/test_credentials_quad.py
> Remove more force_navigates

- cfme/tests/control/test_actions.py
- cfme/tests/control/test_alerts.py
- cfme/tests/control/test_basic.py
- cfme/tests/control/test_bugs.py
- cfme/tests/control/test_compliance.py
- cfme/tests/control/test_export_policies.py
- cfme/tests/control/test_import_policies.py
- cfme/tests/intelligence/reports/test_widgets.py
- cfme/tests/intelligence/test_dashboard.py
Accordng @psav email I've added new pytest.requirement to "control", "alerts" and "dashboard" tests.
> Added pytest.mark.requirement

- cfme/tests/intelligence/reports/test_canned_corresponds.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/intelligence/reports/test_report_corresponds.py
> Fixed some requirements

- requirements.txt
Remove ui_navigate from library
> Removed older ui_navigate

- scripts/coverage_result.py
- scripts/dockerbot/pytestbase/post_result.py
Adds coverage script to compute coverage against changes from a given branch
> Added coverage script

- utils/trackerbot.py
Adds coverage posting to trackerbot
> Added coverage to poster

- cfme/tests/cloud_infra_common/test_tag_visibility.py
- cfme/tests/cloud_infra_common/test_vm_ownership.py
- cfme/tests/configure/test_ntp_server.py
Added mark requirement to ownership, tag visibility and ntp test cases
> [WIP][NOTEST] Added mark requirement to ownership, tag visibility and ntp test cases

- cfme/tests/test_utilization_metrics.py
> Add support for rhos and ec2

- cfme/infrastructure/datastore.py
on_hosts and on_vms methods don't work now because those compare summary when browser window even doesn't appear.
> removing invalid on_hosts and on_vms methods 

- cfme/cloud/keypairs.py
{{ pytest: cfme/tests/cloud/test_keypairs.py }}
> New navigation for key pairs

- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_server.py
- cfme/web_ui/__init__.py
Added testcase to check Suspend/Resume functionality.
> Refactorings in server power operations testcases. Added support of filling number input type.

- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud_infra_common/test_discovery.py
- cfme/tests/control/test_alerts.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_rest_providers.py
__Fixing__ wrong import of test_requirement in some tests.
> Fix for failed test_requirements import

- cfme/web_ui/__init__.py
{{pytest: cfme/tests/automate/test_provisioning_dialogs.py -v --long-running }}
> Changed the sort table locators

- cfme/tests/configure/test_default_filters.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/configure/test_display_settings.py
- cfme/tests/configure/test_timeprofile.py
- cfme/tests/configure/test_visual_cloud.py
- cfme/tests/configure/test_visual_infra.py
Added requirement mapping for settings test cases
> Add requirements mapping

- cfme/tests/cloud/test_instance_power_control.py
> marking power tests

- cfme/configure/configuration/__init__.py
Fixing configure string
{{pytest: cfme/tests/configure/test_zones.py -k test_zone_crud}}
> Fix Configure String

- scripts/dockerbot/check_prs.py
> Fixed cleanup

- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud_infra_common/test_discovery.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_rest_providers.py
> Fix discovery

- utils/appliance/__init__.py
Fixing upstream patching as it's now included by default
> Fix upstream patching

- cfme/automate/explorer.py
> Version pick removals

- cfme/intelligence/chargeback.py
{{ pytest: cfme/tests/intelligence/test_chargeback.py cfme/tests/intelligence/test_chargeback_assignments.py -k "test_assign_storage_enterprise or test_assign_compute_enterprise or test_edit_compute_chargeback or test_edit_storage_chargeback or test_delete_compute_chargeback or test_delete_storage_chargeback" }}
> New navigation for chargeback

- cfme/configure/configuration/__init__.py
- utils/appliance/__init__.py
> Moved server_region_string to assist in refactor

- utils/version.py
* darga-4.1 is based on cfme 5.6.2. updated the same
to utils/version.py
> included darga-4.1 in versions.

- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_zones.py
- cfme/tests/infrastructure/test_instance_analysis.py
Stop importing configuration module to get to these
> Remove old funcs from configuration

- cfme/tests/test_appliance.py
- utils/appliance/__init__.py
* Product name is now obtained from the ymls
* Product name is now dynamically inserted
> Added new test for product name

- cfme/fixtures/service_fixtures.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_add_remove_vm_to_service.py
Entry point locator changed in 5.7
> 5.7 entry point locator change

- cfme/tests/services/test_iso_service_catalogs.py
Marked ISO test with datatstore bug
> ISO datastore bug

- cfme/automate/explorer.py
- cfme/automate/service_dialogs.py
{{pytest: -v --long-running cfme/tests/services/test_dynamicdd_dialogelement.py}}
> Dialog 5.7 locator change

- cfme/configure/configuration/__init__.py
- cfme/configure/configuration/ui.py
- cfme/infrastructure/pxe.py
- cfme/intelligence/reports/dashboards.py
- utils/appliance/__init__.py
> Navmazing config

- cfme/configure/access_control.py
- cfme/configure/configuration/ui.py
- cfme/tests/configure/test_access_control.py
- utils/appliance/__init__.py
Navmazing conversion for access control
{{pytest: cfme/tests/configure/test_access_control.py}}
> Navmazing conversion for Access Control

- cfme/configure/access_control.py
- cfme/configure/configuration/ui.py
- cfme/fixtures/pytest_selenium.py
- cfme/login.py
- utils/appliance/__init__.py
- utils/appliance/endpoints/ui.py
> Single user went boom!

- cfme/automate/buttons.py
- cfme/automate/provisioning_dialogs.py
- cfme/automate/service_dialogs.py
- cfme/cloud/keypairs.py
- cfme/cloud/provider/__init__.py
- cfme/configure/access_control.py
- cfme/containers/image.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/pxe.py
- cfme/infrastructure/resource_pool.py
- cfme/intelligence/chargeback.py
- cfme/intelligence/reports/dashboards.py
- cfme/intelligence/reports/reports.py
- cfme/middleware/provider/__init__.py
- utils/appliance/__init__.py
- Since Loggedin is moved to Server, all existing nav calls have to be updated. 
I made appropriate replacement.
- removed old destination.
P.S. I left Dashboard and Configuration in the same place since those are not completely moved to another place.
> changing existing appliance nav calls to use Server

- utils/appliance/__init__.py
* removed darg-4.1 string from appliance/__init__ under configure_appliance.
> removed darg-4.1 string from version pick in configure_appliance.

- utils/browser.py
extends uppon #3607 and adds url keys as a means to restart the browser when switching the user interface
this is the first iteration, we expect to extend upon it later on to manage multiple browsers if necessary
> Browser object url key

- cfme/infrastructure/config_management.py
1. fixed delete flash message text for 5.7. it is changed there.
2. fixed typo Description->Details
> fixed config manager deletion for 5.7

- cfme/services/catalogs/cloud_catalog_item.py
- cfme/tests/services/test_cloud_service_catalogs.py
{{pytest: -v --long-running --use-provider ec2 cfme/tests/services/test_cloud_service_catalogs.py}}
> GCE provisioning

- cfme/tests/infrastructure/test_instance_analysis.py
This PR adds the @pytest.mark.meta(blockers=1378447)
Bug Link https://bugzilla.redhat.com/show_bug.cgi?id=1378447
> test_instance_analysis: Added blocker

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_timelines.py
- cfme/tests/intelligence/reports/test_canned_corresponds.py
- cfme/tests/openstack/test_credentials_quad.py
SSIA
@psav @mfalesni review and merge asap please
{{pytest: cfme/tests --collect-only}}
> Rename all Provider classes to <Category>Provider

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_individual_host_creds.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
- metaplugins/blockers.py
We shouldn't allow implicit behavior such as this.
> Blockers no longer accepts a single object

- cfme/__init__.py
- cfme/automate/__init__.py
- cfme/automate/buttons.py
- cfme/automate/service_dialogs.py
- cfme/base/ui.py
- cfme/dashboard.py
- cfme/login.py
- cfme/tests/automate/test_buttons.py
- cfme/tests/test_login.py
- fixtures/rbac.py
- requirements.txt
- utils/appliance/__init__.py
- utils/appliance/endpoints/ui.py
- widgetastic_manageiq.py
- widgetastic_patternfly.py
In order to make the progress faster, I cherrypicked and merged the integration changes against master. Seems working as usual so far.
{{pytest: cfme/tests/automate/test_buttons.py -k 'button_group_crud or button_crud' -v }}
> Widgetastic integration - against master

- cfme/intelligence/reports/widgets.py
{{ pytest: cfme/tests/intelligence/reports/test_crud.py -k test_menuwidget_crud}}
> New navigation for widgets

- cfme/login.py
Fixing login as it's broken :)
> Fixed login

- cfme/login.py
> Fix login again

- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_hawkular_crud --use-provider="hawkular"}}
> Fixed inputs and buttons in adding new middleware provider.

- cfme/tests/services/test_myservice.py
5.7 service provisioning message has changed .
> Myservice 5.7 fix

- artifactor/plugins/filedump.py
For some reason, int's are getting in here and messing up the filedumper
> Fixing sanitizer

- cfme/middleware/__init__.py
- cfme/tests/middleware/random_methods.py
- cfme/tests/middleware/test_middleware_downloads.py
- cfme/tests/middleware/test_middleware_tags.py
Created random_methods.py file and moved all common random objet get methods into it.
> Added new tests to support PDF downloads of lists and PDF downloads of summary pages for 5.7 only

- utils/version.py
"euwe-1-beta1.3" has landed, we need to version that to include euwe for testing.
> added euwe-1-beta1.3 to vstring.

- scripts/template_upload_all.py
- scripts/template_upload_ec2.py
* added template_upload_ec2 script, made changes
to template_upload_all to include the ec2 image
and url pattern.
* cfme_data will be updated accordingly.
> Implement ec2 provider template uploads.

- cfme/dashboard.py
- cfme/tests/intelligence/test_dashboard.py
- utils/timeutil.py
{{pytest: cfme/tests/intelligence/test_dashboard.py -k "test_widgets_operation or test_verify_rss_links" --use-provider vsphere55-nested }}
> Fix locators in dashboard

- cfme/tests/infrastructure/test_providers.py
Fixes single rhev test failures
> fix changing feedback messages for rhev cred failure

- cfme/services/catalogs/catalog.py
- cfme/services/catalogs/catalog_item.py
> Generic service 5.7 fix

- cfme/intelligence/reports/reports.py
- cfme/intelligence/reports/ui_elements.py
- cfme/tests/intelligence/reports/test_menus.py
{{pytest:  cfme/tests/intelligence/reports/test_menus.py  cfme/tests/intelligence/reports/test_report_corresponds.py }}
> Fix report's foldermanager locators

- cfme/cloud/stack.py
- cfme/containers/image.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/config_management.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/infrastructure/resource_pool.py
- cfme/intelligence/chargeback.py
- cfme/web_ui/__init__.py
There is a number of checks which we do in every am_i_here method. 
I tried to move those to one place .
> moved am_i_here checks to web elements

- cfme/dashboard.py
{{ pytest: cfme/tests/intelligence/test_dashboard.py -k test_drag_and_drop_widget_to_the_bottom_of_another_column }}
> Fix test_drag_and_drop_widget_to_the_bottom_of_another_column
