- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_service_catalogs.py
UI message change in 5.7 for service requests and added provisioning entry point for bundle .
Also marked tests with some new bugs
> Service Catalog 5.7 fix

- utils/appliance/__init__.py
Renaming sentaku_ctx -> context
> Renamed sentaku_ctx -> context

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
- utils/timeutil.py
fix locator select warning, fix date checking in verify
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py -k "not test_set_unset_retirement_date_tomorrow" --use-provider ec2west }}
> Fix date representation on instance summary

- conftest.py
- fixtures/dev_branch.py
- utils/appliance/__init__.py
Specify the source repo and optionally branch (default master) to have the tests update the appliance before proceeding.
Check `fixtures/dev_branch.py` for more info.
> Enable executing tests against PRs in upstream

- utils/appliance/implementations/ui.py
* Logging updated to
* Make it look more like Widgetastic
* Add better context
> Updated logging in anticipation of SSUI

- scripts/template_upload_rhevm.py
* accessing eth0 and updating it directly. 
* removed additional nic eth1, as we dont need additional NIC.
> Removed additional nic eth1 from rhv template.

- cfme/intelligence/reports/schedules.py
- cfme/intelligence/reports/ui_elements.py
- cfme/intelligence/reports/widgets.py
- cfme/tests/intelligence/reports/test_crud.py
{{ pytest: cfme/tests/intelligence/reports/test_crud.py }}
> fix reports/test_crud

- cfme/intelligence/reports/reports.py
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py }}
> fix reports/test_canned_corresponds

- cfme/tests/intelligence/reports/test_report_chargeback.py
{{ pytest: cfme/tests/intelligence/reports/test_report_chargeback.py }}
> Fix reports/test_report_chargeback

- cfme/intelligence/reports/dashboards.py
{{ pytest: cfme/tests/intelligence/reports/test_widgets.py }}
> fix reports/test_widgets

- scripts/latest_template_tester_report.py
* providers filter is updated with list_providers(type), before this used to be e.g. 'rhevm', which is not reliable in case the provider string pattern changes, as it changed in case of rhevm--> rhv40
> updated latest_template_tester with rhv40 string patter.

- cfme/base/ui.py
Speedier tests by not logging in and out every time we navigate
> Check if already logged in

- cfme/intelligence/chargeback.py
{{ pytest: cfme/tests/intelligence/test_chargeback_assignments.py}}
> Fix test_chargeback_assignments

- cfme/middleware/deployment.py
- cfme/tests/middleware/deployment_methods.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_provider_timelines.py
Moved common methods into deployment_methods.
> Added more tests for deployment events in timelines.

- cfme/base/ui.py
- cfme/configure/settings.py
- cfme/tests/configure/test_display_settings.py
{{pytest: cfme/tests/configure/test_visual_infra.py -v -k 'test_grid_page_per_item'}}
Navmazing for settings.
> Navmazing for settings

- cfme/web_ui/__init__.py
SSIA
@FilipB this should solve both the issues you reported, would you mind testing it please?
> Fix angular help block to return first visible text

- scripts/template_upload_all.py
- utils/trackerbot.py
* euwe is included in uploader and trackebot.
> sync euwe-beta to template uploader and trackerbot.

- utils/version.py
* included euwe in stream vstring. euwe-beta, euwe-rc1, etc are all upstream images.
> include euwe in stream vstring.

- artifactor/plugins/filedump.py
- fixtures/soft_assert.py
Fixing soft assert for non parallel usage
> Soft Assert Fix

- cfme/configure/access_control.py
This chargeback navigation is done in chargeback model page and hence removed from access control.
> Remove irrelevant code

- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/infrastructure/test_delete_infra_object.py
Added mapping to object deletion test cases
> Few more requirement mapping

- utils/log.py
Reverts ManageIQ/integration_tests#3706
> Revert "added timestamp to console logs"

- cfme/configure/access_control.py
Fix for #3667
{{pytest: cfme/tests/configure/test_access_control.py -k test_user_crud}}
> Fixing User update method

- cfme/infrastructure/provider/__init__.py
- cfme/tests/infrastructure/test_advanced_search_providers.py
- cfme/web_ui/search.py
{{ pytest: cfme/tests/infrastructure/test_advanced_search_providers.py }}
Fixing navigation, search, and downstream test failures in test_advanced_search_providers.
Inconsistent test results on back-to-back runs locally, with transient navigation failures dominating. Running through PRT to get more data points.
> Infrastructure.test_advanced_search_providers fix and web_ui.search updates

- cfme/dashboard.py
- cfme/intelligence/reports/widgets.py
- cfme/tests/intelligence/test_dashboard.py
{{ pytest: cfme/tests/intelligence/test_dashboard.py}}
> fix test_dashboard

- cfme/tests/cloud/test_provisioning.py
__Fixing__  Azure Provisioning because 'vm_size' became lowercase in 5.7.0.6 + removing useless sel_force_navigate which started ocasionally failing with Namazing/wigetastic updates
{{pytest: cfme/tests/cloud/test_provisioning.py::test_provision_from_template --use-provider azure --long-running}}
> 5.7 cloud provisioning

- cfme/tests/cloud/test_instance_power_control.py
__Extending__  Power Control tests to check available power actions from  "on/off" because now many test are failing due to inconsistent list of available actions
{{pytest: cfme/tests/cloud/test_instance_power_control.py "-k test_start or test_stop or test_power_options_from_on or test_power_options_from_off" --long-running --use-provider azure}}
> adding separate test for Power options buttons

- artifactor/plugins/reporter.py
> Fix stats to make skips failures

- cfme/fixtures/pytest_selenium.py
- utils/appliance/implementations/ui.py
Ignoring the error modals for now as they are interfering with clicks and navs
> Fix modal errors to be ignored for now

- fixtures/events.py
- fixtures/qa_contact.py
- fixtures/rbac.py
- fixtures/screenshots.py
- fixtures/soft_assert.py
Slave handling was screwed in many places
> Fix artifactor slave handling

- cfme/fixtures/pytest_selenium.py
- utils/appliance/implementations/ui.py
Fixing the skipper when angular isn't defined
> Fix angular skip

- cfme/control/explorer.py
Fixing multiselect
{{pytest: cfme/tests/control/test_basic.py -k test_assign_condition_to_control_policy --long-running --use-provider complete}}
> Fix multiselect from conditions

- cfme/infrastructure/host.py
- cfme/infrastructure/virtual_machines.py
Fix quadicon locator so it works also in upstream.
> change quadicon locator to reflect change in upstream

- cfme/tests/cloud_infra_common/test_power_control_rest.py
add fix for power control rest for gce
> fix vm name for gce

- utils/artifactor_start.py
Added an artifactor crash log as it seems to be happening
> Fix artifactor crash log

- scripts/clone_template.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_vsphere.py
* excluded interop providers from trackerbot.
* updated clone_template to skip Appliance() and
make call to IPAppliance()
> exclude interop providers from trackerbot.

- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/tests/containers/test_containers_projects_summary.py
- cfme/tests/containers/test_containers_properties.py
- cfme/tests/containers/test_containers_route_views.py
- cfme/tests/containers/test_containers_simple_search.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_pods_prop_data_integrity.py
- cfme/tests/containers/test_relationships_tables.py
- cfme/tests/containers/test_views_objects.py
conversion to navmazing
{{pytest: cfme/tests/containers/test_containers_projects_summary.py -v --use-provider container }}
> navmazing convertions

- cfme/infrastructure/config_management.py
> Fix Configuration Management Link

- cfme/base/ui.py
- cfme/dashboard.py
- cfme/tests/configure/test_docs.py
- cfme/tests/test_appliance.py
> Fixed links to docs

- artifactor/plugins/logger.py
- utils/log.py
Reverts ManageIQ/integration_tests#3733
> Revert "artifactor: turn logger into handler and pass on log records"

- cfme/tests/test_utilization_metrics.py
> Fix collection on test

- utils/appliance/implementations/ui.py
- utils/browser.py
{{pytest: cfme/tests/test_utilization_metrics.py -k test_raw_metric_host_memory}}
> introduce cfme.browser logger and log more details of browser startup

- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_cloud_service_catalogs.py
Removing old mgmt parameter because it doesn't get used anywhere
> Removed unused provider_mgmt call

- utils/appliance/implementations/ui.py
* Added use_resetter usage so that navigation can disable the resetter
for the leaf navigation node
* Rejigged navigation logging
> use_resetter usage

- fixtures/parallelizer/__init__.py
> Reducing appliance_police to 1

- fixtures/artifactor_plugin.py
> ready for new riggerlib

- .gitignore
- cfme/tests/cloud/test_cloud_timelines.py
1. removed and added some blockers for timelines tests
2. removed unnecessary code blocks
> timelines test fixes

- cfme/common/provider.py
- cfme/common/vm.py
- data/patches/ovirt_gem.patch
- utils/appliance/__init__.py
- utils/appliance/implementations/ui.py
add temporary patch to ovirt gem to work around rhev c&u credential issues
{{pytest: cfme/tests/infrastructure/test_providers.py -k crud --use-provider rhevm}}
> Latest attempt at working around rhev c&u credentialling issues

- markers/uncollect.py
- utils/testgen.py
this takes test-gen generated uncollected and propagates their reason
> testgen: propagate uncollect messages down to the uncollect log

- cfme/tests/configure/test_access_control.py
Disable tenant project CRUD test because of opened BZ. 
{{pytest: cfme/tests/configure/test_access_control.py -v -k test_superadmin_tenant_project_crud}}
> Disable tenant project test

- cfme/containers/topology.py
Supply navmazing destination for PR 3748
> Add cfme.containers.topology

- cfme/middleware/__init__.py
- cfme/middleware/datasource.py
- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/test_middleware_datasource.py
Added datasource_methods.py as separate methods for Datasource tests.
New created Datasource have default parameters now, as DBAllocator is not integrated yet.
> Added support of creating new Datasource in middleware server, added testcases.

- cfme/tests/containers/test_containers_summary.py
- cfme/web_ui/__init__.py
This tests checks status boxes in the Containers Overview menu and verifies it shows the correct data for:
Pods, Containers and Nodes
{{pytest: cfme/tests/containers/test_containers_summary.py -v --use-provider container }}
> Containers Summary test + Updated StatusBox object

- cfme/tests/middleware/test_middleware_provider.py
{{pytest: cfme/tests/middleware/test_middleware_provider.py -v --use-provider hawkular }}
> Adding new negative cases for hawkular provider creation

- cfme/tests/containers/test_containers_projects_summary.py
This PR fixes test_containers_projects_summary.py for new labels in CFME 5.7.
{{pytest: cfme/tests/containers/test_containers_projects_summary.py -v --use-provider container }}
> test_containers_projects_summary.py fixes for CFME 5.7

- utils/appliance/implementations/ui.py
When patching we shouldn't inc the tries, this was leading to problems by tries running out during navigation if both patches needed applying.
> Don't inc tries on patching

- cfme/cloud/volume.py
BLOCKED: PR #3767 
Adding navigation for Cloud Volumes (CFME < 5.7), replacing PR 3525.
Only implemented All, AllByProvider, and Details navigation destinations for now.
> Cloud Volume module and navigation

- scripts/dockerbot/dockerbot.py
Extending dockerbot to allow dev pr usage
> [WIP][NOTEST] Dockerbot dev pr

- cfme/web_ui/__init__.py
Add a new function to PagedTable to find a row by a cell, instead of a single column/value match.
> Update cfme.web_ui.PagedTable, add find_row_by_cell_on_all_pages

- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --use-provider nested-rhevm35 --long-running}}
> Snapshot tree fix

- cfme/control/explorer.py
{{pytest: cfme/tests/control/test_basic.py -k test_condition_crud[ContainerImageCondition] --long-running}}
> Fixed locator change

- cfme/infrastructure/virtual_machines.py
{{pytest: -k test_action_create_snapshots_and_delete_them[vsphere55] cfme/tests/control/test_actions.py --long-running}}
> Fix link for snapshots active

- cfme/tests/test_utilization_metrics.py
Added support to test collection of individual perf metrics for Azure and GCE.
{{pytest: cfme/tests/test_utilization_metrics.py --use-provider complete}}
> Add support  to test collection of individual perf metrics for Azure and GCE

- cfme/infrastructure/virtual_machines.py
* That'll teach me to work at 1am
> Fixed a bug in the snapshot active (again)

- cfme/tests/configure/test_display_settings.py
> Fixed TZ detection

- cfme/tests/services/test_orchestration_template.py
> Fix template copy test

- cfme/tests/services/test_provision_stack.py
> Fixed orchestration tests

- cfme/tests/configure/test_default_views_cloud.py
* Limited to openstack as GCE caused problems
> Fix compare

- cfme/configure/settings.py
* self.timeprofile -> self.obj
> Fix Navigation for Timeprofiles

- cfme/configure/settings.py
Time profile fix
{{pytest: cfme/tests/configure/test_timeprofile.py}}
> Fixed timeprofile creation

- cfme/control/explorer.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/control/test_actions.py -k test_action_tag --use-provider vsphere55 --long-running}}
> Fix tree in control

- cfme/tests/configure/test_access_control.py
{{pytest: -k test_user_remove_tag cfme/tests/configure/test_access_control.py}}
> Fix remove tag test

- cfme/tests/configure/test_timeprofile.py
{{pytest: cfme/tests/configure/test_timeprofile.py -k test_timeprofile_duplicate_name}}
> Skip time profile blocker

- cfme/tests/cloud_infra_common/test_discovery.py
Self explanatory
{{pytest: cfme/tests/cloud_infra_common/test_discovery.py}}
> Fix vm name for test

- cfme/tests/distributed/test_appliance_replication.py
> Fix dist scope

- cfme/tests/cloud/test_providers.py
Fix azure testing
{{pytest: cfme/tests/cloud/test_providers.py -k test_provider_add_with_bad_credentials --use-provider azure}}
> Fix bad password test

- cfme/configure/settings.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_default_filters.py -k test_cloudimage_defaultfilters}}
> Fixed tree view for filters

- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
* Quad calling was bad before this time it uses internal generator
> Fixed some calls to the quads

- cfme/tests/openstack/test_host_cpu_resources.py
- cfme/tests/openstack/test_host_devices.py
- cfme/tests/openstack/test_host_hostname.py
- cfme/tests/openstack/test_host_memory.py
Purpose or Intent:
The SSA is irrelevant by the added tests, motivation to save test time and overkilling tests
> moved redundant SSA from tests

- cfme/tests/configure/test_log_depot_operation.py
{{pytest:  cfme/tests/configure/test_log_depot_operation.py}}
> Remove blocker log_depot

- cfme/tests/containers/test_topology.py
- cfme/web_ui/topology.py
Tests for containers Topology page + Framework updates
{{pytest: cfme/tests/containers/test_topology.py  -v --use-provider container }}
> Container Topology test + Framework updates

- scripts/ec2cleanup.py
Added ec2cleanup automated script, which will be running from jenkins.
All these deleting methods are free to discuss. Maybe we should not delete instances with some prefix and should delete even newer instances.
This PR is waiting for wrapanapi PR:https://github.com/ManageIQ/wrapanapi/pull/79, because it depends on it.
> Ec2cleanup

- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_analysis_profiles.py
- cfme/web_ui/__init__.py
{{ pytest: cfme/tests/configure/test_analysis_profiles.py}}
> Fix test_analysis_profile

- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_myservice.py
Vm name Change - underscore is removed.
> VM name change fix

- scripts/ec2cleanup.py
* ec2 instances cost, this cleanup script is leveraged to list all the existing instances on ec2 across
regions. If regex and max hours are provided then it deletes the instances matching the regex.
> list existing ec2 instances in all the regions.

- cfme/configure/access_control.py
- cfme/services/catalogs/catalog.py
{{pytest: cfme/tests/services/test_catalog.py }}
> fix test_catalog.py

- cfme/tests/containers/test_data_integrity_for_topology.py
Change Comments only:
* remove irrelevant 
* add related CMP's
> Comments change only

- conftest.py
This is to ensure that people know what version of the appliance is supported by the framework at point X
> Add a warning if running unsupported appliance

- cfme/configure/settings.py
- cfme/tests/configure/test_timeprofile.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/configure/test_timeprofile.py}}
> Fix test_timeprofile

- cfme/tests/containers/test_containers_main_pages_sort.py
> blocker fix

- scripts/clone_template.py
* when local provider data is used, specify the
default ip file.
> specify the default ip file for clone-template.

- cfme/tests/test_rest.py
- utils/api.py
__Adding tests__ for new REST API functionality.
> adding tests for new REST API functionality

- cfme/web_ui/__init__.py
Fix cfme.web_ui.StatusBox xpath
Tested under Downstream 5.6/5.7 (with cfme/tests/containers/test_data_integrity_for_topology.py)
> Fix StatusBox xpath

- cfme/containers/provider/__init__.py
- cfme/tests/containers/test_provider_add_token.py
- cfme/tests/containers/test_relationships_tables.py
{{pytest: cfme/tests/containers/test_provider_add_token.py -v --use-provider container }}
Adding provider to CFME with the valid token
> Adding provider with the valid token

- utils/version.py
* darga-5 is based on cfme 5.6.3, this is included to vstring.
> include darga-5 in version string.

- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/deployment_methods.py
- cfme/tests/middleware/server_methods.py
- cfme/tests/middleware/test_middleware_datasource.py
- cfme/tests/middleware/test_middleware_deployment.py
- cfme/tests/middleware/test_middleware_domain_server.py
- cfme/tests/middleware/test_middleware_drivers.py
- cfme/tests/middleware/test_middleware_messagings.py
- cfme/tests/middleware/test_middleware_server.py
- cfme/tests/middleware/test_provider_timelines.py
> Better solution with getting EAP7, Hawkular and Domain mode servers.

- cfme/tests/cloud_infra_common/test_vm_ownership.py
- cfme/web_ui/__init__.py
{{pytest: cfme/tests/cloud_infra_common/test_vm_ownership.py}}
> Fix test_vm_ownership.py

- cfme/common/__init__.py
- cfme/middleware/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/domain.py
- cfme/middleware/messaging.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
- cfme/middleware/server.py
- cfme/middleware/server_group.py
- cfme/middleware/topology.py
Did changes for all objects, all navigation and validation methods.
Removed several odd methods used in old navigation stuff.
{{pytest: cfme/tests/middleware --use-provider hawkular }}
> Adjusted Middleware Provider Objects into Navymazing Style.

- cfme/tests/cloud_infra_common/test_events.py
- cfme/web_ui/__init__.py
fix of test_events.py  and probably other tests which  use TreeView branches.
related to #3813 
{{pytest: --use-provider=vsphere55 cfme/tests/cloud_infra_common/test_events.py}}
> test_events.py fix

- data/firefox_profile.js.template
Sometimes we end up with too many connections open
Allow us to use more connections in testing
> Temporary fix for max number of connections

- cfme/tests/test_rest.py
__Adding tests__ for bulk queries referencing resources by attributes.
> REST API tests for bulk queries using attributes

- cfme/tests/containers/test_basic_metrics.py
{{pytest: cfme/tests/containers/test_basic_metrics.py -v --use-provider cm-env2 }}
Added CMP# label.
> Added CMP# to test_basic_metrics

- cfme/services/myservice.py
- utils/appliance/implementations/ui.py
Some fixes from another PR which will never get merged
> Some fixes from another PR which will never get merged

- cfme/tests/containers/test_containers_summary.py
{{pytest: cfme/tests/containers/test_containers_summary.py -v --use-provider cm-env2 }}
The test wasn't running according to it's test case.
> Test Containers Summary fix

- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/jdbc_driver_methods.py
- cfme/tests/middleware/test_middleware_datasource.py
- cfme/tests/middleware/test_middleware_drivers.py
Did some refactorings in datasource and JDBC driver methods.
{{pytest: cfme/tests/middleware/test_middleware_datasource.py cfme/tests/middleware/test_middleware_drivers.py -v --use-provider hawkular --long-running}}
> Added more verifications on  datasource creation as bugs are fixed.

- cfme/tests/test_rest.py
__Adding tests__ for new items in api entrypoint in 5.7
> REST API tests for new items in api entrypoint

- cfme/tests/containers/test_containers_default_project_replicators.py
__Optimizing__ the tests
{{pytest: cfme/tests/containers/test_containers_default_project_replicators.py -v --use-provider container }}
> Randomly choose the replicator, and then check all the Properties/Relationships in one navigation

- cfme/tests/cloud/test_providers.py
- utils/api.py
__Adding tests__ for cloud_networks queries.
{{pytest: '''cfme/tests/cloud/test_providers.py::TestProvidersRESTAPI'' -v'}}
> REST API tests for cloud_networks queries

- scripts/ec2cleanup.py
* included instance type in ec2 instance list report.
> included instance type in ec2 instance list report.

- scripts/template_upload_scvmm.py
__Updating tests__  because the library indexes changed after I added SCVMM 2016
> [1LP][RFR] Refined library search so that the index will always be zero.

- cfme/rest/__init__.py
- cfme/tests/test_rest.py
__Adding tests__ for "arbitration_settings" collection.
{{pytest: cfme/tests/test_rest.py -v}}
> [RFR] REST API tests for arbitration_settings

- cfme/tests/cloud/test_providers.py
__Adding tests__ for "arbitration_profiles" collection.
{{pytest: '''cfme/tests/cloud/test_providers.py::TestProvidersRESTAPI'' -v'}}
> [RFR] REST API tests for arbitration profiles

- cfme/configure/access_control.py
- cfme/fixtures/pytest_selenium.py
- cfme/tests/configure/test_access_control.py
- cfme/web_ui/accordion.py
- cfme/web_ui/flash.py
- widgetastic_patternfly.py
the test changes available menus but doesn't update menu object after change
> [RFR] fix for access control tests

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/configure/access_control.py
- cfme/configure/configuration/__init__.py
- cfme/configure/configuration/candu.py
- cfme/configure/red_hat_updates.py
- cfme/login.py
- cfme/tests/configure/test_display_settings.py
- cfme/tests/configure/test_server_name.py
- cfme/tests/configure/test_zones.py
- cfme/tests/distributed/test_appliance_replication.py
- requirements.txt
- utils/appliance/__init__.py
- utils/db_queries.py
- widgetastic_patternfly.py
> [RFR]Navmazing configuration changes

- scripts/clone_template.py
- utils/appliance/__init__.py
- utils/ssh.py
* clone_deploy is changed to specify ssh public key while appliance deployment on gce.
* appliance/__init__: configure_gce method is included, this can be improvised though.
* ssh.py is same as https://github.com/ManageIQ/integration_tests/pull/3304 but modified it to fix smoke test failures on non-root user login.
https://github.com/ManageIQ/wrapanapi/pull/90 is related to this PR
> [1LP][RFR] Changed configuration files to include gce instance to smoke tests.

- widgetastic_manageiq.py
- widgetastic_patternfly.py
1. Added Paginator widget + Pagination view for better usability
2. fixed small typo 
This change was a part of Infra Providers' conversion to widgetastic. However, I decided to split one big PR to a series of small ones because it is difficult to review one big PR and it is possible that this widget can be helpful to someone before I finished that big PR.
> [1LP][RFR] widgetastic paginator

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/tests/infrastructure/test_vm_power_control.py
> [1LP][RFR] various fixes for rhev

- cfme/tests/containers/test_containers_default_services.py
{{pytest: cfme/tests/containers/test_containers_default_services.py -v --use-provider cm-env2 }}
added: cfme/tests/containers/test_containers_default_services.py
> [RFR] test_containers_default_services

- artifactor/__init__.py
- artifactor/plugins/logger.py
- cfme/fixtures/smtp.py
- fixtures/events.py
- fixtures/parallelizer/remote.py
- scripts/dockerbot/check_prs.py
- utils/log.py
- utils/ssh.py
there is probably need to get rid of create_logger in artifactor, its not clear how to do that off-hand
> [1LP][RFR]correct logger creation and artifactor logger creation

- cfme/test_framework/config.py
- utils/conf.py
this moves our configuration object into a new package and reports all module style imports as deprecated
> [RFR]deprecate and abstract configuration module usage

- cfme/fixtures/service_fixtures.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_generic_service_catalogs.py
provider object passed instead of string
> [1LP][RFR] Provider type fix

- utils/appliance/__init__.py
* server is now a property based on _server attribute
> [1LP][RFR] Fixed server to be a littler more deferred

- cfme/tests/control/test_bugs.py
- cfme/tests/infrastructure/test_advanced_search_vms.py
Fixed some bad imports after some merges
> [RFR] Fixed some bad imports after some merges

- cfme/middleware/domain.py
- cfme/middleware/messaging.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/server.py
- cfme/middleware/topology.py
Fixing last navigations which were missed.
> [RFR] Move Middleware navigations to Navmazing.

- utils/appliance/__init__.py
Added is_idle property so we can track idle appliances with ec2 provider to reduce costs of AWS.
> [RFR] Added is_idle property

- cfme/test_framework/config.py
- cfme/web_ui/utilization.py
- utils/__init__.py
- utils/log.py
This PR fixes some logging issue that cropped up with a can't concatenate, and fixes some docs issues too.
> [1LP][RFR] Fixed logging error and some docs issues

- cfme/tests/test_rest.py
Adding basic tests for "arbitration_rules" collection.
> [RFR] REST API tests for arbitration rules

- docs/conf.py
Fix mocking the import of widgetastic for docs
> [1LP][RFR] Fix mocking the import of widgetastic for docs

- cfme/cloud/flavor.py
- cfme/cloud/tenant.py
RHCFQE-1458
Clean up cloud.flavor a bit, merged early.
Add Navigatable destinations for cloud.tenant and CRUD operations
> [WIPTEST] cloud.tenant navigation and CRUD

- cfme/base/ui.py
- cfme/tests/distributed/test_appliance_replication.py
Fix up replication test calls to be future proofed
> [WIPTEST] Fix navmazing for replication

- cfme/tests/cloud/test_provisioning.py
__Adding tests__ for feature GCE preemtible VM. It was implemented in product version 5.7 and was agreed to have it in separate test for GCE.
{{pytest: cfme/tests/cloud/test_provisioning.py --use-provider gce_central --long-running}}
> [RFR] adding separate test for GCE preemtible provision feature

- utils/appliance/__init__.py
> [WIPTEST] Fixed lint error

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_generic_service_catalogs.py
Some other files need to be modified because of this navamzing change like : test_provision_stack and test_service_catalogs , which have some other failures too . 
So fixing them up in a separate PR coming soon.
> [1LP][RFR] Service Catalog Navmazing

- cfme/tests/containers/test_views_objects.py
{{pytest: cfme/tests/containers/test_views_objects.py -v --use-provider cm-env2 }}
Navmazing conversion
> [WIPTEST]Navmazing Conversion for test_views_objects

- cfme/containers/overview.py
- cfme/tests/containers/test_containers_overview_data_integrity.py
{{pytest: cfme/tests/containers/test_containers_overview_data_integrity.py -v --use-provider cm-env2 }}
Added test test_containers_overview_data_integrity.py.
Fix CMP pointers in test_data_integrity_for_topology.py.
> [RFR] test_containers_overview_data_integrity.py + ContainersOverview object

- cfme/tests/containers/test_containers_summary.py
{{pytest: cfme/tests/containers/test_containers_summary.py -v --use-provider cm-env2 }}
Navmazing conversion
> [WIPTEST]Navmazing Conversion for test_containers_summary

- cfme/tests/containers/test_data_integrity_for_topology.py
{{pytest: cfme/tests/containers/test_data_integrity_for_topology.py -v --use-provider cm-env2 }}
Navmazing conversion
> [WIPTEST]Navmazing Conversion for test_data_integrity_for_topology

- cfme/cloud/provider/__init__.py
- cfme/common/__init__.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/test_framework/config.py
- docs/conf.py
- docs/getting_started.rst
- docs/guides/editors.rst
- docs/requirements.txt
- utils/__init__.py
- utils/appliance/__init__.py
- utils/browser.py
- utils/units.py
> [1LP][RFR] Fix docs again

- fixtures/nelson.py
Fixes Nelson due to an upgrade of sphinx
> [1LP][RFR]Fix nelson

- requirements.txt
> [RFR] Fix requirements

- cfme/tests/services/test_myservice.py
- cfme/web_ui/toolbar.py
{{pytest: --use-provider=vsphere55 --long-running cfme/tests/services/test_myservice.py cfme/tests/services/test_service_catalogs.py}}
> [1LP][RFR] small fix for service tests

- cfme/automate/__init__.py
- cfme/automate/explorer.py
{{pytest: -v -m crud cfme/tests/automate/ -k 'domain or namespace or class_ or method or instance'}}
> [1LP][RFR] Navmazing for Automate Explorer

- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/cloud_infra_common/test_tag_objects.py
- cfme/tests/infrastructure/test_snapshot.py
this PR includes replacement for some forgotten force_navigate calls
> [RFR] forgotten force_navigate calls

- cfme/automate/explorer.py
I tested it and got full green.
{{pytest: -v -m crud cfme/tests/automate/ -k 'domain or namespace or class_ or method or instance'}}
> [RFR][1L] Small fix to support upstream for AE

- fixtures/middleware_log.py
- utils/log_validator.py
Added new fixture for validating log.
> [RFR] Added new class for validating log content during test execution. 

- cfme/intelligence/chargeback.py
- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
> [1LP][RFR]Chargeback Tests

- scripts/clone_template.py
* added 'with' to appliance object to invoke  __enter__ in IpAppliance()
which would push the current appliance to stack, otherwise it
tries to pick the base_url from env.yaml
> [1LP][RFR] updated configure_gce to push the appliance to stack.

- cfme/automate/__init__.py
- cfme/automate/simulation.py
- cfme/base/ui.py
To test:
```python
from cfme.automate.simulation import simulate
simulate(request='InspectMe')
sel._thread_local.ajax_timeout = 30
```
Tested in ipython and it works.
> [1LR][RFR] AE Simulation converted to navmazing

- fixtures/widgets.py
Navigate to dashboard using registered Server destination.
> [RFR] Update fixtures.widgets, remove force_navigate

- cfme/intelligence/reports/__init__.py
- cfme/intelligence/reports/dashboards.py
- cfme/intelligence/reports/import_export.py
- cfme/intelligence/reports/menus.py
- cfme/intelligence/reports/reports.py
- cfme/intelligence/reports/saved.py
- cfme/intelligence/reports/schedules.py
- cfme/intelligence/reports/widgets.py
- cfme/tests/intelligence/reports/test_menus.py
- utils/appliance/implementations/ui.py
1. no force_navigates in cfme->intelligence->reports->* items 
{{ pytest: cfme/tests/intelligence/reports/test_menus.py cfme/tests/intelligence/reports/test_widgets.py cfme/tests/intelligence/test_dashboard.py cfme/tests/intelligence/reports/test_report_chargeback.py cfme/tests/intelligence/reports/test_report_corresponds.py }}
> [RFR] moving reports to navmazing

- scripts/browser.py
> [1LP][RFR] Update scripts/browser, use navigate_to

- cfme/services/catalogs/__init__.py
- cfme/services/catalogs/orchestration_template.py
- cfme/tests/services/test_orchestration_template.py
- widgetastic_manageiq.py
- widgetastic_patternfly.py
{{pytest: cfme/tests/services/test_orchestration_template.py}}
> [RFR] navmazing/widgetastic for orchestration templates

- utils/providers.py
Add class map for prov types coming from prov_class
> [1LP][RFR] Update utils.providers._setup_providers, use navigate_to

- cfme/services/requests.py
Should have no impact on tests.
This module really needs refactored, scoping for removal of force_navigates.
> [RFR] Update services.requests, Navmazing 'All'

- cfme/base/ui.py
- cfme/intelligence/rss.py
- cfme/tests/configure/test_about_links.py
- cfme/tests/configure/test_server_name.py
- cfme/tests/intelligence/test_rss.py
1. added RSS destination
2. removed rss force_navigate calls
3. replaced several ocasionally found force_navigates
> [RFR] navmazing's RSS destination

- utils/db.py
The link in Issue #2999 is to like 297, which isn't right anymore, but I think this is what @jkrocil was talking about. maybe.
Fixes #2999
> [WIPTEST] Update utils.db, logging tweak in Db._table

- cfme/dashboard.py
- cfme/intelligence/reports/dashboards.py
Cleared up some dashboards/report dashboards navigation, version picking.  DRY'd Cloud Intel->Dashboard navigation.
Removed a `force_navigate` or two, dropped a `nav.add_branch` and dependency on `cfme.web_ui.menu`.
> [RFR] Refactor dashboard and report dashboard for nav

- cfme/tests/test_ui_problems.py
- cfme/tests/webui/test_splitter.py
> [1LP][RFR] Fix test splitter

- cfme/common/vm.py
{{pytest: cfme/tests/control/test_bugs.py -k test_scope_windows_registry_stuck}}
> [RFR][L1] Fix VM force_navigates

- cfme/base/ui.py
- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_analysis_profiles.py
- cfme/tests/control/test_compliance.py
- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/infrastructure/test_instance_analysis.py
> [RFR] moving configuration to  navmazing

- cfme/services/workloads.py
- cfme/tests/configure/test_default_filters.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/webui/test_splitter.py
- utils/appliance/implementations/ui.py
__adding__ new navigation to Services/Workloads and replacing old force_navigates
> [1LP][RFR]Navmazing in Workloads

- cfme/tests/configure/test_visual_infra.py
- cfme/tests/integration/test_aws_iam_auth_and_roles.py
- cfme/tests/integration/test_ldap_auth_and_roles.py
> [RFR] Fixed a few imports

- cfme/control/explorer/__init__.py
- cfme/control/explorer/actions.py
- cfme/control/explorer/alert_profiles.py
- cfme/control/explorer/alerts.py
- cfme/control/explorer/conditions.py
- cfme/control/explorer/policies.py
- cfme/control/explorer/policy_profiles.py
- requirements.txt
- widgetastic_manageiq.py
- widgetastic_patternfly.py
{{pytest: cfme/tests/control/test_basic.py -v --long-running -k 'not Container and not Pod and not Replicator and not Middleware'}}
> [RFR] Tweaking the objects for WT 0.3.2

- scripts/dockerbot/pytestbase/setup.sh
> [WIP][NOTEST] Trying Keep Alive on PRT

- cfme/test_framework/sprout/client.py
- cfme/tests/cli/test_appliance_cli.py
- utils/appliance/__init__.py
- utils/tests/test_appliance_cli.py
- Adding appliance_console_cli class 
- Adding test to appliance_console_cli
> [RFR] Adding tests for appliance_console_cli

- cfme/control/explorer/policies.py
- cfme/control/explorer/policy_profiles.py
- cfme/tests/control/test_bugs.py
{{pytest: -v -k 'test_check_compliance_history' --long-running}}
__New test__ for feature Control to cover case test_check_compliance_history. https://bugzilla.redhat.com/show_bug.cgi?id=1375093
> [1LP][RFR] New test test_check_compliance_history

- cfme/tests/infrastructure/test_infra_quota.py
Adding tests for feature quota to cover cases for memory,storage and vm quota.
{{pytest: -v -k 'test_tenant_quota_max_memory_check or test_tenant_quota_max_storage_check or test_tenant_quota_max_num_vms_check'}}
> [1LP][RFR] Automated quota test for memory, storage and vms

- utils/appliance/implementations/ui.py
Fixed wrapping of other components of navigation
> [1LP][RFR] Fixed wrapping of other components of navigation

- cfme/fixtures/pytest_selenium.py
- cfme/services/catalogs/catalog.py
- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/orchestration_template.py
- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
{{pytest: -v --long-running --use-provider ec2 cfme/tests/services/test_provision_stack.py }}
> [1LP][WIP] addressing stack failures

- cfme/services/catalogs/catalog_item.py
- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_different_dialogs_in_catalogs.py
Tag dialog test jenkins failure fix
> [RFR]Tag dialog failure fix

- utils/blockers.py
this simply removes an over-complex piece of code that adds no value
it also ensures better python3 support by using six
> [1LP][RFR] simplify logic in blockers + better python3 compat

- cfme/tests/test_rest.py
Adding basic tests for "notifications" collection.
**PRT results**:
all tests passed on 5.7, no tests were run on upstream (PRT hiccup? @psav)
> [1LP][RFR] REST API tests for notifications

- cfme/control/explorer/policy_profiles.py
- cfme/services/requests.py
- cfme/tests/control/test_actions.py
- fixtures/provider.py
{{pytest: -v -k 'test_action_cancel_clone' --long-running}}
New test for Control which tests "Cancel vCenter task" action. https://bugzilla.redhat.com/show_bug.cgi?id=1381255
> [RFR][1LP] Test action cancel clone

- utils/providers.py
Fixes the case where a provider doesn't have tags
> Fix tags usage

- scripts/template_upload_all.py
- utils/providers.py
> Fix utils.providers.list_providers and make upload script more verbose

- cfme/control/explorer/actions.py
- cfme/control/explorer/policies.py
- utils/appliance/implementations/ui.py
test_events.py fix
{{pytest: --use-provider=vsphere55 cfme/tests/cloud_infra_common/test_events.py}}
> [1LP][RFR] test_events.py fix

- cfme/services/myservice.py
- cfme/tests/services/test_add_remove_vm_to_service.py
{{pytest: -v --long-running --use-provider vsphere55 cfme/tests/services/test_add_remove_vm_to_service.py }}
Fixed two locators and one Navmazing conversion error
> [RFR]MyService minor fixes

- cfme/tests/containers/test_topology.py
{{pytest: cfme/tests/containers/test_topology.py -v --use-provider container }}
> [RFR] Fix test topology search + add blocker mark

- cfme/provisioning.py
Split this from PR #4013 to get it merged sooner since its imported by several modules that we'll be converting to widgetastic.
I've tested locally with instance provisioning and the form was properly instantiated and filled. I didn't hit every provisioning field in testing.
Leaving the old form in place for now, it can be removed later once we've removed the dependencies on it.
Upstream PRT failure  can be ignored. 5.6 and 5.7 passed, basically irrelevant.
> [1LP][RFR] Widgetastic ProvisioningForm 

- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/hawkular.py
turning back this optimization after discussion
> [RFR] turn mgmt_class back into normal properties

- cfme/control/explorer/alerts.py
- cfme/control/explorer/conditions.py
- cfme/control/explorer/policies.py
- utils/log_validator.py
> [RFR] Fixed docs again

- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/middleware/provider/hawkular.py
It works for me only in this way.
> [RFR] Another attempt to fix mgmt_class

- scripts/cleanup_old_vms.py
- scripts/cleanup_openstack_fips.py
- scripts/cleanup_openstack_volumes.py
- scripts/ec2cleanup.py
- scripts/get_unregistered_vmware_files.py
- scripts/latest_template_tester_report.py
- scripts/sync_template_tracker.py
- scripts/template_upload_ec2.py
- scripts/template_upload_gce.py
- scripts/template_upload_rhevm.py
- scripts/template_upload_rhos.py
- scripts/template_upload_scvmm.py
- scripts/template_upload_vsphere.py
- utils/providers.py
> [RFR][1LP] Add fn to list provider keys with simple filtering for scripts

- fixtures/templateloader.py
> [1LP][RFR] template loader - list_provider_keys

- cfme/tests/containers/test_containers_main_pages_sort.py
{{pytest: cfme/tests/containers/test_containers_main_pages_sort.py -v }}
> [1LP][RFR] unblock added for cla != ContainersProvider

- utils/appliance/__init__.py
> [RFR] Fix evm service restart

- utils/appliance/__init__.py
Tested `rude=True` and `rude=False`, both OK.
> [RFR] Fix evm service restart fo real this time

- cfme/common/vm.py
- cfme/tests/infrastructure/test_vm_power_control.py
- utils/virtual_machines.py
__Adding tests__ for VMs with installed VM Tools  
and small review/checks in module
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py "-k test_no_template_power_control" --use-provider vsphere6-nested --long-running}}
> [1LP][RFR] Guest addition test for VMware VMs

- cfme/configure/tasks.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/web_ui/__init__.py
- utils/ssh.py
Smart State analysis functionality check for single container image.
Added functions & modifications to framework.
{{pytest: cfme/tests/containers/test_containers_summary.py -v --use-provider container }}
> [RFR] SmartState Analysis + Framework changes

- cfme/common/provider.py
- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/domain.py
- cfme/middleware/messaging.py
- cfme/middleware/server.py
- cfme/tests/containers/test_containers_overview_data_integrity.py
- fixtures/prov_filter.py
- utils/appliance/__init__.py
- utils/providers.py
- utils/testgen.py
$subject + also replaces old `list_providers` with new `list_providers_by_class`.
> [1LP] [RFR] new_list_providers -> list_providers

- scripts/refactoring/provider_move.py
> [RFR] provider move refactor script: dont push up packages

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/openstack.py
Since 5.7 tenant mapping button has been added.
True, False
Default value: False
tenant_mapping is the key to be in cfme_data.yaml file
> [1LP][RFR] tenant mapping

- cfme/automate/__init__.py
- cfme/automate/explorer.py
- cfme/base/ui.py
Fixing the menu change in upstream
> [RFR] Fixed name in upstream

- cfme/containers/template.py
- cfme/tests/containers/test_containers_templates.py
{{pytest: cfme/tests/containers/test_containers_templates.py -v --use-provider cm-env1 }}
This test checks the Container Templates menu.
This PR contains a Container Template object for additional tests
> [RFR] Containers Templates Test

- cfme/containers/template.py
- cfme/tests/containers/test_containers_templates.py
{{pytest: cfme/tests/containers/test_containers_templates.py -v --use-provider cm-env1 }}
> [RFR]Test containers templates fix 

- cfme/tests/containers/test_containers_properties.py
{{pytest: cfme/tests/containers/test_containers_properties.py -v --use-provider cm-env1 }}
> [1LP] [RFR] Randomize tested objects

- cfme/tests/control/test_actions.py
- utils/appliance/__init__.py
{{pytest: -k test_db_restore}}
> [1LP][RFR] Fixed a call in destroy

- fixtures/browser.py
Try to restart the browser if it failed during a test ready for the next one
> [1LP][RFR] Browser restarter

- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/rhevm.py
Some strings changed in version 5.7.1 and tests are failing, this should fix (at least some of) those issues
> [1LP] [RFR] Changed strings for 5.7.1

- cfme/automate/service_dialogs.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
Removed service name from assert as the new service name has random timestamp appended and changed key in heat provisioning
> [1LP][RFR] Service name removed from assert

- cfme/automate/__init__.py
- cfme/automate/buttons.py
- cfme/tests/automate/test_buttons.py
{{pytest: -v cfme/tests/automate/test_buttons.py::test_button_avp_displayed --long-running}}
> [RFR] Fix button avp check test; fix is_displayed oversight

- widgetastic_manageiq.py
1. Stepper control
2. RadioGroup control + RadioButton
3. BreadCrumb control
BTW, I've tested these widgets manually. I'm planning to do better testing when I finish views where those are supposed to use.
> [1LP] [RFR] new widgetastic widgets

- widgetastic_manageiq.py
{{pytest: -v -k 'test_policy_profile_crud' --long-running}}
Small refactoring for MultiBoxSelect and CheckboxSelect widgets. Cast @mfalesni.
> [1LP][RFR] MultiBoxSelect and CheckboxSelect widgets refactoring

- cfme/infrastructure/host.py
- cfme/infrastructure/provider/openstack_infra.py
A method to upload a json file of new host as an openstack undercloud new node
> [1LP][RFR] register nodes method

- cfme/automate/buttons.py
- cfme/tests/automate/test_buttons.py
- cfme/web_ui/__init__.py
- widgetastic_patternfly.py
{{pytest: cfme/tests/automate/test_buttons.py::test_button_on_host --long-running -v --use-provider vsphere55}}
> [1LP] [RFR] Fix the test_button_on_host

- docs/guides/browser_configuration.rst
- docs/guides/vnc_selenium.rst
I seem to look this same information up about once a quarter so probably others may want the information as well.  I've never actually added to the docs, so feel free to help me if it needs work or isn't necessary.
> [RFR] Added explanation of Selenium Standalone Server to the Guides

- cfme/common/vm.py
- cfme/tests/control/test_compliance.py
{{pytest: -v -k 'test_check_compliance_history'}}
__Refactoring__ of vm compliance checking.
> [1LP][RFR] Refactoring in vm compliance checking

- fixtures/templateloader.py
* Introduces a new --use-template-cache option
* Fails over gracefully if there is no cache and pulls from source
> [1LP][RFR] Cached Template Loader

- utils/appliance/__init__.py
Generic getter as discussed with @mfalesni
> [1LP][RFR] Generic getter for collections usage

- cfme/test_framework/sprout/client.py
- cfme/tests/test_db_migrate.py
- conftest.py
- fixtures/appliance.py
- utils/appliance/__init__.py
{{pytest: -k test_db_migrate -v}}
> [1LP][RFR] Fix db_migrate fixtures & add fixtures.appliance

- cfme/tests/cli/test_appliance_cli.py
> [RFR][1LP] Fixed logger call

- cfme/tests/cloud_infra_common/test_retirement.py
> [RFR][1LP] Fixed a retirement test

- cfme/cloud/instance/__init__.py
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k test_quadicon_terminate_cancel}}
> [1LP][RFR] Fixed instance test

- cfme/intelligence/reports/reports.py
Added return statement in select()in reports/reports.py.
> [RFR][1LP]Fix report creation failure

- cfme/tests/containers/test_containers_default_services.py
- cfme/tests/containers/test_containers_default_views.py
- cfme/tests/containers/test_containers_templates.py
- cfme/tests/containers/test_relationships_tables.py
{{pytest: cfme/tests/containers/test_relationships_tables.py -v --use-provider cm-env1 }}
> [RFR] More test + Fixes

- utils/bz.py
> [RFR] A simple, oneliner fix for Bugzilla

- utils/trackerbot.py
- utils/version.py
Backport (needed by template tester)
> Update utils trackerbot and version for cfme 58 (#4102)

- cfme/optimize/__init__.py
- cfme/optimize/bottlenecks.py
- cfme/tests/optimize/test_bottlenecks.py
- utils/appliance/__init__.py
- widgetastic_patternfly.py
{{ pytest: cfme/tests/optimize/test_bottlenecks.py}}
10117 - successful run, after this - problem with appliances (only with upstream)
> [1LP][RFR] New Bottleneck tests

- cfme/tests/cli/test_evmserverd.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/services/test_service_catalogs.py
- cfme/tests/test_rest.py
it does not use the correct logger to begin with
> [1LP][RFR] remove using pytest.wait_for

- scripts/cleanup_edomain_templates.py
Taken from Amogh's PR #3863
I have tested the script, executing locally. It successfully cleaned up old templates on rhevm36, and found no templates to delete on rhvqe40
> [RFR] rhevm export cleanup

- cfme/tests/cli/test_evmserverd.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/services/test_service_catalogs.py
- cfme/tests/test_rest.py
Reverts ManageIQ/integration_tests#4172
> Revert "[1LP][RFR] remove using pytest.wait_for"

- cfme/services/catalogs/catalog_item.py
- cfme/services/myservice.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
> [1LP][RFR]Ansible retire test

- scripts/dockerbot/sel_container.py
* allow user to specify 'vncviewer' on command line or in the config file
(`xdg-open vnc://` in gnome works only with `vinagre`)
* more useful check if VNC session is available
**PRT:**
standalone script, so no PRT necessary
> [1LP][RFR] vncviewer selection; vnc session checking

- utils/browser.py
> [RFR] browser wharf: remove manual renew alltogether

- cfme/services/workloads.py
- cfme/tests/configure/test_default_filters.py
- widgetastic_manageiq.py
__Updating Workloads__ with widgetastic + widget for simple Search
{{pytest: cfme/tests/configure/test_default_filters.py "-k test_service" }}
> [1LP][RFR]Widgetastic updates to Workloads + Search Widget

- sprout/appliances/tasks.py
This is needed to make RHEV team happy - they don't use Sprout but Sprout will be able to see and manage templates and since their provider is in yamls, this is the last bit that will ensure the provider won't be unnecessarily touched or making a ton of backlogged tasks to create a template which will fail anyway due to 0 in the limit.
> [WIP][NOTEST] Sprout - Small tweak for preconfiguration logic

- cfme/control/explorer/actions.py
- cfme/control/explorer/alert_profiles.py
- cfme/control/explorer/alerts.py
- cfme/control/explorer/policies.py
- cfme/tests/control/test_alerts.py
- fixtures/provider.py
- widgetastic_manageiq.py
{{pytest: -v -k "test_alert_vm_turned_on_more_than_twice_in_past_15_minutes" --long-running}}
__Implemented__ adding emails notifications for alerts.
> [1LP][RFR] Emails notifications for alerts

- cfme/tests/cloud/test_providers.py
{{pytest: cfme/tests/cloud/test_providers.py -v -k TestProvidersRESTAPI}}
> [1LP][RFR] check response status code in REST API tests for cloud providers

- widgetastic_manageiq.py
No tests use this yet, but I tested it in Automate/Provisioning dialogs and it worked fine.
> [1LP][RFR] manageiq_widgetastic.py: Add sorting capability to the Table class.

- cfme/tests/cloud/test_provisioning.py
Fixes for `test_provision_from_template_using_rest[azure]`
First problem was caused by camel case `instance_type`, when it's actually lower case in manageiq:
```
flavors = rest_api.collections.flavors.find_by(name=instance_type)
>       assert len(flavors) > 0
E       assert 0 > 0
E        +  where 0 = len(<SearchResult for <Collection u'flavors' (u'Flavors')>>)
```
Second problem was caused by missing parameters:
```
Failed: Error when provisioning: `[Azure::Armrest::BadRequestException]: Required parameter 'adminUsername' is missing (null).`
```
{{pytest: cfme/tests/cloud/test_provisioning.py  --use-provider azure -v -k test_provision_from_template_using_rest}}
> [1LP][RFR] fix test_provision_from_template_using_rest[azure]

- cfme/configure/configuration/__init__.py
- fixtures/browser.py
You can review the single commits if you want.
> [RFR][1LP] Jenkins fixes

- utils/appliance/implementations/ui.py
> [1LP][RFR] Added a noop to shortcut some navmazing fns

- cfme/tests/automate/test_rest.py
{{pytest: cfme/tests/automate/test_rest.py -v}}
> [1LP][RFR] check response status code in REST API tests for searching in automate

- cfme/tests/infrastructure/test_vm_rest.py
{{pytest: cfme/tests/infrastructure/test_vm_rest.py -v}}
> [1LP][RFR] check response status code in REST API tests for vm deletion

- utils/browser.py
Necessary, for making tests pass + keeping keepalive ;)
> [RFR] Keep alive thread :(

- scripts/cleanup_old_vms.py
> [RFR] Update scripts.cleanup_old_vms, default log file

- cfme/configure/settings.py
{{pytest: cfme/tests/configure/test_visual_cloud.py -k test_grid_page_per_item}}
> [RFR] Fixed where '20' had become '20 items'

- cfme/tests/infrastructure/test_rest_providers.py
{{pytest: cfme/tests/infrastructure/test_rest_providers.py -v}}
> [1LP][RFR] check response status code in REST API providers tests

- cfme/tests/configure/test_access_control.py
- cfme/tests/intelligence/test_dashboard.py
{{pytest: cfme/tests/configure/test_access_control.py -k test_user_login}}
> [RFR] Fixed dashboard navs

- cfme/control/explorer/actions.py
{{pytest: -v -k 'test_action_crud' --long-running}}
__Fixing__  Action class.
> [RFR] Fix in Action class

- cfme/automate/buttons.py
- cfme/automate/explorer/method.py
- cfme/tests/automate/test_class.py
- utils/__init__.py
- utils/appliance/__init__.py
{{pytest: cfme/tests/automate/test_domain.py cfme/tests/automate/test_namespace.py cfme/tests/automate/test_class.py cfme/tests/automate/test_instance.py cfme/tests/automate/test_method.py -v --long-running }}
> [1LP][RFR] Fix and optimize some automate tests

- cfme/tests/test_utilization_metrics.py
{{pytest: cfme/tests/test_utilization_metrics.py -k test_raw_metric_host_disk}}
> [WIP] Fixed test

- cfme/test_framework/sprout/plugin.py
The function to check if a pool already exists for a given Jenkins job uses the partial match from sprout.find_pools_by_description. It doesn't support full regex match, and a partial match will return jenkins-job-name-12345 and jenkins-job-name-other-56789
Verify that the pool with a partially matching description is an exact match for jenkins-job-name-[pool] and there isn't any other text between the pool ID and the job name
**This fix is untested**
I could use some help in testing this change. @mfalesni ?
FIXES RHCFQE-1871
> [RFR] Fix erroneous partial matches on sprout pools for jenkins jobs

- cfme/configure/configuration/__init__.py
* Fixed a missing widgetastic view
* Fixed a wrong reference to obj
{{pytest: cfme/tests/configure/test_analysis_profiles.py -k test_vm_analysis_profile_crud --long-running}}
> [1LP][RFR] Fixed a missing view and an obj bug

- cfme/automate/explorer/__init__.py
- utils/appliance/implementations/ui.py
{{pytest: cfme/tests/automate/test_domain.py::test_domain_crud -v --long-running}}
> [RFR] Remove stale step and a unused method

- cfme/tests/cloud_infra_common/test_power_control_rest.py
* fixing suspend test failures on gce and ec2
* refactoring to reuse single vm for all tests - other benefit is broader testing of transitioning between different power states
* better verification of REST API response
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py -v --use-provider gce_central}}
> [RFR] fix test_power_control_rest tests

- cfme/tests/intelligence/reports/test_crud.py
Some reports were renamed.
I've adjusted config file for appropriate reports tests.
> [RFR] report test fix

- utils/browser.py
> [1LP][RFR] Removed a bad assertion

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
Fixes stack provision for openstack
Failures are unrelated another PR needs merging first
> [1LP][RFR] Fixed some stack testing

- cfme/tests/services/test_provision_stack.py
{{pytest: cfme/tests/services/test_provision_stack.py -k test_remove_template_provisioning}}
> [1LP][RFR] Fixed service tests

- utils/appliance/__init__.py
Tested manually, fixes RHCFQE-1955. This was fun to debug.
> [RFR] Fix incorrect db session expire call

- cfme/base/ui.py
- cfme/configure/about.py
- cfme/configure/configuration/__init__.py
- cfme/tests/configure/test_server_name.py
{{pytest: -v cfme/tests/configure/test_server_name.py cfme/tests/configure/test_tag.py cfme/tests/configure/test_workers.py cfme/tests/automate/test_domain.py::test_domain_crud --use-template-cache -k 'not REST'}}
> [RFR] Mostly fix up is_displayed in Configuration; Fix some tests

- cfme/tests/test_utilization_metrics.py
Updating blocker BZ info for RHEV.
> [1LP][RFR]Update blocker BZ info for RHEV

- cfme/tests/infrastructure/test_provisioning_rest.py
HTTP response status code checking
**PRT:**
@mshriver 5.6 error is from teardown, the test itself passed. The `delete_vm` from mgmtsystem module is supposed to stop the vm before deleting it but for some reason it failed to do so. I could wrap `provider.mgmt.delete_vm(vm_name)` in try except and mask such issues, but I think it's better to notice them and maybe make mgmtsystem more robust over time. Looking briefly at the code responsible for stopping vm before deleting, it always returns True:
```
vm.stop()
self.wait_vm_stopped(vm_name)
return True
```
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py -v}}
> [1LP][RFR] check response status code in test_provisioning_rest

- cfme/tests/infrastructure/test_advanced_search_vms.py
- cfme/web_ui/expression_editor.py
We have 20-30+ tests failing due to changes in advanced search view.
This PR should fix most such issues in 5.7.
{pytest: --use-provider=vsphere55 cfme/tests/infrastructure/test_advanced_search_vms.py}
This is just a quick fix. There will be more full one #4180 soon.
Yaml fix - https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/96
> [RFR] fix for advanced search issue

- cfme/tests/infrastructure/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
__Skipping__ VMware provisioning tests due to CFME BZ
> [WIPTEST]adding BZ skips due to 1422953

- cfme/base/ui.py
- cfme/tests/configure/test_zones.py
- utils/appliance/__init__.py
@psav I have a RFE on navmazing based on an experience from this PR :)
{{pytest: cfme/tests/configure/test_zones.py -v --long-running}}
> [RFR] Second round of zones fixing

- cfme/tests/configure/test_zones.py
Added two tests for zones
I found two tests for zones in Polarion that are not automated, so I automated them.
> [RFR][1LP] Added two tests for zones

- cfme/services/catalogs/__init__.py
- cfme/services/catalogs/catalog.py
{{pytest: -v --long-running cfme/tests/services/test_catalog.py }}
> [1LP][RFR] Catalog Widgetastic Conversion

- requirements/frozen.txt
Updating some requirements, most notably widgetastic
> [RFR][1LP] Requirements freeze for upcoming 17.1.5

- cfme/containers/node.py
- cfme/tests/containers/test_containers_default_views.py
- cfme/tests/containers/test_containers_overview_data_integrity.py
- cfme/tests/containers/test_data_integrity_for_topology.py
- cfme/tests/containers/test_relationships_tables.py
- cfme/tests/containers/test_views_objects.py
At this point most of the core Collection/Widget work is done.
Utilization and Timelines still need some work for is_displayed and their views, but the navigation works. These aren't used in tests from what I can tell.
Test files that I was changing anyway got some import cleanup. I didn't modify test behavior, limited to changing for NodeCollection on 'All' navigation.
Upstream failure on all tests in the module, screenshots show login form with a Navigation error. Investigating.
> [1LP][RFR] Update container.node, widgetastic integration

- cfme/infrastructure/host.py
- cfme/tests/control/test_compliance.py
{{pytest: -v -k 'test_compliance_with_unconditional_policy'}}
==============
New test test_compliance_with_unconditional_policy https://bugzilla.redhat.com/show_bug.cgi?id=1369488
> [1LP][RFR] New test test_compliance_with_unconditional_policy

- requirements/frozen_docs.txt
> [RFR] fix frozen module list for docs

- cfme/configure/configuration/__init__.py
depends on https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/89 
Just a fix for upcoming 5.8
> [1LP][RFR]adding Ansible role

- cfme/tests/infrastructure/test_advanced_search_vms.py
- cfme/web_ui/expression_editor.py
one more fix for search tests.
{{pytest: cfme/tests/infrastructure/test_advanced_search_vms.py}}
> [RFR] one more fix for search tests

- scripts/template_upload_vsphere.py
Added escaping for non-alphanum characters in password and also added noSSLVerify to disable interactive query for SSL check with new hosts.
> [RFR] Fix vsphere template upload

- release.py
Simple script to help show released PRs
> [WIP][NOTEST] Added release script

- utils/browser.py
* Only stop if there's something to stop
> [WIPTEST] Fixed stopper

- cfme/tests/services/test_provision_stack.py
__Fixing__
Azure VMs need to be explicitly deleted and I had a typo on the method name.  While I was in there I just went ahead and cleaned up the existing cleanup code.
{{pytest: cfme/tests/services/test_provision_stack.py::test_provision_stack -v --use-provider azure }}
> [RFR] Fix failure to delete Azure stack instances

- cfme/rest/gen_data.py
- cfme/tests/intelligence/test_chargeback.py
* refactoring
* test also DELETE method
{{pytest: cfme/tests/intelligence/test_chargeback.py -v -k REST}}
> [RFR] refactoring; new tests; check response status code for test_chargeback

- cfme/tests/configure/test_rest_access_control.py
* refactoring
* test also DELETE method
{{pytest: cfme/tests/configure/test_rest_access_control.py -v}}
> [RFR][1LP] refactoring; new tests; check response status code for test_rest_access_control

- release.py
Enhancement to rel_update script
> [RFR][1LP] Rel update

- release.py
More functionality to the release script
> [RFR] Added more release functionality

- release.py
What if it's None?! This fixes that
> [RFR] Last Release Update

- scripts/release.py
Final Update to allow proper args and help
> [RFR] Moved to real script

- scripts/release.py
- setup.py
More improvements to the release script
> [1LP][RFR] Release updates

- widgetastic_manageiq.py
> [1LP][RFR] Added quote escaping into AlertEmail view

- cfme/tests/configure/test_tag_category.py
* refactoring
* test also DELETE method
{{pytest: cfme/tests/configure/test_tag_category.py -v -k TestCategoriesViaREST}}
> [1LP][RFR] refactoring; new tests; check response status code for test_tag_category

- cfme/rest/gen_data.py
* preserve HTTP response status so it can be checked in the test
* use `_creating_skeleton` wherever possible
* refactoring
Tests in files specified below are using all of the methods in `gen_data` apart from `arbitration_settings` and `orchestration_templates` that I tested locally.
{{pytest: cfme/tests/configure/test_rest_access_control.py cfme/tests/configure/test_tag.py -v -k REST --use-provider vsphere6-nested}}
> [1LP][RFR] gen_data refactoring to use _creating_skeleton; preserve http response status

- cfme/tests/configure/test_zones.py
Moved to the generic getter for collections to set a good example
> [RFR] Move to the generic getter

- scripts/release.py
Exception on no valid label for PR
> Exception now raised if there is no valid_label

- cfme/fixtures/vm_name.py
Fixed vm_name to be in alignment with standards
> [WIPTEST] Fixed vm_name to be in alignment with standards

- scripts/release.py
> [RFR] Fixes to allow the paging of PRs

- widgetastic_manageiq.py
Also update first_page and last_page to not throw exceptions when
already on the page
Simple method to loop over the pages and search for rows on a given
table
Tested everything locally.
RHCFQE-2110
> [RFR] Add widget_miq.PaginationPane.find_row_on_pages

- cfme/tests/infrastructure/test_vm_retirement_rest.py
* more sensible check than just comparing update time
* fix the date so it's really 5 days in the future as intended
PRT:
due to a PRT issue no tests were run on upstream
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py -v -k test_retire_vm_future --use-provider vsphere6-nested}}
> [1LP][RFR] fix test_retire_vm_future

- cfme/infrastructure/deployment_roles.py
- cfme/infrastructure/host.py
- cfme/tests/openstack/infrastructure/test_credentials_quad.py
- cfme/tests/openstack/infrastructure/test_hosts.py
- cfme/tests/openstack/infrastructure/test_relationships.py
- cfme/tests/openstack/infrastructure/test_resources.py
- cfme/tests/openstack/infrastructure/test_roles.py
More tests for Openstack Infra
> [1LP][RFR] add more openstack infrastructure tests

- cfme/control/explorer/conditions.py
- cfme/tests/control/test_basic.py
- cfme/web_ui/expression_editor_widgetastic.py
{{pytest: -v -k "test_modify_condition_expression" --long-running}}
More extensive testing of expression editor in conditions.
> [1LP][RFR] Automate condition expression editing

- cfme/tests/configure/test_access_control.py
> [RFR][1LP] Fix Automate Explorer import

- cfme/services/catalogs/catalog_item.py
{{pytest: cfme/tests/services/test_service_catalogs.py -k test_order_catalog_bundle}}
> [WIPTEST] - Fixed catalog bundle create

- cfme/tests/control/test_alerts.py
> [WIPTEST] Fixed SNMP test

- cfme/tests/infrastructure/test_host_drift_analysis.py
* Test was trying to get the Host credentials object from the wrong object
> [RFR] Fixed drift test

- cfme/infrastructure/virtual_machines.py
* Locator change
{{pytest: cfme/tests/cloud_infra_common/test_genealogy.py -k test_vm_genealogy_detected}}
> [RFR] Fix Genealogy Test

- cfme/tests/test_login.py
> [RFR] Fixed a bad call

- cfme/tests/infrastructure/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
RHCFQE-2136 - removing skips - as they are not actual
> [1LP][RFR]Removing skipif as BZ was resolved - RHCFQE-2136

- scripts/ec2cleanup.py
don't log on nothing removed, its generates really noisy emails.
Log in Jenkins will still have empty lists per provider for IP and storage so we'll have evidence where it ran.
> [RFR][1LP] Update scripts/ec2cleanup, quiet the noop

- cfme/tests/services/test_generic_service_catalogs.py
* check HTTP response statuses
* tests refactoring
* testing "delete" action with both POST and DELETE methods
{{pytest: --use-provider vsphere6-nested -v -k TestServiceCatalogViaREST}}
> [RFR] TestServiceCatalogViaREST check HTTP response status

- utils/appliance/__init__.py
> [1LP][RFR] datetime auto update in appliances

- cfme/base/ui.py
Reverts ManageIQ/integration_tests#4326
Dev changed their mind
> Revert "[WIPTEST] Fixed E release on upstream"

- scripts/dockerbot/dockerbot.py
- scripts/dockerbot/pytestbase/Dockerfile
- scripts/dockerbot/pytestbase/setup.sh
slightly updated dockerbot to use frozen.txt instead of requrements.txt
> [1LP][RFR] dockerbot should use frozen.txt instead of requrements.txt

- cfme/tests/infrastructure/test_vm_power_control.py
Removing `TestDeleteViaREST` with `test_delete` - it's superseded by delete tests in test_vm_rest.py
No PRT necessary, just removing test code.
> [1LP][RFR] remove outdated redundant TestDeleteViaREST

- cfme/cloud/instance/openstack.py
- cfme/provisioning.py
- cfme/tests/openstack/cloud/__init__.py
- cfme/tests/openstack/cloud/test_instances.py
Adding tests for Openstack cloud instances: provision and power control
> [1LP][RFR] Add Openstack cloud instances tests

- cfme/tests/cloud_infra_common/test_retirement.py
Add new automation for resuming a retired instance.
Skip for known bug, unblock for infra providers
Parametrize on resume via two methods:
* Set a new retirement date in the future
* Remove the set retirement date
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py --use-provider vsphere6-nested --use-provider ec2west --use-provider rhos7-ga --use-provider rhevm36 --long-running }}
5.7 setup failures due to provider problems. It's BZ skipping where I want it to now though.
> [1LP][RFR] Add Resume from Retirement Tests

- cfme/tests/control/test_bugs.py
test_folder_field_scope should be ~~uncollected not skipped~~ removed.
> [1LP][RFR] Removed test_folder_field_scope

- cfme/tests/infrastructure/test_vm_ownership.py
* check HTTP response statuses
* missing metadata
* cleanups
**PRT**:
tests failed on upstream with `Exception: No providers could be set up matching the params` <- not related to changes in this PR
{{pytest: --use-provider vsphere6-nested -v -k TestVmOwnershipRESTAPI}}
> [1LP][RFR] test_vm_ownership check HTTP response status

- cfme/cloud/availability_zone.py
- cfme/cloud/instance/__init__.py
- cfme/cloud/provider/__init__.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/infrastructure/test_timelines.py
- requirements/frozen.txt
- widgetastic_manageiq.py
1. Moved Timelines to widgetastic (currently limited functionality. the main goal is to fix timelines tests for 5.7)
2. updated infra and cloud tests
requires: https://github.com/RedHatQE/widgetastic.core/pull/21
{{pytest: --use-provider=vsphere6-nested cfme/tests/infrastructure/test_timelines.py }}
> [1LP][RFR]Widgetastic timelines

- utils/browser.py
* Renew flow is optimized
* Renew timer starts immediately and doesn't try
* Means no errors at start of test runs
> [RFR][1LP] Optimize renew

- scripts/cleanup_old_vms.py
Added a 'cleanup' boolean to the yamls, True everywhere
> Update cleanup_old_vms, cleanup boolean from yaml

- scripts/dockerbot/check_prs.py
Pika connection often fails
* Pika is handled in a way that is safe
> Fix pika connecrion drop

- cfme/provisioning.py
- cfme/services/catalogs/catalog_item.py
- cfme/services/myservice.py
- cfme/storage/object_store.py
Removed more current_version usage
> [1LP][RFR] Remove current_version part 3

- cfme/configure/settings.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/pxe.py
Removing more current_version usage
> [1LP][RFR] Remove current_version part 2

- cfme/automate/provisioning_dialogs.py
- cfme/automate/service_dialogs.py
- cfme/base/ui.py
- cfme/cloud/instance/__init__.py
- cfme/cloud/provider/openstack.py
- cfme/cloud/tenant.py
- cfme/cloud/volume.py
- cfme/configure/access_control.py
* Remove usage of current_version where access to an appliance is
available
* Other uses of it will disappear with time
> [RFR][1LP] Remove current_version part 1

- cfme/tests/cli/test_rake_evm_automate-52.py
- cfme/tests/cli/test_rake_evm_automate-53.py
- cfme/tests/containers/test_basic_metrics.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/tests/control/test_compliance.py
- cfme/tests/test_appliance.py
- fixtures/ssh_client.py
- utils/tests/test_ssh_client.py
Removing ssh_client and shifting delegation to the appliance object
> [1LP][RFR] Removed ssh_client fixture

- widgetastic_patternfly.py
Allow for DropdownDisabled as well as NoSuchElementException
FIXES #4378
> [1LP][RFR] Update widgetastic_patternfly.Dropdown.close

- cfme/middleware/server.py
- cfme/tests/middleware/test_middleware_server.py
{{pytest: cfme/tests/middleware/test_middleware_server.py::test_container_server_immutability -v --use-provider hawkular}}
> [1LP][RFR] New test to check container based EAP server immutability.

- scripts/ec2cleanup.py
Don't really need to append to the log file every time, just overwrite it.
> [1LP][RFR] Update ec2cleanup, overwrite instead of append log

- widgetastic_manageiq.py
Tested locally, the methods work.
Does not work with the tables like in My Company Tags, I will have to figure that out on WT Table side.
> [1LP][RFR] SummaryTable: Phase #1

- cfme/tests/cloud/test_provisioning.py
New test that selects particular VPC while creating VM in AWS through REST API.
{{pytest: -v -k test_ec2_manual_placement_using_rest --use-provider ec2west}}
> [1LP][RFR] new tests test_ec2_manual_placement_using_rest

- widgetastic_patternfly.py
This will resolve the issue of #4281
> [1LP][RFR] BootstrapSelect: Can ignore NoSuchElementException when closing (select hided)

- cfme/tests/cloud/test_cloud_events.py
1. fixed test_manage_nsg_group test which started failing lately
2. got rid of terrible regexps 
{{pytest: --use-provider=azure cfme/tests/cloud/test_cloud_events.py}}
> [1LP][RFR] fix for test_manage_nsg_group test and some refactoring

- cfme/tests/test_login.py
Smoke test for re-login i.e. Login and Logout again Login to the same appliance.
> [RFR][1LP] This PR will add smoke test for re-login to the appliance.

- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/test_appliance.py
- scripts/data/enable-internal-db.rbt
- scripts/restore.py
- utils/appliance/__init__.py
- utils/db.py
Changes to scl_name to reflect its true nature
> [RFR][1LP] scl_name change

- cfme/control/explorer/alerts.py
- cfme/tests/control/test_alerts.py
{{pytest: -v -k 'test_alert_snmp' --long-running --use-provider vsphere6-nested}}
__Fixing__ test_alert_snmp by implementing evaluate attribute for Alert class
> [1LP][RFR] Implemented evaluate attribute for alert

- cfme/tests/containers/test_relationships.py
- cfme/tests/containers/test_search_bar.py
- cfme/tests/containers/test_tables_fields.py
{{pytest: cfme/tests/containers/test_search_bar.py -v --use-provider cm-env1 }}
> [1LP][RFR] Fixes

- cfme/infrastructure/host.py
- utils/appliance/__init__.py
> [1LP][RFR] Fix infra.Host.get_db_id, use appliance.host_id prop

- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
@pavelzag Does this work for you?
> Add containers sec protocol

- cfme/fixtures/cli.py
- cfme/fixtures/rest_api.py
* Removed current_appliance from rest_api
* Removed current_appliance from cli
> [1LP][RFR] Removed more current_appliance usage

- cfme/tests/infrastructure/test_timelines.py
* check HTTP response statuses
* missing metadata
* cleanups
{{pytest: -v -k TestVmEventRESTAPI}}
> [1LP][RFR] TestVmEventRESTAPI check HTTP response status

- cfme/common/provider.py
- cfme/middleware/provider/__init__.py
- cfme/middleware/provider/hawkular.py
{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_hawkular_crud -v --use-provider hawkular}}
> [1LP][RFR] Fixed Middleware Provider Save button. Added missing db attribute call for executing queries.

- cfme/tests/cli/test_appliance_console.py
- utils/appliance/__init__.py
Starting to automate appliance_console test cases.
> [1LP][RFR] Appliance console testing

- requirements/frozen.txt
[RFR] Template upload is dead without this change.,
> [RFR][1LP] update frozen for mgmt

- cfme/web_ui/paginator.py
{{pytest: cfme/tests/infrastructure/test_advanced_search_vms.py::test_filter_with_user_input -v --long-running}}
> [1LP][RFR] Old paginator checks if it really changed; Raises exception if not

- cfme/tests/services/test_rest_services.py
__Extending__ service retirement tests with check that VMs associated with the service are retired as well.
{{pytest: cfme/tests/services/test_rest_services.py --long-running -v -k service_now}}
> [1LP][RFR] check that VM is retired along with service

- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/test_appliance.py
- scripts/restore.py
- utils/appliance/__init__.py
- utils/db.py
Moving postgres_version within IPAppliance
> [1LP][RFR] Moved postgres_version under IPAppliance

- widgetastic_patternfly.py
Fixes #4409
It will be possible to differ different types of buttons.
> [RFR][1LP] Bootstrap Button: Can also match by classes. Constants added.

- conftest.py
> [1LP][RFR] conftest: remove the unused _pytest_plugins_generator

- cfme/web_ui/form_buttons.py
Fixes #4409 (again)
Usage should be the same like with the new buttons, I olnly added the PRIMARY class there, add another when needed ...
> [RFR] Add class filter support in the old buttons

- scripts/release.py
> [1LP][RFR][NOTEST] Release script - dont fail on 1st missing label, list all at once; add tech-debt

- cfme/rest/gen_data.py
- cfme/tests/control/test_rest_control.py
New REST API tests for /api/conditions
{{pytest: -v -k TestConditionsRESTAPI}}
> [1LP][RFR] new basic REST API tests for /api/conditions

- cfme/control/explorer/conditions.py
- cfme/tests/control/test_basic.py
{{pytest: -v -k 'test_condition_crud' --long-running}}
Fixing strings in conditions.
> [1LP][RFR] Deferred version pick for provider condition string

- cfme/tests/control/test_bugs.py
{{pytest: -v -k 'test_control_identical_descriptions' --long-running}}
> [1LP][RFR] Added 5.8 in forced streams for test_control_identical_descriptions

- cfme/control/explorer/conditions.py
- cfme/web_ui/expression_editor_widgetastic.py
{{pytest: -v -k 'test_modify_condition_expression' --long-running}}
__Fixing__ Expression Editor for CFME 5.8. Images have been replaced by buttons.
> [1LP][RFR] Fixed Expression Editor elements for CFME 5.8

- cfme/automate/explorer/domain.py
- cfme/tests/automate/test_domain.py
{{pytest: -v cfme/tests/automate/test_domain.py -k 'test_domain_name_wrong or test_domain_lock_unlock'}}
> [RFR][1LP] Automated some Automate tests

- cfme/tests/services/test_different_dialogs_in_catalogs.py
Change test due to service catalog widgetastic changes
> [1LP][RFR]Dialog test fix

- cfme/tests/cloud/test_providers.py
New REST API tests for creating arbitration rules with valid and invalid arbitration profile reference.
{{pytest: cfme/tests/cloud/test_providers.py -v -k test_create_arbitration_rule}}
> [1LP][RFR] new REST API test for creating arbitration rules with arbitration profile reference

- cfme/tests/openstack/infrastructure/test_relationships.py
> [1LP][RFR] add some additional assert to tests

- cfme/automate/simulation.py
- cfme/base/ui.py
- cfme/tests/automate/test_domain_priority.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/tests/services/test_add_remove_vm_to_service.py
- widgetastic_manageiq.py
- widgetastic_patternfly.py
{{pytest: -v cfme/tests/automate/test_domain_priority.py cfme/tests/infrastructure/test_snapshot.py cfme/tests/services/test_add_remove_vm_to_service.py --long-running --use-provider vsphere55}}
> [1LP][RFR] Convert Simulation to Widgetastic

- cfme/tests/automate/test_domain_priority.py
> Fix ssh_client FixtureLookup error

- cfme/common/vm.py
- cfme/configure/tasks.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/virtualcenter.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_instance_analysis.py
- utils/virtual_machines.py
@dajohnso originally made these updates, I've just rebased and did some refactoring to account for the new deployment_helper flow.
The plan is to fix any major issues with these changes in this PR, and leave #TODO's and smaller fixes to separate smaller PRs. The idea being that we would like to merge these large fixes into master and then address any fallout separately to keep PR size and scope manageable.
@otsuman and I will me making the fixes here and in the subsequent PRs that result.
Failures that I'm seeing in the latest run are due to the SSA tasks not actually completing, so an exception was raised in the test because the row didn't exist (IndexError). Latest commit covers this exception, returning false when the row DNE and an IndexError is raised by widgetastic.
FIXES #4412
{{ …
> [1LP][RFR] SSA Refactoring/Fixing

- widgetastic_manageiq.py
Original  FileInput created temporary file and passed it to file input field when it got string in input. This is quite handy.
FileInput widget that comes with widgetastic doesn't have such feature. So this version of FileInput just enhances widgetastic's FileInput.
It has been tested and used in PR #4387 
It has been tested only against 5.7 but I'll fix all issues for 5.6/5.8 if I face somethying.
> [1LP][RFR] Enhanced FileInput control

- cfme/rest/gen_data.py
- cfme/tests/control/test_rest_control.py
New REST API tests for /api/policies
{{pytest: -v -k TestPoliciesRESTAPI}}
> [1LP][RFR] new REST API tests for /api/policies

- artifactor/__main__.py
- fixtures/artifactor_plugin.py
- setup.py
untested commit due to unaccesible infra
> [1LP][RFR] switch artifactor to module based startup

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Remove DB stuff from the Chargeback Automation
> [1LP][RFR] Remove DB stuff from Chargeback tests

- widgetastic_patternfly.py
> [1LP][RFR] ViewChangeButton fix

- requirements/frozen.txt
**PRT Results**
upstream: sprout failure, no appliance
> [RFR][1LP] Update frozen.txt for widgetastic-0.5.0

- cfme/intelligence/chargeback.py
- cfme/tests/intelligence/test_chargeback_assignments.py
{{pytest: -v -k 'chargeback'}}
> [1LP][RFR] Fix Form Add button in Chargeback Form

- requirements/frozen.txt
Includes wrapanapi PR 118, which we need for ec2cleanup
> [RFR] Update mgmtsystem in requirements/frozen.txt

- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
@pavelzag Let me know if this works for you.
> [1LP][RFR] Add hawkular creds validation to containers

- scripts/template_upload_all.py
- scripts/template_upload_gce.py
- scripts/template_upload_rhevm.py
- utils/trackerbot.py
- utils/version.py
Updating utils.version, utils.trackerbot for the newest MIQ 'Fine' release.
Update template_upload_all to dynamically parse MIQ release name and version string when not on the MIQ master branch.
Testing locally at the moment, requires YAML updates for CFME QE.
> [RFR][1LP] Updates for MIQ Fine release

- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/openshift.py
This PR fixes the problem that appeared by adding the Hawkular validation tab.
> [RFR]Add provider with SSL fixes

- cfme/infrastructure/pxe.py
- cfme/intelligence/reports/reports.py
- cfme/services/workloads.py
- cfme/tests/control/test_alerts.py
- cfme/tests/infrastructure/test_host_analysis.py
> [RFR][1LP] Fixed a few lint errors that crept in

- cfme/services/myservice.py
- cfme/tests/services/test_add_remove_vm_to_service.py
- cfme/tests/services/test_different_dialogs_in_catalogs.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
Catalog Item widgetastic change impact on test
> [1LP][RFR] Service Widgetastic test fix

- cfme/tests/test_rest.py
New REST API tests for datetime filtering - testing both YYYY-MM-DDTHH:MM:SSZ and YYYY-MM-DD supported formats and all supported operators.
{{pytest: -v -k test_date cfme/tests/test_rest.py}}
> [1LP][RFR] new REST API tests for datetime filtering

- cfme/tests/test_rest.py
new REST API tests checking that it's possible to limit returned attributes for every collection
{{pytest: -v -k "test_select_attributes or test_query_simple_collections"}}
> [1LP][RFR] new REST API tests checking that it's possible to limit returned attributes

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- fixtures/appliance.py
Fixing tests that cause ssh connections to be left open
> [1LP][RFR] Fixes to ssh client connection

- cfme/cloud/instance/__init__.py
- cfme/cloud/instance/azure.py
- cfme/cloud/instance/ec2.py
- cfme/cloud/instance/gce.py
- cfme/cloud/instance/image.py
- cfme/cloud/instance/openstack.py
- cfme/common/vm.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud/test_cloud_init_provisioning.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud/test_provisioning.py
- setup.py
- utils/providers.py
> [1LP][RFR] Entrypoints for instances/templates

- cfme/infrastructure/config_management.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
Changes made for ansible menu changes in 5.8
> [1LP][RFR] Ansible upstream fix

- utils/appliance/implementations/ui.py
Some tweaks to make the log less chatty
> [1LP][RFR] Improve logging to be less chatty

- cfme/configure/tasks.py
- cfme/containers/image.py
- cfme/containers/provider/__init__.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_tables_fields.py
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py -v --use-provider cm-env1 --disablemetaplugins blockers }}
> [1LP][RFR] SSA test improvement

- cfme/tests/configure/test_tag.py
New REST API tests for bulk tags assignment and unassignment.
{{pytest: -k test_bulk_assign_and_unassign}}
> [1LP][RFR] new REST API tests for bulk tags assignment

- cfme/middleware/datasource.py
- cfme/middleware/deployment.py
- cfme/middleware/provider/__init__.py
- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/jdbc_driver_methods.py
- cfme/tests/middleware/test_middleware_datasource.py
{{pytest: cfme/tests/middleware/test_middleware_datasource.py -v --use-provider hawkular}}
> [1LP][RFR] Added new test for XA Datasource creating. Adding new smoke test for non XA datasource creation.

- cfme/tests/automate/test_vmware_methods.py
__Fixing__  vmware hot add disk - as we need template with SCSI controller
> [1LP][RFR]replacing template for hot add disk

- cfme/tests/infrastructure/test_provisioning_rest.py
New REST API test for /api/provision_requests.
{{pytest: --use-provider vsphere6-nested -v cfme/tests/infrastructure/test_provisioning_rest.py}}
> [1LP][RFR] new REST API tests for /api/provision_requests

- cfme/tests/cli/test_evmserverd.py
- cfme/tests/test_appliance.py
- fixtures/ui_coverage.py
- scripts/clean_appliance.py
- scripts/cleanup_edomain_templates.py
- scripts/data/enable-internal-db.rbt
- scripts/harden_security.py
- scripts/install_snmp_listener.py
- scripts/restore.py
- scripts/template_upload_rhevm.py
- utils/appliance/__init__.py
- utils/appliance/implementations/ui.py
- utils/perf.py
- utils/ssh.py
Changes to sysV commands to match newer rhel version
> [1LP][RFR] sysV changes from service command to systemctl

- fixtures/artifactor_plugin.py
- setup.py
Scripts renamed to be compliant
> [1LP][RFR] Rename scripts to be miq

- cfme/tests/configure/test_ntp_server.py
- cfme/tests/configure/test_server_name.py
Removing current_appliance from NTP tests
> [RFR] Remove current_appliance from ntp tests

- cfme/control/explorer/alert_profiles.py
- cfme/tests/control/test_basic.py
- widgetastic_manageiq.py
- widgetastic_patternfly.py
{{pytest: -v -k 'test_alert_profile_assigning' --long-running}}
> [1LP][RFR] New test test_alert_profile_assigning

- cfme/tests/cli/test_appliance_console.py
Using a tuple to give access to name parameter for test parametrization
> [RFR][1LP] Moved to a tuple to supply named parameter

- cfme/web_ui/__init__.py
{{pytest: -v --long-running --use-provider vsphere55 cfme/tests/infrastructure/test_vm_power_control.py -k 'not (rest or Rest)'}}
> [1LP][RFR] Support for new quadicon power state locator

- cfme/tests/cli/test_evmserverd.py
Fix to server_name change for 5.8 build.
> [1LP][RFR] Fix to Server_Name

- cfme/cloud/availability_zone.py
- cfme/cloud/flavor.py
- cfme/cloud/keypairs.py
- cfme/cloud/stack.py
- cfme/cloud/tenant.py
- cfme/common/provider.py
- cfme/common/vm.py
- cfme/control/explorer/alert_profiles.py
- cfme/control/explorer/conditions.py
- cfme/control/explorer/policies.py
- cfme/tests/control/test_basic.py
- cfme/tests/control/test_bugs.py
- utils/__init__.py
_param_name inclusion for parametrization
> [RFR][1LP] Add _param_name for parametrization

- cfme/tests/containers/test_cockpit.py
- cfme/tests/containers/test_reports.py
{{pytest: cfme/tests/containers/test_reports.py cfme/tests/containers/test_cockpit.py -v --use-provider cm-env1 }}
- Updates bug markers for test_reports and test_cokcpit
> Bug updates

- cfme/services/myservice.py
- cfme/tests/services/test_myservice.py
- widgetastic_manageiq.py
Myservice widgetastic conversion
> [1LP][RFR] MyService Widgetastic Conversion

- cfme/tests/configure/test_log_depot_operation.py
Simplifying the pytest_generate_tests
> [1LP][RFR] Changed structure of the log_depot tests

- cfme/tests/configure/test_db_backup_schedule.py
> [RFR] Added param name to db backup

- cfme/services/myservice.py
- cfme/tests/services/test_myservice.py
A followup to #4486
{{pytest: -v cfme/tests/services/test_myservice.py --use-provider default --long-running}}
> [1LP][RFR] Small service test fix

- cfme/tests/configure/test_db_backup_schedule.py
PRT run #4540 was green except 5.8 because it didn't start
> [1LP][RFR] Fix test_db_backup_schedule for new cfme_data

- conftest.py
- markers/composite.py
- markers/meta.py
- markers/skipper.py
- markers/smoke.py
- markers/stream_excluder.py
- markers/uncollect.py
- requirements/frozen.txt
- requirements/frozen_docs.txt
- requirements/template_docs.txt
needs a test run to see if it breaks anything
> [RFR][1LP] detangle marker plugin dependencies and bump pytest to 3.0.7

- cfme/intelligence/chargeback.py
{{ pytest: cfme/tests/intelligence/test_chargeback_assignments.py}}
> [1LP][RFR]Fix chargeback assignment

- cfme/fixtures/base.py
- cfme/fixtures/smtp.py
- cfme/metaplugins/blockers.py
- fixtures/artifactor_plugin.py
- fixtures/browser.py
- fixtures/merkyl.py
- fixtures/provider.py
- fixtures/pytest_store.py
- fixtures/qa_contact.py
- fixtures/rbac.py
- fixtures/screenshots.py
- fixtures/soft_assert.py
- utils/appliance/__init__.py
- utils/log.py
- utils/tests/test_soft_assert.py
* use slave_manager as indicator not to start the server
* use slave_id from the slave_manager
* use a hook-fireing abstraction that gets the artifactor-client for config/items
> [RFR] artifactor client usage refactoring

- fixtures/artifactor_plugin.py
Going to ninja merge this to get jobs running and not crashing, artifactor was being shut down by the first slave killed. This removes that issue and also ensures that the artifactor server is only attempted to be shutdown once.
> Fixed shutdown

- cfme/automate/service_dialogs.py
UPDATE:
I changed the PR to include just the framework fix to make the change obvious and speed up the review/merge process.
The issue is that the ``element_data`` can be list or tuple, in which case the current code fails.
> [1LP][RFR] fix unpacking of element_data

- cfme/containers/volume.py
- cfme/tests/containers/test_breadcrumbs.py
- cfme/tests/containers/test_containers_summary.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_relationships.py
Add Volume tests.
__Adding tests__ for Volumes to cover 
- CMP-10407
- CMP-10319
- CMP-10410
> [1LP][RFR] Volume tests

- scripts/ec2cleanup.py
Waiting for merge in wrapanapi:
https://github.com/ManageIQ/wrapanapi/pull/118
> [RFR]Ec2cleanup - Added ELB & ENI cleanup

- cfme/cloud/instance/azure.py
- cfme/cloud/instance/ec2.py
- cfme/provisioning.py
- cfme/tests/cloud/test_provisioning.py
- cfme/tests/infrastructure/test_provisioning.py
__Extending__ test_provision_from_template to cover auto_placement option
{{pytest: -k test_provision_from_template  --use-provider gce_central --use-provider azure --use-provider vsphere6-nested --long-running}}
> [1LP][RFR]Adding auto_placement tests

- scripts/dockerbot/check_prs.py
As requested, gives runid in description
> [1LP][RFR] Add runid to status description

- cfme/services/myservice.py
- cfme/tests/services/test_provision_stack.py
{{pytest: -v --long-running --use-provider azure cfme/tests/services/test_provision_stack.py }}
> [1LP][RFR]Marked test with BZ

- README.md
@psav please merge when you turn PRT back on
> Update readme, PRT outage over

- cfme/common/provider.py
- cfme/infrastructure/provider/__init__.py
{{ pytest: cfme/tests/infrastructure/test_providers.py -k test_name_max_character_validation }}
> [RFR]Fix provider's save button in 5.8

- cfme/infrastructure/provider/__init__.py
> [1LP][RFR] returned FormButton

- scripts/dockerbot/pytestbase/Dockerfile
just a quick push to show the change, still running the local build/test
> [1LP][RFR] fix dockerbot, ensure package is installed

- cfme/tests/services/test_add_remove_vm_to_service.py
changed a variable that recently got changed as part of widgetastic conversion
> [1LP][RFR]Service name change

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console.py
- utils/appliance/__init__.py
Changes to Variables in class to better match the cli regardless whether the short options are changed.
Also a change to one appliance_console test option due to latest build changes.
> [1LP][RFR] Changes to cli variables to match new setup

- cfme/tests/infrastructure/test_infra_quota.py
Updated tier  for quota test cases.
> [1LP][RFR]Changed tier for quota test cases

- scripts/template_upload_rhevm.py
handle rhevm versions with sysv and systemd for template upload
tested script locally, it detected ovirt-engine status correctly against rhevm36
> [RFR][NOTEST] Update rhevm template upload, service status

- cfme/tests/containers/test_breadcrumbs.py
- cfme/tests/containers/test_cockpit.py
- cfme/tests/containers/test_tables_fields.py
> [RFR] Fix polarion ids

- cfme/tests/containers/test_tables_fields.py
> [RFR] Fix polarion id to CMP-10651

- cfme/base/credential.py
- cfme/configure/tasks.py
- cfme/infrastructure/host.py
1. fixed credentials comparison issue
2. fixed tasks issue
3. fixed issue with hosts in 5.8
{{pytest: cfme/tests/infrastructure/test_host_analysis.py cfme/tests/infrastructure/test_individual_host_creds.py }}
> [1LP][RFR] fixed credentials comparison issue

- cfme/tests/test_db_migrate.py
> [RFR] Fix to db migration tests

- cfme/base/credential.py
- cfme/common/provider.py
- cfme/configure/tasks.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/tests/infrastructure/test_providers.py
One of tests tried to update credentials using old provider.Credentials class
> [RFR][1LP] credentials issue fix in infrastructure/test_providers

- cfme/infrastructure/host.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/tests/infrastructure/test_advanced_search_host.py
- cfme/tests/openstack/cloud/test_instances.py
- cfme/tests/openstack/infrastructure/test_host_power_control.py
- cfme/tests/openstack/infrastructure/test_hosts.py
- cfme/tests/openstack/infrastructure/test_provider.py
- cfme/tests/openstack/infrastructure/test_roles.py
Fixing the issue with Openstack infrastructure nodes navigation (Hosts become Nodes for Openstack)
> [1LP][RFR] Fix for Openstack nodes navigation

- scripts/azure_cleanup.py
Depends on https://github.com/ManageIQ/wrapanapi/pull/120 - wrapanapi update and https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/119 -  yaml update
> [1LP][RFR] azure IP/NIC cleanup scripts for housekeeping

- cfme/web_ui/__init__.py
- utils/appliance/__init__.py
Removed some very old references
> [1LP][RFR] Removed references to 5.3

- cfme/base/ui.py
- cfme/configure/configuration/__init__.py
- cfme/fixtures/cli.py
- cfme/tests/configure/test_log_depot_operation.py
- utils/appliance/__init__.py
{{ pytest: cfme/tests/configure/test_log_depot_operation.py -k "test_collect_single_servers or test_collect_multiple_servers" }}
> [1LP][RFR] Log depot new tests

- requirements/frozen.txt
> [1LP][RFR] new wt.patternfly version with fix of vertical navigation widget

- cfme/tests/automate/test_domain_priority.py
- conftest.py
- fixtures/xunit_tools.py
> [RFR][1LP] Xunit

- scripts/release.py
Fixed release script in case of missing header
> [RFR] Fixed release script in case of missing header

- cfme/tests/configure/test_default_views_cloud.py
Updated the cloud view test cases with correct bz blocker
> [1LP][RFR]update the bz blocker for views test cases

- fixtures/xunit_tools.py
> [RFR] Fix xunit

- cfme/test_framework/sprout/plugin.py
* We now just log if the url is None
> [RFR] Fixed shutdown to allow url to be None

- cfme/services/requests.py
- cfme/tests/services/test_provision_stack.py
__rework__ for requests.
Sometimes we just need to find Request in the table - without waiting it to finish etc
> [1LP][RFR] reworking requests

- fixtures/parallelizer/__init__.py
this one is locally untested, so there is break potential
> [WIP] early appliance loss notifications to shutdown more graceful

- fixtures/parallelizer/__init__.py
Reverts ManageIQ/integration_tests#4644
> Revert "[WIP] early appliance loss notifications to shutdown more graceful"

- fixtures/parallelizer/__init__.py
* Making sure we only shutdown if the slave is asked to shutdown gracefully
> [RFR][1LP] Fixed shutdown of slaves again

- cfme/tests/services/test_request.py
__Fixing__ test_copy_request because it is currently passing only catalog_item name without catalog name to the view
> [1LP][RFR]fixing test_copy_request

- utils/appliance/__init__.py
Fixing what @psav broke :P
CC @jaryn  per his request.
To test this, just do:
```bash
python scripts/ipappliance.py configure 1.2.3.4
python scripts/ipappliance.py --kwargs '{"region": 1}' configure 1.2.3.4
```
> [RFR][1LP] Fix the appliance configure

- artifactor/plugins/ostriz.py
- fixtures/artifactor_plugin.py
Gives ostriz extra jenkins data
> [RFR][1LP] Adds extra jenkins info to Ostriz

- requirements/frozen.txt
Updating to v0.3.0 so better subcollection support and HTTP method selection can be used in new tests.
> [1LP][RFR] update manageiq-client in requirements/frozen.txt

- cfme/tests/webui/test_splitter.py
Post navmazing no longer needed
> [1LP][RFR] Fixed some imports that are no longer needed

- cfme/configure/configuration/__init__.py
- sprout/appliances/models.py
Fixed some problems reported from QC
> [1LP][RFR] Fixed some problems reported from QC

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
-----------------------
Fixing custom Chargeback rate creation after some changes were made to the Chargeback form.
{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider complete --long-running}}
> [RFR] Fix custom Chargeback rate creation

- cfme/common/provider.py
- fixtures/provider.py
add need  debug logging statements
> add some debug logging

- cfme/common/provider.py
> more debugging for pod env

- cfme/common/provider.py
- fixtures/provider.py
- utils/appliance/__init__.py
ignore this, nothing to see here
> revert some debugs

- fixtures/artifactor_plugin.py
> [RFR] Fixed jenkins send

- utils/testgen.py
Only pick one provider when saucing
> [RFR][1LP] Only pick one provider when saucing

- utils/appliance/__init__.py
- utils/ext_auth.py
- utils/mgmt_system/__init__.py
- utils/net.py
- utils/perf.py
To prevent hanging SSH connections, close SSH connections when we're finished with them.
> [RFR][1LP] Cleanup SSH connections after use (utils)

- cfme/configure/tasks.py
Destination was bad, this fixes that
> [1LP][RFR] Fixed a bad destination

- markers/composite.py
- utils/trackerbot.py
Can now choose single source for uncollect
> [RFR] Composite Source selector

- scripts/template_upload_vsphere.py
More explicit list creation was exploding the string to list elements locally for some reason?
> [1LP][RFR] Update list use in template_upload_vsphere

- cfme/tests/infrastructure/test_vm_ownership.py
Replacing the `rest_api` fixture with `appliance.rest_api` in test_vm_ownership.
{{pytest: -v -k TestVmOwnershipRESTAPI}}
> [1LP][RFR] remove rest_api fixture from test_vm_ownership

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console.py
Extending appliance console test
> [1LP][RFR] Appliance console extension

- cfme/tests/cloud/test_cloud_init_provisioning.py
- cfme/tests/configure/test_db_backup_schedule.py
- cfme/tests/configure/test_register_appliance.py
- cfme/tests/containers/test_basic_metrics.py
- cfme/tests/control/test_alerts.py
- cfme/tests/distributed/test_appliance_replication.py
- cfme/tests/infrastructure/test_cloud_init_provisioning.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/tests/optimize/test_bottlenecks.py
- fixtures/appliance.py
To prevent hanging SSH connections, close SSH connections when we're finished with them.
> [RFR][1LP] Cleanup SSH connections after use

- requirements/frozen.txt
Updated widgetastic.patternfly version
> [RFR][1LP] widgetastic.patternfly version update

- markers/composite.py
> [RFR] Fixed uncollect

- markers/composite.py
* getoption in Config in pytest, will not return the "notset" on a
store optin if a default is set
> [RFR] Fixed the uncollect again

- utils/ssh.py
* You can already do: if res, but it is not as explicit as if
res.success or res.failed
> [1LP][RFR] Enhancement to ssh

- utils/browser.py
this removes browser_keepalive in general as it turns out to create issues
> [RFR] do away with browser keep_alive

- scripts/clean_appliance.py
- scripts/cleanup_edomain_templates.py
- scripts/create_cu_vm.py
- scripts/fetch_jenkins_artifacts.py
- scripts/get_unregistered_vmware_files.py
- scripts/install_snmp_listener.py
- scripts/latest_template_tester_report.py
- scripts/template_upload_ec2.py
- scripts/template_upload_vsphere.py
Still need to test some of this. Not sure what PRT will look like, some of these scripts are used by the test runner.
Pretty simple changes. @rsnyman check it out, should complement your PRs #4633 and #4634 
All of these scripts have been tested locally
> [1LP][RFR] Update scripts, close ssh clients after use

- utils/browser.py
Reverts ManageIQ/integration_tests#4706
> Revert "[RFR][1LP] do away with browser keep_alive"

- cfme/configure/configuration/__init__.py
- utils/appliance/__init__.py
We needed to also use server id in the DB query. So I moved the DB querying in the IPAppliance class.
> [RFR] Fix DB role setup

- cfme/tests/infrastructure/test_customization_template.py
{{pytest: cfme/tests/infrastructure/test_customization_template.py}}
> [1LP][RFR] Added bug to customization template test

- scripts/template_upload_scvmm.py
I've been hating this script for quite some time.  Finally had enough.
Anyway, I cleaned up all the script calls, removed unnecessary methods, removed hard-coded values.  Performed more aggressive testing including error injection.
Replaced all print statements with proper logging.
Added proper text formatting.
> [RFR]Refactored unreadable upload script and removed hardcoded references

- cfme/infrastructure/config_management.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
{{pytest: -v --long-running --use-provider ansible cfme/tests/services/test_config_provider_servicecatalogs.py }}
Changed common  test case name and removed bz flag
> [1LP][RFR] Removed bz and changed common test name

- cfme/cloud/tenant.py
- cfme/tests/cloud/test_tenant.py
- cfme/web_ui/form_buttons.py
Added support for 5.8
{{ pytest: cfme/tests/cloud/test_tenant.py --use-provider rhos7-ga }}
> [1LP][RFR] Fix tenant_crud test

- scripts/clone_template.py
More cleanly handle the case where a VM deploy fails explicitly or
silently.
Cleanup some CQ .get('thing', None) cases to .get('thing')
FIXES RHCFQE-2825
> [RFR][1LP] Update scripts/clone_template, handle deploy failures

- fixtures/parallelizer/__init__.py
this ensures we keep the metadata, and ensures termination is handled as separate concern
> [RFR][1LP] parallelizer: introduce slave.forbid_restart and stop altering slave.url

- scripts/dockerbot/pytestbase/get_keys.py
- scripts/dockerbot/pytestbase/post_result.py
- scripts/dockerbot/pytestbase/verify_commit.py
after merge we need to make a new image
> [RFR][1LP] prepare dockerbot for the move of utils to cfme

- cfme/storage/object_store.py
Fix navigation for latest 5.8 build
{{ pytest: cfme/tests/storage/test_object_store.py -v}}
> Fix Navigation of Object storage 

- cfme/tests/openstack/cloud/test_instances.py
Fixing test_shelve_instance and test_shelve_offload_instance in cfme/tests/openstack/cloud/test_instances.py
The reason is - shelving itself behaves unexpectedly, cloud instance can change its power state from 'shelved' to 'shelved_offload' - it is how it designed in Openstack.
So, added Timeout handlers for some wait_for conditions
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_shelve_instance cfme/tests/openstack/cloud/test_instances.py::test_shelve_offload_instance --use-provider rhos_oc }}
> [1LP][RFR] Fix test_instances.py shelve tests

- scripts/template_upload_rhevm.py
Actually print which provider/template had an exception, not just the
raw exception text. things that should be obvious... :)
> [RFR] Update template_upload_rhevm, better exception log

- cfme/configure/access_control.py
Fixing this locator will fix the tenant quota failures.
{{pytest: -v -k  test_tenant_quota_max_cpu_check  --long-running}}
> [1LP][RFR] Fix locator in tenant

- cfme/tests/infrastructure/test_rest_providers.py
* remove the `rest_api` fixture
* edit test enhancement
{{pytest: -v cfme/tests/infrastructure/test_rest_providers.py}}
> [1LP][RFR] remove rest_api fixture from test_rest_providers

- scripts/azure_cleanup.py
> Added end of list line breaks

- cfme/tests/configure/test_access_control.py
- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
- cfme/tests/configure/test_timeprofile.py
- cfme/tests/configure/test_visual_cloud.py
- cfme/tests/configure/test_visual_infra.py
- cfme/tests/infrastructure/test_delete_infra_object.py
> [RFR]Fixed non-unique test names

- conftest.py
- fixtures/pytest_store.py
- fixtures/xunit_tools.py
- markers/composite.py
- markers/manual.py
- markers/uncollect.py
More detailed reporting and manual marker
> [RFR][1LP] Detailed reporting

- cfme/tests/cloud/test_tenant.py
__Extending__ X In previous state, if test fails, tenant remains on provider.
> [1LP][RFR] Added safer way of handling tenants in case of test failure

- cfme/test_framework/sprout/plugin.py
Please add this into the stable branch as well.
> [1LP][RFR][STABLE] Disable appliance destroy with UI coverage enabled

- cfme/configure/tasks.py
- cfme/containers/image.py
- cfme/tests/containers/test_containers_smartstate_analysis.py
- cfme/tests/containers/test_properties.py
- cfme/tests/containers/test_relationships.py
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py -v --use-provider cm-env1 }}
2 Additional test cases:
- check compliance.
- Profile setting
- new blocker bug for SSA
- Fixes in SSA test
- Changed container image instantiation from tag to id
> [1LP][RFR] More SSA tests

- fixtures/ui_coverage.py
> [RFR][1LP] sshpass for scp for coverage report collection

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/reports/test_generate_report.py
This test runs one default report from category under reports accordion.
as well as It deletes the saved report.
> [1LP][RFR] Adding new tests for generating report for each category

- scripts/template_upload_gce.py
- Use gcloud/gsutil from cli-tool box that already exists for CFME
- more robust download/upload/error handling
- clean up bucket to not waste storage costs
FIXES RHCFQE-2850
> [RFR][1LP] Refactor template_upload_gce

- cfme/tests/cloud/test_tenant.py
Added a waiter after tenant update
> [RFR][1LP] added waiter for tenant_crud test

- cfme/login.py
- cfme/tests/test_login.py
Fixing test_bad_password for 5.8.0. There have been two changes in the UI:
1. div id changed to div class
2. Error message changed
> [1LP][RFR] Fix test_bad_password

- scripts/data/coverage/coverage_hook.rb
> [1LP][RFR] Coverage includes also the gems

- cfme/infrastructure/host.py
I've recently added two log statements to debug some issue.
The issue has been fixed. So, these log statemetns are unnecessary now.
> [RFR] removed unnecessary debug statements

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Updating the tests to add support for tiered Chargeback rates
{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider complete  --long-running}}
> [RFR] Add support for tiered Chargeback rates

- cfme/containers/container.py
- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/containers/template.py
{{pytest: cfme/tests/containers/test_labels.py -v --use-provider cm-env1}}
- Fix according to @psav request [followup of PR#4760](https://github.com/ManageIQ/integration_tests/pull/4760#discussion_r120142619) (Optimize cfme/containers/*.get_random_instances)
> [RFR] Fix according to the followup of PR#4760

- notebooks/Interaction with Timelines Notebook.ipynb
First edition of Timelines ipython notebook. 
to be continued
> [RFR][NOTEST] Timelines ipython notebook

- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
{{pytest: -v -k 'test_cloud_compressed_view or test_infra_expanded_view'}}
Remove bz blockers for  view test.
> [RFR]Remove bz blockers for view test

- requirements/freeze.py
> [RFR] requirement freeze: use and delete tmpdirs by default

- scripts/dockerbot/build-container.py
- scripts/dockerbot/dockerbot.py
- scripts/dockerbot/pytestbase/Dockerfile
- scripts/dockerbot/pytestbase/get_keys.py
- scripts/dockerbot/pytestbase/post_result.py
- scripts/dockerbot/pytestbase/setup.sh
- scripts/dockerbot/pytestbase/verify_commit.py
the image is now based on fedora 25, uses multiple virtualenvs and less commands but more convention
it also uses a initial clone to keep the history clone step smaller
> [RFR][1LP] first step of a larger dockerbot upgrade [experiment]

- scripts/coverage_result.py
- scripts/dockerbot/pytestbase/post_result.py
this pr experimental sorts out various path/value issues with result posting
**warning** not locally tested**
> [WIPTEST] dockerbot: sort out path issues in result posting

- scripts/dockerbot/sel_container.py
- setup.py
Added miq_selenium_container script entrypoint
> [RFR] Add selenium_container script

- cfme/scripting/miq.py
- scripts/dockerbot/sel_container.py
- setup.py
* Adding new miq entrypoint master command
* Details all commands available in the miq space
* Converted sel_container.py to click
> [RFR][1LP] Add miq master script

- cfme/scripting/miq.py
- scripts/release.py
Add release script to miq master script
> [RFR] Add release script to miq master script

- cfme/scripting/conf.py
- cfme/scripting/miq.py
> [RFR] Added conf sub command

- cfme/scripting/conf.py
> [RFR] Fixed a doc issue

- cfme/tests/cloud/test_keypairs.py
__Extending__ the tests for case of timeout.
> [1LP][RFR] Add failsafe delete in case of TimeOutError

- cfme/tests/containers/test_ssl_providers.py
This is a super small fix that fixes misnumbered Polarion tests
> [RFR]Fixed Polarion tests numbers

- cfme/web_ui/toolbar.py
Title attribute of reload button in details screen has been changed.
> [RFR] Fixed locator for reload button

- cfme/common/provider.py
- cfme/common/provider_views.py
- cfme/tests/infrastructure/test_providers.py
changed flash messages to widgetastic ones in infra provider views
{{pytest: cfme/tests/infrastructure/test_providers.py }}
> [1LP][RFR] InfraProvider widgetastic flash messages

- cfme/scripting/appliance.py
- cfme/scripting/miq.py
* Added way to access cached_property and properties dynamically
* Future work could include inspectinf the methods for arguments
> [RFR]Added appliance commands

- cfme/control/explorer/actions.py
- cfme/web_ui/utilization.py
- utils/bz.py
- utils/soft_get.py
Though some of these are not necessary, it would perhaps be better to
set a standard of no mutable args. These changes shouldn't break
anything and are really to keep QC happier.
> [RFR]Fix mutable args

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Add support for storage Chargeback rates
{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider complete --long-running}}
> [RFR]Add support for storage Chargeback rates

- cfme/configure/access_control.py
> [RFR][NOTEST] Fulfill access_controll class, method docs

- requirements/template.txt
> [RFR] Fixed a typo on wrap req

- cfme/tests/automate/test_customization_paginator.py
- cfme/tests/configure/test_tag.py
- scripts/matrix.py
- utils/bz.py
Fixed some set comprehensions to make QC happier
> [RFR] Fixed some set comprehensions to make QC happier

- utils/appliance/db.py
> [RFR][1LP] Fix appliance cli call

- utils/appliance/__init__.py
> [1LP][RFR] Fixed DB log_callback

- cfme/tests/configure/test_rest_access_control.py
- cfme/tests/infrastructure/test_set_default_filter.py
- cfme/tests/integration/test_aws_iam_auth_and_roles.py
- cfme/tests/integration/test_ldap_auth_and_roles.py
- cfme/tests/services/test_operations.py
- cfme/tests/test_csrf.py
- cfme/tests/test_db_migrate.py
> [1LP][WIPTEST] Fix more SUI fallout

- cfme/scripting/appliance.py
Fixed appliance commands to not require an appliance
> [RFR] Fixed appliance commands to not require an appliance

- cfme/containers/provider/openshift.py
> Better Exception

- cfme/cloud/instance/__init__.py
is_displayed needs to be a property.
> [RFR] Fix Instance ProvisionView is_displayed

- fixtures/artifactor_plugin.py
- requirements/frozen.txt
Fix artifactor once and for all
> Fix artifactor once and for all

- cfme/infrastructure/config_management.py
- cfme/tests/infrastructure/test_config_management.py
{{pytest: cfme/tests/infrastructure/test_config_management.py }}
> [1LP][RFR] Fixing Config Management module to work for all config managers not only Ansible

- cfme/control/__init__.py
- cfme/control/log.py
- cfme/control/simulation.py
- cfme/tests/control/test_smoke_control.py
Intent
=====
__Adding smoke tests__ for Control tab.
{{py.test: -v -k 'test_control_navigation or test_control_explorer_tree'}}
> [1LP][RFR] Smoke tests for Control

- cfme/infrastructure/provider/__init__.py
__Fixing__ host credentials
{{pytest: cfme/tests/infrastructure/test_vm_migrate.py --use-provider vsphere65-nested}}
> [1LP][RFR] fix for host credentials

- utils/appliance/__init__.py
{{pytest: -k test_ec2_create_sns_topic}}
> [WIPTEST] fix for missed use of old credentials 

- cfme/control/log.py
Purpose
__Fixing__ locator in ControlLogView of cfme/control/log.py.
{{ pytest: -v -k "test_control_navigation"}}
mshriver: I modified the pytest line above from py.test -> pytest.
> [RFR] Fixed locator in ControlLogView

- cfme/base/credential.py
- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/azure.py
- cfme/cloud/provider/ec2.py
- cfme/cloud/provider/gce.py
- cfme/cloud/provider/openstack.py
- cfme/common/provider.py
- cfme/common/provider_views.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/tests/cloud/test_providers.py
- widgetastic_manageiq/__init__.py
{{pytest: -v cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py }}
It should be merged along with cfme_data merge request - 205.
> [1LP][RFR] converting Cloud Providers to widgetastic and endpoints

- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
> [1LP][RFR] Add a check to check if CU VM is running

- cfme/tests/test_rest.py
Basic test for new items in `server_info`.
{{pytest: -v -k test_server_info_href}}
> [1LP][RFR] create new REST API test for server_info

- cfme/cloud/instance/__init__.py
- cfme/tests/openstack/cloud/test_instances.py
Fixing tests/openstack/cloud/test_instances.py because of changes in Instance class
{{ pytest: cfme/tests/openstack/cloud/test_instances.py --use-provider rhos7-ga }}
> [1LP][RFR] Openstack test instances fix

- cfme/common/provider.py
It turned out that I broke credentials update in provider.update by recent changes.
This PR fixes this issue.
Additionally, this PR fixes provider.update method to support 'with update(provider)' construction.
code for test:
```
from utils.providers import get_crud
prov = get_crud('vsphere6-nested')
prov1 = get_crud('vsphere6-nested')
prov.default_endpoint.credentials.secret = 'invalid_password'
prov.update(updates={'endpoints': prov1.endpoints})
```
```
from utils.providers import get_crud
from utils.update import update
prov = get_crud('vsphere6-nested')
prov1 = get_crud('vsphere6-nested')
prov.default_endpoint.credentials.secret = 'invalid_password'
with update(prov):
prov.endpoints = prov1.endpoints
```
There is one more downside - with update(prov) doesn't work for credentials. It …
> [1LP][RFR] fixed credentials update in provider.update method

- cfme/common/provider.py
Fix for cm provider which aren't completely moved to endpoints approach
> [RFR] fixed hostname for cm providers

- cfme/base/ui.py
- cfme/configure/red_hat_updates.py
- cfme/tests/configure/test_register_appliance.py
- utils/appliance/__init__.py
Update to RHSM/SAT6 validation and registration testing. Bringing it up to the latest build versions.
> [1LP][RFR] Fix to RHSM/SAT6 registrations

- cfme/exceptions.py
- cfme/infrastructure/resource_pool.py
- cfme/tests/infrastructure/test_delete_infra_object.py
Converting cfme/infrastructure/resource_pool.py to use Widgetastic
> [1LP][RFR] Resource pool conversion

- docs/guides/dev_guide.rst
Intent
This is a suggestion for our coding style.
> [doc][1LP][RFR][NOTEST] Some coding style suggestions.

- cfme/middleware/provider/__init__.py
- cfme/middleware/server.py
- cfme/middleware/server_group.py
- cfme/tests/middleware/deployment_methods.py
- cfme/tests/middleware/server_group_methods.py
- cfme/tests/middleware/test_middleware_server_group.py
{{pytest: cfme/tests/middleware/test_middleware_server_group.py -v --use-provider hawkular}}
> [1LP][RFR] Added more tests for Server Group Power Operations.

- cfme/exceptions.py
- cfme/infrastructure/cluster.py
- cfme/tests/infrastructure/test_cluster_analysis.py
- cfme/tests/infrastructure/test_delete_infra_object.py
Converting Computer/Infrastructure/Clusters to Widgetastic
> [1LP][RFR] Converting clusters to Widgetastic

- requirements/frozen.txt
This wrapanapi includes several fixes for vcenter
> [RFR] wrapanapi version update

- cfme/containers/container.py
- cfme/containers/image.py
- cfme/containers/image_registry.py
- cfme/containers/node.py
- cfme/containers/overview.py
- cfme/containers/pod.py
- cfme/containers/project.py
- cfme/containers/provider/__init__.py
- cfme/containers/replicator.py
- cfme/containers/route.py
- cfme/containers/service.py
- cfme/containers/template.py
- cfme/containers/volume.py
- cfme/tests/containers/test_containers_summary.py
- cfme/tests/containers/test_overview_data_integrity.py
{{pytest: cfme/tests/containers/test_breadcrumbs.py cfme/tests/containers/test_containers_summary.py cfme/tests/containers/test_overview_data_integrity.py -v --use-provider cm-env2}}
- Added status_boxs to cfme/containers/overview.py
- Fix overview tests
> [RFR][1LP] Fix overview tests

- utils/appliance/implementations/ui.py
> [RFR] Migrated get_rails error to use WT

- cfme/common/vm.py
- cfme/tests/infrastructure/test_vm_power_control.py
__Adding test__  to check Power Toolbar on Archived VM
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py -k "test_no_power_controls_on_archived_vm" --use-provider vsphere65-nested --long-running}}
> [1LP][RFR]adding test_no_power_controls_on_archived_vm

- cfme/middleware/provider/__init__.py
- cfme/tests/middleware/test_middleware_provider.py
- cfme/tests/middleware/test_middleware_topology.py
- cfme/web_ui/topology.py
{{pytest: cfme/tests/middleware/test_middleware_topology.py -v --use-provider hawkular}}
> [1LP][RFR] Moved Topology tests to separate class, added more tests.

- cfme/common/__init__.py
- cfme/middleware/datasource.py
- cfme/middleware/provider/__init__.py
- cfme/tests/middleware/datasource_methods.py
- cfme/tests/middleware/test_provider_timelines.py
- cfme/web_ui/timelines.py
Enabled test methods.
{{pytest: cfme/tests/middleware/test_provider_timelines.py -v --use-provider hawkular}}
> [1LP][RFR] Modified Middleware timelines page to support new widgetastic.

- fixtures/ui_coverage.py
- scripts/coverage_report_jenkins.py
- scripts/coverage_report_sprout.py
- scripts/data/coverage/coverage_hook.rb
- scripts/data/coverage/coverage_merger.rb
- scripts/data/coverage/thing_toucher.rb
{{pytest: -v -m smoke --ui-coverage --long-running}}
> [RFR][1LP] Coverage report compilation

- cfme/automate/explorer/domain.py
- cfme/automate/import_export.py
- cfme/base/ui.py
- cfme/tests/automate/test_domain.py
- widgetastic_manageiq/hacks.py
QuantifiedCode issues addressed where it was possible, the rest are by design.
> [1LP][RFR] Automate GIT Domain import/export

- scripts/repo_gen.py
Script to allow you to create an upgrade repo file from a list of http
> [RFR] Repo script

- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/provider/virtualcenter.py
Needs more work to remove the Form based stuff too
> [1LP][RFR] Discovery Infra generify

- cfme/automate/import_export.py
* PR was old and was never updated
{{pytest: -k test_domain_import_git}}
> [RFR] Fixed db calls

- requirements/frozen.txt
- scripts/template_upload_all.py
- scripts/template_upload_ec2.py
- scripts/template_upload_rhevm.py
Refactoring the script to be region-aware, to use several new methods in wrapanapi.EC2System, and to cleanup after itself.
Requires wrapanapi v2.1.2, update to frozen.txt included here.
Plenty of TODO's that may or may not get addressed right now. Currently CFME QE is only testing against a single region. A lot of possible improvements to this script are only valid when uploading to multiple regions, and I don't see a need or value to addressing them right now.
> [RFR][NOTEST] Refactor EC2 Template Upload for CFME QE

- cfme/infrastructure/cluster.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/resource_pool.py
- cfme/tests/infrastructure/test_delete_infra_object.py
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py}}
1. added accidentally removed yaml statements and updated them
2. fixed tests and various other related issues
> [1LP][RFR] removed unused webui statement from test_delete_infra_object

- cfme/cloud/stack.py
Fix for tag_edit_tags(cloud stack)
{{pytest: cfme/tests/cloud/test_stack.py -v -k test_edit_tags}}
> [1LP][RFR]stack test_edit_tags fix

- cfme/cloud/keypairs.py
- cfme/tests/cloud/test_keypairs.py
This commit contains testing of add_tag and remove_tag to the Key Pair test_case.
> [1LP][RFR] This will add add_tag and remove_tag to the Key Pair test_case.

- requirements/frozen.txt
this version should include several features added to ConditionalView and View.include
> [RFR] Updating widgetastic to the newest version

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console.py
Clean up of appliance_console tests removing duplicate lines.
> [RFR] appliance_console test clean up

- widgetastic_manageiq/__init__.py
__Fixing__  SummaryFormItem locators. Making them a bit more global to pick values from Request Info tabs
[NOTEST]
> [1LP][RFR]fix for SummaryFormItem to work with Requests Info tabs items

- cfme/configure/access_control.py
Remove cfme.web_ui change_stored_password() usage from access_control.py
{{pytest: -v -k test_user_crud}}
> [RFR]Replace change_stored_password

- cfme/tests/infrastructure/test_host.py
__Fixing__ test_multiple_host_bad_creds, for RHV provider, in which the error message is different than other providers.
> [RFR] RHV provider: Fix test_multiple_host_bad_creds error message

- cfme/tests/containers/test_containers_smartstate_analysis.py
remove skip from SSA tests (There was an issue in our testing ENV that caused the tests to fail and it was fixed now)
> [RFR] Removed skipper from SSA tests

- cfme/tests/cloud/test_provisioning.py
* replacing the ``rest_api`` fixture with ``appliance.rest_api`` - this is the last occurrence of this fixture, once this PR is merged, the ``rest_api`` fixture can be removed
* checking the REST API responses using the ``assert_response``
{{pytest: -v -k 'test_manual_placement_using_rest or test_provision_from_template_using_rest' --use-provider ec2west}}
> [1LP][RFR] remove rest_api fixture; check REST API responses for test_provisioning.py

- artifactor/plugins/ostriz.py
- fixtures/artifactor_plugin.py
> [1LP][RFR] Added env params

- cfme/tests/test_db_migrate.py
- fixtures/appliance.py
- scripts/repo_gen.py
Adding basic testing around upgrades.
> [RFR] Upgrade testing

- cfme/tests/configure/test_access_control.py
Fixed test where flash message changed
> [1LP][RFR] Fixed a test for 5.8

- cfme/cloud/flavor.py
- cfme/configure/access_control.py
- cfme/fixtures/tag.py
- cfme/tests/cloud/test_cloud_object_tag_visibility.py
- cfme/tests/configure/test_access_control.py
- cfme/tests/infrastructure/test_infra_object_tag_visibility.py
Add new tests for tag visibility feature
{{pytest: cfme/tests/configure/test_access_control.py cfme/tests/infrastructure/test_infra_object_tag_visibility.py cfme/tests/cloud/test_cloud_object_tag_visibility.py -v -k 'test_group_crud_with_tag or test_tagvis' --long-running}}
> [1LP][RFR] new tag visibility tests

- cfme/tests/middleware/deployment_methods.py
{{pytest: cfme/tests/middleware/test_middleware_deployments.py -v --use-provider hawkular}}
> [RFR] Decreased timeout and wait time for deployment status check.

- cfme/cloud/instance/__init__.py
- cfme/infrastructure/cluster.py
1. fixed typo in Instance navigation
2. fixed typo in Cluster navigation
3. fixed picking cluster name for 5.8.1.2+
> [RFR] instance and cluster fixes

- cfme/tests/infrastructure/test_snapshot.py
This fixes test_verify_revert_snapshot in test_snapshot.py:
- changed used template. VMs based on DamnSmallLinux were without networking and I needed to ssh to the VM
- created waiting for ssh to become available using wait_for. Comments in code describe how it works
- changed soft assert checking. It was failing, so I introduced regular expressions and it's working now
- changed checking for result of the test; added asserts; added checking for both txt files
> [1LP][RFR] Fix test_verify_revert_snapshot

- cfme/infrastructure/pxe.py
- cfme/tests/infrastructure/test_iso_datastore.py
- cfme/tests/infrastructure/test_iso_provisioning.py
- cfme/tests/services/test_iso_service_catalogs.py
@property doesn't play with @variant
Thanks @mfalesni
> [1LP][RFR] Update infra.pxe, remove property decorator

- cfme/containers/container.py
{{pytest: cfme/tests/containers/test_properties.py -v --use-provider cm-env2}}
- Fix navigation to Containers ('All' view) which crashes due to a change in the accordion that introduced in 5.8.1+
> [RFR] Fix containers navigation in 5.8

- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/infrastructure/test_delete_infra_object.py
- cfme/tests/infrastructure/test_instance_analysis.py
- cfme/tests/infrastructure/test_set_default_filter.py
- widgetastic_manageiq/__init__.py
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py cfme/tests/infrastructure/test_datastore_analysis.py cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/infrastructure/test_instance_analysis.py}}
based on #4938
> [1LP][RFR] converting datastore to widgetastic

- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_catalog_item.py
New tests to check tag visibilit for service item and service bundle
{{pytest: cfme/tests/services/test_catalog_item.py -v -k test_tagvis}}
> [1LP][RFR] Service items visibility tests

- cfme/base/credential.py
- cfme/common/provider.py
- cfme/common/provider_views.py
- cfme/containers/provider/__init__.py
- cfme/containers/provider/openshift.py
- cfme/tests/containers/test_ssl_providers.py
{{pytest: cfme/tests/containers/test_ssl_providers.py -v --use-provider cm-env2}}
Containers Provider Widgetastic conversion + Endpoints classes
> [1LP][RFR] Containers Provider Widgetastic conversion + Endpoints classes

- cfme/base/ui.py
- cfme/configure/configuration/region_settings.py
- cfme/tests/configure/test_tag.py
- cfme/tests/configure/test_tag_category.py
Convert Category, Tag classes to widgetastic, add new MapTags tab class
{{pytest: cfme/tests/configure/test_tag.py cfme/tests/configure/test_tag_category.py -v -k 'test_tag_crud or test_category_crud'}}
Other tabs will be converted in another PR
> [RFR][1LP]Widgetastic convertion for Category, Tag tabs

- sprout/appliances/models.py
- sprout/appliances/templates/appliances/my_appliances.html
- sprout/appliances/urls.py
- sprout/appliances/views.py
* Added the possibility of manual deletion of broken pools that litter the view.
* Moved the appliance request into a modal with request button at the top.
> [WIP][NOTEST][RFR] Sprout - Couple of updates

- cfme/tests/containers/test_logging.py
{{pytest: cfme/tests/containers/test_logging.py -v --use-provider cm-env2}}
On the following PR I automated CMP-10643.
This test handles external logging feature which allow you to export logs on real time to extended location but CFME
> [1LP][RFR] logging test

- cfme/base/credential.py
- widgetastic_manageiq/__init__.py
Providers cannot be added in upstream becase Add form was slightly changed. Additionally, there are some other issues.
> [RFR] fixing provider add use case for upstream

- cfme/automate/dialog_box.py
- cfme/automate/dialog_element.py
- cfme/automate/dialog_tab.py
- cfme/automate/service_dialogs.py
- cfme/fixtures/service_fixtures.py
- cfme/rest/gen_data.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/automate/test_buttons.py
- cfme/tests/automate/test_customization_paginator.py
- cfme/tests/automate/test_service_dialog.py
- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/services/test_catalog_item.py
- cfme/tests/services/test_cloud_service_catalogs.py
- cfme/tests/services/test_different_dialogs_in_catalogs.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_generic_service_catalogs.py
> [RFR]Dialog Widgetastic conversion

- cfme/automate/explorer/domain.py
This will make all automate tests except service dialogs pass 100% again when ignoring BZ skips.
> [RFR] Fix locators for domain priority

- cfme/configure/configuration/region_settings.py
Fixed map tags navigation, update and delete methods needed for new tests(https://github.com/ManageIQ/integration_tests/pull/5036)
> [1LP][RFR]map_tags navigation and crud fixes

- utils/appliance/__init__.py
We are still trying to troubleshoot why ifcfg-eth0 network script is overwritten. In previous PR, we did not make audit rules permanent. Therefore they were cleared on next machine boot. This PR should fix it, and [https://access.redhat.com/solutions/1505033](url) was followed.
> [RFR] Debugging overwritten ifcfg-eth0 - make audit rules permanent

- cfme/services/catalogs/service_catalogs.py
- cfme/tests/services/test_provision_stack.py
> [1LP][RFR]Stack Timestamp fix

- cfme/tests/configure/test_access_control.py
Tenant or Project name is unique on parent level, My Company tenant can have only one child tenant/project with unique name.
{{pytest: cfme/tests/configure/test_access_control.py -v -k "test_tenant_unique_tenant_project_name_on_parent_level"}}
> [1LP][RFR] new multi-tenancy test - test_tenant_unique_tenant_project_name_on_parent_level

- requirements/frozen.txt
Update widgetastic.patternfly version
> [RFR]Update widgetastic.patternfly version

- requirements/frozen.txt
- scripts/template_upload_vsphere.py
Depends on wrapanapi update: ~~https://github.com/ManageIQ/wrapanapi/pull/153~~  (in version 2.1.5)
Uses `add_disk_to_vm()` method provided by wrapanapi update.
Removes unused methods that were using a removed wrapanapi virtualcenter.api property.
> [RFR][NOTEST] Update+Fix template_upload_vsphere

- cfme/configure/access_control.py
> [1LP][RFR] reduce the wait delay

- utils/browser.py
it tried to work around a selenium bug that cant be fixed on the client side
and it creates the need for locks, dynamic subclasses and added complexity
> [1LP][RFR] remove browserkeepalive hack

- scripts/cleanup_old_vms.py
`result` was getting referenced before assignment in `delete_vm()`, causing `AsyncResult.get()` to raise an exception that was unhandled in the local `pool_manager()`.
Handle it and include the exception object in the return from pool_manager, which is unused in this context because of the Queue use.
> [1LP][RFR][NOTEST] Fix exception handling in cleanup_old_vms

- artifactor/__main__.py
the result of print is None after all
>  [RFR] artifactor: fix up broken format call

- fixtures/provider.py
__Extending__ Template_Fixture because my PR #4998 uses PhotonOS Template, which is different from small_template, and to resolve that I have added a "console_template" in cfme_data.yaml. To use that template I wrote this new Fixture. I updated the _get_template() function to accommodate the needs. Also, before this gets PR the _get_template() function would return AttrDict in case of templates that have "name" and "creds" attributes, but returning 'str' is really what is required, so made those changes too.
> [1LP][RFR] Adding new  Template Fixture

- cfme/cloud/instance/__init__.py
- cfme/infrastructure/virtual_machines.py
__Extending__ Widgetastic views with the "Access" Dropdown menu from that will help me address @psav  s comment about WT conversion on PR #4998 . This needs to be merged ahead of PR#4998.
> [1LP][RFR] Adding access dropdown widget in toolbar of Widgetastic views

- utils/appliance/__init__.py
Added new method to update server_role without providing the whole dict of roles
`appliance.update_server_roles({"automate": True})
> [RFR][1LP] Small enhancement to appliance.server_roles setter

- scripts/apishow.py
There have been some changes in the REST API client as well as in our framework. This PR updates the script to reflect these changes.
Also changed to compile regular expressions for better performance (even though vast majority of the script's runtime is spent on network IO).
This script is useful for REST API tests authors for identifying coverage gaps.
> [1LP][RFR][NOTEST] Fixing and enhancing the apishow.py script

- cfme/common/host_views.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_advanced_search_host.py
Intent
RHCFQE-2985 cfme/infrastructure/host.py widgetastic conversion
Failures in PRT are not connected with the PR.
> [RFR][1LP] cfme/infrastructure/host.py widgetastic conversion

- scripts/dockerbot/dockerbot.py
- scripts/dockerbot/pytestbase/Dockerfile
- scripts/dockerbot/pytestbase/get_keys.py
- scripts/dockerbot/pytestbase/post_result.py
- scripts/dockerbot/pytestbase/setup.sh
- scripts/dockerbot/pytestbase/verify_commit.py
- scripts/dockerbot/sel_container.py
> [RFR] Dockerbot: reset to 17.06 and fix the issues that came up

- cfme/tests/infrastructure/test_providers.py
Introduced in #5086, no biggie
> Fix broken uncollectif

- cfme/infrastructure/host.py
Purpose
__Fixing__ `update` method of the Host object.
> [1LP][RFR] Fix in host update method

- scripts/dockerbot/sel_container.py
> [RFR] restore miq sel container changes by @psav

- requirements/frozen.txt
> Update wrapanapi,  2.2.2

- cfme/tests/test_rest.py
{{pytest: -v -k test_collection_class}}
> [1LP][RFR] Adding new REST API tests for collection_class

- cfme/cloud/stack.py
- cfme/cloud/tenant.py
- cfme/infrastructure/cluster.py
- cfme/tests/cloud/test_stack.py
- cfme/tests/cloud/test_tenant.py
- cfme/tests/services/test_provision_stack.py
Convert Orchestration Stacks and Tenants to Widgetastic.
Notes:
- Security groups seems to be unused.
- Also converted some Python style docstrings to Google style
FIXES RHCFQE-2973
> [1LP][RFR] Stacks and Tentants Widgetastic Conversion

- cfme/intelligence/chargeback/assignments.py
- cfme/tests/intelligence/test_chargeback_assignments.py
- widgetastic_manageiq/hacks.py
{{pytest: -v cfme/tests/intelligence/test_chargeback_assignments.py}}
> [1LP][RFR] Widgetastic conversion of Chargeback Assignments Form

- fixtures/xunit_tools.py
We use test case names with class names in Polarion (e.g.
``TestProvidersRESTAPI.test_create_arbitration_profiles`` vs ``test_create_arbitration_profiles``).
This was not reflected in the XML files genereted by the xunit_tools.
PRT results are not relevant here.
> [RFR][NOTEST] Generate test case names that contain class names

- cfme/ansible/credentials.py
- cfme/tests/ansible/test_embedded_ansible_basic.py
Intent
Automation/Ansible/Credentials page model and respectful crud test created
{{pytest: -v -k "test_embedded_ansible_credential_crud" --long-running}}
> [1LP][RFR] Automation/Ansible/Credentials page model

- cfme/intelligence/reports/__init__.py
- cfme/intelligence/reports/schedules.py
- cfme/tests/intelligence/reports/test_crud.py
- data/schedules_crud/basic01.yaml
Purpose
This PR is a part of set of Cloud Intel / Reports widgetastic conversion PRs. Cloud Intel / Report / Schedules have been converted to widgetastic.
{{pytest: -v -k "test_schedule_crud"}}
58z failed due https://bugzilla.redhat.com/show_bug.cgi?id=1477901
> [1LP][RFR] Cloud Intel / Reports widgetastic conversion. Part 2

- cfme/common/__init__.py
- cfme/services/catalogs/catalog_item.py
- cfme/tests/services/test_catalog_item.py
Add common class for tagging, for already converted classes to widgetastic.
{{pytest: -v -k 'test_tagvis_catalog_items or test_edit_tags'}}
> [1LP][RFR] Add widgetastic common taggable class

- cfme/containers/provider/kubernetes.py
- cfme/containers/provider/openshift.py
- requirements/frozen.txt
> [1LP][RFR]New version of wrapanapi + related imports

- cfme/automate/explorer/__init__.py
- cfme/intelligence/chargeback/__init__.py
- cfme/intelligence/chargeback/assignments.py
- cfme/intelligence/chargeback/rates.py
- requirements/frozen.txt
- requirements/frozen_docs.txt
It will fail until https://github.com/RedHatQE/widgetastic.patternfly/pull/15 is merged and released
{{pytest: cfme/tests/intelligence/test_chargeback_assignments.py -v --long-running }}
> [1LP][RFR] Fix up Chargeback navigation

- cfme/tests/services/test_pxe_service_catalogs.py
{{pytest: -v --long-running --use-provider vsphere55 cfme/tests/services/test_pxe_service_catalogs.py }}
> [RFR]PXE method name updated

- cfme/dashboard.py
- cfme/intelligence/reports/dashboards.py
- cfme/tests/intelligence/reports/test_widgets.py
- widgetastic_manageiq/__init__.py
Purpose
This PR is a part of set of Cloud Intel / Reports widgetastic conversion PRs. Cloud Intel / Report / Dashboards have been converted to widgetastic.
{{pytest: -v -k "test_widgets_on_dashboard"}}
> [1LP][RFR] Cloud Intel / Reports widgetastic conversion. Part 3

- cfme/common/vm.py
- cfme/configure/configuration/__init__.py
- cfme/web_ui/__init__.py
{{ pytest: cfme/tests/infrastructure/test_instance_analysis.py --long-running}}
1 test failed with assertion error because after SSA it shows 0 files, possible bug and not automation failure
> [1LP][RFR] fix cfme/tests/infrastructure/test_instance_analysis.py

- scripts/template_upload_rhevm.py
Added yaml key to mgmt_system[provider]['template_upload'] to allow for
YAML to specify blocking upload to rhevm providers
> [RFR] Update template_upload_rhevm, use block_upload

- cfme/intelligence/reports/saved.py
Purpose
This PR is a part of set of Cloud Intel / Reports widgetastic conversion PRs. Cloud Intelligence / Reports / Saved Reports converted to widgetastic.
> [1LP][RFR] Cloud Intel / Reports widgetastic conversion. Part 6

- cfme/intelligence/reports/import_export.py
Purpose
This PR is a part of set of Cloud Intel / Reports widgetastic conversion PRs. Cloud Intelligence / Reports / Import/Export converted to widgetastic.
> [1LP][RFR] Cloud Intel / Reports widgetastic conversion. Part 5

- cfme/infrastructure/host.py
Reverts ManageIQ/integration_tests#5153
> Revert "[RFR] Fix wait_for_host_state_change of Host class"

- cfme/cloud/availability_zone.py
- cfme/cloud/flavor.py
- cfme/cloud/keypairs.py
- cfme/common/host_views.py
- cfme/common/provider_views.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/resource_pool.py
- cfme/storage/volume.py
- widgetastic_manageiq/__init__.py
Pagination Pane and QuadIcons were redesigned in 5.9/upstream.
In the meantime ManageIQ started providing JS API for interaction with QuadIcons and PaginationPane.
This PR intends to add support of new JS API to widgetastic Entities, all EntitiesViews, PaginationPane.
This PR is relevant to only widgetastic part of code. Old web_ui code will be updated in another PR
> [1LP][READY-TO-MERGE] Upstream Widgetastic QuadIcons + Paginator

- cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
- requirements/frozen.txt
- utils/ansible.py
- utils/ansible_conf/custom_attributes_basic_script.yml
{{pytest: cfme/tests/containers/test_manageiq_ansible_custom_attributes.py -v --use-provider cm-env2 }}
This test is testing the Custom Attributes function of MIQ Ansible Module
For this test to run successfully it needs the git library added to requirements
> [RFR]ManageIQ Ansible Module Tests - Custom Attributes

- cfme/base/login.py
On upstream tests are failing like this: http://10.16.4.32/trackerbot/pr/run/14925#JWqgCUxz
> [RFR] Fix flash messages locator on upstream

- requirements/frozen.txt
- requirements/template_docs.txt
> [RFR] Add GitPython to requirements
