ManageIQ/integration_tests

cfme/configure/access_control.py
cfme/tests/containers/test_manageiq_ansible_users.py
requirements/frozen.txt
utils/ansible_conf/users_basic_script.yml

{{pytest: cfme/tests/containers/test_manageiq_ansible_users.py -v --use-provider cm-env2 }}
This test is testing the Users function of MIQ Ansible Module
For this test to run successfully it needs the git library added to requirements

[RFR] ManageIQ Ansible Module Tests - Users

---

scripts/dockerbot/pytestbase/Dockerfile

Fixing the requirement for PRT

[1LP][RFR] Add freetype-devel to the requirements

---

scripts/dockerbot/pytestbase/Dockerfile

Added another requirement

---

cfme/tests/cli/test_appliance_update.py

New test PR for testing updates between minor cfme releases. GA versions to latest.

[1LP][RFR] Creating yum update test for minor version testing

---

cfme/cloud/stack.py
cfme/cloud/tenant.py

* Some missing pagination pane fixes
{{pytest: cfme/tests/cloud/test_stack.py cfme/tests/cloud/test_tenant.py}}

[1LP][RFR] PaginationPane fix

---

cfme/intelligence/reports/menus.py
cfme/intelligence/reports/reports.py
cfme/tests/containers/test_reports.py
cfme/tests/intelligence/reports/test_menus.py
cfme/tests/intelligence/reports/test_report_chargeback.py
cfme/tests/intelligence/reports/test_report_corresponds.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py
data/reports_crud/basic01.yaml
utils/timeutil.py
widgetastic_manageiq/__init__.py

Purpose
This PR is a part of set of Cloud Intel / Reports widgetastic conversion PRs. Cloud Intelligence / Reports / Reports and Edit Report Menus have been converted to widgetastic.
{{pytest: -v -k "test_menus or test_download_report or test_report_chargeback or test_report_corresponds or test_custom_report_crud" --use-provider vsphere6-nested}}
test_custom_report_crud passed locally

[RFR] Cloud Intel / Reports widgetastic conversion. Part 4

---

cfme/infrastructure/host.py

SSIA
@sbulage 
Tested manually in ipython and then ran full test locally.
{{pytest: cfme/tests/infrastructure/test_host_drift_analysis.py -s --use-template-cache -vvv --use-provider vsphere55}}

[RFR][1LP] Fix host analysis drift comparison

---

cfme/services/catalogs/__init__.py
cfme/services/catalogs/ansible_catalog_item.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/services/test_catalog_item.py
widgetastic_manageiq/__init__.py

Intent
New test test_service_ansible_playbook_crud with respectful page model
{{pytest: -v -k "test_service_ansible_playbook_crud" --long-running}}

[RFR][1LP] Test service ansible playbook crud

---

requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

Bump numpy to 1.13.1

---

cfme/tests/control/test_rest_control.py

* better response checking
* using new delete methods available in manageiq-api-client
* edit and delete tests enhancements
{{pytest: -v cfme/tests/control/test_rest_control.py}}

[1LP][READY-TO-MERGE] test_rest_control enhancements

---

cfme/rest/gen_data.py
cfme/tests/services/test_rest_services.py

**PRT:** failure on upstream is unrelated to this changes, will be fixed by https://github.com/ManageIQ/integration_tests/pull/5160
{{pytest: -v --long-running -k test_order_catalog_bundle cfme/tests/services/test_rest_services.py}}

[1LP][RFR] New REST API test for ordering catalog bundle

---

cfme/infrastructure/virtual_machines.py

Fixing step method, because it was broken.

[1LP][RFR] Fix navigation for vm reconfigure

---

cfme/tests/ansible/test_embedded_ansible_services.py

Intent
__Adding__  test_service_ansible_playbook_available.
{{pytest: -v -k "test_service_ansible_playbook_available" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_available

---

cfme/ansible/playbooks.py
cfme/ansible/repositories.py
cfme/tests/ansible/test_embedded_ansible_basic.py

Intent
__Adding test__ test_embed_tower_playbooks_list_changed. It tests if playbooks list changed after playbooks repo removing.
{{pytest: -v -k "test_embed_tower_playbooks_list_changed" --long-running}}

[RFR][1LP] New test test_embed_tower_playbooks_list_changed

---

cfme/tests/infrastructure/test_config_management_rest.py

{{pytest: -v -k "test_authentications_options and ansible_tower_310" cfme/tests/infrastructure/test_config_management_rest.py}}

[1LP][RFR] New REST API test test_authentications_options

---

cfme/test_framework/pytest_plugin.py
conftest.py
requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt
setup.py

removes the need for conftest by updating pytest and using a entrypoint
this time around prt should catch up just fine

[RFR] Nomore conftest

---

cfme/rest/gen_data.py
cfme/tests/services/test_rest_services.py

... as a non-admin user.
{{pytest: -v --long-running -k test_user_item_order cfme/tests/services/test_rest_services.py}}

[1LP][RFR] New REST API test for ordering catalog item

---

cfme/infrastructure/pxe.py
cfme/tests/infrastructure/test_pxe.py
cfme/tests/infrastructure/test_pxe_provisioning.py
data/rhel7.cfg

Added rhel7 kickstart, fixed tests fixtures.
P.S. I've verified it on internal env, have no idea if in CI PXE servers are working.

[1LP][RFR] PXE tests fix & update

---

widgetastic_manageiq/__init__.py

Tested locally, nothing uses it yet, it is for ansinha.

[RFR] ViewButtonGroup addition

---

cfme/automate/buttons.py
cfme/configure/configuration/__init__.py
cfme/tests/configure/test_access_control.py
cfme/tests/infrastructure/test_advanced_search_host.py
cfme/tests/infrastructure/test_infra_quota.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py
cfme/tests/integration/test_ldap_auth_and_roles.py
cfme/tests/intelligence/reports/test_report_corresponds.py
cfme/tests/intelligence/test_chargeback_assignments.py
cfme/tests/intelligence/test_dashboard.py
cfme/tests/test_db_restore.py
cfme/web_ui/toolbar.py

Removed 99% of 5.4s and a few 5.5s

[1LP][RFR] Removed 99% of 5.4s and a few 5.5s

---

cfme/infrastructure/pxe.py

{{pytest: cfme/tests/infrastructure/test_iso_datastore.py  cfme/tests/infrastructure/test_iso_provisioning.py cfme/tests/infrastructure/test_pxe.py cfme/tests/infrastructure/test_pxe_provisioning.py cfme/tests/infrastructure/test_system_image_type.py cfme/tests/services/test_pxe_service_catalogs.py cfme/tests/services/test_iso_service_catalogs.py}}

[1LP][RFR] Widgetastic PXE

---

cfme/configure/configuration/region_settings.py
cfme/tests/configure/test_register_appliance.py

New test added for testing update button through webui

[RFR] Test added for webui update

---

cfme/tests/services/test_rest_services.py

* better response checking
* using new delete methods available in manageiq-api-client
{{pytest: -v --long-running cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Service REST API tests enhancements

---

cfme/tests/cloud/test_cloud_object_tag_visibility.py
cfme/tests/cloud/test_delete_cloud_object.py
cfme/tests/cloud/test_stack.py

Changing use of `['stack']` to `['stack'][0]` with the update of [MR](https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/275) to support list of stacks

[RFR][NOTEST] Changing ['stack'] to use list with MR#275

---

cfme/tests/control/test_bugs.py

Purpose
[BZ1304396](https://bugzilla.redhat.com/show_bug.cgi?id=1304396) was closed as WON'T FIX, so this PR removes respectful `uncollectif`.
{{pytest: -v -k "test_control_identical_descriptions"}}

[RFR] Removed uncollectif for test_control_identical_descriptions

---

cfme/tests/ansible/test_embedded_ansible_services.py

Intent
{{pytest: -v -k "test_service_ansible_playbook_negative" --long-running}}

[1LP][RFR] Test service ansible playbook negative

---

cfme/control/explorer/actions.py
cfme/tests/ansible/test_embedded_ansible_basic.py

Intent
{{pytest: -v -k  "test_control_add_ansible_playbook_action_invalid_address" --long-running}}

[1LP][RFR] Added new test test_control_add_ansible_playbook_action_invalid_address

---

cfme/common/host_views.py
cfme/infrastructure/host.py

Purpose
`execute_button` method of Host object converted to widgetastic.
{{pytest: -v -k "test_button_on_host"}}

[1LP][RFR] Host.execute_button() converted to widgetastic

---

cfme/cloud/stack.py
cfme/tests/cloud/test_stack.py

Collection implementation for Stack + its tests 
{{pytest: cfme/tests/cloud/test_stack.py -vvvv}}

[1LP][RFR] StackCollection + tests

---

cfme/cloud/tenant.py
cfme/tests/cloud/test_tenant.py

Collection implementation for Cloud Tenants + its tests
{{pytest: cfme/tests/cloud/test_tenant.py -vvvv}}

[1LP][RFR] Cloud tenant collection

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

[1LP][RFR] Fix Chargeback assignment selections

---

cfme/base/login.py
cfme/base/ui.py
cfme/dashboard.py
cfme/fixtures/model_collections.py
cfme/test_framework/pytest_plugin.py
cfme/tests/intelligence/test_dashboard.py
cfme/tests/test_csrf.py
requirements/frozen.txt
requirements/frozen_docs.txt

Working on the dashboard conversion, but any suggestions welcome. Some things will probably have to be modified in WT to make the work simpler it seems to me ...

[1LP][RFR] Dashboard WT conversion

---

cfme/infrastructure/cluster.py
cfme/tests/infrastructure/test_delete_infra_object.py

Cluster collection conversion and delete test using collection
{{pytest: -v -k 'test_delete_cluster_from_table'}}

[1LP][RFR] Cluster Collection conversion

---

cfme/tests/services/test_service_manual_approval.py

{{pytest: -v --long-running --use-provider vsphere55 cfme/tests/services/test_service_manual_approval.py }}

[1LP][RFR] Service manual approval test

---

cfme/tests/test_rest.py

{{pytest: -v -k "test_attributes_present or test_select_attributes" cfme/tests/test_rest.py}}

[1LP][RFR] New REST API tests test_attributes_present

---

cfme/common/vm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/tests/infrastructure/test_webmks_console.py

__Adding tests__ for feature VMware WebMKS Console which should work with vsphere6 and vsphere6.5.
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere6-nested --use-provider vsphere65-nested}}

[1LP][RFR] Adding NEW TEST: VMware WebMKS Console

---

cfme/cloud/keypairs.py
cfme/tests/cloud/test_keypairs.py

Shriver adding prt line:
{{ pytest: cfme/tests/cloud/test_keypairs.py -v --long-running --use-provider rhos7-ga --use-provider ec2west }}

[1LP][RFR] This PR contains collection in keypairs.

---

scripts/template_upload_rhevm.py

Fix for prior logging refactor.  Missed some `{}` replacements.

[RFR] Fix logging in template_upload_rhevm

---

cfme/tests/configure/test_visual_cloud.py

===============
Fixing changes related to collection to make navigation workable, @Yadnyawalkya also requires these changes to run his tests in PRT.
{{pytest: -v -k 'test_cloud_grid_page_per_item or test_cloud_tile_page_per_item or test_cloud_list_page_per_item or test_cloud_start_page or test_cloudprovider_noquads' }}

[1LP][RFR]Fixing Collection related changes in the test case.

---

cfme/tests/containers/test_relationships.py

{{ pytest: cfme/tests/containers/test_relationships.py --use-provider cm-env2 }}

[RFR] Fix test_relationships

---

cfme/services/catalogs/catalog_item.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_bundle" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_bundle

---

cfme/base/ui.py
cfme/fixtures/tag.py

Added small workaround to group/user tagvis tests as we have bug while login with uppercase letters,
https://bugzilla.redhat.com/show_bug.cgi?id=1486041.
After fix changes will be removed
{{pytest: -v -k 'test_tagvis_group or test_tagvis_user'}}

[1LP][RFR]Group/User tagvis tests small bug workaround

---

cfme/services/catalogs/catalog.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_provision_in_requests" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_provision_in_requests

---

cfme/ansible/repositories.py
cfme/base/__init__.py
cfme/cloud/instance/__init__.py
cfme/common/__init__.py
cfme/common/vm.py
cfme/common/vm_console.py
cfme/configure/access_control.py
cfme/configure/configuration/region_settings.py
cfme/configure/settings.py
cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/infrastructure/deployment_roles.py
cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/resource_pool.py
cfme/intelligence/reports/menus.py
cfme/services/catalogs/ansible_catalog_item.py
cfme/web_ui/paginator.py
docs/conf.py
docs/modules.rst
fixtures/events.py
fixtures/provider.py
utils/appliance/__init__.py
utils/events.py
utils/ssh.py

* Added a mock for wrapanapi.utils
* Moved new_paginator into a function

[1LP][RFR] Fixed docs building

---

cfme/common/vm_views.py
cfme/configure/tasks.py
cfme/infrastructure/virtual_machines.py
cfme/provisioning.py
cfme/services/requests.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/control/test_actions.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/infrastructure/test_infra_quota.py
cfme/tests/infrastructure/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_dialog.py
cfme/tests/infrastructure/test_vm_clone.py
cfme/tests/infrastructure/test_vm_migrate.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_generic_service_catalogs.py
cfme/tests/services/test_iso_service_catalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_operations.py
cfme/tests/services/test_provision_stack.py
cfme/tests/services/test_pxe_service_catalogs.py
cfme/tests/services/test_request.py
cfme/tests/services/test_service_catalogs.py

__Adding __   widgetastic for Services - Requests
latest PRT run was almost 100% - only 1 issue - in approval-edit test - this test needs #5113 navigation - which will give correct navigation for Vm 'Edit'.
{{pytest:  cfme/tests/services/test_request.py cfme/tests/infrastructure/test_provisioning.py cfme/tests/infrastructure/test_provisioning_dialog.py  cfme/tests/infrastructure/test_vm_migrate.py cfme/tests/services/test_different_dialogs_in_catalogs.py --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Request's widgetastic

---

cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_confirm" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_confirm

---

cfme/tests/test_rest.py

... and old uncollectif cleanups
{{pytest: -v -k test_settings_collection cfme/tests/test_rest.py}}

[1LP][RFR] New REST API test test_settings_collection

---

cfme/tests/services/test_rest_services.py

{{pytest: -v --long-running -k TestPendingRequestsRESTAPI cfme/tests/services/test_rest_services.py}}
**PRT results:**
Failures on upstream are unrelated to this PR.

[1LP][RFR] New REST API tests for pending service requests

---

cfme/exceptions.py
cfme/infrastructure/deployment_roles.py

Widgetastic conversion of deployment role model page.

[1LP][RFR][NOTEST] Deployment Role Widgetastic conversion

---

cfme/infrastructure/datastore.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py
cfme/tests/infrastructure/test_instance_analysis.py

Collection for `cfme.infrastructure.datastore.Datastore`
{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py cfme/tests/infrastructure/test_delete_infra_object.py cfme/tests/infrastructure/test_instance_analysis.py -vvvv}}

[1LP][RFR] Datastore collection + tests

---

cfme/tests/test_rest.py
utils/appliance/__init__.py
utils/rest.py

{{pytest: -v -k "test_query_simple_collections or test_query_with_api_version" cfme/tests/test_rest.py}}

[1LP][RFR] New REST API tests test_query_with_api_version

---

cfme/services/catalogs/service_catalogs.py
cfme/services/myservice.py
cfme/services/requests.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_order" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_order

---

cfme/tests/services/test_service_manual_approval.py

__Fixing__  test_service_manual_approval because it was added during  my PR review and was using old requests

[1LP][RFR]fixes to the new tests

---

cfme/tests/services/test_rest_services.py

{{pytest: -v --long-running -k "test_service_add_resource or test_service_remove_resource or test_service_remove_all_resources" cfme/tests/services/test_rest_services.py}}

[1LP][RFR] New REST API tests for adding and removing service resources

---

cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py
cfme/provisioning.py
cfme/tests/infrastructure/test_cloud_init_provisioning.py
cfme/tests/infrastructure/test_infra_quota.py
cfme/tests/infrastructure/test_iso_provisioning.py
cfme/tests/infrastructure/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_dialog.py
cfme/tests/infrastructure/test_pxe_provisioning.py
cfme/tests/services/test_operations.py

Part 1 - Navigation part updates. splitting PR into few parts
Shriver: ~~forked from #4872~~
{{ pytest: -v cfme/tests/infrastructure/test_vm_power_control.py cfme/tests/infrastructure/test_provisioning.py --use-provider vsphere65-nested --use-provider scvmm --use-provider vsphere6-nested  --long-running -k "not RESTAPI"}}

[1LP][RFR] Wigdetastic in cfme.infrastructure.virtual_machines_Pt_1

---

utils/ansible.py

{{pytest: cfme/tests/containers/test_manageiq_ansible_users.py -v --use-provider cm-env2 }}
This PR fixes a small bug introduced in the last commit

[1LP][RFR] ManageIQ Ansible Users test fix

---

cfme/common/vm_views.py
cfme/tests/cloud/test_cloud_init_provisioning.py

__Fixing__ cloud_init test because it is currently not working

[1LP][RFR] fixing cloud_init test

---

cfme/automate/explorer/__init__.py
cfme/automate/explorer/method.py
cfme/test_framework/sprout/plugin.py

* Changed a flash locator
* Accounted for the method edit form change.
{{pytest: -v cfme/tests/automate/test_method.py -k method_crud --sprout-provider rhos7-sprout }}

[1LP][RFR] Fix upstream automate interactions

---

cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/keypairs.py
cfme/cloud/stack.py
cfme/tests/cloud/test_cloud_object_tag_visibility.py
widgetastic_manageiq/__init__.py

Fixing cloud objects visibility tests
{{pytest: cfme/tests/cloud/test_cloud_object_tag_visibility.py -v --long-running}}

[1LP][RFR] Cloud tagvis tests fix

---

cfme/infrastructure/datastore.py
cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_infra_object_tag_visibility.py

Fixing datastores tag visibility tests
{{pytest: cfme/tests/infrastructure/test_infra_object_tag_visibility.py cfme/tests/infrastructure/test_infra_tag_filters_combination.py}}

[1LP][RFR] Infra datastores_tagvis fix

---

cfme/services/catalogs/ansible_catalog_item.py
cfme/services/myservice.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_plays_table" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_plays_table

---

cfme/rest/gen_data.py

* save full response, not just status code
* save the original list of entities so it's available for cleanup and immune to modifications by tests (e.g. ``.pop()``
{{pytest: -v -k TestNotificationsRESTAPI cfme/tests/test_rest.py}}

[1LP][RFR] Fixes for _creating_skeleton

---

cfme/tests/cloud/test_cloud_timelines.py
cfme/tests/infrastructure/test_timelines.py

Diagnostic timelines tests have been broken due to updates in vm views.

[1LP][RFR] Diagnostic timelines fix

---

cfme/tests/configure/test_rest_access_control.py

{{pytest: -v -k "test_change_email_as_user or test_change_password_as_user" cfme/tests/configure/test_rest_access_control.py}}

[1LP][RFR] New REST API tests for user edits

---

cfme/tests/infrastructure/test_vm_power_control.py

__Fixing__   test_guest_os*  - Vmware available PowerOps changed - guest OS operations are not visible/grayed anymore
test_power_options* - automation runs too fast - we are failing on verifying if VmTools are installed
{{pytest: --long-running --use-provider vsphere65-nested  -k  "test_guest_os or test_power_options" cfme/tests/infrastructure/test_vm_power_control.py }}

[1LP][RFR] amending test to meet UI changes

---

cfme/tests/ansible/test_embedded_ansible_actions.py

{{pytest: -v -k "test_action_run_ansible_playbook" --long-running}}

[1LP][RFR] Added test test_action_run_ansible_playbook

---

cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_service_ansible_playbook_order_credentials" --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_order_credentials

---

cfme/scripting/miq.py
cfme/scripting/sprout.py
cfme/test_framework/sprout/plugin.py

* Added sprout checkout command

[1LP][RFR] Added new sprout command sub set

---

utils/appliance/__init__.py

* We want to remove the use of the descriptor
* Added warning deprecations
* Added new Mixin

[RFR][1LP] Collections Navigatable Mixin

---

cfme/automate/import_export.py

Fixes an exception
{{pytest: -v cfme/tests/automate/test_domain.py -k git --long-running }}

[1LP][RFR] Use BootstrapSelect instead of BootstrapSelectByLocator

---

cfme/storage/volume.py
cfme/tests/storage/test_volume.py

- cfme/storage/volume.py >> collection convertion, Base Entities added, delete method added.
- cfme/tests/storage/test_volume.py >> collection changes and test_volume_collective_crud test added.
{{pytest: cfme/tests/storage/test_volume.py -v --use-provider rhos7-ga}}

[1LP][RFR] Volume Collection

---

cfme/tests/cloud_infra_common/test_html5_vm_console.py

__Extending__ wait_for_text('login:') to disappear with an assert to make sure the text is disappeared.

[1LP][RFR] Adding assertion to wait_for_text('login:') to disappear 

---

cfme/common/host_views.py

It exists on Openstack nodes' pages

[1LP][RFR] added Security summary table

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_provisioning_dialog.py

Fixing provisioner closure because it is currently fails on form filling.
{{pytest: -v --long-running cfme/tests/infrastructure/test_provisioning_dialog.py}}

[RFR] test_provisioning_dialog.py Provision fix

---

cfme/infrastructure/host.py

Fixed lost old-style entity usage
Sorry, no PRT. There are no OSP Infra providers available

[RFR] fix Host's wait_for_host_state_change

---

cfme/intelligence/reports/reports.py

Fixed test_generate_report.py
{{pytest: cfme/tests/intelligence/reports/test_generate_report.py -v --use-provider vsphere55}}

[1LP][RFR] Fix generate report tests

---

widgetastic_manageiq/__init__.py

Purpose
BootstrapSwitchSelect stopped to work after https://github.com/RedHatQE/widgetastic.patternfly/pull/20 merging.
{{pytest: -v -k "test_assign_two_random_events_to_control_policy" --long-running}}

[1LP][RFR] Fixed BootstrapSwitchSelect view

---

cfme/services/catalogs/ansible_catalog_item.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k test_service_ansible_playbook_order_pass_extra_vars --long-running}}

[1LP][RFR] Added test test_service_ansible_playbook_order_pass_extra_vars

---

cfme/tests/configure/test_tag.py

* new ``test_query_by_multiple_tags`` test
* tests enhancements
{{pytest: -v  --use-provider vsphere65-nested -k TestTagsViaREST cfme/tests/configure/test_tag.py}}

[1LP][RFR] New REST API tag test + enhancements

---

cfme/common/__init__.py
cfme/services/catalogs/ansible_catalog_item.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py::test_service_ansible_playbook_taging --long-running --use-provider complete}}

[1LP][WIPTEST] Added test test_service_ansible_playbook_tagging

---

cfme/common/provider_views.py
cfme/infrastructure/deployment_roles.py
cfme/tests/openstack/infrastructure/test_roles.py

================
> Deployment Role Collection
> test_roles > collection and WT changes.
> ProviderNodeView entities added.
{{pytest: cfme/tests/openstack/infrastructure/test_roles.py -v --use-provider rhos_uc}}

[1LP][RFR] Collection of Deployment Role

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

[1LP][RFR] Add Chargeback support for cloud providers

---

markers/env.py

[RFR][1LP] Fixing print

---

utils/appliance/__init__.py

* Rest caches collections, they need to be reset prior to use
* Lint bug

[RFR] Fixed blocking REST issue

---

cfme/tests/containers/test_smart_management.py

{{pytest: cfme/tests/containers/test_smart_management.py -v --use-provider cm-env1 }}
After few Jenkins failure I decided to add some log lines in the test so i will be able to debug errors
This PR handle this issue by make the cfme.log richer on smat mgmt test

[1LP][RFR] Add log messages to test log + fix some bugs

---

cfme/tests/infrastructure/test_set_default_filter.py

[1LP][RFR] Fixed a call to title loc

---

cfme/configure/settings.py

```_quad``` was missed off the end of this causing errors

[1LP][RFR] Fix visual quad

---

cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/scvmm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/tests/infrastructure/test_providers.py

* Some providers didn't have error messages
* Messages were not part of appliance object

[1LP][RFR] Fix error messages for bad_creds adding

---

cfme/infrastructure/host.py

assert_no_errors was moved to assert_no_error in PF-WT

[1LP][RFR] Fixed a bad call

---

cfme/tests/test_rest.py

{{pytest: -v -k test_rest_paging cfme/tests/test_rest.py}}
**PRT**
Can't get upstream to test anything, tested locally.

[1LP][RFR] Add new REST API test for paging testing

---

cfme/cloud/keypairs.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/infrastructure/datastore.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py
cfme/tests/infrastructure/test_instance_analysis.py

Added NavigatableMixin to the Collection classes
{{ pytest: cfme/tests/cloud/test_tenant.py cfme/tests/cloud/test_stack.py cfme/tests/cloud/test_keypairs.py -vvvv }}

[1LP][RFR] Added NavigatableMixin to collections

---

cfme/infrastructure/datastore.py
cfme/tests/configure/test_visual_infra.py
cfme/tests/infrastructure/test_set_default_filter.py
cfme/tests/webui/test_splitter.py

* cfme/tests/infrastructure/test_set_default_filter.py/test_clear_datastore_filter_results
* cfme/tests/configure/test_visual_infra.py/test_datastore_noquads
* cfme/tests/webui/test_splitter.py/test_pull_splitter_persistence[Datastore-All]

[1LP][RFR] Datastore Collection broke some tests

---

cfme/tests/infrastructure/test_datastore_analysis.py

{{pytest: cfme/tests/infrastructure/test_datastore_analysis.py}}

[1LP][RFR] infrastructure/test_datastore_analysis.py: rectify collection issue

---

cfme/infrastructure/virtual_machines.py

pagination is non-existent if there are no records

[1LP][RFR] Fixed pagination issue

---

cfme/base/ui.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/configure/configuration/__init__.py
cfme/infrastructure/host.py
cfme/provisioning.py
cfme/tests/containers/test_configurable_menus.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_service_catalogs.py

[RFR] Lint fixes

---

docs/conf.py

Fix docs import

---

cfme/infrastructure/cluster.py
widgetastic_manageiq/__init__.py

{{pytest: cfme/tests/infrastructure/test_timelines.py --use-provider=vsphere6-nested}}

[1LP][RFR] test_timelines against 5.7.4 fixes

---

cfme/configure/configuration/analysis_profile.py
cfme/infrastructure/host.py
cfme/tests/control/test_compliance.py

Purpose
__Fixing__ test_compliance.py after analysis profile widgetastic conversion. 
{{pytest: -v -k "test_compliance" --long-running --use-provider vsphere6-nested}}

[1LP][WIP] Fix test_compliance.py

---

cfme/utils/tracer.py

[RFR][1LP] Enhanced tracer

---

cfme/tests/cloud/test_cloud_events.py

{{pytest: cfme/tests/cloud/test_cloud_events.py --use-provider=azure}}

[RFR] fixes for cloud events tests

---

cfme/control/explorer/alerts.py
cfme/tests/control/test_bugs.py

Intent
Added automation for testing https://bugzilla.redhat.com/show_bug.cgi?id=1378919
{{pytest: -v -k "test_alert_ram_reconfigured"}}

[1LP][RFR] Added test test_alert_ram_reconfigured

---

cfme/tests/control/test_actions.py

{{pytest: -v -k "test_action_prevent_ssa" --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Added test test_action_prevent_ssa

---

cfme/common/vm.py
cfme/tests/control/test_actions.py

{{pytest: -v cfme/tests/control/test_actions.py --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Added test test_action_check_compliance

---

cfme/common/provider.py
cfme/common/provider_views.py
cfme/exceptions.py
cfme/middleware/datasource.py
cfme/middleware/deployment.py
cfme/middleware/domain.py
cfme/middleware/messaging.py
cfme/middleware/provider/__init__.py
cfme/middleware/provider/hawkular.py
cfme/middleware/provider/middleware_views.py
cfme/middleware/server.py
cfme/middleware/server_group.py
cfme/middleware/topology.py
cfme/tests/middleware/test_middleware_provider.py

{{pytest: cfme/tests//cloud/test_providers.py cfme/tests/infrastructure/test_providers.py -v}}

[1LP][RFR] Middleware conversion to widgetastic

---

cfme/middleware/server.py
cfme/tests/middleware/test_middleware_domain_server.py

[1LP][RFR] Remove some web_ui methods

---

cfme/tests/cloud_infra_common/test_html5_vm_console.py

__Fixing__ configure_websocket fixture in reference to conversation I had with @psav on a comment he made at : https://github.com/ManageIQ/integration_tests/pull/5192#discussion_r135070684
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py }}

[1LP][RFR] Updating WebSocket fixture

---

cfme/configure/access_control.py

This works now, removed the TODO comment

[RFR] Removed ToDo comment

---

cfme/middleware/provider/__init__.py
cfme/middleware/provider/middleware_views.py
cfme/middleware/server.py
cfme/middleware/server_group.py
cfme/tests/middleware/datasource_methods.py
cfme/tests/middleware/test_middleware_datasource.py
cfme/tests/middleware/test_middleware_downloads.py
cfme/tests/middleware/test_middleware_server.py
cfme/tests/middleware/test_middleware_server_group.py

Added view.flash assertions in middleware provider side.
Added Tab functionality for selecting JDBC Driver page.
Tests are more stable: wait until driver is listed.

[RFR][1LP] Removed web_ui flash from middleware tests.

---

cfme/base/ssui.py
cfme/fixtures/service_fixtures.py
cfme/services/dashboard/__init__.py
cfme/services/dashboard/ssui.py
cfme/services/myservice/__init__.py
cfme/services/myservice/ssui.py
cfme/services/myservice/ui.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_provision_stack.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_login.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/utils/appliance/implementations/ssui.py
widgetastic_manageiq/__init__.py

{{pytest: -v --long-running --use-provider vsphere55 cfme/tests/ssui/test_ssui_dashboard.py }}

[1LP][RFR] SSUI Myservice tests

---

cfme/cloud/provider/__init__.py
cfme/common/provider.py
cfme/containers/provider/__init__.py
cfme/infrastructure/provider/__init__.py
cfme/middleware/provider/__init__.py

{{pytest: cfme/tests/cloud/test_providers.py  cfme/tests/infrastructure/test_providers.py cfme/tests/middleware/test_middleware_provider.py  cfme/tests/containers/test_ssl_providers.py }}
This PR only replaces old web_ui code.  common/Provider and the rest of providers require some refactoring but it will be done later.

[1LP][RFR] common provider widgetastic conversion

---

cfme/middleware/domain.py
cfme/middleware/provider/middleware_views.py
cfme/tests/middleware/domain_methods.py
cfme/tests/middleware/test_middleware_domain.py

Test is disabled until functionality is implemented.

[RFR] Added new test to Stop/Start Midleware Domain.

---

cfme/ansible/credentials.py
cfme/ansible/playbooks.py
cfme/ansible/repositories.py
cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_basic.py
cfme/tests/ansible/test_embedded_ansible_services.py

Update for proper collections+appliance use
Fix tests where needed.
Not expecting any failures, that's kinda the point here :)

[1LP][RFR] Update ansible.repositories, NavigatableMixin

---

cfme/infrastructure/cluster.py
cfme/infrastructure/provider/__init__.py
cfme/tests/infrastructure/test_cluster_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py

[1LP][RFR] Fixed cluster navigatable

---

cfme/containers/node.py
cfme/tests/containers/test_cockpit.py
cfme/tests/containers/test_table_views.py
cfme/utils/appliance/__init__.py

Fixed Collections for container Node

[1LP][RFR] Fixed Collections for container Node

---

cfme/networks/balancer.py
cfme/networks/cloud_network.py
cfme/networks/network_port.py
cfme/networks/network_router.py
cfme/networks/provider/__init__.py
cfme/networks/security_group.py
cfme/networks/subnet.py
cfme/tests/networks/test_sdn_downloads.py
cfme/tests/networks/test_sdn_ports.py

[1LP][RFR] Networks collection remediation

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/utils/appliance/__init__.py

Added new smoke test for enabling embedded ansible.

[1LP][RFR] Added new smoke test for embedded ansible

---

requirements/frozen.txt
scripts/list_provider_vms.py

__Fixing__ list_provider_vms.py - it duplicated output if provider doesn't have vm_type/vm_hardwareconfiguration methods

[1LP][RFR]fixing duplicated output in list_provider_vms.py

---

cfme/tests/services/test_config_provider_servicecatalogs.py

Fix for the recent widgetastic changes in request.py

[1LP][RFR]Ansible Tower request fix

---

cfme/test_framework/sprout/plugin.py

Fixed bad logger calls

---

cfme/automate/service_dialogs.py
cfme/rest/gen_data.py
cfme/tests/configure/test_tag.py
cfme/tests/services/test_rest_services.py

Fixed, this one needs some looking through for usage of methods I changed

[1LP][RFR] Fixed service template collection

---

cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: --long-running -k "test_service_ansible_playbook_crud" cfme/tests/ansible/test_embedded_ansible_services.py}}

[RFR] fix for test_service_ansible_playbook_crud

---

cfme/common/provider.py

{{pytest: --long-running --use-provider=rhv41 -k "test_alert_vm_turned_on_more_than_twice_in_past_15_minutes" cfme/tests/control/test_alerts.py }}

[RFR] missed click in common/provider

---

cfme/configure/configuration/region_settings.py
cfme/tests/control/test_alerts.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py
cfme/tests/test_utilization.py
cfme/tests/test_utilization_metrics.py

[1LP][RFR] Fixed CANDUCollection

---

cfme/common/__init__.py
cfme/configure/configuration/analysis_profile.py
cfme/middleware/provider/__init__.py
cfme/networks/provider/__init__.py
docs/modules.rst

Fix docs never again - did I mention I hate docs

Fix docs never again

---

cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_crud.py

[1LP][RFR] Fixed Schedules Collections

---

cfme/dashboard.py

Fixed Dashboard Collections
{{pytest: cfme/tests/intelligence/reports/test_widgets.py}}

[1LP][RFR] Fixed Dashboard Collections

---

cfme/ansible/credentials.py
cfme/ansible/playbooks.py
cfme/ansible/repositories.py
cfme/cloud/keypairs.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py
cfme/infrastructure/deployment_roles.py
cfme/storage/volume.py
cfme/tests/ansible/test_embedded_ansible_basic.py

[1LP][RFR] Fix multiple collections

---

cfme/ansible/credentials.py

{{pytest: -v --long-running --use-provider complete cfme/tests/ansible/test_embedded_ansible_actions.py }}

[RFR] Update ansible.credentials, collection fixes

---

cfme/base/ui.py

A few things were going wrong here leading to a slew of failed tests
recently
* The bad_password test was broken, this was because the
flash_text_div changed from the id name to the class name on the
login page. This meant the flash message was not found, which meant
in turn that we didn't think there was an error when logging in.
* Couple that with the fact that the BAD credentials were appended to
the appliance object even though the login was bad. This meant that
when executing the bad_password test, the appliance was left with
faulty credentials which it continued to use
So we did a few things:
* We fixed the flahs message check, this should make test_bad_password
pass again, and locally at least this is the case.
* We also moved the appliance user setter inside the conditionals
which …

[1LP][RFR] Fix login and messages

---

docs/guides/collections.rst

[1LP][RFR] Added Collection docs

---

cfme/automate/dialog_box.py
cfme/automate/dialog_element.py
cfme/automate/dialog_tab.py
cfme/automate/explorer/domain.py
cfme/automate/explorer/instance.py
cfme/automate/explorer/klass.py
cfme/automate/explorer/method.py
cfme/automate/explorer/namespace.py
cfme/automate/service_dialogs.py
cfme/tests/automate/test_class.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_domain_priority.py
cfme/tests/automate/test_instance.py
cfme/tests/automate/test_method.py
cfme/tests/automate/test_namespace.py
cfme/tests/automate/test_smoke.py
cfme/tests/automate/test_vmware_methods.py
cfme/tests/cli/test_rake_evm_automate-53.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_dynamicdd_dialogelement.py
cfme/tests/services/test_rest_services.py
cfme/tests/services/test_service_manual_approval.py

Automate collections remediate

[1LP][RFR] Automate collections remediate

---

cfme/utils/appliance/__init__.py

...at least in remote locations

[1LP][RFR] Speeds up initial test start by a lot (REST conversion)

---

cfme/scripting/appliance.py
cfme/scripting/miq.py
cfme/scripting/setup_env.py
cfme/utils/appliance/__init__.py
notebooks/Basic appliance setup.ipynb
notebooks/BasicApplianceSetup.ipynb

Added appliance provision and configuration for advanced environments to miq appliance scripts and notebooks for further customization.

[1LP][RFR] Appliance provision notebook and miq scripts

---

cfme/cloud/provider/__init__.py
cfme/common/provider.py
cfme/infrastructure/provider/__init__.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py

PRT results
---------------
5.8 
All tests passed
5.7
Tests skipped because of a BZ

[RFR][1LP] Fixing RHEV Chargeback failures

---

cfme/configure/settings.py
cfme/tests/cloud/test_cloud_object_tag_visibility.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/webui/test_splitter.py

Fixed a few tests to use Collections properly

[1LP][RFR] Fixed a few tests to use Collections properly

---

cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py

* New provider mark PoC use for real life tests

[1LP][RFR] PoC conversion to provider marker

---

cfme/tests/ansible/test_embedded_ansible_services.py

Intent
======================
`test_service_ansible_playbook_order` renamed to `test_service_ansible_playbook_order_retire` and added additional parameters.
{{pytest: -v -k "test_service_ansible_playbook_order_retire" --long-running}}

[RFR][1LP] Refactored test_service_ansible_playbook_order

---

cfme/services/requests.py

{{pytest: --long-running cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/ansible/test_embedded_ansible_services.py }}

[1LP][WIPTEST] requests collection fix

---

cfme/tests/automate/test_customization_paginator.py

[1LP][RFR] Fixed dialog collection call

---

cfme/tests/networks/test_sdn_balancers.py
cfme/tests/networks/test_sdn_crud.py
cfme/tests/networks/test_sdn_downloads.py
cfme/tests/networks/test_sdn_navigation.py

Fixing some collections test failures

[1LP][RFR] Fixed tests affected by collections

---

cfme/infrastructure/cluster.py

This PR is intended to fix errors like 
> AttributeError'ListView' object has no attribute 'table'
{{pytest: --long-running --use-provider=vsphere55 cfme/tests/infrastructure/test_delete_infra_object.py}}

[RFR] fix for delete clusters method

---

cfme/tests/infrastructure/test_infra_quota.py

Used the do_vm_provisioning to fix the failing tests
{{ pytest: cfme/tests/infrastructure/test_infra_quota.py -vvvv }}

[1LP][RFR] Fixed failing tests

---

cfme/tests/cloud_infra_common/test_tag_objects.py

[1LP][RFR] More Collections failures

---

cfme/tests/cloud_infra_common/test_tag_visibility.py

Fixing test_tag_vis_vm test
{{pytest: -v -k test_tag_vis_vm --long-running}}

[1LP][RFR] Fix for test_tag_vis_vm

---

scripts/template_upload_all.py
scripts/template_upload_openshift.py

We are going to setup automated testing of podified cfme. 
So, upload template scripts should be updated to upload fresh templates to appropriate openshift environments.

[1LP][RFR] pod appliances upload scripts

---

cfme/utils/version.py
requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

Version and some supporting tools are now in a new pacakge

[1LP][RFR] Moved version to package so it can be used elsewhere

---

cfme/cloud/flavor.py
cfme/tests/cloud_infra_common/test_tag_visibility.py
cfme/tests/services/test_orchestration_template.py

[RFR][1LP] Fix lint 15

---

cfme/configure/access_control.py

[1LP][RFR] Fixed docs again

---

cfme/configure/configuration/__init__.py
cfme/tests/configure/test_db_backup_schedule.py
cfme/tests/containers/test_ssl_providers.py
cfme/tests/distributed/test_appliance_replication.py
cfme/tests/infrastructure/test_vm_clone.py
cfme/tests/infrastructure/test_vm_migrate.py
cfme/tests/intelligence/reports/test_report_chargeback.py
cfme/tests/services/test_catalog_item.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_generic_service_catalogs.py
cfme/tests/services/test_service_catalogs.py

[1LP][RFR] Removed some uneeded web_ui calls

---

cfme/infrastructure/datastore.py
cfme/utils/appliance/__init__.py
setup.py

A proof of concept to enforce good collection objects

[1LP][RFR] Enforce Good Collections

---

cfme/ansible/repositories.py

{{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k test_embed_tower_playbooks_list_changed}}

[1LP][RFR] Fixed a collection instantiation

---

fixtures/artifactor_plugin.py

[RFR][1LP] Fixed version push

---

cfme/services/myservice/ui.py
cfme/tests/services/test_myservice.py

Automation test for [BZ1443772](https://bugzilla.redhat.com/show_bug.cgi?id=1443772): Clicking service link of VMDetails page from test_myservice 
{{pytest: cfme/tests/services/test_myservice.py -v -k 'test_service_link' --long-running }}

[1LP][RFR] Added test_service_link for MyService

---

cfme/utils/appliance/__init__.py

Disabling checks for now as the copy command seems to not support it - probably why we don't have type checking in python :)

[1LP][RFR] Disable Checking for now

---

cfme/storage/manager.py
cfme/tests/storage/test_manager.py

- added combine navigation destination for object and block storage manager.
- added simple navigation test for block and object storage manager.
{{pytest: cfme/tests/storage/test_manager.py -v --use-provider rhos7-ga}}

[1LP][RFR] Storage Manager [Block and Object] WT

---

cfme/base/__init__.py
cfme/base/ui.py
cfme/configure/configuration/server_settings.py
cfme/fixtures/smtp.py
cfme/tests/cloud_infra_common/test_html5_vm_console.py
cfme/tests/configure/test_email.py
cfme/tests/configure/test_ntp_server.py
cfme/tests/configure/test_server_name.py
cfme/tests/configure/test_vmware_console_settings.py
cfme/tests/configure/test_zones.py
cfme/tests/infrastructure/test_webmks_console.py
cfme/utils/ext_auth.py

Part1:
Basic Information, Vmware console, NTP and SMTP settings part of Server Settings page
{{pytest: -v -k 'test_send_test_email or test_provision_from_template or test_alert_vm_turned_on_more_than_twice_in_past_15_minutes or test_server_name' --long-running}}
PRT runs, there are some failed cases, but server settings update works fine:
Basic information cases - 15786
Vmware console  - 15815
Auth and Ntp - 15889

[1LP][RFR] ServerSettings to widgetastic: Part1

---

cfme/base/credential.py

{{pytest: cfme/tests/infrastructure/test_providers.py}}

[1LP][WIPTEST] 5.9 has become downstream

---

cfme/tests/cloud_infra_common/test_html5_vm_console.py

console_template is an AttrDict.
Follow-up to #5314

[RFR] Fix console_template use

---

cfme/containers/node.py

{{pytest: cfme/tests/containers/test_table_views.py}}

[1LP][RFR] Fix node collection order

---

widgetastic_manageiq/__init__.py

@brahmanim needs this. Tested manually in ipython in container templates, seems working as expected.

[1LP][RFR] Add new sorting type to Table

---

cfme/scripting/setup_ansible.py

Purpose
Postgresql version bumped to 9.6

[1LP][RFR] Updated postgresql version in setup_ansible script

---

cfme/tests/infrastructure/test_webmks_console.py

__Extending__ WebMKS Test to take screenshot of console if any exception occurs and additional changes to the test. 
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere6-nested --use-provider vsphere65-nested}}

[1LP][RFR] Adding ability to take screenshot on exception in WebMKS console tests and some other changes

---

cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/infrastructure/test_relationships.py
cfme/tests/openstack/infrastructure/test_roles.py

[1LP][RFR] Small fixes for OSP tests

---

cfme/tests/configure/test_visual_cloud.py

Made few changes to resolve jenkin job failures.
{{pytest: -v -k 'test_cloud_start_page'}}

[1LP][RFR]Fix to resolve test case failure.

---

scripts/template_upload_openshift.py

upload script makes opeshift to pull latest image stream changes now

[RFR] update image streams along with new cfme build

---

requirements/frozen.txt
requirements/frozen_docs.txt

* fixes and enhancements
* Python 3 support

[RFR] Update dump2polarion version

---

cfme/fixtures/service_fixtures.py
cfme/services/service_catalogs/__init__.py
cfme/services/service_catalogs/ssui.py
cfme/services/service_catalogs/ui.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/infrastructure/test_vm_clone.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_dynamicdd_dialogelement.py
cfme/tests/services/test_generic_service_catalogs.py
cfme/tests/services/test_iso_service_catalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_provision_stack.py
cfme/tests/services/test_pxe_service_catalogs.py
cfme/tests/services/test_request.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py
cfme/tests/ssui/test_ssui_service_catalogs.py
cfme/tests/test_ui_problems.py
widgetastic_manageiq/__init__.py

{{pytest: -v --long-running cfme/tests/services/test_service_catalogs.py }}

[1LP][RFR]Service catalogs and Notification drawer

---

cfme/cloud/tenant.py

Fixed import

---

cfme/intelligence/reports/dashboards.py
cfme/intelligence/reports/widgets/menu_widgets.py
cfme/tests/intelligence/reports/test_crud.py
cfme/tests/intelligence/reports/test_widgets.py
widgetastic_manageiq/__init__.py

{{pytest: -v -k "test_menuwidget_crud or test_widgets_reorder_in_reports"}}

[1LP][RFR] Added test test_widgets_reorder_in_reports

---

cfme/infrastructure/host.py

{{pytest: -v cfme/tests/infrastructure/test_individual_host_creds.py -k host_bad_creds --use-provider rhv41}}

[RFR] Fix failing host bad creds test

---

cfme/tests/configure/test_access_control.py
cfme/tests/configure/test_server_roles.py
cfme/tests/configure/test_zones.py

Fix config tests

---

cfme/utils/appliance/__init__.py

Fixed a blank line

---

cfme/utils/log.py

this enable logging up to debug level straight to the console for convenient at test run tacking of behaviour
i found this useful while identifying issues

[1LP][RFR] enable a to_console key for logging to the console

---

cfme/control/explorer/actions.py
cfme/control/explorer/alert_profiles.py
cfme/control/explorer/alerts.py
cfme/control/explorer/conditions.py
cfme/control/explorer/policies.py
cfme/control/explorer/policy_profiles.py
cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_basic.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_basic.py
cfme/tests/control/test_bugs.py
cfme/tests/control/test_compliance.py
cfme/tests/control/test_export_policies.py
cfme/tests/infrastructure/test_instance_analysis.py

Intent
Collections conversion of cfme/control/explorer
{{pytest: -v -k "test_basic or test_bugs or test_actions or test_alert or test_instance_analysis or test_events or test_action_run_ansible_playbook or test_control_crud_ansible_playbook_action or test_control_add_ansible_playbook_action_invalid_address" --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Initial implementation for Collections control

---

cfme/base/ssui.py
cfme/services/dashboard/__init__.py
cfme/services/dashboard/ssui.py
cfme/tests/ssui/test_ssui_dashboard.py
widgetastic_manageiq/__init__.py

[1LP][RFR]Added more dashboard tests

---

cfme/infrastructure/provider/__init__.py
cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/provider/virtualcenter.py

__Fixes__ `test_multiple_host_good_creds` and `test_multiple_host_bad_creds`
{{pytest: cfme/tests/infrastructure/test_host.py -k test_multiple_host --use-provider vsphere65-nested}}

[RFR] Move ProviderNodes to InfraProvider

---

cfme/base/__init__.py
cfme/configure/configuration/server_settings.py
cfme/fixtures/configure_auth_mode.py
cfme/tests/configure/test_session_timeout.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py
cfme/utils/ext_auth.py

Convert server Authentication Tab to widgetastic
{{pytest: -v -k 'test_session_timeout' }}
PRT:
test_auth_configure are failing as configs and test are not fully correct, for now, these cases are running manually. Should be updated and fix in another PR

[1LP][RFR] Authentication Tab to widgetastic

---

cfme/utils/appliance/__init__.py

One more place where change for server settings  were missed

[1LP][RFR] Replace old set/get_server_settings

---

cfme/services/requests.py
cfme/tests/ansible/test_embedded_ansible_services.py

Purpose
__Fixing__ `find_request()` method in `RequestsView`. If we use "ui" method to find a service request "Description" key changes to "description" which cause KeyError in other methods which use `cells` attribute.
Also service fixture has been fixed.
Required for #5496

[RFR] Fixed service request

---

cfme/configure/settings.py

Just removing the Save button custom widget because widgetastic patternfly includes it now.
{{pytest: cfme/tests/configure/test_timeprofile.py -v }}

[1LP][RFR]Removing the save button as it's available in patterfly.

---

cfme/services/requests.py
cfme/tests/services/test_operations.py
requirements/frozen.txt
requirements/frozen_docs.txt

{{pytest: cfme/tests/services/test_operations.py}}

[RFR][1LP] various fixes for requests and test_operations tests and web_ui removal

---

cfme/metaplugins/server_roles.py

[RFR]fix_metaplugins

---

cfme/base/ui.py
cfme/tests/perf/workloads/test_memory_leak.py
cfme/utils/appliance/__init__.py
cfme/utils/workloads.py

Updated:
Jenkins run with latest changes: /view/Perf-Downstream-58z/job/perf-test-downstream-58z-workload/104/

[1LP][RFR] New perf memory leak workload

---

cfme/control/explorer/policies.py
cfme/tests/control/test_basic.py

Intent
{{pytest: -v -k "test_control_assign_actions_to_event" --long-running}}

[1LP][RFR] Added test test_control_assign_actions_to_event

---

conf/cfme_data.yaml.template

Fixed bad template

---

conf/cfme_data.yaml.template

Fixed template for endpoints

---

conf/cfme_data.yaml.template

Fixed a typo

---

cfme/tests/integration/test_cfme_auth.py
conf/cfme_data.yaml.template
conf/credentials.yaml.template

Fixed temaplates and a none getter generator

---

docs/getting_started.rst
docs/guides/gotchas.rst
docs/guides/page_development.rst
docs/guides/tipsntricks.rst

[RFR] Updated docs

---

docs/guides/collections.rst

Collection docs get an update to OCE model v3

[1LP][RFR] New collections docs

---

cfme/tests/networks/test_sdn_downloads.py

[RFR] Fixed a call in the test_sdn_downloads tests

---

cfme/tests/control/test_alerts.py

Purpose
Variuos fixes for `cfme/tests/control/test_alerts.py`
{{pytest: -v -k test_alerts.py --long-running --use-provider vsphere6-nested}}

[RFR] Fixed control alerts tests

---

cfme/tests/cloud/test_provisioning.py

Fix cfme/tests/cloud/test_provisioning.py
https://projects.engineering.redhat.com/browse/RHCFQE-4900
{{pytest: cfme/tests/cloud/test_provisioning.py -k test_provision_from_template --long-running --use-provider azure}}

[1LP][RFR] Fix cloud/test_provisioning.py(RHCFQE-4900)

---

.travis.yml

[RFR] Added .travis.yml

---

cfme/tests/infrastructure/test_host_analysis.py

[RFR][1LP] Fixed a bad getter

---

cfme/cloud/instance/__init__.py
cfme/tests/cloud_infra_common/test_tag_visibility.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_infra_object_tag_visibility.py
cfme/tests/infrastructure/test_timelines.py

{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py cfme/tests/infrastructure/test_datastore_analysis.py cfme/tests/infrastructure/test_infra_object_tag_visibility.py, cfme/tests/infrastructure/test_timelines.py
cfme/tests/cloud_infra_common/test_tag_visibility.py}}

[1LP][RFR] fixing ManyItemFound issues in different tests

---

requirements/frozen.txt

[1LP][RFR] Update wrapanapi to 2.4.4

---

cfme/scripting/setup_env.py

Setup env script was not completing HA configuration correctly, or not the standby node at least. It just needed an increase to the timeout.

[1LP][RFR] Fix to setup-env script

---

cfme/configure/configuration/server_settings.py

Fixing exception for 5.7 version in smtp_test fixture
{{pytest: cfme/tests/infrastructure/test_provisioning.py -v -k test_provision_from_template}}

[1LP][RFR] Fix smtp_test fixture

---

cfme/tests/cli/test_appliance_update.py
fixtures/artifactor_plugin.py

should fix the artifactor issues we see on prt

remove use of get_or_create_current_appliance in artifactor plugin

---

cfme/scripting/ipyshell.py
cfme/utils/appliance/__init__.py

[RFR] reenable get_or_create_current_appliance appliance creation in miq shell

---

cfme/services/requests.py

[RFR] Fixed collection entity object

---

scripts/template_upload_scvmm.py

There's a failure running the powershell script to download the file.
Not intending to fix that here, want to keep this limited to these logging fixes.

[1LP][RFR] Fix logger formatting in template_upload_scvmm

---

cfme/cloud/keypairs.py
cfme/common/provider_views.py
cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py
cfme/intelligence/reports/reports.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

======================
Implementing the suggested changes in the test case to improve it.
{{pytest: -v -k 'test_infra_tile_page_per_item or test_infra_list_page_per_item or test_infra_grid_page_per_item or test_infra_report_page_per_item' }}

[1LP][RFR] Implementing changes to improve test cases

---

cfme/base/credential.py

{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/middleware/test_middleware_provider.py cfme/tests/containers/test_ssl_providers.py }}

[1LP][RFR] removed webui forms from credentials 

---

scripts/template_upload_vsphere.py

[1LP][RFR] Fix template_upload_vsphere, flip template check

---

cfme/control/explorer/policies.py

[1LP][RFR] Fix Collections for Policies

---

docs/getting_started.rst

[RFR] Fixed bad markup

---

cfme/ansible/repositories.py

[RFR] Fixed Repository

---

cfme/cloud/stack.py

[1LP][RFR] Fixed Stack

---

scripts/template_upload_vsphere.py

add_disk_to_vm was returning tuple, unpack it.

[1LP][RFR] Fix template_upload_vsphere, wrapanapi return

---

sprout/appliances/models.py
sprout/appliances/templates/appliances/my_appliances.html
sprout/appliances/templates/base.html
sprout/appliances/urls.py
sprout/appliances/views.py
sprout/sprout/settings.py

NOTEST
{{pytest: --collect-only}}

[RFR][NOTEST] Sprout - Some UI tweaks and a Terminate all pools button

---

cfme/physical/provider/__init__.py
cfme/physical/provider/lenovo.py
conf/cfme_data.yaml.template
setup.py

[RFR] Added boilerplate for lenovo_base_provider

---

cfme/tests/cloud_infra_common/test_rest_providers.py

{{pytest: -v cfme/tests/cloud_infra_common/test_rest_providers.py}}

[1LP][RFR] Workaround and blockers for BZ 1501941 on 5.9 and upstream

---

cfme/common/provider.py
cfme/configure/tasks.py
cfme/tests/openstack/infrastructure/test_roles.py

Added some version.pick's for 5.9
Fixed fixture for deployment roles tests

[1LP][RFR] small fixes according to 5.9 and collections' changes

---

cfme/automate/buttons.py
cfme/tests/automate/test_buttons.py
widgetastic_manageiq/__init__.py

{{pytest: -v cfme/tests/automate/test_buttons.py -k 'test_button_crud or test_button_group_crud'}}

[RFR] Fixing the buttons adding in 5.9

---

cfme/configure/tasks.py

[1LP][RFR] Tasks match_location

---

cfme/tests/infrastructure/test_providers.py

... after BZ 1422596 fix
{{pytest: -v -k test_delete_custom_attributes_from_detail_delete cfme/tests/infrastructure/test_providers.py}}

[1LP][RFR] test_delete_custom_attributes_from_detail_delete changes

---

cfme/tests/test_rest.py

{{pytest: -v -k test_rest_paging cfme/tests/test_rest.py}}

[1LP][RFR] changes to test_rest_paging after BZ 1489885 fix

---

cfme/tests/control/test_compliance.py

{{pytest: -v -k "test_check_files" --long-running --use-provider vsphere65-nested}}

[1LP][RFR] Fixed test_check_files

---

cfme/metaplugins/blockers.py
cfme/utils/blockers.py
requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

[1LP][RFR] JIRA blockers

---

cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/instance/__init__.py
cfme/cloud/keypairs.py
cfme/cloud/provider/__init__.py
cfme/cloud/stack.py
cfme/cloud/tenant.py

Starting to remove match_location

[1LP][RFR] Removed match_location

---

cfme/automate/explorer/instance.py

[RFR] Fixed Instance create

---

cfme/modeling/base.py

Fixed EntityBase __hash__ with stopgap method

[RFR] Fixed EntityBase __hash__ with stopgap method

---

cfme/infrastructure/config_management.py
cfme/tests/infrastructure/test_config_management.py

Convert cfme/infrastructure/config_management.py to Widgetastic

[1LP][RFR] Convert cfme/infrastructure/config_management.py to Widgetastic

---

cfme/tests/infrastructure/test_rest_automation_request.py

{{pytest: -v -k test_edit_requests cfme/tests/infrastructure/test_rest_automation_request.py}}

[RFR] Changes to test_edit_requests after BZ 1418331 fix

---

cfme/tests/services/test_rest_services.py

* fixing test_retire_parent_service_now
* new test test_add_child_resource
{{pytest: -v --long-running -k "test_add_child_resource or test_retire_parent_service_now" cfme/tests/services/test_rest_services.py}}

[RFR] parent service tests changes after BZ 1441412 fix

---

cfme/storage/object_store_container.py

[RFR][1LP] Missing attr decorator

---

cfme/dashboard.py
cfme/fixtures/model_collections.py
cfme/tests/intelligence/test_dashboard.py
setup.py

From CI test failures
{{pytest: cfme/tests/intelligence/test_dashboard.py::test_drag_and_drop_widget_to_the_bottom_of_another_column --long-running}}

[RFR] Update cfme.fixtures.model_collections, use CEMv3

---

artifactor/plugins/reporter.py
data/templates/test_report.html
fixtures/artifactor_plugin.py

Added framework "version" into the report

[1LP][RFR] Added framework "version" into the report

---

cfme/fixtures/model_collections.py
cfme/tests/cloud/test_tenant.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/infrastructure/test_delete_infra_object.py
cfme/tests/infrastructure/test_instance_analysis.py
cfme/tests/storage/test_object_store_container.py
setup.py

Remediated more collections appliance kwarg usage

[1LP][RFR] Remediated more collections appliance kwarg usage

---

cfme/tests/services/test_rest_services.py

* fixing the test as discussed with @mshriver in https://github.com/ManageIQ/integration_tests/pull/5555#discussion_r144925091 
* changes after BZ 1480281 is fixed
{{pytest: -v --long-running -k test_order_multiple_catalog_items cfme/tests/services/test_rest_services.py}}

[1LP][RFR] test_order_multiple_catalog_items fixes

---

cfme/tests/services/test_rest_services.py

{{pytest: -v --long-running -k test_power_parent_service cfme/tests/services/test_rest_services.py}}

[1LP][RFR] test_power_parent_service fixes

---

cfme/tests/cli/test_appliance_cli.py
cfme/tests/cli/test_appliance_console.py

Fix to test_black_console_db_reset

[1LP][RFR] - Fixed reset db test

---

cfme/automate/explorer/method.py

Fixed Method create
{{pytest: cfme/tests/cloud/test_provisioning.py}}

[1LP][RFR] Fixed Method create

---

scripts/delete_vm.py

[RFR] apply lib2to3.fixes.fix_except

---

cfme/tests/automate/test_common_methods.py
cfme/tests/automate/test_vmware_methods.py
cfme/tests/cloud/test_cloud_events.py
cfme/tests/cloud/test_cloud_init_provisioning.py
cfme/tests/cloud/test_cloud_timelines.py
cfme/tests/cloud/test_delete_cloud_object.py
cfme/tests/cloud/test_instance_power_control.py
cfme/tests/cloud/test_keypairs.py
cfme/tests/cloud/test_providers.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/cloud/test_stack.py
cfme/tests/cloud/test_tenant.py
markers/env_markers/provider.py

[1LP][RFR] Added provider mark to cloud tests

---

cfme/scripting/sprout.py

this pr splits up the config file populating in sprout checkout

[1LP][RFR] scripting method cleanup

---

cfme/infrastructure/host.py
cfme/infrastructure/provider/__init__.py
cfme/tests/cloud_infra_common/test_tag_objects.py
cfme/tests/configure/test_default_filters.py
cfme/tests/configure/test_visual_infra.py
cfme/tests/infrastructure/test_advanced_search_host.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py
cfme/tests/infrastructure/test_host_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/infrastructure/test_individual_host_creds.py
cfme/tests/infrastructure/test_infra_object_tag_visibility.py
cfme/tests/infrastructure/test_instance_analysis.py
cfme/tests/infrastructure/test_set_default_filter.py
cfme/tests/infrastructure/test_timelines.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/infrastructure/test_host_lifecycle.py
cfme/tests/openstack/infrastructure/test_host_power_control.py
cfme/tests/openstack/infrastructure/test_hosts.py
cfme/tests/openstack/infrastructure/test_roles.py
cfme/tests/perf/workloads/test_smartstate_analysis.py
cfme/utils/hosts.py
setup.py

{{pytest: cfme/tests/ -k 'test_delete_host_appear_after_refresh  or test_host_noquads or test_can_open_advanced_search or test_run_datastore_analysis or  test_run_host_analysis or test_host_drift_analysis or test_host_provisioning  or test_host_good_creds or set_host_credentials or test_set_default_host_filter or test_infra_host_event' }}
PRT failures  not related to changes

[1LP][RFR] Host Collections

---

cfme/storage/volume.py
cfme/tests/openstack/cloud/test_volumes.py

Adding create, edit and delete tests for Openstack Cloud provider
{{pytest: cfme/tests/openstack/cloud/test_volumes.py --use-provider rhos7-ga}}

[1LP][RFR] add Openstack cloud volumes tests

---

conf/cfme_data.yaml.template

Fixed typo in template yaml

---

cfme/tests/ansible/test_embedded_ansible_basic.py

{{pytest: -v -k "test_control_crud_ansible_playbook_action" --long-running}}

[1LP][RFR] Fixed Ansible playbook catalog item creation

---

fixtures/appliance.py

Fix to provisioning version picking
{{pytest: cfme/tests/test_db_migrate.py -k test_upgrade_single_inplace}}

[RFR][1LP] Upgrade fix

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

__Skipping__  test_operations_vm_on. CFME now has bug that reports archived and orphaned VMs in report "Online VMs (Powered On)". Also adding new check that ensures that there are no duplicate VMs in DB. 
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_operations_vm_on --use-provider rhv41 -v}}

[RFR] Adding BZ wrapper for test_operations_vm_on

---

cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py
widgetastic_manageiq/__init__.py

More tests for Myservice in SSUI .
Set ownership , edit tags and delete

[RFR]SSUI set ownership

---

cfme/tests/ssui/test_ssui_dashboard.py

{{pytest: -v --long-running cfme/tests/ssui/test_ssui_dashboard.py -k 'test_monthly_charges' }}
PRT Results:
Test passed on 58

[1LP][RFR] Add test to verify service Chargeback in SUI

---

cfme/tests/automate/test_vmware_methods.py
cfme/tests/test_utilization.py
cfme/tests/test_utilization_metrics.py

[1LP][RFR] Pytest generate tests removal

---

cfme/ansible/playbooks.py
cfme/automate/explorer/namespace.py
cfme/base/ui.py
cfme/infrastructure/host.py
cfme/tests/configure/test_ntp_server.py
cfme/tests/control/test_bugs.py
cfme/tests/infrastructure/test_instance_analysis.py

Some fixes applied to problems on RC over weekend

[1LP][RFR] Fix rc 17.14.0

---

cfme/tests/cloud_infra_common/test_events.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_basic.py
cfme/tests/services/test_provision_stack.py

{{pytest: --long-running cfme/tests/services/test_provision_stack.py }}

[1LP][RFR] some test fixes related to collection v3 migration

---

cfme/common/vm_views.py
cfme/utils/appliance/implementations/ui.py

The issue is caused by Tab click. That click was added in order to resolve the issue when cfme didn't see some changes made in provisioning dialog. 
So, one of ways to fix that issue could be to fix that root issue.
{{pytest: --long-running cfme/tests/services/test_service_catalogs.py cfme/tests/infrastructure/test_provisioning_dialog.py}}

[1LP][RFR] service tests fix

---

cfme/fixtures/smtp.py

__Fixing__ our smtp - details in comments. RHCFQE-5317

[1LP][RFR][NOTEST]fixes to our smtp

---

cfme/tests/test_login.py

[1LP][RFR]Added ignore marker for 5.9

---

scripts/coverage_report_jenkins.py
scripts/coverage_report_sprout.py

[RFR] coverage builder credentials handling + some checking

---

cfme/middleware/jdr_report.py
cfme/middleware/provider/__init__.py
cfme/middleware/provider/middleware_views.py
cfme/middleware/server.py
cfme/tests/middleware/jdr_report_methods.py
cfme/tests/middleware/test_jdr_report.py

Added basic tests.
{{pytest: cfme/tests/middleware/test_jdr_report.py -v --use-provider hawkular}}

[1LP][RFR] Initial Commit: Added new functionality to Generate JDR Reports.

---

cfme/tests/cli/test_appliance_update.py
cfme/tests/test_db_migrate.py

[1LP][RFR] fix to upgrade testing

---

cfme/tests/cloud_infra_common/test_snapshots_rest.py

{{pytest: -v --long-running -k test_delete_snapshot cfme/tests/cloud_infra_common/test_snapshots_rest.py}}

[1LP][RFR] Reference BZ 1466225

---

cfme/tests/test_rest.py

{{pytest: -v -k test_bulk_delete cfme/tests/test_rest.py}}

[1LP][RFR] New test test_bulk_delete

---

cfme/tests/infrastructure/test_vm_rest.py

{{pytest: -v cfme/tests/infrastructure/test_vm_rest.py}}

[1LP][RFR] New REST API test test_edit_vm + some improvements

---

cfme/tests/configure/test_tag.py

{{pytest: -v -k test_bulk_assign_and_unassign_tag cfme/tests/configure/test_tag.py}}

[1LP][RFR] Testing of BZ 1460257

---

scripts/dockerbot/README.md

__Fixing__ command from docker_bot.py to dockerbot.py.

[1LP][RFR][NOTEST]Updating Dockerbot doc, minor change

---

cfme/storage/volume.py
cfme/tests/openstack/cloud/test_volumes.py

Fixing test:  cfme.tests.openstack.cloud.test_volume.py 
some changes in model page aslo.
{{pytest: cfme/tests/openstack/cloud/test_volumes.py  -v --use-provider rhos7-ga}}

[1LP][RFR]  Fix test: cfme.tests.openstack.cloud.test_volume.py 

---

cfme/utils/appliance/db.py

some additional logging so we know what happened with appliance config

[1LP][RFR] Add log message with appliance db config output

---

cfme/configure/settings.py
cfme/tests/configure/test_visual_infra.py

Here the test case is dynamically parametrised to improve the test coverage.
{{pytest: -v -k 'test_infra_grid_page_per_item or test_infra_tile_page_per_item or test_infra_list_page_per_item or test_infra_report_page_per_item'}}

[1LP][RFR]Improving test coverage

---

cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py

__Updating tests__for SSUI Console, to make it complete. In previous PRs the test was added just as a stub, and was not asserting anything. Now it should test working of console. 
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider vsphere6-nested --use-provider rhv41}}

[1LP][RFR]Initial Prototype of SUI Console Tests

---

docs/guides/editors.rst

__Extending__ docs for PyCharm editor.

[1LP][RFR] Add basic PyCharm configuration to guides in docs

---

cfme/utils/trackerbot.py

PRT results won't really matter here 
RHCFQE-4487

[RFR] Update trackerbot and version utils for gaprindashvili

---

cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_request.py

{{pytest: -k 'test_copy_request or test_service_link or test_add_vm_to_service' --long-running}}

[RFR] Seemingly some bits got missed during a conversion

---

cfme/tests/configure/test_visual_infra.py

This replaces calls made to UI at collection time
{{pytest: --collect-only}}

[RFR] Replaces calls made to UI at collection time

---

cfme/tests/cli/test_appliance_cli.py
cfme/utils/appliance/__init__.py

Fix to cli tests that configure database using manditory dbdisk option

[RFR] fixes to cli tests to use dbdisk option

---

cfme/control/explorer/alert_profiles.py
cfme/tests/control/__init__.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py

{{pytest: -v -k "test_alert_hardware_reconfigured" --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Added test test_alert_hardware_reconfigured

---

cfme/tests/control/test_actions.py
cfme/utils/hosts.py
widgetastic_manageiq/__init__.py

{{pytest: cfme/tests/control/test_actions.py -k test_action_initiate_smartstate_analysis --long-running --use-provider vsphere6-nested}}

[RFR] Nasty hack until they support credentials in the quadicon data getter

---

cfme/utils/appliance/implementations/ui.py

* If view is available then we now can wait_for it for 10 seconds
* This helps some forms to fill in better and also makes us fail hard
in the situation that the is_displayed has been poorly constructed.
* Behaviour is overridable by using the DISABLE_NAVIGATE_ASSERT
environment variable.
* Need to pass wait_for_view=True to navigate_to

[RFR] Added waiting for view on navigation

---

cfme/common/__init__.py
cfme/middleware/datasource.py
cfme/middleware/deployment.py
cfme/middleware/domain.py
cfme/middleware/messaging.py
cfme/middleware/server.py
cfme/middleware/server_group.py
cfme/tests/middleware/test_middleware_tags.py

{{pytest: cfme/tests/middleware/test_middleware_tags.py -v --use-provider hawkular}}

[1LP][RFR] WidgetasticTaggable for Middleware.

---

scripts/template_upload_rhevm.py

[RFR] Connect to Glance from RHV

---

markers/composite.py

* Considering pushing this into the appliance.build

[1LP][RFR] Uncollect needed the additional build updates

---

cfme/configure/access_control.py
cfme/tests/configure/test_access_control.py
cfme/tests/infrastructure/test_infra_quota.py
setup.py

Refactored and converted Tenant to Collection + test cases updated
{{ pytest: -v -k tenant cfme/tests/infrastructure/test_infra_quota.py cfme/tests/configure/test_access_control.py }}

[1LP][RFR] Collection conversion of Tenant & Project

---

cfme/middleware/domain.py
cfme/tests/middleware/domain_methods.py

[1LP][RFR] Added Domain's State field validation.

---

cfme/storage/volume.py

remove one web_ui form volume :)
{{pytest: cfme/tests/openstack/cloud/test_volumes.py -v --use-provider rhos7-ga}}

[1LP][RFR] remove match_location in storage volume

---

scripts/clone_template.py

- log to console using utils.logger.add_stdout_handler
- remove bulk cfme.utils import, only import what's needed for script

[1LP][RFR]Update clone_template, imports and logging

---

cfme/base/ui.py

Button text changed from Login to Log In
Instead of version picking text, use id attribute, which is consistent
through versions

[1LP][RFR] Update Log In button to use id attr

---

cfme/containers/node.py
cfme/tests/containers/test_breadcrumbs.py
cfme/tests/containers/test_containers_summary.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_logging.py
cfme/tests/containers/test_node.py
cfme/tests/containers/test_overview_data_integrity.py
cfme/tests/containers/test_properties.py
cfme/tests/containers/test_relationships.py
cfme/tests/containers/test_smart_management.py
cfme/tests/containers/test_table_views.py
cfme/tests/containers/test_tables_fields.py

Updates to container.node to further integrate with widgetastic/collectionsv3.
Updates:
Added toolbar views for Node,NodeDetails
Added accordion for NodeDetails
Updated NodeView to use BaseLoggedInPage
Removed unused impor
Commented out any import/reference to Node in existing test cases until they can be updated to use the widgetastic views/widgets 
Further Actions Needed:
Missing navigation to Ad hoc Metrics, External Logging, and Web Console.

[1LP][RFR] Updates to container.node

---

cfme/storage/manager.py
cfme/tests/storage/test_manager.py

- collection V3 changes in test
- some changes in manager model page
{{pytest: cfme/tests/storage/test_manager.py -v --use-provider rhos7-ga}}

[1LP][RFR] collection v3 and manager page changes

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/utils/appliance/__init__.py

New test to check embedded ansible gets disabled correctly

[1LP][RFR] New embedded ansible disabling test

---

cfme/cloud/instance/__init__.py

All needed methods are available via the view
{{pytest: cfme/tests/cloud/test_provisioning.py}}

[1LP][RFR] Remove a flash import

---

cfme/middleware/provider/hawkular.py
cfme/tests/middleware/test_middleware_provider.py

{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_auth_status -v --use-provider hawkular}}

[1LP][RFR] Middleware Provider: Added new test for Authentication status field validation.

---

cfme/tests/cli/test_appliance_update.py

New test added for embedded ansible and webui update.

[1LP][RFR] Added new embedded ansible update test

---

cfme/common/__init__.py
cfme/configure/configuration/server_settings.py
cfme/middleware/jdr_report.py
docs/getting_started.rst
docs/guides/editors.rst

* Some issues that crept into recent docs changes - these now build
cleanly

[RFR] Fixing docs

---

cfme/containers/image.py

A fix for wrong title of configuration table.

[RFR] Fix Configuration table

---

cfme/common/provider.py
cfme/middleware/provider/__init__.py
cfme/middleware/server_group.py
cfme/tests/middleware/deployment_methods.py
cfme/tests/middleware/jdr_report_methods.py
cfme/tests/middleware/test_middleware_provider.py

{{pytest: cfme/tests/middleware/test_middleware_provider.py::test_password_mismatch_validation -v --use-provider hawkular}}

[1LP][RFR] Various Fixes, increased some timeouts, Added missing navigation

---

cfme/infrastructure/datastore.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py

{{pytest: --use-provider=vsphere6-nested cfme/tests/infrastructure/test_datastore_analysis.py cfme/tests/infrastructure/test_delete_infra_object.py}}

[1LP][RFR] renaming datastore.contents->entities 

---

cfme/control/explorer/alerts.py

New required field was added in CFME 5.9 in Alerts.
{{pytest: -v -k "test_alert_crud" --long-running}}

[1LP][RFR] Added 'Severity' field into alerts

---

cfme/configure/configuration/diagnostics_settings.py
cfme/tests/configure/test_workers.py
setup.py

Convert server workers page
{{pytest: cfme/tests/configure/test_workers.py -v -k test_restart_workers}}

[1LP][RFR] Server Workers conversion

---

cfme/tests/containers/test_containers_smartstate_analysis.py

{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py}}

[1LP][RFR] Fix SSA test

---

conf/cfme_data.yaml.template
conf/credentials.yaml.template

This PR add some initial configurations to start Lenovo providers integration tests.

[RFR] Add initial configuration to physical infra provider by Lenovo

---

cfme/tests/middleware/test_middleware_provider.py

{{pytest: cfme/tests/middleware/test_middleware_provider.py -v --use-provider hawkular}}

[RFR] Removed deprecated selenium usage.

---

docs/getting_started.rst

Added docs for configuration of appliance

[RFR][1LP] Added docs for configuration of appliance

---

cfme/scripting/sprout.py
scripts/dockerbot/dockerbot.py
scripts/dockerbot/pytestbase/setup.sh

this tries to use the sprout checkout command in dockerbot

[1LP][RFR] Dockerbot use sprout checkout

---

cfme/utils/appliance/__init__.py

* Embedded Ansible requires longer wait time
{{pytest: cfme/tests/ansible/test_embedded_ansible_actions.py --long-running}}

[1LP][RFR] Fix embedded ansible tests

---

cfme/utils/appliance/__init__.py

roles is a dictionary, not a set :)

[1LP][RFR] Fix wrong ansible role handling

---

cfme/tests/containers/test_start_page.py

Commented out Volumes start page test due to a bug.

[RFR] Added blocker for cfme/tests/containers/test_start_page.py

---

cfme/services/dashboard/__init__.py
cfme/services/dashboard/ssui.py
cfme/services/myservice/ssui.py
cfme/services/service_catalogs/ssui.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py
widgetastic_manageiq/__init__.py

Support for 5.7 build testing.

[1LP][RFR] Support tests for 5.7 build

---

cfme/tests/test_rest.py

{{pytest: -v -k test_attributes_present cfme/tests/test_rest.py}}

[1LP][RFR] add blocker for buggy vms collection

---

cfme/base/login.py

{{pytest: cfme/tests/configure/test_server_name.py}}

[1LP][RFR] Fixed Help button in 5.9

---

cfme/configure/configuration/analysis_profile.py

{{pytest: cfme/tests/configure/test_analysis_profiles.py -k test_delete_default_analysis_profile}}

[1LP][RFR] Analysis Profile Table updated id/class in 5.9

---

cfme/configure/configuration/__init__.py

{{pytest: cfme/tests/configure/test_log_depot_operation.py -k test_collect_single_servers}}

[1LP][RFR] Credentials lost the verify for log_depot

---

cfme/automate/provisioning_dialogs.py

{{pytest: cfme/tests/automate/test_provisioning_dialogs.py -k test_provisioning_dialogs_sorting}}

[1LP][RFR] Dialog Table moved locator

---

cfme/automate/explorer/common.py

{{pytest: cfme/tests/services/test_rest_services.py -v -k test_create_pending_request --long-running }}

[1LP][RFR] AE copy ignores known error

---

cfme/automate/explorer/method.py

{{pytest: cfme/tests/automate/test_method.py::test_method_crud -v}}

[1LP][RFR] Do not verify while the button is screwed up

---

cfme/automate/explorer/klass.py

{{pytest: cfme/tests/automate/test_class.py -k duplicate -v }}

[1LP][RFR] Do not check flash message on class create if bug still open

---

cfme/infrastructure/config_management.py

{{pytest: cfme/tests/infrastructure/test_config_management.py}}

[1LP][RFR] Configuration Management ids changed

---

cfme/base/ui.py
cfme/configure/configuration/region_settings.py

Fix Category/Tag views to cover 5.9 feature updates
{{pytest: -v -k 'test_category_crud or test_tag_crud'}}

[1LP][RFR] Fix Tag/Category view for 5.9

---

fixtures/artifactor_plugin.py

Simple update to the tags checker

[1LP][RFR] Simple update to the tags checker

---

scripts/ipappliance.py

Tested locally
Needed by rhev team to be able to check if DB has been enabled on an appliance, from jenkins.
`./scripts/ipappliance db.is_enabled <appliance_ip>`

[RFR] Add ability to traverse properties to ipappliance script

---

cfme/tests/configure/test_access_control.py

Added valid quota input test
{{ pytest: -vvv -k test_tenant_quota_input_validate cfme/tests/configure/test_access_control.py }}

[1LP][RFR] Added Quota valid input test

---

cfme/tests/infrastructure/test_set_default_filter.py

{{pytest: cfme/tests/infrastructure/test_set_default_filter.py::test_clear_datastore_filter_results}}

[1LP][RFR] test_clear_datastore_filter_results fix

---

cfme/scripting/appliance.py

New script to allow people to quickly upgrade a single appliance for additional testing.

[RFR][1LP] New miq upgrade script

---

scripts/template_upload_ec2.py
scripts/template_upload_gce.py
scripts/template_upload_openshift.py
scripts/template_upload_rhos.py
scripts/template_upload_scvmm.py
scripts/template_upload_vsphere.py

No framework impacts, PRT irrelevant.

[RFR] Update template_upload_*, use yaml block_upload

---

cfme/ansible/credentials.py
cfme/tests/ansible/test_embedded_ansible_basic.py

{{pytest: -v -k "test_embedded_ansible_credential_with_private_key" --long-running}}

[1LP][RFR] Added test_embedded_ansible_credential_with_private_key

---

cfme/common/host_views.py
cfme/common/provider_views.py
cfme/common/vm_views.py
widgetastic_manageiq/__init__.py

{{pytest: --long-running cfme/tests/infrastructure/test_snapshot.py cfme/tests/infrastructure/test_vm_power_control.py cfme/tests/infrastructure/test_instance_analysis.py cfme/tests/infrastructure/test_datastore_analysis.py::test_run_datastore_analysis cfme/tests/infrastructure/test_host_analysis.py::test_run_host_analysis cfme/tests/openstack/infrastructure/test_provider.py::test_credentials_quads}}

[RFR][1LP] quad icon power state support in 5.9 

---

cfme/utils/appliance/__init__.py

{{pytest: cfme/tests/configure/test_server_name.py}}

[1LP][RFR] Removing zone descriptoin call to db for 5.8+

---

cfme/configure/access_control.py

Corrected `is_displayed` and `wait_for`
{{ pytest: cfme/tests/configure/test_access_control.py --long-running -vvv -k tenant }}

[1LP][RFR] Corrected is_displayed for Projects

---

cfme/tests/configure/test_visual_infra.py

test_visual_infra.py was using appliance provided data in test parameterization that equaled a already known
constant, so i just shifted to to use that

[1LP][RFR] fix collectonly for dummy-appliance

---

cfme/configure/access_control.py

Correction in views and class to make checking of the object for Projects and Tenants
{{ pytest: -vvvv cfme/tests/configure/test_access_control.py -k tenant }}

[1LP][RFR] Corrected checks for Projects

---

cfme/services/catalogs/orchestration_template.py

{{ pytest: --use-provider ec2west cfme/tests/services/test_orchestration_template.py -k test_orchestration_template_crud }}
Run 17837 is true positive results

[1LP][RFR] Update dropdown text for orch_temp remove

---

cfme/automate/service_dialogs.py
cfme/tests/automate/test_customization_paginator.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py
cfme/web_ui/paginator.py
widgetastic_manageiq/__init__.py

devs added min_item/max_item data to JS Paginator API. So, we can start using it in our tests.

[1LP][RFR] 5.9 paginator enhancement

---

cfme/tests/test_rest.py

{{pytest: -v -k test_select_attributes cfme/tests/test_rest.py}}

[1LP][RFR] Fix test_select_attributes for automate collection

---

cfme/utils/mgmt_system/__init__.py
requirements/frozen.txt

Just a small update to wrapanapi

[1LP][RFR] New wrapanapi removes older reference class

---

cfme/middleware/server.py

{pytest: cfme/tests/middleware/test_middleware_domain_server.py::test_domain_server_suspend_resume  -v --use-provider hawkular}}

[1LP][RFR] Fixed several problems with Middleware Server tests.

---

widgetastic_manageiq/__init__.py

{{ pytest: --long-running -v --use-provider rhv41 -k test_infra_cluster_event }}

[1LP][RFR] adding forgotten name property to quadicons

---

scripts/template_upload_ec2.py

This check was failing if template_upload wasn't in yaml, which was not the intent.

[RFR] Fix template_upload_ec2, block_upload check

---

cfme/common/provider.py

The logic was always returning False for the BZ, and should have been NOT'ing the blocks
{{pytest: cfme/tests/infrastructure/test_provider_discovery.py -k test_discover_infra}}

[RFR] Hack had invalid logic and invalid bz_blocker

---

cfme/utils/blockers.py
docs/conf.py

Fixed docs that were not building

[1LP][RFR] Fixed docs references

---

cfme/services/requests.py

updating locator for Requests table
{{pytest:: cfme/tests/infrastructure/test_provisioning.py -k test_provision_ --long-running}}

[1LP][RFR] updating locator for 5.9

---

cfme/tests/webui/test_splitter.py
cfme/web_ui/splitter.py
widgetastic_manageiq/__init__.py

* Splitter is now WT
* Splitter test was causing failures where the test failed and the
view was not reset

[RFR][1LP] Converting splitter to WT

---

cfme/ansible/repositories.py
cfme/services/myservice/ui.py
cfme/services/service_catalogs/ui.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_custom_button_ansible_credential_list" --long-running}}

[1LP][RFR] Added test test_custom_button_ansible_credential_list

---

cfme/modeling/base.py
cfme/modeling/tests/test_collections.py
cfme/utils/appliance/__init__.py

this tries to unify the different collections for entities and appliance into one kind of ojbect
smoke tests pass but i believe a more excessive test is needed

[RFR] unify different collections manages into EntityCollections

---

cfme/infrastructure/pxe.py
cfme/tests/infrastructure/test_system_image_type.py
setup.py

Converting the SystemImageType to collection
{{pytest: cfme/tests/infrastructure/test_system_image_type.py -v }}

[1LP][RFR] Collection of SystemImageType

---

cfme/rest/gen_data.py

{{pytest: -v -k TestRolesViaREST}}
PRT:
the only failure on upstream is unrelated

[1LP][RFR] Use create_resource for gen_data

---

widgetastic_manageiq/__init__.py

It turned out that some quadicons cannot provide their name when not displayed after their primary key has been replaced from name to id.
These changes fix this issue because name should be always available.

[1LP][RFR] added simple entity name caching mechanizm

---

cfme/tests/cloud/test_instance_power_control.py

Needed a second instance of this

[RFR] Flash message needed updating

---

cfme/common/provider.py

This is already in 17.15.1.rc and needs to be in master

[RFR] Hack needed an upgrade

---

cfme/generic_objects/definition/associations.py
cfme/generic_objects/definition/rest.py
cfme/generic_objects/instance/__init__.py
cfme/generic_objects/instance/rest.py
cfme/tests/generic_objects/test_definitions.py
cfme/tests/generic_objects/test_instances.py
setup.py

and minor enhancements related to Generic Object Definitions
{{pytest: -v cfme/tests/generic_objects/test_instances.py cfme/tests/generic_objects/test_definitions.py}}

[1LP][RFR] Adds Generic Objects collection and CRUD test

---

cfme/scripting/setup_env.py

Extending setup_env because I want to use existing pools

[RFR] Add option to use existing Sprout pools

---

cfme/tests/infrastructure/test_tenant_quota.py

{{ pytest: -vvvv cfme/tests/infrastructure/test_tenant_quota.py }}

[1LP][RFR] removed unnecessary fixtures

---

cfme/intelligence/reports/__init__.py
cfme/intelligence/reports/reports.py

Fixed report flash and table elements

[1LP][RFR] Fixed report flash and table elements

---

cfme/configure/access_control.py
cfme/tests/configure/test_access_control.py

{{ pytest: -vvvv cfme/tests/configure/test_access_control.py -k test_delete_default_tenant }}

[1LP][RFR] New default tenant deletion test case and table xpath correction

---

cfme/utils/appliance/implementations/ssui.py

Updated SSUI navigate go fn
*Shriver edit :: added --long-running to PRT for collection*
{{ pytest: cfme/tests/ssui/test_ssui_dashboard.py --long-running }}

[1LP][RFR] Updated SSUI navigate go fn

---

scripts/template_upload_all.py

shorten upstream release names to 5 characters

[RFR] Update template naming in upload script

---

cfme/tests/cli/test_appliance_cli.py
cfme/utils/appliance/__init__.py

Added some new testing around new cli features for 5.9.
{{pytest: -v -k "test_black_console_cli"}}

[1LP][RFR] New CLI tests for new features

---

cfme/scripting/sprout.py
cfme/test_framework/appliance.py
cfme/test_framework/sprout/client.py
cfme/utils/appliance/__init__.py
scripts/dockerbot/pytestbase/Dockerfile
scripts/dockerbot/pytestbase/setup.sh

work in progress adding the pytest options and the init args as well as the not yet tested code in the prt image commands

[1LP][RFR] Dockerbot collectonly step hack

---

cfme/scripting/sprout.py
cfme/test_framework/appliance.py
cfme/test_framework/sprout/client.py
cfme/utils/appliance/__init__.py
scripts/dockerbot/pytestbase/Dockerfile
scripts/dockerbot/pytestbase/setup.sh

Reverts ManageIQ/integration_tests#5772

Revert "[1LP][RFR] Dockerbot collectonly step hack"

---

cfme/scripting/appliance.py

Change to enable ansible script option to match standardization.

[RFR] change to script option

---

cfme/utils/appliance/__init__.py

[1LP][RFR] Wait for embedded ansible only when enabling it

---

cfme/intelligence/reports/dashboards.py
cfme/tests/intelligence/test_dashboard.py

Purpose
__Fixing__ test_custom_dashboard for CFME 5.9 due changed strings and collections.
{{pytest: -v -k "test_custom_dashboard"}}

[RFR] Fixed test_custom_dashboards

---

cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k "test_action_run_ansible_playbook" --long-running}}

[RFR] Added blockers into ansible tests

---

cfme/infrastructure/cluster.py

{{pytest: --use-provider=vsphere6-nested --long-running cfme/tests/infrastructure/test_cluster_analysis.py}}

[RFR] small paginator call fix for cluster

---

cfme/common/provider_views.py
cfme/containers/node.py
cfme/containers/provider/__init__.py
cfme/tests/containers/test_ad_hoc_metrics.py
cfme/tests/containers/test_logging.py

{{ pytest: cfme/tests/containers/test_logging.py cfme/tests/containers/test_ad_hoc_metrics.py --use-provider cm-env2}}

[RFR] Fix monitor --> toolbar.monitoring

---

fixtures/artifactor_plugin.py

[RFR] Stop held_appliance AttributeError from masking errors

---

cfme/common/provider.py

{{pytest: cfme/tests/infrastructure/test_providers.py -k test_provider_crud --use-provider complete --provider-limit 1}}

[RFR] Workaround to delete providers using UI

---

scripts/azure_cleanup.py

recently pool of public IP was filled with name using old naming - like "test_" and "test<sometext>"

[RFR]fix for azure cleanup

---

cfme/base/ssui.py
cfme/base/ui.py
cfme/utils/appliance/__init__.py

It is necessary for testing pod appliances

[1LP][RFR] fixing static https url

---

cfme/test_framework/pytest_plugin.py
fixtures/skip_not_implemented.py

[RFR] Skip NotImplementedError

---

scripts/image_upload_glance.py
scripts/template_upload_all.py
scripts/template_upload_rhevm_qcow2.py

Added support for upload CFME QCOW2 templates for RHV.

[RFR] Add support for CFME QCOW2 templates for RHV

---

cfme/tests/configure/test_display_settings.py
cfme/web_ui/__init__.py
widgetastic_manageiq/__init__.py

[RFR] ColorGroup removal as it's no longer used

---

cfme/infrastructure/pxe.py
cfme/tests/infrastructure/test_customization_template.py
setup.py

This PR contain the collection related changes in cfme/infrastructure/pxe.py file for CustomizationTemplate class and accordingly making changes in the test case related to it.
{{pytest: cfme/tests/infrastructure/test_customization_template.py -v }}

[1LP][RFR] Introducing Collection in CustomizationTemplate

---

cfme/base/__init__.py
cfme/services/dashboard/__init__.py
cfme/services/myservice/__init__.py
cfme/services/service_catalogs/__init__.py

Removing a warning generator :)

[RFR][1LP] Remove external implementations method from sentaku

---

cfme/utils/rest.py

{{pytest: -v -k '_delete_ and from_collection and not TestReposRESTAPI and not TestAuthenticationsRESTAPI' --use-provider vsphere65-nested}}

[1LP][RFR] Remove import store from utils/rest

---

cfme/base/ui.py

Reverts ManageIQ/integration_tests#5349

Revert "[RFR] AutomateExplorer loaded server base"

---

cfme/tests/cloud/test_keypairs.py

{{pytest: cfme/tests/cloud/test_keypairs.py -k test_keypair_add_and_remove_tag}}

[RFR] Fixed up keypair calls fixture

---

cfme/configure/tasks.py

{{pytest: --long-running cfme/tests/infrastructure/test_instance_analysis.py }}

[RFR] fixed tasks div id  for 59

---

cfme/base/ui.py

The function is in the same file!!

[1LP][RFR] Automate imports were redundant

---

cfme/services/catalogs/orchestration_template.py

{{pytest: cfme/tests/services/test_orchestration_template.py}}

[1LP][RFR] OrchestrationTemplates paginator update

---

cfme/configure/access_control.py

Currently there are no tests checking this table or the property so I've put [NOTEST]

[1LP][RFR][NOTEST] Corrected table xpath and added quotas property

---

cfme/middleware/provider/hawkular.py
cfme/middleware/provider/middleware_views.py
cfme/tests/middleware/test_provider_timelines.py

{{pytest: cfme/tests/middleware/test_provider_timelines.py -v --use-provider hawkular}}

[1LP][RFR] Middleware uses Widgetastic Timelines.

---

cfme/tests/networks/test_sdn_downloads.py

{{pytest: cfme/tests/networks/test_sdn_downloads.py --use-provider=azure}}

[1LP][RFR] Fixed old calls to appliance.get

---

cfme/common/__init__.py

[RFR] Removed old timelines mixin

---

cfme/services/catalogs/catalog_item.py

Remove web_ui tabstrip form catalog items
{{pytest: -k test_cloud_catalog_item --long-running}}

[1LP][RFR]Tabstrip remove

---

cfme/scripting/sprout.py
cfme/test_framework/appliance.py
cfme/test_framework/sprout/client.py
cfme/utils/appliance/__init__.py
scripts/dockerbot/pytestbase/Dockerfile
scripts/dockerbot/pytestbase/setup.sh

this reapplies all changes and then fixes the details that broke the configuration serialization
please check with care

[1LP][RFR] reapply and correct the collectonly prt hack

---

cfme/provisioning.py

{{pytest: cfme/tests/infrastructure/test_provisioning.py}}

[1LP][RFR] Remove flash check from using web_ui

---

cfme/exceptions.py
cfme/fixtures/pytest_selenium.py
cfme/tests/automate/test_customization_paginator.py
cfme/tests/cloud_infra_common/test_genealogy.py
cfme/tests/configure/test_session_timeout.py
cfme/tests/containers/test_manageiq_ansible_users.py
cfme/tests/control/test_bugs.py
cfme/tests/infrastructure/test_advanced_search_host.py
cfme/tests/infrastructure/test_set_default_filter.py
cfme/tests/intelligence/test_rss.py
cfme/tests/webui/test_splitter.py
cfme/utils/tests/test_simple_locators.py
fixtures/browser.py
fixtures/screenshots.py

* This removes the pytest.sel namespace

[1LP][RFR] Removed pytest.sel namespace

---

docs/guides/newprovider.rst

[RFR][NOTEST] New provider docs

---

cfme/ansible/repositories.py
cfme/common/vm.py
cfme/configure/configuration/analysis_profile.py
cfme/configure/settings.py
cfme/exceptions.py
cfme/fixtures/base.py
cfme/intelligence/reports/import_export.py
cfme/rest/gen_data.py
cfme/test_framework/sprout/plugin.py
cfme/tests/cloud/test_tenant.py
cfme/tests/configure/test_session_timeout.py
cfme/tests/control/test_basic.py
cfme/tests/control/test_smoke_control.py
cfme/tests/infrastructure/test_delete_infra_object.py
cfme/tests/infrastructure/test_instance_analysis.py
cfme/tests/intelligence/reports/test_widgets.py
cfme/tests/intelligence/test_chargeback_assignments.py
cfme/tests/storage/test_manager.py
cfme/tests/test_csrf.py
cfme/tests/webui/test_splitter.py
cfme/utils/tests/test_simple_locators.py
cfme/web_ui/paginator.py
fixtures/widgets.py
scripts/browser.py

[1LP][RFR] Flake remediation

---

requirements/frozen.txt

widgetastic_patternfly version update

[1LP][RFR]Version update(widgetastic_patternfly)

---

cfme/tests/ansible/test_embedded_ansible_rest.py

{{pytest: -v --long-running -k test_delete_repository_from_detail cfme/tests/ansible/test_embedded_ansible_rest.py}}

[1LP][RFR] Test changes after fix to BZ 1477520

---

cfme/automate/buttons.py
cfme/automate/explorer/namespace.py
cfme/tests/automate/test_buttons.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_instance.py
cfme/tests/automate/test_vmware_methods.py

{{pytest: -v cfme/tests/automate/ -k 'not (_dialog_ or _dialogs_ or paginator or common_methods or _dialog)'}}

[1LP][RFR] Some work on Automate and its tests

---

cfme/intelligence/reports/dashboards.py

{{pytest: -v -k "test_dashboard_crud"}}

[RFR] Fixed test_dashboard_crud

---

cfme/scripting/quickstart.py
cfme/scripting/tests/test_quickstart.py

{pytest: -k test_quickstart --long-running}

[1LP][RFR] quickstart: fix tests and add fedora 27 support

---

cfme/scripting/link_config.py

* allow missing source -> warnings
* allow local files shadowing files from the source folder -> warning + mention .local.yaml

[1LP][RFR] make quickstart link config more lenient

---

cfme/tests/infrastructure/test_quota_tagging.py

Created new quota tests via tagging for current group
{{ pytest:  -vvvv cfme/tests/infrastructure/test_quota_tagging.py }}

[1LP][RFR] New quota tests via tagging

---

cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/stack.py
cfme/common/host_views.py
cfme/common/vm_views.py
cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py
cfme/infrastructure/virtual_machines.py
cfme/networks/views.py
cfme/storage/manager.py
cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_relationships.py

Intent
It would be nice to have automation for relationship navigation of a provider, a host etc.
{{pytest: -v -k "test_host_relationships or test_infra_provider_relationships or test_cloud_provider_relationships"}}

[RFR][1LP] Test relationships

---

cfme/infrastructure/host.py
cfme/tests/automate/test_buttons.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/services/test_provision_stack.py

{{pytest: cfme/tests/automate/test_buttons.py -k test_button_on_host}}

[RFR] Fixed calls to host

---

cfme/fixtures/tag.py
widgetastic_manageiq/expression_editor.py

More removals
{{pytest: cfme/tests/cloud/test_cloud_object_tag_visibility.py -k test_tagvis_cloud_object}}

[RFR][1LP] Removed some more web_ui references

---

cfme/scripting/quickstart.py

I did not have the time and nerves to update yet.

[RFR] Quickstart supports F23

---

cfme/infrastructure/resource_pool.py
cfme/tests/infrastructure/test_delete_infra_object.py
setup.py

{{pytest: -v cfme/tests/infrastructure/test_delete_infra_object.py --use-provider vsphere55 --long-running -k delete_resource_pool_appear_after_refresh}}

[RFR][1LP] Resource Pool: web_ui removal and collections conversion

---

cfme/base/__init__.py
cfme/base/rest.py
cfme/configure/configuration/diagnostics_settings.py
cfme/tests/configure/test_log_depot_operation.py
cfme/utils/appliance/__init__.py
requirements/frozen.txt
requirements/frozen_docs.txt

Building on the RZS Experiment

[RFR][1LP] Test remove slave stuff

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/reports/test_views.py
widgetastic_manageiq/__init__.py

web_ui removal from reports test

[1LP][RFR] web_ui removal from reports test

---

cfme/scripting/quickstart.py

Quickstart Can't run on RHEL servers added RHEL 7 support

[RFR] Adding RHEL support to quickstart

---

cfme/base/ui.py
cfme/configure/access_control.py
cfme/configure/configuration/server_settings.py
cfme/optimize/bottlenecks.py
cfme/tests/configure/test_log_depot_operation.py
cfme/tests/infrastructure/test_instance_analysis.py
cfme/utils/appliance/__init__.py

[1LP][RFR] Even more removals

---

cfme/base/ssui.py
cfme/configure/access_control.py
cfme/tests/configure/test_access_control.py

* Added a get_tags function to the objects using the view
* Can't use WidgetasticTaggable as the view is completely different
* Added a refresh after creating a group for the tree to update

[RFR] Access control tests web_ui removal

---

cfme/intelligence/rss.py
cfme/tests/intelligence/test_rss.py

[RFR] Remove web_ui for RSS

---

cfme/tests/openstack/infrastructure/test_hosts.py

[RFR] Removed a call to toolbar

---

cfme/tests/storage/test_manager.py
cfme/tests/storage/test_object_store_container.py
cfme/tests/storage/test_object_store_object.py
cfme/tests/storage/test_volume.py

[1LP][RFR] Remove testgen from storage

---

cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

[1LP][RFR] Remove testgen from ssui

---

cfme/common/provider.py
cfme/tests/cloud_infra_common/test_rest_providers.py

Adds support for all infra and cloud providers.
{{pytest: -v -k 'test_provider_refresh and not gce_central' cfme/tests/cloud_infra_common/test_rest_providers.py --use-provider complete}}

[1LP][RFR] More complete provider.create_rest

---

fixtures/skip_not_implemented.py

5 tests, SSIA
{{pytest: --use-provider vsphere55 cfme/tests/services/test_different_dialogs_in_catalogs.py --long-running}}

[RFR] Skip on fixture NotImplementedError as well

---

cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py
widgetastic_manageiq/__init__.py

{{pytest: -v --long-running --use-provider vsphere cfme/tests/ssui/test_ssui_myservice.py }}

[1LP][RFR] SSUI retire test automation

---

cfme/tests/infrastructure/test_tenant_quota.py

Added new test for tenant quota via services
{{ pytest: -vvv cfme/tests/infrastructure/test_tenant_quota.py }}

[1LP][RFR] New tenant quota test via service

---

cfme/services/service_catalogs/ui.py

7 tests, SSIA
I don't believe it will pass on PRT. I think it will trigger the NotImplementedError and therefore skip.
{{pytest: cfme/tests/services/test_service_manual_approval.py -k test_service_manual_approval --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Fix service ordering flash msg

---

cfme/services/catalogs/catalog_item.py
cfme/tests/control/test_bugs.py

* Fixed title search to remove sel
* Fixed time import to remove sel

[RFR] Optimized imports and fixed bugs

---

requirements/frozen.txt

[RFR]Widgetastic.patternfly version_update

---

cfme/common/provider_views.py
cfme/physical/provider/__init__.py
cfme/physical/provider/lenovo.py

Mostly everything is there for the Lenovo provider to be created now, but the string_name is broken in the latest build and I don't want to screw with create method unless I have to

[1LP][RFR] Added Lenovo Provider base views etc

---

cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_vm_clone.py

__Fixing__ text_vm_clone. 
{{pytest: cfme/tests/infrastructure/test_vm_clone.py --long-running }}

[1LP][RFR]refactoring test_vm_clone

---

cfme/ansible/playbooks.py
cfme/tests/ansible/test_embedded_ansible_basic.py

{{pytest: -v -k "test_embed_tower_playbooks_list_changed" --long-running}}

[1LP][RFR] Fixed test_embed_tower_playbooks_list_changed

---

cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/infrastructure/resource_pool.py

Update classes to use BaseEntitiesView + navigation steps update
{{pytest: -k 'test_delete_resource_pool_appear_after_refresh or test_tagvis_cloud_object' --long-running}}

[RFR]Update classes to use BaseEntitiesView

---

cfme/automate/explorer/__init__.py
cfme/automate/explorer/instance.py
cfme/automate/explorer/method.py

{{pytest: -v cfme/tests/automate/test_instance.py cfme/tests/automate/test_method.py -k crud --long-running}}

[1LP][RFR] Fix automate nav by using icons

---

cfme/configure/access_control.py

{{pytest: -v -k test_superadmin_child_tenant_crud}}

[1LP][RFR] Fixed test_superadmin_child_tenant_crud

---

cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/infrastructure/test_vm_reconfigure.py
cfme/tests/infrastructure/test_webmks_console.py

__Updating tests.__ Replace testgen with provider marker.

[1LP][RFR] Remove testgen from infrastructure (part 4)

---

cfme/configure/tasks.py
cfme/containers/image.py
cfme/tests/containers/test_containers_smartstate_analysis.py
setup.py

{{pytest: cfme/tests/infrastructure/test_host_analysis.py -v  --use-provider vsphere65-nested --long-running }}
**Shriver: Expanded PRT to include a test that also uses is_task_finished because of the change to using regex compiled expressions
cfme/tests/containers/test_containers_smartstate_analysis.py  (removed for now)
**
Image conversion to collection
In this PR @shalomnaim1 and I will convert Container Image object to compatible with collection as preparation for SSA test
Also make some updates to support CFME 5.9 UI changes

[1LP][RFR] Image conversion to collection

---

cfme/ansible/repositories.py
cfme/automate/explorer/klass.py
cfme/automate/explorer/method.py
cfme/tests/ansible/test_embedded_ansible_automate.py

{{pytest: -v -k "test_automate_ansible_playbook_method_type_crud or test_automate_ansible_playbook_method_type" --long-running}}

[1LP][WIPTEST] Added new test test_automate_ansible_playbook_method_type

---

cfme/common/host_views.py
cfme/common/provider_views.py
cfme/common/vm_views.py
cfme/infrastructure/datastore.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

================
Making changes in the test case related to quadicon deactivation to resolve failures because of the changes made in the data property of quadicon.
{{pytest: -v -k 'test_cloudprovider_noquads or test_template_noquads or test_datastore_noquads or test_host_noquads or test_infraprovider_noquads or test_vm_noquads'}}

[1LP][RFR] Fixing failure related to quadicon deactivation test case

---

cfme/common/host_views.py
cfme/common/vm.py
cfme/infrastructure/virtual_machines.py
cfme/services/workloads.py
cfme/tests/containers/test_search_bar.py
cfme/tests/infrastructure/test_advanced_search_host.py
cfme/tests/infrastructure/test_advanced_search_providers.py
cfme/tests/infrastructure/test_advanced_search_vms.py
cfme/tests/infrastructure/test_set_default_filter.py
widgetastic_manageiq/__init__.py
widgetastic_manageiq/expression_editor.py

Convert search.py to widgetastic
{{pytest: cfme/tests/infrastructure/test_advanced_search_providers.py cfme/tests/infrastructure/test_advanced_search_vms.py cfme/tests/infrastructure/test_advanced_search_host.py}}

[1LP][WIPTEST]Search to widgetastic

---

cfme/tests/cloud_infra_common/test_genealogy.py
cfme/tests/infrastructure/test_host.py

__Updating tests__ Replaced testgen with pytest.mark.provider.

[1LP][RFR] Removed testgen from infrastructure (part 5)

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

[1LP][RFR] Add BZ blocker for GCE

---

cfme/fixtures/tag.py

Fix tag_visibility_fixture
{{pytest: -v -k test_tagvis_cloud_object}}

[RFR]Fix tag visibility fixture

---

cfme/infrastructure/provider/__init__.py

{{pytest: cfme/tests/infrastructure/test_providers.py -k crud --use-provider vsphere65-nested }}

[1LP][RFR] Work around one UI issue with upset toolbars

---

cfme/control/explorer/alert_profiles.py
cfme/tests/control/test_basic.py

{{pytest: -v -k test_alert_profile_assigning --long-running}}

[1LP][RFR] Fix the locator in AlertProfilesEditAssignmentsView

---

cfme/automate/explorer/method.py
requirements/frozen.txt

{{pytest: -v -k "test_automate_ansible_playbook_method_type_crud or test_automate_ansible_playbook_method_type" --long-running}}

[RFR] Fixed tree_path in Automate/Method class

---

cfme/middleware/server.py
cfme/tests/middleware/server_methods.py
cfme/tests/middleware/test_middleware_domain_server.py

{{pytest: cfme/tests/middleware/test_middleware_domain_server.py -v --use-provider hawkular}}

[1LP][RFR] Fixed case sensitive check.

---

cfme/configure/configuration/server_settings.py

__Extending__ Server settings to accommodate changes in the WebMKS Console. Now in order to find WebMKS Console option on the server settings page, we need to download WebMKS SDK and extract it under /var/www/miq/vmdb/public/ in a new webmks directory. That enables the WebMKS Option in the UI. 
These features are currently in 5.9 only. Soon to be added in CFME 5.8 as well.
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere65-nested }}

[1LP][RFR] Updating Server Settings to get WebMKS SDK downloaded and extracted on Appliance

---

cfme/tests/ansible/test_embedded_ansible_actions.py

{{pytest: -v -k test_action_run_ansible_playbook --long-running}}

[1LP][RFR] Fixed test_action_run_ansible_playbook

---

cfme/cloud/provider/__init__.py

Infra is already in master (added by Milan yesterday), Cloud is in this PR

[RFR] Fix MoveTargetOutOfBoundsException in Cloud as well

---

cfme/services/catalogs/ansible_catalog_item.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k test_service_ansible_playbook_confirm --long-running}}

[RFR] Fixed test_service_ansible_playbook_confirm

---

cfme/base/__init__.py
cfme/base/rest.py
cfme/base/ui.py
cfme/tests/configure/test_zones.py
cfme/tests/infrastructure/test_datastore_analysis.py

* Keeping everything as commented out for now so it can be reverted
* Have the idea of a _fundamental_ that doesn't need to be picked
properly
Just in case we can't resolve the problem another way
**Shriver adding PRT**
{{ pytest: cfme/tests/configure/test_zones.py --long-running -v --use-provider default }}

[1LP][RFR] Reverting sentaku'd properties

---

cfme/common/host_views.py
cfme/tests/infrastructure/test_set_default_filter.py

{[pytest: cfme/tests/infrastructure/test_set_default_filter.py }}

[1LP][RFR] fix test_set_default_filter

---

cfme/automate/buttons.py
cfme/base/ui.py
cfme/cloud/keypairs.py
cfme/configure/access_control.py
cfme/configure/settings.py

__Updating tests__ to remove support of 5.7 version.
Removed unnecessary VersionPick from:
cfme/automate/buttons.py
cfme/base/ui.py
cfme/cloud/keypairs.py
cfme/configure/access_control.py
cfme/configure/settings.py

[1LP][RFR] Removed VersionPick for unsupported versions

---

cfme/containers/container.py
cfme/services/myservice/ssui.py
cfme/storage/manager.py
cfme/storage/volume.py

__Updating tests__ to remove support of 5.7 version.
Removed unnecessary VersionPick from:
cfme/containers/container.py
cfme/services/myservice/ssui.py
cfme/storage/manager.py
cfme/storage/volume.py

[1LP][RFR] Removed VersionPick for unsupported versions (part 2)

---

widgetastic_manageiq/__init__.py
widgetastic_manageiq/expression_editor.py

__Updating tests__ to remove support of 5.7 version.

[1LP][RFR] Removed VersionPick in widgetastic_manageiq for unsupported versions

---

cfme/control/explorer/alert_profiles.py
cfme/infrastructure/config_management.py
cfme/infrastructure/provider/__init__.py
cfme/infrastructure/provider/rhevm.py

__Updating tests__ to remove support of versions lower than 5.8.

[1LP][RFR] Remove version.pick (part 1)

---

cfme/services/catalogs/catalog.py
cfme/services/catalogs/catalog_item.py
cfme/tests/automate/test_service_dialog.py
cfme/tests/cli/test_evmserverd.py
cfme/tests/configure/test_display_settings.py

__Updating tests__ to remove support of versions lower than 5.8.

[1LP][RFR] Remove version.pick (part 2)

---

cfme/tests/intelligence/test_chargeback_assignments.py
cfme/tests/openstack/cloud/test_volumes.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/storage/test_volume_backup.py

__Updating tests__ to remove support of versions lower than 5.8.

[1LP][RFR] Remove version.pick (part 3)

---

cfme/containers/container.py
cfme/containers/provider/__init__.py
cfme/infrastructure/config_management.py
cfme/infrastructure/provider/__init__.py
cfme/rest/gen_data.py

__Updating tests__ to remove support of versions lower than 5.8.

[1LP][RFR] Removed current_version() for unsupported versions (part 1)

---

cfme/tests/storage/test_volume_backup.py
cfme/tests/webui/test_splitter.py
cfme/web_ui/flash.py
cfme/web_ui/form_buttons.py
cfme/web_ui/toolbar.py

__Updating tests__ to remove support of versions <5.8.
__Deleting tests__ if they are invalid for 5.8+ versions.

[RFR] Removed current_version() from tests (part 4)

---

cfme/tests/test_ui.py

[RFR] Basic page test

---

cfme/cloud/provider/__init__.py
cfme/containers/provider/__init__.py
cfme/infrastructure/provider/__init__.py
cfme/middleware/provider/__init__.py
cfme/networks/balancer.py
cfme/networks/cloud_network.py
cfme/networks/network_port.py
cfme/networks/network_router.py
cfme/networks/provider/__init__.py
cfme/networks/security_group.py
cfme/networks/subnet.py
cfme/physical/provider/__init__.py

[RFR] Remove page_name it is no longer used

---

cfme/tests/configure/test_register_appliance.py

Fixes to test_rh_updates to work with 5.9 packages and timeout extension to test_rh_register as it takes a longer period to register appliances.

[1LP][RFR] Fixes to broken automation

---

cfme/infrastructure/datastore.py
cfme/infrastructure/virtual_machines.py
cfme/services/dashboard/ssui.py
cfme/services/myservice/ssui.py
widgetastic_manageiq/__init__.py

__Updating tests__ to disable support of <5.8 versions.

[RFR] Removed outdated product_version() conditions

---

cfme/scripting/setup_env.py

Added default pool names to setup-env scripts and also the option to allow users to name there appliance pools for better management.

[1LP][RFR] Added pool description option to script

---

cfme/tests/infrastructure/test_individual_host_creds.py

__Wraping__ test_individual_test_creds test cases due to created BZ's.

[1LP][RFR] Adding BZ wrapper for test_individual_host_creds

---

cfme/tests/automate/test_buttons.py

{{pytest: -v cfme/tests/automate/test_buttons.py -k _on_host}}

[RFR] Fix test_button_on_host

---

cfme/test_framework/pytest_plugin.py
fixtures/sauce.py

Add a fixture which pumps the test name to sauce

[1LP][RFR] Sauce test name post

---

cfme/configure/configuration/server_settings.py
cfme/tests/configure/test_vmware_console_settings.py

[1LP][RFR] Some minor fixes

---

cfme/storage/manager.py
cfme/storage/volume.py

- fixed changes in `volume.py`
- removed VirsionPick complatly from `manager.py`
{{pytest: cfme/tests/openstack/cloud/test_volumes.py --use-provider rhos7-ga -v}}

[1LP][RFR] fix for changes in VirsionPick

---

cfme/configure/settings.py
cfme/tests/configure/test_timeprofile.py

Implementing fix related to timeprofile test case for 5.9.
{{pytest: cfme/tests/configure/test_timeprofile.py -v }}

[RFR]Implementing fix for timeprofile test cases.

---

cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/infrastructure/test_provisioning_dialog.py

[RFR] Removed more web_ui

---

cfme/base/rest.py
cfme/base/ssui.py
cfme/base/ui.py
cfme/generic_objects/definition/__init__.py
cfme/generic_objects/definition/rest.py
cfme/generic_objects/instance/__init__.py
cfme/generic_objects/instance/rest.py
cfme/modeling/base.py
cfme/services/dashboard/ssui.py
cfme/services/myservice/ssui.py
cfme/services/myservice/ui.py
cfme/services/service_catalogs/ssui.py
cfme/services/service_catalogs/ui.py
cfme/utils/appliance/__init__.py

* Move to using new style Sentaku registration
* Remove one existing old style import scan
* Import cleanups

[RFR] Remove a warning (YAY) and migrate to newstyle registration

---

cfme/automate/explorer/namespace.py
cfme/cloud/stack.py
cfme/common/vm_views.py
cfme/tests/cli/test_appliance_update.py
fixtures/ui_coverage.py

__Updating tests__ to disable support of versions lower than 5.8.

[RFR] Removed support for versions <5.8

---

sprout/appliances/templates/appliances/my_appliances.html

Thanks to @romanblanco for moral support and guidance.

[WIP][NOTEST][SPROUT] Sprout - Relief Firefox users from the partially hidden dropup

---

scripts/sync_template_tracker.py

GCE was collecting public images, we only want private
FIXES RHCFQE-6182

[RFR] Update sync_template_tracker, limit gce to private

---

cfme/storage/object_store_container.py
cfme/tests/storage/test_object_store_container.py

- Navigation failing due to JS API issue so changes `get_entity` method with normal row method.
- Changes in Tags 
- Removed Flash widget as it covers by `BaseEntityView` itself. 
{{pytest: cfme/tests/storage/test_object_store_container.py --use-provider rhos7-ga -v}}

[1LP][RFR] storage container: fix test

---

cfme/infrastructure/config_management.py
widgetastic_manageiq/__init__.py

{{pytest: --use-provider=ansible_tower_310 cfme/tests/infrastructure/test_config_management_rest.py}}
failed authentication tests should be fixed by #5657

[1LP][RFR] fixing config manager tests

---

cfme/base/__init__.py
cfme/infrastructure/config_management.py
cfme/infrastructure/datastore.py
cfme/infrastructure/networking.py
cfme/infrastructure/pxe.py
cfme/intelligence/chargeback/rates.py
cfme/intelligence/reports/reports.py
cfme/optimize/bottlenecks.py
cfme/optimize/utilization.py
cfme/tests/webui/test_splitter.py

A few more parametrization optimizations

 [1LP][RFR] Fixed a few more parametrizations

---

scripts/azure_cleanup.py

1)adding unused disk removal
2)updating cleanup output.
example of log we get
```
azure_cleanup.py, NICs, PIPs, Disks and Stack Cleanup
Date: 2017-12-08 10:34:06.268223
----- Provider: azure -----
Removing Nics with the name 'test':
| Name          |
|---------------|
| testsdfsdfsdf |
Removing Public IPs with the name 'test':
| Name          |
|---------------|
| testsdfsdfsdf |
Removing empty Stacks:
| Name   |
|--------|
Removing 'bootdiagnostics-test*' containers
| Name                 |
|----------------------|
| bootdiagnostics-test |
Removing unused blobs and disks
Managed disks:
| disk                                                          | resource_group   |
|---------------------------------------------------------------+------------------|
| …
```

[1LP][RFR] azure cleanup log updates

---

cfme/control/explorer/policies.py
cfme/middleware/provider/middleware_views.py
cfme/middleware/server.py
cfme/tests/middleware/server_methods.py
cfme/tests/middleware/test_middleware_server_compliance.py

{{pytest: cfme/tests/middleware/test_middleware_server_compliance.py -v --use-provider hawkular}}

[1LP][RFR] Added support of Compliances for Middleware Servers. Added new tests.

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

__Updating test__ test_datastores_summary. This is needed in case you have two providers and each one of them has datastore with the same name but different attributes. In the old way, datastores were compared if their name was matching. However if you had two datastores with the same name but e.g. different free space, it might have happened that they were compared incorrectly. 
This approach basically parses both outputs (from DB and from report) into the list with the same format and then compares if both lists are equal. 
If they are not, AssertionError from this is also quite readable and informative IMHO (see attached screenshot)
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_datastores_summary --use-provider rhv41 -vv}}

[1LP][RFR] Changing test_datastores_summary to account for multiple providers

---

cfme/services/service_catalogs/ui.py

28 tests.
The message had been fixed less than 2 weeks ago in #6022 and they've changed it again... The type still differs though.

[RFR] Change service order flash message again

---

cfme/infrastructure/config_management.py

[RFR] Removed old Table usage

---

cfme/utils/appliance/__init__.py

Removing some deprecated calls

[RFR] Removing some deprecated calls

---

cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py

Convert Virtual Machines to Widgetastic

[1LP][WIP] VM Widgetastic Conversion

---

cfme/cloud/security_groups.py
cfme/exceptions.py
cfme/tests/cloud/test_security_groups.py
setup.py

PRT run:
{{ pytest: cfme/tests/cloud/test_security_groups.py -v --long-running }}

[1LP][RFR] This PR contains Security_groups Modal_Page and test case for it.

---

cfme/automate/__init__.py
cfme/automate/dialog_collection_pick.py
cfme/automate/dialog_element.py
cfme/automate/dialogs/__init__.py
cfme/automate/dialogs/dialog_box.py
cfme/automate/dialogs/dialog_element.py
cfme/automate/dialogs/dialog_tab.py
cfme/automate/dialogs/service_dialogs.py
cfme/modeling/base.py
cfme/rest/gen_data.py
cfme/services/catalogs/catalog.py
cfme/services/catalogs/catalog_item.py
cfme/services/catalogs/orchestration_template.py
cfme/services/service_catalogs/ui.py
cfme/tests/automate/test_customization_paginator.py
cfme/tests/automate/test_service_dialog.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_dynamicdd_dialogelement.py
cfme/tests/services/test_generic_service_catalogs.py
cfme/tests/services/test_provision_stack.py
setup.py
widgetastic_manageiq/__init__.py

{{pytest: -v --long-running --use-provider vsphere cfme/tests/services/test_different_dialogs_in_catalogs.py}}

[1LP][RFR] New dialog editor automation

---

cfme/infrastructure/virtual_machines.py
cfme/services/catalogs/__init__.py
cfme/services/myservice/ui.py
cfme/services/workloads.py
cfme/tests/configure/test_default_views_infra.py

__Updating views__ to have them toolbar included.
__Updating tests__ to remove web_ui toolbars.

[RFR] Removed web_ui toolbars from test_default_views_infra

---

cfme/web_ui/__init__.py

[RFR] Remove old web_ui elements

---

cfme/infrastructure/virtual_machines.py

Fix up some issues highlighted in my previous PR, as well as completely remove references to web_ui in virtual_machines.py

[RFR] Fix up issues left over from VM conversion

---

cfme/tests/cloud/test_tenant_quota.py

New tenant quota test for cloud
{{ pytest: -vvvv cfme/tests/cloud/test_tenant_quota.py }}

[1LP][RFR] New tenant quota tests for cloud

---

cfme/tests/infrastructure/test_quota_tagging.py

Change in the name of the test

[RFR] test name change

---

requirements/frozen.txt
requirements/template_docs.txt

Want to use this for RBAC AttrDict diff.
#5755 Is the PR using it, figured I would pull the new requirement into separate request.

[1LP][RFR] Add deepdiff 3.3.0

---

cfme/cloud/instance/__init__.py
cfme/tests/configure/test_default_views_cloud.py
cfme/tests/configure/test_default_views_infra.py

__Updating views__ to have them toolbar included.
__Updating tests__ to remove web_ui toolbars.

[RFR] Removed web_ui toolbar from test_default_views_cloud

---

cfme/automate/dialogs/service_dialogs.py
cfme/tests/automate/test_customization_paginator.py

[RFR] Removed some Table use

---

cfme/intelligence/reports/__init__.py
cfme/intelligence/reports/menus.py
cfme/intelligence/reports/reports.py
cfme/tests/intelligence/reports/test_menus.py

{{pytest: -v -k 'report or test_shuffle_top_level'}}
PRT results
There are some failures in both 58 and 59 that are not related to the code changes made through this PR.

[1LP][RFR] Add version pick for accordion item title in Reports tree

---

cfme/infrastructure/virtual_machines.py

[RFR] HOTFIX added missing import CompareToolBarActionsView

---

cfme/common/provider_views.py
cfme/infrastructure/provider/__init__.py
cfme/tests/openstack/infrastructure/test_relationships.py

{{pytest: --use-provider=rhos11 cfme/tests/openstack/infrastructure/test_relationships.py}}

[RFR] removed web_ui from test_relationships

---

cfme/fixtures/pytest_selenium.py
cfme/web_ui/__init__.py

[RFR] Remove some more old elements

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_tenant_quota.py

New quota test for VM reconfigure
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py -vvv -k test_tenant_quota_vm_reconfigure }}

[1LP][RFR] New quota test for vm reconfigure

---

cfme/common/vm_views.py
cfme/infrastructure/config_management.py
cfme/infrastructure/pxe.py
cfme/infrastructure/virtual_machines.py
cfme/intelligence/reports/reports.py
cfme/intelligence/reports/widgets/__init__.py
cfme/services/myservice/ui.py

{{pytest: -v -k 'reportl'}}
There is a change in the Refresh button title in 5.9.0.13.This PR addresses that change.

[1LP][RFR] Address Refresh button title change

---

cfme/services/requests.py

{{ pytest: -vvv cfme/tests/infrastructure/test_quota_tagging.py }}

[1LP][RFR] Fix NoSuchElementFound for reload button

---

cfme/common/host_views.py
cfme/tests/infrastructure/test_host_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_instance_analysis.py

Removed web_ui elements for ssa tests. 
{{pytest: -k 'test_run_host_analysis or test_drift_analysis' --long-running --use-provider complete}}
PRT run can fail as currently I'm working on SSA tests fixes and refactoring https://github.com/ManageIQ/integration_tests/pull/6131

[RFR]Remove web_ui elements from ssa tests

---

cfme/utils/update.py

[RFR] Remove old fill

---

cfme/tests/infrastructure/test_quota_tagging.py

{{ pytest: -vvv cfme/tests/infrastructure/test_quota_tagging.py }}

[1LP][RFR] New quota tagging tests for Users and VMWare provider

---

cfme/cloud/instance/__init__.py
cfme/cloud/instance/image.py
cfme/common/provider_views.py
cfme/common/vm_views.py
cfme/configure/tasks.py
cfme/infrastructure/config_management.py
cfme/infrastructure/pxe.py
cfme/infrastructure/virtual_machines.py
cfme/services/myservice/ui.py
cfme/services/requests.py
cfme/storage/manager.py
cfme/web_ui/toolbar.py

reload button title was changed in latest 5.9.

[1LP][RFR] update reload buttons 

---

cfme/common/vm.py
cfme/tests/infrastructure/test_vm_power_control.py
requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

{{pytest: --long-running cfme/tests/infrastructure/test_vm_power_control.py}}

[RFR] removed toolbar from test_vm_power_control

---

cfme/automate/buttons.py
cfme/tests/automate/test_common_methods.py

__Updating tests__ for removing usage of cfme/web_ui.

[RFR] Removed toolbar from test_common_methods

---

markers/env_markers/provider.py

Fixed selector ONE
{{pytest: --collect-only --use-provider gce_central}}

[RFR] Fixed selector ONE

---

cfme/tests/automate/test_vmware_methods.py

{{pytest: --long-running cfme/tests/automate/test_vmware_methods.py}}

[RFR] removed toolbar from test_vmware_methods

---

cfme/exceptions.py

[RFR] Removed some exceptions

---

docs/guides/dev_guide.rst

[RFR] Removed some docs

---

cfme/tests/cloud_infra_common/test_rest_providers.py
cfme/utils/rest.py

* prevent possible race condition when task can be accessed before it's created
* don't check response when affected by https://bugzilla.redhat.com/show_bug.cgi?id=1525498
* remove unneeded workaround for BZ1501941
{{pytest: -v -k test_provider_delete_ cfme/tests/cloud_infra_common/test_rest_providers.py --use-provider complete}}
PRT: failing on upstream because it's also affected by BZ1525498 and it's not blocked yet (no cfme-future flag and 6.0 flag yet)

[1LP][RFR] fix provider delete tests using REST

---

cfme/fixtures/pxe.py
cfme/infrastructure/pxe.py
cfme/test_framework/pytest_plugin.py
cfme/tests/cloud/test_cloud_init_provisioning.py
cfme/tests/infrastructure/test_cloud_init_provisioning.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/infrastructure/test_iso_provisioning.py
cfme/tests/infrastructure/test_pxe_provisioning.py
cfme/tests/services/test_iso_service_catalogs.py
cfme/tests/services/test_pxe_service_catalogs.py
cfme/utils/testgen.py

as it turns out the objects added/obtained in the parameter-set where easily added as a fixture

[1LP][RFR] fix pxe collection by using fixtures

---

cfme/tests/optimize/test_bottlenecks.py
cfme/utils/appliance/__init__.py

{{pytest: cfme/tests/optimize/test_bottlenecks.py }}

[1LP][RFR] Fix bottleneck tests

---

cfme/configure/settings.py
cfme/tests/configure/test_display_settings.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

Writing fixture for Visual object for collection conversion of Time Profile. This PR is required to get PR: https://github.com/ManageIQ/integration_tests/pull/6095 merged.
{{pytest: -v -k 'test_cloud_start_page or test_cloud_grid_page_per_item or test_cloud_tile_page_per_item or test_cloud_list_page_per_item or test_infra_grid_page_per_item or test_infra_tile_page_per_item or test_infra_list_page_per_item or test_infra_report_page_per_item or test_infra_start_page or test_timezone_setting'}}

[1LP][RFR] Writing fixture for collection conversion

---

cfme/configure/access_control.py
cfme/tests/configure/test_access_control.py

{{ pytest: -v cfme/tests/configure/test_access_control.py -k tenant }}

[1LP][RFR] Fixed failing tests due to string change and views

---

cfme/test_framework/appliance_police.py
cfme/utils/appliance/__init__.py
cfme/utils/appliance/db.py
cfme/utils/ssh.py

one of known issues:  evmserverd cannot be started/stopped, etc.

[1LP][RFR] fixes for podified appliance

---

cfme/common/provider.py
cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/tests/test_rest.py

{{pytest: -k 'test_find_created_events' cfme/tests/test_rest.py}}

[1LP][RFR] smoke tests for api's event_streams collection

---

cfme/storage/object_store_object.py
cfme/tests/storage/test_object_store_object.py

- Fixed navigation: attribute change 'key';
- improve all method with filter
- added provider attribute; i wast go with standard; If create method came we need provider as attri
- new changes in tag
{{pytest: cfme/tests/storage/test_object_store_object.py --use-provider rhos7-ga -v}}

[1LP][RFR] Object: fix nav; changed tag method

---

cfme/fixtures/configure_auth_mode.py
cfme/roles.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py

Related to #5754, and includes a hack to work around it.
There will be test failures in PRT, I'm expecting them and am engaging with dev. I will either write many specific RBAC bugs, or start to lump some of the permission mismatches into 2 BZ's that were written while writing these tests.
PRT failures in run 19290 will all be BZ's.

[1LP][RFR] Update auth fixtures, views, widgets, and tests

---

cfme/infrastructure/cluster.py

Cluster set comparison was comparing wrong object types str + Cluster

[1LP][RFR] Cluster set comparison was comparing wrong object types str + Cluster

---

cfme/common/vm.py

* Was part of the WT conversion

[1LP][RFR] .pick() is not needed as descriptor resolves it

---

cfme/tests/infrastructure/test_advanced_search_vms.py

Fix for exception which was no available

[1LP][RFR] Fix for exception which was no available

---

cfme/tests/networks/test_sdn_downloads.py

* Converted into using collections and not get which no longer exists
* Beautified imports

[RFR] Fixed test and beautify imports

---

cfme/common/vm.py

Purpose
`get_detail` method of `BaseVM` class accepts list or tuple.
{{pytest: -v -k test_action_check_compliance --use-provider vsphere6-nested --long-running}}

[1LP][RFR] Fixed vm compliance_status property

---

cfme/infrastructure/datastore.py

{{pytest: --long-running cfme/tests/infrastructure/test_datastore_analysis.py}}
The intention of this PR is to fix one introduced error.
PRT tests fail after that fix and failures aren't related to fix.

[1LP][RFR] Fix datastore analysis tests 

---

cfme/infrastructure/virtual_machines.py
cfme/networks/cloud_network.py

Destination not Found + other fix

[RFR] Destination not Found + other fix

---

cfme/utils/appliance/implementations/ui.py

Though I noticed that people use it in various places :(

[RFR] Do not flush - workaround

---

cfme/infrastructure/virtual_machines.py

fix bug in is_displayed
Fixing a bug in vm view is displayed. it was returning false. So navigating through all vms was taking more time. Bug was noticed in the #5701 .This PR can be tested once #5701 will be merged

[RFR] fix bug in is_displayed

---

cfme/fixtures/configure_auth_mode.py
cfme/roles.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py

[1LP][RFR] Block AWS RBAC tests on BZs

---

README.md

[RFR] Added PR Process link

---

cfme/tests/networks/test_sdn_downloads.py

[RFR] Fixed SDN test

---

cfme/cloud/tenant.py

Fixes failing tenant crud tests
{{ pytest: -vvvv cfme/tests/cloud/test_tenant.py }}

[RFR] Fixed failing tenant_crud tests

---

cfme/infrastructure/cluster.py

[RFR] Fixed a bad arg

---

cfme/cloud/stack.py
cfme/infrastructure/cluster.py

{{pytest: -v --use-template-cache 'cfme/tests/infrastructure/test_delete_infra_object.py' cfme/tests/cloud/test_stack.py --long-running -k 'delete_cluster_from_table or collection_delete' --use-provider complete}}

[RFR] Cluster & Stack collection .delete(): No longer trigger unhashable error

---

cfme/metaplugins/blockers.py
cfme/tests/distributed/test_appliance_replication.py
cfme/utils/appliance/__init__.py
cfme/utils/ssh.py
cfme/utils/version.py

remove various uses of the contextual version.current_version

[RFR] remove various uses of the contextual version.current_version

---

cfme/common/__init__.py
cfme/common/provider.py
cfme/common/vm.py
cfme/common/vm_views.py
cfme/middleware/provider/__init__.py
cfme/tests/automate/test_vmware_methods.py
cfme/tests/cloud_infra_common/test_retirement.py

Cleanup SummaryMixin usage as we have SummaryTable widget for replace
{{pytest:  -vvv -k  test_retirement_now_ec2_instance_backed --long-running }}

[RFR]SummaryMixin cleanup

---

cfme/tests/cli/test_appliance_update.py

* This was generating an Exception type log message when it shouldn't.
This is not an ERROR scenario, it is entirely expected and should just
be logged.

[1LP][RFR] Fixed annoying exception

---

cfme/infrastructure/pxe.py
cfme/tests/infrastructure/test_customization_template.py
cfme/tests/infrastructure/test_system_image_type.py

Implementing changes related to copy method and multiple delete in pxe main page.
{{pytest: -v -k 'test_system_image_type_selective_delete or test_customization_template_copy or test_system_image_type_delete_validation or test_customization_template_copy_validation'}}

[1LP][RFR]Improving test coverage in PXE page

---

cfme/tests/configure/test_tag.py
markers/uncollect.py

[1LP][RFR] initial support for accessing appliance in uncollect

---

scripts/dockerbot/check_prs.py

[1LP][RFR] Fix PRT to support more than 100 PRS

---

cfme/storage/volume_backup.py

Fixes a sporadic error that was caused by returninng None. Handling of two possible error states.
{{pytest: -v cfme/tests/storage/test_volume_backup.py --long-running --use-provider rhos11 }}

[1LP][RFR] Fix VolumeBackupCollection.all: Only return list, better error handling

---

scripts/dockerbot/pytestbase/setup.sh

[RFR] Fix PRT appliance usage

---

cfme/cloud/stack.py
cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py
cfme/infrastructure/host.py
cfme/infrastructure/pxe.py

{{ pytest: cfme/tests/infrastructure/test_esx_direct_host.py cfme/tests/infrastructure/test_iso_datastore.py cfme/tests/infrastructure/test_delete_infra_object.py -v --long-running }}

[1LP][RFR] "DropdownItemNotFound" issue fix.

---

cfme/tests/integration/test_cfme_auth.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py

Fixed a few Candidate Not Found tests

[1LP][RFR] Fixed a few Candidate Not Found tests

---

cfme/base/__init__.py

[RFR] Fix Zone

---

scripts/dockerbot/pytestbase/setup.sh

we git pre holiday trouble with the gating so we disable the failing part until the new year

[RFR] dockerbot image - make rhev smoke test gating a opt in

---

cfme/common/provider.py
requirements/frozen.txt
scripts/azure_cleanup.py

Script should now remove pips, nics from all subscriptions and resource groups.
slightly changed logging mechanizm.
requires ManageIQ/wrapanapi/202

[RFR] make azure clean up script remove stale resources from any subscription and any resource groups

---

cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_timelines.py
widgetastic_manageiq/__init__.py

__Updating tests__ Adding more events to the test timeline
‎ {{pytest: -v -k "test_timeline_events" --use-provider=vsphere6-nested}}

[1LP][RFR]  Adding more events to the test timeline

---

cfme/tests/control/test_actions.py
widgetastic_manageiq/expression_editor.py

Purpose
__Fixing__ expression editor. Due to the issue editing an entity's scope was always failed. It affected test_action_canel clone.
{{pytest: -v -k test_action_cancel_clone --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Fixed expression editor

---

cfme/cloud/provider/ec2.py
cfme/tests/cloud/test_providers.py

{{pytest: cfme/tests/cloud/test_providers.py}}

[1LP][RFR] submitted a BZ and added new tab for ec2 provider

---

cfme/tests/test_rest.py

{{pytest: -v cfme/tests/test_rest.py -k test_sorting_by_attributes}}

[1LP][RFR] Fixed test_sorting_by_attributes issue    

---

cfme/tests/automate/test_customization_paginator.py

__Fixing test_paginator__ because it is currently counting wrong total number of items.
{{pytest: cfme/tests/automate/test_customization_paginator.py}}

[RFR] Fixed test_paginator

---

cfme/control/explorer/alerts.py
cfme/tests/control/test_alerts.py

Supersedes #6270
{{pytest: -v -k test_alert_vm_turned_on_more_than_twice_in_past_15_minutes --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Fixed test_alert_vm_turned_on_more_than_twice_in_past_15_minutes

---

cfme/automate/service_dialogs.py
cfme/tests/automate/test_customization_paginator.py
widgetastic_manageiq/__init__.py

__Fixing__ automate.DialogsView because it is currently don't have table.
{{pytest: cfme/tests/automate/test_customization_paginator.py}}

[RFR] Added table to automate.DialogsView

---

cfme/infrastructure/host.py

{{pytest: --long-running --use-provider=vsphere65-nested cfme/tests/control/test_actions.py -k test_action_prevent_ssa }}
~ 16 tests should be fixed

[1LP][RFR] fixes many tests failing with KeyError->creds error

---

cfme/utils/tests/test_simple_locators.py

{{pytest: cfme/utils/tests/test_simple_locators.py}}

[RFR]Update html path for test_simple_locators.py

---

cfme/containers/container.py

In 5.8.3, the id field to reference the pods table is "container_definition_id" compared to  of "container_group_id" in 5.9. This addresses the difference between the two versions.
Note: Testing was done with the rest of the Container Objects in 5.8.3 and no problems were found.
Manual Testing Results:
5.8.3:
```
In [1]: juwatts
Out[1]: <cfme.containers.provider.openshift.OpenshiftProvider name='CM JUWATTS', key='cm-juwatts', zone='default', metrics_type='Hawkular', alerts_type='Disabled'>
In [2]: coll_containers = appliance.collections.containers
In [3]: coll_containers
Out[3]: ContainerCollection(filters={})
In [4]: coll_containers.all()
Out[4]: 
[Container(name=u'registry', pod=u'docker-registry-1-gjjgs', provider=<cfme.containers.provider.openshift.OpenshiftProvider name='CM JUWATTS', …
```

[1LP][RFR] containers.container.ContainerCollection.all(): Add support for 5.8.3

---

cfme/infrastructure/cluster.py
cfme/tests/infrastructure/test_cluster_analysis.py

{{pytest: -k test_run_cluster_analysis -vvv --use-provider complete --long-running}}

[1LP][RFR] cluster_ssa update/fix

---

cfme/cloud/keypairs.py
cfme/tests/cloud/test_keypairs.py
widgetastic_manageiq/__init__.py

{{pytest: cfme/tests/cloud/test_keypairs.py}}

[1LP][RFR] fixed fixture lookup issue

---

cfme/common/host_views.py
cfme/tests/infrastructure/test_set_default_filter.py

{{pytest: -v cfme/tests/infrastructure/test_set_default_filter.py -k test_set_default_host_filter}}
**Description:** 
list[0] = ALL
list[-2] = 'Status / Running (Default)
**Screenshot:**

[1LP][RFR] Fixed failing test_set_default_host_filter issue

---

cfme/containers/container.py
cfme/containers/image.py
cfme/containers/image_registry.py
cfme/containers/node.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/provider/__init__.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/template.py
cfme/containers/volume.py
cfme/fixtures/has_persistent_volume.py
cfme/tests/containers/test_breadcrumbs.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_logging.py
cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
cfme/tests/containers/test_properties.py
cfme/tests/containers/test_relationships.py
cfme/tests/containers/test_smart_management.py
cfme/tests/containers/test_start_page.py
cfme/tests/containers/test_tables_fields.py
cfme/tests/containers/test_tables_sort.py

{{ pytest: cfme/tests/containers/test_relationships.py --use-provider cm-env2 }}
Adjust tests for collections conversions and few additional fixes

[1LP][RFR] Tests fixes / match to collections

---

cfme/configure/documentation.py
cfme/tests/configure/test_docs.py

{{pytest: cfme/tests/configure/test_docs.py}}

[1LP][RFR] docs tests fix

---

requirements/frozen.txt
scripts/azure_cleanup.py

Switch to updating subscription_id after creating AzureSystem object
Requires wrapanapi https://github.com/ManageIQ/wrapanapi/pull/205
I want to update the wrapanapi version in requirements.txt within this PR once wrapanapi #205 is merged/released

Fix azure_cleanup, remove get_crud use

---

cfme/services/myservice/ui.py

Purpose
Fixed locator and added VersionPick in ServiceRetirementForm
{{pytest: -v cfme/tests/services/test_myservice.py -k test_retire_service_on_date[vsphere65-nested-ViaUI]}}

[1LP][RFR] Fixed locator and added VersionPick for ServiceRetirementForm

---

cfme/infrastructure/virtual_machines.py

Picked up a couple of small issues that caused some of the snapshot and genealogy tests to fail.

[1LP][RFR] Fix up some outstanding issues after the VM merge

---

cfme/networks/provider/__init__.py
cfme/tests/networks/test_sdn_balancers.py
cfme/tests/networks/test_sdn_crud.py

{{pytest: cfme/tests/networks/test_sdn_crud.py cfme/tests/networks/test_sdn_balancers.py}}

[1LP][RFR] fixing network provider tests

---

cfme/tests/containers/test_tables_fields.py
cfme/tests/containers/test_tables_sort.py

Fix for container objects tests

[1LP][RFR] Fix for container objects tests

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

[RFR] Simple fix for UnboundError

---

cfme/intelligence/reports/reports.py

Reports generation doesn't update the tree (possibly a CFME issue to raise)

[1LP][RFR] Fix report tests

---

widgetastic_manageiq/__init__.py

There are cases when we need to do something with several entities. Usually, it is just entity.check() operation. This PR should add such function

[1LP][RFR] map function for entities

---

docs/guides/faq.rst

__Extending__ FAQ section of docs about pdb (requested by @quarckster) and -rs param for pytest.

[1LP][RFR] Some more FAQ

---

cfme/configure/tasks.py
cfme/infrastructure/datastore.py
cfme/tests/infrastructure/test_datastore_analysis.py

{{pytest: -k test_run_datastore_analysis -vvv --long-running --use-provider complete}}

[1LP][RFR]Fix/update ssa_datastores

---

cfme/control/import_export.py
cfme/tests/cloud/test_tenant_quota.py
cfme/tests/infrastructure/test_quota_tagging.py

{{pytest: -vvv -k 'test_tenant_quota_enforce_via_lifecycle or test_quota_tagging or test_import_policies or test_control_import_invalid_yaml_file' --long-running --use-provider complete}}

[1LP][RFR] Some fixes for WebdriverException

---

cfme/containers/container.py
cfme/containers/image_registry.py
cfme/containers/node.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/volume.py
cfme/tests/containers/test_breadcrumbs.py

{{ pytest: cfme/tests/containers/test_breadcrumbs.py --use-provider ocp-v1 }}
- Fixed navigations in containers 
- Added blocker - https://bugzilla.redhat.com/show_bug.cgi?id=1530610

[1LP][RFR] Fixed navigations in containers

---

cfme/common/provider.py

[RFR] Setup via REST if possible

---

cfme/services/catalogs/catalog_item.py
cfme/tests/services/test_catalog_item.py
widgetastic_manageiq/__init__.py

{{pytest: -k 'test_add_button or test_filter_save_and_load' --use-provider complete}}

[1LP][RFR] Fix some views elements

---

cfme/services/catalogs/catalog_item.py

{{pytest: -k 'test_add_button'}}

[RFR]Move button name into class

---

requirements/frozen.txt
requirements/frozen_docs.txt

Update wt.core to 0.19

---

cfme/common/provider.py
cfme/exceptions.py
cfme/infrastructure/provider/__init__.py
cfme/tests/infrastructure/test_cloud_init_provisioning.py
cfme/tests/infrastructure/test_individual_host_creds.py
cfme/tests/infrastructure/test_instance_analysis.py
cfme/tests/intelligence/test_chargeback_assignments.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/cloud/test_networks.py
cfme/tests/openstack/infrastructure/test_host_lifecycle.py
cfme/tests/openstack/infrastructure/test_provider.py
cfme/tests/services/test_operations.py
cfme/utils/ocp_cli.py

Remove provider.get_mgmt_system and provider.get_yaml_data
Replace usage with provider.mgmt and provider.data

[1LP][RFR] Remove provider.get_mgmt_system and provider.get_yaml_data

---

cfme/common/vm.py

Fot the most of the cases vms, templates where missing on provider side, also add small fixes where is needed
{{pytest: -vvv -k 'test_delete_image_appear_after_refresh' --use-provider complete}}

[RFR] Fix dropdown option for 5.9

---

cfme/intelligence/reports/dashboards.py
cfme/tests/intelligence/reports/test_widgets.py

{{pytest: -v -k test_widgets_on_dashboard}}

[1LP][RFR] Fixed test_widgets_on_dashboard

---

cfme/networks/network_router.py
cfme/networks/subnet.py
cfme/tests/networks/test_sdn_downloads.py

{{pytest: --use-provider=azure cfme/tests/networks/test_sdn_downloads.py}}

[1LP][RFR] fixed network collections

---

cfme/control/explorer/policies.py

{{pytest: -v -k test_assign_two_random_events_to_control_policy --long-running}}

[1LP][RFR] Fixed broken string comparison in EditPolicyEventAssignments view

---

fixtures/browser.py

[1LP][RFR] Enhance Traceback

---

cfme/tests/webui/test_splitter.py

* elements is not available, but element is, so we are just checking
existence which makes this OK

[1LP][RFR] Fix splitter test

---

cfme/tests/services/test_catalog_item.py

Purpose
Updated BZ id for test_catalog_item_duplicate_name
{{pytest: -v cfme/tests/services/test_catalog_item.py -k test_catalog_item_duplicate_name}}

[RFR]Updated BZ id for test_catalog_item_duplicate_name

---

cfme/cloud/keypairs.py
cfme/infrastructure/provider/__init__.py

Workaround for navigation to avoid MoveTargetOutOfBoundsException
{{pytest: -k 'test_add_cancelled_validation or test_hostname_max_character_validation or test_host_name_max_character_validation or test_empty_discovery_form_validation or test_keypair_add_and_remove_tag' -vvv --long-running --use-provider complete --use-template-cache}}

[1LP][RFR]Workaround for MoveTargetOutOfBoundsException

---

cfme/infrastructure/host.py
cfme/tests/infrastructure/test_host_analysis.py

Update SSA host test
{{pytest: -k test_run_host_analysis -vvv --long-running --use-provider complete}}

[1LP][RFR] SSA host update

---

requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

Blocking CM QE PRs:
https://github.com/ManageIQ/integration_tests/pull/6332
https://github.com/ManageIQ/integration_tests/pull/6316
https://github.com/ManageIQ/integration_tests/pull/6301

Update wt.core, 0.20.0

---

fixtures/log.py

* During dev, a line was misintroduced, it should have been the one
here.

[RFR] Fixing bug in manage_provider skipper

---

cfme/automate/dialog_element.py
cfme/automate/dialogs/dialog_element.py
cfme/tests/automate/test_service_dialog.py

For duplicate dialog test ,error is expected .
SO removed assert_no_error.

[1LP][RFR] Added assertionError in crud method

---

cfme/infrastructure/datastore.py

{{ pytest: cfme/tests/infrastructure/test_delete_infra_object.py -k test_delete_datastore_appear_after_refresh --long-running --use-provider vsphere55 }}

Update datastore.delete_all_attached_vms text

---

cfme/tests/infrastructure/test_config_management.py
cfme/tests/services/test_config_provider_servicecatalogs.py

[1LP][RFR] Add blocker mark (unable to remove config manager)

---

cfme/control/explorer/policies.py

{{pytest: -v -k test_assign_condition_to_control_policy --long-running}}

[1LP][RFR] Workaround for conditions assignment to policies

---

cfme/fixtures/has_persistent_volume.py
cfme/tests/containers/test_relationships.py

{{ pytest: cfme/tests/containers/test_relationships.py --use-provider ocp-v1 }}
- Fix test_relationships
- Fix has_persistent_volume fixture to create PV only if such doesn't exist

[1LP][RFR] Fix test_relationships

---

cfme/base/ui.py
cfme/configure/settings.py
cfme/tests/configure/test_server_name.py
cfme/tests/configure/test_session_timeout.py

[1LP][RFR] A few fixes for Sauce run

---

cfme/tests/containers/test_logging.py

{{ pytest: cfme/tests/containers/test_logging.py --use-provider cm-env2 }}
Fix test_logging

[1LP][RFR] Fix test_logging

---

widgetastic_manageiq/vm_reconfigure.py

{{ pytest: -vvv cfme/tests/infrastructure/test_vm_reconfigure.py -k test_vm_reconfig_add_remove_disk_cold --long-running }}

[1LP][RFR] fixing failing tests due to name change

---

cfme/tests/configure/test_register_appliance.py

Required wait before running register.

[1LP][RFR] Fix to rhsm/sat6 registration to overcome bug issue

---

cfme/infrastructure/virtual_machines.py

__Fixing__ current snapshot getter because it is currently can get only first Active snapshot.
{{pytest: --long-running -v cfme/tests/control/test_actions.py::test_action_create_snapshots_and_delete_them}}

[1LP][RFR] Fixed test_action_create_snapshots_and_delete_them

---

cfme/tests/cloud/test_tenant_quota.py

Making names unique for Polarion

[1LP][RFR] Changing name for Polarion

---

artifactor/plugins/reporter.py
cfme/configure/settings.py
cfme/tests/configure/test_timeprofile.py
fixtures/artifactor_plugin.py

* In a previous PR the All view was introduced but some sync up with the
views wasn't done. This PR resolves that.
{{pytest: -k test_hours_required_error_validation}}

[RFR] Fixed TimeProfile

---

cfme/common/host_views.py
cfme/infrastructure/host.py
cfme/tests/infrastructure/test_host_drift_analysis.py

{{pytest: -k test_host_drift_analysis -vvv --long-running --use-provider complete}}
Drift views is updated in https://github.com/ManageIQ/integration_tests/pull/6131

[1LP][RFR] Fix for host_drift_analysis

---

cfme/utils/tests/test_simple_locators.py

{{pytest: cfme/utils/tests/test_simple_locators.py}}

[1LP][RFR] fix test_simple_locators.py

---

cfme/tests/containers/test_search_bar.py

{{ pytest: cfme/tests/containers/test_search_bar.py -m 'not long_running_env' --use-provider ocp-v1 }}

[1LP][RFR] Fix test_search_bar (collections)

---

cfme/tests/containers/test_table_views.py

{{ pytest: cfme/tests/containers/test_table_views.py --use-provider ocp-v1 }}
Fix test_table_views.py (collections)

[1LP][RFR] Fix test_table_views.py (collections)

---

cfme/common/provider_views.py
cfme/tests/containers/test_tables_fields.py

{{ pytest: cfme/tests/containers/test_tables_fields.py --use-provider ocp-v1 }}
- Fix test_tables_fields
- Fix ContainerProvidersView.table (wrong locator)

[1LP][RFR] Fix test_tables_fields

---

cfme/utils/testgen.py

testgen.fixture_filter wants an argvalues to be a list of lists

[1LP][RFR]minor fix for pxe server crud

---

cfme/tests/cli/test_appliance_cli.py
cfme/tests/cli/test_appliance_console.py

Name changing to all appliance_console tests to match FA naming.

[1LP][RFR] Refactoring name changes to appliance_console tests

---

cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py

`Shriver`: PRT failures unrelated to this change.

[1LP][RFR] fix vm migrate views and put them in the shared space for those views

---

cfme/tests/infrastructure/test_timelines.py

Add missing test and make the needed refactoring to include it
While making the previous refactoring of this module #5701, I forgot to include the test_diagnostic_timeline, which should have been here. Some modification were required in order to include this test. If possible this PR should be merged before #6149
{{pytest: -v -q cfme/tests/infrastructure/test_timelines.py --use-provider=vsphere6-nested}}

[1LP][RFR] add missing test and needed refactoring for this purpose

---

cfme/tests/automate/test_buttons.py
cfme/tests/automate/test_class.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_instance.py
cfme/tests/automate/test_method.py
cfme/tests/automate/test_namespace.py
cfme/tests/automate/test_provisioning_dialogs.py
cfme/tests/automate/test_service_dialog.py
cfme/tests/configure/test_access_control.py
cfme/tests/configure/test_analysis_profiles.py
cfme/tests/configure/test_tag.py
cfme/tests/control/test_basic.py
cfme/tests/generic_objects/test_definitions.py
cfme/tests/generic_objects/test_instances.py
cfme/tests/infrastructure/test_customization_template.py
cfme/tests/infrastructure/test_system_image_type.py
cfme/tests/intelligence/reports/test_crud.py

New tests for sauce/ui testing

[RFR] Added some new sauce tests

---

cfme/tests/ansible/test_embedded_ansible_actions.py

Splitted parametrized test_action_run_ansible_playbook into several tests due to broken module fixture scope for parametrized test.
{{pytest: -q cfme/tests/ansible/test_embedded_ansible_actions.py -v --long-running}}

[1LP][RFR] Fixed test_embedded_ansible_actions.py

---

cfme/tests/control/test_alerts.py

{{pytest: -v -k test_alert_snmp --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Fixed test_alert_snmp

---

requirements/frozen.txt

Update dump2polarion to the latest version

[1LP][RFR] update dump2polarion version
