scripts/cleanup_old_vms.py
PR4800 still had a mgmtsystem import, module name changed to wrapanapi.
=> [RFR] Fix cleanup_old_vms, wrapanapi import

cfme/tests/containers/test_ssl_providers.py
TestItem object introduced a PyTest error in Jenkins:
test_ssl_providers.py cannot collect test class 'TestItem' because it has a __new__ constructor
This should fix it
{{pytest: cfme/tests/containers/test_ssl_providers.py -v --use-provider cm-env2 }}
=> [RFR]TestItem changed to checked_item due to pytest warnings

cfme/containers/provider/openshift.py
{{pytest: cfme/tests/containers/test_relationships.py -v --use-provider cm-env2 }}
We'd like a Hawkular endpoint added with every Openshift Containers Provider we add for the tests
=> [RFR][1LP] Added a mandatory Hawkular provider

cfme/tests/containers/test_reports.py
{{pytest: cfme/tests/containers/test_reports.py -v --use-provider cm-env1 -m 'long_running_env'}}
Added reports tests:
- test_report_pod_counts_for_container_images_by_project
- test_report_recently_discovered_pods
- test_report_number_of_images_per_node
- test_report_projects_by_number_of_containers
Note: This tests are designed for long running ENV only but should also pass in short one.
=> [RFR] Added reports tests

cfme/scripting/quickstart.py
As Fedora 26 has no zeromq3-devel package, `python -m cfme.scripting.quickstart` command from getting started guide will fail.
So I've added REDHAT_PACKAGES_F26 variable with valid packages set.
Cheers.
=> [1LP][RFR] Support for F26 devenv.

cfme/tests/test_rest.py
* the DELETE method is not working and won't be fixed (see BZ 1410504), removing corresponding test
* uncollect on > 5.8 as the arbitration_rules collection is no longer present there
{{pytest: -v -k TestArbitrationRulesRESTAPI}}
=> [RFR] uncollect the arbitration_rules tests on > 5.8

cfme/tests/control/test_rest_control.py
The BZ 1435773 is now in POST as it's fixed in upstream, the target is 5.9+. It's no longer blocker on 5.8. It won't be fixed in 5.8 so it doesn't make sense to test is there.
{{pytest: -v -k test_delete_policies_from_detail_delete}}
PRT
-----
The failure on upstream is fixed by https://github.com/ManageIQ/integration_tests/pull/4882
=> [1LP][RFR] uncollect delete_policies_from_detail_delete on < 5.9

cfme/tests/test_rest.py
The BZ 1420872 should be blocker on 5.8 as well.
{{pytest: -v -k test_delete_notifications_from_detail}}
=> [1LP][RFR] test_delete_notifications_from_detail - add 5.8 to forced_streams for BZ1420872

utils/bz.py
This fixes BZ blockers on upstream. It's failing with
```
>       raise AttributeError(msg)
E       AttributeError: Bug object has no attribute 'can_test_on_upstream'.
E       If 'can_test_on_upstream' is a bugzilla attribute, it may not have been cached when the bug was fetched. You may want to adjust your include_fields for getbug/query.
```
It's caused by API change - ``Bug.get_history()`` is now ``Bug.get_history_raw()`` - see e.g. http://blog.wikichoon.com/2016/06/python-bugzilla-api-changes-in-git.html
This one was tricky to find, ``Bug.get_history()`` is called in ``can_test_on_upstream`` property and since it fails with attribute error, the ``can_test_on_upstream`` is passed to ``__getattr__``, hence this misleading error.
=> [1LP][RFR] fix for python-bugzilla API change

cfme/tests/infrastructure/test_providers.py
Move testing with the DELETE method to separate test so the blocker BZ1422596 can be easily set.
Also use new entity.action.delete.METHOD() instead of old entity.action.delete(force_method=METHOD)
{{pytest: -v -k test_delete_custom_attributes_from_detail}}
=> [1LP][RFR] test_delete_custom_attributes - move DELETE method to separate test

cfme/tests/containers/test_smart_management.py
{{pytest: cfme/tests/containers/test_smart_management.py -v --use-provider cm-env1 }}
When I automated Smart Management test suite i forgotten to add container object to test suite
in this PR i added the missing object.
=> [1LP][RFR] Add container object to smart mgmt test suite

cfme/base/ui.py
* Login method was trying to assert a flash message on a page that it
shouldn't be on if the previous statement passed
{{pytest: cfme/tests/configure/test_access_control.py -k test_user_login}}
=> [1LP][RFR] Fixed login method

utils/appliance/__init__.py
All our Sprout appliances (configured & unconfigured) are not able to pick up NTP servers offered by DHCP client. Root cause of the problem are 2 missing lines in chrony.conf:
```
commandkey 1
keyfile /etc/chrony.keys
```
During appliance provisioning, we overwrite chronyd configuration file (and we miss above 2 lines). We should not overwrite but amend this config. This fix is trying to use default chronyd config which comes with rpm and adds only those NTP servers (from yamls), which are not defined in chrony.conf already.
More details about the problem is captured here - [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1439755).
=> [1LP][RFR] NTP configuration fix

docs/guides/vnc_selenium.rst
__Fixing__ vnc_selenium.rst because it currently does not show how to use the setup with the latest selenium server. Latest version of selenium server (3.4.0) does not take arguments "-ensureCleanSession -trustAllSSLCertificates" hence need to update those as capabilities in the env.yaml or env.local.yaml, whichever you are using.
=> [1LP][RFR] Updating the doc with information about how to use latest selenium server

cfme/tests/containers/test_containers_smartstate_analysis.py, cfme/tests/containers/test_properties.py, cfme/tests/containers/test_reload_button_provider.py, cfme/tests/containers/test_reports.py, cfme/tests/containers/test_smart_management.py
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py cfme/tests/containers/test_properties.py cfme/tests/containers/test_reload_button_provider.py cfme/tests/containers/test_reports.py cfme/tests/containers/test_smart_management.py -v --use-provider cm-env2}}
- Skipping unstable tests
=> [RFR] Skip unstable tests

cfme/cloud/provider/openstack.py
Events endpoint won't be necessary for RHOS cloud providers if it is absent in config_file
=> [RFR] rhos in sprout doesn't require events endpoint

cfme/fixtures/base.py, cfme/test_framework/sprout/plugin.py, conf/env.yaml.template, fixtures/artifactor_plugin.py, fixtures/merkyl.py, fixtures/parallelizer/__init__.py, fixtures/parallelizer/remote.py, scripts/apishow.py, scripts/install_netapp_lib.py, scripts/install_vddk.py, utils/appliance/__init__.py, utils/db.py, utils/ssh.py
Requesting review and comments on this even though it is WIP
- Added a couple of functions in utils/appliance.py which handle configuration data and turn them into lists of appliances.
- This one is used in the parallelizer setup to process the appliances
- get_or_create_current_appliance uses it as well.
- IPAppliance can (de)serialize itself as json
- SlaveDetail uses appliance instead of url and passes the appliance into slave as serialized json instead of just URL
- SSHClient and Db accept port as well
- IPAppliance passes the port into SSHClient and Db as well
- Things that were refering directly to env.base_url were converted to get_or_create_appliance().(url|address) based on the use case
Samples:
Multiple appliances in env.yaml
```
$ py.test -v -m smoke --long-running …
```
=> [1LP][RFR] Refactor parallelization data source handling

utils/appliance/__init__.py
it turned out that my changes in Cloud providers break  appliance.check_no_conflicting_providers in some cases. This is the fix for that issue.
=> [RFR] fix for providers which don't have ipaddress or hostname

cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py
Create service templates using REST API on versions >= 5.8 for REST tests
{{pytest: -v --long-running -k TestServiceTemplateRESTAPI}}
=> [1LP][RFR] create service_templates using REST API

utils/version.py
This is a fix for get_version when 'obj' is float.
During my testing an error occurred with get_version function. For whatever reason it was getting a float number on input (obj == 5.7) and it did not expect that to happen. My fix propagates this number through the function and fixes the tests for both 5.7 and 5.8.
=> fix version float

utils/appliance/__init__.py
It turned out that appliance.check_no_conflicting_providers didn't check existance of gce properly.
When GCE was converted to endpoints/widgetastic  + some consequent changes, that method started to fail.
This PR makes check_no_conflicting_providers ignore gce providers.
I expect to fix checking for existance of gce providers a bit later when I figure out how to compare gce providers.
{{pytest: -v cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py}}
=> [RFR] fix for check_no_conflicting_providers which fails on gce

cfme/tests/test_rest.py
Test checking that the default region is present in the REST API
{{pytest: -v -k test_default_region}}
=> [1LP][RFR] check that default region is present in REST API

cfme/tests/test_utilization_metrics.py
{{pytest: cfme/tests/test_utilization_metrics.py -k test_raw_metric_host_disk --use-provider rhevm36 }}
=> [RFR]Add BZ blocker for rhev disk io metric test for 5.8

utils/appliance/__init__.py
Hawkular provider has `default_endpoint` defined but it is `None` which causes an error.
=> [RFR][NOTEST] Fix to avoid error on py.test invocation

cfme/cloud/provider/__init__.py, cfme/cloud/provider/gce.py, cfme/common/provider.py, cfme/common/provider_views.py, cfme/infrastructure/provider/__init__.py, cfme/tests/cloud/test_providers.py, cfme/tests/infrastructure/test_providers.py, utils/appliance/__init__.py
1. Converted rest of cloud provider views to widgetastic
2. fixed all broken tests
3. Removed old code from both cloud and infra providers
4. fixed various issues
{{pytest: -v cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/cloud_infra_common/test_discovery.py cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/cloud_infra_common/test_tag_visibility.py }}
=> [1LP][WIP] Cloud provider widgetastic conversion -  rest of views

cfme/tests/containers/test_start_page.py
{{pytest: cfme/tests/containers/test_start_page.py -v --use-provider cm-env2}}
- Commented out containers start page test due to https://bugzilla.redhat.com/show_bug.cgi?id=1466350
=> [1LP][RFR] Commented out containers start page test due to bug

cfme/cloud/provider/__init__.py, cfme/cloud/provider/azure.py, cfme/cloud/provider/ec2.py, cfme/tests/cloud/test_providers.py
Previously, the discovery function, which is in common, had knowledge
about providers baked in. This means that when adding a new provider,
we had to modify the common file. This changes means that shouldn't be
necessary.
* Created a new discover_dict() function that will take a credential
and return the correct field dict to be filled in.
* Created the same function on CloudProvider to act as a default and
prevent people trying to use discover on a provider that doesn't
support it.
* Modified all tests to now supply the class and not a string type
{{pytest: cfme/tests/cloud/test_providers.py}}
=> [1LP][RFR] Generify the cloud discovery

fixtures/xunit_tools.py
Generate xml files with legacy testcases (without parametrization) for xunit importer.
To be run with ``pytest --collect-only --generate-legacy-xmls --xmls-testrun-id <testrun id>``
{{pytest: --collect-only --use-provider complete --generate-legacy-xmls --xmls-testrun-id 5_7_3_01}}
=> [RFR][1LP] create legacy testcases

cfme/tests/test_rest.py, utils/rest.py
Adds new ``assert_response`` function for checking REST API responses.
I plan to use it in all REST API tests eventually. In this PR it's used for basic tests in cfme/tests/test_rest.py so PRT can tests something.
The functionality will be expanded later as needed (checking content of "message", etc.)
PRT
------
Failures are not related to changes in this PR (are mostly related to https://github.com/ManageIQ/wrapanapi/pull/142)
{{pytest: -v cfme/tests/test_rest.py}}
=> [RFR] check REST API responses

cfme/tests/containers/test_topology.py
{{pytest: cfme/tests/containers/test_topology.py -v --use-provider cm-env2}}
Added above just to verify that the test is skipped.
- Old blocker has been removed.
- Added blocker bug#1467064 for topology search.
=> [RFR] Added blocker bug#1467064 for topology search

cfme/tests/cloud/test_provisioning.py
Adds support for instance manual placement on OpenStack using REST API.
Automating https://bugzilla.redhat.com/show_bug.cgi?id=1335471
{{pytest: -v -k 'test_manual_placement_using_rest or test_provision_from_template_using_rest' --use-provider ec2west}}
PRT
-----
Can't do better than this, tried many times and failed. Increasing ``wait_for`` further doesn't make sense to me. Damn cloud providers.
=> [1LP][RFR] support for instance manual placement using REST

cfme/exceptions.py, cfme/middleware/provider/__init__.py, cfme/middleware/server.py, cfme/middleware/server_group.py, cfme/tests/middleware/jdbc_driver_methods.py, cfme/tests/middleware/server_methods.py, cfme/tests/middleware/test_middleware_datasource.py, cfme/tests/middleware/test_middleware_deployment.py, cfme/tests/middleware/test_middleware_domain_server.py, cfme/tests/middleware/test_middleware_drivers.py, cfme/tests/middleware/test_middleware_provider.py, cfme/tests/middleware/test_middleware_server.py, cfme/tests/middleware/test_middleware_server_group.py
Fixed failing Datasource tests because of UI changes. Disabled unnecessary tests.
{{pytest: cfme/tests/middleware/test_middleware_server.py -v --use-provider hawkular}}
=> [RFR] Added support for Container based servers in standalone mode.

cfme/base/ui.py, cfme/cloud/instance/__init__.py, cfme/common/vm.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud/test_cloud_timelines.py, cfme/tests/infrastructure/test_timelines.py
new timelines test 
{{pytest: -k test_infra_vm_diagnostic_timelines  --use-provider=rhevm36 cfme/tests/infrastructure/test_timelines.py}}
cfme/tests/cloud/test_cloud_timelines.py
=> [1LP][RFR] test diagnostic timelines

cfme/infrastructure/datastore.py, cfme/tests/infrastructure/test_delete_infra_object.py
1. Update infrastructure.datastore methods to use up-to-date toolbar text  (which will all get overwritten anyway with @izapolsk planned widgetastic conversion)
2. add BZ blocker to test case (valid regardless of widgetastic conversion)
=> [1LP][RFR] Fix/Block Infra Datastore 

cfme/tests/cloud/test_provisioning.py
__Fixing__ auto_placement provision for azure - one argument was missed
{{pytest: --long-running --use-provider azure  -k "azure-Auto"}}
=> [1LP][RFR]fix for azure provision

cfme/tests/cli/test_appliance_console.py, utils/appliance/__init__.py
New test coverage for timezone setting through appliance_console
{{pytest: -k test_black_console_set_timezone}}
=> [RFR] New test coverage for Timezones

cfme/test_framework/sprout/plugin.py, fixtures/artifactor_plugin.py, fixtures/parallelizer/__init__.py
* Sprout shutdown would be attempted even if sprout hadn't been used
for deployment of appliance
* No slaveid was being set on the handlers, so no per test logging was
occuring as the slaveid was always None (which didn't exist in
artifactor)
=> [1LP][RFR]Fix logging and sprout shutdown

cfme/tests/configure/test_tag.py, utils/rest.py
* check the response when assigning tags using the "assign_tags" action
* more complete REST API responses check using the ``assert_response``
{{pytest: -v --use-provider vsphere65-nested -k TestTagsViaREST}}
=> [RFR] check REST API responses when assigning tags

cfme/containers/provider/__init__.py, cfme/tests/containers/test_properties.py, cfme/tests/containers/test_reload_button_provider.py, cfme/tests/containers/test_reports.py, cfme/tests/containers/test_smart_management.py
{{pytest: cfme/tests/containers/test_reload_button_provider.py cfme/tests/containers/test_properties.py cfme/tests/containers/test_reports.py cfme/tests/containers/test_smart_management.py -v --use-provider cm-env2}}
- Created Pod.pods_per_ready_status in order to be able to share this usage between test_pods_conditions and test_report_pods_per_ready_status
- Fixed test_smart_management which didn't wait enough time to the tags to be populated.
=> [RFR] Added Pod.pods_per_ready_status + Fix smart management test

cfme/configure/configuration/__init__.py
New server role cockpit is added in upstream and many test cases in upstream are failing due to this error "Exception: Unknown server role(s): cockpit_ws".
Adding this should fix all those  errors.
=> Adding new server role for cockpit

cfme/common/provider.py, cfme/infrastructure/provider/rhevm.py
It turned out that sprout yamls don't have api_port in their yaml. This didn't allow sprout to add rhevm providers.
Since this field isn't mandatory, provider object should handle this properly
=> [RFR] api_port can be absent in yamls for rhemv providers

cfme/cloud/provider/__init__.py, cfme/common/provider.py, cfme/common/provider_views.py, cfme/exceptions.py, cfme/infrastructure/provider/__init__.py, cfme/tests/openstack/infrastructure/test_provider.py, widgetastic_manageiq/__init__.py
This PR is going to extact BaseItem widget which will be used everywhere as a replacement for QuadIcon, etc. Additionally, BaseItems view will be extracted and refactored.
requires:[widgetastic.core->View.include fix]( https://github.com/RedHatQE/widgetastic.core/pull/42)
=> [RFR] extracting BaseItem and BaseItems widgets

cfme/cloud/provider/azure.py, cfme/cloud/provider/openstack.py, cfme/common/provider.py, cfme/infrastructure/provider/openstack_infra.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/scvmm.py
It turned out that some yamls don't contain full endpoints. So, sometimes providers cannot be added just because some not mandatory parameters are absent in provider endpoints in yaml.
This PR fixes this issue for Cloud and Infra providers
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py}}
=> [1LP][RFR] made some parameters not mandatory for cloud/infra providers

cfme/tests/configure/test_default_views_cloud.py, cfme/tests/configure/test_default_views_infra.py
Renamed the name of the test cases uniquely.
{{pytest: -v -k 'test_cloud_tile_defaultview or test_cloud_list_defaultview or test_cloud_grid_defaultview or test_infra_list_defaultview or test_infra_grid_defaultview or test_infra_tile_defaultview' }}
=> [1LP][RFR] Uniquely renaming test cases for infra and cloud test cases.

cfme/base/ui.py, cfme/cloud/tenant.py, cfme/infrastructure/pxe.py, cfme/services/myservice.py, cfme/tests/cloud/test_cloud_init_provisioning.py, cfme/tests/cloud/test_tenant.py, cfme/tests/infrastructure/test_cloud_init_provisioning.py, cfme/tests/infrastructure/test_host_provisioning.py, cfme/tests/infrastructure/test_iso_datastore.py, cfme/tests/infrastructure/test_iso_provisioning.py, cfme/tests/infrastructure/test_pxe_provisioning.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/services/test_iso_service_catalogs.py, cfme/tests/services/test_pxe_service_catalogs.py
most were, just making it consistent.
Fixed all the calls using .exists() for .exists
Not including sentaku implementations here because of: 
https://github.com/RonnyPfannschmidt/Sentaku/issues/12
If Sentaku PR is merged to fix ContextualProperty, Zone.exists can be implemented as a property as well. https://github.com/RonnyPfannschmidt/Sentaku/pull/14/files
FIXES RHCFQE-3249
PRT might be a bit crazy because I'm not intending to fix any modified tests that may not be working, limiting scope to just fixing the exists calls.
Failures, but nothing to do with any of the calls to exists properties that I've modified here.
=> [1LP][RFR] Update class.exists() methods to be properties

cfme/tests/cloud_infra_common/test_snapshots_rest.py
New REST API tests for snapshots on VMs and instances (currently only OpenStack is supported)
{{pytest: -v --use-provider vsphere65-nested  --use-provider rhos7-ga --long-running -k TestRESTSnapshots}}
=> [1LP][RFR] new REST API tests for snapshots

widgetastic_manageiq/vm_reconfigure.py
`Table.__locator__()` used to return `str` but now it returns `Locator` obj, which doesn't work with `.format`. This fixes the issue because `Table.locator` is a `str`.
{{pytest: -k test_vm_reconfig_add_remove_disk_cold --use-provider vsphere6-nested --long-running}}
=> [RFR] Fix DisksTable locator

cfme/web_ui/__init__.py
The ``self.read_contents()`` can (and does) return ``None`` which leads to the
mentioned error.
See https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-58z/job/downstream-58z-tests-master/87/Artifactor_Report/cfme/tests/infrastructure/test_snapshot.py/test_create_snapshot_via_ae[vsphere6-nested]/filedump-traceback.log
{{pytest: -v --long-running --use-provider vsphere6-nested -k test_create_snapshot_via_ae}}
=> [1LP][RFR] Fixing TypeError: 'NoneType' object is not iterable

cfme/common/vm.py
__Extending__ BaseVM Class to add ip_address property to it as per conversation with jkrocil on #cfme-qe-dev. Previously one would require using provider.mgmt.get_ip_address method, but now VM will have ip_address property.
=> [1LP][RFR] Adding ip_address property to BaseVM

cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/provider/__init__.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py, cfme/tests/containers/test_tables_sort.py
{{pytest: cfme/tests/containers/test_tables_sort.py -v --use-provider cm-env2}}
- Removed the issue skip in cfme/tests/containers/test_tables_sort.py
- Added cfme.web_ui.exceptions.TableOrderingException
- Instead of skipping the entire test, if the TableOrderingException raised we just warning with error in the log and continue to the next header.
=> [RFR] Sort tests fix + Widgetastic Conversions 

cfme/tests/configure/test_access_control.py, cfme/tests/services/test_catalog.py
Fixing ``TypeError: test_permissions() takes exactly 4 arguments (3 given)``
by adding the ``appliance`` parameter to function definitions where it's
missing.
See e.g. https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-58z/job/downstream-58z-tests-master/87/Artifactor_Report/cfme/tests/services/test_catalog.py/test_permissions_catalog_add/filedump-traceback.log
{{pytest: -v -k test_permissions_ cfme/tests/configure/test_access_control.py cfme/tests/services/test_catalog.py}}
PRT results
---------------
The tests fails anyhow (assert errors), but the TypeErrors are fixed. It's up to the test owners to decide if it's bug in test logic or in the product, I'm not knowledgeable enough.
=> [1LP][RFR] Fixing TypeError in test_access_control tests

cfme/infrastructure/provider/__init__.py, cfme/tests/infrastructure/test_provider_discovery.py
Fixing ``discover()`` calls
See e.g. https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-58z/job/downstream-58z-tests-master/87/Artifactor_Report/cfme/tests/infrastructure/test_provider_discovery.py/test_discover_infra[virtualcenter]/filedump-traceback.log
{{pytest: -v -k 'test_discover_infra and virtualcenter'}}
=> [RFR] Fix TypeError: discover() takes at most 4 arguments (6 given)

cfme/tests/configure/test_ntp_server.py
Fixing the ``appliance_date()`` and ``check_ntp_grep()`` calls.
Solving 
``TypeError: check_ntp_grep() takes exactly 2 arguments (1 given)``
and
``TypeError: appliance_date() takes exactly 1 argument (0 given)``
fails.
PRT results
---------------
The TypeErrors are fixed, the tests fails anyhow. The /etc/chrony.conf file is not updated when server addresses are cleared, it's probably a bug.
=> [RFR] Fixing TypeErrors for appliance_date() and check_ntp_grep()

cfme/fixtures/configure_auth_mode.py
See https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-58z/job/downstream-58z-tests-master/87/Artifactor_Report/cfme/tests/integration/test_cfme_auth.py/test_auth_configure[miq_openldap-create_group]/filedump-traceback.log
{{pytest: '''cfme/tests/integration/test_cfme_auth.py::test_auth_configure[miq_openldap-retrieve_group]'' -v'}}
=> [RFR] Fixing TypeError: 'NoneType' object is not callable in the configure_auth fixture

cfme/common/vm.py, cfme/tests/infrastructure/test_vm_power_control.py
__Extending__ tests coverage for archived/orphaned VMs because we don't have any
{{pytest: --use-provider vsphere65-nested --long-running -k "archived or orphaned"}}
=> [1LP][RFR] Adding tests for archived/orphaned VMs

cfme/base/credential.py, cfme/common/provider.py
It turned out that containers team store their credentials in cfme_data.yaml. So those should be parsed in a bit different way
=> [RFR] Support for plaintext credentials in credentials classes

cfme/tests/containers/test_chargeback_for_images.py, cfme/tests/containers/test_chargeback_for_projects.py
Refactor chargeback rates/assignements according to the changes in #4923.
{{ pytest: cfme/tests/containers/test_chargeback_for_projects.py --use-provider cm-env2 -m 'not long_running_env' }}
=> [1LP][RFR] Refactor chargeback rates/assignment

cfme/tests/configure/test_rest_access_control.py
Fix for ``APIException: Api::BadRequestError: Must filter on valid attributes for resource``
{{pytest: -v -k "TestGroupsViaREST and test_edit_groups"}}
=> [RFR] fixing APIException: Api::BadRequestError

utils/appliance/__init__.py
Upstream Sprout appliances won't get IP addresses because of erased ifcfg-eth0 configuration file. We try to use auditd here and set monitoring of the network config file.
=> [1LP][RFR] Debugging of overwritten ifcfg-eth0

cfme/containers/provider/__init__.py, cfme/tests/containers/test_tables_sort.py
- Changed ContainerObjectAllBaseView to inherit ProvidersView.
- fixed test_tables_sort
{{ pytest: cfme/tests/containers/test_tables_sort.py --use-provider cm-env2 }}
=> [1LP][RFR] Added paginator to ContainerObjectAllBaseView + fixed test_tables_sort

cfme/tests/infrastructure/test_infra_tag_filters_combination.py
New tests cover group tag filters cases for tag visibility
{{pytest: cfme/tests/infrastructure/test_infra_tag_filters_combination.py -v -k test_tagvis --long-running}}
=> [1LP][RFR]Tag filter combination tests

cfme/control/explorer/policies.py, requirements/frozen.txt, widgetastic_manageiq/__init__.py
Purpose
__Fixing__ events assignment in CFME 5.8.1. Checkboxes are replaced by BootstrapSwitches. BootstrapswitchSelect has been implemented. Requires https://github.com/RedHatQE/widgetastic.patternfly/pull/9
{{pytest: -v -k "test_assign_two_random_events_to_control_policy" --long-running}}
=> [1LP][RFR] Fixed EditPolicyEventAssignments view

cfme/tests/infrastructure/test_snapshot.py
This is a fix for existing test. The wait_for needs to mask an exception that occurs while waiting for snapshot to be created.
=> [1LP][RFR] fix test_create_snapshot_via_ae

cfme/common/provider.py
Quick fix of Events endpoint for OpenStack provider.
Honestly, the best fix would be to turn this view into ConditionalView but I'm not sure that ConditionalView can be used along with View.include. Otherwise,  fill scheme has to be changed.
Closes #5028
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py}}
=> [RFR] fix for case when OpenStack provider uses Oscilomenter instead of AMPQ

cfme/containers/provider/__init__.py, cfme/tests/containers/test_logging.py
{{pytest: cfme/tests/containers/test_logging.py -v --use-provider cm-env2}}
I had some issues with this test so i was asked to fix some code.
The fixes i made are:
1. The polarion id of the test was inexact
2. I was asked to add validation to the popup window which come up after the external logging button is pushed, so i had to get the correct URL from OSE and assert it with the actual URL of the popup window.
=> [1LP][RFR]fix logging test 

cfme/tests/control/test_alerts.py, fixtures/provider.py
Intent
=====
__Refactoring__ test_alerts.py.
* Removed redundant fixtures
* Refactored pytest_generate_tests
* `provider.type` strings comparison replaced by `provider.one_of()`
* Renamed test VMs to `test-alert-`
{{py.test: -v -k 'test_alert' --long-running --use-provider vsphere65-nested}}
=> [RFR][1LP] Test alerts refactoring

scripts/list_outdated_testcases.py
The script creates a CSV file with test cases that are present in Polarion but are missing in pytest.
It's handy when you want to find out what test cases should be deactivated/deleted in Polarion.
=> [RFR][NOTEST] Script for listing outdated test cases

scripts/cleanup_old_vms.py, scripts/list_provider_vms.py
Depends on: ~~https://github.com/ManageIQ/wrapanapi/pull/151~~
vsphere no longer requires connecting to the host to get
vm_creation_date for a powered off VM, greatly simplifies this script,
removing the need for a separate method for these vm types.
Converted to using MultiProcessing Process + Queue instead of threads
and global dicts
MP applied to delete with a process for each prov+vm tuple, instead of
threaded per-provider which is really slow (vm deletes were sequential)
FIXES RHCFQE-3256
=> [1LP][RFR][NOTEST]Refactor cleanup_old_vms

cfme/configure/access_control.py
tests in `cfme/infrastructure/test_infta_quota.py` were failing with the error `NoSuchElementException`, but the locator seemed correct; So adding a `wait_for` to let the page load properly, and then go for further execution.
{{pytest: cfme/tests/infrastructure/test_infra_quota.py -k storage -vvv}}
=> [1LP][RFR] Added wait_for to solve NoSuchElementException

cfme/scripting/quickstart.py
__Extending__ quickstart to include the "tesseract" package. As  @RonnyPfannschmidt pointed it out that PRT may start using quickstart to build containers for testing, I would need those to contain the package mentioned above in order to get PR #4998 tested on PRT before it is merged.
=> [RFR][1LP] Adding tesseract dependency in quickstart

cfme/tests/intelligence/test_chargeback.py
Reload the resource after it's detected that it was already changed, not before (where it can still show the old value).
{{pytest: -v -k test_edit_rates}}
=> [1LP][RFR] Reload resource right before check in test_edit_rates

cfme/tests/cloud_infra_common/test_genealogy.py
This is a quick fix for existing test. The test was failing with NameError exception, so I introduced a try+except block, sent the exception to log and the test is now failing with pytest.fail.
=> [1LP][RFR] fix NameError in genealogy

conf/cfme_data.yaml.template
__Extending__ cfme_data.yaml.template to reflect extended Provider Data that includes a templates section to track those templates that are required for testing and any additional info about each of them may require such as credentials.
=> [1LP][RFR][NOTEST] Adding templates section under the provider on example cfme_data template

cfme/control/explorer/actions.py, cfme/control/explorer/alert_profiles.py, cfme/control/explorer/alerts.py, cfme/control/explorer/policies.py, cfme/control/explorer/policy_profiles.py, widgetastic_manageiq/__init__.py
Purpose
In 5.8.1 all image buttons in MultiBoxSelect are replaced by usual `<button>` elements. This PR adds temporary NewMultiBoxSelect view which uses `Button` widget from widgetastic_patternfly.
{{pytest: -v -k 'test_assign_condition_to_control_policy or test_policy_profile_crud or test_alert_profile_crud' --long-running}}
=> [RFR] MultiBoxSelect refactored

cfme/common/provider_views.py, widgetastic_manageiq/__init__.py
1. According to hhovsepy, this view didn't work well with Middleware providers
2. this view had to be refactored since CondtionalView widget was developed
=> [1LP][RFR] refactoring ProviderDetailsView

cfme/tests/ansible/test_embedded_ansible_rest.py
New REST API test for CRUD on /api/configuration_script_sources
{{pytest: -v --long-running cfme/tests/ansible/test_embedded_ansible_rest.py}}
=> [1LP][RFR] Adds new REST API tests for /api/configuration_script_sources

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
Hi!
I've took https://github.com/ManageIQ/integration_tests/pull/4562
pull request and it wasn't working properly. As far as I understood
it's because of RHV VM's quadicon state could be not just
'currentstate-on' but 'currentstate-on-<some_hash_here>'.
So I've changed soft assertion's condition and now it's fine.
Thanks.
{{pytest: -v --long-running cfme/tests/infrastructure/test_snapshot.py --use-provider rhv41}}
=> [1LP][RFR] Snapshots tests adoption for RHV.

cfme/tests/infrastructure/test_config_management_rest.py
New REST API tests for the /api/authentications collection.
{{pytest: -v -k ansible_tower_310 cfme/tests/infrastructure/test_config_management_rest.py}}
=> [1LP][RFR] Adds new tests for /api/authentications

cfme/infrastructure/provider/rhevm.py, cfme/tests/infrastructure/test_providers.py
Adding test for RHV provider to cover it's creation with and without tls.
{{pytest: -v --long-running cfme/tests/infrastructure/test_providers.py -k test_provider_rhv_create_delete_tls --use-provider rhv41}}
=> [1LP][RFR] RHV Provider create/delete test with & without tls.

cfme/common/host_views.py, cfme/infrastructure/provider/virtualcenter.py, cfme/tests/infrastructure/test_host.py
The credentials_form was removed during widgetastic configuration, and is causing an ImportError for `infrastructure/test_host.py`.
Refactor tests to use widgetastic views/forms.
FIXES #5098
=> [RFR] Fix infra.test_host import error, credentials_form

requirements/frozen.txt, requirements/frozen_docs.txt
This version makes it easier to pair importer logs in Polarion UI to
polarion_dumper output in Jenkins logs.
=> [RFR][NOTEST] Updating dump2polarion

widgetastic_manageiq/__init__.py
When BaseEntitiesView is switched to list view, it cannot correctly recognize entities in it due to missing entity_names method.
This PR fixes that issue.
=> [1LP][RFR] Correct recognition of entities in list view 

cfme/containers/node.py, cfme/containers/provider/__init__.py, cfme/tests/containers/test_logging.py
{{pytest: cfme/tests/containers/test_logging.py -v --use-provider cm-env2}}
In this PR I automated test case CMP-10635, 
**Short explanation about logging:**
The feature logging allow to save system logs to second location for backup goals, this option allowed for provider and for node. 
I had to create new view for logging-able object to avoid code duplication.
I also moved "Monitoring" dropdown to  logging-able view because each object that support logging have to navigate through "Monitoring --> External logging"
=> [1LP][RFR] Nodes Logging test

cfme/tests/infrastructure/test_providers.py
Fixing test uncollectif condition because it is currently incorrect because provider.data does not have 'verify_tls' key. It should be provider.endpoints['default'].verify_tls.
Thanks.
{{pytest: -v --long-running cfme/tests/infrastructure/test_providers.py -k test_provider_rhv_create_delete_tls --use-provider rhv41}}
=> [1LP][RFR] RHV Verify TLS test fix uncollection condition

cfme/tests/intelligence/reports/test_views.py
Changed bz number from 5.8 verified bug to 5.7 blocker clone which is reason tests are skipped
=> changed blocker mark to correct blocker bz

cfme/tests/cloud_infra_common/test_power_control_rest.py
The REST reset VM test is running for the RHV provider, though the power reset option is not supported there.
Thus, need to skip it for now.
=> [WIPTEST] Skip unsupported rest reset vm test for RHV provider

cfme/cloud/provider/openstack.py, cfme/common/provider.py, cfme/common/vm.py, cfme/common/vm_console.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py, eng.user-words, requirements/frozen.txt, utils/appliance/implementations/ui.py
Adding HTML5 Remote Console tests.  It does following:
- For VMware: 
Configures VMware Console Support option on  Appliance Config to use VNC
- For VMware and RHOSP: 
Deploys a VM small_template and opens HTML5 Console to it, login using credentials, and touch a file. 
-For VMware: 
It can SSH to VM and try to remove the file which was created through HTML5 console, which if succeeds indicates that file was created and removes it, and if fails, indicates there was some issue with console and could not create file. 
- For VMware and RHOSP:
Tests Ctrl+Alt+Del Button functionality as well
Note:
-  Requires tesseract to be installed via dnf/yum.
- It might work well with RHEV, but not tested. 
- Tests do not run back to back, please run them against a …
=> [1LP][RFR] HTML5 Remote Console Test - Initial Prototype

requirements/frozen.txt, requirements/frozen_docs.txt, requirements/template_docs.txt
with this pr we update riggerlib to a version that correct uses per thread socket patterns as well as the lazy pirate pattern for signal and artifactor shutdown aware message handling
this should remove the occasional deadlocks we see in the larger jenkins builds
=> [RFR] version bump riggerlib on order to get rid of locks

cfme/infrastructure/virtual_machines.py
This is a quick fix for snapshot creating when VM is in state other than POWERED_ON.
When a VM is suspended or powered off, we cannot create a snapshot that would contain VM's memory. There is also no checkbox displayed on the page. This was causing errors in the original code, which expected the checkbox to be there at all times.
=> [1LP][RFR] fix creating snapshot for powered off VMs

cfme/tests/test_rest.py
The BZ 1437201 affecting the tests will be fixed in 5.9. Skipping in
older versions.
Cleanups of unsupported versions.
Skipping all test_select_attributes tests because of https://github.com/ManageIQ/manageiq/issues/15754
{{pytest: -v -k "test_select_attributes or test_query_simple_collections" cfme/tests/test_rest.py}}
=> [1LP][RFR] Fixing test_select_attributes

widgetastic_manageiq/__init__.py
Add an miq implementation for dynamic table, covers those with Add/Save buttons in the right-hand column.
Note this may not be everything DynamicTable eventually needs, but satisfies the required actions for #4908, AnalysisProfile implementation. We'll certainly need a row_delete method as well.
Needed by #4908
Depends on ~~https://github.com/RedHatQE/widgetastic.core/pull/52~~  <- merged, need a release with it.
=> [1LP][RFR] Update wt_manageiq, add DynamicTable

cfme/fixtures/service_fixtures.py, cfme/infrastructure/config_management.py, cfme/tests/services/test_config_provider_servicecatalogs.py
{{pytest: -v --long-running --use-provider ansible_tower_310 cfme/tests/services/test_config_provider_servicecatalogs.py }}
Due to recent widgetastic changes in dialog One field needs to be modified here .
Note : The ansible tower provider are having issues so the test will fail .
Pavol is checking the issues .
=> [1LP][RFR] Dialog widgetastic impact on ansible test

cfme/tests/services/test_rest_services.py
{{pytest: -v --long-running -k "TestServiceCatalogsRESTAPI or test_assign_unassign_service_template_to_service_catalog" cfme/tests/services/test_rest_services.py}}
=> [1LP][RFR] New REST API tests for /api/service_catalogs

cfme/tests/test_db_migrate.py, fixtures/appliance.py
Changes to test_db_migrate to collect the new repo files for upgrades.
Also fix to version picking to save manual intervention.
{{ pytest: -k test_upgrade_single_inplace}}
=> [1LP][RFR] Refactoring to repo collection

cfme/common/vm_console.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py
- searching for canvas element is now using a wait_for loop and
a try-catch to avoid having an initial miss in finding the
canvas element not cause the test to fail.
- Fixed the exceptions that were being caught from the provider
in vm_console.py.  Previously we had been catching the selenium
exception, but now the provider code throws its own exception, so
now vm_console.py catches that.
- Make running of HTML5 Console test be based on a test_flag,
html5_console, in the cfme_data.yaml file rather than provider                                                           
type.
The problem with failing on the first time you access a VM console on a provider failing because we never see the status element (really its having a problem connecting to the websocket) still exists, so PRT may very …
=> [1LP][RFR] RHV5 fixes and lingering PR review fixes

cfme/cloud/instance/__init__.py, cfme/common/vm.py, cfme/common/vm_views.py, cfme/infrastructure/virtual_machines.py, cfme/provisioning.py, cfme/tests/cloud/test_instance_power_control.py, cfme/tests/cloud/test_provisioning.py
Convert cloud.instances model to WT views and widgets.
Implemented common views and widgets for instances and VM's in cfme.common.vm_views. These are cases where the pages are exactly the same. Any pages with slight differences should be implemented in their respective modules.
Moved ProvisioningForm class to cfme.common.vm_views.ProvisionView. ProvisionView.form nested view class implements `before_fill()` to select the provisioning image from the table, the first half of the UI form. This gives the syntax `view.form.fill({<tab keyed fill dict>})` to complete the entire provisioning form fill process, through both pages.
Skipping RESTAPI tests, not relevant here.
* 58z: 70+% overall, failures in test_provisioning due to VM's not provisioning, no page model/widget/view exceptions.
* 57z: …
=> [1LP][RFR] cloud.instance widgetastic conversion (Part 2)

cfme/tests/containers/test_smart_management.py
{{pytest: cfme/tests/containers/test_smart_management.py -v --use-provider cm-env2}}
Add Container object to smart management tests
=> [1LP][RFR]Enable Container object testing

widgetastic_manageiq/__init__.py
Purpose
Current `parent_table` in `BaseListEntity` is always not displayed. `ParametrizedLocator('.//table[.//td[normalize-space(.)={name|quote}]]')` searches **descendant** table of the `ROOT`, but we need the parent one. Therefore such xpath `./ancestor::table[1]` can be used here. It searches the first **ancestor** table of the `ROOT`.
=> [RFR] Fixed BaseListEntity parent_table locator

cfme/infrastructure/host.py
Fixing `wait_for_host_state_change` - `entity.status` returns `None`.
{{pytest: cfme/tests/openstack/infrastructure/test_host_power_control.py --use-provider rhos_uc}}
=> [RFR] Fix wait_for_host_state_change of Host class

utils/providers.py
Now test flags are expecting string type in CFME yaml, but unfortunately it could be list in some environments. 
In this patch I've just added a check for a type so tests will not fail at string splitting and will proceed successfully in environments where test flags are defined as list.
Thanks.
=> [1LP][READTOMERGE] utils/providers.py Fix for test flags.

utils/appliance/__init__.py
SSIA
Tested manually.
```
current_appliance._encrypt_string('smartvm')
```
=> [RFR][1LP] Fix IPAppliance._encrypt_string

cfme/infrastructure/host.py, cfme/tests/control/__init__.py, cfme/tests/control/test_actions.py, cfme/tests/control/test_compliance.py, fixtures/provider.py, utils/appliance/__init__.py, utils/hosts.py
Purpose
=======
__Refactoring tests__  in test_actions.py. There are several deprecated objects and functions.
* Instead of strings comparing `provider.key` we should check the instance of the provider object `provider.one_of()`
* Removed fixtures: `vm_crud_refresh`, `automate_role_set`
* Enabled tests for openstack and azure providers
* `pytest.store.appliance` replaced by `appliance` fixture
{{pytest: -v -k 'test_action and not test_action_crud' --long-running --use-provider vsphere6-nested}}
test_action_cancel_clone failed due the template absence. 58z failed because of testing vm is deleted for some reason during test run.
=> [1LP][RFR] Action tests refactoring

cfme/tests/containers/test_miq_ansible_providers.py, utils/ansible.py, utils/ansible_conf/providers_basic_script.yml
{{pytest: cfme/tests/containers/test_manageiq_ansible_providers.py -v --use-provider cm-env2 }}
This test is testing the Providers function of MIQ Ansible Module
For this test to run successfully it needs the git library added to requirements
=> [RFR]ManageIQ Ansible Module Tests - Providers

cfme/tests/containers/test_manageiq_ansible_tags.py, utils/ansible.py, utils/ansible_conf/tags_basic_script.yml
**Purpose or Intent**
{{pytest: cfme/tests/containers/test_manageiq_ansible_tags.py -v --use-provider cm-env2 }}
This test is testing the Tags function of MIQ Ansible Module which adds adds to objects inside ManageIQ.
For this test to run successfully it needs the git library added to requirements
=> [RFR]ManageIQ Ansible Module Tests - Tags

cfme/scripting/runtest.py
pkg_ressources would be initialized with stale data the time pytest gets to it after the updates
=> [RFR] miq-runtest restart the python process to avoid global state

widgetastic_manageiq/__init__.py
Purpose
PaginationPane wrapper always returns VersionPick object, also wrapper doesn't have any arguments.
=> [RFR] Fixed PaginationPane wrapper

widgetastic_manageiq/__init__.py
__Fixing__ set_items_per_page because I was getting following error during execution of my tests:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
def select_by_visible_text(self, *items):
"""Selects items in the select.
Args:
*items: Items to be selected. If the select does not support multiple selections and you
pass more than one item, it will raise an exception.
"""
if len(items) > 1 and not self.is_multiple:
raise ValueError(
'The BootstrapSelect {} does not allow multiple selections'.format(self.id))
self.open()
for text in items:
self.logger.info('selecting by visible text: %r', text)
try:
self.browser.click(self.BY_VISIBLE_TEXT.format(quote(text)), parent=self)
except NoSuchElementException:
raise …
=> [1LP][RFR] Fix pagination widgetastic

cfme/tests/control/test_alerts.py, cfme/tests/control/test_compliance.py, cfme/tests/infrastructure/test_vm_power_control.py
Purpose
After merging #5044 some tests failed. `full_template` fixture now always returns a string and respectful tests should be fixed.
{{pytest: -v -k "test_alert_snmp or test_check_package_presence or testing_vm_tools" --long-running --use-provider vsphere6-nested}}
=> [RFR] Fixed full_template name

cfme/infrastructure/host.py
Purpose
During host object update a warning from widgetastic raised. `updates` dict contains more items than view.fill() requires. We should specify the same update items as fields in the view.
=> [RFR][1LP] Fixed warning which appears during host update

widgetastic_manageiq/__init__.py
Purpose
status property in `HostQuadIconEntity`, which inherits `BaseQuadIconEntity`, always returns `None` due incorrect locator.
```html
<div class="flobj b72">
<div class="stretch" style="background-image: url('/assets/svg/currentstate-on-d9d3fbe67ad09da2fb76e7674b093c3843b03b9a392b32d7e7d13e7bb35883cf.svg')"/>
</div>
```
=> [RFR][1LP] Fixed BaseQuadIconEntity

cfme/tests/control/test_basic.py
Intent
Automation of test_control_is_ansible_playbook_available_in_actions_dropdown
{{pytest: -v -k "test_control_is_ansible_playbook_available_in_actions_dropdown" --long-running}}
=> [RFR][1LP] New test test_control_is_ansible_playbook_available_in_actions_dropdown

cfme/common/provider.py
The flash message during endpoint credentials validation was not being
asserted against.
Add calls to WT.patternfly.FlashMessages assert_no_errors() and
assert_success_message for the credentials validation against each
endpoint
Remove CloudInfraProvider.wait_for_creds_ok(), it was using
web_ui.Quadicon.creds and generating an exception due to bad Quadicon
attr resolution.  The method was unused in the framework, and if needed
should be rewritten using Widgetastic quadicon implementation.
FIXES RHCFQE-3858
FIXES #3792
{{ pytest: -v --long-running --use-provider complete -k 'test_provider_crud' }}
80% / 70% passing on CFME
Seeing some stats_match `TimedOutError` failures and a 401 on rhos7-ga *after* the provider is created and this new creds validation code is called, and is happening in …
=> [1LP][RFR] Update BaseProvider.create, validate creds flash

cfme/common/provider.py, cfme/common/vm.py, cfme/common/vm_console.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py
__Adding tests__ for feature ToggleFullScreen Button on HTML5 Remote Console. 
**Expected Result:**Tests are supposed to fail against the vsphere6-nested and RHV41 because it is a known Bug (https://bugzilla.redhat.com/1479935) and RHOS7-GA would be skipped for ToggleFullScreen button test since it does not support this functionality.  
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider vsphere6-nested --use-provider default }}
=> [1LP][RFR] Adding ToggleFullScreen Button Test for HTML5 Remote Console

widgetastic_manageiq/__init__.py
__Fixing__  GH issue #5180. When we are using paginator, we expect some page result. such workaround would give us a try to go thru items at page we currently have. as that happened with Requests page - no pagination controls at all if we open them manually
=> [RFR]adding BZ blocker and workaround for Requests page

cfme/cloud/instance/__init__.py, cfme/cloud/instance/openstack.py
There were several navigation destinations that were only available for
openstack type instances. Instead of checking for correct class type in
the navigation destination, move the classes and register them against
OpenStackInstance only.
There don't appear to be any tests that directly use these navigation destinations? It's an enhancement, just moving existing nav+views to the only module/class where they're relevant.
=> [1LP][RFR] Move OpenStackInstance nav destinations

cfme/cloud/instance/__init__.py
Override BaseVM.set_ownership until subclasses support widgetastic
FIXES #5038
FIXES RHCFQE-3855
Scoping PRT for `cloud_infra_common/test_vm_ownership` for standard ownership tests, and `intelligence/reports/test_validate_chargeback_report` for where the failure was originally observed.
test_vm_ownership is only supported by ec2 according to YAML configuration.
The original issue was written against intelligence/reports/test_validate_chargeback_report, which at the moment does not support cloud instances for testing. @nachandr Is adding cloud instance support to the test via #4891, and will be independently running that test against this commit.
{{ pytest: -v --long-running --use-provider ec2west cfme/tests/cloud_infra_common/test_vm_ownership.py }}
Seeing passing results in run 15099 …
=> [1LP][RFR] Add cloud.instance.set_ownership

cfme/tests/cli/test_appliance_update.py
skip if an IndexError occurs because we can't parse minor version
In testing I'm seeing the following, showing that the test is skipped during generation where 2141 tests are initially collected.
```
=============================================================================================== test session starts ===============================================================================================
platform linux2 -- Python 2.7.13, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: /home/mshriver/repos/integration_tests, inifile:
plugins: wait-for-1.0.9, manageiq-integration-tests-0.0.0
collected 2141 items / 1 skipped 
Appliance's streams: [upstream]
=============================================================================================== Running smoke tests …
```
=> [1LP][RFR] Fix test generation in test_appliance_update

cfme/tests/cli/test_appliance_update.py
Takes care of current downstream collection issue. My bad. See #5215
=> Use current_appliance from store; fix downstream collection

cfme/tests/distributed/test_appliance_replication.py, utils/appliance/__init__.py, utils/appliance/db.py
Methods to start/stop postgresql service on the appliance using
systemctl.  Dynamically constructs the service name from
IPAppliance.db.postgres_version
**These tests are blocked by broken browser_steal, so we won't get PRT results here**
The new IPAppliance methods should be tested by hand, they were tested locally.
Also addresses open issue #3784 by using utils.generator.random_vm_name with a shorter prefix that's more compatible with a range of providers.
FIXES RHCFQE-3857
=> [1LP][RFR] Update IPAppliance, add start/stop_db_service

cfme/tests/cloud_infra_common/test_html5_vm_console.py
__Extending__ Timeout for the wait_for_connect() function call because RHV HTML5 console takes longer time to open on first launch. OSP does not require that much time and it was working with default (30 sec) timeout with the function as well. This PR is connected to **RHCFQE-3577** on our sprint board. See comments on that card for additional details. Also moved the fixture configure_websocket before vm_obj, so that there is more time between Enabling Websocket Role and Opening of Remote Console.
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider vsphere6-nested --use-provider default }}
=> [1LP][RFR] Adding extended timeout to avoid RHV Console failure due to TimedOutError

cfme/tests/infrastructure/test_snapshot.py
This modifies some core components used in snapshot testing. Features:
- testing VM gets always deployed with a different name [1]
- able to choose a template for testing VM [2]
- able to choose to create a snapshot with/without memory
[1] This is needed due to a known (?) issue with pytest scopes. Solves the intermittent error that sometimes appears when destroying and then again deploying a VM with the same name.
[2] Some of the snapshot tests need a testing VM that has network configured, sshd running and automation can connect to it. This is not possible when the VM is deployed from the smallest template. On the other hand, most of the snapshot tests do not need bigger template, so it makes no sense to run them all with default template. Thus, we can now choose what template to use in …
=> [1LP][RFR] modify snapshot testing

cfme/rest/gen_data.py, utils/rest.py
* use ``service_templates_ui`` for service creation
* use new ``get_vms_in_service`` function
{{pytest: -v --long-running -k "test_service_vm_subcollection or test_edit_service" cfme/tests/services/test_rest_services.py}}
=> [1LP][RFR] Unify service creation in REST API tests

cfme/intelligence/reports/reports.py, cfme/tests/containers/test_reports.py
{{ pytest: cfme/tests/containers/test_reports.py --use-provider cm-env2 -m 'not long_running_env' }}
- Align reports tests functionality to work with the recent widgetastic changes.
- Added a temporary workaround for cases we have row span greater that 1 column (e.g. in case of "Totals: ddd" column).
=> [1LP][RFR] Fix report tests + CannedSavedReport data workaround

requirements/frozen.txt, requirements/frozen_docs.txt
Mainly workaround for problem of ``stomp.py`` that can get stuck terminating
the subscription to the Polarion message bus.
Useful for our jenkins jobs that are submitting results to Polarion.
=> [1LP][RFR] Bump dump2polarion version

cfme/common/vm_console.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py
__Fixing__ File creation command 'touch blather' to make sure that RHV and RHOS HTML5 Remote consoles are receiving all characters correctly, otherwise sometimes RHOS and RHV Providers drop some characters resulting in the file not being created.
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider vsphere6-nested --use-provider default }}
=> [1LP][RFR] Making sure 'touch blather' command is sent to console correctly for RHOS and RHV

cfme/tests/control/test_actions.py
Purpose
__Fixing__ test_action_prevent_event because `power_control_from_cfme` in `cfme.cloud.instances` method requires `option` argument.
{{pytest: -v -k "test_action_prevent_event" --long-running --use-provider azure}}
=> [RFR] Fixed test_action_prevent_event for cloud instances

cfme/tests/containers/test_manageiq_ansible_users.py, utils/ansible.py
{{pytest: cfme/tests/containers/test_manageiq_ansible_users.py -v --use-provider cm-env2 }}
This fix allows running successfully the ansible-playbook command by creating a separated virt_env within the test run.
Sorry for somewhat an unorthodox solution, lots of bricks were lifted to find it.
https://stackoverflow.com/questions/45795480/import-error-when-running-an-ansible-playbook-with-a-python-module.
=> [1LP][RFR] Fixed virt_env problem for the ansible-playbook command

cfme/common/provider.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py, cfme/exceptions.py, cfme/tests/containers/test_labels.py
{{ pytest: cfme/tests/containers/test_labels.py --use-provider cm-env2 }}
- Added mgmt property to containers objects for API access.
- Getting bearer token and use it for the mgmt system.
- + get_bearer_token function  …
- Match Labalable class to use mgmt
- Removed redundant exceptions
=> [1LP][WIPTEST] Integrate wrapanapi containers

cfme/ansible/playbooks.py, cfme/cloud/availability_zone.py, cfme/cloud/flavor.py, cfme/cloud/instance/__init__.py, cfme/cloud/provider/__init__.py, cfme/cloud/stack.py, cfme/cloud/tenant.py, cfme/common/host_views.py, cfme/common/provider_views.py, cfme/common/vm_views.py, cfme/containers/node.py, cfme/infrastructure/datastore.py, cfme/infrastructure/host.py, cfme/infrastructure/provider/__init__.py, cfme/tests/openstack/infrastructure/test_provider.py, widgetastic_manageiq/__init__.py
We have a bunch of views which contain quadicons like Edit Tags/Manage Policies/etc. Those quadicons provide some info and can be clicked. 
This PR allows to use BaseEntity widget for interaction with such QuadIcons. Besides that, it has a BaseNonInteractiveEntitiesView which is added to mentioned above views and allows to get all quadicons there and play with them.
=> [1LP][WIP] Non Interactive Quadicons support + BaseNonInteractiveEntitiesView

cfme/configure/access_control.py, cfme/tests/configure/test_access_control.py
Resolve failure in the access control test
**test_edit_sequence_usergroups**
- Use VersionPick use appropriate locators for UpDownSelect widget
- Move widgetastic/navmazing code from test to access_control Group object
- Use PaginationPane to select a row from the checklist on the Access Control Evm Group page
{{pytest: -v -k "test_edit_sequence_usergroups"}}
=> [1LP][RFR] Fix access_control test_edit_seq_usergroups

cfme/tests/configure/test_access_control.py
Resolves the failing access_control tests:
**test_permissions_role_crud and test_permissions_vm_provisioning**
- Test was incorrectly logging in as admin instead of the test user when verifying role permissions
- When creating appropriate role permissions in 5.7, the default permissions don't have all child permissions select
**test_permission_edit**
- Corrected error where method was not passing a function reference to addfinalizer
{{pytest: -v -k "test_permissions_role_crud or test_permissions_vm_provisioning or test_permission_edit"}}
=> [1LP][RFR] Fix 3 failing access control tests

cfme/automate/__init__.py, cfme/automate/provisioning_dialogs.py, cfme/tests/automate/test_provisioning_dialogs.py
Conversion of automate.provisioning_dialog to widgetastic.
CRUD methods implemented, old 'change_type' method removed, this can be done through update method.
Modification of the 'type' attribute from tuples to a string of the UI value.
FIXES RHCFQE-2971
Run 15314 passed 57z and 58z provisioning dialog tests.
{{ pytest: cfme/tests/automate/test_provisioning_dialogs.py -v --long-running }}
=> [1LP][RFR] Convert automate.provisioning_dialogs to widgetastic

cfme/intelligence/reports/reports.py, cfme/tests/containers/test_tables_sort.py, widgetastic_manageiq/__init__.py
__Extending__ set_items_per_page pagination function to accommodate different CFME versions. 
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere6-nested --use-provider vsphere65-nested}}
=> [1LP][RFR] Adding version pick ability to pagination

scripts/cleanup_old_vms.py, scripts/ec2cleanup.py, scripts/template_upload_all.py, scripts/template_upload_ec2.py, scripts/template_upload_gce.py, scripts/template_upload_rhevm.py, scripts/template_upload_rhos.py, scripts/template_upload_scvmm.py, scripts/template_upload_vsphere.py, utils/log.py
Use logger to print all messages to stdout and to the log.
Within the scope of the `scripts` directory, and especially with those scripts run by CI infrastructure, we want to simultaneously write all info/debug/warning/error/exception messages both to stdout and to the logger provided by `utils.log.logger`.
These scripts can't/won't be tested by PRT for now, so I'm testing all of them locally before committing changes.
Adding basic logging import and console args where appropriate for the scripts that are scoped for this PR. 
Ignore the damn lint tool.
FIXES #4472
=> [RFR][NOTEST] Logging refactor for CI scripts

cfme/containers/provider/openshift.py
{{ pytest: cfme/tests/containers/test_labels.py --use-provider cm-env2 }}
We don't have to use the session token and we can just use the token from the config.
=> [RFR] Removed the grabbing of bearer token

cfme/containers/provider/__init__.py, cfme/containers/template.py, cfme/containers/volume.py, cfme/tests/containers/test_breadcrumbs.py
{{ pytest: cfme/tests/containers/test_breadcrumbs.py --use-provider cm-env2 }}
- Convert navigate_and_get_rows to widgetastic.
- TemplateAllView to inherit ContainerObjectAllBaseView.
=> [RFR] Convert navigate_and_get_rows to widgetastic

fixtures/provider.py
Parallelizer is not enough to take care of this; jenkins simply has to run limited to 1 provider and since there is really no reason not to have this as a default for non-parallelized (local) runs either, let's set it to 1.
=> [RFR][NOTEST] Make 1 provider the default limit

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
This is a new test for testing basic snapshot operations on a suspended vm.
First, I create a snapshot when the vm is running, then I suspend it and create a second snapshot [1]. While the vm is suspended, I try to revert to first snapshot and check the status of the vm (off). I then revert back to the second snapshot, check the status of the vm (suspended) and try to delete all the snapshots. ~~This is a bit tricky since I can't mask the NameError with wait_for, so I used try/except blocks.~~ Update: The NameError is now caught within Snapshot.exists.
[1] we can't create two snapshots when the vm is suspended: https://bugzilla.redhat.com/show_bug.cgi?id=1419872
=> [1LP][RFR] test snapshot operations on suspended vm

fixtures/xunit_tools.py
* updates blacklist so it matches also the new rhv41
* is more specific about what's supposed to be matched only in test parameters
=> [1LP][RFR] xunit_tools blacklist update

cfme/common/host_views.py, cfme/common/provider.py, cfme/common/provider_views.py, cfme/infrastructure/host.py, cfme/infrastructure/openstack_node.py, cfme/infrastructure/provider/openstack_infra.py, cfme/tests/openstack/infrastructure/test_host_lifecycle.py, cfme/tests/openstack/infrastructure/test_hosts.py
Adding tests for Openstack nodes' lifecycle operations: scale down, delete, register, introspect, provide, scale out.
Please no PRT run, any wrong thing might wreck your OSP environment. Added test_flag for avoid you of running this on your environments.
=> [1LP][RFR] Add Openstack Node lifecycle tests

cfme/tests/infrastructure/test_snapshot.py
This is a new test for testing basic snapshot operations on a powered off vm.
Snapshot create, revert and delete.
=> [1LP][RFR] test snapshot operations on powered off vm

cfme/tests/containers/test_manageiq_ansible_providers.py, utils/ansible.py
This adds SSL verification test to Add Providers and also fixes refresh timeout for one of the tests.
The test currently fails on PRT due to cfme_data.yml discrepancy but passes on our Jenkins
{{pytest: cfme/tests/containers/test_manageiq_ansible_providers.py -v --use-provider cm-env2 }}
=> [1LP][RFR] Add Providers with SSL

cfme/base/ui.py, cfme/configure/configuration/__init__.py, cfme/configure/configuration/analysis_profile.py, cfme/tests/configure/test_analysis_profiles.py, cfme/tests/control/test_compliance.py, cfme/tests/infrastructure/test_instance_analysis.py
Separate AnalysisProfile into its own module
Widgetastic conversion of the pages and CRUD
All tests in `cfme/tests/configure/test_analysis_profiles.py` should pass.
NOT Including test_compliance.py and test_instance_analysis.py because I slightly changed the yield_fixture there for an AnalysisProfile object, and the tests pretty much completely failed for unrelated reasons.
{{ pytest: -v --long-running cfme/tests/configure/test_analysis_profiles.py }}
=> [1LP][RFR] Convert AnalysisProfile to Widgetastic

cfme/tests/cloud_infra_common/test_snapshots_rest.py
Necessary changes when BZ 1466225 is fixed.
{{pytest: -v --long-running -k test_delete_snapshot_ cfme/tests/cloud_infra_common/test_snapshots_rest.py}}
=> [1LP][RFR] Tests changes for BZ 1466225

cfme/automate/explorer/domain.py, cfme/automate/explorer/namespace.py
{{pytest: cfme/tests/automate/ -v -k "(domain or namespace or lass or instance) and crud" --long-running }}
=> [1LP][RFR] Fix flash message checking in Automate Domain model

cfme/tests/containers/test_manageiq_ansible_providers.py
{{pytest: cfme/tests/containers/test_manageiq_ansible_providers.py -v --use-provider cm-env2 }}
This PR fixes a crash in Ansible Providers test.
It crashes on PRT due to a misconfiguration but passes on our Jenkins
=> [1LP][RFR] Fix for crashing Ansible Providers test

cfme/tests/ansible/test_embedded_ansible_rest.py
{{pytest: -v --long-running -k TestPayloadsRESTAPI cfme/tests/ansible/test_embedded_ansible_rest.py}}
=> [1LP][RFR] New REST API tests for configuration_script_payloads

cfme/tests/infrastructure/test_snapshot.py
New automation for snapshot area. Tests check the state of a VM after snapshot revert.
- when reverting from snapshot with memory created on running VM, state should be powered on
- when reverting from snapshot without memory created on running VM, state should be powered off
- when reverting from snapshot created on stopped VM, state should be powered off
=> [1LP][RFR] test vm state after revert snapshot

widgetastic_manageiq/__init__.py
Fix for tests which fail in upstream due to paginator error.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py}}
=> [1LP][RFR] js methods should check whether page is safe before/after their call

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
New test for the snapshot area.
In this one, I'm checking that we can't create snapshot with memory on powered off VM. First, I check if I can create snapshot with memory on powered on VM, which should succeed. Then I power down the VM and again try to create snapshot with memory. This should throw a NoSuchElementException, which I catch as an expected behaviour. The wait_for at the end is to double check that the snapshot on powered off VM was indeed not created.
All this will run only if current_version() >= 5.8. In 5.7, there is an unfixed bug that allows users to create snapshot with memory even on a powered off VM.
Included in this are changes in some of snapshot methods:
- ~~Snapshot.exists now catches also NameError~~ This was merged in another PR
- Snapshot.create now contains a …
=> [1LP][RFR] Test snapshot memory checkbox for powered off VM

cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
{{pytest: cfme/tests/containers/test_manageiq_ansible_custom_attributes.py -v --use-provider cm-env2 }}
Added setup providers fixture for each CA test to prevent Jenkins crashes
=> [1LP][RFR] ManageIQ Ansible Custom Attributes tests fix

cfme/tests/cloud_infra_common/test_tag_objects.py
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py}}
One tests failed because of old web_ui elements. I will get rid of it in next PR. 
Other failures not related to current PR
=> [1LP][RFR] Fix test_tag_objects

requirements/frozen.txt, requirements/frozen_docs.txt, requirements/template_docs.txt
Fixes bootstrap switch when used as a widget in a table, among other things. That's why the vm reconfigure test below.
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py -v --use-provider vsphere65-nested --long-running}}
=> [1LP][RFR] Bump wt-pf to 0.0.14 everywhere

cfme/cloud/provider/azure.py, docs/conf.py, requirements/frozen.txt
wrapanapi.azure is moved to rest. now it uses "azure" package. In order to resolve name resolution confict it was decided to rename wrapanapi.azure to msazure.
This PR should be merged when https://github.com/ManageIQ/wrapanapi/pull/169 gets merged.
{{pytest: cfme/tests/cloud cfme/tests/cloud_infra_common --use-provider=azure --long-running}}
=> [1LP][RFR] wrapanapi.azure method will be renamed to wrapanapi.msazure

cfme/services/requests.py
Increased waiting timeout because of very slow environment (pxe service catalog fails on timeout, request takes about 25-28 minutes to finish).
=> [RFR] Increased request waiting timeout

cfme/scripting/appliance.py, cfme/scripting/setup_ansible.py, utils/ports.py
Intent
In order to automate ansible configuring described in http://talk.manageiq.org/t/howto-setup-embedded-ansible/2291/8 a new option `setup_ansible` has been added for `miq appliance` cli tool.
Usage:
`miq appliance setup_ansible [APPLIANCE_IP] --license PATH_TO_LICENSE`
=> [1LP][RFR][NOTEST] Added 'setup_ansible' option for 'miq appliance' cli tool

cfme/cloud/keypairs.py, cfme/tests/cloud/test_keypairs.py, widgetastic_manageiq/__init__.py
Original conversion done before BaseEntitiesView was written, convert it over. So pretty.
Use BaseEntitiesView via common.vm_views.VMEntities, since it handles the version picking already.  Maybe those entities views are a bit more common than vm's.
Tests are fine on RHOS running locally. The CFME QE RHOS provider that was available for PRT has been unstable and removed, so we won't get PRT results.
Run 15737:
* 57z pass
* 58z failures from slow UI updates.
{{ pytest: -v --long-running --use-provider rhos7-ga cfme/tests/cloud/test_keypairs.py }}
=> [1LP][RFR] Update cloud.keypairs, use BaseEntitiesView

cfme/common/__init__.py, cfme/services/catalogs/catalog_item.py, cfme/tests/services/test_catalog_item.py
Standardize naming for view.form and view.entities
Maintain support for current implementation for any classes that are
using it already
Local tests for catalog_item tagging passed, waiting for PRT.
- 57z: passed
- 58z: **Unrelated** failure during test teardown when deleting catalog
{{ pytest: -v --long-running cfme/tests/services/test_catalog_item.py  -k "test_edit_tags or test_tagvis_catalog_items" }}
=> [1LP][RFR] Update WidgetasticTaggable, standard views/widgets

cfme/base/ui.py, cfme/configure/settings.py
cfme/configure/settings.py page was in web_ui, in this PR I have converted it to widgetastic.
{{pytest: -v -k 'test_cloud_grid_page_per_item or test_cloud_tile_page_per_item or test_cloud_list_page_per_item or test_infra_grid_page_per_item or test_infra_tile_page_per_item or test_infra_list_page_per_item or test_infra_report_page_per_item or test_infra_start_page or test_timezone_setting or test_timeprofile_crud or test_timeprofile_duplicate_name or test_timeprofile_name_max_character_validation or test_cloudimage_defaultfilters or test_cloudinstance_defaultfilters or test_infrastructurehost_defaultfilters or test_infrastructurevms_defaultfilters or test_infrastructuretemplates_defaultfilters or test_servicetemplateandimages_defaultfilters or …
=> [1LP][RFR] Converting settings page to widgetastic

cfme/control/explorer/actions.py
Often that test fails because Add button doesn't get active quick enough.
This PR should sort out that issue.
{{pytest: --use-provider=scvmm2016 cfme/tests/cloud_infra_common/test_events.py}}
=> [1LP][RFR] small fix for test_events

cfme/tests/ansible/test_embedded_ansible_actions.py
{{pytest: -v -k "test_control_action_run_ansible_playbook_in_requests" --long-running}}
=> [1LP][RFR] Added test test_control_action_run_ansible_playbook_in_requests

cfme/cloud/instance/__init__.py, cfme/common/host_views.py, cfme/common/vm.py, cfme/common/vm_views.py, cfme/infrastructure/datastore.py, cfme/infrastructure/host.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud/test_instance_power_control.py, cfme/tests/cloud_infra_common/test_discovery.py, cfme/tests/distributed/test_appliance_replication.py, cfme/tests/infrastructure/test_advanced_search_host.py, cfme/tests/infrastructure/test_datastore_analysis.py, cfme/tests/infrastructure/test_instance_analysis.py, cfme/tests/infrastructure/test_snapshot.py, cfme/tests/infrastructure/test_vm_power_control.py, cfme/tests/openstack/infrastructure/test_host_lifecycle.py, cfme/tests/test_db_restore.py, widgetastic_manageiq/__init__.py
vm/instance.find_quadicon method is widely used and doesn't allow to get rid of web_ui.QuadIcon. 
This PR intends to replace find_quadicon with widgetastic calls and updates all tests to use widgetastic Entity instead
=> [1LP][RFR] replacing vm/instance find_quadicon with widgetastic implementation

cfme/tests/control/test_actions.py
Purpose
__Fixing__ policy updating in test_action_cancel_clone.
{{pytest: -v -k "test_action_cancel_clone" --long-running --use-provider vsphere6-nested}}
=> [WIPTEST] Fixed test_action_cancel_clone

cfme/scripting/setup_ansible.py
Removed line firewall-cmd reload, this was reloading firewalld and clearing the added ports from iptables, preventing ports opening.
=> [1LP][RFR] Fix to enable embedded ansible script

cfme/cloud/instance/image.py, cfme/common/vm_views.py, cfme/fixtures/tag.py
Testing, no specific Image tests
Filtering pytest very specifically here to tests that actually import and use the Image navigation.
Well it looks like pretty much any test that is using Images is doing so with a collection of other cloud objects, and trying to do things like tagging or default view settings.
**In order for these tests to work on the collections of cloud objects, they need to be pretty heavily refactored, including the mixins that they're using, to work properly with the updated cloud objects.**
See PR #5296 for some initial work that goes in parallel with this PR to get things setup for consistent tag fixtures/testing across the framework.
This PR is a very good scope at the moment, and I'd really like to address the mixin (Taggable) refactoring to a GH issue, with …
=> [1LP][RFR] Convert cloud.instance.image to Widgetastic

cfme/tests/containers/test_chargeback_for_images.py, cfme/tests/containers/test_chargeback_for_projects.py
{{ pytest: cfme/tests/containers/test_chargeback_for_projects.py -m 'not long_running_env' --use-provider cm-env2 }}
Fix rate assignment in chargeback tests
=> [1LP][RFR] Fix chargeback rate assignment

cfme/tests/intelligence/reports/test_validate_chargeback_report.py
This is a follow up to https://github.com/ManageIQ/integration_tests/pull/4891 .
I'm adding an additional check for cloud providers through this PR.
PRT results
----------------------------
1)57.z: 
Tests skipped because of a BZ
2)58.z 
The tests passed for Azure on PRT.The tests will be skipped for GCE until BZ 1486529 is resolved.
The tests for also skipped for vsphere6, vsphere65, rhv41 because the cu-24x7 VM is not running on these providers.
=> [1LP][RFR] Chargeback support for cloud -2

scripts/azure_cleanup.py
Template format has been slightly changed after moving wrapanapi.azure to rest.
Comparison is done using "in" operation now instead of regexp.
So, asterisk shouldn't be present in templates now.
I'd use "test-" but there are cases when nics/pips are calles testblabla and test_blabla
=> [1LP][RFR] fixed azure search template

cfme/configure/settings.py
Add a widget for Configuration Management Providers.
This could be modeled much better with a wrapper widget for the ViewButtonGroups, so I wrote issue #5335.
For now we'll have to write widgets and maps for whatever tests use default view settings.
Testing passes locally, this is only called at the very end of test_order_tower_catalog_item, which may fail for other reasons.
Tests failing before the DefaultView call for unrelated reasons.
Reviewers can easily test this by running `miq shell`, and then:
```python
from cfme.configure.settings import DefaultView
DefaultView.set_default_view('Configuration Management Providers', 'List View')
```
{{pytest: -v --long-running --use-provider complete cfme/tests/services/test_config_provider_servicecatalogs.py::test_order_tower_catalog_item}}
=> [1LP][RFR] Update ViewDefault, add Configuration Management

cfme/tests/containers/test_configurable_menus.py
{{ pytest: cfme/tests/containers/test_configurable_menus.py --use-provider cm-env2 }}
Skipping monitoring test (5.9 feature)
=> [1LP][RFR] Skipping monitoring test (5.9 feature)

cfme/tests/control/test_actions.py
{{pytest: -v -k "test_action_prevent_vm_retire" --long-running --use-provider vsphere6-nested}}
=> [1LP][RFR] Added test test_action_prevent_vm_retire

cfme/tests/openstack/infrastructure/test_host_lifecycle.py
Skip host lifecycle tests because this functionality doesn't work for OSPd deployments  without mistral service
=> [1LP][RFR] added skipping of host lifecycle tests for ospd without mistral service

cfme/tests/intelligence/test_dashboard.py
Purpose
Added pdf downloading check for dashboard widgets https://bugzilla.redhat.com/show_bug.cgi?id=1461008. The test cannot be ran in PRT because it has blocker meta.
=> [1LP][RFR][NOTEST] Added pdf downloading check into test_widgets_operation

cfme/configure/access_control.py
Fixed the NoSuchElementException which was occurring due to no having a is_displayed and form being filled before showing up. 
Note: This PR fixes just the Navigation & NoSuchElementException issue in setting up Quotas. 
The PRT might fail due to other error, this solves issue in setting up quota and removes the blocker on writing its other tests. 
{{ pytest: cfme/tests/infrastructure/test_infra_quota.py -vvvv }}
=> [RFR][1LP] Fixed NoSuchElementException in setting up Quotas

cfme/services/catalogs/__init__.py, cfme/services/catalogs/ansible_catalog_item.py, cfme/tests/ansible/test_embedded_ansible_services.py
Intent
`test_service_ansible_playbook_order_pass_extra_vars` renamed to `test_service_ansible_playbook_pass_extra_vars`. Also from now it has two parameters: provisioning and retirement.
{{pytest: -v -k "test_service_ansible_playbook_pass_extra_vars or test_service_ansible_playbook_plays_table" --long-running}}
=> [1LP][RFR] Refactored test_service_ansible_playbook_order_pass_extra_vars

cfme/tests/configure/test_visual_cloud.py, cfme/tests/configure/test_visual_infra.py
Fixed failure related to quadicon in test_visual_cloud.py and test_visual_cloud.py
{{pytest: -v -k 'test_cloudprovider_noquads or test_infraprovider_noquads or test_host_noquads' }}
=> [1LP][RFR]Fixing test case failure for quadicon

cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/provider/__init__.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py, cfme/tests/containers/test_start_page.py
{{ pytest: cfme/tests/containers/test_search_bar.py cfme/tests/containers/test_start_page.py --use-provider cm-env2 }}
ContainerObjectAllBaseView implementation was wrong and is_displayed didn't work properly in the container objects.
=> [1LP][RFR] Fix test_start_pages & test_search_bar

cfme/configure/settings.py, cfme/tests/containers/test_table_views.py
{{ pytest: cfme/tests/containers/test_table_views.py --use-provider cm-env2 }}
- Fix test_table_views.py
- Added containers group buttons to settings.DefaultView
Note: I'd change the design of DefaultView/DefaultViewForm and as first change the lookup to be more hierarchical (but this requires a big refactoring all over the tests). e.g.
```python
look_up = {
'Containers': {
'Nodes': 'container_nodes',
'Pods': 'container_pods',
},
'Services': {...}
}
```
=> [RFR] Fix default containers views

cfme/common/vm.py, cfme/common/vm_views.py
vm's state is stored in style attr in 5.8 and img/src in 5.7.  This PR fixes this case.
{{ pytest: --long-running cfme/tests/infrastructure/test_vm_power_control.py }}
=> [1LP][RFR] fixing entity data for vms/instances in 5.7

cfme/cloud/provider/__init__.py, cfme/common/provider.py, cfme/containers/provider/__init__.py, cfme/infrastructure/provider/__init__.py, cfme/middleware/provider/__init__.py, requirements/frozen.txt, requirements/frozen_docs.txt
Tying views with each provider class isn't good idea. Especially when those views are already defined in navmazing destinations. 
This PR intends to replace such predefined views with new navmazing feature Navigate->get_class() method.
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/middleware/test_middleware_provider.py cfme/tests/containers/test_ssl_providers.py }}
=> [RFR] replacing provider views with navigation.get_class

cfme/common/vm.py
Pulled this out of #5314 where I found it was causing test failures.  refresh provider relationships and the UI browser in `BaseVM.wait_to_appear()`
58z pass, true positive
57z pass, true positive
upstream waiting
{{pytest: --use-provider ec2west -k "test_delete_instance_appear_after_refresh" cfme/tests/cloud/test_delete_cloud_object.py }}
=> [1LP][RFR] Update common.vm.wait_for_appear, provider+browser refresh

cfme/infrastructure/cluster.py, cfme/infrastructure/provider/__init__.py
{{ pytest: cfme/tests/infrastructure/test_providers.py  cfme/tests/infrastructure/test_timelines.py cfme/tests/infrastructure/test_cluster_analysis.py }}
1. This PR intends to remove web_ui traces from infra provider. This is necessary for successful testing 5.9/upstream.
2. It refactors clusters in order to use BaseEntitiesView instead of table.
=> [1LP][RFR] Get rid of web_ui in infra provider

fixtures/pytest_store.py
Not sure why this was ever needed given it is a property it should
be called at the appropriate time
=> [1LP][RFR] Removing SSH call

cfme/infrastructure/virtual_machines.py
This is a quick fix for `Snapshot.delete`.
After creating a VM on a RHV provider, there already is one RHV-created snapshot, the default one. When we create another snapshot using automation, it does get created, but it is NOT active and it is NOT highlighted. This behaviour differs from what we can see when working with vmware providers, where most of snapshot testcases are runnning, and is causing failures.
The fix is simple, I make sure we are currently on the snapshot we created and not on the snapshot that gets created by RHV. This way, it works with RHV as well as vsphere providers.
PS: this is only a quick remedy for jenkins failures. For the future, more complex refactoring in snapshot area will be needed. I need to change the way we interact with snapshots so that these kind of …
=> [1LP][RFR] Fix Snapshot.delete for RHV provider

cfme/infrastructure/virtual_machines.py
This is a quick fix for `Snapshot.active` property. Originally, this returned False only if the `CandidateNotFound` exception occurred, meaning it did not return False if the snapshot was there, but was not active.
After this fix, it returns False correctly even in case the snapshot is there, but is not active, which is what we want.
=> [1LP][RFR] Add return value to Snapshot.active

cfme/configure/settings.py, cfme/services/myservice/__init__.py, cfme/services/myservice/ui.py, cfme/services/requests.py, cfme/tests/services/test_provision_stack.py
Removed some originally committed code to add a web_ui.Quadicon.click() method, screw that.
Small tweaks to services/myservice, biggest being the use of RequestsView for redirect validation.
* 57z: 75% passing, test_remove_template_provisioning is failing when requests succeed, working with @sshveta on finding/writing BZ, not really related 
* 58z: 88% passing, same test failure, but only on one provider here
* upstream: uncollected, stream ignored.
=> [1LP][RFR] Update MyService.ui, services.Request, and settings.DefaultView, small fixes

cfme/infrastructure/deployment_roles.py, widgetastic_manageiq/__init__.py
This PR inclue Comparison tool bar actions widges:
> Attribute Selector
> Mode Selector
> View Selector
Which will be useful in all model pages comparison view as well as drift pages.
=> [1LP][RFR] Comparison Toolbar Actions

cfme/configure/access_control.py, cfme/exceptions.py, cfme/tests/configure/test_access_control.py
This PR updates these tests so that they all call the widgetastic methods and adds a new exception (RBACOperationBlocked) that will be thrown when an action(create, delete, edit) is blocked due to operating on an object that is immutable (default user, group, role).  Tests can now catch RBACOperationBlocked without having to rely on checking for a specific flash message to see if RBAC allowed an operation.  The state of the page will not be modified so a test can check the page elements after the exception
{{pytest: -v -k 'test_delete_default_group or test_delete_default_roles or test_delete_default_user or test_delete_group_with_assigned_user or test_delete_roles_with_assigned_group or test_edit_default_group or test_edit_default_roles or test_edit_sequence_usergroups or …
=> [RFR][1LP] Use widgetastic automation for access control tests and resolve test failures on CFME default users/groups/roles

cfme/fixtures/service_fixtures.py, cfme/infrastructure/virtual_machines.py, cfme/provisioning.py, cfme/services/requests.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/ansible/test_embedded_ansible_services.py, cfme/tests/cloud/test_provisioning.py, cfme/tests/control/test_actions.py, cfme/tests/infrastructure/test_cloud_init_provisioning.py, cfme/tests/infrastructure/test_host_provisioning.py, cfme/tests/infrastructure/test_infra_quota.py, cfme/tests/infrastructure/test_iso_provisioning.py, cfme/tests/infrastructure/test_provisioning.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_pxe_provisioning.py, cfme/tests/infrastructure/test_vm_clone.py, cfme/tests/infrastructure/test_vm_migrate.py, cfme/tests/services/test_add_remove_vm_to_service.py, cfme/tests/services/test_cloud_service_catalogs.py, cfme/tests/services/test_config_provider_servicecatalogs.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_iso_service_catalogs.py, cfme/tests/services/test_myservice.py, cfme/tests/services/test_operations.py, cfme/tests/services/test_provision_stack.py, cfme/tests/services/test_pxe_service_catalogs.py, cfme/tests/services/test_request.py, cfme/tests/services/test_service_catalogs.py, cfme/tests/services/test_service_manual_approval.py
Using BaseCollection and BaseEntity for Request itself
{{pytest: -v --long-running --use-provider complete cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/control/test_actions.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/infrastructure/test_infra_quota.py
cfme/tests/infrastructure/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_dialog.py
cfme/tests/infrastructure/test_vm_clone.py
cfme/tests/infrastructure/test_vm_migrate.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_different_dialogs_in_catalogs.py …
=> [1LP][RFR] Update services.requests, add RequestCollection

cfme/control/explorer/policies.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/cloud_infra_common/test_events.py, cfme/tests/control/test_actions.py, cfme/tests/control/test_alerts.py, cfme/tests/control/test_bugs.py, cfme/tests/control/test_compliance.py, cfme/tests/infrastructure/test_instance_analysis.py
Nested view of toolbar with configuration dropdown
{{pytest: -v --long-running --use-provider complete  --collect-only cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/cloud/test_cloud_object_tag_visibility.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/configure/test_access_control.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_bugs.py
cfme/tests/control/test_compliance.py
cfme/tests/infrastructure/test_instance_analysis.py}}
=> [RFR] Add toolbar to explorer/policies/EventDetailsView

cfme/common/vm_console.py
__Extending__ vm_console class to show some logging and send "\n" if the screen_text is coming out to be blank, which happens with RHOS7-GA Cirros VMs, they go into screensaver mode causing a blank "Black" screen to be displayed and test fails even if console was displayed. Sending "\n' causes screen to wake up.
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider rhos7-ga --use-provider vsphere6-nested --use-provider rhv41}}
=> [1LP][RFR] Minor fixes which will help failing tests pass

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
This adds waiting for completion of delete action for snapshots. The `Snapshot.delete` method did not wait for the snapshot to be actually deleted, it just initiated the action. This required changes in some of the snapshot tests that were checking for successful deletion.
I've decided not to add waiting to `Snapshot.delete_all`, since this method can not wait for deletion of all the snapshots that are currently on a test VM. It could wait for the snapshot that it has been called on, but this would not ensure the deletion of all snapshots. I modified the tests accordingly.
This solves the problem that PR #5422 has been originally created for.
PRT results of changed tests:
- test_snapshot_crud: PASS for both vsphere and RHV providers
- test_delete_all_snapshots: PASS
- …
=> [1LP][WIP] Add wait to Snapshot.delete

cfme/configure/settings.py, cfme/tests/configure/test_timeprofile.py
Implementing changes in test case related to cfme/tests/configure/timeprofile.py to work with new cfme/configurewidgetastic/settings.py page.
{{pytest: -v -k 'test_timeprofile_description_required_error_validation or test_hours_required_error_validation or test_days_required_error_validation' }}
=> [1LP][RFR] Implementing changes in the test case to use the new setting page

cfme/containers/provider/__init__.py, cfme/tests/containers/test_provider_configuration_menu.py
{{ pytest: cfme/tests/containers/test_provider_configuration_menu.py cfme/tests/containers/test_provider_configuration_menu.py --use-provider cm-env2 }}
- Get rid of Quadicons and use widgetastic.
- test_provider_configuration_menu has been updated accordingly.
=> [1LP][RFR] Getting rid of Quadicons

cfme/tests/infrastructure/test_vm_power_control.py
Fixing `check_power_option` function's Value Error as `vm.GUEST_RESTART` does not exist in `must_be_available` dictionary.
=> [1LP][RFR] Fix value error

cfme/tests/infrastructure/test_infra_tag_filters_combination.py
Replace Cluster to ClusterCollection for cfme/tests/infrastructure/test_infra_tag_filters_combination.py, fix for test
{{pytest: -v -k test_tagvis_tag_datacenter_combination --long-running}}
=> [1LP][RFR] Replace Cluster to ClusterCollection for test_infra_tag_filters_combination.py

cfme/tests/ansible/test_embedded_ansible_rest.py, cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/infrastructure/test_config_management_rest.py, cfme/utils/rest.py
* check tasks that corresponds to the action using ``assert_response``
* use more readable ``.wait_not_exists`` where possible
{{pytest: -v --long-running --use-provider vshere65-nested cfme/tests/ansible/test_embedded_ansible_rest.py cfme/tests/cloud_infra_common/test_snapshots_rest.py cfme/tests/infrastructure/test_config_management_rest.py}}
**PRT**
the ansible errors are not related to changes in this PR
=> [1LP][RFR] Extend assert_response to check corresponding task

cfme/tests/ansible/test_embedded_ansible_crud.py
Removed @smoke as the test provisions an appliance from sprout which it cannot do during smoke testing on jenkins.
=> [RFR] Removed smoke assignment as it provisions from sprout

cfme/cloud/provider/openstack.py, cfme/common/provider_views.py
Provide a possibility of adding OSP cloud provider on keystone v3 api
PRT run is just to ensure that old configs still work
{{pytest: cfme/tests/openstack/cloud --use-provider rhos7-ga}}
=> [1LP][RFR] Add support of keystone v3 to Openstack Cloud provider

cfme/cloud/stack.py, cfme/cloud/tenant.py, cfme/common/vm.py, cfme/infrastructure/virtual_machines.py, cfme/services/myservice/ui.py, cfme/storage/object_store.py, cfme/tests/cloud/test_delete_cloud_object.py, cfme/tests/cloud_infra_common/test_tag_objects.py, cfme/tests/configure/test_access_control.py, cfme/tests/configure/test_default_views_cloud.py, cfme/tests/configure/test_default_views_infra.py, cfme/tests/control/test_bugs.py, cfme/tests/infrastructure/test_host.py, cfme/tests/openstack/cloud/test_instances.py, cfme/tests/openstack/infrastructure/test_host_power_control.py, cfme/tests/openstack/infrastructure/test_hosts.py
{{pytest: cfme/tests/cloud/test_stack.py cfme/tests/control/test_bugs.py cfme/tests/infrastructure/test_advanced_search_vms.py cfme/tests/storage/test_object_store.py cfme/tests/cloud/test_delete_cloud_object.py cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/configure/test_access_control.py cfme/tests/configure/test_default_views_cloud.py cfme/tests/configure/test_default_views_infra.py cfme/tests/infrastructure/test_host.py cfme/tests/openstack/cloud/test_instances.py cfme/tests/openstack/infrastructure/test_host_power_control.py cfme/tests/openstack/infrastructure/test_hosts.py}}
=> [1LP][RFR] expelling remaining quadicons from tests and classes

cfme/ansible/repositories.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/cloud/test_provisioning.py, cfme/tests/cloud_infra_common/test_events.py, cfme/tests/cloud_infra_common/test_genealogy.py, cfme/tests/cloud_infra_common/test_power_control_rest.py, cfme/tests/cloud_infra_common/test_retirement.py, cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/control/test_actions.py, cfme/tests/control/test_alerts.py, cfme/tests/control/test_compliance.py, cfme/tests/infrastructure/test_provisioning_rest.py, cfme/tests/infrastructure/test_scvmm_specific.py, cfme/tests/infrastructure/test_snapshot.py, cfme/tests/infrastructure/test_vm_power_control.py, cfme/tests/infrastructure/test_vm_reconfigure.py, cfme/tests/perf/workloads/test_provisioning.py, fixtures/provider.py
This goes with a CFME QE YAML merge request (# 297) that implements a 'templates' section for all providers, with 'small_template', 'big_template', etc, as relevant for the different providers.
The pairing to that is updating the `_get_template` method that supplies all of of the `small_template`, `big_template`, etc fixtures, and updating all of the tests to handle these fixtures providing a template AttrDict instead of just the template name.
I am not addressing test failures directly here. I've created PRs #5400, #5401, #5429, #5413, #5384 to fix tests/modules that I found had bugs during testing of this PR.
{{pytest: --long-running --use-provider complete}}
=> [1LP][RFR] Update Tests for Templates Change in Yaml

cfme/configure/configuration/server_settings.py
__Fixing__ Configuration because it is currently doing looking for name in CONSOLE_TYPES which is incorrect and causing Console Test Failures. It should be looking for Value in CONSOLE_TYPES. 
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider vsphere6-nested }}
=> [1LP][RFR]Correcting configuration for VMware Console

cfme/tests/services/test_cloud_service_catalogs.py
{{pytest: -v --long-running --use-provider rhos7-ga cfme/tests/services/test_cloud_service_catalogs.py }}
=> [1LP][RFR] Fix test_cloud_service_catalogs, call is_succeeded

cfme/ansible/repositories.py, cfme/tests/ansible/test_embedded_ansible_basic.py
Add method that's used in a test in catalog_item creation.
Works fine locally
Run 16506: Dropdown was disabled in UI for adding ansible repository. I saw this locally, and it cleared when I re-ran the test. There may be a UI bug here.  Continuing to fail on re-runs of the test.
{{pytest: -v --use-provider complete --long-running cfme/tests/ansible/test_embedded_ansible_basic.py::test_control_add_ansible_playbook_action_invalid_address}}
=> [1LP][RFR] Add ansible.repository.as_fill_value method

cfme/services/myservice/ssui.py
Added `wait_for` to `update` method of a service so it won't fail on slow environment.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py }}
=> [1LP][RFR] Added wait_for to update method

cfme/intelligence/reports/reports.py
Fixing `navigate` method as now `"Info"` does not gives desired page of report's information.
Changing `"Info"` to `"Details"` fixes it and `cfme/tests/intelligence/reports/test_views.py` `test_report_view` passes.
{{pytest:  -v --long-running cfme/tests/intelligence/reports/test_views.py }}
=> [1LP][RFR] Fix for report does not getting selected

cfme/containers/node.py
{{pytest: cfme/tests/containers/test_relationships.py}}
Fix node instantiation in get_random_instances().
Complete this PR: https://github.com/ManageIQ/integration_tests/pull/5479
=> [RFR] Fix get random instances

cfme/infrastructure/datastore.py, cfme/tests/configure/test_visual_infra.py
3 test case related to quadicon were failing after conversion of setting page to widgetastic. In this PR I have added entities for datastore and fixed other failing test cases.
{{pytest: -v -k 'test_datastore_noquads or test_vm_noquads or test_template_noquads' }}
=> [1LP][RFR]Quadicon related fix

cfme/automate/service_dialogs.py
{{pytest: -v --long-running cfme/tests/services/test_service_catalogs.py }}
temporary fix for the dialog UI selenium bug . 
Filling the label field twice.
=> [1LP][RFR] Dialog selenium UI bug fix

cfme/common/vm_views.py, cfme/tests/cloud/test_provisioning.py
Cloud provivioning tests with selected tag
{{pytest: cfme/tests/cloud/test_provisioning.py -v -k 'test_provision_from_template or test_cloud_provision_with_tag' --long-running }}
=> [1LP][RFR] Cloud provision with tag test

cfme/modeling/base.py, cfme/utils/appliance/__init__.py
So we got talking about how just instantiating a collection wasn't always enough and indeed there were some collection objects that already take some secondary arguments which they use for filtering. This would allow you to have a collection object for VirtualMachines, that only listed virtual machines for a particular provider.
The issue is the in order to get the BaseCollection, we had to make all of the constructors the same and since we wanted to get it via the appliance,  we had introduced this kind of methodology
```python
appliance.collections.virtualmachines.all
```
Which would return for you a list/iterator of all VirtualMachine objects that the appliance has access to. However, even though the Collection may look like this:
```python
class …
```
=> [1LP][RFR] Filter collections attrs

cfme/utils/tests/test_soft_assert.py, fixtures/soft_assert.py
This is quick fix. soft_assert fixture needs deeper refactoring later on. 
{{pytest: cfme/utils/tests/test_soft_assert.py}}
=> [1LP][RFR] soft_assert fix

cfme/fixtures/service_fixtures.py, cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py
As discussed with @psav and @sshveta, this makes the ``dialog`` fixture use REST API as it's more reliable than the UI.
{{pytest: -v --long-running cfme/tests/services/test_service_catalogs.py}}
**PRT**
Some timeout errors and failed soft asserts due to timeout errors, nothing related to dialog creation.
=> [1LP][RFR] Dialog fixture using REST API

cfme/tests/services/test_rest_services.py
{{pytest: -v --long-running -k TestServiceOrderCart cfme/tests/services/test_rest_services.py}}
=> [RFR] Adds new tests for /api/service_orders/cart

cfme/tests/cli/test_appliance_console.py
Smoke test was randomly failing, changed the collection method of command output to fix the issue.
{{pytest: -v test_appliance_console.py::test_black_console}}
=> [1LP][RFR] Fix to test_appliance_console smoke test

cfme/rest/gen_data.py
Service provisioning generates service with names that contains timestamp of provisioning .
It is difficult to assert for service names containing these random timestamps .
So as a work around the dialog in use should have element name = "service_name" 
so that service name can be overridden by the value provided while ordering the service .
Hence some changes in dialog data .
@mkoura : Please check once
=> [1LP][RFR]REST dialog change

cfme/configure/access_control.py, cfme/tests/configure/test_access_control.py
PR #4974 added an RBACOperationBlocked exception that will be thrown whenever an operation is performed but blocked due to permissions. This test was mistakenly left out of that update. This moves the flash message check out of the test and adds Group.delete() where it will be checked against a list of messages that specify that the delete operation was blocked
{{pytest: -v -k 'test_delete_group_with_assigned_user or test_delete_default_group or test_group_crud'}}
=> [1LP][RFR] Update test_delete_group_with_assigned_user to catch RBACOperationBlocked exception

cfme/cloud/instance/__init__.py
The super() call wasn't resulting in the correct object, raising an
exception on not finding in_cloud_instances property. Changed to a
direct self.in_cloud_instances call
Updated InstanceDetailsView.is_displayed to check entities.relationships
instead of no-longer-implemented relationships widget.
=> [1LP][RFR] Fix cloud.instance details view and nav

cfme/tests/ssui/test_ssui_myservice.py
__Extending__ test_ssui_myservice Adding Websocket fixture to enable websocket server role, for vm conole tests that are to be added soon. Adding the role to pytest.mark.meta, next to +automate would not work because the fixture adding provider will disable the websocket role after pytest has already enabled the role, hence need separate fixture to re-enable websocket role.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py  }}
=> [1LP][RFR] Adding Websocket fixture to enable websocket server role

cfme/services/requests.py, cfme/tests/infrastructure/test_provisioning.py
This is kinda hackish, but @mfalesni identified a failure where after editing a request navigation failed.
I believe the core failure is not in updating the description as the request is edited to change some values (number of vms), but because the description was never set because only `cells` was passed to the Request constructor.
RHCFQE-4868
* 57z: webdriver exceptions during smtp setup, not related to these change, test_operations passed
* 58z: success
* upstream: Requests table isn't recognized/found in xpath, larger bug at play.
{{pytest: cfme/tests/infrastructure/test_provisioning.py cfme/tests/services/test_operations.py --use-provider vsphere6-nested --use-provider ec2west --long-running -v }}
=> [1LP][RFR] Update request, get description from cells

cfme/cloud/instance/image.py, cfme/common/__init__.py, cfme/common/vm.py, cfme/infrastructure/virtual_machines.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/ansible/test_embedded_ansible_services.py, cfme/tests/cloud/test_keypairs.py, cfme/tests/cloud_infra_common/test_tag_visibility.py, cfme/tests/control/test_actions.py, cfme/tests/infrastructure/test_infra_object_tag_visibility.py, cfme/tests/infrastructure/test_instance_analysis.py, widgetastic_manageiq/__init__.py
Update SummaruTable  and SummaryForm widgets to handle multiple tags on details page.
Update VM, Template classes to use WidgetasticTaggable
{{pytest: -v -k 'test_control_action_run_ansible_playbook_in_requests or test_service_ansible_playbook_tagging or test_keypair_add_and_remove_tag or test_tag_vis_vm or test_tagvis_infra_object' --long-running}}
PRT: some of test_tagvis_infra_object tests can fail but those will be refactored this sprint to be more stable
=> [1LP][RFR] get_tag() multiple tags handling + vm, template classes update

cfme/scripting/disable_bytecode.py
this is necessary since based on virutalenv setup usercustomize may be disabled
after my last system upgrade and venv remake i started to see bytecode,
applying this change fixed it
ref #4936 @vatsalparekh this should match what you see
due to a minor system difference the issue was hidden
=> [RFR] disable_bytecode: switch to sitecustomize

scripts/image_upload_glance.py
Script to upload iso/ova/qcow images to Glance server.
I have tested the script locally.
Usage:
scripts/image_upload_glance.py --image cfme-rhevm-5.8.2.1-1.x86_64.qcow2 \
--image_name_in_glance cfme-5821.qcow2 \
--provider glance11
=> [1LP][RFR] Script to upload images to Glance

cfme/tests/control/test_actions.py
Purpose
`test_action_create_snapshot_and_delete_last` and `test_action_create_snapshots_and_delete_them` were not converted to collections.
{{pytest: -v -k "test_action_create_snapshot_and_delete_last or test_action_create_snapshots_and_delete_them" --long-running --use-provider vsphere6-nested}}
=> [1LP][RFR] Fixed control action tests which weren't converted to collections

cfme/tests/cli/test_evmserverd.py, cfme/utils/appliance/__init__.py, cfme/utils/ssh.py
There are tests which kill podified applience by stopping evmserverd, etc. This happens because those don't add finalizers.
=> [1LP][RFR] fixes for tests which don't correctly restore appliance when fail

cfme/configure/settings.py, cfme/infrastructure/virtual_machines.py, cfme/tests/configure/test_default_views_infra.py
Adding new test case for checking the working of vm visibility in explorer tree option on the setting page.
{{pytest: -v -k 'test_vm_visibility_off or test_vm_visibility_on' }}
=> [1LP][RFR] Adding new test cases for testing of Vm visibility in explorer treeview

cfme/fixtures/service_fixtures.py, cfme/tests/ssui/test_ssui_myservice.py
__Extending__ order_catalog_item_in_ops_ui fixture to accept 'console_test' parameter so that I can use the same fixture for Console tests in SSUI and any other test in SSUI. The difference that this fixture will make when passed 'console_test' parameter is that, it will choose the console_template from templates section of yaml rather than template sub-section of Provisioning section of yamls.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console'  }}
=> [1LP][RFR] Ability to choose template for console tests by parametarizing the order_catalog_items_in_ops_ui

cfme/cloud/availability_zone.py, cfme/cloud/flavor.py, cfme/cloud/instance/__init__.py, cfme/cloud/instance/image.py, cfme/cloud/keypairs.py, cfme/cloud/provider/__init__.py, cfme/cloud/stack.py, cfme/cloud/tenant.py, cfme/common/__init__.py, cfme/infrastructure/cluster.py, cfme/infrastructure/datastore.py, cfme/infrastructure/host.py, cfme/infrastructure/provider/__init__.py, cfme/infrastructure/resource_pool.py, cfme/infrastructure/virtual_machines.py, cfme/networks/balancer.py, cfme/networks/cloud_network.py, cfme/networks/network_port.py, cfme/networks/network_router.py, cfme/networks/provider/__init__.py, cfme/networks/security_group.py, cfme/networks/subnet.py, cfme/services/catalogs/catalog.py, cfme/services/catalogs/orchestration_template.py, cfme/storage/manager.py
Move common "EditTagsFromDetails" navigation step to WidgetasticTaggable class
Should be merged after https://github.com/ManageIQ/integration_tests/pull/5425
{{pytest: -v -k 'test_tagvis_cloud_object or test_tagvis_infra_object'}}
=> [1LP][RFR]EditTags navigation steps cleanup/move

cfme/tests/configure/test_access_control.py
BZ 1487199 Logins fail in version >= 5.8.2 when they have an uppercase character in the username. This fix is planned for 5.9 so we need to expand the BZ check to versions from 5.8.2 to < 5.9
{{pytest: -v -k 'test_user_login or test_current_user_login_delete or test_user_change_password'}}
=> [1LP][RFR] Expand BZ1487199 check to versions between 5.8.2 < 5.9

cfme/services/myservice/__init__.py, cfme/services/myservice/ssui.py, cfme/tests/ssui/test_ssui_myservice.py, widgetastic_manageiq/__init__.py
__Adding tests__ for feature VM Console in SSUI. In this PR, actual test is not added, but the groundwork for being able to navigate to the "Access" Dropdown of a service and clicking "VM Console" from the dropdown is done. 
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' }}
=> [1LP][RFR] Open vm console ssui

cfme/common/vm_views.py
__Fixing__ tests which were filling provisioning tabs. right now each 2nd test was failing because of 
some JS issues. https://projects.engineering.redhat.com/browse/RHCFQE-4901 
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py --long-running --use-provider complete}}
=> [1LP][RFR]workaround for provisioning tabs filling

cfme/scripting/conf.py
Changed default behavior from raising yayclCryptError on exising
decrypted yaml, to printing a message and exiting cleanly.
New option --skip/--no-skip is a boolean flag to pass or raise the
exception for YayclCryptError with 'overwrite' in the message.
=> [1LP][RFR] Update miq conf decrypt, suppress exception

cfme/infrastructure/virtual_machines.py
This is a fix for `Snapshot.delete` and `Snapshot.delete_all` methods for cfme version 5.9. The flash messages changed from:
"Remove Snapshot initiated for 1 VM and Instance from the CFME Database"
and
"Remove All Snapshots initiated for 1 VM and Instance from the CFME Database"
to:
"Delete Snapshot initiated for 1 VM and Instance from the CFME Database"
and
"Delete All Snapshots initiated for 1 VM and Instance from the CFME Database"
I used `version.pick` instead of widgetastic `VersionPick` because I don't want to convert whole file to use widgetastic right now, and I want to be consistent with what is already used.
{{pytest: -v --long-running -k "test_snapshot_crud or test_delete_all_snapshots"}}
=> [1LP][RFR] Snapshots in 5.9: add version.pick for flash message

cfme/tests/infrastructure/test_snapshot.py
This is a fix for a snapshot test `test_memory_checkbox`. Two things have been changed:
- line 74: added random alphanumeric part to snapshot description. Reason: when using RHV provider, we can't create snapshot with name, only with description. This is RHV-provider-specific and I can't do anything about it. The name of the created snapshot, that is displayed in CFME UI, is then created from the description. Without the fix, when creating two snapshots, they would have the same name and cause errors when checking for existence. With the fix, every snapshot has different name, as it is with snapshots created on different provider than RHV.
- line 85: added `not`. This is my mistake that I didn't notice first time around. The snapshot needs to have a name when it is created on a provider …
=> [1LP][RFR] Fix test_memory_checkbox

cfme/automate/explorer/instance.py, cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py
test is trying to get ordered service name from request message, but was
adding in the template name, which isn't present in 58z
As @mkoura suggested, get the dialog name from the request options, this is the service name.
RHCFQE-4905
* **58z 75% passing**
There are 2 failures in 58z that I'd like to leave to @mkoura if he's alright with that. This PR fixes ~10 failures in the rest test in the latest builds because of UI changes and framework collections changes.
Limiting PRT to test cases that were modified
{{pytest: cfme/tests/services/test_rest_services.py --long-running -v -k "test_order_single_catalog_item or test_order_multiple_catalog_items or test_order_catalog_bundle or test_order_manual_approval or test_user_item_order or test_order_cart or test_power_service" }}
=> [1LP][RFR] Update services/test_rest_services, service names and collection fixtures

cfme/tests/infrastructure/test_host_provisioning.py
It turned out that template tester fails due to absent web_ui provisioning form. 
This PR should sort that issue out.
=> [1LP][RFR] removed old provisioning form from test_host_provisioning

cfme/tests/infrastructure/test_providers.py
This test is no longer valid and is uncollected on versions > 5.4.0.0.24
=> [1LP][RFR] Removing outdated test test_ip_required_validation

cfme/tests/test_rest.py
{{pytest: -v -k test_attributes_present cfme/tests/test_rest.py}}
=> [1LP][RFR] Blocker and uncollecting changes for test_attributes_present

cfme/storage/volume.py, cfme/tests/storage/test_volume.py
typo, collections are plural
FIXES RHCFQE-5229
{{pytest: cfme/tests/storage/test_volume.py --long-running --use-provider rhos7-ga}}
=> [1LP][RFR] Update tests.storage.test_volume, use collections

cfme/networks/cloud_network.py, cfme/networks/network_router.py, cfme/networks/subnet.py, cfme/networks/views.py, cfme/tests/openstack/cloud/test_networks.py, cfme/tests/openstack/infrastructure/test_networks.py
Added tests for Openstack Cloud provider networks, subnets and routers with corresponding naviagtions and views.
Edit subnet fails by [BZ#1467725](https://bugzilla.redhat.com/show_bug.cgi?id=1467725)
Delete network fails by [BZ#1502736](https://bugzilla.redhat.com/show_bug.cgi?id=1502736)
{{pytest: cfme/tests/openstack/cloud/test_networks.py cfme/tests/openstack/infrastructure/test_networks.py --use-provider rhos7-ga}}
=> [1LP][RFR] add Openstack networks tests

cfme/common/vm.py, cfme/common/vm_console.py, cfme/fixtures/service_fixtures.py, cfme/services/myservice/ssui.py, cfme/tests/ssui/test_ssui_myservice.py
__Updating test and other files__ to be able to handle the VM Console opening for SSUI. I have tried to use existing HTML5 console code by slight modification to achieve DRY.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' }}
=> [1LP][RFR] Handling vm console opening in SSUI and returning console handle to the test

cfme/tests/services/test_rest_services.py
{{pytest: -v --long-running -k test_create_cart cfme/tests/services/test_rest_services.py}}
=> [RFR] changes to test_create_cart after BZ 1493785 fix

cfme/services/myservice/ssui.py
__Fixing__ access to dict provisioning_data since PR #5629 broke it. Also changing 001 to 0001 since that will give correct name of VM, previously missed a 0.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' }}
=> [RFR] Fixing code broken by PR #5629

cfme/control/explorer/alert_profiles.py
Purpose
`instantiate` method is reimplemented in `AlertProfileCollection`. It should return a specific Alert Profile instance, not `BaseAlertProfile`.
{{pytest: -v -k "test_alert_profile_crud" --long-running}}
=> [1LP][RFR] Fixed Alert Profile collection

cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/virtualcenter.py
__Extending__ rhevm.py and virtualcenter.py to find correct elements from screen of SSUI Console. This code previously helped to find correct elements for HTML5 console and webMKS consoles. By using piped(|) OR in the xpath selector I am trying to reuse same code for SSUI VM Console as well. 
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' }}
=> [1LP][RFR]Adding ability to get canvas/sendCtrlAltDel element for RHV and VMware for SSUI VM Console

cfme/tests/infrastructure/test_rest_automation_request.py
* added test for editing automation requests through /api/automation_requests
* small fixes/enhancements here and there
{{pytest: -v cfme/tests/infrastructure/test_rest_automation_request.py}}
=> [1LP][RFR] Fixes for test_rest_automation_request tests

cfme/configure/configuration/server_settings.py, cfme/utils/ext_auth.py
Need an appliance object, not the module, in order to access
appliance.server property.
Tried to update utils.ext_auth to use appliance.current_appliance consistently and always use the appliance object, not the module to call functions.
FIXES RHCFQE-5227
Its going to be a mess, because the ext-auth servers aren't available.  But reviewers can directly import and call the methods to modify their auth settings to verify.  Some of the tests get past or call the methods in their teardown after failing, so the results are still useful - but won't be green.
All failures in PRT are because ext-auth servers aren't up, no more AttributeErrors or TypeErrors
{{pytest: cfme/tests/integration/test_cfme_auth.py --long-running -v}}
=> [1LP][RFR] Update utils.ext_auth set_auth_mode call

cfme/tests/services/test_service_manual_approval.py
{{pytest: --long-running --use-provider=rhv41 cfme/tests/services/test_service_manual_approval.py}}
=> [1LP][RFR] test_service_manual_approval fix

cfme/fixtures/service_fixtures.py, cfme/rest/gen_data.py
Use REST for catalog fixture to make it more robust (there are problem with the UI dialog).
{{pytest: '-v --long-running ''cfme/tests/services/test_service_catalogs.py::test_order_catalog_item[rhv41]'''}}
=> [1LP][RFR] Use REST for catalog fixture

cfme/utils/appliance/db.py
Appliance DB setup happily ignores the error messages coming out of appliance_console_cli. This recitfies the issue by looking at the RC and the output of the CLI script. Unfortunately, with the current issue it does not change the RC so I also added a check for "failed" in the output.
=> [1LP][RFR] DB setup reacts to the output of appliance_console_cli

cfme/tests/cloud/test_tenant.py, setup.py
Updated name to `cloud_tenants`, because just `tenants` would be for cfme tenants collection
{{ pytest: -v cfme/tests/cloud/test_tenant.py }}
=> [RFR] Updated name for cloud tenants

cfme/configure/access_control.py
See https://bugzilla.redhat.com/show_bug.cgi?id=1498075
{{pytest: -v -k 'test_group_crud or test_user_crud or test_role_crud or test_delete_default_group or test_delete_default_roles or test_edit_default_group or test_edit_default_roles'}}
=> [1LP][RFR] Verify RBAC User/Group/Role is highlighted in accordion when Details view is displayed

cfme/tests/cloud_infra_common/test_vm_ownership.py
test_vm_ownership creates new users for testing. These users are created with usernames that contain uppercase characters which fails when causes login to fail per BZ1487199. 
{{pytest: -v -k 'test_user_ownership_crud or test_group_ownership_on_user_only_role or test_group_ownership_on_user_or_group_role'}}
=> [1LP][RFR] Check for BZ1487199 to see if new creds need lowercasing when testing vm ownership

cfme/tests/infrastructure/test_vm_migrate.py, cfme/tests/infrastructure/test_vm_power_control.py
__Skipping__ two test blocked by reported BZs.
{{pytest: cfme/tests/infrastructure/test_vm_migrate.py::test_vm_migrate cfme/tests/infrastructure/test_vm_power_control.py::test_no_template_power_control --use-provider rhv41 -v}}
=> [1LP][RFR] Adding BZ wrapper for test_vm_migrate and test_no_template_power_control

cfme/tests/cloud_infra_common/test_rest_providers.py
__Extending__ cfme/tests/cloud_infra_common/test_rest_providers.py because it was not possible to set up provider via REST with SSL certificate.
{{pytest: cfme/tests/cloud_infra_common/test_rest_providers.py --use-provider rhv41 -v}}
=> [1LP][WIPTEST] Include certificate when creating provider via REST

cfme/cloud/instance/image.py
common.vm_views.VMEntities uses InstanceEntity types, which version pick
and correctly fills data dict property
FIXES RHCFQE-5370
Followup to #5669, ~~marking rc-regression-fix for now. @psav might disagree, as this wasn't necessarily introduced in this sprint.~~
59z failure shows the 'Images by Provider' screen with no images listed, not relevant to this small scope.
{{pytest: --use-provider rhos7-ga --long-running -v cfme/tests/infrastructure/test_instance_analysis.py::test_ssa_template }}
=> [1LP][RFR] Update cloud.instance.image to use VMEntities

artifactor/plugins/reporter.py, fixtures/browser.py
* tb_info hook is now registered with the tb_info() method
* browser.py now fires more information into the test information to
give a better view into test failures and classification
=> [1LP][RFR] Added a simple plugin for artifactor that gives traceback info

cfme/common/provider.py, cfme/common/provider_views.py, cfme/infrastructure/deployment_roles.py, cfme/infrastructure/provider/__init__.py, cfme/infrastructure/provider/openstack_infra.py, cfme/middleware/provider/__init__.py, cfme/tests/intelligence/reports/test_canned_corresponds.py, cfme/tests/networks/test_sdn_crud.py, cfme/tests/networks/test_sdn_navigation.py
ProviderDetails page uses contents attribute instead of entities as everywhere.
This PR fixes this issue.
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/middleware/test_middleware_provider.py cfme/tests/containers/test_ssl_providers.py }}
@gshefer, ^^
=> [1LP][RFR] provider.contents -> provider.entities

cfme/common/vm.py, cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vm_power_control.py
__Extending__ VM model. The reason is that if you want to access VM's details, navmazing path to it contains view with VMs of a provider. However, archived VM is no longer visible under provider. That's why you can now specify that you want to load details independently of provider.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_no_power_controls_on_archived_vm --use-provider rhv41 -v --long-running}}
=> [1LP][RFR] Adding different path to Details view for archived/orphaned VM

scripts/post_jenkins_result.py
The template-test jobs were updated and no longer use jenkins-runner, so
there are no longer RUNNER_RETURN/TEST_RETURN variables, or a file with
these values.
New creds have been pushed to cfme_data/credentials.eyaml.
Tested in CI on one-off, running full template_tester build now to confirm.
=> [1LP][RFR] Update post_jenkins_result, remove RUNNER_RETURN

cfme/tests/cloud_infra_common/test_events.py
{{pytest: --use-provider=rhv41 cfme/tests/cloud_infra_common/test_events.py}}
=> [1LP][RFR] blocker for  test_vm_create event

cfme/tests/automate/test_common_methods.py
After extending the VM retirement date, verify that the WebUI is updated with the correct date
{{pytest: -v -k 'test_vm_retire_extend'}}
=> [1LP][RFR] test_vm_retire_extend: Add check to verify extended retirement date

cfme/services/catalogs/catalog_item.py
__Fixing__ is_displayed() method of EditCatalogItemView since test_edit_catalog_after_deleting_provider was failing on that.
{{pytest: cfme/tests/services/test_service_catalogs.py::test_edit_catalog_after_deleting_provider --use-provider rhv41 -v --long-running}}
=> [1LP][RFR] Fixing EditCatalogItemView

cfme/fixtures/tccheck.py, cfme/test_framework/pytest_plugin.py
Use ``--validate-test-cases``
Does not work with ``--collect-only`` currently.
```
================================================ test session starts =================================================
platform linux2 -- Python 2.7.11, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: /home/mfalesni/git/cfme_tests, inifile:
plugins: wait-for-1.0.9, cov-2.5.1, polarion-cfme-0.1.1, manageiq-integration-tests-0.0.0
collected 6 items 
Appliance's streams: [5.9, downstream]
[TCV-E] MISSING REQUIREMENT: cfme/tests/automate/test_namespace.py::test_namespace_crud[plain]
[TCV-E] MISSING REQUIREMENT: cfme/tests/automate/test_namespace.py::test_namespace_delete_from_table[plain]
[TCV-E] MISSING REQUIREMENT: cfme/tests/automate/test_namespace.py::test_duplicate_namespace_disallowed[plain]
[TCV-E] …
```
=> [RFR] Test cases: Tier and Requirement check

cfme/tests/control/test_actions.py
Grab flavour_name from the provisioning AttrDict, don't use template
name
{{pytest: --use-provider rhos7-ga --long-running -k test_action_start_virtual_machine_after_stopping cfme/tests/control/test_actions.py}}
=> [RFR] Update flavour_name for openstack in test_actions

cfme/common/provider_views.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/tests/containers/test_ssl_providers.py, cfme/tests/containers/test_start_page.py
In 5.9, there were recent changes that renamed the 'Hawkular' endpoint from "Hawkular" to "Metrics" and added a new drop down widget called Metrics. The changes in this PR address these updates and allow the creation of a ContainerProvider in 5.9 
{{ pytest: --use-provider cm-env2 --long-running cfme/tests/containers/test_start_page.py cfme/tests/containers/test_ssl_providers.py}}
=> [1LP][RFR] Initial fixes for ContainerProvider form for 5.9

cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py
* fixes orchestration templates creation using REST API
* adds new test testing https://bugzilla.redhat.com/show_bug.cgi?id=1510215
{{pytest: -v --long-running -k TestOrchestrationTemplatesRESTAPI cfme/tests/services/test_rest_services.py}}
=> [1LP][RFR] Fix orchestration templates creation using REST

cfme/base/ui.py, cfme/exceptions.py
* This allows us to separate these NoSuchElementExceptions from real
ones
{{pytest: cfme/tests/configure/test_zones.py -k test_zone_add_cancel_validation}}
=> [1LP][RFR] Zone Creation is broken in 5.9.0.5

cfme/tests/configure/test_ntp_server.py
{{pytest: cfme/tests/configure/test_ntp_server.py -k test_ntp_server_check}}
=> [1LP][RFR] Fixture was being used as a fn and not the fixture value

cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: -v --long-running --use-provider rhv41 cfme/tests/ssui/test_ssui_service_catalogs.py }}
Fixture.name returns service
=> [RFR] fixture.name returns service

cfme/automate/service_dialogs.py
Service Dialogs now use new UI which is not modeled in FW
{{pytest: cfme/tests/services/test_service_catalogs.py}}
=> [1LP][RFR] Service Dialogs now use new UI which is not modeled in FW

cfme/tests/cloud/test_instance_power_control.py
Text fix for VM terminate, version pick flash message
First PRT results were mixed, I had left 'CFME' in hardcoded. Added use of `appliance.product_name`.
{{ pytest: cfme/tests/cloud/test_instance_power_control.py --long-running --use-provider rhos7-ga -k "test_quadicon_terminate and not test_quadicon_terminate_cancel" }}
=> [1LP][RFR] Update terminate string for VM/instance

cfme/infrastructure/virtual_machines.py
This is a quick fix to existing snapshot tests. In 5.9 the flash message changed, so we need to use `version.pick()` to choose the appropriate message for different versions of CFME.
{{pytest: -v --long-running --use-provider vsphere65-nested -k "test_verify_vm_state_revert_snapshot"}}
=> [1LP][RFR] Fix snapshot flash message for 5.9

cfme/utils/appliance/db.py
This impacts appliance configuration and the sprout appliances that PRT gets won't have this applied to their configuration.
I've been testing this locally against the RHOS and non-RHOS providers.
In the case where dbdisk isn't mounted, calling umount shouldn't be a problem. It will have non-zero return code, but that's fine and we can basically ignore. Log the output anyway.
This option is required for g-release MIQ builds or CFME 5.9+ configuration.
=> [1LP][RFR] update appliance.db.enable_internal, umount dbdisk

scripts/clone_template.py, scripts/template_upload_ec2.py
Cloud-init had to be overridden to allow root login with password.
Now ec2 appliance will behave as any other provider appliance and can be configured and used for template_testing.
=> [1LP][RFR] added cloud-init script for ec2 appliance and increased timeout for image import

cfme/tests/cloud/test_providers.py, cfme/tests/infrastructure/test_providers.py
These tests should be the same tier, infra was already set to 1
CFME QE wants to include these in smoke testing as well, so add smoke mark.
=> [RFR] Mark both test_provider_crud methods as tier(1)

cfme/exceptions.py, cfme/storage/volume.py, cfme/storage/volume_backup.py, cfme/tests/storage/test_volume_backup.py, setup.py
- Its supporting model page for cfme.storage.volume.py for volume backup operations.
- from version >5.7 separations of backups and snapshot page came.
- backup creation going to be add using volume.py.
- added a simple tag test using available backups only. as create method add in volume.py its possible to add and remove a tag on newly created backup.  [RHCFQE-5459](https://projects.engineering.redhat.com/browse/RHCFQE-5459)
{{pytest: cfme/tests/storage/test_volume_backup.py --use-provider rhos7-ga  -v}}
=> [1LP][RFR] storage volume backups model page[ WT and collection]

cfme/common/provider.py
{{pytest: --long-running cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/containers/test_ssl_providers.py cfme/tests/middleware/test_middleware_provider.py }}
=> [RFR][1LP] temporary fix for removing providers via UI in 5.9

cfme/tests/infrastructure/test_snapshot.py, markers/__init__.py, markers/rhv.py
__Extending__ framework with @pytest.mark.rhv marker because we at the RHV-CFME integration want to categorize tests into three tiers according to their importance specifically to integration work.
Note: Once this is in downstream-stable, we will mark all tests relevant for RHV-CFME integration with one of those.
{{pytest: markers/rhv.py -p pytester}}
=> [1LP][RFR] Adding @pytest.mark.rhv marker for purposes of RHV-CFME integration

cfme/utils/hosts.py
Tested locally.
This appears randomly, so if you want to test it, you need to pass a nonexisting host into the function.
Usually appears when a SSA test against vsphere55 deploys a VM on the 4th host, which is not in yamls.
I contacted infra about the credentials of that host so I can add it.
At least we can have a meaningful message here instead of a cryptic `__getitem__`
=> [1LP][RFR] Sensible host credentials errors

cfme/configure/access_control.py, cfme/fixtures/tag.py, cfme/tests/cloud_infra_common/test_vm_ownership.py, cfme/tests/configure/test_access_control.py, cfme/tests/infrastructure/test_infra_quota.py, cfme/tests/integration/test_cfme_auth.py, cfme/tests/intelligence/reports/test_validate_chargeback_report.py, setup.py
Implementing Collections in the RBAC Group object.  This PR just updates tests that rely on RBAC groups
{{ pytest: -v -k 'test_validate_default_rate or test_group_quota_max or test_form_button_validation or test_user_ownership_crud or test_group_ownership_on_user_only_role or test_group_ownership_on_user_or_group_role or test_user_crud or test_user_login or test_user_duplicate_name or test_username_required_error_validation or test_current_user_login_delete or test_group_crud_with_tag or test_group_duplicate_name or test_group_remove_tag or test_group_description_required_error_validation or test_delete_default_group or test_delete_group_with_assigned_user or test_edit_default_group or test_edit_sequence_usergroups or test_tagvis_group or test_delete_default_roles_with_assigned_group or …
=> [1LP][RFR] Implement Collections in RBAC Groups

cfme/configure/tasks.py
Does not create new view for only 2 tabs in 59z vs 4 tabs in 58z
WORKAROUND: I'd consider this a bit of a workaround, as ultimately the views/tests should be reworked to use a separate view for versions before the change from 4 tabs to 2 tabs.  The scope of refactoring view/tests is much larger than an rc-regression-fix
I 50% expect it to get closed unmerged and we'll wait for a more complete fix
{{ pytest: cfme/tests/infrastructure/test_instance_analysis.py --long-running --use-provider rhos7-ga }}
=> [1LP][RFR] Update configure.tasks, tab names for 59z

cfme/services/myservice/ssui.py, cfme/tests/ssui/test_ssui_myservice.py
__Extending__ SSUI Console test to appropriately select HTML5 console button for CFME 5.7 while choosing Access Dropdown for CFME 5.8
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider vsphere6-nested --use-provider rhv41}}
=> [1LP][RFR] Adding new console button for cfme5.7 and mechanism to select correct widget for 5.7 and 5.8

requirements/frozen.txt
__Updating__ required version of psycopg2 package because of this [issue](https://github.com/psycopg/psycopg2-wheels/issues/2) (problem with new version of glibc)
=> [RFR] Updating version of psycopg2 in requirements

cfme/fixtures/smtp.py
@lkhomenk Please test this locally, if it works for you as well.
{{pytest: cfme/tests/control/test_alerts.py -k test_alert_vm_turned_on_more_than_twice_in_past_15_minutes --use-provider vsphere65-nested --long-running}}
=> [RFR] Kill smtp_collector process correctly on rhel-based systems

cfme/cloud/provider/__init__.py
create views for the cloud provider relationship pages for instances and
images.
Navigation destinations already existed but were using web_ui and
pytest_selenium, this removes that use
FIXES RHCFQE-5777
I've tested navigation and is_displayed locally with success.
=> [1LP][RFR] Add WT pages for cloud.provider Instance/Image rel

cfme/tests/configure/test_access_control.py
During a PR 5664 update, I failed to update this test to use group_collection fixture instead of appliance. The test will still fail on 5.9.0.8 [BZ 1512645](https://bugzilla.redhat.com/show_bug.cgi?id=1512645)  but not due to group_collection not being passed as a fixture :)
[BZ 1512645](https://bugzilla.redhat.com/show_bug.cgi?id=1512645) was closed as a duplicate of [BZ 1503076](https://bugzilla.redhat.com/show_bug.cgi?id=1503076)
{{pytest: -v -k 'test_user_edit_tag'}}
=> [1LP][RFR] Fix failure in access_control::test_user_edit_tag due to incorrect test fixture

cfme/tests/services/test_rest_services.py
... as this collection was removed in 5.9
{{pytest: -v --long-running -k TestBlueprintsRESTAPI cfme/tests/services/test_rest_services.py}}
=> [RFR] Skipping blueprints tests on 5.9

cfme/tests/cloud/test_providers.py, cfme/tests/test_rest.py
... as these were removed in 5.9
{{pytest: -v -k 'TestArbitrationRulesRESTAPI or TestArbitrationSettingsRESTAPI or _arbitration_' cfme/tests/cloud/test_providers.py cfme/tests/test_rest.py}}
=> [RFR] Skipping tests on arbitration_* collections

cfme/tests/control/test_alerts.py
Purpose
Control alert tests marked as blocked due the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1501895
=> [RFR] Marked blocked alert tests

cfme/fixtures/cli.py, cfme/tests/cli/test_appliance_cli.py, cfme/tests/cli/test_appliance_console.py, cfme/tests/configure/test_register_appliance.py
Fixes to extend storage test for 5.9, added bug skip to test_rh_updates. Also removed some unused args. We see the odd test failures on some database configurations due to current rhos template issues, this issue is because there is no additional disk to configure the database with.
=> [RFR][1LP] Fixes to tests + clean up

cfme/cloud/availability_zone.py, cfme/cloud/instance/__init__.py, cfme/cloud/provider/__init__.py, cfme/common/host_views.py, cfme/common/provider_views.py, cfme/containers/node.py, cfme/infrastructure/cluster.py, cfme/infrastructure/virtual_machines.py, cfme/middleware/provider/middleware_views.py, widgetastic_manageiq/__init__.py
remove use of super() for timelines view checking
Add property to base TimelinesView to check title without overriding
is_displayed.
add some breadcrumb widgets for reliable is_displayed returns unique to
the resource they're on.
NOTE:
There is a TODO for middleware_providers, because I don't have a provider to test this on and find a unique identifier. Should be trivial to add breadcrumb or title validation.
{{ pytest: --long-running -v --use-provider rhos7-ga --use-provider rhv41  cfme/tests/infrastructure/test_timelines.py cfme/tests/cloud/test_cloud_timelines.py }}
Removed azure from providers to run against, producing URLError failures that are completely unrelated.
The 59z/upstream failures are a StopIteration in the test because its not finding a cluster of the expected name.  
92% …
=> [1LP][RFR] Update TimelinesView is_diplayed calls

cfme/tests/control/test_compliance.py
Purpose
__Fixing__ tests in test_compliance.py due changes in `setup_host_creds`.
{{pytest: -v -k "test_check_package_presence or test_check_files" --long-running --use-provider=vsphere6-nested}}
=> [1LP][RFR] Fixed tests in test_compliance.py

cfme/cloud/provider/__init__.py, cfme/cloud/stack.py, cfme/cloud/tenant.py, cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/provider/__init__.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py, cfme/infrastructure/cluster.py, cfme/infrastructure/datastore.py, cfme/infrastructure/provider/__init__.py, cfme/infrastructure/resource_pool.py, cfme/middleware/datasource.py, cfme/middleware/deployment.py, cfme/middleware/domain.py, cfme/middleware/messaging.py, cfme/web_ui/paginator.py, widgetastic_manageiq/__init__.py
redundant paginator's check_all/uncheck_all calls are moved from navmazing resetter to appropriate paginator method
{{pytest: --long-running cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/infrastructure/test_datastore_analysis.py}}
=> [1LP][RFR] pagination pane resetter

cfme/common/host_views.py, cfme/common/provider_views.py
It turned out that quads can be disabled for QuadIcons. Quadicon.data doesn't work in such case. This fix inhibits exceptions and return empty dict for such case
=> [1LP][RFR] data property shouldn't raise exception  when quads are disabled

cfme/services/myservice/ssui.py
__Fixing__ SSUI VM Console view to wait_for page to load before throwing NoSuchElement.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider vsphere6-nested --use-provider rhv41}}
=> [1LP][RFR] Sometimes page takes time to load and ends up with NoSuchElement, handling that with wait_for

cfme/tests/cloud_infra_common/test_rest_providers.py, cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/configure/test_rest_access_control.py, cfme/tests/configure/test_tag.py, cfme/tests/configure/test_tag_category.py, cfme/tests/control/test_rest_control.py, cfme/tests/infrastructure/test_providers.py, cfme/tests/infrastructure/test_rest_templates.py, cfme/tests/infrastructure/test_vm_rest.py, cfme/tests/intelligence/test_chargeback.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_rest_services.py, cfme/tests/test_rest.py, cfme/utils/rest.py
{{pytest: -v --long-running -k '_delete_ and _from_collection and not TestReposRESTAPI and not TestAuthenticationsRESTAPI' --use-provider vsphere65-nested}}
=> [RFR] Fix delete from collection after partial fix to BZ 1511128

cfme/infrastructure/cluster.py
cluster_id obtained thru rest has unicode type since 5.9. It had int before.
{{pytest: --use-provider=vsphere6-nested cfme/tests/infrastructure/test_timelines.py}}
=> [1LP][RFR] fix cluster id type

cfme/tests/cloud_infra_common/test_rest_providers.py
__Fixing__ provider creating via REST. I found out that REST API in 5.7 does not accept certificate_authority.
`APIException: Api::BadRequestError: Could not create the new provider - unknown attribute 'certificate_authority' for Endpoint`
{{pytest: cfme/tests/cloud_infra_common/test_rest_providers.py -v --use-provider rhv41}}
=> [RFR] Fixing creation of provider via REST for CFME < 5.8

cfme/control/explorer/policy_profiles.py
{{pytest: --use-provider=scvmm --long-running cfme/tests/cloud_infra_common/test_events.py}}
=> [RFR] workaround for policy profiles view in 5.9

cfme/utils/log.py, requirements/frozen.txt, requirements/frozen_docs.txt, requirements/template_docs.txt, scripts/delete_vm.py
We no longer use psphere, wrapanapi moved to pyVmomi. Remove psphere from the requirements, and use the methods in wrapanapi to delete the VirtualCentre vms and templates.
=> [RFR][1LP][NOTEST] Remove all references to psphere

cfme/base/ui.py
* This is NOT what we want to do, but is happening because the
registration is in a different file Not seeing much of a way around
this, but it is most definitely not ideal
{{pytest: -k test_pull_splitter_persistence[Server-AutomateExplorer]}}
=> [RFR] AutomateExplorer loaded server base

cfme/tests/control/test_alerts.py
Fix for test_alerts
```
>       setup_host_creds(provider.key, host)
cfme/tests/control/test_alerts.py:120: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
provider = 'vsphere65-nested'
host_name = 'env-nvc65-h03.cfme2.lab.eng.rdu2.******.com', remove_creds = False
ignore_errors = False
def setup_host_creds(provider, host_name, remove_creds=False, ignore_errors=False):
try:
>           appliance = provider.appliance
E           AttributeError: 'str' object has no attribute 'appliance'
cfme/utils/hosts.py:23: AttributeError
```
{{pytest: --long-running cfme/tests/control/test_alerts.py}}
=> [RFR] fixed test alerts -> it passed provider key instead of object

cfme/base/__init__.py, cfme/base/ui.py, cfme/configure/configuration/analysis_profile.py, cfme/infrastructure/provider/__init__.py, cfme/physical/provider/__init__.py
This issue is currently blocking master ^
As long as there is no `AttributeError: 'property' object has no attribute 'server'` on PRT, we are good.
{{pytest: cfme/tests/infrastructure/test_providers.py -k test_provider_add_with_bad_credentials --use-provider vsphere6-nested}}
=> [1LP][RFR] Replace NavigateToObject with NavigateToAttribute; minor lint

cfme/tests/cloud_infra_common/test_events.py
__Adding__ BZ wrapper for test_vm_create.
{{pytest: cfme/tests/cloud_infra_common/test_events.py::test_vm_create -v --use-provider rhv41}}
=> [1LP][RFR] Adding BZ wrapper for test_vm_create

cfme/common/vm.py, cfme/tests/cloud_infra_common/test_retirement.py
__Wrapping__ tests that set retirement date with BZ, since remove retirement date button (used to be red X) is missing in the page. Also input_name was changed for retirement date field.
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py -vv --use-provider rhv41}}
=> [1LP][RFR] Wrapping retirements tests with BZ

markers/polarion.py
In this PR I created a new polarion marker for our test so each test that decorated with pytest.mark.polarion("some-id"), will be translated into the xunit.xml file
**For example:**
```xml
<testcase classname="cfme.tests.containers.fake_test" file="cfme/tests/containers/fake_test.py" line="14" name="test_nothing2[1]" time="0.00894999504089">
<skipped message="skipping..." type="pytest.skip">cfme/tests/containers/fake_test.py:14: &lt;py._xmlgen.raw object at 0x7f84c032fd90&gt;</skipped>
</testcase>
<testcase classname="cfme.tests.containers.fake_test" file="cfme/tests/containers/fake_test.py" line="14" name="test_nothing2[2]" time="0.0127758979797">
<properties>
<property name="test_id" value="CMP-002"/>
</properties>
<system-out>
This is just an empty test
</system-out>
</testcase>
```
=> [1LP][RFR] Add a Polarion marker to integration test

cfme/services/catalogs/catalog_item.py
__Fixing__ test_edit_catalog_after_deleting_provider with this workaround after consulting with @mfalesni. The reason is that framework sometimes attempted to click "Save" button on Catalog Item edit sceen before it was actually clickable.
{{pytest: cfme/tests/services/test_service_catalogs.py::test_edit_catalog_after_deleting_provider --use-provider rhv41 --long-running -vv}}
=> [1LP][RFR] Fixing test_edit_catalog_after_deleting_provider with WA

cfme/tests/control/test_alerts.py, cfme/utils/hosts.py
{{pytest: cfme/tests/control/test_alerts.py -k test_alert_hardware_reconfigured --long-running}}
=> [1LP][RFR] Fixed up setup_hosts_creds

conf/cfme_data.yaml.template
@psav Please review.
These are apparently required to configure a non-sprout appliance, but since no defaults are given all you get are cryptic error messages
=> Add conf settings that are required to the template

cfme/services/catalogs/__init__.py, cfme/services/catalogs/orchestration_template.py
Fix for test errors like:
```
def step(self):
>       self.prerequisite_view.toolbar.policy.item_select('Edit Tags')
E       AttributeError: 'DetailsTemplateView' object has no attribute 'toolbar'
```
{{pytest: --long-running cfme/tests/services/test_orchestration_template.py}}
=> [1LP][RFR] workaround for catalogs view which causes some tests fail

cfme/tests/openstack/infrastructure/test_host_lifecycle.py, cfme/tests/openstack/infrastructure/test_host_power_control.py, cfme/tests/openstack/infrastructure/test_hosts.py, cfme/tests/openstack/infrastructure/test_networks.py
=> [RFR] Remove testgen from openstack/infrastructure (part 1)

cfme/tests/perf/workloads/test_memory_leak.py
=> [1LP][RFR] Remove testgen from test_memory_leak

cfme/tests/networks/test_sdn_inventory_collection.py, cfme/tests/networks/test_sdn_navigation.py, cfme/tests/networks/test_sdn_ports.py
=> [1LP][RFR] Removed testgen from networks (part 2)

cfme/tests/openstack/infrastructure/test_provider.py, cfme/tests/openstack/infrastructure/test_relationships.py, cfme/tests/openstack/infrastructure/test_resources.py, cfme/tests/openstack/infrastructure/test_roles.py
__Updating tests__ Replace testgen with pytest.mark.provider.
=> [1LP][RFR] Remove testgen from openstack/infrastructure (part 2)

cfme/tests/openstack/cloud/test_instances.py, cfme/tests/openstack/cloud/test_networks.py, cfme/tests/openstack/cloud/test_volumes.py
=> [1LP][RFR] Removed testgen from openstack/cloud

cfme/tests/intelligence/reports/test_canned_corresponds.py, cfme/tests/intelligence/reports/test_generate_report.py, cfme/tests/intelligence/reports/test_validate_chargeback_report.py, cfme/tests/intelligence/reports/test_views.py
__Updating tests__: replace testgen with pytest.mark.provider.
=> [1LP][RFR] Removed testgen from intelligence

cfme/tests/middleware/test_middleware_server_group.py, cfme/tests/middleware/test_middleware_tags.py, cfme/tests/middleware/test_middleware_topology.py, cfme/tests/middleware/test_middleware_utilization.py, cfme/tests/middleware/test_provider_timelines.py
{{pytest: --use-provider hawkular cfme/tests/middleware/test_middleware_server_group.py cfme/tests/middleware/test_middleware_tags.py cfme/tests/middleware/test_middleware_topology.py cfme/tests/middleware/test_middleware_utilization.py cfme/tests/middleware/test_provider_timelines.py}}
=> [1LP][RFR] Removed testgen from middleware (part 3)

cfme/configure/access_control.py
5+ tests, SSIA
User, Role and Group are not affected. Dev only made this flash message change for Tenant and Project... :face_with_head_bandage: 
{{pytest: -k test_unique_project_name_on_parent_level cfme/tests/configure/test_access_control.py}}
=> [1LP][RFR] Fix tenancy and project flash messages

cfme/tests/middleware/test_middleware_downloads.py, cfme/tests/middleware/test_middleware_drivers.py, cfme/tests/middleware/test_middleware_messagings.py, cfme/tests/middleware/test_middleware_provider.py, cfme/tests/middleware/test_middleware_server.py
=> [1LP][RFR] Removed testgen from middleware (part 2)

cfme/configure/tasks.py, cfme/containers/image.py
Remove web_ui/pytest_selenium code from configure/tasks.
Remove wait_for_task_finished, was only being used in one place.
=> [RFR] Update tasks and dependent modules, remove web_ui

cfme/tests/services/test_add_remove_vm_to_service.py, cfme/tests/services/test_cloud_service_catalogs.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_myservice.py, cfme/tests/services/test_orchestration_template.py
=> [RFR] Remove testgen from services (part 1)

cfme/tests/services/test_provision_stack.py, cfme/tests/services/test_request.py, cfme/tests/services/test_service_catalogs.py, cfme/tests/services/test_service_manual_approval.py
=> [RFR] Remove testgen from services (part 2)

cfme/fixtures/tag.py, cfme/tests/cloud_infra_common/test_vm_ownership.py, cfme/tests/configure/test_access_control.py, cfme/tests/infrastructure/test_quota_tagging.py, cfme/tests/integration/test_cfme_auth.py, cfme/tests/intelligence/reports/test_validate_chargeback_report.py, setup.py
Renaming the appliance collections reference of GroupCollection from rbac_groups to groups
{{pytest: cfme/tests/configure/test_access_control.py}}
=> [RFR][1LP] Rename GroupCollection reference to .groups

cfme/tests/configure/test_access_control.py
=> [RFR] Removing an old test + comment

cfme/configure/tasks.py, cfme/tests/infrastructure/test_host_drift_analysis.py
version pick the task tab name for 5.9 change
Versioned picked the tab name in the tasks view class during sprint 16, but this was insufficient to fully fix the test.
Tasks is in need of a pretty full refactor to move to collection and to move all the module methods into a proper entity class.
So far working like I want locally. though there are test failures.  They're not related to the tasks views/widgets.
Can't explain the 5909 failure selecting 'Department' tag category.
{{ pytest: cfme/tests/infrastructure/test_host_drift_analysis.py --long-running --use-provider vsphere65-nested --use-provider scvmm --use-provider rhv41 }}
=> [1LP][RFR] Fix test_host_drift_analysis, versioned task tabs

cfme/tests/middleware/test_middleware_topology.py
Whole test suite failed during collecting due: Using pytest.skip outside of a test is not allowed. To decorate a test function, use the @pytest.mark.skip or @pytest.mark.skipif decorators instead, and to skip a module use `pytestmark = pytest.mark.{skip,skipif}.
=> Fixed test_middleware_topology.py

cfme/common/vm_views.py, cfme/services/requests.py, cfme/tests/cloud/test_provisioning.py
FIxing typo and widget type
{{pytest: --long-running --use-template-cache --use-provider gce_central -k preemptible cfme/tests/cloud/test_provisioning.py}}
=> [1LP][RFR]fix for preemptible checkbox

cfme/tests/infrastructure/test_snapshot.py
**WAS**: Fix wait_for_vm_state_change for 5.9
~~This is a quick fix to enable `wait_for_vm_state_change` usage for 5.9. There was a change in dictionary that is returned from `find_quadicon().data`, in 5.9 we must be looking for key 'quadicon' instead of 'state' which is not there any more.~~
~~`find_quadicon().data['quadicon']` returns a rather nasty and long line of html code, which thankfully contains also 'currentstate-*', so there is no need to change anything else but the item key.~~
Also removed all occurrences of `find_quadicon` from snapshot tests, since it is exactly what `wait_for_vm_state_change` does, so `find_quadicon` doesn't bring any added value to the test.
{{pytest: -v --long-running --use-provider vsphere65-nested -k "test_operations_suspended_vm"}}
=> [RFR] Snapshot: remove soft asserts

cfme/containers/image.py, widgetastic_manageiq/__init__.py
It turned out that some entities like containers->Image use id to hold some their internal ids. Whereas current implementation of entities use id to hold entity_id.
So, this PR will make entities use entity_id property instead of id.
{{pytest: cfme/tests/cloud/test_providers.py cfme/tests/infrastructure/test_providers.py cfme/tests/middleware/test_middleware_provider.py cfme/tests/containers/test_ssl_providers.py}}
=> [1LP][RFR] entities id will be changed to entity_id

cfme/common/vm.py, widgetastic_manageiq/__init__.py
This PR doesn't add any search reset functionality. 
test owner should take of it by himself. 
For example add view.entities.search.clear_search() to nav destination->resetter()
=> [1LP][RFR] adding search support to entities.get_entity()

cfme/tests/control/test_compliance.py, cfme/tests/infrastructure/test_cloud_init_provisioning.py, cfme/tests/infrastructure/test_cluster_analysis.py, cfme/tests/infrastructure/test_delete_infra_object.py, cfme/tests/infrastructure/test_individual_host_creds.py
__Updating tests.__ Replace testgen and pytest_generate_tests with pytest.mark.provider.
=> [1LP][RFR] Remove testgen from control and infrastructure (part 1)

cfme/tests/cloud_infra_common/test_rest_providers.py, cfme/tests/cloud_infra_common/test_retirement.py, cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/cloud_infra_common/test_tag_visibility.py, cfme/tests/cloud_infra_common/test_vm_ownership.py
__Updating tests.__ Replace testgen and pytest_generate_tests with pytest.mark.provider.
=> [1LP][RFR] Remove testgen from cloud_infra_common (part 2)

cfme/fixtures/service_fixtures.py, cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_vm_clone.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_iso_service_catalogs.py, cfme/tests/services/test_operations.py, cfme/tests/services/test_pxe_service_catalogs.py
This PR needs ~~https://github.com/RedHatQE/widgetastic.patternfly/pull/18~~ and ~~https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/375~~
Vlan names are different from version to version - we are adding subnets/vlan etc. SCVMM/RHEVM would appreciate having this 
local testing
```
view.form.network.vlan.read()
Out[14]: u'<None>'
view.form.network.vlan.all_options
Out[15]:
[Option(text=u'<None>', value=u'0'),
Option(text=u'<No Profile>', value=u'1'),
Option(text=u'ovirtmgmt (ovirtmgmt)', value=u'2')]
view.form.network.vlan.fill(partial_match('ovirt'))
Out[16]: True
```
=> [1LP][RFR][NOTEST]applying partial match for vlan selection in ops ui

cfme/tests/infrastructure/test_iso_datastore.py, cfme/tests/infrastructure/test_providers.py, cfme/tests/infrastructure/test_provisioning.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_provisioning_rest.py
__Updating tests.__ Replace testgen and pytest_generate_tests with pytest.mark.provider.
Moved some common fixtures to pytestmark.
=> [1LP][RFR] Remove testgen from infrastructure (part 2)

cfme/tests/infrastructure/test_scvmm_specific.py, cfme/tests/infrastructure/test_snapshot.py, cfme/tests/infrastructure/test_vm_clone.py, cfme/tests/infrastructure/test_vm_migrate.py
Moved some common fixtures to pytestmark.
=> [1LP][RFR] Remove testgen from infrastructure (part 3)

cfme/utils/appliance/__init__.py
`--ui-coverage` uses rude evm restart and it kills ~40% appliances per test run; I wasn't able to reproduce it locally, but this should take care of the issue.
If not, I'll revisit after next jenkins run.
Tested locally, works fine.
=> [1LP][RFR] Rude evm restart is now less rude but still thorough

cfme/tests/ansible/test_embedded_ansible_services.py
Purpose
Automation test suite cannot find elements which don't have some unique locator like it's implemented here:
```html
<input ng-model="vm.dialogField.default_value" ng-disabled="vm.dialogField.read_only || vm.inputDisabled" ng-change="vm.changesHappened()" ng-blur="vm.validateField()" ng-model-options="{debounce: {'default': 500}}" class="form-control ng-pristine ng-untouched ng-valid ng-not-empty" uib-tooltip="" value="localhost" type="text">
```
There is no "id", "name" or another attribute which helps to locate this input on the page. So until the [BZ 1519275](https://bugzilla.redhat.com/show_bug.cgi?id=1519275) won't be fixed, some tests should be uncollected.
=> [1LP][RFR] Marked some ansible service tests as uncollected due BZ 1519275

cfme/common/vm_views.py, cfme/provisioning.py, cfme/tests/infrastructure/test_provisioning_dialog.py
__Fixing test_disk_format_select__  - after we moved to WT
{{pytest: --long-running --use-provider vsphere65-nested cfme/tests/infrastructure/test_provisioning_dialog.py}}
=> [1LP][RFR]fixes in provision_dialog tests

cfme/tests/infrastructure/test_snapshot.py
This changes the way how `test_verify_revert_snapshot` is run and adds additional very similar test `test_revert_active_snapshot`.
Because the two tests are so similar, I extracted the code to a standalone function `verify_revert_snapshot` that gets called in each test with different `active_snapshot` parameter. The body of the function is basically the original `test_verify_revert_snapshot` test, with exception of:
- added `active_snapshot` parameter
- line 169: determine if we need second snapshot OR we are reverting to active snapshot
- added comments
I had to comment out the events after some testing. They work fine with `test_verify_revert_snapshot` but not when `test_revert_active_snapshot` is run. According to evm.log, events are appearing fine in both cases. I have no idea where …
=> [1LP][RFR] Revert snapshot tests redone

cfme/tests/cloud_infra_common/test_discovery.py, cfme/tests/cloud_infra_common/test_events.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py, cfme/tests/cloud_infra_common/test_power_control_rest.py
__Updating tests.__ Replace testgen and pytest_generate_tests with pytest.mark.provider.
Test collections seem to be the same as before.
=> [1LP][RFR] Remove testgen from cloud_infra_common (part 1)

cfme/tests/cloud/test_cloud_timelines.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py, cfme/tests/configure/test_timeprofile.py, cfme/tests/infrastructure/test_config_management.py
__Updating tests__ to remove support of versions <5.8.
__Deleting tests__ with uncollectif always True for versions 5.8+.
=> [1LP][RFR] Removed current_version() from tests (part 2)

cfme/tests/infrastructure/test_config_management_rest.py, cfme/tests/infrastructure/test_set_default_filter.py, cfme/tests/infrastructure/test_webmks_console.py, cfme/tests/services/test_rest_services.py, cfme/tests/storage/test_object_store_object.py
__Updating tests__ to remove support of versions <5.8.
__Deleting tests__ if they are invalid for 5.8+ versions.
=> [RFR] Removed current_version() from tests (part 3)

cfme/tests/infrastructure/test_vm_power_control.py
{{pytest: --use-provider=scvmm -k 'test_no_power_controls_on_archived_vm or test_archived_vm_status' cfme/tests/infrastructure/test_vm_power_control.py}}
=> [1LP][RFR]cfme shows archived scvmm vms as orphaned 

cfme/tests/configure/test_visual_cloud.py, cfme/tests/configure/test_visual_infra.py
Making changes related to paginator and fixing automation failure.
{{pytest: -v -k 'test_infra_grid_page_per_item or test_infra_tile_page_per_item or test_infra_list_page_per_item or test_cloud_grid_page_per_item or test_cloud_tile_page_per_item or test_cloud_list_page_per_item'}}
=> [1LP][RFR]Making changes related to paginator.

cfme/infrastructure/pxe.py, cfme/services/service_catalogs/ui.py, cfme/tests/infrastructure/test_customization_template.py, cfme/tests/infrastructure/test_pxe_provisioning.py, cfme/tests/services/test_pxe_service_catalogs.py
fixes for PXE tests in 5.9.
{{pytest: cfme/tests/infrastructure/test_customization_template.py cfme/tests/infrastructure/test_pxe.py cfme/tests/infrastructure/test_pxe_provisioning.py  cfme/tests/services/test_pxe_service_catalogs.py  --long-running --use-provider vsphere65-nested}}
=> [1LP][RFR]PXE fixes for 5.9

cfme/containers/image.py
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py -v --use-provider cm-env2 }}
Fixing navigation to Container Image Details because it is currently run very slow on appliance 5.8 searching row one by one which is very slow.
add search image by Image name , before get_entity by Image ID.
=> [1LP][RFR] Image container reduce row selection time

cfme/tests/cloud_infra_common/test_retirement.py
__Wrapping__ retirement tests with Jira ticket. What I originally considered a bug is actually testing framework not reflecting the new position of button that removes retirement date. All the details in relevant Jira [ticket](https://projects.engineering.redhat.com/browse/RHCFQE-5912).
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py -k "set_retirement" -vv --use-provider rhv41 --long-running}}
=> [1LP][RFR] Wrapping retirement tests with Jira

cfme/tests/infrastructure/test_pxe_provisioning.py, data/rhel7.cfg
__Updating configuration__ for RHEL7 kickstart file used in PXE provisioning. 
- Changing bootloader options so that the newly-provisioned VM is able to power on
- Adding logging for post-installation step
- Adding wrapper because of regression in 5.9
{{pytest: cfme/tests/infrastructure/test_pxe_provisioning.py::test_pxe_provision_from_template --use-provider rhv41 -vv}}
As of now, the relevant test is __skipped__ because setup fails on mentioned BZ in 5.9. However I've tested this with manual assistance on my env and it worked as expected. Also the test for CFME 5.8 times out in PRT, but works OK in our env.
=> [1LP][RFR] Updating kickstart file RHEL7

cfme/tests/infrastructure/test_advanced_search_host.py, cfme/tests/infrastructure/test_advanced_search_providers.py, cfme/tests/infrastructure/test_advanced_search_vms.py
__Updating tests__ for using flash messages instead of cfme_exceptions.
{{pytest: cfme/tests/infrastructure/test_advanced_search_host.py::test_cannot_delete_more_than_once cfme/tests/infrastructure/test_advanced_search_providers.py::test_cannot_delete_more_than_once cfme/tests/infrastructure/test_advanced_search_vms.py::test_cannot_delete_more_than_once}}
=> [RFR] Removed cfme_exception

cfme/infrastructure/config_management.py, cfme/tests/infrastructure/test_config_management_rest.py
* BZ 1476869 fixed
* fixed data for authentication creation where wrong user id was used ("user" is not CFME user)
{{pytest: -v -k test_delete_authentications cfme/tests/infrastructure/test_config_management_rest.py}}
Error in ``config_manager_obj.delete()`` is known bug https://bugzilla.redhat.com/show_bug.cgi?id=1491704
Otherwise PRT was successful.
=> [1LP][RFR] Changes to test_delete_authentications tests

cfme/infrastructure/pxe.py, cfme/tests/cloud/test_cloud_init_provisioning.py, cfme/tests/infrastructure/test_cloud_init_provisioning.py
Purpose
`get_template_from_config()` is located not only in the fixtures, but also in `pytest_generate_tests()`. After merging #5872 customization templates are created also during the tests collecting. This fix adds `create` boolean argument into `get_template_from_config()`.
=> [1LP][RFR] Fixed get_template_from_config()

cfme/automate/explorer/method.py
This is a quick fix for test_create_snapshot_via_ae.
They seem to have reverted the success message for 5.9 to the string that is in use also for 5.8.
{{pytest: -v --long-running --use-provider vsphere65-nested -k "test_create_snapshot_via_ae"}}
=> [1LP][RFR] Fix success message for snapshot test

cfme/tests/infrastructure/test_host.py
__Wrapping__ test_multiple_host_bad_creds because of this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1524411) that causes wrong flash message to appear.
{{pytest: -vv -rs cfme/tests/infrastructure/test_host.py::test_multiple_host_bad_creds}}
=> [RFR] Wrapping test_multiple_host_bad_creds with BZ

widgetastic_manageiq/__init__.py
Intent
CFME 5.7 is deprecated and `MulitBoxSelect` can be refactored to remove 5.7 support.
{{pytest: -v -k "test_policy_profile_crud" --long-running}}
=> [RFR] Refactored MulitBoxSelect view

cfme/utils/appliance/__init__.py
Currently we have problems running CFME appliances in RHOS environment. 
The issue is that before CFME appliance image is used by Sprout system, we start the image on each provider and do pre-configuration of that image. Pre-configuration involves setup of the VMDB database. appliance_console script requires that you have new block device available for the DB. Currently we start appliances on Openstack with ephemeral disk which is then visible in the system as vdb device. Once we are done with pre-configuration we shut down the instance down and make snapshots of it. Then this snapshot is ready for use. But the problem is that ephemeral disks are deleted on instance stop and snaphots cannot be done for them. Until we come with proper solution for …
=> [1LP][RFR] Workaround: use internal disk on RHOS appliances

fixtures/browser.py
unfortunately an trace back entry path may be a plain string sometimes
=> [1LP][RFR] browser fixture: handle when exception traceback paths are plain strings

cfme/cloud/instance/__init__.py, cfme/common/vm.py, cfme/common/vm_views.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud_infra_common/test_retirement.py
Huge retirement changes in 59z/gaprindashvili
implemented set_retirement_date in cloud.instance since its converted to
WT via vm_views.
Update vm_views with new views/widgets/conditionals
With conversion of VM, this method should be applicable to cloud and
infra both, and can be moved up into common.vm
Fixes RHCFQE-5192
@rsnyman This will have some implications for your VM conversion PR
@jan-zmeskal  This should resolve the retirement tests that are blocked by the JIRA card
@rlbabyuk Could use your review here, know you wanted to look at this with @jan-zmeskal but when I started to look into it I determined it was way too complex and nasty for a WT introduction for @jan-zmeskal. Didn't want to start him off on something that would make him hate the framework.
This aims to fix the …
=> [1LP][RFR] Implement views and set_retirement_date for new retirement modes

scripts/dockerbot/pytestbase/Dockerfile
this updates the image to fedora 27, and has passing image builds, test run outstanding
=> [RFR] dockerbot - switch test image to fedora 27

cfme/tests/infrastructure/test_provisioning_dialog.py
__Change__ VM provision to use 2048 MB instead of 4096 MB as used templateate in RHV has max memory limit set to 2048MB.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py::test_change_cpu_ram  -vv}}
=> [1LP][RFR] Change VM provision to use 2048MB instead of 4096MB

cfme/tests/cloud/test_cloud_init_provisioning.py
Depends on https://github.com/ManageIQ/integration_tests/pull/5872 
Right now EC2 gives us VM IP much faster than VM is created which leads to ssh failure
=> [1LP][RFR]fix for ec2 cloudinit

cfme/scripting/quickstart.py
{{pytest: cfme/tests/containers/test_basic_metrics.py -v --use-provider cm-env2 }}
Update quickstart redhat_packages_specs in order to suport  RHEL Workstation .
=> [1LP][RFR] Update quickstart redhat_packages_specs with RHEL Workstation

cfme/base/ui.py, cfme/configure/configuration/diagnostics_settings.py, cfme/configure/configuration/server_settings.py, cfme/tests/configure/test_server_name.py, cfme/utils/appliance/__init__.py
8+ tests
`appliance.server_name()` would get invalidated but `appliance.server.name` wouldn't. This takes care of that issue.
I'm leaving the deprecated methods in, just in case. I believe they could be just removed, but I'd prefer to do it the nice way, as planned by whoever added the deprecation messages.
Edit:
Removed all caching. Also removed `zone_description` in favor of `zone.description`. There is no mention of `zone_description` in the whole codebase, except the 2 changes I've made, so I believe it is safe to just remove, without deprecating it first.
{pytest: cfme/tests/configure/test_server_name.py}}
=> [1LP][RFR] Fix appliance server and server name test, remove caching

cfme/tests/infrastructure/test_webmks_console.py
__Updating tests__ WebMKS Console now supports "Connection Status Display", "CtrlAltDel Button" and "ToggleFullScreen" Button on latest 5.9 builds. Updating automation to support that.
These features are currently in 5.9 only. Soon to be added in CFME 5.8 as well.
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere65-nested }}
PRT Build : 19123
58z- had bug, and its fixed, but not present in current build, fix will be available probably in next build tomorrow and test should pass , https://bugzilla.redhat.com/show_bug.cgi?id=1500445
59z- works
upstream - inconsistent failure, it should really pass but it didn't, I just ran it locally and it passed with no issues.
=> [1LP][RFR] Extending test to assert FullScreen Button, Ctrl+Alt+Del Button and Connection Status, which are newly added

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vm_reconfigure.py, widgetastic_manageiq/vm_reconfigure.py
__Adding test__ test_vm_reconfig_add_remove_disk_cold for RHV provider. Until now, it was available only for VMware. However, the same thing can be done for RHV and therefore should be tested. 
When the test case is parametrized for `disk_mode` = 'independent_persistent' or 'independent_nonpersistent', it is uncollected for RHV. It is because disk mode cannot be specified at all when adding RHV provider.
This test case has not been working properly for VMware before and I am pretty sure I did not break it any more than it was. If anything, the change of `is_displayed()` method of `VmsTemplatesAllView` class causes that it does not fail at the very beginning.
{{pytest: -vv -rs cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_disk_cold --use-provider rhv41 …
=> [1LP][RFR] Enabling test_vm_reconfig_add_remove_disk_cold for RHV provider

cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py
Changed NavigateToSibling to NavigateToAttribute for Container Details
```
coll = appliance.collections.container_routes
route = coll.instantiate(name='docker-registry', project_name= 'default', provider=juwatts)
navigate_to(route, 'Details')
Out[7]: <cfme.containers.route.RouteDetailsView at 0x7fbec5028bd0>
```
=> [1LP][RFR] Changed NavigateToSibling to NavigateToAttribute for Container Details Classes

cfme/common/provider.py
The warning will look like this, once we get 5.8.3.1:
```
[WARNING] ./cfme/common/provider.py:153: UserWarning: REMOVE ME: BZ#1526050
warnings.warn('REMOVE ME: BZ#1526050')
(/home/jkrocil/Workspace/cfme_tests/cfme/common/provider.py:153)
```
I didn't use BZ.blocks because it seems unnecessary. The issue is urgent and should be fixed in the next build.
Tested locally.
=> [1LP][RFR] Workaround for vsphere setup in 5.8.3.0

cfme/common/provider_views.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, conf/cfme_data.yaml.template
Adding Support for
Alerts:
New dropdown widget called "Alerts", that when selected, creates a new Endpoint nested tab.
Settings:
A new form called "Settings" with two nested tabs, "Proxy" and "Advanced", was added to the "Add New Containers Provider" view. 
{{ pytest: --use-provider cm-env2 --long-running  cfme/tests/containers/test_ssl_providers.py }}
=> [1LP][RFR] Adding Support for Alerts Endpoint and Settings for OpenShift Provider

cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/replicator.py, cfme/containers/route.py, cfme/containers/service.py, cfme/containers/template.py, cfme/containers/volume.py
The scope of this PR is to create the all method for each Collection Class for all of the Container Objects. Existing all methods have been updated to support filtering.
Adding the Collection Classes for the Container objects is handled in:
https://github.com/ManageIQ/integration_tests/pull/6091 
Manual Testing, two providers were configured (Few examples):
```
In [2]: snaim
Out[2]: <cfme.containers.provider.openshift.OpenshiftProvider name='CM SNAIM 36', key='cm-snaim-36', zone='default', metrics_type='Hawkular'>
In [3]: juwatts
Out[3]: <cfme.containers.provider.openshift.OpenshiftProvider name='CM JUWATTS', key='cm-juwatts', zone='default', metrics_type='Hawkular'>
In [4]: coll_image_reg = appliance.collections.container_image_registries
In [5]: coll_image_reg.all()
Out[5]: …
```
=> [1LP][RFR] all() For Container Collection Classes

cfme/configure/configuration/region_settings.py
Updating BZ id to [1525929](https://bugzilla.redhat.com/show_bug.cgi?id=1525929) because flash message is missing after deleting category.
{{pytest: -v cfme/tests/infrastructure/test_infra_tag_filters_combination.py -k test_tagvis_tag_datacenter_combination[clusters-visible]}}
=> [1LP][RFR]Updated BZ id for Category delete flash msg

conf/env.yaml.template
__Updating__ env.yaml.template. As far as I understand this is now the proper way how to initialize IPAppliance without getting deprecation warning.
https://github.com/ManageIQ/integration_tests/blob/master/cfme/utils/appliance/__init__.py#L2593
=> [RFR] Updating env.yaml.template

cfme/tests/test_login.py
This test will fail in 5.8 due to this bz 1089786.This bz is only fixed in 5.9. 
{{pytest: -v cfme/tests/test_login.py -k test_bad_password}}
=> [1LP][RFR] Checks Password field empty or not after invalid login attempt

cfme/common/vm.py, cfme/tests/cloud_infra_common/test_retirement.py
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py --long-running }}
PRT fails because of provider's issues
=> [RFR] Fix retirement tests

scripts/template_upload_all.py, scripts/template_upload_scvmm.py
needs - 
-  https://github.com/ManageIQ/wrapanapi/pull/201
- https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/399
```
(CFME) lkhomenk@Fuzzy ~/git/integration_tests (scvmm_upload_template_fix) $ git log -1
commit 6f61f5f06216599a8c68cc3015e33f91dabbda55
Author: Leonid Khomenko <lkhomenk@redhat.com>
Date:   Thu Dec 14 23:11:29 2017 +0200
scvmm upload template fixes
(CFME) lkhomenk@Fuzzy ~/git/integration_tests (scvmm_upload_template_fix) $ python scripts/template_upload_all.py --provider-type scvmm --image_url http://file.cloudforms.lab.eng.rdu2.redhat.com/builds/cfme/5.9/stable/
[WARNING] ./cfme/utils/appliance/__init__.py:2739: DeprecationWarning: Using class 'CurrentAppliance' (either directly or via inheritance) is deprecated: The CurrentAppliance descriptor is being …
```
=> [1LP][RFR]scvmm upload template fixes

cfme/common/provider.py
Fixes a bug in the workaround introduced in #6182 
I've tested locally by configuring ec2west, rhv41, and vsphere65-nested providers.
vsphere65-nested configuration fails because the VMRC tab is required and we don't have these values in the YAML to fill with, not related to this workaround fix.
=> [RFR] Fix 5.8.3.0 workaround for RHEVMProvider in common

cfme/tests/cloud_infra_common/test_vm_ownership.py
Changing user_ownership_vm.exists to group_ownership_vm.find_quadicon(from_any_provider=True) for restricted user, due to error "Could not find the item Instances by Provider/ec2-west in Boostrap tree instances_tree" because restricted user doesn't have permission to see Instances by Provider/ec2-west, another way is to search through All Instances.
{{pytest: -v cfme/tests/cloud_infra_common/test_vm_ownership.py -k 'test_user_ownership_crud or test_group_ownership'}}
=> [1LP][RFR]Changing the way of selecting instances for test_group_ownership

cfme/ansible/repositories.py, cfme/automate/buttons.py, cfme/infrastructure/virtual_machines.py, cfme/tests/ansible/test_embedded_ansible_automate.py
Intent
__Adding test__  for ordering ansible service via a custom button. That feature implemented in version 5.9.
{{pytest: -v -k "test_custom_button_order_ansible_playbook_service" --long-running}}
=> [1LP][RFR] Added test_custom_button_order_ansible_playbook_service

cfme/ansible/repositories.py, cfme/automate/explorer/method.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/ansible/test_embedded_ansible_basic.py, cfme/tests/ansible/test_embedded_ansible_services.py
Purpose
In the recent builds it takes a while until ansible playbooks appeared in the ui, we should wait until repository status will be "successful".  Also in some cases "Add New Repository" item is disabled, but embedded ansible role is enabled. I couldn't reproduce it locally, so it will be sort of experiment.
{{pytest: -v -k "test_automate_ansible_playbook_method_type_crud" --long-running}}
=> [1LP][RFR] Various fixes and workarounds for embedded ansible tests

cfme/services/catalogs/catalog_item.py
* Sometimes a form breaks, a subsequent navigation will be left with
a tainted form. This needs to be mitigated by performing a
re-navigation
=> [1LP][RFR] We should always assume we are not on the Add pages

cfme/tests/cloud_infra_common/test_retirement.py
Missed a web_ui.toolbar call in test_retirement
{{ pytest: --long-running -v -k test_retirement_now_ec2_instance_backed --use-provider ec2west }}
PRT failures unrelated to this fix. (ec2 config failure and instance create timeout)
=> [RFR] Update toolbar.refresh in test_retirement

cfme/tests/automate/test_vmware_methods.py
* You cannot View.nested an ordinary class
* Widgets must always be placed on another Widget or instantiated directly with browser
=> [RFR] Fix "this constructor takes no arguments" error

cfme/storage/volume.py, cfme/tests/storage/test_volume_backup.py
- Added BZ related to issue: [#1528154](https://bugzilla.redhat.com/show_bug.cgi?id=1528154)
- Some time for smaller volume and most of time for larger volume on openstack status='error'
- added `status` property in `volume.py` to check status of `volume`
- Improved `backup_create` method in `volume.py` check for `initial_cound` and then compair
- added check for status in `test_volume_backup.py` else it will skip all backup test due to volume creation fail on provider side.
{{pytest: cfme/tests/storage/test_volume_backup.py  -v}}
=> [1LP][RFR]fix: backup error

cfme/infrastructure/virtual_machines.py
Fix navigation Issue in Upstream
==========================
{{pytest: cfme/tests/infrastructure/test_timelines.py -k "test_timeline_events" --use-provider=vsphere6-nested}}
It was impossible to navigate to the VM's Details/Timeline pages and other menu in the toolbar in Upstream. This is because it was because it was not finding the button "Reload" In the toolbar. 
PR like #6149 were failing in upstream.
=> [1LP][RFR] added the reload button in InfraVmDetailsToolbar

cfme/tests/configure/test_access_control.py
* If the item wasn't created we can't use it in navigation
* Fallout from the CEMv3 conversion
=> [RFR] Some access control fixes

cfme/tests/automate/test_service_dialog.py
Issue fixed with new flash text
{{pytest: -v cfme/tests/automate/test_service_dialog.py -k test_service_dialog_duplicate_name}}
=> [RFR] Fixed test_service_dialog_duplicate_name issue

cfme/tests/cloud/test_providers.py
1. uncollectif `test_password_mismatch_validation` for 5.9 as discovery for `ec2` not possible and password validation only for `EC2` not for `Azure`
2. `test_empty_discovery_form_validation` moved on Azure
3. `test_discovery_cancelled_validation` moved on Azure
{ pytest: cfme/tests/cloud/test_providers.py -k "test_empty_discovery_form_validation or test_empty_discovery_form_validation or test_discovery_cancelled_validation"}}
=> [1LP][RFR]  fix: test_password_mismatch_validation

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
__Fixing test framework__ for proper work of snapshot_vm_memory checkbox selection.
{{pytest: --long-running cfme/tests/infrastructure/test_snapshot.py}}
=> [1LP][RFR] Fixed the framework bug with selection of Snapshot VM memory checkbox

cfme/control/explorer/alerts.py
Purpose
"Severity" field that was introduced in Alerts in 5.9 is removed in 5.9.0.14.
{{pytest: -v -k test_alert_crud -- long-running}}
=> [RFR] Changed severity argument to None in Alert class

cfme/intelligence/chargeback/rates.py, cfme/tests/intelligence/test_chargeback.py
__Fixing__ test_chargeback because the view was simplified to show variable rate only when it has a value.
Comment from developer: ```simplify editor, by disabling variable rate edit for fixed rates (allow edit only when this value already exists)```
{{pytest: cfme/tests/intelligence/test_chargeback.py}}
=> [RFR] Fixed test_chargeback.py NoSuchElementException

cfme/configure/configuration/region_settings.py
__Fixing__ CANDU create for skipping flash message assertion when nothing changed and Save and Reset buttons are disabled.
=> [RFR] added skip assert CANDU flash message when nothing changed

widgetastic_manageiq/__init__.py
There was a locator issue related to click operation on table in the widget which is resolved in this PR.
{{pytest: -v -k 'test_provisioning_dialogs_sorting'}}
=> [1LP][RFR] Resolved locator issue for test_provisioning_dialogs_sorting

cfme/automate/provisioning_dialogs.py
Purpose 
Updated provisioning_dialogs flash messages to assert by description not by name after code [change](https://github.com/ManageIQ/manageiq-ui-classic/pull/2027) for [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1481637).
{{pytest: -v cfme/tests/automate/test_provisioning_dialogs.py -k test_provisioning_dialog_crud}}
=> [1LP][RFR]Fixed provisioning_dialogs flash messages

cfme/tests/intelligence/reports/test_canned_corresponds.py
Purpose 
Fix for test_cluster_relationships SoftAssertionError: Cluster hyperv_cluster not found in ms-scvmm (cfme/tests/intelligence/reports/test_canned_corresponds.py:57). 
Added to get the first element from provider.list_cluster.
{{pytest: -v cfme/tests/intelligence/reports/test_canned_corresponds.py -k test_cluster_relationships --use-provider=ms_scvmm}}
=> [1LP][RFR]Fix for test_cluster_relationships SoftAssertionError

cfme/fixtures/tag.py
Purpose 
Fixing fixture check_item_visibility because of failing test_tagvis_tag_datacenter_combination
{{pytest: -v cfme/tests/infrastructure/test_infra_tag_filters_combination.py -k test_tagvis_tag_datacenter_combination}}
=> [1LP][RFR]Fixing fixture check_item_visibility

cfme/tests/infrastructure/test_advanced_search_host.py, cfme/tests/infrastructure/test_advanced_search_vms.py
================
There is a change in UI, now the save button appears before load option hence causing failure, which is fixed in this PR.
{{pytest: -v -k 'test_delete_button_should_appear_after_save'}}
=> [1LP][RFR]Fix for advance search failure: test_delete_button_should_appear_after_save

cfme/configure/configuration/server_settings.py, cfme/tests/configure/test_server_roles.py
- test fixed
- removed `rhn_mirror` and add `cockpit_ws`
{{ pytest: -v cfme/tests/configure/test_server_roles.py }
=> [1LP][RFR] changes in rhn_mirror, cockpit_ws

cfme/tests/configure/test_access_control.py
__Fixing__ test_user_duplicate_username because it is currently testing identical Full Name field instead of Username.
__Adding__ test to check that it is allowed to create users with same full name.
{{pytest: -v cfme/tests/configure/test_access_control.py::test_user_duplicate_username cfme/tests/configure/test_access_control.py::test_user_allow_duplicate_name}}
=> [RFR] Fixed test_user_duplicate_username to check duplicate Username instead of Full Name

cfme/configure/access_control.py, cfme/tests/configure/test_access_control.py
Changed `instantiate` to `create` so that the test can use it to create group with that role. This fixes the `NoSuchElement found` exception occurring due to the dummy instantiated role not found in the create group view.
{{ pytest: -vvv cfme/tests/configure/test_access_control.py -k test_role_crud }}
=> [RFR] Fixed failing tests due to role not created

cfme/tests/test_utilization_metrics.py
- https://bugzilla.redhat.com/show_bug.cgi?id=1525296
- block some tests related to raw_metric
- **Note: Collect for All Clusters must be checked to be able to collect C & U data from Cloud Providers such as Red Hat OpenStack or Amazon EC2**
{{pytest: cfme/tests/test_utilization_metrics.py -v --long-running }}
=> [1LP][RFR] C&U: skipping for cloud provider

cfme/common/vm.py
__Fixing__ BaseVM.is_retired to catch proper exception.
Fixes test_retirement.py.
{{ pytest: --long-running cfme/tests/cloud_infra_common/test_retirement.py }}
=> [RFR] Changed except AtrributeError to catch NameError

cfme/services/service_catalogs/ui.py
changed `name` to `id`, because in `5.9` only `id` is there in these `input`
{{ pytest: -vvv cfme/tests/services/test_provision_stack.py }}
=> [RFR] Fix for change in id

cfme/tests/infrastructure/test_vm_power_control.py
__Fixing__ test to check the presence of a power dropdown.
{{pytest: --long-running cfme/tests/infrastructure/test_vm_power_control.py -k test_no_power_controls_on_archived_vm}}
=> [RFR] Fixed test_no_power_controls_on_archieved_vm

cfme/generic_objects/definition/rest.py, cfme/generic_objects/instance/rest.py
{{pytest: cfme/tests/generic_objects/test_instances.py cfme/tests/generic_objects/test_definitions.py}}
=> [1LP][RFR] fix for LookupErrors in generic objects

docs/guides/faq.rst
__Adding FAQ section__ to the docs.
OK, I don't really know if these questions are asked frequently. But it is better name than "Questions That Have Been Asked in the Past and Might Be Asked Again". Imagine the acronym. 
- __Why?__ As a new guy working with the framework, those are some of the questions I have encountered. Therefore there's a chance that the next new guy might ask them as well.
- __Why not put those into Development Tips and Tricks?__ Because they aren't really about developing the framework or tests. They are more about using it. But if you think this belongs there, I am okay with that.
- __Another benefit?__ I think this could be a convenient place to gather some cool tips that can be found in mailing threads from time to time. 
There's not many of them, but if you …
=> [1LP][RFR] Adding FAQ to docs

cfme/cloud/instance/__init__.py, cfme/common/vm.py
PRT results:
test_user_ownership_crud[ec2west]  failed in both 58 and 59 and the failure is not related to code changes made through this PR.
{{pytest: -v -k 'set_ownership or user_ownership'}}
=> [1LP][RFR] Move set_ownership and unset_ownership to a common area

cfme/tests/containers/test_ssl_providers.py
The test was deleting and attempting to readd the provider before CFME had fully deleted the previous provider, which would cause a failure in adding the new provider. Adding wait_for_delete() method to prevent hitting this case.
{{ pytest: cfme/tests/containers/test_ssl_providers.py --use-provider cm-env2 --long-running }}
Failures in PRT are not caused by these changes
=> [1LP][RFR] Adding wait_for_delete() to Container SSL Tests

fixtures/xunit_tools.py
* add whitelist for test that would be otherwise matched by blacklist, but we want them in our Polarion (some rhv variants etc.)
* add (invisible) timestamp so tests are updated in Polarion even when no fields were changed (so it's possible to search for tests that are active, i.e. were updated recently)
=> [1LP][RFR] Add whitelist for tests that would be blacklisted

cfme/tests/infrastructure/test_timelines.py
Exclude RHEVM provider
Exclude RHEVM provider, refactor the variable name where it is excluded. 
Also add RHEVM tl_event in the action, as the event has been added.
https://bugzilla.redhat.com/show_bug.cgi?id=1513389
{{pytest: -v -q cfme/tests/infrastructure/test_timelines.py --use-provider=rhv41 }}
=> [1LP][RFR] Timeline fix rhevm

cfme/tests/cloud_infra_common/test_html5_vm_console.py, cfme/tests/infrastructure/test_instance_analysis.py
{{pytest: --long-running cfme/tests/infrastructure/test_instance_analysis.py cfme/tests/cloud_infra_common/test_html5_vm_console.py}}
fix includes:
1.  updated RHOS11 floating ips configuration (wrong ext subnet was used for obtaining ips)
2. updated yamls. rhos7-ga and rhos11 have public_network now.
3. hardcoded network for openstack providers is removed from tests and replaced with yaml value
=> [1LP][RFR] fix of NoMoreFloatingIPs issue for tests against RHOS11

cfme/base/ui.py, cfme/configure/access_control/__init__.py, cfme/configure/configuration/server_settings.py, cfme/fixtures/configure_auth_mode.py, cfme/tests/integration/test_aws_iam_auth_and_roles.py, cfme/tests/integration/test_cfme_auth.py
Create a conditionalswitchable view and remove navigation destinations
that were modifying the authentication tab form.
refactor methods for getting/setting auth configuration
I am addressing failures in `test_cfme_auth.py` that are related to my changes, but am not currently trying to fix all the tests there. I plan to address these tests within the stabilization phase, but after getting these view/navigation updates for `Server`, `ServerInformation`, and `ServerAuthentication` approved and merged.
The `test_aws_iam_auth_and_roles` is currently blocked by a few BZs that should be fixed in the next 2 weeks.
=> [1LP][RFR] Refactor server auth settings views/methods

cfme/containers/provider/__init__.py
{{ pytest: cfme/tests/containers/test_properties.py --use-provider ocp-v2 }}
- Fixed is_displayed after changed to use_search (when we use search the text will include include (Names with "..."))
=> [RFR] Fixed is_displayed after changed to use_search

cfme/containers/volume.py
Added a filter to only return volumes with the type "PersistentVolume". This matches what is displayed in the GUI.
Manual Testing:
Pre filter:
```
In [2]: coll = appliance.collections.container_volumes
In [3]: coll.all()
Out[3]: 
[Volume(name=u'pv-10', provider=<cfme.containers.provider.openshift.OpenshiftProvider name='ose3-master.ksi83.cmqe.eng.bos.redhat.com', key='ose3-master.ksi83.cmqe.eng.bos.redhat.com', zone='default', metrics_type='Hawkular', alerts_type='Disabled'>),
Volume(name=u'pv-9', provider=<cfme.containers.provider.openshift.OpenshiftProvider name='ose3-master.ksi83.cmqe.eng.bos.redhat.com', key='ose3-master.ksi83.cmqe.eng.bos.redhat.com', zone='default', metrics_type='Hawkular', alerts_type='Disabled'>),
Volume(name=u'pv-8', …
```
=> [1LP][RFR] Added filter for PersistentVolume to containers.volume.all()

cfme/tests/control/test_alerts.py
{{pytest: -v -k test_alert_timeline_cpu --long-running --use-provider vsphere6-nested}}
=> [RFR] Fixed test_alert_timeline_cpu

requirements/frozen.txt, scripts/azure_cleanup.py
Right now  cleanup is broken on jenkins. ~~to loop though subscriptions we ought to re-instantiate some azure components. - added method for that~~. also extended all current cleanup methods to use Resource group.
Our cleanup will loop though subscription:resource_groups:storage_account:containers.
Logging was left as we have right now - no reporting, only stdout log with what we have removed 
needs - https://github.com/ManageIQ/wrapanapi/pull/204
=> [1LP][RFR]Azure cleanup

fixtures/log.py, fixtures/parallelizer/remote.py
* The call to managed_provider could cause INTERNALERROR because it
used current_appliance. This usually points to the first slave in the
case of the master in a parallelized setup. The problem is that if
slave00 dies/shutdown and something fails in teardown, we can't get
managed_provider calls to work because the appliance has gone.
* We now only run this on the master if we are not running in a
parallelized setup. If we are in a parallelized setup we now run it
in the client process instead. This means we can access the slaves
own appliance instead of get_current_appliance of the master. This
should always get us a good appliance and if the appliance isn't good
then subsequent tests will fail anyway.
=> [1LP][RFR] Fix for managed_provider call

cfme/common/provider_views.py, cfme/physical/provider/__init__.py, cfme/physical/provider/lenovo.py, cfme/tests/physical_infrastructure/test_providers.py
Introducing provider crud tests for the lenovo provider. Adding a separate set of crud tests from the existing test_provider_crud to module how the lenovo provider specifically is implemented. (Not an infrastructure provider, but some button labels say infrastructure vs physical infrastructure)
Depends on  changes from PR https://github.com/ManageIQ/integration_tests/pull/5761
=> [1LP][RFR] Test provider crud

cfme/tests/containers/test_reports.py
{{ pytest: cfme/tests/containers/test_reports.py -m 'not long_running_env' --use-provider ocp-v1 }}
Fix test reports
=> [1LP][RFR] Fix test reports

requirements/frozen.txt
This update should fix "AttributeError: This is not an instance of fields. You need to call this object and pass the required parameters of the view."
{{pytest: -v -k test_automate_ansible_playbook_method_type_crud --long-running}}
=> [1LP][RFR] widgetastic.core 0.20.1

cfme/tests/cloud_infra_common/test_events.py
__Deleteing__ BZs that are not needed anymore (already in VERIFIED or CLOSED ERRATE status).
{{pytest: cfme/tests/cloud_infra_common/test_events.py::test_vm_create --use-provider rhv41}}
=> [1LP][RFR] Deleting BZs no more needed for test_vm_create

cfme/tests/infrastructure/test_vm_reconfigure.py
__Fixing__ test_vm_reconfig_add_remove_hw_cold for memory. The reason is that rhv_cfme_integration provider uses small_template that has max memory 2048 MB. Therefore it we attempt to increase it by 512 MB, it will never happen. We can, however, decrease it instead. And it test the functionality pretty much the same way. 
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_hw_cold[rhv41-memory] -vv --long-running}}
=> [1LP][RFR] Adjusting test_vm_reconfig_add_remove_hw_cold memory value

cfme/tests/containers/test_ad_hoc_metrics.py, cfme/tests/containers/test_basic_metrics.py, cfme/tests/containers/test_cockpit.py, cfme/tests/containers/test_configurable_menus.py
{{ pytest: cfme/tests/containers/test_ad_hoc_metrics.py cfme/tests/containers/test_basic_metrics.py cfme/tests/containers/test_cockpit.py cfme/tests/containers/test_containers_summary.py cfme/tests/containers/test_configurable_menus.py --use-provider ocp-v1 }}
- Remove undesirable uncollections
- configurable menus should be invisible by default - changed the name
to test_invisible_menus
- Updated skippers for test_cockpit
=> [1LP][RFR] Remove undesirable uncollections

cfme/containers/pod.py, cfme/containers/project.py, cfme/tests/containers/test_labels.py
{{ pytest: cfme/tests/containers/test_labels.py --use-provider ocp-v1 }}
- Fixed versioning in project restter
- Fixed test_labels
=> [1LP][RFR]  Fixed test_labels

cfme/tests/infrastructure/test_vm_power_control.py, cfme/utils/virtual_machines.py
__Fixing__ deploy_template method so it is consistent with new way of defining templates:
templates:
- small_template
- name: my_template
- creds: my_creds
The old way is kept for backwards compatibility.
I am getting `INTERNALERROR> Exception: SSH is unavailable` for 5.9 in PRT. However, I tested this locally and the change is pretty straightforward.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_no_power_controls_on_archived_vm --use-provider rhv41-vv --long-running}}
=> [1LP][RFR] Fixing deploy_template to get small_template name properly

cfme/tests/cloud/test_cloud_timelines.py
Fix the imports and pytest.mark.provider
RHOS should not be tested for the timelines, as it is done by a dedicated team. We are testing only EC2 (>= 5.8) and Azure. This PR excludes OpenStack.
{{pytest: -v -k test_cloud_instance_event --collect-only --use-provider=complete}}
=> [1LP][RFR] fix the import statements in order to exclude OpenStack provider

cfme/tests/containers/test_tables_sort.py
{{ pytest: cfme/tests/containers/test_tables_sort.py --use-provider ocp-v1 }}
- Fixed test_tables_sort
- Skip the test due to issue: https://github.com/ManageIQ/integration_tests/issues/6385
=> [1LP][RFR] Fix test_tables_sort

cfme/configure/configuration/server_settings.py
__Fixing__  CFME Version in server settings in order to copy the SDK on 5.8 appliances as well
{{ pytest: cfme/tests/infrastructure/test_webmks_console.py --use-provider vsphere65-nested }}
=> [RFR]Updating CFME Version in server settings in order to copy the SDK on 5.8 appliances as well

cfme/tests/cloud_infra_common/test_power_control_rest.py
__Fixing__ wait_for_vm_state_change method. Without this fail_func, REST API is just returning last known power state regardless of VM's actual power state.
This refreshing of relationships is done via UI. It would probably be better to do it via REST, but I don't think such method exists in the framework. At least I could not find it. So if you know about better way, feel free to point it out to me.
{{pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py  -vv --use-provider rhv41}}
=> [1LP][RFR] Fixing wait_for_vm_state_change method

cfme/tests/containers/test_smart_management.py
{{ pytest: cfme/tests/containers/test_smart_management.py --use-provider ocp-v1 }}
Fix test_smart_management
=> [1LP][RFR] Fix test_smart_management

cfme/tests/services/test_cloud_service_catalogs.py
{{pytest: -v --long-running --use-provider ec2 cfme/tests/services/test_cloud_service_catalogs.py }} 
While provisioning values in dropdown of security_group and instance_type are different for 5.8 and 5.8.
Ex: for 5.8 instance_type shows value "m1.tiny" and for 5.9 value displayed is "m1.tiny :1 CPU ..." 
So by adding partial match to the value only m1.tiny is checked in the dropdown value and then selected.
=> [1LP][RFR] Added partial match for updated values in 5.9

cfme/services/service_catalogs/ui.py, cfme/tests/ansible/test_embedded_ansible_services.py, widgetastic_manageiq/__init__.py
Intent
BZs [1519275](https://bugzilla.redhat.com/show_bug.cgi?id=1519275) and [1515841](https://bugzilla.redhat.com/show_bug.cgi?id=1515841) are fixed. This PR introduces new widget `DialogFieldDropDownList` that is quite similar to `BootstrapSelect`. It depends on this [PR](https://github.com/RedHatQE/widgetastic.core/pull/69) in widgetastic.core repo and #6310.
{{pytest: -v -k test_service_ansible_playbook_order_credentials --long-running}}
=> [1LP][RFR] Fixed order catalog screen for ansible services

fixtures/xunit_tools.py
Whitelist also Open Stack tests. For this tests it's not necessary to filter providers, so simplification of the regex to match the file name works as expected.
=> [1LP][RFR] Add cloud tenant quota tests to whitelist

cfme/tests/openstack/infrastructure/test_resources.py
Replaced obsolete WebUI get_detail with view_details.entities.properties.get_text_of
{{ pytest: cfme/tests/openstack/infrastructure/test_resources.py }}
=> [1LP][RFR] fix 2 tests from test_resources

cfme/common/vm.py
{{pytest: -v -k test_alert_snmp --long-running --use-provider vsphere6-nested}}
=> [1LP][RFR] Fixed wait_candu_data_available method in VM class

cfme/tests/configure/test_access_control.py
Purpose 
Refactored test, added new action to view VMs insted of provisioning VM as there is  a separate test for provisioning.
{{pytest: -v cfme/tests/configure/test_access_control.py -k test_permission_edit}}
=> [1LP][RFR] Fixed test_permission_edit

cfme/tests/ansible/test_embedded_ansible_services.py
Purpose
It should fix the issue when an ansible credential cannot be deleted during teardown.
~~There is no test for PRT because #6303 hasn't been merged yet.~~
{{pytest: -v -k test_custom_button_ansible_credential_list  --long-running}}
=> [1LP][RFR] Fixed ansible_credential fixture in test_embedded_ansible_services.py

docs/guides/faq.rst
__Extending__ FAQ in docs by pycurl error that occurs in Fedora 27.
=> [1LP][RFR] Adding pycurl error to FAQ

cfme/tests/containers/test_ssl_providers.py
Block test_ssl_providers until https://github.com/ManageIQ/integration_tests/issues/6409 is resolved. 
{{ pytest: cfme/tests/containers/test_ssl_providers.py --use-provider cm-env2 --long-running }}
=> [1LP][RFR] Blocking test_ssl_providers

cfme/tests/cloud/test_providers.py
- As per new build Azure also removed for discovery.. so no more cloud provider support for discovery. limiting discovery test to 5.8 only. 
{{pytest: -vv cfme/tests/cloud/test_providers.py -k 'test_empty_discovery_form_validation or test_discovery_cancelled_validation or test_password_mismatch_validation'}}
=> [1LP][RFR] Provider Discovery limit to 5.8

cfme/tests/cloud/test_providers.py
Added one more click for dropdown selection as workaroud for bz 1475303
{{pytest: -vvv -k 'test_hostname_max_character_validation or test_add_cancelled_validation'}}
=> [1LP][RFR] Added workaround step for provider tests

cfme/services/myservice/ui.py, cfme/tests/ansible/test_embedded_ansible_services.py
"Plays" table in an ansible service details is not a "SummaryTable" anymore.
{{pytest: -v -k test_service_ansible_playbook_plays_table --long-running}}
=> [1LP][RFR] Fixed test_service_ansible_playbook_plays_table

cfme/exceptions.py, cfme/intelligence/chargeback/rates.py, cfme/tests/intelligence/reports/test_validate_chargeback_report.py, cfme/tests/intelligence/test_chargeback.py
Some refactoring of the chargeback rates views and CRUD methods, moving flash message assertions into the tests.
Only parametrized one test to highlight a BZ blocker, @nachandr will be following up with more parametrization of the test case, reducing the separate create/edit/delete tests to a single function.
{{ pytest: cfme/tests/intelligence/test_chargeback.py --use-provider vsphere65-nested --long-running }} 
The test_validate_chargeback_reports is currently blocked from BZ's.
Test skips from blockers, passing otherwise.
=> [1LP][RFR] Update Chargeback Rates, views, navigation, and CRUD tests

cfme/tests/cli/test_evmserverd.py, cfme/tests/integration/test_cfme_auth.py, cfme/tests/optimize/test_bottlenecks.py
__Updating tests__ with uncollectifs because they are incompatible with podified versions of appliance.
=> [1LP][RFR] Uncollecting tests incompatible with podified appliances.

cfme/tests/intelligence/reports/test_validate_chargeback_report.py
1)Removed a few BZ blockers that are not relevant anymore.
2)Added BZ blocker 1532368 for 59 so that all test_validate_custom_rate* tests except  test_validate_custom_rate_storage_usage_cost are blocked.
https://bugzilla.redhat.com/show_bug.cgi?id=1532368 No variable input while adding adding new Chargeback storage rates
=> [1LP][RFR] Adding BZ blocker for test_validate_custom_rate_storage_usage_cost 

cfme/intelligence/chargeback/assignments.py, cfme/tests/intelligence/test_chargeback_assignments.py
- row name changed its combination of provider name and cluster name
{{py.test: -vv cfme/tests/intelligence/test_chargeback_assignments.py -k 'test_assign_compute_cluster'}}
=> [1LP][RFR] assign_compute_cluster_fix

cfme/common/provider.py, cfme/tests/infrastructure/test_provider_discovery.py
- Its fix for teardown TimedOut error in `test_discover_infra[rhevm-virtualcenter]`
- For REST `clear_provider()` method we are using individual provider `wait_for_delete()`. As its REST adding common check for it. It will be fast and effective check for collective multiple provider deletion. 
- For diffrent types of provider discovery at single time take time to appear on UI. so refreshing browser. 
- refresh witll fix ssvm discovery problem as well
{{py.test: cfme/tests/infrastructure/test_provider_discovery.py -vvv}}
=> [1LP][RFR] test_discover_infra[rhevm-virtualcenter] teardown failure 

cfme/configure/configuration/server_settings.py, cfme/utils/appliance/__init__.py
Small enhancement to help with the ext auth test refactoring that's in-progress.
Nothing using it yet obviously, but I've tested it locally, easy enough to grab appliance object and call fqdn property.
=> [1LP][RFR] Add appliance.fqdn, hostname to ServerInformation

cfme/tests/infrastructure/test_provisioning.py
This PR has 4 points:
- Removing old unnecessary blocker
- Little refactoring of provisioning_data
- Workaround for widgetastic [issue](https://github.com/RedHatQE/widgetastic.core/issues/74)
- Probably most important is making check for number of received e-mails more strict. This is necessary to automate verification of [BZ 1422208](https://bugzilla.redhat.com/show_bug.cgi?id=1422208)
{{pytest: cfme/tests/infrastructure/test_provisioning.py::test_provision_approval -vv --use-provider rhv41}}
__Note to PRT result:__ The failure on 5.8 looks like env problem - missing storage?
=> [1LP][RFR] Cleaning test_provision_approval and making it more strict

cfme/utils/blockers.py
When debugging why https://github.com/ManageIQ/integration_tests/pull/6410 was not being blocked by the open GH issue, @mshriver and I discovered that we are setting upstream_only to True by default. 
We believe that the default should be set to False and the user must explicitly set upstream_only to True if we are referencing a GH issue for ManageIQ. 
Since we do not set the default repo to upstream ManageIQ, we do not see a reason to specify upstream or downstream since other repos do not necessarily follow this convention (for example, fauxfactory).
=> [1LP][RFR] Update the default of upstream_only to False in cfme.utils.blockers

cfme/tests/cloud/test_provisioning.py
added `partial_match` to solve `NoSuchElementException` ([Traceback](https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-59z/job/downstream-59z-tests-master/223/Artifactor_Report/cfme/tests/cloud/test_provisioning.py/test_provision_from_template[azure-Manual]/filedump-traceback.log), [Screenshot](https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-59z/job/downstream-59z-tests-master/223/Artifactor_Report/cfme/tests/cloud/test_provisioning.py/test_provision_from_template[azure-Manual]/filedump-exception_screenshot.png))
{{ pytest: -vvvv cfme/tests/cloud/test_provisioning.py -k test_provision_from_template --use-provider azure }}
=> [1LP][RFR] Fix for azure enviroment vars partial match

cfme/tests/cloud/test_provisioning.py
{{ pytest: -vvv cfme/tests/cloud/test_provisioning.py -k 'test_provision_with_additional_volume or test_provision_with_boot_volume' }}
=> [1LP][RFR] Fixed failing tests due to string match issue

cfme/services/myservice/ssui.py, cfme/tests/ssui/test_ssui_myservice.py, widgetastic_manageiq/__init__.py
{{pytest: -v --long-running --use-provider openstack cfme/tests/ssui/test_ssui_myservice.py -k test_myservice_crud }}
=> [1LP][RFR]Enabled test for 5.9 and added support for cloud providers

cfme/tests/intelligence/test_dashboard.py
This module was missing the BZ import, breaking test collection.
=> [RFR] Update test_Dashboard, import BZ blocker class

cfme/common/vm.py
Updated input for clear calandar, as with empty string it was not cleared correctly
{{pytest: -vvv -k test_resume_retired_instance --long-running}}
=> [1LP][RFR] Fix test_resume_retired_instance 

cfme/infrastructure/datastore.py, cfme/tests/infrastructure/test_delete_infra_object.py
- added vm and host count property in Model page
- removed some `version.pick`
- It will fix test_delete_datastore_appear_after_refresh
{{py.test: -vvv cfme/tests/infrastructure/test_delete_infra_object.py -k 'test_delete_datastore_appear_after_refresh' --use-provider vsphere55}}
=> [1LP][RFR] fix: test_delete_datastore_appear_after_refresh

cfme/cloud/security_groups.py
One more case with MoveTargetOutOfBoundsException: Message. This time I've tried to close flash message, as some action before open configuration in toolbar(BZ 1520669).
{{pytest: cfme/tests/cloud/test_security_groups.py -vvv}}
=> [1LP][RFR] Workaround for test_security_group create

cfme/cloud/instance/__init__.py, cfme/infrastructure/virtual_machines.py
Fix issue in Vm/Instance tree navigation
Navigation to a VM/Instance was done from the provider view. Hence, it was not possible to navigate to a deleted VM/Instance because it was in the archived/orphaned folder. Changing the navigation to All fixed it. PR #6364 and #6149 are depending on this one. 
{{pytest: -v -k  test_cloud_instance_event --use-template-cache --use-provider=azure }}
=> [1LP][RFR] Fix bug in navigation

cfme/tests/integration/test_cfme_auth.py
need new server deployed
{{ pytest: cfme/tests/integration/test_cfme_auth.py -k ext_openldap }}
=> [1LP][RFR] Block test_cfme_auth ext_openldap on GH issue

cfme/tests/infrastructure/test_timelines.py
removed useless statement after the yield
Test is working but the VM is already deleted after the yield in new_vm, so there is no point of trying to keep this statement after the yield. Tests are finishing in failed state because of trying to navigate to a deleted VM.
{{pytest: -v -k test_infra_diagnostic_timeline_events --use-template-cache --use-provider=vsphere6-nested }}
=> [1LP][RFR] fix test test_infra_diagnostic_timeline_events

cfme/common/provider_views.py, cfme/infrastructure/provider/__init__.py, cfme/tests/infrastructure/test_infra_tag_filters_combination.py, cfme/tests/infrastructure/test_vm_clone.py
Updated the way we get vms, and templates, for a test.
{{pytest: -vvv -k 'test_tagvis_tag_datacenter_combination or test_vm_clone' --long-running --use-provider complete}}
=> [1LP][RFR] test_tagvis_combination, test_clone fixes

cfme/tests/services/test_pxe_service_catalogs.py
PXE tests are failing on jenkins because create option is not provided for customization template .
Create=True added for customization template .
If template does not exist , create template
=> [1LP][RFR] Create template if not exist 

cfme/tests/networks/test_sdn_balancers.py
Added a check for available load balancers for provider, it not found will skip the test
{{pytest: cfme/tests/networks/test_sdn_balancers.py -vvv --use-provider complete}}
=> [1LP][RFR] Check provider for available load balancers

cfme/common/vm.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py
__Fixing__ item_select in open_console which was causing timeout error as given in RHCFQE-6568. It was occurring because it was taking False as the default value and it would wait for 10 sec to find an alert and timeout, it should rather take none, but during WT conversion someone changed that logic as it seems based on git history. 
Removed the cancel parameter from the function since it was not being used at all and I do not see a use case for it at this moment. 
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider vsphere6-nested }}
=> [1LP][RFR] Resolving Timeout Error caused by handle_alert

fixtures/screenshots.py
__Fixing__ Screenshot Namespace Collision in screenshot function.  take_screenshot() was calling itself recursively, causing failures.
http://10.16.45.124/o7ZR4HEz/artifacts/cfme/tests/cloud_infra_common/test_html5_vm_console.py/test_html5_vm_console[vsphere6-nested]/filedump-traceback.log
Shriver:
{{ pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py -k test_html5_vm_console --use-provider vsphere6-nested --long-running -vv }}
=> [1LP][RFR] Fixing namespace collision for take screenshot

cfme/scripting/appliance.py
__Adding__ a script to get any new appliance configured for WebMKS testing quickly instead of configuring it manually every time I need to validate a BZ. It will help me save time to Download and extract the WebMKS SDK manually.
=> [1LP][RFR][NOTEST]Adding a small script to get WebMKS SDK quickly on any new appliance aiding BZ validations for WebMKS

cfme/tests/containers/test_manageiq_ansible_custom_attributes.py, cfme/tests/containers/test_manageiq_ansible_providers.py, cfme/tests/containers/test_manageiq_ansible_tags.py, cfme/tests/containers/test_manageiq_ansible_users.py
https://github.com/ManageIQ/integration_tests/issues/6484
{{ pytest: cfme/tests/containers/test_manageiq_ansible_custom_attributes.py cfme/tests/containers/test_manageiq_ansible_providers.py cfme/tests/containers/test_manageiq_ansible_tags.py cfme/tests/containers/test_manageiq_ansible_users.py --use-provider cm-env2  }}
=> [1LP][RFR] Blocking cfme.tests.containers.test_manageiq_ansible* 

cfme/tests/storage/test_volume_backup.py
- test `test_storage_volume_backup_delete` was running locally but failing always on Jenkin Run. may cause is collective curd in simultaneous Jenkin Runs.
{{py.test: cfme/tests/storage/test_volume_backup.py -k 'test_storage_volume_backup_delete' -v}}
=> [1LP][RFR] fix: BackupNotFoundError: No Volume Backups for Deletion

cfme/tests/ansible/test_embedded_ansible_services.py
{{pytest: -v -k test_service_ansible_playbook_order_credentials --long-running}}
=> [1LP][RFR] Fixed test_service_ansible_playbook_order_credentials

cfme/utils/appliance/implementations/ui.py
Issue: Imagine we had landed on Cloud Providers page, and then via REST
we add a cloud provider. If we now try to navigate to the Details
page of that cloud provider it will fail because the am_i_here is
True, but the provider is not visible on the page as it was done
via REST.
* Added a try/except around step to retry the step operation after a
refresh. This _could_ make some things fail, but then they were going
to fail anyway.
=> [1LP][RFR] Fixed step issue

cfme/configure/configuration/server_settings.py, cfme/exceptions.py, cfme/fixtures/configure_auth_mode.py, cfme/utils/appliance/__init__.py, cfme/utils/ext_auth.py
Update ServerAuthentication.auth_mode, turn into a property
Updates throughout Appliance, ext_auth util module, and
configure_auth_mode fixture
Refactoring for test stabilization, plans are to add more test cases, and modify parametrization of existing cases.
I'm filtering on just openldap tests here, ext_openldap is GH skipped, and miq_openldap should pass.  miq_ipa fails at the moment, which I'll address in a 2nd PR with further refactoring. Wanted to keep this PR scope gradual.
{{ pytest: cfme/tests/integration/test_cfme_auth.py -v -k openldap }}
=> [1LP][RFR] Update miq-openldap auth tests

cfme/tests/configure/test_access_control.py
Fix failure in the access control test_permissions_role_crud test
{{pytest: -v cfme/tests/configure/test_access_control.py -k 'test_permissions_role_crud'}}
=> [1LP][RFR]Fix for access_control test_permissions_role_crud

cfme/cloud/provider/azure.py, cfme/cloud/provider/ec2.py, cfme/cloud/provider/gce.py, cfme/cloud/provider/openstack.py, cfme/fixtures/service_fixtures.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/scvmm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/rest/gen_data.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_pxe_service_catalogs.py, cfme/tests/services/test_service_catalogs.py
* This value used to be obtained via the yaml files as part of the
provisioning data.
* As the catalog_name is provider specific it should be stored in the
provider module.
* This includes a fix to make 5.9 work properly as the string changed
These values can now be removed from the cfme_data.yaml
=> [1LP][RFR] Fixed catalog_name selection

cfme/tests/configure/test_access_control.py
Purpose
Refactored and fixed test_permissions_vm_provisioning.
{{pytest: -v cfme/tests/configure/test_access_control.py -k test_permissions_vm_provisioning}}
=> [1LP][RFR] Fixed test_permissions_vm_provisioning

cfme/services/requests.py, cfme/services/service_catalogs/ui.py, cfme/tests/services/test_provision_stack.py, data/orchestration/azure_vm_template.json
Purpose
"azure-single-vm-from-user-image" service dialog has been removed in CFME 5.9. This PR requires updated cfme_data.yaml. Also, it can potentially break other services test, but without refactoring `OrderForm` fixing test_provision_stack.py cannot proceed.
{{pytest: -v cfme/tests/services/test_provision_stack.py --use-provider azure}}
=> [RFR][1LP] Fixed tests for Azure provider in test_provision_stack.py

cfme/containers/provider/__init__.py
{{ pytest: cfme/tests/containers/test_properties.py --use-provider cm-env2 }}
- Fix get_random_instances by limit the count with the count of instances
- Added description
=> [1LP][RFR] Fix get_random_instances by limit the count with the count of instances

cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/tests/containers/test_ssl_providers.py
{{ pytest: cfme/tests/containers/test_ssl_providers.py::test_add_provider_ssl --use-provider ocp-v1 }}
In the following PR I will create a new fixture for sync SSL certification between OCP and CFME
**3 steps required for sync the certificates:**
1. Get the certificate from OCP
1. Deploy the certificate to CFME
1. Run "update-ca-trust" to actually install the new certificate
FIXES #6409
=> [1LP][RFR] Add a fixture for sync SSL certificate between CFME and OCP

requirements/frozen.txt
* adds support for CMP Polarion project
* removes support for legacy CI message bus (will stop working from February)
* adds new way for verifying that testcases were updated in Polarion
Needs to be merged together with MR https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/431
=> [RFR] Bump dump2polarion version

cfme/tests/services/test_cloud_service_catalogs.py
`security_group` is not found in GCE provider, adding conditions for handling `environment` dict 
{{ pytest: -vvvv cfme/tests/services/test_cloud_service_catalogs.py --use-provider complete }}
=> [1LP][RFR] Fix for GCE provider

requirements/frozen.txt
This gets us around RunTimeError's seen while pytest imports plugins. I ran into this after setting up a fresh test environment on fedora27
```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
```
```
ImportError: Error importing plugin "fixtures.version_info": numpy.core.multiarray failed to import
```
=> [RFR] Require numpy 1.14.0

cfme/tests/configure/test_access_control.py, cfme/tests/services/test_catalog.py
Purpose
__Fixing__ _cfme/tests/configure/test_access_control.py::test_permissions_ which failed with error:
```AttributeError: 'module' object has no attribute 'buttons'```
__Fixing__ _cfme/tests/services/test_catalog.py::test_permissions_catalog_add_ which failed with error:
```TypeError: create() takes exactly 1 argument (2 given)```
__Now__ _test_permissions_catalog_add_ __fails__ because user without proper permissions can add new Service Catalog [(link to BZ)](https://bugzilla.redhat.com/show_bug.cgi?id=1460891)
{{pytest: -v cfme/tests/services/test_catalog.py::test_permissions_catalog_add cfme/tests/configure/test_access_control.py::test_permissions}}
=> [1LP][RFR] Fixed test_permissions_catalog_add

cfme/services/service_catalogs/ui.py, cfme/tests/ansible/test_embedded_ansible_services.py
__Fixing__ test_service_ansible_playbook_order_credentials as it was failing due to incorrect is_displayed function, and view couldn't find args. 
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py  --long-running -s -k 'test_service_ansible_playbook_order_credentials'}}
=> [1LP][RFR] Fixing ansible service order credentials test to find correct view to look up creds dropdown

cfme/configure/configuration/diagnostics_settings.py
Updated to use checkboxes on 5.9 instead of clicking on row. 
{{pytest: -v cfme/tests/configure/test_workers.py -k test_restart_workers}}
=> [1LP][RFR] Fixed test_restart_workers

cfme/tests/cloud/test_provisioning.py
Fixing test_provision with_additional_volume and boot_volume. Issue releted to provisioning error where fixed using Choose Automate enviroment for Openstack provider. 
{{pytest: -v cfme/tests/cloud/test_provisioning.py -k "test_provision_with_additional_volume or test_provision_with_boot_volume" --use-provider openstack --long-running}}
=> [1LP][RFR] Fix test_provision with_additional_volume and boot_volume

requirements/frozen_docs.txt, requirements/template_docs.txt
An extension of PR #6528 -- updating version in the other needed places.
=> [RFR] Bump numpy to 1.14 in template requirements as well

cfme/tests/containers/test_reports.py
{{ pytest: cfme/tests/containers/test_reports.py --use-provider cm-env2 }}
Skip test_report_projects_by_cpu_usage and test_report_projects_by_memory_usage due to a BZ#1539378
=> [1LP][RFR] Skippers for BZ#1539378

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
This can be considered as fix for all of the existing snapshot tests.
The problem in the Automation Issues spreadsheet is that there are multiple failures like this:
"TimedOutError: Could not do function <lambda>()"
This makes it harder to detect why exactly the failure occurred. It's caused by missing attribute 'message' in function wait_for. This PR adds those messages to wait_for functions with regards to snapshot testing.
There are other snapshot issues currently being fixed, the PRT might not look good for this PR. Reviewers, please keep in mind that this PR only adds text messages to wait_for, nothing else changed.
{{ pytest: -v --long-running --use-provider vsphere55 cfme/tests/infrastructure/test_snapshot.py }}
=> [1LP][RFR] Add messages to wait_for for snapshot tests

markers/polarion.py
this is facilitated by always passing on the ids using the main process and enriching the junitxml report directly
=> [1LP][RFR] support polarion ids in junitxml on the parallelizer

cfme/utils/ssh.py, scripts/clean_appliance.py
__Fixing__ clean_appliance.py. `evm:db:reset` is not executed if `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` is not defined in environemt. It is just a quick fix and probably not the best. I suppose the correct approach would be to fine-tune this [method](https://github.com/ManageIQ/integration_tests/blob/c0962522aafed3b75180ebfe26c42580bcc71503/cfme/utils/appliance/__init__.py#L2000), but I unfortunately don't have capacity for that at the moment.
=> [1LP][RFR] Fixing clean_appliance helper script

cfme/fixtures/cli.py, cfme/fixtures/configure_auth_mode.py, cfme/tests/integration/test_aws_iam_auth_and_roles.py, cfme/tests/integration/test_cfme_auth.py
Fix collection for auth tests, a change to cfme_data.yaml (moving things to auth_data.yaml) broke collection.
I have #6538 open to actually do some auth test refactoring, this is fix for collection.
Only looking for collect-only to be fixed - there likely will be auth test failures, see #6538 for any of those fixes.
=> [RFR] Fix collection on auth tests, auth_data.yaml

cfme/cloud/stack.py, cfme/tests/cloud/test_stack.py
Updated CandidateNotFound message type, and stack fixture: removed stack deletion, as we use existing ones, and also add a check to look for available stack not just the first one from yamls.
{{pytest: cfme/tests/cloud/test_stack.py}}
=> [1LP][RFR]Fix stack exeption message and fixture update

cfme/configure/access_control/__init__.py, cfme/tests/infrastructure/test_tenant_quota.py
This replaces #6436 based on advice from @quarckster and @mfalesni 
Two tests failed on downstream-59z because of catalog item type issue.
{{pytest: cfme/tests/infrastructure/test_tenant_quota.py -vv --use-provider rhv41}}
=> [1LP][RFR] Fixing test_tenant_quota

cfme/common/provider.py
Wait until provider is deleted.
I don't think the old code worked as expected. It was checking intersection of set of providers existing before delete with set of currently existing providers. One problem is that we are not deleting all providers (but only providers of certain type), so we don't need the intersection to be empty. The other problem is that it was checking original list of instances of the Entity class with new list of [new instances](https://github.com/mkoura/manageiq-api-client-python/blob/master/src/manageiq_client/api.py#L343), i.e. the intersection was always empty.
=> [RFR] Fix waiting for provider delete

cfme/rest/gen_data.py, cfme/tests/infrastructure/test_pxe_provisioning.py
Added partial_match for network select to tests, as value was not found in dropdown
{{pytest: cfme/tests/services/test_rest_services.py cfme/tests/infrastructure/test_pxe_provisioning.py --use-provider rhevm --long-running}}
=> [1LP][RFR]Add partial_match for network select

cfme/configure/configuration/diagnostics_settings.py, cfme/tests/configure/test_log_depot_operation.py
__Fixing__ AssertionError:
```
assert  message: Log collection for CFME MiqServer EVM [1] has been initiated.
Available messages: [u'Log collection for CFME MiqServer EVM [2] has been initiated']
```
{{pytest: cfme/tests/configure/test_log_depot_operation.py::test_collect_multiple_servers}}
=> [1LP][RFR] Fixed test_collect_multiple_servers

cfme/tests/ssui/test_ssui_myservice.py
Purpose 
Add pytest.skip for vsphere65, VNC consoles are unsupported on VMware ESXi 6.5 and later, which causes error _"DropdownItemDisabled: Item "VM Console" of dropdown "Access" is disabled"_
{{pytest: -v cfme/tests/ssui/test_ssui_myservice.py -k test_vm_console[vsphere65-nested-order_catalog_item_in_ops_ui0-ViaSSUI]}}
=> [RFR][1LP]Add pytest.skip in configure_vmware_console for vsphere65

cfme/tests/services/test_service_catalogs.py
__Wrapping__ test_edit_catalog_after_deleting_provider with this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1540592). The bug makes it impossible to save changes made to already created Catalog Item.
{{pytest: cfme/tests/services/test_service_catalogs.py::test_edit_catalog_after_deleting_provider -vv --use-provider rhv41}}
=> [1LP][RFR] BZ wrapper for test_edit_catalog_after_deleting_provider

cfme/tests/services/test_operations.py
This bug breaks this test: https://bugzilla.redhat.com/show_bug.cgi?id=1540731
However, I don't think the fact that this test navigates to the base_url really affects the 'intent of the test', so I'm changing it to simply nav to another page. I think we'd be better to fix this for now, and add an additional test to properly address the above BZ and specifically test that kind of login/auth flow.
=> [1LP][RFR] Fix test_services_request_direct_url due to BZ1540731

requirements/frozen.txt
Moving `stats` to WrapanapiAPIBase fixes container tests and is needed for the new SDN work.
=> Wrapanapi 2.5.2

cfme/tests/intelligence/reports/test_menus.py
{{ pytest: cfme/tests/intelligence/reports/test_menus.py -v}}
=> [1LP][RFR] Adding BZ blockers to skip reports shuffle top/first level tests

cfme/tests/cloud_infra_common/test_retirement.py
__Fixing__ test_resume_retired_instance to wait a bit longer for SCVMM to retire, because it takes more than 10 min.
without a line to specify what provider to use, it will collect against 'default' providers, which doesn't include scvmm.
Leaving this here for you to see and know, but your PR's small timeout change doesn't warrant needing to verify all the results. 
{{ pytest: cfme/tests/cloud_infra_common/test_retirement.py -k test_retirement_now --use-provider scvmm --long-running }}
=> [1LP][RFR] Increased timeout for wait scvmm to retire

cfme/configure/access_control/__init__.py, cfme/configure/settings.py, cfme/control/explorer/alert_profiles.py, cfme/tests/infrastructure/test_provisioning_dialog.py
Tied to wt.patternfly [#43](https://github.com/RedHatQE/widgetastic.patternfly/pull/43) updates to the CheckableBootstrapTreeview.
I'm mainly looking at the failure for places where the form fill of the `CheckableBootstrapTreeview` failed. I will not be addressing all test failures here unless related to my changes.
Widgetastic has been updated past 0.0.28 outside of this PR, and these calls are now broken in the framework until this is merged. 
{{ pytest: cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/configure/test_default_filters.py cfme/tests/control/test_alerts.py cfme/tests/control/test_basic.py --long-running -v }}
=> [1LP][RFR] Update wt.patternfly.CheckableBootstrapTreeview fill() calls 

cfme/common/__init__.py, cfme/containers/provider/__init__.py, cfme/tests/containers/test_provider_openscap_policy_attached.py
This PR comes to check Container Image compliance check in case that the policy profile is attach from provider view (and not from Image).
{{pytest: cfme/tests/containers/test_provider_openscap_policy_attached.py -v --use-provider cm-env2 }}
=> [1LP][RFR] Container image compliance check with attach policy from provider view

cfme/containers/provider/__init__.py
This is a fix to get cfme.tests.containers.test_reload_button_provider.py working correctly. refresh_provider_relationships_ui selects the refresh based on refresh_text.
This also depends on wrapanapi PR: https://github.com/ManageIQ/wrapanapi/pull/211
Manual test:
with refresh_text
```
In [5]: juwatts = providers.get_crud('cm-juwatts')
In [6]: juwatts
Out[6]: <cfme.containers.provider.openshift.OpenshiftProvider name='CM JUWATTS', key='cm-juwatts', zone='default', metrics_type='Hawkular', alerts_type='Disabled'>
In [7]: juwatts.refresh_text
Out[7]: 'Refresh items and relationships'
In [8]: view = navigate_to(juwatts, 'Details')
In [9]: juwatts.refresh_provider_relationships(method='ui')
[WARNING] /home/juwatts/repos/cfme_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver. …
```
=> [RFR] Missing refresh text from container providers

cfme/tests/services/test_cloud_service_catalogs.py
Purpose
Added partial match for Azure _cloud_subnet_ in _test_cloud_catalog_item_.
{{pytest: -v cfme/tests/services/test_cloud_service_catalogs.py -k test_cloud_catalog_item[azure] --use-provider azure}}
=> [1LP][RFR] Added partial match for Azure cloud_subnet

cfme/tests/infrastructure/test_provisioning_rest.py
Adding BZ wrapper to skip tests in test_provisioning_rest.py because of BZ 1541036
{{ pytest: -v --long-running --use-provider rhv41  cfme/tests/infrastructure/test_provisioning_rest.py }}
=> [1LP][RFR] Adding BZ wrapper to skip VM provision testcases using rest api.

cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py, cfme/utils/rest.py
Service name can no longer be used to uniquely identify service when multiple services are using the same dialog (all services have the same name). Using service template id instead.
Also reworked a way how to get info about what VMs are associated with service.
{{pytest: -v --long-running --use-provider vsphere65-nested -k 'not TestServiceOrderCart' cfme/tests/services/test_rest_services.py}}
**PRT**
The only failed test is not related to changes in this PR (the bug no longer blocks the test but was not fixed in the tested version).
=> [1LP][RFR] Unique service identification fix

cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py -k test_infrastructure_add_provider_trailing_whitespaces}}
Based on RHCF3-11219
=> [1LP][RFR] New infra provider test

cfme/fixtures/tag.py
Purpose
In case if Category name starts from digit it will be on the top of the list and selected by default as the first one. Because of [BZ#1517285](https://bugzilla.redhat.com/show_bug.cgi?id=1517285), it will have other Tags than preconfigured for this Category.
{{pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py -k test_tag_infra_objects}}
=> [1LP][RFR] Add BZ blocker for category in fixtures/tag.py

cfme/tests/infrastructure/test_infra_tag_filters_combination.py
Purpose
Fixed test_tagvis_tag_datacenter_combination due to checknode, unchecknode issue.
{{pytest: -v cfme/tests/infrastructure/test_infra_tag_filters_combination.py -k test_tagvis_tag_datacenter_combination[clusters-visible]}}
=> [1LP][RFR]Fix test_tagvis_tag_datacenter_combination

cfme/cloud/provider/vcloud.py, conf/cfme_data.yaml.template, conf/credentials.yaml.template, setup.py
With this commit we introduce VMwareCloudProvider class and implement it enough for following (exisiting) tests to pass:
- cfme/tests/cloud/test_providers.py::test_provider_add_with_bad_credentials
- cfme/tests/cloud/test_providers.py::test_provider_crud
Depends on: https://github.com/ManageIQ/wrapanapi/pull/209
=> [1LP][RFR] First integration test for VMware Cloud provider

cfme/utils/trackerbot.py
Fix for trackerbot.trackerbot_add_provider_template which tried to load ~6000 templates from trackerbot in order to check whether passed template name already exists.
=> [1LP][RFR] reduced number of retrieved existing templates to certain provider templates

cfme/tests/infrastructure/test_host.py, cfme/tests/infrastructure/test_individual_host_creds.py
__Fixing__ the way how bad password is provided in test_multiple_host_bad_creds. If we **update** `credentials[host['credentials']]` as we used to do, this variable will retain the bad password as long `provider` exists. This will cause `cfme/tests/infrastructure/test_individual_host_creds.py::test_host_good_creds` to fail if it is exexuted after this test case.
{{pytest: cfme/tests/infrastructure/test_host.py cfme/tests/infrastructure/test_individual_host_creds.py -k cred -vv --use-provider rhv41}}
=> [1LP][RFR] Do not update creds in test_multiple_host_bad_creds

cfme/tests/infrastructure/test_config_management.py
Purpose
Added **https** to _**invalid_url**_ to fix   _AssertionError: URL has to be HTTPS_.
{{pytest: -v cfme/tests/infrastructure/test_config_management.py -k test_config_manager_add}}
=> [1LP][RFR] Fixed test_config_manager_add_invalid_url

cfme/common/provider.py, fixtures/provider.py
An idea how to speed provider deletion in some situations.
**PRT**
The two failures on 5.9 are ``MoveTargetOutOfBoundsException: Message: Despite all the workarounds, scrolling to `<selenium.webdriver.remote.webelement.WebElement ...>` was unsuccessful`` in ``provider.create()``. It's not related to changes in this PR.
=> [1LP][RFR] Delete providers using REST

cfme/infrastructure/provider/rhevm.py, cfme/tests/infrastructure/test_providers.py
__Activating__ test_provider_add_with_bad_credentials for RHV and __fixing__ `RHEVMProvider.bad_credentials_error_msg` in the process.
{{pytest: cfme/tests/infrastructure/test_providers.py::test_provider_add_with_bad_credentials --use-provider rhv41 -vv}}
=> [1LP][RFR] Activating test_provider_add_with_bad_credentials for RHV

cfme/tests/services/test_rest_services.py
Purpose 
Changed type of OrchestrationTemplate to invalid value as _OrchestrationTemplateCfn_ is accepted by CFME due to changes [PR#284-Temporarily allow to create deprecated orchestration template types](https://github.com/ManageIQ/manageiq-api/pull/284).
{{pytest: -v cfme/tests/services/test_rest_services.py -k test_invalid_template_type}}
=> [1LP][RFR]Fixed test_invalid_template_type

cfme/tests/services/test_provision_stack.py
__Moving__  teardown registration up. if test fails on order/verification/navigation - we won't execute teardown
=> [1LP][RFR] Fix for stack teardown registration

cfme/ansible/repositories.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/ansible/test_embedded_ansible_automate.py, cfme/tests/ansible/test_embedded_ansible_basic.py, cfme/tests/ansible/test_embedded_ansible_services.py, widgetastic_manageiq/__init__.py
Intent
We should replace `get_detail()` method in our objects by a parametrized summary table in respectful detail views.
{{pytest: -v -k "test_control_action_run_ansible_playbook_in_requests or test_embedded_ansible_repository_crud or test_automate_ansible_playbook_method_type_crud or test_service_ansible_playbook_crud" --long-running}}
=> [1LP][RFR] Get rid off get_detail() in ansible repositories

cfme/tests/control/test_alerts.py
RHV provider should be skipped for this test.
{{pytest: -v -k test_alert_vm_turned_on_more_than_twice_in_past_15_minutes --long-running --use-provider complete}}
=> [1LP][RFR] Added a bz blocker for test_alert_vm_turned_on_more_than_twice_in_past_15_minutes

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
* fixing uncollecting so the tests run on 5.8 as expected
* changing fixtures so vms and instances are created only when needed while keeping the tests general
{{pytest: -v --long-running cfme/tests/cloud_infra_common/test_custom_attributes_rest.py}}
**PRT**
The only failure on 5.9 is ``E URLError: <urlopen error [Errno 111] Connection refused>``  in ``vm_obj.create_on_provider``, this is probably infrastructure issue.
=> [1LP][RFR] Fix custom attributes tests on 5.8

cfme/common/provider.py, cfme/scripting/sprout.py, cfme/test_framework/appliance.py, cfme/test_framework/sprout/plugin.py, cfme/tests/services/test_operations.py, cfme/utils/appliance/__init__.py, cfme/utils/browser.py, cfme/utils/net.py, cfme/utils/ssh.py, cfme/utils/tests/test_ipappliance.py, docs/getting_started.rst, docs/guides/browser_configuration.rst, docs/guides/container.rst, docs/guides/tipsntricks.rst, docs/guides/vnc_selenium.rst, fixtures/parallelizer/__init__.py, fixtures/parallelizer/remote.py, fixtures/pytest_store.py, notebooks/Browser Session.ipynb, scripts/dockerbot/pytestbase/setup.sh, scripts/wait_for_appliance_ui.py
Defining an appliance in env.yaml like this:
```yaml
base_url: https://1.2.3.4
```
...or like this...
```yaml
appliances:
- base_url: https://1.2.3.4
```
is deprecated.
Our code was written to support both the "old way" (base_url) or "new way" (list of appliances). We've decided to clean up support for base_url entirely. Corresponding docs/scripts/plugins that reference or create env YAML files are also updated. Moving forward, env.yaml *must* be set up in the "new way", e.g.:
```yaml
appliances:
- hostname: 1.2.3.4
- hostname: 3.4.5.6
```
...or optionally other kwargs used when instantiating IPAppliance could be defined...
```yaml
appliances:
- hostname: 1.2.3.4
ui_port: 80
ui_protocol: http
```
=> [RFR][1LP] Remove deprecated use of base_url in env appliance configuration

cfme/roles.py, cfme/tests/integration/test_aws_iam_auth_and_roles.py
Updates to go with BZ resolutions and re-opening. Narrowing the BZ blocker scope to increase test coverage on non-impacted roles/groups.
One BZ for 'requests' showing up throughout the vertical navigation tree where there is no matching access control tree entry was marked as an RFE.  As a result I'm now checking for 'Requests' in the diff, and skipping verification.
* 21004: 58z failures: 2 from BZ, 1 from RBAC change for super_admin role.  2nd commit should resolve: https://github.com/ManageIQ/integration_tests/pull/6626/commits/bddc751dc4104035a4353a1ba568a4f43f8e09a4
{{ pytest: cfme/tests/integration/test_aws_iam_auth_and_roles.py  --long-running -v }}
=> [1LP][WIPTEST] Update BZ blockers in aws RBAC/login tests

cfme/utils/auth/__init__.py, setup.py
Auth provider classes for the MIQ and external auth providers
registered with entrypoints for dynamic type fetching
get_auth_crud method for easy from_config() access
To support auth test refactoring in #6538 
PRT irrelevant
=> [1LP][RFR] Add auth provider classes

cfme/base/ui.py
Updated login default method to use Enter button instead of running js, as as js login was not successful for FF versions 52+ and selenium3
=> [1LP][RFR] Change login method for FF52+

cfme/scripting/link_config.py
Add a --force option to link_config.py to overwrite existing symlinks/files -- this makes it easier to switch back and forth between different cfme-qe-yaml dirs.
The logic is now:
* If force, rename current target "file.yaml" to "file.yaml_bak" and create new symlink
* If not force, do the same checks we did before:
-- If target "file.yaml" is a symlink:
---- and it already points to same src, we're good, do nothing.
---- and it points to somewhere else, throw error
-- If target is an existing file, throw error
-- If above checks pass, create the new symlink
=> [1LP][RFR] Add a --force option to link_config.py to overwrite existing symlinks/files

cfme/services/catalogs/catalog_item.py
{{pytest: -v  --long-running cfme/tests/services/test_config_provider_servicecatalogs.py}}
while creating catalog item , the Ansible tower text is different in 5.9 .
Did a version pick.
=> [1LP][RFR] Ansible tower type is different in 5.9

cfme/tests/openstack/infrastructure/test_provider.py
Replaced access to provider api port through details view instead of provider.summary.properties.api_port.value 
{{ pytest: cfme/tests/openstack/infrastructure/test_provider.py::test_api_port }}
=> [1LP][RFR] fix provider api port test

cfme/tests/infrastructure/test_vm_reconfigure.py
__Blocking__ test_vm_reconfig_add_remove_hw_cold. I changed the test case to *decrease* memory instead of increase few weeks ago. I did so because I thought that RHV does not support increasing VM's memory over the max size. Well, it turns out that it does and this is indeed a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1534520). Therefore reverting the test case to its original state and wrapping it with BZ.
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_hw_cold -vv --use-provider rhv41 --long-running}}
=> [1LP][RFR] Blocking test_vm_reconfig_add_remove_hw_cold for RHV

cfme/base/credential.py, cfme/cloud/provider/ec2.py, cfme/common/provider_views.py, cfme/tests/cloud/test_providers.py
- Added Cloud provider discovery test for `Azure` and `AWS`; supported for `version  < 5.9`
- Small change in `Credential` Class for Azure support
- Fix in `discover_dis()`; changed key to `confirm_password` as per `CloudProvidersDiscoverView()`
{{py.test: -v cfme/tests/cloud/test_providers.py --use-provider complete}}
=> [1LP][RFR] Cloud provider discovery test

cfme/tests/networks/test_network_providers.py
Purpose
Added BZ in test_network_providers.py due to [BZ#1518301:Unable to add a Network provider](https://bugzilla.redhat.com/show_bug.cgi?id=1518301)
{{pytest: -v cfme/tests/networks/test_network_providers.py}}
=> [1LP][RFR] Added BZ in test_network_providers.py

widgetastic_manageiq/__init__.py
Removed integer casting from get element id because it supports only region 0
{{ pytest: cfme/tests/openstack/infrastructure/test_hosts.py::test_host_memory }}
=> [1LP][RFR] fix get element id to support any region

cfme/cloud/instance/__init__.py, cfme/cloud/instance/image.py, cfme/common/vm.py, cfme/common/vm_views.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud/test_instance_power_control.py, cfme/tests/cloud/test_provisioning.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis.py, cfme/tests/control/__init__.py, cfme/tests/control/test_alerts.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_vm_migrate.py, cfme/tests/infrastructure/test_vm_power_control.py, cfme/tests/openstack/cloud/test_instances.py
Intent
=========
Continuation of replacing `get_detail()` method by calling `ParametrizedSummaryTable` in respectful views.
{{pytest: -v -k "test_soft_reboot or test_gce_preemptible_provision or test_ssa_template or test_change_cpu_ram or test_vm_migrate or test_suspend or test_create_instance"  --long-running}}
=> [1LP][RFR] Replace get_details() for VMs

fixtures/ui_coverage.py, scripts/data/coverage/coverage_merger.rb
- Update comments in script to properly explain format of
.resultset.json files and the merged .resultset.json file.
- The location of the coverage data is no longer hard coded, and now
defaults to ./coverage.  Also added a --coverageRoot option.
- Merged file output is now pretty printed.  I found this useful when
I was trying to understand the file.  Someone else may also at
some point.
Additionally some comment changes were made to fixtures/ui_coverage.py.
It has an explanation of almost the whole end to end process for
gathering and reporting coverage statistics and I wanted to make that
accurate.
One last note, the --coverageRoot option is going to be used by the process that will upload the coverage data to SonarQube (i.e. scripts/coverage_reports_jenkins.py).   That will be changed …
=> [1LP][RFR] Minor changes to coverage_merger.rb

cfme/tests/control/test_actions.py
Policy and profile names should differ from another control policy in the module.
{{pytest: -v -k "test_action_prevent_host_ssa or test_action_prevent_ssa" --long-running}}
=> [1LP][RFR] Fixed test_action_prevent_host_ssa

cfme/tests/control/__init__.py, cfme/tests/control/test_actions.py, cfme/tests/control/test_alerts.py, cfme/tests/control/test_rest_control.py
Purpose
In order to make `TimedOutError` more readable and clear, we should provider descriptions for `wait_for` functions.
=> [1LP][RFR][NOTEST] Added descriptions for wait_for functions

cfme/tests/infrastructure/test_config_management_rest.py
{{pytest: -v -k test_query_authentications_attributes cfme/tests/infrastructure/test_config_management_rest.py}}
=> [1LP][RFR] Add test for querying authentications attributes

widgetastic_manageiq/__init__.py
JS API should always provide Name for entities but Floating IP entities don't have it for some reason.
This is temporary patch. I'll contact devs in the meantime.
It should be tested in #6675
=> [1LP][RFR] fixed issue with floating ip entities 

widgetastic_manageiq/__init__.py
href was updated in 58 non interactive entities and has params like ?link=true now.
This PR intends to make NoneInteractiveEntitiesView retrieve ids correctly.
It is required for #6365
=> [1LP][RFR] fix for non interactive entities

scripts/azure_cleanup.py
cleanup_azure was failing in Jenkins and we had no idea why, exceptions should be logged to help with that.
=> [1LP][RFR] Log exceptions to stdout

cfme/tests/openstack/infrastructure/test_hosts.py
Fixed 2 tests:
test_host_configuration: app.browser.refresh no more supported
test_host_devices: Not working without split()[0])
{{pytest: --use-provider=rhos_uc cfme/tests/openstack/infrastructure/test_hosts.py -k 'test_host_configuration or test_host_devices' }}
=> [RFR] fix failed tests on infrastructure test_hosts.py

widgetastic_manageiq/__init__.py
Quadicons have been broken recently by my changes. 
This change should fix the issue. 
To be honest, the best way would be to get rid of ParametrizedLocator in QuadIcon classes since xpath gets more and more sophisticated. However, I believe Quadicons 5.8 will go away soon along with 5.8.
So, I left ParametrizedLocator with that compex xpath
In addition, I bumped into issue with click in TileIcon and fixed it toghether with the rest of stuff.
I tested it locally.
=> [1LP][RFR] fix for quadicons in 5.8

cfme/intelligence/reports/reports.py, cfme/tests/intelligence/reports/test_canned_corresponds.py
Purpose 
Various fixes for test_operations_vm_on and test_datastores_summary:
- Updated to use NonJSPaginationPane as PaginationPane() is not working on Report Details page
- Added finalizer to delete created report.
{{pytest: -vvv cfme/tests/intelligence/reports/test_canned_corresponds.py -k "test_datastores_summary or test_operations_vm_on"}}
=> [1LP][RFR] Fixing test_operations_vm_on and test_datastores_summary

cfme/utils/appliance/__init__.py, cfme/utils/testgen.py
Update appliance.configure_openldap
To support more consistent auth automation and setup for RBAC tests
update auth_data/cfme_data queries in utils/testgen
To support auth test refactoring in #6538, will be rebasing and following up anything from here in that PR.
PRT failures are pseudo-random smoke test failures from timeouts, not related
=> [1LP][RFR] Update appliance openldap config method

cfme/tests/infrastructure/test_iso_provisioning.py, cfme/tests/services/test_iso_service_catalogs.py
Wrapping test_rhev_iso_service_catalog and test_iso_provision_from template tests, because our environment isn't prepared for these tests yet (these tests were previously excluded by provision flag, that flag is now removed).
Removed BZ 1358069 wrapper as it is not needed anymore.
=> [1LP][RFR] Wrap test_rhev_iso_service_catalog and test_iso_provision_from template

cfme/tests/infrastructure/test_snapshot.py
This is a fix/workaround for a known issue in automation:
"Could not do function _looking_for_state_change"
This occurs mainly when running snapshot tests where a suspend VM action is performed. For an unknown reason, when jenkins tries to suspend the testing VM, it gets powered off and an error is thrown when waiting for it to become suspended. I investigated the behaviour and could not reproduce locally nor in PRT.
The error occurs on regular basis for many runs on 5.9. In order to increase our success rate when running our test suite, a fix for this is proposed: try to suspend the VM on a provider instead of doing it via CFME UI.
The proposed fix/workaround does not interfere with the purpose of the test. Test just needs a suspended VM to perform snapshot operations on it and doesn't …
=> [1LP][RFR] Workaround for snapshot VM suspend

docs/guides/debugging.rst
Intent
pytest has a cool feature to enable a debugger if an exception occurred. By default, it calls `pdb`, but it isn't so convenient. There is another debugger called `pudb`. It requires only two packages to be installed and then you can use it in such way:
`pytest some_test --pudb`
https://github.com/inducer/pudb
https://github.com/wronglink/pytest-pudb
=> [DOC][1LP][RFR] Introducing pudb

cfme/cloud/provider/__init__.py, cfme/cloud/provider/vcloud.py, cfme/common/provider.py, cfme/common/provider_views.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/infrastructure/provider/__init__.py, cfme/networks/provider/nuage.py, cfme/physical/physical_server.py, cfme/physical/provider/__init__.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/openstack/infrastructure/test_relationships.py
Intent
Continuation of replacement get_detail() method by calling ParametrizedSummaryTable in respectful views.
{{pytest: -v -k "test_infra_provider_relationships or test_assigned_roles" --long-running}}
=> [1LP][RFR] Replacement get_detail() for providers

cfme/tests/infrastructure/test_provisioning_rest.py
This PR has three parts:
1) __Fixing__ provisioning data in `test_provisioning_rest.py` to be compliant with new definition of vlan attribute: https://bugzilla.redhat.com/show_bug.cgi?id=1541036#c4
2) __Moving__ some helper functions from test_provision to module level, since I will need them for future tests as well and don't want to duplicate code.
3) __Removing__ BZ wrapper. The referenced BZ is still not solved, but it became clear that it is not actually a blocker.
Note: This still does not work for vsphere. I tried to do a quick fix but it didn't work. Unfortunately I don't really have the resources for fixing vsphere.
=> [1LP][RFR] Using default vNIC profile in REST VM provision

cfme/common/provider_views.py
{{pytest: --use-provider=scvmm2016 cfme/tests/cloud_infra_common/test_events.py}}
we also need to double check the rest of places
=> [1LP][RFR] reload button title has been changed in 5.8.3.4

cfme/tests/containers/test_provider_configuration_menu.py
Fixing test, by deleting the part of removing the selected container provider.
{{pytest: cfme/tests/containers/test_provider_configuration_menu.py -v --use-provider ocp-v1}}
=> [1LP][RFR] Provider configuration menu test , cancel  removing selected container provider

cfme/rest/gen_data.py, cfme/tests/services/test_rest_services.py
* removed unused ``dialog_ui`` function
* better checking of data returned by create and edit actions
* new test ``test_edit_service_dialogs``
{{pytest: -v --long-running -k TestServiceDialogsRESTAPI cfme/tests/services/test_rest_services.py}}
=> [1LP][RFR] New tests and enhancements to service dialogs API testing

cfme/tests/infrastructure/test_vm_rest.py, cfme/tests/test_rest.py
{{pytest: -v -k test_vm_scan cfme/tests/infrastructure/test_vm_rest.py}}
=> [1LP][RFR] Move test_vm_scan to file with other VMs-related tests

cfme/configure/tasks.py, cfme/tests/infrastructure/test_host_analysis.py
_Fixing_ test_host_drift_analysis.py. I recently re-activated this module in RHV-CFME integration suite and found out it failes seemingly randomly. After some digging I discovered that the reason for failure was this:
-  FW runs SSA on host
- Then goes to Administration -> Tasks view
- Then it tries to check the task of SSA was completed successfully
However, at this point it sometimes happen that the task is not even displayed yet in the table of tasks. Therefore any attempt to operate on it resulted `NoSuchElementException`. The only way AFAIK to get task's updated status is to refresh the whole view. I achieved that by overloading `wait_displayed` method of Table, but I don't know if this is the right way. Please share your ideas with me. 
Addendum:
I also discovered that test …
=> [1LP][RFR] Fixing table of tasks in Tasks view

cfme/common/host_views.py, cfme/infrastructure/host.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/control/test_actions.py, cfme/tests/infrastructure/test_host_analysis.py, cfme/tests/infrastructure/test_host_drift_analysis.py, cfme/tests/infrastructure/test_host_provisioning.py, cfme/tests/openstack/cloud/test_instances.py, cfme/tests/openstack/infrastructure/test_host_lifecycle.py, cfme/tests/openstack/infrastructure/test_hosts.py
Intent
Continuation of replacement get_detail() method by calling ParametrizedSummaryTable in respectful views.
{{pytest: -v -k "test_host_relationships or test_run_host_analysis or test_host_drift_analysis or test_host_provisioning or test_host_configuration" --long-running}}
=> [1LP][RFR] Replacement get_detail() for hosts

cfme/automate/buttons.py, cfme/tests/ansible/test_embedded_ansible_automate.py, cfme/tests/ansible/test_embedded_ansible_services.py, cfme/tests/automate/test_buttons.py, cfme/tests/automate/test_common_methods.py, cfme/tests/automate/test_vmware_methods.py, widgetastic_manageiq/__init__.py
Intent
Ansible Playbook button was introduced in CFME 5.9
{{pytest: -v -k "test_ansible_playbook_button_crud or test_custom_button_order_ansible_playbook_service or test_custom_button_ansible_credential_list or test_button_crud or test_button_on_host or test_vm_retire_extend or test_vmware_vimapi_hotadd_disk " --long-running --use-provider vsphere6-nested}}
=> [1LP][RFR] Added ansible playbook custom button

cfme/containers/provider/openshift.py
Add is_refreshed method in openshift provider,
Overrides cfme.common.provider.BaseProvider#is_refreshed.
Add validate_status check after provider creation,
In order to make sure that openShift provider data refresh completed.
{{pytest: cfme/tests/containers/test_provider_openscap_policy_attached.py -v --use-provider ocp-v1}}
=> [1LP][RFR] Override is_refreshed method in openshift provider

cfme/scripting/quickstart.py, cfme/utils/browser.py, cfme/utils/trackerbot.py, scripts/template_tester.py, scripts/template_upload_all.py
1) Add two new methods to template tester scripts to support the new multijob flow
a) check if a template is already tested
b) simply print the template name that will be generated, so we can pass that in to method a above
2) Check installed pkgs before running dnf or yum install. This is to get around the 'transaction error check failed'/'package is already installed' dnf errors we're sporadically hitting on Jenkins runs.
=> [1LP][RFR] Changes for jenkins

cfme/tests/infrastructure/test_snapshot.py
__Wrapping__ test_verify_revert_snapshot until we can accomodate our RHV-CFME env.
{{pytest: cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot --use-provider rhv41 -vv}}
=> [1LP][RFR] Wrapping test_verify_revert_snapshot for RHV-CFME integration

cfme/tests/infrastructure/test_vm_reconfigure.py
__Wrapping__ test_vm_reconfig_add_remove_hw_cold in a way that
1) Skips it on 5.8 as well. This bug was not seen in 5.8 before but I encountered it in 5.8.3.4
2) It is executed when it is not parametrized with `change_type == memory`. Other variants should run because the referenced bug is affecting solely memory reconfiguration.
{{pytest:  cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_hw_cold -vv --long-running}}
=> [1LP][RFR] Wrapping test_vm_reconfig_add_remove_hw_cold with BZ for 5.8

cfme/tests/infrastructure/test_vm_reconfigure.py
Cancel reconfiguration changes.
{{pytest: --long-running --use-provider vsphere65-nested --use-provider rhv41 -k test_reconfig_vm_negative_cancel cfme/tests/infrastructure/test_vm_reconfigure.py}}
=> [1LP][RFR] Add new test to cancel vm reconfiguration changes

cfme/utils/testgen.py
Fix for an issue with PXE test collection after recent refactor.
@lkhomenk @jan-zmeskal Please check that current collection (on PRT) is correct. The tests won't be executed, this affects only collection. Thanks
Edit: I decided to execute the tests, just in case.
{{pytest: cfme/tests/infrastructure/test_host_provisioning.py cfme/tests/infrastructure/test_pxe_provisioning.py cfme/tests/services/test_pxe_service_catalogs.py cfme/tests/infrastructure/test_pxe.py --use-provider complete}}
=> [1LP][RFR] Fix PXE-related testgen and test collection

cfme/tests/infrastructure/test_vm_reconfigure.py
__Removing__ wrapper. The bug still exists but we changed RHV-CFME integration env in a way that this test case can now be executed. I will create a test case that specifically covers this BZ afterwards.
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_hw_cold[rhv41-memory] -vv --long-running}}
=> [1LP][RFR] Removing BZ wrapper for test_vm_reconfig_add_remove_hw_cold

cfme/common/provider.py, cfme/physical/provider/lenovo.py, cfme/tests/physical_infrastructure/api/test_physical_server_inventory_api.py
__Adding tests__ for get physical servers inventory data by rest API:
- test_get_hardware
- test_get_hardware_attributes (firmwares, nics and ports)
- test_get_asset_details
This PR also adapt the `LenovoProvider` class to work properly with `create_rest` method
=> [1LP][RFR] Adding Physical Servers Inventory API Tests

cfme/utils/trackerbot.py
Class for generating trackerbot/sprout friendly template names from the CFME build server URLs.
This is intended as a replacement for what is currently in template_upload_all generating template names for us.  The current naming scheme is inconsistent, and uses different date timestamps sometimes for the same build of MIQ/CFME.  Timestamps also were not consistent across streams.
To be used in new template_upload flow that @ohiliazo is working on.
Testing against several CFME/MIQ build URLs, including the URLs that until now have not been able to run through template_upload_all:
http://pastebin.test.redhat.com/558699
=> [1LP][RFR] Add TemplateName class to cfme/utils/trackerbot

cfme/cloud/instance/azure.py, cfme/tests/cloud/test_instance_power_control.py
{{ pytest: -v -k test_hard_reboot_unsupported --use-provider azure --long-running cfme/tests/cloud/test_instance_power_control.py }}
This is a negative test, hard reboot is not supported in azure and an error message should be thrown by CFME.
=> [1LP][RFR] Automate test hard reboot for azure

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
__Fixing__ `get_service` fixture. Why doing this? Consider following scenario:
1) You execute a test case (or combination thereof) where the private method `_get_service` never gets actually called.
2) During the module teardown, the outer public `get_service` method continues after `yield` statement and tries to delete the service
3) None is found (remember, `_get_service` was never called!) and `Collection.get` method throws [ValueError](https://github.com/ManageIQ/manageiq-api-client-python/blob/fd3893d51a0a25daffb9db7723dc15feb2877c42/src/manageiq_client/api.py#L333).
In this scenario, you will get FAILURE during teardown after whichever test case was executed the last.
{{pytest: cfme/tests/cloud_infra_common/test_custom_attributes_rest.py::TestCustomAttributesRESTAPI::test_edit[rhv41- …
=> [1LP][RFR] Fixing get_service fixture

cfme/scripting/setup_env.py, cfme/test_framework/sprout/client.py, cfme/tests/test_db_migrate.py, fixtures/appliance.py
Added the usage of provider_type to make migration tests and setup-env script more reliable to prevent unusable templates causing errors.
{{pytest: -v -k "test_db_migrate_replication"}}
=> [1LP][RFR] provider_type intergration to stabilize tests and scripts

cfme/tests/infrastructure/test_provisioning_rest.py
* more complete attributes checks
* replace some UI actions with REST counterparts
* better cleanup
* better results checking
{{pytest: -v --use-provider rhv41 cfme/tests/infrastructure/test_provisioning_rest.py}}
=> [1LP][RFR] Enhancements to test_provisioning_rest

cfme/tests/cloud_infra_common/test_rest_providers.py
{{pytest: -v -k test_provider_options cfme/tests/cloud_infra_common/test_rest_providers.py}}
=> [1LP][RFR] Adds test_provider_options API test

cfme/tests/intelligence/reports/test_metering_report.py
{{pytest: cfme/tests/intelligence/reports/test_metering_report.py --use-provider complete}}
PRT results:
59 : Passed on RHV, Provider skips - v6, v65
58 : Tests uncollected like expected since Metering reports have been introduced in 59
=> [1LP][RFR] Metering Reports: Add support for storage metrics

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
__Adding tests__ for snapshot functionality for RHV provider. It's basically automation of [RHEVM-17102](https://polarion.engineering.redhat.com/polarion/redirect/project/RHEVM3/workitem?id=RHEVM-17102) and [RHEVM-17137](https://polarion.engineering.redhat.com/polarion/redirect/project/RHEVM3/workitem?id=RHEVM-17137) from Polarion.
These are actually my first tests written in CFME QE framework. Therefore I am not sure if I am using things  the right way and putting them in correct places.
{{pytest: cfme/tests/infrastructure/test_snapshot.py::test_create_without_description cfme/tests/infrastructure/test_snapshot.py::test_revert_on_running_vm --use-provider rhv41 -vv --long-running}}
=> [1LP][RFR] Adding RHV tests for snapshots

cfme/tests/control/test_actions.py
Purpose
RHV 4.1 supports snapshots creation, therefore it can be enabled for appropriate tests.
{{pytest: --use-provider=vsphere6-nested -v -k "test_action_create_snapshot_and_delete_last or test_action_create_snapshots_and_delete_them" --long-running}}
=> [1LP][RFR] Enabled RHV provider for snapshots action test

scripts/clean_appliance.py
__Extending__ clean_appliance.py utility script.
1) `-q` argument for quiet
2) Waiting for closing all DB connections. If you try to call evm:db:reset and some connections are still active, the call will fail
3) I noticed that evm:db:reset sometimes leaves appliance in a state from where it cannot be started using `systemctl start evmserverd`. AFAIK this only happens with 5.8. Therefore handling this with condition.
=> [1LP][RFR] Extending clean_appliance.py

cfme/tests/networks/test_tag_tagvis.py
Purpose
Added _test_tagvis_network_provider_children_ to check visibilty of network provider childs for restricted user.
{{pytest: -vvv cfme/tests/networks/test_tag_tagvis.py}}
=> [1LP][RFR] Added test_tagvis_network_provider_children

cfme/tests/ssui/test_ssui_myservice.py
Extending SSUI console test for OSP.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider rhos11 }}
=> [1LP][RFR]Updating Console tests for SSUI to work with OSP

cfme/scripting/ipyshell.py
Intent
`miq shell` cannot be used on systems that are not defined in [cfme/scripting/quickstart.py](https://github.com/ManageIQ/integration_tests/blob/master/cfme/scripting/quickstart.py).  This PR adds `--no-quickstart` flag to prevent execution of quickstart.py.
=> [RFR][1LP] Added --no-quickstart flag for miq shell

data/rhel6.cfg
Recent image is rhel63 is a bit outdated. PXE provision on rhv41 stucks on "Unsupported hardware warning" message. with MR will pass it safely 
{{pytest: -k "test_pxe_provision" --long-running --use-provider complete}}
=> [1LP][WIPTEST]skip unsupported hardware warning during PXE provision

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vm_reconfigure.py, widgetastic_manageiq/vm_reconfigure.py
__Fixing__ test_vm_reconfig_add_remove_disk_cold because it is currently doesn't remove disks that were added to VM from the env
+ Resolving few TODOs
{{pytest: --long-running --use-provider vsphere65-nested --use-provider rhv41 -k test_vm_reconfig_add_remove_disk_cold cfme/tests/infrastructure/test_vm_reconfigure.py}}
=> [1LP][RFR] fixes for test_vm_reconfigure

cfme/utils/ssh.py
The recv_ready functions on stdout and stderr were being called as property's rather than functions (which they are defined as functions).   Beause of this when calling ssh.py's
run_command() it was causing some programs to hang when ran.
What was happening was when the recv_ready function was checked 
without the params, it would return an object, and an object is always true
in the context of an if (well unless operator overloading in boolean context
was used).   Anyway, needed to add ()'s at the end of those calls.
I'm actually not sure why it wasn't seen with just any program,
but maybe somehow short running programs did not experience the
problem.   But the end result was if you had a either stdout or
stderr empty, it would still try to read from it and then the
paramiko read() code …
=> [RFR][1LP] Use paramiko recv_ready as function

cfme/tests/intelligence/reports/test_canned_corresponds.py
__Fixing__ test_providers_summary. The test used to failed with: 
> AttributeError: 'ProviderDetailsSummaryView' object has no attribute 'properties'
I am also excluding redhat_network provider from the test.
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_providers_summary -vv}}
=> [RFR] Fixing test_providers_summary

cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/utils/rest.py
* support for testing snapshots on RHEVM
* test for BZ 1550551
{{pytest: -v --long-running cfme/tests/cloud_infra_common/test_snapshots_rest.py}}
=> [RFR] Add support for RHEVM snapshots REST testing

cfme/tests/networks/test_sdn_crud.py, cfme/tests/networks/test_sdn_navigation.py
Purpose
Updated _test_sdn_crud_ and _test_sdn_navigation_ due to get_details changes for providers view.
{{pytest: -vvv cfme/tests/networks -k "test_provider_relationships_navigation or test_provider_topology_navigation or test_sdn_crud"}}
=> [1LP][RFR]Updated test_sdn_crud and test_sdn_navigation

cfme/utils/ssh.py
I got two of the recv_ready calls in ssh.py but missed the other
two.  This fixes that.
=> [WIPTEST] Turn the other two recv_ready()'s into functions

cfme/networks/subnet.py
The flash message of edit subnet was changed from Network Subnet "subnet" updated to Cloud Subnet "subnet" updated which fails assert_success_message operation
{{ pytest: cfme/tests/openstack/cloud/test_networks.py::test_edit_subnet }}
=> [RFR] update flash message of edit subnet

cfme/services/myservice/__init__.py, cfme/services/myservice/ui.py
Purpose
MyService class should have `exists` property, not a method. This property is heavily used in ansible tests.
{{pytest: -v -k "test_custom_button_ansible_credential_list" --long-running}}
=> [1LP][RFR] exists() method converted to a property

cfme/ansible/repositories.py, cfme/tests/ansible/test_embedded_ansible_services.py
Intent
`test_service_ansible_playbook_provision_in_requests` didn't contain a teardown and that affected on other tests.
{{pytest: -v -k "test_service_ansible_playbook_provision_in_requests or test_service_ansible_playbook_plays_table" --long-running}}
=> [1LP][RFR] Fixed Multiple requests error in ansible services tests

cfme/tests/openstack/cloud/test_networks.py
items property is no longer available under view.entities.relationships. it was replaced with fields
{{ pytest: cfme/tests/openstack/cloud/test_networks.py::test_clear_router_gateway }}
=> [RFR] items property replaced with fields

cfme/utils/appliance/__init__.py, cfme/utils/events.py, cfme/utils/events_db.py, fixtures/events.py
* created a separate module that use REST API instead of DB calls for events processing.
* commented changes
* made a copy of DB calls module to maintain 5.8 version that doesn't have such REST API functionality.
* removed duplicated set_last_record()
{{ pytest: -v cfme/tests/cloud/test_cloud_events.py cfme/tests/cloud_infra_common/test_events.py}}
=> [1LP][RFR] Changed event_streams db calls to rest calls

cfme/tests/infrastructure/test_customization_template.py
__Extending__ test_customization_template_crud to cover all customization types
{{pytest: -k "test_customization_template_crud"}}
=> [1LP][RFR]parametrizing  test_customization_template_crud

cfme/services/requests.py, cfme/tests/cloud/test_provisioning.py, cfme/tests/infrastructure/test_provisioning.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_provisioning_rest.py, cfme/tests/infrastructure/test_vm_clone.py, cfme/tests/infrastructure/test_vm_migrate.py, cfme/tests/services/test_cloud_service_catalogs.py, cfme/tests/services/test_config_provider_servicecatalogs.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_iso_service_catalogs.py, cfme/tests/services/test_myservice.py, cfme/tests/services/test_provision_stack.py, cfme/tests/services/test_pxe_service_catalogs.py, cfme/tests/services/test_service_catalogs.py
__Fixing__  error logging for faulty provision requests. When we get  "Error" state of request, message requires some time to be updated
{{pytest: --long-running --use-provider complete cfme/tests/cloud/test_provisioning.py cfme/tests/infrastructure/test_provisioning_rest.py cfme/tests/infrastructure/test_provisioning.py cfme/tests/services/test_service_catalogs.py }}
=> [1LP][RFR]last_message update

cfme/fixtures/vm.py, cfme/test_framework/pytest_plugin.py, cfme/tests/ansible/test_embedded_ansible_actions.py, cfme/tests/ansible/test_embedded_ansible_automate.py, cfme/tests/control/test_alerts.py
Intent
Reduced code duplication by creating the special full_template_vm fixture.
{{pytest: -v -k "test_custom_button_order_ansible_playbook_service or test_action_run_ansible_playbook_localhost or test_alert_vm_turned_on_more_than_twice_in_past_15_minutes" --use-provider vsphere6-nested --long-running}}
=> [1LP][RFR] Added full_template_vm fixture

cfme/tests/test_utilization_metrics.py
Removed  vm/host_rising in test_utilization_metrics because it was necessary for host and vm to report metrics within 15 seconds interval. It should be sufficient to wait until non-zero number of metrics are reported by host and vm.
=> [1LP][RFR] Removed vm/host_rising in test_utilization_metrics.

cfme/networks/provider/__init__.py, cfme/networks/provider/nuage.py, cfme/utils/appliance/__init__.py
With this commit we add Nuage provder to the RECOGNIZED_BY_CREDS in order to make fixtures work again. Doing this it turns out that Nuage provider is not hashable, which causes problems when adding it to a set(), which we also fix in this commit.
=> [1LP][RFR] Add Nuage to the RECOGNIZED_BY_CREDS list

cfme/tests/infrastructure/test_provisioning_rest.py
__Adding test__ to automate [BZ1422208](https://bugzilla.redhat.com/show_bug.cgi?id=1422208). The test checks that no redundant mails have been sent after requesting and completing provision where VM has CPU and memery values different from template's default. 
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_emails -vv}}
=> [1LP][RFR] Adding test_provision_emails

cfme/services/catalogs/orchestration_template.py, cfme/services/requests.py, cfme/services/service_catalogs/ui.py, cfme/tests/services/test_provision_stack.py
Fixed incorrect teardown in test_provision_stack.py. We should remove orchestration templates via UI. Besides some refactoring has been made. All prerequisite stuff moved to fixtures.
{{pytest: -v cfme/tests/services/test_provision_stack.py --use-provider ec2west}}
=> [1LP][RFR] Refactored test_provision_stack.py

cfme/utils/ssh.py
Some programs put out a small amount of output, and we will receive the
exit code before transport thread that unencrypts the data from
stdout and stderr has time to do so.   In that case checking
recv_ready() is the wrong thing to do because recv_ready in
paramiko's ssh implementation only returns True if there is
unencrypted data in the buffer.   However for programs producing
lots of output just doing reads without first checking whether there
is data to be read may put your process in a blocked state if the
file will never have output (e.g. stderr).   Even programs
producing lots of output on both stderr and stdout can experience this
because if for a bit its not producing output on one file while
it is on the other, the one it is producing output on may fill
up its remote buffer …
=> [RFR] Make ssh.py's run_command work for all programs

cfme/cloud/provider/__init__.py, cfme/infrastructure/provider/__init__.py
I was hitting `MoveTargetOutofBounds` exceptions in PR #6814, and found that it was always occuring on the Providers 'All' destination, when trying to click the dropdown to add a new provider.  The screenshots showed that it was on the 'All' destination, and a provider quadicon was there with a flash message that it had been deleted - indicating no navigation/refresh between the fixture  cleanup of the provider and the next test case.
Not considering this a 'fix-framework' PR since this is more a workaround than a fix for the `MoveTargetOutofBounds` occuring when the widget is visible.
{{ pytest: -k test_provider_crud --use-provider complete }}
=> [1LP][RFR] Add browser refresh to provider 'All' resetters

cfme/networks/views.py, cfme/tests/networks/test_sdn_balancers.py, cfme/tests/networks/test_sdn_crud.py, cfme/tests/networks/test_sdn_downloads.py, cfme/tests/networks/test_sdn_navigation.py, cfme/tests/networks/test_sdn_ports.py
Renamed all tests to have them starting with sdn_*
Fix a button. 
Add more provider coverage
{{pytest: -v -q cfme/tests/networks/test_sdn_balancers.py cfme/tests/networks/test_sdn_crud.py cfme/tests/networks/test_sdn_downloads.py cfme/tests/networks/test_sdn_navigation.py cfme/tests/networks/test_sdn_ports.py --use-provider=complete}}
=> [1LP][RFR] Add providers and rename tests

cfme/cloud/tenant.py, cfme/tests/cloud_infra_common/test_relationships.py
Purpose 
Added _test_tagvis_infra_provider_children_ and _test_tagvis_cloud_provider_children_ to check that provider child's are not be visible for restricted user. 
{{pytest: -v cfme/tests/cloud_infra_common/test_relationships.py -k provider_children}}
=> [1LP][RFR]Added test_tagvis_provider_children for cloud and infra

cfme/tests/configure/test_register_appliance.py
Added new test to check default repos of appliance. Also checks what repos are set after clicking default button.
{{pytest: -v -k "test_rhsm_registration_check_repo_names"}}
=> [1LP][RFR] New test added for checking repos

cfme/tests/openstack/infrastructure/test_relationships.py
fixed syntax error on: view.entities.view.entities.relationships.get_text_of('Templates')
Removed 'not' from: soft_assert(image not in template_names, 'Missing template: {}'.format(image))
{{ pytest: cfme/tests/openstack/infrastructure/test_relationships.py::test_templates --use-provider default }}
=> [1LP][RFR] fixed test templates test

cfme/networks/provider/__init__.py, cfme/networks/provider/nuage.py, cfme/networks/views.py, cfme/tests/networks/test_network_providers.py, conf/cfme_data.yaml.template, conf/credentials.yaml.template
With this commit we extend Nuage provider so that it now inputs AMQP credentials upon creation as well. Until now we were only inputing the Default credentials.
Also, with this commit we update test that was only testing
- CREATE
- RETRIEVE
- DELETE
of Nuage provider to now also validate
- UPDATE
which gives us a complete CRUD test in the end.
=> [1LP][RFR] Turn eventing ON for Nuage provider

cfme/tests/physical_infrastructure/api/test_physical_server_api.py
__Adding tests__ for the Physical Server API:
- GET
-  Existent physical server;
-  Nonexistent physical server.
- Power actions:
-  invalid_action;
-  refresh;
-  power_on;
-  power_off;
-  power_off_now;
-  restart;
-  restart_now.
- Led actions:
-  blink_loc_led;
-  turn_on_loc_led;
-  turn_off_loc_led.
Implementation details
Once the tests are covering the entire cycle of *power operations* it needs to wait the following steps to be conclude:
1. Send request to ManageIQ;
1. Send request to Physical Servers Provider;
1. The operation be concluded on Physical Server;
1. The refresh cycle of Physical Server Provider to identify the power state of Physical Server change;
1. The refresh cycle of ManageIQ to get the new state of Physical …
=> [1LP][RFR] Adding Physical Server API tests

cfme/physical/provider/__init__.py, cfme/physical/provider/lenovo.py, conf/cfme_data.yaml.template
__Updating `cfme_data.yaml.template`__ adding hostname information in `lenovo` section.
__Updating__ the way that Physical Providers access the `hostname` and `ip_address` information to follow the standard on project
=> [1LP][RFR] Adding hostname information in cfme_data in lenovo section

scripts/coverage_report_jenkins.py, scripts/data/coverage/coverage_merger.rb
When we merged the coverage data we would replicate all .resultset.json files in one file, merge/.resultset.json.   This file in some case would be 100Mb's.   These changes make it actually merge the file coverage data for reach file, thus not having replicated data.   Merging the data in this way makes the file like 2Mb in size, and makes the sonar-scanner run for less than 2 minutes (as opposed to approximately 50 minutes).
=> [1LP][RFR] Make coverage_merger.rb not replicate file data anymore

cfme/common/vm_views.py
Intent
`SelectTable` can find a row not only by the name column but by others as well:
```python
select_table_widget.fill({
'name': 'some_string',
'provider': 'some_provider'
})
```
{{pytest: -v -k "test_provision_from_template" --use-provider vsphere6-nested}}
=> [1LP][RFR] Slight improvement of SelectTable

cfme/tests/intelligence/reports/test_metering_report.py
{{pytest: cfme/tests/intelligence/reports/test_metering_report.py --use-provider complete}}
PRT results:
58 - Tests were skipped, like expected
59 - All the tests, including the ones for cloud providers passed , except for test_validate_storage_usage[vsphere65-nested] 
I could investigate and fix that failure with a follow up PR.
=> [1LP][RFR] Metering Reports: Support for cloud providers

cfme/base/__init__.py, cfme/utils/appliance/__init__.py
Implemented for Server, Zone, and Region
Appliance set_yaml_config runs against the master server
Repetitive code for get/set yaml_config, but each uses a different 'id' attribute. But as a single method, each class would still need a method wrapping them, and I don't think this is appropriate to implement in BaseEntity, thus, code duplication.
Requesting lots of reviews, I want to get a lot of eyes on this.
I've tested locally, would love to get some feedback regardless of PRT results at this time, given the impact.
=> [1LP][RFR] Refactor get_yaml_config/set_yaml_config for REST

cfme/tests/containers/test_containers_summary.py, cfme/tests/containers/test_static_custom_attributes.py
During examination of the RC jobs, the tests were failing with the following attribute error:
AttributeError
'ProviderDetailsSummaryView' object has no attribute 'custom_attributes'
Updating tests to use the new parameritized table
{{ pytest: cfme/tests/containers/test_containers_summary.py cfme/tests/containers/test_static_custom_attributes.py --use-provider ocp-v2 --long-running }}
=> [1LP][RFR] Update CMQE tests to use the new parametized summary table

cfme/base/login.py, cfme/configure/access_control/__init__.py, cfme/fixtures/tag.py, cfme/tests/cloud_infra_common/test_vm_ownership.py, cfme/tests/configure/test_access_control.py, cfme/tests/intelligence/reports/test_metering_report.py, cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Add support for adding a user to multiple RBAC groups. Supported in version >= 5.9
access_control.UserCollection.create will allow you to create a user that is a member of multiple groups.
You can now check the currently assigned group and all assigned groups properly in 5.9
{{pytest: -v -k 'test_user_group_test_user_crud or test_user_assign_multiple_groups or test_user_group_error_validation or test_group_ownership_on_user_or_group_role or test_group_ownership_on_user_only_role'}}
=> [1LP][RFR] Add support for adding a user to multiple RBAC groups

cfme/cloud/provider/azure.py, cfme/cloud/provider/ec2.py, cfme/cloud/provider/gce.py, cfme/cloud/provider/openstack.py, cfme/common/provider.py, cfme/containers/provider/kubernetes.py, cfme/containers/provider/openshift.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/scvmm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/networks/provider/nuage.py, cfme/physical/provider/lenovo.py, cfme/tests/cloud/test_providers.py, cfme/utils/appliance/__init__.py, fixtures/provider.py
Methods to deal with disabled_regions field in advanced configuration, which is commonly used by MIQ/CFME to disable govcloud regions (or any other).
Add provider attribute for what its ems settings key is in the config
(YAML or JSON)
Lookup disabled regions for everything, or per given provider
We don't have govcloud regions available for general consumption or via PRT, running crud test to verify no failure in configuring non-govcloud regions.
With #6836 this passes PRT (mostly) clean. I've pulled in 1 line from that to cloud providers in this PR.
59z passing ~83% with 3 unrelated REST test failures.
Have tested in Jenkins for govcloud, sufficient to get tests running.
{{ pytest: cfme/tests/cloud/test_providers.py --long-running --use-provider complete }}
=> [1LP][RFR] Add appliance methods for querying/modifying disabled regions

cfme/networks/views.py
This is a followup commit for a PR where we introduced ParametrizedSummaryTable for all providers at once, but NetworkProviders were somehow only partially refactored and hence left in broken state.
The PR we're fixing: https://github.com/ManageIQ/integration_tests/pull/6713
=> [1LP][RFR] Make `summary("Relationships")` great again for NetworkManagers

cfme/tests/infrastructure/test_snapshot.py
__Blocking__ test_snapshot_crud because of RHV bug.
{{pytest: cfme/tests/infrastructure/test_snapshot.py::test_snapshot_crud --use-provider rhv41}}
=> [1LP][RFR] Blocking test_snapshot_crud for RHV

cfme/tests/infrastructure/test_snapshot.py
__Unblocking__ test_verify_revert_snapshot since #6744 is solved.
{{pytest: cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot -vv --use-provider rhv41 --long-running}}
=> [1LP][RFR] Unblocking test_verify_revert_snapshot

cfme/tests/ssui/test_ssui_myservice.py
__Uncollecting__ test_vm_console for RHV-CFME integration. The reason is quite pragmatic. The console tests are very much browser-dependent. In order to achieve stability, we wound need to emulate CFME QE testing environment. Now in the context of scaling down of resources dedicated to this effort, we cannot really do that for the purpose of this test case.
{{pytest:  cfme/tests/ssui/test_ssui_myservice.py::test_vm_console}}
=> [1LP][RFR] Uncollecting test_vm_console for RHV-CFME integration

cfme/tests/cloud/test_providers.py, cfme/tests/configure/test_tag_category.py, cfme/tests/infrastructure/test_provisioning_rest.py, cfme/tests/infrastructure/test_vm_ownership.py, cfme/tests/infrastructure/test_vm_retirement_rest.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/intelligence/test_chargeback.py, cfme/tests/perf/workloads/test_provisioning.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_service_catalogs.py, cfme/utils/rest.py
These tests were failing due to MIQ API returning a 200 OK after calling delete. Technically, this is acceptable according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html section 9.7
=> [1LP][RFR] Expect 200 or 204 from a REST DELETE, change to using assert_response() in most places

cfme/containers/container.py, cfme/containers/image.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py
Problem:
CloudForms archives the following resources:
app/models/container.rb:  include ArchivedMixin
app/models/container_group.rb:  include ArchivedMixin
app/models/container_image.rb:  include ArchivedMixin
app/models/container_node.rb:  include ArchivedMixin
app/models/container_project.rb:  include ArchivedMixin
Solution:
Allow user to query on all, active, archived entries. 
{{ pytest: cfme/tests/containers/test_cockpit.py --use-provider cm-env2 --long-running }}
Manual Testing:
container_projects:
```
In [2]: dc = appliance.collections.container_projects
In [3]: dc.all()
Out[3]: 
[Project(name=u'muihvefzcm', provider=<cfme.containers.provider.openshift.OpenshiftProvider name='CM JUWATTS', key='cm-juwatts', zone='default', metrics_type='Hawkular', alerts_type='Disabled'>), …
```
=> [1LP][RFR] Update all Method to allow Querying of All, Active, or Archived DB Entries

cfme/tests/intelligence/reports/test_validate_chargeback_report.py
PRT results:
58 - All tests passed
59 - All tests passed
=> [1LP][RFR] Chargeback cost validation : some code refactoring

cfme/test_framework/appliance_log_collector.py, cfme/test_framework/pytest_plugin.py
Adding a pytest option for appliance log collection at session shutdown.
* New `--collect-logs` cli arg
* Gets configuration from env.yaml
* List of logs to collect on appliances, and a local dir relative to `conf.utils.path.log_path`.
* Handles multiple appliances
* Names the file based on `appliance.hostname`
* Logging!
First time writing hookwrapper, hopefully I haven't done anything too foolish.
=> [1LP][RFR] Add appliance_log_collector plugin

scripts/coverage_report_jenkins.py
Updated generation of project key to match format of:
<project-name>_<major_version>_<minor_version>_<language>_<coverage|static|full-analysis>
Which for us looks like:
CFME_5_9_ruby_coverage
=> [1LP][RFR] Update project_key to match what Central CI wants for their sonarqube

cfme/base/__init__.py, cfme/utils/appliance/__init__.py
* Sometimes, I think in 5.8 the sid, id are coming in as int. So here
we cast them to strings.
=> [RFR] Get yaml config doesn't work on 5.8

cfme/tests/physical_infrastructure/api/test_physical_server_events_api.py
Adds simple events API test to Lenovo provider
Depends on:
* [ManageIQ/integration_tests](https://github.com/ManageIQ/integration_tests/pull/6689)
=> [1LP][RFR] Adds events API tests to Lenovo provider

cfme/storage/volume.py, cfme/tests/storage/test_volume.py
- Storage pages improved now. It's time to add test cases
- `test_volume_navigation` test no more needed. All view going to use in different upcoming tests.
- `test_volume_collective_crud` test was not good approach [ Initial time it was good means test with model page] as it's unable to delete volume having status `in-use` better to go with `test_storage_volume_crud` now.
- changes added for future purpose as I am trying to automate all tests related to storage.
{{pytest: cfme/tests/storage/test_volume.py -v}}
=> [1LP][RFR] Refactor Volume tests

cfme/containers/provider/openshift.py
validate_stats is to specific of a check for checking if the provider is refreshed. This is blocking adding OCP providers.  This is undoing https://github.com/ManageIQ/integration_tests/pull/6737
{{ pytest: cfme/tests/containers/test_static_custom_attributes.py --use-provider ocp-v1 --long-running }}
=> [RFR] Remove is_refreshed method from OpenShiftProvider class

cfme/common/provider.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/control/explorer/alert_profiles.py, cfme/tests/containers/test_alerts.py
In this PR I added a pre-step for openshift provider setup.
In case an OpenShift provider has Prometheus alerts endpoint pre-setup steps are required.
I added the assignment of alert's profile (both node and provider) to "The Enterprise", so CFME will not ignore alerts that raise after adding the endpoint.
This PR can't run in PRT because it requires yamls change see https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/466
=> [WIP][RFR] Add pre-setup step for openshift provider with alert endpoint

cfme/cloud/instance/__init__.py, cfme/tests/cloud_infra_common/test_cockpit_server.py
{{ pytest: cfme/tests/cloud_infra_common/test_cockpit_server.py --use-provider complete }}
BZ 1497684
Cockpit Server role not available in 5.8 version.
=> [1LP][RFR] Add new test to check cockpit 'Web Console' button enable and disable working

cfme/tests/configure/test_ntp_server.py, cfme/tests/control/test_alerts.py, cfme/utils/appliance/__init__.py, cfme/utils/perf.py
* Symbols are converted to strings in REST API leading to broken config
for OpenShift.
* Previously we would get_yaml_config, modify it and then push the
entire config back. The getting of the yaml via the REST is what
breaks the strings.
* We now only do full patching for 5.8. This will need to be merged
alongside the other PR for yaml updates
=> [1LP][RFR] Mitigate the bug in CFME where symbols are converted to strings by REST

sprout/appliances/models.py
Those two parameters should appear in result of sprout appliance request
=> [1LP][RFR] essential params for openshift appliance serialization

cfme/tests/openstack/cloud/test_volumes.py
BZ  pytests mark no longer needed. BZ 1502609 is closed
{{ pytest: cfme/tests/openstack/cloud/test_volumes.py }}
=> [1LP][RFR] Remove BZ 1502609  blocker pytest.mark from volume tests

cfme/tests/networks/test_sdn_balancers.py
health check field is appearing only if it is setup and it is not mandatory on GCE. LBs were created without so test failed. check for a presence of an other field.
{{pytest: -v -q cfme/tests/networks/test_sdn_balancers.py --use-provider=complete}}
=> [1LP][RFR] remove BZ, fix test

scripts/cleanup_old_vms.py, scripts/list_provider_vms.py
Adds --tag option to cleanup_old_vms, and uses ProviderFilter instead of
directly implemented filtering.
@bsquizz this should help with running the script in govcloud contexts.
=> [1LP][RFR] Update cleanup_old_vms, use ProviderFilter

cfme/tests/containers/test_ssl_providers.py
Shriver: modified pytest line below, needs double brackets, was only singular bracket so no tests collected.
{{ pytest: cfme/tests/containers/test_ssl_providers.py --use-provider ocp-v3 }}
Update SSL tests to support Prometheus metrics in addition to Hawkular
=> [1LP][RFR] Update SSL test to support any metrics type

cfme/tests/openstack/infrastructure/test_provider.py
properties attribute is no longer available under entities. used instead view_details.entities.summary('Properties').get_text_of....
{{ pytest: cfme/tests/openstack/infrastructure/test_provider.py::test_api_port }}
=> [1LP][RFR] fixed provider test_api_port test

scripts/clone_template.py
not all providers have ssh_creds
=> [1LP][RFR] fix for template clone script 

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
I accidentally wrapped wrong test case with this BZ. __Fixing__ my mistake.
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py::test_ssa_vm --long-running -vv --use-provider rhv41}}
=> [1LP][RFR] Wrapping test_ssa_vm with BZ

cfme/tests/cloud_infra_common/test_power_control_rest.py
You can't do a 'hard reboot' from CFME UI on an azure instance, since that is unsupported by azure. So reset VM via REST shouldn't be expected to work either.
=> [1LP][RFR] Filter azure out of test_reset_vm, azure doesn't support hard reset

cfme/fixtures/service_fixtures.py, cfme/tests/ssui/test_ssui_myservice.py
__Fixing__ order_service and create_catalog_item Moved console_template out of function signature to avoid tests being skipped incorrectly due to 'console_template' not being found in provider data
**trackerbot/pr/run/22397 refer to this PRT run. latest run will skip due to bz. 59z failed due to regression BZ see comment below. 58z passed.**
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console'  --use-provider vsphere6-nested }}
=> [1LP][RFR] Making sure SSUI Tests are not skipped 

cfme/tests/test_rest.py
Added missing collections.
**PRT**
the failed test ``TestEventStreamsRESTAPI.test_find_created_events`` on 5.9 is not related to changes in this PR.
=> [1LP][RFR] Add missing API collections

cfme/base/login.py, cfme/base/ui.py
Was producing an exception because the view isn't actually displayed.
```python
>               appliance.server.login(user, method='click_on_login')
cfme/tests/integration/test_cfme_auth.py:183: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/site-packages/sentaku/context.py:132: in __call__
return bound_method(*k, **kw)
cfme/base/ui.py:189: in login
user.name = logged_in_view.current_fullname
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <cfme.base.login.BaseLoggedInPage object at 0x7fcd42f2f610>
@property
def current_fullname(self):
>       return self.settings.text.strip().split('|', 1)[0].strip()
E       AttributeError: 'NoneType' object has no attribute 'strip'
cfme/base/login.py:46: …
```
=> [1LP][RFR] Tweak base login and ui for exception handling

cfme/tests/services/test_myservice.py
In a recent change all tags are suffixed by * ,
so removing it from the test here .
=> [1LP][RFR] Changed tag name because of a recent change

cfme/scripting/quickstart.py, cfme/tests/cloud/test_cloud_events.py, cfme/utils/events.py
PURPOSE
__Fixing__ quickstart script because it was failing when the OS version wasn't recognized.
__Fixing__ test_cloud_events because now in 5.9 the response is dict instead of yaml stream.
__Minor changes__ to REST event listener get_next_portion func.
Shriver:
{{ pytest: cfme/tests/cloud/test_cloud_events.py --long-running --use-provider azure}}
=> [1LP][RFR] Fix cloud event listener

sprout/appliances/tasks.py
It doesn't make sense to check openshift appliances swap. This PR adds additional filter to exclude openshift appliances.
=> [1LP][RFR] excluding openshift appliances from swap check in sprout

requirements/frozen.txt, requirements/frozen_docs.txt
Fixing ``AttributeError: 'NoneType' object has no attribute 'strip'`` - like in [this Jenkins job](https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/downstream-59z-tests-master/331/consoleFull) (at the very bottom).
=> [1LP][RFR] Bump dump2polarion version to fix AttributeError

sprout/appliances/tasks.py
When there is new openshift template in trackerbot, sprout doesn't update custom data correctly.
It happens because only some certain fields are saved but custom_data isn't. 
This PR fixes that issue.
=> [1LP][RFR] updated custom data isn't saved

cfme/common/vm.py, cfme/fixtures/virtual_machine.py, cfme/tests/cloud/test_instance_power_control.py, cfme/tests/cloud_infra_common/test_power_control_rest.py, cfme/tests/distributed/test_appliance_replication.py, cfme/tests/infrastructure/test_vm_power_control.py
{{ pytest: -v --ui-coverage --long-running -k test_hard_reboot -k test_hard_reboot_unsupported -k  test_suspend -k test_unpause -k test_resume -k test_suspend_resume -k test_pause_unpause -k test_power_on_or_off_multiple --use-provider azure --use-provider openstack cfme/tests/cloud/test_instance_power_control.py }}
This PR is for automating the 'power_on_or_off_multiple" test case (which tests selecting multiple instances from the quadicons/collections view and performing a power action on them)
While writing this I ran into some code I needed to re-factor
1) I needed 2 occurences of the `testing_instance` fixture, so I pulled the logic for creating the instance out into its own method (`create_instance`) to re-use it twice. If I had to create more than 2 maybe I'd do something craftier …
=> [1LP][RFR] Add test for power_on_or_off_multiple, consolidate some common code

cfme/test_framework/appliance.py, cfme/test_framework/sprout/plugin.py, sprout/appliances/models.py
Opeshift appliances can be requested only when preconfigured=False and template_type = 'openshift_pod'. This PR is going to make pytest's sprout plugin to request such appliances
REQUIRES: https://github.com/ManageIQ/integration_tests/pull/6905
=> [1LP][RFR] openshift support in pytest sprout options

cfme/cloud/provider/gce.py
- `test_providers.py::test_provider_crud` failing due to region selection not available from 5.9.2.
- BZ-1560473
{{pytest: cfme/tests/cloud/test_providers.py::test_provider_crud --use-provider gce_central -v}}
=> [RFR][1LP] gce endpoints fix for 5.9.2

cfme/tests/test_modules_importable.py, cfme/utils/log.py
the additional loggin setup would fail in cases where the appliance module was imported incompletely
thisis now elevatd with a warning and will correctly resolved in a more detailed followup
additionally a test was created to demonstrate the detail issues of failing freestanding imports
=> [1LP][RFR] sort the import loop issues wrt logging setup

cfme/tests/cloud/test_providers.py, cfme/tests/configure/test_database_ui.py
1. Corrected timezone format, got incorrest one
2. Updated entities check as floating ips have only address
{{pytest: -k 'test_display_network_topology or test_configure_vmdb_last_start_time'}}
=> [1LP][RFR]Fix some ui tests

cfme/tests/infrastructure/test_snapshot.py
{{pytest: cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot --use-provider rhv41 -vv --long-running}}
=> [1LP][RFR] Wrapping test_verify_revert_snapshot with BZ1561618

scripts/ec2cleanup.py
Removes EC2 Cloudformations - ManageIQ EC2 Stack objects
- Added Condition 1 day old stack to avoid interrupting other tests.
- Added `sleep(5)` to avoid "Rate exceeded"-issue. which probably won't ever happen unless we are not deleting 10+ stacks at a time
- Generates reports like:
```
Date: 2018-03-09 13:52:06.076403
| Provider Key   | Stack Name   |
|----------------+--------------|
| ec2-west       | testlkhom19  |
| ec2-west       | testlkhom18  |
| ec2-west       | testlkhom17  |
| ec2-west       | testlkhom16  |
| ec2-west       | testlkhom15  |
| ec2-west       | testlkhom14  |
| ec2-west       | testlkhom13  |
| ec2-west       | testlkhom12  |
| ec2-west       | testlkhom11  |
| ec2-west       | testlkhom10  |
| ec2-west       | testlkhom9   | …
```
=> [1LP][RFR][NOTEST]adding stack removal for ec2

cfme/tests/infrastructure/test_providers.py
{{pytest: cfme/tests/infrastructure/test_providers.py::test_providers_discovery -vv --use-provider rhv41}}
=> [1LP][RFR] Wrapping test_providers_discovery with BZ

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
__Fixing__ VM verification because atm module-scoped test being parallelized to different appliances might provision duplicated VMs - EC2 allows duplicated names.
1. Verify that VM with such name exists on backend
2. Check it in CFME - refresh if it's not
This leads to the EC2 cleanup issue - we had duplicated Instances which we couldn't delete
{{pytest: cfme/tests/cloud_infra_common/test_custom_attributes_rest.py --long-running --use-provider ec2 --use-sprout --sprout-group downstream-59z  --sprout-appliance 5}}
=> [1LP][RFR]updating Vm verification

cfme/tests/infrastructure/test_vm_clone.py
__Adding negative tests__  for non-VMware providers
{{pytest: --long-running --use-provider complete cfme/tests/infrastructure/test_vm_clone.py}}
=> [1LP][RFR]adding negative test_vm_clone for other providers

cfme/common/provider_views.py
It's impossible to create ocp providers in downstream because of new widget which is absent.
This PR should fix that issue.
{{pytest: --use-provider ocp-env2 cfme/tests/containers/test_reload_button_provider.py}}
=> [1LP][RFR] fix ocp providers before_fill

cfme/infrastructure/provider/kubevirt.py
There's no kubevirt wrapanapi class to connect to, mgmt_class=None
Because PRT is only running downstream, this fix won't be tested by it.
When running `cfme.utils.providers.list_providers_by_class()` against an upstream appliance, the KubeVirt provider causes an AttributeError because of missing `type_name`.
Note I've set the mgmt_class to None here, since there is no wrapanapi class.
This doesn't actually get reached/called though, because the code path when calling `KubeVirt().mgmt` fails at the `default` endpoint lookup. The KubeVirt provider only has the virtualization endpoint, and its parent_provider has the default endpoint. We'll need to resolve this parent_provider default endpoint relationship when looking up default endpoints, but I don't want to include that scope here.
=> [1LP][RFR] Update KubeVirt with type_name and settings_key

cfme/tests/test_rest.py, cfme/utils/rest.py
So far only tests in test_rest.py were converted, other tests will follow in separate PRs.
{{pytest: -v -k test_delete_ cfme/tests/test_rest.py}}
=> [1LP][RFR] Unifies delete from details REST tests

cfme/tests/cloud/test_providers.py
Filtering is no longer supported on cloud_networks collection.
{{pytest: -v -k test_cloud_networks_query cfme/tests/cloud/test_providers.py}}
=> [RFR] Fix test_cloud_networks_query

cfme/tests/configure/test_rest_access_control.py
{{pytest: -v -k TestUsersViaREST cfme/tests/configure/test_rest_access_control.py}}
**PRT**
The ``AttributeError: catch_log_handler`` on 5.8 is not related to changes in this PR.
=> [1LP][RFR] Change user testing via REST following BZ fixes

cfme/tests/ansible/test_embedded_ansible_rest.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_custom_attributes_rest.py, cfme/tests/cloud_infra_common/test_rest_providers.py, cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/configure/test_tag.py, cfme/tests/configure/test_tag_category.py, cfme/tests/control/test_rest_control.py, cfme/tests/infrastructure/test_rest_templates.py, cfme/tests/infrastructure/test_vm_rest.py, cfme/tests/intelligence/test_chargeback.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_rest_services.py, cfme/tests/test_rest.py, cfme/utils/rest.py
{{pytest: -v --long-running -k test_delete_ cfme/tests/ansible/test_embedded_ansible_rest.py cfme/tests/cloud/test_providers.py cfme/tests/cloud_infra_common/test_custom_attributes_rest.py cfme/tests/cloud_infra_common/test_rest_providers.py cfme/tests/cloud_infra_common/test_snapshots_rest.py cfme/tests/configure/test_tag.py cfme/tests/configure/test_tag_category.py cfme/tests/control/test_rest_control.py cfme/tests/infrastructure/test_rest_templates.py cfme/tests/infrastructure/test_vm_rest.py cfme/tests/intelligence/test_chargeback.py cfme/tests/services/test_generic_service_catalogs.py cfme/tests/services/test_rest_services.py cfme/tests/test_rest.py}}
**PRT**
Some time out errors, nothing related to changes in this PR.
=> [1LP][RFR] Use delete helper functions in all REST tests

cfme/test_framework/appliance_log_collector.py
Prevent the hookwrapper from raising an AttributeError if there were no appliances available to the testrun and holder was empty.
=> [1LP][RFR] Check holder in appliance_log_collector

cfme/configure/access_control/__init__.py
After saving a role that has it's name updated, the accordion may not update to
show the role under the new name.
[BZ 1561698](https://bugzilla.redhat.com/show_bug.cgi?id=1561698) and fix for #5984 PRT failure
{{ pytest: -vvvv cfme/tests/configure/test_access_control.py -k 'role_crud or test_edit_default_roles' }}
=> [1LP][RFR] Disable view.is_display check at the end of Role.update. Fix for BZ156198

cfme/fixtures/service_fixtures.py, cfme/tests/ssui/test_ssui_dashboard.py, cfme/tests/ssui/test_ssui_myservice.py, cfme/tests/ssui/test_ssui_service_catalogs.py
Follow up PR for the changes in  https://github.com/ManageIQ/integration_tests/pull/6881
{{ pytest: -v --long-running --use-provider vsphere cfme/tests/ssui/test_ssui_dashboard.py cfme/tests/ssui/test_ssui_myservice.py cfme/tests/ssui/test_ssui_service_catalogs.py -k 'test_service_catalog_crud or test_myservice_crud or test_total_services' }}
=> [1LP][RFR] fixture name change

cfme/tests/cloud_infra_common/test_power_control_rest.py, cfme/tests/infrastructure/test_vm_power_control.py
some lint tweaks too
{{ pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py cfme/tests/infrastructure/test_vm_power_control.py -k 'test_reset_vm_rest or test_start_from_suspend'  --use-provider vsphere65-nested }}
=> [1LP][RFR] Fixture name change for ensure_vm_[running|suspended]

cfme/common/topology.py, cfme/tests/networks/test_sdn_topology.py
Add more providers to the test
And fix it ( it was only disabliing the items otherwise)
{{pytest: -v -q cfme/tests/networks/test_sdn_topology.py --use-provider=complete}}
=> [1LP][RFR] Fix sdn_add_topology

cfme/common/vm_views.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud_infra_common/test_vm_ownership.py
Two things happening here:
1. Fix for publish_to_template method in cfme.infrastructure.virtual_machines.Vm
2. Add template ownership test which also tests the above fix
For the first point, publish_to_template navigated to a wrong view, resulting in error when trying to fill a from that wasn't in that view. So instead of navigating to 'Details', I created a new view 'PublishVmView' in cfme.common.vm_views. This view has a form from 'BasicProvisionFormView' that was already implemented and contains all the things publish_to_template needs.
I then created new navigation step 'Publish' to enable navigation to my newly created view and added that to publish_to_template method.
For the second point, I wrote a very simple ownership test that just tries to set an ownership to a template. This …
=> [1LP][RFR] Fix publish_to_template; add ownership test

cfme/physical/physical_server.py, cfme/tests/physical_infrastructure/ui/test_physical_server_details_buttons.py
This PR is able to :
* Add new tests to cover all options in the Identify button are working on physical server details page.
Depends On: https://github.com/ManageIQ/integration_tests/pull/6898
=> [1LP][RFR] Add UI tests for Identify buttons in the physical server page

cfme/storage/manager.py, cfme/tests/storage/test_manager.py
- I found that in Jenkins run for `storage`. It first run `test_manager.py` in that `test_storage_manager_delete` causes deletion of `child providers`. Its continue with that brocken provider for other files causes `NoSuchElementException`. 
- best to clear that `CloudProvider`
{{pytest: cfme/tests/storage/ -v}}
=> [1LP][RFR] storage Manager provider cleanup

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_snapshot.py
This adds new simple test with snapshot and history toolbar button.
The test is for a polarion testcase. Creates snapshot, navigates to VM Details page, then uses the history toolbar button to go back to snapshots for that VM. Verifies the correct page is displayed.
I also corrected some pre-existing locators for the history toolbar button.
I had to define is_displayed for the InfraVmSnapshotView, I'm using title and in_infra_vms.
{{ pytest: -v --long-running cfme/tests/infrastructure/test_snapshot.py -k test_snapshot_history_btn }}
=> [1LP][RFR] New history button test with snapshot

scripts/data/coverage/coverage_hook.rb, scripts/data/coverage/coverage_merger.rb
- Now pick up cfme gems.
- HTML report creates tabs for providers on appliance.  These are automatically 
generated based on existence of provider gems on the appliance.
=> [1LP][RFR] Coverage data acquisition refinements.

cfme/utils/__init__.py
Intent
`deferred_verpick` is a good solution and it should be improved. `deferred_verpick` should select the appropriate version based on `appliance.version`. This PR is required for #6989.
=> [1LP][RFR] Improved deferred version pick

cfme/configure/access_control/__init__.py
Do a version check for specifying the column name in the RBAC Group checklist changed from "Name" to "Description".
{{ pytest: -v cfme/tests/configure/test_access_control.py -k 'test_edit_sequence_usergroups' }}
=> [1LP][RFR] Fix failure in test_edit_sequence_usergroups for 5.9.2

cfme/utils/trackerbot.py
ValueError exception when a template didn't get parsed correctly and we got an invalid year, month, day
The loose regex in `stream_matchers` is matching a datestamp like `20180404` as `month=20` and `day=18` instead of <year><month><day>.
=> [RFR] Update utils.trackerbot.parse_template, handle exception

cfme/tests/configure/test_access_control.py
The initial navigate_to() statement is wrapped in a 'with pytest.raises'
incorrectly (#6994) since the statement is expected to succeed. Added comments
to explain that the navigation should succeed on the initial attempt
with valid permissions
{{ pytest: -v cfme/tests/configure/test_access_control.py -k 'test_permission_edit' }}
=> [1LP][RFR] Remove 'with pytest.raises' statement in test_permission_edit

cfme/tests/storage/test_object_store_object.py
This was raising a TypeError when the collection returned `None` from `all()`, skip the test since we're missing a necessary item.
{{ pytest: --use-provider rhos11 -k test_object_add_remove_tag }}
=> [1LP][RFR] Catch empty object store collection

cfme/utils/appliance/__init__.py, scripts/clone_template.py, scripts/template_upload_scvmm.py, scripts/template_upload_vsphere.py
* SCVMM upload was timing out, increasing wait_for timeout and also adding retries
* Storing results of VMWare and SCVMM upload attempts and failing "loudly" by raising an Exception if upload fails for all providers so that we get a red ball on the jenkins template upload jobs.
* Checking if cloud-init is done on ec2 before trying to configure appliance
* Attaching a 5gb disk to GCE instances for vmdb (needed on 5.9+)
* Switched from using ```IPAppliance.configure_gce()``` to using the same logic in ```IPAppliance.configure()``` with a couple "if" statements handled by an `on_gce` kwarg. This fixes some issues we were seeing such as internal DB trying to be setup on an upstream template (the configure method already accounts for this).
**NOTE:** I know the last 2 bullet points are messy. …
=> [1LP][RFR] Fix template tester upload/template cloning issues across providers

cfme/tests/services/test_service_catalogs.py
`fill` method of Edit view does not change the description without this.
{{pytest: cfme/tests/services/test_service_catalogs.py::test_edit_catalog_after_deleting_provider --long-running -vv}}
=> [1LP][RFR] Fixing test_edit_catalog_after_deleting_provider

cfme/tests/cloud_infra_common/test_relationships.py
{{pytest: cfme/tests/cloud_infra_common/test_relationships.py --use-provider rhv41 -m "rhv1 or rhv2 or rhv3" -vv}}
=> [1LP][RFR] Marking test_relationships with RHV tiers

cfme/tests/ssui/test_ssui_myservice.py, cfme/tests/ssui/test_ssui_service_catalogs.py
PRT result is failed since I did not received an appliance -> SSH exception
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_service_start cfme/tests/ssui/test_ssui_service_catalogs.py::test_service_catalog_crud -m "rhv1 or rhv2 or rhv3" --long-running --use-provider rhv41}}
=> [1LP][RFR] Marking service test cases with RHV tier

cfme/tests/cloud_infra_common/test_cockpit_server.py
{{pytest: cfme/tests/cloud_infra_common/test_cockpit_server.py --use-provider rhv41 -m "rhv3" -vv}}
=> [1LP][RFR] Marikng test_cockpit_server_role with RHV tier

cfme/tests/cloud_infra_common/test_snapshots_rest.py
PRT: SSH exception
{{pytest: cfme/tests/cloud_infra_common/test_snapshots_rest.py::TestRESTSnapshots --long-running --use-provider rhv41 -m "rhv1 or rhv2 or rhv3"}}
=> [1LP][RFR] Marking TestRESTSnapshots with RHV tiers

scripts/tier_analyzer.py
This little __utility script__ is to be used by RHV-CFME integration team to compare
-  All the tests run for our provider with
- Tests that are marked with RHV tier 1, 2 or 3.
It's quite useful for us since from time to time we need to assign tiers to new tests. I am not sure if you're okay with having this in your repository. If not, we can store it somewhere else. But I thought this would be the most intuitive location.
PRT: There is SSH exception once again for downstream-58z
Example output:
************************************************************
There are 40 test cases not marked with "-m rhv1 or rhv2 or rhv3":
test_action_create_snapshot_and_delete_last[rhv_cfme_integration]
test_action_create_snapshots_and_delete_them[rhv_cfme_integration] …
=> [1LP][RFR] RHV tier analyzer

cfme/tests/infrastructure/test_host_drift_analysis.py
If you use 'Department (1)' as arg for `drift_analysis_view.drift_analysis.check_section_attribute_availability`, the underlying method `DriftComparison.check_section_attribute_availability` returns `IndexError`, as opposed to `AttributeError` that is actually handled. I am not sure if handling `IndexError` is correct there. But I believe that checking for 'Department' in that case is more correct. The reason is that you don't want to check how many changes are in field 'Department'. You want to check that none of the attributes of that field are not available.
PRT failure: SSH exception
{{pytest: cfme/tests/infrastructure/test_host_drift_analysis.py::test_host_drift_analysis --use-provider rhv41}}
=> [1LP][RFR] Fix test_host_drift_analysis

cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_custom_attributes_rest.py, cfme/tests/cloud_infra_common/test_rest_providers.py, cfme/tests/configure/test_rest_access_control.py, cfme/tests/configure/test_tag.py, cfme/tests/configure/test_tag_category.py, cfme/tests/control/test_rest_control.py, cfme/tests/infrastructure/test_rest_templates.py, cfme/tests/infrastructure/test_vm_rest.py, cfme/tests/intelligence/test_chargeback.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_rest_services.py, cfme/tests/test_rest.py, cfme/utils/rest.py
{{pytest: -v --long-running -k test_delete_ cfme/tests/cloud/test_providers.py cfme/tests/cloud_infra_common/test_custom_attributes_rest.py cfme/tests/cloud_infra_common/test_rest_providers.py cfme/tests/configure/test_rest_access_control.py cfme/tests/configure/test_tag.py cfme/tests/configure/test_tag_category.py cfme/tests/control/test_rest_control.py cfme/tests/infrastructure/test_rest_templates.py cfme/tests/infrastructure/test_vm_rest.py cfme/tests/intelligence/test_chargeback.py cfme/tests/services/test_generic_service_catalogs.py cfme/tests/services/test_rest_services.py cfme/tests/test_rest.py}}
**PRT**
Timeout error, not related to changes in this PR.
=> [1LP][RFR] delete_resources_from_collection - collection parameter optional

cfme/tests/intelligence/reports/test_validate_chargeback_report.py
{{pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider gce_central}}
The tests got skipped for GCE on 58 and 59, like expected, but there was an error in both the runs.
(/cfme_tests_te/fixtures/browser.py:40)
sssException AttributeError: AttributeError('catch_log_handler',) in <generator object pytest_runtest_setup at 0x7f355ac0eaf0> ignored
Exception AttributeError: AttributeError('catch_log_handler',) in <generator object pytest_runtest_setup at 0x7f355aca7d70> ignored
Exception AttributeError: AttributeError('catch_log_handler',) in <generator object pytest_runtest_setup at 0x7f355a914780> ignored
ss
==================================== ERRORS ====================================
ERROR at teardown of …
=> [1LP][RFR] Skip chargeback tests for gce for 58

cfme/tests/integration/test_cfme_auth.py
I am seeing auth test failures where a test is logged in as a non-admin user and thus cannot find toolbar dropdown menus.
This adds finalizers that will login_admin during teardown.
{{ pytest: -k 'test_login_evm_group or test_login_retrieve_group' --long-running }}
=> [RFR] Add finalizers to login_admin to auth teardown

cfme/infrastructure/provider/rhevm.py
was forcing appliance version check on providers.get_crud() which breaks scripts that don't actually need an appliance to interact with providers.
Moved ca_cert and tls_verify picks into the view_value_mapping
Local testing on 5.7.4.3 and 5.9.2.2 was good.
Run 23135: 
* 58z did not receive appliance from sprout
* 59z some smoke test failures, on scvmm providers, not related.         
Restarted with only rhv41 provider to get cleaner results that are all relevant to changes.
{{ pytest: -k test_infra_provider_crud --use-provider rhv41 }}
=> [1LP][RFR] Remove version check from RHEVMProvider constructor

cfme/tests/test_appliance.py
/etc/rhsm/ca/candlepin-stage.pem appears to no longer be present in the OS, I am guessing due to recent RHEL changes or other repos we rely upon
We'll no longer check for this cert, but also we will verify that we trust the RHN subscription site's cert with a curl test.
{{ pytest: cfme/tests/test_appliance.py -k test_certificates_present --long-running }}
=> [1LP][RFR] Fix certs test

cfme/ansible/credentials.py, cfme/tests/ansible/test_embedded_ansible_basic.py
Purpose
CFME 5.9.2.1 has added new types of ansible credentials: vault and red hat virtualization.
{{pytest: -v -k test_embedded_ansible_credential_crud --long-running}}
=> [1LP][RFR] Added new ansible credentials types

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
This is pretty much the same as #7054 
PRT outcome since very much unrelated to the content of this PR.
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py::test_drift_analysis --long-running -vv}}
=> [RFR] Fixing test_drift_analysis

requirements/frozen.txt
* boto is frozen in wrapanapi, no need for it in here as it causes conflicts
* cryptography 1.9 is failing to compile for me recently in Fedora 27, incompatible with latest openssl-devel packages perhaps?
{{ pytest: cfme/scripting/tests/test_quickstart.py }}
=> [RFR] Bump cryptography, get rid of boto

cfme/base/__init__.py, cfme/tests/configure/test_ntp_server.py, cfme/tests/control/test_alerts.py, cfme/utils/appliance/__init__.py, cfme/utils/perf.py
Update appliance `get_yaml_config`/`set_yaml_config` methods, rewrite to be an `advanced_settings` property with a setter.
Slight enhancement to appliance's yaml configuration methods, a property is a better means to represent the appliance configuration.
Updating all uses of the old methods to instead use correct property+setter syntax.
{{ pytest: cfme/tests/configure/test_ntp_server.py cfme/tests/control/test_alerts.py cfme/tests/configure/test_server_roles.py --long-running -v}}
=> [1LP][RFR] Update appliance get/set_yaml_config to property

cfme/tests/infrastructure/test_vm_reconfigure.py
PRT fail is caused by current problem with FW that occurs when using @pytest.mark.meta for defining blockers.
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_disk_cold -vv --long-running}}
=> [1LP][RFR] Wrapping test_vm_reconfig_add_remove_disk_cold with GH6996

cfme/networks/balancer.py, cfme/networks/cloud_network.py, cfme/networks/floating_ips.py, cfme/networks/network_port.py, cfme/networks/network_router.py, cfme/networks/security_group.py, cfme/networks/subnet.py, cfme/tests/networks/test_sdn_inventory_collection.py
Automate the collections SDN
Those new tests will compare the items gathered by the provider API with the ones from CFME.
failed only on 5.8 because of the SSL error. 
{{pytest: -v -q cfme/tests/networks/test_sdn_inventory_collection.py --use-provider=complete}}
=> [1LP][RFR] Update sdn collections

cfme/tests/cloud_infra_common/test_events.py
{{pytest: --use-provider=gce_central cfme/tests/cloud_infra_common/test_events.py}}
=> [RFR] gce doesn't support vms with underscore in name

cfme/tests/services/test_different_dialogs_in_catalogs.py
Adding new BZ wrapper and removing the old one since the original bug is closed.
PRT fail: SSH exception
{{pytest: cfme/tests/services/test_different_dialogs_in_catalogs.py::test_tagdialog_catalog_item --long-running}}
=> [RFR] Wrapping test_tagdialog_catalog_item with BZ1567108

cfme/modeling/tests/test_collections.py, cfme/utils/appliance/__init__.py
collections property is necessary for DummyAppliance until we get rid of provider object instantiation during test session setup. So, this PR adds such property for a while.
=> [1LP][RFR] added collections to DummyAppliance
