cfme/tests/automate/test_service_dialog.py
cfme/tests/configure/test_zones.py

{{ pytest: -v cfme/tests/configure/test_zones.py -k 'test_zone_add_dupe' }}
**What was the issue?**
Wrong flash!

[1LP][RFR] Corrected zone error flash for versions

---

fixtures/artifactor_plugin.py

Need thi sfor some debugging on sauce

[RFR] Log message addition

---

cfme/tests/control/test_alerts.py

Purpose
Removed module "uncollectif" due to fixed BZs.

[1LP][RFR] Removed uncollectif in test_alerts.py

---

cfme/tests/configure/test_visual_infra.py

Added new pages converted to collection in parametrization and made changes in the test case to accommodate it.
{{pytest: -v -k 'test_infra_grid_page_per_item or test_infra_tile_page_per_item or test_infra_list_page_per_item'}}

[1LP][RFR] Adding pages converted to collection in parametrization

---

cfme/common/physical_server_views.py

Add the views for testing the physical server provider functions of the Lenovo Provider for ManageIQ
Replaces  https://github.com/ManageIQ/integration_tests/pull/5856

[1LP][RFR] Adds physical server views

---

cfme/tests/test_db_migrate.py
cfme/utils/appliance/__init__.py

New db migrate replication tests.
{{pytest: -v -k "test_db_migrate_replication"}}

[1LP][RFR] new db migrate and replication checks test

---

cfme/tests/intelligence/test_dashboard.py

Purpose
The test cannnot be executed because of [BZ1533792](https://bugzilla.redhat.com/show_bug.cgi?id=1533792)

[1LP][RFR] Added blocker for test_widgets_operation

---

cfme/utils/appliance/implementations/rest.py
cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py

[1LP][RFR] Context names + import fixing

---

cfme/tests/infrastructure/test_pxe_provisioning.py

Fix to fit template helper function

[RFR]PXE customization template fix

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

__Fixing__ test_operations_vm_on. The previous version did not take into account a situation where there might be:
- Orphaned VMs that don't have a host anymore
- Archived VMs that don't have a datastore anymore
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_operations_vm_on -vv}}

[1LP][WIPTEST] Fixing test_operations_vm_on for archived/orphaned VMs

---

cfme/tests/configure/test_workers.py
cfme/tests/infrastructure/test_tenant_quota.py

{{pytest: -vvv -k 'test_tenant_quota or test_restart_workers' --long-running}}

[1LP][RFR]More exception fix + bz block

---

cfme/tests/infrastructure/test_host_analysis.py

{{pytest: -vvv -k cfme/tests/infrastructure/test_host_analysis.py --use-provider complete --long-running
}}

[1LP][RFR] Update assertion check for host type

---

cfme/configure/configuration/server_settings.py

- Problem in WMware WebMKS console update
- small change in WebMKS_SDK.zip extraction 
{{py.test: -vv cfme/tests/configure/test_vmware_console_settings.py}}

[1LP][RFR] fix test_vmware_console_support

---

cfme/services/myservice/ui.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k test_service_ansible_playbook_pass_extra_vars --long-running}}

[1LP][RFR] Fixed test_service_ansible_playbook_pass_extra_vars

---

cfme/tests/intelligence/test_dashboard.py

Purpose
This test never worked. After closing [BZ1316134](https://bugzilla.redhat.com/show_bug.cgi?id=1316134) another one was opened [BZ1485637](https://bugzilla.redhat.com/show_bug.cgi?id=1485637). But it does not fix the problem, so this will always fail.

[1LP][RFR][NOTEST] Removed test_drag_and_drop_widget_to_the_bottom_of_another_column

---

cfme/utils/browser.py

This PR fixes issue when FF doesn't start after quit. 
The issue is in cached profile which is removed during browser quit. As a result selenium raises error on next attempt to start browser.

[1LP][RFR] firefox profile cache invalidation fix

---

cfme/tests/cloud_infra_common/test_genealogy.py

Fixed the filter to not use a lambda

[RFR] Fixed the filter to not use a lambda

---

cfme/infrastructure/resource_pool.py

- fix test `test_delete_resource_pool_appear_after_refresh`
- Removed table for entities as `BaseEntitiesView` going to work on page
- Fixed All page `is_displayed()`
- Removed view resets
- Improve `exist()` method 
{{pytest: cfme/tests/infrastructure/test_delete_infra_object.py -k 'test_delete_resource_pool_appear_after_refresh' --use-provider vsphere55 -v}}

[1LP][RFR] fix: test_delete_resource_pool_appear_after_refresh 

---

widgetastic_manageiq/expression_editor.py

{{pytest: -k test_modify_condition_expression -vvv --long-running}}

[1LP][RFR] Fix expression buttons in expression_editor

---

cfme/tests/configure/test_visual_cloud.py

Removing support for 5.7 in a test case.
{{pytest: -v -k 'test_cloud_start_page'}}

[1LP][RFR] Removing support for 5.7

---

cfme/utils/pytest_shortcuts.py
cfme/utils/tests/test_pytest_shortcuts.py

the code before was not quite working correct, unittests to the rescue

[RFR][1LP] unittest fixture_filter and fix type related bugs

---

cfme/tests/configure/test_visual_cloud.py

Introducing parametrization in page per item related test case to test complete options available on the setting page.
{{pytest: -v -k 'test_cloud_grid_page_per_item or test_cloud_tile_page_per_item or test_cloud_list_page_per_item'}}

[1LP][RFR]Introducing parametrization in page per item test cases.

---

cfme/cloud/instance/__init__.py

Update instance navigate to 'All' resetter, as current doesn't clear simple search if there is any
{{pytest: -vvv cfme/tests/configure/test_default_views_cloud.py}}

[1LP][RFR] Update search clearance in resetter

---

cfme/control/explorer/actions.py
cfme/control/explorer/policies.py

{{pytest: --use-provider=scvmm cfme/tests/cloud_infra_common/test_events.py}}

[1LP][RFR] fix test_events which often fails on assert view.is_displayed

---

cfme/tests/test_utilization_metrics.py

[1LP][RFR] Remove store usage

---

cfme/tests/cloud_infra_common/test_vm_ownership.py

This is a refactor of existing ownership tests. The point of this PR is to remove the dependency on a vm set in the cfme_data.yaml.
Before, the ownership tests required a pre-provisioned VM with name set in the cfme_data file in every provider we wanted to test, like so:
"ownership_vm: <name_of_the_vm>"
This was cumbersome, the data repeated across the cfme_data.yaml file and it caused problems when trying to run PRT or automation, because there was no entry "ownership_vm" in the cfme_data.yaml.
Now, the module works with a yield fixture which provisions the VM beforehand, as seen in many other tests that are currently running in automation.
{{ pytest: -v --long-running --use-provider vsphere65-nested cfme/tests/cloud_infra_common/test_vm_ownership.py }}

[1LP][RFR] Ownership: Remove dependency on existing vm

---

fixtures/artifactor_plugin.py

Test it out by executing the line in ipython with conf.credentials imported.

[RFR] Do not sanitize None

---

cfme/tests/cloud_infra_common/test_tag_visibility.py

Fixed an error in the provider selection

[1LP][RFR] Fixed an error in the provider selection

---

widgetastic_manageiq/__init__.py

1. removed surf_pages since cfme doesn't keep selection on different pages now
2. fixed indention mistake which caused apply function to use only first condition

[1LP][RFR] entity.apply function fix

---

cfme/utils/appliance/implementations/ui.py

Dismiss notifications because they cause us issues

[RFR] Dismiss notifications

---

cfme/tests/networks/test_sdn_balancers.py

{{pytest: cfme/tests/networks/test_sdn_balancers.py --use-provider azure}}

[1LP][RFR] Fix balancers type error

---

cfme/scripting/setup_env.py

FIX: UnboundLocalError: local variable 'request_id' referenced before assignment

[1LP][RFR][NOTEST] Fix using existing pool

---

cfme/tests/integration/test_aws_iam_auth_and_roles.py

These BZ's weren't tagged for the specific streams, so I'm forcing the skip.

[1LP][RFR] Update BZ blockers for test_aws_iam_auth_and_roles

---

requirements/frozen.txt

{{pytest: -v -k test_query_simple_collections cfme/tests/test_rest.py}}

[1LP][RFR] Use v0.4.0 of manageiq-client

---

cfme/tests/ssui/test_ssui_myservice.py

__Extending__ Support for SSUI Console Test for 5.9, previously it was limited by uncollect if version was above 5.9. 
Might fail for RHV provider until #6510  is merged.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider vsphere6-nested --use-provider rhv41}}

[1LP][RFR] Adding support for cmfe5.9 ssui console tests rhv/vmware

---

cfme/tests/test_db_restore.py
cfme/utils/appliance/db.py

PR to fix broken automation test, a future PR should follow to re-factor the test into fixtures and functions where possible, removing setup from the test itself.

[1LP][RFR] Fix to broken test_db_restore

---

cfme/common/__init__.py
cfme/control/explorer/alert_profiles.py
cfme/infrastructure/virtual_machines.py
widgetastic_manageiq/__init__.py

Making updates to wt.patternfly.CheckableBootstrapTreeview, made this quick change while I was working on the area.

[1LP][RFR] Replace CheckableManageIQTree with CheckableBootstrapTreeview

---

cfme/common/vm.py

{{pytest: --use-provider=azure --long-running -k test_action_tag cfme/tests/control/test_actions.py}}

[1LP][RFR] trying to fix error when Instance Details View isn't displayed on time

---

cfme/tests/configure/test_landing_page.py

Adding test case to check the show at login page for admin user.
{{pytest: cfme/tests/configure/test_landing_page.py -v }}

[1LP][RFR] Adding test case to check the show at login for admin.

---

cfme/tests/cloud_infra_common/test_rest_providers.py

{{pytest: -v -k test_provider_delete_from_ cfme/tests/cloud_infra_common/test_rest_providers.py}}

[1LP][RFR] Check response after BZ1525498 is fixed

---

cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/services/test_rest_services.py

Fixed catalog name type which had been missed

[1LP][RFR] Fixed catalog name type which had been missed

---

cfme/cloud/instance/image.py
cfme/fixtures/tag.py
cfme/tests/cloud_infra_common/test_tag_objects.py

{{pytest:: -vvv cfme/tests/cloud_infra_common/test_tag_objects.py}}

[1LP][RFR]Update cloud, infra tag selection

---

requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt

{{pytest: cfme/tests/control/test_compliance.py -v --use-provider vsphere6-nested }}

[1LP][RFR] Bump the WT.PF version to ifx an issue

---

cfme/tests/services/test_provision_stack.py

IDs had changed
{{pytest: -k test_provision_stack --long-running --use-provider complete}}

[1LP][RFR] Fixed provision stack key

---

cfme/containers/container.py
cfme/containers/image.py
cfme/containers/image_registry.py
cfme/containers/node.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/template.py
cfme/containers/volume.py

{{ pytest: cfme/tests/containers/test_relationships.py --use-provider cm-env2 }}
Addresses issue #6540
Use surf_pages instead in case that the search bar is not visible.

[1LP][RFR] Addresses issue#6540

---

cfme/infrastructure/virtual_machines.py

Implementing changes to resolve test case failure due to change in title on template all view page.
{{pytest: -v -k 'test_infra_provider_relationships'}}

[1LP][RFR]Implementing fix for Template related test case.

---

cfme/scripting/setup_env.py

Adds option for remote worker in remote region

[1LP][RFR][NOTEST] Add worker appliance to remote region option.

---

fixtures/xunit_tools.py

* reworked duplicates.log generation
* Polarion testcase name are now generated only once so it's bit more efficient
* use of ``item.location`` instead of ``item.nodeid``

[1LP][RFR] xunit_tools enhancements

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

PRT results:
58: All tests passed
59: All tests passed
The tests for default rates are failing because the data for the group, source, metric columns in the chargeback_rate_details table is missing for default rates.
I have modified the DB query so that we filter on chargeback_rate_details.description and not 
chargeback_rate_details.metric like we did before.

[1LP][RFR] Chargeback : Fix Default rate tests

---

cfme/infrastructure/host.py
cfme/tests/infrastructure/test_host.py

{{pytest: -v -k cfme/tests/infrastructure/test_host.py}}

[1LP][RFR] Add vsphere hosts discover test

---

cfme/fixtures/vm_console.py
cfme/test_framework/pytest_plugin.py
cfme/tests/cloud_infra_common/test_html5_vm_console.py
cfme/tests/infrastructure/test_webmks_console.py
cfme/tests/ssui/test_ssui_myservice.py

__Fixing__ VM Console Fixtures by de-duplicating code from WebMKS,HTML5,SSUI VM Console tests and aggregating it as fixture.
{{pytest: -v --long-running cfme/tests/ssui/test_ssui_myservice.py -k 'test_vm_console' --use-provider vsphere6-nested}}

[1LP][RFR] Moving VM Console fixture to separate file

---

cfme/utils/appliance/implementations/ui.py

{{pytest: cfme/tests/configure/test_access_control.py -v --long-running}}

[RFR] Firefox focus fix

---

scripts/data/openshift/patches/main_template/add_common_service.patch
scripts/openshift/add_remove_persistent_volumes.sh
scripts/openshift/create_ip_aliases.sh
scripts/template_upload_all.py
scripts/template_upload_openshift.py

After playing around with openshift api and updating wrapanapi, I came to conclusion that I have to prepare and upload templates in upload scripts. This is only good way to deal with templates atm.

[1LP][RFR] changing openshift template upload

---

cfme/base/__init__.py
cfme/base/login.py
cfme/base/ui.py

Will be using this for auth and RBAC test automation.
@LandoCalrizzian @izapolsk check it out :)

[1LP][RFR] Add BaseLoggedInView.current_groupname

---

cfme/tests/services/test_rest_services.py
cfme/utils/rest.py

* add ``query_resource_attributes`` for testing resource attributes/subcollections access
* add test for service (more tests will follow in other PRs once this one is merged)
{{pytest: -v --long-running -k test_query_service_attributes cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Test resource attributes/subcollections

---

cfme/common/__init__.py
cfme/configure/tasks.py
cfme/containers/image.py
cfme/containers/provider/__init__.py
cfme/exceptions.py
cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py

In this PR I automated test id 9497 & 10065 from Polarion.
Smart State analysis functionality check for multiple container image.
Added functions & modifications to framework , some of them update to use widgetastic instead of web-ui.
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py -v --use-provider cm-env2 }}

[1LP][RFR] Smartstate analysis for multiple Containers Images

---

cfme/tests/control/test_bugs.py

{{pytest: -v -k test_control_identical_descriptions}}

[1LP][RFR] Fixed test_control_identical_descriptions

---

cfme/configure/access_control/__init__.py
cfme/fixtures/tag.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/configure/test_access_control.py

Checknode, Unchecknode named tuple were added to widget. Fix tests
{{pytest:  cfme/tests/cloud/test_provisioning.py cfme/tests/configure/test_access_control.py cfme/tests/cloud_infra_common/test_tag_visibility.py -k 'test_tag_vis_vm or test_tag or test_group_crud_with_tag or test_cloud_provision_with_tag' --long-running}}

[RFR]Update path to Checknode type

---

cfme/control/explorer/alert_profiles.py

{{pytest: -v -k test_alert_profile_assigning --long-running}}

[1LP][RFR] Fixed test_alert_profile_assigning

---

cfme/tests/test_db_migrate.py

Small fix to migration tests.
{{pytest: cfme/tests/test_db_migrate.py -k test_db_migrate_replication}}

[1LP][RFR] Fix to test_db_migrate_replication

---

cfme/scripting/appliance.py

New Script for restoring and migrating databases. Should help people verify the occasional bz and give the option for additional testing. Also updated some parts of other scripts to make use of the migration functions in PR#6349

[1LP][RFR] New db migrate script

---

cfme/tests/test_rest.py

* fixed blocker (GH issue fixed but still open)
* removed unnecessary uncolectifs
{{pytest: -v -k test_select_attributes cfme/tests/test_rest.py}}

[1LP][RFR] Fix test_select_attributes on 5.8

---

cfme/utils/appliance/implementations/ui.py

Hack to help with the FF issue

[1LP][RFR] Glitch master hack

---

cfme/services/service_catalogs/ui.py
cfme/tests/services/test_different_dialogs_in_catalogs.py

{{pytest: -v -k test_tagdialog_catalog_item --long-running --use-provider vsphere6-nested}}

[1LP][RFR] Fixed test_tagdialog_catalog_item

---

cfme/tests/services/test_rest_services.py

{{pytest: -v --long-running -k TestServiceOrderCart cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Fix REST cart tests

---

cfme/common/provider_views.py
cfme/networks/provider/__init__.py
cfme/networks/provider/nuage.py
cfme/networks/views.py
cfme/tests/networks/test_network_providers.py
conf/cfme_data.yaml.template
conf/credentials.yaml.template

With this commit we implement the very first pair of tests for Nuage provider. First test just opens up a form for creating new Nuage provider, clicks "Cancel" and then asserts specific popup content. Second test inputs valid credentials, asserts correct inventory (using wrapanpi) and then deletes provider.
Depends on: https://github.com/ManageIQ/wrapanapi/pull/208

[RFR] First integration tests for Nuage provider

---

docs/getting_started.rst

__Extending__ Getting Started page in docs. This kept me thinking for a little while so I might as well ease the struggle for others in the future.

[RFR][1LP][DOC] Adding warning to Getting Started doc page

---

data/orchestration/aws_vm_template.yaml

__Extending__ templates repo for AWS. yaml format is also available

[1LP][RFR][NOTEST] Adding yaml template for aws

---

cfme/tests/control/test_actions.py

{{pytest: -v -k test_action_prevent_host_ssa --long-running}}

[1LP][RFR] Added test test_action_prevent_host_ssa

---

cfme/ansible/credentials.py
cfme/ansible/repositories.py
cfme/tests/ansible/test_embedded_ansible_basic.py
widgetastic_manageiq/__init__.py

{{pytest: -v -k test_embedded_ansible_credential_crud --long-running}}

[1LP][RFR] Ansible credentials refactoring

---

cfme/physical/physical_server.py
cfme/tests/physical_infrastructure/test_physical_server.py

This PR implements the physical server integration tests.
Depends on view changes made in ManageIQ/integration_tests/pull/5968

[1LP][RFR] Physical server tests

---

cfme/tests/infrastructure/test_rest_automation_request.py

and /api/automation_requests
{{pytest: -v -k test_query_request_attributes cfme/tests/infrastructure/test_rest_automation_request.py}}

[1LP][RFR] Test resource attributes/subcollections of /api/requests

---

cfme/ansible/repositories.py

[RFR] Fixed ansible repositories

---

cfme/tests/configure/test_access_control.py

{{ pytest: cfme/tests/configure/test_access_control.py -k test_copied_user_password_inheritance}}
Based on RHCF3-12621

[1LP][RFR] New test_copied_user_password_inheritance test

---

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py

{{pytest: -v --long-running -k services cfme/tests/cloud_infra_common/test_custom_attributes_rest.py}}

[1LP][RFR] Add services custom attributes tests

---

cfme/tests/cloud/test_provisioning.py

`boot_disk_size` used in REST request should be like '10.GB', '50.GB'
More details are in 
https://bugzilla.redhat.com/show_bug.cgi?id=1543804
Currently PRT won't pass due to another BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1544547 which add random failure - depending on the Region that will be used
+ minor changes into dict filling to pass lint
{{pytest: -k "test_provision_from_template_using_rest[gce_central]"  --long-running  --use-provider gce_central}}

[1LP][RFR]changing  GCE boot_disk_size format used in REST

---

cfme/test_framework/browser_isolation.py
cfme/test_framework/pytest_plugin.py

[1LP][RFR] Ability to isolate browser sessions

---

cfme/tests/cloud/test_provisioning.py
cfme/tests/services/test_cloud_service_catalogs.py
requirements/frozen.txt

Needs Yaml update 1st - MR - 441
{{pytest: -v --long-running  cfme/tests/cloud/test_provisioning.py cfme/tests/services/test_cloud_service_catalogs.py  --use-provider azure --use-provider gce_central}}

[1LP][RFR] Aligning cloud provision attributes

---

cfme/common/__init__.py

Fix get_tags after get_details changes
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/configure/test_access_control.py -k 'test_tag or test_tagvis_user' --long-running}}

[1LP][RFR]Check for smart_management attr

---

cfme/tests/infrastructure/test_vm_migrate.py

{{pytest: -v -k test_migrate_vm --use-provider rhv41}}

[1LP][RFR] Fixed test_migrate_vm

---

cfme/configure/settings.py
cfme/tests/configure/test_timeprofile.py
setup.py

Converting Timeprofile to collection and making changes in the test case related to it.
{{pytest: cfme/tests/configure/test_timeprofile.py -v }}

[1LP][RFR] Timeprofile collection conversion and Timeprofile fix

---

cfme/tests/services/test_service_catalogs.py

__Updating test__ test_edit_catalog_after_deleting_provider. The behaviour during editing Catalog Item after deleting the original provider from inventory has changed in 5.9.0.21. You can read the details [here](https://bugzilla.redhat.com/show_bug.cgi?id=1544487#c4) and in two following comments.
I know that you don't really like branching of tests in the test code itself. But I think this does not really belong to the code of `CatalogItem` class. That code is supposed to be generally valid while this is a very specific situation. 
Also, I was trying to do:
> with error.expected("required"):
>     catalog_item.update(changes)
This did not work since `CatalogItem.update` [checks](https://github.com/ManageIQ/integration_tests/blob/73f4b629884265d36c4bae5c5879fd75aa4d41b9/cfme/services/catal …

[1LP][RFR] Updating test_edit_catalog_after_deleting_provider

---

cfme/tests/cloud_infra_common/test_rest_providers.py

{{pytest: -v -k test_query_provider_attributes cfme/tests/cloud_infra_common/test_rest_providers.py}}

[1LP][RFR] Add test for querying provider attributes

---

cfme/test_framework/appliance.py
cfme/utils/appliance/__init__.py
cfme/utils/dockerbot/pytestbase/setup.sh

Fixes PR tester after recent base_url changes, since appliances 'hostname' must have a string.

[1LP][WIPTEST] Enhancements to dockerbot setup.sh for easier debugging

---

cfme/services/service_catalogs/ui.py

Added additional check for submiting orver view
{{pytest: cfme/tests/services/test_provision_stack.py --long-running}}
PRT: Failures are not caused by these changes

[1LP][RFR] Check for order view

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Added missed navigation to details page
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_drift_analysis --long-running}}

[RFR]Fix navigation for drift analysis

---

cfme/tests/cloud/test_providers.py

Check none value for key pair in provision form
{{pytest: -vvv -k test_select_key_pair_none_while_provisioning}}
https://polarion.engineering.redhat.com/polarion/#/project/RHCF3/workitem?id=RHCF3-12722

[RFR]Check none value for key pair

---

cfme/tests/containers/test_static_custom_attributes.py

Stability effort for CM-QE automation tests. 
{{ pytest: cfme/tests/containers/test_static_custom_attributes.py --use-provider cm-env2 }}

[RFR] Fix Failing tests cfme.tests.containers.test_static_custom_attributes.py

---

cfme/tests/services/test_myservice.py

{{pytest: cfme/tests/services/test_myservice.py -v -k 'test_service_link' --long-running --use-provider vsphere55}}

[1LP][RFR] Fixed relationship click

---

cfme/tests/services/test_add_remove_vm_to_service.py

{{pytest: -v cfme/tests/services/test_add_remove_vm_to_service.py -k 'test_add_vm_to_service' --long-running --use-provider vsphere55}}
**What was the issue?**
VM name `auto_test_services` hardcoded in earlier code which was requiring VM to be present on every infra provider, I am creating and deleting new VM instead of that.
@sshveta: What say?

[1LP][RFR] Fixed test_add_vm_to_service and removed vm hardcoding

---

cfme/common/vm.py
cfme/tests/automate/test_vmware_methods.py
cfme/tests/cloud_infra_common/test_retirement.py
cfme/tests/infrastructure/test_provisioning_dialog.py

{{pytest: -k 'test_retirement_now or test_disk_format_select or test_vmware_vimapi_hotadd_disk' --long-running}}

[1LP][RFR] VM summary fix for some tests

---

cfme/configure/configuration/server_settings.py

- refresh browser required
{{pytest: cfme/tests/configure/test_vmware_console_settings.py -v}}

[1LP][RFR] VMware WebMKS test fix

---

cfme/tests/intelligence/reports/test_metering_report.py

Metering Reports have been introduced in 59.
PRT results:
59 - All the tests passed.
58 - Tests skipped, like expected.

[1LP][RFR] Automate Metering report

---

cfme/tests/control/test_rest_control.py

\+ minor enhancements and cleanups
{{pytest: -v cfme/tests/control/test_rest_control.py}}

[1LP][RFR] Add test checking expected control attributes

---

cfme/tests/infrastructure/test_vm_rest.py

\+ minor fixture enhancement
{{pytest: -v cfme/tests/infrastructure/test_vm_rest.py}}

[1LP][RFR] Add test checking expected VM attributes

---

cfme/tests/services/test_rest_services.py
cfme/utils/rest.py

{{pytest: -v --long-running -k test_query_ cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Add query attributes tests for services collections

---

cfme/scripting/quickstart.py

__Adding Ubuntu__ to quickstart.

[1LP][RFR] Added Ubuntu to quickstart script

---

cfme/fixtures/service_fixtures.py
cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py
widgetastic_manageiq/__init__.py

{{pytest: -v  --long-running --use-provider azure --use-provider rhos11 cfme/tests/ssui/test_ssui_myservice.py }}
====Couple of fixes====
1) Fixed catalog item for cloud providers and some views in myservice page .
2) Also marked tests with a BZ .
3) Corrected some views
4) Added wait_for in some methods because of long loading time

[1LP][RFR] Fixed catalog item for cloud providers

---

requirements/frozen.txt

Bump wrapanapi to pick up https://github.com/ManageIQ/wrapanapi/pull/216

[RFR] Bump wrapanapi

---

cfme/rest/gen_data.py
cfme/tests/configure/test_rest_access_control.py

\+ enhancements to existing tests
\+ new test ``test_create_uppercase_user`` for bug discovered along the way
{{pytest: -v cfme/tests/configure/test_rest_access_control.py}}

[1LP][RFR] Add new tests for querying access control attributes

---

cfme/ansible/credentials.py
cfme/tests/ansible/test_embedded_ansible_basic.py

{{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -v -k test_embedded_ansible_credential_crud[OpenStack] --long-run}}

[1LP][RFR] New Openstack Ansible Embedded credential

---

requirements/frozen.txt
requirements/frozen_docs.txt

[RFR] Updating PF to 0.20.4

---

cfme/infrastructure/networking.py
cfme/tests/webui/test_splitter.py

As a first stab at doing a collections conversion, convert InfraNetwork to collections.

[RFR] Convert InfraNetwork to Collections

---

cfme/fixtures/cli.py
cfme/tests/cli/test_appliance_cli.py
cfme/tests/cli/test_appliance_console.py
cfme/tests/cli/test_appliance_update.py
cfme/utils/appliance/__init__.py

Added additional testing for appliance_console and appliance_console_cli aimed at HA configurations. Cleaned up older tests to only run on the current build version, removed old support. Also cleaned up collections and skipping tests.

[1LP][RFR] New HA test and clean up/fixed old tests for ap+cli

---

cfme/dashboard.py

{{pytest: -v -k fix_test_widgets_operation}}

[1LP][RFR] Fixed test_widgets_operation

---

cfme/tests/infrastructure/test_ssa_vddk.py

===========
test different vddk version against different VMware provider versions
{{pytest: cfme/tests/infrastructure/test_ssa_vddk.py --long-running --use-provider complete}}

[1LP][RFR] Test vddk version(ssa)

---

cfme/networks/floating_ips.py
cfme/networks/views.py
cfme/tests/cloud/test_providers.py
setup.py

{{pytest: -vvv -k 'test_display_network_topology or test_cloud_names_grid_floating_ips'}}

[1LP][RFR] Test Floating ips names

---

cfme/infrastructure/provider/__init__.py

fix_provider_summary
change view to parametrized view
{{pytest: -v -k test_timeline_events --use-provider=vsphere6-nested}}

[1LP][RFR] fix_provider_summary

---

cfme/containers/provider/__init__.py

Fixing ContainersProvider num_container, adding a query that supports changes on CFME 5.9 DB.
The container_definitions table doesn't exist anymore on CFME 5.9,
The data on this table merged into containers table.
{{pytest: cfme/tests/containers/test_provider_openscap_policy_attached.py -v --use-provider ocp-v1}}

[RFR] ContainersProvider update num_container to support changes on CFME 5.9 DB

---

cfme/utils/ssh.py

[1LP][RFR] Fixed SSH buffering

---

cfme/physical/provider/lenovo.py
cfme/tests/physical_infrastructure/test_providers.py

* Added support for new api_port
* Added provider clearing to allow crud test to pass

[1LP][RFR] Some Lenovo fixes

---

widgetastic_manageiq/__init__.py

{{pytest: --long-running cfme/tests/openstack/cloud/test_networks.py }}

[1LP][RFR] fixed non 0 region issue for list views in 5.8

---

cfme/common/provider.py

Purpose
A provider can pass validation even it's not refreshed. If refresh failed there should be an error that also should be accounted.
```json
{
"href": "https://10.0.0.0/api/providers/1",
"id": "1",
"name": "scvmm2016",
"created_on": "2018-02-27T12:27:55Z",
"updated_on": "2018-02-27T13:22:25Z",
"guid": "3972e7dd-26bf-4a3b-935e-73d7fe6b6a30",
"zone_id": "1",
"type": "ManageIQ::Providers::Microsoft::InfraManager",
"last_refresh_error": "undefined method `[]' for nil:NilClass",
"last_refresh_date": "2018-02-27T13:22:25Z",
"tenant_id": "1",
"enabled": true,
"options": {},
"actions": [
{
"name": "edit",
"method": "post",
"href": "https://10.0.0.0/api/providers/1"
},
{
"name": "refresh",
"method": "post",
"href": "https://10.0.0.0/api/providers/1"
},
{
"name": "delete", …
```

[1LP][RFR] Fixed is_refreshed() for providers

---

cfme/tests/configure/test_rest_access_control.py

Adds new tests for editing user groups.
{{pytest: -v -k TestUsersViaREST cfme/tests/configure/test_rest_access_control.py}}

[1LP][RFR] New access control tests for user's groups editing

---

cfme/tests/infrastructure/test_rest_templates.py

\+ small enhancements to existing tests
{{pytest: -v --use-provider vsphere65-nested cfme/tests/infrastructure/test_rest_templates.py}}

[1LP][RFR] Add test for querying template attributes

---

cfme/tests/test_rest.py

* new test ``test_rest_ping``
* new tests for querying collections attributes ``test_query_*``
* moving pictures tests to ``TestPicturesRESTAPI`` class
* uncollectifs cleanups
* ``test_rest_paging`` fix
* minor enhancements
{{pytest: -v cfme/tests/test_rest.py}}
**PRT**
The ``TestEventStreamsRESTAPI.test_find_created_events`` failure on 5.9 is unrelated to changes in this PR.

[1LP][RFR] New tests, enhancements and fixes in test_rest.py

---

cfme/intelligence/reports/saved.py

Detail page navigation failing because Navigation step was missing for All page.

[1LP][NOTEST][RFR] Adding Saved reports All Navigation View

---

cfme/ansible/credentials.py
cfme/tests/ansible/test_embedded_ansible_basic.py

{{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -v -k test_embedded_ansible_credential_crud --long-running}}

[RFR] GCE credentials for Ansible embedded

---

cfme/tests/ssui/test_ssui_dashboard.py

{{pytest: cfme/tests/ssui/test_ssui_dashboard.py --long-running -k  test_monthly_charges --use-provider scvmm2016}}

[RFR] Add BZ blocker for SCVMM chargeback tests

---

cfme/utils/ssh.py

Reverts ManageIQ/integration_tests#6774

Revert "[RFR][1LP] Use paramiko recv_ready as function"

---

cfme/utils/ssh.py

Will be reinstated when debug around the changed code paths is resolved

Revert changing paramiko recv_ready to function calls

---

cfme/networks/subnet.py
cfme/networks/views.py

The network name locator was changed from cloud_network_id to network_id on SubnetAddView
{{ pytest: cfme/tests/openstack/cloud/test_networks.py::test_create_subnet }}

[1LP][RFR] update network name locator to network_id on SubnetAddView

---

cfme/tests/cloud/test_providers.py

{{pytest: -vvv -k test_display_network_topology}}

[1LP][RFR]Fix a typo

---

sprout/appliances/models.py
sprout/appliances/tasks.py
sprout/appliances/templates/appliances/my_appliances.html
sprout/appliances/views.py
sprout/sprout/settings.py

This PR fixes some issues in sprout tasks, finally removes container property, adds template_type to view and so on.
It should be last patch which adds support of openshift provider in sprout

[1LP][RFR] Fix for typo in sprout's poke_trackerbot

---

cfme/infrastructure/datastore.py
cfme/tests/infrastructure/test_datastore_analysis.py

Fix get_text for datastore summary
{{pytest: -vvv -k test_run_datastore_analysis}}

[1LP][RFR]Update summary for datastores

---

cfme/tests/test_db_restore.py
fixtures/appliance.py

Changed fixture usage for test to improve test passing rate due to template issues.

[1LP][RFR] Stabilization fix to test_db_restore

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_vm_reconfigure.py

__Fixing__  vm_reconfigure. CPU&RAM test were broken after last commit
Current fix would also work for various combinations of CPU-RAM-DISK reconfigurations
Consideration: default values for `sockets/cores_per_socket/mem_size/mem_size_unit` - `reconfigure()` doesn't know anything about `old_config`

[1LP][RFR]fixes for vm_reconfigure

---

cfme/base/ui.py
cfme/tests/configure/test_database_ui.py

Added Summary View for ui Database settings
Added New test to check last db start time, test for db garbage collection
{{pytest: -vv -k 'test_configure_vmdb_last_start_time or test_configuration_database_garbage_collection'}}

[1LP][RFR] New db ui test

---

cfme/control/explorer/policy_profiles.py
cfme/tests/control/test_import_policies.py

{{pytest: -v -k "test_control_import_existing_policies"}}

[1LP][RFR] Added test test_control_import_existing_policies

---

cfme/automate/buttons.py
cfme/tests/ansible/test_embedded_ansible_automate.py

{{pytest: -v -k test_embedded_ansible_custom_button --long-running --use-provider vsphere6-nested}}

[1LP][RFR] New test_embedded_ansible_custom_button

---

requirements/frozen.txt

[RFR] Bump wrapanapi for pyvcloud fix

---

widgetastic_manageiq/__init__.py

Adding support for is_displayed for ParametrizedSummaryTable

[1LP][RFR] Adding support for is_displayed for ParametrizedSummaryTable

---

cfme/tests/cli/test_appliance_console.py

Automating a few more tests, added date/time test and db maintenance tests.

[1LP][RFR] New db maintenance and time/date tests

---

cfme/base/__init__.py
cfme/configure/access_control/__init__.py
cfme/fixtures/base.py
cfme/test_framework/appliance.py
cfme/tests/configure/test_db_backup_schedule.py
cfme/tests/configure/test_log_depot_operation.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py
cfme/tests/test_db_migrate.py
cfme/utils/appliance/__init__.py
cfme/utils/ssh.py
fixtures/templateloader.py

This branch enables the running of the suite against a rails server

[RFR] Dev trial

---

cfme/fixtures/cli.py
cfme/tests/cli/test_appliance_cli.py
cfme/tests/cli/test_appliance_console.py

Added a few more cli tests, setting timezone, db maintenance and date/time.

[1LP][RFR] Added new appliance console cli tests

---

cfme/fixtures/service_fixtures.py
cfme/fixtures/vm_name.py
cfme/services/service_catalogs/__init__.py
cfme/services/service_catalogs/ssui.py
cfme/services/service_catalogs/ui.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

Refactored some code and added cloud support for service catalogs in SSUI

[1LP][RFR] Added cloud support for service catalogs and some refactoring

---

cfme/base/ui.py
cfme/services/workloads.py
cfme/tests/services/test_service_catalogs.py

Moved Server steps and view to cfme/base/ui.py
Added test for bz
Shriver: modified pytest with --long-running since its marked at module level.
{{ pytest: -vvv -k test_advanced_search_registry_element --long-running }}

[1LP][RFR]New test_advanced_search_registry_element

---

scripts/image_upload_glance.py

Note: Another file has crept into this PR.I will take care of it.

[1LP][RFR] image_upload_glance : Add image location url

---

cfme/base/ui.py
cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/instance/__init__.py
cfme/common/host_views.py
cfme/configure/access_control/__init__.py
cfme/configure/settings.py
cfme/infrastructure/config_management.py
cfme/infrastructure/datastore.py
cfme/services/catalogs/catalog.py
cfme/services/myservice/ui.py
cfme/services/workloads.py
cfme/tests/configure/test_default_filters.py
cfme/tests/configure/test_default_views_cloud.py
cfme/tests/configure/test_default_views_infra.py
cfme/tests/configure/test_display_settings.py
cfme/tests/configure/test_timeprofile.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py
cfme/tests/containers/test_start_page.py
cfme/tests/containers/test_table_views.py
cfme/tests/services/test_config_provider_servicecatalogs.py
cfme/tests/services/test_provision_stack.py

Refactored the user settings "My Settings" to be a property on the user property of the appliance object. In the process I had to refactor or migrate some other stuff to Widgetastic.

[1LP][WIPTEST] Refactor user settings

---

cfme/tests/cloud_infra_common/test_relationships.py

Automating the test case related to refresh relationship for all the cloud and infra providers.
{{pytest: -v -k 'test_provider_refresh_relationship' --use-provider complete}}

[1LP][RFR] Adding new test case related to relationship discovery

---

markers/uses.py

this branch had gotten forgotten, lets either merge or kill

[1LP][RFR] simplify the uses markers

---

cfme/utils/rest.py

{{pytest: -v --long-running -k TestOrchestrationTemplatesRESTAPI cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Check that API response contains data

---

cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v -k test_ansible_group_id_in_payload --long-running}}

[1LP][RFR] Added test_ansible_group_id_in_payload

---

cfme/control/explorer/alerts.py
cfme/tests/ansible/test_embedded_ansible_automate.py

{{pytest: -v -k "test_alert_run_ansible_playbook" --long-running}}

[1LP][RFR] Added test_alert_run_ansible_playbook

---

cfme/ansible/credentials.py
cfme/common/provider.py
cfme/control/explorer/policies.py
cfme/exceptions.py
cfme/infrastructure/virtual_machines.py
cfme/metaplugins/blockers.py
cfme/test_framework/pytest_plugin.py
cfme/utils/__init__.py
cfme/utils/appliance/__init__.py
cfme/utils/browser.py
cfme/utils/category.py
cfme/utils/smem_memory_monitor.py
cfme/utils/units.py
cfme/utils/update.py

i generally tried to go for items instead of six.iteritems

[1LP][RFR] remove iteritems from the framework

---

cfme/exceptions.py
cfme/storage/volume.py
cfme/storage/volume_snapshot.py
cfme/tests/storage/test_volume_snapshot.py
setup.py

- added a new model page for storage volume snapshot
- added a new test for snapshot
- collection and widgetastic
{{pytest: cfme/tests/storage/test_volume_snapshot.py -v --long-running }}

[1LP][RFR] Storage Volume Snapshot Model page [WT + Collection]

---

cfme/fixtures/service_fixtures.py
cfme/rest/gen_data.py
cfme/services/catalogs/catalog.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/services/test_catalog.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_dynamicdd_dialogelement.py
cfme/tests/services/test_provision_stack.py
cfme/tests/services/test_rest_services.py
setup.py

Convert cfme/services/catalogs/catalog.py to collections

[1LP][RFR] Services catalog collections

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/utils/appliance/__init__.py
cfme/utils/ssh.py

5.8 errors aren't related to my changes. aim of this PR is just to make ansible tests work against podified appliance

[1LP][RFR] make embedded ansible tests work against pod appliance

---

cfme/tests/test_rest.py

{{pytest: -k test_collections_actions cfme/tests/test_rest.py}}

[1LP][RFR] New API tests for checking collection actions

---

cfme/services/myservice/__init__.py
cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py

{{pytest: -v --long-running --use-provider rhv41 cfme/tests/ssui/test_ssui_myservice.py }}
This PR Is same as https://github.com/ManageIQ/integration_tests/pull/6874.
An unwanted commit came in there so closed that one .

[1LP][RFR] Service start/stop

---

cfme/utils/bz.py

removes itervalues and simplifies the code a little bit

[1LP][RFR] simplify utils.bz and remove itervalues usage

---

cfme/services/catalogs/orchestration_template.py
cfme/tests/services/test_orchestration_template.py
cfme/tests/services/test_provision_stack.py
setup.py

Collection conversion of orchestration template

[1LP][RFR] Orchestration template collection

---

cfme/storage/manager.py
cfme/tests/storage/test_manager.py

- Added new tests
1. `test_storage_manager_edit_tag`
2. `test_storage_manager_delete`

[1LP][RFR] Storage manager tag and remove tests

---

cfme/configure/configuration/system_schedules.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

PRT run:
{{ pytest:  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_schedule -vvvv --use-provider vsphere --long-running }}

[1LP][RFR] SSA on VM via System Schedule.

---

requirements/frozen.txt

__Fixing__ frozen.txt to reflect latest widgetastic core. Needs fix to run saucelabs tests correctly.

[1LP][RFR][NOTEST]Widgetastic version 0.20.4 had some issues in def classes in browser.py, fixed in latest version

---

requirements/frozen.txt

https://github.com/ManageIQ/wrapanapi/releases/tag/2.8.4

[RFR] Wrapanapi 2.8.4

---

cfme/tests/test_db_migrate.py

Removed nested loop to prevent extra tests being generated on collection.

[RFR] removed nested loop

---

cfme/tests/control/test_alerts.py

Fixing broken fixture  after merging #6820

[1LP][RFR] Fixed configure_fleecing fixture in test_alerts.py

---

cfme/tests/physical_infrastructure/api/test_physical_server_inventory_api.py

* Updating tests for feature Physical Server API
because the name asset_details changed to asset_detail
this change was done here https://github.com/ManageIQ/manageiq-providers-lenovo/pull/125

[1LP][RFR] Updating test to use asset_detail

---

cfme/tests/cloud_infra_common/test_relationships.py

[1LP][RFR] Added missing import

---

cfme/test_framework/appliance_log_collector.py

Tested locally with files that DNE on the appliance, tar command does not error out and what files are present get included in the archive.
Added `try:except` block to capture command assertion error to stop pytest from exiting with the exception.

[1LP][RFR] Wrap appliance log tarring, catch errors

---

cfme/tests/configure/test_landing_page.py

There is a change in the setting model page which caused some failure in the landing page test case, providing a fix for that.
{{pytest: -v -k 'test_landing_page_admin'}}

[1LP][RFR]Implementing fix landing_page related failures

---

cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py

Moved the setup_provider fixture first in the list else the catalog item was created before setting up provider .

[1LP][RFR] Moved the setup_provider first in the fixture list

---

cfme/services/myservice/ui.py
cfme/services/service_catalogs/ui.py
cfme/tests/services/test_myservice.py

{{pytest: -v --long-running cfme/tests/services/test_myservice.py }}

[RFR] PR 5762 corrections

---

cfme/utils/appliance/__init__.py

{{pytest: cfme/tests/ansible/test_embedded_ansible_crud.py}}

[1LP][RFR] fix for check whether supervisord is running in pod appliance

---

requirements/frozen.txt

No PRT testing necessary/available (tested locally).

[1LP][RFR] Bump dump2polarion version to v0.20

---

requirements/frozen.txt

[1LP][RFR] widgetastic.patternfly version update

---

cfme/infrastructure/openstack_node.py
cfme/tests/openstack/infrastructure/test_host_lifecycle.py
setup.py

Add OpenstackNodeCollection on openstack_node.py
Update entry on setup.py
Modify host_lifecycle tests fixture to use new collection
{{ pytest: cfme/tests/openstack/infrastructure/test_host_lifecycle.py }}

[1LP][RFR] Add OpenstackNodeCollection to fix host lifecycle tests

---

cfme/infrastructure/virtual_machines.py
cfme/tests/cloud_infra_common/test_relationships.py

Introducing other providers for test case related to test_relationship.py
{{pytest: -v -k 'test_host_relationships or test_infra_provider_relationships or test_cloud_provider_relationships' --use-provider complete}}

[1LP][RFR] Introducing other providers for test case in test_relationship.py

---

cfme/common/__init__.py
cfme/configure/access_control/__init__.py
cfme/tests/configure/test_access_control.py

{{pytest: cfme/tests/configure/test_access_control.py -k 'test_user_edit_tag or test_user_remove_tag or test_tagvis_user or test_group_edit_tag or test_group_remove_tag or test_tagvis_group'}}

[1LP][RFR]Update access_control.py to use WidgetasticTaggable Class

---

cfme/services/myservice/ui.py
cfme/services/service_catalogs/ui.py

{{ pytest: -v --long-running cfme/tests/services/test_different_dialogs_in_catalogs.py }}
Fixed test_different_dialogs_in_catalogs.py/test_tagdialog_catalog_item
and test_myservice.py/test_download_file

[1LP][RFR] Added wait for view

---

requirements/frozen.txt
requirements/frozen_docs.txt
requirements/template_docs.txt
requirements/test_frozen_requirements.py

experimenting with bumping to the most recent pytest to find detail issues

[1LP][RFR][CAREFUL] bump pytest to 3.4.1

---

cfme/tests/test_utilization_metrics.py

- Skipping test for GCE : BZ-1511099
{{pytest: cfme/tests/test_utilization_metrics.py -v --use-provider complete --long-running }}

[1LP][RFR] C&U skip for GCE

---

cfme/scripting/ipyshell.py
cfme/scripting/quickstart.py
cfme/scripting/runtest.py

this fixes a few calls that call into the internals of quick-start,
we might add a few acceptance tests as follow-up

[RFR] fix runtest/shell calling into quickstart for multi-checkout support

---

cfme/intelligence/reports/widgets/__init__.py
cfme/intelligence/reports/widgets/chart_widgets.py
cfme/intelligence/reports/widgets/menu_widgets.py
cfme/intelligence/reports/widgets/report_widgets.py
cfme/intelligence/reports/widgets/rss_widgets.py
cfme/tests/intelligence/reports/test_crud.py
cfme/tests/intelligence/reports/test_widgets.py
setup.py

{{pytest: -v -k "test_menuwidget_crud or test_reportwidget_crud or test_chartwidget_crud or test_rssfeedwidget_crud or test_widgets_on_dashboard"}}

[1LP][RFR] Dashboard report widgets collections conversion

---

cfme/common/__init__.py

- Found some of my tag tests are failing due to other exception
{{pytest: cfme/tests/storage/test_manager.py::test_storage_manager_edit_tag -v}}

[1LP][RFR] added exception SelectItemNotFound

---

cfme/ansible/repositories.py
cfme/fixtures/ansible_fixtures.py

{{pytest: -v --long-running cfme/tests/ssui/test_ssui_ansible_service.py}}

[1LP][RFR] Catalog collection change fix

---

cfme/common/provider_views.py
cfme/tests/infrastructure/test_providers.py

- Automate Infra provider discovery screen test by @jistefan 
https://polarion.engineering.redhat.com/polarion/#/project/RHCF3/workitem?id=RHCF3-10050
- Added `OpenStack Intra` Discovery support in `DiscoveryView`
{{pytest: cfme/tests/infrastructure/test_providers.py::test_infra_discovery_screen -v}}

[1LP][RFR] infra provider discovery screen test

---

cfme/test_framework/__init__.py
cfme/utils/appliance/__init__.py
cfme/utils/log.py

* of the entrypoints package
* of Navigatable.appliance
* of Navigatable usage in general
* of oslo_i18n

[RFR] take out various warnings that are indeed irrelevant now

---

cfme/storage/volume.py
cfme/tests/storage/test_volume.py

- added tag test for storage volume
{{pytest: cfme/tests/storage/test_volume.py::test_storage_volume_edit_tag -v}}

[RFR] Storage: volume tag test

---

cfme/scripting/sprout.py
cfme/utils/dockerbot/pytestbase/setup.sh

Add required options for SproutProvisioningRequest
Log commands that are run by dockerbot setup script

[1LP][RFR] Update miq sprout options

---

requirements/frozen.txt

[1LP][RFR] widgetastic patternfly version update(tab fix)

---

cfme/ansible/repositories.py

__Fixing__ Flash message with version pick since developers changed the flash message in 5.9.2.0
{{pytest:  cfme/tests/ansible/test_embedded_ansible_services.py --long-running -s  -k 'test_service_ansible_playbook_crud'}}

[1LP][RFR] Adding Version Pick to handle Ansible Repo Add operation Flash Message

---

cfme/base/ui.py
cfme/tests/configure/test_paginator.py

{{pytest: cfme/tests/configure/test_paginator.py }}

[1LP][RFR] Check pagination on configuration pages

---

cfme/common/provider_views.py
cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/infrastructure/provider/kubevirt.py
cfme/tests/infrastructure/test_kubevirt.py
setup.py

Adding the new KubeVirt Provider 
{{ pytest: -vvvv cfme/tests/infrastructure/test_kubevirt.py --use-provider kubevirt }}

[1LP][RFR] New Provider: KubeVirt

---

.gitignore

Added gitignore for pytest_cache

[1LP][RFR] ignoring .pytest_cache

---

scripts/coverage_report_jenkins.py

The Central CI sonarqube requires us to authenticate to it when we upload our sonar scan data.   This PR adds that capability to cover_merger_jenkins.py.

[1LP][RFR] Added support for authentication to a sonarqube

---

cfme/tests/infrastructure/test_host_analysis.py

{{pytest: -k test_run_host_analysis --long-running}}

[1LP][RFR]Host sidebar navigation fix

---

cfme/automate/buttons.py
cfme/fixtures/vm.py
cfme/tests/ansible/test_embedded_ansible_automate.py

After wrong rebase I broke test_embedded_ansible_custom_button, this PR fixes that.
{{pytest: -v -k test_embedded_ansible_custom_button --long-running}}

[1LP][RFR] New tests test_embedded_ansible_custom_button

---

cfme/tests/pod/test_appliance_crud.py
cfme/tests/pod/test_db_backup_restore.py
cfme/tests/pod/test_ext_auth.py

Pod appliance requires some tests. This PR creates templates for manual tests which will be replaced with automated tests later.

[1LP][RFR] basic manual pod tests

---

cfme/tests/containers/test_ad_hoc_metrics.py
cfme/tests/containers/test_basic_metrics.py
cfme/tests/containers/test_manageiq_ansible_custom_attributes.py

Failures in the last RC job required some test updates. 
{{ pytest: cfme/tests/containers/test_basic_metrics.py  cfme/tests/containers/test_manageiq_ansible_custom_attributes.py cfme/tests/containers/test_ad_hoc_metrics.py --use-provider ocp-v2 }}

[1LP][RFR] Automation Fixes for CMQE

---

cfme/tests/physical_infrastructure/ui/test_physical_server_details_buttons.py

* Add new tests to cover Monitoring button is working on physical server details page.
Depends On: https://github.com/ManageIQ/integration_tests/pull/6898

[1LP][RFR] Add UI tests for Monitoring button in the physical server page

---

cfme/intelligence/reports/reports.py

{{pytest: cfme/tests/intelligence/reports/test_report_corresponds.py}}

[1LP][RFR] Skip assertion of flash message after report deletion

---

cfme/services/catalogs/orchestration_template.py
cfme/tests/services/test_orchestration_template.py
cfme/tests/services/test_provision_stack.py

__Adding tests__  and  __Updating tests__  
Docstrings were added
Also made some refactoring
{{pytest: cfme/tests/services/test_orchestration_template.py}}

[1LP][RFR]adding orchestration template tests

---

cfme/tests/infrastructure/test_kubevirt.py

[RFR] name change for kubevirt

---

.gitignore

[RFR] added gitignore for env.local.backup

---

cfme/markers/env_markers/provider.py

Added override flag for provider marker

[RFR] Added override flag for provider marker

---

cfme/tests/physical_infrastructure/ui/test_physical_server_details.py
cfme/tests/physical_infrastructure/ui/test_physical_server_list.py

__Fixing__ the remove button for physical server was removed which is making the test to fail

[1LP][RFR] Delete action for physical server was removed

---

cfme/services/myservice/ssui.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_iso_service_catalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_pxe_service_catalogs.py
cfme/tests/services/test_request.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py

{{ pytest: -vvv --long-running cfme/tests/services/test_add_remove_vm_to_service.py cfme/tests/services/test_service_manual_approval.py cfme/tests/services/test_different_dialogs_in_catalogs.py test_service_catalogs.py cfme/tests/services/test_myservice.py }}

[1LP][RFR] Fixed prov_data failures

---

cfme/tests/infrastructure/test_quota_tagging.py

{{pytest: cfme/tests/infrastructure/test_quota_tagging.py --long-running --use-provider rhevm}}

[1LP][RFR]Fix test_quota_tagging

---

cfme/markers/uncollect.py
cfme/tests/control/test_compliance.py
cfme/tests/test_appliance.py

* We now allow multiple uncollectif markers and will correctly identify the reason.
* Logic altered to shortcut where necessary

[1LP][RFR] Optimized uncollectif

---

cfme/control/explorer/conditions.py
cfme/control/explorer/policies.py
cfme/tests/control/test_basic.py

Requires #7002 
{{pytest: -v -k "test_condition_crud or test_policy_crud" --long-running }}

[1LP][RFR] Fixed strings in Control

---

cfme/tests/configure/test_session_timeout.py

modify advanced settings authentication:bind_timeout value via REST, for BZ 1553394
currently BZ active and blocking
58z will be ignored
59z will be BZ skip
Failures are as expected in 22951
I've run the test locally without the BZ skip, and it fails as expected due to the active BZ.
{{ pytest: cfme/tests/configure/test_session_timeout.py -k test_bind_timeout_rest }}

[1LP][RFR] Add rest bind_timeout test for BZ

---

cfme/intelligence/reports/dashboards.py
cfme/tests/intelligence/reports/test_crud.py
cfme/tests/intelligence/test_dashboard.py
setup.py

{{pytest: -v -k "test_custom_dashboards or test_dashboard_crud"}}

[1LP][RFR] Reports dashboard collections

---

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py

{{pytest: -v --long-running -k test_add_duplicate cfme/tests/cloud_infra_common/test_custom_attributes_rest.py}}

[1LP][RFR] Add test for adding duplicate custom attribute using REST

---

docs/guides/dev_guide.rst

First draft.
Documenting RC tagging and release process

[1LP][RFR] Update dev_guide doc with RC tag/release

---

scripts/cleanup_edomain_templates.py

There is an exception raised during creation of the API object when the credentials are invalid, this was occuring when cleanup_templates was called with provider_mgmt.api passed.
Make this call in the try block that's already supposed to be checking for API handler.
Move the print statement for the provider start to before we actually start trying to connect to the provider.
PRT results are void here unless I've managed to make a colossal error.
The script is currently in-use by CFME QE Jenkins, and runs successfully, logging the API failure to a provider with incorrect credentials.

[1LP][RFR] cleanup_edomain_templates, handle API exception

---

cfme/tests/cloud/test_instance_power_control.py
cfme/tests/cloud/test_providers.py
cfme/tests/cloud/test_provisioning.py
cfme/tests/cloud/test_stack.py
cfme/tests/configure/test_tag.py
cfme/tests/configure/test_version.py
cfme/tests/infrastructure/test_advanced_search_host.py
cfme/tests/infrastructure/test_advanced_search_providers.py
cfme/tests/infrastructure/test_advanced_search_vms.py
cfme/tests/infrastructure/test_customization_template.py
cfme/tests/infrastructure/test_providers.py
cfme/tests/infrastructure/test_provisioning.py
cfme/tests/infrastructure/test_system_image_type.py
cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/intelligence/test_dashboard.py
cfme/tests/networks/test_network_providers.py
cfme/tests/physical_infrastructure/test_providers.py
cfme/tests/services/test_catalog_item.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_orchestration_template.py
cfme/tests/services/test_request.py
cfme/tests/ssui/test_ssui_ansible_service.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

Renamed some tests to avoid duplicates

[1LP][RFR] Renamed some tests to avoid duplicates

---

requirements/frozen.txt
requirements/frozen_docs.txt

Fixes issue with ``None`` attributes - https://github.com/ManageIQ/manageiq-api-client-python/pull/39
{{pytest: -v -k test_attributes_present cfme/tests/test_rest.py}}

[1LP][RFR] Update manageiq-client to 0.4.1

---

cfme/infrastructure/provider/rhevm.py

The ability to provide TLS certificate for RHV provider was added to CFME only in version 5.8.0.8. That's why creation of provider will fail on older versions -> the framework is not able to fill in the provider creation form. This PR __fixes__ that by removing TLS information from endpoint if appliance is < 5.8.0.8.
PRT fail: SSH exception
{{pytest: cfme/tests/infrastructure/test_providers.py::test_infra_provider_crud --use-provider rhv41}}

[1LP][RFR] Fix provider create for RHV and CFME < 5.8.0.8

---

scripts/template_upload_scvmm.py

[RFR] Use wait_for func properly

---

cfme/markers/composite.py

* Parallelizer slave AND master run collections, and also uncollection
* When composite uncollection occurs, a call to trackerbot is made to
do so
* Sometimes, this fails for either master or slave causing a collection
diff
* Master now ALWAYS stores the result of the uncollection in a cache
* Slaves now ALWAYS use the cached version, ensuring no difference in
uncollection due to a timeout, OR a change of test data

[1LP][RFR] Fixed Paralleizer Composite Uncollect

---

requirements/frozen.txt

[RFR] wrapanapi 2.8.8 has been released

---

cfme/common/candu_views.py
cfme/fixtures/candu.py
cfme/infrastructure/virtual_machines.py
cfme/test_framework/pytest_plugin.py
cfme/tests/candu/test_vm_graph.py
widgetastic_manageiq/__init__.py

- Introduce `LineChart` widget for reading data from graph 
- Created `cfme.fixtues.canu.py` for `C&U fixtures`, so we can move our fixture at common location
- Created `cfme.common.candu_views.py` for C&U views.
- Added one navigation in `virtual_machines.py` for utilization page
- Created dir `cfme.tests.candu` for C&U tests
- Added small screen test for graph automation
{{pytest: cfme/tests/candu/ -v}}

[1LP][RFR] C&U: Line Graph

---

cfme/intelligence/reports/saved.py
setup.py

There are no tests for this part of the CFME UI. Therefore no PRT task was provided.

[1LP][RFR] Saved reports converted to collections

---

cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_reports_schedules.py
data/schedules_report/daily.yaml
data/schedules_report/hourly.yaml
data/schedules_report/monthly.yaml
data/schedules_report/once.yaml
data/schedules_report/weekly.yaml

{{ pytest: -vvvv cfme/tests/intelligence/reports/test_reports_schedules.py -k test_schedule }}

[1LP][RFR] Adding new tests of reports scheduling

---

cfme/automate/provisioning_dialogs.py
cfme/tests/automate/test_provisioning_dialogs.py
setup.py

{{pytest: -v cfme/tests/automate/test_provisioning_dialogs.py}}

[1LP][RFR] Provisioning dialogs collections conversion

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py

PRT results:
58 - passed
59 - passed

[1LP][RFR] Chargeback tests for long term rates

---

cfme/scripting/appliance.py

Upgrade script extension to allow users to upgrade appliances from 5.7+ to a specific version they require.

[RFR][1LP] Added new version picking to scripts

---

cfme/tests/configure/test_register_appliance.py

Fix to 5.9.2 test runs to support new repos listed in the UI.
{{pytest: -v -k "test_rhsm_registration_check_repo_names"}}

[1LP][RFR] New fixes for current testing

---

.gitignore
cfme/utils/dockerbot/pytestbase/Dockerfile
cfme/utils/dockerbot/pytestbase/check_provisioned.py
cfme/utils/dockerbot/pytestbase/setup.sh

moves the checking into a python script instead of shell magic

[RFR] Fix dockerbot provisioning check

---

cfme/tests/cloud/test_cloud_timelines.py

Refactoring and adding new event on the Cloud Timeline
Rewriting the module the same way as test_timelines.py  and adding new events.
PRT failed because on some random events the source_instance field is missing ( a reported bug).
Some tests of the module failed because of some issues with providers/region. mostly overloaded, so events are not coming on time. On a run it might be good, on the next it might be delayed.
Test failed also on because somebody created a availability zone on Azure without a provider so but timeline button is disabled.
{{pytest: -v -q cfme/tests/cloud/test_cloud_timelines.py --use-template-cache --use-provider=complete}}

[1LP][RFR] Cloud timeline adding events

---

cfme/utils/appliance/implementations/ui.py

We are running things in the browser without first checking for modal dialog, I decided it may be better to put all the precheck stuff inside the try block. This is a PoC really, and I think check_for_badness really needs to be redesigned.

[1LP][RFR] Check for badness rework

---

cfme/test_framework/pytest_plugin.py

this takes off the part of pytest we trigger issues in :(

[1LP][RFR] also back out of pytest logging integration :(

---

requirements/frozen.txt

Attempting to resolve #7094 -- requires https://github.com/ManageIQ/wrapanapi/pull/246 to be merged at the same time.
{{ pytest: cfme/tests/cloud/test_instance_power_control.py --long-running --use-provider openstack }}

[1LP][RFR] Fix package dependency conflicts

---

cfme/test_framework/appliance.py
cfme/test_framework/appliance_log_collector.py
cfme/test_framework/browser_isolation.py
cfme/utils/appliance/__init__.py

this bit introduces and starts to use a utility to get the appliance from "any" object within reason

[1LP][RFR] introduce find appliance helper

---

cfme/ansible/repositories.py

{{pytest: -v -k test_embedded_ansible_repository_crud --long-running}}

[1LP][RFR] Fixed flash message in test_embedded_ansible_repository_crud

---

cfme/tests/automate/test_buttons.py

{{pytest: -v -k test_button_avp_displayed}}

[1LP][RFR] Fixed test_button_avp_displayed

---

sprout/README.rst

The link to setting up your environment was broken.

[1LP][RFR][NOTEST] Fix sprout read the docs link in README.rst

---

cfme/configure/tasks.py
cfme/scripting/conf.py
cfme/scripting/disable_bytecode.py
cfme/scripting/link_config.py
cfme/scripting/quickstart.py
cfme/utils/browser.py
cfme/utils/db.py
cfme/utils/dockerbot/sel_container.py
cfme/utils/repo_gen.py
fixtures/browser.py
requirements/template_docs.txt
widgetastic_manageiq/__init__.py

this also makes ´miq shell` start without exceptions

[RFR][1LP] enable the venv to be build on py3k using the template files

---

cfme/common/__init__.py
cfme/fixtures/tag.py
cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_automate.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/cloud/test_keypairs.py
cfme/tests/cloud/test_stack.py
cfme/tests/cloud_infra_common/test_retirement.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/configure/test_access_control.py
cfme/tests/containers/test_smart_management.py
cfme/tests/control/test_actions.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/services/test_catalog_item.py
cfme/tests/services/test_myservice.py
cfme/tests/storage/test_manager.py
cfme/tests/storage/test_object_store_container.py
cfme/tests/storage/test_object_store_object.py
cfme/tests/storage/test_volume.py
cfme/tests/storage/test_volume_backup.py
cfme/tests/storage/test_volume_snapshot.py

Update Taggable to work only with Tag object
{{pytest: -k 'edit_tag or test_drift_analysis or test_host_drift_analysis' --long-running}}

[1LP][RFR]Use tag object only updates

---

cfme/infrastructure/deployment_roles.py
cfme/tests/openstack/infrastructure/test_resources.py
cfme/tests/openstack/infrastructure/test_roles.py

1. Fix access to Relationships of Deployment roles summary table
2. Added a remove item VersionPick handler for 5.8 and 5.9
{{ pytest: cfme/tests/openstack/infrastructure/test_roles.py }}

[1LP][RFR] Fix test roles tests

---

cfme/tests/cloud/test_tenant_quota.py
cfme/tests/infrastructure/test_tenant_quota.py

Implementing changes to extend the quota test case to be performed via SSUI.
{{pytest: -v -k 'test_tenant_quota_enforce_via_service_infra or test_tenant_quota_enforce_via_lifecycle_infra or test_tenant_quota_enforce_via_lifecycle_cloud or test_tenant_quota_enforce_via_service_cloud'}}

[1LP][RFR] Extending test cases for SSUI

---

cfme/tests/networks/test_sdn_downloads.py

Fixed PDF download skipping on upstream

[RFR] Fixed PDF download skipping on upstream

---

docs/getting_started.rst

To remove annoying `` in the docs

[1LP][RFR] corrected inline literal in getting_started.rst

---

cfme/intelligence/reports/reports.py
cfme/intelligence/reports/saved.py
cfme/tests/configure/test_visual_infra.py
cfme/tests/containers/test_chargeback.py
cfme/tests/containers/test_reports.py
cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
cfme/tests/intelligence/reports/test_canned_corresponds.py
cfme/tests/intelligence/reports/test_crud.py
cfme/tests/intelligence/reports/test_generate_report.py
cfme/tests/intelligence/reports/test_menus.py
cfme/tests/intelligence/reports/test_metering_report.py
cfme/tests/intelligence/reports/test_report_chargeback.py
cfme/tests/intelligence/reports/test_report_corresponds.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py
cfme/tests/intelligence/reports/test_views.py
cfme/tests/intelligence/test_download_report.py
setup.py

{{pytest: -v -k "test_report_view or test_reports_generate_report or test_infra_report_page_per_item or test_providers_summary or test_cluster_relationships or test_operations_vm_on or test_datastores_summary or test_custom_report_crud or test_reports_generate_report or test_shuffle_top_level or test_shuffle_first_level or test_charge_report_filter_owner or test_custom_vm_report"}}

[1LP][RFR] Reports collections conversion

---

cfme/base/__init__.py

This PR is to be reverted once the issue is resolved

[RFR][1LP] Fixed server name again, previous attempt led to recursion

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/infrastructure/test_vm_clone.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/ssui/test_ssui_dashboard.py

RHV tier markers for several test cases

[1LP][RFR] RHV tiers for several tests

---

cfme/fixtures/version_info.py
requirements/frozen.txt
requirements/perf.txt
requirements/template_docs.txt

PRT failures not related to changes

[1LP][RFR] New performance requirements

---

cfme/cloud/instance/__init__.py
cfme/tests/cloud_infra_common/test_cockpit_server.py

{{ pytest: cfme/tests/cloud_infra_common/test_cockpit_server.py --use-provider complete }}

[1LP][RFR] Fix cockpit server role tests for cloud providers

---

cfme/configure/configuration/system_schedules.py
cfme/tests/configure/test_schedule_operations.py

{{pytest: cfme/tests/configure/test_schedule_operations.py}}

[1LP][RFR]tests for system schedules 

---

requirements/frozen.txt
requirements/frozen_docs.txt

Fixes https://github.com/mkoura/dump2polarion/issues/1, thanks @mshriver !

[1LP][RFR] Update dump2polarion version to 0.23

---

cfme/tests/infrastructure/test_vm_reconfigure.py

__Adding__ new tests for VM reconfiguration while the VM is running. Main points summarized:
- I refactored code of test method `test_vm_reconfig_add_remove_hw_cold` in a way that can be reused and code duplication is avoided.
- New tests are uncollected for VMWare. I don't have capacity and env for developing VMWare tests. Feel free to run them on VMWare and enable if it's okay.
- I changed scope of small_vm fixture to `function`. If the VM is shared by test cases in whole module, it allows for propagation of faults to following test cases. If for example one test case does not manage to revert to original configuration, then in the following test case you have a VM with unexpected hardware. I know this is slower but I think this is more in line with the philosophy of rather being slower …

[1LP][RFR] Adding VM hot reconfigure tests

---

cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/tests/containers/test_basic_metrics.py
scripts/openshift/change_metrics_collection_threshold.rb

{{ pytest: cfme/tests/containers/test_basic_metrics.py::test_validate_metrics_collection_db cfme/tests/containers/test_basic_metrics.py::test_validate_metrics_collection_provider_gui  --use-provider ocp-v3 }}
In this PR I will add some FW code and tests for metrics tests for Container provider

[1LP][RFR] Metrics tests for OpenShift provider

---

cfme/cloud/provider/vcloud.py
cfme/networks/provider/nuage.py

[RFR] Fixed a typo in the providers

---

fixtures/log.py

[RFR] use a list comprehension instead of a lambda map for log sessionfinish

---

cfme/utils/providers.py

[RFR][1LP] fix up types in utils.providers

---

cfme/control/explorer/policies.py

[RFR] fix relative import in cfme/control/explorer/policies.py

---

fixtures/artifactor_plugin.py

this simply lines up the methods for python3

[RFR] artifactor client dummy nonzero - py3k

---

cfme/common/provider.py

[1LP][RFR] fix size changed while iteration in provider.all_types

---

requirements/template_docs.txt

this pr is just updating the requirement files adding what we have in frozen

[RFR][NOTEST] add missing deps to requirement templates

---

cfme/services/myservice/ui.py

[1LP][RFR] use self.appliance instead of current_appliance in myservice/ui

---

cfme/metaplugins/blockers.py

[1LP][RFR] use find_appliance in blockers metaplugin

---

cfme/markers/uncollect.py

[1LP][RFR] use find_appliance in markers.uncollect

---

cfme/tests/integration/test_aws_iam_auth_and_roles.py

[1LP][RFR] use find_appliance in test_aws_iam_auth_and_roles.py

---

cfme/tests/cli/test_appliance_update.py

[1LP][RFR] use find_appliance in test_appliance_update

---

cfme/scripting/appliance.py

[1LP][RFR] fix up appliance fetching in appliance script

---

cfme/common/candu_views.py
cfme/infrastructure/host.py
cfme/tests/candu/test_host_graph.py

- Added test for recent hour host graph
- Supported Providers
* Vsphere
* RHV
- Added Views for support
- Added Navigation and wait for Utilization enable with reference to host object.
{{pytest: cfme/tests/candu/test_host_graph.py -v --use-provider complete}}

[1LP][RFR] Host Utilization for recent hr

---

cfme/tests/pod/test_appliance_crud.py

additional manual test cases for pod appliance to automate

[1LP][RFR] two more manual pod appliance test cases

---

cfme/metaplugins/server_roles.py

[RFR] use find_appliance in server roles metaplugin

---

cfme/infrastructure/virtual_machines.py
cfme/tests/control/test_bugs.py
cfme/tests/infrastructure/test_advanced_search_vms.py
cfme/tests/infrastructure/test_vm_power_control.py

* Removed get_number_of_vms (unused)

[1LP][RFR] Remove some usages of get_or_create_current_appliance

---

cfme/tests/configure/test_docs.py

[1LP][RFR] remove unused import in test_docs

---

.travis.yml

this pr merely enables the build and and uses quickstart - #7135 will be a followup

[1LP][RFR] run travis on py3

---

cfme/tests/intelligence/reports/test_metering_report.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py

[1LP][RFR] uncollect scvmm for chargeback and metering reports

---

cfme/test_framework/appliance.py

Appliance holder shouldn't check version on a dev appliance

[1LP][RFR] Fixed appliance holder

---

requirements/frozen.py2.txt
requirements/frozen_docs.py2.txt
requirements/template_docs.txt

Added cycler to template_docs.txt, used `python scripts/freeze_all.py` to re-freeze.

[RFR] Update requirements, add cycler

---

scripts/template_upload_scvmm.py

This is so that DB setup on new downstream appliances will work once again on SCVMM. We are attaching a blank disk for the DB. A parameter for SCVMM providers in `cfme_data.yaml` under `template_upload` called `db_disk` will specify which .vhd file should be used. 
Tested locally with template_upload on cfme 5.9.2.4, followed by a clone_template, and things are working fine.
There will be a corresponding PR for cfme YAMLs

[1LP][RFR] Add a DB disk to SCVMM appliance templates

---

cfme/tests/integration/test_cfme_auth.py

Bad handling of non-existent conf file

[RFR] Fix auth_tests

---

cfme/tests/configure/test_paginator.py
cfme/tests/integration/test_cfme_auth.py

[RFR] Fixed a few more tests

---

cfme/cloud/instance/openstack.py

Replace deferred verpick with VersionPick
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_delete_instance }}

[RFR] Replace deferred verpick with VersionPick

---

cfme/tests/infrastructure/test_vm_power_control.py

Also wrapping `wait_for_last_boot_timestamp_refresh` with `soft_assert`. If that is not the case, the test case can succeed even though last boot time was not updated.
Regarding PRT outcome: As you can see, tests for VMWare failed. That might be an actual bug. I've filled this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1571830) for RHV but maybe it's actually the same one.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_guest_os_reset --long-running}}

[1LP][RFR] Activating test_guest_os_reset for RHV

---

cfme/cloud/instance/__init__.py
cfme/cloud/provider/azure.py
cfme/cloud/provider/ec2.py
cfme/common/candu_views.py
cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/infrastructure/virtual_machines.py
cfme/tests/candu/test_vm_graph.py

- Added support of VM graph test for other provider.
* Azure
* AWS
* Vsphere6
* RHV
- Added changes in Views as per Provider
- One test uncollected due to our infra problem; we are not getting proper metrics for EC2 disk activity. 
{{pytest: cfme/tests/candu/ -v --use-provider complete --long-running}}

[1LP][RFR] Added support for other providers [VM graph]

---

cfme/tests/infrastructure/test_project_quota.py

Adding new test cases related to project quota.
{{pytest: -v -k 'test_project_quota_enforce_via_lifecycle_infra ' --long-running}}

[1LP][RFR]Adding test case related to project.

---

requirements/on_rtd.txt

[RFR] Fixed docs building

---

docs/conf.py

[RFR] Fixed nelson reference

---

artifactor/plugins/filedump.py
artifactor/plugins/reporter.py
cfme/infrastructure/virtual_machines.py
cfme/metaplugins/server_roles.py
cfme/utils/__init__.py
cfme/utils/appliance/__init__.py
cfme/utils/blockers.py
cfme/utils/bz.py
cfme/utils/ssh.py
cfme/utils/units.py
scripts/list_tests.py
sprout/appliances/models.py
sprout/sprout/log.py
widgetastic_manageiq/expression_editor.py

[RFR] python-modernize -f libmodernize.fixes.fix_basestring . -j8 -w -n

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
requirements/template_docs.txt

Added Taretto
* WT/NM/Sentaku are now no longer described manually, but included by Taretto

[RFR] Added Taretto

---

cfme/utils/providers.py

Creating a new instance of wrapanapi System classes is inefficient, the most glaring example involves vCenter where every new instance of the class needs to call a method that takes 5min or more -- "service_instance.RetrieveContent()" -- this is a cached property in the class so if we return the same provider mgmt instance when asked to get mgmt again for the same provider key, we save a ton of time.

[1LP][RFR] Use a cache for returning provider mgmt instances

---

cfme/tests/configure/test_zones.py

__Extending__  zone tests. verifying that we can add/remove Windows domain credentials

[1LP][RFR]added windows domain credential tests

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

PRT run:
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_compliance -vvvv --use-provider vsphere6-nested --long-running }}

[1LP][RFR] This PR will automate SSA via Compliance.

---

cfme/utils/appliance/__init__.py
sprout/appliances/tasks.py

Allows for calling in custom_configure as-is currently done, and for calling separately during deployment of a snapshotted configured image in sprout

[1LP][RFR] Move FQDN setting into Appliance.set_resolvable_hostname

---

.travis.yml
cfme/fixtures/browser.py
cfme/fixtures/nelson.py
cfme/fixtures/smtp.py
cfme/markers/env_markers/provider.py
cfme/modeling/base.py
cfme/scripting/quickstart.py
cfme/tests/configure/test_docs.py
cfme/utils/__init__.py
cfme/utils/appliance/__init__.py
cfme/utils/appliance/db.py
cfme/utils/appliance/implementations/ui.py
cfme/utils/browser.py
cfme/utils/log_validator.py
cfme/utils/mgmt_system/__init__.py
cfme/utils/providers.py
cfme/utils/pytest_shortcuts.py
cfme/utils/ssh.py
cfme/utils/tests/test_datafile_fixture.py
cfme/utils/tests/test_soft_assert.py
cfme/utils/units.py
cfme/utils/virtual_machines.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py3.txt
requirements/template.txt
requirements/template_docs.txt
requirements/test_frozen_requirements.py

[1LP][RFR] fix python3 on travis and for --collectonly

---

cfme/base/login.py
cfme/tests/configure/test_access_control.py
widgetastic_manageiq/__init__.py

Enables the currently logged in user to change its RBAC group via the webui via a call to BaseLoggedInPage.change_group. CFME 5.9 added support for a user being assigned to multiple groups. 
Follow up to #6749 
{{ pytest: -v cfme/tests/configure/test_access_control.py -k 'test_user_change_groups or test_user_group_test_user_crud or test_user_assign_multiple_groups or test_user_group_error_validation or test_group_ownership_on_user_or_group_role or test_group_ownership_on_user_only_role' }}

[1LP][WIPTEST]Add widget and tests for changing the RBAC group for the currently logged in user via the webui

---

cfme/tests/openstack/infrastructure/test_host_lifecycle.py

Added wait_for statements where needed
{{ pytest: cfme/tests/openstack/infrastructure/test_host_lifecycle.py }}

[1LP][RFR] fixed timing issues in test_host_lifecycle tests

---

cfme/tests/infrastructure/test_child_tenant.py

==================
Implementing new test cases for child tenant quota related test cases.
{{pytest: -v -k 'test_child_tenant_quota_enforce_via_lifecycle_infra' --long-running}}

[1LP][RFR] Adding new test case related to child tenant.

---

cfme/tests/infrastructure/test_quota_tagging.py

This PR provides fix for jenkin failure of test_quota_tagging for rhv provider.
{{pytest: -v -k 'test_quota_tagging'}}

[1LP][RFR] Fixing Quota tagging automation failure

---

cfme/tests/intelligence/chargeback/test_resource_allocation.py
cfme/tests/ssui/test_ssui_dashboard.py

{{pytest: cfme/tests/ssui/test_ssui_dashboard.py -k test_monthly_charges --long-running --use-provider complete}}
PRT results:
58 - PASS
59 - PASS

[1LP][RFR] Service chargeback: fix SCVMM failure

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Some small fixes for newly added SSA templates
Needs -  https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/501
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_vm --long-running}}

[1LP][RFR]SSA templates extend fixes

---

cfme/utils/appliance/__init__.py

[1LP][RFR] Fixed escape sequences

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/services/myservice/ui.py
cfme/services/service_catalogs/__init__.py
cfme/tests/services/test_provision_stack.py

__Fixing__ locator for custom service dialogs + some fixes for OrchestrationCatalogItem creation
{{pytest: --long-running --use-provider azure --use-provider ec2west cfme/tests/services/test_provision_stack.py }}

[1LP][RFR]fixing stack dialog filling

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[RFR] Uprev WT.core

---

cfme/tests/configure/test_logs.py

__Adding tests__ to cover provider logs verification. Full list of providers which have separate log can be found in CFME  Advanced Settings under `:log:` section

[1LP][RFR]test provider logs

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/template.txt

To pick up https://github.com/ManageIQ/wrapanapi/pull/261

[1LP][RFR]Bump wrapanapi to 2.9.2

---

cfme/utils/appliance/__init__.py
sprout/.gitignore
sprout/appliances/models.py
sprout/appliances/tasks.py
sprout/sprout.sh

This PR contains a bunch of sprout changes which are necessary for turning on preconfigured openshift appliances.
In addition, it restores mfalesni's sprout.sh script which is convenient to kick off sprout locally for testing/development purpose.
Besides that, there is .gitignore file for sprout which is convenient for development.

[1LP][RFR] preconfigured openshift sprout providers

---

cfme/tests/configure/test_tag.py

New collections for REST taggign testing
{{pytest: cfme/tests/configure/test_tag.py}}

[1LP][RFR]Added new collection for taging api testing

---

cfme/common/physical_server_views.py
cfme/physical/physical_server.py
cfme/tests/physical_infrastructure/ui/test_physical_server_details.py

This PR contains tests that verify that the storage and network devices links on the physical server summary page work correctly.
Depends on https://github.com/ManageIQ/wrapanapi/pull/252 and https://github.com/ManageIQ/integration_tests/pull/7221

[1LP][RFR][BLOCKED] Tests for the network and storage devices links

---

cfme/tests/automate/test_buttons.py
cfme/tests/cloud_infra_common/test_cockpit_server.py
cfme/tests/cloud_infra_common/test_relationships.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/configure/test_logs.py
cfme/tests/control/test_actions.py
cfme/tests/infrastructure/test_child_tenant.py
cfme/tests/infrastructure/test_individual_host_creds.py
cfme/tests/infrastructure/test_kubevirt.py
cfme/tests/infrastructure/test_project_quota.py
cfme/tests/infrastructure/test_quota_tagging.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/intelligence/reports/test_canned_corresponds.py
cfme/tests/intelligence/reports/test_views.py

[RFR] Added flags to some tests

---

cfme/utils/appliance/__init__.py

[1LP][RFR] Fixed a bad import

---

cfme/base/ui.py
cfme/tests/test_login.py

This adds a new test and some new implementation that goes with it.
Test creates new user, then tries to change user's password while logging in, then checks if user can't use the old password.
I opted for creating new user instead of just using the Administrator user. Changing the password for the Administrator user results in weird automation behaviour and also Sprout is not happy with it.

[1LP][WIP] Test updating password from the login screen

---

cfme/cloud/provider/azure.py
cfme/cloud/provider/ec2.py
cfme/cloud/provider/openstack.py
cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/scvmm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/networks/provider/nuage.py
cfme/physical/provider/lenovo.py
cfme/tests/configure/test_logs.py

Moved log_names to providers - closes #7286

[1LP][RFR] Moved log_names to providers

---

cfme/tests/networks/test_sdn_balancers.py
cfme/tests/networks/test_sdn_crud.py
cfme/tests/networks/test_sdn_downloads.py
cfme/tests/networks/test_sdn_inventory_collection.py
cfme/tests/networks/test_sdn_navigation.py
cfme/tests/networks/test_sdn_ports.py
cfme/tests/networks/test_sdn_topology.py

__Updating SDN tests__ with 'sdn' flag. needs MR 511 - https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/511

[1LP][RFR][NOTEST]tagging sdn tests

---

cfme/utils/ftp.py

[1LP][RFR] switch utils/ftp to bytesio

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[RFR] Updated navmazing

---

cfme/tests/infrastructure/test_quota.py

Implementing test case related to quota using automate method.
{{pytest: cfme/tests/infrastructure/test_quota.py -v}}

[1LP][RFR]Adding new file which includes test case related to quota

---

cfme/tests/cloud/test_cloud_events.py
cfme/tests/cloud_infra_common/test_events.py

__Fixing__  automation
{{pytest: --use-provider azure cfme/tests/cloud/test_cloud_events.py}}

[1LP][RFR]fixing azure event tests

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[RFR] uprev'd miq_version

---

cfme/configure/configuration/region_settings.py
cfme/tests/configure/test_paginator.py
setup.py

Convert map tagging to collections
{{pytest: -vvv -k test_paginator}}

[RFR][1LP] Map Tags to Collections

---

cfme/tests/cloud/test_providers.py

__Extending__ provider tests
{{pytest: --long-running --use-provider complete -k test_azure cfme/tests/cloud/test_providers.py}}

[1LP][RFR]adding azure provider tests

---

cfme/tests/automate/test_instance.py

{{pytest: -v -k "test_automate_instance_missing"}}

[1LP][RFR] Added test_automate_instance_missing

---

cfme/automate/import_export.py
cfme/tests/automate/test_git_import.py

{{pytest: -v -k test_automate_git_domain_removed_from_disk}}

[1LP][RFR] Added test_automate_git_domain_removed_from_disk

---

cfme/tests/services/test_pxe_service_catalogs.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

{{pytest: --long-running cfme/tests/services/test_pxe_service_catalogs.py}}

[RFR] new wrapanapi version + one fixed test

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/template.txt
scripts/template_upload_rhevm.py

extra arg was put into upload_template call, removed, unecessary

[1LP][RFR] Remove arg in template_upload_rhevm

---

cfme/common/host_views.py
cfme/infrastructure/host.py
cfme/tests/infrastructure/test_individual_host_creds.py

__Adding tests__ for other host credentials except 'default'
Needs ~~MR 500 & MR 512~~
{{pytest: --long-running --use-provider complete cfme/tests/infrastructure/test_individual_host_creds.py }}

[1LP][RFR] Adding host credential tests

---

cfme/cloud/instance/image.py
cfme/common/__init__.py
cfme/storage/volume.py
cfme/tests/cloud/test_providers.py
cfme/tests/infrastructure/test_host.py
cfme/tests/services/test_catalog_item.py
cfme/tests/storage/test_volume.py

Added more test to cover tag visibility, added TaggableCollection class to give an oportunity to select multiple items for tagging
Shriver: updated pytest line to include more tests
{{pytest: -k 'test_tag_host_after_provider_delete or test_multiple_cloud_volumes_tag_edit or test_tagvis_provision_fields or test_restricted_catalog_items_select_for_catalog_bundle' -vvv}}

[1LP][RFR] Some more tags test

---

cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

__Adding widget__ for v2v migration not started/completed list
**UPSTREAM ONLY**
{{pytest: cfme/tests/v2v/test_v2v.py -v }}

[1LP][RFR] Adding new widget to capture migrations not started/completed list in v2v

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_multiple_vms --long-running --use-provider complete}}

[1LP][RFR] Multiple vms ssa test

---

cfme/configure/access_control/__init__.py
cfme/tests/cloud_infra_common/test_tag_visibility.py
cfme/tests/configure/test_access_control.py
widgetastic_manageiq/expression_editor.py

{{pytest: cfme/tests/configure/test_access_control.py cfme/tests/cloud_infra_common/test_tag_visibility.py  -k 'test_group_crud_with_tag or test_tag_expression' --use-provider rhv42 --use-provider ec2west --use-provider vsphere6-nested }}

[1LP][RFR]New tag expression tests

---

cfme/networks/balancer.py
cfme/networks/cloud_network.py
cfme/networks/network_port.py
cfme/networks/network_router.py
cfme/networks/provider/__init__.py
cfme/networks/security_group.py
cfme/networks/subnet.py

- I found some time tests are failing due to `Entity {'name': u'x'} isn't found on this page`. 
- best to allow surf pages for entity.

[1LP][RFR][NOTEST] Allow surf_pages for Network pages

---

cfme/tests/networks/test_sdn_balancers.py

{{pytest: cfme/tests/networks/test_sdn_balancers.py::test_sdn_balancers_tagvis --use-provider azure -sqvv}}

[1LP][RFR] fix sdn balancer tagvis test

---

cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

__Adding New Widget__ for Infrastructure Mapping List. It is partially COMPLETE, needs few enhancements, which have not been delivered by ManageIQ Devel Team yet, as they provide those, I will extend this PR, if they come before this PR is merged, I will update PR with those changes, else submit a different PR later. 
**UPDATE**: Aforementioned enhancements  still far out in devel hence I'd like to request this PR to merge. Enhancements will be submitted in different PR later.
**UPDATE 2**:Received changes from Devel, updated PR to reflect everything. It should be complete now.
{{pytest: cfme/tests/v2v/test_v2v.py -v }}

[1LP][RFR] Added new widget Infra Mappings List

---

cfme/containers/container.py
cfme/containers/image.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/provider/__init__.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/template.py
cfme/containers/volume.py
cfme/tests/containers/test_ad_hoc_metrics.py
cfme/tests/containers/test_alerts.py
cfme/tests/containers/test_basic_metrics.py
cfme/tests/containers/test_logging.py
cfme/tests/containers/test_tables_sort.py
widgetastic_manageiq/__init__.py

{{ pytest: cfme/tests/containers/test_alerts.py cfme/tests/containers/test_basic_metrics.py cfme/tests/containers/test_logging.py cfme/tests/containers/test_tables_sort.py --use-provider ocp-36-hawk }}

[RFR] CMQE Automation Fixes and Fix to ManageIQ Table Sort

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

Depends on https://github.com/RedHatQE/miq_version/pull/7 to be released

Bump miq-version

---

cfme/configure/tasks.py
cfme/containers/image.py

Following cfme/configure/tasks.py update that has been done,
I had to fix cfme/containers/image.py perform_smartstate_analysis with correct task name,
That includes "Container Image Analysis: " prefix on task name.
Also, an update regarding  perform_smartstate_analysis_multiple_images,
update the following functions regarding TasksCollection:
is_finished, is_successfully_finished and wait_for_finished.
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis.py -v --use-provider ocp-37-hawk }}

[1LP][RFR] Fixing Container Images perform_smartstate_analysis with correct task name

---

cfme/scripting/quickstart/__init__.py
cfme/scripting/quickstart/__main__.py
cfme/scripting/quickstart/proc.py
cfme/scripting/quickstart/system.py
cfme/scripting/tests/test_quickstart.py

this pr simplifies quickstart and unifies how package names pass
it also splits parts of it to extra files, eventually supporting distinct invocation
this is prerequisite of preparing global/automated dockerfiles for this repo

[RFR] Split quickstart

---

cfme/tests/infrastructure/test_quota_tagging.py

Adding new test case related to Infra-quota-tagging and also renaming lifecycle related test case.
{{pytest: -v -k 'test_quota_tagging_infra_via_services' --use-provider rhv41}}

[1LP][RFR] Implementing Infra service quota tagging related test case.

---

cfme/markers/env_markers/provider.py

Fixed filtering for supported providers

[RFR] Fixed filtering for supported providers

---

cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

__Adding navigation/Views/Widgets__ for migration plan details page.
**Should be merged after #7343**

[1LP][RFR] V2v migration details page

---

cfme/common/provider.py

* It turns out that iterating the entrypoints is expensive, very
expensive.
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
3115684  149.962    0.000  322.137    0.000 (iter_entry_points)
263271918   78.278    0.000   96.130    0.000 (get_entry_map)
264051168   60.633    0.000   60.633    0.000 (__iter__)
278980146   19.371    0.000   19.390    0.000 {method 'get' of 'dict' objects}
263275585   15.413    0.000   15.413    0.000 {method 'values' of 'dict' objects}
```
* So I added some caches to the different iter_entry_points. The
function is now only called ```292``` times, instead of ```3,115,684``` times.
* It should be noted that those ```292``` times could be reduced. There are
other uses of iter_entry_points that are not included in these
changes.
* This …

[1LP][RFR] Caching for provider types

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
requirements/template_docs.txt
sprout/appliances/tasks.py
sprout/requirements.txt

it demands some changes in miq version. which are in progress

[RFR] Force sprout use miq version instead of its own regexps

---

cfme/utils/appliance/__init__.py
cfme/utils/appliance/plugin.py

[1LP][RFR] Update attr.ib convert -> converter

---

cfme/infrastructure/host.py
cfme/infrastructure/provider/__init__.py
cfme/tests/infrastructure/test_datastore_analysis.py
cfme/tests/infrastructure/test_esx_direct_host.py
cfme/tests/infrastructure/test_individual_host_creds.py
cfme/utils/hosts.py
conf/cfme_data.yaml.template

Purpose
Fixing configuring hosts credentials. Follows up #7261. Requires yamls update.
{{pytest: --long-running --use-provider complete cfme/tests/infrastructure/test_individual_host_creds.py }}

[WIPTEST] Fixed hosts credentials

---

cfme/tests/cloud/test_quota_tagging.py

Adding test case related to cloud quota tagging.
{{ pytest: cfme/tests/cloud/test_quota_tagging.py --use-provider complete -v }}

[1LP][RFR]Adding test case related cloud quota tagging.

---

cfme/tests/openstack/cloud/test_instances.py

After Instances were moved to collections, adjustment was needed on instance.py fixture
{{pytest: cfme/tests/openstack/cloud/test_instances.py::test_create_instance }}

[RFR] Adjust new instance fixture to use collections

---

cfme/utils/browser.py

[RFR] Fix for Wharf

---

cfme/fixtures/candu.py
cfme/tests/candu/test_vm_graph.py

- Automating Hourly and Daily graph for Vsphere Provider
{{pytest: cfme/tests/candu/test_vm_graph.py::test_graph_screen -v --use-provider complete}}

[1LP][RFR] Daily and Hourly graph tests

---

cfme/utils/browser.py

keyerror trying to delete it when it doesn't exist

[RFR] Only delete marionette on chrome if its there

---

cfme/tests/v2v/test_v2v.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

Commit1 shows expected thing to achieve with sample code.
Commit2 is final commit after that sample removal for reviews.

[1LP][RFR] v2v migration plan collections and widgets

---

cfme/tests/integration/test_cfme_auth.py

Utilizing users with an evmgroup and a custom ext-auth group, this test configures the necessary authentication mode, adds a group, logs in, and tests that groups can be switched for ext-auth users.
{{ pytest: cfme/tests/integration/test_cfme_auth.py -k test_user_group_switching --long-running }}

[1LP][RFR] Ext-auth group switching test

---

cfme/utils/browser.py

[RFR] Fixed an error

---

scripts/sync_template_tracker.py

Fix sync_template_tracker, ValueError handling
Add new arg to specify --provider-key args
Testing in Jenkins directly -- PASSED
PRT irrelevant, unless I broke collections via insanity.

[1LP][RFR] Update sync_template_tracker, fixes and new arg

---

cfme/common/__init__.py
cfme/configure/configuration/region_settings.py
cfme/fixtures/tag.py
cfme/generic_objects/instance/ui.py
cfme/infrastructure/config_management.py
cfme/tests/cloud_infra_common/test_retirement.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/configure/test_paginator.py
cfme/tests/configure/test_tag.py
cfme/tests/configure/test_tag_category.py
cfme/tests/infrastructure/test_config_management.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_quota_tagging.py
setup.py

Convert Categories and Tags to collections
{{pytest: -vvv -k 'test_generic_objects_tag_ui or test_paginator_details_page or test_tag_crud or test_category_crud or tagged_vm or test_user_remove_tag'}}

[1LP][RFR] Categories, Tags collection conversion

---

cfme/base/__init__.py
cfme/base/ui.py
cfme/configure/access_control/__init__.py
cfme/tests/webui/test_general_ui.py

General UI new tests
{{pytest: -vvv -k 'test_add_provider_trailing_whitespaces or test_configuration_large_number_of_tags'}}

[1LP][RFR] General UI new tests

---

cfme/infrastructure/host.py

[1LP][RFR] Fix host update method

---

sprout/appliances/tasks.py

It turned out that clone_template_to_appliance__clone_template worked wrongly when vm deployment failed but vm was created. 
That task tried to deploy vm once more if deployment had failed. What made logic sophisticated.
In addition, it didn't create DelayedProvisionTask and didn't remove broken vm if there were some errors during deployment though such logic existed.
I simplified this logic. That task makes basic clean up and creates DelayedProvisionTask and then terminates chain of deployment tasks if deployment has finished with errors.

[1LP][RFR] make sprout's clone template create new delayed task and remove failed appliance

---

cfme/ansible/repositories.py

Reverting back "Edit" destination after merging #7148 
{{pytest: -v -k test_embedded_ansible_repository_crud --long-running}}

[1LP][RFR] Fixed Ansible Repository edit

---

cfme/tests/infrastructure/test_provisioning_dialog.py

* Navigation was moved to the collection, not the class

[RFR] Fixed navigation issue

---

cfme/tests/cloud_infra_common/test_tag_visibility.py

Fix tag and category fixture creation

[RFR] Fix tag and category fixture creation

---

cfme/tests/configure/test_register_appliance.py

[RFR] Moved finalizer definition

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

Embedded Ansible shouldn't be in the reports

[RFR] Embedded Ansible shouldn't be in the reports

---

cfme/fixtures/service_fixtures.py
cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py

Fix test_service_start for azure. ec2 
{{pytest: --long-running --use-provider ec2west  --use-provider azure cfme/tests/ssui/test_ssui_myservice.py -k test_service_start}}

[1LP][RFR] Fixed test Service Start for Azure and EC2

---

cfme/base/ui.py
cfme/common/candu_views.py
cfme/tests/candu/test_gap_collection.py

- Gap collection tests for VM and Host
{{pytest: cfme/tests/candu/test_gap_collection.py -v --use-provider complete}}

[1LP][RFR] Gap Collection C&U

---

cfme/networks/provider/__init__.py

Nuage needed to correctly pass the class for instantiation

[1LP][RFR] Fixed creation of Nuage Provider

---

cfme/utils/bz.py
conf/cfme_data.yaml.template
conf/env.yaml.template

There is corresponding RH CFME QE yaml change.
Thanks @izapolsk for raising the issue of failing travis runs

[1LP][RFR] Add Bugzilla default URL for Travis

---

cfme/tests/cli/test_appliance_cli.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/configure/test_log_depot_operation.py
cfme/tests/control/test_compliance.py
cfme/tests/infrastructure/test_vm_power_control.py
cfme/utils/bz.py

Seeing this break test collection

[1LP][RFR] Fix BZ blocker use (remove uncollectif)

---

sprout/appliances/models.py
sprout/appliances/tasks.py

There is some weird issue in sprout. It is difficult to figure out exact reason w/o enough logging.

[1LP][RFR] adding some logging to sprout

---

cfme/tests/containers/test_projects_dashboard.py

Following changes in wrapanapi that affect our container tests, 
I needed to update test_project_dashboard function with new wrapanapi methods
And attributes name.
This test should run on appliance version 5.9 and above.
{{pytest: cfme/tests/containers/test_projects_dashboard.py -v --use-provider ocp-37-prom }}

[1LP][RFR] Update Container test project dashboard according to wrapanapi changes

---

cfme/fixtures/tag.py
cfme/tests/cloud_infra_common/test_tag_visibility.py

{{pytest: --long-running --use-provider=rhos11 cfme/tests/cloud_infra_common/test_tag_visibility.py}}

[1LP][RFR] fixed tag tests broken by collections conversion

---

cfme/tests/infrastructure/test_provisioning_rest.py

Must wait until #7463 is merged.

[WIP] Fixing typo in BZ wrapper for test_provision_attributes

---

requirements/template.txt
requirements/template_docs.txt

the freeze has a few bigger updates and we may need to limit the freeze update to sort out the details

[RFR] fix pinnns for wrapanapi pre 3.x and add gevent to the templates

---

cfme/utils/trackerbot.py

[RFR] Added limit_ts

---

cfme/tests/optimize/test_bottlenecks.py

{pytest:: cfme/tests/optimize/test_bottlenecks.py}
required https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/562

[1LP][RFR]Fix bottlenecks tests

---

cfme/tests/configure/test_db_backup_schedule.py

{{pytest:: -k test_db_backup_schedule}}

[1LP][RFR]Fix dict key for test_db_backup_schedule

---

cfme/common/__init__.py
cfme/tests/cloud_infra_common/test_tag_objects.py

Remove duplication for cloud anf infra providers, after selectors update
{{pytest: cfme/tests/cloud_infra_common/test_tag_objects.py}}

[1LP][RFR]Update cloud/infra tagging tests

---

cfme/utils/providers.py

[1LP][RFR] fix get mgmt

---

cfme/physical/physical_server.py

this PR is intended to be merged if [this PR in wrapanapi](https://github.com/ManageIQ/wrapanapi/pull/288) is accepted, in order to avoid tests breaking.

[1LP][RFR][W3] refactor lenovo physical server to adequate to lenovo system changes

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
scripts/ocp_cleanup.py

Requires: https://github.com/ManageIQ/wrapanapi/pull/302

[1LP][RFR] ocp servers cleanup script

---

cfme/base/__init__.py
cfme/fixtures/authentication.py
cfme/roles.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py
cfme/tests/integration/test_cfme_auth.py

Update access control tree for 510z
BZ blocks 59z testing.
{{ pytest: --long-running  -vv cfme/tests/integration/test_aws_iam_auth_and_roles.py }}

[1LP][RFR] Update aws_iam auth/RBAC test, new access tree in 510z

---

cfme/automate/buttons.py

{{pytest: -v cfme/tests/automate/test_buttons.py::test_button_crud}}

[1LP][RFR] Fixed creation of custom buttons

---

cfme/ansible_tower/explorer.py
cfme/ansible_tower/jobs.py
cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/host_aggregates.py
cfme/cloud/instance/__init__.py
cfme/cloud/instance/image.py
cfme/cloud/keypairs.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/common/host_views.py
cfme/common/physical_server_views.py
cfme/common/provider_views.py
cfme/containers/build.py
cfme/infrastructure/cluster.py
cfme/infrastructure/config_management.py
cfme/infrastructure/datastore.py
cfme/infrastructure/resource_pool.py
cfme/infrastructure/virtual_machines.py
cfme/networks/views.py
cfme/services/myservice/ui.py
cfme/services/workloads.py
cfme/storage/object_store_container.py
cfme/storage/object_store_object.py
cfme/storage/volume.py
cfme/storage/volume_backup.py
cfme/storage/volume_snapshot.py
cfme/tests/webui/test_advanced_search.py
setup.py

Added two global parametrized advanced_search tests for checking whether advanced search is possible.
Also had to add some navmazing code for tested pages.
More tests for advanced search/filters are on the way.

[1LP][RFR] Added two parametrized advanced_search tests

---

cfme/tests/containers/test_projects_dashboard.py

{{ pytest : cfme/tests/containers/test_projects_dashboard.py::test_project_has_provider --use-provider ocp-36-hawk }}

[1LP][RFR] Add test for validating provider column in all projects table

---

cfme/physical/provider/lenovo.py

this PR adds the mgmt property to the Lenovo Provider. the lack of this property were breaking some tests.
depends on #7470

[1LP][RFR] add mgmt property to Lenovo Provider

---

cfme/fixtures/appliance.py
cfme/test_framework/sprout/client.py
cfme/tests/pod/test_appliance_crud.py

This PR will add smoke tests for pod apliance.

[1LP][RFR] pod appliance test cases automation

---

artifactor/plugins/logger.py
artifactor/plugins/post_result.py
widgetastic_manageiq/__init__.py

[1LP][RFR] sort out Py3k issue in artifactor

---

cfme/cloud/provider/ec2.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

PRT run:
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_vm -vvvv --long-running --use-provider ec2west }}

[1LP][RFR] This PR will automate SSA on EC2 instance.

---

cfme/control/explorer/policies.py

{{pytest: -v cfme/tests/control/test_basic.py::test_policy_crud --long-running}}

[RFR][1LP] Fixed Control policies CRUD operations

---

cfme/networks/provider/__init__.py

- TypeError: instantiate() takes at least 2 arguments (1 given): 7 error in sheet
- Instantiate method needs provider class so added that.
{{pytest: cfme/tests/networks/test_sdn_navigation.py --use-provider azure -sqvv}}

[RFR] Fix: Instantiate Method error in N/W

---

cfme/tests/v2v/test_v2v_migrations.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv}}

[1LP][RFR] End to end migration: stage one

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
scripts/cleanup_old_vms.py

Running locally with wrapanapi fixes.

[RFR][1LP] Cleanup vms handle error

---

cfme/storage/manager.py

Note: module pages does not need direct assert message
{{ pytest: cfme/tests/storage/test_manager.py::test_manager_navigation --use-provider complete }}

[1LP][RFR] Fixed AssertionError 

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/infrastructure/test_host_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

the `host_data,` type unpacking raises a ValueError when there are multiple items in the list.

[RFR] Fix ValueError in host yaml lookup

---

cfme/utils/appliance/implementations/ui.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

Fixed FF60 inside our repo for testing

[1LP][RFR] Fixed FF60 inside our repo for testing

---

cfme/common/vm_views.py
cfme/services/catalogs/catalog_items/__init__.py

{{pytest: cfme/tests/services/test_myservice.py -v --long-running --use-provider vsphere65}}
Changing the order to items to be filled because if the dropdowns are filled after filling textboxes , values in dropdown are reset and lost (somehow, selenium bug )

[1LP][RFR] Jenkins failure fix

---

cfme/tests/infrastructure/test_advanced_search_host.py

Host collections are now accessible from the provider

[1LP][RFR] Host collections are now accessible from the provider

---

cfme/infrastructure/virtual_machines.py

* The NavigationDestinationNotFound is internal to navmazing and though
it could be raised here, it would probably give an errorneous error :)
It would say something like, "can't find destination [Page] in object,
available destinations [Page]" which would lead to confusion.
* If we really can't navigate, let the error bubble.
This is +212 in latest jenkins run

[RFR] Fixed destination error

---

cfme/tests/infrastructure/test_config_management.py

Few fixes for Ansible Tower tests.
{{pytest: cfme/tests/infrastructure/test_config_management.py -v -k "cfme/tests/infrastructure/test_config_management.py"}}

[1LP][RFR] few fixes for Ansible Tower tests

---

conf/supportability.yaml.template

Nuage is now in supportability templete so test get collected.

[1LP][RFR] Add Nuage to supportability template

---

cfme/common/candu_views.py
cfme/tests/candu/test_host_graph.py

- Host Hourly and Daily Graph automation
- Infrastructure provider support host
{{pytest: cfme/tests/candu/test_host_graph.py::test_graph_screen -v --use-provider complete}}

[1LP][RFR] Host hourly and daily Utilization for Vsphere

---

cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/utils/testgen.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

__Adding tests__ for feature v2v UI validations.
{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv }}

[1LP][RFR] V2v ui validations

---

cfme/utils/dockerbot/pytestbase/setup.sh

[1LP][RFR] dockerbot: correct rm statement and remove the force so we notice errors

---

cfme/common/provider.py
cfme/infrastructure/host.py

Intent
==============
`all()` method in HostsCollection uses REST API. Thanks @mkoura for the help.
{{pytest: -v -k "test_schedule_timer or test_vm_migrate or test_host_drift_analysis" --long-running}}

[1LP][RFR] HostsCollection.all() uses REST API

---

cfme/common/physical_switch_views.py
cfme/physical/physical_switch.py
cfme/tests/physical_infrastructure/ui/test_physical_switch_details.py
cfme/tests/physical_infrastructure/ui/test_physical_switch_list.py
entry_points.txt

__Adding tests__ for Physical Switches to cover basic UI test cases.

[1LP][RFR] Adding Physical Switches basic UI tests

---

cfme/optimize/utilization.py
entry_points.txt

[1LP][RFR][NOTEST] collection of utilization

---

cfme/common/vm.py
cfme/common/vm_views.py
cfme/utils/appliance/implementations/ui.py

1. Fixed template select in provision table
2. Added BZ blocker for 5.10
{{pytest: cfme/tests/cloud_infra_common/test_provisioning.py -k test_provision_approval}}

[1LP][RFR] provision tests/views fixes

---

cfme/common/vm_views.py

[RFR] run pre-commit to restore a passing lint stage

---

cfme/fixtures/provider.py

Templates added via merged MRs
https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/575
https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/582
Adding template fixtures which are under cfme_data.yaml templates section.

[1LP][NOTEST][RFR] Adding template related fixtures under cfme.fixtures.provider.py

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[RFR] upgrade the cryptography pin to sort out the cve warning

---

cfme/configure/configuration/diagnostics_settings.py
cfme/tests/configure/test_log_depot_operation.py

{{pytest: cfme/tests/configure/test_log_depot_operation.py}}

[1LP][RFR]Fix log collection tests

---

cfme/tests/candu/__init__.py
cfme/tests/candu/test_host_graph.py
cfme/tests/candu/test_vm_graph.py

{{pytest: cfme/tests/candu/test_vm_graph.py -k test_graph_screen -v --use-provider complete}}

[1LP][RFR] support for azure ec2 and rhv graph

---

cfme/common/vm.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
cfme/tests/intelligence/chargeback/test_resource_allocation.py
cfme/tests/intelligence/reports/test_metering_report.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py

* This function took just a username, it has been altered to now take an
object instead.

[1LP][RFR] Moving ownership function to use objects

---

cfme/tests/containers/test_smart_management.py

I this PR I simply added a BZ blocker decorator for one of our tests.

[1LP][RFR] Adding blocker for smart mgmt tests

---

cfme/tests/openstack/infrastructure/test_hosts.py
cfme/tests/openstack/infrastructure/test_roles.py

Remove provider argument from host collection all on test_hosts.py 
{{ pytest: cfme/tests/openstack/infrastructure/test_hosts.py }}

[1LP][RFR] Remove provider argument from host collection all

---

cfme/tests/openstack/cloud/test_instances.py

[1LP][RFR] Update openstack/cloud/test_instances

---

cfme/configure/configuration/analysis_profile.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/configure/test_analysis_profiles.py
cfme/tests/configure/test_paginator.py
cfme/tests/control/test_compliance.py
cfme/tests/infrastructure/test_ssa_vddk.py
entry_points.txt

{{pytest: cfme/tests/configure/test_analysis_profiles.py}}

[1LP][RFR] AnalysisProfile collection conversion

---

cfme/common/vm.py
cfme/tests/cloud/test_quota_tagging.py
cfme/tests/cloud/test_tenant_quota.py

Adding new test case related to quota and providing fix for a test case failure.
{{pytest: -v -k 'test_tenant_quota_enforce_via_lifecycle_cloud' --use-provider complete}}

[1LP][RFR] Adding new test case and implementing fix for the a failure.

---

cfme/utils/appliance/__init__.py
cfme/utils/appliance/implementations/__init__.py
cfme/utils/appliance/implementations/rest.py
cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py

* This function spans all the navigators and gives a dict of
implementation name and navigations

[1LP][RFR] Added the ability for any object to have a list destinations fn

---

cfme/optimize/bottlenecks.py
cfme/tests/optimize/test_bottlenecks.py
entry_points.txt

{{pytest: cfme/tests/optimize/test_bottlenecks.py}}

[1LP][RFR] Bottlenecks collection conversion

---

cfme/cloud/availability_zone.py
cfme/common/candu_views.py
cfme/tests/candu/test_azone_graph.py

- Added `wait_candu_data_available` method in Azone Model Page
- Added `Utilization` navigation in the model page with returning View
- Added `AzoneCloudUtilizationView` in candu view page
- Added Hourly graph support test in new `cfme/candu/azone.py` file.
{{pytest: cfme/tests/candu/test_azone_graph.py -v --use-provider complete}}

[1LP][RFR] Azone Graph Initial commit

---

cfme/tests/openstack/cloud/test_volume_backup.py

Added 2 tests:
1. test_create_volume_backup
2. test_create_volume_incremental_backup
{{ pytest: cfme/tests/openstack/cloud/test_volume_backup.py --use-provider rhos11 }}

[1LP][RFR] Added 2 new volume backup tests

---

cfme/dashboard.py

{{pytest: -v cfme/tests/intelligence/test_dashboard.py::test_widgets_reorder}}

[1LP][RFR] Fixed dashboard widget column locator

---

cfme/common/vm_views.py

{{pytest: -v cfme/tests/control/test_actions.py::test_action_power_on_audit --long-running}}

[1LP][RFR] Fixed KeyError: 'total_snapshots' in openstack tests

---

cfme/utils/template/base.py
cfme/utils/template/virtualcenter.py

Locally tested with several uploads

[1LP][RFR] Update template upload, ovftool error logging

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt

includes ec2 fix, OCP enhancement, and some ext provider additions.

[RFR] wrapanapi 3.0.22

---

cfme/tests/pod/test_appliance_crud.py
cfme/utils/ssh.py

REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/322
{{ pytest: cfme/tests/pod/test_appliance_crud.py --use-provider cm-pod1  }}

[1LP][RFR] ansible deployment test for pod appliance

---

cfme/base/ui.py

{{pytest: -v cfme/tests/automate/test_domain.py::test_domain_import_git}}

[1LP][RFR] Fixed test_domain_import_git

---

cfme/common/candu_views.py
cfme/infrastructure/cluster.py
cfme/tests/candu/test_cluster_graph.py

- Added graph automation for Cluster
{{pytest: cfme/tests/candu/test_cluster_graph.py -v --use-provider complete}}

[1LP][RFR] Initial cluster graph commit

---

cfme/cloud/instance/openstack.py
cfme/tests/openstack/cloud/test_instances.py

Added the following:
1. test_instance_attach_volume
2. attach_volume method
3. dettach_volume
4. volume_count property
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_volume --use-provider rhos11 }}

[1LP][RFR] Added test_instance_attach_volume and related methods

---

cfme/automate/explorer/method.py

{{pytest: -v -k "test_method_inputs or test_schema_crud"}}

[1LP][RFR] Fixed test_method_inputs

---

cfme/fixtures/service_fixtures.py

PRT Run: 
{{ pytest: cfme/tests/ssui/test_ssui_service_catalogs.py -k test_service_catalog_crud_ssui -vvvv --long-running --use-provider azure --use-provider ec2west --use-provider gce --use-provider openstack }}
All services/ssui cloud test cases were failing while creating the catalog item in 5.9.4
eg: 
http://infra-trackerbot2.cfme2.lab.eng.rdu2.redhat.com/ostriz/dini/?stream_report=downstream-59z&source=jenkins#cfme/tests/ssui/test_ssui_myservice.py/test_myservice_crud[ec2-ViaSSUI]

[1LP][RFR] Fix test service/ssui tests for cloud provider

---

cfme/containers/provider/__init__.py
cfme/tests/containers/test_tables_fields.py

{{ pytest : cfme/tests/containers/test_tables_fields.py   --use-provider ocp-39-hawk }}
Added table object to ContainerObjectAllBaseView

[RFR] Added table object to ContainerObjectAllBaseView

---

cfme/scripting/sprout.py
cfme/test_framework/appliance.py
cfme/test_framework/sprout/plugin.py
cfme/utils/appliance/__init__.py

* also added via populate-yamls for the checkout command
or
or
or
--

[1LP][RFR][poc] initial support for explicitly passing of the appliance version

---

cfme/tests/automate/test_provisioning_dialogs.py

{{pytest: cfme/tests/automate/test_provisioning_dialogs.py::test_provisioning_dialog_crud -v}}

[1LP][RFR] Fixed test_provisioning_dialog_crud

---

cfme/services/service_catalogs/ui.py
cfme/tests/ansible/test_embedded_ansible_services.py

{{pytest: -v cfme/tests/ansible/test_embedded_ansible_services.py::test_custom_button_ansible_credential_list --long-running}}

[1LP][RFR] Fixed test_custom_button_ansible_credential_list

---

cfme/markers/rhv.py

We're parsing jUnit XML output in Report Portal and it would be very nice to filter test cases there based on tiers. This change will expose RHV tiers as properties. Example here:
```
<testcase classname="cfme.tests.intelligence.reports.test_canned_corresponds" file="cfme/tests/intelligence/reports/test_canned_corresponds.py" line="115" name="test_operations_vm_on[rhv_cfme_integration]" time="10.0113461018">
<properties>
<property name="rhv_tier" value="rhv2"/>
</properties>
</testcase>
```
If the tier is exposed as a property, we can propagate it into Report Portal as a tag.
Verification run [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CFME-DEV/job/cfme-5.9-rhv-4.2-integration-test-dev/). XML report from it [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view …

[1LP][RFR] Adding RHV tier as property to XML report

---

cfme/tests/infrastructure/test_ssa_vddk.py

PRT run:
{{ pytest: cfme/tests/infrastructure/test_ssa_vddk.py -vvvv --long-running --use-provider vsphere6-nested }}

[1LP][RFR] This PR will fix the scope of test and updated with Analysis profile create method.

---

cfme/containers/container.py
cfme/containers/image.py
cfme/containers/image_registry.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/template.py
cfme/containers/volume.py
cfme/tests/containers/test_ad_hoc_metrics.py
cfme/tests/containers/test_basic_metrics.py
cfme/tests/containers/test_breadcrumbs.py
cfme/tests/containers/test_cockpit.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_logging.py
cfme/tests/containers/test_properties.py
cfme/tests/containers/test_relationships.py
cfme/tests/containers/test_reports.py
cfme/tests/containers/test_static_custom_attributes.py
cfme/tests/containers/test_tags.py
cfme/utils/appliance/__init__.py

{{ pytest: cfme/tests/containers/test_cockpit.py  cfme/tests/containers/test_basic_metrics.py cfme/tests/containers/test_ad_hoc_metrics.py cfme/tests/containers/test_logging.py cfme/tests/containers/test_tags.py cfme/tests/containers/test_static_custom_attributes.py  cfme/tests/containers/test_properties.py cfme/tests/containers/test_reports.py cfme/tests/containers/test_breadcrumbs.py cfme/tests/containers/test_relationships.py   --use-provider ocp-36-hawk --use-provider ocp-39-hawk }}

[1LP][RFR] CMQE Stabilization Effort

---

cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py

{{ pytest : cfme/tests/containers/test_reload_button_provider.py --use-provider ocp-39-hawk }}
Updating automation after provider summary tables fields were changed .

[RFR] Updating provider summary tables fields

---

cfme/rest/gen_data.py
cfme/tests/infrastructure/test_infra_tag_filters_combination.py
cfme/tests/infrastructure/test_rest_automation_request.py
cfme/tests/infrastructure/test_rest_templates.py
cfme/tests/infrastructure/test_vm_retirement_rest.py
cfme/tests/services/test_rest_services.py

mostly rest tests, followup to #7306
PRT failures for 59z for dialog_service_name are addressed in #7652

[1LP][RFR] Remove last a_provider uses

---

sprout/appliances/tasks.py

sprout started to reboot rhev appliances after changes in wrapanapi->rhevm module. It didn't check appliance state after rename. So, this Pr should fix this issue by adding a web ui check after rename

[1LP][RFR] fix for issue when sprout restarts rhev appliances after delivery

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Changing label of smartstate agent, cleanup job will remove it from respective provider.

[NOTEST][RFR][1LP] This PR will change label of smartstate agent.

---

cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py

Forgot to add this in my original PR.

[1LP][RFR][NOTEST] Adding RHV tier to test_provision_cloud_init

---

cfme/utils/appliance/__init__.py
cfme/utils/appliance/services.py

Apply the httpd workaround on all streams

[1LP][RFR] Update httpd workaround for 59z

---

cfme/tests/configure/test_register_appliance.py

Version pick the repo names
Needs cfme-qe-yamls MR#613

[1LP][RFR] Update test_register_appliance

---

cfme/automate/buttons.py
cfme/tests/automate/test_buttons.py

- Added ColorPicker in create method
- Create attributs imporve and changes in fill method
- sorted inputs 
- Added parametrize test for group crud for all objects 5.9 and 5.10
{{pytest: cfme/tests/automate/test_buttons.py::test_button_group_crud -v}}

[1LP][RFR] Custom Button: Group crud parametrization for All objects

---

cfme/utils/appliance/__init__.py

starting httpd causes APIExceptions and 503 responses from the endpoints
Don't start httpd immediately, let it start with evmserverd
Add logger_wrap to the method
Tested across providers and 59, 58, 510

[RFR] Do not start httpd during httpd.service workaround

---

cfme/tests/infrastructure/test_advanced_search_host.py

{{pytest: -v cfme/tests/infrastructure/test_advanced_search_host.py::test_host_filter_save_cancel}}

[1LP][RFR] fixed test_host_filter_save_cancel

---

sprout/appliances/tasks.py

We have gaps in logging during appliance killing. This PR intends to partially fix this issue.

[RFR] added some sprout logging during killing appliance

---

cfme/tests/automate/test_buttons.py

- Parametrize button crud test for all avaialable object of 5.9 and 5.10.
{{pytest: cfme/tests/automate/test_buttons.py::test_button_crud -v}}

[1LP][RFR] Custom button crud parametrization

---

cfme/tests/ssui/test_ssui_myservice.py

[1LP][RFR][NOTEST] Blocking test_service_start with BZ1511099

---

cfme/containers/provider/__init__.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_logging.py

Few small fixes for failing tests. 
{{ pytest:   cfme/tests/containers/test_labels.py cfme/tests/containers/test_logging.py cfme/tests/containers/test_projects_dashboard.py --use-provider ocp-39-hawk }}

[RFR] CMQE Minor Test Fixes

---

cfme/tests/cli/test_appliance_console.py

__Adding tests__ for setting the appliance IP address.
Shriver: limiting PRT
{{ pytest: cfme/tests/cli/test_appliance_console.py  -k 'test_appliance_console_static_ipv4 or test_appliance_console_static_ipv6 or test_appliance_console_dhcp' }}

[1LP][RFR] Add test for appliance console IP configuration

---

cfme/tests/infrastructure/test_advanced_search_host.py

{{pytest: -v cfme/tests/infrastructure/test_advanced_search_host.py::test_host_filter_without_user_input}}

[1LP][RFR] fixed test_host_filter_without_user_input and host_with_median_vm

---

cfme/control/explorer/conditions.py
cfme/tests/control/test_basic.py

{{ pytest: -v cfme/tests/control/test_basic.py -k 'test_modify_condition_expression or test_assign_condition_to_control_policy or test_condition_crud' --long-running }}

[1LP][RFR] fixed error: str object has no attribute pick; added import wait_for

---

cfme/tests/infrastructure/test_individual_host_creds.py

{{ pytest: -v cfme/tests/infrastructure/test_individual_host_creds.py::test_host_bad_creds }}

[1LP][RFR] fixed test_host_bad_creds

---

cfme/cloud/provider/openstack.py

- Avoiding to fill `AMQP` even credentials in create method for OpenStack.
- We are facing AMQP credential validation BZ[0]
[0] https://bugzilla.redhat.com/show_bug.cgi?id=1618700

[1LP][WIPTEST] Skipping AMQP event with BZ

---

cfme/tests/infrastructure/test_iso_provisioning.py

Uncovered new bug during development of this test case.

[RFR][NOTEST] Skipping test_iso_provision_from_template due to BZ1613326

---

cfme/tests/containers/test_containers_smartstate_analysis.py
cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
cfme/tests/containers/test_provider_openscap_policy_attached.py
cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py

{{ pytest: cfme/tests/containers/test_containers_smartstate_analysis.py cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py cfme/tests/containers/test_provider_openscap_policy_attached.py cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py --use-provider ocp-36-hawk }}

[1LP][RFR] Add 5.10 stream to Blocking Bug 1620068 for CMQE Smartstate Tests

---

cfme/fixtures/physical_switch.py
cfme/test_framework/pytest_plugin.py
cfme/tests/physical_infrastructure/api/test_physical_switch_api.py
cfme/tests/physical_infrastructure/api/test_physical_switch_inventory_api.py

This PR adds initial API tests for Lenovo switches.

[1LP][RFR] Add initial Lenovo switches API tests

---

cfme/utils/events.py

{{ pytest: --long-running --use-provider vsphere65-nested cfme/tests/cloud_infra_common/test_events.py }}
There is bug found in EventListener found by @miha-plesko. This PR intends to fix it.

[RFR] fix of issue when new events aren't compared against all expected events

---

scripts/list_provider_vms.py

Jenkins already running from this branch.

Fix list provider vms

---

cfme/tests/openstack/infrastructure/test_hosts.py

Added new tests: 
test_hypervisor_hostname
test_hypervisor_hostname_views
{{ pytest: cfme/tests/openstack/infrastructure/test_hosts.py::test_hypervisor_hostname cfme/tests/openstack/infrastructure/test_hosts.py::test_hypervisor_hostname_views }}

[1LP][RFR] Add Hypervisor hostname tests

---

cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py

__Updating tests__ with BZ blocker

[RFR] test_provision_cloud_init blocked with BZ 1619744

---

cfme/tests/infrastructure/test_datastore_analysis.py

{{ pytest: -v cfme/tests/infrastructure/test_datastore_analysis.py::test_run_datastore_analysis }}

[1LP][RFR] fixed AttributeError in test_run_datastore_analysis

---

cfme/tests/configure/test_session_timeout.py

{{ pytest: -v cfme/tests/configure/test_session_timeout.py::test_bind_timeout_rest }}

[1LP][RFR] fixed AttributeError in test_bind_timeout_rest

---

cfme/common/vm_views.py
cfme/infrastructure/provider/kubevirt.py
cfme/tests/infrastructure/test_kubevirt.py

>Requirement: yaml PR 481
Added new tests for KubeVirt provider
- CRUD test for VM
- Power management test for a test VM
{{ pytest: -vvvv cfme/tests/infrastructure/test_kubevirt.py --use-provider kubevirt }}

[1LP][RFR] Added new tests for KubeVirt

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[1LP][RFR] bump pycryptodome after cve

---

cfme/tests/cloud/test_quota_tagging.py

{{ pytest: cfme/tests/cloud/test_quota_tagging.py::test_quota_tagging_cloud_via_lifecycle --use-provider complete }}

[1LP][RFR] Fixed vm provisioning error in quota test

---

cfme/tests/networks/nuage/test_events_are_triggered.py
requirements/frozen.py3.txt

With this commit we add a test to verify that events are being recieved by MIQ.

[1LP][RFR] Check that Nuage events are emitted and received

---

.gitignore

updated `gitignore` for `geckodriver` and `vscode`

[1LP][RFR] Updated gitignore

---

cfme/infrastructure/deployment_roles.py

- No need of quad icon normal `BaseEntitiesView` will work on All page views.
- It  will fix all navigation failures facing by @dkholodo 
- Not adding the test as we don't have `under cloud` provider.
- Tested it locally. working awesome. thanks to @dkholodo for an appliance. 
Local  Results:
http://pastebin.test.redhat.com/640753

[1LP][RFR][NOTEST] fix for deployment role entity

---

cfme/tests/cloud_infra_common/test_provisioning.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_tag }}

[RFR] added instance cleanup

---

cfme/base/credential.py
cfme/common/provider.py

Jenkins verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.8-rhv-4.2-integration-flow-dev/97/

[1LP][RFR] Fixing provider creation and deleteion for 5.8

---

cfme/common/candu_views.py
cfme/configure/configuration/region_settings.py
cfme/fixtures/candu.py
cfme/tests/candu/__init__.py
cfme/tests/candu/test_host_graph.py

{{pytest: cfme/tests/candu/test_host_graph.py::test_tagwise -v --use-provider complete}}

[1LP][RFR] VM TagWise graph for host

---

cfme/tests/infrastructure/test_provisioning_rest.py

Verified:
Test pass, but sometimes there is a problem with the cleanup- VM removal.
This is handled by rhrazdil PR ManageIQ/wrapanapi#329
A RHV only addition:
Expanding the provision rest testing, to include RHV vlan added options:
<Empty> & Profile name (network name). 
This should cover customer Bug 1574351 - prov.set_vlan() method didn't set the vnicprofiles identifier.
VM provision Rest api, network options, for RHV provider:
1) "vlan": "3a8dce01-dd59-4a46-8a6f-823acccda79f" (specific vnic profile ID) 
- Not covered yet. 
2) "vlan": <Empty> (no vNIC profile) 
- Covered in this PR, by 'test_provision_vlan'
3) "vlan": <Template> (use template's default vNIC profile) 
- Already covered in existing code, by 'test_provision' 
4) "vlan": "profile_name(network_name)" (Specific vnic …

[1LP][RFR] Expand provision test to check more vlan options for RHV provider

---

cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_individual_host_creds.py

Adding BZ wrapers for test host creds test cases for 5.8 stream.

[1LP][RFR][NOTEST] Add BZs for test host creds cases

---

cfme/infrastructure/cluster.py
cfme/tests/infrastructure/test_cluster_analysis.py
cfme/tests/infrastructure/test_delete_infra_object.py

- Added all method for cluster Entity with REST
{{pytest: cfme/tests/infrastructure/test_cluster_analysis.py::test_run_cluster_analysis cfme/tests/infrastructure/test_delete_infra_object.py::test_delete_cluster_appear_after_refresh cfme/tests/infrastructure/test_delete_infra_object.py::test_delete_cluster_from_table -sqvv --use-provider vsphere55}}

[1LP][RFR] all method for cluster

---

cfme/fixtures/provider.py
cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

__Adding new tests__ for v2v vm migrations
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv --long-running}}

[1LP][RFR] V2v migration tests

---

cfme/cloud/flavor.py
cfme/cloud/instance/openstack.py
cfme/tests/openstack/cloud/test_flavors.py

Add test test_create_instance_with_zero_disk_flavor  including related mothods
{{ pytest: cfme/tests/openstack/cloud/test_flavors.py }}

[1LP][RFR] Add flavor methods and tests

---

cfme/storage/manager.py
cfme/tests/storage/test_manager.py

- Added `all` method for `Block storage manager` supporting ec2 and rhos
- Added `all` method for `Object storage manger` supporting rhos. ec2 not support object storage
- Added changes in `test_mangers.py` as per collection all method. 
- Sometime after `storage manager` deletion'  provider still available in broken condition. BZ-1613420 not fixed on 5.9 OpenStack deletions operation need to call two times so better to clean it end of manager deletion test. 
{{pytest: cfme/tests/storage/test_manager.py -sqvvv}}

[1LP][RFR] all method for storage managers

---

cfme/tests/intelligence/test_chargeback.py

Parameterizing CRUD tests on compute/storage + fixed/variable to minimize code duplication
All tests passed locally.

[1LP][RFR] Chargeback CRUD operations: Parameterizing tests

---

cfme/cloud/keypairs.py
cfme/tests/openstack/cloud/test_keypairs.py

Add download_private_key test 
{{ pytest: cfme/tests/openstack/cloud/test_keypairs.py }}

[1LP][RFR] Add download_private_key test

---

cfme/tests/v2v/test_v2v_migrations.py

{{ pytest: cfme/tests/v2v/test_v2v_migrations.py::test_conversion_host_tags }}

[RFR] fixed some v2v migration tests

---

cfme/tests/infrastructure/test_vm_migrate.py

[1LP][RFR][NOTEST] Blocking test_vm_migrate with BZ1627297

---

cfme/tests/configure/test_visual_infra.py
cfme/tests/infrastructure/test_kubevirt.py
cfme/tests/webui/test_splitter.py

A few nav destinations referencing the wrong class/destination combo.

[1LP][RFR] Fix navigation destinations

---

cfme/tests/infrastructure/test_publish_vm_to_template.py

Bug was originally reported by @lina-nikiforova

[RFR][NOTEST] Blocking test_publish_vm_to_template with BZ1622952

---

cfme/tests/infrastructure/test_provisioning_dialog.py

[RFR][NOTEST] Blocking test_change_cpu_ram with BZ1627673

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt

Includes fixes for openstack infra auth

[1LP][RFR] Bump wrapanapi to 3.0.25

---

sprout/appliances/tasks.py

Update logging when a provider is marked not working and we're trying to do something on it.

[RFR] Update provider not working messages in sprout

---

cfme/tests/automate/custom_button/__init__.py
cfme/tests/automate/custom_button/test_infra_objects.py

- Added common automation log parsing method for request count
- Added new test for infra objects
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_automate -v}}

[1LP][RFR] Custom Button: Automate test for Infra objects

---

cfme/base/ui.py
cfme/configure/access_control/__init__.py
cfme/services/myservice/__init__.py
cfme/services/myservice/ui.py
cfme/tests/services/test_service_rbac.py

{{pytest: cfme/tests/services/test_service_rbac.py --use-template-cache --use-provider vsphere67-nested -vvvv}}

[1LP][RFR] Added test_service_rbac.py testcase

---

cfme/tests/cloud/test_quota_tagging.py

- Testing cloud quota of user and group with openstack provider
- Provisioning instance with more than assigned quota
{{ pytest: cfme/tests/cloud/test_quota_tagging.py::test_cloud_quota_by_lifecycle --use-provider complete }}

[1LP][RFR] Testing cloud quota for 'user' and 'group' by provisioning instance via lifecycle

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

I am backporting fix of @rhrazdil  to legacy branch.
Jenkins verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.8-rhv-4.2-integration-flow-dev/101/console

[1LP][RFR] Fix problem with host list comprehention

---

cfme/tests/infrastructure/test_provisioning_dialog.py

Adding test case that tests provisioning VM from a template with 2 NICs. 
BZ reported by customer: https://bugzilla.redhat.com/show_bug.cgi?id=1460622
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py::test_provision_vm_with_2_nics --use-provider rhv42}}

[1LP][RFR] Adding test that tries provision VM from template with 2 NICs

---

cfme/tests/services/test_provision_stack.py

[RFR]Marked test with BZ

---

widgetastic_manageiq/__init__.py

.isort.cfg updated by precommit
Fix container overview page tests, xpath wasn't working for 510z.
{{ pytest: cfme/tests/containers/test_overview_data_integrity.py --use-provider ocp-39-hawk -vv }}

[1LP][RFR] Update StatusBox xpath

---

cfme/tests/automate/custom_button/test_infra_objects.py

{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_display -v}}

[1LP][RFR] Custom Button: Cluster support in infa object

---

cfme/fixtures/authentication.py

don't restart httpd directly
isort.cfg updated automatically by precommit

[1LP][RFR] Update auth fixture, restart evmserverd

---

cfme/fixtures/v2v.py

__Extending__ cfme/fixtures/v2v.py  ability to add VMware Host creds, as this is new requirement for v2v tests, currently for 5.10, probably will end up in 5.9 builds as well. No harm in adding creds in current 5.9 tests as well. 
{{ pytest:  cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv --long-running -k 'test_dual_datastore_dual_vm_migration' }}

[1LP][RFR] Adding ability to add VMware Host creds, as this is new requirement for v2v tests

---

cfme/services/catalogs/catalog_items/catalog_bundles.py
cfme/tests/services/test_generic_service_catalogs.py

1) Marked tests with BZ.
2) Catalog name is appended with 'My company' in catalog bundles.
3) Candidatenotfound exception is raised when catalog node not found.

[1LP][RFR]Generic service 5.10 fix

---

cfme/infrastructure/virtual_machines.py

Quick add flash message for 5.8. Fixes failures in snapshot testing for 5.8.

[1LP][RFR] 5.8 - add flash message for snapshot

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

This PR deals with 2 issues:
- variable host in list comprehention overshadows variable host in the for loop.
- host credentials are not validated for rhevm provider. SSA on requires host creds validation on Infra provider
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py::test_ssa_compliance --use-provider complete --long-running}}

[RFR] Fix issue with list comprehention and calling host validation for InfraProvider

---

cfme/tests/cloud_infra_common/test_vm_ownership.py

This is a fix/redo of an existing ownership test.
The original test had two flaws:
1. If an exception occurred, we never got to the template deletion
2. If the test went fine, the template was deleted only from CFME database - not from provider.
This caused templates with the name "test-ownrs*" stack up on vmware providers and that is bad.
Also, the 'set_ownership' method now takes an user instance as an argument, not a string.
On 5.10 this will fail because: https://bugzilla.redhat.com/show_bug.cgi?id=1622952

[RFR] Fix template ownership test

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_csv_import.py
cfme/v2v/migrations.py

{{pytest: cfme/tests/v2v/test_csv_import.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv }}

[1LP][RFR] Add csv imports tests to v2v

---

cfme/tests/control/test_actions.py

https://bugzilla.redhat.com/show_bug.cgi?id=1633606

[1LP][RFR][NOTEST] Blocking test_actions.py with BZ1633606

---

cfme/tests/infrastructure/test_tenant_quota.py

https://bugzilla.redhat.com/show_bug.cgi?id=1626232

[1LP][RFR][NOTEST] Blocking test_tenant_quota_vm_reconfigure with BZ1626232

---

cfme/tests/infrastructure/test_quota_tagging.py
cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

https://bugzilla.redhat.com/show_bug.cgi?id=1633540

[1LP][RFR][NOTEST] Blocking several service tests with BZ1633540

---

cfme/tests/infrastructure/test_pxe_provisioning.py
cfme/tests/services/test_pxe_service_catalogs.py

[RHV] Wrong number of arguments error during PXE provision from template: https://bugzilla.redhat.com/show_bug.cgi?id=1633516
Cannot add a new Catalog Item for RHV: https://bugzilla.redhat.com/show_bug.cgi?id=1633540

[1LP][RFR][NOTEST] Adding two PXE blockers and removing unused ones

---

cfme/configure/configuration/diagnostics_settings.py

Imported from the wrong module, just moving it.

[1LP][RFR] Move widgetastic exception import

---

cfme/tests/test_login.py

This adds a functionality to existing login test to cover a testcase. We try to change password of an user without knowing his current password.
This won't work on 5.10 (with Chrome) because of https://bugzilla.redhat.com/show_bug.cgi?id=1632718
{{ pytest: -v cfme/tests/test_login.py -k test_update_password }}

[1LP][RFR] Upgrade the change password test

---

cfme/tests/infrastructure/test_vm_power_control.py

https://bugzilla.redhat.com/show_bug.cgi?id=1633727

[1LP][RFR][NOTEST] Wrapping test_no_power_controls_on_archived_vm with BZ1633727

---

cfme/tests/infrastructure/test_vm_reconfigure.py

https://bugzilla.redhat.com/show_bug.cgi?id=1632782

[1LP][RFR][NOTEST] Blocking test_vm_reconfig_add_remove_hw_* with BZ1632782

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_buttons.py
cfme/tests/automate/custom_button/test_cloud_objects.py
cfme/tests/automate/custom_button/test_infra_objects.py

1. Introduce test for template and image custom button object
2. changes fro better id
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_display -v}}

[1LP][RFR] Custom Button: template images object support

---

cfme/tests/v2v/test_v2v_migrations_ui.py

{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py -k test_migration_rbac --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv}}

[1LP][RFR] Add test for migration with rbac

---

cfme/storage/volume_backup.py
cfme/tests/openstack/cloud/test_volume_backup.py

- Added test_incr_backup_of_attached_volume_crud test
- delete method under VolumeBackup class
{{ pytest: cfme/tests/openstack/cloud/test_volume_backup.py::test_incr_backup_of_attached_volume_crud }}

[1LP][RFR] Add test incr backup of attached volume crud

---

cfme/common/vm.py
cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/v2v/migrations.py

__Extending__ v2v_tests to check MAC address of the VMs pre and post migration.
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv --long-running  -k 'test_single_datastore_single_vm_migration' }}

[1LP][RFR]V2v tests mac addr

---

cfme/fixtures/merkyl.py

With this commit we implement search with regular expression that uses Merkyl plugin.
Here is a simple use case that searches `evm.log` for `ems_ref` that starts with `1` and ends with `9`:
```python
import re
def test(merkyl_inspector):
log_path = '/var/www/miq/vmdb/log/evm.log'
merkyl_inspector.add(log_path) # <- add log that you want to track with merkyl
simple_regex = re.compile(r'^.*ems_ref=1[0-9]+9 .*$', re.MULTILINE) # <- compile regex
if merkyl_inspector.search_log_with_regex(simple_regex, log_path): # <- search for regex in evm.log
print('ems_ref was found')
```

[1LP][RFR] Implement regex search

---

cfme/tests/automate/test_common_methods.py
cfme/tests/cloud_infra_common/test_retirement.py

[1LP][RFR][NOTEST] Dealing with datepicker bug in CFME 5.9

---

widgetastic_manageiq/__init__.py

KK going to automate -
1. Test if progress bar on in progress card shows correct status during migration initial migration
2. Test if progress bar on in progress card shows correct status during migration - for failed migration that is being retried
This functions are prerequisites for that. Created https://github.com/ManageIQ/manageiq-v2v/issues/676 and mentioned TODO in code for ids.

[1LP][RFR] Functions to get progress bar percentage in MigrationProgressBar widget

---

cfme/infrastructure/virtual_machines.py
cfme/tests/cloud/test_cloud_timelines.py
cfme/tests/infrastructure/test_timelines.py

{{pytest: cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_diagnostic --use-provider=vsphere6-nested}}

[RFR]EditManagementRelationship view should have wait_for_view check disabled

---

cfme/common/vm.py
cfme/provisioning.py
cfme/tests/cloud/test_providers.py

{{pytest: cfme/tests/infrastructure/test_quota.py cfme/tests/cloud_infra_common/test_provisioning.py cfme/tests/cloud/test_providers.py}}

[RFR] fix provisioning view navigation

---

cfme/tests/cli/test_appliance_update.py

Adding some simple logging of the repo files written for updating appliance via yum.

[1LP][RFR] Add logging for writing yum repos in update tests

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_import_export.py

Adding test for RFE on 5.10 for import and export fuctionality of custom button
https://bugzilla.redhat.com/show_bug.cgi?id=1164306
{{pytest: cfme/tests/automate/custom_button/test_import_export.py -v}}

[1LP][RFR] Custom Button:  Import & Export RFE automate

---

cfme/automate/explorer/instance.py
cfme/automate/explorer/klass.py
cfme/automate/explorer/namespace.py
cfme/dashboard.py
cfme/infrastructure/config_management.py
cfme/intelligence/chargeback/rates.py
cfme/services/catalogs/orchestration_template.py

Invalid references to `self.obj`, within View classes its under `self.context['object']`

[1LP][RFR] Fix view obj context

---

cfme/automate/buttons.py
cfme/configure/access_control/__init__.py
cfme/tests/automate/custom_button/test_generic_objects.py

Custom button
- User
- Group
- Tenent
Added missing paginator :)
{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py -v}}

[1LP][WIPTEST] Custom Button: User Group Tenant

---

cfme/storage/volume.py
cfme/storage/volume_backup.py

fix is_displayed methods of VolumeRestoreView and VolumeBackupView to return True as wait_for_view is True by default now
{{ pytest: cfme/tests/openstack/cloud/test_volume_backup.py::test_create_volume_backup }}

[1LP][WIPTEST] fix is_displayed of VolumeRestoreView and VolumeBackupView to return True

---

cfme/intelligence/reports/reports.py

title may include report title or report menu_name
{{ pytest: cfme/tests/intelligence/reports/test_views.py --long-running }}

[RFR] Fix SavedReportDetailsView.is_displayed

---

cfme/optimize/bottlenecks.py

view tested locally
{{ pytest: cfme/tests/optimize/test_bottlenecks.py --long-running }}

[RFR] Fix bottlenecks view is_displayed

---

cfme/configure/tasks.py

Tasks tabs reduced in 5.10 and 5.9.5, checking 5.9.4.

[RFR] Fix tasks nav

---

cfme/infrastructure/virtual_machines.py

{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_display -v}}
5.10  two test failing due to host bug 1636120

[RFR] Fix: is_displayed for template details

---

cfme/common/__init__.py
cfme/common/host_views.py
cfme/common/vm_views.py
cfme/containers/provider/__init__.py
cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/pxe.py
cfme/intelligence/chargeback/rates.py
cfme/networks/views.py
cfme/services/catalogs/catalog_items/ansible_catalog_items.py
cfme/storage/volume.py
cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py

{{pytest: --long-running --use-provider=complete cfme/tests/infrastructure/test_timelines.py cfme/tests/cloud/test_cloud_timelines.py}}

[1LP][RFR] replace view.is_displayed->False with NotImplementedError

---

cfme/automate/__init__.py
cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_buttons.py

{{pytest: cfme/tests/automate/custom_button/test_buttons.py -v}}

[1LP][RFR] fix group navigation displayed

---

cfme/automate/dialogs/__init__.py
cfme/automate/dialogs/dialog_box.py
cfme/automate/dialogs/dialog_element.py
cfme/automate/dialogs/dialog_tab.py

{{ pytest: cfme/tests/automate/test_service_dialog.py::test_reorder_elements -v}}
{{ pytest: cfme/tests/automate/test_service_dialog.py::test_dropdownlist_dialog_element -v}}

[1LP][RFR] Fix is_displayed for create and edit dialog

---

cfme/tests/configure/test_log_depot_operation.py

Removed verified BZ1627273 for 5.10 and blockers for 5.8 stream

[1LP][RFR][NOTEST] removed BZ blockers

---

cfme/tests/candu/test_gap_collection.py
cfme/tests/candu/test_host_graph.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_individual_host_creds.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

Security update for paramiko, major update for wt.core including @izapolsk moving widgets into separate modules, and implementing `Table` support for rowspan/colspan.

Update paramiko and wt.core

---

cfme/containers/project.py

{{ pytest: cfme/tests/containers/test_projects_dashboard.py --use-provider ocp-36-hawk }}

[RFR] Fix is_displayed and step() for CMQE project Class

---

cfme/cloud/instance/openstack.py
cfme/common/__init__.py
cfme/common/host_views.py
cfme/common/vm_views.py
cfme/containers/provider/__init__.py
cfme/exceptions.py
cfme/infrastructure/config_management.py
cfme/infrastructure/datastore.py
cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/pxe.py
cfme/infrastructure/virtual_machines.py
cfme/intelligence/chargeback/rates.py
cfme/networks/views.py
cfme/services/catalogs/catalog_items/ansible_catalog_items.py
cfme/storage/volume.py

So we're not trying to repeat the same exception text in 100 places - @RonnyPfannschmidt suggestion, ran with it.

[1LP][RFR] Add assignable displayed exception

---

cfme/networks/provider/__init__.py
cfme/networks/views.py

- added some small fixes in network views
- tested most of with miq shell
http://pastebin.test.redhat.com/656198
- not going to cover all tests but adding one test  for @dkholodo as he only pointed me this
{{pytest: cfme/tests/networks -v}}

[WIPTEST] Network view fix

---

cfme/tests/infrastructure/test_pxe_provisioning.py
cfme/tests/services/test_pxe_service_catalogs.py

[1LP][RFR][NOTEST] Blocking test_pxe_provision_from_template with GH7965

---

cfme/tests/infrastructure/test_host.py

{{ pytest: -v cfme/tests/infrastructure/test_host.py::test_250_vmware_hosts_loading }}

[1LP][RFR] new test_250_vmware_hosts_loading

---

cfme/tests/v2v/test_v2v_schedule_migrations.py
widgetastic_manageiq/__init__.py

__Adding tests__ for schedule_migration feature.
**Note**: Please ignore the changes in Widgetastic_manageiq/__init__.py as these are already being reviewed in #7818 
Once that PR is merged, this PR should be reviewed and merged.
{{pytest: cfme/tests/v2v/test_v2v_schedule_migrations.py --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv --long-running}}

[1LP][RFR]V2v schedule migration tests

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/migrations.py

__Fixing__ v2v ui tests. 
{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running}}

[RFR]updating v2v ui tests to correctly work with 5.10 and handle wait_for_view better

---

cfme/configure/configuration/system_schedules.py
cfme/tests/configure/test_db_backup_schedule.py

{{ pytest: cfme/tests/configure/test_db_backup_schedule.py --long-running --use-provider default }}
Related to fixing #7960

[RFR] Update SystemSchedule views for zone reference

---

cfme/intelligence/reports/reports.py

View timing out in 59z
SavedReportDetailsView timing out in PRT, debugging further. This fixed 4/6 tests so far though.
{{ pytest: cfme/tests/intelligence/reports/test_generate_report.py --use-provider default --long-running }}
Part of resolving #7960

[RFR] Change nav targets for report prerequisites

---

cfme/control/explorer/alert_profiles.py

Part of fixing #7960 
{{ pytest: cfme/tests/control/test_alerts.py --long-running }}

[RFR] Fix alert profile All is_displayed

---

cfme/tests/automate/custom_button/__init__.py
cfme/tests/automate/custom_button/test_cloud_objects.py
cfme/tests/automate/custom_button/test_infra_objects.py

{{pytest: -k "test_custom_button_dialog" -v}}

[1LP][RFR] Test custom button dialog

---

cfme/tests/configure/test_paginator.py

removed blocker as BZ1623091 is verified

[1LP][RFR][NOTEST] removed blocker for test_paginator

---

cfme/physical/physical_storage.py
entry_points.txt

This PR adds the Physical Storage entity to the framework.

[1LP][RFR] Add Physical Storage entity

---

cfme/fixtures/cli.py
cfme/tests/cli/test_appliance_update.py
cfme/utils/appliance/__init__.py

Added new update tests for different scenarios and moved all fixtures to cli.py for central usage.
REQUIRES PR: 7759

[1LP][RFR] Added new update tests and fixtures for them

---

cfme/intelligence/chargeback/assignments.py
cfme/intelligence/chargeback/rates.py
cfme/tests/containers/test_chargeback.py
cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
cfme/tests/intelligence/chargeback/test_resource_allocation.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py
cfme/tests/intelligence/test_chargeback_assignments.py
cfme/tests/ssui/test_ssui_dashboard.py

{{pytest: cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py  cfme/tests/intelligence/chargeback/test_resource_allocation.py cfme/tests/intelligence/reports/test_validate_chargeback_report.py cfme/tests/intelligence/test_chargeback_assignments.py cfme/tests/ssui/test_ssui_dashboard.py --use-provider complete --long-running}}

[WIPTEST] Updates to Chargeback Assignments Class and Tests

---

cfme/cloud/instance/image.py

Use of ParametrizedSummaryTable

[1LP][RFR] Update ImageDetailsView.is_displayed

---

cfme/tests/automate/custom_button/test_generic_objects.py

{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py -v}}

[1LP][RFR] Custom Button: automate with dialog test and BZ blockers

---

cfme/infrastructure/host.py
cfme/networks/views.py
cfme/tests/openstack/infrastructure/test_hosts.py

Added 2 tests:
1. test_host_networks
2. test_host_subnets
{{ pytest: cfme/tests/openstack/infrastructure/test_hosts.py::test_host_networks cfme/tests/openstack/infrastructure/test_hosts.py::test_host_subnets --use-provider rhos11}}

[1LP][RFR] Add host networks and subnets tests

---

cfme/tests/candu/test_vm_graph.py

{{pytest: cfme/tests/candu/test_vm_graph.py --use-provider complete --collect-only }}

[1LP][RFR] Limit tests to one provider per type

---

cfme/tests/intelligence/reports/test_tenant_quota_reports.py

This PR automates a test case to check if the newly set tenant quota data reflects in the report generated for `Tenant Quota`.
{{pytest: cfme/tests/intelligence/reports/test_tenant_quota_reports.py --use-template-cache -sqvvv}}

[1LP][RFR]Automate test: Queue Tenant Quota Reports

---

cfme/ansible/repositories.py
cfme/configure/configuration/diagnostics_settings.py
cfme/services/catalogs/catalog_items/__init__.py
cfme/services/catalogs/catalog_items/ansible_catalog_items.py
cfme/tests/configure/test_log_depot_operation.py

automated test for log collection to dropbox, dropbox was added to cfme_data.yaml to generate the new test

[1LP][RFR] added check for logs on dropbox

---

cfme/cloud/instance/openstack.py

{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_volume }}

[WIPTEST] fix is_displayed of AttachVolumeView

---

cfme/tests/infrastructure/test_provisioning_dialog.py

__Adding tests__ for feature vmware default placement of vm after provisioning to cover case RHCF3-13102
Shriver: module is marked with --long-running, tests were uncollecting, added option below.
{{ pytest: -v cfme/tests/infrastructure/test_provisioning_dialog.py -k test_vmware_default_placement --long-running }}

[1LP][RFR] Add test for vmware default placement

---

cfme/tests/openstack/cloud/test_provider.py

Add test_dashboard_card_tenants
{{ pytest: cfme/tests/openstack/cloud/test_provider.py::test_dashboard_card_tenants cfme/tests/openstack/cloud/test_provider.py::test_dashboard_card_security_groups }}

[1LP][RFR] Add cloud provider dashboard tests

---

cfme/base/ui.py
cfme/tests/configure/test_paginator.py

{{ pytest: -v cfme/tests/configure/test_paginator.py::test_paginator }}
1. Added check for the Advanced tab on Region and Zone level (https://bugzilla.redhat.com/show_bug.cgi?id=1082155)
2. Fixed some navigation issues

[1LP][RFR] added check for advanced tab for region and zones and fixed navigation

---

cfme/storage/volume.py

Add support for volume type field
{{ pytest: cfme/tests/openstack/cloud/test_volumes.py::test_create_volume }}

[1LP][RFR] Add support for volume type field

---

cfme/fixtures/v2v.py

Implementing https://gist.github.com/fdupont-redhat/0661f6310e8ca0a1dab4b9016ea752e9
{{pytest: cfme/tests/v2v/test_v2v_migrations.py -k test_single_datastore_single_vm_migration --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv}}

[RFR] Added new way to set conversion host

---

cfme/generic_objects/definition/definition_views.py
cfme/generic_objects/definition/ui.py
cfme/tests/generic_objects/test_definitions.py

-  Fixed view
- Added one BZ for flash and blocked it for now...
{{pytest: cfme/tests/generic_objects/test_definitions.py -vvv}}
part of https://github.com/ManageIQ/integration_tests/issues/7960

[1LP][RFR] Fix generic object class view and test

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_generic_objects.py
widgetastic_manageiq/expression_editor.py

- Test for visibility  expression custom button control
- Enhancement for visibility and enablement
- Workaround in expression editor second try..... 
- small blackification
{{pytest:  cfme/tests/automate/custom_button/test_generic_objects.py::test_visibility_expression -vv}}

[1LP][RFR] Visibility enhancement and Test

---

cfme/tests/automate/custom_button/test_container_objects.py

- New test for dialog execution check
- added globle blocker for 5.10
{{pytest:  cfme/tests/automate/custom_button/test_container_objects.py::test_custom_button_dialog -sqvv --use-provider ocp-35-hawk}}

[1LP][RFR] Block for 5.10 and test_custom_button_dialog

---

cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_automate.py
cfme/tests/ansible/test_embedded_ansible_basic.py
cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/tests/ansible/test_embedded_ansible_rest.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/ansible/test_embedded_ansible_tags.py

PRT Run:
{{ pytest: cfme/tests/ansible -qsvvvv }}

[RFR] Added blocker BZ to uncollect tests till BZ fix.

---

cfme/tests/infrastructure/test_quota_tagging.py

{{ pytest: cfme/tests/infrastructure/test_quota_tagging.py::test_quota_infra -v }}

[RFR] Tests quota for user and group via ui and ssui

---

cfme/exceptions.py
cfme/storage/volume_type.py
cfme/tests/openstack/cloud/test_volumes.py
entry_points.txt

Add volume 3 tests which uses volume type:
{{ pytest: cfme/tests/openstack/cloud/test_volumes.py::test_create_volume_with_type cfme/tests/openstack/cloud/test_volumes.py::test_edit_volume_with_type cfme/tests/openstack/cloud/test_volumes.py::test_delete_volume_with_type }}

[WIPTEST] Add Volume Types Collection including related tests

---

cfme/cloud/instance/__init__.py

{{ pytest: cfme/tests/cloud/test_instance_power_control.py --use-provider azure --long-running }}

[1LP][RFR] Surf pages on cloud instance power control

---

cfme/fixtures/service_fixtures.py

{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_retire_service_ssui --use-provider vsphere67-nested -svvv }}

[RFR] Fix retire ssui test 510z

---

cfme/fixtures/nuage.py

Refactor Nuage fixture so we have an option to reuse it with different test configuration.
/cc @miha-plesko

[1LP][RFR] Refarctor Nuage fixture

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
scripts/ec2cleanup.py

Added delete_snapshots method to ec2cleanup script.
Depends on this wrapanapi PR: https://github.com/ManageIQ/wrapanapi/pull/342/files
Tested.

[1LP][NOTEST][WIPTEST] Cleanup snapshots

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

[1LP][RFR]TableRow should use index starting from 0 now

---

cfme/services/catalogs/catalog.py
cfme/tests/configure/test_access_control.py
cfme/tests/services/test_catalog.py

1) Added wait for a view .
2) fixed is_displayed for a view 
3) Fixed test catalog permission test

[1LP][RFR]Catalog view is_displayed fix

---

cfme/common/host_views.py

Account for both hostcollection and provider contexts for the is_displayed method.
Replacing PR #8026 
Part of resolving #7960 
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py cfme/tests/infrastructure/test_host.py --long-running --use-provider complete}}

[1LP][RFR] Fix provider host all view is_displayed implementation

---

cfme/services/catalogs/catalog_items/catalog_bundles.py
cfme/tests/services/test_generic_service_catalogs.py

1) Removed BZ
2) Fixed Editbundle view

[1LP][RFR]Bundle view is_displayed fix

---

cfme/common/__init__.py
cfme/tests/storage/test_manager.py
cfme/tests/storage/test_object_store_container.py
cfme/tests/storage/test_object_store_object.py
cfme/tests/storage/test_volume.py
cfme/tests/storage/test_volume_backup.py
cfme/tests/storage/test_volume_snapshot.py

{{pytest: cfme/tests -k "test_tag or test_tagvis or test_tagwise or edit_tag"}}
- https://bugzilla.redhat.com/show_bug.cgi?id=1648243
- https://bugzilla.redhat.com/show_bug.cgi?id=1648658
- other BZ also there but blocking with `1648243`.  I think some will duplicate, we will put exact BZ Id. let's wait for a run.

[1LP][RFR] skip tests in navigation related to tag

---

cfme/cloud/instance/openstack.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/cloud/test_volume_backup.py

Added test_create_backup_of_volume_with_type
Added test_instance_attach_volume_with_type
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_detach_volume_with_type cfme/tests/openstack/cloud/test_volume_backup.py::test_create_backup_of_volume_with_type }}

[RFR] Add tests related to volume type RFE

---

cfme/tests/ssui/test_ssui_myservice.py

[1LP][RFR][NOTEST] Blocking test_myservice_crud with BZ1646925

---

cfme/tests/networks/test_provision_to_virtual_network.py

[1LP][RFR][NOTEST] Blocking test_provision_vm_to_virtual_network with GH8128

---

cfme/fixtures/xunit_tools.py

remove containers from blacklist

[1LP][RFR] Update xunit fixture, include group-id from xunit.conf

---

cfme/tests/automate/custom_button/test_generic_objects.py

- I found most of thing common so changed plane and parametrize for both expression
{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_expression -v}}

[1LP][RFR] Parametrize: enablement and visibility for General objects

---

cfme/tests/candu/test_host_graph.py

{{pytest: cfme/tests/candu/test_host_graph.py -k  test_tagwise}}

[1LP][RFR] Add BZ blocker for VM tag tests in 59

---

cfme/common/vm.py
cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_cancel_migrations.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/tests/v2v/test_v2v_schedule_migrations.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

Fixing Navigation as cfme 510z has different menu options as well as fixing vm_obj call by replacing it with vm_list
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running -k 'test_single_datastore_single_vm_migration' }}

[1LP][RFR]V2v fixes 510z

---

scripts/ec2cleanup.py

Deleting SQS queues older than 14 days.
This wrapanapi PR required for this PR: https://github.com/ManageIQ/wrapanapi/commit/291b029fdcc5860218201d694f3408a3a76289b9
Also after merge please keep rerunning ec2cleanup for at least one day as there are so many queues and only 1k are deleted by one run. @mshriver

[RFR][NOTEST] Added cleanup for SQS queues

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

I cannot really provide valid verification, since SSA tests are blocker by #8152

[1LP][RFR] Making activation of SmartProxy Affinity idempotent

---

cfme/tests/infrastructure/test_host_analysis.py

[1LP][RFR] Blocking test_run_host_analysis with BZ1650179

---

cfme/cloud/flavor.py
cfme/tests/openstack/cloud/test_flavors.py

Add tests:
1. test_flavors_list
2. test_flavor_details
{{ pytest: cfme/tests/openstack/cloud/test_flavors.py::test_flavors_details_from_list_view cfme/tests/openstack/cloud/test_flavors.py::test_flavor_details }}

[1LP][RFR] Add tests from flavors management RFE

---

.travis.yml

this ensures we see a diff on a failure of pre-commit

[1LP][RFR] Travis pre commit diff

---

cfme/tests/openstack/cloud/test_volume_backup.py

Add tests: 
test_restore_volume_backup
test_restore_incremental_backup
{{ pytest: cfme/tests/openstack/cloud/test_volume_backup.py::test_restore_volume_backup cfme/tests/openstack/cloud/test_volume_backup.py::test_restore_incremental_backup }}

[1LP][RFR] Add 2 volume backup restore tests

---

cfme/configure/configuration/diagnostics_settings.py

{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_multiple_servers }}

[1LP][RFR] fixed test_collect_multiple_servers tests

---

cfme/tests/v2v/test_v2v_migrations.py

{{pytest: cfme/tests/v2v/test_v2v_migrations.py -k test_migration_long_name --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv }}

[1LP][RFR] Add long name vm migration test

---

cfme/tests/automate/custom_button/test_infra_objects.py

- test for Infra cutom button objects
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_expression -sqvv}}

[1LP][RFR] Infra object: CB visibility and enablement

---

cfme/tests/control/test_bugs.py

__Fixing__ `test_vmware_alarm_selection_does_not_fail` by restructuring the test to assert that an alert with `evaluate=("VMware Alarm", {})` is successfully created. Previously, this test would expect the alert creation to fail. It is written against BZ 1231889. 
{{ pytest: --long-running cfme/tests/control/test_bugs.py::test_vmware_alarm_selection_does_not_fail }}

[1LP][RFR] fix test_vmware_alarm_selection_does_not_fail by restructuring test

---

cfme/tests/v2v/test_post_migrations.py
cfme/tests/v2v/test_v2v_migrations.py

{{pytest: cfme/tests/v2v/test_post_migrations.py -k test_migration_policy_tag --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv }}

[1LP][RFR] Add test policy to check source VM from starting after migration

---

cfme/tests/cloud/test_quota_tagging.py

- This test case verifies the quota assigned by automation method for user and group
is working correctly for the cloud providers.
- Steps:
- Navigate to Automation > Automate > Explorer
- Add quota automation methods to domain
- Change 'quota_source_type' to 'user' or 'group'
- Test quota by provisioning instances over quota limit via UI or SSUI for user and group
- Check whether quota is exceeded or not
{{ pytest: cfme/tests/cloud/test_quota_tagging.py::test_quota_cloud_via_services -v }}

[1LP][RFR] New tests for Quota: checks quota assigned by automation methods for user and group by provisioning instance over quota limit

---

cfme/common/vm.py
cfme/common/vm_views.py
cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_vm_ownership.py

{{ pytest: cfme/tests/infrastructure/test_vm_ownership.py::test_rename_vm --use-provider vsphere67-nested  -v }}

[1LP][RFR] Test for new feature of VM: Rename  the VM

---

cfme/fixtures/v2v.py

Migration was disabled, this fixture will add it back to permissions for downstream 5.10 if its missing.
Session scoped so anything using v2v_providers will get it enabled for the entire session duration.
Local testing successful with workaround already applied and without.
{{ pytest: --long-running --provider-limit=2 --use-provider rhv42 --use-provider vsphere67-nested cfme/tests/v2v/test_v2v_migrations_ui.py }}

[1LP][RFR] Add fixture to enable v2v migration UI in downstream 510z

---

cfme/dashboard.py
cfme/services/myservice/ssui.py

{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_service_start -v  --use-provider vsphere65-nested --long-running}}

[1LP][RFR] Fix power operation

---

cfme/utils/template/base.py

Removing tar.gz unpacking as GCE needs tar.gz archive for image upload and reworked try/except for archive unpacking.

[RFR][NOTEST]Unzip rework

---

cfme/tests/test_db_migrate.py

Migration test is blocked by BZ.

[RFR] Add blocker to test_upgrade_single_inplace

---

cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/migrations.py
widgetastic_manageiq/__init__.py

{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running -k test_edit_mapping_description}}
Reference PR 8174

[1LP][RFR]v2v Edit mapping test case

---

cfme/fixtures/ansible_fixtures.py
cfme/fixtures/cli.py
cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_automate.py
cfme/tests/ansible/test_embedded_ansible_basic.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/ansible/test_embedded_ansible_tags.py
cfme/tests/cli/test_appliance_console_db_restore.py
cfme/tests/cli/test_appliance_update.py
cfme/tests/configure/test_log_depot_operation.py
cfme/tests/v2v/test_v2v_ansible.py
cfme/v2v/migrations.py
conf/cfme_data.yaml.template
widgetastic_manageiq/__init__.py

{{pytest: cfme/tests/v2v/test_v2v_ansible.py --use-provider vsphere65-nested --use-provider rhv42 --provider-limit 2 -vvvv}}

[1LP][RFR]  Pre and post migration tests

---

cfme/tests/test_ui.py

{{ pytest: -v cfme/tests/test_ui.py::test_each_page }}
This tag solves the issue in https://bugzilla.redhat.com/show_bug.cgi?id=1648338

[1LP][RFR] added check for the meta tag for IE11

---

cfme/services/dashboard/ssui.py

{{ pytest: cfme/tests/ssui/test_ssui_dashboard.py::test_current_service --long-running -v }}

[1LP][RFR] Fix ssui dashboard test

---

cfme/tests/services/test_catalog_item.py

{{ pytest: cfme/tests/services/test_catalog_item.py::test_add_button --long-running -v }}

[1LP][RFR] Fix test service catalog add button

---

cfme/tests/pod/test_appliance_crud.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/346 , https://github.com/ManageIQ/wrapanapi/pull/347
{{pytest: --use-template-cache --long-running --use-provider=cm-pod1 -k 'test_pod_appliance_db_backup_restore' cfme/tests/pod/test_appliance_crud.py}}

[1LP][RFR] backup restore test

---

cfme/cloud/stack.py

{{ pytest: cfme/tests/cloud/test_stack.py -v --long-running }}

[1LP][RFR]stack collection delete fix

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/migrations.py

{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running -k test_edit_mapping_fields}}
1) Extended edit mapping test case to edit fields like datastore and network too .
2) refactored some code .

[RFR]v2v edit mapping fields

---

cfme/tests/automate/custom_button/test_buttons.py
cfme/tests/automate/custom_button/test_cloud_objects.py
cfme/tests/automate/custom_button/test_container_objects.py
cfme/tests/automate/custom_button/test_generic_objects.py
cfme/tests/automate/custom_button/test_import_export.py
cfme/tests/automate/custom_button/test_infra_objects.py

[1LP][RFR][NOTEST] update doc bock polarion

---

cfme/services/myservice/ssui.py
cfme/tests/automate/custom_button/test_service_objects.py
widgetastic_manageiq/__init__.py

- Added To-Do  for paginator on ssui views
- Added new test for sevice  automate
{{pytest:  cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_automate -vv}}

[1LP][RFR] CB: service automate

---

cfme/cloud/flavor.py
cfme/tests/openstack/cloud/test_flavors.py

Added test: test_create_instance_with_private_flavor
{{ pytest: cfme/tests/openstack/cloud/test_flavors.py::test_create_instance_with_private_flavor }}

[1LP][RFR] Add test from flavors management RFE
