cfme/configure/access_control/__init__.py
cfme/roles.py
cfme/tests/configure/test_access_control.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py
cfme/tests/integration/test_cfme_auth.py
cfme/tests/integration/test_ldap_auth_and_roles.py

We are seeing test failures that surface as a ValueError, when trying to navigate (primarily with the 'Configuration' dropdown).
Debugging with @psav we found that some tests were specifically logging in with an `appliance.server.login()` command, both within and outside of user contexts.
This was causing interaction between tests, where some tests wouldn't "cleanup" and return to superadmin login for the appliance. Subsequent tests would be on a non-admin user, and would be missing permissions for some action required for the test.
This PR addresses a few actions across a few different tests:
1. Replace uses of direct login calls with a specific user with a `navigate_to()` call
2. Have a context manager for any custom users
running...
{{ pytest: --long-running -k …

[1LP][RFR] Update tests using custom users

---

cfme/tests/perf/workloads/test_provisioning.py

So that it gets cleaned up by cleanup scripts.
The test doesn't have direct provider objects or vm objects, so cleanup within the test will require a larger scope.

[RFR] Update vm name for perf workloads

---

cfme/base/__init__.py

* There is currently a bug in MiQ upstream where the servername field is
not populated in the UI, consequently, saving settings clears the name
which is required for creating the Server object. We now use a default
in the case that the Attribute can't be accessed. This is because null
attributes are not returned in the REST API.

[1LP][RFR] Hack to allow upstream testing to work again

---

cfme/markers/stream_excluder.py
cfme/markers/uncollect.py
cfme/rest/gen_data.py
cfme/tests/cli/test_appliance_cli.py
cfme/tests/configure/test_docs.py
cfme/tests/configure/test_register_appliance.py
cfme/tests/infrastructure/test_host_analysis.py
cfme/tests/infrastructure/test_host_provisioning.py
cfme/tests/storage/test_volume_backup.py
cfme/tests/test_db_migrate.py
cfme/tests/test_login.py
cfme/utils/providers.py
cfme/utils/version.py
docs/guides/tipsntricks.rst

this pr is part of removing multi-methods and part of removing the magical current_appliance globals
it removes many call sites where a better way is available
it does not yet touch version.pick and blockers
please avoid merging before i squash

[1LP][RFR] remove multimethods from utils.version and remove magical globals usage

---

cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/ansible/test_embedded_ansible_automate.py
cfme/tests/ansible/test_embedded_ansible_basic.py
cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/tests/ansible/test_embedded_ansible_rest.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/utils/appliance/__init__.py

1. 5.8 pod appliances don't support embedded ansible.
2. updated uncollects a bit
3. fixed some tests

[1LP][RFR] uncollect ansible tests for 5.8 pod appliance

---

cfme/tests/openstack/infrastructure/test_resources.py

Access to properties of provider summary table is now done via view_details.entities.summary('Properties') and not view_details.entities.properties
{{ pytest: cfme/tests/openstack/infrastructure/test_resources.py }}

[1LP][RFR] access to properties of provider summary table has changed

---

cfme/common/vm.py
cfme/infrastructure/virtual_machines.py
cfme/provisioning.py
cfme/tests/cloud_infra_common/test_cockpit_server.py
cfme/tests/cloud_infra_common/test_relationships.py
cfme/tests/cloud_infra_common/test_tag_objects.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/configure/test_access_control.py
cfme/tests/configure/test_default_filters.py
cfme/tests/configure/test_default_views_infra.py
cfme/tests/configure/test_visual_infra.py
cfme/tests/control/test_bugs.py
cfme/tests/infrastructure/test_advanced_search_vms.py
cfme/tests/infrastructure/test_infra_tag_filters_combination.py
cfme/tests/infrastructure/test_provisioning_dialog.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/services/test_operations.py
cfme/tests/webui/test_splitter.py
cfme/utils/appliance/__init__.py
setup.py
widgetastic_manageiq/__init__.py

There are a ton of tests collected due to the scope of this change. I'm not aiming to fix any test issues here, just an enhancement against the `virtual_machines.Vm` class name.
PRT run 23306 executed about 1100 tests, with ~90% passing.  No failures look related to this rename.
{{ pytest: --use-provider scvmm --use-provider onprem }}

[1LP][RFR] Rename Infrastructure.virtual_machines.Vm to InfraVm

---

cfme/automate/simulation.py
cfme/tests/automate/test_domain_priority.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/services/test_add_remove_vm_to_service.py

it was all there and removes support for the global

[1LP][RFR] always use appliance parameter in automate simulation calls

---

cfme/common/physical_server_views.py
cfme/physical/physical_server.py
cfme/tests/physical_infrastructure/ui/test_physical_server_list.py
cfme/tests/physical_infrastructure/ui/test_physical_server_list_buttons.py

This PR is able to:
* Add new tests for the physical server `list` page to test the buttons of a collection.
* Add new tests cases inside the `test_pyhsical_server_list.py` file.

[1LP][RFR] Add new tests for the physical server list page

---

cfme/fixtures/service_fixtures.py
cfme/services/service_catalogs/ui.py

__Fixing__  catalog_item.order().
https://github.com/ManageIQ/integration_tests/pull/6773/files#diff-77a8ead22c41840ab8714e03f56c5bbcL191 - introduced a gap - many tests were relying on `order()` to return Request object - all stack tests/ service PXE test/ OPS UI service tests.
`provision_request` fixture was removed almost right after but any return wasn't added into `.order()`
This PR will fix broken tests and keep up running tests which use `order_service` fixture

[1LP][RFR] fixing service order() method

---

cfme/tests/infrastructure/test_vm_power_control.py

`vm.GUEST_RESTART` and `vm.GUEST_SHUTDOWN` are (as they should be) available for RHV VM when it is up so I also modified `check_power_options` accordingly.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_vm_power_options_from_on --long-running}}

[1LP][RFR] Activating test_vm_power_options_from_on for RHV

---

cfme/scripting/quickstart.py

This is to support CI nodes having the correct version-matched python-debug package after being configured via quickstart.
Tested locally:
* F27
* CentOS:
* dropped, the versions of python, python-debug, and gdb in the repos are mismatched and won't run
* Ubuntu:
* 16.04.4 I installed isn't recognized and package install isn't run. Its a simple additional package for apt though.

[1LP][RFR] debuginfo-install in quickstart

---

requirements/frozen.txt
requirements/frozen_docs.txt

Other improvements:
* parametrization support
* new auth support (not yet in Polarion prod)
@mshriver @sbulage The version 2.0.12 of Polarion Importers broke checks if the data were successfully imported, because it can split data into several jobs and returns list of IDs. This version of dump2polarion fixes this and should be used by our Jenkins ASAP.

[RFR] New dump2polarion version with support for v2.0.12 of Importers

---

cfme/utils/mgmt_system/__init__.py
cfme/utils/virtual_machines.py

ovirt imports break testing on py3k because our port prs are not merged yet, this is a stopgap to support py3k porting in face of the ovirt issues

[RFR] py3 compat hack - ignore unimportable ovirtsdk

---

cfme/exceptions.py
fixtures/ui_coverage.py
scripts/data/coverage/manageiq-17302.patch

We are losing coverage statistics because the way we
setup CFME to give us that data was designed around its
2014 architecture where it would launch multiple processes.
It changed at some point to launch a single process that forked.
What is happening now is there is we are only getting the statistics
from the parent and not from the children.
This is a temporary hack, to get this info until this PR is submitted
and makes it into a build:
https://github.com/ManageIQ/manageiq/pull/17302
And even that is a temporary solution until CFME takes ownership
of generating code coverage statistics as a full feature.
{{ pytest: --use-provider rhv41 --ui-coverage  cfme/tests/cloud_infra_common/test_vm_ownership.py }}

[1LP][RFR]Temporary patch to track coverage in forked CFME processes

---

cfme/utils/tracer.py
requirements/template_docs.txt
scripts/jenkins_failure_analysis.py

* take it completely out of tracer for just wraps
* use sorting instead of lru_cache in scripts/jenkins_failure_analysis.py

[1LP][RFR] remove the need for functools32

---

cfme/tests/infrastructure/test_vm_power_control.py

{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_guest_os_shutdown --long-running}}

[1LP][RFR] Activating test_guest_os_shutdown for RHV

---

cfme/services/myservice/ssui.py
cfme/tests/infrastructure/test_snapshot.py
cfme/tests/infrastructure/test_vm_reconfigure.py
cfme/tests/ssui/test_ssui_myservice.py

Yet another pull request for __RHV markers__. There is also a little __workaround__ that is needed until #7157 is fixed.
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_myservice_crud --long-running --use-provider rhv41}}

[1LP][RFR] Adding some more RHV markers

---

cfme/utils/appliance/db.py

* The restart_db_service call was missing parentheses, which meant that
connections would hang open and prevent certain operations
* The dropping of the database was placed inside the wait_for, this
could yield another issue where we try to drop a database which has
already been dropped.

[1LP][RFR] Fix 2 bugs with dropping database

---

cfme/tests/integration/test_aws_iam_auth_and_roles.py

BZ has been verified and can be removed from test

[1LP][RFR] Remove verified BZ from auth integration tests

---

cfme/scripting/quickstart.py

It seems that:
yum debuginfo-install -y python
on RHEL 7 does not work.  In fact the RHEL 7 docs show calling
debuginfo-install the exectuable directly as in:
debuginfo-install -y python
It also seems that dnf has debuginfo-install baked into, without the
need for an external package.
This commit then does:
1) Change systems with yum to call debuginfo-install directly.
2) Install on RHEL7 systems the yum-utils package that contains
debuginfo-install.
**TEST RESULTS on RHEL 7:**
```
[root@dhcp-8-198-201 integration_tests]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@dhcp-8-198-201 integration_tests]# python -m cfme.scripting.quickstart
QS $ yum install -y python-virtualenv gcc postgresql-devel libxml2-devel libxslt-devel zeromq3-devel libcurl-devel …
```

[1LP][RFR][notest] quickstart RHEL7 debuginfo-install fix

---

sprout/appliances/tasks.py

it should help to find out why some providers become disabled for some time

[RFR] add logging and retry for enable/disable provider check in sprout

---

fixtures/parallelizer/__init__.py

this wont need a test using the plugin, since the hooks are added in all cases

[RFR] fix relative import in parallelizer

---

cfme/containers/image.py
cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py

Since smart state analysis (SSA) on container images, is able to check only images from redHat registry, 
I add an ability to filter active images from redHat registry, on containers image collection.
{{pytest: cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py -v --use-provider ocp-v1 }}

[1LP][RFR] Containers images collection,add ability to filter active images from redHat registry

---

cfme/tests/configure/test_docs.py

removes get_or_create_current_appliance in various places where its already possible, this ensures better code behaviour

[HOLD] Clean out many get_or_create_current_appliance usages

---

cfme/tests/intelligence/chargeback/test_resource_allocation.py

{{pytest: cfme/tests/intelligence/chargeback/test_resource_allocation.py --use-provider complete}}
PRT results:
58 - passed
59 - passed

[1LP][RFR] chargeback tests to validate resource allocation costs

---

sprout/appliances/tasks.py

REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/253

[RFR][1LP] removing retry from check template task because it produces many failed tasks for invalid providers

---

cfme/networks/cloud_network.py
cfme/tests/networks/test_provision_to_virtual_network.py

Test that VM can be provisioned to virtual network create in RHV OVN.
Test case definition in polarion: https://polarion.engineering.redhat.com/polarion/#/project/RHEVM3/wiki/CFME/4_2_cfme_ovn
Feature page: https://www.ovirt.org/blog/2016/11/ovirt-provider-ovn/
ManageIQ integration: https://www.ovirt.org/develop/release-management/features/network/manageiq_ovn/

[1LP][RFR] Added test case to test provision of VM to OVN network.

---

cfme/tests/intelligence/chargeback/test_resource_allocation.py

{{pytest: cfme/tests/intelligence/chargeback/test_resource_allocation.py --use-provider complete --long-running}}

[1LP][RFR] Chargeback resource allocation : Add support for other providers

---

cfme/tests/openstack/infrastructure/test_relationships.py

Used iapi to get node list
{{ pytest: cfme/tests/openstack/infrastructure/test_relationships.py::test_nodes }}

[1LP][RFR] fixed test_nodes test

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Purpose of this PR is this:
1. test_ssa_vm a special [provision](https://github.com/ManageIQ/integration_tests/blob/8624a13117640a8007d12642833c2c3ebf8c4db8/cfme/tests/cloud_infra_common/test_vm_instance_analysis.py#L602) for RHEL VM that is missing in test_ssa_schedule, resulting in failure.
2. I found a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1578792) concerning counting number of services on RHEL VM. Because of it, results of SSA are unreliable. Therefore I blocked the test case for scenarios where RHEL VM is used. I know that `unblock` there is quite dirty, but I did not want to block it for all other scenarios. Please let me know what do you think.
3. Correction of soft_assert failure message in test_ssa_vm.
Regarding PRT: I don't really know how to test it, since `rhv41` …

[1LP][RFR] Fixing test_ssa_schedule for RHEL VM

---

cfme/common/vm_console.py

vm_console was checking the state of console_handle, instead of console_handle checking its own value before returning None.
Allows for some more pythonic use of console_handle classmethod and uses a more appropriate ValueError
Found during VMCollection work in #7107  and pulled out for separate consideration.

[1LP][RFR] Move console handle check and change exception type

---

cfme/tests/candu/test_utilization_metrics.py

- Add proper `wait_for`
- moved test file to `candu` dir
{{pytest: cfme/tests/candu/test_utilization_metrics.py -v --use-provider complete --long-running }}

[1LP][RFR] Raw metric test wait_for and relocate 

---

cfme/tests/openstack/infrastructure/test_host_lifecycle.py

Replace fail_func of wait_for and added provider refresh to fix non-existence of registered host
{{ pytest: cfme/tests/openstack/infrastructure/test_host_lifecycle.py }}

[1LP][RFR] fixed test_register_host test

---

cfme/tests/control/test_actions.py

Can't have a property that's in `__slots__`
Don't really care about PRT results here, this is to fix a travis failure during collection for py3.6

[WIPTEST] Fix crud property and __slots__ for test_actions

---

cfme/networks/floating_ips.py
cfme/tests/networks/test_sdn_balancers.py
cfme/tests/networks/test_tag_tagvis.py

Covers tag visibility for network items
{{pytest:: -k (test_network_tagvis or test_sdn_balancers_tagvis) -vvv --use-provider complete}

[1LP][RFR]Network tag visibility tests

---

cfme/tests/infrastructure/test_cloud_init_provisioning.py
data/rootpass.cfg

This PR __activates__ `test_provision_cloud_init` for RHV-CFME integration. 
So what's it about?
- Fixing `provisioning_data` supplied to VM provision request.
- Fixing `required_fiels` of provider.
- Providing new customization template. This probably needs some explanation. The [customization template ](https://github.com/ManageIQ/integration_tests/blob/master/data/basiccloudinit.cfg)that is already presentein integration_tests could not be reused. The reason is that no user is specified there. In such case, cloud-init changes password of the default user. That is fedora for Fedora, ubuntu for Ubuntu etc. However, RHEL (which we use as VM's OS) does not have such user. Therefore I had to provide customization template that changes root password. 
I am not providing any `{ pytest }` …

[1LP][RFR][NOTEST] Adding cloud-init test for RHV

---

widgetastic_manageiq/__init__.py

Locator forcing the `expandable` method to return False, resulting in `items` returning 'Change Groups' when the UI was actually expandable, instead of the list of group names.
Tested locally, setting to RFR since its so small.
{{ pytest: cfme/tests/configure/test_access_control.py -k 'test_user_assign_multiple_groups or test_user_change_groups' }}

[RFR] Fix locator in SettingsGroupSubmenu

---

cfme/tests/intelligence/reports/test_report_corresponds.py

{{pytest: cfme/tests/intelligence/reports/test_report_corresponds.py::test_custom_vm_report --use-provider rhv41 -vv}}

[1LP][RFR] Activating test_custom_vm_report for RHV-CFME

---

conf/credentials.yaml.template

__Fixing__ credentials template indent by using 4 spaces because the entire project use that indent size and just a few lines are using 2 spaces.

[1LP][RFR] Fix credentials template indent

---

cfme/tests/openstack/cloud/test_instances.py

IP Addresses returned by hypervisors list don't match IP Addresses returned by hosts, So under current implementation this test will always fail and should be skipped
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_list_vms_infra_node }}

[1LP][RFR] Skipping test: hypervisors IPs don't match Hosts IPs

---

cfme/tests/cloud/test_providers.py

{{ pytest: --use-provider=ec2west cfme/tests/cloud/test_providers.py::test_select_key_pair_none_while_provisioning}}

[RFR] fix one test broken by collection conversion

---

cfme/cloud/instance/__init__.py
cfme/tests/cloud/test_tenant_quota.py

Add template_name arg to instantiate call within create, pulling from form_values
{{ pytest: cfme/tests/cloud/test_tenant_quota.py --long-running -v  --use-provider complete }}

[1LP][RFR] Fix instance create in test_tenant_quota

---

cfme/containers/image.py
cfme/containers/image_registry.py
cfme/containers/node.py
cfme/containers/pod.py
cfme/containers/project.py
cfme/containers/replicator.py
cfme/containers/route.py
cfme/containers/service.py
cfme/containers/template.py
cfme/containers/volume.py

With the updates coming in https://github.com/ManageIQ/wrapanapi/pull/255/files, there is no need to have a separate method to access the mgmt interface. It should be access using `provider.mgmt`.
The mgmt method was not used in any of the cmqe tests
{{ pytest: cfme/tests/containers/test_alerts.py cfme/tests/containers/test_node.py cfme/tests/containers/test_start_page.py --use-provider ocp-36-hawk }}

[1LP][RFR] Remove mgmt method from CMQE object classes

---

cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/ssui/test_ssui_ansible_service.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

See #7297 for reason behind this PR.
PRT: One test that's failing has apparently another issue.
{{pytest: cfme/tests/ssui --long-running -vv --use-provider rhv41}}

[1LP][RFR] Skipping tests blocked by issue #7297

---

cfme/utils/appliance/implementations/ui.py

it turned out that ManageIQ isn't present in SSUI. So, page_has_changes should probably return false in such case.
{{pytest: --long-running cfme/tests/ssui/test_ssui_dashboard.py}}

[1LP][RFR] fix for SSUI tests failing on page_has_changes js 

---

cfme/fixtures/service_fixtures.py
cfme/services/catalogs/catalog_items/__init__.py
cfme/services/myservice/ssui.py
cfme/tests/ssui/test_ssui_myservice.py

some of collection conversions broke ssui tests because catalog items lost provider property.
This PR fixes some of such tests.
{{pytest: --use-template-cache --use-provider=rhv41 --long-running cfme/tests/ssui/test_ssui_myservice.py}}

[RFR] added provider to catalog items

---

cfme/tests/cloud/test_providers.py

- Test Domain Id required for keyston v3
- removed Intance as not used in code my git hook not allow me to commit
{{pytest: cfme/tests/cloud/test_providers.py::test_domain_id_validation --use-provider rhos11}}

[1LP][RFR] domain id validation for osp

---

cfme/common/provider_views.py
cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_providers.py

Fixing a few issues I came across while troubleshooting SCVMM test failures in the latest 59z master test run
{{pytest: --use-provider scvmm --use-provider scvmm2016 cfme/tests/infrastructure/test_providers.py -k 'test_multiple_host_bad_creds or test_infra_provider_add_with_bad_credentials' --long-running}}

[1LP][RFR] Scvmm test fixes

---

cfme/cloud/provider/__init__.py
cfme/tests/cloud/test_providers.py

- Automating test  RHCF3-11608 
- This test similar to the provider discovery, only with false data also discovery will start but provider will not apper. 
 
{{pytest: cfme/tests/cloud/test_providers.py::test_discovery_error_azure_cloud}}

[1LP][WIPTEST] Test: azure_provider_discovery_error

---

cfme/tests/networks/test_sdn_downloads.py

- No need of `instantiate` as `all()` method returning `list` of `instantiate` objects
{{pytest: cfme/tests/networks/test_sdn_downloads.py -k test_download_pdf_summary --use-provider complete}}

[1LP][RFR] fix summery download test for N/W

---

cfme/utils/trackerbot.py

add 510 to stream-parsers.
This will eventually get replaced with miq_version package use when template upload gets merged.

Add 510z stream parser to trackerbot client util

---

cfme/tests/infrastructure/test_provisioning_rest.py

PRT failure: Sprout provision failed
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_attributes -vv}}

[RFR] Wrapping test_provision_attributes with BZ1592326

---

cfme/utils/appliance/__init__.py

Ansible pod starts very slow first time. So, some tests fail. This is temporary workaround.

[1LP][RFR] workaround for some bug in ansible pod

---

cfme/fixtures/has_persistent_volume.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/template.txt

Remove wrapanapi call to create a persistent volume if one no longer exists, the create method was removed in https://github.com/ManageIQ/wrapanapi/pull/255/files. 
{{ pytest: cfme/tests/containers/test_relationships.py --use-provider cmqe }}

[1LP][RFR] Fix CMQE Persistent Volume Fixture

---

cfme/tests/infrastructure/test_provisioning_rest.py

Turns out that the problem with test_provision_attributes is an actual product bug, therefore replacing GH issue with BZ.
PRT: On downstream-58z get_keys.py script failed for some reason - not a bad sig though.
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_attributes -vv}}

[1LP][RFR] Wrapping test_provision_attributes with BZ1592326

---

cfme/fixtures/authentication.py
cfme/tests/integration/test_cfme_auth.py

Yaml change already merged, PRT should pass?
There will be 2nd PR with new switch-groups test for ext auth, wanted to keep this scope small to cover the multiple-groups support.
PRT failures aren't related to these changes, but to login failure or provider configuration.
{{ pytest: cfme/tests/integration/test_cfme_auth.py --long-running }}

[1LP][RFR] Update ext-auth tests to handle multiple groups

---

cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/infrastructure/test_vm_reconfigure.py

PRT: Test failed for virtualcenter-6.5. However it seems pretty much unconnected to the bug. The failure happens during test teardown when deleteing VM from provider. However, I cannot really fix wrapanapi methods for VMWare.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_archived_vm_status -vv --long-running}}

[1LP][RFR] Adding wrappers for BZ1591606 and BZ1592430

---

cfme/utils/template/template_upload.py
cfme/utils/trackerbot.py
scripts/sync_template_tracker.py
scripts/template_upload_all.py

We have to get rid of many duplicate sets of regexps for version parsing. miq-version has been updated recently to support all those old regexps. So, we can eventually remove replace those regexps with miq-version calls.

[1LP][RFR] replace steam regexps in favor of miq-version

---

cfme/base/__init__.py

So, @psav s temporary patch #7158 should be used for it as well

[1LP][RFR] server name isn't available for pod 5.10 now

---

cfme/tests/test_login.py
cfme/utils/browser.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
requirements/template_docs.txt

* Forces chrome to run in --no-sandbox mode with Remote webdriver
* Forces Marionette to False for Firefox, which is required for older
FF versions
This is really just to allow us to support the fact that 5.10 MUST at
the moment run under Chrome, but that we want to allow original tests
of 5.9 and 5.8 to run under Firefox still.
NOTE: This is temporary and fully expected to be removed once FF 60.1
is out.

[1LP][RFR] Change required to support dual browser setup in container

---

cfme/networks/provider/__init__.py
cfme/tests/networks/test_sdn_crud.py
cfme/tests/networks/test_sdn_navigation.py

- added support for filtering provider in `NetworkProvider` `all()` method
- related some changes. 
- may be tests releted to rhos11 will fail due to deletion problem going on with rhos provider. 
{{pytest: cfme/tests/networks/test_sdn_navigation.py  cfme/tests/networks/test_sdn_crud.py --use-provider complete -sqvv}}

[1LP][RFR] all method filtering support NetworkProvider

---

cfme/tests/cloud/test_cloud_timelines.py
cfme/tests/networks/test_sdn_balancers.py
cfme/tests/networks/test_sdn_inventory_collection.py
cfme/tests/networks/test_sdn_navigation.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

__Updating tests__  by adding test_flag. main reason - we don't want to collect\run these test on azure_msdn. another PR will be into yamls

[RFR][NOTEST]flagging tests to avoid collection for azure_msdn

---

setup.py

__Fixing setup.py__  Removing infrastructure_mapping collection as we have  v2v_mappings collection. Somehow we ended up with duplicates. 
Compare line 140 with 180 in setup.py

[1LP][RFR] Removing infrastructure_mapping collection as we have v2v_mappings collection

---

cfme/scripting/quickstart/system.py
cfme/utils/browser.py

Allow quickstart to support Fedora 28

[RFR] Allow quickstart to support Fedora 28

---

cfme/utils/hosts.py

Fixes https://github.com/ManageIQ/integration_tests/pull/7327's failure.
PR7327 is waiting and dependent on another pending PR hence fixing it separately.
Should be merge before PR7327.
`Error: principle not found in dict`

[1LP][RFR] Fixed remove_creds step

---

cfme/configure/settings.py
cfme/tests/configure/test_default_views_cloud.py
cfme/tests/configure/test_default_views_infra.py

Added test case of 'Reset' button to check whether it is enable or disable.
{{ pytest: cfme/tests/configure/test_default_views_infra.py cfme/tests/configure/test_default_views_cloud.py }}
Note: This test runs and passes successfully on my local environment, but fails here, since my gpg key hasn't been merged into cfme-qe-yamls yet.

[1LP][RFR] Add 'Reset' button test case

---

cfme/tests/configure/test_help_menu.py

Add a new test case to check if editing items in the help menu actually updates the help menu.
{{ pytest: cfme/tests/configure/test_help_menu.py }}
Note: This test runs and passes successfully on my local environment, but fails here, since my gpg key hasn't been merged into cfme-qe-yamls yet.

[1LP][RFR] Automate test for help menu

---

cfme/v2v/migrations.py

5.9.3.2/5.10 introduced new dropdown so changed text
```
In [1]: from widgetastic_manageiq import MigrationDropdown
In [2]: view = navigate_to(appliance.server, 'LoggedIn')
In [3]: x = MigrationDropdown(view, text='Not Started Plans')
In [4]: x.items
Out[4]: 
[u'Not Started Plans',
u'In Progress Plans',
u'Completed Plans',
u'Archived Plans']
```

[1LP][RFR] v2v: Renamed new dropdown

---

cfme/tests/infrastructure/test_advanced_search_vms.py

Changed test_can_open_vm_view -> test_can_open_vm_advanced_search  to make it corresponding with Polarion and tests in same category.

[1LP][RFR] Changed test_can_open_vm_view -> test_can_open_vm_advanced_search 

---

cfme/tests/v2v/test_v2v.py
cfme/utils/appliance/__init__.py

__Extending IPAppliance__ to add new methods that can enable/disable migration UI.
and
__Adding test__ to enable and disable migration UI and validate if it shows/hides 'Migration' option on navigation bar.
{pytest: cfme/tests/v2v/test_v2v.py -k 'test_migration_ui_enable_disable' -vvvv}

[1LP][RFR]Adding appliance method to enable-disable migration UI, and test it

---

cfme/tests/candu/test_utilization_metrics.py

BZ fixed on 5.9 and 5.10 so enabling support of gce
{{pytest: cfme/tests/candu/test_utilization_metrics.py -v --use-provider gce_central}}

[1LP][RFR] enable gce for metric on 5.9

---

cfme/utils/ssh.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

paramiko's _ready calls hang if out of the blue destination host  gets unavailable.
This PR is going to handle this issue.

[1LP][RFR] circumvent issue when ssh.run_command hangs if appliance suddenly got unavailable 

---

cfme/tests/networks/test_sdn_crud.py

* This test case needs to go to details page of provider. 
which can be done by ```view = navigate_to(network_provider, 'Details')``` - It navigates to network > providers > Details page 
* ```view = navigate_to(provider, 'Details')``` - It navigates to compute > provider  > Details Page. This   **extra navigation** is not required for this test case. Because it is not used in test execution.
{{ pytest: cfme/tests/networks/test_sdn_crud.py }}

[1LP][RFR]Extra navigation in test_sdn_crud.py

---

cfme/infrastructure/provider/__init__.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/v2v/migrations.py

__Adding fixtures__ for migration tests. These fixtures will enable us to perform migration tests. Currently only fixtures are added. Initial  provider setup is taken from https://github.com/ManageIQ/integration_tests/pull/7327 and actual tests will be added in the separate PR, tests in this PR are just for demonstration purpose.
~~**NOTE** results of execution of these test will depend on https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/545~~
{{pytest: cfme/tests/v2v/test_v2v_migrations.py  --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv}}

[1LP][RFR] V2V migration tests fixtures

---

cfme/utils/bz.py

I was hitting an instance where variant.version was a string, not a version object - occurring in PRT but was not able to reproduce locally with the same BZ definition and options.
Make the if-statement checks more robust, checking for object type since we're calling a method from an expected class
A piece of this is included in #7436 since it was blocking PRT execution there.

[1LP][RFR] Check version type before calling functions in utils.bz

---

cfme/tests/cloud/test_quota_tagging.py

{{pytest: --long-running --use-provider=rhos11 cfme/tests/cloud/test_quota_tagging.py}}

[1LP][RFR] fixing quota tagging tests broken by collections conversion

---

cfme/utils/bz.py

@jan-zmeskal found some cfme_data.yaml queries still in utils/bz.py, that I missed in earlier PR to move things to env.
DRY up the config lookups by storing the env.yaml config as an object attribute.
```
In [1]: from cfme.utils.blockers import BZ
In [2]: from cfme.utils.conf import env
In [3]: env.get('bugzilla')
Out[3]: 
AttrDict([('url', 'https://bugzilla.redhat.com/xmlrpc.cgi'),
('loose', ['target_release', 'version', 'fixed_in']),
('upstream_version', 'master'),
('credentials', 'bugzilla'),
('skip', ['ON_DEV', 'NEW', 'ASSIGNED'])])
In [4]: b = BZ(1527239)
In [5]: b.bugzilla.loose
Out[5]: ['target_release', 'version', 'fixed_in']
In [6]: b.bugzilla.open_states
Out[6]: ['ON_DEV', 'NEW', 'ASSIGNED']
In [7]: b.bugzilla.upstream_version
Out[7]: Version('master')
```

[1LP][RFR] Remove cfme_data use in utils.bz

---

cfme/provisioning.py
cfme/tests/networks/test_provision_to_virtual_network.py

The testcase for provisioning vm into virtual network requires vm_name fixture, which was probably accidentally removed during code review process.
Currently, this fix depends on  #7410, because InfraVm doesn't have navigation step to Provision.
{{pytest: --use-provider complete --long-running -vv cfme/tests/networks/test_provision_to_virtual_network.py}}

[1LP][RFR] Fix provisioning vm to virtual network

---

cfme/utils/bz.py

~~We were seeing BugWrapper().is_opened calls resolve via `__getattr__` instead of the property.
Moving this definition below all the properties~~
This is real strange behavior, @psav and I looked at it together.
The property was raising an AttributeError, which was triggering the __getattr__ call.
{{ pytest: --long-running --use-provider rhv41 cfme/tests/infrastructure/test_vm_power_control.py -k test_no_template_power_control }}

[RFR] Update Bugzilla.open_states, return set

---

cfme/tests/networks/test_tag_tagvis.py

Fix for:
```
TypeError: __init__() got an unexpected keyword argument 'prov_class'
```
{{pytest: cfme/tests/networks/test_tag_tagvis.py -k test_tagvis_network_provider_children}}
Maybe teardown will fails as it using OpenStack provider :D

[1LP][RFR] Removed network provider class use and added use of collection filtering

---

cfme/tests/containers/test_basic_metrics.py

{{ pytest : cfme/tests/containers/test_basic_metrics.py::test_flash_msg_not_contains_html_tags --use-provider ocp-36-hawk}}

[1LP][RFR]Add test for validating flash message tags

---

cfme/common/provider_views.py
cfme/containers/provider/openshift.py

Updated view_value_mapping method in OpenshiftProvider class to enable virt_type for downstream builds, "Virtualization" drop down was added in downstream 510.
Updated .get to default to "Disabled" by default if the value is not found. 
Fixed variable naming. 
{{ pytest: cfme/tests/containers/test_node.py cfme/tests/containers/test_static_custom_attributes.py  --use-provider cmqe }}

[1LP][RFR] Add virt_type Support for Downstream OpenShiftProvider

---

scripts/sync_template_tracker.py

it turned out that some providers have templates w/o name. 
When such templates are processed by sync_template_tracker script, those are 1. added to trackerbot; 2. all templates are removed  from trackerbot.
this PR adds some protection from such templates.

[RFR] make sync_template_trackerbot script ignore templates with empty name

---

cfme/utils/appliance/__init__.py
scripts/template_upload_openshift.py
sprout/appliances/tasks.py

Developers removed ansible from cloudforms template in the newest downstream. Default ansible image stream url points out to access.registry.redhat.com whilst we need to use our internal repo in this case. In addition, we have to specify exact tag in such case. This PR intends to get around this change by saving image stream urls along with tags and passing them everywhere during deployment. Finally, appliance is patched with correct url and tag before usage.
Stuff to change:
1. upload template script
2. wrapanapi
3. sprout
4. IPAppliance

[1LP][RFR] ansible url fix for pod appliances

---

cfme/common/vm.py
cfme/common/vm_views.py
cfme/infrastructure/host.py
cfme/tests/cloud/test_instance_power_control.py
cfme/tests/distributed/test_appliance_replication.py
cfme/tests/infrastructure/test_vm_power_control.py

Later CFME versions drop the ability to access 'quadicon' attribute. So
in order to fix this, we now access each corner through the tooltips.
This meant that it made more sense to do actual comparisons instead of
looking for substrings.
{{pytest: cfme/tests/infrastructure/test_vm_power_control.py -k TestControlOnQuadicons.test_power_on_cancel --long-running}}

[1LP][RFR] Fix for quadicon states

---

cfme/tests/infrastructure/test_pxe_provisioning.py

{{pytest: cfme/tests/infrastructure/test_pxe_provisioning.py::test_pxe_provision_from_template --long-running --use-provider rhv41}}

[1LP][RFR] Blocking test_pxe_provision_from_template by #7494

---

cfme/tests/services/test_pxe_service_catalogs.py

{{pytest: cfme/tests/services/test_pxe_service_catalogs.py::test_pxe_servicecatalog --long-running --use-provider rhv41}}

[1LP][RFR] Skipping test_pxe_servicecatalog because of #7491

---

cfme/tests/containers/test_overview_data_integrity.py

Update get_api_object_counts, change old method list_container_group to new list_pods method.
{{pytest: cfme/tests/containers/test_projects_dashboard.py -v --use-provider ocp-36-hawk}}

[1LP][RFR] Update Container test overview data integrity according to wrapanapi changes

---

cfme/tests/infrastructure/test_child_tenant.py

{{pytest: cfme/tests/infrastructure/test_child_tenant.py::test_child_tenant_quota_enforce_via_lifecycle_infra --long-running --use-provider rhv41}}
PRT was actually successful: http://10.16.4.32/trackerbot/pr/run/25164#0JoWcFYF

[1LP][RFR] Blocking test_child_tenant_quota_enforce_via_lifecycle_infra with GH7385

---

cfme/common/vm.py
cfme/infrastructure/host.py

- while working with Capacity and Utilization. I found that there must be support for capture historical data with `vm` or `host` object directly. It will help in Utilization automation. 
- Added `capture_historical_data()` method having default `6 day` back data capacity.
- Provided flexibility to modify with arguments.

[1LP][RFR][NOTEST] support for capturing historical data

---

sprout/appliances/tasks.py

It makes sense to set ansible urls only for cfme > 5.10. So, this forgotten if statement has to be added.

[RFR] ansible url fix for sprout

---

cfme/tests/infrastructure/test_quota_tagging.py
cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_pxe_service_catalogs.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py
cfme/tests/ssui/test_ssui_ansible_service.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

Plus removing some old blockers that are not needed any more.
{{pytest: cfme/tests/services/test_pxe_service_catalogs.py cfme/tests/infrastructure/test_tenant_quota.py cfme/tests/infrastructure/test_quota_tagging.py cfme/tests/ssui/test_ssui_service_catalogs.py cfme/tests/ssui/test_ssui_myservice.py cfme/tests/ssui/test_ssui_dashboard.py cfme/tests/services/test_service_manual_approval.py cfme/tests/services/test_service_catalogs.py cfme/tests/services/test_different_dialogs_in_catalogs.py --use-provider rhv41 --long-running}}

[1LP][RFR] Blocking several service tests because of #7479

---

cfme/infrastructure/host.py
cfme/infrastructure/openstack_node.py
cfme/infrastructure/provider/__init__.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/configure/test_schedule_operations.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_compliance.py
cfme/tests/infrastructure/test_esx_direct_host.py
cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_host_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_vm_migrate.py
setup.py

Purpose
`provider.hosts` should return a hosts collection filtered out by the provider.
{{pytest: -v -k "test_schedule_timer or test_vm_migrate or test_host_drift_analysis" --long-running}}

[1LP][RFR] Fixed provider and hosts relationships

---

cfme/services/service_catalogs/ui.py

Multiple services tests re failing due to missing flash message 'Order Request was Submitted'. BZ for 5.10 is created and this fix should block asserting flash message. 
11 tests are failing because of missing flash message.

[1LP][RFR] - Missing flash message - Order Request was Submitted

---

cfme/tests/networks/test_provision_to_virtual_network.py

Fix TypeError: instantiate() takes at least 2 arguments (1 given)

[RFR] Add prov_class parameter to instantiate network provider

---

cfme/tests/infrastructure/test_provisioning_rest.py

Some REST provision tests were leaving leftover VMs on provider. And I like my env clean after executing regression suite. :-)
PRT: Since all of the stuff is uncollected with provider `rhv42`, here's a verification from our Jenkins: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/124/
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py --use-provider rhv42 -vv}}

[RFR] Cleaning up after REST provisioning tests

---

cfme/containers/provider/openshift.py
cfme/tests/containers/test_ssl_providers.py

{{ pytest: cfme/tests/containers/test_ssl_providers.py::test_add_mertics_provider_ssl --use-provider ocp-36-hawk }}
skipping add metrics endpoint test for providers without metrics endpoint

[1LP][RFR] Add retries to certificate copy while copy fails network issue occurs

---

cfme/tests/containers/test_reports.py

Einat wanted to move the entire test_reports under the long_running_env marker

[RFR] CMQE Move long_running_env marker

---

cfme/tests/infrastructure/test_tenant_quota.py

* This test checks whether vm could be able to migrate after assigning tenant quota
* It creates vm first then assigns tenant quota
* After assigning tenant quota; it migrates vm and checks migration is done successfully or not
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py::test_vm_migration_after_assigning_tenant_quota --long-running --use-provider rhv41 }}

[1LP][RFR] Test for checking vm migration after assigning tenant quota

---

cfme/tests/infrastructure/test_tenant_quota.py
cfme/utils/providers.py

* In the case of nested keys, sometimes different providers have set
things up differently and have a string where another provider has a
set of nested keys.
* This makes that allowable when provider filtering.

[1LP][RFR] Fix in the case a required field is a string

---

cfme/utils/appliance/__init__.py

When calling `get_vm()` it may raise `VMInstanceNotFound`

[RFR] Catch VMInstanceNotFound in IPAppliance

---

cfme/fixtures/provider.py
cfme/markers/env_markers/provider.py

* --legacy-ids option added this will disable type/version
parametrization
* --disable-selectors option disables the use of selectors

[1LP][RFR] Add legacy options for parametrization

---

cfme/tests/control/test_actions.py
scripts/clone_template.py

Use `flavor_name`, yaml change already merged.
wrapanapi 3.0 changed this arg spelling so we can't pass it as 'flavour_name' anymore.

[RFR] Clone template rhos flavor

---

cfme/networks/provider/nuage.py

Add `num_cloud_tenant` and  `num_network_router` function that checks number of cloud tenants and network routers on UI.
Depends on: https://github.com/ManageIQ/wrapanapi/pull/296 , https://github.com/ManageIQ/integration_tests/pull/7452 , https://github.com/ManageIQ/integration_tests/pull/7450

[1LP][RFR] Implement test count for tenants and routers

---

cfme/tests/openstack/cloud/test_instances.py

Add new to cloud test_instances: test_instance_operating_system_linux
New entry was introduced on cfme_data.local.yaml:  ['provisioning']['image']['os_distro']
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_operating_system_linux }}

[1LP][RFR] Add test_instance_operating_system_linux to test_instances

---

cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_individual_host_creds.py

Format of credentials of hosts in yamls has changed recently. Example:
credentials:
default: vspherehost-nested
remote_login: vspherehost-nested
web_services: vspherehost-nested
Fixed access to these credentials in test_host.py and extended the test to run for all credential types.
Additionally, uncollecting tests for 'remote_login' and 'web_services' for RHV provider, as these are not relevant for RHV. (https://bugzilla.redhat.com/show_bug.cgi?id=1591228)
{{ pytest: cfme/tests/infrastructure/test_host.py cfme/tests/infrastructure/test_individual_host_creds.py }}

[1LP][RFR] Fix reading host credentials from yaml to reflect recent changes

---

cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py

Adding tests for feature containers SSA, that checks RFE BZ 1459189, Allow specifying per provider,
The location of OpenSCAP CVEs and image-Inspector image.
In order to verify the above setup, run a smart state analysis on container image.
They were implemented in CFME 5.9 and above.
{{pytest: cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py -v --use-provider ocp-36-hawk}}

[1LP][RFR]  Specify per containers provider the location of OpenSCAP CVEs and Image-Inspector image

---

cfme/control/explorer/alert_profiles.py

{{pytest: -v cfme/tests/control/test_basic.py::test_alert_profile_crud --long-running}}
This PR fixes 6 tests.

[1LP][RFR] Fix alert profiles update method

---

cfme/tests/networks/test_sdn_downloads.py

This commit fixes issues with downloading pdf. "Download to PDF" has been changed to "Print or export as PDF" in 5.10, and I've changed that accordingly in the test case.
{{ pytest: cfme/tests/networks/test_sdn_downloads.py -k test_download_lists_base -vvv }}

[1LP][RFR] Fix 5.10 PDF issue 

---

entry_points.txt

the introduction of this file was in a race with the introduction of stricter linting
thus the failure was missed

[1LP][RFR] fix end of file of the entry_points.txt

---

cfme/fixtures/v2v.py
cfme/test_framework/pytest_plugin.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/utils/appliance/__init__.py

Currently executing via,
```pytest test_v2v.py --use-provider complete --provider-limit 2 --use-template-cache```
Tasks done:
1. Added mutli-provider usage
2. Removed pytest_generate_tests from tests
3. Moved common fixtures to v2v.py
Steps:
1.Add rhvm and nvc providers and return provider objects
2.Validate host credentials
3.Assign tags to conversation host
~~4.Import automate domain via github repo~~
{{pytest: cfme/tests/v2v/test_v2v.py --use-template-cache --use-provider rhv42 --use-provider vsphere6-nested --provider-limit 2 -vvvv}}

[1LP][RFR] Initial setup for v2v

---

cfme/tests/automate/test_buttons.py

{{pytest: cfme/tests/automate/test_buttons.py::test_button_on_host --long-running -vv --use-provider rhv42}}
It used to throw:
> host = appliance.collections.hosts.all(provider)[0]
> E TypeError: all() takes exactly 1 argument (2 given)
Verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/134/

[1LP][RFR] Fixing test_button_on_host

---

cfme/physical/provider/__init__.py

this PR fixes the name of the button the test should click to add a new physical provider

[1LP][RFR] fix ui button name to add Physical Infrastructure Provider

---

cfme/tests/cloud_infra_common/test_relationships.py

Verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/135/console
This used to throw:
> TypeError: all() takes exactly 1 argument (2 given)
The reason I used `appliance.collections.hosts.filter({'provider': provider})` as opposed to `provider.hosts` is that if you call `all()` method on `provider.hosts`, the framework will navigate to Compute -> Infrastructure -> Providers -> <your_provider> -> Hosts. This is a problem, because if you view hosts in such way, you cannot apply advanced search filter and you cannot see it if it has been applied before.

[1LP][RFR] Fixing host fixture in test_relationships

---

cfme/common/vm.py
cfme/infrastructure/host.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py

Host drift analysis fails on:
E       assert False
E        +  where False = <cfme.common.host_views.HostDriftAnalysis object at 0x7f20545a7ad0>.is_displayed
The problem begins on the following line:
https://github.com/ManageIQ/integration_tests/blob/5f4466953e7b0007b7810fbec30018e65115be56/cfme/tests/infrastructure/test_host_drift_analysis.py#L115
This line is supposed to check first two rows representing latest 2 analysis. What actually happens is that no line is selected. The reason is that indexes 0 and 1 both point to the first row, so the first row is selected and deselected afterwards.
Now, at this point I changed the indexes from 0,1 to 1,2 so that first and second row is selected correctly.
Better way to deal with this may be fixing the selection logic instead.
{{ pytest: …

[1LP][RFR] Fix clicking checkboxes on HostDriftHistory view

---

cfme/common/provider_views.py

Fixing ContainerProviderEditView is_displayed method, to use ProviderEditView 
is_displayed instead of ProviderAddView one.
{{pytest: cfme/tests/containers/test_provider_configuration_menu.py -v --use-provider ocp-39-hawk}}

[1LP][RFR] Update ContainerProviderEditView is_displayed to use ProviderEditView

---

cfme/infrastructure/provider/openstack_infra.py

This PR adds ability to get all openstack nodes from an openstack provider:
```python
nodes = provider.nodes.all()
```
Requires #7549

[1LP][RFR] Added relationship between Openstack Infra provider and Openstack Node

---

cfme/tests/services/test_rest_services.py

and fix ``is_retired``
{{pytest: --long-running -v -k test_retire_parent_service_now cfme/tests/services/test_rest_services.py}}

[1LP][RFR] Add BZ1608958 blocker

---

cfme/tests/containers/test_provider_configuration_menu.py

{{ pytest : cfme/tests/containers/test_provider_configuration_menu.py::test_ocp_operator_out_of_the_box --use-provider ocp-36-hawk }}

[1LP][RFR] Test OCP operator role out-of-the-box

---

cfme/tests/containers/test_ssl_providers.py

{{ pytest : cfme/tests/containers/test_ssl_providers.py::test_setup_with_wrong_port --use-provider ocp-39-hawk }}

[1LP][RFR] Add negative test (wrong API port for container provider)

---

cfme/fixtures/authentication.py
cfme/tests/integration/test_cfme_auth.py
cfme/utils/auth/__init__.py

Parametrizes the ext_auth tests on the user, instead of just looping through applicable users within the test cases.  Increases the number of collected tests pretty significantly, but allows for much more consistent and sane fixture use/cleanup.
1. PRT results will show `testuser16` and `testuser20`, both of these users are special cases (unicode passwords, no full name) that should be able to login, but I would like to address the fixes specific to these users as a separate PR and continue with review of the parametrization changes made here.
2. Failure for external mode and freeipa will occur on rhos-based appliances because they don't have resolvable FQDN properly configured.  #7445 should address this, but needs to be applied to the templatized images and we likely won't see the …

[1LP][WIPTEST] New auth providers users

---

cfme/infrastructure/pxe.py
cfme/tests/infrastructure/test_iso_datastore.py
cfme/tests/infrastructure/test_iso_provisioning.py
entry_points.txt

So, this PR does many things, let's look at them:
- Providing __new model__ of ISO SystemImage that can be found in ISO datastore. I mean this:
I did this because I want to be able to change `Type` of such ISO image. It might seem like an overkill. I also thought so. But then I realize I cannot really use existing models/views/navigation steps for this purpose without too much hacking. The approach that was used originally (`iso_datastore.set_iso_image_type`) simply was not working, because it was using wrong view (`ISODatastoreAll`). I believe this proposed approach is more in line with the overall philosophy of the framework and is extensible if the need arises. And it will (at least for me) in the near future.
- `test_iso_datastore_crud` now runs not only if provider definition …

[1LP][RFR] SystemImage and ISO datastore changes

---

cfme/utils/rest.py

Check for ``current_version < '5.9'`` is no longer needed. The issue was that when comparing version strings, '5.10' < '5.9'.

[1LP][RFR] Fix version string comparison in delete REST tests

---

cfme/tests/infrastructure/test_host_drift_analysis.py

This PR finishes the job that should have been done in #7568.
Thanks to @rlbabyuk for pointing out, that I forgot to change the equal_drift_results function call arguments. It would be unpleasant to see the test fail again ;).

[1LP][RFR] Fix clicking checkboxes on HostDriftHistory view (2. attempt)

---

cfme/infrastructure/host.py
cfme/tests/openstack/infrastructure/test_host_power_control.py

Used provider.nodes.all() and fixed wait_for_host_state_change method
{{ pytest: cfme/tests/openstack/infrastructure/test_host_power_control.py }}

[1LP][RFR] Used provider.nodes.all()

---

cfme/rest/gen_data.py
cfme/tests/configure/test_access_control.py
cfme/tests/configure/test_tag.py
cfme/tests/infrastructure/test_advanced_search_vms.py
cfme/tests/infrastructure/test_infra_tag_filters_combination.py
cfme/tests/infrastructure/test_rest_automation_request.py
cfme/tests/infrastructure/test_rest_templates.py
cfme/tests/infrastructure/test_vm_ownership.py
cfme/tests/infrastructure/test_vm_rest.py
cfme/tests/infrastructure/test_vm_retirement_rest.py
cfme/tests/services/test_operations.py
cfme/tests/services/test_rest_services.py
cfme/tests/test_rest.py

* The a_provider has always been problematic. The order of the providers
in the yamls is non-determinable. The provider filter used in most of
these cases also doesn't take into account the test flags. The problem
manifests that a provider can be used for a test when it really should
not.
* The change eliminates the a_provider fixture and moves towards using
the provider marker instead. This is function scoped, but has
protection against double setup. It also supports all the necessary
field flags and can run with selector=ONE meaning we only get one
provider test collected, but that the provider is known at collection
time. This will mean that there are less provider add/remove
operations on an appliance due to the "limit". It will also allow for
a slight speed increase in test running …

[1LP][RFR] This removes a_provider and replaces with equivalent provider marks

---

.travis.yml
cfme/networks/provider/__init__.py
cfme/tests/test_modules_importable.py
conf/cfme_data.yaml.template

It turns out that templates are innocent. Travis just doesn't have yamls. 
So, I think we have to remove templates from ignore list and make travis create basic yamls from templates instead.

[1LP][RFR]removal of new templates from test_modules_importable.py

---

cfme/tests/infrastructure/test_tenant_quota.py

It fixes 
1. 'type error' 
2. 'HostCollection object is not iterable error'
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py::test_vm_migration_after_assigning_tenant_quota --use-provider complete --long-running }}

[1LP][RFR] Fixed TypeError while collecting hosts

---

cfme/tests/cloud_infra_common/test_rest_providers.py

Exchanging the original BZ with its 5.9 clone. Detailed explanation in #7603.
{{pytest: cfme/tests/cloud_infra_common/test_rest_providers.py::test_query_provider_attributes --long-running}}

[1LP][RFR] Adding clone BZ to test_query_provider_attributes

---

cfme/cloud/provider/__init__.py
cfme/common/provider.py
cfme/infrastructure/provider/__init__.py
cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
cfme/tests/cloud_infra_common/test_cockpit_server.py
cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
cfme/tests/cloud_infra_common/test_html5_vm_console.py
cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/cloud_infra_common/test_relationships.py
cfme/tests/cloud_infra_common/test_rest_providers.py
cfme/tests/cloud_infra_common/test_retirement.py
cfme/tests/cloud_infra_common/test_tag_visibility.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/intelligence/chargeback/test_resource_allocation.py
cfme/tests/intelligence/reports/test_metering_report.py
cfme/tests/intelligence/reports/test_validate_chargeback_report.py

1. CloudInfraProvider class is removed.
2. All its methods are added to both Cloud and Infra providers.
3. All CloudInfraProvider calls are replaced with CloudProvider and InfraProvider.

[1LP][RFR] get rid of CloudInfraProvider class

---

cfme/infrastructure/virtual_machines.py

- Added one property to `VM` for collecting related `datastore`
- I need it for automating graphs stuff related to `datastore` and avoid redundant navigation to fetch name for relationship table.
In [1]: v = vm(provider=vsphere55)
In [2]: v.datastore
Out[2]: Datastore(name=u'h03-ds2', provider=VMwareProvider(endpoints={'default': <cfme.infrastructure.provider.virtualcenter.........)

[1LP][RFR][NOTEST] Related datastore for VM

---

scripts/clone_template.py
sprout/appliances/tasks.py

trackerbot's issue with wrong parsing JSONField's data has been fixed. Trackerbot should provide custom data in correct format. So, old bad decode statements aren't necessary now and can be removed

[RFR] remove bad json deserialization statements in sprout and etc

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
sprout/appliances/tasks.py

It turned out that last changes made generic shepherd choose wrong template for app name generation. therefore, wrong appliance name was generated for ocp appliances. 
This commit should fix such issue.
This change needs some local testing before merge.

[RFR] generic shepherd fix for openshift

---

cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py

{{pytest: cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init --long-running --use-provider rhv42 -vv}}
Verification run: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/147/console

[RFR] Making sure we've got VM IP in test_provision_cloud_init

---

cfme/tests/openstack/cloud/test_instances.py

navigation to AllForProvider view through deleted  instance.parent is not working.
Modified to be via collections with filtering
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_delete_instance }}

[1LP][RFR] fixed navigation to AllForProvider view via deleted instance

---

cfme/common/vm.py
cfme/infrastructure/host.py

- removed `repr` so compartable with `unicode` and `str`
- F401 'wrapanapi.exceptions.NotFoundError' imported but unused :+1: 
Shriver adding pytest:
{{ pytest: cfme/tests/candu/test_vm_graph.py cfme/tests/candu/test_host_graph.py }}

[1LP][RFR][NOTEST] fix for historical data with unicode and str

---

cfme/networks/provider/nuage.py

We're facing no problems modifying internal provider state, but since @RonnyPfannschmidt noticed it could be potentially dangerous, we're fixing it here as well. Also removing unused import by the way.
https://github.com/ManageIQ/integration_tests/pull/7472/files#r209255418

[1LP][RFR] Duplicate self.data to preserve internal state

---

cfme/networks/provider/nuage.py

With this commit we extend Nuage provider CRUD test to check for all the stats that currently inventoried. Nuage provider details page looks like this:
With this PR we now check all the 7 stats.
Depends on: https://github.com/ManageIQ/wrapanapi/pull/326

[1LP][RFR] Check all stats for Nuage provider

---

cfme/cloud/provider/__init__.py
cfme/common/provider_views.py
cfme/containers/provider/__init__.py
cfme/infrastructure/provider/__init__.py
cfme/networks/views.py
cfme/physical/provider/__init__.py

Modified `is_displayed` methods inside the following edit views:
1. `InfraProviderEditView`
2. `PhysicalProviderEditView`
3. `ContainerProviderEditView`
This change was made to fix the `is_displayed` methods of the above mentioned views, which returned `False` even if the page was displayed.

[1LP][RFR] Modify is_displayed method in every provider's Edit view

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
sprout/requirements.txt

This modifies the TemplateName ID for upstream ManageIQ to use `miq`

miq-version 0.1.7

---

cfme/utils/appliance/__init__.py
sprout/appliances/tasks.py

It turned out that 5.10 version comparison as a string doesn't work right. So, ansible url fix was applied to 5.9 as well.

[RFR] fixed version check in sprout

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Purpose of this PR is twofold:
1. Fix instantiating/creating of analysis profile. It used to throw this:
> TypeError: 'AnalysisProfileCollection' object is not callable
2. Renaming used analysis profile to anything different than "default". SSA used to work only when "default" analysis profile was used. However, since this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1553808) has been fixed, user should be able to provide any name for their analysis profile. 
Verification run: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CFME-DEV/job/cfme-5.9-rhv-4.2-integration-flow-dev/268/
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py --long-running --use-provider rhv41}}

[1LP][RFR] Fixing analysis profile creation for SSA tests

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/utils/appliance/__init__.py

```
file /var/ci/workspace/downstream-59z-tests-master/integration_tests/cfme/tests/v2v/test_v2v_migrations.py, line 235
@pytest.mark.parametrize('form_data_dual_datastore', [[['nfs', 'nfs'], ['iscsi', 'iscsi']],
[['nfs', 'local'], ['iscsi', 'iscsi']]], indirect=True)
def test_dual_datastore_dual_vm_mapping_crud(appliance, form_data_dual_datastore, migration_ui,
E       fixture 'providers' not found
```
DRY up the fixtures for the V2V modules, there was duplication and ambiguous fixture names causing confusion between the 2 test modules.
There are some open V2V PRs, but I want to get these simple fixes in for scope mismatches and such into the downstream-stable release.
There are some PRT failures to locate the provider record (its via rest), but this is outside of the scope of exceptions …

[1LP][RFR] DRY the fixtures for V2V

---

cfme/rest/gen_data.py
cfme/tests/services/test_rest_services.py

its version based, little while ago 'dialog_service_name' was added, but that's not available in 5.9z, so version pick and include the older regex search for the name in the expected message syntax.
few lines later the service request is pulled from the rest api collections again, and the name verified.

[1LP][RFR] Fix KeyError in test_rest_services for dialog_service_name

---

cfme/test_framework/sprout/plugin.py
sprout/appliances/tasks.py

1. sprout plugin returned appliances using pool.fulfilled attribute what is incorrect. it should use pool.finished instead.
2. rename_appliance task was made synchronous in order to get rid of cases when provided appliance is rebooted afterwards

[1LP][RFR] additional sprout client/server fixes in order to fix the issue caused by reboot during rename vm

---

cfme/utils/ssh.py

We were reading only from the stdout, therefore if there was something
available on stderr, it was available forever, causing deadlock.

[1LP][RFR] Remove deadlock from ssh client.

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt

`miq selenium-container` failed in Ubuntu 18.04, because this system only supports libssl version 1.1. The pycurl 7.43.0.1 expects the older version of openssl, so it crashes. We bump pycurl requirement to 7.43.0.2 [1] to address this.
[1] https://github.com/pycurl/pycurl/blob/01bc6af76dfec1d766857c4471076a06ec99d640/ChangeLog#L4

[1LP][RFR] Bump pycurl to version 7.43.0.2

---

cfme/tests/configure/test_default_views_cloud.py
cfme/tests/configure/test_default_views_infra.py

Shriver edited to include infra module:
{{ pytest: cfme/tests/configure/test_default_views_cloud.py cfme/tests/configure/test_default_views_infra.py }}
Changes introduces with this PR:
1. Modify `set_and_test_default_view` by parametrizing it and changing the name to `test_default_views`.
2. Remove `test_cloud_tile_defaultview`, `test_cloud_grid_defaultview` and `test_cloud_list_defaultview` tests.
3. Replace `test_cloud_expanded_view` and `test_cloud_compressed_view` tests with the parametrized `test_cloud_views` test.
4. Replace `test_cloud_exists_mode` and `test_cloud_details_mode` tests with the parametrized `test_cloud_modes` test.
5. Add doc-strings in tests.

[1LP][RFR] Parameterize default and compare views tests for clouds

---

cfme/common/candu_views.py
cfme/infrastructure/datastore.py
cfme/tests/candu/test_datastore_graph.py

- Added Datastore Utilization views
- Added Utilization navigation and wait for data method
- Added test for hourly graph
Note: Daily graph not possible to automate as Datastore not support historical data collection else we have to add automation in sleep for a day at least to collect daily metrics. 
{{pytest: cfme/tests/candu/test_datastore_graph.py -v --use-provider complete}}

[1LP][RFR] Datastore Hourly graph

---

cfme/tests/containers/test_basic_metrics.py

{{ pytest : cfme/tests/containers/test_basic_metrics.py::test_typo_in_metrics_endpoint_type --use-provider ocp-39-hawk }}

[1LP][RFR] Add test for checking for typos in metrics endpoint type

---

cfme/networks/provider/__init__.py

The `Provider.create` method must now expect additional named parameter, `check_exisiting`. With this commit we add the parameter as well as apply it in code.
(If we didn't add it, then `networks_provider` fixture crashes. But it's good to add it event if it wouldn't crash because it brings significant performance improvement as provider now needn't be recreated everytime we run the test)
/cc @mshriver

[1LP][RFR] Follow interface change

---

cfme/physical/provider/redfish.py
cfme/tests/physical_infrastructure/test_redfish_providers.py
conf/cfme_data.yaml.template
conf/credentials.yaml.template
conf/supportability.yaml.template
entry_points.txt
requirements/frozen.py2.txt
requirements/frozen.py3.txt

__Adding tests__ for Redfish Physical Infrastructure Provider.
This commit introduces integration testing for the Redfish type of the [Physical Infrastructure provider](https://github.com/ManageIQ/manageiq-providers-redfish).  In the initial version, we support checking for creating a new provider, checking the number of servers, and updating the provider.
This implementation relies on the corresponding Redfish API implementation of the RedfishSystem wrapanapi class.
There are two commits in this PR, where the first commit updates the label string for adding physical infrastructure provider to the one actually used in the UI.
Depends on: https://github.com/ManageIQ/integration_tests/pull/7629
/cc @gberginc @tadeboro

[1LP][RFR] Add initial support for redfish provider testing

---

cfme/tests/networks/test_provision_to_virtual_network.py
cfme/tests/services/test_different_dialogs_in_catalogs.py

Making some tests clean after themselves.
Verification run: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/173/
{{pytest:  cfme/tests/networks/test_provision_to_virtual_network.py::test_provision_vm_to_virtual_network cfme/tests/services/test_different_dialogs_in_catalogs.py::test_tagdialog_catalog_item --long-running -vv --use-provider rhv42}}

[1LP][RFR] Cleaning up VMs after some more tests

---

conf/env.yaml.template

PR #7672 adds a BZ check to Provider.from_config class method, which is called by get_crud within travis test execution.  This is a valid BZ use, but requires a reachable bugzilla URL

[RFR] Put real bugzilla.redhat.com URL in env template

---

cfme/tests/openstack/cloud/test_instances.py

In the CFME 5.10 during new instance creation cloud_tenant at the environment tab is required
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_create_instance }}

[1LP][RFR] Fixing CFME5.10 new instance creation

---

cfme/containers/provider/__init__.py
cfme/tests/containers/test_provider_configuration_menu.py

{{ pytest : cfme/tests/containers/test_provider_configuration_menu.py::test_pause_and_resume_provider --use-provider ocp-39-hawk }}

[1LP][RFR] Add basic test for pause and resume container provider

---

cfme/tests/integration/test_aws_iam_auth_and_roles.py

@quarckster I'm thinking in the future when we remove deprecated CFME versions from the pickers, we replace with Version.lowest() instead of a specific version - When an older appliance version is run against this, it ends up getting None from the `.pick()` call and fails in odd ways during collection.
In this case if you're running against 5.8, you get a 'wrong' version of the role_dict, but that's more expected as you're running against unsupported version.
Thoughts? Not something I feel too strongly about, but hit it while template_tester was running against an older appliance version, from the master branch.

[1LP][RFR] Use version.lowest instead of 5.9

---

cfme/utils/appliance/__init__.py
scripts/cleanup_old_vms.py
scripts/ocp_cleanup.py

Use in cleanup_old_vms, because we need provider objects but don't have an appliance.

[1LP][RFR] Add context manager for DummyAppliance, for script use

---

cfme/tests/ssui/test_ssui_dashboard.py

This test should not actually be a part of RHV-CFME integration regression suite, therefore removing rhv marker.

[1LP][RFR][NOTEST] Removing test_total_services from RHV suite

---

cfme/fixtures/cli.py

__Fixing__ problem with unbound local `apps` that was caused by timeout in SproutClient.provision_appliances
{{ pytest: -v cfme/tests/cloud_infra_common/test_provisioning.py -k 'test_gce_preemptible_provision --use-provider gce }}

[RFR]Fix unbound local error.

---

cfme/tests/containers/test_pause_resume_workers.py

{{ pytest : cfme/tests/containers/test_pause_resume_workers.py --use-provider ocp-39-hawk }}
Add new test for provider test resume workers.
This is an implementation for Polarion test cases '10790',  '10791'

[1LP][RFR]  Add new test for provider test resume workers

---

cfme/tests/infrastructure/test_host.py
cfme/tests/infrastructure/test_individual_host_creds.py

Wrapping host creds validation tests because of [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1619626).
The problem is that when SSH keys change on hosts, CFME fails to accept the new one. Once the bug is fixed, the next step would be to update the tests so that if an alert informing about new ssh keys shows up, 'OK' button is clicked and new keys accepted.

[1LP][RFR][NOTEST] Add BZ wrapper for test host credentials

---

cfme/networks/cloud_network.py
cfme/networks/views.py
cfme/tests/openstack/cloud/test_networks.py

Were fixed selectors for correct working automation tests not only with CFME 5.8 and CFME 5.9 but with CFME 5.10 too.
Was updated returning object of parent cloud provider regarding version of the CFME
{{ pytest: cfme/tests/openstack/cloud/test_networks.py -k 'test_create_network or test_create_subnet or test_create_router_with_gateway or test_clear_router_gateway or test_add_gateway_to_router' }}

[1LP][RFR] Fixing clod tests for supporting the CFME 5.10 automation

---

cfme/tests/infrastructure/test_provisioning_dialog.py
requirements/frozen.py2.txt
requirements/frozen_docs.py2.txt

Extending test_provision_dialog to include test cases that provision VM with vnic profiles 'No Profile' and 'Use template nics'. 
For RFE page refer to https://bugzilla.redhat.com/show_bug.cgi?id=1449157, comment #4.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py::test_provisioning_vnic_profiles --long-running}}

[1LP][RFR] Cover provision cases with vlan profiles <No Profile> and <Use template nics>

---

cfme/physical/provider/__init__.py

In version 5.10, the Details view for a physical infrastructure now has a choice between a Dashboard View, which is new, and a Summary View, which has been refreshed but it contains elements of the previous Details view. By default, the Dashboard View is opened, so we added a step to select the Summary View before doing the stats check.

[1LP][RFR] Add switching to Summary view for physical infrastructure provider

---

cfme/tests/cloud/test_cloud_timelines.py

When azure or ec2 instance is created, it is already created up and running.
So, there is no "start" event. This test can be fixed either by adding instance stop and start or making it check for "create" event instead.
{{pytest: --long-running --use-provider=azure cfme/tests/cloud/test_cloud_timelines.py::test_cloud_timeline_diagnostic }}

[1LP][RFR] fix cloud_timelines->diagnostic view test

---

cfme/infrastructure/provider/kubevirt.py

This was causing non-Kube providers to get the wrong class.
Before, with rhevm and vmware provider configured:
```
In [12]: coll = app.collections.infra_providers
In [13]: coll.all()
Out[13]: 
[RHEVMProvider(endpoints={}, name=u'rhv42', key=None, zone=None, start_ip=None, end_ip=None, provider_data=None),
KubeVirtProvider(endpoints={}, name=u'vSphere 6.5 (nested)', key=None, zone=None, start_ip=None, end_ip=None, provider_data=None, parent_provider=None)]
```
After, with kubevirt and vmware providers configured:
```
In[4]: app.collections.infra_providers.all()
Out[4]: 
[KubeVirtProvider(endpoints={}, name=u'openshift-kubevirt Virtualization Manager', key=None, zone=None, start_ip=None, end_ip=None, provider_data=None, parent_provider=None),
VMwareProvider(endpoints={}, name=u'vSphere 6.5 …
```

[1LP][RFR] Update KubeVirt provider class db_types

---

cfme/tests/services/test_service_catalogs.py

__Removing__ test_edit_catalog_after_deleting_provider
Editing/removing catalog items after Provider has been removed from CFME
was decided not to be supported.
We should consider removing test_edit_catalog_after_deleting_provider from our test suite.

[1LP][RFR][NOTEST] Remove test_edit_catalog_after_deleting_provider from our test suite

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

The test case fails when the number of VMs is greater than 999. Take for example the number of VMs is 1248. The data received by reading rows is `1,248`. Converting `1,248` to integer fails, since `int()` fails to convert a string with ',' in between. This change removes the ',', which allows successful string conversion.
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py -k test_datastores_summary }}

[1LP][RFR] Fix test_datastores_summary test on 5.8

---

cfme/tests/containers/test_ad_hoc_metrics.py
cfme/tests/containers/test_basic_metrics.py
cfme/tests/containers/test_breadcrumbs.py
cfme/tests/containers/test_cockpit.py
cfme/tests/containers/test_configurable_menus.py
cfme/tests/containers/test_containers_smartstate_analysis.py
cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
cfme/tests/containers/test_containers_summary.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_logging.py
cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
cfme/tests/containers/test_node.py
cfme/tests/containers/test_overview_data_integrity.py
cfme/tests/containers/test_projects_dashboard.py
cfme/tests/containers/test_properties.py
cfme/tests/containers/test_provider_configuration_menu.py
cfme/tests/containers/test_provider_openscap_policy_attached.py
cfme/tests/containers/test_relationships.py
cfme/tests/containers/test_reload_button_provider.py
cfme/tests/containers/test_reports.py
cfme/tests/containers/test_search_bar.py
cfme/tests/containers/test_smart_management.py
cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
cfme/tests/containers/test_ssl_providers.py
cfme/tests/containers/test_start_page.py
cfme/tests/containers/test_static_custom_attributes.py
cfme/tests/containers/test_table_views.py
cfme/tests/containers/test_tables_fields.py
cfme/tests/containers/test_tables_sort.py
cfme/tests/containers/test_tags.py

Combining cmqe and cfme polarion projects, the CMP IDs are no longer needed.

[RFR] Remove Polarion IDs from CMQE Tests

---

cfme/tests/automate/custom_button/test_cloud_objects.py

- basic display test for cloud-related custom button objects.
- added support for a provider with navigations
- provider
- network provider
- To add support of other provider need to add all method for objects :)
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py -v --use-provider complete}}

[1LP][RFR] custom button: cloud objects initial commit

---

cfme/tests/infrastructure/test_advanced_search_host.py

{{ pytest: cfme/tests/infrastructure/test_advanced_search_host.py::test_quick_search_without_host_filter cfme/tests/infrastructure/test_advanced_search_host.py::test_quick_search_with_host_filter }}

[1LP][RFR] Fixed all() method error in host advanced search

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_publish_vm_to_template.py

Added test case for publishing vm to template in RHEVM provider.
Updated infraVm publish_to_a_tamplate method to fit RHEVM needs - on RHEVM it is not possible to configure host for a template. 
{{pytest: cfme/tests/infrastructure/test_publish_vm_to_template.py::test_publish_vm_to_template --long-running --use-provider rhv41 -vv}}

[1LP][RFR] Ading test publish_vm_to_template for RHV.

---

docs/guides/documenting.rst

The old link doesn't work anymore.

[1LP][RFR] Fix the link to Google Python Style Guide

---

cfme/common/vm_views.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

The name of file that is used to get VM state is different in 5.8. I am not using `VersionPicker` because this fix is specific for 5.8-breakpoint-patched branch.
Jenkins verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.8-rhv-4.2-integration-flow-dev/92/

[1LP][RFR] Fixing getting VM state for 5.8

---

cfme/fixtures/cli.py
cfme/scripting/sprout.py
cfme/test_framework/sprout/client.py
cfme/test_framework/sprout/plugin.py
sprout/appliances/views.py

Remove default credentials lookup for sprout client, using only env vars or a passed creds key
This prevents groups with a credentials file that contains a 'sprout' key from defaulting to that user for anyone using the credentials file.
This was causing regular users to make sprout requests as a CI user instead of themselves.
Testing:
All changes tested locally, CI configuration changes ready, for passing `--sprout-user-key` to `miq-runtest`

[1LP][RFR] Change sprout client default auth behavior

---

cfme/infrastructure/virtual_machines.py
cfme/services/myservice/ssui.py
cfme/services/service_catalogs/ui.py

There are some minor differences between messages in UI in 5.8. This should take care of that. Also, at some point in SSUI, there is a notification that obscures upper right menu. I added **super-lazy workaround** using `time.sleep(15)`. I know it is ugly, but hey, it's almost deprecated branch and there's IMO no value in fixing it properly.
Jenkins verification: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.8-rhv-4.2-integration-flow-dev/95/

[1LP][RFR] Adding some fixes for UI problems in 5.8

---

cfme/common/vm_views.py

{{ pytest: -v cfme/tests/cloud_infra_common/ --use-provider complete }}
This commit undo some changes in #7502 as 'quadicon' property is accessible again.
The removed lines didn't work if page is opened in List view and it is opened in this view by default for Images, so the test test_tag_cloud_objects was broken.

[1LP][RFR] fix for quadicon

---

cfme/test_framework/sprout/plugin.py

Bad tuple unpacking was setting pool attribute to tuple of IPAppliance.from_json call and the pool ID.

[1LP]Update SproutManager.pool setting

---

cfme/configure/access_control/__init__.py
cfme/tests/configure/test_access_control.py

Modified following files;
-  cfme/configure/access_control/__init__.py
- Updated delete() method
-  cfme/tests/configure/test_access_control.py
{{ pytest: cfme/tests/configure/test_access_control.py::test_delete_default_tenant }}

[1LP][RFR] Fixed exception error while deleting default tenant in 5.8.5.0

---

cfme/tests/infrastructure/test_advanced_search_host.py

{{ pytest: cfme/tests/infrastructure/test_advanced_search_host.py::test_quick_search_without_host_filter cfme/tests/infrastructure/test_advanced_search_host.py::test_quick_search_with_host_filter }}

[1LP][RFR] Fixed TypeError in advanced search for 5.8.5.0

---

cfme/utils/dockerbot/pytestbase/setup.sh

[RFR] dockerbot: use the correct user-key cli argument for sprout checkout

---

cfme/common/vm_views.py

quadicon was removed replaced wit quad in 5.10. So, this code should definitely be restored.
{{ pytest: -v cfme/tests/cloud_infra_common/ --use-provider complete }}

[WIPTEST] restoring parsing quad removed by PR #7758

---

cfme/common/provider_views.py

This PR fixes issues with `ContainerProviderEditViewUpdated`. The `update` method for a container provider fails when the values for widgets inside the `COND_WIDGETS` are not passed inside the `values` dictionary. This code change fixes those issues.

[WIPTEST][NOTEST] Modify ContainerProviderEditViewUpdated view

---

cfme/tests/cloud/test_quota_tagging.py

Fixed exception error while returning VM with openstack provider in **5.8.5.0**
{{ pytest: cfme/tests/cloud/test_quota_tagging.py -k test_quota_tagging_cloud_via_lifecycle --use-provider complete }}

[RFR] Fixed exception error for openstack provider in 5.8.5.0

---

cfme/fixtures/cli.py

I broke this in #7756 with only passing pytestconfig in the first fixture using temp_appliance method.

[RFR] Fix fixtures for sprout appliances, pass pytestconfig

---

cfme/test_framework/sprout/client.py

If bool(user_key) resolved to false, None was used as user/password. The
environment variable was never effective.

[RFR] Fix getting sprout auth.

---

cfme/fixtures/provider.py

{{ pytest: cfme/tests/cloud_infra_common/test_power_control_rest.py --use-provider kubevirt }}

[WIPTEST] Catch KeyError in _get_template()

---

cfme/tests/automate/test_common_methods.py
cfme/tests/cloud_infra_common/test_retirement.py

1) Why am I modifying `verify_retirement_state`?
Because in CFME 5.10, you are redirected to a view with Requests when you do Lifecycle -> Retire VM.
I did not use `VersionPicker` since call to `navigate_to(retire_vm, 'Details')` does not cause any problem in 5.9 - we're already there.
2) Why am I wrapping so many tests with [BZ1627758](https://bugzilla.redhat.com/show_bug.cgi?id=1627758)?
Recently there was a change in datepicker. Its timezone is now determined by local time zone of your browser. However, the success flash message is always displayed in UTC. Therefore we cannot really verify now that the flash message displayed after setting retirement date is correct. 
Example: I am running this test case in my time zone (CEST) and set retirement date to 12th of September 23:00. The …

[WIPTEST] Adding BZ1627758 and fixing test_retirement_now

---

cfme/tests/configure/test_register_appliance.py

This was not recognizing reg_method argname, changing the parametrize call and scope resolves this, while maintaining the same parametrization result.
{{ pytest: --long-running cfme/tests/configure/test_register_appliance.py -k test_rh_registration }}

[1LP][RFR] Fix test generation in test_register_appliance

---

cfme/common/vm.py
cfme/tests/cloud_infra_common/test_retirement.py

Main point of this PR is the fact that field 'Retirement state' in VM details view has been changed to 'Retirement State' in 5.10. However, once I fixed that I also encountered a product [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1626971), that is influencing all tests that invoke [set_retirement_date](https://github.com/ManageIQ/integration_tests/blob/401acc6d20e8860710799ae95bd57eb6eeb5ada9/cfme/common/vm.py#L764) method. Therefore providing a BZ wrapper.
Jenkins: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CFME-DEV/job/cfme-5.9-rhv-4.2-integration-flow-dev/332/console

[1LP][RFR] Fixing getting retirement state

---

cfme/containers/provider/__init__.py

{{ pytest: cfme/tests/containers/test_node.py --use-provider ocp-36-hawk }}

[RFR] Fix Adding Container Provider for 5.8 Breakpoint

---

cfme/services/catalogs/catalog_items/__init__.py

{{pytest: cfme/tests/services/test_myservice.py -v --use-provider vsphere55}}
In 5.10 catalog name is displayed with My Company/catalog_name.
It affects some tests but tests cannot be run since 5.10 tests are failing because of issue 
https://bugzilla.redhat.com/show_bug.cgi?id=1626232.
Blocking tests with this BZ in another upcoming PR

[1LP][RFR]Catalog name appended by My_Company in 5.10

---

cfme/configure/access_control/__init__.py

fixed the cause of error for tests on 5.8.5:
NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator=u'.//div[contains(@class, "bootstrap-select")]/button[normalize-space(@data-id)="use_filter_expression"]/..')

[RFR]  fixed NoSuchElementException use_filter_expression

---

cfme/utils/dockerbot/pytestbase/get_keys.py

The fedoraproject keyserver seems to always answer even repetetive
queries contrary to whatever is in the servers pool which is used by default.

[1LP][RFR] Use specific keyserver.

---

cfme/infrastructure/datastore.py
cfme/tests/automate/custom_button/test_infra_objects.py

- add `all` method for datastore with `REST`
- removed `get_all_datastores`; this method unused
- added support for `datastore` object in `custom button` display test. 
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py -v --use-provider complete}}

[1LP][RFR] Custom Button: Datastore support and all method for it.

---

cfme/tests/automate/custom_button/test_cloud_objects.py

- Removed To-Do
- added support for storage mangers in cloud objects navigation :+1: 
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py -v --use-provider complete}}

[1LP][RFR] custom button: support for storage managers

---

cfme/tests/openstack/infrastructure/test_provider.py

Fixing test test_credentials_quads for the CFME 5.10
{{ pytest: cfme/tests/openstack/infrastructure/test_provider.py::test_credentials_quads }}

[1LP][RFR] Fixing test test_credentials_quads for the CFME 5.10

---

cfme/tests/intelligence/reports/test_canned_corresponds.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

Changes introduced with this PR:
1. The name of`list_host` and `list_cluster` methods differ for `SCVMMProvider`. They're `list_hosts` and `list_clusters`. This PR fixes the test `test_cluster_relationships` by adding a fix for the issue. 
2. `test_cluster_relationships` test was also failing due to some issue with wrapanapi. A patch was merged into `wrapanapi` to solve this issue. The latest version was released yesterday, hence updating `wrapanapi` in requirements.
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_cluster_relationships --use-provider=complete  -sqvvv}}

[1LP][RFR] Fix test_cluster_relationships test and update wrapanapi requirements for 5.8

---

cfme/fixtures/artifactor_plugin.py

Artifactor gets triggered by `fire_art_hook` to handle events after they happen, Artifactor then tells plugin that certain event has occurred and the plugin then reacts accordingly, while `fire_art_hook` does not expect any response. So in other words we tell plugin to do something and then we expect nothing to be returned. But in some cases plugin does return some value, which we expect immediately. With this commit `fire_art_hook` and `fire_art_test_hook` now return value that they get from plugins.
For example we can look at Merkyl plugin that checks log content, which was logged after test started. Merkyl has `merkyl_inspector` fixture that has `get_log` method. This method uses `fire_art_test_hook` to tell plugin to get log content, plugin does return that content but then it gets …

[1LP][RFR] Allow plugins to return value

---

cfme/tests/intelligence/reports/test_canned_corresponds.py

Changes introduced with this PR:
1. The name of `list_host` and `list_cluster` methods differ for `SCVMMProvider`. They're `list_hosts` and `list_clusters`. This PR fixes the test `test_cluster_relationships` by adding a fix for the issue.
{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_cluster_relationships --use-provider=complete -sqvvv}}
Note: Same changes have been added for 5.8. Reference #7823

[1LP][RFR]Fix test_cluster_relationships

---

cfme/tests/configure/test_zones.py

{{ pytest: -v cfme/tests/configure/test_zones.py::test_zone_add_blank_description }}

[1LP][RFR] changed error message to match for blank description

---

cfme/utils/release.py

May make further changes to format the `brief` option as a markdown table, instead of just pipe separated.  Will have to stop it from splitting rows though, since markdown doesn't parse that.

[1LP][RFR] Update valid labels for release script

---

cfme/tests/configure/test_log_depot_operation.py

1. automated test_log_collect_ansible_logs (check that downloaded logs contain ansible logs)
2. removed old blocker
3. added new blocker for new BZ

[1LP][RFR] added check for ansible logs

---

cfme/cloud/availability_zone.py
cfme/tests/automate/custom_button/test_cloud_objects.py

- Added all  method for Azone with REST
- Added support of Azone to custum button  file
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py -v --use-provider complete}}

[1LP][RFR] Custom Button: Azone support and all method

---

cfme/fixtures/authentication.py

causes semaphore exhaustion for following tests

[RFR] Remove http restart in auth fixture

---

cfme/fixtures/artifactor_plugin.py

So a major bug has been present in the shutdown system for a looooooong time and many people have tried to fix it, myself included. Today, whilst working on integrating artifactor into iqe, I found something interesting. The result of this is here.

[1LP][RFR] Fixes the double artifactor shutdown

---

cfme/fixtures/appliance.py
cfme/fixtures/cli.py
cfme/tests/pod/test_appliance_crud.py

backported https://github.com/ManageIQ/integration_tests/commit/f56606c5fae257ecd84b0bca37a530fddddb6dd0 to 5.8
fixtures/cli and fixtures/appliance had pretty much exactly the same contextmanager for checking out sprout appliances.
establish single contextmanager in cfme/fixtures/appliance, import and use it in cfme/fixtures/cli
Update direct use of the contextmanager in tests/pod/test_appliance_crud

[RFR] consolidate sprout_appliance contextmanager and fixtures

---

cfme/common/vm_views.py
cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
cfme/utils/net.py

I believe the test case (and its docstring) are pretty self-explanatory. What is maybe not so clear are changes in cfme/common/vm_views.py. They are two:
- I added RadioGroup for Address Mode
- I rearranged the button definitions so they are in the same order as in UI. This can be significant because some of the "later" fields are dependent on Customize Type.
Also, what might not be very clear is that why I am not specifying Customization Template. The reason is that there is already one pre-defined (`oVirt cloud-init`) that perfectly suits this purpose.
Also, why am I using pure `paramiko` as opposed to `cfme.utils.ssh`? The reason is that I need to SSH to the provisioned VM using IPv6 and I just could not get it to work with `SSHClient` from `cfme.utils.ssh`.
Jenkins verification: …

[1LP][RFR] Adding test_provision_cloud_init_payload for RHEVM

---

artifactor/plugins/merkyl.py
cfme/fixtures/merkyl.py

With this commit we implement method that resets log for merkyl plugin. Now we can clear content of a log and continue tailing it.
This is needed when a log is tailed for a duration of the whole session and there are multiple tests being ran. For example two test can search for the same log entry. If first one succeeds and we don't clear the log content after, second one will just find the log content of the first test and succeed.

[1LP][RFR] Support reset log for merkyl plugin

---

cfme/exceptions.py
cfme/tests/networks/nuage/test_events_are_triggered.py

With this commit we create fixture that tails 'evm.log' to see whether targeted refresh was triggered. We then use it to test targeted refresh for Nuage.
Fixture first starts tailing the log and waits for events to occur. Then it searches the 'evm.log' for a line that looks something like this:
```
Collection of targets with id: [{:ems_ref=>"b35d3afe-6f19-4da8-b1ee-b79de433cace"}, ... ]
```
If any of the log entry is not found `NeedleNotFoundInLog` error is raised and failed entities are listed.
NOTE: The fixture actually checks whether targeted refresh was _started_ i.e. whether Automate Instances are properly configured. It does not check the result of refreshing
Depends on:  https://github.com/ManageIQ/integration_tests/pull/7797, …

[1LP][RFR] Test targeted refresh for Nuage entities

---

cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/tests/containers/test_pause_resume_workers.py

Add new test to verify a OpenShift provider can be paused and resumed via the API
{{ pytest: cfme/tests/containers/test_pause_resume_workers.py --use-provider ocp-39-hawk }}

[1LP][RFR] Add/Resume OCP Provider API Test

---

cfme/tests/intelligence/reports/test_report_corresponds.py

So, why remove this from RHV-CFME regression suite?
1) This does not really test any RHV specific functionality. The main point of this test case is that custom report can be successfully created and therefore I don't see much reason to keep it in specific RHV-CFME integration suite.
2) This test case works quite problematically in you environment because:
2.1) The fixture `report_vms` [requires](https://github.com/ManageIQ/integration_tests/blob/23c846c40c23eef0d1f5b1c1619f026abb2665c7/cfme/tests/intelligence/reports/test_report_corresponds.py#L32) that there are **at least two VMs present on a provider**. Recently, I created some PRs that make sure that our tests clean after themselves. And since we have much cleaner env now, this test case started to fail. There just aren't two random …

[1LP][RFR][NOTEST] Removing test_custom_vm_report from RHV regression suite

---

cfme/configure/access_control/__init__.py
cfme/tests/configure/test_access_control.py

Following error occured:
```
Failed: DID NOT RAISE <type 'exceptions.Exception'>
```
Shriver: expanding PRT coverage since delete method was modified.
{{ pytest: cfme/tests/configure/test_access_control.py -k 'test_delete_default_tenant or test_superadmin_tenant_crud' -vv }}

[1LP][RFR] Fixed Exception Error while deleting default tenant

---

cfme/tests/configure/test_access_control.py

{{ pytest: -v cfme/tests/configure/test_access_control.py::test_group_crud_with_tag --use-provider complete }}

[1LP][RFR] fixed test_group_crud_with_tag for vsphere55

---

cfme/base/ui.py
cfme/utils/__init__.py

View objects don't have a `obj` attribute, they store the related entity/collection in `context['object']`
When testing fix, I found that the tries() method is hitting UnboundLocalError, fixed by setting a default exception.

[1LP][RFR] Update RegionView and tries() method

---

cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_rest.py

There are two points to this PR:
1) Subjects of confirmation e-mails have changed in CFME 5.10
2) There is a bug with those subjects. However, it does not meria a full skip of the test, so I provided a workaround.
5.9: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/206/console
5.10: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.10-rhv-4.2-integration-test-dev/22/console

[RFR] New subject of provision e-mails in CFME 5.10

---

cfme/tests/configure/test_access_control.py

tested locally for 5.8
PR fixes error CandidateNotFound: path: ('Datacenter', 'Discovered virtual machine'), message: Could not find the item vSphere 5.5 (nested)/Datacenter/Discovered virtual machine in Boostrap tree vat_treebox, cause: Was not found in Datacenter

[RFR] fixed failed test_group_crud_with_tag[tag-virtualcenter] for vsphere55 for 5.8

---

cfme/infrastructure/virtual_machines.py

In 5.9 there is a title 'rhv_cfme_integration (All VM Templates)', in 5.10 this is now changed to
'rhv_cfme_integration (All VM Templates and Images)'.
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_infra_provider_relationships --use-provider rhv41 }}

[RFR] Fix Provider relationships templates view for 5.10

---

cfme/tests/candu/test_cluster_graph.py

Fixed ItemNotFound: Entity {'name': 'Cluster'} isn't found on this page for 5.8.
In UI 5.9 the clusters's name is Cluster
But in 5.8 it is displayed as Cluster in Datacenter (for VMware)
Tested locally

[RFR] modified the name of cluster for 5.8

---

cfme/tests/configure/test_log_depot_operation.py

1. Removed the BZ1603163 blocker. The issue described there is not the issue in the product. It was fixed by editing configs earlier. Also removed it for master, see #7805
2. Added uncollection for anonymous ftp log collection for versions below 5.9, see BZ1341502 (it was fixed in version 5.9).

[RFR] uncollect anon_ftp for 5.8 and below

---

cfme/infrastructure/host.py
cfme/tests/cloud_infra_common/test_relationships.py

The fixture was getting a provider filtered collection, then applying an unrelated search filter in the UI.
This would filter without taking the provider into account, and doesn't impact what is returned by the fixture at all.
Use a provider to get HostCollection instance with a parent set
Modify the HostCollection.all() method to use provider filter in addition to parent filter
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py }}

[1lLP][RFR] Fix host fixture for test_relationships, Navigation

---

cfme/cloud/provider/__init__.py
cfme/infrastructure/provider/__init__.py
cfme/tests/cloud_infra_common/test_relationships.py

Infra details view had this default, cloud should as well.
resetter will select summary view by default on provider pages. use_resetter=false, or explicit dashboard view selection where needed.

[1LP][RFR] Add summary view selection to cloud details nav resetter

---

cfme/tests/cloud_infra_common/test_tag_visibility.py

Since PRT do not run on 58z, posting local results ran on CFME 5.8.5.1:
```
Appliance's streams: [5.8, downstream]
========================================================================================================================= test session starts ==========================================================================================================================
platform linux2 -- Python 2.7.5, pytest-3.4.1, py-1.5.3, pluggy-0.6.0 -- /home/anikifor/cfme/bin/python
cachedir: .pytest_cache
rootdir: /home/anikifor/projects/integration_tests, inifile:
plugins: wait-for-1.0.9, pycharm-0.5.0, manageiq-integration-tests-17.34.1.dev50+ge66806a
collected 4 items …
```

[1LP][RFR] delete vm after the test

---

cfme/tests/infrastructure/test_advanced_search_host.py

fixed:
- Error:
```
>       assert len(more_than_median_hosts) == len(host_collection.all(infra_provider))
E       TypeError: all() takes exactly 1 argument (2 given)
cfme/tests/infrastructure/test_advanced_search_host.py:140: TypeError
TypeError
all() takes exactly 1 argument (2 given)
```
{{ pytest: cfme/tests/infrastructure/test_advanced_search_host.py::test_host_filter_save_and_load }}

[1LP][RFR] Fixed type error in advance search for 5.10

---

cfme/tests/cloud_infra_common/test_tag_objects.py

These tests are skipped anyway, so to avoid N/A in the reports I uncollected them.
Appliance version doesn't matter now as the branch is for 5.8 only.

[1LP][RFR] uncollect tests for keypair visibility in 5.8

---

cfme/test_framework/sprout/client.py
cfme/test_framework/sprout/plugin.py

default sprout client request time has been decreased to 15 min what isn't enough for provisioning appliance pool from scratch

[1LP][RFR] custom sprout request time

---

cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py

- We  are getting error like this
```
def get_crud_by_name(provider_name):
""" Creates a Provider object given a management_system name in cfme_data.
Usage:
get_crud_by_name('My RHEV 3.6 Provider')
Returns: A Provider object that has methods that operate on CFME
"""
for provider_key, provider_data in providers_data.items():
if provider_data.get("name") == provider_name:
return get_crud(provider_key)
>       raise NameError("Could not find provider {}".format(provider_name))
E       NameError: Could not find provider Embedded Ansible Automation Manager
```
- we have seperate out all manager those are `child provider` not `main provider`
Note: Test not adding as will not reproduce with fresh appliance... need a proper run or cloud provider with infra …

[1LP][RFR][NOTEST] Need to separate out Managers  from provider

---

cfme/networks/cloud_network.py
cfme/tests/automate/custom_button/test_cloud_objects.py

- Added support for provider object in all method with REST
- Added support of  cloud network for custom button. 
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py -v --use-provider complete}}

[1LP][RFR] Custom Button: Support for Cloud networks and All method

---

cfme/tests/configure/test_access_control.py

This is a quick fix for existing test.
Changing only the Exception text and adding a comment about what's happening.
{{ pytest: -v --long-running cfme/tests/configure/test_access_control.py -k test_rolename_required_error_validation --use-provider vsphere67-nested }}

[1LP][RFR] Fix test_rolename_required_error_validation

---

cfme/utils/template/base.py
cfme/utils/template/rhevm.py

The ovirt templates were not being uploaded to the Sprout providers.
I have made changes to cfme/utils/template/rhevm.py so that the regular expression matches both ovirt and rhevm.
Ovirt template files  are named like this 
manageiq-ovirt-master-201809272000-96d0b65c0f.qc2
RHV template files are named like this:
cfme-rhevm-5.10.0.17-1.x86_64.qcow2
I have also tested the PR locally .

[RFR] Fix ovirt template upload failure

---

cfme/tests/cloud/test_providers.py

__Adding tests__ for password requirements to cover case RHCF3-14524
Shriver: Editing pytest line, azure isn't default provider, needs to be collected against.
{{ pytest: -v cfme/tests/cloud/test_providers.py::test_azure_instance_password_requirements --use-provider azure }}

[1LP][RFR] Add password requirements test.

---

cfme/tests/candu/test_gap_collection.py
cfme/tests/candu/test_host_graph.py
cfme/tests/infrastructure/test_host_drift_analysis.py
cfme/tests/infrastructure/test_individual_host_creds.py
cfme/tests/v2v/test_csv_import.py
cfme/tests/v2v/test_v2v_migrations_ui.py

1. uncollected host tests because host view summary page is broken
2. removed wait_for_view=True because it is always enabled now

[RFR] uncollect host tests against 5.10

---

cfme/cloud/provider/__init__.py
cfme/common/provider_views.py
cfme/containers/overview.py
cfme/tests/containers/test_containers_summary.py
cfme/tests/containers/test_overview_data_integrity.py
widgetastic_manageiq/__init__.py

Parametrize StatusBox widget, use it in ProviderDashboard view so we don't have 10 of the same widgets with different names
These two tests are basically the same, but I don't want this PR scope to involve reducing them to a single parametrized test.
I'm seeing a mismatch on container count, CMQE team is aware, leaving a TODO for now, but adding the parameter back into the test.
`E           There is a mismatch between API and UI values: Container: 25 (API) != 30 (UI) (cfme/tests/containers/test_overview_data_integrity.py:72)`
{{ pytest: --use-provider ocp-39-hawk --long-running cfme/tests/containers/test_overview_data_integrity.py cfme/tests/containers/test_containers_summary.py }}

[RFR] Provider dashboard view with parametrized cards

---

cfme/configure/settings.py
cfme/tests/configure/test_default_filters.py

This PR adds a test case, which checks if resetting a change on Default Filters page works. It also adds a Reset Button to `DefaultFiltersForm`.
{{pytest: cfme/tests/configure/test_default_filters.py::test_default_filters_reset --use-template-cache -sqvvv}}

[1LP][RFR]Automate test: Resetting changes on Default Filters page

---

cfme/common/vm.py

{{pytest: cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py cfme/tests/intelligence/reports/test_validate_chargeback_report.py cfme/tests/intelligence/reports/test_metering_report.py}}

[RFR]Fixing navigation to SetOwnershipView which doesn't have is_displayed

---

cfme/infrastructure/provider/__init__.py

{{pytest: cfme/tests/infrastructure/test_timelines.py --use-provider=vsphere6-nested}}

[1LP][RFR]ProviderClusters.is_displayed had a typo and always returned False

---

cfme/tests/containers/test_static_custom_attributes.py

Fix custom cttribute test case to match the implantation of the GUI. 
{{ pytest: cfme/tests/containers/test_static_custom_attributes.py --use-provider ocp-36-hawk }}

[1LP][RFR] Fix CMQE Custom Attribute Test Case

---

cfme/fixtures/networks.py
cfme/fixtures/nuage.py
cfme/test_framework/pytest_plugin.py
cfme/tests/networks/nuage/test_events_are_triggered.py

With this commit we move two of Nuage fixtures to fixtures folder and register them. They are now available in global fixture list and can be used by multiple tests.
`with_nuage_sandbox` is very useful fixture that we want to use in multiple tests. It creates Nuage enterprise and its entities, and returns its values, which can then be compared to ui and database values. We moved it to `cfme/fixtures/nuage.py`, since its Nuage specific and will only be used by Nuage tests.
`targeted_refresh` fixture checks logs, if targeted refresh was started for specific targets. It can be used by other providers as well, so it was moved to `cfme/fixtures/networks.py`.

[1LP][RFR] Move Nuage fixtures

---

cfme/common/__init__.py
cfme/configure/tasks.py
cfme/containers/image.py
cfme/tests/containers/test_containers_smartstate_analysis.py

Add new test to verify a OpenShift image can perform SmartState Anaylsis scan via the API
{{ pytest: cfme/tests/containers/test_containers_smartstate_analysis.py --use-provider ocp-39-hawk }}

[1LP][RFR] Adding New Smart State Analysis Test 

---

cfme/base/__init__.py

We're seeing a large number of automation failures from the second call to `server.name` here, but I can't yet replicate the failure locally.
At least wanted to start with  adding the list for forced_streams arg

[RFR] Fix BZ instantiation for server.get_master

---

cfme/services/service_catalogs/ui.py
cfme/tests/services/test_service_catalogs.py

Flash message that is displayed after ordering Service Catalog is `success` in 5.9 and `info` in 5.10, therefore applying `VersionPicker`. 
PRT does not really seem to be working, therefore providing verification from Jenkins.
{{pytest: cfme/tests/services/test_service_catalogs.py::test_order_catalog_item --long-running -vv}}
Jenkins: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/209/console

[RFR] Flash message after ordering catalog is success now

---

cfme/tests/automate/custom_button/test_infra_objects.py

-  Fix paginator error
- Fix all destination custom button not desplay with filter means if you go with relationship table.
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_automate -v}}

[1LP][WIPTEST] Fix- custom button infra object paginator selection problem

---

cfme/common/__init__.py

Raise common exception when nav to Details fails for a Taggable entity
Right now we're hitting a `TimedOutError` on Taggable entities that are returning `False` for `is_displayed` on their `Details` view, I think its more fit to raise an ItemNotFound error here consistently. Happens to handle case where Taggable class doesn't have details nav defined either.

[1LP][RFR] Update Taggable.add_tag nav error handling

---

cfme/services/catalogs/catalog_items/__init__.py

Create call was failing because am_i_here is implemented and returns False.

[RFR] Update call to CatalogItem 'Add' dest, wait_for_view

---

cfme/cloud/instance/openstack.py
cfme/common/vm_views.py
cfme/infrastructure/config_management.py
cfme/infrastructure/datastore.py
cfme/infrastructure/virtual_machines.py

There were some other views returning False which didn't match pattern. 
Those should also raise NotImplementedError until those are correctly defined.
This is part of resolving #7960

[1LP][RFR] fixed more is_displayed methods which I missed before

---

cfme/containers/build.py

```
In[2]: ocp = providers.get_crud('ocp-36-hawk')
In[3]: coll = appliance.collections.container_builds
In[4]: view = navigate_to(coll, 'All')
In[5]: view.is_displayed
Out[5]: True
In[6]: navigate_to(ocp, 'All')
Out[6]: <cfme.common.provider_views.ContainerProvidersView at 0x7f56d3b04450>
In[7]: view.is_displayed
Out[7]: False
```

[1LP][RFR] CMQE Fix is_displayed for Container Builds

---

cfme/configure/configuration/diagnostics_settings.py

{{ pytest: cfme/tests/containers/test_pause_resume_workers.py --use-provider ocp-36-hawk }}

[RFR] Fix is_displayed() for DiagnosticServerWorkersView

---

cfme/tests/cloud_infra_common/test_retirement.py

Retired VMs now have "retired" in the Power Management field.
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py::test_retirement_now -vv --use-provider rhv42}}
PRT failed because of ec2, which cannot be set up.

[1LP][RFR] Fixing retirement state for 5.10

---

cfme/tests/configure/test_access_control.py

This is a quick fix for a expected error message in two tests:
- test_unique_project_name_on_parent_level
- test_unique_tenant_name_on_parent_level
I suppose I could have used versionpick. My chosen approach is quicker and easier though.
{{ pytest: -v cfme/tests/configure/test_access_control.py -k test_unique_tenant_name_on_parent_level }}

[RFR] Fix message in unique name tests

---

cfme/services/catalogs/__init__.py
cfme/services/service_catalogs/ui.py

Fix service view is_displayed
Part of resolving https://github.com/ManageIQ/integration_tests/issues/7960
{{pytest: cfme/tests/services/test_service_catalogs.py --use-provider vsphere55 --long-running}}

[RFR]Fix view is_displayed for services

---

cfme/control/explorer/conditions.py
cfme/control/explorer/policies.py
cfme/control/explorer/policy_profiles.py
cfme/tests/control/test_actions.py

is_displayed raises exception because PolicyCollection has no `PRETTY` attribute.
Added `PRETTY=None` and updated `is_displayed` because the collection page doesn't have a unique title.
{{ pytest: cfme/tests/control/test_actions.py -k test_action_start_virtual_machine_after_stopping --long-running }}

[1LP][RFR] Fix PolicyCollection.PRETTY and PoliciesAllView.is_displayed

---

cfme/infrastructure/config_management.py

failing is_displayed, nav steps in resetter
Split view classes for configmanager and systemmanager
nav + is_displayed for both `ConfigManager` and `ConfigSystem` tested locally
This may need some more work for all Config views to work properly with ansible an non-ansible providers, since the core page is different in the two cases. We may need to consider splitting the classes/views so that the views for Ansible are separate classes and is_displayed doesn't have to pick between the two throughout the nav tree.
{{ pytest: cfme/tests/infrastructure/test_config_management.py --long-running }}

[1LP][WIPTEST] Update ConfigManager/SystemManager views/nav

---

cfme/cloud/instance/__init__.py

Fix is_displayed method for InstanceDetailsView
Part of resolving #7960
{{pytest: cfme/tests/candu/test_vm_graph.py}}

[WIPTEST] Fix is_displayed method for InstanceDetailsView

---

cfme/services/myservice/ui.py

1) View is_displayed fix - Part of resolving #7960
2) corrected Text displayed for set ownership for both 5.9 and 5.10
{{pytest: cfme/tests/services/test_myservice.py --use-provider vsphere55 --long-running}}

[RFR]Myservice view fix

---

cfme/base/ui.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

In our RHV integration testing environment we don't have CFME appliance imported in the provider, but is running in a different data center and our RHV GEs (providers) are also elsewhere, meaning hosts of our GEs are attached to a different storage domain than the host running the CFME appliance.
In such situation it seems that smart proxy affinity needs to be enabled for SSA to work.
Adding fixture that enables smartproxy affinity specifically for our 'rhv_cfme_integration' provider 
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py --long-running -vv --use-provider rhv42}}

[1LP][RFR] Enabled SmartProxy Affinity for SSA

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations.py
cfme/tests/v2v/test_v2v_migrations_ui.py

__Adding tests__v2v migration where migration plan name includes only special characters.
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv --long-running -k 'test_migration_special_char_name' }}

[1LP][RFR]V2v migration with special chars name

---

cfme/base/__init__.py

Hi all, I am adding [BZ1639364](https://bugzilla.redhat.com/show_bug.cgi?id=1639364) to appliance name workaround. The original condition looked like this:
`BZ(1635178, forced_streams=['5.9', '5.10']).blocks`
I don't know why, but this resolves as `False`. Even though [BZ1635178](https://bugzilla.redhat.com/show_bug.cgi?id=1635178) has [BZ1639364](https://bugzilla.redhat.com/show_bug.cgi?id=1639364) listed in Blocks field. It might be caused by the fact that [BZ1635178](https://bugzilla.redhat.com/show_bug.cgi?id=1635178) is in ON_QA state. However I still believe `blocks` should resolve to `True` since [BZ1639364](https://bugzilla.redhat.com/show_bug.cgi?id=1639364) is still ON_DEV.
I am not sure which test case to verify this against, since it's pretty hard for me to find a test that …

[1LP][RFR][NOTEST] Adding BZ1639364 to appliance name workaround

---

cfme/utils/template/base.py
cfme/utils/template/ec2.py

This PR is fixing EC2 template upload process. 
Now it deletes ec2 ami before it's copied so it's failing.
Tested and it works correctly with this PR.
This PR removes copy & cleanup from the process and just adds tagged name for ami.
Also two shell functions called from template upload were changed to python functions.
This PR depends on this wrapanapi PR: https://github.com/ManageIQ/wrapanapi/pull/338

[NOTEST][RFR] EC2 template fix

---

cfme/tests/configure/test_proxy.py
cfme/utils/appliance/__init__.py

Update tests for provider proxy. Make them working.
* The IP has to be waited for
* Fixturize the changes to the appliance config, making sure the changes are "undone" after the tests by setting proxy to False instead of sub-dictionary.
* Added docstrings.
{{pytest: -v cfme/tests/configure/test_proxy.py --use-provider azure }}

[1LP][RFR] Make proxy tests working

---

cfme/tests/configure/test_visual_infra.py

This PR introduces changes and fixes to the test `test_infra_report_page_per_item`. Due to a BZ: [1616201](https://bugzilla.redhat.com/show_bug.cgi?id=1616201), the test was failing. The BZ has now been fixed on version `5.10.0.20`. The new changes include:
1. Uncollect the test if `appliance.version < 5.10.0.20`.
2. Add a new fixture `get_report` to queue a report as a part of setup and delete it as a part of teardown. The test would fail otherwise.
3. Navigate to correct page and use correct paginator.
4. Assert if the value of `items_per_page` is according to the value set on settings page.
{{pytest: cfme/tests/configure/test_visual_infra.py::test_infra_report_page_per_item --use-template-cache -sqvvv}}

[RFR] Fix Test: test_infra_report_page_per_item

---

cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/migrations.py

__Adding tests__ for Migration Plans Sorting type/Order and Archive plans
{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running -k 'test_v2v_ui_migration_plan_sorting' }}

[1LP][RFR]Adding new Test: Migration Plans Sorting type/Order

---

cfme/common/host_views.py
cfme/infrastructure/host.py
cfme/v2v/migrations.py

__Fixing__ host collection navigation to use correct view when navigating via Compute->Infrastructure->Providers.
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv --long-running  -k 'test_single_datastore_single_vm_migration'}}

[1LP][RFR]Fixing navigation on host collection via Compute-Infrastructure-Providers

---

cfme/tests/automate/custom_button/__init__.py
cfme/tests/automate/custom_button/test_infra_objects.py

- Some time tests  fails due to parameterization and big automation log request. So better to clean before execution of custom button.
- Also increased wait_for time.
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_automate -v}}
https://github.com/ManageIQ/integration_tests/pull/7964 needs for proper navigations

[RFR] Fix: Clean automation log before execute button

---

cfme/tests/cloud_infra_common/test_vm_ownership.py

groups is a plural attribute.
Tests are failing to login as the test user, not related to this AttributeError.

[1LP][RFR] Update groups reference in test_vm_ownership

---

cfme/tests/containers/test_smart_management.py

{{ pytest: cfme/tests/containers/test_smart_management.py --use-provider ocp-36-hawk }}

[RFR] CMQE Remove Blocking Bug for Smart Management Test

---

cfme/automate/explorer/domain.py
cfme/base/ui.py
cfme/services/catalogs/catalog_items/__init__.py
cfme/services/catalogs/catalog_items/ansible_catalog_items.py
cfme/services/catalogs/orchestration_template.py

Related to #7960
PRT run 27593 shows the tests that were hitting view timeouts when navigating to ServiceCatalog are passing.  Without #8007 content, will likely fail PRT in 27595
{{ pytest: cfme/tests/cloud/test_quota_tagging.py -k test_quota_tagging_cloud_via_services --use-provider rhos11 -vvvv --long-running }}

[1LP][RFR] Fix services catalog view

---

cfme/tests/containers/test_ssl_providers.py

{{ pytest: cfme/tests/containers/test_ssl_providers.py::test_add_mertics_provider_ssl --use-provider ocp-311 }}

[RFR] Updated CMQE SSL Test to Handle No Metrics

---

cfme/intelligence/reports/__init__.py
cfme/intelligence/reports/schedules.py
data/schedules_report/daily.yaml
data/schedules_report/hourly.yaml
data/schedules_report/monthly.yaml
data/schedules_report/once.yaml
data/schedules_report/weekly.yaml

move CloudIntelReportsView mycompany_title out of property
Related to #7960
The schedule form is not filling out correctly due to wt.patternfly's `BootstrapSelect' widget not filling correctly.  When it uses click to open, the widget immediately closes, and fails to complete `select_by_visible_text`.  Requires further debugging.
The form uses different keys than were being set by the data yaml, so I updated those keys.
{{ pytest: cfme/tests/intelligence/reports/test_reports_schedules.py -k test_schedule_queue }}

[RFR] Update keys in schedules_report/*.yaml, email types

---

cfme/tests/openstack/cloud/test_provider.py

Add cloud provider dashboard tests using parametrization
{{ pytest: cfme/tests/openstack/cloud/test_provider.py }}

[1LP][RFR] Add cloud provider dashboard tests

---

cfme/cloud/instance/image.py

- I found some time `ImageAllView` is fails. Its due to now clearning advance seach which done before... better to clear it at navigation. 
TimedOutError: Could not do Waiting for view [ImageAllView] to display at /home/ndhandre/cfme/integration_tests/cfme/utils/appliance/implementations/ui.py:562 in time
part of https://github.com/ManageIQ/integration_tests/issues/7960

[RFR][NOTEST] fix Image time out 

---

cfme/common/provider_views.py
cfme/physical/physical_server.py
cfme/physical/provider/redfish.py
cfme/tests/physical_infrastructure/test_redfish_physical_server_details.py
entry_points.txt

This test validates the statistics of a selected physical server that has been inventorised by the Redfish provider as it is shown in the GUI. It checks the displayed values against the ones accessible through the Redfish API client.
To enable the proper retrieval of a physical server's resource from the API server, we extended the `PhysicalServer` class to include the database field `ems_ref`. Thanks, @miha-plesko!
Depends on the following PRs:
* https://github.com/ManageIQ/wrapanapi/pull/328
* https://github.com/ManageIQ/integration_tests/pull/7629
/cc @miha-plesko

[1LP][WIP] Add a test for redfish physical server details

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/test_download_report.py

This PR modifies `download` method for Report. If the appliance version is greater than 5.10, it looks for `Print or export as PDF` option while downloading a report.
{{pytest: cfme/tests/intelligence/test_download_report.py --use-template-cache -sqvvv}}

[1LP][RFR] Modify report download method for 5.10

---

cfme/tests/configure/test_logs.py

Shriver: expanding pytest coverage to include all modified cases
{{ pytest: -v cfme/tests/configure/test_logs.py --use-provider complete }}

[1LP][WIPTEST] new test_provider_log_level

---

data/schedules_crud/basic01.yaml

This PR introduces fix to YAML data for scheduling a report. There is a change in the name of `txt`, `csv` and `pdf`. Until this change, `txt`, `csv` and `pdf` were not selected even if they were set to `True` in the data, since they were not configured properly. 
{{ pytest: cfme/tests/intelligence/reports/test_crud.py::test_schedule_crud --use-template-cache -sqvvv }}

[1LP][RFR]Fix YAML data for scheduling a report

---

cfme/tests/cloud/test_providers.py

{{ pytest: -v cfme/tests/cloud/test_providers.py::test_openstack_provider_has_dashboard  }}

[1LP][RFR] new test_openstack_provider_has_dashboard

---

cfme/base/ui.py
cfme/tests/configure/test_remote_server_tabs.py

{{ pytest: -v cfme/tests/configure/test_remote_server_tabs.py }}
new test to address new feature (in 5.10) https://bugzilla.redhat.com/show_bug.cgi?id=1536524
I had to modify is_displayed and navigation for Server as it depends whether the server is remote or not

[1LP][RFR] new test for advanced setting for remote servers

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/reports/test_crud.py

This PR adds a test case, which creates a schedule for a base report and asserts the schedule was created without any error.
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_reports_crud_schedule_for_base_report_once --use-template-cache -sqvvv}}

[1LP][RFR] Automate test: Create schedule for base report

---

cfme/tests/infrastructure/test_host.py

{{ pytest: cfme/tests/infrastructure/test_host.py::test_discover_host  -qsvvvv }}
Fixed:
```
>       all_hosts = collection.all(provider)
E       TypeError: all() takes exactly 1 argument (2 given)
cfme/tests/infrastructure/test_host.py:93: TypeError
TypeError
all() takes exactly 1 argument (2 given)
```

[RFR] Fixed TypeError of host in 5.10z

---

cfme/infrastructure/pxe.py

{{ pytest: cfme/tests/infrastructure/test_customization_template.py::test_name_max_character_validation -qsvvv }}
Fixed:
```
>           title = 'Customization Template "{name}"'.format(self.context['object'].name)
E           KeyError: 'name'
cfme/infrastructure/pxe.py:405: KeyError
KeyError
'name'
```

[RFR] Fixed KeyError of customization_template in 5.10z

---

cfme/services/catalogs/catalog.py
cfme/services/catalogs/catalog_items/__init__.py
cfme/services/catalogs/orchestration_template.py

1) Removed assertions to be moved to test in following PR
2) Fixed some views
3) Changed order of filling fields as provider dropdown appears once template is selected.
{{ pytest: --use-provider rhos11 cfme/tests/services/test_provision_stack.py::test_provision_stack }}

[RFR]Orchestration view is_displayed fix

---

cfme/cloud/instance/image.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

for running PRT
Will collect tests here that were hitting StopIteration on dynamictable.row_save, or other index access to table.
Might include some test/framework tweaks as well.  Really just looking to eliminate StopIteration exceptions, but not replace them with RowNotFound. 
{{ pytest: --use-provider complete --long-running -vvv cfme/tests/cloud/test_providers.py cfme/tests/ansible/test_embedded_ansible_tags.py cfme/tests/cloud_infra_common/test_provisioning.py cfme/tests/cloud_infra_common/test_relationships.py cfme/tests/cloud_infra_common/test_tag_objects.py }}

[WIPTEST] Update wt.core, debug StopIteration

---

cfme/tests/services/test_dialog_element_in_catalog.py

{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dropdownlist_required_dialog_element }}
steps
1. Create a dropdownlist dialog with some entries and "required" button turned ON.
2. Create a catalog item that uses this dialog.
3. When we order that catalog item the order shouldn't be submitted in the dropdown. Submit button should be disable.

[1LP][RFR] Add service dropdownlist dialog required element

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

sync_template_tracker hitting TypeError when trying to parse templates

[1LP][RFR]miq-version 0.1.8, fix py3 compat and TypeError

---

cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_crud.py

This PR adds a test case, which creates a custom report and checks if a schedule can be created for it.
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_crud_custom_report_schedule --use-template-cache -sqvvv }}

[1LP][RFR] Automate Test: Add schedule for custom report

---

cfme/configure/access_control/__init__.py
cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py

{{ pytest: cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py -k 'test_show_quota_used_on_tenant_screen'  --use-provider rhv41  --use-provider vsphere67-nested --provider-limit 2 -v }}
Ref. PR: #8020

[1LP][RFR] QUOTA TEST:  To show quota used on tenant quota screen even when no quotas are set

---

cfme/tests/openstack/cloud/test_flavors.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/cloud/test_keypairs.py
cfme/tests/openstack/cloud/test_networks.py
cfme/tests/openstack/cloud/test_volume_backup.py
cfme/tests/openstack/cloud/test_volumes.py
cfme/tests/openstack/infrastructure/test_host_lifecycle.py
cfme/tests/openstack/infrastructure/test_host_power_control.py
cfme/tests/openstack/infrastructure/test_hosts.py
cfme/tests/openstack/infrastructure/test_provider.py
cfme/tests/openstack/infrastructure/test_relationships.py
cfme/tests/openstack/infrastructure/test_resources.py
cfme/tests/openstack/infrastructure/test_roles.py

Added `@pytest.mark` to separate regression and RFE tests.
Marked all RFE tests with `@pytest.mark.rfe`, then
in order to run only RFE tests, we invoke the following key during execution:
`-m rfe`
Marked all Regression tests with `@pytest.mark.regression`, then
in order to run only Regression tests, we invoke the following key during execution:
`-m regression`

[1LP][RFR] Added @pytest.mark to separate Regression and RFE tests

---

cfme/tests/configure/test_schedule_operations.py

{{ pytest: cfme/tests/configure/test_schedule_operations.py -k 'test_schedule_timer[virtualcenter-Once]' -v }}
Fixed Error:
```
available_list = view.time_zone.all_options
E       AttributeError: 'ScheduleAddView' object has no attribute 'time_zone'
cfme/tests/configure/test_schedule_operations.py:146: AttributeError
AttributeError
'ScheduleAddView' object has no attribute 'time_zone'
```

[RFR] Fixed AttributeError in ScheduleAddView for 5.10z

---

cfme/common/vm_views.py

{{ pytest: cfme/tests/cloud/test_delete_cloud_object.py -k 'test_delete_image_appear_after_refresh' -v }}
Fixed Error:
```
>               data_dict['no_snapshots'] = data_dict['quad']['bottomRight']['tooltip']
E               KeyError: 'tooltip'
cfme/common/vm_views.py:69: KeyError
KeyError
'tooltip'
```

[1LP][RFR] Fixed KeyError in quadicon for 5.10z

---

cfme/tests/configure/test_region.py

{{ pytest: cfme/tests/configure/test_region.py -k 'test_description_change' -v }}
Fixed error:
```
E         + Settings Region "y7VlL [0]"
E         ? ^^^^^^^^
cfme/tests/configure/test_region.py:31: AssertionError
AssertionError
assert 'CFME Region "y7VlL [0]"' == 'Settings Region "y7VlL [0]"'
- CFME Region "y7VlL [0]"
? ^^^^
+ Settings Region "y7VlL [0]"
? ^^^^^^^^
```

[1LP][RFR] Fixed assertion error in region for 5.10z

---

cfme/tests/ansible/test_embedded_ansible_automate.py

Add tier metadata for test_alert_run_ansible_playbook so that it matches tier on Polarion.

[1LP][RFR] Add pytest.mark.tier(3) for all tests in test_embedded_ansible_automate

---

cfme/tests/infrastructure/test_project_quota.py

__Added__ custom role instead of using super_administrator role. 
Motivation behind the change is comment 6 in the following BZ https://bugzilla.redhat.com/show_bug.cgi?id=1636958#c6 .
TL;DR
Quotas should not be applied to Super_administrator role because of possible (and quite real) unpredictable behaviour.
juwatts:
{{ pytest: cfme/tests/infrastructure/test_project_quota.py --use-provider complete --long-running }}

[1LP][RFR] Create custom role in quota tests instead of super_admin

---

cfme/tests/test_appliance.py

__Adding tests__ for non-existence rh-ruby packages in 5.10:
https://polarion.engineering.redhat.com/polarion/#/project/RHCF3/workitem?id=RHCF3-42352
{ pytest: -v cfme/tests/test_appliance.py::test_appliance_console_packages }

[1LP][RFR] Add test for scl packages.

---

cfme/provisioning.py
cfme/tests/infrastructure/test_iso_provisioning.py
data/rhel7.cfg

This PR does a couple of things:
1) We started using RHEL7.5 image in ISO provisioning testing. That's why I am adding _wget_ installation to the Kickstart script. We need to make a callback to CFME in the end, but _wget_ is not present on clean RHEL7.5 box.
2) Removing BZ1613326 since it's been verified.
3) Adding #8033 as a blocker.
4) BZ1642924 now causes that e-mail about approval of provision request is not sent. Therefore I suggest we don't check it while the bug is open. It's probably not a good idea to block a big chunk of tests just because of that.
5) Adding `addr_mode` as a new value in `provisioning_data`. You can choose either "Static" or "DHCP". If you don't provide anything in cfme_data, then this is just ignored.
6) Setting VM to be powered off after provision. This is in …

[1LP][RFR][NOTEST] Updating ISO provisioning test

---

cfme/tests/infrastructure/test_system_image_type.py

{{ pytest: cfme/tests/infrastructure/test_system_image_type.py -k 'test_system_image_duplicate_name_error_validation' -v }}
Fixed Error:
```
>               provision_type=SystemImageType.VM_OR_INSTANCE)
E           AssertionError: Pattern 'Name has already been taken' not found in 'assert_no_error: error: Name is not unique within region 0'
cfme/tests/infrastructure/test_system_image_type.py:37: AssertionError
AssertionError
Pattern 'Name has already been taken' not found in 'assert_no_error: error: Name is not unique within region 0'
```

[1LP][RFR] Fixed Assertion error in system_image_duplicate_name for 5.10z

---

cfme/tests/openstack/cloud/test_provider.py
cfme/tests/openstack/infrastructure/test_hosts.py

Update to previous PR: https://github.com/ManageIQ/integration_tests/pull/8023
Added @pytest.mark to separate regression and RFE tests.
Marked all RFE tests with @pytest.mark.rfe, then
in order to run only RFE tests, we invoke the following key during execution:
-m rfe
Marked all Regression tests with @pytest.mark.regression, then
in order to run only Regression tests, we invoke the following key during execution:
-m regression

[1LP][RFR ]Added new @pytest.mark to separate regression and RFE tests

---

sprout/appliances/admin.py
sprout/appliances/tasks.py

Exception when this is run by celery-beat against cm-pod1/2 since their `list_vms` mgmt function returns a list of names instead of objects.
Continuing to debug orphan behavior, just small change to consider on its own.
```
2018-10-31 17:13:37,547 [ERROR] 'str' object has no attribute 'name'
Traceback (most recent call last):
File "/opt/sprout/integration_tests/sprout/appliances/tasks.py", line 125, in wrapped_task
return task(self, *args, **kwargs)
File "/opt/sprout/integration_tests/sprout/appliances/tasks.py", line 1985, in synchronize_untracked_vms_in_provider
if Appliance.objects.filter(name=vm.name, template__provider=provider).count() != 0:
AttributeError: 'str' object has no attribute 'name'
```

[RFR] Fix sprout orphans

---

requirements/freeze.py

L64 passes this as args.keep, opting to set that name here via dest instead of changing L64 to use keep_venv

[RFR] Fix arg name in requirements/freeze.py

---

cfme/control/explorer/alert_profiles.py

__Fixing__ AlertProfile 'Edit' view because currently the is_displayed() conditions are not met, the third condition has been edited to fix this and reflect the accordion tree info. 
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_alert_profile_crud }}

[RFR] Fix alert_profile 'Edit' view by adding a check to is_displayed()

---

cfme/tests/ssui/test_ssui_myservice.py

{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_service_start --use-provider vsphere67-nested -svvv }}

[RFR] Fix ssui service start

---

cfme/control/explorer/alerts.py

__Changing__ `assert view.is_displayed` to `view.wait_displayed()` in the `AlertCollection` method `create()` to fix the `test_alert_snmp` test. 
{{ pytest: --long-running cfme/tests/control/test_alerts.py::test_alert_snmp }}

[1LP][RFR] Fix test failures related to view.is_displayed during Alert creation 

---

cfme/cloud/instance/azure.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_tag[azure-common] --use-provider=complete }}
This PR fixes
`SelectItemNotFound: Could not find 'standard_a1' in BootstrapSelect(locator=u'.//div[contains(@class, "bootstrap-select")]/button[normalize-space(@data-id)="hardware__instance_type"]/..')`
In 5.9 instance types are like `standard_a1`, but in 5.10 they are like `Standard_A1`

[1LP][RFR] fixed azure vms provisioning in 5.10

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Just looking to resolve TypeError on L272 for test_vm_instance_analysis.
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py --use-provider complete --long-running -k 'test_ssa_template or test_ssa_schedule or test_ssa_vm or test_ssa_users or test_ssa_groups or test_drift_analysis' }}
FIXES #8099

[1LP][RFR] Remove smtp_test kwarg from do_vm_provisioning call

---

cfme/infrastructure/virtual_machines.py

Fixed following Error:
```
E       assert False
E        +  where False = <cfme.infrastructure.virtual_machines.HostTemplatesOnlyAllView object at 0x7f2e613bcad0>.is_displayed
cfme/tests/cloud_infra_common/test_relationships.py:158: AssertionError
AssertionError
assert False
+  where False = <cfme.infrastructure.virtual_machines.HostTemplatesOnlyAllView object at 0x7f2e613bcad0>.is_displayed
```
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_host_relationships[virtualcenter-Templates] -v }}

[RFR] Fixed is_displayed in HostTemplatesOnlyAllView for 5.10z

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Believe this was the cause of many duplicate 'test_smartstate' instances in our ec2 region.  The duplicate name instances don't get cleaned up by normal means, and should have unique id's.

[1LP][RFR] Update test_vm_instance_analysis, unique ssa agent name

---

cfme/cloud/instance/image.py
cfme/tests/cloud_infra_common/test_tag_objects.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py::test_tag_cloud_objects }}
This PR fixes
```
test_tag_cloud_objects[cloud_images-cloud-list] 
test_tag_cloud_objects[cloud_images-cloud-details]
```
Fixed `AttributeError: 'ImageCollection' object has no attribute 'provider'`

[WIPTEST] fixed ImageProviderAllView

---

cfme/tests/control/test_actions.py

If I understand this correctly, these test cases verify primarily CFME's control capabilities. The actions that are determined by used control policies (start VM, stop VM, suspend VM) also of course verify VM capabilities of provider. However, since those capabilities are verified at other places in more basic scenarios as well (e.g. test_vm_power_control.py), I don't see any need to include test_actions.py in RHV regression suite. The point of that suite is to test CFME's interaction with RHV and these kind of interactions are tested elsewhere. CFME control and policy capabilities are not really in scope.
@istein1 Removing tests as per our e-mail conversation.

[1LP][RFR][NOTEST] Removing test_actions.py out of RHV regression suite

---

cfme/tests/infrastructure/test_tenant_quota.py

{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py::test_setting_child_quota_more_than_parent -v }}
Fixed Error:
```
E           AssertionError: assert  message: Error when saving tenant quota: Validation failed: Templates allocated quota is over allocated, parent tenant does not have enough quota. 
E            Available messages: [u'Error when saving tenant quota: Validation failed: TenantQuota: Templates allocated quota is over allocated, parent tenant does not have enough quota']
../cfme_venv/lib/python2.7/site-packages/widgetastic_patternfly/__init__.py:258: AssertionError
AssertionError
assert  message: Error when saving tenant quota: Validation failed: Templates allocated quota is over allocated, parent tenant does not have enough quota. 
Available messages: [u'Error when …
```

[1LP][RFR] Fixed AssertionError in child_quota for 5.10z

---

cfme/common/provider_views.py
cfme/tests/infrastructure/test_infra_tag_filters_combination.py

{{ pytest: -v cfme/tests/infrastructure/test_infra_tag_filters_combination.py::test_tagvis_tag_datacenter_combination }}
This PR fixes ProviderTemplatesView that affected 2 tests:
```
test_tagvis_tag_datacenter_combination[infra_templates-infra-not_visible]
test_tagvis_tag_datacenter_combination[infra_templates-infra-visible]
```
Also removed the BZ blocker.

[1LP][RFR] fixed ProviderTemplatesView and removed BZ blocker

---

cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py

```
>       raise NameError("Could not find provider {}".format(provider_name))
E       NameError: Could not find provider Embedded Ansible Automation Manager
cfme/utils/providers.py:340: NameError
NameError
Could not find provider Embedded Ansible Automation Manager
```
```
In [5]: for prov in providers:
...:     print prov.name, getattr(prov, "parent_ems_id", False)
...:
...:
RHOS11 False
RHOS11 Network Manager 3
RHOS11 Cinder Manager 3
RHOS11 Swift Manager 3
Embedded Ansible Automation Manager False
```
I found the check for `parent_ems_id` is not proper in case of `Ansible Embedded Manager`. To deal with Manger better to check in provider name only `"Manager"` is available or not.

[1LP][RFR][NOTEST] Fix for all method avoiding Ansible Embedded Manager

---

cfme/tests/infrastructure/test_host.py

{{ pytest: -v cfme/tests/infrastructure/test_host.py::test_tag_host_after_provider_delete }}
It was not able to tag the host because it was defined using provider (which was deleted).

[1LP][RFR] fixed test_tag_host_after_provider_delete

---

cfme/tests/cloud/test_instance_power_control.py

{{ pytest: cfme/tests/cloud/test_instance_power_control.py::test_hard_reboot_unsupported --use-provider azure  --long-running -v }} 
Fixed Error:
```
E           AssertionError: assert  message: Reset does not apply to at least one of the selected items. 
E            Available messages: [u'Reset action does not apply to selected items']
../cfme_venv/lib/python2.7/site-packages/widgetastic_patternfly/__init__.py:258: AssertionError
AssertionError
assert  message: Reset does not apply to at least one of the selected items. 
Available messages: [u'Reset action does not apply to selected items']
```

[1LP][RFR] Fixed AssertionError while hard_reboot of azure in 5.10z

---

widgetastic_manageiq/__init__.py

__Fixing__ test_alert_timeline_cpu because currently it is failing in the `_prepare_event()` method of `TimelinesChart` class. The fix is to remove whitespace from `br.tail` and to add a `try` `except` clause around the `get_groups()` method.
{{ pytest: --long-running cfme/tests/control/test_alerts.py::test_alert_timeline_cpu }}

[1LP][RFR] Fix alert_timeline_cpu by making change for TimelinesChart class

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_buttons.py

- Every custom button object have `Unassigned Buttons` Group. The view is common like other group except title.
- Added new non fuctional test for required filed checks like icon and request. 
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_button_required -v}}

[1LP][RFR] Custom button Icon and Request required test

---

cfme/ansible/playbooks.py
cfme/tests/ansible/test_embedded_ansible_tags.py

{{ pytest: -v cfme/tests/ansible/test_embedded_ansible_tags.py::test_tagvis_playbook }}
This PR fixes
```
test_tagvis_playbook[visible]
test_tagvis_playbook[notVisible]
```
Fixed the error
`AttributeError: 'PlaybookDetailsView' object has no attribute 'in_ansible_repositories'`

[1LP][RFR] fixed PlaybookDetailsView

---

cfme/control/explorer/alerts.py

__Fixing__ `update` method of `Alert` object by using `view.wait_displayed()`
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_alert_crud }}

[1LP][RFR] Add view.wait_displayed() when updating an alert

---

cfme/networks/views.py
cfme/tests/networks/test_sdn_balancers.py

{{ pytest: -v cfme/tests/networks/test_sdn_balancers.py::test_sdn_balancers_tagvis --use-provider azure }}
For 5.9.6 title is also with `(All Load Balancers)`
juwatts: adding azure provider to pytest statement, tests were uncollected on azure_msdn.

[1LP][RFR] fixed OneProviderBalancerView

---

cfme/control/explorer/alerts.py
cfme/tests/control/test_basic.py

__Extending__  the `alert_collection.create()` method to work when only passed a description. The `create()` method now defaults to have `timeline_event=True` and `driving_event='Hourly Timer'`. The latter is selected from the dropdown menu on the `AlertCollection` "Add" page. 
__Updating__ docstring for `Alert` to reflect the proper way to create new alerts; via `alert_collection.create()` method
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_alert_crud }}

[1LP][RFR] Update Alert docstring and add ability to create alert with only a 'description'

---

cfme/tests/control/test_alerts.py

__Updating tests__ for `test_alerts.py` so that they don't run against RHEVM provider. c.f. [BZ 1533451](https://bugzilla.redhat.com/show_bug.cgi?id=1533451) and the [support matrix](https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/support_matrix/index).
Supersedes #8135 
{{ pytest: --long-running cfme/tests/control/test_alerts.py::test_alert_vm_turned_on_more_than_twice_in_past_15_minutes }}

[RFR] Add global uncollect for RHEVM providers for alerts tests

---

cfme/control/explorer/alerts.py
cfme/tests/control/test_default_alerts.py
data/ui/control/default_alerts.yaml

__Extending__  AlertCollection to have an all() method. The all method will read the table on the "All Alerts" alerts page and create a list of alert objects based on the fields in that table. 
__Adding tests__ smoke test for the default alerts predefined on the appliance. 
__Adding data file__ for the default alerts on CFME 5.9.5.3 and 5.10.0.21
{{ pytest: cfme/tests/control/test_default_alerts.py::test_default_alerts }}

[1LP][RFR] Add default alerts smoke test

---

cfme/tests/automate/custom_button/test_buttons.py

- OpenUrl facility now only available for `Single` display for option
- It was  bug now fixed by restricting it for `List` or `single and list`
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_open_url_availability -v}}
Note: Need https://github.com/ManageIQ/integration_tests/pull/8118 for Unassigned Group functionality

[1LP][RFR] Custom Button: Open url non functional test

---

cfme/generic_objects/definition/__init__.py
cfme/generic_objects/definition/definition_views.py
cfme/generic_objects/definition/ui.py
cfme/generic_objects/instance/ui.py
cfme/services/myservice/ui.py
cfme/tests/generic_objects/test_instances.py

- Fix `MyServicesView` `is_displayed`
- Fix `GenericObjectActionsDetailsView`
- Added `resetter` after `All` call so, It will maintain All view every time... When we try to navigate second time. It will on a detail page due to previous actions.
- Added sentaku propery for `instance` count. So if count is 0; it will not try to click on `Instance` from relationship table.
Let's add complete generic object tests against changes. 
{{pytest: cfme/tests/generic_objects/ -vv}}

[1LP][RFR] Fix generic object test and views

---

cfme/fixtures/xunit_tools.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

This is effectively temporary, as #7690 will replace this use.

[1LP][RFR] whitelist test_v2v in xunit_tools

---

cfme/control/explorer/conditions.py
widgetastic_manageiq/expression_editor.py

__Fixing__ the condition CRUD test. This requires: 
__1)__ Updating the `condition_collection.create()` method to use `view.wait_displayed()` and update `ExpressionEditor` to use `show_loc` to select the proper buttons. 
__2)__ Putting in a workaround for [BZ 1649057](https://bugzilla.redhat.com/show_bug.cgi?id=1649057) in `BootstrapSelect` for the expression_editor
__3)__ Fixing `EditConditionView` `is_displayed()` method
__4)__ Adding a view for all the conditions in a condition class, since the appliance redirects the user to this page when a condition is deleted. 
FIXES #8103
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_condition_crud }}

[1LP][RFR] Fixing Condition CRUD test 

---

cfme/tests/platform/test_advanced_config.py

__Adding tests__ for advanced config resetting.
juwatts:
{{ pytest: cfme/tests/platform/test_advanced_config.py --use-provider complete }}

[1LP][RFR] Test reset of advanced config to default values.

---

cfme/tests/services/test_iso_service_catalogs.py

Create customization template in preparation for `test_rhev_iso_servicecatalog` if it does not exist. Unfortunately, I cannot provide proper verification run, since this test later fails at `view.is_displayed` [here](https://github.com/ManageIQ/integration_tests/blob/5a0745b6fd75e33898878fa06da8bb5bb516a12b/cfme/services/catalogs/catalog_items/__init__.py#L494).

[1LP][RFR][NOTEST] Updating iso_cust_template fixture

---

cfme/services/myservice/ui.py

{{pytest: cfme/tests/services/test_myservice.py::test_service_link -v --long-running}}
ServiceVMDetailsView inherits VMDetailsEntities
which does not have navigation and other things so removed them and fixed object .

[1LP][RFR]Service Link test fix

---

cfme/automate/explorer/instance.py
cfme/automate/explorer/klass.py

This tiny fix should resolve at least one navigation failure in about 20 automate tests using automate classes.
I've included test_instance module as well since a few of those tests were failing from this as well.
I'll be on PTO tomorrow, planning a very small scope for this, PRT may not be totally clean for these modules, but I'm looking for no timeout failures from adding a class, because of the view's is_displayed method.
{{ pytest: cfme/tests/automate/test_class.py cfme/tests/automate/test_instance.py --long-running -vv }}

[1LP][RFR] Fix ClassAddView.is_displayed

---

cfme/automate/explorer/domain.py

{{ pytest: cfme/tests/automate/test_domain.py -k 'test_domain_edit_enabled or test_domain_crud' -v }}
Fixed Attribute Error:
```
>           self.title.text == 'Editing Automate Domain "{}"'.format(self.obj.name))
E       AttributeError: 'DomainEditView' object has no attribute 'obj'
cfme/automate/explorer/domain.py:85: AttributeError
AttributeError
'DomainEditView' object has no attribute 'obj'
```
Affected tests:
1. cfme/tests/automate/test_domain.py/test_domain_crud[disabled]
2. cfme/tests/automate/test_domain.py/test_domain_crud[enabled]
3. cfme/tests/automate/test_domain.py/test_domain_edit_enabled

[1LP][RFR] Fixed AttributeError in DomainEditView for 5.10z

---

cfme/control/explorer/alerts.py

__Fixing__ `alert_collection.create()` method because it assumes that a `driving_event` is necessary to define an alert. However, if `evaluate is not None` then this is not true, and when the evaluate field is filled the driving event dropdown menu disappears -- resulting in a failed alert creation. 
The fix is to only select a default `driving_event` if both `driving_event` and `evaluate` are `None`
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_alert_crud }}

[1LP][RFR] Fix alert creation by adding an extra condition for the default driving event

---

cfme/services/catalogs/orchestration_template.py

{{ pytest: cfme/tests/services/test_orchestration_template.py -k 'test_orchestration_template_crud'  -v }}
Fixed Error:
```
)
E       AttributeError: 'OrchestrationTemplate' object has no attribute 'name'
cfme/services/catalogs/orchestration_template.py:69: AttributeError
AttributeError
'OrchestrationTemplate' object has no attribute 'name'
```
Affected tests:
1. cfme/tests/services/test_orchestration_template.py/test_orchestration_template_crud[azure]
2. cfme/tests/services/test_orchestration_template.py/test_orchestration_template_crud[heat]
3. cfme/tests/services/test_orchestration_template.py/test_orchestration_template_crud[vapp]
4. cfme/tests/services/test_orchestration_template.py/test_copy_template

[1LP][RFR] Fixed AttributeError in OrchestrationTemplate for 5.10z

---

cfme/tests/openstack/cloud/test_instances.py

Changed order of test arguments so instances will be torn down before volume
If volume is deleted first while still attached to instance, deletion will fail
{{ pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_volume }}

[1LP][RFR] fix teardown of test_instance_attach_volume

---

cfme/tests/v2v/test_v2v_migrations.py

{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -k test_dual_nics_migration -vvvv}}
Migration with dual NICs working in 5.10.0.24 and this test compare MAC of both vms on source and target.  As it is reading string from UI tables, sometime MACs become unordered and string just don't match, this will fix that.
For example,
```
E         - 00:50:56:80:20:5d, 00:50:56:80:84:c7
E         + 00:50:56:80:84:c7, 00:50:56:80:20:5d
```
Failure - https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kkulkarn-v2v/50/Artifactor_Report/report.html#cfme/tests/v2v/test_v2v_migrations.py/test_dual_nics_migration[virtualcenter-6.5-rhevm-4.2-form_data_vm_obj_dual_nics0]

[1LP][RFR] Fixes dual NICs MAC comparison failure - 1liner

---

cfme/fixtures/tag.py
cfme/tests/cloud_infra_common/test_tag_objects.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py::test_tagvis_infra_object }}
1. fixed finalizer cleanup for test_tagvis_infra_object
2. fixed checking visibility for hosts

[1LP][RFR] fixed finalizer cleanup for test_tagvis_infra_object

---

cfme/intelligence/reports/__init__.py
cfme/intelligence/reports/menus.py

This PR fixes TimedOutError with CloudIntelReportsView  and `test_add_reports_to_available_reports_menu` test which failed due to UI change in 5.10
Changes:
1) A resetter method has been added to the CloudIntelReports to reset the page.
2) To fix UI error, `get_folders` and `get_subfolders` methods have been updated.
{{pytest: cfme/tests/intelligence/reports/test_menus.py --use-template-cache -sqvvv}}
Related to #7960

[1LP][RFR]Fix CloudIntelReportsView TimedOutError and other test failure

---

cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_crud.py
widgetastic_manageiq/__init__.py

This PR fixes `test_schedule_crud` by making following changes:
1) `StaleElementReferenceException` error. A condition has been added to `AlertEmail` in `widgetastic_manageiq/__init__.py` file. 
2) `view_wait_displayed` has been added to `update` method of schedules, which fixes assertion error on asserting `view.is_displayed`.
3) Fix `NameError` for `ScheduleCollection` in `test_schedule_crud`.
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_schedule_crud --use-template-cache -sqvvv}}

[1LP][RFR] Fix StaleElementReferenceException error for test_schedule_crud

---

cfme/networks/floating_ips.py
cfme/tests/networks/test_tag_tagvis.py

{{ pytest: -v cfme/tests/networks/test_tag_tagvis.py  --use-provider=complete }}
I changed the provider for these tests from OpenStack to Azure because Azure has load balancers and `test_tagvis_network_provider_children[cloud-Load Balancers]` will not be skipped anymore.

[RFR] changed the provider to azure for test_tag_tagvis.py

---

cfme/intelligence/reports/schedules.py

This PR removes all the commented checks under all `is_displayed` and other methods that were commented due to BZ: [1441101](https://bugzilla.redhat.com/show_bug.cgi?id=1441101).
{{pytest: cfme/tests/intelligence/reports -k "test_schedule_queue  or test_schedule_crud" --use-template-cache -sqvvv}}

[1LP][RFR] Remove TODO from schedules

---

cfme/configure/settings.py

This PR fixes `TimedOutError` error on time_profile test cases.
{{pytest: cfme/tests/configure/test_timeprofile.py -k "test_time_profile_crud or test_time_profile_name_max_character_validation or test_time_profile_copy" --use-template-cache -sqvvv}}

[1LP][RFR] Fix TimeProfileAddView's is_displayed

---

cfme/configure/configuration/system_schedules.py

This PR fixes `TimedOutError` due to a typo in the `ScheduleEditView`'s is_displayed method.
{{pytest: cfme/tests/configure/test_schedule_operations.py::test_schedule_crud --use-template-cache -sqvvv}}

[1LP][RFR]Fix ScheduleEditView is_displayed

---

cfme/tests/configure/test_access_control.py

{{ pytest: -v cfme/tests/configure/test_access_control.py::test_group_crud_with_tag }}
This PR fixes `test_group_crud_with_tag[tag_expression-virtualcenter]`that didn't work because tag value was not filled

[RFR] removed BZ and fixed fill_tag for test_group_crud_with_tag

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

note: wrapanapi being removed from the `frozen_doc.*.txt` rectifies a version file management mistake

[1LP][RFR] upgrade notebook requirement after cve warning

---

widgetastic_manageiq/__init__.py

There are views with WaitTab widget like AnsibleCatalogItemView where WaitTab is displayed after some timeout. If other view tries to access child widget of such view right after navigation, it will get exception on wait_tab->child_widget_accessed->select() because wait tab isn't rendered yet.
So, it is necessary to wait for WaitTab to be displayed before attempt to select tab and/or access child widget.

[1LP][RFR] WaitTab should wait until it is displayed before accessing child widget

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

[1LP][RFR] Updating blockers for test_ssa_schedule

---

cfme/tests/automate/custom_button/test_generic_objects.py

- In new build `5.10.0.25` if `button` is `disabled` then `group` `disabled`. 
{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_expression}}

[RFR] fix 5.10.0.25 changes in enablement

---

cfme/intelligence/reports/schedules.py

This PR fixes a typo in `reports/schedules.py` from one of my previous commits.
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_reports_disable_enable_schedule --use-template-cache -sqvvv}}

[RFR]Remove typo

---

cfme/infrastructure/host.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/infrastructure/test_host_drift_analysis.py

This PR is a reaction to [commit](https://github.com/ManageIQ/integration_tests/commit/93ed7bd51fad54eb50ab87ee0131cba605e687aa) made by @mshriver few days ago. The indexes used there (-2 and -1) actually selected the _oldest_ two SSA runs. Often times, this was not an issue. Especially with VMs that are provided fresh and clean. However, if you had some older SSA runs still present on your hosts, this test failed, because it was not comparing the two most recent SSAs. 
Unfortunately, I cannot properly test test_drift_analysis for VMs in automation since that test case is still blocked by #8152.
{{pytest: cfme/tests/infrastructure/test_host_drift_analysis.py::test_host_drift_analysis --long-running --use-provider rhv41 -vv}}

[RFR] Fixing test_host_drift_analysis

---

cfme/tests/test_rest.py

This PR fixes `ScopeMismatch` error on `TestEventStreamsRESTAPI`. Changing scope of all the fixtures involved to `function`.
{{pytest: cfme/tests/test_rest.py::TestEventStreamsRESTAPI --use-template-cache -sqvvv}}

[RFR]Fix ScopeMismatch error

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_container_objects.py

{{pytest: cfme/tests/automate/custom_button/test_container_objects.py::test_custom_button_expression -vv --use-provider ocp-39-hawk}}

[1LP][RFR] visibility and enablement test for container

---

cfme/tests/configure/test_log_depot_operation.py

Fixed here the error for `test_collect_log_depot[dropbox]`
```
AssertionError
assert datetime.datetime(2018, 11, 21, 22, 55, 58) >= datetime.datetime(2018, 11, 21, 23, 55, 38, 959365)
```
that happened due to incorrect `collect_time` calculation, introduced here #7859
Initially, I didn't take DST (Daylight saving time) into account, so with the use of timezones this test should work correctly all year round :+1:

[1LP][RFR] fixed collect_time for dropbox log collection

---

cfme/tests/automate/custom_button/test_cloud_objects.py

- Visibility and enablement for cloud custom button objects
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py::test_custom_button_expression -vvv}}

[1LP][RFR] Custom Button: Cloud-Visibility and Enablement

---

cfme/tests/control/test_alerts.py

Adding uncollect for KubeVirt Provider
{{ pytest: --long-running --use-provider kubevirt cfme/tests/control/test_alerts.py::test_alert_vm_turned_on_more_than_twice_in_past_15_minutes }}

[1LP][RFR] Uncollect for KubeVirt Provider so that alerts tests don't run on this provider

---

cfme/services/catalogs/catalog_items/catalog_bundles.py
cfme/tests/infrastructure/test_quota_tagging.py

- This test case verifies the quota assigned by automation method for user and group
is working correctly for the infra providers by ordering catalog bundle.
- Added new fixture
- **catalog bundle()**
- **catalog_item_list** : this is used to add more than one catalog items to list and pass them to catalog bundle.
- Here in this test, only one catalog item is created and it is passed to add in catalog bundle.
- catalog_item_list is taken because list of catalog items are accepted by catalog bundle's create method
{{ pytest: cfme/tests/infrastructure/test_quota_tagging.py -k 'test_quota_catalog_bundle_infra' -v }}

[1LP][RFR] Test for Quota with Catalog_bundle: Verifying quota limit by ordering catalog bundle over the assigned quota 

---

cfme/base/ssui.py
cfme/services/myservice/ui.py
cfme/tests/automate/custom_button/test_service_objects.py

- Service and Generic object custom button tests base
- display test for service and generic object
- Fix sometime `ssui` login problem with `wait`
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py -vvv}}

[1LP][RFR] Custom button: Service and Generic object test

---

cfme/tests/control/test_alerts.py

__Fixing__ `cfme/tests/control/test_alerts.py::test_alert_hardware_reconfigured` because it is currently using vddk v5_5 instead of a more recent v6_5. This results in the test failing against the provider "virtualcenter 6.7" because SSA is not able to be completed. In order to fix this, I have modified `vddk_url` to default to `v6_5` is testing against the provider "virtualcenter 6.7"
We do not use vddk `v6_7` because according to [BZ 1651702](https://bugzilla.redhat.com/show_bug.cgi?id=1651702), this version does not work with SSA in CFME. 
{{ pytest: --use-provider vsphere67-nested --long-running cfme/tests/control/test_alerts.py::test_alert_hardware_reconfigured }}

[1LP][RFR] Use vddk v6_5 for provider vSphere 6.7 (nested) on test_alert_hardware_reconfigured

---

cfme/common/vm_views.py

Sometimes it happened to me that during filling of VM provision request, in the end, the `Submit` button was not _actually_ clicked but the framework thought it was. Therefore it expected to see a flash message and failed with this:
> TimedOutError: Could not do wait for Flash Success at /home/jan/cfme_tests/integration_tests/cfme/common/vm.py:526 in time
So I added `ensure_page_safe` to `after_fill` for provisioning form. To be completely honest, I don't know if that's what's really needed. But it helps and I am not seeing the aforementioned problem any more.
What do you think, @mshriver?
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py::test_tag --long-running -vv}}

[1LP][RFR] Ensuring page safe after filling VM provisioning form

---

cfme/tests/ssui/test_ssui_myservice.py

{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_myservice_crud --use-provider vsphere67-nested -svvv }}
Due to this [1] bug I am replacing cost center 001 to 002 
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1646925

[1LP][RFR] Fix myservice ssui crud

---

cfme/cloud/flavor.py
cfme/cloud/keypairs.py
cfme/cloud/tenant.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py::test_tag_cloud_objects }}
fixed 
```
AttributeError: 'KeyPairCollection' object has no attribute 'all'
AttributeError: 'TenantCollection' object has no attribute 'all'
AttributeError: 'FlavorCollection' object has no attribute 'all'
```
that I introduced by fixing `test_tag_infra_objects tests` in #8144

[1LP][RFR] added all method for keypairs, tenant and flavor collections

---

cfme/tests/cloud_infra_common/test_tag_objects.py

{{ pytest: -v  cfme/tests/cloud_infra_common/test_tag_objects.py::test_tagvis_cloud_object --use-provider=complete }}
1. fixed indent for `test_tagvis_cloud_object` so it will be executed 
2. removed the line with `appliance.version < '5.9'` as 5.8 in the separate branch and is not supported in master
PRT will not pass until #8191 is merged

[RFR] fixed indent for test_tagvis_cloud_object and removed if for appliance.version < 5.8

---

cfme/services/myservice/ui.py

- Fix test
- As PR-https://github.com/ManageIQ/integration_tests/pull/8194 merged this wrong implementation fails. No need  of  `WaitTab`
```
>               view = navigate_to(obj, dest_name)
test_service_objects.py:147: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../../cfme_venv/lib/python2.7/site-packages/navmazing/__init__.py:123: in navigate
return nav(cls_or_obj, self, self.logger).go(0, *args, **kwargs)
../../../utils/appliance/implementations/ui.py:544: in go
self.check_for_badness(self.step, _tries, nav_args, *args, **kwargs)
../../../utils/appliance/implementations/ui.py:387: in check_for_badness
return fn(*args, **kwargs)
../../../services/myservice/ui.py:427: in step …
```

[1LP][RFR] Fix Myservice Details view tables implementation. 

---

cfme/utils/template/base.py
cfme/utils/template/gce.py

Added unzipping of manageiq images, which are for some reason zipped for scvmm, gce, hyperv and azure.
It also changes image_name to unzipped image and then removes zipped archived from system.
It works for EC2. Can't test on GCE.

[RFR] [NOTEST] Added unzipping of manageiq templates for ec2 and gce

---

cfme/tests/infrastructure/test_vm_ownership.py

This PR fixes `ScopeMismatch` error in `test_vm_ownership.py`.
Error: 
`ScopeMismatch: You tried to access the 'function' scoped fixture 'provider' with a 'module' scoped request object, involved factories
cfme/tests/infrastructure/test_vm_ownership.py:22:  def vm(request, provider, appliance)`
{{pytest: cfme/tests/infrastructure/test_vm_ownership.py::TestVmOwnershipRESTAPI --use-template-cache -sqvvv}}

[1LP][RFR]Fix ScopeMismatch Error

---

cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_compliance.py

__Fixing__ test_alert_hardware_reconfigured because the `vddk_url` fixture was not working properly. The BZ fixture introduced in #8203, needed a `forced_streams` argument. The test was previously being skipped. 
Also updating the `vddk_url()` functions in test_compliance and test_actions. 
{{ pytest: --use-provider vsphere67-nested --long-running cfme/tests/control/test_alerts.py::test_alert_hardware_reconfigured }}

[1LP][RFR] Update vddk_url() fixtures in test_compliance, test_actions, & test_alerts

---

cfme/infrastructure/cluster.py
cfme/infrastructure/datastore.py

- Fix my bad; replece `and`  by `or` :D. 
- I dont understand, why sometime we are not  getting `ems_id` for `host`? Adding workaround  for it by itteration  over available `hosts` attached to `datastore`.
```
>   datastore_db = {ds.name: ds.hosts[0]["ems_id"] for ds in datastores if ds.hosts}
E   KeyError: 'ems_id'
```
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_display[Datastore-virtualcenter-Single_entity]}}

[RFR] fix all method

---

cfme/intelligence/reports/reports.py
cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_crud.py
data/schedules_crud/basic01.yaml
data/schedules_report/daily.yaml
data/schedules_report/hourly.yaml
data/schedules_report/monthly.yaml
data/schedules_report/once.yaml
data/schedules_report/weekly.yaml

1. Add a new test `test_report_schedules_invalid_email` to test if invalid emails are checked for sanity while adding a schedule.
2. Add a `from_email` attribute to `Schedule` entity, `from_email` widget to `SchedulesFormCommon` and all the methods where it's required.
3. Add `from_email` to all the YAML files related to schedules.
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_report_schedules_invalid_email --use-template-cache -sqvvv}}

[1LP][RFR]New Test to validate emails in schedules and add a new attribute to `Schedule`

---

cfme/automate/explorer/method.py
cfme/tests/automate/test_vmware_methods.py

- This test was skipping because of ```Key Error``` while getting ```small_template``` of vSphere provider.
- Also fixed ```Assertion Error``` which is occurred while asserting flash message of data validation in ```MethodAddView```
{{ pytest: cfme/tests/automate/test_vmware_methods.py -k 'test_vmware_vimapi_hotadd_disk' --long-running --use-provider complete -v }}

[1LP][RFR] Fixed KeyError and AssertionError in inline automate method

---

cfme/intelligence/reports/widgets/__init__.py
cfme/tests/intelligence/reports/test_crud.py

{{ pytest: -v cfme/tests/intelligence/reports/test_crud.py::test_reportwidget_crud }}
1. fixed title comparison in is_displayed
2. but it fails due to BZ (there's description instead of title) - so `update` part will not be executed for 5.9 until BZ is verified
3. widget description instead of title is shown in the flash message after creation, added BZ for 5.10

[1LP][RFR] fixed is_displayed for BaseEditDashboardWidgetView and added BZ

---

cfme/base/ui.py
cfme/tests/configure/test_database_ui.py

{{ pytest: -v cfme/tests/configure/test_database_ui.py::test_configure_vmdb_last_start_time }}
1. added properties table, it fixed `test_configure_vmdb_last_start_time`
2. removed `uncollectif` as 5.8 tests are in separate branch

[1LP][RFR] added properties table for vmdb summary

---

cfme/automate/explorer/method.py
cfme/base/login.py
cfme/base/ssui.py
cfme/base/ui.py
cfme/configure/configuration/server_settings.py
cfme/intelligence/reports/schedules.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

Many views have their own xpaths for FlashMessages. We need to unify that. 
Besides that there are flash messages stored in their own flash_text_div block in hammer. This also has to be sorted out
REQUIRES: https://github.com/RedHatQE/widgetastic.patternfly/pull/76
{{ pytest: cfme/tests/infrastructure/test_providers.py cfme/tests/automate/test_domain.py --long-running }}

[1LP][RFR] unifying flash message xpaths and fixing issue in hammer

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/services/myservice/ui.py
cfme/services/service_catalogs/ui.py

where provider dropdown appears with some timeout
{{pytest: --long-running --use-template-cache --use-provider=azure -k test_provision_stack cfme/tests/services/test_provision_stack.py}}

[1LP][RFR] Fix fill for orchestration catalog item view 

---

cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

1. Add one more asserting statement to all the test cases, which checks the value of `default items per page` in the paginator on a particular page.
2. Add one more value(5) to the `value` fixture.
{{pytest: cfme/tests/configure -k "page_per_item" --use-template-cache -sqvvvv}}

[WIPTEST]Mark test cases with blockers and optimize the test cases

---

cfme/tests/configure/test_log_depot_operation.py

1. added check for models and dialogs (new feature introduced in 5.10)
2. During testing I saw some failures for ansible logs, so it's different if we're looking at the file named "Archive..." or "Current...".

[RFR] added check for models and dialogs in log collection

---

cfme/configure/access_control/__init__.py

{{ pytest: cfme/tests/configure/test_access_control.py -k 'test_delete_default_group or test_edit_default_group' -v }}
- While **deleting** or **editing** default group, configuration drop-down issue.
- Observations:
- ```Configuration``` drop-down is disabled in 5.10
-  ```Configuratio``` drop-down is enabled in 5.9 but both options **Edit this group**  and **Delete this group** are disabled.
Fixed Error:
```
>           raise DropdownDisabled('Dropdown "{}" is not enabled'.format(self.text))
E           DropdownDisabled: Dropdown "Configuration" is not enabled
../cfme_venv/lib/python2.7/site-packages/widgetastic_patternfly/__init__.py:1538: DropdownDisabled
DropdownDisabled
Dropdown "Configuration" is not enabled
```

[1LP][RFR] Fixed configuration DropdownDisabled issue

---

cfme/tests/infrastructure/test_vm_power_control.py

- This PR fixes the **power** drop-down button issue on archived vm's details page.
- Observations:
- 5.9 - The power button option on archived VM's detail page is not present.
- 5.10 - The power button option on VM's detail page is present, but it's disabled. 
{{ pytest: cfme/tests/infrastructure/test_vm_power_control.py::test_no_power_controls_on_archived_vm --use-provider vsphere67-nested --long-running }}

[1LP][RFR] Fixed power option button is_displayed on archived vms details page

---

cfme/cloud/instance/__init__.py
cfme/configure/configuration/region_settings.py
cfme/tests/cloud/test_tag_mapping.py
cfme/tests/test_manual.py

{{ pytest: -v cfme/tests/cloud/test_tag_mapping.py::test_tag_mapping_azure_instances --use-provider=complete }}
Here I automated the manual test `test_tag_mapping_azure_instances`. 
I'm planning to expand the tag mapping testing later.

[1LP][RFR] new test_tag_mapping_azure_instances

---

cfme/cloud/instance/image.py
cfme/tests/test_rest.py

1. Add 19 new collections introduced with 5.10
2. Fix few typos
{{pytest: cfme/tests/test_rest.py -k "test_query_simple_collections or test_collections_actions or test_query_with_api_version" --use-template-cache -sqvvv }}

[1LP][RFR]Add new collections to rest test cases and fix few typos

---

cfme/configure/access_control/__init__.py

- This PR fixes the Assertion Error while creating new group with blank description. 
{{ pytest: cfme/tests/configure/test_access_control.py -k 'test_group_description_required_error_validation' -v }}
Fixed Error:
```
>           group_collection.create(description=None, role='EvmRole-approver')
E           AssertionError: Pattern 'Description can't be blank' not found in 'Could not do function <lambda>() at /var/ci/workspace/downstream-510z-rc/cfme_venv/lib/python2.7/site-packages/widgetastic/widget/base.py:493 in time'
cfme/tests/configure/test_access_control.py:471: AssertionError
AssertionError
Pattern 'Description can't be blank' not found in 'Could not do function <lambda>() at /var/ci/workspace/downstream-510z-rc/cfme_venv/lib/python2.7/site-packages/widgetastic/widget/base.py:493 …
```

[1LP][RFR] Fixed assertion error while creating  new group

---

cfme/cloud/tenant.py
cfme/fixtures/nuage.py
cfme/networks/__init__.py
cfme/networks/provider/__init__.py
cfme/networks/provider/nuage.py
cfme/tests/networks/nuage/test_inventory.py

This test creates sandbox with Nuage cloud tenant and its entities. We then navigate to Cloud tenant (which we created in previous step) through provider, where we compare UI stats with sandbox stats.
We also extended fixture for nuage sandbox and made it 'module' scoped which will help us with the future inventory tests.
\cc @miha-plesko

[1LP][WIPTEST] Add test for validation of Nuage Cloud Tenant inventory

---

cfme/base/__init__.py
cfme/base/ui.py
cfme/utils/appliance/__init__.py

The appliance name should be a property, not an attribute, as it must be fetched from the appliance.
I did some searching through the framework, but did not find any uses of the appliance rename, or of its name attribute directly, where the property is not preferred.

[1LP][RFR] Update appliance name

---

cfme/tests/infrastructure/test_vm_power_control.py

- BZ - [1592430](https://bugzilla.redhat.com/show_bug.cgi?id=1592430) is already verified. hence removed.
- BZ - [1659340](https://bugzilla.redhat.com/show_bug.cgi?id=1659340) is reproducible on 5.10z and 5.9z. Hence test ```test_archived_vm_status``` is failing for rhv provider.
- BZ -  [1571830](https://bugzilla.redhat.com/show_bug.cgi?id=1571830) is not yet fixed. Also it is now reproducible on 5.10z. hence test ```test_guest_os_reset``` is failing for rhv provider.
- BZ - [1571895](https://bugzilla.redhat.com/show_bug.cgi?id=1571895) not yet fixed. And reproducible on 5.10 as well.
{{ pytest: cfme/tests/infrastructure/test_vm_power_control.py -k 'test_guest_os_reset or test_archived_vm_status or test_guest_os_shutdown' --long-running -v }}

[1LP][RFR] This PR blocks the test cases because of BZs

---

cfme/tests/intelligence/chargeback/test_resource_allocation.py

{{pytest: cfme/tests/intelligence/chargeback/test_resource_allocation.py --long-running }}
PRT results:
59 : PASS
510 : PASS
The commit made through this PR fixes this failure .This failure occurs in both 59 and 510.
http://infra-trackerbot2.cfme2.lab.eng.rdu2.redhat.com/ostriz/dini/?stream_report=downstream-59z&source=jenkins#cfme/tests/intelligence/chargeback/test_resource_allocation.py/test_validate_alloc_memory_cost[azure]
The chargeback report generated through this automation contains only one row with chargeback costs(since we only have C&U data for an hour and daily chargeback reports have one row per hour).
The second row contains the VM name only.I have updated the tests so that we read the first row only .

[1LP][RFR] Read first row only from chargeback report

---

cfme/services/catalogs/orchestration_template.py
cfme/tests/services/test_orchestration_template.py

{{pytest: cfme/tests/services/test_orchestration_template.py -k 'test_duplicated_content_error_validation'   -vvv}}

[RFR]Fixed services orchestration template

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

Seeing some cost comparison failures, DRYing the cost comparison functions in chargeback tests.
Ultimately this isn't resolving the failing comparisons between the chargeback reports and estimations. @nachandr is looking into these failures, which are occurring in PRT.
{{ pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider complete --long-running }}

[1LP][RFR] Update validate_chargeback_report cost comparisons

---

cfme/tests/intelligence/reports/test_validate_chargeback_report.py

The code changes through this PR re-enable server roles which were disabled as part of the test setup.
{{ pytest: cfme/tests/intelligence/reports/test_validate_chargeback_report.py --use-provider complete --long-running }}

[RFR] Re-enable server roles for chargeback report validation tests

---

cfme/automate/explorer/method.py
cfme/tests/automate/test_domain.py

{{ pytest: cfme/tests/automate/test_domain.py -k 'test_domain_lock_unlock' -v }}
This PR fixes changed behavior of ```configuration``` dropdown button on different versions with respect to Locked domain.

[RFR] Fixed DropDown is_displayed/is_enabled issue

---

cfme/services/catalogs/orchestration_template.py

{{pytest: cfme/tests/services/test_orchestration_template.py -k 'test_duplicated_content_error_validation' -vvv}}

[RFR] Fix orchestration template flash assertion error

---

cfme/common/vm.py
cfme/infrastructure/datastore.py
cfme/infrastructure/provider/__init__.py
cfme/physical/provider/__init__.py
widgetastic_manageiq/__init__.py

Move the title check that's done in-code to the widget, collapse common view selector widget operations into single class.
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py --long-running --use-provider default -k test_host_relationships }}

[1LP][RFR] Update ViewSelector widgets and selected checks against title

---

cfme/automate/explorer/__init__.py
cfme/automate/explorer/klass.py
cfme/tests/networks/nuage/test_automation.py

With this commit we are testing nuage automation, more specifically we are testing if variables exist in Nuage class, which is navigated through automate explorer tree (ManageIQ/System/Event/EmsEvent/Nuage).
\cc @miha-plesko 
There was an issue because clicking happens at the middle of an element, and at the middle of an element there was a chevron for expanding tree. This chevron only expanded the tree not actually clicking on it. We made use of the buttons showed on the image to make the explorer larger so chevron is not exactly at the middle of the element.

[1LP][RFR] Ensure Nuage AE Class contains auth attributes in AE Schema

---

cfme/tests/services/test_orchestration_template.py

{{pytest: cfme/tests/services/test_orchestration_template.py -k 'test_name_required_error_validation_orch_template' -vvv}}

[RFR]Adding Blocker BZ to orchestration template test

---

cfme/utils/appliance/__init__.py
cfme/utils/net.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
sprout/appliances/tasks.py

REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/350
with updating wrapanapi to 3.0, rhev ip started returning ipv6 until ipv4 was available. This ip isn't accessaible and isn't parsed well in appliance atm.
So, we need to wait for ipv4 and return appliance only then.

[1LP][RFR] ipv6 handing in sprout

---

cfme/tests/cloud_infra_common/test_cockpit_server.py

{{ pytest: cfme/tests/cloud_infra_common/test_cockpit_server.py::test_cockpit_server_role --use-provider vsphere67-nested -v }}

[1LP][RFR] Fix cockpit server role

---

cfme/control/explorer/actions.py

Fixed error:
```
>       assert view.is_displayed
E       AssertionError
cfme/control/explorer/actions.py:180: AssertionError
AssertionError
```
{{ pytest: cfme/tests/control/test_basic.py -k 'test_action_crud' --long-running }}

[RFR] Fixed is_displayed for ActionDetailsView

---

cfme/control/explorer/policy_profiles.py

Fixed error:
```
>       assert view.is_displayed
E       AssertionError
cfme/control/explorer/policy_profiles.py:99: AssertionError
AssertionError
```
{{ pytest: cfme/tests/control/test_basic.py -k 'test_policy_profile_crud' --long-running }}

[RFR] Fixed is_displayed for PolicyProfileDetailsView

---

cfme/automate/explorer/klass.py

Total 23 failures due to this issue. 
```
E           AssertionError: Pattern 'Name has already been taken' not found in ''Details' object has no attribute 'prerequisite_view''
```
{{pytest: cfme/tests/automate/test_class.py -sqvv}}

[RFR] resetter method not able to access prerequisite view

---

cfme/tests/automate/test_provisioning_dialogs.py

{{ pytest: cfme/tests/automate/test_provisioning_dialogs.py::test_provisioning_dialogs_sorting -v }}

[RFR] Blocking test provisioning dialogs

---

cfme/rest/gen_data.py

This PR brings the following changes which fixes failing test cases of `test_rest_services.py`:
1. Remove `VersionPicker` from `get_dialog_service_name` as no value is returned for `dialog_service_name` in the service_request options, rendering it useless.
2. Simply use `_regex_parse_name` method for now.
{{pytest:  cfme/tests/services/test_rest_services.py -k "test_user_item_order or test_order_single_catalog_item or test_order_catalog_bundle or test_user_item_order or test_order_multiple_catalog_item" --use-template-cache -sqvvvv --long-running -sqvvvv}}

[RFR] Fix failing rest service test case

---

cfme/tests/configure/test_access_control.py

Automating Multi-Tenancy Test Case  RHCF3-4653 - test_superadmin_tenant_admin_crud
{{ pytest: cfme/tests/configure/test_access_control.py::test_superadmin_tenant_admin_crud --use-template-cache }}

[1LP][RFR] Automating test_superadmin_tenant_admin_crud

---

cfme/networks/network_router.py
cfme/tests/networks/nuage/test_inventory.py

This test creates sandbox with Nuage cloud tenant and its entities. We then navigate to Cloud tenant's network routers through provider, where we compare UI stats with sandbox stats.
This PR depends on: https://github.com/ManageIQ/integration_tests/pull/8150
Please review 3rd commit as the first and the second one are related to other PRs.
\cc @miha-plesko

[1LP][RFR] Test network router details

---

cfme/fixtures/v2v.py
cfme/tests/v2v/test_v2v_migrations.py

{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider vsphere67-nested --use-provider rhv42 --provider-limit 2 -vvvv -k 'test_single_datastore_single_vm_migration[virtualcenter-6.7-rhevm-4.2-form_data_vm_obj_single_datastore0]'}}
1. __Fixing__ X because it is currently doing Y which is incorrect. It should be doing Z.
2. So changes in UI now gives conversion host warning if host is already been used. This happened multiple times and thus caused many timeouts in V2V. With changes we are setting all RHV hosts as a conversion host so it will not wait for particular host and proceeds without mentioned warning,

[1LP][RFR] Apply multi-conversion host setup to every rhv host

---

sprout/appliances/tasks.py

sync provider hw log is full of errors because it is triggered for disabled providers.

[1LP][RFR] fix sync_provider_hw task

---

cfme/tests/automate/test_service_dialog.py

{{ pytest: cfme/tests/automate/test_service_dialog.py::test_mandatory_entry_point_with_dynamic_element -v }}

[1LP][RFR]Adding a new dialog element entry point mandatory test

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
scripts/cleanup_old_vms.py

Rework the multiprocess structure in cleanup_old_vms to layer the process/thread use across providers, and to avoid two things:
1. failing to delete vms because of duplicate names
2. skipping deletion of vms with unknown creation dates
I've also removed the prompt, instead opting for a 'dry-run' kind of approach, leaving this as the default via keeping the --force arg.
Unfortunately `Pool.starmap`, is only python 3.

[1LP][RFR] Refactor cleanup_old_vms

---

cfme/configure/access_control/__init__.py
cfme/tests/services/test_service_rbac.py

{{pytest: --use-template-cache --use-provider=complete --long-running cfme/tests/services/test_service_rbac.py cfme/tests/webui/test_advanced_search.py}}
adding teardown steps to rbac tests because those screw up many other tests

[1LP][RFR] adding teardown to rbac tests

---

cfme/tests/pod/test_appliance_crud.py

If browser get's restarted in test, frameworks picks up default appliance instead of temporary one
{{pytest: --use-provider=cm-pod1 --long-running --use-template-cache -k test_crud_pod_appliance cfme/tests/pod/test_appliance_crud.py}}

[1LP][RFR] added workaround for temporary pod appliances

---

cfme/fixtures/events.py
cfme/fixtures/nelson.py
cfme/fixtures/ui_coverage.py
cfme/scripting/sprout.py
cfme/tests/cli/test_appliance_console.py
cfme/tests/cloud/test_cloud_events.py
cfme/tests/control/test_default_alerts.py
cfme/tests/intelligence/reports/test_crud.py
cfme/tests/intelligence/reports/test_menus.py
cfme/tests/intelligence/reports/test_reports_schedules.py
cfme/utils/appliance/__init__.py
scripts/matrix.py
sprout/appliances/migrations/0043_provider_provider_type.py
sprout/appliances/models.py

4.1 release was reverted, 4.2 is not yet available, 3.13 flagged as high severity because of code execution through load calls
Should not have any impact on the modified calls.

[1LP][RFR] Move all yaml.load calls to yaml.safe_load

---

cfme/tests/pod/test_appliance_crud.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

fixing db pod backup/restore test which sometimes fail because of interfering completed jobs
{{pytest --use-provider=cm-pod1 --use-template-cache --long-running -k test_pod_appliance_db_backup_restore cfme/tests/pod/test_appliance_crud.py}}
REQUIRES:
https://github.com/ManageIQ/wrapanapi/pull/352
https://github.com/ManageIQ/integration_tests/pull/8311

[NOTEST][RFR] some useful pod db/restore test fixes

---

cfme/tests/physical_infrastructure/test_redfish_physical_server_details.py

__Adding tests__ for feature Redfish physical infrastructure provider to test that pressing power, LED identification and lifecycle menu buttons of a pysical server details works. This functionality is implemented in Hammer.
Depends on:
* [#8234](https://github.com/ManageIQ/integration_tests/pull/8234) for the fix of flash message assertion
Related Bugzilla bugs:
* https://bugzilla.redhat.com/show_bug.cgi?id=1574816
* https://bugzilla.redhat.com/show_bug.cgi?id=1574817
* https://bugzilla.redhat.com/show_bug.cgi?id=1574818
* https://bugzilla.redhat.com/show_bug.cgi?id=1574820
* https://bugzilla.redhat.com/show_bug.cgi?id=1574821
/cc. @miha-plesko

[RFR] Testing Redfish physical server detail page's buttons

---

cfme/common/vm.py
cfme/common/vm_views.py
cfme/tests/cloud/test_quota.py

**Purpose or Intent**
- Adding test case related to ```project``` and ```child-tenant``` quota for cloud providers.
{{ pytest: cfme/tests/cloud/test_quota.py --long-running  --use-provider=azure -v }}
Note: Ref. PR: #7255

[1LP][RFR] Adding test cases for project and child quota for cloud providers

---

cfme/rest/gen_data.py
cfme/tests/cloud/test_providers.py
cfme/tests/configure/test_rest_access_control.py
cfme/tests/configure/test_tag.py
cfme/tests/configure/test_tag_category.py
cfme/tests/control/test_rest_control.py
cfme/tests/infrastructure/test_rest_automation_request.py
cfme/tests/infrastructure/test_rest_templates.py
cfme/tests/infrastructure/test_vm_ownership.py
cfme/tests/infrastructure/test_vm_rest.py
cfme/tests/infrastructure/test_vm_retirement_rest.py
cfme/tests/intelligence/test_chargeback.py
cfme/tests/services/test_generic_service_catalogs.py
cfme/tests/services/test_rest_services.py
cfme/tests/test_rest.py

1. Fix failing `TestConditionsRESTAPI`. `modifier` attribute is no longer supported in 5.10, so make changes related to that.
2. Fix failing `TestPoliciesRESTAPI` test.
3. Replace all `rest_api` arguments of functions with `appliance` and make corresponding changes to tests.
4. Fix `ScopeMismatchError` in test_tag.py.
{{ pytest: cfme/tests -k "test_user_item_order or test_edit_service or test_query_orchestration_templates_attributes or test_cloud_networks_query or test_query_tenant_attributes or test_query_role_attributes or test_query_group_attributes or test_query_user_attributes or test_assign_and_unassign_tag or test_query_condition_attributes or test_query_policy_attributes or test_query_request_attributes or test_create_categories or …

[1LP][RFR] Fix failing rest test cases and add blockers

---

cfme/services/myservice/ssui.py

{{ pytest: -v cfme/tests/ssui/test_ssui_myservice.py::test_service_start }}
Should be `LOWEST` as in `5.9` it's the dropdown, not kebab.
Fixes the error 
```
> view.power_operations.item_select(power)
E AttributeError: 'NoneType' object has no attribute 'item_select'
```

[1LP][RFR] fixed power_operations for test_service_start (ssui)

---

cfme/tests/infrastructure/test_vm_power_control.py

1. Removed `if` for `5.9` in first assertion as in `5.9.7.0` Power dropdown is not displayed (not just disabled)
2. The test fails at second assertion, that's due to BZ1634713, so I updated the blocker.
I didn't add the PRT as the test is skipped.

[1LP][RFR] updated BZ for templates power control and assertion for template grid

---

cfme/tests/automate/test_provisioning_dialogs.py

{{ pytest: cfme/tests/automate/test_provisioning_dialogs.py::test_provisioning_dialogs_sorting -v }}
https://bugzilla.redhat.com/show_bug.cgi?id=1662219#c2

[1LP][RFR] Uncollect Host Provisioning dialog test in 5.10

---

cfme/tests/control/test_rest_control.py
conf/polarion_tools.yaml

This PR brings the following change:
1. Add a new test, `test_create_invalid_policy` to check policy creation with invalid data. This test is created to cover BZ: [1435780](https://bugzilla.redhat.com/show_bug.cgi?id=1435780)
{{ pytest: cfme/tests/control/test_rest_control.py::TestPoliciesRESTAPI::test_create_invalid_policies --use-template-cache -sqvvvvv }}

[1LP][RFR] Add a new test to create policy with invalid data

---

cfme/tests/infrastructure/test_vm_rest.py
cfme/tests/services/test_rest_services.py
cfme/utils/rest.py

1. Add conditions to block certain subcollections in `test_service_query_attributes`.
BZ: [1663972](https://bugzilla.redhat.com/show_bug.cgi?id=1663972) - Internal Server Error when querying services attribute `reconfigure_dialog`
{{ pytest: cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_query_service_attributes cfme/tests/infrastructure/test_vm_rest.py::test_query_vm_attributes --use-template-cache -sqvvvv --long-running }}

[RFR] Add blocker to test_service_query_attributes

---

cfme/control/explorer/conditions.py
widgetastic_manageiq/expression_editor.py

__Fixing__ `expression_editor` as a workaround for [BZ 1664852](https://bugzilla.redhat.com/show_bug.cgi?id=1664852) and [BZ 1664886](https://bugzilla.redhat.com/show_bug.cgi?id=1664886). This bug is impacting automation by causing condition creation to fail -- which leaves a browser stuck on that view with no way to get off of it. For that reason, it is impacting many tests. 
Another issue is arising on CFME 5.10.0.31 when an expression is created with the field `Find`. So that this issue does not impact other automation we have allowed for `condition.update()` to click the `cancel` button if we hit a `TimedOutError`. A future PR will address the issue directly. 
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_modify_condition_expressio …

[RFR] Fix condition modify by adding a time.sleep(1) to get around BZ's 1664852 and 1664886

---

cfme/tests/automate/custom_button/test_infra_objects.py

{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_dialog[Datastores-virtualcenter] -v}}

[WIPTEST] CB: block dialog test for 5.9 as not backported

---

cfme/control/explorer/alerts.py
cfme/tests/control/test_basic.py
cfme/tests/control/test_bugs.py
widgetastic_manageiq/__init__.py

__1)__ __Adding view__ for the "Monitor->Alerts->Overview" page in CFME. This view is registered to the alert collection because they will only have content on them if an alert has fired on an appliance. 
__2)__ __Adding test__ to test basic functionality of this view/page.
This, in combination with PR #8235, provide representation of both of the pages on Monitor->Alerts.  
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_alerts_monitor_overview_page }}

[1LP][RFR] Add in a view for the Monitor->Alerts->Overview page

---

cfme/fixtures/nelson.py
cfme/fixtures/node_annotate.py
cfme/scripting/sprout.py
cfme/utils/ansible.py
cfme/utils/appliance/__init__.py
cfme/utils/smem_memory_monitor.py
sprout/appliances/models.py

yaml.dump() saves data with python extensions which cannot be parsed by safe_load()

[RFR] replace yaml.dump()->yaml.safe_dump()

---

cfme/utils/browser.py

it seems keepalive works right. So, this workaround should be removed if extended testing proves no errors
REQUIRES: 
https://github.com/RedHatQE/cfme_dockerfiles/pull/8
https://github.com/RedHatQE/cfme_dockerfiles/pull/9

[RFR] removing keep_alive = False workaround

---

cfme/fixtures/ansible_fixtures.py
cfme/fixtures/cli.py

{{pytest: cfme/tests/ssui/test_ssui_ansible_service.py::test_service_catalog_crud_ui -v --long-running}}

[1LP][RFR] Fix test service/ssui ansible 

---

cfme/automate/dialogs/dialog_element.py
cfme/tests/services/test_dialog_regex_validation_in_catalog.py

{{ pytest: cfme/tests/services/test_dialog_regex_validation_in_catalog.py::test_dialog_element_regex_validation -v }}

[1LP]RFR] Add new tests Service Dialog Elements with regex validation in catalog item

---

cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_rest.py

1. Add a blocker to `test_provision` and `test_provision_emails` that tests/requires VM provisioning via REST. Issue is related to vsphere65-nested provider.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1662638
{{pytest: cfme/tests/infrastructure/test_provisioning_rest.py::test_provision cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_emails cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_from_template_using_rest --use-provider=vsphere65-nested --use-template-cache -sqvvvv }}

[1LP][RFR]Add blocker to tests provisioning vsphere65 VM via REST

---

widgetastic_manageiq/__init__.py

- I was just debugging things for container custom button. As container objects using serach while navigation. I stuck on one place and found
Current `Serach` `is_displayed` pointing to `View` `is_displayed`
Example: fallowing condition always `True` as its pointing `view`. 
https://github.com/ManageIQ/integration_tests/blob/master/cfme/containers/pod.py#L111
{{pytest: cfme/tests/automate/custom_button/test_container_objects.py::test_custom_button_display -v --use-provider ocp-39-hawk}}
FIXES #8385

[RFR] is_displayed for Search

---

sprout/appliances/models.py

just wrong comparison rule -> "<=" instead of "<"

[RFR] sprout doesn't allow to request exact number of appliances according to quota

---

cfme/fixtures/authentication.py

This fixes numerous 'CandidateNotFound' errors for both 5.9 and 5.10.
The error:
> CandidateNotFound
> path: ('Zones', 'Zone: Default Zone (current)', 'Server:  [1] (current)'), message: Could not find the item CFME Region: Region 0 [0]/Zones/Zone: Default Zone (current)/Server:  [1] (current) in Boostrap tree settings_tree, cause: Was not found in Zone: Default Zone (current)
Cause:
During auth testing, evmserverd is restarted; after that, we wait for an UI to appear. What in fact does happen in automation is that the UI never disappears. The browser sits there and seems like the server never restarted. This causes appliance to behave unexpectedly when the automation tries to navigate or perform actions in UI.
The appliance does not logout the user after evmserverd restart. BZ in …

[1LP][RFR] Auth: add logout after evm restart

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/tests/cloud/test_tenant_quota.py

- This PR tests Tenant Quota in UI and SSUI by selecting default entry point(field_entry_point) while creating catalog item.
- Added new fixture:
- **set_default()**
- This modification applied on all tests which are creating **catalog item** from this file. 
- This fixture used to modify **field_entry_point**
- Some of the tests from this file do not require **field_entry_point** except new test -  ```test_service_cloud_tenant_quota_with_default_entry_point```
- **provider_type** while creating catalog item
- It is used to differentiate ``` field_entry_point``` for provider types because field_entry_point is different for **cloud** providers and **infra** providers.
{{ pytest: cfme/tests/cloud/test_tenant_quota.py -k 'test_service_cloud_tenant_quota_with_default_entry_point or …

[1LP][RFR] Quota Test For Cloud: Testing tenant quota via UI and SSUI 

---

cfme/common/vm_views.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_tag }}
`test_provision_with_tag[ec2]` was failing because `def _select_template` was looking for the template only on the first page and the template was not there.
There are tons of templates on ec2 provider, so some iteration is needed.

[1LP][RFR] _select template for all pages

---

cfme/control/explorer/conditions.py
widgetastic_manageiq/expression_editor.py

Making use of #8361 for conditions. The second and third commits to this PR are meant to address a `StaleElementReferenceException` that was occurring after an expression was entered into CFME 5.10. The second commit waits for a button to be displayed before clicking it. The third commit waits for the text to have changed in the expression after the fill is completed. 
__Fixes__ `cfme.tests.control.test_basic::test_modify_condition_expression`
{{ pytest: --long-running cfme/tests/control/test_basic.py::test_modify_condition_expression }}

[1LP][RFR] Update conditions to use wait keyword for create_view

---

cfme/base/ui.py
cfme/configure/configuration/diagnostics_settings.py
cfme/configure/configuration/server_settings.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

There is an issue in new appliances 5.9/5.10 appliances when server name is displayed wrongly.
This is temporary fix for tests which fail due to that issue.
REQUIRES: https://github.com/RedHatQE/widgetastic.core/pull/137
{{ pytest: --long-running --use-template-cache cfme/tests/integration/test_cfme_auth.py cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py cfme/tests/v2v/test_v2v_migrations_ui.py cfme/tests/services/test_service_rbac.py cfme/tests/configure/test_access_control.py cfme/tests/intelligence/reports/test_validate_chargeback_report.py }}

[1LP][RFR] workaround for server name in 5.10

---

cfme/base/ui.py
cfme/intelligence/reports/reports.py
cfme/intelligence/timelines.py
cfme/tests/intelligence/test_reports_with_timelines.py
cfme/tests/test_modules_importable.py

__Automating__ manual test cases `test_reports_with_timelines` for `cfme.tests.intelligence`
This requires two things: 
__1)__ Adding a new view for the `Cloud Intel -> Timelines` page, and registering this view both against the server in `cfme.base.ui`, and since the timeline will appear if a Custom report is made, against a report in `cfme.intelligence.reports`
__2)__ Since the default reports are quite long, I have added functionality to copy pre-defined reports in CFME. This is a new method in the `Report` object. 
{{ pytest: --long-running --use-provider vsphere6-nested cfme/tests/intelligence/test_reports_with_timelines.py }}

[1LP][RFR] Add in a CloudIntelTimelines View and automate manual test cases

---

cfme/fixtures/physical_switch.py
cfme/tests/physical_infrastructure/api/test_physical_server_api.py
cfme/tests/physical_infrastructure/test_physical_rack.py
cfme/tests/physical_infrastructure/ui/test_physical_overview.py
cfme/tests/physical_infrastructure/ui/test_physical_switch_list.py

physical infra tests were collecting when no provider was available, although they needed a provider to be present for the test and fixtures to work.
Updated fixtures to cleanly skip instead of raise IndexError when a provider doesn't have the necessary physical entities present.
Fixes one FixtureLookupError created by a method that wasn't decorated as a fixture.

[1LP][RFR] Update physical infrastructure test collection

---

cfme/services/catalogs/catalog_items/catalog_bundles.py

View changes have broken the create method's fill of the form. This is impacting ~35 tests, tried to pick one of the shorter ones.
@ganeshhubale please take a look as this is related to the view changes for the entry points in that view.
Not sure that this will completely fix the `create` method, but it should at least resolve the `AttributeError` triggered because of the invalid widget name.
{{ pytest: --long-running -vv --use-provider complete cfme/tests/services/test_catalog_item.py -k test_tagvis_catalog_bundle }}

[WIPTEST] Update catalogbundle View/Collection.create

---

cfme/services/catalogs/catalog.py

Catalog exists property throws "CandidateNotFound" Exception
This patch except the exception and return False Output
Closes #8405 
{{pytest: cfme/tests/services/test_service_rbac.py::test_service_rbac_catalog -v}}

[1LP][RFR] Fixing catalog exists property

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/services/myservice/ui.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_catalog_item.py
cfme/tests/services/test_myservice.py

Cleanup some old 5.8 stuff, move flash messages into CRUD test
Targeting a fix for the `VMDetails` nav destination, found a few small things along the way.

[1LP][RFR] Update CatalogItem and MyService

---

cfme/tests/pod/test_appliance_crud.py

{{ pytest: cfme/tests/pod/test_appliance_crud.py -k test_pod_appliance_basic_ipa_auth --use-provider cm-pod2 --long-running --use-template-cache }}

[WIPTEST] Update ApiException Import for podified appliance crud

---

cfme/tests/generic_objects/test_instances.py

__Fixing__ `test_generic_objects_tag_rest`.
Also adding in case components. 
{{ pytest: cfme/tests/generic_objects/test_instances.py::test_generic_objects_tag_rest }}

[RFR] Fix test_generic_objects_tag_rest by fixing fixtures

---

cfme/tests/configure/test_access_control.py

{{pytest: cfme/tests/configure/test_access_control.py::test_tenant_unique_automation_domain_name_on_parent_level  -v}}

[1LP][RFR]Automating test unique_automation_domain_name

---

cfme/services/catalogs/catalog_items/catalog_bundles.py

- This PR has improved catalog bundle's ```create``` method. 
- Now, three entry points: ```provisioning_entry_point, reconfigure_entry_point and retirement_entry_point``` can be filled with ```view.basic_info.fill```.
- Removed check: ```view.basic_info.provisioning_entry_point.value == ""``` because on the basic info page of catalog bundle; we are getting default value for ```provisioning_entry_point``` which is not ```""```. So this check will always return false.
- ```AttributeError``` occurred because of name changes of entry point ```widgets``` in ```BasicInfoForm``` view. This is fixed by #8407 
@mshriver I have updated ```create``` method of catalog bundle. Please take a look at it and let me know, if we need more changes in this PR.
{{ pytest: …

[RFR] Improved catalog bundle's 'create' method

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_class.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_domain_priority.py
cfme/tests/automate/test_git_import.py
cfme/tests/automate/test_instance.py
cfme/tests/automate/test_method.py
cfme/tests/automate/test_namespace.py
cfme/tests/automate/test_provisioning_dialogs.py
cfme/tests/automate/test_smoke.py
cfme/tests/automate/test_vmware_methods.py
cfme/tests/cloud/test_instance_power_control.py
cfme/tests/cloud_infra_common/test_power_control_manual.py
cfme/tests/cloud_infra_common/test_quota_manual.py
cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
cfme/tests/cloud_infra_common/test_relationships.py
cfme/tests/infrastructure/test_child_tenant.py
cfme/tests/infrastructure/test_quota.py
cfme/tests/infrastructure/test_quota_tagging.py
cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/services/test_catalog_item.py
cfme/tests/test_manual.py

**Purpose or Intent**
- Moved test cases related to automate, quota, power control  manuals to respective file with manual tag
- Deleted already automated manual tests
- Improved polarion tags
- Polarion refactoring: add assignee, casecomponent, initialEstimate and caseimportance wherever missing. Add setup, testSteps and expectedResults for manual testcases.
- Create new files ```automate/test_automate_manual.py```, ```cloud_infra_common/test_power_control_manual.py``` and ```cloud_infra_common/test_quota_manual.py```

[RFR][NOTEST] Distributed manual tests with manual tag

---

cfme/ansible_tower/explorer.py
cfme/ansible_tower/jobs.py
cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/host_aggregates.py
cfme/cloud/keypairs.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/common/host_views.py
cfme/common/physical_server_views.py
cfme/common/provider_views.py
cfme/containers/build.py
cfme/containers/provider/__init__.py
cfme/infrastructure/cluster.py
cfme/infrastructure/config_management.py
cfme/infrastructure/resource_pool.py
cfme/infrastructure/virtual_machines.py
cfme/networks/views.py
cfme/storage/object_store_container.py
cfme/storage/object_store_object.py
cfme/storage/volume.py
cfme/storage/volume_backup.py
cfme/storage/volume_snapshot.py
cfme/tests/webui/test_advanced_search.py

Extending test_advanced_search parametrized tests.
Added filter crud test for non global filters:
1) Creates filter
2) Checks whether filter was created
3) Changes first expression element value
4) Checks whether first expression element value was changed
5) Deletes filter
6) Checks whether My Filters Accordion disappeared or filter was deleted
There are still many things which are not working correctly:
1) I need uncollectif specifically for this test, but I also need global uncollectif working - probably add to global uncollectif to uncollect only when this test is executed.
2) There is change in naming for Job Templates in 5.10. VersionPick didn't work with changing these parameters so I had to add parameters for both 5.9 and 5.10 and then uncollect them depending on appliance version. …

[RFR]Added crud test for non global filters

---

cfme/fixtures/ansible_fixtures.py
cfme/services/catalogs/catalog_items/__init__.py
cfme/services/catalogs/catalog_items/ansible_catalog_items.py
cfme/tests/ansible/test_embedded_ansible_services.py

PRT run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k 'test_service_ansible_playbook_available or test_service_ansible_playbook_tagging or test_service_ansible_playbook_negative or test_service_ansible_playbook_bundle or test_service_ansible_playbook_provision_in_requests or test_service_ansible_playbook_confirm or test_service_ansible_playbook_order_retire' -qsvvvv --long-running }}

[1LP][WIPTEST] This will fix embedded_ansible_services tests

---

cfme/tests/networks/test_sdn_downloads.py

As tests were fixed for 5.10 these uncollectifs are not needed anymore.
They were not working anyway.
juwatts:
{{ pytest: cfme/tests/networks/test_sdn_downloads.py --use-provider complete }}

[1LP][RFR] Deleted obsolete uncollectifs for sdn_downloads tests

---

cfme/containers/project.py

sometimes tests fail because cfme gets logged off when some pod is restarted 
{{pytest --use-provider=cm-pod2 --use-template-cache --long-running -k test_pod_appliance_db_backup_restore cfme/tests/pod/test_appliance_crud.py}}

[RFR] tiny fixes necessary for pod tests

---

cfme/automate/explorer/__init__.py
cfme/automate/explorer/domain.py
cfme/automate/explorer/method.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_method.py

{{ pytest: cfme/tests/automate -k 'test_method_crud or test_domain_lock_unlock or test_domain_cannot_delete_builtin or test_domain_cannot_edit_builtin or test_priority or test_automate_method_inputs_crud' -v }}
Fixed Error:
```
>           raise TimedOutError("Could not do {} at {}:{} in time".format(message, filename, line_no))
E           TimedOutError: Could not do Waiting for view [MethodEditView] to display at /var/ci/workspace/downstream-59z-tests-master/integration_tests/cfme/utils/appliance/implementations/ui.py:562 in time
../cfme_venv/lib/python2.7/site-packages/wait_for/__init__.py:180: TimedOutError
TimedOutError
Could not do Waiting for view [MethodEditView] to display at /var/ci/workspace/downstream-59z-tests-master/integration_tests/cfme/utils/appliance/implementations/ui.py …
```

[1LP][RFR] Fixed is_displayed of MethodEditView

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/tests/automate/test_git_import.py

{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_domain_displayed_in_service -v }}
Fixed Error:
```
>       view.field_entry_point.fill("")
E       AttributeError: 'AddCatalogItemView' object has no attribute 'field_entry_point'
cfme/tests/automate/test_git_import.py:66: AttributeError
AttributeError
'AddCatalogItemView' object has no attribute 'field_entry_point'
```

[RFR] Fixed AttributeError for AddCatalogItemView

---

cfme/tests/cloud/test_cloud_timelines.py
widgetastic_manageiq/__init__.py

__Adding__ BZ blocker metadata for [BZ 1670474](https://bugzilla.redhat.com/show_bug.cgi?id=1670474) and [BZ 1670550](https://bugzilla.redhat.com/show_bug.cgi?id=1670550). These bugs are causing test failures for cloud timeline events. 
__Fixing__ `detailed_events` for 5.10, since the checkbox was replaced by a BootstrapSelect.
{{ pytest: --long-running --use-provider complete cfme/tests/cloud/test_cloud_timelines.py }}

[1LP][RFR] Add in blocker BZs and fix tests that can be fixed for cloud timelines

---

cfme/intelligence/reports/reports.py
widgetastic_manageiq/__init__.py

__Extending__ `ManageIQTree` such that it inherits `BootstrapTreeview` rather than being equivalent to it, this will allow us to define MIQ specific functions for the `BootstrapTreeview`s that are present in MIQ. 
I have modified the `currently_selected` property to be able to deal with trees that have more than one root. As a smoke test, I have modified the Reports Timeline view to use this method. 
{{ pytest: --long-running --use-provider vsphere6-nested cfme/tests/intelligence/test_reports_with_timelines.py }}

[1LP][RFR] Allow currently_selected to work with trees with multiple roots

---

cfme/infrastructure/virtual_machines.py
widgetastic_manageiq/__init__.py

This is a fix for snapshot memory checkbox in appliance version 5.10 and above.
The original checkbox from 5.9 has been replaced by a something that looks like a BootstrapSwitch, but that is only a decoy. The Wigetastic BootstrapSwitch cannot be used here, the layout of divs is different and there is no input and no id. So I created new class SnapshotMemorySwitch inheriting from Widget with some basic operations defined, also with read and fill operations, so it works like any other widget.
I've put this into widgetastic_manageiq, since I suspect this kind of switch is used only in snapshots. There also exist other examples of kind-of-a-BootstrapSwitch already in different parts of the framework.
This should fix all of the snapshot failures currently appearing in jenkins for 5.10.
{{ …

[1LP][RFR] Fix snapshot memory checkbox for 5.10

---

cfme/common/__init__.py
cfme/containers/project.py
cfme/containers/provider/__init__.py
cfme/tests/containers/test_tags.py

Added the ability to add tags from the dashboard view. Default functionality has remained the same with this change. 
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py --use-provider complete }}

[1LP][RFR] New tagging updates

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
widgetastic_manageiq/__init__.py

This PR will bring in the most recent release of wt.patternfly (0.0.41). Since this release includes the `root_items` property, I have removed this from `ManageIQtree` in wt.manageiq.
{{ pytest: --long-running --use-provider vsphere6-nested cfme/tests/intelligence/test_reports_with_timelines.py }}

[1LP][RFR] Update wt.patternfly requirements to 0.0.41 and remove root_items

---

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py --use-provider complete --collect-only --long-running }}

[WIPTEST] Fix pytest_generate_tests for test_vm_instance_analysis

---

cfme/tests/configure/test_register_appliance.py

```
>       available fixtures: LineMatcher, _pytest, amazon_auth_provider, ansible_catalog, ansible_catalog_item, ansible_repository, ansible_service_catalog, anypython, app_creds, app_creds_modscope, appliance, appliance_police, appliance_preupdate, appliance_with_preset_time, appliance_with_providers, auth_provider, azure_provider, big_template, big_template_modscope, blocker, blockers, browser, bug, cache, candu_tag_vm, capfd, capfdbinary, caplog, capsys, capsysbinary, catalog, catalog_item, category, cfme_data, cfme_log_level_rails_debug, check_item_visibility, cloud_provider, collect_data, configure_auth, configure_console_vnc, configure_console_webmks, configure_websocket, configured_appliance, console_template, console_template_modscope, containers_provider, conversion_tags, …
```

[RFR] fixed FixtureLookupError bug

---

cfme/tests/cli/test_appliance_console.py

{{pytest: --use-template-cache --long-running cfme/tests/cli/test_appliance_console.py::test_appliance_console}}

[1LP][RFR] fix appliance test in 5.10

---

cfme/tests/generic_objects/test_definitions.py

Assigning `test_generic_object_definition_crud` to myself and removing a manual test case that is automated. 
{{ pytest: --long-running cfme/tests/generic_objects/test_definitions.py }}

[1LP][RFR][NOTEST] Reassign generic object test and remove manual test case

---

cfme/fixtures/cli.py

The propety of the provider class is not "dereferenced" when
accessed from class, so we get something like this in the skip message:
```
In [2]: VMwareProvider.type
Out[2]: <property at 0x7fc9090b0470>
```
which is not too helpful. It is better to use the type_name
{ py.test: cfme/tests/cli/test_appliance_console_db_restore.py::test_appliance_console_restore_pg_basebackup_replicated }

[1LP][RFR] Fix No providers available skip message.

---

cfme/intelligence/reports/reports.py
cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/infrastructure/test_provisioning_rest.py
cfme/tests/perf/workloads/test_provisioning.py

1. Unassign a test case: `test_provisioning`
2. Remove BZ meta - not required anymore.

[1LP][RFR][NOTEST] Remove BZ meta and unassign a test case

---

cfme/tests/cloud_infra_common/test_custom_attributes_rest.py

The BZ is mentioned in a comment (few lines above) so the information is not lost.
{{pytest: -v --long-running -k test_bad_section_ cfme/tests/cloud_infra_common/test_custom_attributes_rest.py}}

[WIPTEST] Remove unneeded BZ blockers from custom attributes tests

---

sprout/appliances/tasks.py

Wrong indentation created `UnboundLocalError`
This has been applied to production sprout already

[1LP][RFR] Fix poke_trackerbot sprout task

---

cfme/automate/__init__.py
cfme/automate/dialogs/__init__.py
cfme/automate/explorer/__init__.py
cfme/automate/provisioning_dialogs.py
cfme/base/ui.py

-  removed `automate_menu_name` which was used for navigation tree selection related to automate
{{pytest: cfme/tests/automate/ -k "test_class_crud or test_paginator or test_domain_crud or test_automate_git_domain_removed_from_disk or test_instance_crud or test_method_crud or test_namespace_crud or test_provisioning_dialog_crud or test_crud_service_dialog" -vv}}

[1LP][RFR] remove automate_menu_name

---

artifactor/__init__.py
artifactor/plugins/reporter.py

* By default artifactor uses the per_test reporting mechanism. This
allows it to continually overwrite test results in the same directory.
It's a little odd some times as it will leave orphaned artifacts,
but it makes it nice to successively run test reports.
* In order to allow easy bundling up of artifactor data, the report.html
file needs to be inside the run dir. This DIDN'T happen. The
report.html file was being saved at the artifact root. Meaning that,
although all the artifacts were in a separate dir, the report was
outside of that.
* These changes allow for a report_path to be passed down into the
reporting plugin. This makes it so that the system knows where to
store this report.

[1LP][WIPTEST] Changes to allow the report to be stored inside the artifact run dir

---

cfme/tests/cloud_infra_common/test_cockpit_server.py
cfme/tests/services/test_add_remove_vm_to_service.py
cfme/tests/services/test_cloud_service_catalogs.py
cfme/tests/services/test_different_dialogs_in_catalogs.py
cfme/tests/services/test_myservice.py
cfme/tests/services/test_provision_stack.py
cfme/tests/services/test_request.py
cfme/tests/services/test_service_catalogs.py
cfme/tests/services/test_service_manual_approval.py
cfme/tests/services/test_service_rbac.py
cfme/tests/ssui/test_ssui_dashboard.py
cfme/tests/ssui/test_ssui_myservice.py
cfme/tests/ssui/test_ssui_service_catalogs.py

{{pytest: --long-running  cfme/tests/cloud_infra_common/test_cockpit_server.py cfme/tests/services/test_add_remove_vm_to_service.py cfme/tests/services/test_cloud_service_catalogs.py cfme/tests/services/test_different_dialogs_in_catalogs.py cfme/tests/services/test_myservice.py cfme/tests/services/test_provision_stack.py cfme/tests/services/test_request.py cfme/tests/services/test_service_catalogs.py cfme/tests/services/test_service_manual_approval.py cfme/tests/services/test_service_rbac.py cfme/tests/ssui/test_ssui_dashboard.py cfme/tests/ssui/test_ssui_myservice.py cfme/tests/ssui/test_ssui_service_catalogs.py }}

[1LP][RFR] Adding ONE_PER_TYPE in ssui/services tests

---

cfme/tests/automate/custom_button/test_rest_custom_button.py

1. It is for consistency element for the reorder_imports tool (one import per line)
2. It will also greatly enhances merge-ability and removes merge conflict potential
Merged a PR while #8487 was open and didn't rebase.

[1LP][RFR]Fix import formatting in test_rest_custom_button

---

cfme/networks/__init__.py
cfme/networks/network_port.py
cfme/networks/subnet.py
cfme/networks/views.py
cfme/tests/networks/nuage/test_inventory.py

This test creates sandbox with Nuage cloud tenant and its entities. We then navigate to Network port through Nuage network provider, where we compare UI stats of ports with sandbox stats.
We test two different navigations, one navigates through L3 subnet, other one through L2 subnet.
This PR depends on: https://github.com/ManageIQ/integration_tests/pull/8169
Please review 4th commit as the first, second and third one are related to other PRs.
\cc @miha-plesko

[1LP][RFR] Test network port details

---

cfme/services/myservice/ui.py
cfme/tests/automate/custom_button/test_service_objects.py

{{ pytest: --long-running cfme/tests/services/test_myservice.py -vvv }}
Fixing `test_custom_button_expression` which was facing this error:
```
>           tag_table = entities.summary('Smart Management')
E           AttributeError: 'GridView' object has no attribute 'summary'
cfme/common/__init__.py:433: AttributeError
AttributeError
'GridView' object has no attribute 'summary'
```

[1LP][RFR] Fix for test_custom_button_expression by allowing tags to be read

---

cfme/tests/infrastructure/test_config_management.py

{{pytest: cfme/tests/infrastructure/test_config_management.py -k creds --use-provider ansible}}
PRT results:
59 - Passed
510 - Passed

[1LP][RFR] Fix invalid cred test for Ansible

---

cfme/tests/cloud/test_cloud_events.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt

__Fixing__ both tests in `test_cloud_events` for CFME 5.10. An error was occuring in the `cmp_func` for these events. The data returned for the event does not have `status` or `subStatus` in CFME 5.10. 
{{ pytest: --long-running --use-provider azure cfme/tests/cloud/test_cloud_events.py }}
Exception that was seen: 
```
2019-01-23 14:21:05,143 [I] [cfme] (events) [(BaseEvent(source=AZURE, full_data=will be ignored, event_type=networkSecurityGroups_write_EndRequest), 0), (BaseEvent(source=AZURE, full_data=will be ignored, event_type=networkSecurityGroups_delete_EndRequest), 0)] (cfme/utils/events.py:270)
2019-01-23 14:21:05,406 [I] [cfme] (rest-api) [RESTAPI] GET https://10.16.5.92/api/event_streams/919 {} …
```

[1LP][RFR] Fix test_cloud_events for changes in 5.10 vs 5.9

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/reports/test_reports_manual.py
cfme/tests/intelligence/reports/test_tenant_quota_reports.py

1. Automate test: `test_report_fullscreen_enabled`
2. Change the scope of fixtures
3. Remove unnecessary arguments from test function
4. Update polarion doc strings of tests.
5. Fix linting.
{{ pytest: cfme/tests/intelligence/reports/test_tenant_quota_reports.py --use-template-cache -sqvvvv}}

[1LP][RFR]New Test: test_report_fullscreen_enabled

---

cfme/configure/access_control/__init__.py
cfme/containers/image.py
cfme/containers/provider/__init__.py
cfme/tests/containers/test_cockpit.py
cfme/tests/containers/test_containers_smartstate_analysis.py
cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
cfme/tests/containers/test_labels.py
cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
cfme/tests/containers/test_provider_openscap_policy_attached.py
cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
cfme/tests/containers/test_static_custom_attributes.py
cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py

Add a new nav_arg, force_nav, to force navigate to a view. 
{{ pytest: cfme/tests/containers/test_cockpit.py cfme/tests/containers/test_labels.py cfme/tests/containers/test_manageiq_ansible_custom_attributes.py cfme/tests/containers/test_static_custom_attributes.py --use-provider ocp-39-hawk }}

[1LP][RFR] New Navigate Key to Force Navigation and Remove Browser Refreshes

---

cfme/tests/cloud/test_quota.py
cfme/tests/cloud/test_quota_tagging.py
cfme/tests/cloud/test_tenant.py
cfme/tests/cloud/test_tenant_quota.py
cfme/tests/cloud_infra_common/test_discovery.py
cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
cfme/tests/cloud_infra_common/test_relationships.py
cfme/tests/infrastructure/test_child_tenant.py
cfme/tests/infrastructure/test_project_quota.py
cfme/tests/infrastructure/test_quota.py
cfme/tests/infrastructure/test_quota_tagging.py
cfme/tests/infrastructure/test_tenant_quota.py
cfme/tests/infrastructure/test_vm_ownership.py

- Adds 'tags:' wherever missing
- Updating polarion tags
- Removed deprecated code like imports, not used test arguments etc
- Updated email generating with faux factory
- Removed verified BZs
- Added 'setup_provider' as global fixture in quota test's file
- Removed 5.8 dependency
{{ pytest: cfme/tests/infrastructure/test_project_quota.py::test_project_quota_enforce_via_lifecycle_infra --use-provider=rhv41 --long-running -vv }}
Note: Running only one test case to see whether it is able to set up provider or not(Quota test cases are taking too much time to finish)

[1LP][RFR] This PR updates files for global fixture and removes depricated arguments

---

cfme/tests/cloud_infra_common/test_events.py
cfme/tests/control/test_alerts.py
cfme/tests/infrastructure/test_timelines.py

Adding `Metadata` for timelines tests so that they do not pickup vSphere-IMS providers. Also, fixing tests that were collecting against Kubevirt that shouldn't be. Some general cleanup of old BZs as well.  
Also including fixes for tests in `test_timelines.py`, these tests were failing due to a change in 5.10 and BZ 1670550. 
{{pytest: -v --long-running --color=yes --use-provider  complete cfme/tests/infrastructure/test_timelines.py }}

[1LP][WIPTEST] Do not collect kubevirt or vSphere-IMS providers

---

cfme/services/myservice/ui.py
cfme/tests/generic_objects/test_instances.py

Fix for `generic_objects` test that was impacted by #8460.
{{pytest: cfme/tests/generic_objects/test_instances.py::test_generic_objects_with_buttons_ui}

[RFR] Fix for test generic_buttons

---

cfme/tests/services/test_generic_service_catalogs.py

Creating bundles in bundle is not supported now
https://bugzilla.redhat.com/show_bug.cgi?id=1678368
{{pytest: cfme/tests/services/test_generic_service_catalogs.py -k test_bundles_in_bundle -v}}

[RFR] Fix service bundles in bundle test

---

cfme/fixtures/provider.py
cfme/tests/cloud_infra_common/test_discovery.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/storage/test_volume.py
cfme/tests/storage/test_volume_backup.py
cfme/tests/storage/test_volume_snapshot.py

Test markers were missing a required field that they were assuming would be there - `provisioning`
This was missing on a CFME provider that was not intended for general provisioning tests, and is not excluding that marker
The CFME yaml has also been updated to change test collection for CFME, but this doesn't impact MIQ testing.
The fixtures and test markers now explicitly state the assumed yaml fields they will be using for provisioning, and some KeyErrors are explcitily caught, just in case.
Labeling rc-regression-fix, other maintainers feel free to remove if you don't think that's appropriate. Over 50 tests failing with `KeyError` right now in our `complete` provider collection because of these test modules.
I don't expect the PRT run to be clean, this should prevent ~40 tests from …

[1LP][RFR] Update tests and fixtures to resolve KeyError on yaml keyword

---

cfme/storage/object_store_container.py

failing because table with entities isn't displayed yet
{{pytest: --use-template-cache --long-running --use-provider=rhos13 cfme/tests/storage/test_object_store_container.py}}

[1LP][RFR] fixed storage container tests

---

cfme/automate/explorer/klass.py
cfme/fixtures/automate.py
cfme/test_framework/pytest_plugin.py
cfme/tests/automate/test_class.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_instance.py
cfme/tests/automate/test_method.py
cfme/tests/automate/test_namespace.py
cfme/tests/automate/test_smoke.py
cfme/tests/automate/test_vmware_methods.py

- Added global fixtures for automate
- ```domain``` : This fixture used to create automate domain - Datastore/Domain
- ```namespace```: This fixture used to create automate namespace - Datastore/Domain/Namespace
- ```class```: This fixture used to create automate class - Datastore/Domain/Namespace/Class
- Removed deprecated code from tests
- Removed less than ```5.9``` dependency
- Used global fixtures in automate tests
Note: Running the test cases which uses newly added global fixtures
{{ pytest: cfme/tests/automate/ -k "test_duplicate_domain_disallowed or test_domain_edit_enabled or test_class_crud or test_schema_crud or test_schema_duplicate_field_disallowed or test_duplicate_class_disallowed or test_same_class_name_different_namespace or test_class_display_name_unset_from_ui or …

[1LP][RFR] Adding global fixtures and formatting tests according to it

---

cfme/tests/infrastructure/test_snapshot.py

This is a fix for snapshot tests.
Something has changed in the framework and ScopeMismatch errors started to appear. Solved by changing scope from module to function.
{{ pytest: -v --long-running cfme/tests/infrastructure/test_snapshot.py --use-provider vsphere65-nested }}

[1LP][RFR] Fix scopes for snapshot tests

---

cfme/tests/infrastructure/test_vm_reconfigure.py

{{ pytest: -v cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_hw_hot  --long-running }}
Fixed the error
```
ScopeMismatch: You tried to access the 'function' scoped fixture 'provider' with a 'module' scoped request object, involved factories
cfme/fixtures/provider.py:283: def setup_provider_modscope(request, provider)
../.cfme/lib/python2.7/site-packages/_pytest/fixtures.py:242: def get_direct_param_fixture_func(request)
```

[RFR] fixed fixture scope mismatch

---

cfme/tests/intelligence/chargeback/test_resource_allocation.py

Not looking for complete test passing, just fixing the UnboundLocalError that was happening in 59z because this BZ was being forced. The BZ is closed/fixed in 59z and 510z, so I removed it. Bad pattern was causing UnboundLocal, pattern removed.

[RFR] Fix UnboundLocalError in test_resource_allocation

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_class.py

- Adding test case for checking schema creation without providing 'Type'
- This test case is related to [BZ:1365442](https://bugzilla.redhat.com/show_bug.cgi?id=1365442) 
{{ pytest: cfme/tests/automate/test_class.py -k 'test_automate_schema_field_without_type' -vv }}

[1LP][RFR] New test for automate: Checking schema creation without 'Type'

---

cfme/tests/configure/test_default_filters.py
cfme/tests/configure/test_default_views_cloud.py
cfme/tests/configure/test_default_views_infra.py
cfme/tests/configure/test_landing_page.py
cfme/tests/configure/test_timeprofile.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

1. Automate test: `test_change_truncate_long_text_save_button_enabled`
2. Add `settings` tag to related test cases.
{{ pytest: cfme/tests/configure/test_visual_infra.py::test_change_truncate_long_text_save_button_enabled --use-template-cache -sqvvv }}

[1LP][RFR] Automate test case: test_change_truncate_long_text_save_button_enabled

---

cfme/cloud/provider/openstack.py
cfme/common/provider.py

Changes that have been integrated from @mkoura's PR #6476:
1. Add `tenant_mapping_enabled` attribute while using create_rest method.
2. Add `_fill_amqp_endpoint_dicts`.
Other Changes:
1. Modify `_fill_rsa_endpoint_dicts` to take `rsa_keypair` endpoints if they exist, even if they're not accessible directly.
{{ pytest: cfme/tests -k "test_cloud_provider_crud or test_create_provider" --use-provider={osp13-ims,rhos13} --use-template-cache -sqvvvv }}

[1LP][RFR] modify fill_rsa_endpoint method and add tenant_mapping options in provider create_rest method

---

cfme/infrastructure/virtual_machines.py

{{ pytest: -v cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot --long-running }}
According to the fix mentioned here https://bugzilla.redhat.com/show_bug.cgi?id=1561618#c6
"Active VM" is always the active snapshot, so instead of
before:
it looks like:

[1LP][RFR] fixed active snapshot detection for RHEV

---

cfme/services/catalogs/catalog.py

is_displayed for catalog all page returns True even if the view is on Add catalog page. This patch will fix the issue.
Closes #8532
{{pytest: cfme/tests/services/test_catalog.py::test_catalog_crud -v}}

Updating is_displayed for catalog all page

---

cfme/fixtures/parallelizer/__init__.py
cfme/markers/env_markers/provider.py

fixing grouping tests by provider in order to speed up parallelized testing.
It turned out that provider "supportability" + DataProvider changes broke grouping tests by providers.
this PR means to fix this grouping issue.

[1LP][RFR] fix grouping tests by provider in test paralellizer

---

cfme/tests/test_manual.py

This test case is automated by https://github.com/ManageIQ/integration_tests/blob/387e9235a8659974138b0df4b5dfbc491c29410e/cfme/tests/cloud/test_cloud_timelines.py#L349

[RFR] remove manual case test_diagnostic_timelines

---

cfme/services/service_catalogs/ui.py
cfme/tests/services/test_cloud_service_catalogs.py

{{ pytest: -v cfme/tests/services/test_provision_stack.py::test_provision_stack[azure]  --use-provider=complete }}
This is the fix for the error
```
TimedOutError: Could not do function <lambda>() at /var/ci/workspace/downstream-510z-tests-master-extcloud/cfme_venv/lib/python2.7/site-packages/widgetastic/widget/base.py:494 in time
../cfme_venv/lib/python2.7/site-packages/wait_for/__init__.py:180: TimedOutError
TimedOutError
Could not do function <lambda>() at /var/ci/workspace/downstream-510z-tests-master-extcloud/cfme_venv/lib/python2.7/site-packages/widgetastic/widget/base.py:494 in time
```
The button is always displayed, but is not always enabled, like here
Also added block for `5.9` instance type, because it's written in lowercase

[1LP][RFR] added wait_for the Submit button to be enabled

---

cfme/roles.py
cfme/tests/integration/test_aws_iam_auth_and_roles.py

This is a fix for test_aws_iam_auth_and_roles.py for 5.9.
Two things happening here:
1. Remove BZ blocker that caused skipping tests for 5.9. This BZ is CLOSED CURRENTRELEASE, no longer blocking execution of the tests.
2. Update the hardcoded roles to reflect actual navigation possibilities in 5.9.
Similar PR for 5.10 is #8530 
{{ pytest: -v --long-running cfme/tests/integration/test_aws_iam_auth_and_roles.py }}

[1LP][RFR] Update tree for aws rbac for 5.9

---

cfme/roles.py

This is a fix for test_aws_iam_auth_and_roles.py for 5.10
The navigation tree changed in 5.10 and the test was expecting roles that weren't available in our code. Roles are hardcoded, so I updated them to reflect the UI navigation possibilities for various roles. This fixes all test_group_roles errors for 5.10.
{{ pytest: -v --long-running cfme/tests/integration/test_aws_iam_auth_and_roles.py }}

[1LP][RFR] Update tree for aws rbac

---

cfme/tests/control/test_actions.py
cfme/tests/infrastructure/test_vm_clone.py

{{ pytest: --long-running cfme/tests/control/test_actions.py::test_action_cancel_clone cfme/tests/infrastructure/test_vm_clone.py::test_vm_clone}}

[1LP][RFR] clone dialog is broken. uncollecting tests until those are fixed

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/tests/cloud/test_tenant_quota.py

Fixed Error:
```
>           raise StaleElementReferenceException("Couldn't handle it")
E           StaleElementReferenceException: Message: Couldn't handle it
../cfme_venv/lib/python2.7/site-packages/widgetastic/utils.py:686: StaleElementReferenceException
StaleElementReferenceException
Message: Couldn't handle it
```
{{ pytest: cfme/tests/cloud/test_tenant_quota.py -k 'test_service_cloud_tenant_quota_with_default_entry_point' --use-provider=complete -v }}

[1LP][RFR] Fixed exception error while adding entry points

---

cfme/control/explorer/conditions.py
cfme/control/explorer/policies.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_basic.py
cfme/tests/control/test_bugs.py

Minor refactor to get rid of all of the fixtures of the following form: 
```
@pytest.fixture
def collection:
return appliance.collections.collection
```
from `test_alerts.py`, `test_basic.py`, and `test_bugs.py`. Also fixing a couple of views for policies by removing a BZ that has since been fixed. Fixing the test `test_delete_all_actions_from_compliance_policy`. Registering a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1683697) against condition creation, since this was causing test failures in `test_basic`. 
{{ pytest: --long-running cfme/tests/control/test_bugs.py::test_control_identical_descriptions }}

[1LP][RFR] Remove fixtured collections from control tests

---

cfme/tests/test_db_migrate.py
cfme/utils/appliance/__init__.py
cfme/utils/ssh.py

Start testing with 5.9 db backup.
juwatts:
{{ pytest: -v cfme/tests/test_db_migrate.py::test_db_migrate_replication[59]  --use-provider complete }}

[1LP][RFR] Add 5.9 to the test_db_migrate_replication

---

cfme/base/ui.py
cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_method.py

- This test case create schema which includes state machines
- Adding method for retry button and to execute it using 'State' machines
- Adding 'retry_button' to the 'Automatesimulation' view page
- Checking whether 'Retry' button is displayed after simulation
{{ pytest: cfme/tests/automate/test_method.py -k 'test_automate_simulate_retry' -v }}

[1LP][RFR] New test: Testing automate simulate 'Retry' button using state machines

---

cfme/common/vm_views.py
cfme/configure/settings.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

visual tests have been relied on data provided by NonJSEntities which was replaced with JSEntities long time ago. 
In addition visual configuration view widgets have had wrong ids.

[RFR] fixed nodata tests and visual configuration view

---

cfme/tests/control/test_compliance.py

also adding some polarion metadata
{{ pytest: --long-running --use-template-cache --color=yes --use-provider vsphere6-nested cfme/tests/control/test_compliance.py }}

[RFR] removing fixtured collections from test_compliance

---

cfme/tests/cli/test_appliance_update.py

Fix updates tests failing on auth error. Use the sprout_user_key from the cmdline.
{{py.test: --sprout-user-key sprout cfme/tests/cli/test_appliance_update.py::test_update_yum}}

[RFR]Fix updates

---

cfme/tests/infrastructure/test_timelines.py

Adding a blocker statement for [BZ 1687493](https://bugzilla.redhat.com/show_bug.cgi?id=1687493), so that the test will pass event if the Source VM is not listed on the event details. 
{{ pytest: --use-provider rhv42 --use-template-cache cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_create_event }}

[RFR] Add in a blocker statement for BZ 1687493

---

cfme/tests/control/test_basic.py
cfme/tests/control/test_import_policies.py

Removing the manual case `test_control_import_with_incorrect_schema` because this is automated by [`test_control_import_invalid_yaml_file`](https://github.com/ManageIQ/integration_tests/blob/5fbeb7a5f0903a9ddb998b57e6a68242a3f023cf/cfme/tests/control/test_import_policies.py#L41)
Also removing a fixtured collection in `test_import_policies.py`
{{ pytest: --use-template-cache cfme/tests/control/test_import_policies.py }}

[RFR] Remove manual control case

---

cfme/tests/configure/test_access_control.py

Automating manual test test_tenant_unique_catalog
{{pytest: cfme/tests/configure/test_access_control.py::test_tenant_unique_catalog -v}}

[1LP][RFR]Automating test_tenant_unique_catalog

---

cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py

There is notification drawer in both UI and SSUI. It was likely absent in SSUI earlier.
That drawer sometimes shows up what makes selenium loose focus or switch frames.
We decided to hide notification drawer until we really need it. 
As far as I'm concerned js code used in UI doesn't handle this case for the time being.
As for SSUI such code is absent at all.
This PR intends to sort out this issue with notification drawers.

[1LP][RFR] drawer isn't closed in both UI and SSUI 

---

widgetastic_manageiq/expression_editor.py

__Fixing__ `test_group_crud_with_tag` when deleting existing expressions.
The `wait_for` in question here checks also for `self.expression_text != "<new element>"`. When deleting expressions during testing, we use:
```
while self.any_expression_present():
self.select_first_expression()
self.click_remove()
```
so we are deleting expression after expression and in the end, we are left with `"<new element>"` string. The condition that I removed from here would never be True for this case.
{{ pytest: -v --long-running cfme/tests/control/test_basic.py::test_modify_condition_expression }}

[RFR] Remove condition to fix deleting expressions

---

cfme/configure/access_control/__init__.py

__Fixing__ `test_group_description_required_error_validation`, when creating a group without description.
I simply moved `create_view` below error checking, that was already present in the file:
```
try:
view.flash.assert_message(flash_blocked_msg)
raise RBACOperationBlocked(flash_blocked_msg)
except AssertionError:
pass
```
Nothing else changed.
{{ pytest: -v --long-running cfme/tests/configure/test_access_control.py --use-provider vsphere65-nested -k test_group_description_required_error_validation }}

[1LP][RFR] Move create_view to enable error check

---

cfme/tests/test_manual.py

Removing Test test_superadmin_child_tenant_delete_parent_catalog from test_manual.py as this test is already automated and added in test_access_control.py

[1LP][RFR][NOTEST] Removing the test as it is already automated

---

cfme/tests/networks/test_provision_to_virtual_network.py

There's another BZ that blocks the execution of this test

[1LP][RFR][NOTEST] updated BZ for test_provision_vm_to_virtual_network

---

cfme/rest/gen_data.py
cfme/tests/configure/test_rest_access_control.py
cfme/tests/intelligence/reports/test_reports.py

1.  Create a separate file `intelligence/reports/test_reports.py` which includes all functional test cases of reports, this is a part of future refactoring of reports code.
2. Automate a test case: test_non_admin_user_reports_access_rest
3. Modify `users`, `roles`, `groups`, and `tenants` function to accept kwargs
4. Remove functions related to deprecated features.
5. Modify test cases using these functions to work well.
{{ pytest: cfme/tests/configure/test_rest_access_control.py cfme/tests/intelligence/reports/test_reports.py --use-template-cache -sqvvvv }}

[1LP][RFR] Automate test case: test_non_admin_user_reports_access_rest AND modify gen_data access_control functions

---

cfme/tests/optimize/test_bottlenecks.py

For the bottleneck tests, the current DB on the appliance is dropped and a DB with bottleneck events is restored.
The bottleneck tests were failing in 510 because EVM server wouldn't start after restoring a DB with the bottleneck events.
When you load a database from an older version of the application,  you always need to run migrations.
So,through this PR, I've added the extra DB migration step after loading the DB.
https://bugzilla.redhat.com/show_bug.cgi?id=1643250
PRT results:
59 - PASSED
510 - PASSEd

[1LP][RFR] Bottleneck tests : Add DB migration step after loading DB from an older version of CFME

---

cfme/base/ui.py
cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/instance/__init__.py
cfme/cloud/instance/image.py
cfme/cloud/keypairs.py
cfme/cloud/security_groups.py
cfme/cloud/tenant.py
cfme/common/vm.py
cfme/common/vm_views.py
cfme/configure/about.py
cfme/exceptions.py
cfme/generic_objects/definition/ui.py
cfme/infrastructure/deployment_roles.py
cfme/infrastructure/resource_pool.py
cfme/infrastructure/virtual_machines.py
cfme/modeling/base.py
cfme/storage/volume.py
cfme/storage/volume_backup.py
cfme/storage/volume_snapshot.py
cfme/storage/volume_type.py
cfme/tests/cloud_infra_common/test_tag_visibility.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/openstack/infrastructure/test_host_lifecycle.py

1. Use a common `ItemNotFound` exception when an item is not found.
2. Removed Exceptions - `ElementOrBlockNotFound`,  `VmOrInstanceNotFound`, `VmNotFound`, `InstanceNotFound`, `ImageNotFound`, `TenantNotFound`, `TenantNotFound`, `HostNotFound`,  `FlavorNotFound`, `SecurityGroupsNotFound`, `ResourcePoolNotFound`, `AvailabilityZoneNotFound`, `VolumeNotFoundError`, `VolumeTypeNotFoundError`, `ZoneNotFound`,  , `RoleNotFound`, `BackupNotFoundError`, `SnapshotNotFoundError`.
2. Remove unused exceptions such as - `AccordionItemNotFound`, `ScheduleNotFound`, `StackNotFound`, `ClusterNotFound`, `StorageManagerNotFound`.
3. Replace almost all exceptions similar to `ItemNotFound` exception with it. Some exceptions have not been changed since they might not be …

[1LP][RFR] Use a common exception ItemNotFound

---

cfme/utils/appliance/__init__.py

__Fixing__ `test_login_evm_group` errors for 5.10 when running with IPA.
From my testing, it seems that for whatever reason the process of setting up IPA authentication method takes more time in 5.10 than it takes in 5.9. This causes timeouts on some auth tests when running against 5.10.
The proposed solution is the easiest one, I just upped the timeout globally by 10 seconds. This seems to work.
{{ pytest: -v --long-running cfme/tests/integration/test_cfme_auth.py::test_login_evm_group[external-freeipa01-uid-ldapuser1] }}

[1LP][RFR] Increase IPA timeout

---

cfme/tests/configure/test_tag.py
cfme/tests/intelligence/reports/test_generate_report.py
cfme/tests/intelligence/reports/test_views.py

This PR brings the following change:
1. Separate `test_assign_and_unassign_tag` for cloud and infra providers since few collections work only with specific providers and supported only on specific appliance versions.
2. Minimize parametrization for `test_views.py` and `test_generate_reports.py` since it's not required.
{{ pytest: cfme/tests/configure/test_tag.py::TestTagsViaREST::test_assign_and_unassign_tag cfme/tests/intelligence/reports/test_views.py cfme/tests/intelligence/reports/test_generate_report.py --use-template-cache -sqvvv }}

[1LP][RFR] Separate test_assign_and_unassign_tag for different providers and minimize parametrization 

---

cfme/tests/configure/test_access_control.py

__Fixing__ `test_permissions_role_crud` for 5.10 and making it a bit nicer in 5.9.
The change here is use `_mk_role` instead of original `new_role`, reason being that we need to specify some product features to be enabled for testing user instead of having enabled everything, which is default.
Test is creating a role, group and a user with product features Configuration and Catalogs Explorer enabled, everything else is disabled. Then this user logs in and tries to perform role-related crud testing. Up until now, the role that this user creates had enabled all product features.
In 5.9, this is ok, because user can create role with permissions higher than he himself has. He however can't create group or new user with it. This means that it is secure, and this role testing PASSes.
In 5.10, …

[1LP][RFR] Use role with product features

---

cfme/intelligence/reports/reports.py
cfme/tests/intelligence/reports/test_tenant_quota_reports.py

1. Fix failing `test_queue_tenant_quota_reports` test
2. Use Uppercase for global variable `property_mapping`.
{{ pytest: cfme/tests/intelligence/reports/test_tenant_quota_reports.py --use-template-cache -sqvvv }}

[RFR] Fix failing test_tenant_quota_reports test

---

cfme/automate/buttons.py
cfme/automate/dialogs/service_dialogs.py
cfme/automate/explorer/domain.py
cfme/automate/explorer/instance.py
cfme/automate/explorer/klass.py
cfme/automate/explorer/method.py
cfme/automate/explorer/namespace.py
cfme/common/provider.py
cfme/control/explorer/actions.py
cfme/modeling/base.py
cfme/services/catalogs/catalog_items/__init__.py

1. Move `delete_if_exists` method to `BaseEntity`. The method raises a `NotImplementedError` if `delete` method has not been implemented for an entity.
2. Remove `delete_if_exists` from all other places.
{{ pytest: cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_display cfme/tests/automate/test_class.py::test_class_crud cfme/tests/automate/test_domain.py::test_domain_crud cfme/tests/automate/test_namespace.py::test_wrong_namespace_name cfme/tests/automate/test_service_dialog.py::test_checkbox_dialog_element cfme/tests/cloud/test_providers.py::test_add_cancelled_validation_cloud  --use-template-cache -sqvvvv }}

[1LP][RFR] Move `delete_if_exists` to BaseEntity

---

cfme/tests/control/test_compliance.py

Performing some maintenance for `test_compliance`. 
1) Adding policy `test_flag` so that these tests won't collect against the IMS provider
2) For vSphere 6.5, SSA is not working on hosts other than host-01. This is causing test failures for some of the tests in `test_compliance`. For now, we provision onto host-01 only, but we can remove this check once we know why SSA is failing for the other hosts. 
{{ pytest: --use-provider vsphere65-nested --use-template-cache cfme/tests/control/test_compliance.py::test_check_files cfme/tests/control/test_compliance.py::test_check_package_presence }}

[RFR] Fix collection test compliance

---

cfme/common/vm.py
cfme/tests/cloud_infra_common/test_html5_vm_console.py
cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/cloud_infra_common/test_vm_ownership.py
cfme/tests/infrastructure/test_vm_power_control.py
cfme/tests/infrastructure/test_webmks_console.py
cfme/tests/ssui/test_ssui_myservice.py

if one does:
```
In [1]: try:
...:     raise Exception("fff")
...: except Exception as e:
...:     print "Zde"
...:     raise e
...: 
Zde
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-8b4b63314306> in <module>()
3 except Exception as e:
4     print "Zde"
----> 5     raise e
Exception: fff
```
...then the traceback to the real exception raise line is lost,
as seen above. For re-raising the caught exception we can
use just the `raise` keyword. This makes sure the traceback is preserved:
```
In [1]: try:
...:     raise Exception("fff")
...: except Exception:
...:     print "Here"
...:     raise
...:
Here
-------------------------------------------------------------------- …
```

[1LP][RFR] Don't obscure the tracebacks.

---

cfme/services/requests.py
cfme/tests/infrastructure/test_tenant_quota.py

- To test Tenant Quota in UI and SSUI by selecting field entry points.
- Quota has to be checked if it is working with field entry points also.
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py -k 'test_service_infra_tenant_quota_with_default_entry_point' --use-provider=rhv42 -v }}
Note:
This test is depend on PR #7903

[1LP][RFR] Quota test for Infra: Testing tenant quota via UI and SSUI 

---

cfme/scripting/quickstart/__init__.py
cfme/scripting/quickstart/system.py

Add cli option to quickstart, making debuginfo an optional install
Update OS_NAME and OS_VERSION regex to be a bit more flexible, allowing for quotes around names/versions
Use VERSION_ID for OS_VERSION, since 'VERSION' field in os-release can contain things like 29 (workstation edition) instead of just 29
Tested with RHEL and Fedora os-release files
{{ pytest: cfme/scripting/tests/test_quickstart.py }}

[RFR] Update quickstart, OS_NAME and OS_VERSION, make debuginfo optional

---

cfme/configure/access_control/__init__.py
cfme/tests/integration/test_cfme_auth.py

__Fixing__ `test_login_retrieve_group` when working with non-ASCII characters in group description.
This applies to python version < 3.
If we want to work with unicode characters, there are two main problems:
1. How to get unicode character into our test without being escaped
2. How to work with unicode character in our code
For the first problem, as far as I can tell, we are loading our yamls with yaycl. This gets us `AttrDict` with strings. For authentication testing, there's `auth_data.yaml` that we are loading and then using in tests. We can specify unicode character in the yaml file like this: `SR-APP-EPM-Membre-\xe9`. The problem is that after loading this kind of string with yaycl, it escapes the character like so: `SR-APP-EPM-Membre-\\xe9`. It doesn't know that we want a unicode …

[1LP][RFR] Unicode hack for auth group

---

cfme/intelligence/reports/reports.py
cfme/intelligence/reports/saved.py

1. Add `tree_path` property for reports and saved_reports.
2. Add `delete_if_exists` method for reports, saved_reports and schedules.
3. Use `tree_path`in all `is_displayed` methods.
{{ pytest: cfme/tests/intelligence/test_reports_with_timelines.py cfme/tests/intelligence/reports/test_reports_schedules.py cfme/tests/intelligence/reports/test_crud.py cfme/tests/intelligence/reports/test_reports_schedules.py --use-template-cache -sqvvvv }}

[RFR]Add tree path in reports

---

cfme/tests/configure/test_workers.py

{{ pytest: -v cfme/tests/configure/test_workers.py::test_restart_workers }}
The test was skipped but the BZ was verified for `5.10` (in a clone of the mentioned BZ)

[RFR] removed a blocker for test_restart_workers

---

cfme/tests/test_csrf.py

{{ pytest: -v cfme/tests/test_csrf.py::test_csrf_post }}
The behavior has changed and in `5.10` you get logged out if the token has changed instead of the error page.
Please suggest what FA is that, I'm not really sure it should be mine.

[RFR] updated according to different behaviour in 5.10

---

cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
cfme/tests/intelligence/chargeback/test_resource_allocation.py

This test module wasn't updated with the PR bringing in compute/storage rate collection
May not see 100% pass on PRT, but I'm looking to resolve the TypeError that was occurring in the fixture.
```
E       TypeError: __init__() takes at least 3 arguments (3 given)
cfme/tests/intelligence/chargeback/test_resource_allocation.py:376: TypeError
TypeError
__init__() takes at least 3 arguments (3 given)
```
{{ pytest: --long-running cfme/tests/intelligence/chargeback/test_resource_allocation.py }}

[RFR] Fix chargeback/test_resource_allocation compute/storage rate creation

---

cfme/configure/access_control/__init__.py

__Fixing__ unicode errors in `test_login_retrieve_group`. This continues the work that has been started in PR #8606.
This PR is changing only one string and that's it. There's more interesting PR in cfme-qe-yamls that this PR depends on. When that gets merged, we should be finally green.
{{ pytest: -v --long-running cfme/tests/integration/test_cfme_auth.py -k test_login_retrieve_group }}

[1LP][WIPTEST] Add unicode format for string

---

cfme/configure/access_control/__init__.py
cfme/tests/integration/test_cfme_auth.py
widgetastic_manageiq/__init__.py

__Fixing__ `test_user_group_switching`.
I introduced unicode characters to auth testing, which broke this test that didn't expect it. This is the fix.
I had to make changes also to widgetastic_manageiq.
{{ pytest: -v --long-running cfme/tests/integration/test_cfme_auth.py -k test_user_group_switching }}

[1LP][WIPTEST] Fix unicode errors

---

cfme/tests/infrastructure/test_vm_reconfigure.py

This works with VMware, so only RHV needs to be blocked
{{ pytest: -v cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_disk_cold  --long-running }}

[1LP][RFR] blocker for test_vm_reconfig_add_remove_disk_cold

---

cfme/tests/services/test_catalog.py

Removing Test test_catalog_duplicate_name as its duplicate of this test https://github.com/ManageIQ/integration_tests/blob/c1d0d217ad297bff1e0dbde502a85a1195f23462/cfme/tests/configure/test_access_control.py#L1455

[1LP][RFR][NOTEST] Removing the duplicate test

---

cfme/tests/candu/test_host_graph.py

The hourly graph tests for disk metrics for RHV should be uncollected since RHV doesn't collect disk metrics for hosts.

[1LP][RFR] Uncollect RHV hourly disk graph tests

---

cfme/rest/gen_data.py
cfme/tests/configure/test_rest_access_control.py
cfme/tests/services/test_rest_services.py

1. Enhance `roles` to accept features.
2. Use `My Company` tenant by default if no tenant is explicitly provided in `groups` function.
3. Make corresponding changes to tests.
{{ pytest: cfme/tests/configure/test_rest_access_control.py cfme/tests/services/test_rest_services.py::TestServiceRequests --use-template-cache -sqvvvv --long-running }}

[1LP][RFR] Enhance gen_data functions

---

cfme/tests/cli/test_evmserverd.py
cfme/utils/ssh.py

index was too high, server list was empty
Tested locally in 5.9.9 and 5.10.2
{{ pytest: --long-running cfme/tests/cli/test_evmserverd.py }}

[1LP][RFR] Update SSHClient.status, evmserverd output processing

---

cfme/fixtures/appliance.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_alerts.py
cfme/tests/control/test_compliance.py

The fixture `configure_fleecing` was in 3 different spots in the control tests. I have decided that it deserves to be made a member of `cfme.fixtures.appliance`.
{{ pytest: --long-running --use-provider vsphere6-nested cfme/tests/control/test_actions.py::test_action_prevent_ssa  }}

[1LP][WIPTEST] Add in fleecing fixture to cfme.fixtures.appliance

---

cfme/tests/webui/test_rest.py

1. Add 2 new test cases:
1. `test_delete_advanced_search_filter_from_collection`
2. `test_delete_advanced_search_filter_from_detail`
{{ pytest: cfme/tests/webui/test_rest.py --use-template-cache -sqvvv }}

[1LP][RFR] Automate test: test_delete_advanced_search filter via REST

---

cfme/tests/intelligence/test_timelines_rss_removed.py

Creating a new test for this [RFE BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1672933). Designed to test this [PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/5271) on upstream builds. 
{{ pytest: --use-template-cache cfme/tests/intelligence/test_timelines_rss_removed.py }}

[1LP][RFR] New test: Include test cases to assert removal of RSS and Timelines pages

---

cfme/control/simulation.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_control_simulation.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt
widgetastic_manageiq/__init__.py

Automating `test_control_icons_simulation` and moving it into a new module. This requires some widgets to be added to the view for the Control->Simulation page, so I've done that. 
Depends on minor widgetastic.patternfly PRs [here](https://github.com/RedHatQE/widgetastic.patternfly/pull/85) and [here](https://github.com/RedHatQE/widgetastic.patternfly/pull/88) 
{{ pytest: --long-running --use-provider complete --use-template-cache cfme/tests/control/test_control_simulation.py }}

[1LP][WIPTEST] Automate test control icons simulation

---

cfme/tests/webui/test_general_ui.py

`test_breadcrumbs` exists only for containers, should be something more generic like `test_advanced_search_button_displayed`
{{pytest: --collect-only --use-template-cache --long-running --manual cfme/tests/webui/test_general_ui.py}}

[1LP][RFR] Added a test for breadcrumbs RFE

---

cfme/tests/configure/test_paginator.py

{{ pytest: -v cfme/tests/configure/test_paginator.py::test_paginator_details_page }}
200 and 500 are back! https://bugzilla.redhat.com/show_bug.cgi?id=1515952
I added this additional check in one test as this widget is the same in the whole UI.

[1LP][RFR] items per page in 5.11

---

cfme/storage/object_store_container.py
cfme/storage/object_store_object.py
cfme/tests/storage/test_object_store_container.py
cfme/tests/storage/test_object_store_object.py

Needs: https://github.com/ManageIQ/wrapanapi/pull/360
Most of time these test are skipping in absence of storage `container` or `object` so creating with `api` and trying to maintain single on OSP.
{{pytest: cfme/tests/storage/test_object_store_object.py cfme/tests/storage/test_object_store_container.py -v}}

[1LP][RFR] create osp container with wrapanapi

---

cfme/tests/infrastructure/test_host.py

{{pytest: --long-running --use-provider complete cfme/tests/infrastructure/test_host.py }}

[1LP][RFR] fix for tests which fail due to absent web_services credentials

---

cfme/tests/services/test_catalog_item.py

Removing test test_add_button_group as its duplicate of this test 
https://github.com/ManageIQ/integration_tests/blob/139bcd0b34892850c822bff6a1a9a6d0b6472d50/cfme/tests/automate/custom_button/test_catalog_custom_button.py#L9

[1LP][RFR]Removing the duplicate test add button group 

---

cfme/tests/v2v/test_migration_plan.py
cfme/v2v/infrastructure_mapping.py
cfme/v2v/migration_plans.py
entry_points.txt
widgetastic_manageiq/__init__.py

Migration Plan code refactoring .
juwatts:
{{ pytest: cfme/tests/v2v/test_migration_plan.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2   -vvvv --long-running}}

[1LP][RFR] Migration Plans Refactoring

---

cfme/tests/cloud/test_snapshot.py
cfme/tests/cloud_infra_common/test_genealogy.py
cfme/tests/configure/test_access_control.py

__New__ manual tests added as a result of qe_test_coverage flag.
Created new file `test_snapshot.py` in tests/cloud for snapshot testing with cloud providers. More manual tests will go to this file in PR #8636 
Added new manual tests to existing files.

[1LP][RFR] New manual testcases

---

cfme/configure/configuration/system_schedules.py
cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_domain.py
cfme/tests/configure/test_schedule_operations.py

- Added test case for checking whether internal server error is occuring while selecting object atrribute type
- Added following widgets in ```ScheduleAddEditEntities```:
```
request = Input(name='object_request')
object_type = BootstrapSelect('target_class')
object_selection = BootstrapSelect('target_id')
```
- This test case is created as per the the BZs: [1479570](https://bugzilla.redhat.com/show_bug.cgi?id=1479570) and [1686762](https://bugzilla.redhat.com/show_bug.cgi?id=1686762)
- Also changed name of test case and behaviour of the test case as per above BZs test scenarios
{{ pytest: cfme/tests/automate/test_domain.py -k 'test_object_attribute_type_in_automate_schedule' -vv }}

[1LP][RFR] New Test: Test object atrribute type in automation schedule

---

cfme/common/provider.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py

Adding new AMI usage due to BZ 1684203 for EC2 SSA testing.
PRT run:
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_vm -qsvvvv --use-provider ec2west --long-running }}

[1LP][RFR] This will add workaround for AMI image selection.

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_git_import.py

- Test case added for checking domain imports with or without top level domain
- Removed test cases which was already exist for importing domain
- Merged two test cases into one
{{ pytest: cfme/tests/automate/test_git_import.py -k 'test_domain_import_git' -vv }}

[1LP][RFR] New Test: Checking domain import via git with or without top level domain

---

cfme/tests/automate/test_automate_manual.py

Following updated to this PR:
- Added new manual test cases for 5.10
- Removed tests which are already automated like [custom button](https://github.com/ManageIQ/integration_tests/search?q=test+custom+button+expression&)

[1LP][RFR][NOTEST] Added manual test case for 5.10

---

cfme/tests/cli/test_appliance_cli.py
cfme/tests/cli/test_appliance_console.py
cfme/tests/containers/test_blacklisted_container_events.py
cfme/tests/containers/test_pause_resume_workers.py
cfme/utils/ssh.py

Don't pass hostname/username/password if its just the default or current test appliance
Its just duplicating SSHClient default behavior.
PRT failures in run 30978 are not related to the LogValidator/SSHClient changes, but issues with sprout or with the test.

[1LP][RFR] Update LogValidator usage

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/tests/ansible/test_embedded_ansible_manual.py

Removed Manual tests.
PRT run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_crud.py -k "test_embedded_ansible_event_catcher_process or test_embedded_ansible_logs" -qsvvvv --long-running }}

[1LP][RFR] Automating Critical Embedded Ansible manual tests.

---

cfme/tests/automate/custom_button/test_generic_objects.py
cfme/tests/automate/custom_button/test_infra_objects.py
cfme/tests/automate/custom_button/test_service_objects.py

Previously only `VM` object supporting open url and new support going to be add in next release for now adding manual test.
- Added as per custom button test structure.... so as automate ids going to match with manual.

[1LP][RFR][NOTEST] CB: new manual tests

---

cfme/cloud/provider/__init__.py
cfme/cloud/provider/azure.py
cfme/cloud/provider/ec2.py
cfme/cloud/provider/gce.py
cfme/cloud/provider/openstack.py
cfme/common/provider.py
cfme/containers/provider/__init__.py
cfme/containers/provider/openshift.py
cfme/infrastructure/provider/__init__.py
cfme/infrastructure/provider/openstack_infra.py
cfme/infrastructure/provider/rhevm.py
cfme/infrastructure/provider/scvmm.py
cfme/infrastructure/provider/virtualcenter.py
cfme/markers/env_markers/provider.py
cfme/tests/cloud/test_providers.py
cfme/tests/cloud_infra_common/test_discovery.py
cfme/tests/cloud_infra_common/test_discovery_and_support.py
cfme/utils/providers.py

Add test for selection of provider type
Based on supportability.yaml list of all supported providers for given appliance version
Add attribute to provider classes to define the ems pretty name that's listed for the type
Will be adding a supportability.yaml for integration_tests, and moving CFME's to supportability.local.yaml
Passed in 59z so I pushed branch, failing in 510z though, GCE is being looked for on the infra provider page
{{ pytest: cfme/tests/cloud_infra_common/test_discovery.py -k test_provider_type_support}}

[1LP][WIP] Add test for provider type selection

---

cfme/tests/generic_objects/test_instances.py

Adding a manual case for https://bugzilla.redhat.com/show_bug.cgi?id=1595259
This is for 5.11/upstream testing.

[1LP][RFR][NOTEST] Add manual case for BZ 1595259

---

cfme/tests/candu/test_host_graph.py

The 'group by tag' tests have been implemented in a different way and have been moved to a new location[0].So, I'm removing the tests from this module.
[0]https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/candu/test_graph_groupbytag.py
{{pytest: cfme/tests/candu/test_host_graph.py --collect-only}}

[1LP][RFR] Remove group by tag tests

---

scripts/ec2cleanup.py

Wrapanapi ec2 is moving to boto3 and in boto3 response returns dict instead of object so I needed to change calling of elb.name.
Depends on this PR:
https://github.com/ManageIQ/wrapanapi/pull/362
{{ pytest: cfme/tests/cloud* --use-provider ec2west --long-running }}

[NOTEST] [RFR] EC2cleanup boto3 refactor from object to dict

---

cfme/v2v/migrations.py

What was the issue?
PR https://github.com/ManageIQ/integration_tests/commit/d8a116d811c664360f84bca9fb2fac84c51f17e6#diff-264354a78406ae4ca6d836bd7388d376L5040  removed locator from Widget but we are still using it in older structure which failing ~50 TCs.
```
>       return method(self, *new_args, **new_kwargs)
E       TypeError: __init__() got an unexpected keyword argument 'locator'
/var/ci/cfme_venv/lib/python2.7/site-packages/widgetastic/widget/base.py:67: TypeError
TypeError
__init__() got an unexpected keyword argument 'locator'
```
{{pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider vsphere67-nested --use-provider rhv42 --provider-limit 2 -vvvv -k 'test_single_datastore_single_vm_migration[virtualcenter-6.7-rhevm-4.2-form_data_vm_obj_single_datastore0]'}}
@digitronik …

[1LP][RFR] Removing locator to support modified progress bar widget

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/tests/cli/test_appliance_update.py
cfme/utils/appliance/__init__.py
cfme/utils/appliance/services.py

{{ pytest: --long-running cfme/tests/ansible/test_embedded_ansible_crud.py  }}
There is some flaky behavior in the new tests checking for some EmbeddedAnsible process. @sbulage is going to address these test failures. I've changed the fixture name here, but that's unrelated to the process state changes that cause the test to fail.

[1LP][RFR] Move convenience methods to use SystemdService plugin for appliance

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_git_import.py
cfme/tests/cloud_infra_common/test_power_control_manual.py
cfme/tests/cloud_infra_common/test_quota_manual.py
cfme/tests/services/test_catalog_item.py

Following updated to this PR:
- Added new manual test cases
- Updated files with test_requirements
- Removed tests which are already automated like [custom button](https://github.com/ManageIQ/integration_tests/search?q=test+custom+button+expression&unscoped_q=test+custom+button+expression)
- Some tests are RFE; hence not added teststeps.
- Removed 5.9 dependency

[1LP][RFR] Added new manual test cases

---

cfme/fixtures/provider.py
cfme/fixtures/service_fixtures.py
cfme/tests/services/test_add_remove_vm_to_service.py

- Added global fixture for returning `service` and respective `vm` object.
- This fixture going to use in upcoming `custom button` test cases
- I found this functionality in one of service test so removed that local fixture added small improvement and move to global.
- Yup there is one more global fixture which order catalog but returning item name. which not useful for everyone. 
{{pytest: cfme/tests/services/test_add_remove_vm_to_service.py -v --long-running}}

[1LP][RFR] Global fixture for custom button support. 

---

cfme/automate/explorer/method.py
cfme/fixtures/ansible_fixtures.py
cfme/fixtures/embedded_ansible.py
cfme/test_framework/pytest_plugin.py
cfme/tests/networks/nuage/test_automation.py

Test that Nuage events trigger Embedded Ansible automation and that playbook has access to authentication attributes and event data.
Specifically, we copy AE Instance 'ManageIQ/System/Event/EmsEvent/Nuage/nuage_enterprise_create' from default domain into our own domain and customize it's 'meth5' attribute to invoke Embedded Ansible playbook which prints authentication attributes and event data into evm.log. This test then triggers a 'nuage_enterprise_create' event and waits for appropriate line to appear in evm.log.
Prerequisites:
Following content needs to be present in cfme_data.yaml in order to fetch correct Ansible repository:
```yaml
ansible_links:
playbook_repositories:
embedded_ansible: https://github.com/xlab-si/integration-tests-nuage-automation.git
```
Video explaining what the …

[RFR] Test Embedded Ansible integration for Nuage

---

cfme/base/__init__.py

See https://github.com/ManageIQ/manageiq-api-client-python/issues/45, @valaparthvi is __Extending__ upstream API to not reserve `url` keyword argument, so that she can add test case for adding AnsibleTower via REST API.
For now https://github.com/ManageIQ/manageiq-api-client-python/pull/46 preserved backward compatibility — `get(url=..., **...)` still works — but it might get dropped later.
Also for consistency - over 30 calls in this project pass it positionally.  (Same in some other projects on the internet.  This was the _only_ call I found passing it by name.) 
@valaparthvi please review

Pass url positionally as its name is changing in manageiq_client

---

cfme/rest/gen_data.py

1. Functions such as `tenants`, `groups`, `roles`, and `users` that accept kwargs would fail if num >1, an exception will be raised in such case.
{{ pytest: cfme/tests/configure/test_rest_access_control.py --use-template-cache -sqvvv }}

[WIPTEST]Fix gen_data function

---

cfme/tests/services/test_rest_services.py
cfme/tests/test_rest_manual.py

Changes brought with this PR:
1. Automate test case: test_deny_service_ordering_via_api
2. Add fixture `update_advanced_settings` for the test
3. Remove test from the manual file.
{{ pytest: cfme/tests/services/test_rest_services.py::test_deny_service_ordering_via_api --use-template-cache -sqvvv --long-running }}

[1LP][RFR] Automate test: test_deny_service_ordering_via_api

---

cfme/tests/infrastructure/test_infra_manual.py
cfme/tests/infrastructure/test_vm_retirement_rest.py

1. Automate test case: test_vm_retirement_requester
2. Add a fixture `retire_vm` to retire the vm.
3. Add a fixture `vm_retirement_report` to generate report.
4. Blackify the file.
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py::test_check_vm_retirement_requester --use-template-cache -sqvvv }}

[1LP][RFR] Automate test: test_vm_retirement_requester

---

cfme/tests/control/test_actions.py

rc-regression, this `finally` block should not exist, as that skips all tests.  Recent change also caused `message` reference triggering an `UnboundLocal`
Not necessarily expecting this module to completely pass PRT, but I'm looking to not hit any `UnboundLocal` or other failing results connected to whether this skip is called or not.

[RFR] Remove finally clause from _get_vm method in control/test_actions.py

---

cfme/tests/test_appliance.py

to fix
```
ValueError: invalid literal for int() with base 10:
```

[RFR] fix two smoke tests

---

cfme/tests/control/test_basic.py

Adding BZ metadata to `test_control_assign_actions_to_event`, which is failing due to https://bugzilla.redhat.com/show_bug.cgi?id=1700070. This PR also brings a workaround for this BZ. 
{{ pytest: --long-running --use-template-cache cfme/tests/control/test_basic.py::test_control_assign_actions_to_event }}

[RFR] Add BZ and workaround for this test

---

cfme/fixtures/appliance.py

A few tests are skipping because we don't have a `vddk_url` for VSphere 6.7. This PR will make tests use `vddk v6_5` for these skipped tests. 
{{pytest: --long-running --use-template-cache --use-provider vsphere67-nested cfme/tests/control/test_alerts.py::test_alert_hardware_reconfigured }}

[RFR] Default to vddk 6.5 in vddk_url fixture

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_method.py

- Automating test case which checks ```Q-task_id``` for automate methods
{{ pytest: cfme/tests/automate/test_method.py -k 'test_task_id_for_method_automation_log' -vv }}

[1LP][RFR] New Test: Checking 'Q-task_id' for automate methods in automation logs

---

cfme/automate/explorer/common.py
cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_domain.py

This PR includes following changes:
- Removing flash message assertions from module page
- Automated test case which was related to copy ```automate class/instance/method``` to new domain
- Asserted those removed statements in this test case
- This fix will save more number of test cases related to quota and automate from failures
- Fixed Error:
```E           AssertionError: assert exact match of message: Copy selected Automate <class 'cfme.automate.explorer.instance.Instance'> was saved. 
E            Available messages: [u'Copy selected Automate Instance was saved']
/var/ci/cfme_venv/lib/python2.7/site-packages/widgetastic_patternfly/__init__.py:299: AssertionError
AssertionError
assert exact match of message: Copy selected Automate <class 'cfme.automate.explorer.instance.Instance'> …
```

[1LP][RFR] Fixed AssertionError while copying method/instance/class to domain

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_instance.py

- Testing instance(```/System/Request/ansible_tower_job```) calls the updated automate method(```/AutomationManagement/AnsibleTower/Operations/StateMachines/Job/default```)
- It should **not call deprecated** ```/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job/default``` method.
{{ pytest: cfme/tests/automate/test_instance.py -k 'test_check_system_request_calls_depr_conf_mgmt' -vv }}
juwatts:
https://github.com/ManageIQ/integration_tests/pull/8723 needs to be merged first

[1LP][RFR] New Test: Testing instance(ansible_tower_job) calls the proper automate method

---

cfme/tests/cloud/test_cloud_timelines.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/control/test_rest_control.py
cfme/tests/infrastructure/test_timelines.py

Making use of #8672 to add requirement metadata for my test cases. 
I've added requirements for timelines and events tests and also a control test.

[RFR] Add in test_requirements where necessary for FAs

---

cfme/tests/configure/test_tag_category.py
cfme/tests/test_rest_manual.py

1. Automate test: test_query_custom_category
2. Add a fixture to create a custom category.
{{pytest: cfme/tests/configure/test_tag_category.py::test_query_custom_category_via_api --use-template-cache -sqvvv }}

[1LP][RFR]Automate testcase: test_query_custom_category

---

cfme/tests/intelligence/reports/test_reports.py
cfme/tests/intelligence/reports/test_reports_manual.py

1. Automate test case: `test_reports_custom_tags`
2. Add a fixture to create the custom tags
3. Remove the test from manual file.
{{pytest: cfme/tests/intelligence/reports/test_reports.py::test_reports_custom_tags --use-template-cache -sqvvvv}}

[1LP][RFR]Automate test: test_reports_custom_tags

---

cfme/tests/infrastructure/test_vm_power_control.py

This PR includes following changes:
- Two test cases: ```test_guest_os_shutdown``` and ```test_guest_os_reset``` are failing for ```rhv``` provider because of the BZs
raised for both of these tests.
- These test cases were skipping for 5.10z before but As I see now blockers marker were removed accidentaly in any of the old PRs.
- Hence adding the blockes mark with related BZs and skipping these test cases for 5.10z
- These test cases were failing in 5.10 with below errors:
```E           SoftAssertionError: 
E           Last Boot Time value has not been refreshed (cfme/tests/infrastructure/test_vm_power_control.py:542)
cfme/fixtures/soft_assert.py:64: SoftAssertionError
SoftAssertionError
Last Boot Time value has not been refreshed (cfme/tests/infrastructure/test_vm_power_control.py:542) …
```

[1LP][RFR] Fixed failing test cases in 5.10z for rhv provider

---

cfme/tests/services/test_operations.py

```
}
E       KeyError: 'vlan'
cfme/tests/services/test_operations.py:72: KeyError
KeyError
'vlan'
```

[1LP][RFR] Fix test operations

---

cfme/tests/infrastructure/test_scvmm_specific.py

The purpose of this pr is to:
1) Add testSteps for manual cases in `test_scvmm_specific`, these will be automated later
2) Remove tests that have 2016 in the name, these tests will be parametrized against both SCVMM 2016 and 2012
3) Minor fixes for `test_no_dvd_ruins_refresh`
{{ pytest: --long-running --use-template-cache --use-provider complete cfme/tests/infrastructure/test_scvmm_specific.py }}

[1LP][RFR] SCVMM test cleanup

---

cfme/tests/openstack/cloud/test_flavors.py
cfme/tests/openstack/cloud/test_instances.py
cfme/tests/openstack/cloud/test_volume_backup.py

```
>       prov_data = provider.data['provisioning']
E       KeyError: 'provisioning'
cfme/tests/openstack/cloud/test_flavors.py:41: KeyError
KeyError
'provisioning'
```

[1LP][RFR] fix tests screwed up by v2v osp provider

---

cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py

```
>       cloud_init_template_name = provider.data['provisioning']['ci-template']
E       KeyError: 'ci-template'
cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py:48: KeyError
KeyError
'ci-template'
```

[1LP][RFR] cloud init provisioning tests fix

---

cfme/fixtures/service_fixtures.py

Changing some global fixture scopes affected some existing tests. This PR restores scopes for those global fixtures.
{{pytest: --long-running cfme/tests/services/test_generic_service_catalogs.py}}

[RFR] fixing scopes of some global fixtures

---

cfme/utils/appliance/__init__.py

There was a bug that lead to messages like
"Popped an appliance empty from the stack"
this patch is fixing that.
{{ py.test: -v -m smoke -k "not test_cloud_provider_crud" }}

[1LP][RFR] Fix the Pop and Push the appliance to the stack messages

---

cfme/utils/log_validator.py

The `LogValidator` currently uses `re.match()` to verify the presence of a pattern in the line(s) of a log. `re.match()` begins its search at the start of a file, so if you have a pattern you want to match that may appear later in the line, you must put `.*` at the start of your pattern. 
With `re.search()` no such preamble is necessary. 
{{ pytest: --long-running --use-template-cache --use-provider complete cfme/tests/networks/nuage/test_automation.py::test_embedded_ansible_executed_with_data_upon_event cfme/tests/containers/test_pause_resume_workers.py::test_pause_and_resume_single_provider_api }}
Example: 
```python,
In [1]: import re …
```

[1LP][RFR] Use re.search instead of re.match in LogValidator

---

cfme/utils/appliance/__init__.py
cfme/utils/appliance/db.py

pyopenssl change may get removed in favor of the implementation in #8689.  Have it included here for testing, won't hurt.
The main workaround provided here is setting permissions on the mounted LV for the DB. PG10 uses the home dir as data dir mountpoint, needs specific ownership/permissions that were not needed in 5.10.

[1LP][RFR] Updates for 5.11 configuration, set postgres permissions

---

.pre-commit-config.yaml
requirements/frozen.py2.txt
requirements/frozen.py3.txt

This PR adds the flake8 plugin[ `bugzilla-docstrings`](https://pypi.org/project/bugzilla-docstrings/) to our pre-commit config. This plugin makes sure that BZs placed under `Bugzilla:` are just numbers, and that each BZ is on its own line, as described by #8684.  
Note that this plugin does not check and make sure that the `Bugzilla:` field is present in the docstring, since not all tests are written against BZs. It also does not currently look for variations of Bugzilla, such as `BZ`, or `Bugzillas`. It only looks at what is written below `Bugzilla:`.

[1LP][RFR] Add bugzilla-docstrings to pre-commit

---

cfme/tests/integration/test_cfme_auth.py
cfme/tests/test_manual.py

__Moving__ manual auth testcases to test_cfme_auth.py
I've done some changes like renamed too long testcase names, added requirements and such.
Per discussion with @mshriver , this is __first pass__ of the whole process. Things like setup, testSteps, expectedResults will be added in second pass. Please let me know what you think.

[1LP][RFR] Move auth manual testcases

---

cfme/tests/ansible/test_embedded_ansible_crud.py
cfme/utils/appliance/__init__.py
cfme/utils/appliance/services.py

PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_crud.py --long-running }}
Fixes #8702

[1LP][RFR] Fixed Embedded Ansible CRUD test file by re-ordering sub-tests

---

cfme/infrastructure/virtual_machines.py

__Updating__ strings related to snapshot manipulation. 'ManageIQ' has changed to 'CFME'.
This fixes all failing snapshot tests.
{{ pytest: -v --long-running cfme/tests/infrastructure/test_snapshot.py --use-provider vsphere67-nested }}

[1LP][RFR] Update snapshot strings

---

cfme/infrastructure/virtual_machines.py

{{ pytest: cfme/tests/infrastructure/test_timelines.py }}
It looks like this is the only usage of vm_object.cluster.So, I'd like this test to be run on PRT against the new PR.
PRT results:
I'm still waiting on PRT results since Sprout is unable to provision an appliance at the moment.
I have tested this PR locally using this code segment .
http://pastebin.test.redhat.com/758518
With these code changes, the relevant information is fetched via REST API and not UI ; Using REST API speeds up the process .

[1LP][RFR] Update cluster property to fetch info through REST

---

cfme/tests/openstack/cloud/test_flavors.py
cfme/tests/test_rest_manual.py

Changes:
1. Remove tests no longer in need to automate.
2. Automate test case: test_filter_by_flavor_via_api
{{ pytest: cfme/tests/openstack/cloud/test_flavors.py::test_filter_by_flavor_via_api --use-template-cache -sqvvv }}

[1LP][RFR]Automate test:test_filter_by_flavor_via_api

---

cfme/control/explorer/policies.py
cfme/tests/ansible/test_embedded_ansible_actions.py
cfme/tests/cloud_infra_common/test_events.py
cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
cfme/tests/control/test_actions.py
cfme/tests/control/test_basic.py
cfme/tests/intelligence/test_reports_with_timelines.py
widgetastic_manageiq/__init__.py

The current implementation of `BootstrapSwitchSelect`'s fill method is quite slow (taking around 10 s before a fill when assigning events to a policy), since it looks at each switch on the page and decides whether or not it's selected. 
This PR modifies the fill method of `BootstrapSwitchSelect` that allows for a faster fill of the page. It is less cautious than the original fill method since it does not look at the events which are already selected. 
This PR also introduces an `unassign_events` function that takes in the names of the events you'd like to unassign from the policy. I have modified tests to use this function for cleanup, as it is more explicit (and faster) than using `assign_events()`  
{{ pytest: --long-running --use-template-cache …

[1LP][RFR] Optimize assign events for policies

---

cfme/tests/infrastructure/test_scvmm_specific.py

Removing some of the basic manual cases that are automated by the `test_relationships` tests for SCVMM. I am using this PR to test the relationships tests on PRT. Also making a small change for `test_no_dvd_ruins_refresh`
{{ pytest: --use-provider ms_scvmm --use-template-cache --long-running cfme/tests/cloud_infra_common/test_relationships.py cfme/tests/infrastructure/test_scvmm_specific.py }}

[RFR] Remove tests automated in test_relationships for SCVMM

---

cfme/tests/automate/test_customization_paginator.py
cfme/tests/automate/test_service_dialog.py
cfme/tests/configure/test_config_manual.py
cfme/tests/configure/test_paginator.py
cfme/tests/configure/test_server_name.py
cfme/tests/networks/test_sdn_downloads.py
cfme/tests/webui/test_advanced_search.py
cfme/tests/webui/test_filter_conditions.py
cfme/tests/webui/test_general_ui.py

1. reassigned some `general_ui` tests to pvala
2. marked some tests with `configuration` requirements and reassigned to tpapaioa
3. found some tests that should belong to `searching and filtering` and reassigned them to myself

[RFR][NOTEST]reassigned more general ui tests

---

scripts/cleanup_old_vms.py

Some providers were returning `None` for vm_creation_time, which breaks the check.
Adjust how the default is set to avoid this trap.
Running in Jenkins now.

[WIPTEST] Update creation time check in cleanup_old_vms

---

cfme/fixtures/ui_coverage.py

We were still trying to install coverage when using --ui-coverage and --collect-only.
This could be achived with a mutually exclusive argparse group, but both are part of the larger `cfme` group.
If the team prefers, I can take that route, but this seemed an appropriate check to me, without preventing both from being included in a py.test call.

[1LP][RFR] Check collectonly before registering UiCoveragePlugin

---

cfme/tests/test_rest.py
cfme/tests/test_rest_manual.py

Changes:
1. Automate test: test_rest_metric_rollups - not enabling candu, because we only want to check if the endpoint works and does not give any error.
2. Move `test_settings_collections` to `test_query_simple_collections`, and also test `automate_workspaces` collections which wasn't tested earlier.
{{ pytest: cfme/tests/test_rest.py -k "test_query_simple_collections or test_rest_metric_rollups" --use-template-cache -sqvvv }}

[1LP][RFR] Automate test: test_rest_metric_rollups

---

cfme/tests/infrastructure/test_vm_reconfigure.py
cfme/tests/test_rest_manual.py

1. Automate test: test_vm_disk_reconfig_via_rest
2. Add a function to help reconfigure the VM via REST.
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_disk_reconfig_via_rest --long-running --use-template-cache -sqvvv}}

[1LP][RFR]Automate test: test_vm_disk_reconfig_via_rest

---

cfme/utils/log_validator.py

Adding a simple `wait_for_log_validation` for the `LogValidator`. This can be used in the following way, 
```python,
from cfme.utils.log_validator import LogValidator
test = LogValidator("/root/test.log", matched_patterns=[".*blah"])
test.fix_before_start()
test.wait_for_log_validation(timeout=300, delay=1)
```

[1LP][RFR] Add in a wait_for LogValidator

---

cfme/configure/configuration/diagnostics_settings.py

{{ pytest: cfme/tests/configure/test_log_depot_operation.py -qsvvv --long-running }}
the previous solution didn't work if the server's number is more than 1 digit

[1LP][RFR] fixed is_displayed for ServerCollectLogsView

---

cfme/tests/control/test_actions.py
cfme/tests/networks/nuage/test_automation.py

PR to make use of the `wait_for_log_validation()` function of the `LogValidator`.
{{ pytest: --use-template-cache --use-provider vsphere65-nested --long-running cfme/tests/networks/nuage/test_automation.py::test_embedded_ansible_executed_with_data_upon_event cfme/tests/control/test_actions.py::test_action_power_on_audit cfme/tests/control/test_actions.py::test_action_power_on_logged }}

[RFR] Use wait_for_log_validation where possible

---

cfme/utils/template/rhopenshift.py

Output looks like:
```
(.py2env)  #  cfme/utils/template/template_upload.py --image-url http://file.cloudforms.lab.eng.rdu2.redhat.com/builds/cfme/5.11/stable --provider cm-pod1                
Matching stream name based on image_url base: http://file.cloudforms.lab.eng.rdu2.redhat.com/builds/cfme/5.11
(template-upload) [OPENSHIFT:cm-pod1:cfme-5.11.0.2-20190430] BEGIN template upload script
(template-upload) [OPENSHIFT:cm-pod1:cfme-5.11.0.2-20190430] BEGIN run upload template
Podified appliances not available for 5.11+ or upstream
(template-upload) [OPENSHIFT:cm-pod1:cfme-5.11.0.2-20190430] FAIL run upload template
(template-upload) [OPENSHIFT:cm-pod1:cfme-5.11.0.2-20190430] END template upload script
```

[1LP][RFR] Update openshift template upload, block 5.11

---

sprout/appliances/templates/appliances/providers.html

Put the appliance limits/counts in the header instead of the footer
Then you don't have to scroll to see them when there are 30+ appliances running on a provider
Tested locally

[RFR] Update Providers page in sprout

---

cfme/tests/configure/test_proxy.py
cfme/tests/distributed/test_appliance_replication.py
cfme/tests/v2v/test_csv_import.py
cfme/utils/appliance/__init__.py
conf/cfme_data.yaml.template
scripts/clone_template.py

test_appliance_replication fixture needs rewritten to use existing sprout fixtures
provision_appliance method now requires provider name
update flavor picking in clone_template
pytest.skip in test_proxy when no proxy_template is available
clone_template tested locally.

[RFR] Random updates related to vsphere55 yaml cleanup

---

sprout/appliances/tasks.py

Sprout is putting shepherd appliances on disabled providers.
Tested locally

[RFR] Update provider check in shepherd task

---

cfme/fixtures/artifactor_plugin.py
cfme/fixtures/node_annotate.py
cfme/fixtures/parallelizer/__init__.py
cfme/fixtures/portset.py
cfme/fixtures/prov_filter.py
cfme/fixtures/templateloader.py
cfme/fixtures/ui_coverage.py
cfme/markers/skipper.py
cfme/test_framework/appliance.py

Now it takes all of 5s to get the help text, instead of minutes.
Several of our plugins were running costly `pytest_configure` hooks regardless of other config context, like `--help`.  Specifically check for this in costly config methods, returning immediately.
This should have no functional effect on the plugins themselves, and no impact on the content of the help text.
Only impact should be much faster execution time when calling `py.test --help` in our test environment.
No starting artifactor
No pulling template caches
No instantiating appliance objects
No instantiating provider objects

[RFR] Skip plugin config when --help is passed

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_buttons.py

- https://bugzilla.redhat.com/show_bug.cgi?id=1535215 FIXED for 511
- Now EVM prefix not found evm objects in simulation.
- need https://github.com/ManageIQ/integration_tests/pull/8776 for a run
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_simulation}}

[1LP][RFR] fix simulation 511 changes

---

cfme/tests/control/test_actions.py

Adding actions metadata to these tests as they were collecting against providers they shouldn't be collecting against. 
{{ pytest: --use-provider complete --use-template-cache --collect-only cfme/tests/control/test_actions.py }}

[1LP][RFR] Adding actions metadata for the tests in test_actions

---

cfme/tests/configure/test_email.py

Reassigned `test_send_test_email` and marked as `configuration` requirement after some discussion with @mshriver

[1LP][RFR][NOTEST] reassigned test_email

---

cfme/tests/automate/custom_button/test_buttons.py

- blocker for 511
- move test from provider object to vm/instance
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_open_url_availability}}

[1LP][RFR] 511 open url only for vm/instance and BZ-1706900

---

cfme/tests/containers/test_chargeback.py

{{ pytest: cfme/tests/containers/test_chargeback.py -v --use-template-cache --use-provider ocp-37-hawk -m 'uses_testgen and long_running_env' }}

[1LP][RFR] Blocking test_chargeback_containers for now

---

cfme/utils/trackerbot.py

composite-uncollect was timing out on the trackerbot read for composite-uncollect. 
Loosen the timeout, short for connect and long for read.

[1LP][RFR] Update composite-uncollect timeout

---

cfme/fixtures/parallelizer/__init__.py

We're hitting an exception trying to call decode on the exception object, because the call to print_message was passing the wrong object.
Changed things up a bit, no longer trying to pass the exception itself to print_message.
Cleaned up some print_message calls otherwise as well.

[RFR] Fix parallelizer decode

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_namespace.py

- Testing removal of openshift "Deployment" from automate domain - ManageIQ
{{ pytest: cfme/tests/automate/test_namespace.py -k 'test_remove_openshift_deployment_in_automate' -vv }}

[1LP][RFR] New Test: Removal of openshift "Deployment" from automate domain

---

cfme/utils/appliance/__init__.py

Use `Appliance.from_provider()` to instantiate the appliance object in `provision_appliance`. This should fix this error that's seen with the current implementation: 
```python,
Traceback (most recent call last):
File "/home/jdupuy/cfme_tests/cfme_venv/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-6-921e85341915>", line 1, in <module>
create_appliance(provider, image_name)
File "/home/jdupuy/cfme_tests/integration_tests/cfme/tests/infrastructure/test_scvmm_specific.py", line 112, in create_appliance
return provision_appliance(provider.key, version=version, template=template_name)
File "/home/jdupuy/cfme_tests/integration_tests/cfme/utils/appliance/__init__.py", line 2952, in …
```

[1LP][RFR] Change appliance instantiation to use from_provider

---

cfme/storage/manager.py
cfme/storage/volume.py
cfme/tests/storage/test_volume.py

Extending storage volume tests also for ec2.
Also in volume crud changing volume size and then checking whether it was changed.
Tests are failing because of ec2cleanup script which deletes volumes before all the tests are completed.
I know that this code could be somewhere messy so please tell me how to improve it. Thanks.
{{pytest: cfme/tests/storage/test_volume.py --use-provider complete}}

[1LP][RFR] Storage volume tests also for ec2

---

cfme/tests/automate/test_rest.py
cfme/tests/test_rest_manual.py

Changes:
1. Add a fixture `domain_rest` to create domain.
2. Add 2 tests:
1. `test_delete_automate_domain_from_collection`
2. `test_delete_automate_domain_from_detail`
{{ pytest: cfme/tests/automate/test_rest.py -k "test_delete_automate_domain"  --use-template-cache -sqvvv }}

[1LP][RFR] Automate test: test_delete_automate_domain_via_api

---

cfme/tests/cli/test_evmserverd.py

This test was failing with the following error:
```
cfme/tests/cli/test_evmserverd.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.0 = <listiterator object at 0x7f284f5e9390>
server[server_name_key].rstrip('*')  # evm* shows up in status
>   for server in appliance.ssh_client.status["servers"]
}
E       KeyError: 'Server'
cfme/tests/cli/test_evmserverd.py:47: KeyError
```
Adding a wait_for should in getting the server_name should remedy this. 
{{ pytest: --long-running --use-template-cache cfme/tests/cli/test_evmserverd.py::test_evmserverd_stop }}

[RFR] Add a wait_for in getting the server_names

---

cfme/tests/services/test_iso_service_catalogs.py

{{ pytest: --use-template-cache --long-running --use-provider rhv43 cfme/tests/services/test_iso_service_catalogs.py -k test_rhev_iso_servicecatalog }}
@lina-nikiforova This test was failing with a `KeyError` due to the template `rhel74` not being available in the `customization_templates`, this PR will skip the test for now.

[1LP][RFR] Add a skip if the template is not available in customization templates

---

cfme/configure/configuration/server_settings.py
cfme/tests/cloud_infra_common/test_provisioning.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

This exception doesn't always occur during the fixture, which obviously causes test failures.  Only occurring on the rhos provider tests, so only including it for PRT.
{{ pytest: --long-running --use-provider rhos13 cfme/tests/cloud_infra_common/test_provisioning.py }}

[RFR] Update wt.pf, fix test_provisioning fixtures, add remote_console role

---

cfme/utils/template/base.py
cfme/utils/template/rhopenshift.py
cfme/utils/trackerbot.py
scripts/sync_template_tracker.py

Refactor of sync_template_tracker, adding in threadpools to speed things up. Optimized some of the API calls being made.  Broke some sections out into separate functions for better readability.
Some updates to provider/template selection/filtering. Ignoring amzn-ami images in particular, and not trying to run against disabled providers.
py3 only now, because of using starmap.
Will run in Jenkins to compare time.

[RFR] Update sync_template_tracker, ignore AMI

---

cfme/automate/explorer/domain.py
cfme/automate/explorer/instance.py
cfme/automate/explorer/klass.py
cfme/automate/explorer/method.py
cfme/automate/explorer/namespace.py
cfme/tests/automate/test_domain.py
cfme/tests/automate/test_method.py

- Fixed test cases of ```Automate``` which are failing because of BZ: 1704439
{{ pytest: cfme/tests/automate/ -k 'test_domain_crud or test_domain_delete_from_table or test_duplicate_domain_disallowed or test_duplicate_namespace_disallowed or test_wrong_namespace_name or test_namespace_delete_from_table or test_namespace_crud or test_duplicate_class_disallowed or test_same_class_name_different_namespace or test_class_crud or test_method_crud or test_duplicate_method_disallowed or test_task_id_for_method_automation_log or test_instance_crud or test_instance_display_name_unset_from_ui or test_duplicate_instance_disallowed' -vvv }}

[1LP][RFR] Fixed test cases related to automate in 5.11

---

cfme/tests/configure/test_logs.py

{{ pytest: -v cfme/tests/configure/test_logs.py::test_provider_log_level --use-provider=complete }}
The blocker is not valid for the whole test, it got changed during removing `5.9` references, so I'm restoring it.

[1LP][RFR] modified blocker for test_provider_log_level

---

cfme/tests/cloud/test_snapshot.py
cfme/tests/configure/test_access_control.py
cfme/tests/infrastructure/test_vm_reconfigure.py
cfme/tests/ssui/test_ssui_myservice.py

__Adding__ new tests as a result of qe_test_coverage flag.
I left @niyazRedhat as assignee in `test_vm_reconfig_resize_disk_snapshot`, since he has already two very similar tests in there. Please let me know if that's the correct way to do this.

[1LP][RFR] New tests for BZs qe_test_coverage

---

cfme/infrastructure/config_management.py
cfme/tests/infrastructure/test_config_management_rest.py
cfme/tests/test_rest_manual.py

Changes:
1. Add config_manager CRUD tests for REST
2. Add `create_rest`, `delete_rest` and `rest_api_entity` methods for Config Manager
{{ pytest: cfme/tests/infrastructure/test_config_management_rest.py -k "test_config_manager_create or test_config_manager_edit or test_config_manager_delete_details" --use-template-cache -sqvvv }}

[1LP][RFR] Automate config manager tests for REST

---

cfme/fixtures/v2v_fixtures.py
cfme/tests/v2v/test_v2v_migrations_ui.py
cfme/v2v/infrastructure_mapping.py
cfme/v2v/migration_plans.py

{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
- Removed sorting and host tag testcase since this aren't necessary.
- Moving host refresh test to somewhere else I might raise new PR for that which includes tier4/chaos tests
Reviewers, better to review with `cfme/tests/v2v/test_v2v_migrations_ui.py` instead of diff.

[1LP][RFR] Migration UI refactor

---

cfme/common/vm_views.py

In newer versions of Chrome, the test_set_retirement_date tests are failing. In the RetirementDateSelectionView, the clear() method of the TextInput class used by datetime_select makes the calendar pop-up disappear, so that when send_keys() is subsequently called, the calendar pops up a second time. This causes the default current date-time, e.g., '05/06/2019 15:45' to get re-populated, undoing the effect of clear(). The send_keys() method then pastes the intended retirement date-time, e.g., '05/08/2019 00:00', appending it onto the default current date-time to form an invalid date-time, '05/06/2019 15:4505/08/2019 00:00'. When the save() method is called, the web UI tries to turn this value into a valid date-time by stripping off the appended …

[1LP][RFR] Fix test_set_retirement_date failures

---

cfme/utils/template/base.py
cfme/utils/template/ec2.py
cfme/utils/template/gce.py
cfme/utils/template/rhopenshift.py
cfme/utils/template/template_upload.py

Specify for each provider type what streams should not be uploaded.
Might be better to have this in cfme_data.yaml?
We want to block upload of certain streams to certain provider types based on image availability.

[RFR] Update template_upload to block providers on streams

---

cfme/tests/control/test_bugs.py
cfme/utils/bz.py

This PR is meant to provider automated test coverage for the BZ 1708434.
Regarding the comment below, @jawatts and I spent some time debugging this and decided that a change to the `is_opened` property in `cfme.utils.bz` was necessary. The bug this test case was written against is on the latest downstream build. New BZs that are written against the latest build are considered to be upstream bugs, since they are also broken in the upstream build. Upstream bugs are also considered to be bugs that have no version string. However, in this case, for the downstream build, we want to consider the states of `POST` and `MODIFIED` as open for the BZ, since the bug is not fixed in the latest downstream build. This is remedied by changing `and` to `or`. 
{{ pytest: --use-template-cache …

[1LP][RFR] Automate BZ: Add in test_case for buttons on action-edit page

---

cfme/utils/appliance/__init__.py

_custom_configure() doesn't work correctly for upstream builds and I guess it doesn't work right for downstream as well. fixing appliance.configure() to not call _custom_configure durining sprout templatization.

[RFR] _custom_configure doesn't work correctly for upstream

---

cfme/services/catalogs/catalog_items/__init__.py
cfme/utils/appliance/implementations/common.py
cfme/utils/appliance/implementations/ssui.py
cfme/utils/appliance/implementations/ui.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

trying to kill two rabbits by one shot
{{ pytest: --use-template-cache --long-running cfme/tests/services/test_config_provider_servicecatalogs.py }}
fixing issue: https://github.com/ManageIQ/integration_tests/issues/8836
this implementation isn't final yet.
I lean towards to creating parametraized decorator like
```
@handle_modal(action=cancel, wait='10s')
view.configuration.item_select('Remove Catalog Item'), handle_alert=True)
```

[1LP][RFR] handling modals in 5.11

---

cfme/base/ui.py
cfme/configure/configuration/diagnostics_settings.py

==============
In 5.11.0.4, the following tests fail, because the is_displayed() method for ServerView and ServerDiagnosticsView fail to return True.
ServerView:
Server, Authentication, Workers, Custom Logos, Advanced tabs
test_paginator_config_pages[servers_details]
test_paginator_config_pages[servers_authentication]
test_paginator_config_pages[servers_workers]
test_paginator_config_pages[servers_customlogos]
test_paginator_config_pages[servers_advanced]
ServerDiagnosticsView:
Summary, Workers, Collect Logs, CFME Log, Audit Log, Production Log, Utilization, and Timelines tabs
test_paginator_config_pages[servers_diagnosticsdetails]
test_paginator_config_pages[servers_diagnosticsworkers]
test_paginator_config_pages[servers_serverdiagnosticscollectlogs] …

[1LP][RFR] Undo workaround for BZ 1668849

---

cfme/tests/test_rest.py
cfme/tests/test_rest_manual.py

1. Fix failing test `test_datetime_filtering` - [BZ1437529](https://bugzilla.redhat.com/show_bug.cgi?id=1437529) was closed with NOTABUG, and some changes introduced to the test with #8675 caused the test to fail. Reverting all the changes fixed the test failure.
2. Remove a test from test_rest_manual.py that is already covered. 
3. Refactor collections in `test_rest.py` to support 5.11 and 5.10, removing references older than 5.10
{{ pytest: cfme/tests/test_rest.py --use-template-cache -sqvvv }}

[1LP][RFR]Collections refactor for 511, fix failing test and other cleanup

---

cfme/common/__init__.py
cfme/tests/cloud/test_tag_mapping.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

As promised in #8543 I'm fixing the errors in tagging tests
{{ pytest: --long-running -vvvv --use-provider complete cfme/tests/cloud/test_tag_mapping.py  }}
I don't know how `def get_tags` worked before, but I saw sometime ago also empty name in Tag property, so I believe this fix going to fix more tests.
https://github.com/ManageIQ/wrapanapi/pull/382 This is also needed for this fix.

[RFR] follow-up for #8543

---

cfme/automate/buttons.py
cfme/tests/automate/custom_button/test_cloud_objects.py
cfme/tests/automate/custom_button/test_container_objects.py
cfme/tests/automate/custom_button/test_generic_objects.py
cfme/tests/automate/custom_button/test_infra_objects.py

- As 510 also moved to new ui-component
https://github.com/ManageIQ/ui-components/pull/372
- Added fix for 510.. 511 will fails due to tag... need to fix tag.
{{pytest: cfme/tests/automate/custom_button -k 'test_custom_button_expression'}}

[RFR] Fix expression test for component ui changes

---

cfme/ansible/credentials.py
cfme/ansible/playbooks.py
cfme/ansible/repositories.py
cfme/cloud/availability_zone.py
cfme/cloud/flavor.py
cfme/cloud/instance/__init__.py
cfme/cloud/instance/image.py
cfme/cloud/keypairs.py
cfme/cloud/security_groups.py
cfme/cloud/stack.py
cfme/cloud/tenant.py
cfme/common/provider_views.py
cfme/control/log.py
cfme/infrastructure/cluster.py
cfme/infrastructure/config_management.py
cfme/infrastructure/deployment_roles.py
cfme/infrastructure/resource_pool.py
cfme/infrastructure/virtual_machines.py
cfme/intelligence/reports/reports.py
cfme/networks/views.py
cfme/storage/manager.py
cfme/storage/object_store_container.py
cfme/storage/object_store_object.py
cfme/storage/volume.py
cfme/storage/volume_backup.py
cfme/storage/volume_snapshot.py
cfme/storage/volume_type.py

Changes:
1. Since 5.10, the title of the download button in the toolbar has been changed from `Download summary in PDF format` to `Print or export Summary`, change that for automation.
I didn't find any tests using this download feature, so not testing the changes, but I have tested it locally and it works fine.

[1LP][RFR] Fix toolbar download button for details page

---

requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

The newer wait_for doesn't display its own traceback frames which saves space on screen.
{{ py.test: -sv --use-provider 'complete' -m smoke }}

[WIPTEST] Bump wait_for to display less trash in the traceback.

---

cfme/fixtures/ansible_tower.py
cfme/rest/gen_data.py
cfme/test_framework/pytest_plugin.py
cfme/tests/services/test_config_provider_servicecatalogs.py

1)Created Ansible service dialog through REST API
2)The existing tests through which Tower catalog items are ordered now use the new service dialog
3)Also added a new test to verify that Ansible jobs run on limited hosts.

[RFR] Create Ansible service dialog through REST API

---

cfme/utils/appliance/implementations/common.py
cfme/utils/appliance/implementations/ui.py

Shriver: adding module that's seeing recursive failures in other PRT runs:
{{ pytest: --use-template-cache --long-running cfme/tests/services/test_config_provider_servicecatalogs.py cfme/tests/automate/test_method.py }}

[RFR] fixing recursion caused by handling modal

---

cfme/base/__init__.py

This is the new feature in 5.11, more details can be found here https://github.com/ManageIQ/manageiq/issues/17489
I found this test that was affected but maybe there are others:
{{ pytest: -v cfme/tests/configure/test_zones.py }}

[1LP][RFR] Skip maintenance zone in ZoneCollection

---

cfme/automate/explorer/method.py

Fixed Error:
```
>           return self.parent_obj.tree_path + [(icon_name_map[self.location], self.name)]
E           KeyError: 'inline'
cfme/automate/explorer/method.py:391: KeyError
KeyError
'inline'
```
{{ pytest: cfme/tests/automate/test_domain_priority.py -k 'test_priority' -vv }}

[1LP][RFR] Fixed key error in tree path for 5.11

---

cfme/configure/access_control/__init__.py
cfme/fixtures/tag.py
cfme/tests/configure/test_access_control.py
cfme/utils/appliance/implementations/common.py

When there is no wait, there's no check against the fact that the modal is actually present.
Addressing the following failure mode specifically:
```
>           self.logger.info('handling alert: %r', popup.text)
E           AttributeError: 'NoneType' object has no attribute 'text'
cfme/utils/appliance/implementations/common.py:80: AttributeError
AttributeError
'NoneType' object has no attribute 'text'
```
Local testing looks good, included some cases that failed in automation for PRT.
Not necessarily trying to resolve all PRT failures that might happen in these modules.
{{ pytest: cfme/tests/configure/test_access_control.py cfme/tests/configure/test_landing_page.py cfme/tests/infrastructure/test_quota.py }}

[1LP][RFR] Fix AttributeError in HandleModalsMixin.handle_alert

---

cfme/tests/test_appliance.py
cfme/utils/appliance/__init__.py
cfme/utils/appliance/db.py
cfme/utils/appliance/services.py
cfme/utils/ssh.py
scripts/data/enable-internal-db.rbt
scripts/restore.py

It seems that in CFME 5.11, the postgress is no longer a one from SCL.
We need to change some path prefixes and service names to because of
that.
There are also some problems with the tests verifying ssl chains. I don't know the reason for the openssl command to fail so I am disabling these tests as the curl connection works in the end.
CFME 5.11 uses netfilter instead of iptables so checking whether iptables rules exist is wrong on 5.11. We can rather check whether the firewalld services are present in the managiq zone and whether this zone is attached to the eth0 interface.
{{py.test: -v --long-running cfme/tests/test_appliance.py}}

[1LP][RFR] Changes related to CFME 5.11

---

cfme/storage/volume.py
cfme/storage/volume_snapshot.py
cfme/tests/storage/test_volume_snapshot.py

Volume.status wasn't work, because elements.read was checking only first page of paginator so I added get_entity with surf_pages to target page of the entity and then elements are read.
My previous PR for storage tests made snapshot/backup tests broken by deleting storage_manager argument and also renamed size argument to volume_size - both is fixed in this PR.
Also added EC2Provider snapshot tests.

[1LP][RFR] EC2 storage snapshot tests

---

cfme/tests/ansible/test_embedded_ansible_automate.py
cfme/tests/ansible/test_embedded_ansible_basic.py

PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k "test_control_crud_ansible_playbook_action or test_control_add_ansible_playbook_action_invalid_address" -svvvv --long-running }}
{{ pytest: cfme/tests/ansible/test_embedded_ansible_automate.py -k "test_ansible_playbook_button_crud or test_embedded_ansible_custom_button_localhost or test_embedded_ansible_custom_button_target_machine or test_embedded_ansible_custom_button_specific_hosts"  -svvvvv --long-running }}
Use of global fixture `catalog_item` rather local.

[1LP][RFR] Updated tests with use of ansible global fixture.

---

cfme/utils/ssh.py

fix : 
```Exception: SSH connection to ('192.168.122.230',):22 failed, port unavailable```
{{pytest:  cfme/tests/automate/test_method.py -k 'test_task_id_for_method_automation_log' -v}}

[RFR] fix log-validator

---

cfme/tests/test_appliance.py

The package prince is no longer required for generating the PDF reports.
We shouldn't check it's presence on the CFME appliance.

[RFR, NOTEST] Remove prince from the packages on appliance.

---

cfme/tests/infrastructure/test_snapshot.py

{{ pytest: -v cfme/tests/infrastructure/test_snapshot.py::test_delete_active_vm_snapshot --use-template-cache  --use-provider=complete --long-running }}

[RFR] test coverage for BZ1443411

---

cfme/tests/test_rest.py

Changes:
1. Update test `test_server_info` to test for the presence of all the keys. Reference [RHCFQE-10276](https://projects.engineering.redhat.com/browse/RHCFQE-10276) and [manageiq-api/pr-473](https://github.com/ManageIQ/manageiq-api/pull/473).
{{ pytest: cfme/tests/test_rest.py::test_server_info  --use-template-cache -sqvvv }}

[1LP][RFR]Update test_server_info test

---

cfme/common/provider.py

Changes:
1. Change the key name that passes azure `tenant_id` while creating Azure provider via REST. According to the enhancement card [RHCFQE-7605](https://projects.engineering.redhat.com/browse/RHCFQE-7605) and [manageiq-api/pr-279](https://github.com/ManageIQ/manageiq-api/pull/279/files) `azure_tenant_id` key must be used to pass `tenant_id`, while `uid_ems` is the key that will be used to return the `tenant_id` in the response.
{{ pytest: cfme/tests/cloud_infra_common/test_rest_providers.py --use-provider=azure }}

[1LP][RFR]Change provider_attribute key for passing azure tenant id

---

cfme/common/provider_views.py
cfme/tests/cloud_infra_common/test_relationships.py

{{ pytest: -v cfme/tests/cloud_infra_common/test_relationships.py::test_template_refresh_relationships }}
+ added `BZ.blocks` due to breadcrumb issue

[1LP][RFR] new test to check template refresh relationships

---

cfme/intelligence/reports/menus.py
cfme/tests/intelligence/reports/test_menus.py
cfme/tests/intelligence/reports/test_reports_manual.py

1. Add a new method `move_reports` to move custom reports to a different menu.
2. Automate a test case: test_rbac_move_custom_report
3. Add 2 fixtures: `get_custom_report` and `rbac_user`.
3. Blackify test_menus.py (kindly ignore this for now)
4. Add test_requirements.
5. Add a new view `AllReportMenusView` and a navigator to the view.
6. Remove `handle_alert` from `logout` function which raises error on logout.
{{ pytest: cfme/tests/intelligence/reports/test_menus.py::test_rbac_move_custom_report --use-template-cache -sqvvv }}

[1LP][RFR] Automate Test: test_rbac_move_custom_report

---

sprout/appliances/tasks.py

We enountered several issues in sprout today.
Those need to be urgently handled because it affects whole sprout task processing queue.
This Pr intends to sort out below issues.
1. calling disconnect_current_lun and kill_appliance for already absent appliance
2. infinite loop in retrieve ip task
3. broken worker in wait_appliance_ready because of wrong callbacks statement
4. removed statements bombing task queue with many tasks.

[1LP][RFR] sprout fixes

---

cfme/tests/generic_objects/test_instances.py

Automating the test case `test_import_export_generic_object_definition` for CFME 5.11, this test case closely follows the test steps explained by https://github.com/ManageIQ/manageiq/pull/18688 for reference. 
{{ pytest: --use-template-cache --long-running cfme/tests/generic_objects/test_instances.py::test_import_export_generic_object_definition }}

[1LP][RFR] Automate import/export of generic object definitions

---

cfme/tests/infrastructure/test_advanced_search_vms.py

1. Unfortunately, this test was uncollected because of `required_fields=['large']` - we don't have such providers in yamls, therefore BZ 1715550 was missed.
So I removed it.
2. After that, there was scope mismatch, so I also fixed it.
3. The last problem was with the test itself. As described in the bug, nothing happens when 'Apply" is clicked, therefore this test will never fail as the filtering doesn't occur. I updated the test to check that after filtering the number of VMs is at least less than originally and now the test is failing.
4. Added BZ to block this test.
{{ pytest: -v cfme/tests/infrastructure/test_advanced_search_vms.py}}

[1LP][RFR] fixed test_vm_filter_with_user_input

---

cfme/tests/cli/test_appliance_console.py

This test was depend on screen package which
is not included in rhel8, i confirmed with author
of the TC, this TC is no more required for testing
any of the CFME feature, so removing it.

[RFR] Removing test_appliance_console_screen test

---

cfme/tests/configure/test_tag.py

Changes:
1. Add `users` collection to test cases to test tag assignment/unassignment via REST. This change is in accordance with the enhancement card [RHCFQE-9947](https://projects.engineering.redhat.com/browse/RHCFQE-9947).
2. Remove 5.9 references.
{{ pytest: cfme/tests/configure/test_tag.py::TestTagsViaREST -k "users]" --use-template-cache -sqvvv }}

[RFR]Enhance test cases to test user tag assignment/unassignment via REST.

---

cfme/configure/configuration/diagnostics_settings.py

no tests as rhv43 provider is down (it has a template for log collection)
5.10
5.11
https://bugzilla.redhat.com/show_bug.cgi?id=1717902
Discovered in #8888 failures

[RFR] added BZ for ServerCollectLogsEditView is_displayed

---

cfme/control/explorer/alerts.py

This BZ https://bugzilla.redhat.com/show_bug.cgi?id=1653427 (and this PR https://github.com/ManageIQ/manageiq-ui-classic/pull/5326) added alert severity back into CFME 5.11. This PR is setting the default severity for created alerts to "Info". "Severity" is a required field, so this is necessary for creating an alert in CFME 5.11. 
{{ pytest: --use-template-cache --long-running cfme/tests/control/test_basic.py::test_alert_crud }}

[RFR] Add a default severity for CFME 5.11

---

cfme/tests/cloud/test_cloud_events.py

`test_manage_nsg_group` was failing because it didn't have time to register the event between creating and subsequently deleting the network security group. I have added a wait for that waits for a minute before deleting the network security group, this gives CFME time to receive the event from Azure. 
{{ pytest: --long-running --use-template-cache --use-provider azure cfme/tests/cloud/test_cloud_events.py::test_manage_nsg_group }}

[RFR] Add in a wait_for between creating and removing the network security group

---

cfme/tests/cloud_infra_common/test_policy_simulation.py
cfme/tests/infrastructure/test_scvmm_specific.py

Adding forced streams to blocker BZs that have been fixed in 5.11 but whose fixes are not backported to 5.10. These tests are failing when they should be skipped. This is impacting `test_policy_simulation_ui` and `test_check_disk_allocation_size_scvmm`.
Also adding some forced_streams for some BZs in 5.11. 
{{ pytest: --use-template-cache --use-provider complete cfme/tests/cloud_infra_common/test_policy_simulation.py::test_policy_simulation_ui cfme/tests/infrastructure/test_scvmm_specific.py::test_check_disk_allocation_size_scvmm }}

[RFR] Add forced streams for BZ's that aren't backported to 5.10 and some for 5.11

---

cfme/utils/net.py
sprout/appliances/tasks.py

some vms obtain available outside ip after some time. our current solution tries to use first currently available ip instead of waiting for first good one. This PR should fix the issue.

[RFR] make sprout wait for first outward appliance ip

---

cfme/modeling/base.py

PR #8788 introduced breadcrumbs checks for CFME 5.11, as it was different from CFME 5.10. But now devel reverted and looks like CFME 5.10.
By removing CF 5.11 check fix lot's of test failing at `is_displayed`.
I have cross-check `(Summary)` is added there in all files fixed in PR #8788 by navigating to each location.
PRT Run:
{{pytest: cfme/tests/ -k "test_manager_navigation or test_host_good_creds" -svvv --long-running}}

[1LP][RFR] This PR will fix Breadcrumbs issue

---

cfme/tests/infrastructure/test_scvmm_specific.py
cfme/utils/appliance/__init__.py
scripts/clone_template.py

This PR automates the test case to provision a CFME appliance on SCVMM. It goes through the steps of downloading the VHD, creating the template, deploying the template to a VM, configuring the appliance, and waiting for the web ui to become accessible. 
In the process of this PR, I've fix a minor bug in the `Appliance` class. In that class, provider refers to the wrapanapi system class, not the integration_tests provider class, so I fixed this where necessary. 
~~Depends on wrapanapi PR https://github.com/ManageIQ/wrapanapi/pull/378~~
~~Depends on wrapanapi PR https://github.com/ManageIQ/wrapanapi/pull/380~~
~~Depends on wrapanapi PR https://github.com/ManageIQ/wrapanapi/pull/384~~
{{ pytest: --long-running --use-template-cache --use-provider complete …

[1LP][RFR] Automate test case for creating an appliance in SCVMM

---

cfme/tests/automate/custom_button/test_buttons.py

In 511 we disabled checkbox other than vm object so this test was failing 
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_button_required}}

[RFR] fix required icon/request

---

cfme/tests/test_appliance.py

Fix the following error seen when running smoke tests:
```INTERNALERROR> APIException: JSONDecodeError: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
INTERNALERROR> <html><head>
INTERNALERROR> <title>503 Service Unavailable</title>
INTERNALERROR> </head><body>
INTERNALERROR> <h1>Service Unavailable</h1>
INTERNALERROR> <p>The server is temporarily unable to service your
INTERNALERROR> request due to maintenance downtime or capacity
INTERNALERROR> problems. Please try again later.</p>
INTERNALERROR> </body></html>
```
{{ pytest: cfme/tests/test_appliance.py --use-provider complete }}

[RFR] Add wait_for_web_ui after Restarting Server

---

cfme/control/explorer/actions.py
widgetastic_manageiq/__init__.py

Implementing a widget to deal with sectioned bootstrap selects, like the one present on the actions tagging page. 
This is meant to address the changes brought in CFME 5.11 with https://github.com/ManageIQ/manageiq-ui-classic/pull/5535
Since that page is not in the final state, this widget is more of a hack than a full-fledged implementation. The single bootstrap select will eventually be replaced by the tagging editor, which is essentially two bootstrap selects (one for the tag category, and one for the tag itself). This PR is a workaround until https://bugzilla.redhat.com/show_bug.cgi?id=1715397 is fixed. 
Fixes broken action tests which are impacting many tests that follow them.  
{{ pytest: --use-template-cache --long-running cfme/tests/control/test_basic.py::test_action_crud }}

[RFR] Add a widget to deal with sectioned bootstrap selects, fix action tests

---

cfme/utils/appliance/__init__.py
cfme/utils/blockers.py
cfme/utils/bz.py

I recently faced some confusion in dealing with the BZ objects. A lot of it stemmed from the fact that `BugWrapper` in `cfme.utils.bz` gives information relative to the appliance that you're using for testing. My thought is that `cfme.utils.bz` should give information about the BZ _independent_ of the appliance on which you're testing. This appliance specific stuff should be evaluated in the `BZ()` blocker class in `cfme.utils.blockers`.

[1LP][RFR] Remove appliance dependencies from cfme.utils.bz and move them to cfme.utils.blockers

---

widgetastic_manageiq/expression_editor.py

Minor refactor of the `expression_editor` to,
1. Remove lingering CFME 5.9 refs
2. Rename widgets to lowercase
3. Make use of built-in button `click` method
{{ pytest: --use-template-cache --long-running cfme/tests/control/test_basic.py::test_modify_condition_expression }}

[1LP][RFR] Change naming of widgets, use button click method for ExpressionEditor

---

cfme/tests/services/test_catalog_item.py

- Testing service provisioning mail error in automation logs
- This test case scenario is based on BZ: 1668004
- This bug was reported on 5.10 but fixed in 5.11 only.
{{ pytest: cfme/tests/services/test_catalog_item.py -k 'test_service_provisioning_email' -vv }}

[1LP][RFR] New Test: Testing service provisioning mail error in automation logs

---

cfme/tests/automate/test_simulation.py

- Testing if object attribute's type and dependent objects to select are loading succefully or not
- This PR contains new file: ```test_simulation.py```. This file will include all the tests related to simulation page.
{{ pytest: cfme/tests/automate/test_simulation.py -k 'test_object_attributes' -vv }}

[1LP][RFR] New Test: Testing object attributes on simulation page

---

cfme/tests/test_rest.py

Changes:
1. Add a new test `test_provider_options_region` that checks if `regions` is included in `OPTIONS /api/providers`. In accordance with enhancement card [RHCFQE-12080](https://projects.engineering.redhat.com/browse/RHCFQE-12080).
{{ pytest: cfme/tests/test_rest.py::test_supported_provider_options --use-template-cache -sqvvv }}

[1LP][RFR]New Test: test_provider_options_region

---

cfme/automate/dialogs/__init__.py
cfme/automate/dialogs/dialog_element.py

- This PR fixes ```AttributeError``` for two tests.
- Fixed Error:
```
>       self.prerequisite_view.element.edit_element("Text Box")
E       AttributeError: 'EditDialogView' object has no attribute 'element'
cfme/automate/dialogs/dialog_element.py:247: AttributeError
AttributeError
'EditDialogView' object has no attribute 'element'
```
{{pytest: cfme/tests/automate/test_service_dialog.py -vv }}

[WIPTEST] Fixed reorder elements in service dialogs

---

cfme/tests/cloud_infra_common/test_provisioning.py

Adding cleanup for `test_provision_from_template_using_rest`. This test case will create an instance/vm but does not clean it up when the test is finished. 
In testing this on PRT, I noticed a 5.11 BZ: 
https://bugzilla.redhat.com/show_bug.cgi?id=1720751
So I am adding that BZ as a blocker for the test on SCVMM. 
{{ pytest: --use-provider scvmm --long-running cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_from_template_using_rest }}

[RFR] Add cleanup to test provision from template using rest

---

cfme/tests/candu/test_nor_rightsize.py
cfme/tests/cloud_infra_common/test_retirement_manual.py
cfme/tests/distributed/test_appliance_manual.py
cfme/tests/distributed/test_appliance_replication_manual.py
cfme/tests/intelligence/test_chargeback_manual.py
cfme/tests/satellite/test_satellite_manual.py
cfme/tests/test_manual.py
cfme/tests/test_server_manual.py
cfme/tests/webui/test_general_ui_manual.py

No PRT testing required.
Moving manual tests owned by tpapaioa out of test_manual.py and into focus area-specific files:
cfme/tests/candu/test_nor_rightsize.py
cfme/tests/cloud_infra_common/test_retirement_manual.py
cfme/tests/distributed/test_appliance_manual.py
cfme/tests/distributed/test_appliance_replication_manual.py
cfme/tests/intelligence/test_chargeback_manual.py
cfme/tests/satellite/test_satellite_manual.py
cfme/tests/test_server_manual.py
cfme/tests/webui/test_general_ui_manual.py

[1LP][WIPTEST] Move manual test cases owned by tpapaioa out of test_manual.py

---

cfme/utils/net.py

==============
test_send_test_email fails in 5.11 because it runs the following command on the appliance:
cfme/utils/net.py:
****
def net_check_remote(port, addr=None, machine_addr=None, ssh_creds=None, force=False):
[...]
with ssh_client:
cmd = '''python -c "
import sys, socket
addr = socket.gethostbyname('%s')
socket.create_connection((addr, %d), timeout=10)
sys.exit(0)
"''' % (addr, port)
result = ssh_client.run_command(cmd)
[...]
****
The "python" symlink doesn't exist in 5.11:
-bash: python: command not found
lrwxrwxrwx. 1 root root    9 Dec 14 13:21 /usr/bin/python2 -> python2.7
-rwxr-xr-x. 1 root root 9264 Dec 14 13:21 /usr/bin/python2.7
lrwxrwxrwx. 1 root root   25 Jun  5 13:52 /usr/bin/python3 -> /etc/alternatives/python3
lrwxrwxrwx. 1 root root   31 Jan 23 …

[1LP][RFR] Fix python command for test_send_test_email

---

cfme/tests/cloud_infra_common/test_snapshots_rest.py
cfme/tests/configure/test_config_manual.py

Changes:
1. Add [blocker](https://bugzilla.redhat.com/show_bug.cgi?id=1712850) to test_snapshots_rest.py
2. Add manual tests.
{{ pytest: cfme/tests/cloud_infra_common/test_snapshots_rest.py --long-running --use-provider rhos13 --use-template-cache -sqvvv }}

[1LP][RFR] Add test coverages

---

cfme/tests/configure/test_landing_page.py
cfme/tests/configure/test_visual_cloud.py
cfme/tests/configure/test_visual_infra.py

1. Remove `test_infra_start_page` and `test_cloud_start_page`.
2. Modify `test_landing_page_admin` to assert that the user is able to see the page that they set on login.
{{pytest: cfme/tests/configure/test_landing_page.py --use-template-cache -sqvvvv }}

[1LP][RFR]Modify test which encases landing page testing

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_simulation.py

- Testing invalid value for assertion field in class schema
- Simulation(execution) of instance with invalid value of ```assertion``` type field should give error message on simulation page.
{{ pytest: cfme/tests/automate/test_simulation.py -k 'test_assert_failed_substitution'  -vv }}

[1LP][RFR] Testing invalid value for assertion field

---

cfme/tests/generic_objects/test_definitions.py

Adding test case for https://bugzilla.redhat.com/show_bug.cgi?id=1650104
{{ pytest: --use-template-cache --long-running cfme/tests/generic_objects/test_definitions.py::test_upload_image_generic_object_definition }}

[1LP][RFR] Add test case for BZ 1650104

---

sprout/appliances/tasks.py

sprout returns external ip instead of url

[1LP][RFR] fix openshift appliances in sprout

---

cfme/cloud/keypairs.py
cfme/tests/cloud/test_keypairs.py
cfme/tests/test_manual.py

Added key pair tests for ec2
It's failing for 5.11 - when I fix all 5.10 problems with automation I will start fixing 5.11.
Also it was failing in 5.10 when calling keypair.exists so I overriden that method and added wait_for which fixes it. I know this is dumb fix, but didn't find any better way. So if you know how to fix it better then please tell me. Thanks.

[1LP][RFR] Added key pair tests for ec2

---

cfme/ansible/credentials.py
cfme/ansible/repositories.py
cfme/tests/ansible/test_embedded_ansible_tags.py

Blocking this test(s) for CFME 5.11 due to BZ.
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_tags.py -k "test_tag_ansible_repository or test_tagvis_ansible_repository" -svvvv --long-running }}

[1LP][RFR] Global fixture update and some tests tag fix

---

cfme/tests/configure/test_workers.py

==============
Removing blocker for resolved BZ 1656873. test_set_memory_threshold_in_ui test cases should now run successfully.
{{ pytest: cfme/tests/configure/test_workers.py -k test_set_memory_threshold_in_ui -vvvv }}

[1LP][RFR] Remove blocker for resolved bz 1656873

---

cfme/fixtures/bzs.py
cfme/scripting/bz.py
cfme/scripting/miq.py
cfme/test_framework/pytest_plugin.py
cfme/tests/control/test_bugs.py
cfme/utils/bz.py

This PR adds a `miq` command to check tests marked with the `pytest.mark.meta(automates=[<bug_id>])` and `pytest.mark.meta(coverage=[<bug_id>])` and output information about them. 
The basic usage is a follows:
```python,
miq bz <command> <directory>
```
where <command> is one of report, list, or coverage, and <directory> is the testing directory, e.g.
"cfme/tests/control/"
To list BZs that this script would set coverage for, you can do,
```python,
miq bz coverage <directory>
```
This will print out the ids of BZs that could have qe_test_coverage switched to '+'
To then set qe_test_coverage on those BZs, you can do,
```python,
miq bz coverage --set <directory>
```
**Note to reviewers**: if you'd like to test this command, it is easiest to setup a test function in a new file (e.g. …

[1LP][RFR] Add miq command for updating qe-test-coverage flag and generating BZ reports

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_vmware_provider.py

__Adding tests__ for feature  DVSwitch displayed and tagging. 
Depends on merge of #8942 to fix Tagging UI. 
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py --use-provider complete -k 'test_vmware_vds_ui' }}

[RFR]Vds ui tests

---

cfme/tests/cloud_infra_common/test_relationships.py

@ganeshhubale pointed out that this `test_host_relationships` would sometimes fail on SCVMM providers. This is because not all of the hosts on SCVMM are clustered hosts. For the portion of the test that checks the `Cluster` link, if a host is unclustered, I have implemented a skip. 
@ganeshhubale, @jawatts and I discussed also passing in this case, since CFME is properly reporting the relationship for that particular host, i.e. that the host is not clustered. What do you think? 
{{ pytest: --use-provider scvmm --use-template-cache cfme/tests/cloud_infra_common/test_relationships.py::test_host_relationships }}

[RFR] Skip the cluster test if the host is unclustered

---

cfme/tests/infrastructure/test_vmware_provider.py

__Removing__ test for linked clones as the feature will be removed and is declared unreliable, hence makes no sense to test it any more **https://bugzilla.redhat.com/show_bug.cgi?id=1588908#c15**

[NOTEST][RFR]Removing test test_vmware_guests_linked_clone as this feature is no longer valid

---

cfme/common/__init__.py
widgetastic_manageiq/__init__.py

The previous locator worked fine until it hit "Quota - Max Memory" tag category, that has 2 spaces in the html source code.
So I added `normalize-space` to the selection and removal of the tag.
Thanks to @ganeshhubale for letting me know about that failure.
{{ pytest: -v cfme/tests/infrastructure/test_quota_tagging.py::test_quota_tagging_infra_via_lifecycle }}

[1LP][RFR] improved locator for ReactSelect

---

cfme/cloud/provider/openstack.py

The v3 keystone field is not displayed when keystone version v2 is selected.
Update OpenstackProvider.view_value_mapping to only include v3 attributes when using v3 endpoint.

[1LP][RFR] Update OpenstackProvider.view_value_mapping, v3 fields

---

cfme/utils/template/rhevm.py
requirements/frozen.py2.txt
requirements/frozen.py3.txt
requirements/frozen_docs.py2.txt
requirements/frozen_docs.py3.txt

Depends on wrapanapi: ~~https://github.com/ManageIQ/wrapanapi/pull/390~~

[1LP][RFR] Update template upload for rhevm, name database disk

---

cfme/infrastructure/provider/__init__.py
cfme/tests/control/test_basic.py

This test is breaking a lot of the basic control tests because it gets stuck on the edit alert profile page due to https://bugzilla.redhat.com/show_bug.cgi?id=1723815
{{ pytest: --long-running --use-template-cache cfme/tests/control/test_basic.py }}

[1LP][RFR] Block alert_profile_crud test due to BZ

---

cfme/infrastructure/virtual_machines.py
cfme/tests/infrastructure/test_vm_power_control.py

- This PR fixed ```Power``` dropdown xpath issue after getting disabled.
- Fixed error:
```
>           raise NoSuchElementException('Could not find an element {}'.format(repr(locator)))
E           NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator=u'.//div[contains(@class, "dropdown") and ./button[normalize-space(.)="VM Power Functions" or normalize-space(@title)="VM Power Functions"]]')
/var/ci/cfme_venv/lib/python2.7/site-packages/widgetastic/browser.py:347: NoSuchElementException
NoSuchElementException
Message: Could not find an element Locator(by='xpath', locator=u'.//div[contains(@class, "dropdown") and ./button[normalize-space(.)="VM Power Functions" or normalize-space(@title)="VM Power Functions"]]')
```
{{ pytest: …

[1LP][RFR] Fixed power dropdown 

---

cfme/tests/configure/test_proxy.py

{{ pytest: -v cfme/tests/configure/test_proxy.py::test_proxy_invalid  --use-provider=complete }}
Sometimes the test failed, I _guess_ because proxy settings are not taking effect immediately.
A simple "try again to refresh the provider" works and makes the test passed.

[1LP][RFR] fixed test_proxy_invalid

---

cfme/control/explorer/policies.py

In 5.11 this was changed to read "Physical Server", but it hasn't changed in 5.10
{{ pytest: --use-template-cache --long-running cfme/tests/control/test_basic.py::test_policy_crud }}

[RFR] Fix physical infra policy TREE_NODE for 5.11

---

cfme/tests/automate/test_automate_manual.py
cfme/tests/automate/test_method.py
cfme/utils/log_validator.py

- Testing whether quota check is done for once while provisioning services
- This line: ```Getting Tenant Quota Values for:``` should be visible once in automation logs
- Added ```match_count``` function in ```logvalidator```
Waiting for this PR #8918 
{{ pytest: cfme/tests/automate/test_method.py -k 'test_automate_service_quota_runs_only_once' -vv }}

[1LP][RFR] New Test: Tesing quota check while provisioning services

---

cfme/tests/infrastructure/test_publish_vm_to_template.py

Thanks @valaparthvi for pointing to this: templates were left on the provider after `test_publish_vm_to_template`.
{{ pytest: -v cfme/tests/infrastructure/test_publish_vm_to_template.py::test_publish_vm_to_template }}

[1LP][RFR] added template cleanup on provider

---

cfme/tests/cloud/test_tenant_quota.py
cfme/tests/infrastructure/test_tenant_quota.py

- This PR fixes root node not match error because of ```EntryPoint``` widget introduced.
- Error:
```
>                   'cause': 'Root node did not match {}'.format(self._repr_step(image, step))})
E               CandidateNotFound: path: ('M', 'a', 'n', 'a', 'g', 'e', 'I', 'Q', ' ', '(', 'L', 'o', 'c', 'k', 'e', 'd', ')', '/', 'I', 'n', 'f', 'r', 'a', 's', 't', 'r', 'u', 'c', 't', 'u', 'r', 'e', '/', 'V', 'M', '/', 'P', 'r', 'o', 'v', 'i', 's', 'i', 'o', 'n', 'i', 'n', 'g', '/', 'S', 't', 'a', 't', 'e', 'M', 'a', 'c', 'h', 'i', 'n', 'e', 's', '/', 'P', 'r', 'o', 'v', 'i', 's', 'i', 'o', 'n', 'R', 'e', 'q', 'u', 'e', 's', 't', 'A', 'p', 'p', 'r', 'o', 'v', 'a', 'l', '/', 'D', 'e', 'f', 'a', 'u', 'l', 't'), message: Could not find the item / in Boostrap tree automate_treebox, cause: Root …
```

[1LP][RFR] Fixed root node issue for entry point selection

---

cfme/tests/cloud/test_cloud_events.py
cfme/tests/control/test_actions.py

Blocking two tests due to BZs: 
https://bugzilla.redhat.com/show_bug.cgi?id=1531547
https://bugzilla.redhat.com/show_bug.cgi?id=1724312
These BZs impact `test_action_start_virtual_machine_after_stopping` and `test_vm_capture` respectively.

[RFR] Adding two blocking BZs to tests

---

cfme/tests/configure/test_log_depot_operation.py

The test actually works and I got them passed in 5.10.6.1
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_single_servers  --long-running }}

[1LP][RFR] make test_collect_single_servers work

---

cfme/tests/ansible/test_embedded_ansible_manual.py
cfme/tests/ansible/test_embedded_ansible_services.py

Removed few already automated tests `test_embed_tower_add_public_repo`  and added New test for `test_embed_tower_exec_play_stdout, test_embed_tower_enhanced_playbook_debug and test_service_ansible_verbosity` -->  Ansible Service with Verbosity.
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k test_service_ansible_verbosity -svvvv --long-running }}

[1LP][RFR] Automating Ansible Service Verbosity tests

---

cfme/intelligence/reports/schedules.py
cfme/tests/intelligence/reports/test_reports_schedules.py
widgetastic_manageiq/__init__.py

Changes:
1. New Test: test_reports_disable_enable_schedule_from_summary
[RHCFQE-11727](https://projects.engineering.redhat.com/browse/RHCFQE-11727)
2. Add a new widget `schedules_info`
3. Fix `get_text_of` which used to fail if the item had no value.
{{ pytest: cfme/tests/intelligence/reports/test_reports_schedules.py -k "test_reports_disable_enable_schedule" --use-template-cache -sqvvv }}

[1LP][RFR]New Test: test_reports_disable_enable_schedule_from_summary

---

cfme/common/__init__.py
cfme/configure/configuration/region_settings.py
cfme/fixtures/candu.py
cfme/fixtures/tag.py
cfme/tests/ansible/test_embedded_ansible_services.py
cfme/tests/ansible/test_embedded_ansible_tags.py
cfme/tests/automate/custom_button/test_cloud_objects.py
cfme/tests/automate/custom_button/test_container_objects.py
cfme/tests/automate/custom_button/test_generic_objects.py
cfme/tests/automate/custom_button/test_infra_objects.py
cfme/tests/automate/custom_button/test_service_objects.py
cfme/tests/cloud/test_keypairs.py
cfme/tests/cloud_infra_common/test_provisioning.py
cfme/tests/cloud_infra_common/test_tag_objects.py
cfme/tests/infrastructure/test_config_management.py
cfme/tests/infrastructure/test_vmware_provider.py

Don't set the Tag.name attribute to the Category.display_name
Update test_vmware_vds_ui_tagging
Update add_tag to check for tag existing already
Marking RFR as PRT run 32832 passed `test_vmware_vds_ui_tagging`.  Including the test_tag_objects module as well for a broader run.
{{ pytest: cfme/tests/infrastructure/test_vmware_provider.py::test_vmware_vds_ui_tagging cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/infrastructure/test_config_management.py::test_config_system_tag cfme/tests/infrastructure/test_config_management.py::test_ansible_tower_job_templates_tag cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_tag cfme/tests/automate/custom_button/test_generic_objects.py cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_expres …

[1LP][RFR] Update Taggable.get_tags
