ManageIQ/integration_tests

cfme/tests/v2v/test_v2v_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running -k test_migration_with_edited_mapping}}
Test migration with edited mapping test case .
=> [RFR]Test migration with edited mapping

cfme/services/catalogs/catalog_items/__init__.py
{{pytest: cfme/tests/services/test_generic_service_catalogs.py::test_bundles_in_bundle --long-running -vvv}}
=> [RFR]Fixed flash assertion error for catalog items

cfme/tests/networks/test_network_providers.py
Update "test_network_provider_add_with_bad_credentials" test with new
warning about failed login.
\cc @miha-plesko, @mshriver
=> [1LP][RFR] Update "test_network_provider_add_with_bad_credentials" test

cfme/base/__init__.py, cfme/base/ui.py, cfme/tests/cloud/test_cloud_timelines.py
My own regression from Server.name property implementation.
{{ pytest: --long-running --use-provider complete cfme/tests/cloud_infra_common/test_relationships.py cfme/tests/cloud_infra_common/test_tag_objects.py cfme/tests/networks/test_tag_tagvis.py }}
=> [1LP][RFR] Fix instantiation of server in ServerCollection.all()

cfme/tests/services/test_catalog_item.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_permissions_catalog_item_add --long-running -vvv}}
=> [1LP][RFR]Fixed permissions service catalog item

cfme/tests/automate/custom_button/test_buttons.py
automating BZ-1646905
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_quotes -v}}
=> [1LP][RFR] CB: test check quotes

cfme/storage/volume.py, cfme/tests/openstack/cloud/test_volumes.py
Add test: test_volume_attach_detach_instance
{{ pytest: cfme/tests/openstack/cloud/test_volumes.py::test_volume_attach_detach_instance }}
=> [1lP][RFR] Add test_volume_attach_detach_instance

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Updates to newest version of manageiq-client.
This version fixes issue https://github.com/ManageIQ/manageiq-api-client-python/issues/42 reported by @Yadnyawalkya 
{{pytest: -vv cfme/tests/test_rest.py}}
=> [RFR] Update manageiq-client

cfme/cloud/tenant.py, cfme/networks/network_router.py, cfme/networks/subnet.py, cfme/networks/views.py, cfme/tests/networks/nuage/test_inventory.py
This test creates sandbox with Nuage cloud tenant and its entities. We then navigate to Cloud tenant's subnets through provider, where we compare UI stats with sandbox stats. 
We are testing both L3 and L2 subnets. The difference is that, L3 subnets are always connected to network router while L2 subnets arent.
Depends on: https://github.com/ManageIQ/integration_tests/pull/8115
Please review second commit as the first is different PR.
\cc @miha-plesko
=> [RFR] Test cloud subnet details

sprout/appliances/tasks.py
fixed two issues in sprout: 
1. false mark for some vms as orphaned; 
2. wrapanapi 3.0 uuid->name issue
=> [1LP][RFR] fix sprout issues

cfme/services/catalogs/catalog_items/__init__.py
{{ pytest: cfme/tests/services/test_catalog_item.py::test_catalog_item_crud --long-running -v }}
=> [RFR]Fix test catalog item crud

notebooks/BasicApplianceSetup.ipynb, notebooks/Browser Session.ipynb, notebooks/Interaction with Timelines Notebook.ipynb, notebooks/SSUI Login.ipynb
just change `utils` import to `cfme.utils`. 
Those are basic notebooks for cfme...
=> [1LP][RFR][NOTEST] update cfme.utils for basic Notebooks

cfme/tests/automate/custom_button/test_infra_objects.py
- Added test for open url functionality
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_open_url -vvv}}
=> [1LP][RFR] CB: Added test for open url

cfme/tests/configure/test_access_control.py, cfme/tests/test_manual.py
=> [1LP][RFR] Moving manual multi-tenancy test

conf/polarion_tools.yaml, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Adds config file so the flake8 plugin installed in polarion_docstrings can check the Polarion metadata values.
=> [RFR] Adds config for polarion docstrings flake8 plugin

cfme/automate/explorer/method.py, cfme/tests/ansible/test_embedded_ansible_crud.py, cfme/utils/appliance/__init__.py
{{pytest: --long-running --use-template-cache --use-provider=cm-pod2 cfme/tests/ansible}}
=> [1LP][RFR] fix ansible tests  against pod appliance

cfme/infrastructure/config_management.py
{{pytest: --long-running --use-template-cache -k test_config_manager_edit[satellite_62]  cfme/tests/infrastructure/test_config_management.py}}
=> [1LP][RFR] Fix config management test

cfme/tests/infrastructure/test_datastore_analysis.py
{{pytest: --use-provider=complete --use-template-cache --long-running cfme/tests/infrastructure/test_datastore_analysis.py }}
=> [1LP][RFR] fixing datastore analysis tests

widgetastic_manageiq/expression_editor.py
{{pytest: --long-running --use-template-cache -k test_modify_condition_expression cfme/tests/control/test_basic.py}}
fixed tests failing on attempt to fill count form due to delay in element appearance
=> [1LP][RFR] fix test_modify_condition_expression_test

cfme/tests/ssui/test_ssui_service_dialog.py
{{ pytest: cfme/tests/ssui/test_ssui_service_dialog.py::test_tag_dialog_catalog_item_ssui -v }}
=> [1LP][RFR] Adding a new test to test required dialog element in ssui order page

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_service_objects.py
- Automated BZ-1653193
- Added BZ-1659452
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_text_display -vv}}
=> [1LP][RFR] CB: display on test

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vm_reconfigure.py, widgetastic_manageiq/vm_reconfigure.py
- Part of https://github.com/ManageIQ/integration_tests/issues/6996
- Fixed VMReconfiguration table
- Added related changes  in vm model page
- remove blocker from test
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_disk_cold -v --long-running}}
=> [RFR] Fix VM  reconfigure disk related things

cfme/tests/containers/test_blacklisted_container_events.py
{{ pytest:: cfme/tests/containers/test_blacklisted_container_events.py --use-provider ocp-36-hawk }}
=> [RFR] Containers: New test case for Blacklisting Container Events

cfme/control/explorer/alerts.py
{{ pytest: cfme/tests/control/test_basic.py -k test_control_alert_copy -v --use-provider complete }}
Fixed Error:
```
>           raise TimedOutError("Could not do {} at {}:{} in time".format(message, filename, line_no))
E           TimedOutError: Could not do Waiting for view [NewAlertView] to display at /var/ci/workspace/ds59z-tests-new-image/integration_tests/cfme/utils/appliance/implementations/ui.py:562 in time
../cfme_venv/lib/python2.7/site-packages/wait_for/__init__.py:180: TimedOutError
TimedOutError
Could not do Waiting for view [NewAlertView] to display at /var/ci/workspace/ds59z-tests-new-image/integration_tests/cfme/utils/appliance/implementations/ui.py:562 in time
```
=> [1LP][RFR] Fixed is_displayed of NewAlertView

cfme/tests/infrastructure/test_rest_templates.py
1. Delete the templates that were created during test runs.
Test case responsible: [test_rest_templates.py](https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/infrastructure/test_rest_templates.py#L30)
Teardown code for `template` fixture did not work well, causing failed template deletion. Also, using API to delete template only deletes it from the appliance inventory and not from the actual provider. Using wrapanapi instead, to delete the template from provider.
{{ pytest: cfme/tests/infrastructure/test_rest_templates.py::test_set_ownership --use-template-cache -sqvvv }}
=> [RFR] Add fix to delete vm templates created during rest tests

cfme/tests/cloud_infra_common/test_relationships.py
{{ pytest: -v cfme/tests/cloud_infra_common/test_relationships.py::test_host_refresh_relationships }}
I created this test in response to https://bugzilla.redhat.com/show_bug.cgi?id=1658240
=> [1LP][RFR] new test_host_refresh_relationships

cfme/services/myservice/ssui.py
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_retire_service_ssui --use-provider vsphere67-nested --long-running -svvv }}
=> [1LP][RFR] Fix test retire service ssui

cfme/automate/buttons.py
1. Bug having hover and image mismatch found by @sbulage https://github.com/ManageIQ/integration_tests/issues/8346
2. Refactor model removed some 5.8 requirements added arguments etc...
3. Blackify
{{pytest: cfme/tests/automate/custom_button/ -v}}
FIXES #8346
=> [RFR] Button model [bug + refactor + blackify]

cfme/automate/buttons.py, cfme/services/myservice/ui.py, cfme/tests/automate/custom_button/__init__.py, cfme/tests/automate/custom_button/test_service_objects.py, cfme/tests/test_manual.py
Adding test for enablement and visibility for Service
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_expression -vv}}
=> [1LP][RFR] CB: Visibility/Enablement service

cfme/tests/test_db_migrate_manual.py
The related bugs vere fixed for 5.10. So this case should start in 5.10
https://bugzilla.redhat.com/show_bug.cgi?id=1478986
https://bugzilla.redhat.com/show_bug.cgi?id=1561075
=> [RFR] Fix startsin in test_upgrade_dedicated_db_migration_local

cfme/utils/template/rhopenshift.py
This PR intends to add external db template upload to openshift. It is necessary for testing external db pod appliance.
=> [1LP][RFR] external database template upload

conf/polarion_tools.yaml
=> [NOTEST] added custom_button casecomponent

cfme/tests/networks/test_sdn_downloads.py
=> [1LP][RFR] Fix assignee of  test_download_lists_base

cfme/tests/automate/custom_button/test_buttons.py, cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_container_objects.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_import_export.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/automate/custom_button/test_rest.py, cfme/tests/automate/custom_button/test_service_objects.py, cfme/tests/test_manual.py
-  Moved custom button manuals to respective file with `manual` tag
- Deleted already automated manual tests
- Improved polarion tags
=> [1LP][RFR] Manual Custom button

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_container_objects.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/automate/custom_button/test_service_objects.py
- some error in cloud expression test for custom button it will  fix that.
- remove wait for view
{{pytest: cfme/tests/automate/custom_button/ -k "test_custom_button_expression"}}
=> [1LP][WIP] CB: Expression fix

cfme/infrastructure/virtual_machines.py
{{ pytest: -v cfme/tests/infrastructure/test_vm_reconfigure.py::test_vm_reconfig_add_remove_disk_cold  --long-running }}
As written here https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/infrastructure/test_vm_reconfigure.py#L111
disk modes are not supported for RHV
=> [1LP][RFR] Disk modes cannot be specified when adding disk to VM in RHV provider

cfme/common/__init__.py, cfme/common/provider.py, cfme/common/vm.py, cfme/infrastructure/cluster.py, cfme/infrastructure/datastore.py, cfme/infrastructure/host.py, cfme/tests/automate/custom_button/test_infra_objects.py
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_events -v}}
=> [1LP][RFR] CB events infra object and Mixing

scripts/sync_template_tracker.py
extdb templates shouldn't be removed as it happens to other templates ending with db
=> [1LP][RFR] long live extdb templates

cfme/tests/containers/test_blacklisted_container_events.py, cfme/utils/appliance/__init__.py
REST API is available in 5.9, use this for the GET/POST of advanced settings instead of rails.
{{ pytest:  cfme/tests/platform/test_advanced_config.py --use-provider complete }}
=> [RFR] Only use REST API for GET/POST of Advanced Settings

cfme/networks/views.py, cfme/tests/networks/test_sdn_downloads.py
This PR is fixing change in 5.10 where pdf instead of being downloaded is displayed as popup tab.
Also setting importance from high to medium.
@lina-nikiforova Maybe I should reassign these test cases to you?
=> [1LP][RFR] pdf download popup fix

cfme/tests/pod/test_appliance_crud.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt
REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/356
=> [1LP][RFR] extdb pod smoke tests

cfme/tests/infrastructure/test_vm_reconfigure.py, cfme/tests/test_manual.py
1. Moved my tests from manual.py to my vm reconfigure test files
=> [1LP][RFR] Manual vm reconfigure cleanup

cfme/tests/containers/test_pause_resume_workers.py
{{ pytest: cfme/tests/containers/test_pause_resume_workers.py --use-provider ocp-36-hawk }}
=> [1LP][RFR] Fix Container Provider Pause/Resume Test

cfme/tests/v2v/test_post_migrations.py
__Adding tests__ for feature X to cover cases in product version 5.10.0.27, 5.9.6.3.
{{pytest: cfme/tests/v2v/test_post_migrations.py -k test_migrations_vm_attributes --use-provider rhv42 --use-provider vsphere65-nested --provider-limit 2 -vvvv }}
=> [1LP][RFR] Tests to check post migration vm attributes

cfme/tests/generic_objects/test_instances.py
changed the test owner as it belongs to `rest` FA
=> [1LP][RFR] changed the owner of test_generic_objects_tag_rest

cfme/tests/configure/test_access_control.py
Automating Multi-Tenancy Test Case RHCF3-35087: test_superadmin_child_tenant_delete_parent_catalog
{{ pytest: cfme/tests/configure/test_access_control.py::test_superadmin_child_tenant_delete_parent_catalog --use-template-cache }}
=> [1LP][RFR] Automating test_superadmin_child_tenant_delete_parent_catalog

cfme/cloud/availability_zone.py, cfme/cloud/security_groups.py, cfme/networks/cloud_network.py, cfme/networks/network_router.py, cfme/networks/security_group.py, cfme/networks/subnet.py, cfme/storage/manager.py, cfme/storage/object_store_container.py, cfme/storage/volume.py, cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_infra_objects.py
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py -k test_custom_button_events -v --use-provider complete}}
=> [1LP][RFR] CB: Event cloud objects

cfme/fixtures/v2v.py, cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py, cfme/tests/v2v/test_csv_import.py, cfme/tests/v2v/test_post_migrations.py, cfme/tests/v2v/test_v2v_ansible.py, cfme/tests/v2v/test_v2v_cancel_migrations.py, cfme/tests/v2v/test_v2v_migrations.py, cfme/tests/v2v/test_v2v_migrations_single_vcenter.py, cfme/tests/v2v/test_v2v_migrations_ui.py, cfme/tests/v2v/test_v2v_schedule_migrations.py
1) Edited v2v.py to change scope of providers to module as it takes lot of time to set up providers for each test . SO now the providers and all the set up will be done once for each test file.
2) Renamed second_provider to source_provider
3) Formatting 
4) Changed all tests for scope .
=> [1LP][RFR] V2V fixture file

cfme/tests/storage/test_manager.py
Co-authored-by: Matous Mojzis <mmojzis@redhat.com>
- adding support for ec2 storage manager 
- blackify test file
{{pytest: cfme/tests/storage/test_manager.py -v}}
=> [1LP][RFR] Adding support of ec2

cfme/tests/ansible/test_embedded_ansible_crud.py
PRT run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_crud.py -qsvvv }}
=> [1LP][RFR] Fixes Ansible crud test.

cfme/tests/infrastructure/test_scvmm_specific.py, cfme/tests/test_manual.py
Move manual cases from `test_manual` to `test_scvmm_specific`. Also removing test cases which are automated (`test_retirement`) and removing manual cases that are already in integration tests.
=> [1LP][RFR] Moving SCVMM manual cases

cfme/tests/v2v/test_rest_migrations.py
__Adding tests__ for feature X to cover cases Y and Z. They were implemented in product version 5.10.0.27, 5.9.6.5.
{{pytest: cfme/tests/v2v/test_rest_migrations.py --use-provider vsphere65-nested --use-provider rhv42 --provider-limit 2 -vvvv}}
=> [1LP][RFR] Added rest migrations tests

cfme/tests/candu/test_azone_graph.py, cfme/tests/candu/test_utilization_metrics.py
{{pytest: cfme/tests/candu/test_host_graph.py --use-provider azure }}
=> [1LP][RFR] Adding BZ blocker for Azure

cfme/tests/cloud_infra_common/test_relationships.py
{{ pytest: -v cfme/tests/cloud_infra_common/test_relationships.py::test_tagvis_cloud_provider_children   --use-provider=complete }}
As `OpenStack` provider is currently disabled, `test_tagvis_cloud_provider_children` was not executed at all. So I'm adding a second provider.
=> [1LP][RFR] added second provider to test_tagvis_cloud_provider_children

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
template test and upload scripts for rhevm are broken. Fixing that issue
=> [RFR] fix rhevm template scripts

cfme/tests/services/test_config_provider_servicecatalogs.py
I have parameterized  the existing tests so that the tests can be run for Ansible Workflow jobs as well.
PRT results 
59 - PASSED
510 - PASSED
=> [1LP][RFR] Adding tests for Ansible Workflow jobs

cfme/tests/storage/test_manager.py
Added test_storage_manager_navigation_from_cloudprovider automated test and caseimportance.
It should whether Storage Manager is accessible from Cloud Provider
@digitronik Please review
=> [1LP][RFR] Added test_storage_manager_navigation_from_cloudprovider

cfme/tests/cloud_infra_common/test_events.py
Assigning `test_vm_create` to myself.
=> [1LP][RFR] Reassign test_vm_create to jdupuy

cfme/tests/candu/test_vm_graph.py
{{pytest: cfme/tests/candu/test_vm_graph.py --use-provider azure }}
=> [1LP][RFR] Adding BZ blocker for Azure candu graph tests

cfme/automate/buttons.py, cfme/base/ui.py, cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_simulation -v}}
=> [1LP][RFR] CB: Simulation

cfme/scripting/quickstart/system.py, cfme/scripting/tests/test_quickstart.py
{{ pytest: cfme/scripting/tests/test_quickstart.py::test_quickstart_run }}
=> [1LP][RFR] fixing quickstart tests

cfme/utils/browser.py
Ref: https://github.com/RedHatQE/cfme_dockerfiles/pull/11
=> [1LP][RFR] a few useful chrome browser options

cfme/fixtures/rdb.py, data/bundles/merkyl/__init__.py, scripts/gh-find.py
=> [RFR] Fixed prints

widgetastic_manageiq/__init__.py
Added some widgets for v2v.
Black formatted some data
=> [RFR]V2V widgets

cfme/intelligence/reports/dashboards.py, cfme/intelligence/reports/reports.py, cfme/intelligence/reports/widgets/__init__.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/intelligence/test_dashboard.py, cfme/utils/bz.py
__Fixing__ test_menuwidget_crud.
There were some typo-like mishaps.
{{ py.test: cfme/tests/intelligence/reports/test_crud.py }}
=> [1LP][RFR] Fix dashboard tests

cfme/cloud/provider/__init__.py, cfme/cloud/provider/azure.py, cfme/cloud/provider/ec2.py, cfme/cloud/provider/gce.py, cfme/cloud/provider/openstack.py, cfme/cloud/provider/vcloud.py, cfme/common/provider.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/infrastructure/provider/__init__.py, cfme/infrastructure/provider/kubevirt.py, cfme/infrastructure/provider/openstack_infra.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/scvmm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/networks/provider/__init__.py, cfme/networks/provider/nuage.py, cfme/physical/provider/__init__.py, cfme/physical/provider/lenovo.py, cfme/physical/provider/redfish.py
{{ pytest: --long-running --use-template-cache -k 'smoke or test_ipappliance_managed_providers ' cfme }}
=> [1LP][RFR] fixing broken provider object comparison

cfme/scripting/quickstart/system.py, cfme/scripting/tests/test_quickstart.py
{{ pytest: cfme/scripting/tests/test_quickstart.py::test_quickstart_run --long-running}}
=> [1LP][RFR] fixed permissions issue and ubuntu version in quickstart scripts and tests 

cfme/tests/test_manual.py
- This PR removes all the manual test cases assigned to me: ```assignee: ghubale```
- As these test cases are distributed on the basis of their focus areas by PR #8391
=> [1LP][RFR][NOTEST] Removed manual tests from test_manual.py file

cfme/tests/cli/test_appliance_log_rotate.py, cfme/tests/test_appliance.py
__Adding tests__ for logrotate on appliance.
=> [1LP][RFR] Add logrotate tests.

cfme/control/explorer/alerts.py, cfme/tests/control/test_bugs.py
Automating test-coverage for [BZ 1658670](https://bugzilla.redhat.com/show_bug.cgi?id=1658670)
{{ pytest: --long-running cfme/tests/control/test_bugs.py::test_alert_for_disk_usage }}
=> [1LP][RFR] Add in automation test-coverage for BZ 1658670

cfme/tests/configure/test_workers.py
Adding in a automated test case for a BZ.
https://bugzilla.redhat.com/show_bug.cgi?id=1656873
{{ pytest: --long-running cfme/tests/configure/test_workers.py::test_set_memory_threshold_in_ui }}
=> [1LP][RFR] Add test cases for BZ

cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py, cfme/tests/test_manual.py
- Moved Manual Tests to respective automated folder.
=> [1LP][RFR] This will separate manual_tests

cfme/services/myservice/ui.py, cfme/tests/services/test_myservice.py
{{pytest: cfme/tests/services/test_myservice.py -k test_retire_service_on_date --long-running --use-provider vsphere6-nested -v}}
=> [1LP][RFR]Fix is_displayed for service retirement date

cfme/tests/containers/test_overview_data_integrity.py
Adding new manual test case of the node utilization graphs on the Container provider dashboard.
=> [1LP][RFR] Add new manual test case for Node Utlization graphs

cfme/tests/automate/test_service_dialog.py, cfme/tests/services/test_catalog.py, cfme/tests/services/test_catalog_item.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_request.py, cfme/tests/services/test_rest_services.py, cfme/tests/services/test_service_manual_approval.py, cfme/tests/ssui/test_ssui_ansible_service.py, cfme/tests/ssui/test_ssui_dashboard.py, cfme/tests/ssui/test_ssui_myservice.py, cfme/tests/ssui/test_ssui_service_catalogs.py, cfme/tests/ssui/test_ssui_service_dialog.py
1. Reassigning assignee
2. Added casecomponent
3. Added tags
=> [1LP][RFR]Tests ssui/services tests cleanup

cfme/cloud/instance/azure.py, cfme/cloud/instance/openstack.py, cfme/tests/cloud_infra_common/test_provisioning.py
provisioning request in 5.10 doesn't skip email now. + one more comparison fix
UPD: added fix for osp tenant issue
=> [1LP][RFR] fix provisioning tests

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt, requirements/template_docs.txt
selenium server version is 3.14 whilst client is 3.12.  That's definitely wrong. we need to change both versions together.
=> [1LP][RFR] bump selenium client version to selenium server version

cfme/cloud/provider/vcloud.py, cfme/containers/provider/__init__.py, cfme/networks/balancer.py, cfme/networks/cloud_network.py, cfme/networks/floating_ips.py, cfme/networks/network_port.py, cfme/networks/network_router.py, cfme/networks/provider/__init__.py, cfme/networks/provider/nuage.py, cfme/networks/security_group.py, cfme/networks/subnet.py
Removing the `in_version` variable.
=> [1LP][RFR] Remove the in_version variable, as it is unused

cfme/cloud/availability_zone.py, cfme/networks/cloud_network.py, cfme/storage/object_store_container.py, cfme/tests/automate/custom_button/test_cloud_objects.py
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py::test_custom_button_events -vv}}
=> [1LP][RFR] Fix event cloud object test

cfme/automate/explorer/domain.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_domain.py, cfme/tests/automate/test_namespace.py
{{ pytest: cfme/tests/automate/ -k 'test_wrong_namespace_name or test_wrong_domain_name' -v }}
=> [1LP][RFR] This test for checking invalid name of namespaces

cfme/services/catalogs/orchestration_template.py, cfme/tests/services/test_orchestration_template.py
{{pytest: cfme/tests/services/test_orchestration_template.py  -v}}
one test failing test_orchestration_template.py::test_copy_template[vapp]
I have raised BZ for that 1684479
=> [RFR] Fix orchestration template test

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_buttons.py, widgetastic_manageiq/__init__.py
- Added `MutiBoxOrderedSelect` selection widget in `wt.miq`
- Enhance Button group create method with selection
- Added new test for  checking ordered changes
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_order_sort -v}}
=> [1LP][RFR] Group enhancement

cfme/intelligence/reports/widgets/__init__.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/intelligence/reports/test_widgets.py
This tests case checks  whether content of dashboard widget is generated using via automate method.
{{ pytest: cfme/tests/intelligence/reports/test_widgets.py -k 'test_generate_widget_content_by_automate' -v }}
=> [1LP][RFR] Testing generate widget content using auotmate method

cfme/tests/infrastructure/test_snapshot.py
{{ pytest: -v cfme/tests/infrastructure/test_snapshot.py::test_create_without_description --long-running }}
NOTE: here I applied the same changes as in #8516 to get rid of the scope mismatch.
In `5.10` there's no longer error message to check for as "Create" button is simply disabled if there's no description.
=> [1LP][RFR] fixed test_create_without_description for 5.10

cfme/tests/automate/test_automate_manual.py, cfme/tests/test_manual.py
- Added new manual test cases for ```auotmate``` FA
- BZ: [1684417](https://bugzilla.redhat.com/show_bug.cgi?id=1684417) is closed as not a bug hence removed related test case.
=> [1LP][RFR][NOTEST] Added new manual test case

cfme/utils/template/base.py
So that a re-run of template upload will create the trackerbot record if it failed the first time, or got removed for whatever reason
=> [RFR] Update template upload to call trackerbot API if template already exists

cfme/fixtures/v2v_fixtures.py, cfme/test_framework/pytest_plugin.py, cfme/tests/v2v/test_infrastructure_mapping.py, cfme/v2v/infrastructure_mapping.py, entry_points.txt
{{ pytest: cfme/tests/v2v/test_infrastructure_mapping.py --use-provider vsphere67-ims --use-provider rhv42 --provider-limit 2 --long-running }}
=> [1LP][RFR] Infra mapping

cfme/ansible/credentials.py
{{ pytest: --long-running --use-template-cache cfme/tests/ansible/test_embedded_ansible_basic.py::test_embedded_ansible_credential_crud }}
=> [1LP][RFR] fixed no such element in ansible credentials

cfme/tests/configure/test_access_control.py
=> [1LP][RFR][NOTEST] Refactoring polarion metadata and adding tag

cfme/tests/cloud_infra_common/test_provisioning_manual.py
`test_service_provision_azure` is automated:
https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/services/test_cloud_service_catalogs.py#L35
=> [1LP][NOTEST][RFR] deleted duplicate test test_service_provision_azure

cfme/automate/__init__.py, cfme/automate/dialogs/dialog_element.py, cfme/tests/automate/test_service_dialog.py
- fix tear-down for `test_service_dialog_duplicate_name`. 
- fix flash
- small formatting.
{{pytest: cfme/tests/automate/test_service_dialog.py -v}}
=> [1LP][RFR] fix teardown dialog

cfme/tests/control/test_basic.py, cfme/tests/control/test_bugs.py, cfme/tests/control/test_compliance.py, cfme/tests/control/test_export_policies.py, cfme/tests/control/test_import_policies.py, cfme/tests/control/test_smoke_control.py, cfme/tests/test_manual.py
Bulk reassign of control test cases to myself. Also moving some leftover manual cases.
=> [1LP][RFR][NOTEST] Reassign control tests and move manual cases

cfme/services/catalogs/orchestration_template.py, cfme/tests/services/test_provision_stack.py, data/orchestration/rhos13_vm_template.data
{{pytest: cfme/tests/services/test_provision_stack.py  -v}}
=> [RFR]Fix provision stack tests

cfme/scripting/miq.py, cfme/scripting/polarion.py, conf/polarion_tools.local.yaml.template, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Add miq polarion, template for polarion_tools.local.yaml
Update requirements for ruamel.yaml and polarion
Make casecomponent required for polarion docblocks
=> [1LP][RFR] Add miq polarion, template for polarion_tools.local.yaml

cfme/services/catalogs/catalog.py
{{pytest: cfme/tests/services/test_catalog.py -k  test_catalog_crud -v}}
=> [1LP][RFR] Fix assert view.is_displayed for catalog

cfme/cloud/availability_zone.py, cfme/cloud/provider/ec2.py, cfme/tests/candu/test_azone_graph.py
Some of the locators are different on the Utilization page of the EC2 Availability zone.The tests were failing because of that. I have fixed the locators for ec2.
PRT results:
59 - PASSED
510 - PASSED
=> [1LP][RFR] Fix azone utilization views

cfme/fixtures/cli.py
Same as #8559, different fixture.
=> [RFR] Update cli fixture get_apps method, lookup sprout user key from config

requirements/frozen.py2.txt, requirements/frozen.py3.txt
3.0.43 includes fix to default GCE account credentials type
=> [RFR] Update wrapanapi

cfme/tests/ansible/test_embedded_ansible_services.py, cfme/utils/providers.py, cfme/utils/ssh.py
It should fix test_evmserverd_stop test.
in addition, this PR fixes a few tiny code style issues.
{{pytest: cfme/tests/cli/test_evmserverd.py::test_evmserverd_stop}}
=> [RFR] fixed parsing process status

cfme/control/explorer/conditions.py, cfme/tests/control/test_bugs.py
Adding a new automated test for [BZ 1683697](https://bugzilla.redhat.com/show_bug.cgi?id=1683697). 
{{ pytest: --use-template-cache cfme/tests/control/test_bugs.py::test_accordion_after_condition_creation }}
=> [1LP][RFR] Test coverage for BZ 1683697

cfme/tests/infrastructure/test_vmware_provider.py, cfme/tests/test_manual.py
__Adding tests__ new VMware Manual Tests.
=> [RFR][NOTEST]Adding/updating VMware manual tests

cfme/automate/buttons.py, cfme/infrastructure/networking.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/webui/test_splitter.py, entry_points.txt
- Networking model changes move to specific entity `switch`
- Added support for `switch` object in custom button
- Address to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1685555
{{pytest: cfme/tests/automate/custom_button/test_infra_objects.py cfme/tests/webui/test_splitter.py -k "Switch or InfraSwitchesCollection" -vv}}
=> [1LP][RFR] Networking Switch

cfme/tests/automate/custom_button/__init__.py, cfme/tests/automate/custom_button/test_service_objects.py
- Automating manual test of custom button dialog execution. 
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_dialog -v}}
=> [RFR] test_custom_button_dialog

cfme/tests/control/test_actions.py
Reassigning some more control test cases.
=> [1LP][RFR] Reassign test cases from mmojzis to jdupuy

cfme/utils/appliance/__init__.py
=> [1LP][RFR] docblock for create_view

cfme/automate/explorer/instance.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_domain_priority.py
- Added ```Text``` widget for reading domain priority status
{{ pytest: cfme/tests/automate/test_domain_priority.py -k 'test_automate_disabled_domains_in_domain_priority' -vv }}
=> [1LP][RFR] New test: Checking 'Disabled' domain on instance' detail's page

cfme/automate/buttons.py, cfme/cloud/tenant.py, cfme/common/__init__.py, cfme/services/catalogs/__init__.py, docs/guides/dev_guide.rst
- It will help to avoid confusion. 
- Lets use same `TODO` style for overall repo.
- Added small point in our guide
Reference:
code tags: https://www.python.org/dev/peps/pep-0350/#id30
Google code style: http://google.github.io/styleguide/pyguide.html
{{pytest: cfme/tests/cloud/test_tenant.py::test_tenant_crud -v}}
=> [RFR] TODO consistency 

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt, sprout/requirements.txt
=> [WIPTEST][NOTEST] freezing miq-version support for py2

requirements/template_docs.txt
=> Update deepdiff in template_docs.txt

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_instance.py
- This test cases checks relationship value of instance with trailing spaces.
- Removed test ```test_quota_source``` because it is already automated in quota FA
{{ pytest: cfme/tests/automate/test_instance.py -k 'test_automate_relationship_trailing_spaces' -vv }}
=> [1LP][RFR] New Test: Checking relationship value with trailing spaces

cfme/common/__init__.py, cfme/containers/container.py, cfme/containers/image.py, cfme/containers/image_registry.py, cfme/containers/node.py, cfme/containers/pod.py, cfme/containers/project.py, cfme/containers/provider/__init__.py, cfme/containers/provider/openshift.py, cfme/containers/template.py
Rebasing a contribution from @shalomnaim1 from #7391 to update to our current master.
{{ pytest: --long-running --use-provider cmqe --use-provider onprem -vvvv cfme/tests/cloud_infra_common/test_tag_objects.py  cfme/tests/cloud_infra_common/test_tag_visibility.py }}
=> [1LP][RFR] Add TaggableCollection, update containers smart tag tests

cfme/tests/services/test_config_provider_servicecatalogs.py
Added a test for Ansible template jobs with surveys
=> [1LP][RFR] Automate test for Ansible template job with survey

cfme/tests/automate/custom_button/test_service_objects.py, cfme/tests/configure/test_access_control.py, cfme/tests/test_manual.py
1. Move multi-tenancy test to respective file and change owner
2. Remove one test as its cover with other.
=> [1LP][RFR] ndhandre manual move

requirements/frozen.py2.txt, requirements/frozen.py3.txt, scripts/ec2cleanup.py
Depends on https://github.com/ManageIQ/wrapanapi/pull/345
=> [RFR] This PR will add deletion of S3 buckets for cleanup script.

cfme/tests/ansible/test_embedded_ansible_basic.py
=> [1LP][RFR][NOTEST] Change assignee of ansible control tests

cfme/services/myservice/ui.py
Fixes #8610 
{{pytest: cfme/tests/services/test_myservice.py --long-running -v}}
=> [1LP][RFR] move tree selection to entity

cfme/utils/dockerbot/pytestbase/get_keys.py
temporary solution for PRT until we move it to openshift
=> [1LP][RFR] randomly get keys and try to servers

cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/automate/custom_button/test_service_objects.py
Fix flash
{{pytest: cfme/tests/automate/custom_button -k "test_custom_button_automate" -v}}
=> [1LP][RFR] CB: change in flash msg

cfme/tests/automate/test_customization_paginator.py, cfme/tests/cloud/test_stack.py, cfme/tests/configure/test_paginator.py, cfme/tests/services/test_catalog_item.py
Here I renamed the duplicate tests cases
```
test_paginator
test_edit_tags
```
to avoid them being identified as duplicates for polarion upload.
=> [RFR][NOTEST] resolved duplicate test cases

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_infrastructure_mapping.py, cfme/v2v/infrastructure_mapping.py
{{ pytest: cfme/tests/v2v/test_infrastructure_mapping.py --use-provider osp13-ims --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running }}
=> [1LP][RFR] Added plan_type in Infra Mapping

cfme/cloud/instance/__init__.py, cfme/common/vm_views.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud_infra_common/test_policy_simulation.py, cfme/tests/control/test_basic.py, widgetastic_manageiq/__init__.py
Adding test coverage for Cloud/Infra policy simulation page for vms/instances. There are quite a few bugs associated with this page, so this test is designed to cover those [BZs](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=VERIFIED&bug_status=ASSIGNED&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=RELEASE_PENDING&bug_status=POST&email1=jdupuy%40redhat.com&emailassigned_to1=1&emailcc1=1&emailreporter1=1&emailtype1=exact&list_id=10025319). 
{{ pytest: --use-provider complete cfme/tests/cloud_infra_common/test_policy_simulation.py }}
=> [1LP][RFR] Add in policy simulation test case

conf/supportability.yaml
Define supportability.yaml in integration_tests to specify what MIQ supports.
=> [RFR] Add supportability.yaml for MIQ master

cfme/fixtures/service_fixtures.py, cfme/services/catalogs/catalog_items/__init__.py, cfme/tests/automate/custom_button/test_catalog_custom_button.py, cfme/tests/automate/custom_button/test_service_objects.py
{{pytest: cfme/tests/automate/custom_button/test_catalog_custom_button.py -v}}
=> [1LP][RFR] Cb catalog Buttons

cfme/storage/object_store_container.py, cfme/storage/object_store_object.py
- Refactor model pages
- Used get_entity method as JS API issue (#2898) resolve.
- Remove tag navigation as mixing now capable of it.
- Moved containers all method to rest but for object we con't due to rest collection not available for it.
{{pytest: cfme/tests/storage/test_object_store_object.py cfme/tests/storage/test_object_store_container.py -v}}
=> [1LP][RFR] Storage Container and Object changes.

cfme/cloud/provider/__init__.py, cfme/cloud/provider/ec2.py, cfme/common/provider.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis.py, cfme/tests/pod/test_appliance_crud.py
podified appliance buids are shipped with smartstate image for aws. This image has to be smoke tested.
This PR should introduce smoke tests for aws image 
REQUIRES: https://github.com/ManageIQ/wrapanapi/pull/358
{{ pytest: --long-running --use-template-cache --use-provider=cm-pod2 cfme/tests/pod/test_appliance_crud.py::test_aws_smartstate_pod }}
=> [1LP][WIPTEST] smartstate smoketest in pod appliance

conf/polarion_tools.yaml
This comment is relevant to a change in pytest-polarion-collect that has to be released. When it is, I'll include the updated version requirement in this PR as well.
https://gitlab.com/mkourim/pytest-polarion-collect/merge_requests/2/diffs
=> [WIP] Update polarion_tools.yaml, comments around caseautomation

cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_container_objects.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/automate/custom_button/test_service_objects.py
try to give unique names without changing common meaning.
=> [1LP][RFR][NOTEST] CB: test unique names

cfme/tests/candu/test_azone_graph.py, cfme/tests/candu/test_cluster_graph.py, cfme/tests/candu/test_datastore_graph.py, cfme/tests/candu/test_host_graph.py, cfme/tests/candu/test_vm_graph.py
{{pytest: -v -k 'graph_screen' --collect-only}}
=> [1LP][RFR] Remove duplicate test names

cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Removal of duplicate/automated test cases from manual file.
test_ssa_vm --> https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/cloud_infra_common/test_vm_instance_analysis.py#L635
test_embed_tower_exec_play_against_amazon --> https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/ansible/test_embedded_ansible_services.py#L516
=> [1LP][RFR][NOTEST] This will remove duplicate/automated tests from respective manual file.

cfme/base/ui.py
- Fixed reset button xpath
- Added ```reset_title``` widget to read title
{{ pytest: cfme/tests/automate/test_git_import.py -k 'test_automate_git_domain_removed_from_disk' -vv }}
=> [1LP][RFR] Updated is_diplayed of AutomateImportExportView

cfme/tests/cli/test_appliance_console.py
Manual test move.
test_appliance_console_packages --> https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/test_appliance.py#L268
=> [RFR][NOTEST] This PR will remove Manual tests (Duplicate)

cfme/tests/services/test_catalog_item.py, cfme/tests/services/test_generic_service_catalogs.py, cfme/tests/services/test_myservice.py
{{pytest: --manual --long-running --use-template-cache --collect-only cfme/tests/services/test_catalog_item.py cfme/tests/services/test_generic_service_catalogs.py cfme/tests/services/test_myservice.py}}
=> [1LP][RFR] Adding manual test of services RFE

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_git_import.py
- Importing of multiple domains from a single git repository is not allowed
{{ pytest: cfme/tests/automate/test_git_import.py -k 'test_automate_git_import_multiple_domains' -vv }}
=> [1LP][RFR] New Test: Checking git import for multiple domains

cfme/control/explorer/actions.py, cfme/tests/ansible/test_embedded_ansible_basic.py
PRT run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -qsvvvv --long-running }}
=> [1LP][RFR] This will fix control-action tests for Ansible.

cfme/tests/test_manual.py
Added caseautomation for mmojzis' manual tests and also changed owners of some tests
=> [NOTEST][RFR] Added caseautomation for mmojzis' manual tests

cfme/configure/configuration/region_settings.py, cfme/tests/configure/test_tag.py
{{ pytest: -v cfme/tests/configure/test_tag.py::test_updated_tag_name_on_vm }}
also moved tag creation from `test_tag_crud` to fixture to use it in the new test
=> [1LP][RFR] new test_tag_change_tag_name

cfme/tests/infrastructure/test_vm_reconfigure.py
{{ pytest:  cfme/tests/infrastructure/test_vm_reconfigure.py -k test_vm_reconfig_add_remove_disk --use-template-cache  --long-running -sqvvv }}
=> [1LP][RFR]Automate test for vm reconfig add remove disk hot

cfme/tests/automate/custom_button/test_buttons.py
=> [1LP][RFR][NOTEST]move to manual only

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Ref:
https://github.com/ManageIQ/integration_tests/issues/8660
=> [RFR][NOTEST] update manageiq-client requirnment to 0.5.1 py3 support

cfme/tests/infrastructure/test_vm_reconfigure.py
=> [1LP][RFR] Manual test cleanup of vmware reconfig test

cfme/fixtures/candu.py, cfme/tests/candu/test_graph_groupbytag.py
I have added tests for grouping C&U graphs by tags.
PRT results:
510 - PASSED
=> [1LP][RFR] Tests for grouping candu graphs by tags

cfme/tests/ansible/test_embedded_ansible_basic.py, cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/ansible/test_embedded_ansible_services.py
Also removed already automated tests.
PRT run:
{{ pytest: cfme/tests/ansible/ -k "test_service_ansible_retirement_remove_resources or test_embedded_ansible_repository_invalid_url_crud" -qsvvvv  --long-running }}
=> [1LP][RFR] Automating Ansible manual test cases.

cfme/rest/gen_data.py
{{ pytest: cfme/tests/configure/test_rest_access_control.py --use-template-cache -sqvvv }}
=> [RFR] Modify tenants function

cfme/control/explorer/conditions.py, cfme/tests/control/test_basic.py
{{pytest: --long-running cfme/tests/control/test_basic.py}}
=> [1LP][RFR] fixing test_basic tests 

cfme/tests/infrastructure/test_vm_reconfigure.py
{{ pytest: cfme/tests/infrastructure/test_vm_reconfigure.py -k test_vm_reconfig_add_remove_hw_hot --use-template-cache --long-running -sqvvv }}
=> [1LP][RFR]Adding new tests of vm reconfig add sockets and memory on running Vm

cfme/tests/infrastructure/test_vmware_provider.py
__Adding tests__ for VMware provider.
=> [1LP][RFR][NOTEST]Adding more VMware tests to address qe_test_coverage flags

cfme/automate/explorer/domain.py, cfme/configure/access_control/__init__.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_git_import.py
- Testing imported domain refresh with non-super user
- Added new view for refreshing imported domains
- DomainRefreshView
- Added new property for domain
- Refresh
- Removed not used imports
- Removed ```<5.9``` dependencies
{{pytest: cfme/tests/automate/test_git_import.py -k 'test_refresh_git_current_user' -vv }}
=> [1LP][RFR] New Test: Testing imported domain refresh with non-super user

cfme/configure/configuration/diagnostics_settings.py, cfme/tests/configure/test_log_depot_operation.py
PRT Run:
{{ pytest: cfme/tests/configure/test_log_depot_operation.py -k test_collect_log_depot -qsvvv --long-running }}
=> [1LP][RFR] Removed local Ansible fixture and fixed is_displayed.

cfme/test_requirements.py, cfme/tests/infrastructure/test_config_management_rest.py, cfme/tests/test_appliance.py, cfme/tests/test_manual.py, cfme/tests/test_replication.py, cfme/tests/webui/test_general_ui.py, cfme/utils/testgen.py
Updating all test requirement markers with metadata to populate polarion (or any other test tool requirement item)
=> [1LP][RFR] Add Requirement Meta

cfme/fixtures/provider.py, cfme/fixtures/service_fixtures.py
{{pytest: --long-running cfme/tests/ssui/test_ssui_myservice.py cfme/tests/ssui/test_ssui_service_catalogs.py }}
=> [1LP][RFR] restoring scopes of global fixtures

cfme/tests/infrastructure/test_publish_vm_to_template.py
__Extending__ template cloning test to cover VMware provider.
{{pytest: cfme/tests/infrastructure/test_publish_vm_to_template.py --long-running }}
=> [1LP][RFR] Updating template test to cover vmware provider

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_common_methods.py, cfme/tests/cloud_infra_common/test_discovery_and_support.py, cfme/tests/cloud_infra_common/test_power_control_manual.py, cfme/tests/cloud_infra_common/test_quota_manual.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/infrastructure/test_vm_ownership.py, cfme/tests/test_manual.py
This PR includes following changes:
- Updated manual test cases
- Removed tests from test_manual.py
- Added test_requirements wherever required
- Updated polarion doc strings
As I cant see ```relationships``` test requirement in current file. So need to wait until PR #8672 gets merged.
Note: **PR #8672 merged**
=> [1LP][RFR][NOTEST] Updated manual/automated test cases

cfme/configure/configuration/diagnostics_settings.py
{{pytest: --long-running cfme/tests/configure/test_log_depot_operation.py}}
=> [RFR] fixed diagnostics & logs views and relevant tests

cfme/utils/template/virtualcenter.py
{{ pytest: cfme/tests/control/test_actions.py cfme/tests/infrastructure/test_publish_vm_to_template.py cfme/tests/cloud_infra_common/test_vm_instance_analysis.py --long-running --use-provider vsphere }}
=> [1LP][RFR] Testing Datastore Cluster Changes with PRT

cfme/test_requirements.py, cfme/tests/automate/custom_button/test_buttons.py, cfme/tests/automate/custom_button/test_catalog_custom_button.py, cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_container_objects.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_import_export.py, cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/automate/custom_button/test_rest_custom_button.py, cfme/tests/automate/custom_button/test_service_objects.py
- Added custom button FA test requirement
=> [1LP][RFR][NOTEST] custom button test requirements

cfme/fixtures/service_fixtures.py
{{pytest: cfme/tests/ -k 'test_add_vm_to_service or  test_custom_group_on_catalog_item_crud' --long-running -v}}
=> [1LP][RFR] fix fixture scope

cfme/tests/cloud/test_providers.py
{{ pytest: -v cfme/tests/cloud/test_providers.py::test_create_azure_vm_from_azure_image --use-provider=complete  --long-running }}
Automation for `test_create_azure_vm_from_azure_image`. In fact, also automates `test_upload_azure_image_to_azure` as it's part of the test.
=> [1LP][RFR] provision cfme from azure

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_post_migrations.py
{{pytest: cfme/tests/v2v/test_post_migrations.py --use-provider rhv42 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
closing https://github.com/ManageIQ/integration_tests/pull/8419
@sshveta  @digitronik  ^^
=> [1LP][RFR] Post migration new structure and osp support

cfme/tests/v2v/test_v2v_ansible.py
{{ pytest: cfme/tests/v2v/test_v2v_ansible.py  --use-provider={rhv42,osp13-ims} --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running}}
=> [1LP][RFR]Ansible test refactoring

cfme/common/__init__.py, cfme/tests/automate/custom_button/test_cloud_objects.py, cfme/tests/automate/custom_button/test_infra_objects.py
{{pytest: cfme/tests/automate/custom_button -k 'test_custom_button_events' -v}}
=> [1LP][RFR] Remove todo and blocker BZ-1668023

cfme/configure/configuration/analysis_profile.py
{{ pytest: --long-running cfme/tests/configure/test_analysis_profiles.py }}
=> [1LP][RFR] fixed events table in analysis profiles

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
{{ pytest: --long-running cfme/tests/configure/test_analysis_profiles.py -k 'test_delete_default_analysis_profile or test_edit_default_analysis_profile'}}
=> [1LP][RFR] deploying fix for manageiq's table

cfme/ansible_tower/explorer.py, cfme/infrastructure/config_management.py, cfme/tests/infrastructure/test_config_management.py
{{ pytest: -v cfme/tests/infrastructure/test_config_management.py::test_ansible_tower_job_templates_tag }}
New test to cover https://bugzilla.redhat.com/show_bug.cgi?id=1673104
=> [1LP][RFR] added test_ansible_tower_job_templates_tag

requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Updates rhv VM IP fetching to avoid a TypeError
=> [1LP][RFR]Update wrapanapi to 3.1.3

cfme/utils/appliance/db.py, cfme/utils/template/base.py, cfme/utils/template/openstack.py, cfme/utils/template/rhevm.py, cfme/utils/template/virtualcenter.py, scripts/clone_template.py
Requires support for vmware datastore clusters if we want to enable the new vmware provider:
https://github.com/ManageIQ/wrapanapi/pull/368
Needs the following merged first:
https://github.com/ManageIQ/integration_tests/pull/8609
=> [RFR] Upstream builds templatized and cloned working for VMware, RHEV, and OSP

cfme/tests/control/test_actions.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
`test_actions.py` is in dire need of an update, it has many failing tests and is in need of an upgrade to make use of methods that have since been included in our framework. 
{{ pytest: --use-provider vsphere65-nested --long-running --use-template-cache cfme/tests/control/test_actions.py }}
=> [1LP][RFR] Cleanup and address test failures in test actions

cfme/tests/infrastructure/test_scvmm_specific.py
Automating `test_vm_mac_scvmm` 
{{ pytest: --use-provider complete --long-running --use-template-cache cfme/tests/infrastructure/test_scvmm_specific.py::test_vm_mac_scvmm }}
=> [RFR] Automate test case for testing scvmm mac address

cfme/tests/infrastructure/test_scvmm_specific.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Automating the test case `test_check_disk_allocation_size_scvmm`, this test is currently blocked by BZ 1700909, but I wanted to automate test coverage for it. 
This PR depends on the wrapanapi PR https://github.com/ManageIQ/wrapanapi/pull/374
=> [WIP] Add test case for bz-1700909

cfme/tests/infrastructure/test_vmware_provider.py
__Adding tests__ for VMware customer bzs.
=> [1LP][RFR]Adding new test for customer BZ 1695008

cfme/automate/buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py}}
=> [1LP][RFR] fix cb group view for 511

cfme/tests/v2v/test_csv_import.py, cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_csv_import.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running}}
=> [1LP][RFR] V2V CSV test

cfme/common/provider.py
1. Rectify `_fill_rsa_endpoint_dicts` method so that it creates the provider correctly via REST and works for v2v testing.
2. Modify `_fill_default_endpoint_dicts` method.
{{ pytest: cfme/tests/cloud_infra_common/test_rest_providers.py::test_create_provider --use-template-cache -sqvvv }}
=> [1LP][RFR]Rectify create_rest method for rsa credentials

cfme/tests/v2v/test_migration_plan.py, cfme/tests/v2v/test_post_migrations.py, cfme/tests/v2v/test_v2v_ansible.py, cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_migration_plan.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running}}
=> [1LP][RFR]Fixed some method names

cfme/tests/configure/test_tag.py
{{ pytest: -v cfme/tests/configure/test_tag.py::test_map_tagging_crud }}
=> [RFR] added block for BZ1707328

cfme/tests/test_manual.py
reassigned as agreed in the discussion
=> [RFR][NOTEST] reassigned test_puma_server

cfme/fixtures/service_fixtures.py, cfme/services/myservice/ssui.py, cfme/services/myservice/ui.py, cfme/services/requests.py, cfme/tests/automate/custom_button/test_service_vm_custom_button.py
- Trying to satisfy custom button requirements for testing thing on UI and SSUI VM objects
- Added some views and restore old implementation
- Added basic test for service vm objects so i can go for other after this PR. 
{{pytest: cfme/tests/automate/custom_button/test_service_vm_custom_button.py -v}}
=> [1LP][RFR] CB service vm display test

cfme/base/login.py, cfme/base/ui.py
{{pytest: cfme/tests/configure/}}
=> [1LP][RFR] fix setting configuration nav 511

cfme/tests/test_appliance.py
__Adding tests__ for codename in log and stdout.
{{ pytest: cfme/tests/test_appliance.py -k test_codename_in_ -v }}
=> [1LP][RFR] Codename tests

cfme/utils/appliance/__init__.py, cfme/utils/ssh.py
When ssh connection to additional appliances (for example in the update
tests) is being made, it could fail, because SSH was not fully up and
running.
This patch adds re-trying to create the ssh connections for 2 minutes.
The reraise was used to log-and-ignore the exceptions when running an
SSH command, but this looks to me as a bad practice as it just burries
the problems in the logs.
{{ py.test: -v -m smoke -k "not test_cloud_provider_crud" }}
=> [1LP][RFR] Retry ssh connection if failed.

cfme/tests/configure/test_access_control.py
Changing ownership of Multi-tenancy FA to nachandr
=> [NOTEST]Chown of TestCases to nachandr

cfme/tests/v2v/test_v2v_schedule_migrations.py, cfme/v2v/migration_plans.py
{{pytest: cfme/tests/v2v/test_v2v_schedule_migrations.py --use-provider rhv42 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
@sshveta @digitronik  needs your reviews!
Tested locally and it works. PRT should fail until https://github.com/ManageIQ/integration_tests/pull/8690 gets merge since we are using mini fixture.
=> [1LP][RFR] Schedule migration refactor

cfme/automate/buttons.py, cfme/services/catalogs/catalog_items/__init__.py, cfme/tests/automate/custom_button/test_catalog_custom_button.py, widgetastic_manageiq/__init__.py
- Adding custom button on catalog crud test
- Moved `AutomateRadioGroup` to `miq.wt` so we can share it in other files.
- Added some refactor in view; I would like catalog button params should similar to main custom button model page.
- Added methods for button; for group already we have.
- Added one workaround; as i don't want to guess flash msg.
=> [1LP][RFR] CB catalog crud test and small refactor. 

cfme/ansible/credentials.py, cfme/ansible/playbooks.py, cfme/ansible/repositories.py, cfme/cloud/availability_zone.py, cfme/cloud/flavor.py, cfme/cloud/keypairs.py, cfme/cloud/provider/__init__.py, cfme/cloud/security_groups.py, cfme/cloud/stack.py, cfme/common/host_views.py, cfme/containers/node.py, cfme/infrastructure/cluster.py, cfme/infrastructure/deployment_roles.py, cfme/infrastructure/resource_pool.py, cfme/modeling/base.py, cfme/networks/views.py, cfme/storage/manager.py, cfme/storage/object_store_container.py, cfme/storage/object_store_object.py, cfme/storage/volume.py, cfme/storage/volume_backup.py, cfme/storage/volume_snapshot.py, cfme/storage/volume_type.py
- manager details
{{pytest: cfme/tests/storage/}}
=> [1LP][RFR] Fix storage navigation

cfme/tests/cli/test_appliance_cli.py, cfme/tests/cli/test_appliance_console.py
Updating **Appliance Console** tests with **testSteps** in the **Manual Tests** and **re-assigning FA owner**.
=> [RFR] [NOTEST] Re-assigning and Adding testSteps to Maunal tests.

cfme/tests/cli/test_appliance_update_manual.py, cfme/tests/cloud_infra_common/test_provisioning_manual.py, cfme/tests/configure/test_proxy.py, cfme/tests/distributed/test_appliance_replication.py, cfme/tests/platform/test_locale.py, cfme/tests/test_manual.py
Note: The test
test_azure_instance_password_requirements_azure
is a dup with
test_azure_instance_password_requirements
Note: The test
test_vm_placement_with_duplicated_folder_name_vmware
is already in
cfme/tests/cloud_infra_common/test_provisioning_manual.py
Note: The test
test_appliance_log_error
is already in
cfme/tests/test_appliance.py
=> [RFR] Move manual update cases

cfme/utils/appliance/__init__.py
Add `ui_protocol=http` for `from_provider`
=> [1LP][RFR] Add ui_protocol to Appliance.from_provider for provision_appliance

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_v2v_migrations.py, cfme/v2v/infrastructure_mapping.py, cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running}}
=> [1LP][RFR]V2V migration tests

cfme/tests/cloud/test_snapshot.py, cfme/tests/infrastructure/test_snapshot.py, cfme/tests/test_manual.py
__Moving__ manual snapshot tests to test_snapshot.py.
This is my first PR with manual tests.
In the process of moving the tests, I sometimes added setup, testSteps and expectedResults. Also, I deleted test that is already automated.
I also updated names of some of the tests - this could possibly cause problems when exporting/importing stuff.
=> [1LP][RFR] Move snapshot manual tests

cfme/automate/buttons.py, cfme/rest/gen_data.py, cfme/storage/volume.py, cfme/tests/ansible/test_embedded_ansible_automate.py, cfme/tests/storage/test_volume_backup.py
{{ pytest: cfme/tests/storage/test_volume_backup.py cfme/tests/services/test_rest_services.py cfme/tests/ansible/test_embedded_ansible_automate.py -v --long-running --use-provider complete }}
=> [1LP][RFR] Fix TypeError in Latest RC Run

cfme/tests/cli/test_appliance_cli.py, cfme/tests/cli/test_appliance_console.py
=> [1LP][RFR][NOTEST] Re-assigning Test cases to new FA owner

cfme/fixtures/ssh_client.py, cfme/utils/log.py, cfme/utils/ssh.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt, scripts/cleanup_edomain_templates.py
This script was hitting an exception in trying to cleanup rhv script when there was no edomain listed in yamls.
Pulling on this thread, I ended up basically rewriting the script.
~~Depends on ManageIQ/wrapanapi#379 for functional storage domain state changes.~~
=> [1LP][RFR] refactor cleanup_edomain_templates

cfme/tests/ansible/test_embedded_ansible_manual.py
=> [1LP][RFR][NOTEST] Adding manual_tests

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_method.py
Added manual test cases for automate.
Also added comment to automate newly added automate methods.
=> [1LP][RFR][NOTEST] Added manual test case

cfme/tests/v2v/test_rest_migrations.py
{{pytest: cfme/tests/v2v/test_rest_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
=> [1LP][RFR] Migration rest tests refactor

cfme/base/login.py, cfme/common/provider_views.py, cfme/tests/webui/test_general_ui.py
Changes:
1. Add a new widget `add_button`
2. Automate test:  `test_welcoming_page`
{{ pytest: cfme/tests/webui/test_general_ui.py::test_welcoming_page --use-template-cache -sqvvv }}
=> [1LP][RFR] Automate test: test_welcoming_page

cfme/networks/views.py
Fix my bad :)
{{pytest: cfme/tests/automate/custom_button/test_cloud_objects.py::test_custom_button_events_cloud_obj[Cloud_network-openstack-dialog] -v}}
=> [1LP][RFR] fix Cloud NW Details view

cfme/tests/automate/test_method.py
- This test case checks whether while sending mails automate methods considers person in cc and bcc.
{{ pytest: cfme/tests/automate/test_method.py::test_send_email_method -vv }}
=> [1LP][RFR] New Test: Testing automate method of sending emails

cfme/tests/test_appliance.py
Below Test cases are already automated in test_appliance_replication.py 
(https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/distributed/test_appliance_replication.py#L253#L292 )
test_appliance_replicate_database_disconnection_with_backlog
test_appliance_replicate_database_disconnection
=> [1LP][RFR][NOTEST] Removing Duplicate Test Cases

cfme/tests/v2v/test_v2v_migrations_single_vcenter.py, cfme/v2v/migration_plans.py
{{pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
=> [1LP][RFR]Single Vcenter tests

cfme/common/__init__.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
PRT run:
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k test_ssa_vm -svvvv --use-provider vsphere6-nested --long-running }}
=> [1LP][WIPTEST] This PR will fix SSA tests.

cfme/services/requests.py, cfme/tests/cloud/test_quota.py, cfme/tests/cloud_infra_common/test_quota_manual.py
{{ pytest: cfme/tests/cloud/test_quota.py::test_custom_service_dialog_quota_flavors --use-provider=complete --long-running -vv }}
=> [1LP][RFR] New Test: Testing quota with service dialog using automate method

cfme/tests/services/test_dialog_element_in_catalog.py, cfme/tests/services/test_dialog_regex_validation_in_catalog.py, cfme/tests/services/test_different_dialogs_in_catalogs.py
=> [1LP][RFR] Adding service dialog manual test cases

cfme/test_requirements.py, cfme/tests/automate/custom_button/test_service_vm_custom_button.py
- Introducing a new FA `Customer Stories` requirement. 
- Added one manual test
=> [1LP][RFR] Customer stories requirement

cfme/test_requirements.py
=> [1LP][WIPTEST]Adding requirement marker for test feature

notebooks/MultiProcessing.ipynb
Jupyter notebook with some basic multiprocessing patterns
=> [WIPTEST] Add notebook with intro to python multiprocessing

cfme/tests/test_replication.py
__Updating the replication tests__ with the testSteps
=> [1LP][RFR][NOTEST] Add test steps to the replication tests.

cfme/tests/automate/test_service_dialog.py, cfme/tests/services/test_dialog_element_in_catalog.py, cfme/tests/services/test_dialog_regex_validation_in_catalog.py, cfme/tests/services/test_different_dialogs_in_catalogs.py, cfme/tests/services/test_dynamicdd_dialogelement.py
=> [1LP][RFR]Adding requirement-marker to test

cfme/fixtures/service_fixtures.py, cfme/tests/automate/custom_button/test_catalog_custom_button.py
-BZ 1653195
{{pytest: cfme/tests/automate/custom_button/test_catalog_custom_button.py::test_custom_button_unassigned_behavior_catalog_level -v}}
=> [1LP][RFR] Catalog level unassigned btn test

cfme/tests/automate/test_provisioning_dialogs.py, cfme/tests/cloud/test_tenant.py, cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py, cfme/tests/configure/test_access_control.py, cfme/tests/configure/test_analysis_profiles.py, cfme/tests/infrastructure/test_quota.py, cfme/tests/infrastructure/test_quota_tagging.py, cfme/tests/infrastructure/test_tenant_quota.py
- Added ```test_requirements``` to test cases
- Changed position of test case - ```test_tenant_quota_input_validate```
- Updated some comments
- Assigned some test cases to respective FA owners:
- **test_tenant_crud**  to @nachandr 
- **test_custom_role_modify_for_dynamic_product_feature** to @apagac 
- **test_provisioning_dialog_crud** to @jaryn 
- **test_provisioning_dialogs_sorting** to @valaparthvi
=> [1LP][RFR] Test cases updated with requirements

cfme/utils/appliance/__init__.py
default configure method to set this to :log
at request of CFME dev, QE appliances should log deprecations for inspection
Testing configure from unconfigured appliance with this new method locally.
I've tested the method itself against an appliance and monitored changes to the given file. Checked error logging is working too.
=> [1LP][RFR] Add rails deprecation behavior config method to appliance

cfme/tests/infrastructure/test_publish_vm_to_template.py, cfme/tests/infrastructure/test_vmware_provider.py
__Adding tests Requirements__
Requires https://gitlab.com/mkourim/pytest-polarion-collect/merge_requests/3/diffs to be merged.
=> [NOTEST][RFR]Adding test_requirements

cfme/tests/v2v/test_v2v_cancel_migrations.py
{{pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
=> [1LP][RFR]v2v cancel migration tests

cfme/ansible/repositories.py, cfme/fixtures/ansible_fixtures.py, cfme/services/myservice/ui.py, cfme/tests/ansible/test_embedded_ansible_services.py
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py --long-running }}
=> [RFR] Update tests to use Global fixture.

cfme/automate/explorer/__init__.py, cfme/utils/ftp.py
py re pattern py37 compartability i found two usecase only...
one is the third party in ansible network config; it fixed... it will part of next release `2.8.0`
=> [RFR][NOTEST] py37 re pattern

cfme/tests/cli/test_appliance_cli.py, cfme/tests/cli/test_appliance_console.py, cfme/tests/test_replication.py
=> [1LP][RFR]Adding global test requirement for test cases

cfme/base/login.py, cfme/tests/automate/test_domain.py, cfme/tests/automate/test_git_import.py, cfme/tests/cloud/test_tenant.py
{{ pytest: cfme/tests/cloud/test_tenant.py::test_dynamic_product_feature_for_tenant_quota -vv }}
=> [1LP][RFR] Fixed path of quota related product feature tree

cfme/base/ui.py, cfme/tests/configure/test_rest_config.py, cfme/utils/appliance/implementations/ui.py
{{ pytest: cfme/tests/configure/test_rest_config.py --use-template-cache -sqvvv }}
=> [1LP][RFR]New Test: test_update_advanced_settings_new_key

cfme/test_requirements.py, cfme/tests/cloud/test_targeted_refresh.py, cfme/tests/test_manual.py
Moved targeted refresh tests to cloud and moved Steps under Polarion in docstrings.
=> [1LP][RFR] Moved targeted refresh tests to cloud

cfme/utils/ssh.py
=> [1LP][RFR] trying to turn off strict host key checking

cfme/tests/webui/test_advanced_search.py
{{ pytest: -v cfme/tests/webui/test_advanced_search.py::test_filter_crud }}
=> [1LP][RFR] added new param to cover BZ1402392

cfme/tests/automate/custom_button/test_buttons.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Needs `Checkbox` `is_enabled` property
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_open_url_availability}}
=> [1LP][RFR] fix open url changes

cfme/tests/optimize/test_bottlenecks.py
I've added requirements for Bottleneck tests.
The tests don't have to be run on PRT.
=> [NOTEST] Adding requirements for Bottleneck tests

cfme/tests/automate/custom_button/test_service_objects.py
- BZ-1653195
- BZ over BZ :) 1709870
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_unassigned_behavior_objs -v}}
=> [1LP][RFR] test_unassigned button behavior for service obj

cfme/tests/configure/test_access_control.py
I've added requirements for multi-tenancy tests (both automated and manual).
The tests don't have to be run on PRT.
=> [NOTEST] Adding requirements for Multi-tenancy tests

cfme/tests/v2v/test_csv_import.py, cfme/tests/v2v/test_infrastructure_mapping.py, cfme/tests/v2v/test_migration_plan.py, cfme/tests/v2v/test_post_migrations.py, cfme/tests/v2v/test_rest_migrations.py, cfme/tests/v2v/test_v2v_ansible.py, cfme/tests/v2v/test_v2v_migrations.py, cfme/tests/v2v/test_v2v_migrations_single_vcenter.py, cfme/tests/v2v/test_v2v_schedule_migrations.py
PRT results are not relevant since we have
=> [1LP][RFR][NOTEST] Migration requirement and metadata

cfme/tests/storage/test_object_store_container.py, cfme/tests/storage/test_object_store_object.py, cfme/tests/storage/test_volume.py, cfme/tests/storage/test_volume_backup.py, cfme/tests/storage/test_volume_snapshot.py, cfme/tests/test_manual.py
Deleted duplicate tests from test_manual.py
Reassigned several tests
Moved some tests from test_manual.py
@apagac Why were some storage snapshot tests assigned to you?
=> [1LP][RFR] Put in order storage tests

cfme/tests/automate/test_automate_manual.py
Added manual test cases for BZs:
1715396, 1716443 in automate FA
=> [1LP][RFR][NOTEST] Added new manual test cases

cfme/tests/ansible/test_embedded_ansible_actions.py
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_actions.py -svvvv --long-running }}
=> [RFR] Updated with use of ansible global fixture.

cfme/tests/intelligence/test_chargeback.py
The tests need not be run on PRT.
=> [RFR] Re-assigning chargeback CRUD tests to current FA owner

cfme/utils/dockerbot/pytestbase/Dockerfile
Adding iputils to pytestbase Dockerfile
=> [RFR] Add iputils to pytestbase Dockerfile

cfme/utils/template/base.py
Use wait_pingable in template upload to ensure the VM is reachable.
=> [1LP][RFR] Update template upload to use wait_pingable

cfme/utils/db.py
db client doesn't support views but some cf tables have been turned into views.
This PR should add support for views.
{{ pytest: --use-template-cache --long-running cfme/tests/candu/test_utilization_metrics.py }}
=> [RFR] views support in db client

cfme/tests/cloud/test_cloud_manual.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud/test_security_groups.py, cfme/tests/configure/test_proxy.py, cfme/tests/networks/test_sdn_security_groups.py, cfme/tests/test_appliance.py, cfme/tests/test_manual.py
After this PR merge there should be no tests in test_manual.py assigned to me.
=> [1LP][RFR] Moved the rest of tests from test_manual.py

cfme/tests/test_manual.py
No tests have to be run on PRT.
1)Removed the following C&U tests that have been automated : Gap collection, Availability zone tests
2)Removed tests for GCE since GCE is no longer supported
=> [1LP][RFR] Deleting candu tests that have been automated

cfme/tests/infrastructure/test_ssa_vddk.py
PRT Run:
{{ pytest: cfme/tests/infrastructure/test_ssa_vddk.py -svvvv --long-running }}
=> [RFR] Added VDDK 6.7 checks and updated getter method

cfme/services/catalogs/catalog_items/__init__.py
{{pytest: cfme/tests/automate/custom_button/test_catalog_custom_button.py -v}}
=> [RFR] Fix catalog button group nav

cfme/automate/dialogs/dialog_element.py, cfme/fixtures/automate.py, cfme/tests/automate/custom_button/__init__.py, cfme/tests/automate/custom_button/test_service_vm_custom_button.py, widgetastic_manageiq/__init__.py
{{pytest: cfme/tests/automate/custom_button/test_service_vm_custom_button.py::test_custom_button_with_dynamic_dialog_vm --use-provider vsphere67-nested}}
=> [1LP][RFR] Customer Story: Automate-Dynamic Dialog-Custom Button

cfme/generic_objects/definition/rest.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_method.py
{{ pytest: cfme/tests/automate/test_method.py -k 'test_automate_generic_object_service_associations' -vv }}
Depend on: #8900
=> [1LP][RFR] New Test: Test generic object service associations using automate method

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_buttons.py, widgetastic_manageiq/__init__.py
- Created widget as use of checkbox was difficult
- Added support of role in custom button model
- Added test for BZ-1703588
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_role_selection}}
=> [1LP][RFR] CB- roles Selection test

cfme/tests/automate/test_git_import.py
{{ pytest: cfme/tests/automate/test_git_import.py --use-template-cache -sqvvv }}
=> [1LP][RFR] Automate test: test_domain_import_git_rest

cfme/tests/control/test_bugs.py, widgetastic_manageiq/expression_editor.py
Creating a test case for the following customer BZ https://bugzilla.redhat.com/show_bug.cgi?id=1711352
{{ pytest: --use-template-cache --use-provider vsphere65-nested --long-running cfme/tests/control/test_bugs.py::test_policy_condition_multiple_ors }}
=> [1LP][RFR] Create a test case to test policy conditions with multiple OR statements

cfme/automate/buttons.py, cfme/automate/simulation.py, cfme/base/ui.py, cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_simulated_object_copy_on_button}}
=> [1LP][RFR] Simulation copy test

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_service_automate.py
- Testing requester for service or life cycle provision are in logs
{{ pytest: cfme/tests/automate/test_service_automate.py -k 'test_user_requester_for_lifecycle_provision' -vv }}
=> [1LP][RFR] Testing user requester for service or life cycle provision

cfme/tests/automate/test_automate_manual.py
- Added test coverage for automate FA
=> [1LP][RFR] Added new test cases

cfme/utils/dockerbot/check_prs.py
=> [1LP][RFR] dockerbot: use readable task ids

cfme/common/host_views.py, cfme/infrastructure/host.py, cfme/tests/infrastructure/test_vmware_provider.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
__Adding tests__ automated test for vmware_filters and test vdswitch ui display.
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py }}
=> [1LP][RFR]updating vmware test to automate vmware filters test and test vdswitch ui display

cfme/cloud/provider/__init__.py, cfme/cloud/tenant.py, cfme/common/__init__.py, cfme/configure/access_control/__init__.py, widgetastic_manageiq/__init__.py
{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py }}
=> [1LP][RFR] fixed CloudProviderInstancesView and tags

cfme/tests/v2v/test_v2v_cancel_migrations.py
{{pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
PRT should pass after - 
_keystone service issue -
I am using `get_vm` function of wrapenapi which works on kapi aka keystone api in backend. When wrapenapi try to connect to kapi for authentication, since `osp13-ims`'s keystone endpoint exposes private IP we are unable to connect there. I have raised this concerns to @mnadeem92  and he might replace private IP with public IP if possible or redeploy OSP13-ims so that keystone will have public IP. Meanwhile, we can always use `rhos13` if we want to check if mentioned wrapenapi code works but we can not use this provider for end to end migration since this is not suppose to be target provider for IMS._
=> [1LP][RFR] Cancel migration and check if instance, volumes and ports get deleted

cfme/fixtures/ansible_fixtures.py, cfme/services/catalogs/catalog_items/__init__.py, cfme/services/catalogs/catalog_items/ansible_catalog_items.py, cfme/services/myservice/ui.py, cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/ansible/test_embedded_ansible_services.py
Blocking this test(s) for CFME 5.11 due to BZ.
PRT Run: 
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k test_embed_tower_exec_play_against -svvvv --long-running }}
=> [1LP][RFR] Automating Ansible manual tests

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
PRT Run:
{{ pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k "test_ssa_vm or test_ssa_packages or test_ssa_files" -svvvv --long-running --use-provider vsphere6-nested }}
=> [RFR] This PR will reduce creation of extra VMs for each test.

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_conversion_host.py, cfme/v2v/conversion_hosts.py, entry_points.txt, widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_conversion_host.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running}}
=> [1LP][RFR] New conversion host ui

widgetastic_manageiq/__init__.py
last-minute decisions are not good #8942
the functionality is not affected but I'd like to fix it as it doesn't make much sense
=> [RFR] fixed set in ReactSelect

cfme/services/catalogs/catalog_items/__init__.py, cfme/services/catalogs/catalog_items/catalog_bundles.py, cfme/tests/services/test_service_customer_bz.py, widgetastic_manageiq/__init__.py
=> [1LP][RFR] BZ 1698431

cfme/test_requirements.py
=> [RFR] fixed assignee for azure and rhev

cfme/tests/automate/test_instance.py
- Testing quota source value in automation logs 
{{ pytest: cfme/tests/automate/test_instance.py  -k 'test_quota_source_value' -vv }}
=> [1LP][RFR] New Test: Testing quota source value

cfme/tests/automate/test_domain.py
- Updated domain disable and lock test case
- Added functionality check:
- If we try to execute automate method of disabled domain using simulation then it does not work(gives error in automation logs)
{{ pytest: cfme/tests/automate/test_domain.py -k 'test_domain_lock_disabled' -vv }}
=> [1LP][RFR] Updated test case of automate domain disable and lock

cfme/tests/automate/custom_button/test_infra_objects.py, cfme/tests/test_appliance.py, cfme/utils/log_validator.py
- The current implementation of LogValidator is just to `search` some pattern in the log which is not sufficient for the custom button use case
- In the custom button after button execute request are fired in automation log and in our test, we are checking those. It's not a single request may be multiple.
- This checks can be part of `LogValidator`
- Shriver: removed from pytest, collecting more uses of LogValidator because of the scope of changes.
-k "test_custom_button_automate_infra_obj or test_custom_button_dialog_infra_obj or test_codename_in_log"
{{pytest: cfme/tests/test_appliance.py cfme/tests/cli/test_appliance_console.py cfme/tests/automate/test_method.py …
=> [1LP][RFR] Enhance LogValidator for pattern match

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vmware_provider.py, widgetastic_manageiq/vm_reconfigure.py
**IMPORTANT NOTE**: This PR includes commits from the PR #8879 as it was written in succession. 
__Adding tests__ for `test_vmware_cdrom_dropdown_not_blank`  This is going to fail on last assertion as this is a bug that is not fixed. But to avoid that, I have added blocker marker to it. Below GIF shows what would test do once bz is resolved.
Merge after #8879 
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py --use-provider complete -k 'test_vmware_cdrom_dropdown_not_blank' }}
=> [1LP][RFR]Cd dvd/DIsk table updates and Tests

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_rest_migrations.py
{{pytest: cfme/tests/v2v/test_rest_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv -k test_rest_conversion_host_crud}}
=> [RFR] Add conversion setup as a fixture and test

cfme/test_requirements.py, cfme/tests/cloud_infra_common/test_power_control_manual.py, cfme/tests/cloud_infra_common/test_provisioning.py, cfme/tests/cloud_infra_common/test_retirement.py, cfme/tests/distributed/test_appliance_replication.py, cfme/tests/infrastructure/test_vm_reconfigure.py, cfme/tests/intelligence/reports/test_reports_manual.py, cfme/tests/services/test_service_catalogs.py, cfme/tests/test_replication.py
Multi-Region FA.
This is first PR is the chain of PRs with tests related to Multi-Region/Central Administration FAs
=> [1LP][RFR] Adding Multi-Region FA requirement and appropriate tests

cfme/infrastructure/provider/__init__.py
Due to https://bugzilla.redhat.com/show_bug.cgi?id=1718209, we currently cannot setup host credentials in CFME 5.11 via REST. This is blocking a large number of tests that require host credentials for SSA, so as a workaround, we set them via the UI.
{{ pytest: --use-provider vsphere6-nested cfme/tests/control/test_compliance.py::test_check_files }}
@sbulage can you use this function regarding the changes you made in #8917? That way when the BZ is no longer blocking, it will again use REST.
=> [RFR] Add a UI workaround for setting up host creds in 5.11

cfme/tests/cloud_infra_common/test_snapshots_rest.py, cfme/tests/infrastructure/test_snapshot.py, scripts/cleanup_openstack_instance_snapshot.py
This PR will delete all instance snapshot with name started
with "test_snapshot_" and created by >= 2 hours before.
This PR is dependent on : https://github.com/ManageIQ/wrapanapi/pull/385
=> [1LP][RFR] Adding cleanup script for old snapshot

cfme/tests/cloud/test_azure_manual.py, cfme/tests/cloud/test_providers.py
{{ pytest: -v cfme/tests/cloud/test_providers.py::test_vpc_env_selection  --use-provider=complete  }}
=> [1LP][RFR] automated test_vpc_env_selection

cfme/tests/automate/custom_button/test_service_vm_custom_button.py
also added provisioning tag as its related to vm with service
=> [RFR] removed force block

cfme/tests/automate/custom_button/test_generic_objects.py
Fix visibiliy test for evm type objects
{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_expression_evm_obj}}
=> [RFR] fix evm object visibility test

cfme/tests/control/test_actions.py, cfme/tests/control/test_bugs.py
Adding BZ metadata for control FA, for those BZs which are automated.
=> [1LP][RFR][NOTEST] Add automates metadata for control FA

cfme/tests/intelligence/reports/test_canned_corresponds.py, cfme/tests/openstack/infrastructure/test_hosts.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt, requirements/template_docs.txt
Depends on https://github.com/ManageIQ/wrapanapi/pull/394
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py cfme/tests/openstack/infrastructure/test_hosts.py --use-provider complete }}
=> [RFR] Changes list_hosts to list_host for mgmt method calls

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vmware_provider.py
__Adding tests__ for making sure SCSI controller - Appliance cfme-vsphere-paravirtual-*.ova has SCSI controller 
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py -k "test_appliance_scsi_control_vmware" --long-running}}
=> [1LP][RFR] Scsi controller vmware

cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
{{pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py -k test_migration_restart --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv -k test_migration_restart}}
PRT should pass when,
=> [1LP][RFR] Add evmserver and appliance restart test for migration

cfme/tests/infrastructure/test_vmware_provider.py
__Adding__ Adding new Test Case
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py -k "test_rebuilt_vcenter_duplicate_hosts or test_switches_class_present_ems"}}
=> [1LP][RFR] Adding new customer test case for ems switches bz 1688900 and  vcenter rebuilt bz 1719399

cfme/configure/configuration/diagnostics_settings.py
The tests would fail (skipped due to blockers) anyway because of the other BZs.
=> [1LP][RFR] removed BZ1717902

cfme/tests/services/test_dialog_element_in_catalog.py, cfme/tests/ssui/test_ssui_myservice.py
=> [1LP][RFR] Adding service dialog manual test

cfme/intelligence/reports/reports.py, cfme/intelligence/reports/schedules.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/intelligence/reports/test_reports_schedules.py, data/schedules_crud/basic01.yaml
{{ pytest: cfme/tests/intelligence/reports/test_crud.py::test_reports_crud_schedule_for_base_report_once cfme/tests/intelligence/reports/test_crud.py::test_crud_custom_report_schedule cfme/tests/intelligence/reports/test_reports_schedules.py --use-template-cache -sqvvv }}
=> [1LP][RFR] Refactor schedules

cfme/tests/intelligence/reports/test_reports.py, cfme/tests/intelligence/reports/test_reports_manual.py
{{ pytest: cfme/tests/intelligence/reports/test_reports.py::test_new_report_fields --use-template-cache -sqvvv }}
=> [1LP][RFR]Automate Test: test_new_report_fields

cfme/tests/automate/test_instance.py
- This PR updates test case with use of ```LogValidator```
- Fixing Error:
```
E               AssertionError: assert 'LISvKJNizS' in 'Binary file /var/www/miq/vmdb/log/automation.log matches\n'
E                +  where 'Binary file /var/www/miq/vmdb/log/automation.log matches\n' = SSHResult(command='grep LISvKJNizS /var/www/miq/vmdb/log/automation.log\n', rc=0).output
cfme/tests/automate/test_instance.py:223: AssertionError
AssertionError
assert 'LISvKJNizS' in 'Binary file /var/www/miq/vmdb/log/automation.log matches\n'
+  where 'Binary file /var/www/miq/vmdb/log/automation.log matches\n' = SSHResult(command='grep LISvKJNizS /var/www/miq/vmdb/log/automation.log\n', rc=0).output
```
{{ pytest: cfme/tests/automate/test_instance.py -k 'test_automate_relationship_trailing_spaces' -vv }}
=> [1LP][RFR] Test case updated with log validator

cfme/tests/v2v/test_v2v_migrations.py, cfme/tests/v2v/test_v2v_smoke.py
{{pytest: cfme/tests/v2v/test_v2v_smoke.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv}}
New PR for 9007.
=> [1LP][RFR]Smoke tests v2v

cfme/services/requests.py, cfme/tests/cloud_infra_common/test_provisioning.py
rework its assertion patterns
Fix request view.is_displayed methods
PRT results:
Passing in 5.10, 1 pass + 1 failure + 2 BZ skip in 5.11
{{ pytest: --use-provider rhv43 --use-provider ec2west --long-running -vvvv cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval }}
=> [1LP][RFR] Fix test_provision_approval and Request views

cfme/tests/automate/test_automate_manual.py
Added test case for BZ - 1713072
=> [1LP][RFR][NOTEST] Added manual test case for schedules

cfme/test_framework/sprout/plugin.py
and re-format sprout pytest option formatting
Addressing warning:
`[WARNING] [py.warnings] ./cfme/test_framework/sprout/plugin.py:10: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
17:34:24   from .client import AuthException`
=> [1LP][RFR] Update imports in test_framework/sprout/plugin

cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/ansible/test_embedded_ansible_services.py
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k test_ansible_service_linked_vm -svvvv --long-running }}
=> [1LP][RFR] Automate manual tests to see VM is attached to Ansible Service.

cfme/tests/candu/test_azone_graph.py, cfme/tests/candu/test_utilization_metrics.py
{{pytest: cfme/tests/candu/test_utilization_metrics.py --use-provider ec2}}
=> [1LP][RFR] Collect memory tests for EC2 instances and Availability zones

cfme/configure/access_control/__init__.py
{{ pytest: -v cfme/tests/configure/test_access_control.py::test_group_crud_with_tag }}
=> [1LP][RFR] UI change for Hosts & Clusters tab

cfme/fixtures/service_fixtures.py, cfme/tests/services/test_myservice.py
{{pytest: cfme/tests/services/test_myservice.py  --use-provider vsphere67-nested -vvvv --long-running}}
automated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1720338
=> [1LP][RFR] Automated BZ1720338

cfme/tests/infrastructure/test_child_tenant.py, cfme/tests/infrastructure/test_project_quota.py, cfme/tests/infrastructure/test_tenant_quota.py
- This PR fixes the issue of skipped test cases related to vsphere provider
=> [1LP][RFR] Fixed vsphere skiping issue

cfme/tests/automate/custom_button/test_buttons.py
=> [1LP][RFR]: Missing log validator changes 

cfme/cloud/provider/openstack.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt
Handful of updates to wrapanapi. 
https://github.com/ManageIQ/wrapanapi/releases/tag/3.3.1
{{pytest: cfme/tests/cloud/test_providers.py --long-running --use-provider azure --use-provider openstack }}
=> [RFR] Update to wrapanapi 3.3.1

cfme/tests/automate/test_common_methods.py
- Testing v2_key password decryption using ```manageiq-password```
{{ pytest: cfme/tests/automate/test_common_methods.py -k 'test_miq_password_decrypt' -vv }}
=> [1LP][RFR] New Test: Testing manageiq-password decrypt

cfme/utils/template/scvmm.py
Fixing template upload for SCVMM provider.
=> [1LP][RFR] Fix template upload for scvmm

cfme/tests/automate/custom_button/test_custom_menu.py
=> [1LP][RFR] custom menu manual test

cfme/tests/services/test_myservice.py
{{pytest: cfme/tests/services/test_myservice.py::test_crud_set_ownership_and_edit_tags --use-provider vsphere67-nested -vvvv --long-running}}
=> [1LP][RFR]Adding blocker BZ

cfme/tests/automate/test_common_methods.py
by mistake old method merged in https://github.com/ManageIQ/integration_tests/commit/e32f8c3adbf50241e4318acbfe9a42d531476cc8
=> [RFR] fix test #9011

cfme/test_requirements.py
The purpose of this PR is to add an entry for the FA infra_hosts that is assigned to me. I'll be updating files in integration tests and will need to reference the infra_hosts FA.
=> [1LP][RFR] Added entry for infra_hosts and assigned me "prichard" to it.

cfme/tests/configure/test_config_manual.py, cfme/tests/configure/test_server_name.py, cfme/tests/infrastructure/test_infra_manual.py, cfme/tests/intelligence/reports/test_reports_manual.py, cfme/tests/networks/test_sdn_downloads.py, cfme/tests/test_rest_manual.py, cfme/tests/webui/test_general_ui_manual.py
Adding test coverage for the following BZs:
1504010, 1404280, 1503213, 1595377, 1532404, 1504010, 1727948, 1700378, 1684681, 1475553
=> [1LP][RFR]Add manual tests for test coverage

cfme/configure/configuration/server_settings.py
Adding this role for CFME 5.11
{{ pytest: cfme/tests/control/test_actions.py -k test_action_tag --long-running }}
=> [1LP][RFR] Add in internet_connectivity server role for CFME 5.11

cfme/base/login.py, cfme/base/ssui.py, cfme/base/ui.py, cfme/configure/about.py, cfme/tests/configure/test_server_name.py, cfme/tests/ssui/test_ssui_dashboard.py, requirements/frozen.py2.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py2.txt, requirements/frozen_docs.py3.txt, widgetastic_manageiq/__init__.py
~~NEEDS: https://github.com/RedHatQE/widgetastic.patternfly/pull/100~~
~~NEEDS: #9096 for passing 5.11 PRT~~
Update to use new NavDropdown pattern.
Updates/fixes to SSUI widget locators
Updates/fixes to expandable checks in latest MIQ.
{{ pytest: cfme/tests/configure/test_server_name.py cfme/tests/ssui/test_ssui_dashboard.py }}
=> [1LP][RFR] Update NavDropdown use, parametrized locators, SSUI locator changes

.github/PULL_REQUEST_TEMPLATE.md
Updating PR template
- all commented 
- some workflow info
- PRT run instructions
=> [1LP][RFR] update PR template

cfme/tests/pod/test_appliance_crud.py
polarion metadata update to exclude pod tests
=> [1LP][RFR] exclude pod tests for 5.11 stream

cfme/cloud/provider/__init__.py
- This PR fixes ```is_displayed``` of view - ```CloudProviderImagesView```
- Fixed error:
```
E       assert False
E        +  where False = <cfme.cloud.provider.CloudProviderImagesView object at 0x7f9570f9a7d0>.is_displayed
cfme/tests/cloud_infra_common/test_relationships.py:208: AssertionError
AssertionError
assert False
+  where False = <cfme.cloud.provider.CloudProviderImagesView object at 0x7f9570f9a7d0>.is_displayed
```
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_cloud_provider_relationships[azure-Images] --use-provider=azure --long-running -vvv }}
=> [1LP][RFR] Fixed is displayed of cloud provider image view

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_method.py, cfme/tests/cloud_infra_common/test_power_control_manual.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/infrastructure/test_vm_power_control.py
- This PR adds more test coverage for new BZs reported as well as fixed
=> [1LP][RFR][NOTEST] Adding new manual test cases

.travis.yml
=> Not at all trusty

artifactor/plugins/reporter.py, cfme/modeling/base.py, cfme/utils/dockerbot/pytestbase/Dockerfile, cfme/utils/dockerbot/pytestbase/setup.sh, requirements/frozen.py3.txt
Shriver: This is built off of #9053
=> [RFR] py3prt

cfme/tests/test_appliance.py
=> [1LP][RFR] Add test_fixauth_dryrun_has_feedback

requirements/frozen.py3.txt, requirements/frozen_docs.py3.txt
Resolving some inconsistencies in requirements.
=> Updating requirement versions

cfme/tests/infrastructure/test_scvmm_specific.py
=> [1LP][RFR] Change vm_name_prefix to include "test-"

cfme/utils/dockerbot/pytestbase/get_keys.py, cfme/utils/dockerbot/pytestbase/verify_commit.py
adding more information in PRT commands' output
=> [1LP][RFR] git verify-commit output

cfme/tests/infrastructure/test_infra_manual.py
…ests to add for host comparison.
- __Adding manual tests__ for FA infra_hosts to cover cases for adding default filters and also the major sections in host comparison. I'll be adding additional test for host comparison in upcoming PRs to handle things like download and the different modes and views.
=> [1LP][WIPTEST] Add manual cases for Infra Hosts

cfme/tests/automate/custom_button/test_container_objects.py, cfme/tests/automate/custom_button/test_service_vm_custom_button.py
{{pytest: cfme/tests/automate/custom_button/test_container_objects.py::test_custom_button_dialog_container_obj --use-provider ocp-39-hawk -v}}
=> [1LP][RFR] Remove force stream

cfme/tests/automate/custom_button/test_custom_menu.py, cfme/tests/automate/custom_button/test_generic_objects.py, cfme/tests/automate/custom_button/test_service_objects.py
As start in 5.11 ignoring on 5.10
=> [1LP][RFR] Added ignore_stream for 510

cfme/configure/configuration/server_settings.py, cfme/tests/webui/test_general_ui.py, cfme/tests/webui/test_general_ui_manual.py
__Adding tests__ `test_tls_openssl_verify_mode` that covers BZ 1475553.
{{ pytest: cfme/tests/webui/test_general_ui.py::test_tls_openssl_verify_mode -vvv }}
PS: I feel the need to appreciate @sbulage's effort in helping me resolve errors with this PR. Thanks Satya :)
=> [1LP][RFR]Automate test: test_tls_openssl_verify_mode

.readthedocs.yml, requirements/docs.txt, requirements/frozen.py3.txt, requirements/frozen_docs.py3.txt, requirements/on_rtd.txt
=> [RFR] Update docs requirements for py3

cfme/tests/automate/custom_button/test_custom_menu.py
{{pytest: cfme/tests/automate/custom_button/test_custom_menu.py}}
=> [1LP][RFR] automate custom menu test

cfme/common/provider.py, cfme/common/vm.py, cfme/configure/tasks.py, cfme/tests/automate/test_common_methods.py, cfme/tests/cloud/test_cloud_timelines.py, cfme/tests/infrastructure/test_timelines.py, cfme/tests/perf/workloads/test_provisioning.py, cfme/tests/perf/workloads/test_refresh_providers.py, cfme/tests/perf/workloads/test_refresh_vms.py, cfme/tests/perf/workloads/test_smartstate_analysis.py, cfme/tests/pod/test_appliance_crud.py, cfme/utils/dockerbot/check_prs.py, cfme/utils/grafana.py, cfme/utils/smem_memory_monitor.py, cfme/utils/template/base.py, cfme/utils/template/rhevm.py
fixed one issue and one deprecation warning
=> [1LP][RFR] fixing template upload scripts

cfme/tests/infrastructure/test_tenant_quota.py
- This PR improves test case of testing root tenant - ```My Company``` quota against reconfiguring vm. 
- This test case now checks if quota is exceeded after vm reconfiguration above assigned qutoa.
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py -k 'test_tenant_quota_vm_reconfigure' --use-provider=complete --long-running -qsvvv --use-template-cache }}
=> [1LP][RFR] Fixed quota testing against reconfigure vm

cfme/utils/dockerbot/pytestbase/setup.sh
=> [RFR] Use openssl for PYCURL_SSL_LIBRARY

cfme/tests/infrastructure/test_infra_manual.py
- __Add manual tests__ for FA infra_hosts to cover remaining cases for the hosts comparison view.
=> [1LP][RFR] Add remaining manual tests for Compare Host/Node view to test_infra_manual.py

cfme/automate/buttons.py
This going to help me with local testing to clean stuff. Even in future we can use in automation :+1:
=> [1LP][RFR] delete all methods to clean button and groups

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_instance.py
- Test miq stop and miq abort in state machines
{{ pytest: cfme/tests/automate/test_instance.py -k 'test_miq_stop_abort_with_state_machines' -vv }}
=> [1LP][RFR] New Test: Test miq stop and abort in state machines

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_method.py
- Testing automate method call via state schema type
{{ pytest: cfme/tests/automate/test_method.py  -k 'test_automate_state_method' --use-template-cache -qsvv }}
=> [1LP][RFR] New Test: Testing automate method call in state schema

cfme/tests/configure/test_rest_access_control.py, cfme/tests/test_rest_manual.py
__Adding tests__ `test_create_picture_with_role` automates BZ 1727948, 1731157.
{{ pytest: cfme/tests/configure/test_rest_access_control.py::test_create_picture_with_role -v }}
=> [1LP][RFR] Automate test: test_create_picture_with_role

cfme/tests/test_db_migrate.py
=> [1LP][RFR][NOTEST]Uncollect inplace upgrade test for 5.11.

cfme/automate/explorer/klass.py, cfme/automate/explorer/method.py, cfme/tests/automate/test_method.py, widgetastic_manageiq/__init__.py
- This test case, tests feature - ```notify``` which helps to provide notifications like info, error, warning etc using embedded method.
{{ pytest: cfme/tests/automate/test_method.py -k 'test_method_for_log_and_notify' -vv}}
=> [1LP][RFR] New Test: Testing embedded method for notify feature

cfme/fixtures/rdb.py, cfme/utils/net.py, scripts/harden_security.py
Our socket closing is a bit sloppy, leaving warnings for open socket resources.
=> [1LP][RFR] Use contextmanager to close sockets

cfme/tests/cli/test_appliance_update_manual.py
The removed tests are duplicate of the automated tests.
=> [1LP][RFR][NOTEST] Remove dup tests

cfme/generic_objects/definition/definition_views.py
{{ pytest: cfme/tests/generic_objects/test_definitions.py  -svvvvv }}
=> [1LP][RFR] Fix generic object

cfme/common/vm.py, cfme/tests/infrastructure/test_vm_rest.py, cfme/tests/test_rest_manual.py
__Adding tests__ `test_filtering_vm_with_multiple_ips` to cover BZ: 1684681.
{{ pytest: cfme/tests/infrastructure/test_vm_rest.py::test_filtering_vm_with_multiple_ips -v }}
=> [1LP][RFR]Automate test: test_filtering_vm_with_multiple_ips

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_common_methods.py
- This test case creates one catalog item and orders it and tries to retire that service provisioned via automate method: ```create_retire_request```
{{ pytest: cfme/tests/automate/test_common_methods.py::test_service_retirement_from_automate_method -vv }}
=> [1LP][RFR] New Test: Check whether service is getting retired by automate method

cfme/tests/automate/test_domain.py
- Testing tenant attached to domain
- Automating RFE for automate on 5.11z
{{ pytest: cfme/tests/automate/test_domain.py -k 'test_tenant_attached_with_domain'  -vv }}
=> [1LP][RFR] New Test: Testing tenant attached to domain

cfme/tests/cloud/test_cloud_events.py, cfme/tests/infrastructure/test_timelines.py
Add BZ metadata for cloned BZ to `test_vm_capture`
=> [RFR] Add bugzilla metadata to test_vm_capture

cfme/fixtures/rdb.py
I noticed that RDB started to fail though listened to connections.
This PR should fix that issue.
=> [RFR] fix unavailable RDB

cfme/tests/configure/test_logs.py
1. I wanted to rewrite this using LogValidator as it seems like a better approach.
2. The test itself needed a change as it's hard to get debug outputs for certain providers (see https://bugzilla.redhat.com/show_bug.cgi?id=1633656)
Notes:
I had a problem with this test, when the log level is changed to `warn`, for some time there're still `info` messages - not a lot of time, it's hard to reproduce manually. I came up with that `def _no_info()` that works but I'm open to other suggestions.
{{ pytest: -v cfme/tests/configure/test_logs.py::test_provider_log_level --use-provider=complete }}
=> [RFR] fixed test_provider_log_level

cfme/tests/automate/custom_button/test_service_objects.py
- Fixed failing test by replacing `text` with `hover`
- raised https://bugzilla.redhat.com/show_bug.cgi?id=1745492 and block respective tests.
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_text_display -v}}
=> [1LP][RFR] fix test and added blocker for custom button display

cfme/fixtures/ansible_fixtures.py, cfme/tests/ansible/test_embedded_ansible_crud.py, cfme/utils/appliance/__init__.py
{{ pytest: cfme/tests/ansible/test_embedded_ansible_crud.py -svvvvv --long-running }}
=> [1LP][RFR] Embedded Ansible 511 changes

cfme/test_requirements.py
=> [RFR] Set assignee to jdupuy for Control requirement

cfme/tests/ansible/test_embedded_ansible_basic.py
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -svvvvv --long-running }}
=> [1LP][RFR] Fixed Ansible basic test for CF5.11

cfme/tests/cloud_infra_common/test_tag_visibility.py
Automated these 2 manual medium tests that were incorrectly parametrized to 12 tests.
{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_visibility.py -k 'test_tag_expression_and_with_or_with_not or test_tag_expression_and_with_or' --long-running }}
=> [1LP][RFR] automated the rest of expression editor tests

cfme/tests/services/test_config_provider_servicecatalogs.py
Adding test for Tower job using survey with a text area field
{{ py.test: cfme/tests/services/test_config_provider_servicecatalogs.py }}
510 - PASS
511 - PASS
=> [1LP][RFR] Adding test for Tower job using survey with a text area field

cfme/tests/infrastructure/test_providers.py
Automated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1691109
{{ pytest: -v cfme/tests/infrastructure/test_providers.py::test_rhv_guest_devices_count }}
=> [1LP][RFR] automated BZ for recreating RHV Guest Devices on refresh

cfme/tests/cloud_insights/test_cloud_insights_manual.py, conf/polarion_tools.yaml
Adding manual tests until these can be automated
=> [1LP][RFR] Adding manual CFME/Insights integration test cases

cfme/scripting/setup_env.py
=> [1LP][RFR]  to speed up creating new multi-region environments.

cfme/tests/infrastructure/test_host_manual.py
- __Updating tests__ for FA infra_hosts. Changing caseimportance from low to high for some of the tests.
=> [RFR]Update caseimportance to high for some infra_hosts tests

cfme/tests/cloud_infra_common/test_provisioning.py
Add blocker to Openstack provisioning tests.
=> [1LP][RFR] Add blocker BZ(1746931) -- In openstack provisioning.

cfme/tests/cloud/test_azure_manual.py
Removing this test case as the BZ was closed as `CLOSED CANTFIX`
=> [1LP][RFR] removed test_vm_terminate_deletedisk_azure

cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
it got one test with wrong tier. let's fix it to be in right range
=> [1LP][RFR] changing tier to correct value

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_service_automate.py
- This PR automates test case for automate method which is attached to dynamic service dialog
{{ pytest: cfme/tests/automate/test_service_automate.py::test_automate_method_with_dialog --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing automate method attached to dynamic dialog

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_common_methods.py
- Testing if assigned qutoa i shown as per units in automation logs
{{ pytest: cfme/tests/automate/test_common_methods.py::test_automate_quota_units --use-template-cache --use-provider=complete -qsvvv}}
=> [1LP][RFR] New Test: Testing quota units

cfme/base/login.py, cfme/tests/control/test_bugs.py
Adding a test case for this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1740290
{{ pytest: --long-running cfme/tests/control/test_bugs.py::test_control_breadcrumbs }}
=> [1LP][RFR] Add a new test for control breadcrumbs

cfme/tests/containers/test_ad_hoc_metrics.py, cfme/tests/containers/test_basic_metrics.py, cfme/tests/containers/test_blacklisted_container_events.py, cfme/tests/containers/test_breadcrumbs.py, cfme/tests/containers/test_cockpit.py, cfme/tests/containers/test_configurable_menus.py, cfme/tests/containers/test_containers_smartstate_analysis.py, cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py, cfme/tests/containers/test_containers_summary.py, cfme/tests/containers/test_labels.py, cfme/tests/containers/test_logging.py, cfme/tests/containers/test_manageiq_ansible_custom_attributes.py, cfme/tests/containers/test_node.py, cfme/tests/containers/test_overview_data_integrity.py, cfme/tests/containers/test_pause_resume_workers.py, cfme/tests/containers/test_projects_dashboard.py, cfme/tests/containers/test_provider_configuration_menu.py, cfme/tests/containers/test_provider_openscap_policy_attached.py, cfme/tests/containers/test_relationships.py, cfme/tests/containers/test_reload_button_provider.py, cfme/tests/containers/test_reports.py, cfme/tests/containers/test_search_bar.py, cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py, cfme/tests/containers/test_ssl_providers.py, cfme/tests/containers/test_start_page.py, cfme/tests/containers/test_static_custom_attributes.py, cfme/tests/containers/test_table_views.py, cfme/tests/containers/test_tables_fields.py, cfme/tests/containers/test_tables_sort.py, cfme/tests/containers/test_tags.py
Updating caseimportance for container tests
=> [RFR] Change caseimportance for container tests

cfme/services/catalogs/catalog_items/__init__.py, cfme/tests/automate/custom_button/test_catalog_custom_button.py
- Added Copy  method in catalog item
- Automate on bugzilla
- ** Note:** test will skip as we are automating that bug having open status**
{{pytest: cfme/tests/automate/custom_button/test_catalog_custom_button.py::test_catalog_item_copy_with_custom_buttons}}
=> [1LP][RFR] Cat item copy

cfme/automate/dialog_import_export.py, cfme/automate/explorer/domain.py, cfme/fixtures/automate.py, cfme/fixtures/service_fixtures.py, cfme/services/service_catalogs/__init__.py, cfme/services/service_catalogs/ui.py, cfme/tests/services/test_dialog_element_in_catalog.py, cfme/tests/services/test_service_customer_bz.py
{{ pytest: cfme/tests/services/test_service_customer_bz.py --use-provider vsphere -vvvv --long-running -k test_refresh_dynamic_field }}
=> [1LP][WIPTEST] BZ 1705021 automated

sprout/requirements.txt
sprout has its own requirements file.
=> Update sprout miq-version requirement

cfme/tests/automate/test_method.py
{{py.test: cfme/tests/automate/test_method.py -qsvvv }}
=> [1LP][RFR] wrapping failing tests into set_context(UI)

cfme/tests/cloud/test_cloud_events.py, cfme/tests/cloud_infra_common/test_policy_simulation.py, cfme/tests/intelligence/test_reports_with_timelines.py, cfme/tests/intelligence/test_timelines_rss_removed.py
=> [RFR] Add test_requirements to test cases

cfme/tests/intelligence/test_dashboard.py
The BZ (and its clones) was resolved
{{pytest: cfme/tests/intelligence/test_dashboard.py::test_custom_dashboards -v}}
=> [1LP][RFR] Remove blocker BZ(1666712)

.travis.yml, cfme/configure/configuration/server_settings.py, cfme/tests/cloud/test_targeted_refresh.py, cfme/tests/cloud_infra_common/test_policy_simulation.py, cfme/tests/configure/test_access_control.py, cfme/tests/control/test_bugs.py, cfme/tests/intelligence/reports/test_reports_manual.py, conf/polarion_tools.yaml, requirements/frozen.py3.txt, requirements/frozen_docs.py3.txt, setup.cfg
Indention and initialestimate validation added by polarion-docstrings.
=> [1LP][RFR] Update polarion-docstrings and fix linting

cfme/fixtures/parallelizer/__init__.py
=> [RFR] Fix TypeError in parallelizer/__init__.py

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_rest_custom_button.py
- Added instantiation with rest for custom button group
- Added new test for BZ-1737449
{{pytest: cfme/tests/automate/custom_button/test_rest_custom_button.py::test_associate_unassigned_buttons_rest -v}}
=> [1LP][RFR] unassigned button association with rest

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_method.py
- This PR tests exposed method ```miq_groups``` to automate
- It tests if this method returns ```groups``` associated with user
{{ pytest: cfme/tests/automate/test_method.py::test_automate_user_has_groups --use-template-cache -qsvv }}
=> [1LP][RFR] New Test: Testing exposed method miq_groups to automate

cfme/tests/configure/test_log_depot_operation.py
dropbox is deprecated and will be replaced
https://bugzilla.redhat.com/show_bug.cgi?id=1660143
https://bugzilla.redhat.com/show_bug.cgi?id=1720142
=> [1LP][RFR] removed dropbox from log collection test

cfme/tests/storage/test_volume_backup.py
To have this test approved in Polarion
=> [1LP][RFR] added requirement for test_storage_volume_backup_edit_tag_from_detail

cfme/tests/services/test_rest_services.py, cfme/tests/test_rest_manual.py
- __Adding tests__ `test_edit_service_request_task`
{{ pytest: cfme/tests/services/test_rest_services.py -k "test_edit_service_request_task" --long-running -vvv }}
=> [1LP][RFR]Automate: test_edit_service_request_task

cfme/tests/test_db_migrate_manual.py
=> [1LP][RFR] custom css manual test steps update

cfme/tests/configure/test_register_appliance.py
Fixes test_rhsm_registration_check_repo_names 5.11 runs
Needs cfme-qe/cfme-qe-yamls/merge_requests/827
{{pytest: cfme/tests/configure/test_register_appliance.py::test_rhsm_registration_check_repo_names -v}}
=> [RFR] Fix test_rhsm_registration_check_repo_names

cfme/tests/services/test_catalog_item.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_copy_catalog_item}}
Thanks, @digitronik  for adding copy method  #9302
=> [1LP][RFR] Adding copy catalog item test

cfme/tests/intelligence/reports/test_reports.py, cfme/tests/intelligence/reports/test_reports_manual.py
__Adding tests__ that covers BZ 1504010.
{{ pytest: cfme/tests/intelligence/reports/test_reports.py::test_reports_online_vms -vvv }}
=> [1LP][RFR] Automate test: test_reports_online_vms

cfme/tests/control/test_actions.py
I made a whoopsie :disappointed:
=> [1LP][RFR] Fix unblock statement

cfme/fixtures/automate.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_domain.py
- Testing role of for user where user is able to view domains but not able to perform crud
{{ pytest: cfme/tests/automate/test_domain.py::test_automate_restrict_domain_crud -vvv }}
=> [1LP][RFR] New Test: Testing user role for domains permissions

cfme/services/catalogs/catalog_items/__init__.py, cfme/tests/automate/test_service_automate.py
- Testing value passing between two catalog items by ordering  catalog bundle
- Automating RFE - 1678136
{{ pytest: cfme/tests/automate/test_service_automate.py::test_passing_value_between_catalog_items --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing value passing between two catalog items

cfme/tests/cloud/test_providers.py
test_bad_credentials was leaving the browser on the add provider form
subsequent tests were breaking, as the browser would not navigate away.
{{ pytest: cfme/tests/cloud/test_providers.py::test_cloud_provider_add_with_bad_credentials cfme/tests/cloud/test_providers.py::TestProvidersRESTAPI  --long-running --use-provider extcloud }}
=> [RFR] Fix test interation in test_providers

cfme/tests/v2v/test_v2v_manual.py, cfme/tests/v2v/test_v2v_migrations_ui.py, cfme/v2v/infrastructure_mapping.py, widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_duplicate_mapping_name }}
=> [1LP][RFR] Duplicate Infra mapping test

cfme/tests/test_rest.py
- __Adding tests__ `test_provider_specific_vm`
Note: I need more than 1 provider for this test, so I'm adding another provider from within the test.
{{ pytest: cfme/tests/test_rest.py::test_provider_specific_vm  --provider-limit=2  -vvv }}
=> [1LP][RFR] Automate test: test_provider_specific_vm 

cfme/tests/cli/test_appliance_update_manual.py, cfme/tests/configure/test_analysis_profiles.py, cfme/tests/infrastructure/test_pxe_provisioning.py, cfme/tests/infrastructure/test_vmware_provider.py, cfme/tests/test_db_migrate.py, cfme/tests/test_db_migrate_manual.py, cfme/tests/test_manual.py, cfme/tests/test_replication.py, conf/polarion_tools.yaml
Polarion admins are limiting the testtype field.
subtype1 will be available in the near future with some of the types that we were using.
=> [RFR] Restrict testtype values in polarion meta

cfme/containers/provider/__init__.py
{{ pytest: cfme/tests/containers/test_breadcrumbs.py --use-provider cmqe --long-running }}
=> [1LP][RFR] Fix Breadcrumb test for Container Providers

cfme/tests/configure/test_log_depot_operation.py
Automated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1652116
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_log_depot --long-running }}
=> [1LP][RFR] added check for postgres conf in log collection

docs/guides/dev_guide.rst
Adding some documentation for #9226
=> [1LP][RFR] Add some documentation for miq requirement commands

cfme/tests/ansible/test_embedded_ansible_services.py
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k "test_embed_tower_exec_play_against[azure" --long-running --use-provider azure -svvvv }}
=> [1LP][RFR] Added Ansible test for "play_against" Azure provider.

cfme/tests/cloud/test_tenant_quota.py, cfme/tests/cloud_infra_common/test_quota_manual.py
- Testing instance reconfiguration with changing flavor
{{ pytest: cfme/tests/cloud/test_tenant_quota.py::test_instance_quota_reconfigure_with_flavors --use-template-cache -qsvvv --use-provider=rhos13 }}
=> [1LP][RFR] New Test:  Testing instance reconfiguration against quota

cfme/utils/ssh.py
__Fixing__ messges like: TypeError: super() argument 1 must be type, not None
=> [RFR] Fix TypeError: super() argument 1 must be type, not None

cfme/fixtures/v2v_fixtures.py
With latest 5.10 build flag skip_event_history is introduced in 5.10 too .
=> [RFR][NOTEST]Set flag for 5.10

cfme/tests/ansible/test_embedded_ansible_manual.py
Cleaning up already automated manual tests.
=> [1LP][RFR] Removed already automated tests from manual.

requirements/constraints.txt, requirements/frozen.txt, requirements/template_non_imported.txt
Thanks to @mkoura  for resolving our issue with setting testrun ID via conf when using cfme-testcases to create testruns in polarion.
=> [RFR] Update cfme-testcases, handle testrun ID via conf

cfme/tests/infrastructure/test_vm_delete.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1592430
{{ pytest: -v cfme/tests/infrastructure/test_vm_delete.py::test_delete_vm_on_provider_side }}
=> [1LP][RFR] added new test_delete_vm_on_provider_side

cfme/tests/cloud_infra_common/test_genealogy.py
=> [1LP][RFR] Change FA assignee 

cfme/utils/release.py
Adding label to the release script.
Thanks @john-dupuy for the idea!
=> [RFR] add new label to release script

cfme/services/service_catalogs/__init__.py, cfme/tests/services/test_dynamicdd_dialogelement.py, cfme/tests/services/test_service_customer_bz.py
{{ pytest: cfme/tests/services/test_service_customer_bz.py --use-provider vsphere -vvvv --long-running -k test_update_dynamic_checkbox_field }}
=> [1LP][RFR] BZ 1570152: Automate test update dynamic dialog checkbox

cfme/tests/cloud_infra_common/test_tag_objects.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1726313
{{ pytest: -v cfme/tests/cloud_infra_common/test_tag_objects.py::test_tag_vm_10k_category }}
=> [1LP][RFR] added test_tag_vm_10k_category

cfme/tests/automate/custom_button/test_buttons.py
- Try to cover more fields :dancer: 
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_simulated_object_copy_on_button -v}}
=> [1LP][RFR] improved simulation copy test

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_service_automate.py, cfme/tests/cloud_infra_common/test_power_control_manual.py
=> [NOTEST][1LP][RFR] Added test coverage

cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_under_group_multiple_button_crud}}
=> [1LP][RFR] button test for multiple deletion

cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
Automate test case for https://bugzilla.redhat.com/show_bug.cgi?id=1753237
Depends on #9391 
{{ pytest: --long-running cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py::test_generic_object_button_edited_request }}
=> [1LP][RFR] Test case for BZ 1753237

cfme/tests/v2v/test_v2v_ansible.py, cfme/tests/v2v/test_v2v_manual.py, cfme/v2v/migration_plans.py
Downloading Pre and Post migration logs after migration
=> [1LP][RFR] Download ansible logs

cfme/tests/configure/test_database_ui.py
This PR fixes several issues with test_configure_vmdb_last_start_time. The main issues are:
1.) It ssh's to the appliance in order to perform a journalctl command to find the last startup time of the postgres db. This assumes that the appliance hosts the db.
2.) There is no guarantee that the first journal entry logged by postgres will match the DB startup time displayed in the web UI. The actual startup time as displayed in the UI is taken from the output of the pg_postmaster_start_time() function.
This PR modifies the test to call this db function using appliance.db instead of ssh, to ensure that the actual db_host is used.
{{ pytest: cfme/tests/configure/test_database_ui.py::test_configure_vmdb_last_start_time -v }}
=> [1LP][RFR] Fix db last start time lookup in test_configure_vmdb_last_start_time

cfme/fixtures/v2v_fixtures.py
This BZ is only for 5.10 and we need the workaround for 5.11 too hence forced stream
=> [1LP][RFR] forced stream for 5.11

cfme/tests/automate/__init__.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_simulation.py
- Testing hash data generated by automate method
{{ pytest: cfme/tests/automate/test_simulation.py::test_automate_simulation_result_has_hash_data --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing hash data in simulation tree on UI

cfme/automate/import_export.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_file_import.py
- Testing importing of blank file for datastore and dialog
{{ pytest: cfme/tests/automate/test_file_import.py::test_upload_blank_file -vv }}
=> [1LP][RFR] New Test: Testing import of blank file 

cfme/tests/integration/test_cfme_auth.py
https://bugzilla.redhat.com/show_bug.cgi?id=1759291
=> [1LP][RFR] Block group switching tests for auth

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_v2v_migrations_ui.py, cfme/v2v/migration_plans.py, widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_migration_with_no_conversion }}
=> [1LP][RFR] Migration without conversion hosts

cfme/markers/env_markers/provider.py, cfme/tests/cloud/test_providers.py
The test was still skipped in jenkins, I hope it will fix it.
{{ pytest: -v cfme/tests/cloud/test_providers.py::test_azure_multiple_subscription --use-provider=complete --long-running }}
=> [1LP][RFR] marked test_azure_multiple_subscription with 2 providers

cfme/tests/automate/test_git_import.py
- Fixed Error:
```
>               raise AssertionError('assert_no_error: {}'.format(err))
E               AssertionError: assert_no_error: error: Error: import failed: Selected branch or tag contains more than one domain
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:296: AssertionError
AssertionError
b'assert_no_error: error: Error: import failed: Selected branch or tag contains more than one domain'
```
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_import_multiple_domains --use-template-cache -qsvvv }}
=> [1LP][RFR] Fixed multiple domain import

cfme/configure/configuration/server_settings.py, cfme/utils/appliance/__init__.py, cfme/utils/auth/__init__.py, entry_points.txt, requirements/frozen.txt, requirements/template_scanned_imports.txt
Depends on yaml MR 843. Right now this is for convenience with manual testing of the saml provider.
=> [RFR][NOTEST] Configure saml provider on appliance

cfme/tests/automate/custom_button/test_buttons.py
Just uncollect 
{{pytest: cfme/tests/automate/custom_button/test_buttons.py -k "Load_balancer" -v}}
=> [1LP][RFR] uncollect load balancer for 5.11+

cfme/cloud/provider/ec2.py, cfme/tests/cloud/test_providers.py
QE_TEST_COVERAGE FOR BZ https://bugzilla.redhat.com/show_bug.cgi?id=1631845
{{ pytest:  cfme/tests/cloud/test_providers.py -k "test_add_ec2_provider_with_sts_assume_role" -v }}
=> [1LP][RFR] Ec2 sts assume role test

cfme/intelligence/reports/reports.py, cfme/tests/intelligence/reports/test_reports.py, cfme/tests/intelligence/reports/test_reports_manual.py, widgetastic_manageiq/__init__.py
1. Add data view to reports which is useful for filtering report content.
2. Enhance wt.manageiq Tree, ReportsToolbarViewSelector and SearchBox
- __Add tests__
1. Automate test `test_reports_filter_content`
{{ pytest: cfme/tests/intelligence/reports/test_reports.py --long-running -vvvv }}
=> [1LP][RFR] Report data view

cfme/storage/volume.py, cfme/tests/storage/test_object_store_container.py, cfme/tests/storage/test_object_store_object.py, cfme/tests/storage/test_volume.py, cfme/tests/storage/test_volume_backup.py
Deleted duplicate OSP storage tests and automated test_storage_volume_attached_delete
=> [1LP][RFR] Deleted duplicate OSP storage tests and automated test_storage_volume_attached_delete

cfme/tests/automate/custom_button/test_service_objects.py
- test for BZ-1628727 (ansible service button expression)
- extended usecase 
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_expression_ansible_service}}
=> [1LP][RFR] expression test for ansible service

cfme/cloud/instance/__init__.py, cfme/common/provider.py, cfme/common/vm.py, cfme/fixtures/nuage.py, cfme/infrastructure/virtual_machines.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud/test_tag_mapping.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/configure/test_logs.py, cfme/tests/infrastructure/test_snapshot.py, cfme/tests/infrastructure/test_vmware_provider.py, cfme/tests/networks/test_sdn_inventory_collection.py
This snippet of code appears often, so I created a new `provider` method.
Possible different solution would be just adding `wait=False` argument to `provider.refresh_provider_relationship` for occurrences where it's just supposed to wait without specific times.
:x:   failing PRT tests (3) also failed in report with same error, seems unrelated to my PR
=> [1LP][RFR] add refresh_and_wait / remove copypasta

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_file_import.py
- Testing domain, namespace and class attributes update with import of datastore
{{ pytest: cfme/tests/automate/test_file_import.py::test_automate_import_attributes_updated --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing datastore attribute update

cfme/automate/dialogs/service_dialogs.py, cfme/tests/automate/test_service_dialog.py, cfme/tests/services/test_dialog_element_in_catalog.py, cfme/tests/services/test_service_customer_bz.py
{{ pytest: cfme/tests/services/test_service_customer_bz.py --use-provider vsphere -vvvv --long-running -k test_edit_import_dialog }}
=> [1LP][RFR]  Adding new test of edit import dialog. bz_1720617

cfme/tests/infrastructure/test_snapshot.py
Automated test for the https://bugzilla.redhat.com/show_bug.cgi?id=1552732
{{ pytest: -v cfme/tests/infrastructure/test_snapshot.py::test_revert_to_active_vm --long-running }}
=> [1LP][RFR] added test_revert_to_active_vm for RHV

cfme/tests/services/test_dialog_element_in_catalog.py
- Testing dialog widget types with respect to submit button while ordering service
- Removed test case: ```test_dropdownlist_required_dialog_element``` and parametrized in new test case for dropdown widget
- This PR will automate **7** test cases
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_required_dialog_elements -vvvv }}
=> [1LP][RFR] New Test: Testing dialog widget types while ordering catalog

cfme/tests/automate/generic_objects/test_instances.py
Automating test case for BZ 1741050
{{ pytest: cfme/tests/automate/generic_objects/test_instances.py::test_generic_object_on_service_breadcrumb }}
=> [1LP][RFR] Automate test_generic_object_on_service_breadcrumb

cfme/scripting/appliance.py
- added support for `minor` upgrade of 5.11.z
- Major need more work... for now its not supporting
- Avoid some operation which not needed for minor upgrade.
=> [1LP][RFR] miq appliance minor upgrade 511 support

cfme/markers/env_markers/provider.py
Also update ID's when using the ALL selector to append the provider key (legacy ID)
When encountering multiple providers with the same type+version we were relying on pytest to make our ID's unique, resulting in IDs with an integer directly appended to the ID string.
This resulted in a delta between parametrization against a large provider set and a smaller subset.
I don't think we want ALL to be the default.
This results in a change in test parametrization like the following *if the ALL selector is used*
```
<Module 'cfme/tests/cloud/test_keypairs.py'>
<Function 'test_keypair_crud[openstack-130]'>
<Function 'test_keypair_crud_with_key[openstack-130]'>
<Function 'test_keypair_create_cancel[openstack-130]'>
<Function 'test_keypair_create_name_validation[openstack-130]'>
<Function …
```
=> [1LP][RFR] Change default provider marker selector to ONE_PER_VERSION

cfme/tests/ansible/test_embedded_ansible_manual.py, cfme/tests/ansible/test_embedded_ansible_tags.py
=> [1LP][RFR][NOTEST] Added BZ param in the already automated tests.

cfme/configure/access_control/__init__.py, cfme/tests/automate/custom_button/test_service_objects.py
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_role_access_service -v}}
=> [1LP][RFR] rbac roles custom button

cfme/automate/import_export.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_git_import.py
- Testing domain import with or without internet connectivity to appliance
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_domain_import_connection -vvv }}
=> [1LP][RFR] New Test: Testing domain import with or without connection

cfme/infrastructure/virtual_machines.py, cfme/tests/infrastructure/test_vm_engine_relationship.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1534400
{{ pytest: -v cfme/tests/infrastructure/test_vm_engine_relationship.py }}
=> [1LP][RFR] automated BZ1534400

cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
{{ pytest: cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py::test_generic_object_button_delete_flash }}
=> [1LP][RFR] Automate test_generic_object_button_delete_flash

cfme/provisioning.py, cfme/tests/cloud_infra_common/test_quota_manual.py, cfme/tests/infrastructure/test_tenant_quota.py
- Testing quota exceed mail. Configured mail using custom domain.
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py::test_quota_exceed_mail_with_more_info_link --use-template-cache -qsvvv --use-provider=rhv43 --long-running }}
=> [1LP][RFR] New Test: Testing quota exceed mail

cfme/tests/infrastructure/test_vm_reconfigure.py
{{ pytest: cfme/tests/infrastructure/test_vm_reconfigure.py --use-provider vsphere6-nested -vvvv --long-running -k test_vm_reconfig_resize_disk_snapshot }}
- Automating VM reconfiguration resize disk snapshot
- This PR will automate 18 test cases
=> [1LP][RFR] Adding new test of vm reconfig resize disk snapshot

cfme/tests/webui/test_expression_editor.py
{{ pytest: -v cfme/tests/webui/test_expression_editor.py::test_apply_after_save }}
=> [RFR] automated BZ 1741243

cfme/common/vm_views.py, cfme/fixtures/authentication.py, cfme/tests/integration/test_auth_manual.py, cfme/tests/integration/test_ldap_auth.py
{{ pytest: --use-provider vsphere65-nested cfme/tests/integration/test_ldap_auth.py }}
=> [RFR] automation for test_validate_lookup_button

cfme/automate/buttons.py
Test failures with the screenshot showing a filled form and an active 'Add' button, but the button was never clicked.
Wrapping the 'Add' button click in a wait.
{{ pytest: --use-provider complete --long-running cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_order_sort cfme/tests/automate/custom_button/test_infra_objects.py::test_custom_button_dialog_infra_obj cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_automate_evm_obj}}
=> [RFR] Update automate button group create, add button wait

cfme/cloud/provider/azure.py, cfme/cloud/provider/ec2.py, cfme/cloud/provider/gce.py, cfme/cloud/provider/openstack.py, cfme/cloud/provider/vcloud.py, cfme/containers/provider/openshift.py, cfme/infrastructure/provider/kubevirt.py, cfme/infrastructure/provider/openstack_infra.py, cfme/infrastructure/provider/rhevm.py, cfme/infrastructure/provider/scvmm.py, cfme/infrastructure/provider/virtualcenter.py, cfme/networks/provider/nuage.py, cfme/physical/provider/lenovo.py, cfme/physical/provider/redfish.py, cfme/utils/appliance/__init__.py, cfme/utils/providers.py, sprout/appliances/models.py, sprout/appliances/tasks/maintainance.py, sprout/sprout/settings.py
=> [RFR] sprout tasks' fixes

cfme/tests/v2v/test_v2v_cancel_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py --use-provider rhv43 --use-provider vsphere65-nested --provider-limit 2 -vvvv --long-running -k test_retry_migration_plan }}
=> [1LP][RFR] Retry migration plan

cfme/tests/containers/test_container_provider_crud.py
=> [1LP][RFR] Add BZ automates marker to Containers Crud Test

cfme/tests/infrastructure/test_host.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1669011
{{ pytest: -v cfme/tests/infrastructure/test_host.py::test_add_ipmi_refresh }}
=> [1LP][RFR] automated BZ 1669011

cfme/automate/buttons.py, cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py -v}}
=> [1LP][RFR] moved flash msg to test and improved checks

cfme/test_requirements.py, cfme/tests/cli/test_appliance_console_db_restore.py, cfme/tests/cli/test_appliance_log_rotate.py, cfme/tests/cli/test_appliance_update_manual.py, cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py, cfme/tests/cloud_infra_common/test_provisioning_manual.py, cfme/tests/configure/test_proxy.py, cfme/tests/configure/test_register_appliance.py, cfme/tests/configure/test_schedule_operations.py, cfme/tests/configure/test_version.py, cfme/tests/infrastructure/test_customization_template.py, cfme/tests/infrastructure/test_host_provisioning.py, cfme/tests/infrastructure/test_iso_provisioning.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_pxe.py, cfme/tests/infrastructure/test_pxe_provisioning.py, cfme/tests/infrastructure/test_vm_clone.py, cfme/tests/integration/test_auth_scripts.py, cfme/tests/platform/test_advanced_config.py, cfme/tests/platform/test_locale.py, cfme/tests/services/test_provision_stack.py, cfme/tests/test_appliance.py, cfme/tests/test_db_migrate.py, cfme/tests/test_db_migrate_manual.py
Marking tests with test_requirements
Some requirements do not exist yet. I presume they will get added to Polarion by the importer.
Some requirements were changed. I presume I will have to delete the old ones from polarion by hand.
Some of the touched tests failed but I was not changing any tests logic so they fail for reasons unrelated to this PR. Perhaps I should just have set this as NOTEST.
=> [1LP][RFR] Add test_requirements for jhenner's tests

cfme/tests/ansible/test_embedded_ansible_manual.py
Clean up duplicate cases, parametrize with provider.
=> [RFR] Remove duplicated ansible test cases, parametrize with provider

cfme/tests/candu/test_nor_rightsize.py
These tests are duplicates, and should be provider parametrized.
=> [RFR] [NOTEST] Parametrize the nor/rightsize tests, eliminate duplication

cfme/common/__init__.py, cfme/containers/topology.py, entry_points.txt
Replacing PR #7591, but dropping the dashboard updates.
DefaultDashboard conversion will take some more work, splitting it up.
=> [1LP][RFR] Update cfme.container.topology, CEMv3

cfme/common/provider.py
- __Enhancement__ for BaseProvider class
=> [1LP][RFR] Add stringification function to BaseProvider class

cfme/configure/configuration/region_settings.py, cfme/tests/test_replication.py
{{ pytest: cfme/tests/test_replication.py -k "test_replication_appliance_add_single_subscription" }}
=> [1LP][RFR] Automating Replication Test

cfme/tests/intelligence/test_dashboard.py
__Cleanup__:      There is no meaningful test steps description.
=> [NOTEST][1LP][RFR]Remove test_identical_dashboard_widgets

cfme/tests/cli/test_appliance_console.py
{{ pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_scap }}
=> [RFR] Add BZ Blocker test_appliance_console_scap

cfme/tests/candu/test_candu_manual.py, cfme/tests/test_manual.py
=> [1LP][RFR] Moving candu manual tests

cfme/markers/meta.py
This is _way too much logging_
=> [1LP][RFR] Update meta marker to debug log

cfme/tests/automate/test_service_dialog.py, cfme/tests/services/test_different_dialogs_in_catalogs.py
- Testing customer scenario where automate method called multiple times where it need not be called.
{{ pytest: cfme/tests/automate/test_service_dialog.py::test_automate_methods_from_dynamic_dialog_should_run_as_per_designed --long-running --use-template-cache -qsvvv}}
=> [1LP][RFR] New Test: Testing automate method called more than expected

cfme/tests/services/test_dialog_element_in_catalog.py
- Testing expression method for collecting vms associated with rhvem provider using dialog
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_service_dialog_expression_method --long-running --use-template-cache -qsvvv --use-provider=complete }}
=> [1LP][RFR] New Test: Testing expression method with dialog

cfme/test_requirements.py, cfme/tests/infrastructure/test_snapshot.py
- __Updating tests__ for feature snapshot to take ownership of them.
=> [RFR] Update assignee in Polarian doc block for snapshot tests

cfme/intelligence/reports/reports.py, cfme/tests/intelligence/reports/test_reports.py, cfme/tests/intelligence/reports/test_reports_manual.py, widgetastic_manageiq/__init__.py
1. test_reports_sort_column
1. Enhance report's data view to implement sort column.
- __Fixing__
1. Fix `Table` to sort data properly.
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_reports_sort_column"   -sqvvv }}
=> [1LP][RFR] Report sort column

cfme/tests/ansible/test_embedded_ansible_services.py
The global fixture is module scoped, and the tests in test_embedded_ansible_services are modifying the object given by the fixture, breaking other tests.
=> [RFR] Add function scoped ansible cat item fixture

cfme/tests/cli/test_appliance_console.py
Adding reboot to check the changes done via appliance console should persist after appliance reboot to cover the BZ's #1755398 #1766939
{{pytest: cfme/tests/cli/test_appliance_console.py -k "test_appliance_console_dhcp or test_appliance_console_static_ipv4 or test_appliance_console_static_ipv6" -vvv}}
=> [1LP][RFR]Adding reboot to the test steps

cfme/tests/automate/custom_button/test_service_objects.py
No need of provider parametrization. 
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_dialog_service_archived -v}}
=> [1LP][RFR] one vsphere only 

cfme/services/requests.py
- The reason why request was not clearing at tear down
=> [1LP][RFR] Fix request remove

cfme/tests/cloud_infra_common/test_quota_manual.py, cfme/tests/infrastructure/test_tenant_quota.py
- Testing quota not fails after removing disk from vm
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py::test_quota_not_fails_after_vm_reconfigure_disk_remove --use-template-cache -qsvvv  --long-running --use-provider=complete}}
=> [1LP][RFR] New Test: Test vm with quota for disk removal

cfme/tests/networks/test_sdn_inventory_collection.py
Needs this(https://github.com/ManageIQ/wrapanapi/pull/421) before merge to make it working.
{{ pytest:  -k "test_sdn_nsg_firewall_rules" -v --use-provider azure }}
=> [1LP][RFR]test_sdn_nsg_firewall_rules fix

cfme/tests/ssui/test_ssui_myservice.py
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_list_supported_languages_on_ssui}}
=> [1LP][RFR] Automate lang check test

cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_simulation.py
- Test copy button on simulation page
{{ pytest: cfme/tests/automate/test_simulation.py::test_simulation_copy_button --use-template-cache -qsvv }}
=> [1LP][RFR] New Test: Test copy button on simulation page

cfme/tests/infrastructure/test_provisioning_rest.py
existing assert is always true
=> [RFR] fix wrong assert

cfme/tests/infrastructure/test_host.py, widgetastic_manageiq/__init__.py
- __Enhancement__ for selecting entities in the JSBaseEntity class. Using new functions ensure_checked() or ensure_unchecked() will make sure entities are unchecked before selecting them, and checked before un-selecting them.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_crud
cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_refresh_multi
cfme/tests/infrastructure/test_host.py::test_compare_hosts_from_provider_allhosts }}
=> [RFR][1LP] Add ensure_checked() and ensure_unchecked() functions to JSBaseEntity.

cfme/tests/containers/test_chargeback.py, cfme/tests/containers/test_reports.py
There are two test suits with wrong markers
=> [1LP][RFR] fixing wrong markers

cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Removing already parameterized tests from manual SSA test cases file.
=> [1LP][RFR] Removed already automated tests.

cfme/storage/manager.py, cfme/tests/cloud_infra_common/test_tag_objects.py
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py::test_tagvis_cloud_object -v --use-provider complete }}
=> [1LP][RFR] automate: test_tagvis_storage_managers

cfme/tests/ssui/test_ssui_service_catalogs.py
{{ pytest: cfme/tests/ssui/test_ssui_service_catalogs.py  -k 'test_refresh_ssui_page' --long-running --use-template-cache -sqvvv }}
=> [1LP][RFR] Adding a new test to refresh ssui browser page

cfme/base/__init__.py, cfme/tests/configure/test_zones.py
This PR makes the following changes for zone-related tests:
1.) In test_zone_crud, when a zone has been deleted, the subsequent call to zone.exists will log an exception:
```
2019-11-07 14:15:58,710 [I] [cfme] (MiqBrowser) handling alert: 'Are you sure you want to delete this Zone?' (cfme/utils/appliance/implementations/common.py:82)
2019-11-07 14:15:58,711 [I] [cfme] (MiqBrowser)   accepting (cfme/utils/appliance/implementations/common.py:93)
2019-11-07 14:15:59,238 [I] [cfme] [ZoneSettingsView/flash]: exact match of the flash message 'Zone "laUmU": Delete successful' (.cfme_venv/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:275)
2019-11-07 14:15:59,403 [W] [cfme] [ZoneSettingsView/flash]: __locator__ of FlashMessage class returns a WebElement! …
```
=> [1LP][WIPTEST] Fix zone tests

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_conversion_host_ui.py, cfme/v2v/migration_settings.py, widgetastic_manageiq/__init__.py
Adding create conversion host from UI test .
Will add remove conversion host test in next PR.
{{ pytest: cfme/tests/v2v/test_conversion_host_ui.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running }}
=> [1LP][RFR] V2V conversion host ui

cfme/cloud/host_aggregates.py, cfme/tests/cloud_infra_common/test_tag_objects.py
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py::test_tagvis_cloud_object -v --use-provider complete }}
=> [1LP][RFR] automate: test_tagvis_cloud_host_aggregates

cfme/tests/configure/test_access_control.py
Automating user crud operations for Tenant administrator
{{pytest: cfme/tests/configure/test_access_control.py -k test_tenantadmin_user_crud}}
PRT results:
510 - PASS
511 - PASS
=> [1LP][RFR] Multitenancy user crud as tenant admin

cfme/tests/v2v/test_v2v_smoke.py
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running  }}
=> [RFR] Fix Smoke tests

cfme/tests/services/test_dynamicdd_dialogelement.py
{{ pytest: cfme/tests/services/test_dynamicdd_dialogelement.py  -vvvv --long-running -k test_dynamic_field_on_textbox }}
=> [1LP][RFR] Adding new test of service dialog dynamic textbox

cfme/tests/cloud_infra_common/test_snapshots_rest.py
This pattern was directly calling the fixture function, which is not allowed by pytest.
=> [1LP][RFR] Fix fixture call pattern in test_snapshots_rest

cfme/common/provider.py
make timeout/delay for wait_for kwargs to BaseProvider.validate
pass timeout=300 in BaseProvider.create_rest
=> [1LP][RFR] Shorten default provider create_rest validate timeout

cfme/tests/automate/test_file_import.py
- Fixed domain import name
{{ pytest: cfme/tests/automate/test_file_import.py::test_domain_import_file --use-template-cache -qsvv }}
=> [1LP][RFR] Fixed datastore import

cfme/utils/appliance/__init__.py
Wrap exceptions on appliance stack hook execution.
I'm also looking at moving the hook registration into pytest_configure, but need to thoroughly test the stack push order in the existing appliance plugin to make sure the hook is injected before anything is pushed to the stack.
=> [RFR] Add exception diaper to appliance hooks, reduce ssh wait time

cfme/tests/automate/custom_button/__init__.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_service_dialog.py
- Test values populated from dynamic dialog and are passing to service or not
{{ pytest: cfme/tests/automate/test_service_dialog.py::test_dialog_element_values_passed_to_button --use-template-cache -qsvvv --long-running}}
=> [1LP][RFR] New Test: Test values populated from dynamic dialog

cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_tag_visibility.py, cfme/tests/configure/test_log_depot_operation.py, cfme/tests/infrastructure/test_iso_datastore.py, cfme/tests/infrastructure/test_publish_vm_to_template.py, cfme/tests/webui/test_advanced_search.py
"all of your focus areas (should) have at least a couple of critical test cases. They might not be critical in scope of whole ManageIQ, but relatively, within the scope of the focus area, there should be a couple that are critical."
Here they are.
=> [1LP][RFR][NOTEST] change caseimportance of some tests

cfme/tests/cli/test_appliance_update.py, cfme/tests/cloud_infra_common/test_provisioning.py, cfme/tests/configure/test_schedule_operations.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/intelligence/test_dashboard.py
Management wants to have more tests marked as critical.
=> [1LP][RFR][NOTEST]Make some jhenner's high importance tests critical.

cfme/tests/configure/test_register_appliance.py, cfme/tests/test_db_migrate_manual.py
Add BZ links to covering cases
=> [1LP][RFR][NOTEST] Add BZ links to the test cases

cfme/tests/services/test_service_catalog_dialog_manual.py, cfme/tests/services/test_service_catalogs.py
{{pytest: cfme/tests/services/test_service_catalogs.py::test_order_service_after_deleting_provider --long-running -v}}
=> [1LP][RFR] service order after prov deletion

cfme/tests/infrastructure/test_providers.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1594817
{{ pytest: -v cfme/tests/infrastructure/test_providers.py::test_rhv_custom_attributes_after_refresh }}
=> [1LP][RFR] automated BZ 1594817

cfme/tests/services/test_catalog_item.py, cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_dropdown_int_required --long-running}}
=> [1LP][RFR] Adding dialog dropdown int test

cfme/automate/explorer/domain.py, cfme/automate/import_export.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_domain.py
- Testing error message while importing locked domain to existing domain
- Testing if domain's childs like namespace, class, methods, instances are not getting override after importing new childs in same domain
{{ pytest: cfme/tests/automate/test_domain.py::test_existing_domain_child_override --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing error message while importing locked domain to existing domain

cfme/ansible/repositories.py, cfme/fixtures/ansible_fixtures.py, cfme/tests/ansible/test_embedded_ansible_basic.py, cfme/tests/ansible/test_embedded_ansible_manual.py
Thanks @valaparthvi for debugging.
{{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k "test_embedded_ansible_private_repository_crud" --long-running -svvvv }}
=> [1LP][RFR] Ansible Automation for Private Repository CRUD.

cfme/automate/explorer/domain.py, cfme/tests/automate/__init__.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_git_import.py
- Testing domain refresh via API call with verify ssl
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_verify_ssl --use-template-cache -qsvv }}
=> [1LP][RFR] New Test: Testing domain refresh via API call with verify ssl

cfme/tests/containers/test_relationships.py
Removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/3332
=> [1LP][RFR] Remove test_container_status_relationships_data_integrity

cfme/tests/intelligence/reports/test_reports_schedules.py
1. Add `test_miq_schedule_validation_failed` for [customer BZ ](https://bugzilla.redhat.com/show_bug.cgi?id=1740229).
{{ pytest: cfme/tests/intelligence/reports/test_reports_schedules.py -k "test_miq_schedule_validation_failed" }}
=> [1LP][RFR] New Customer Scenario Test: test_miq_schedule_validation_failed

cfme/ansible/playbooks.py
cc @valaparthvi 
{{pytest: cfme/tests/ansible/test_embedded_ansible_tags.py::test_ansible_tagging[tag_details-playbook-visible] --long-running -svvvvv}}
=> [1LP][RFR] Fixed Ansible playbook tags tests.

cfme/tests/configure/test_rest_access_control.py
- __Fixing__ 
1. `TestUsersViaREST` which was failing because of incorrect use of fixture.
{{ pytest: cfme/tests/configure/test_rest_access_control.py -k "TestUsersViaREST" -vvv }}
=> [1LP][RFR] Fix test: TestUsersViaREST

cfme/common/provider.py, cfme/common/vm_console.py, cfme/configure/configuration/server_settings.py, cfme/fixtures/vm_console.py, cfme/infrastructure/provider/virtualcenter.py, cfme/services/myservice/ssui.py, cfme/test_requirements.py, cfme/tests/cloud_infra_common/test_html5_vm_console.py, cfme/tests/infrastructure/test_vmrc_console.py, cfme/tests/infrastructure/test_webmks_console.py, cfme/tests/ssui/test_ssui_myservice.py, cfme/utils/net.py, requirements/frozen.txt
- __Fixing__ Console Tests - Automated and Manual both kinds. 
{{pytest: cfme/tests/infrastructure/test_webmks_console.py cfme/tests/cloud_infra_common/test_html5_vm_console.py -vvv --use-provider complete }}
=> [1LP][RFR] Console tests

cfme/configure/configuration/region_settings.py, cfme/tests/test_replication.py
- __Adding tests__ Adding new tc to validate remote appliance's credentials before saving on the global appliance .
{{pytest: cfme/tests/test_replication.py -k "test_replication_subscription_revalidation_pglogical" --long-running -v}}
=> [1LP][RFR] New Test: remote appliance's credential validation testcase

cfme/tests/test_replication.py
Co-authored-by: Devidas Gaikwad <dgaikwad@redhat.com>
Co-authored-by: mnadeem92 <mnadeem@redhat.com>
{{ pytest: cfme/tests/test_replication.py::test_replication_remote_to_global_by_ip_pglogical --long-running  -svvv }}
=> [1LP][RFR] Automating test_replication_remote_to_global_by_ip_pglogical

cfme/tests/cloud_infra_common/test_html5_vm_console.py, cfme/tests/cloud_infra_common/test_html5_vm_console_ssui.py
**Fixing Console** Tests - SSUI
This is built on top of #9595, so we need to merge that first and then merge this.
Passed in jenkins at
5.11 -- job/kk-console-chrome/55/console
5.10 -- job/kk-console-chrome/62/console
{{pytest: cfme/tests/cloud_infra_common/test_html5_vm_console_ssui.py -vvv --use-provider complete }}
=> [1LP][RFR]Ssui console tests

cfme/tests/containers/test_table_views.py
{{ pytest: cfme/tests/containers/test_table_views.py  --use-provider ocp-311-hawk }}
=> [1LP][RFR] Refactor test_table_views for containers

cfme/configure/access_control/__init__.py
- This fix for test **`test_delete_group_with_assigned_user`**
run showing not breaking other things 
{{pytest: cfme/tests/configure/test_access_control.py -v --long-running}}
=> [1LP][RFR] fix flash for group deletion

cfme/utils/appliance/__init__.py
- As per @mshriver suggestion moving `upgrade` method for appliance in this PR. Actually, It part of https://github.com/ManageIQ/integration_tests/pull/9510;
=> [1LP][RFR] upgrade method for appliance

cfme/tests/configure/test_access_control.py
=> [1LP][RFR] Fix TypeError in pytest.raises call

artifactor/plugins/filedump.py, artifactor/plugins/ostriz.py, artifactor/plugins/reporter.py
3 issues have been found in artifactor plugins. This PR is going to sort them out
=> [RFR] Fix artifactor plugins

cfme/tests/cloud_infra_common/test_provisioning.py, cfme/tests/configure/test_db_backup_schedule.py, cfme/tests/test_db_migrate_manual.py
Adding tests and markers to resolve customer bugs.
=> [RFR] Changes to resolve the customer qa test coverage

cfme/tests/cli/test_appliance_update.py
The BZ is fixed.
I think tests may need this to pass:
https://github.com/ManageIQ/integration_tests/pull/9646
=> [1LP][RFR] Remove the BZ 1704835 workaround and mark with automates.

cfme/tests/test_replication.py
This PR is dependent on #9519 
{{ pytest: cfme/tests/test_replication.py -k "test_replication_powertoggle"  --long-running }}
=> [1LP][RFR] Automating test replication powertoggle

cfme/control/explorer/actions.py, cfme/tests/automate/test_automate_manual.py, cfme/tests/automate/test_simulation.py
- Testing attribute value pairs of action type invoke automation
{{ pytest: cfme/tests/automate/test_simulation.py -k 'test_action_invoke_custom_automation' --use-template-cache -qsvvv }}
=> [1LP][RFR] New Test: Testing attribute value pairs of action type invoke automation

cfme/tests/cli/test_appliance_log_rotate.py
The log path changed. Test needed to accommodate to that.
=> [1LP][RFR] Fix test_appliance_log_rotate on 5.11

cfme/cloud/stack.py, cfme/exceptions.py, cfme/tests/cloud/test_stack.py, cfme/utils/appliance/implementations/ui.py
Move the import for this, prompted by #9631
=> [1LP][RFR] Move CandidateNotFound exception imports

cfme/fixtures/service_fixtures.py, cfme/tests/services/test_dialog_element_in_catalog.py, requirements/frozen.txt, requirements/frozen_docs.py3.txt
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py -v}}
=> [1LP][RFR] Automate test dialog not required behavior

cfme/infrastructure/config_management/__init__.py, cfme/tests/webui/test_general_ui.py
Creating a test case for https://bugzilla.redhat.com/show_bug.cgi?id=1741310
{{ pytest: cfme/tests/webui/test_general_ui.py::test_add_provider_button_accordion }}
=> [RFR] Add in test case for BZ 1741310

cfme/tests/candu/test_utilization_metrics.py
{{py.test: cfme/tests/candu/test_utilization_metrics.py --use-provider complete -k "test_azone_disk_io"}}
=> [1LP][RFR] Add test for disk io for availability zones

docs/getting_started.rst
=> [1LP][RFR] Update getting started doc, mention core support for Fedora

cfme/utils/appliance/__init__.py
=> [1LP][RFR] Clear cached appliance DB properties on appliance upgrade

cfme/tests/cloud_infra_common/test_genealogy.py, cfme/tests/configure/test_visual_infra.py, cfme/tests/infrastructure/test_advanced_search_vms.py, cfme/tests/services/test_config_provider_servicecatalogs.py, cfme/tests/services/test_pxe_service_catalogs.py
There will be more to come, but here's a small block.
Updating our plugins to include an option to report on closed blockers, which will allow us to automate this check.
=> [1LP][RFR] Remove old/irrelevant/closed blockers

cfme/tests/configure/test_access_control.py
{{pytest: cfme/tests/configure/test_access_control.py -k 'test_permission_edit or test_permissions' -v}}
=> [1LP][RFR] fix test with new product feature changes

cfme/tests/cli/test_appliance_console.py, cfme/tests/test_db_migrate_manual.py
=> [1LP][RFR] Adding Test Coverage for customer BZ

cfme/infrastructure/cluster.py, cfme/tests/cloud_infra_common/test_relationships.py
- Testing relationships for vm under particular cluster
- Depend on #9788 
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py -k 'test_ssa_cluster_relationships' --use-template-cache -qsvvv --use-provider rhv43 }}
=> [1LP][RFR] New Test: Testing relationships for vm under particular cluster

cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Here is MR Link--> https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/877
=> [1LP][RFR][NOTEST] Removed already automated SSA manual tests.

cfme/tests/infrastructure/test_publish_vm_to_template.py, cfme/tests/infrastructure/test_vmware_provider.py
- __Fixing__ __test_vmware_provider__ to have correct scope and __test_publish_vm_to_template__ to have correct provider setup
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py cfme/tests/infrastructure/test_publish_vm_to_template.py -vv}}
=> [RFR]Vmware automation tests

cfme/tests/integration/test_auth_manual.py
Adding test coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1784145
=> [1LP][RFR] Add manual case for OpenID auth provider

cfme/scripting/release.py
This was causing some very odd behavior within click.echo method.  Build the strings first.
=> [1LP][RFR] Fix click.echo calls in release script

cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Cleanup manual tests related to Azure SSA.
=> [1LP][RFR][NOTEST] Removed automated Azure manual tests related to SSA.

cfme/tests/automate/test_service_automate.py, cfme/tests/cloud_infra_common/test_quota_manual.py
- This test case is to check Quota calculation using service dialog overrides.
{{ pytest: cfme/tests/automate/test_service_automate.py -k 'test_quota_calculation_using_service_dialog_overrides' --use-template-cache -qsvvv --use-provider rhv43 --long-running }}
=> [1LP][RFR] New Test: Testing quota calculation check using service dialog overrides

cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_custom_button_service_dialog_link -v}}
=> [1LP][RFR] Automate BZ-1770300

cfme/tests/cli/test_appliance_console.py
__adding_tests__ Test to check SSL is by default enabled or not, It should be enabled by default.
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_ssl -v}}
=> [1LP][RFR] CLI - Test to check SSL 

requirements/frozen.txt, requirements/frozen_docs.py3.txt
More info at
https://github.com/psav/riggerlib/pull/30/commits/b6e9c769f69209112389294c9efeae4df3a6e512
=> [RFR] Bump riggerlib to mitigate zmq deadlock issue

cfme/test_requirements.py, cfme/tests/cloud_infra_common/test_vm_ownership.py
Updated assignee for ownership FA and genealogy test cleanup.
=> Update FA assignee 

cfme/tests/cli/test_appliance_console.py
__Adding tests__ adding test to test navigation from all menus to back using control+c
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_cancel -v}}
=> [1LP][RFR] CLI - Test appliance console cancel

cfme/tests/infrastructure/test_config_management.py
{{ pytest: cfme/tests/infrastructure/test_config_management.py -k dialog_creation }}
=> [RFR] Fix parametrization for Tower dialog creation tests

cfme/fixtures/v2v_fixtures.py
Some time openstack event catchers takes time to start, So adding 30 second wait time and re-check worker status before skipping the test.
{{ pytest: cfme/tests/v2v/test_conversion_host_ui.py -k "test_add_conversion_host_ui_crud" --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
=> [1LP][RFR]Adding wait_for for event workers to gets start

cfme/tests/automate/custom_button/test_rest_custom_button.py
{{pytest: cfme/tests/automate/custom_button/test_rest_custom_button.py -vv}}
=> [1LP][RFR] uncollect load balancer for 5.11

cfme/tests/v2v/test_v2v_manual.py, cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
Automating New TC: test_osp_if_no_password_is_exposed_in_logs_during_migration
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py -k "test_if_no_password_is_exposed_in_logs_during_migration" --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -v }}
=> [1LP][RFR] Automate passoword visibility test

cfme/test_requirements.py, cfme/tests/migration_analytics/test_migration_analytics.py, conf/polarion_tools.yaml
- Added **Migration Analytics** in requirements
- Added **MigrationAnalytics** as casecomponent
- Added manual test cases
=> [1LP][NOTEST][RFR] Added MA requirement and manual test cases

cfme/tests/cloud/test_providers.py
Added automated test for refresh_with_stack_without_parameters
{{ pytest: -k "test_refresh_with_stack_without_parameters" -v }}
=> [1LP][RFR]Added test_refresh_with_stack_without_parameters

cfme/tests/cli/test_appliance_console.py
__adding test__ test to check "secondary DNS should be shown while reconfiguring the static network configuration"
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_static_dns -v}}
=> [1LP][RFR] CLI - test to re-configure secondary dns

cfme/scripting/release.py
Using the date only, this was including PR's merged on the tag day, more than it should have been.
Tested/counted with last few tags.
=> Update miq release to use datetimes for PR listing

cfme/tests/cloud_infra_common/test_discovery_and_support.py
- Fixed vm archived status
{{ pytest: cfme/tests/cloud_infra_common/test_discovery_and_support.py::test_vm_discovery --long-running -vv --use-provider complete }}
=> [1LP][RFR] Fixed discover vm test case

cfme/tests/configure/test_config_manual.py, cfme/tests/configure/test_rbac_landing_page.py
1. `test_validate_landing_pages_for_rbac`
{{ pytest: cfme/tests/configure/test_rbac_landing_page.py -vvv }}
=> [1LP][RFR]Automate: test_validate_landing_pages_for_rbac

cfme/tests/cli/test_appliance_console.py
__Adding tests__ 
- Setting up IPV4, IPV6 and hostname 
- Verification of IPV4 and hostname
{{pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_network_conf -v}}
=> [1LP][RFR] testing network configuration for ipv4 and ipv6

cfme/tests/cloud/test_providers.py
{{ pytest: -k "test_create_sns_topic" -v }}
=> [1LP][RFR]Automated test_create_sns_topic

cfme/tests/v2v/test_v2v_cancel_migrations.py
{{pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k retry --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims -qsvv }}
=> [RFR] Fix retry migration plan test

cfme/utils/template/ec2.py
Needs this wrapanapi PR https://github.com/RedHatQE/wrapanapi/pull/440 to be working.
=> [1LP][RFR]5.11 ec2 image upload

cfme/base/__init__.py, cfme/base/ui.py, cfme/cloud/provider/__init__.py, cfme/infrastructure/cluster.py, cfme/infrastructure/datastore.py, cfme/infrastructure/host.py, cfme/infrastructure/provider/__init__.py, cfme/optimize/utilization.py
- Enhancement in Utilization model page
- New views and nagivation destination against `Utilization` obj
- We have Utilization collection but to instantiate Utilization and find related entities like... host, datastore is a hectic task.
Registering some navigation destination against these Entity objects with short-name `Utilts`; which will try to resolve entity dependencies.  
{{pytest: cfme/tests/webui/test_splitter.py::test_pull_splitter_persistence[UtilizationCollection-All] -v}}
=> [1LP][RFR] Utilization Model page

cfme/tests/infrastructure/test_vm_migrate.py
__Adding tests__  To check getting correct error message and log entry on vm migration fail
{{pytest: ./cfme/tests/infrastructure/test_vm_migrate.py::test_vm_migrate_should_create_notifications_when_migrations_fail -v}}
=> [1LP][RFR] - Testing failure on VM migration

cfme/tests/test_appliance.py
It is not gonna be fixed for this stream.
=> [1LP][RFR] Remove the firewall-zone test from 5.10

cfme/tests/configure/test_config_manual.py, cfme/tests/intelligence/reports/test_reports_manual.py, cfme/tests/services/test_service_catalogs_multi_region.py
Assigning replication tests to me.
=> [RFR][NOTEST] Assign replication tests to tpapaioa

cfme/services/catalogs/orchestration_template.py
{{pytest: cfme/tests/services/test_orchestration_template.py::test_orchestration_template_crud --long-running }}
=> [1LP][RFR] Fix test service orchestration template

cfme/automate/dialogs/__init__.py, cfme/automate/dialogs/service_dialogs.py
Fixed is_displayed for service dialog views
{{pytest: cfme/tests/automate/test_service_dialog.py::test_crud_service_dialog -vvv }}
=> [1LP][RFR] Fixing is_displayed for service dialog

cfme/tests/cli/test_appliance_console.py
Test case to check is SSL certification is overwritting or not after syncing with freeipa server
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_overwrite_ssl_ipa --long-running -v}}
=> [1LP][RFR] - Test to check overwrite SSL cert 

cfme/test_requirements.py, conf/polarion_tools.yaml
Add priority to the requirement markers
Re-assign the requirements.
=> [RFR] Updating requirement markers, adding priority and re-assigning

cfme/test_requirements.py, cfme/tests/cli/test_appliance_console.py
Just improve sorting and mark another test with `restore` requirement
=> [1LP][RFR] maintenance of requirement "restore"

cfme/tests/v2v/test_v2v_cancel_migrations.py, cfme/v2v/migration_plans.py
There is an issue with below Selenium send key"
self.browser.send_keys(Keys.ENTER, self)", So whenever for
the first time send key gets called, it cause the reload of
browser and which landed in all page of the said collection
and throw the exception "NoSuchElementException".
which causes the failure of TC, This PR will works as work around
to resolve the failure.
{{  pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k "test_retry_migration_plan"  --use-provider rhv-ims  --use-provider vsphere67-ims --provider-limit 2 -v }}
=> [RFR] fixing retry fixture and test_retry_migration_plan

cfme/tests/infrastructure/test_advanced_search_host.py, cfme/tests/infrastructure/test_advanced_search_providers.py, cfme/tests/infrastructure/test_advanced_search_vms.py, cfme/tests/infrastructure/test_set_default_filter.py, cfme/tests/networks/test_sdn_topology.py, cfme/tests/services/test_service_catalogs.py, cfme/tests/webui/test_advanced_search.py, cfme/tests/webui/test_expression_editor.py
=> [1LP][RFR] Change assignee from anikifor to gtalreja for S&F

cfme/tests/control/test_actions.py, cfme/tests/control/test_basic.py, cfme/tests/control/test_compliance.py, cfme/tests/control/test_control_simulation.py, cfme/tests/control/test_default_alerts.py, cfme/tests/control/test_export_policies.py, cfme/tests/control/test_import_policies.py, cfme/tests/control/test_smoke_control.py
=> [RFR] Control FA - Changed assignee

cfme/tests/configure/test_access_control.py
=> [RFR] Multi-tenancy - Changed assignee

cfme/tests/cloud_infra_common/test_relationships.py
1. Own test cases related to Relationship Discovery.
=> [1LP][RFR] FA reassignment

cfme/tests/candu/test_candu_manual.py
Added test coverage for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1684525
=> [1LP][RFR]Test ec2 instance memory metrics 

cfme/tests/cloud/test_instance_power_control.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_discovery_and_support.py, cfme/tests/cloud_infra_common/test_power_control_manual.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/cloud_infra_common/test_tag_objects.py, cfme/tests/configure/test_access_control.py, cfme/tests/infrastructure/test_infra_tag_filters_combination.py, cfme/tests/infrastructure/test_vm_ownership.py, cfme/tests/infrastructure/test_vm_power_control.py, cfme/tests/networks/test_sdn_balancers.py, cfme/tests/networks/test_tag_tagvis.py, cfme/tests/services/test_catalog_item.py, cfme/tests/ssui/test_ssui_tags.py
- __Updating tests__ to change ownership of power control tests to prichard
{{pytest: -m smoke}}
=> [1LP][RFR] Update owner for tests in the power control and tag visibility FAs.

cfme/tests/cloud/test_instance_reconfigure.py, cfme/tests/cloud_infra_common/test_power_control_manual.py, cfme/tests/cloud_infra_common/test_provisioning.py, cfme/tests/infrastructure/test_vm_reconfigure.py
Assign some tests marked with the multi_region requirement to tpapaioa.
=> [1LP][RFR][NOTEST] Assign multi-region tests to tpapaioa

cfme/test_requirements.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis.py, cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py, cfme/tests/infrastructure/test_cluster_analysis.py, cfme/tests/infrastructure/test_datastore_analysis.py, cfme/tests/infrastructure/test_host_analysis.py, cfme/tests/infrastructure/test_host_drift_analysis.py, cfme/tests/infrastructure/test_ssa_vddk.py
=> [1LP][RFR] Reassigning SSA test

cfme/tests/v2v/test_csv_import.py
{{  pytest: cfme/tests/v2v/test_csv_import.py --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 }}
=> [1LP][RFR] Refactoring the TC as per check_vm_status method definition

.gitignore
pytest collection data stored in tests_data.json should be ignored by git.
=> [1LP][RFR] Add tests_data.json to .gitignore

cfme/fixtures/v2v_fixtures.py, widgetastic_manageiq/__init__.py
1)UCI has been pushed to 5.11.6. So, I'm updating set_conversion_host_api() through this PR.
2)A few element locators have been changed in 5.11.5. I've also updated the element locators through this PR.
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims }}
510 - PASS
511 - PASS
=> [1LP][WIPTEST] Updating set_conversion_host_api() for 5.11.5

cfme/intelligence/reports/__init__.py, cfme/intelligence/reports/widgets/__init__.py, cfme/tests/intelligence/reports/test_crud.py, cfme/tests/intelligence/test_dashboard.py, cfme/utils/blockers.py, cfme/utils/bz.py
When bug is resolved in DEFERRED, it is known, not worked on but not fixed.
I am not sure what to do with tests that have problems with this.
https://bugzilla.redhat.com/show_bug.cgi?id=1667064
{{pytest: cfme/tests/intelligence/reports/test_crud.py::test_menuwidget_crud  cfme/tests/intelligence/test_dashboard.py::test_widgets_operation   -v --use-provider 'complete' --collect-logs}}
=> [1LP][RFR] Make tests work around bug closed as DEFERRED.

cfme/tests/configure/test_workers.py
Remove BZ blockers for fixed BZ's from test_set_memory_threshold.
=> [1LP][RFR] Remove BZ blockers for test_set_memory_threshold

cfme/tests/ansible/test_embedded_ansible_services.py
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py::test_ansible_service_order_vault_credentials --long-running }}
=> [1LP][RFR] Fix for test_ansible_service_order_vault_credentials

cfme/tests/services/test_dialog_regex_validation_in_catalog.py
- Testing validation regex flag is working or not after the updating the element box in service dialog
{{pytest: cfme/tests/services/test_dialog_regex_validation_in_catalog.py::test_regex_dialog_disabled_validation  --long-running -v}}
=> [1LP][RFR] regex validation test

cfme/fixtures/v2v_fixtures.py, cfme/infrastructure/virtual_machines.py
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv-ims --use-provider vsphere67-ims }}
PRT results:
510 - PASS
511 - PASS
=> [1LP][RFR] Update set_conversion_host_api() to use CA certs

cfme/tests/automate/custom_button/test_rest_custom_button.py
- Due [BZ-1827818](https://bugzilla.redhat.com/show_bug.cgi?id=1827818)- unable to create custom button with REST.
- Skiping test with msg
- Added automate flag on create method
{{ pytest: cfme/tests/automate/custom_button/test_rest_custom_button.py -v }}
=> [1LP][RFR] Block REST custom button tests

cfme/utils/appliance/__init__.py
This PR removes fix_httpd_issue() which was used in appliance configuration. This appears to be a workaround for the issue in the following BZ, which was fixed a long time ago:
Bug 1410883 - httpd reload causes leak of semaphores
https://bugzilla.redhat.com/show_bug.cgi?id=1410883
{{ pytest: -v --long-running -k test_appliance_httpd_roles cfme/tests/distributed/test_appliance_replication.py }}
=> [1LP][RFR] Remove fix_httpd_issue from appliance configuration.

cfme/tests/candu/test_utilization_metrics.py
Automated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1741188
{{pytest: cfme/tests/candu/test_utilization_metrics.py::test_utilization_breadcrumbs -v }}
=> [RFR] Automate BZ-1741188

cfme/tests/infrastructure/test_host_manual.py
Removing manual test (only) as it has been added to test_infrastructure_hosts_crud.
=> [RFR] Remove test_host_removal as it has been added to crud test

widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k "test_retry_migration_plan"  --use-provider osp13-ims  --use-provider vsphere67-ims --provider-limit 2 }}
5.11 : PRT pass
5.10: PRT failed due to time out for log_validator which is not related to this PR changes.
=> [1LP][RFR] Fixing locator issue for test_retry_migration_plan

cfme/tests/services/test_dynamicdd_dialogelement.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_dynamic_dropdown_load_value_on_init --long-running -svvvv }}
=> [1LP][RFR] Automating dynamic dialog load value on init

cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py --use-template-cache --provider-limit 2 --use-provider osp13-ims --use-provider vsphere67-ims -k test_multi_host_multi_vm_migration }}
PRT 5.11 : PASS
PRT 5.10: PASS
=> [1LP][RFR] Fixing test fix_test_multi_host_multi_vm

README.md
Add readme statement concerning the supported CFME versions.
=> [1LP][RFR] Update readme with supported CFME version

conf/cfme_data.yaml.template, conf/credentials.yaml.template
Pull some updates from what we're running internally at RH to the template structure.
FIXES #10118
=> Update cfme_data.yaml template with some additional content

cfme/base/ui.py, cfme/configure/configuration/server_settings.py, cfme/tests/configure/test_workers.py
Remove Server Workers tab view for pre-5.11 versions.
{{ pytest: -vvv cfme/tests/configure/test_workers.py }}
=> [1LP][RFR] Remove Server Workers tab view for 5.10

cfme/tests/distributed/test_appliance_replication.py
Remove 5.10-specific logic from httpd role test.
{{ pytest: -vvv --long-running cfme/tests/distributed/test_appliance_replication.py }}
=> [RFR] Remove pre-5.11 logic from httpd role test

cfme/fixtures/v2v_fixtures.py
UCI support for RHV has been pushed to a future release. So, I'm updating set_conversion_host_api() through this PR.
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv-ims --use-provider vsphere67-ims }}
The PR fails on PRT because the migration plan page needs to be updated. The migration page updates would be done through another PR.
This PR only reverts the UCI code for RHV and the conversion host was successfully configured locally and on the PRT run with these changes.
=> [1LP][RFR] Reverting all UCI code for RHV

cfme/tests/intelligence/test_optimization.py
- __Fixing__ 
1. `test_generate_optimization_report` 
{{ pytest: cfme/tests/intelligence/test_optimization.py::test_generate_optimization_report -svvv }}
=> [1LP][RFR] Fix test: test_optimization_report

cfme/tests/cloud_infra_common/test_relationships.py
- __Fixing__ 
1. test_ssa_cluster_relationships
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_ssa_cluster_relationships -svvv}}
=> [1LP][RFR] Fix test: test_ssa_cluster_relationships

widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k "test_dual_vm_cancel_migration"  --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 }}
=> [1LP][RFR] Fixing Title locator

cfme/tests/services/test_myservice.py
{{ pytest: cfme/tests/services/test_myservice.py -k "test_load_multiple_services" --long-running}}
=> [1LP][RFR] Automating load multiple service

cfme/tests/infrastructure/test_host_manual.py
- __Removing__ manual test because it has been automated.
=> [1LP][RFR]Remove manual test as it is automated now

cfme/tests/v2v/test_conversion_host_ui.py
{{ pytest: cfme/tests/v2v/test_conversion_host_ui.py --use-template-cache --provider-limit 2 --use-provider rhv-ims --use-provider vsphere67-ims}}
**PRT results:**
511 - PASS
=> [1LP][RFR] Fix test_conversion_host_ui

cfme/configure/configuration/server_settings.py
{{ pytest: -vv --long-running -k test_appliance_httpd_roles cfme/tests/distributed/test_appliance_replication.py }}
=> [1LP][RFR] Remove 5.10 version of ServerRolesView

cfme/control/explorer/conditions.py, cfme/tests/control/test_compliance.py
- __Fixing__ 
1. `BaseCondition::delete` method. Added a workaround for BZ(1811689).
1. `test_compliance_instance` that covers BZ(1824811).
{{ pytest: cfme/tests/control/test_compliance.py::test_compliance_instance -svvv }}
=> [1LP][RFR] Add coverage for BZ 1824811

cfme/tests/infrastructure/test_rest_templates.py, cfme/tests/infrastructure/test_vm_rest.py
1. `cfme/tests/infrastructure/test_vm_rest.py::test_vm_disk_subcollection`
2. `cfme/tests/infrastructure/test_rest_templates.py::test_edit_template`
{{ pytest: cfme/tests/infrastructure/test_vm_rest.py::test_vm_disk_subcollection cfme/tests/infrastructure/test_rest_templates.py::test_edit_template -svvv }}
=> [1LP][RFR] New test:test_vm_disk_subcollection AND test_edit_template

requirements/frozen_docs.py3.txt
__fixing__ Updating widgetastic patternfly version
=> [1LP][RFR][NOTEST] - Updating widgetastic patternfly version

requirements/frozen.txt
Bump widgetastic.patternfly fixing the stratification problem when logging it's objects.
=> [1LP][RFR] Bump widgetastic.patternfly

cfme/cloud/provider/azure.py, cfme/tests/infrastructure/test_provisioning_dialog.py, cfme/tests/infrastructure/test_vm_clone.py
Two fixes:
* Bug BZ 1797706 was fixed.
* Azure seem to not have Volumes tab. Not sure this is a bug or not, but the point of the test should display without an error. Azure is prioritized, so I am fixing the test this way.
=> [1LP][RFR] provisioning tests fix

cfme/tests/services/test_rest_services.py
- __Fixing__ 
1. `TestServiceOrderCart`
{{ pytest:  -svvv --long-running cfme/tests/services/test_rest_services.py::TestServiceOrderCart --long-running}}
=> [1LP][RFR] Fix test: TestServiceOrderCart

cfme/tests/configure/test_access_control.py
=> [1LP][NOTEST][RFR] correcting wrongly  added BZ coverage

cfme/tests/control/test_actions.py
=> [RFR][NOTEST] - Adding blocker

cfme/services/requests.py, cfme/tests/services/test_catalog_item.py, cfme/tests/services/test_request.py, cfme/tests/services/test_service_catalog_dialog_manual.py, cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: cfme/tests/services/test_request.py::test_services_requester_dropdown_sorting -svv --long-running }}
- automated services requester drop down sorting test
- Removed deprioritized low/non required tests
- Changed caseimportance for 3 tests
=> [1LP][RFR] Adding services requester drop down sorting test

cfme/automate/import_export.py, cfme/tests/automate/test_domain.py, widgetastic_manageiq/__init__.py
{{pytest: cfme/tests/automate/test_file_import.py   cfme/tests/automate/test_git_import.py     cfme/tests/automate/test_domain.py   cfme/tests/ansible/test_embedded_ansible_automate.py::test_import_domain_containing_playbook_method  -vvv  --long-running -v}}
=> [1LP][RFR] - Fixing custom locator issue

cfme/tests/test_db_migrate.py
Test area is deprioritized, remove scvmm from the parametrization.
=> [RFR] Remove scvmm test for db migrate

cfme/tests/automate/test_method.py
{{pytest: cfme/tests/automate/test_method.py::test_automate_task_schedule --long-running -v}}
=> [1LP][RFR] - test-fix test_automate_task_schedule

cfme/tests/ansible/test_embedded_ansible_basic.py
Automated BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1845281
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py::test_embedded_ansible_file_type_repository_crud --long-running }}
=> [1LP][RFR] Add test coverage for BZ-1845281

cfme/tests/infrastructure/test_providers.py, cfme/utils/__init__.py
__Improve success rate__ of guest devices test.
{{ pytest:  --use-provider complete  'cfme/tests/infrastructure/test_providers.py::test_rhv_guest_devices_count' --long-running -v }}
=> [RFR] Guest devices

cfme/tests/ansible/test_embedded_ansible_automate.py, cfme/tests/cli/test_appliance_console.py, cfme/tests/configure/test_access_control.py
- Added coverage of BZ-1836125
- changed some tests ownership
- removed inactive testcases code
=> [1LP][NOTEST][RFR] - Adding coverage + code cleanup

cfme/tests/ansible/test_embedded_ansible_manual.py
- Removing already automated/deferred tests
- Added BZ flag to existing tests.
=> [1LP][RFR][NOTEST] Remove already automated Ansible manual tests

sprout/requirements.txt
django-ipware 3.0 broke an import
=> [RFR] Update calls to ansible service ordering

cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py::test_ssa_vm --use-provider vsphere67-nested --long-running -v}}
=> [WIPTEST] Fixing SSA failures

cfme/configure/access_control/__init__.py, cfme/tests/cloud/test_providers.py, cfme/tests/cloud_infra_common/test_relationships.py, cfme/tests/configure/test_tag.py, cfme/tests/infrastructure/test_config_management_rest.py, cfme/tests/webui/test_general_ui.py
- __Fixing__ 
1. test_cloud_names_grid_floating_ips to use ec2 provider 
2. test_datastore_relationships to use the correct template
3. test_edit_tag_from_detail to use lower case for tag name
4. Uncollect TestAuthenticationsRESTAPI for ansible_tower 36.
- __Deleting__
1. test_configuration_with_large_tags since it is no longer relevant.
{{ pytest : cfme/tests/cloud/test_providers.py::test_cloud_names_grid_floating_ips cfme/tests/cloud_infra_common/test_relationships.py::test_datastore_relationships cfme/tests/cloud_infra_common/test_relationships.py::test_ssa_cluster_relationships cfme/tests/configure/test_tag.py::TestTagsViaREST::test_edit_tag_from_detail -svvv }}
=> [RFR] Fix tests

cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
Mark manual test as manual only
=> [RFR] Marked test as manual only

cfme/tests/configure/test_access_control.py, cfme/tests/integration/test_auth_manual.py
=> [RFR][NOTEST] Add test importance

cfme/tests/infrastructure/test_vm_ownership.py
- __Fixing__ Test to add `test-*` prefix to vms so that it can be deleted by our SLA.
=> [NOTEST][RFR]add test- prefix to renamed vms test

cfme/intelligence/reports/reports.py
- __Fixing__ 
1. test_reports_filter_content
{{ pytest: cfme/tests/intelligence/reports/test_reports.py::test_reports_filter_content --use-template-cache -sqvvv }}
=> [WIPTEST] Fix test_reports_filter_content

cfme/tests/configure/test_register_appliance.py
The rpmbuild or rpmrebuild may have some deps unsatisfied. To satisfy
them, the machine has to have some repos enabled. The easiest is to
register with subscription manager and unregister just after rebuilding
the required packages.
=> [RFR] Fix test_rh_updates

cfme/services/catalogs/catalog_items/__init__.py, cfme/tests/services/test_catalog_item.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_catalog_item_price_currency --long-running -svvvv }}
=> [1LP][RFR] Automating catalog item price currency test

widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py -k test_migration_with_no_conversion --use-template-cache --provider-limit 2 --use-provider rhv-ims --use-provider vsphere67-ims}}
=> [RFR] Update error text locator in MigrationProgressBar class

cfme/fixtures/v2v_fixtures.py, cfme/tests/v2v/test_conversion_host_ui.py, cfme/tests/v2v/test_rest_migrations.py, cfme/tests/v2v/test_v2v_migrations_ui.py, cfme/tests/v2v/test_v2v_smoke.py
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv44 --use-provider vsphere67-ims}}
The SSH test failure is not related to the changes made through this PR . The remaining three tests related to VDDK passed.
[rhevm-4.3-virtualcenter-6.7-nfs-nfs-rhel7_minimal-SSH]
=> [RFR] V2V: Add support for multiple versions of VDDK
