ManageIQ/integration_tests

- sprout/appliances/tasks.py
moving rename to happen before retrieve ip. so, those won't interfere with each other.
> [RFR] retrieve ip and rename happen at the same time

- cfme/tests/infrastructure/test_vm_power_control.py
- This PR updates test cases for os reset and shutdown of rhv provider 
{{ pytest: cfme/tests/infrastructure/test_vm_power_control.py -k 'test_guest_os_reset or test_guest_os_shutdown' --use-template-cache --use-provider=complete --long-running -qsvvv }}
> [1LP][RFR] Improved guest os reset and shutdown test case for rhv

- cfme/automate/buttons.py
- cfme/tests/automate/custom_button/test_buttons.py
{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_attribute_override -vvv}}
> [1LP][RFR] CB attribute override test

- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_csv_import.py
{{pytest: cfme/tests/v2v/test_csv_import.py --use-provider={rhv43,osp13-ims} --use-provider vsphere67-ims --provider-limit 3 -vvvv}}
- Fixed non-csv test failure
- Added security group and flavor tests
- Fixed tests to accomodate OSP
- Fixed IndexError from network component to run OSP tests
> [1LP][RFR] Refactored test_csv_imports.py

- cfme/tests/configure/test_analysis_profiles.py
==============
A 5.11 BZ prevents test_vm_analysis_profile_crud from running successfully. Adding blocker for that test/stream.
Bug 1727929 - Unable to save changes to VM Analysis Profile's categories
https://bugzilla.redhat.com/show_bug.cgi?id=1727929
{{ pytest: cfme/tests/configure/test_analysis_profiles.py -k test_vm_analysis_profile_crud -vvvv }}
> [1LP][RFR] Add BZ Blocker for 5.11 bug 1727929

- cfme/tests/infrastructure/test_vmware_provider.py
__Fixing__ Test test_rebuilt_vcenter_duplicate_hosts as it was passing with false_positives as the test was not waiting for provider to be refreshed. 
Also, adding ONE_PER_TYPE provider filter for some of the tests.
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py -k "test_rebuilt_vcenter_duplicate_hosts"}}
> [1LP][WIPTEST]fixing provider refresh with adding wait_for so that hosts_after count is accurate

- cfme/utils/net.py
We're getting a warning for leaving this socket connection open:
`[WARNING] [py.warnings] ./cfme/utils/net.py:75: ResourceWarning: unclosed <socket.socket fd=27, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39936), raddr=('127.0.0.1', 53007)>`
> [1LP][RFR] Close socket connection in utils.net.check_port

- cfme/tests/automate/test_class.py
- cfme/tests/automate/test_domain.py
- cfme/tests/automate/test_domain_priority.py
- cfme/tests/automate/test_method.py
- cfme/tests/cloud/test_quota.py
- cfme/tests/intelligence/reports/test_widgets.py
- This PR improves the class schema fields naming because class schema fields must be unique.
{{ pytest: cfme/tests/automate/ -k 'test_generate_widget_content_by_automate or test_automate_disabled_domains_in_domain_priority or test_automate_schema_field_without_type or test_automate_generic_object_service_associations or test_send_email_method or test_domain_lock_disabled or test_object_attribute_type_in_automate_schedule' -vv }}
> [1LP][RFR] Fixed schema field issue in automate

- cfme/tests/configure/test_tag.py
This BZ is also valid for 5.11.
{{ pytest: -v cfme/tests/configure/test_tag.py::test_map_tagging_crud }}
> [1LP][RFR] added forced streams for BZ1707328

- cfme/intelligence/chargeback/rates.py
- cfme/tests/intelligence/test_chargeback.py
==============
1.) Editing of chargeback rate didn't work, because there is no difference in is_displayed between RatesDetailView and Edit{Compute,Storage}ChargebackView. Added am_i_here that returns False for both {Compute,Storage}RateEdit to force successful navigation.
2.) test_chargeback_rate never actually ran the 'edit' tests, because the code checked for a rate_action value of 'update' instead of 'edit'. Also, there was a bug in checking rate_action instead of rate_resource for the type of chargeback rate to edit.
3.) Updated cfme/intelligence/chargeback/rates.py to import CandidateNotFound from widgetastic_patternfly instead of the outdated cfme.exceptions version. The step methods for {Compute,Storage}RateDetails were unable to catch the correct exception. Also …
> [1LP][RFR] Chargeback rate edit/delete test fixes

- cfme/tests/ansible/test_embedded_ansible_services.py
- cfme/tests/automate/custom_button/test_infra_objects.py
- cfme/tests/automate/custom_button/test_service_vm_custom_button.py
- cfme/tests/automate/test_domain.py
- cfme/tests/automate/test_instance.py
- cfme/tests/automate/test_method.py
- cfme/tests/automate/test_service_automate.py
- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/configure/test_database_ui.py
- cfme/tests/containers/test_blacklisted_container_events.py
- cfme/tests/containers/test_pause_resume_workers.py
- cfme/tests/control/test_actions.py
- cfme/tests/networks/nuage/test_automation.py
- cfme/tests/services/test_catalog_item.py
- cfme/tests/services/test_rest_services.py
- cfme/tests/test_appliance.py
- cfme/utils/log_validator.py
- Refactor method names as per converstation [PR-8918](https://github.com/ManageIQ/integration_tests/pull/8918#issuecomment-504006364)
- `fix_before_start()` > `start_monitoring()`
- `validate_logs()` > `validate()`
- `wait_for_log_validation` > `validate(wait="....")`
{{pytest: cfme/tests -k 'test_custom_button_with_dynamic_dialog_vm or test_custom_button_automate_service_vm or test_domain_lock_disabled or test_custom_button_automate_infra_obj or test_custom_button_dialog_infra_obj or test_check_system_request_calls_depr_conf_mgmt or test_quota_source_value or test_task_id_for_method_automation_log or test_send_email_method or test_automate_generic_object_service_associations or …
> [1LP][RFR] Refactor LogValidator

- requirements/frozen.py2.txt
- requirements/frozen.py3.txt
- requirements/frozen_docs.py2.txt
- requirements/frozen_docs.py3.txt
2.4.2 was warning on cryptography deprecations.
2.6 appears compatible with our current use on inspection, and includes a move to a version of cryptography that is not deprecated
> [1LP][RFR] Update paramiko 2.6

- cfme/automate/explorer/method.py
- cfme/common/__init__.py
- cfme/common/vm.py
- cfme/configure/configuration/server_settings.py
- cfme/tests/cloud_infra_common/test_provisioning.py
This patch requires https://github.com/ManageIQ/wrapanapi/pull/370
Remove a `pytest.raises` as it seems to me that is shouldn't be there. It causes:
```
request = <SubRequest 'modified_request_class' for <Function 'test_cloud_provision_from_template_with_attached_disks[openstack-13-1]'>>
domain = <cfme.automate.explorer.domain.Domain object at 0x7f93cade6fd0>
original_request_class = <cfme.automate.explorer.klass.Class object at 0x7f93cb1fdb10>
@pytest.fixture(scope="module")
def modified_request_class(request, domain, original_request_class):
with pytest.raises(Exception, match="error: Error during 'Automate Class copy'"):
>           original_request_class.copy_to(domain)
E           Failed: DID NOT RAISE <type 'exceptions.Exception'> …
```
> [1LP][RFR] Fix test_provisioning.

- cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
- The name ```v2v_providers``` is now changed to ```v2v_provider_setup```
- Fixed Error:
```
>       available fixtures: LineMatcher, _pytest, amazon_auth_provider, ansible_catalog, ansible_catalog_item, ansible_repository, ansible_service, ansible_service_catalog, ansible_service_request, ansible_tower_dialog, anypython, app_creds, app_creds_modscope, appliance, appliance_police, appliance_preupdate, appliance_with_preset_time, appliance_with_providers, auth_provider, .........
>       use 'pytest --fixtures [testpath]' for help on them.
/var/ci/workspace/downstream-510z-tests-master/integration_tests/cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py:25
FixtureLookupError
```
{{ pytest: cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py -k …
> [1LP][RFR] Fixed v2v_providers naming issue

- cfme/tests/infrastructure/test_timelines.py
The test case `test_infra_timeline_migrate_event` will sometimes fail if the migration fails for whatever reason. Since we are testing events and not migration, we need to allow for these failure events. Adding `VM_MIGRATION_FAILED` to the searched for events on the timeline. 
{{ pytest: --use-template-cache --use-provider rhv43 cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_migrate_event }}
> [RFR] Allow for the event VM_MIGRATION_FAILED

- cfme/intelligence/reports/reports.py
- cfme/intelligence/reports/schedules.py
- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/intelligence/reports/test_reports_schedules.py
Changes:
1. While creating/editing schedule, `timer` attribute was not filled, this PR fixes that.
2. Enhance `test_reports_schedule_crud`  to cover BZ 1729882 and automate [RHCF3-36149](https://polarion.engineering.redhat.com/polarion/redirect/project/RHCF3/workitem?id=RHCF3-36149)
{{ pytest: cfme/tests/intelligence/reports -k "test_reports_schedule_crud or test_schedule_queue" --use-template-cache -sqvvv }}
> [1LP][RFR]fix schedules and enhance a test for BZ 1729882

- cfme/tests/configure/test_server_name.py
- cfme/utils/appliance/__init__.py
{{pytest: cfme/tests/configure/test_server_name.py }}
PRT RESULTS:
5.11 failure is addressed in wt.patternfly PR #98 and #9084  (which will include update to wt.patternfly)
> [1LP][RFR] Add BZ marker and update test_server_name patterns for filling

- cfme/tests/candu/test_azone_graph.py
- cfme/tests/candu/test_utilization_metrics.py
{{pytest: cfme/tests/candu/test_utilization_metrics.py --use-provider azure}}
PRT results:
With the fix, test_raw_metric_vm_memory[azure-common]  is being skipped for both 510 and 511, like expected.
The test_raw_metric_vm_disk[azure-common] is failing because there is no disk activity on the Azure VM and it doesn't have to do anything with this PR. I'll investigate and fix the disk activity issue.
> [1LP][RFR] Add BZ blocker for Azure memory metric

- cfme/common/provider.py
- cfme/test_requirements.py
- cfme/tests/containers/test_container_provider_crud.py
Removing flash message assertions for setup and delete in `BaseProvider`.
Add new containers provider crud test
{{ pytest: cfme/tests/containers/test_container_provider_crud.py --use-provider ocp-39-hawk }}
> [1LP][RFR] New container crud test and remove flash assert in BaseProvider

- widgetastic_manageiq/__init__.py
it isn't correctly perceived by js code in some cases
{{pytest: --use-provider ocp-39-hawk --long-running cfme/tests/containers/test_node.py }}
> [1LP][RFR] removing entity_id type convertion to int

- cfme/cloud/instance/__init__.py
- cfme/tests/cloud/test_cloud_timelines.py
1) Fixing `is_displayed` on archived instances, as they do not display the "Cloud Provider" row in the "Relationships" table. This was causing `test_cloud_timeline_delete_event` to skip when it shouldn't
2) Adding BZ metadata to the above test case for https://bugzilla.redhat.com/show_bug.cgi?id=1730819
{{ pytest: --use-provider azure cfme/tests/cloud/test_cloud_timelines.py::test_cloud_timeline_delete_event }}
> [1LP][RFR] Fix is displayed archived instances

- cfme/tests/candu/test_nor_rightsize.py
No PRT testing required.
Separate manual tests for NOR and Right-Sizing exist for individual providers. This PR removes the tests for old providers rhv41 and vsphere55 which either do not exist or no longer support C&U-related tests.
Future PR's will automate these tests and parametrize the type (CPU or Memory) and provider.
> [1LP][RFR] Remove manual nor/rightsize tests for old providers rhv41 and vsphere55

- cfme/ansible/repositories.py
- cfme/tests/ansible/test_embedded_ansible_basic.py
- cfme/tests/ansible/test_embedded_ansible_manual.py
Already automated manual tests: `test_embed_tower_repo_list`, `test_embed_tower_repos_available`.
This PR automating manual tests: `test_embed_tower_repo_links`, `test_embed_tower_add_branch_repo`, `test_embed_tower_playbook_links`.
PRT Run:
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k "test_embedded_ansible_repository_playbook_link or test_embedded_ansible_repository_branch_crud" -svvvv --long-running }}
> [1LP][RFR] Automating Ansible tests for Branched Repo and Link to playbook

- cfme/tests/automate/custom_button/test_container_objects.py
- cfme/tests/automate/custom_button/test_service_vm_custom_button.py
{{pytest: cfme/tests/automate/custom_button/test_container_objects.py::test_custom_button_dialog_container_obj --use-provider ocp-39-hawk  -v}}
> [1LP][RFR] block test with BZ-1729594

- cfme/common/__init__.py
- widgetastic_manageiq/__init__.py
{{ pytest: -v cfme/tests/configure/test_access_control.py::test_user_remove_tag }}
`all_options` selected some wrong (invalid) options, so I modified the locator.
The other problem was with encoding, that is also fixed but please let me know if there's a better solution.
> [1LP][RFR] fixed random tag selection for 5.11

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/dashboard.py
- cfme/intelligence/chargeback/__init__.py
- cfme/intelligence/reports/__init__.py
- cfme/intelligence/reports/reports.py
- cfme/intelligence/rss.py
- cfme/intelligence/timelines.py
- cfme/tests/configure/test_landing_page.py
- cfme/tests/intelligence/reports/test_crud.py
__Fixing__ navigation to 'Cloud Intel' because, since 5.11, "Cloud Intel" has been changed to "Overview", by adding a new property called `intel_name` to `Server` that returns appropriate name.
Few tests on 5.11.0.15 are failing because of [BZ 1724209](https://bugzilla.redhat.com/show_bug.cgi?id=1724209), but since they're passing for 5.10, I'm assuming these changes are alright.
{{ pytest: cfme/tests/intelligence/reports/test_crud.py -vvv }}
> [1LP][WIPTEST] Fix Cloud Intel navigation

- cfme/tests/distributed/test_appliance_manual.py
No PRT testing for this PR.
There are manual tests in cfme/tests/distributed/test_appliance_manual.py that are duplicated by automated tests in cfme/tests/configure/test_zones.py. This PR removes those manual tests.
Manual test                                                             Automated test
test_distributed_field_zone_description_long		test_zone_add_maxlength
test_distributed_zone_create_new                          test_zone_crud
test_distributed_zone_create_duplicate                  test_zone_add_dupe
test_distributed_field_zone_name_long                  test_zone_add_maxlength
test_distributed_change_appliance_zone               test_zone_change_appliance_zone
> [1LP][RFR] Remove manual zone tests that are already automated

- cfme/base/ui.py
- cfme/cloud/availability_zone.py
- cfme/cloud/instance/__init__.py
- cfme/cloud/provider/__init__.py
- cfme/common/__init__.py
- cfme/common/host_views.py
- cfme/common/physical_server_views.py
- cfme/common/physical_switch_views.py
- cfme/common/provider_views.py
- cfme/containers/node.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/virtual_machines.py
- widgetastic_manageiq/__init__.py
Fixing the `is_displayed` properties in 5.11. I would also like to fix cluster and host views since those are also impacting these tests. 
{{ pytest: --use-provider vsphere6-nested cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_create_event }}
> [1LP][RFR] Use common view class for timelines view

- cfme/infrastructure/cluster.py
- cfme/infrastructure/datastore.py
Nearly 23 test are affected due to this... 
Tested locally... can not reproduce with one or two test as this happened only if embedded ansible enabled. 
```
In [1]: [p.name for p in appliance.rest_api.collections.providers]                
(rest-api) [RESTAPI] GET https://10.8.196.115/api/providers {'expand': 'resources'}
Out[1]: 
['Embedded Ansible',
'RHOS13',
'RHOS13 Network Manager',
'RHOS13 Cinder Manager',
'RHOS13 Swift Manager',
'vSphere 6.7 (nested)']
In [2]: appliance.collections.clusters.all()                                      
Out[2]: [Cluster(name='Cluster', provider=VMwareProvider(endpoints={'default': <cfme.infrastructure.provider.virtualcenter.VirtualCenterEndpoint object at 0x7f45ce01ef28>}, name='vSphere 6.7 (nested)', …
```
> [1LP][RFR][NOTEST] fix Could not find provider Embedded Ansible

- widgetastic_manageiq/__init__.py
- This PR fixes test cases related to quota and service where quota is getting checked with ordering service catalogs. 
- This issue breaks more number of test cases in 5.10 and 5.11 as well.
-  This PR fixes:
```
>                   'cause': 'Root node did not match {}'.format(self._repr_step(image, step))})
E               CandidateNotFound: path: ('Provisioning', 'StateMachines', 'ServiceProvision_Template', 'CatalogItemInitialization'), message: Could not find the item Service in Boostrap tree automate_treebox, cause: Root node did not match Service
/var/ci/cfme_venv/lib/python2.7/site-packages/widgetastic_patternfly/__init__.py:1422: CandidateNotFound
CandidateNotFound
path: ('Provisioning', 'StateMachines', 'ServiceProvision_Template', 'CatalogItemInitialization'), message: Could …
```
> [1LP][RFR] Fixed CandidateNotFound issue

- cfme/services/myservice/ui.py
In latest build `MyServiceView` is broken due to `VeriticalNav`; It will break all tests related to `service.` `currently_selected` returning value like  `['Services', 'My Services', 'Services', 'Providers']`. 
some local checks
```
ipdb> self.navigation.currently_selected                                          
['Services', 'My Services', 'Services', 'Providers']
ipdb> self.navigation.currently_selected                                          
['Storage', 'Block Storage', 'Managers']
ipdb> self.navigation.currently_selected                                          
['Services', 'Catalogs']
```
{{pytest: cfme/tests/automate/custom_button/test_service_vm_custom_button.py::test_custom_button_with_dynamic_dialog_vm -v}}
> [1LP][RFR] Nav work around for 5.11.0.16

- cfme/tests/openstack/cloud/test_flavors.py
- cfme/tests/openstack/cloud/test_instances.py
Adding `test-` to instance names for OSP tests so they will be cleaned by our cleanup script. 
{{ pytest: --use-provider rhos13 cfme/tests/openstack/cloud/test_instances.py cfme/tests/openstack/cloud/test_flavors.py }}
> [RFR] Add "test" to instance names for OSP tests

- cfme/storage/volume.py
attribute name has changed in 5.11 and during `test_storage_volume_snapshot_edit_tag_from_detail[ec2]` I got
```
NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator=u'.//div[contains(@class, "bootstrap-select")]/select[normalize-space(@name)="aws_availability_zone_id"]/..')
```
{{ pytest: -v cfme/tests/storage/test_volume_snapshot.py::test_storage_volume_snapshot_edit_tag_from_detail[ec2] }}
> [1LP][RFR] fixed VolumeAddForm for ec2

- cfme/tests/automate/custom_button/test_cloud_objects.py
- cfme/tests/automate/custom_button/test_container_objects.py
- cfme/tests/automate/custom_button/test_service_objects.py
- cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Just avoid flash check as it lands on wrong page. As we are getting proper request no need to block tests.
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py}}
> [1LP][RFR] Avoid flash check with bz

- .travis.yml
just a band-aid for travis until #9053 is merged. Recently travis was updated to use ubuntu 16.04 by default, which breaks our quickstart. So here force it to use 14.04 until #9053 is merged.
> [RFR] Use ubuntu 14.04 for travis

- cfme/tests/control/test_alerts.py
severity is a required field in 5.11
{{ pytest: --use-provider vsphere6-nested --long-running cfme/tests/control/test_alerts.py::test_alert_vm_turned_on_more_than_twice_in_past_15_minutes }}
> [RFR] Add severity to alerts test

- cfme/tests/configure/test_access_control.py
RBAC tests __refactor__.
Removed global `pytest.mark.provider` and `setup_provider` fixture, since most of the tests do not need a provider to be present.
Moved these markers to a couple of tests that do need to use provider.
Refactored usage of `group_collection` fixture. It was suggested we don't need to use a fixture to return a collection when we can reference that collection directly from `appliance`.
{{ pytest: -v --long-running cfme/tests/configure/test_access_control.py }}
> [1LP][RFR] RBAC tests refactor

- cfme/tests/control/test_actions.py
https://bugzilla.redhat.com/show_bug.cgi?id=1702018 also impacts 5.11. This BZ is causing the VM that is used for the other tests in this module to be retired. 
{{ pytest: --use-provider vsphere6-nested --long-running cfme/tests/control/test_actions.py::test_action_prevent_vm_retire }}
> [RFR] Block retire test in 5.11, remove unused appliance fixtures

- cfme/utils/browser.py
Causing failure across the framework, this iterator was changed with move to py3
> [RFR] Change iterator use in FirefoxProfile.set_preference

- cfme/utils/ssh.py
- scripts/gen_ssl_cert.py
__fixing__ some problems related to switch to py3.
Regarding the SSHResult, I did some local testing:
```
In [4]: cfme.utils.ssh.SSHResult("ff", 3, "oo")                                                          
Out[4]: SSHResult(command='ff', rc=3)
In [5]: cfme.utils.ssh.SSHResult("ff", 3, "oo") == 3                                                     
Out[5]: True
In [6]: cfme.utils.ssh.SSHResult("ff", 3, "oo") == 2                                                     
Out[6]: False
In [7]: cfme.utils.ssh.SSHResult("ff", 3, "oo") < 2                                                      
Out[7]: False
In [8]: cfme.utils.ssh.SSHResult("ff", 3, "oo") > 2                                                      
Out[8]: True
In [9]: cfme.utils.ssh.SSHResult("ff", 3, "oo") > "oo" …
```
> [RFR] Py3 compact

- cfme/base/ui.py
- cfme/tests/configure/test_paginator.py
==============
1.) If more than one test_paginator_config_pages test for a tab under the Zone Diagnostics configuration page runs as part of the same pytest command, navigation between the tabs was not happening. This is fixed by adding am_i_here methods, which return False, to the NavigateStep classes for each tab. This matches the existing behavior of the tabs on the Region Diagnostics page.
2.) The same fix is also applied to the Zone and Advanced tabs under Configuration > Settings > Zone, which share the same ZoneDetailsView class.
3.) test_paginator_config_pages[zones_servers] was failing because the test case expected no paginator to be present, but a paginator has been added.
4.) There is a bug in the UI for 5.11, in which the Zone Diagnostics configuration page …
> [1LP][RFR] Fixes for UI navigation in test_paginator_config_pages

- cfme/tests/control/test_alerts.py
- cfme/tests/control/test_compliance.py
Adding BZ metadata for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1730805 which was impacting tests which use SSA
> [1LP][RFR][NOTEST] Add SSA bz metadata

- cfme/tests/configure/test_default_views_infra.py
- __Fixing__  `test_vm_visibility_off` and `test_vm_visibility_on` by marking the test with ignore_stream for 5.11 since the feature is no longer available on it.
- {{pytest: cfme/tests/configure/test_default_views_infra.py -k "test_vm_visibility" -v}}
> [1LP][RFR] Fix failing tests

- cfme/ansible/credentials.py
- cfme/tests/ansible/test_embedded_ansible_basic.py
- cfme/tests/ansible/test_embedded_ansible_manual.py
This PR contains enhancement in Credentials Modal Page:
PRT Run: 
{{ pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k test_embedded_ansible_credential_crud -svvvv --long-running }}
> [1LP][RFR] Added Azure and Network credentials with Credentials modal page refactor.

- cfme/tests/networks/test_tag_tagvis.py
I thought it's a bug but it's a feature https://bugzilla.redhat.com/show_bug.cgi?id=1672949
{{ pytest: -v cfme/tests/networks/test_tag_tagvis.py::test_tagvis_network_provider_children   --use-template-cache --use-provider=complete }}
The test `test_tagvis_network_provider_children[cloud-Load Balancers]` should not be collected for 5.11
> [1LP][RFR] removed a check for load balancers for 5.11

- cfme/tests/automate/test_service_automate.py
- cfme/tests/automate/test_simulation.py
- This BZ(1728706) is hot fix for 5.10z. Hence updating this test case for 5.10z
- Fixed Error for ```test_object_attributes```:
```
>               assert view.target_object.all_options > 0
E               TypeError: '>' not supported between instances of 'list' and 'int'
cfme/tests/automate/test_simulation.py:38: TypeError
TypeError
b"'>' not supported between instances of 'list' and 'int'"
```
{{ pytest: cfme/tests/automate/ -k 'test_user_requester_for_lifecycle_provision or test_object_attributes' --use-template-cache -qsvv }}
> [1LP][RFR] Test case updated for 5.10z

- scripts/smtp_collector.py
The test_provision_approval started failing after switching to Py3 due to
adding of an argument `mail_options`.
The argument `data` of the `process_message` is `bytes` unless the argument to SMTPServer
`decode_data=True` in which case we get the utf-8 decoded string.
{{pytest: cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval -v}}
> [RFR] Fix test_provision_approval.

- cfme/tests/infrastructure/test_vm_reconfigure.py
- __Fixing__ test `test_vm_disk_reconfig_via_rest` after py3 upgrade.
{{ pytest: cfme/tests/infrastructure/test_vm_reconfigure.py -k "test_vm_disk_reconfig_via_rest" --use-provider=vsphere65-nested --long-running -v }}
> [RFR]Fix test: test_vm_disk_reconfig_via_rest

- widgetastic_manageiq/__init__.py
I see this is failing in 5.11 with `E       AssertionError: assert ' Testing: testing' == 'Testing: testing'`, so this removes extra spaces and `test_tag_mapping_azure_instances` passes.
{{ pytest: -v cfme/tests/cloud/test_tag_mapping.py::test_tag_mapping_azure_instances --use-provider=complete }}
> [1LP][RFR] fixed get_text_of in SummaryTable

- cfme/configure/documentation.py
- cfme/tests/configure/test_docs.py
Changes:
1. Fix test `test_contents`.
{{ pytest: cfme/tests/configure/test_docs.py::test_contents --use-template-cache -sqvvv }}
> [1LP][RFR]Fix test: test_contents

- cfme/tests/automate/test_git_import.py
- widgetastic_manageiq/__init__.py
- This PR fixes issue while selecting ```provision entry point``` tree
- Removed 5.11 blocker BZ
{{ pytest: cfme/tests/automate/test_git_import.py -k 'test_automate_git_domain_displayed_in_service' -vv }}
> [1LP][RFR] Fixed provision entry point issue

- cfme/utils/appliance/__init__.py
Addressing:
```
cfme/tests/cli/test_appliance_cli.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <cfme.utils.appliance.ApplianceConsole object at 0x7f9baa39bbe0>
timezone = ['Africa/Abidjan']
def timezone_check(self, timezone):
channel = self.appliance.ssh_client.invoke_shell()
channel.settimeout(20)
channel.send("ap")
result = ''
try:
while True:
>               result += channel.recv(1)
E               TypeError: can only concatenate str (not "bytes") to str
cfme/utils/appliance/__init__.py:122: TypeError
```
Local testing:
```
In [1]: app = store.current_appliance                                                                                              
In [2]: app.appliance_console.timezone_check('Africa/Abidjan') …
```
> [1LP][RFR] Update appliance console channel recv use, remove six from appliance

- cfme/utils/datafile.py
This fixes
`E       TypeError: a bytes-like object is required, not 'str'`
{{pytest: cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py -k test_provision_cloud_init -v}}
Tests are failing for
`cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init[ec2]`
but the other variants are fixed.
Also, there is https://github.com/ManageIQ/wrapanapi/pull/403 fixing wrapanapi issue with `next()`.
> [1LP][RFR] Use non-binary NamedTemporaryFile (fixes TypeError)

- cfme/tests/services/test_ansible_workflow_servicecatalogs.py
- __Adding tests__ for Ansible workflow jobs
Tested with
{{ py.test:  cfme/tests/services/test_ansible_workflow_servicecatalogs.py }}
PRT results:
510 - Passed
511 - Passed
> [1LP][RFR] Add tests for automating Tower workflow jobs

- cfme/common/vm_views.py
Some elements in SetOwnershipView have changed between 5.10 and 5.11, breaking all VM chargeback / metering report tests. The changes are:
- The Owner and Group dropdowns have changed from BootstrapSelect to ReactSelect elements.
- The 'Save' button is now titled 'Submit'.
This PR uses VersionPicker to define these three elements as appropriate, depending on whether we are testing against CFME 5.11 or not.
{{ pytest: -v --long-running --use-provider vsphere67-nested cfme/tests/intelligence/reports/test_validate_chargeback_report.py::test_validate_default_rate_cpu_usage_cost }}
> [1LP][RFR] Update Set Ownership view for 5.11

- cfme/tests/configure/test_tag.py
BZ 1707328 was fixed only for 5.11, therefore we need to keep this workaround so the check works only for 5.11.
{{ pytest: -v cfme/tests/configure/test_tag.py::test_map_tagging_crud }}
> [1LP][RFR] fixed BZ flash message only for 5.11

- cfme/tests/networks/test_sdn_topology.py
py3 produced the error in  the error in `test_topology_search` tests
E       TypeError: slice indices must be integers or None or have an __index__ method
cfme/tests/networks/test_sdn_topology.py:41: TypeError
TypeError
b'slice indices must be integers or None or have an __index__ method'
{{ pytest: -v cfme/tests/networks/test_sdn_topology.py::test_topology_search }}
> [1LP][RFR] fixed division in slicing

- cfme/tests/intelligence/reports/test_canned_corresponds.py
- __Fixing__ `test_providers_summary` to pick correct name of `Hostname` for both the versions of appliance.
- __Fixiing__ `test_datastores_summary` to work for py3 upgrade.
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py -k "test_providers_summary or test_datastores_summary" --use-provider=vsphere65-nested -vvvv }}
> [1LP][RFR]Fix test: test_providers_summary and test_datastores_summary

- cfme/tests/test_appliance.py
Adding test checking presence of ansible modules
{{pytest: cfme/tests/test_appliance.py::test_appliance_contains_ansible_modules -v}}
> [1LP][RFR] add test_appliance_contains_ansible_modules

- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/utils/smtp_collector_client.py
1. Adding test_send_text_custom_report_with_long_condition to automate BZ 1677839.
2. Adding a fixture to create reports for `test_send_text_custom_report_with_long_condition` and `test_report_edit_secondary_display_filter`.
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_send_text_custom_report_with_long_condition or  test_report_edit_secondary_display_filter" --use-template-cache -sqvvvv }}
> [1LP][RFR]Automate test: test_sent_text_custom_report_with_long_condition

- cfme/base/ui.py
- cfme/tests/configure/test_config_diagnostics.py
- cfme/tests/configure/test_config_manual.py
- widgetastic_manageiq/__init__.py
- __Adding tests__ `test_configuration_dropdown_roles_by_server` that covers BZ
- __Extending__ add missing widgets to `rolesbyservers` and `serversbyroles`.
{{ pytest: cfme/tests/configure/test_config_diagnostics.py -v }}
> [1LP][RFR] Automate test: test_configuration_dropdown_roles_by_server

- cfme/configure/about.py
- cfme/tests/configure/test_about.py
- __Adding tests__ test_about_zone and test_about_region that automates BZ 1402112, which adds zone and region information in the About modal. They were implemented in 5.11.
{{ pytest: cfme/tests/configure/test_about.py -v }}
> [RFR]Add tests: test_about_region AND test_about_zone

- cfme/common/provider_views.py
The BZ is verified and the workaround is no longer needed. However, I'd like to keep the BZ number nearby as it helps with finding qe_test_coverage - I'm not sure which test exactly automates this check.
> [1LP][RFR] removed workaround for BZ 1703744

- widgetastic_manageiq/__init__.py
Fixes
```
>           item = item.split(" *")[0]
E           TypeError: a bytes-like object is required, not 'str'
widgetastic_manageiq/__init__.py:2813: TypeError
TypeError
b"a bytes-like object is required, not 'str'"
```
I guess `encode("utf-8")` no longer needed with python3 and it works now without it.
{{ pytest: -v cfme/tests/storage/test_volume.py::test_storage_volume_edit_tag --use-provider=complete --long-running }}
> [RFR] fixed all_options in tagging dropdown

- cfme/tests/storage/test_volume.py
Fixes 
```
E           assert exact match of message: success: Cloud Volume "xwKtzvVAhC" created. 
E            Available messages: []
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:315: AssertionError
AssertionError
b'assert exact match of message: success: Cloud Volume "xwKtzvVAhC" created. \n Available messages: []'
```
{{ pytest: -v cfme/tests/storage/test_volume.py::test_storage_volume_edit_tag --use-template-cache --use-provider=complete --long-running }}
> [RFR] fixed create_volume function for 5.11

- cfme/tests/storage/test_volume_backup.py
Fixes
```
E           assert exact match of message: success: Cloud Volume "EGpJdOjrzy" created. 
E            Available messages: []
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:315: AssertionError
AssertionError
b'assert exact match of message: success: Cloud Volume "EGpJdOjrzy" created. \n Available messages: []'
```
for 5.11.
5.11:
5.10:
{{ pytest: -v cfme/tests/storage/test_volume_backup.py::test_storage_volume_backup_edit_tag_from_detail  --use-template-cache --use-provider=complete --long-running }}
!!NOTE: the PRT will still fail because it cannot create a backup (limit 10 exceeded).
> [RFR] fixed backup fixture for 5.11

- cfme/automate/explorer/method.py
- Fixed error:
```
>       to_delete = present - keys
E       TypeError: unsupported operand type(s) for -: 'list' and 'set'
cfme/automate/explorer/method.py:100: TypeError
TypeError
b"unsupported operand type(s) for -: 'list' and 'set'"
```
{{ pytest: cfme/tests/automate/test_method.py -k 'test_automate_method_inputs_crud' --use-template-cache -qsvv }}
> [RFR] Fixed type error in automate method

- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/tests/webui/test_general_ui.py
- __Updating tests__ `test_tls_openssl_verify_mode` to validate smtp_server updates.
- __Removing tests__ `test_after_setting_certain_types_of_filters_filter_tab_should_be_accessible_and_editable` and `test_report_secondary_display_filter_should_be_editable` which have already been automated in `test_report_edit_secondary_display_filter`.
{{ pytest: cfme/tests/webui/test_general_ui.py::test_tls_openssl_verify_mode -vvv }}
> [1LP][RFR] Test cleanup and other changes

- cfme/tests/v2v/test_rest_migrations.py
- __Fixing__ migration failures for 5.11
{{pytest: cfme/tests/v2v/test_rest_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv -k 'test_rest_mapping_bulk_delete_from_collection or test_rest_mapping_create'}}
> [1LP][RFR] Fixing 5.11 migration failures

- cfme/tests/networks/test_sdn_balancers.py
Load balancers are no longer there
> [1LP][RFR] ignore test_sdn_balancers_tagvis for 5.11

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/infrastructure/test_vm_power_control.py
- This PR contains new test case to check whether newly created user with role vm-user can able to retire the vm provisioned by admin
{{ pytest: cfme/tests/infrastructure/test_vm_power_control.py -k 'test_retire_vm_with_vm_user_role' --use-provider=complete --long-running -vvv }}
> [1LP][RFR] New Test: Test vm retire by new user

- cfme/common/host_views.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- __Extending__ Test case for including "Thick - Lazy Zero/Eager Zero" that is being introduced in new 5.11 build.
https://github.com/ManageIQ/manageiq-providers-vmware/pull/427
Some examples are:
- {{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py -k 'test_disk_format_select' --use-provider vsphere67-nested --long-running -v}}
> [1LP][RFR] Automates BZ 1633867 for thick-lazy zero/eager zero provisioning

- cfme/intelligence/reports/schedules.py
- cfme/tests/intelligence/reports/test_crud.py
- __Fixing__ `test_reports_schedule_crud` to choose Date for `Starting Date`. Using `DatePicker` instead of `Calendar`.
- __Remove__ BZ blocker which no longer blocks.
{{ pytest: cfme/tests/intelligence/reports/test_crud.py::test_reports_schedule_crud -vvv }}
> [1LP][RFR]Fix schedules starting_date

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_snapshot.py
Added a small check that size of RHV snapshot is now shown in the UI.
Automates https://bugzilla.redhat.com/show_bug.cgi?id=1608475
{{ pytest: -v cfme/tests/infrastructure/test_snapshot.py::test_snapshot_crud  --use-provider=complete --long-running }}
> [1LP][RFR] added check for snapshot size in rhv

- cfme/configure/configuration/diagnostics_settings.py
- cfme/tests/configure/test_log_depot_operation.py
Automation is blocked for 5.11 but I tried to run it locally without some blockers and still found some differences. It worked before because, e.g. the result of `self.appliance.server.zone.id` and `self.appliance.server.sid` was the same. But since maintenance zone was introduced in 5.11 it started to fail in that place.
Also added `automates` and changed the BZ blocker for models and dialogs.
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_log_depot --long-running }}
> [1LP][RFR] log collection fixes

- cfme/tests/configure/test_log_depot_operation.py
fixes
```
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//div[contains(@class, "dropdown") and ./button[normalize-space(.)="Collect Logs" or normalize-space(@title)="Collect Logs"]]')
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic/browser.py:347: NoSuchElementException
NoSuchElementException
b'Message: Could not find an element Locator(by=\'xpath\', locator=\'.//div[contains(@class, "dropdown") and ./button[normalize-space(.)="Collect Logs" or normalize-space(@title)="Collect Logs"]]\')\n'
```
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_unconfigured --long-running }}
> [RFR] fixed test_collect_unconfigured

- cfme/common/host_views.py
Fixed `test_set_default_host_filter` for 5.11
{{ pytest: -v cfme/tests/infrastructure/test_set_default_filter.py::test_set_default_host_filter --use-provider=complete --long-running }}
> [RFR] fixed test_set_default_host_filter

- cfme/tests/cloud/test_instance_power_control.py
Provider markers are preferred over using uncollectif. Especially without a reason! 
More of these to come as we change the behavior of uncollectif.
> [1LP][RFR] Replace uncollectif with Provider markers

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/reports/test_generate_report.py
- __Fixing__ `is_displayed` method of `SavedReportDetailsView`. There are many reports whose title changes after they're generated.
See this screenshot to understand better:
Here `view.title.text` is `Saved Report "Processes for prod VMs sorted by CPU Time - Wed, 14 Aug 2019 07:54:53 +0000"`
but `expected_title` is `Saved Report "Processes for prod VMs sort by CPU Time - Wed, 14 Aug 2019 07:54:53 +0000"`
This is not a bug. There are other reports which have different name than it's `menu_name`, so instead of exactly matching the titles, we only check if `saved_report.queued_datetime_in_title` is present in `view.title.text`.
{{ pytest: cfme/tests/intelligence/reports/test_generate_report.py -vvv }}
> [1LP][RFR]Fix SavedReportDetailsView is_displayed

- cfme/tests/intelligence/reports/test_crud.py
- cfme/tests/intelligence/reports/test_import_export_reports_widgets.py
- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_views.py
- __Extending__ reports tests by adding finalizer wherever missing.
{{ pytest: cfme/tests/intelligence/reports/test_crud.py cfme/tests/intelligence/reports/test_views.py -vvv }}
> [1LP][RFR]Add request.addfinalizer wherever missing in reports

- cfme/fixtures/parallelizer/__init__.py
Resolve:
```
02:28:20 INTERNALERROR>   File "/var/ci/workspace/downstream-511z-tests/integration_tests/cfme/fixtures/parallelizer/__init__.py", line 416, in pytest_runtestloop
02:28:20 INTERNALERROR>     self._slave_audit()
02:28:20 INTERNALERROR>   File "/var/ci/workspace/downstream-511z-tests/integration_tests/cfme/fixtures/parallelizer/__init__.py", line 222, in _slave_audit
02:28:20 INTERNALERROR>     for slave in self.slaves.values():
02:28:20 INTERNALERROR> RuntimeError: dictionary changed size during iteration
```
> [RFR] Fix RuntimeError in parallelizer due to dict size change

- cfme/tests/webui/test_advanced_search.py
- widgetastic_manageiq/expression_editor.py
__Updating tests__ for new UX feature
When there is no provider, "add new provider" page appears now.. And search is not available at this page. So it's needed to add providers before checking advanced search.
Also separated tests into classes.
One test fail (TimeoutError) is not related to changes, doesn't happen locally where it runs faster. 
{{pytest: cfme/tests/webui/test_advanced_search.py --use-template-cache --use-provider=complete --use-provider=container -v}}
> [1LP][RFR] fix test advanced search

- cfme/base/ui.py
- cfme/tests/configure/test_config_diagnostics.py
- cfme/tests/configure/test_config_manual.py
- __Adding tests__ `test_diagnostics_server`.
- __Extending__ `ZoneDiagnosticsView.servers` and `RegionDiagnosticsView.servers` tab by adding `Table`.
{{ pytest: cfme/tests/configure/test_config_diagnostics.py::test_diagnostics_server -vvv }}
> [1LP][RFR]Automate test: test_diagnostics_server

- cfme/tests/integration/test_auth_scripts.py
- cfme/tests/test_appliance.py
module it was in was marked as smoke
This test uses temp_appliance fixture, and cannot be run in smoke testing
> [1LP][RFR] Move test_fixauth_dryrun_has_feedback

- cfme/tests/configure/test_log_depot_operation.py
Previously it worked by coincidence as zone was the same as server id (1). Since the introduction of the maintenance zone, it's no longer true.
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_single_servers --long-running }}
> [RFR] fixed test_collect_single_servers

- cfme/tests/infrastructure/test_vmware_provider.py
- __Updating tests__ to use smaller ISO Data store as bigger datastore was taking over 15 mins for SSA and would cause failure - false negative. 
- {{pytest: cfme/tests/infrastructure/test_vmware_provider.py --use-provider vsphere67-nested -k 'test_vmware_cdrom_dropdown_not_blank'  --long-running -v  }}
> [1LP][RFR]Vmware automation tests

- docs/conf.py
- docs/guides/bugzilla.rst
- docs/guides/dev_guide.rst
Adding some documentation for BZ related stuff. If you'd like to see the compiled html file, you can build the docs yourself. Checkout this branch, `cd` to `docs`, and run `make html`. Note that you must be on the latest version of Sphinx in order for the build to complete successfully. 
The `html` file will be in `docs/_builds/html`.
> [1LP][RFR] Add guidelines about Bugzilla related stuff

- cfme/fixtures/automate.py
- cfme/tests/automate/test_file_import.py
- Intention of this PR is just add one global fixture to import datastore files
- Adding one supporting test; I know its bad; this test should not use `gloable` fixture but these steps should be part of test as its basic test. but just for adding this in support of global fixture.
{{pytest: cfme/tests/automate/test_file_import.py -v}}
> [1LP][RFR] import_datastore fixture

- cfme/tests/services/test_ansible_workflow_servicecatalogs.py
{{ py.test: cfme/tests/services/test_ansible_workflow_servicecatalogs.py }}
Added tests for automating ordering of Ansible workflow service based on project sync up and inventory sync up.
PRT results:
510 - PASS
511 - PASS
Note
The latest PRT run[0] passed on both 510 and 511.But, GH still shows the failure from run#34025
[0]http://infra-trackerbot2.cfme2.lab.eng.rdu2.redhat.com/pr/run/34040
> [1LP][RFR] Adding more Tower workflow tests

- cfme/fixtures/qa_contact.py
Remove deadlock from qa_contact fixture.
The qa_contact.py is spawning `git blame` to get some info about the code.
Right after spawning it, `wait()` is called to wait for the `git blame`
to exit. But no read is being done between these two actions. This
creates a danger for git blame to fill the stdout buffer and get stopped.
The parent process is waiting as well on this point so no read from the
git blame's stdout pipe will ever be done and no process is allowed to
advance -> DEADLOCK.
In fact, even the Python doc does warn about this situation:
https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen.wait
pytest being blocked:
```
Traceback (most recent call first):
<built-in method waitpid of module object at remote 0x7efcd68d7350>
File …
```
> [1LP][RFR] Remove deadlock from qa_contact fixture.

- cfme/base/ui.py
- cfme/configure/configuration/server_settings.py
In 5.11, the Settings > Server > Workers configuration tab has been refactored:
- The ordering of elements in the HTML is different
- The dropdowns have changed from BootstrapSelect to ReactSelect widgets
This PR implements those changes by moving ServerWorkersView from cfme.base.ui into ServerWorkersTab510 in cfme.configure.configuration.server_settings, and creating a new class ServerWorkersTab511 with the above changes. ServerView in cfme.base.ui now uses VersionPicker to determine which of these classes to set as its nested 'workers' view.
The test_set_memory_threshold_in_ui test now works for both 5.10 and 5.11.
{{pytest: cfme/tests/configure/test_paginator.py cfme/tests/configure/test_workers.py::test_set_memory_threshold_in_ui -v}}
> [1LP][RFR] New View in 5.11 for Settings > Server > Workers

- cfme/fixtures/generic_object.py
- cfme/test_framework/pytest_plugin.py
- cfme/tests/automate/custom_button/test_service_objects.py
- cfme/tests/generic_objects/test_instances.py
- Generic object creation is with `rest` OR `ruby` and hectic task
- we repetition of fixtures nearly common so moving to global so anyone can use this for setup.
- I need this for increasing coverage for custom button over generic definition/class. 
- **Note: Just moving fixture not changing implementation** 
{{pytest: cfme/tests/generic_objects/test_instances.py cfme/tests/automate/custom_button/test_service_objects.py -sqvv}}
> [1LP][RFR] Some Generic obj fixture move to global

- cfme/cloud/instance/__init__.py
- cfme/common/vm.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud_infra_common/test_power_control_manual.py
- cfme/tests/infrastructure/test_vm_power_control.py
- This test case is to check Power option drop-down button is disabled on archived and orphaned
VMs all page. Also it performs the power operations on vm and checked expected flash messages.
- Added two new views:
- **OrphanedVmsAllView**: for all page of orphaned vms
- **ArchivedVmsAllView**: for all page of archived vms
- Added fixture:
- **archive_orphan_vm**: To create orphaned/archived vms
- Improved **find_quadicon** method as it is used to find quadicon and check the particular vm.
- Added ```from_archived_all``` and ```from_orphaned_all```
{{ pytest:  cfme/tests/ -k "test_power_options_on_archived_orphaned_vms_all_page or test_power_options_on_archived_instance_all_page or test_quadicon_terminate_cancel" --long-running -vv }}
> [1LP][RFR] New Test: Checking power operations on archived/orphaned vms

- cfme/tests/infrastructure/test_rest_automation_request.py
- Testing multiple automation requests and denying
{{ pytest: cfme/tests/infrastructure/test_rest_automation_request.py -k 'test_multiple_automation_requests' -vv --long-running }}
> [1LP][RFR] Testing multiple automation requests

- cfme/tests/intelligence/reports/test_menus.py
1. `get_custom_report` fixture to import a report instead of creating a new report with the yaml data. 
2. `rbac_api` to not delete user, since that is anyway done by `gen_data._create_skeleton`.
- __Adding tests__ `test_reports_menu_with_duplicate_reports` which automates BZ 1676638, 1731017
- __Updating tests__ `test_rbac_move_custom_report` and `test_add_reports_to_available_reports_menu` to use the updated `get_custom_report` fixture.
{{ pytest: cfme/tests/intelligence/reports/test_menus.py -k "test_add_reports_to_available_reports_menu or test_rbac_move_custom_report or test_reports_menu_with_duplicate_reports" -vvv }}
> [1LP][RFR]New Test: test_reports_menu_with_duplicate_reports

- cfme/services/catalogs/orchestration_template.py
- widgetastic_manageiq/__init__.py
Fixes 
```
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//div[contains(@class, "bootstrap-select")]/button[normalize-space(@data-id)="type"]/..')
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic/browser.py:347: NoSuchElementException
NoSuchElementException
b'Message: Could not find an element Locator(by=\'xpath\', locator=\'.//div[contains(@class, "bootstrap-select")]/button[normalize-space(@data-id)="type"]/..\')\n'
```
~~in 5.11 but there's another frontend change that will fail the PRT.~~
I also had to create a new widget `ReactCodemirror` which is incomplete. I'd also like to implement `read` method there but so far tests pass and I can do it in a separate PR.
{{ pytest: -v …
> [1LP][RFR] fixed select in adding new orchestration template

- cfme/tests/cloud/test_cloud_timelines.py
`test_cloud_timeline_delete_event` should still run for providers other than Azure.
> [RFR] Add unblock for providers that aren't Azure

- cfme/tests/infrastructure/test_timelines.py
Cloning is unsupported for RHV providers. 
source: https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/pdf/support_matrix/Red_Hat_CloudForms-4.7-Support_Matrix-en-US.pdf
{{ pytest: --use-provider rhv43 --long-running cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_clone_event }}
> [RFR] Uncollect RHV provider for cloning test

- cfme/tests/control/test_actions.py
The BZ removed was closed due to age. It still exists and I opened a new BZ https://bugzilla.redhat.com/show_bug.cgi?id=1745065, but really the action test is not relevant to this BZ, so I removed it as a blocker. 
{{ pytest: --use-provider rhv43 --long-running cfme/tests/control/test_actions.py::test_action_create_snapshot_and_delete_last }}
> [1LP][RFR] Remove old blocker for action test

- cfme/tests/infrastructure/test_quota_tagging.py
- This test case needs to updated because in this test case we are checked if quota is getting  exceeded or not while reconfiguring vm above quota
- Here vm is not getting reconfigured because of quota exceeded. So removing assertion.
{{ pytest: cfme/tests/infrastructure/test_quota_tagging.py::test_quota_vm_reconfigure --use-template-cache -qsvvv --use-provider=complete --long-running }}
> [RFR] Fixed vm reconfigure quota test case

- cfme/tests/cloud/test_providers.py
- cfme/tests/infrastructure/test_vm_retirement_rest.py
- cfme/tests/intelligence/test_reports_with_timelines.py
- cfme/tests/intelligence/test_rss.py
- __Fixing__ tests:
1. `test_check_vm_retirement_requester` - test was failing due to a change in the request description, which is now fixed by using `find_by` instead of `get` action.
2. Add ignore_stream("5.11") to test_rss.py and test_reports_with_timeline.py, since they have been removed from 5.11.
3. Remove unnecessary code related to arbitration_profiles from cfme/tests/cloud/test_providers.py
{{ pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py::test_check_vm_retirement_requester  -vvv }}
> [1LP][RFR]Fix failing tests and add ignore_stream wherever required

- cfme/optimize/utilization.py
- cfme/tests/webui/test_splitter.py
- __Fixing__ `test_splitter.py` for UtilizationCollection which is failing because Utilization has been moved to Overview.
- __Enhance__ `UtilizationView` by adding `ManageIQTree()` which will be a useful widget for 5.11 and adding `tree.currently_selected` check in the `is_displayed`.
- __Extending__ `All` navigator of `UtilizationCollection` by adding a step to click a certain tree path if the appliance version > "5.11".
{{ pytest: cfme/tests/webui/test_splitter.py -k "test_pull_splitter_persistence[UtilizationCollection-All" -vvv }}
> [1LP][RFR]Fix test: test_splitter.py for UtilizationCollection

- cfme/tests/automate/custom_button/test_custom_menu.py
- It was failing with `test runs`. update advance setting is with rest after evmserverd restart; we need force navigation.... locally and with single test run it was working properly. 
{{pytest: cfme/tests/automate/custom_button/test_custom_menu.py -v}}
> [1LP][RFR] fix custom menu test for test run

- cfme/physical/provider/__init__.py
The PR [#9220](https://github.com/ManageIQ/integration_tests/pull/9220) missed the physical infrastructure providers in changing the default `cancel` value. This commit resolves the issue.
The original commit removed the explicit `cancel=False` parameter to `provider.delete()` call while it didn't actually change the default value in the definition of the method. As a result, the integration tests would fail because they would expect the provider to have been deleted, which never happened.
/cc @jawatts
> [1LP][RFR] Change default of the provider.delete() to False

- cfme/tests/configure/test_config_manual.py
- cfme/tests/intelligence/reports/test_menus.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- __Adding tests__ `test_reset_report_menus` to test resetting reports menu.
- __Removing tests__ 
1. `test_my_settings_default_views_alignment` - no longer required.
2.  `test_reports_manage_report_menu_accordion_with_users` and `test_report_menus_moving_reports` which are already covered by other tests.
{{ pytest : cfme/tests/intelligence/reports/test_menus.py::test_reset_report_menus -vvv }}
> [1LP][RFR]New Test: test_reset_report_menus AND remove unnecessary tests

- cfme/utils/appliance/db.py
When running the test_upgrade_single_inplace, None was passed as service
unit name because VersionPicker didn't have definition for the 5.9. This
happened on testing upgrade from 5.9 to 5.10.
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
appliance_preupdate = IPAppliance.from_json('{"is_dev": false, "db_host": null, "ui_protocol": "https", "browser_steal": false, "hostname": ...196.157", "openshift_creds": {}, "ui_port": 443, "project": null, "container": null, "db_port": 5432, "ssh_port": 22}')
appliance = IPAppliance.from_json('{"is_dev": false, "db_host": null, "ui_protocol": "https", "browser_steal": false, "hostname": ...198.129", "openshift_creds": {}, "ui_port": 443, "project": null, "container": null, "db_port": …
```
> [1LP][RFR] Fix problem with None being passed as service unit name on 5.9

- cfme/utils/ansible.py
Seeing value error in the file defined below for PRT.
{{ pytest: --long-running --use-provider cmqe cfme/tests/containers/test_manageiq_ansible_custom_attributes.py::test_manageiq_ansible_edit_custom_attributes -k "openshift-3.9" }}
> [1LP][RFR] Fix ValueError due to opening files with 'rw' mode

- cfme/common/vm_views.py
This select was updated to a react select in 5.11, which is breaking some timelines tests. 
{{ pytest: --use-provider rhv42 cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_diagnostic }}
> [RFR] Update BootstrapSelect to ReactSelect for 5.11

- cfme/tests/networks/test_provision_to_virtual_network.py
Reassigned this to me as it appears to be RHV specific test. Still hope @mmojzis will help me just in case :D
Also removed old `uncollectif` and `ignore_stream`.
> [1LP][RFR] reasigned test_provision_vm_to_virtual_network

- cfme/tests/infrastructure/test_scvmm_specific.py
- cfme/utils/appliance/__init__.py
- cfme/utils/appliance/db.py
- docs/getting_started.rst
The tests started loosening the DB in far past (commit 6695364f56).
As the commit message states, it was a temporary solution to some
problem. It seems to me we do not need it any more and we should
rather use the default db permissions to do real testing.
Also, an invalid BZ#1741481 was reported because we are modifying the permissions in such a way that it doesn't allow replication
The unmodified permissions on CFME 5.11 are:
local   all         all           peer map=usermap
local   replication all           peer map=usermap
hostssl all         all   all     md5
host    replication all   all     md5
> [1LP][RFR] Don't loosen DB

- cfme/ansible_tower/explorer.py
- cfme/tests/infrastructure/test_config_management.py
{{pytest: cfme/tests/infrastructure/test_config_management.py -v}}
Test to automate creation of service dialog from Ansible Tower job template
1)The existing TowerExplorerJobTemplateDetailsView was using an incorrect toolbar. Fixed that.
2)Created a new view for creation of service dailogs from Tower job templates.
2)Added a new test to create service dialog from Tower job template
The test_config_system_tag[satellite_62] test  is failing on both 510 and 511 . The failure is not related to the code changes made through this PR.
All the other tests passed on both 510 and 511.
> [RFR] Test to create service dialog from Tower job template

- cfme/tests/infrastructure/test_publish_vm_to_template.py
- __Fixing__ this test by adding required_fields as it was picking wrong vmware provider and failing. 
- {{pytest: cfme/tests/infrastructure/test_publish_vm_to_template.py -k "test_publish_vm_to_template" -v}}
> [RFR]Fixing test failure by adding required_fields

- cfme/automate/explorer/method.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_class.py
- This PR includes testing of state machines variables by executing ```inline``` automate methods in state schema
- Removed test case - ```test_automate_retry_onexit_increases```. It is already automated test case - ```test_automate_schema_field_without_type```
{{ pytest: cfme/tests/automate/test_class.py::test_state_machine_variable --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing state machine variables

- cfme/automate/explorer/method.py
- cfme/tests/ansible/test_embedded_ansible_automate.py
In 5.11 "Playbook" is uppercase, so we must make the condition use `lower()` for this to evaluated properly. 
{{ pytest: --use-provider vsphere65-nested --long-running cfme/tests/ansible/test_embedded_ansible_automate.py::test_alert_run_ansible_playbook }}
> [1LP][RFR]: Make playbook lowercase in create method

- cfme/automate/explorer/method.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_method.py
- This PR tests embedded method is visible after selection in ```inline``` type of automate method
- Removed ```test_method_for_log_and_notify``` as this test case  is already automated.
{{ pytest: cfme/tests/automate/test_method.py::test_embedded_method_selection --use-template-cache -qsvv}}
> [1LP][RFR] New Test: Testing embedded method is visible after selection

- cfme/tests/cloud_infra_common/test_policy_simulation.py
{{ pytest: --use-provider complete cfme/tests/cloud_infra_common/test_policy_simulation.py::test_policy_simulation_ui }}
> [1LP][RFR]: Add 1704395 as a blocker for test_policy_sim ui

- cfme/tests/infrastructure/test_timelines.py
Adding a `blocks` statement for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1747132 and adding metadata throughout `test_timelines.py`
{{ pytest: --use-provider rhv43 cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_create_event }}
> [1LP][RFR] Add bz metadata for timelines tests

- cfme/tests/configure/test_log_depot_operation_manual.py
These tests are already automated by `test_collect_single_servers`.
```
<Module 'cfme/tests/configure/test_log_depot_operation.py'>
<Function 'test_collect_single_servers[smb-collect_all-zone_collect]'>
<Function 'test_collect_single_servers[smb-collect_all-server_collect]'>
<Function 'test_collect_single_servers[smb-collect_current-zone_collect]'>
<Function 'test_collect_single_servers[smb-collect_current-server_collect]'>
```
> [1LP][RFR] removed automated manual tests

- cfme/automate/explorer/method.py
- cfme/automate/simulation.py
- cfme/tests/ansible/test_embedded_ansible_automate.py
- cfme/tests/automate/test_method.py
- This PR fixes crud operation of ```automate method type - playbook```
- Also changes in the naming of the automate method types for playbook and inline are resolved in this PR
- This PR updates test case with global fixture 
{{ pytest: cfme/tests/ansible/test_embedded_ansible_automate.py -k "test_automate_ansible_playbook_method_type_crud or test_automate_ansible_playbook_method_type" --long-running  -vvvvv }}
> [1LP][RFR] Fixed playbook method crud operations

- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/configure/test_log_depot_operation_manual.py
Added 1 more check to cover `test_log_collect_all_zone_unconfigured` and `test_log_collect_current_zone_all_unconfigured`
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_unconfigured  --long-running }}
> [1LP][RFR] automated manual test for unconfigured log depot

- cfme/tests/test_rest.py
- __Fixing__ test_date_filtering AND test_datetime_filtering.
{{ pytest: cfme/tests/test_rest.py -k "test_date_filtering or test_datetime_filtering" -vvv }}
> [1LP][RFR] Fix test: test_date_filtering AND test_datetime_filtering

- cfme/tests/infrastructure/test_advanced_search_vms.py
Well, it didn't work
```
>       assert callable(finalizer)
E       AssertionError
```
{{ pytest: -v cfme/tests/infrastructure/test_advanced_search_vms.py::test_quick_search_without_vm_filter }}
> [1LP][RFR] fixed test_quick_search_without_vm_filter

- cfme/generic_objects/definition/__init__.py
- cfme/generic_objects/definition/rest.py
- cfme/generic_objects/definition/ui.py
- cfme/generic_objects/instance/__init__.py
- cfme/generic_objects/instance/rest.py
- cfme/generic_objects/instance/ui.py
Adding in an `all()` method for generic_objects and generic_object_definitions.
> [1LP][RFR][NOTEST] Add in an all() method ViaREST for generic-object and definitions

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_git_import.py
- This PR automates the scenario of importing automate domain via rake command using git repo and checking via UI if imported domain is exists without any error.
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_import_case_insensitive --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing automate domain import via rake command

- cfme/tests/control/test_actions.py
This should have been included in #9248, but I missed it. Essentially it is doing the same thing as that PR, but for a slightly different test case. 
{{ pytest: --use-provider rhv43 --long-running cfme/tests/control/test_actions.py::test_action_create_snapshots_and_delete_them }}
> [1LP][RFR] Remove old bz 1549529, allow tests to run

- cfme/tests/ansible/test_embedded_ansible_rest.py
- __Removing__  tests related to embedded ansible rest which is no longer available on 5.11
{{ pytest:  cfme/tests/ansible/test_embedded_ansible_rest.py  --long-running -vvv }}
> [1LP][RFR]Uncollect embedded ansible rest tests which ends in 5.10

- conf/polarion_tools.yaml
- requirements/frozen.py3.txt
- requirements/frozen_docs.py3.txt
Has been tested against stage polarion instance, polarion workflow restrictions are still applied in the transition of the workitems from draft to approved.
> [1LP][RFR] Default polarion status and approvals

- cfme/tests/infrastructure/test_publish_vm_to_template.py
Updated:
- Removed provider override marker
- Updated global provider marker to use ProviderFilter class
{{ pytest: cfme/tests/infrastructure/test_publish_vm_to_template.py --use-provider onprem }}
This now should uncollect for vpshere60-ims:
```
miq-runtest --collect-only --use-provider vsphere60-ims cfme/tests/infrastructure/test_publish_vm_to_template.py
.
.
.
Appliance's streams: [5.10, downstream]
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.7.0, pytest-3.4.1, py-1.8.0, pluggy-0.6.0
rootdir: /home/juwatts/repos/integration_tests, …
```
> [1LP][RFR] Updating Test to Use ProviderFilter and Remove Provider Override Mark

- cfme/intelligence/reports/__init__.py
- cfme/intelligence/reports/dashboards.py
- cfme/intelligence/reports/widgets/__init__.py
- cfme/tests/intelligence/reports/test_crud.py
Make reports tests running.
There were some bugs regarding the report tests but they may be worked around and tests may start running.
* Workaround BZ 1667064
* remove blocker BZ 1653796 because it was resolved
* remove test_rssfeedwidget_crud from CFME 5.11 runs as per BZ 1728328
Some examples are:
- {{pytest:  cfme/tests/intelligence/reports/test_crud.py -v}}
> [1LP][RFR] Workaround bz 1667064

- cfme/fixtures/parallelizer/__init__.py
- cfme/fixtures/parallelizer/remote.py
- cfme/utils/providers.py
- requirements/frozen.py3.txt
- requirements/frozen_docs.py3.txt
Collection in parallelizer remote slaves included manual tests
debug showing all options still passed, but update to pytest-polarion-collect 0.18 breaks collection with manual tests included
Not sure why the addition of a hookspec by pytest-polarion-collect is changing the markers in slave python processes
> [WIPTEST] Revert pytest-polarion-collect update, parallelizer broken

- cfme/tests/infrastructure/test_provisioning_dialog.py
Test was failing because the selected option overridden the template.
{{pytest: cfme/tests/infrastructure/test_provisioning_dialog.py::test_provision_vm_with_2_nics -v --long-running --use-provider complete }}
> [1LP][RFR] fix test_provision_vm_with_2_nics

- cfme/cloud/instance/__init__.py
- cfme/common/vm.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud_infra_common/test_power_control_rest.py
1. Add `rest_api_entity` property to `BaseVM` which returns a VM/Instance's REST entity based on the VM/Instance name and provider.
2. Add `wait_for_power_state_change_rest` method to `BaseVM` which waits until the VM/Instance reaches the desired state.
3. Remove `get_vm_via_rest` since we now have `rest_api_entity`.
4. Remove `get_collection_via_rest` since it's not used anywhere.
1. `cloud/test_cloud_timelines.py`, `cloud/test_instance_power_control.py`, `cloud_infra_common/test_power_control_rest.py`to use `rest_api_entity` instead of `get_vm_via_rest`.
2. `cloud_infra_common/test_power_control_rest.py`  to use `wait_for_power_state_change_rest`.
{{ pytest: cfme/tests/cloud/test_instance_power_control.py …
> [1LP][RFR] Add `wait_for_power_state_change_rest` to BaseVM

- cfme/tests/webui/test_general_ui_manual.py
[](https://bugzilla.redhat.com/show_bug.cgi?id=)## Purpose or Intent
- __Adding tests__ :
1. `test_red_hat_cloud_page_internal_server_error` for [BZ 1740131](https://bugzilla.redhat.com/show_bug.cgi?id=1740131)
2. `test_provider_documentation` for [BZ 1741030](https://bugzilla.redhat.com/show_bug.cgi?id=1740130)
3. `test_vm_right_size_recommendation_back_button` for [BZ 1733207](https://bugzilla.redhat.com/show_bug.cgi?id=1733207)
4.  `test_compliance_column_header` for [BZ 1745660](https://bugzilla.redhat.com/show_bug.cgi?id=1745660)
> [1LP][RFR]Add general UI test coverage

- cfme/tests/infrastructure/test_provisioning_rest.py
- cfme/tests/test_rest_manual.py
1. Automating manual test - `test_edit_provider_request_task`
{{ pytest: cfme/tests/infrastructure/test_provisioning_rest.py -k "test_edit_provider_request_task" -vvv }}
> [1LP][RFR]Automate test: test_edit_provider_request_task

- cfme/tests/intelligence/reports/test_reports_manual.py
1. `test_created_on_time_report_field` for [BZ 1743579](https://bugzilla.redhat.com/show_bug.cgi?id=1743579).
2. `test_case_insensitive_report_filtering` for [BZ 1741588](https://bugzilla.redhat.com/show_bug.cgi?id=1741588)
3. `test_reports_service_unavailable` for [BZ 1725142](https://bugzilla.redhat.com/show_bug.cgi?id=1725142)
4. `test_optimization_reports` for [BZ 1714197](https://bugzilla.redhat.com/show_bug.cgi?id=1714197)
5. `test_reports_timelines_tab` for [BZ 1743651](https://bugzilla.redhat.com/show_bug.cgi?id=1743651)
> [1LP][RFR]Add test coverage for reports BZ

- cfme/tests/infrastructure/test_host.py
{{ pytest: cfme/tests/infrastructure/test_host.py::test_hosts_not_displayed_several_times -v  --use-provider=complete  }}
> [1LP][RFR] New test: test hosts not displayed several times

- cfme/tests/infrastructure/test_timelines.py
This BZ is present in 5.10 but the bug was written against 5.11 and it hasn't been cloned yet.
> [1LP][RFR] Add forced streams 5.10 for bz 1747132

- cfme/common/provider.py
- cfme/tests/infrastructure/test_host.py
- __Updating tests__ for FA infra_hosts to cover refreshing multiple hosts. This was initially a manual test, but now it is automated.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_refresh_multi }}
> [1LP][RFR] Add test_infrastructure_hosts_refresh_multi to test_host.py

- cfme/tests/intelligence/reports/test_reports.py
{{ pytest: cfme/tests/intelligence/reports/test_reports.py --use-provider onprem }}
> [RFR] Remove Container Provider from test_reports_online_vms collection

- cfme/tests/test_appliance.py
- cfme/tests/test_manual.py
The test_optimize_memory_usage_by_making_object_in_hash is being deleted
here as I (jhenner) have no clue what is meant to be tested.
The test_puma_server is obsolete as per BZ 1752509
> [1LP][RFR][NOTEST] Deal with last two jhenner manual tests to sort.

- cfme/ansible_tower/explorer.py
- cfme/tests/infrastructure/test_config_management.py
1.Updated AnsibleTowerJobTemplatesCollection so that it can be filtered on Ansible job type.
2.Updated TowerExplorerJobTemplateDetailsView to cover workflow template details page as well.
3.Added test to create service dialog using Tower Workflow
{{py.test: cfme/tests/infrastructure/test_config_management.py -k "dialog"}}
All tests except for the test_config_system_tag[satellite_62]  test passed on both 510 and 511. The failure is not related to the code changes made through this PR.
> [1LP][RFR] Test to create service dialog using Tower Workflow

- cfme/tests/configure/test_log_depot_operation.py
Log collection tests failed on checking ansible logs. Before there was a workaroud and now it seems to work the same for all archives.
{{ pytest: -v cfme/tests/configure/test_log_depot_operation.py::test_collect_log_depot  --long-running }}
> [RFR] fixed the expected path for ansible logs in the collected logs

- cfme/base/ui.py
Navigation to the Server/Server (ServerDetails class) and Server/CustomLogos (CustomLogos class) destinations logs exceptions when running the associated am_i_here() methods. The navigation eventually succeeds, because it falls back to their associated prerequisites:
juwatts testing:
{{ pytest: cfme/tests/configure/test_paginator.py::test_paginator_config_pages[servers_customlogos] cfme/tests/configure/test_ntp_server.py::test_clear_ntp_settings -v }}
****
2019-08-21 12:39:08,103 [I] [cfme] ------------------ test_server_roles_changing[default_candu] ------------------- (cfme/fixtures/log.py:27)
2019-08-21 12:39:08,436 [I] [cfme] [UI-NAV/Server/Server]: Beginning Navigation... (cfme/utils/appliance/implementations/ui.py:527)
2019-08-21 12:39:08,818 [E] [cfme] [UI-NAV/Server/Server]: …
> [RFR] Fix navigation exceptions in ServerDetails and CustomLogos

- cfme/common/host_views.py
- cfme/tests/infrastructure/test_host.py
- __Adding tests__ for FA infra_hosts to cover BZ 1738664. BZ was found in 5.11.0.22. 
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_navigation_after_download }}
> [1LP][RFR] Add test_infrastructure_hosts_navigation_after_download to test_host.py

- cfme/containers/container.py
- cfme/tests/containers/test_search_bar.py
Fixes:
```
TypeError
b'slice indices must be integers or None or have an __index__ method'
```
{{ pytest: cfme/tests/containers/test_search_bar.py  --use-provider ocp-39-hawk }}
> [1LP][RFR] Fix TypeError and is_displayed Containers in 5.11

- cfme/tests/automate/test_common_methods.py
- This test case is getting skipped for VMWareProvider.
- Scenario of this test case is not related to any specific provider. Hence changing provider to RHEVMProvider.
{{ pytest: cfme/tests/automate/test_common_methods.py::test_automate_quota_units -vvv }}
> [1LP][RFR] Changed provider to rhvm

- cfme/services/catalogs/catalog.py
Co-authored-by: Satyajit Bulage <sbulage@redhat.com>
- 22 test are failing due to this locator changes with error `Could not find an element './/select[@id="selected_fields"]'`
trying to cover some tests
{{pytest: cfme/tests/ -k "test_service_catalog_crud_ui or test_service_ansible_verbosity or test_embed_tower_exec_play_against or test_service_ansible_playbook_order_credentials or test_service_ansible_playbook_order_retire or test_service_ansible_playbook_pass_extra_varstest_service_ansible_playbook_pass_extra_vars or test_service_ansible_execution_ttltest_service_ansible_execution_ttl or test_custom_button_ansible_credential_list" --long-running -sqv}}
> [1LP][RFR] fix locator for Catalog Multibox widget

- cfme/tests/test_appliance.py
- cfme/tests/test_db_migrate.py
- cfme/utils/appliance/__init__.py
- cfme/utils/ssh.py
It seems that creating the db takes ~4 minutes to complete. It seems
that when our systems are more loaded, we are getting slightly over
4 minutes and many migration tests fail.
I tested
```
time appliance_conosle_cli --region {region} --internal \
--hostname localhost \
--username {username} --password {password} \
--dbname {dbname} --verbose --dbdisk {dbdisk}
```
with some configurations with these results:
```
CFME version
region	5.11.0.23 	5.11.0.24
---------------------------------
0	3m53.328s	4m16.664s
50	3m58.793s	3m40.494s
99	4m16.768s	3m49.669s
```
To make the test passing I also had to:
1) handle the exception risen from the connection checking code that happened when the machine was till refusing the connection attempts as there was no service listening yet.
1) increase timeout …
> [1LP][RFR] Increase timeout for creating the db

- cfme/base/ui.py
- cfme/tests/configure/test_paginator.py
- cfme/tests/configure/test_zones.py
Changes to Zone configuration page navigation in PR #9028 affected tests in test_zones.py. This PR fixes those tests with the following changes:
- ZoneSettingsView.is_displayed now checks for "(current)" after the zone description only if the zone being displayed is actually the current zone (i.e., the appliance we're using belongs to it).
- ZoneEditView, Zone.exists, and Zone.delete are updated to use the new navigation destination (Zone > Zone tab) introduced in the previous PR.
- Old BZ blockers removed.
- Updated test_zone_crud to look up the newly-created zone in order to populate the id and region in the Zone object, so that the view's is_displayed method will work.
{{pytest: cfme/tests/configure/test_zones.py cfme/tests/configure/test_paginator.py -v}}
> [1LP][RFR] Fix navigation issues in zone tests

- cfme/tests/cloud_infra_common/test_power_control_manual.py
- cfme/tests/pod/test_appliance_crud.py
- cfme/tests/services/test_service_catalogs.py
- cfme/tests/services/test_service_catalogs_multi_region.py
- Existing service catalogs tests file covers only limited range of catalog items due to provider == InfraProvider filter.
In my case I need to override this marker to have provider == None, provider marker doesn't support this. 
So, I just moved my manual tests to another file in order to turn off provider parametrization. 
- fixed wait_for value str->int.
- added Bundle option to service tests
- fixed power on/off tests in global region because collection of these tests has been broken
> [1LP][RFR] fixed collection for service multi-region tests

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/common/provider.py
- cfme/exceptions.py
- cfme/fixtures/base.py
- cfme/infrastructure/host.py
- cfme/services/myservice/__init__.py
- cfme/tests/integration/test_cfme_auth.py
create tree_path property for Server
Use it in navigation/views where this tree path is built from server attributes
add base session fixture to set appliance name
There are some other failures going on in PRT, but I don't really want this PR scope creeping too far beyond the changes here related to server configuration navigation/view assertions.
{{ pytest: cfme/tests/integration/test_cfme_auth.py::test_login_evm_group --long-running }}
> [1LP][RFR] Fix navigation for server

- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/cloud_infra_common/test_provisioning.py
- cfme/tests/configure/test_email.py
- cfme/tests/configure/test_ntp_server.py
- cfme/tests/configure/test_workers.py
- cfme/tests/control/test_actions.py
- cfme/tests/infrastructure/test_child_tenant.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/infrastructure/test_vm_reconfigure.py
- cfme/tests/networks/test_network_providers.py
- cfme/tests/networks/test_sdn_crud.py
- cfme/tests/ssui/test_ssui_myservice.py
PR covers two things:
1) Removing rhel_testing marker on tests that don't need to be run after an upgrade
2) Adding rhel_testing marker on test that should be executed after an upgrade
> [RFR] Add/Remove rhel_testing marker on tests

- cfme/tests/infrastructure/test_host.py
- __Updating tests__ in test_host module to use the ONE_PER_VERSION selector.
{{ pytest: --long-running --use-provider vsphere6-nested cfme/tests/infrastructure/test_host.py }}
> [1LP][RFR] Add ONE_PER_VERSION selector to test_host module

- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_v2v_migrations.py
- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_single_datastore_single_vm_migration[rhevm-4.3-virtualcenter-6.7-mapping_data_vm_obj_single_datastore0]}}
Added a method to set a flag in advanced setting for OSP required for V2V testing .
Tested this fixture locally . Flag is set to true.
Also added a method to start event catchers as a workaround.
> [1LP][RFR]Set flag in advanced setting

- cfme/common/vm.py
- __Fixing__ 
1. `BaseVM.rest_api_entity` to fix all failing tests using rest_api_entity.
{{ pytest: cfme/tests/cloud/test_instance_power_control.py -k "TestInstanceRESTAPI" --long-running -vvv }}
> [1LP][RFR] Fix tests using BaseVM.rest_api_entity

- cfme/configure/configuration/server_settings.py
- cfme/tests/configure/test_server_roles.py
Removing server roles from ServerInformationView's nested server_roles view that were removed from the CFME UI ages ago:
rhn_mirror
database_synchronization_role
storage_metrics_processor
storage_metrics_collector
storage_metrics_coordinator
storage_inventory
vmdb_storage_bridge
Also, the websocket role exists in 5.10 but not in 5.11, so VersionPicker has been used to implement it as a BootstrapSwitch in 5.10 or to set it to None in 5.11, so that fill() and read() calls on the ServerInformationView.server_roles view in 5.11 do not raise NoSuchElementException errors.
This PR fixes the following test cases:
test_server_roles_changing[default]
test_server_roles_changing[default_candu]
{{ pytest: cfme/tests/configure/test_server_roles.py::test_server_roles_changing -v }}
> [1LP][RFR] Remove unused server roles from ServerInformationView

- cfme/tests/infrastructure/test_snapshot.py
{{ pytest: cfme/tests/infrastructure/test_snapshot.py::test_snapshot_crud -v --use-provider rhv43 --use-provider complete --long-running }}
> [1LP][RFR] Extend test: reload after deleting snapshot

- requirements/constraints.txt
- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
- requirements/template_non_imported.txt
Bump Werkzeug for docs to get rid of security alert as well.
Issues with parallelizer remote collection have been resolved in pytest-polarion-collect 0.21, tested locally.
> [1LP][RFR] Update pytest-polarion-collect, add pytest-report-parameters

- requirements/constraints.txt
- requirements/frozen.txt
Setting of testrun ID via configuration isn't working in cfme-testcases 0.15.1, change came in at 0.13.
dump2polarion downgrade as well, upgrade both together when cfme-testcases issue #1 is resolved
> Downgrade cfme-testcases to 0.12, conf loading broken

- cfme/test_requirements.py
- cfme/tests/cloud/test_delete_cloud_object.py
- cfme/tests/cloud/test_keypairs.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/networks/test_network_providers.py
- cfme/tests/networks/test_sdn_balancers.py
- cfme/tests/networks/test_sdn_crud.py
- cfme/tests/networks/test_sdn_downloads.py
- cfme/tests/networks/test_sdn_inventory_collection.py
- cfme/tests/networks/test_sdn_navigation.py
- cfme/tests/networks/test_sdn_ports.py
- cfme/tests/networks/test_sdn_security_groups.py
- cfme/tests/networks/test_sdn_topology.py
- cfme/tests/storage/test_volume_backup.py
- cfme/tests/test_manual.py
Added generic cloud requirement - is needed for cloud tests where are all cloud providers used.
Deleted duplicated keypair tests.
Also moved some general_ui tests to pvala.
> [RFR] Added test_requirements for test cases owned by me

- cfme/markers/__init__.py
- cfme/markers/isolation.py
- cfme/test_framework/browser_isolation.py
- cfme/tests/integration/test_cfme_auth.py
Browser isolation is needed at a lower level than wrapped around every test case via the CLI option.
This adds a marker (to auth tests first) that enforces setup/teardown based browser isolation.
> [RFR] Add browser isolation marker for test items

- cfme/ansible/repositories.py
- Fix ansible 5.10 problem as it took time to enable ansible
```
DropdownDisabled
b'Dropdown "Configuration" is not enabled'
```
- Now if all `items` in `Dropdown` disabled then over all Dropdown disabled.
{{pytest: cfme/tests/ansible/test_embedded_ansible_crud.py}}
> [1LP][WIPTEST] fix ansible repo enable check

- cfme/fixtures/ansible_fixtures.py
- cfme/tests/ansible/test_embedded_ansible_services.py
Ansible Galaxy role fetching and asserting service finished with okay status.
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k "test_ansible_service_ansible_galaxy_role" --long-running -svvvv }}
> [1LP][RFR] Added test for BZ1734904.

- cfme/fixtures/automate.py
- cfme/tests/automate/test_common_methods.py
- BZ(1700524) is fixed for 5.10.11.0. So need to remove ```ignore_stream```.
- Improved length of the instance and method names created in custom instance global fixture.
{{ pytest: cfme/tests/automate/test_common_methods.py::test_service_retirement_from_automate_method --use-template-cache -qsvvv }}
> [1LP][RFR] Removed ignore stream and updated global fixture

- cfme/tests/cli/test_appliance_console.py
Adding `rhel_testing` marker back on to `test_appliance_console_scap`. Orginally removed because it was using temp appliance but  https://github.com/ManageIQ/integration_tests/pull/9403 should handle the upgrade
> [1LP][RFR] Adding rhel_testing markers back on test_appliance_console_scap

- cfme/common/vm.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/configure/test_landing_page.py
- cfme/tests/infrastructure/test_provisioning_rest.py
- cfme/tests/test_rest.py
- cfme/tests/test_rest_manual.py
- cfme/tests/test_ui.py
- __Fixing__ 
1. Fix test: test_cloud_names_grid_floating_ips - no `title` is present in `entity.quadicon`, as a workaround, a temporary `Text` widget is created which points to the title of quadicon.
2. Fix test: test_landing_page_admin[infra-Networks / Load Balancers] - because Load Balancers have been deprecated in 5.11
3. Fix test: test_provision_vlan - fix `vnic_profile` name whose format has changed
4. Fix test_rest.py tests - 
1. `test_collections_actions[pxe-servers]` - a bug(1754972) has been filed for `pxe_servers` collection
2. `test_rest_paging` - use `/` instead of `//` which returns an int value, instead of float which caused test failure.
3. `test_collection_class_valid` - `random.sample` requires a list or tuple, but `response` doesn't always return that, instead use …
> [1LP][RFR]Fix tests and cleanup

- cfme/utils/template/base.py
Added checking of templates whether they were downloaded correctly.
Fails only when checksum of downloaded image is not equal to checksum from SHA256SUM file.
When SHA256SUM checksum parsing fails then downloaded file is not checked and compared.
Tested.
> [1LP][RFR] Templates checksum

- cfme/services/myservice/__init__.py
`myservice.rest_api_entity` was returning 
```{TypeError}getattr(): attribute name must be string```
due to an unnecessary index `[0]`
> [RFR] Fix rest-api-entity for myservice

- cfme/generic_objects/definition/__init__.py
- cfme/generic_objects/definition/button_groups.py
- cfme/generic_objects/definition/definition_views.py
- cfme/generic_objects/definition/ui.py
- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
Automating test case for https://bugzilla.redhat.com/show_bug.cgi?id=1650559
Note that this test case doesn't require you to create the Ansible Playbook type generic object button, just that the fields are valid. A future test case will create these buttons.
This test case required some framework enhancements to allow for different types of generic object buttons. 
{{ pytest: --long-running cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py::test_ansible_playbook_generic_object_button }}
> [1LP][RFR] Automate test case for BZ 1650559

- cfme/tests/cloud/test_targeted_refresh.py
- cfme/tests/configure/test_landing_page.py
- cfme/tests/networks/test_sdn_crud.py
- cfme/tests/networks/test_sdn_downloads.py
- cfme/tests/networks/test_sdn_inventory_collection.py
- cfme/tests/networks/test_sdn_navigation.py
- cfme/tests/test_rest.py
There are multiple tests running with loadbalancers parameter in 5.11.
There are loadbalancer tests running in 5.11.
Purpose of this PR is to ignore_stream for load balancers tests or uncollect loadbalancer parameter for 5.11.
> [1LP][RFR]Ignoring load balancers in 5.11 because of deprecation

- cfme/tests/cloud/test_keypairs.py
Fixed bytes to string decode for public key in test_keypairs.
Probably new version of package that generates public_key is returning bytes instead of string.
> [1LP][RFR]Fixed bytes to string decode for public key in test_keypairs

- cfme/tests/storage/test_volume_snapshot.py
Volume fixture has to use availability zone in 5.11 for testing snapshots.
> [RFR]Fixing volume snapshot tests for openstack in 5.11

- cfme/tests/cloud/test_azure_manual.py
- cfme/tests/cloud/test_providers.py
- requirements/frozen.txt
:heavy_check_mark:  requires https://github.com/ManageIQ/wrapanapi/pull/419
:stop_sign:  5.10.11 blocker found by test run https://bugzilla.redhat.com/show_bug.cgi?id=1756984 
{{ pytest: cfme/tests/cloud/test_providers.py::test_refresh_with_empty_iot_hub_azure -v --use-provider azure }}
> [1LP][RFR] Automate: test_refresh_with_empty_iot_hub_azure

- cfme/tests/services/test_provision_stack.py
Tests are failing in PRT because of some issues in the tests, not because of the provider fixture scope mismatch as @jaryn reported.
> [1LP][RFR] Add module scope to override provider markers in test_provision_stack

- cfme/common/__init__.py
- This issue is occurring because of change in names of tags assigned to user and groups. Tag category names differs in 5.10 and 5.11. 
- This issue is present on 5.11 while removing assigned tag.
- This fix is required for PR https://github.com/ManageIQ/integration_tests/pull/9331
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py --use-template-cache -qsvvv --long-running}}
> [RFR] Fixed tag remove issue

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/cloud/test_quota_tagging.py
-  Instance type ```m1.large``` is not available. Hence checking with existing type -  ```m1.small```
{{ pytest: cfme/tests/cloud/test_quota_tagging.py --long-running --use-template-cache -qsvvv --use-provider=rhos13 }}
> [1LP][RFR] Fixed instace type issue of rhos provider

- cfme/roles.py
- cfme/tests/configure/test_landing_page.py
- cfme/tests/configure/test_rest_access_control.py
Red Hat Insights is no longer present, remove all references
- __Fixing__ 
1. cfme/tests/configure/test_landing_page.py
2. test_delete_users_from_collection
> [1LP][RFR][NOTEST] Remove insights and load balancers to fix test

- cfme/test_requirements.py
> [RFR] Add jdupuy as auth requirement owner

- cfme/tests/cloud_infra_common/test_relationships.py
There should be no errors during refreshing relationships.
By checking for errors in a more specific test case of this one [1] 5.10.11 blocker [2] was found. (Which will also block 5.10 of this test for now.)
[1] - https://github.com/ManageIQ/integration_tests/pull/9400
[2] - https://bugzilla.redhat.com/show_bug.cgi?id=1756984
{{ pytest:  cfme/tests/cloud_infra_common/test_relationships.py -v --use-provider complete  }}
> [1LP][RFR] Extend test_refresh_relationships: check for errors in evm.log

- cfme/common/vm.py
- cfme/tests/cloud/test_instance_power_control.py
1. Optimize `TestInstanceRESTAPI` to use REST to wait for power changes, use `assert_reponse` and other minor changes.
Note: Dependent on #9387.
{{ pytest: cfme/tests/cloud/test_instance_power_control.py -k "TestInstanceRESTAPI" --use-provider=complete --long-running -vvv }}
> [1LP][RFR] Optimize TestInstanceRESTAPI to execute faster

- cfme/tests/cloud/test_providers.py
Added manual tests for ec2 url_endpoint and ec2 regions.
For url endpoint I need to create VPC and then add it to yamls so I could automate it.
For regions I think there is no way how to automate this test case.
> [1LP][RFR]Added manual tests for ec2 url_endpoint and ec2 regions

- cfme/tests/intelligence/test_download_report.py
Last jenkins run revealed that this test is problematic and all tests that are executed after it fail, because when downloading pdf, the separate window opens and the focus is lost.
It could be possibly fixed by https://github.com/RedHatQE/widgetastic.core/pull/157
For now this should not be run in automation to avoid random failures.
{{ pytest: -v cfme/tests/intelligence/test_download_report.py }}
> [1LP][RFR] skip pdf download

- cfme/tests/cloud/test_quota_tagging.py
- cfme/tests/cloud/test_tenant_quota.py
- This issue is related to instance type of rhos13 provider. Where m1.large is not available in now. So updated the test case with m1.small instance type.
- Now instance type is fetched from cfme_data.yml
- Also updated test case code
- My bad! I missed this file while working on this issue in PR https://github.com/ManageIQ/integration_tests/pull/9331
{{ pytest: cfme/tests/cloud/test_tenant_quota.py --use-template-cache -qsvvvv --use-provider rhos13 --long-running }}
> [1LP][RFR] Fixed instance type issue of rhos with quota

- cfme/automate/explorer/method.py
- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/automate/test_method.py
- Testing embedded method attached with inline automate method is getting copied to new domain
- Updated test steps by going through BZ. This does not belogs to ansible. So changed case component and assignee.
{{ pytest: cfme/tests/automate/test_method.py::test_copy_with_embedded_method --use-template-cache -qsvv}}
> [1LP][RFR] New Test: Test embedded method copy to new domain

- cfme/automate/explorer/domain.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_file_import.py
- Testing crud operation on imported domains with respect to different sources
{{ pytest: cfme/tests/automate/test_file_import.py::test_crud_imported_domains --use-template-cache -qsvv }}
> [1LP][RFR] New Test: Testing CRUD operations on imported domains

- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_v2v_ansible.py
- cfme/tests/v2v/test_v2v_migrations.py
- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
- cfme/tests/v2v/test_v2v_schedule_migrations.py
- cfme/tests/v2v/test_v2v_smoke.py
- cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k rhevm-4.3-virtualcenter-6.7-mapping_data_dual_vm_obj_dual_datastore0 }}
> [1LP][RFR] cleanup volume on target provider

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/configure/configuration/diagnostics_settings.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/configure/test_paginator.py
- cfme/tests/configure/test_remote_server_tabs.py
Navigation within the configuration accordion requires special logic to determine whether the string '(current)' follows a zone or server. The logic currently used by the views and navigation classes in cfme.base.ui, however, is incorrect. It assumes that '(current)' is displayed for the master server (and its associated zone) in a multi-appliance/zone environment. The actual logic, however, is based on whether the web UI request was handled by that server. E.g., if there are two appliances, both of which have the 'User Interface' server role, then a browser connecting to server A will show server A and its zone as 'current', whereas a browser connecting to server B will show server B and its zone as 'current'.
This PR updates the logic in cfme/base/ui.py, and like recent PR #9382 , it …
> [1LP][RFR] Fix logic for whether server or zone display as current

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vmware_provider.py
- widgetastic_manageiq/__init__.py
- __Adding tests__ for BZ 1755070
{pytest: cfme/tests/infrastructure/test_vmware_provider.py  -k "test_vm_notes_ui" --use-provider vsphere65-nested }
> [1LP][RFR] Adding test automation for bz1755070

- cfme/services/myservice/ui.py
- Fix 
```
AttributeError: 'MyServiceAll' object has no attribute 'prerequisite_view'
```
- `resetter` should never use `prerequisite_view`; it can use `view` as its post operation
- We had this resetter to point `ActiveServices` so restoring old line.
{{py.test: cfme/tests/services/test_service_performance.py::test_services_performance cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_automate_service_obj[Service-Submit_all-ViaUI] -vv}}
> [1LP][RFR] resetter should point all active services

- cfme/services/myservice/__init__.py
- cfme/services/myservice/ui.py
- cfme/tests/ansible/test_embedded_ansible_services.py
Automated Ansible tests which stuck in queue and never finishes if "Provider Operations" role is disabled.
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k "test_ansible_service_with_operations_role_disabled" --long-running -svvvv }}
> [1LP][RFR] Automated BZ 1742839 applicable for CF5.11

- cfme/tests/services/test_service_performance.py
{{py.test: cfme/tests/services/test_service_performance.py::test_services_performance -vv}}
> [1LP][RFR] fix: avoid resetter for perf test

- cfme/test_requirements.py
- conf/polarion_tools.yaml
- requirements/frozen.txt
An update to requirement meta, including 'planned in' ID's for polarion.
Default in yaml are the default supported versions of the framework.
Specific requirements can set the ID's as needed.
> [1LP][RFR] Add planned-in to requirements for polarion

- cfme/tests/configure/test_access_control.py
{{pytest: cfme/tests/configure/test_access_control.py -k tenantadmin}}
Automating group crud operations for Tenant administrator
-->
###PRT results:
510 - PASS
511 - PASS
> [1LP][RFR] Multi tenancy : Test group crud as tenant admin

- cfme/tests/automate/custom_button/test_service_objects.py
we have code coverage for this with [basic tests]( https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/automate/custom_button/test_catalog_custom_button.py)
> [1LP][RFR][NOTEST] remove duplicate cat item button test

- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/ansible/test_embedded_ansible_services.py
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k "test_ansible_service_cloud_credentials" --long-running --use-provider=complete -svvvv }}
> [1LP][RFR] Embedded Ansible service to check "Cloud Credentials" used in the service.

- cfme/tests/test_modules_importable.py
Recently I opened a PR that caused `test_import_own_module` to hang in travis -- causing it to fail on a timeout. It is difficult to pinpoint the module that causes travis to hang. Specifying a timeout will allow users to see which module is causing the hang in the travis output. E.g.
```python
=================================== FAILURES ===================================
_________________ test_import_own_module[cfme/scripting/bz.py] _________________
module_path = local('/home/travis/build/ManageIQ/integration_tests/cfme/scripting/bz.py')
@pytest.mark.parametrize('module_path', MODULES, ids=ROOT.dirpath().bestrelpath)
@pytest.mark.long_running
def test_import_own_module(module_path):
"""
Polarion:
assignee: mshriver
casecomponent: Appliance
initialEstimate: 1/4h
"""
if module_path in …
```
> [1LP][RFR] Specify a timeout on test_import_own_module

- cfme/cloud/stack.py
- cfme/services/catalogs/orchestration_template.py
- cfme/services/myservice/__init__.py
- cfme/services/myservice/ui.py
- cfme/services/requests.py
- cfme/tests/services/test_provision_stack.py
Fix `test_provision_stack`, `test_retire_stack` and `test_reconfigure_service`
The stack creation was failing
* Changed name of the input field from dialog_name to label on 5.11.
* Need to select correct network for the stack.
* On 5.11, there is a bug BZ 1754543 making fill method silently fail
to fill the orchestration template content (it fills only first
character).  The template then doesn't contain parameter which then
"surprises" the test as it has no options to fill when ordering the
stack.
* Wait for Submit button to get displayed.
The stack was also not properly cleaned-up after I got it created. When
the stack was created using a service, we need to retire the service to
get the stack deleted by CFME.
When we are deleting the stack on EC2, the stack remains in
DELETE_COMPLETE …
> [1LP][RFR] Fix test_provision_stack

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
- cfme/tests/cloud_infra_common/test_retirement_manual.py
This PR removes manual VM retirement tests that are already taken care of by existing automated tests:
test_vms_retirement_state_field_is_capitalized_correctly
test_retirement_date_uses_correct_time_zone
The capitalization of 'Retirement State' is fixed in 5.10 and later, so the version-specific capitalization is removed from the is_retired method. The datetime checking in verify_retirement_date verifies the expected time zone.
{{pytest: cfme/tests/cloud_infra_common/test_retirement.py -k 'not from_global_region' --use-provider vsphere67-nested -v --long-running}}
> [1LP][RFR] Remove superfluous manual vm retirement tests

- cfme/tests/test_rest.py
1. `test_release_server_info` which automates this [feature](https://www.slideshare.net/ManageIQ/sprint-116/25).
{{ pytest: cfme/tests/test_rest.py -k "test_release_server_info"  -sqvvv }}
> [1LP][RFR] New Test: test_release_server_info

- cfme/tests/cloud_infra_common/test_relationships.py
- cfme/tests/infrastructure/test_scvmm_specific.py
Removing the test case `test_vm_volume_specchar1_scvmm` as this test case is already covered by automation with `test_provider_refresh_relationship`
> [1LP][RFR][NOTEST] Remove old test that is covered by automation

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_db_auth.py
Automating some manual test cases that test password types for db auth users. Deleting a manual case that is covered by `test_login.py`
{{ pytest: cfme/tests/integration/test_db_auth.py }}
> [1LP][RFR] Automate test-pwd tests, delete manual cases

- cfme/fixtures/appliance.py
{{ pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_scap --update-url http://download.eng.bos.redhat.com/rhel-7/rel-eng/RHEL-7/RHEL-7.8-20190912.3/compose/Server/x86_64/os/ --update-appliance }}
> [1LP][RFR] Adding RHEL upgrade to Temporary Appliances for Interop Testing

- cfme/tests/infrastructure/test_datastore_analysis.py
The test failed instead of skipping because the whole dropdown was disabled because both options are disabled. Second is to remove the datastore and it's not possible when there are VMs or templates.
{{ pytest: -v cfme/tests/infrastructure/test_datastore_analysis.py::test_run_datastore_analysis  --long-running }}
> [1LP][RFR] added proper skip if the datastore is not available for ssa

- cfme/tests/automate/custom_button/test_service_objects.py
{{pytest: cfme/tests/automate/custom_button/test_service_objects.py::test_custom_button_dialog_service_archived -vv --use-provider vsphere67-nested}}
> [1LP][RFR] Archive vm custom button

- cfme/tests/infrastructure/test_host.py
- widgetastic_manageiq/__init__.py
- __Extending__  entities.get_all() to allow it to return only a subset of the available entities.  This will keep entities I am not using from being built.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_refresh_multi cfme/tests/infrastructure/test_host.py::test_multiple_host_good_creds }}
> [1LP][RFR] Update entities.get_all() to allow return of subset of total entities and optimize how I determine number of entities in test.

- cfme/intelligence/reports/menus.py
- cfme/tests/intelligence/reports/test_menus.py
- widgetastic_manageiq/__init__.py
- __Fixing__ 
1. `add_folder` and `add_subfolder` of ReportMenus
2. Fix `add` method of `FolderManager` widget of wt.manageiq
1. Add `remove_folder` and `remove_subfolder` to ReportMenus
2. Add ` delete` method to `FolderManager` widget of wt.manageiq
1. `test_reports_menu_folder_crd` to `test_menus.py`
{{ pytest: cfme/tests/intelligence/reports/test_menus.py -k "test_custom_reports_menu" -vvvv }}
> [1LP][RFR] Add methods to add and delete folders and subfolders

- cfme/intelligence/reports/schedules.py
- cfme/tests/intelligence/reports/test_reports_schedules.py
1. `ScheduleCollection` to include a new attribute `user_email`.
1. `test_reports_schedules_user`
1. Add a new widget `VolatileBootstrapSelect` for `user_email`.
{{ pytest: cfme/tests/intelligence/reports/test_reports_schedules.py -k "test_reports_schedules_user" -vvv }}
> [1LP][RFR] New Test: test_reports_schedules_user

- cfme/tests/configure/test_register_appliance.py
Removing rhel_testing pytest mark from test_rh_updates because:
1) Uses `appliance_preupdate` so not using the appliance that was upgraded during test run
2) After RHEL upgrade, appliance will not have any updates.
> [1LP][RFR] Remove rhel_testing mark from test_rh_updates

- cfme/tests/cli/test_appliance_console.py
{{ pytest: cfme/tests/cli/test_appliance_console.py }}
> [1LP][RFR] Time configuration removed from the appliance console in 5.11

- cfme/tests/intelligence/reports/test_metering_report.py
- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
This PR restores module scope to provider fixtures where it was accidentally removed by the changes introduced in:
[1LP][RFR] Remove uses of uncollectif where provider markers should be used
https://github.com/ManageIQ/integration_tests/pull/9419
Those changes resulted in errors like the following:
```
____ ERROR at setup of test_validate_custom_rate_memory_usage_cost[virtualcenter-6.5] ____
ScopeMismatch: You tried to access the 'function' scoped fixture 'provider' with a 'module' scoped request object, involved factories
cfme/fixtures/provider.py:282:  def setup_provider_modscope(request, provider)
[...]
```
{{ pytest: cfme/tests/intelligence/reports/test_metering_report.py::test_validate_memory_usage cfme/tests/intelligence/reports/test_validate_chargeback_report.py::test_validate_defau …
> [WIPTEST] Restore accidentally-removed module scope for provider fixture.

- cfme/tests/webui/test_expression_editor.py
The BZ was backported and verified.
{{ pytest: -v cfme/tests/webui/test_expression_editor.py }}
> [1LP][RFR] removed uncollectif for 5.10

- cfme/tests/services/test_dialog_element_in_catalog.py
- Testing handle alert while editing dialog. This feature is introduced in 5.11
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_editor_modify_field --use-template-cache -qsvv --long-running }}
> [1LP][RFR] New Test: Testing  handle alert while editing dialog

- cfme/fixtures/service_fixtures.py
- cfme/services/service_catalogs/__init__.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- Test input values of dialog input after refresh while ordering catalog item
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_field_on_refresh_button --use-template-cache -qsvvv}}
> [1LP][RFR] New Test: Test input values of dialog input after refresh

- cfme/tests/services/test_rest_services.py
1. `test_embedded_ansible_cat_item_edit_rest` automating customer BZ 1716847.
{{ pytest: cfme/tests/services/test_rest_services.py -k "test_embedded_ansible_cat_item_edit_rest" --long-running -vvv }}
> [1LP][RFR] New test: test_embedded_ansible_cat_item_edit_rest

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vm_reconfigure.py
{{ pytest: cfme/tests/infrastructure/test_vm_reconfigure.py  --use-provider vsphere6-nested -vvvv --long-running -k test_vm_reconfig_resize_disk  }}
- Automating VM reconfiguration resize disk
- Removing test_vm_reconfig_attach_iso_vsphere67_nested because it's already automated
- This PR will automate 30 test cases
> [1LP][RFR] Adding new tests of VM reconfig resize disk

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- Testing details page of newly created catalog item via list of catalog items
- This PR automates BZ(1702343)
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_clicking_created_catalog_item_in_the_list -vvv --long-running }}
> [1LP][RFR] New Test: Checking details of catalog item via list

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_cfme_auth.py
Creating a fixture to check logs for plaintext passwords during auth tests. Automates the test case `test_auth_password_plaintext`
> [1LP][RFR] Create a fixture to monitor logs for passwords for auth tests

- cfme/cloud/instance/openstack.py
- cfme/common/vm.py
- cfme/common/vm_views.py
- cfme/tests/webui/test_general_ui.py
- cfme/tests/webui/test_general_ui_manual.py
1. `RightSizeView`  by adding widgets and `is_displayed` property to it.
1. `test_vm_right_size_recommendation_back_button`
1. Add navigator for `RightSizeView` by removing existing navigator registered against `OpenstackInstance` and writing a common one registered against `VM`.
{{ pytest: cfme/tests/webui/test_general_ui.py -k "test_vm_right_size_recommendation_back_button" -vvvv }}
> [1LP][RFR]Automate: test_vm_right_size_recommendation_back_button

- cfme/common/host_views.py
- cfme/tests/infrastructure/test_host.py
- __Adding test__ for BZ 1746214, opened in 5.10.9. Fix is slated for 5.11.1.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_compare_hosts_from_provider_allhosts }}
> [1LP][WIPTEST] Add test_compare_hosts_from_provider_allhosts to test_host.py

- cfme/tests/v2v/test_v2v_migrations_ui.py
Added a test to migrate a VM with different flavor and security group in a different project in OSP and check if the migrated VM got the correct flavor and security group.
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-provider osp13-ims --use-provider vsphere65-nested --provider-limit 2 -vvvv --long-running -k test_v2v_custom_attribute }}
> [1LP][RFR] OSP flavor and security group

- cfme/common/provider.py
- cfme/infrastructure/provider/openstack_infra.py
- cfme/infrastructure/provider/rhevm.py
- cfme/infrastructure/provider/scvmm.py
AttributeError triggered by references to endpoint attributes that don't exist.
There's no clean way to refer back to the default endpoint via the provider, that is an enhancement that can be handled separately.
This, ~~combined with a YAML change to restore the hostname for the openstack events endpoint~~, should prevent AttributeError error results in tests.
> [1LP][RFR] Prevent AttributeError in provider endpoints

- cfme/fixtures/rdb.py
AttributeError as `self.sock` references within RDB resolved `None`
> [1LP][RFR] Have to actually return the socket object

- cfme/tests/candu/test_utilization_metrics.py
- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_provisioning_rest.py
fixture scope mismatches from provider markers.
PRT results: 
Showing test execution for those tests impacted by the scope mismatch. Not trying to resolve every test failure within these tests, just the scope mismatch.
> [1LP][RFR] Fix fixture scope mismatches

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_db_auth.py
{{ pytest: cfme/tests/integration/test_db_auth.py::test_login_invalid_user }}
> [1LP][RFR] Automate test case for checking that invalid user cannot login

- cfme/fixtures/appliance.py
- cfme/fixtures/authentication.py
- cfme/tests/integration/test_aws_iam_auth_and_roles.py
- cfme/tests/integration/test_cfme_auth.py
- cfme/tests/integration/test_ldap_auth_and_roles.py
{{ pytest: --long-running cfme/tests/integration/test_cfme_auth.py }}
> [1LP][RFR] Use temp_appliance_preconfig for auth tests

- cfme/tests/services/test_service_performance.py
- cfme/tests/test_db_migrate.py
The test_db_migrate was removed by accident.
- {{pytest: cfme/tests/test_db_migrate.py::test_db_migrate[ec2_5620] cfme/tests/services/test_service_performance.py -v }}
> [1LP][RFR] Re-add removed test_db_migrate

- cfme/tests/cli/test_appliance_update.py
Uses `appliance_preupdate` fixture, pointless for testing new rhel packages.
> [RFR] Removing rhel_testing marker from test_appliance_update.py

- cfme/services/catalogs/catalog.py
- cfme/tests/services/test_catalog.py
- widgetastic_manageiq/__init__.py
This PR addresses two updates:
1) Updating test_catalog.py
2) Removing the flash message success assertions from the catalog entity and moves them to the crud test
{{ pytest: cfme/tests/services/test_catalog.py::test_catalog_crud }}
> [1LP][RFR] Updates to test_catalog.py and Remove Flash Assert in Catalog Entity

- cfme/tests/candu/test_utilization_metrics.py
Added tests for  C&U data rollup in Availability zones. The tests check if the hourly rollup records are available in the DB.
{{py.test: cfme/tests/candu/test_utilization_metrics.py --use-provider complete -k "azone"}}
510 - PASS
511 - PASS
> [1LP][RFR] Automate tests for C&U data rollup in Availability zones

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_ldap_auth.py
Automating manual test case that asserts that authentication fails if we try to login with a DB user on a ldap-configured appliance. 
{{ pytest: --use-provider vsphere65-nested cfme/tests/integration/test_ldap_auth.py }}
> [1LP][RFR] Automate test case for db user in ldap configured appliance

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_external_auth.py
- cfme/utils/appliance/__init__.py
- cfme/utils/auth/__init__.py
We run this on `freeipa03` instead of `freeipa01` so that `test_cfme_auth` tests are not affected by `ntpd` being turned off. 
{{ pytest: cfme/tests/integration/test_external_auth.py }}
> [1LP][RFR] Test case for setting up external auth when ntpd is off on IPA server

- cfme/tests/test_db_migrate_manual.py
__Cleanup__: The RFE BZ 1464387 is WONTFIX. There is no possibility tu unregister
trough the UI. There is no point of keeping this test case.
> [1LP][RFR][NOTEST]Remove the test_rh_unregistration_ui

- cfme/tests/cloud_infra_common/test_provisioning_manual.py
The referred BZ 1427477 is an RFE that is not resolved and has low PM
score and therefore there is no point of having the test here.
> [NOTEST][1LP][RFR]Remove the test_template_list_of_provider.

- cfme/common/vm_views.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
Automated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1726590 for provisioning with the selected "Linked Clone" option from the template with preallocated disks. 
~Requires wrapanapi PR https://github.com/ManageIQ/wrapanapi/pull/424~
Requires yaml update.
{{ pytest: -v cfme/tests/infrastructure/test_provisioning_dialog.py::test_linked_clone_default }}
Actually, PRT run is useless because the BZ is still on dev. I tested locally and the test currently fails as expected.
> [1LP][RFR] automated BZ 1726590

- cfme/automate/dialogs/dialog_element.py
- cfme/services/service_catalogs/__init__.py
- cfme/tests/services/test_different_dialogs_in_catalogs.py
- Automated scenario: ```Testing default values of dialog widgets```
- Updated test case: ```test_tagdialog_catalog_item```
{{ pytest: cfme/tests/services/test_different_dialogs_in_catalogs.py -vvvv --long-running }}
> [1LP][RFR] New Test: Testing default values of dialog widgets

- cfme/automate/dialog_import_export.py
- cfme/tests/automate/test_service_automate.py
- Checking flash message on wrong page
{{ pytest: cfme/tests/automate/test_service_automate.py -k 'test_import_dialog_file_without_selecting_file' --use-template-cache -qsvvv}}
> [1LP][RFR] New Test: Checking dialog export flash message on while editing dialog

- cfme/fixtures/vm.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud/test_tag_mapping.py
{{ pytest: cfme/tests/cloud/test_tag_mapping.py::test_ec2_tags -v --use-provider complete }}
{{ pytest: cfme/tests/cloud/test_instance_power_control.py -v --use-provider complete }}
> [1LP][RFR] automate test_ec2_tags_image & instance

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_service_automate.py
- Retire vm with new custom user using option ```Retire this vm``` and checking evm.logs file to check whether any error is available.
- Test case: ```test_variable_pass``` already automates two test cases: ```test_variable_pass_successive_playbook``` and ```test_variable_pass_method_playbook```
{{ pytest: cfme/tests/automate/test_service_automate.py::test_retire_vm_now --use-provider=complete --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing retire vm and evm logs

- cfme/scripting/bz.py
- cfme/tests/test_modules_importable.py
- data/bugzilla-queries/fixed_in_query.yaml
- requirements/frozen.txt
- requirements/template_scanned_imports.txt
Adding a new `miq bz` command, `miq bz build-report`, this command will build a BZ report on BZ's that have gone into the current appliance version (i.e. their `fixed_in` version matches that of the current appliance). 
```
Usage: miq bz build-report [OPTIONS]
Generate BZ report on bugs going into a z-stream
Options:
-s, --stream TEXT      Stream for which to get BZs (e.g. 5.10.11.0)
[default: <current-appliance-stream>]
-q, --query-file TEXT  Template query file  [default: fixed_in_query.yaml]
-o, --output           Show information about BZs in the terminal  [default:
False]
-f, --filename TEXT    Filename into which the report is written (must be
yaml file)
--help                 Show this message and exit.
```
> [1LP][RFR] BZ build report

- cfme/common/provider.py
- cfme/tests/infrastructure/test_host.py
- __Adding tests__ for infra_hosts FA to cover BZ1634794 fixed in 5.11. And also updated setup_provider_min_hosts fixture and tests that use it.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_crud
cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_refresh_multi
cfme/tests/infrastructure/test_host.py::test_compare_hosts_from_provider_allhosts }}
> [1LP][RFR] Add test_infrastructure_hosts_crud to test_host.py to cover BZ1634794

- cfme/configure/access_control/__init__.py
- cfme/fixtures/authentication.py
- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_cfme_auth.py
{{py.test: cfme/tests/configure/test_access_control.py -k 'switch_between_tenants'}}
> [1LP][RFR] Automate tenant switching of LDAP user

- cfme/scripting/bz.py
bz scripting stuff needs lazy evaluation. otherwise, it makes miq sprout check current appliance
> [RFR] fix sprout client

- cfme/tests/integration/test_cfme_auth.py
{{ pytest: --long-running cfme/tests/integration/test_cfme_auth.py::test_login_retrieve_group }}
> [RFR] Fix uncollect for test_login_retrieve_group

- cfme/tests/automate/custom_button/test_generic_objects.py
- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
- One step toward automating Open Url support for `User`, `Group` and `Tenanat`
- RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1550002
- **one test will fail for tenant**
**Note:** RFE is in progress means Faild ON_QA but still I would like to make it as part of integration test as some objects are working fine.
{{pytest: cfme/tests/automate/custom_button/test_generic_objects.py::test_custom_button_open_url_evm_obj -v}}
> [1LP][RFR] Automating RFE for open url general objects

- cfme/fixtures/parallelizer/remote.py
- cfme/test_framework/appliance.py
- cfme/utils/appliance/__init__.py
This helps to see what slaves get which tests during a parallelized run. To use it you can do 
```pytest --collect-only --dummy-appliance --num-dummies N cfme/tests```
{{ pytest: --collect-only --dummy-appliance --num-dummies 4 cfme/tests/ }}
> [1LP][WIPTEST] Allow dummy appliances to be used with the parallelizer

- cfme/fixtures/appliance.py
No web ui for an unconfigured appliances
{{ pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_internal_db -v --use-template-cache --use-provider complete --sprout-user-key sprout  --update-url http://download.eng.bos.redhat.com/rhel-7/rel-eng/RHEL-7/RHEL-7.8-20190912.3/compose/Server/x86_64/os --update-url http://download.eng.bos.redhat.com/rhel-7/rel-eng/RHEL-7/RHEL-7.8-20190912.3/compose/Server-optional/x86_64/os -k 'not junkasdf' -m rhel_testing --long-running --ui-coverage --update-appliance }}
> [RFR] Update Sprout Appliances Context Manager to Handle Unconfigured Appl 

- cfme/fixtures/authentication.py
- cfme/tests/integration/test_cfme_auth.py
- cfme/utils/appliance/__init__.py
Sometimes configuring freeipa01 failed with a timeout because NTP was not properly synced. 
{{ pytest: --long-running cfme/tests/integration/test_cfme_auth.py::test_login_evm_group -k "external-freeipa01" }}
> [RFR] Add evmserverd restart so that NTP properly syncs

- cfme/utils/release.py
Was looking to make sure RFR/1LP labels won't get listed in release notes, and they won't by virtue of them not being included in VALID_LABELS.
While reading through I made some small formatting updates, didn't want to just throw them out.
> [1LP][RFR] Small formatting updates to release script

- cfme/base/__init__.py
The test is failing with below error:
```
E       ValueError: not enough values to unpack (expected 1, got 0)
cfme/base/__init__.py:263: ValueError
ValueError
b'not enough values to unpack (expected 1, got 0)'
```
{{pytest: cfme/tests/configure/test_zones.py::test_zone_add_maxlength -svvvv }}
> [1LP][RFR] Fixed zone failing test.

- cfme/roles.py
This tab was removed in CFME 5.11.1
{{ pytest: --long-running cfme/tests/integration/test_aws_iam_auth_and_roles.py -k "evmgroup-super_administrator-role_access0-ViaUI" }}
> [1LP][RFR] Remove Red Hat Cloud tab from role_access

- cfme/tests/integration/test_cfme_auth.py
Tenant is a required field. 
{{ pytest: --long-running cfme/tests/integration/test_cfme_auth.py::test_login_retrieve_group -k "ldap-ad_dev_2012-cn-ldapuser2" }}
> [1LP][RFR] Fix test_login_retrieve_group

- cfme/exceptions.py
- cfme/fixtures/appliance.py
- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/tests/cli/test_appliance_update.py
- cfme/tests/test_db_migrate_manual.py
- cfme/utils/appliance/__init__.py
- cfme/utils/ssh_expect.py
This is the first part of my big PR#8655. I was asked to split it. This is not an easy task to do but I did my best. This PR brings:
* Fixing menu option numbers
* some cleanups
* starting using SSHExpect
* increasing some timeouts
* adding some waits
This PR makes these restore tests passed:
test_appliance_console_restore_db_external result
test_appliance_console_restore_pg_basebackup_ansible
test_appliance_console_backup_restore_db_local result
test_appliance_console_dump_restore_db_local
which is an improvement from the state of origin/master. 
Locally I tested also:
cfme/tests/cli/test_appliance_update.py::test_update_distributed_webui
with pass
The further patches will make the other tests (`cfme/tests/cli/test_appliance_console_db_restore.py` and `cfme/tests/configure/test_proxy.py` …
> [1LP][RFR] Fix restore tests part one

- cfme/fixtures/templates.py
- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_migration_throttling.py
- cfme/tests/v2v/test_v2v_ansible.py
- cfme/tests/v2v/test_v2v_cancel_migrations.py
- cfme/tests/v2v/test_v2v_migrations.py
- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
- cfme/tests/v2v/test_v2v_migrations_ui.py
- cfme/tests/v2v/test_v2v_smoke.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_migration_long_name }}
Made changes to pass template name as string instead of function to fix test failure
vm_obj = collection.instantiate(
>           vm_name, source_provider, template_name=template["name"] )
E       TypeError: 'function' object is not subscriptable`
> [1LP][RFR] Passed template name as string instead of function

- cfme/fixtures/service_fixtures.py
- In FTP server we have separate folders for each entity. mapping as fallow
```
entities:
databases: "miq/Databases"
datastores: "miq/Datastores"
dialogs: "miq/Dialogs"
others: "miq/Others"
reports: "miq/Reports"
```
- Copy all dialogs from `datastores` to `dialog` for now.
- As this PR merged; I will remove `dialogs` l.e. yml files from `datastores`
- Always file name can't be a dialog `label` so added some enhancement in same PR
{{pytest: -sqvv cfme/tests/ -k "test_service_dialog_expression_method or test_update_dynamic_checkbox_field or test_automate_methods_from_dynamic_dialog_should_run_as_per_designed or test_refresh_dynamic_field or test_dynamic_field_on_refresh_button or test_edit_import_dialog or test_upload_blank_file"}}
> [1LP][RFR] separate dialog and datastores

- cfme/fixtures/v2v_fixtures.py
get_vm method do not have any param name template
Fixing below error
TypeError: get_vm() got an unexpected keyword argument 'template'
> [1LP][RFR] Fixing the type error

- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/tests/test_rest_manual.py
- cfme/tests/webui/test_general_ui_manual.py
1. test_widget_generate_content_via_rest - [BZ 1761836](https://bugzilla.redhat.com/show_bug.cgi?id=1761836)
2. test_service_refresh_dialog_fields_default_values - [BZ 1730813](https://bugzilla.redhat.com/show_bug.cgi?id=1730813)
3. test_schedule_automation_request - [BZ 1740340](https://bugzilla.redhat.com/show_bug.cgi?id=1740340)
4. test_update_roles_via_rest_name_change - [BZ 1596142](https://bugzilla.redhat.com/show_bug.cgi?id=1596142)
5. test_compare_vm_from_datastore_relationships -  [BZ 1733120](https://bugzilla.redhat.com/show_bug.cgi?id=1733120)
- __Removing tests__
1. test_automation_request_task [already automated]
2. test_date_should_be_change_in_editing_reports_scheduled [already automated]
3. test_custom_reports_with_timelines
> [1LP][RFR] Manual test cleanup and qe-test-coverage test cases

- cfme/services/myservice/ui.py
- cfme/tests/services/test_service_manual_approval.py
{{ pytest: cfme/tests/services/test_service_manual_approval.py -k 'test_service_retire_manual_approval' --long-running --use-template-cache -sqvvv }}
> [1LP][RFR]  Adding new test of service retire manual approval

- cfme/tests/automate/__init__.py
- cfme/tests/automate/test_method.py
- cfme/tests/cloud_infra_common/test_power_control_manual.py
-  Testing ```tag_delete``` method introduced for deletion of tags under category
- This test case also goes through methods like ```test_create```, ```tag_exists``` etc
- **Note**: Test cases ```test_archived_instance_status``` and ```test_orphaned_instance_status``` are already automated in test case ```test_power_options_on_archived_instance_all_page```
{{ pytest: cfme/tests/automate/test_method.py::test_delete_tag_from_category --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Test tag delete using automate method

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/utils/appliance/__init__.py
- cfme/utils/appliance/console.py
Hopefully an __enhancement__ of how the code is layed out in the repo.
{ py.test: -v cfme/tests/cli/test_appliance_console_db_restore.py }
> [1LP][RFR] Extract ApplianceConsole and fixtures cli methods into cfme.utils.appliance.console

- cfme/tests/ansible/test_embedded_ansible_basic.py
- cfme/tests/ansible/test_embedded_ansible_manual.py
{{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py::test_embed_tower_repo_add_new_zone  --long-running -svvvv }}
> [1LP][RFR] Automated BZ1656308, Add Ansible repository in another zone.

- cfme/tests/ansible/test_embedded_ansible_tags.py
test_tag_ansible_playbook[details] failed in latest test run, not fixing the test case in this PR
> [RFR] Refactoring: delete copypasta in test_embedded_ansible_tags

- cfme/containers/image.py
When there are multiple container images with the same name, the ManageIQ rest api returns the first one in the list. This may not always be the correct images. 
{{ pytest: cfme/tests/containers/test_containers_smartstate_analysis.py::test_containers_smartstate_analysis_api --use-provider ocp-39-hawk }}
> [RFR] Update Rest API Calls to find_by() instead of get() for Container Images

- cfme/fixtures/service_fixtures.py
- cfme/services/myservice/__init__.py
- cfme/services/myservice/ssui.py
- cfme/services/myservice/ui.py
- cfme/services/service_catalogs/ssui.py
- cfme/tests/automate/custom_button/test_service_objects.py
- cfme/tests/ssui/test_ssui_myservice.py
- Moved fixture as global 
- Automated test
- Some enhancements in ssui service pages
- Like order retired should return request object
- etc..
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_retire_owned_service --long-running}}
> [1LP][RFR] Service retired

- cfme/tests/v2v/test_v2v_ansible.py
- cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_v2v_ansible.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running }}
PR to fix 
AttributeError: 'MigrationPlanRequestDetailsView' object has no attribute 'flash'
> [RFR] Fixed failure for flash

- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
> [1LP][RFR] pining wait_for to 1.1.1 parsedatetime problem

- cfme/fixtures/authentication.py
- cfme/tests/test_login.py
{{pytest: --long-running cfme/tests/test_login.py cfme/tests/integration/test_cfme_auth.py}}
> [1LP][RFR] fixed calls for removed session fixtures

- cfme/fixtures/v2v_fixtures.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_dual_nics_migration }}
OSP Tests fail when VM networks are passed in parameters for V2V tests as it has only one lan.This PR fixes it
> [RFR] Fixed network failure for OSP

- cfme/services/myservice/ssui.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- widgetastic_manageiq/__init__.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_provider_field_should_display_in_vm_details_page_in_ssui -v}}
> [1LP][RFR] SSUI page provider check tests

- cfme/scripting/bz.py
- cfme/utils/bz.py
handle api_key authentication to bugzilla
remove contextmanager for login, the underlying library should authenticate when URL is passed
Add scan for clone BZs to the method used for BZ coverage reports
At this time, it takes a while (several minutes) to run when collecting clone BZ's. May be able to do some filtering to optimize, based on cross-cloning of BZ's.
Additional coverage list generated by this change:
```
id: 1155295, qe_test_coverage: ?
id: 1232022, qe_test_coverage: ?
id: 1236683, qe_test_coverage: ?
id: 1316137, qe_test_coverage: -
id: 1335529, qe_test_coverage: -
id: 1357013, qe_test_coverage: -
id: 1382845, qe_test_coverage: -
id: 1382847, qe_test_coverage: -
id: 1385897, qe_test_coverage: -
id: 1386782, qe_test_coverage: -
id: 1388152, qe_test_coverage: -
id: 1393120, …
```
> [1LP][RFR] Update authentication for bz util, add clone coverage

- cfme/tests/containers/test_container_provider_refresh.py
{{ pytest: cfme/tests/containers/test_container_provider_refresh.py --use-provider ocp-39-hawk }}
> [1LP][WIPTEST] Automated Test Case for BZ 1732442

- cfme/tests/cloud/test_cloud_events.py
- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/cloud_infra_common/test_events.py
These tests were collecting against `azure_msdn` which has no templates on it.
> [1LP][RFR] Add required flags for test_cloud_timelines.py

- cfme/tests/integration/test_cfme_auth.py
These tests were facing an error because the auth setting change to NOT retrieve groups from the LDAP server takes some time to register. Therefore, when the LDAP user was logging into the appliance, MIQ pulled the LDAP groups rather than the local groups. 
{{ pytest: cfme/tests/integration/test_cfme_auth.py::test_login_local_group --long-running --use-provider complete -k "ad_dev_2012-upn-ldapuser10" }}
> [RFR] Fix test_login_local_group tests

- cfme/configure/configuration/diagnostics_settings.py
4 of the tests got broken `test_collect_multiple_servers[*-from_secondary]` with the error
```
E               widgetastic_patternfly.CandidateNotFound: message: Could not find the item CFME Region: Region 0 [0]/Zone: Default Zone (current)/Server: EVM, [34] in Boostrap tree diagnostics_tree, path: ('Zone: Default Zone (current)', 'Server: EVM, [34]'), cause: Was not found in Zone: Default Zone (current)
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:1459: CandidateNotFound
CandidateNotFound
b"message: Could not find the item CFME Region: Region 0 [0]/Zone: Default Zone (current)/Server: EVM, [34] in Boostrap tree diagnostics_tree, path: ('Zone: Default Zone (current)', 'Server: EVM, [34]'), cause: Was not found in Zone: Default Zone (current)"
``` …
> [1LP][RFR] fixed log collection from second server

- cfme/fixtures/parallelizer/__init__.py
- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
slave id appears as bytes in logs everywhere. That's a bit annoying. 
This PR should make it appear as string in logs.
{ pytest: --long-running --use-template-cache --collect-only --dummy-appliance --num-dummies 10 }
> [1LP][RFR] fix slave id representation in logs

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_git_import.py
- Testing domain import via git from different branch than master
- Git repository doesn't have to have master branch
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_import_without_master --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing domain import via git from different branch than master

- cfme/fixtures/artifactor_plugin.py
capabilities don't have platform and version in currently used selenium. so, this code throws exception. 
It seems those fields were renamed into browserVersion and browserPlatform. Thus this PR fixes that issue.
> [1LP][RFR] fixing error in artifactor shutdown appearing due to changes in selenium

- cfme/tests/automate/test_service_dialog.py
- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/automate/test_service_dialog.py::test_service_dialogs_crud_non_admin_user --long-running}}
> [1LP][RFR] Adding user service dialog crud test

- cfme/configure/configuration/region_settings.py
- cfme/tests/test_replication.py
1. test_replication_re_add_deleted_remote
2. test_replication_delete_remote_from_global
- __Removing tests__
1. test_replication_low_bandwidth
1. Make `setup_replication` a fixture instead of a function.
2. Add a new method `remove_global_appliance` to `Replication`.
3. Enhance the `subscription_table`.
{{ pytest: cfme/tests/test_replication.py --long-running  -vvv }}
> [1LP][RFR] New Replication Automation tests

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_service_dd_dialog_load_values_on_init --long-running}}
> [1LP][RFR]  Adding dialog load value init test

- sprout/appliances/models.py
- sprout/appliances/tasks/template.py
there is a bug with django's jsonfield. it gets updated with data on every save and doubles data size.
it happens in template.set_status call.
This PR is intended to fix this issue.
> [1LP][RFR] fix sprout's huge custom_data issue

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_domain.py
- After upgrading appliance from lower version to higher version.The change in datastore versions logged in evm logs.
{{ pytest: cfme/tests/automate/test_domain.py::test_redhat_domain_sync_after_upgrade --long-running -vv }}
> [1LP][RFR] New Test: Testing domain version changed after upgrading appliance

- cfme/tests/webui/test_general_ui.py
- cfme/tests/webui/test_general_ui_manual.py
1. `test_compliance_column_header` 
2. `test_misclicking_checkbox_vms`
- Remove related manual test cases.
{{ pytest: cfme/tests/webui/test_general_ui.py -k "test_compliance_column_header or test_misclicking_checkbox_vms" -vvv }}
> [1LP][RFR]Automate: test_compliance_column_header AND test_misclicking_checkbox_vms

- cfme/tests/automate/test_service_dialog.py
- cfme/tests/configure/test_rest_access_control.py
- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/tests/test_rest_manual.py
- cfme/tests/webui/test_general_ui_manual.py
1. `test_authorization_header_sql_response`
2. `test_vm_compliance_attribute_rest`
- __Updating tests__  - Update missing Bugzilla coverage and missing markers.
1. `test_create_picture_with_role`
2. `test_reports_service_unavailable`
3. `test_notification_url_parallel_requests`
4. `test_service_refresh_dialog_fields_default_values`
- __Removing tests__ 
1. `test_copying_customization_dialog`
> [1LP][RFR] Audit qe-test-coverage for Customer BZs

- cfme/automate/import_export.py
- cfme/tests/ansible/test_embedded_ansible_automate.py
- cfme/tests/automate/test_git_import.py
- Testing proper error flash message for playbook type domain imports
{{ pytest: cfme/tests/ansible/test_embedded_ansible_automate.py::test_import_domain_containing_playbook_method --use-template-cache -qsvv --long-running }}
> [1LP][RFR] New Test: Testing proper error flash message for playbook type domain imports

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_request_details_page_tagcontrol_field --long-running}}
> [1LP][RFR]  Adding dialog tag control for request test

- cfme/utils/template/base.py
It should compare checksums even when template_image file exists.
It could be downloaded incomplete.
When file is corrupted, it will be deleted and downloaded again.
> [RFR] ec2 template checksum validation fix

- cfme/tests/intelligence/reports/test_reports.py
1. `test_import_report_preserve_owner`
- __Enhancements__
1. Apply black and remove unused arguments.
2. Convert all formattings to use f-string
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_import_report_preserve_owner" -vvv }}
> [1LP][RFR] Automate: test_import_report_preserve_owner

- cfme/tests/intelligence/reports/test_reports.py
Automated this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1696412
{{ pytest: -v cfme/tests/intelligence/reports/test_reports.py::test_reports_filter_expression_editor_disk_size }}
> [1LP][RFR] automated BZ 1696412

- cfme/tests/services/test_catalog_item.py
- __Fixing__ test_add_button because it is currently checking assert message with button name. It should check with rover name and removed version check which is not required.
Note: You can introduce Screenshots/Gifs for providing more information.
{{pytest: cfme/tests/services/test_catalog_item.py::test_add_button -v}}
> [1LP][RFR] Fixed test_add_button testcase

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_simulation.py
- It should consider attribute message in logs with instance as per BZ fixed for custom button simulation: https://bugzilla.redhat.com/show_bug.cgi?id=1651099
{{ pytest: cfme/tests/automate/test_simulation.py::test_attribute_value_message --use-template-cache -qsvvv}}
> [1LP][RFR] New Test: Test message attribute while simulation

- cfme/tests/containers/test_provider_configuration_menu.py
Ability to pause/resume providers removed from gui in 5.11
{{ pytest:  cfme/tests/containers/test_provider_configuration_menu.py --use-provider ocp-311-hawk }}
> [1LP][RFR] Ignore Pause/Resume Container Test for 5.11

- cfme/tests/containers/test_ssl_providers.py
{{ pytest: cfme/tests/containers/test_ssl_providers.py --use-provider ocp-39-hawk }}
> [RFR] Fix pytest.raise for test_ssl_providers

- cfme/utils/appliance/__init__.py
`mgmt` object should refer to the wrapanapi VM object, not the wrapanapi provider object. That is provided by `self.provider`.
Fixing a bug introduced in #9674
> [1LP][RFR] mgmt should refer to the vm object provider object

- cfme/generic_objects/definition/button_groups.py
- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
Updating generic object button tests as some BZs have been fixed that change the flash messages. 
{{ pytest: --long-running cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py }}
> [RFR] Updates for gob tests that have had BZ's fixed

- cfme/tests/infrastructure/test_scvmm_specific.py
- cfme/utils/appliance/__init__.py
CFME is now zipped for hyperv images in 5.11, here we are fixing our test case to deal with the zipped file. 
Depends on:
~~https://github.com/ManageIQ/wrapanapi/pull/411~~
~~https://github.com/ManageIQ/wrapanapi/pull/418~~
#9716 
{{ pytest: --use-provider scvmm --long-running cfme/tests/infrastructure/test_scvmm_specific.py::test_create_appliance_on_scvmm_using_the_vhd_image }}
> [RFR] Add support for 5.11's zip files for creating appliance on SCVMM

- cfme/fixtures/service_fixtures.py
- cfme/tests/ssui/test_ssui_dashboard.py
- cfme/tests/ssui/test_ssui_myservice.py
1)Automated chargeback test for a service with multiple VMs
2)Parametrized the order_service fixture on vm_count
3)Fixed the test_vm_console test so that it passes a key value pair to the vm_count parameter to the order_service fixture
{{ pytest: --long-running cfme/tests/ssui/test_ssui_dashboard.py::test_service_chargeback_multiple_vms cfme/tests/ssui/test_ssui_myservice.py::test_vm_console }}
PRT Results:
510 - PASS
511 - PASS
> [RFR] SUI:Automate chargeback test for service with multiple VMs

- cfme/common/provider.py
- cfme/infrastructure/provider/virtualcenter.py
1. `provider.create_rest` to work for VMRC console endpoints.
1. Add `_fill_vmrc_console_endpoint_dicts`
> [RFR] Add _fill_vmrc_console_endpoint_dicts to provider.create_rest()

- cfme/tests/cloud_infra_common/test_relationships.py
- Blocked azure provider refresh test case as it shows error in evm logs. but no issue with fetching data in UI. 
- This issue was already reported for 5.10 but now this seems to be reproducible on 5.11 too. As commented here: https://bugzilla.redhat.com/show_bug.cgi?id=1756984#c9
- Hence blocking this test case
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py -k 'test_provider_refresh_relationship' --use-template-cache -qsvv --long-running --use-provider=azure }}
> [1LP][RFR] Blocked azure provider refresh test case

- cfme/dashboard.py
- cfme/tests/intelligence/reports/test_widgets.py
- widgetastic_manageiq/__init__.py
Recent changes to widgetastic broke the dashboard tests:
```
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic/widget/base.py:1199: AttributeError
AttributeError
b'This is not an instance of widgets. You need to call this object and pass the required parameters of the view.'
```
There probably actually was a problem that ParametrizedView class was
used where just View should have been used.
When testing this PR, I also found out that the `cfme/tests/intelligence/reports/test_widgets.py::test_widgets_on_dashboard` fails on CFME 5.11 because it misses RSS which was removed in 5.11. I made creating of that conditional and this fixes the test.
{{pytest: cfme/tests/intelligence/test_dashboard.py cfme/tests/intelligence/reports/test_widgets.py -v}}
> [1LP][RFR] Fix dashboard tests.

- cfme/tests/cloud_infra_common/test_rest_providers.py
- cfme/tests/test_rest_manual.py
1. `test_create_rhev_provider_with_metric` and remove manual test.
{{ pytest: cfme/tests/cloud_infra_common/test_rest_providers.py -k "test_create_rhev_provider_with_metric" }}
> [1LP][RFR] Automate: test_create_rhev_provider_with_metric

- cfme/tests/test_providerless_rest.py
- cfme/tests/test_rest.py
- cfme/tests/test_rest_manual.py
1. `test_update_roles_via_rest_name_change`
1. Add a separate test file for rest test cases that do not require a provider setup.
{{ pytest: cfme/tests/test_providerless_rest.py -vvv }}
> [1LP][RFR] Automate: test_update_roles_via_rest_name_change

- cfme/tests/cloud/test_quota_tagging.py
- Fixed quota exceed test case for cloud provider
{{ pytest: cfme/tests/cloud/test_quota_tagging.py -k "test_quota_tagging_cloud_via_lifecycle or test_cloud_quota_by_lifecycle" --long-running --use-provider=complete -qsvvv --use-template-cache }}
> [1LP][RFR] Fixed quota exceed via lifecycle for cloud provider

- cfme/fixtures/skip_not_implemented.py
~120 tests were hitting NotImplementedError, which was triggering a typeerror in pytest.skip in the fixture.
> [1LP][RFR] Fix typeerror in skip_not_implemented plugins

- cfme/tests/candu/test_utilization_metrics.py
{pytest: cfme/tests/candu/test_utilization_metrics.py --use-provider azure}
> [1LP][RFR] Adding BZ blocker for Azure candu tests for 510

- cfme/tests/v2v/test_migration_throttling.py
{{ pytest: cfme/tests/v2v/test_migration_throttling.py --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running  }}
Fixes Throttling test for OSP
> [1LP][RFR] Migration throttling fix

- cfme/tests/test_providerless_rest.py
- cfme/tests/test_rest_manual.py
1. `test_authorization_header_sql_response`
{{ pytest: cfme/tests/test_providerless_rest.py -k "test_authorization_header_sql_response" -vvv }}
> [1LP][RFR] Automate: test_authorization_header_sql_response

- cfme/intelligence/optimization.py
- cfme/modeling/base.py
- cfme/tests/intelligence/test_optimization.py
1. `test_delete_generated_report`
- __Enhancements__
1. Add `RowNotFound` exception to the list of exceptions for `exists` method in `BaseEntity`.
2. Replace `runs` attribute of `OptimizationReport` to property.
{{ pytest: cfme/tests/intelligence/test_optimization.py -k "test_delete_generated_report" -vvv }}
> [1LP][RFR] Automate: test_delete_generated_report

- cfme/tests/configure/test_access_control.py
- widgetastic_manageiq/__init__.py
Fixed Error:
```
>                       self._repr_step(*self._process_step(steps_tried[-2])))})
E               widgetastic_patternfly.CandidateNotFound: message: Could not find the item Everything/Settings in Boostrap tree features_treebox, path: ('Settings', 'Configuration'), cause: Was not found in Everything
/var/ci/cfme_venv3/lib64/python3.7/site-packages/widgetastic_patternfly/__init__.py:1459: CandidateNotFound
CandidateNotFound
b"message: Could not find the item Everything/Settings in Boostrap tree features_treebox, path: ('Settings', 'Configuration'), cause: Was not found in Everything"
```
{{ pytest: cfme/tests/configure/test_access_control.py -k "test_role_crud or test_tenant_unique_catalog" --use-template-cache -qsvvv }}
> [1LP][RFR] Fixed rbac tree issue on 5.11

- cfme/tests/automate/custom_button/test_service_objects.py
> [RFR] remove tests as not supported by object

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vm_reconfigure.py
- widgetastic_manageiq/vm_reconfigure.py
- Add network adapter reconfig facility in model page
- Automate network related test
{{pytest: cfme/tests/infrastructure/test_vm_reconfigure.py -k 'test_vm_reconfig_add_remove_network_adapters' --long-running -v}}
> [1LP][RFR] Network adapter support in VM reconfiguration for vsphere

- cfme/configure/configuration/region_settings.py
- cfme/fixtures/appliance.py
- cfme/tests/test_replication.py
- __Adding tests__ Test to add multiple remote appliances in global appliance
- {{pytest: cfme/tests/test_replication.py::test_replication_appliance_add_multi_subscription   --long-running -v}}
> [1LP][RFR] New Test: Adding multiple Remote Appliances in Global Appliance

- cfme/tests/configure/test_rest_access_control.py
- cfme/tests/infrastructure/test_config_management_rest.py
- cfme/tests/webui/test_rest.py
- __Fixing__ 
1. test_create_picture_with_role[individual
2. webui/test_rest.py
{{ pytest: cfme/tests -k "test_create_picture_with_role or test_delete_advanced_search_filter_from_detail or test_delete_advanced_search_filter_from_collection" -vvv }}
> [RFR] Fix test failure

- cfme/configure/configuration/region_settings.py
- cfme/tests/test_replication.py
- __Adding tests__ Adding new tc which is making remote appliance, global appliance and starting replication using UI
- {{pytest: cfme/tests/test_replication.py::test_replication_appliance_set_type_global_ui --long-running -v}}
> [1LP][RFR] Configuring remote app. and global App replication using UI

- cfme/common/vm.py
- cfme/utils/appliance/implementations/common.py
it should be disabled during vmrc tests. these changes will be tested by @kedark3 's PR #9703 .
> [1LP][RFR] dismiss_alerts closes vmrc related alerts

- cfme/fixtures/appliance.py
- cfme/test_framework/sprout/client.py
- cfme/utils/__init__.py
Automatically prolong the sprout "pool" until fixture is destroyed.
This was sucessfully tested in https://github.com/ManageIQ/integration_tests/pull/9524
> [1LP][RFR] Add periodic call and use it to prolong the appliances from Sprout

- cfme/test_framework/appliance.py
- cfme/utils/dockerbot/pytestbase/setup.sh
if dummy-appliance option is set, it will cause setting collect-only by default
> [1LP][RFR] dummy-appliance=>collect-only

- cfme/common/provider.py
- cfme/fixtures/templates.py
- cfme/utils/bz.py
- cfme/utils/db.py
- cfme/utils/events_db.py
- cfme/utils/providers.py
Deprecation warnings for some collections imports.
> [1LP][RFR] Fix collections import deprecation

- artifactor/plugins/filedump.py
- artifactor/plugins/reporter.py
changes are being tested in job `izapolsk-testing-9748`
> [1LP][RFR] fixing one more issue in artifactor's filedump

- cfme/fixtures/parallelizer/__init__.py
- cfme/markers/serial.py
- cfme/tests/control/test_basic.py
- cfme/tests/integration/test_aws_iam_auth_and_roles.py
- cfme/tests/integration/test_cfme_auth.py
- conftest.py
In some instances there are test cases that should be run against a single appliance (in order to avoid fixture duplication on multiple appliances). For instance, the auth tests require a temp appliance. But during jenkins test runs they are split between multiple slaves, each of which requires a temp appliance. 
This creates an unnecessary load on sprout -- resulting in test failures due to sprout being unable to provision appliances. This PR introduces a `serial` marker. By marking a test as a serial test with `pytest.mark.serial`, all the test cases generated by that test function will be sent to a single slave.
~Depends on #9580~  
{{ pytest: --long-running --use-sprout --sprout-appliances=2 cfme/tests/integration }}
> [RFR] Serial marker for parallelizer

- cfme/scripting/bz.py
- cfme/tests/configure/test_db_backup_schedule.py
- cfme/tests/test_db_migrate_manual.py
The BZ may be covered by a manual test case. These cases were ignored
whe marked as manual test cases. We need to collect them as well to make
the coverage flag set.
> [1LP][WIPTEST] Also use --include-manual when setting the coverage flag.

- cfme/tests/infrastructure/test_child_tenant.py
FIXES #7385 
Per developer comments, the test should not be using super_admin for quota testing.
PRT failures aren't really related to the original issue that was blocking the test.  I'd like to work with @ganeshhubale (test assignee) to resolve these failures in a followup.
{{ pytest: cfme/tests/infrastructure/test_child_tenant.py::test_child_tenant_quota_enforce_via_lifecycle_infra --long-running }}
> [1LP][RFR] Change test_child_tenant to use non super-admin role

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_file_import.py
- Test overwrite domain using rake
{{ pytest: cfme/tests/automate/test_file_import.py -k 'test_overwrite_import_domain' --use-template-cache -qsvv }}
> [1LP][RFR] New Test: Test overwrite domain using rake command

- cfme/automate/dialogs/service_dialogs.py
- cfme/tests/services/test_rest_services.py
- cfme/tests/test_rest_manual.py
1. Automate: `test_service_refresh_dialog_fields_default_values` and remove manual test.
1. Add `rest_api_entity` property to `ServiceDialogs`.
{{ pytest: cfme/tests/services/test_rest_services.py -k "test_service_refresh_dialog_fields_default_values" --long-running -vvvv }}
> [1LP][RFR] Automate: test_service_refresh_dialog_fields_default_values

- cfme/tests/test_replication.py
- __Adding tests__ Creating VM on global appliance and verifying on remote appliance
- {{pytest: cfme/tests/test_replication.py::test_replication_global_to_remote_new_vm_from_template  --long-running -v }}
> [1LP][RFR] New Test:: test_replication_global_to_remote_new_vm_from_template

- cfme/tests/ssui/test_ssui_myservice.py
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_no_error_while_fetching_the_service --long-running -vv}}
> [1LP][RFR] automate service fetch error after user delete

- cfme/tests/automate/test_common_methods.py
- cfme/utils/appliance/__init__.py
- scripts/harden_security.py
Thanks for the heads up @Fryguy
> [1LP][RFR] Update password gem name

- cfme/tests/webui/test_general_ui.py
- cfme/tests/webui/test_general_ui_manual.py
1. `test_provider_details_page_refresh_after_clear_cookies`
- __Removing tests__
1. `test_red_hat_cloud_page_internal_server_error` inactive test case.
{{ pytest: cfme/tests/webui/test_general_ui.py -k "test_provider_details_page_refresh_after_clear_cookies" -vvv }}
> [1LP][RFR] Automate: test_provider_details_page_refresh_after_clear_cookies

- cfme/automate/explorer/domain.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_git_import.py
- Testing available tags on GitHub repo are displayed while refreshing domain
{{ pytest: cfme/tests/automate/test_git_import.py -k 'test_automate_git_import_deleted_tag' --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing available tags on GitHub repo are displayed while refreshing domain

- cfme/services/catalogs/catalog.py
- cfme/tests/services/test_rest_services.py
1. Add new customer scenario test: `test_crud_service_template_with_picture`
1. Add `rest_api_entity` property to 
1. `Dialog` entity
2. `Catalog` entity
{{ pytest: cfme/tests/services/test_rest_services.py -k "test_crud_service_template_with_picture" --long-running -vvvv }}
> [1LP][RFR] New Test: test_crud_service_template_with_picture

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
**PRT Run**
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_dropdown_int_required --long-running}}
also removed manual test test_dialog_text_box_triggers_fields_shouldnt_refresh_too_soon_often. no test required for testing. bz has already been closed.
> [1LP][RFR] Adding Service Dialog Dropdown tests.

- cfme/tests/cli/test_appliance_console.py
- Testing appliance IP address is present or not on appliance console
- {{pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_check_default_ip -v}}
> [1LP][RFR] New Test:: Testing App IP is present or not on appliance console

- cfme/services/myservice/ssui.py
Old version pick dictionaries, 10s static sleeps
> [1LP][RFR] clean up version picking and time.sleeps in ssui service module

- cfme/configure/configuration/region_settings.py
- cfme/tests/configure/test_register_appliance.py
- cfme/utils/appliance/__init__.py
Fix tests of appliance subscriptions
https://CFME_GITLAB/cfme-qe/cfme-qe-yamls/merge_requests/876
On CFME 5.11:
```
cfme/tests/configure/test_register_appliance.py::test_rh_creds_validation[rhsm-proxy_off] PASSED
cfme/tests/configure/test_register_appliance.py::test_rh_creds_validation[sat6-proxy_off] PASSED
cfme/tests/configure/test_register_appliance.py::test_rh_registration[rhsm-proxy_off] PASSED
cfme/tests/configure/test_register_appliance.py::test_rh_registration[sat6-proxy_off] FAILED
cfme/tests/configure/test_register_appliance.py::test_rhsm_registration_check_repo_names PASSED
cfme/tests/configure/test_register_appliance.py::test_rh_updates FAILED
```    
On CFME 5.10
```
cfme/tests/configure/test_register_appliance.py::test_rh_creds_validation[rhsm-proxy_off] PASSED …
```
> [1LP][RFR] Fix subscription tests

- cfme/tests/services/test_dynamicdd_dialogelement.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_dialog_dynamic_field_refresh_in_log --long-running}}
> [1LP][RFR]  Automate dialog dynamic field refresh 

- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/infrastructure/test_vm_migrate.py
- cfme/tests/test_replication.py
> [1LP][RFR][NOTEST] Re-assigning FA

- cfme/infrastructure/datastore.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/cloud_infra_common/test_power_control_manual.py
- cfme/tests/cloud_infra_common/test_relationships.py
- Testing managed vms relationships
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_datastore_relationships --use-template-cache -qsvvv --use-provider rhv43 }}
> [1LP][RFR] New Test: Testing managed vms relationships

- cfme/services/service_catalogs/ui.py
- cfme/tests/ssui/test_ssui_myservice.py
- Created customer story based on BZ-1695804
- **Here I don't want to use fixtures for setup :D. Just end-end test**
{{pytest: cfme/tests/ssui/test_ssui_myservice.py::test_service_dynamic_dialog_execution --long-running}}
> [1LP][RFR] Automate dynamic dialog execution

- cfme/tests/cli/test_appliance_console.py
- Testing start evm command using remote console and verifying output using API and UI
- {{pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_evm_start -vvvvv}}
> [1LP][RFR] New Test:: Testing start EVM command

- cfme/tests/automate/test_common_methods.py
- This is RFE has exposed ```move_into_folder``` to move VMWare vm to custom folder via automate method
- Depend on PR: https://github.com/ManageIQ/wrapanapi/pull/407
{{ pytest: cfme/tests/automate/test_common_methods.py::test_move_vm_into_folder --use-provider=complete --use-template-cache -qsvv }}
> [1LP][RFR] New Test: Checks moving VMWare vm to custom vm folder

- cfme/tests/services/test_dynamicdd_dialogelement.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_update_dynamic_field_on_refresh --long-running}}
> [1LP][RFR] Adding new dynamic service dialog test

- cfme/tests/services/test_dynamicdd_dialogelement.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_read_dynamic_textbox_dialog_element --long-running}}
> [1LP][RFR]Automate dynamic textbox read value test

- cfme/configure/access_control/__init__.py
- cfme/tests/cloud_infra_common/test_quota_manual.py
- cfme/tests/infrastructure/test_tenant_quota.py
- Test multiple tenant quotas simultaneously
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py -k 'test_simultaneous_tenant_quota' --use-template-cache -qsvv --use-provider=rhv43 }}
> [1LP][RFR] New Test: Testing quota simultaneous

- cfme/tests/cli/test_appliance_console.py
- cfme/utils/appliance/console.py
- testing appliance shutdown scenario
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_shutdown --long-running -v}}
> [1LP][RFR] NewTest::Test Shutdown Appliance

- cfme/utils/ftp.py
- __Fixing__ `FTPClient.ls()` which in my opinion is failing due to the change in year.
**Normal lines**
-rwxrwxrwx   1 ftp      ftp          1602 Jul 25 **05:02** filter_report.yaml
**Changed lines**                   
-rwxrwxrwx   1 ftp      ftp          1361 Jun 10  **2019** import_report.yaml
Error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-13-eec0aba7fc42> in <module>
----> 1 fs.ls()
~/code/cfme_workspace/integration_tests/cfme/utils/ftp.py in ls(self)
343             result.append((is_dir, fields[-1], date))
344 
--> 345         self.ftp.dir(_callback)
346         return result
347 
/usr/lib64/python3.7/ftplib.py in dir(self, *args)
573             if arg:
574                 cmd = cmd + (' ' + arg)
--> 575 …
```
> [1LP][RFR] Fix ftp failures due to year change

- cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
- This PR will fix calling of parametrized fixture.
- **Error in tests:**
```
Fixture "compare_linux_vm_data" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```
{{pytest: cfme/tests/cloud_infra_common/test_vm_instance_analysis.py -k "test_ssa_compliance or test_ssa_schedule or test_ssa_vm" --use-provider vsphere65-nested --long-running -vvv}}
> [1LP][RFR] Fix SSA fixture for failing tests.

- cfme/tests/cli/test_appliance_console.py
- Testing network configuration using negative input
Testing below options:
1) Set DHCP Network Configuration
4) Test Network Configuration
5) Set Hostname
{{pytest: cfme/tests/cli/test_appliance_console.py::test_appliance_console_network_conf_negative --long-running -v}}
> [1LP][RFR] NewTest:: testing network configuration using negative input

- cfme/tests/cli/test_appliance_console.py
- Test to set ipv4 and ipv6 using invalid data
{{pytest: cfme/tests/cli/test_appliance_console.py -k "test_appliance_console_static_ip_negative" -v}}
> [1LP][RFR] NewTest::setting up ipv4 and ipv6 using invalid data

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_service_dynamic_dialog_tagcontrol }}
> [1LP][RFR] Adding Service dynamic dialog tag test

- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/tests/cli/test_appliance_update.py
- cfme/tests/cloud_infra_common/test_provisioning.py
- cfme/tests/configure/test_config_manual.py
- cfme/tests/test_db_migrate.py
Just another bit to decrease the count of BZs with `qa_tests_coverage?` flag.
> [1LP][RFR][NOTEST] Add tests for resolved bugs

- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
1. Automate: test_vm_volume_free_space_less_than_20_percent
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_vm_volume_free_space_less_than_20_percent" --long-running -vvv }}
> [1LP][RFR] Automate: test_vm_volume_free_space_less_than_20_percent

- cfme/utils/appliance/__init__.py
- scripts/clone_template.py
Longer window for SSH timeout through clone_template
> [RFR] Add timeout handling to appliance config and clone_template script

- cfme/tests/configure/test_default_views_cloud.py
- cfme/tests/configure/test_default_views_infra.py
- __Updating tests__  test_infra_compare_view and test_cloud_compare_view to use slice kwarg in entities.get_all() call instead of the inline slice of the returned values. Since I was testing I also updated these tests to use ensure_checked().
> [1LP][RFR] Replace inline slice in entity.get_all() with slice kwarg and use ensure_checked()

- cfme/tests/networks/test_sdn_balancers.py
There's no need to run it in different subscriptions.
{{ pytest: -v cfme/tests/networks/test_sdn_balancers.py::test_sdn_balancers_tagvis  --use-provider complete }}
> [1LP][RFR] test_sdn_balancers_tagvis to run only on one azure provider

- cfme/tests/control/test_alerts.py
Due to recent changes in the `reconfigure` function for reconfiguring a VM, this test is failing with 
```
>       for network_adapters_change in changes['network_adapters']:
E       KeyError: 'network_adapters'
```
This is because a changes dict was supplied rather than a `new_configuration` dict. https://github.com/ManageIQ/integration_tests/blob/b5cbdba1af393290565ac0c29cce72323f3e3ba3/cfme/infrastructure/virtual_machines.py#L1096-L1097
{{ pytest: --long-running --use-provider vsphere65-nested cfme/tests/control/test_alerts.py::test_alert_hardware_reconfigured }}
> [RFR] Use new_configuration rather than changes for reconfigure dict

- cfme/tests/control/test_alerts.py
> [1LP][RFR] Actually fix hardware reconfigured alert test

- cfme/tests/infrastructure/test_timelines.py
BZ 1747132 was marked CLOSED NOTABUG, so we need to change these tests to not check the Host timeline for RHV providers. 
{{ pytest: --long-running --use-provider rhv43 cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_create_event cfme/tests/infrastructure/test_timelines.py::test_infra_timeline_delete_event }}
> [1LP][RFR] Do not check RHV host timeline for create/delete events

- cfme/common/vm.py
- cfme/common/vm_console.py
- cfme/fixtures/vm_console.py
- cfme/tests/infrastructure/test_vmrc_console.py
- __Adding new tests__ VMRC Test automation is added. 
Note: This PR is built on top of work from #9701  and #9595, please review those first so that I can rebase this.
{{pytest: cfme/tests/infrastructure/test_vmrc_console.py}}
izapolsk: REQUIRES #9764 9764
> [1LP][RFR] Automating basic VMRC Console Test

- cfme/common/host_views.py
- cfme/common/provider_views.py
- cfme/infrastructure/cluster.py
- cfme/infrastructure/resource_pool.py
- cfme/tests/infrastructure/test_host_analysis.py
- cfme/tests/webui/test_general_ui.py
- cfme/tests/webui/test_general_ui_manual.py
- requirements/frozen.txt
- __Adding tests__ `test_infrastructure_provider_left_panel_titles`
- __Updating tests__ `test_run_host_analysis` which uses host details sidebar.
- __Enhancement__ Add sidebar accordions to the following pages
1. Infrastructure > Providers
2. Infrastructure > Clusters
3. Infrastructure > Hosts
4. Infrastructure > Resource Pools
Note: Dependent on : https://github.com/RedHatQE/widgetastic.patternfly/pull/114
{{ pytest : cfme/tests/webui/test_general_ui.py::test_infrastructure_provider_left_panel_titles cfme/tests/infrastructure/test_host_analysis.py::test_run_host_analysis -vvv }}
> [1LP][RFR] Add sidebar accordion to Compute Infrastructure pages AND automate test: test_infrastructure_provider_left_panel_titles

- cfme/cloud/instance/__init__.py
- cfme/cloud/provider/__init__.py
- cfme/common/provider.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
- cfme/tests/infrastructure/test_host.py
- __Updating tests and framework__ to use entity ensure_checked() instead of entity.check(). ensure_checked() is an enhancement to check() functionality that accounts for the checked state of an entity when selecting it.
{{ pytest: --use-provider rhv42 --use-provider rhos13 --long-running cfme/tests/cloud_infra_common/test_policy_simulation.py::test_policy_simulation_ui cfme/tests/cloud/test_instance_power_control.py::test_power_on_or_off_multiple cfme/tests/cloud_infra_common/test_vm_instance_analysis.py::test_ssa_multiple_vms cfme/tests/infrastructure/test_host.py::test_multiple_host_good_creds }}
> [1LP][RFR] Replace usage of entity.check() with entity.ensure_checked. Part 1.

- cfme/tests/cli/test_appliance_console.py
__Adding tests__ testing DB configuration command by providing the disk which is not available on the host
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_ap_failed_dbconfig_status -v}}
> [1LP][RFR] CLI - Test to fail DB config command - negative

- cfme/cloud/provider/__init__.py
- cfme/tests/cloud_infra_common/test_relationships.py
- Testing network manager's all security groups by navigation from provider's details page to 
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py -k 'test_change_network_security_groups_per_page_items' --use-template-cache -qsvv --use-provider azure }}
> [1LP][RFR] New Test: Testing network manager's all security groups

- cfme/tests/automate/test_ansible_tower_automate.py
- cfme/tests/cloud_infra_common/test_quota_manual.py
- Testing ansible service with quota enablement
{{ pytest: cfme/tests/automate/test_ansible_tower_automate.py -k 'test_quota_for_ansible_service' --use-template-cache -qsvvv --use-provider=complete }}
> [1LP][RFR] New Test: Testing ansible service with quota enablement

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_dialogs --long-running }}
> [1LP][RFR] Adding dynamic service dialog test

- cfme/tests/configure/test_db_backup_schedule.py
- cfme/utils/log_validator.py
Cover BZ 1732417
This PR also makes `LogValidator` an context manager. Its method `waiting` is a context manager already, but now we have the ability to check the log without any waiting.
> [1LP][RFR] Add check for log errors for NFS Scheduled backup test (BZ#1732417)

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_common_methods.py
- Testing associated vm storages using automate method
{{ pytest: cfme/tests/automate/test_common_methods.py -k 'test_list_of_diff_vm_storages_via_rails' --use-provider complete --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing associated vm storages using automate method

- cfme/tests/cloud/test_providers.py
{{ pytest: -k "test_deploy_instance_with_ssh_addition_template" -v }}
> [1LP][RFR]Implemented automated test for test_deploy_instance_with_ssh_addition_template

- cfme/tests/distributed/test_appliance_replication.py
- cfme/utils/appliance/__init__.py
- cfme/utils/appliance/db.py
This PR updates test_appliance_replication.py to provision unconfigured appliances using sprout fixtures. This addresses the following issue:
Distributed tests don't use random names
https://github.com/ManageIQ/integration_tests/issues/3784
The function-scoped fixture temp_appliances_unconfig_funcscope_rhevm is used to return a pair of unconfigured appliances. Using the 'rhevm' provider type ensures that the two appliances can reach each other's IP address, unlike with, e.g., openstack vm's.
I've also removed the test_appliance_replicate_sync_role_change and test_appliance_replicate_sync_role_change_with_backlog tests, which are no longer relevant (they test the database_synchronization server role, which was removed in CFME 5.7).
{{ pytest: …
> [1LP][RFR] Use appliance provisioning fixtures for distributed and replicated appliance testing

- cfme/tests/cli/test_appliance_console.py
- cfme/utils/appliance/console.py
__Adding tests__ Adding encryption key from the invalid remote host
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_key_fetch_negative -v}}
> [1LP][RFR] CLI - Fetching encryption key from invalid remote host - negative

- cfme/tests/automate/test_service_automate.py
- Added specific error in failures patterns
- Fixed error:
```
>               raise FailPatternMatchError(pattern, "Expected failure pattern found in log.", line)
E               cfme.utils.log_validator.FailPatternMatchError: "Pattern '.*ERROR.*': Expected failure pattern found in log."
cfme/utils/log_validator.py:82: FailPatternMatchError
FailPatternMatchError
b'"Pattern \'.*ERROR.*\': Expected failure pattern found in log."'
```
{{pytest: cfme/tests/automate/test_service_automate.py -k 'test_retire_vm_now' --use-template-cache -qsvv --long-running --use-provider=complete }}
> [1LP][RFR] Fixed vm retire now error message in logs

- cfme/cloud/keypairs.py
- cfme/fixtures/multi_tenancy.py
- cfme/tests/cloud/test_keypairs.py
- cfme/tests/configure/test_access_control.py
- conftest.py
1.Automated test to verify key pair visibility in child tenants
2.Moved fixtures related to multi tenancy to a separate file
3.Added set_ownership method and SetOwnership view to cloud key pair page
{{ pytest: cfme/tests/cloud/test_keypairs.py::test_keypair_visibility_in_tenants cfme/tests/configure/test_access_control.py::test_tenantadmin_user_crud }}
PRT results:
510 - PASS
511- PASS
> [1LP][RFR] Automate test to verify key pair visibility in child tenants

- cfme/fixtures/vm.py
- cfme/test_requirements.py
- cfme/tests/cloud/test_cloud_timelines.py
- cfme/tests/cloud_infra_common/test_cockpit_server.py
- cfme/tests/cloud_infra_common/test_discovery_and_support.py
- cfme/tests/cloud_infra_common/test_genealogy.py
- cfme/tests/cloud_infra_common/test_html5_vm_console.py
- cfme/tests/cloud_infra_common/test_power_control_rest.py
- __Enhancement__ to replace one off fixtures and create_on_provider calls with `create_vm` fixture.
NO PRT RUN. Will run in Jenkins.
> [1LP][RFR][NOTEST]Vm name enhancement 2

- cfme/tests/ansible/test_embedded_ansible_services.py
- cfme/tests/automate/test_common_methods.py
- cfme/tests/automate/test_vmware_methods.py
- cfme/tests/cloud/test_cloud_events.py
- __Enhancement__ to replace one off fixtures and create_on_provider calls with `create_vm` fixture.
NO PRT RUN. Will run in Jenkins.
> [1LP][RFR][NOTEST]Vm name enhancement

- cfme/tests/v2v/test_rest_migrations.py
{{ pytest: cfme/tests/v2v/test_rest_migrations.py --use-provider rhv43 --use-provider vsphere67-ims --provider-limit 2 -vvvv --long-running -k test_rest_plan_create }}
Test to create migration plan via API
> [1LP][RFR]Add migration plan via API

- cfme/ansible/playbooks.py
- cfme/common/__init__.py
- cfme/containers/provider/__init__.py
- cfme/generic_objects/instance/ui.py
- cfme/infrastructure/config_management/__init__.py
- cfme/infrastructure/deployment_roles.py
- cfme/infrastructure/host.py
- cfme/infrastructure/pxe.py
- cfme/networks/provider/__init__.py
- cfme/physical/physical_rack.py
- cfme/physical/physical_server.py
- cfme/physical/physical_storage.py
- cfme/physical/physical_switch.py
- cfme/tests/infrastructure/test_vm_power_control.py
- __Updating tests and framework__ to use entity ensure_checked() instead of entity.check(). ensure_checked() is an enhancement to check() functionality that accounts for the checked state of an entity when selecting it.
{{ pytest: --use-provider rhv42 --use-provider rhos13 --long-running cfme/tests/physical_infrastructure/ui/test_physical_server_list_buttons.py::test_manage_button cfme/tests/infrastructure/test_pxe.py::test_pxe_server_crud cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_navigation_after_download_from_compare cfme/tests/infrastructure/test_vm_power_control.py::test_no_template_power_control cfme/tests/infrastructure/test_vm_power_control.py::test_retire_vm_with_vm_user_role }}
> [1LP][RFR] Replace usage of entity.check() with entity.ensure_checked. Part 2.

- cfme/common/__init__.py
- cfme/common/vm.py
- cfme/containers/image.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/virtual_machines.py
- cfme/storage/object_store_object.py
- cfme/storage/volume.py
- cfme/storage/volume_backup.py
- cfme/tests/cloud/test_instance_power_control.py
- cfme/tests/infrastructure/test_vm_power_control.py
- __Updating tests and framework__ to use entity ensure_checked() instead of entity.check(). ensure_checked() is an enhancement to check() functionality that accounts for the checked state of an entity when selecting it.
###PRT
{{ pytest: --long-running --use-provider ec2west cfme/tests/cloud/test_instance_power_control.py::test_power_options_on_archived_instance_all_page --use-provider rhv43 cfme/tests/infrastructure/test_vm_power_control.py::test_power_options_on_archived_orphaned_vms_all_page }}
> [1LP][RFR] Replace usage of entity.check() with entity.ensure_checked. Part 3.

- cfme/fixtures/appliance.py
- cfme/test_framework/sprout/client.py
- cfme/utils/__init__.py
Reverts ManageIQ/integration_tests#9753
This is causing miq-runtest process to not end after the pytest session has completed and the webdriver is checked back in.  Observed in PRT pods, holding the pod for an extended period and blocking other testing.
> Revert "[1LP][RFR] Add periodic call and use it to prolong the appliances from Sprout"

- cfme/tests/infrastructure/test_vmware_provider.py
- __Fixing__ VMware tests.
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py -k "test_vmware_reconfigure_vm_controller_type or test_vmware_vds_ui_tagging " -v}}
> [1LP][RFR] Fixing tagging test and ignoring deffered bz test for streams 5.10,5.11

- cfme/tests/cli/test_appliance_console.py
- cfme/utils/appliance/console.py
__Adding tests__ Testing restoring DB using NFS via appliance console by providing negative input.
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_network_conf_negative ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_static_ip_negative ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_key_fetch_negative ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_restore_db_network_negative ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_key_fetch_negative -v }}
> [1LP][RFR] CLI - Testing restoring DB using NFS - negative

- cfme/infrastructure/config_management/__init__.py
- cfme/tests/webui/test_general_ui.py
- cfme/tests/webui/test_general_ui_manual.py
1. `test_provider_documentation` and remove it's manual test.
1. Enhance `ConfigManagementCollectionView` and `ConfigManagementView` views `is_displayed` to work for navigation through `AnsibleTowerProvider` and `SatelliteProvider` class.
2. Add `data/ui/provider_docs.yaml`
{{ pytest: cfme/tests/webui/test_general_ui.py -k "test_provider_documentation" -vvv }}
> [1LP][RFR] Automate: test_provider_documentation

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_git_import.py
- conf/cfme_data.yaml.template
- **Note:** In this test case, we are checking that datastore with broken __domain__.yml should not
get imported. But this BZ says, automate namespace, class, instance, method under domain should
be refreshed even if you broke the __domain__.yml once it imported(This could be only tested
manually)
- Made this test case (```test_copy_automate_method_without_edit```) - **manualonly**
{{ pytest: cfme/tests/automate/test_git_import.py -k "test_git_refresh_with_renamed_yaml or test_automate_git_import_multiple_domains  or test_domain_import_git or test_automate_git_domain_displayed_in_service" --use-template-cache -qsvvv }}
> [1LP][RFR] New Test: Testing domain import with broken yml

- cfme/tests/infrastructure/test_host.py
- __Updating tests__ so test_infrastructure_hosts_refresh_multi will not run with rhevm and scvmm providers for more than 2 hosts. These providers will not have the needed hosts and the tests are getting uploaded into Polarion and must be marked blocked, manually.
{{ pytest: --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_refresh_multi }}
> [1LP][RFR] Add uncollect for more than 2 hosts and RHEVM and SCVMM providers

- cfme/fixtures/service_fixtures.py
- cfme/services/myservice/ui.py
- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
1. Automate: `test_reports_generate_custom_conditional_filter_report` and remove manual test.
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_reports_generate_custom_conditional_filter_report" -vvv }}
> [1LP][RFR] Automate: test_reports_generate_custom_conditional_filter_report

- cfme/tests/services/test_myservice.py
{{pytest: cfme/tests/services/test_myservice.py::test_service_state --use-provider vsphere67-nested --long-running }}
> [1LP][RFR]Automated Service state test

- cfme/tests/cli/test_appliance_console.py
__Adding tests__ Verifying available disks on default appliance 
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_extend_storage_negative  -v}}
> [1LP][RFR] Test To Extend Temporary Storage negative-test

- cfme/tests/services/test_myservice.py
{{pytest: cfme/tests/services/test_myservice.py::test_load_service_with_button --long-running }}
> [1LP][RFR] Automate load service with button

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/tests/services/test_catalog_item.py
- cfme/tests/test_manual.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_copy_catalog_item_with_tags }}
No PRT run, the BZ is still in Post state. I have tested locally with ipdb.
> [1LP][RFR] Automating copy catalog item with tags

- cfme/tests/infrastructure/test_provisioning_rest.py
- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/test_ui.py
- cfme/tests/webui/test_general_ui_manual.py
- __Fixing__ 
1. test_each_page
2. test_provision_emails
1. Removing parametrization from `test_report_filter_content`
2. Add "manualonly" tag to `test_pdf_provider_summary"
{{ pytest: cfme/tests/test_ui.py cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_emails -sqvvv --long-running }}
> [1LP][RFR] Fix test

- cfme/automate/buttons.py
- cfme/tests/automate/custom_button/test_buttons.py
- Moving custom button attributes to use `AttributeValueForm`
- It will also fix failing tests
{{pytest: cfme/tests/automate/custom_button/test_buttons.py -k "test_button_avp_displayed or test_simulated_object_copy_on_button or test_attribute_override"}}
> [1LP][RFR] Moving custom button to use AttributeValueForm

- cfme/tests/cli/test_appliance_console.py
To grep` "local_login_disabled to true"` message in log file we have to call `"13) Update External Authentication Options"`=> `"4) Disable Local Login for SAML or OIDC"` function from CLI so added logic for the same.
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_external_auth_all -v}}
> [1LP][RFR] Fix for - test_appliance_console_external_auth_all TC

- cfme/tests/automate/test_domain.py
Test case for Automate domain is failing because of BZ 1752875 WONTFIX, hence removing BZ blocker from test. 
Fixed Error:
```
E            +      where ManageIQTree('ae_tree') = <Accordion 'Datastore'>.tree
E            +        where <Accordion 'Datastore'> = <cfme.automate.explorer.domain.DomainDetailsView object at 0x7ff035d98790>.datastore
cfme/tests/automate/test_domain.py:649: AssertionError
AssertionError
b"assert False\n +  where False = <bound method BootstrapTreeview.has_path of ManageIQTree('ae_tree')>('Datastore', 'bz_1752875', 'System', 'Request')\n +    where <bound method BootstrapTreeview.has_path of ManageIQTree('ae_tree')> = ManageIQTree('ae_tree').has_path\n +      where ManageIQTree('ae_tree') = <Accordion 'Datastore'>.tree\n +        where <Accordion 'Datastore'> = …
```
> [1LP][RFR] Removed BZ 1752875 blocker because won't fix.

- cfme/tests/cli/test_appliance_console.py
- cfme/tests/test_replication.py
__updating_tests__ removing test as we do not have test steps and BZ for the reference.
> [1LP][RFR] Removing test case

- cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
The image with cloud-init needs a bigger flavor than the one which was
getting selected so this patch adds using a ci-flavor-name to specifying
which flavor to use.
This needs yamls PR 885
> [1LP][WIPTEST] Fix test_cloud_init_provisioning for openstack-13

- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_v2v_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py -k "test_dual_nics_migration" --use-provider rhv43  --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR]Fixing dual_nic_migration Test

- cfme/tests/cloud_infra_common/test_relationships.py
Enhanced as per suggestion given: https://github.com/ManageIQ/integration_tests/pull/9799/files#r366572190
{{ pytest: cfme/tests/cloud_infra_common/test_relationships.py::test_change_network_security_groups_per_page_items --use-provider complete --use-template-cache -qsvv }}
> [1LP][RFR] Enhanced security group test case for multiple checks

- cfme/fixtures/appliance.py
- cfme/test_framework/sprout/client.py
- cfme/utils/__init__.py
This introduces back the #9753 reverted in #9862
I believe the revert was not solving any problem we had with the PRT
> [RFR] Reintroduce the reverted Add periodic call and use it to prolong the appliances from Sprout

- cfme/tests/distributed/test_appliance_replication.py
- cfme/utils/appliance/__init__.py
This PR updates the distributed appliance test test_distributed_vm_power_control to use the create_vm fixture. This requires using the parametrized provider fixture, instead of the unparametrized virtualcenter fixture that was used in this module previously. I've changed all of the other tests in the module to use it too, for consistency, even though they do not need it for VM creation.
I've also removed the get_ssh_client method, which is no longer used.
There was an issue with ssh clients getting connection refused errors in PRT testing, when configuring the appliance. This commit also includes a one line change to appliance.configure, to re-connect after the audit rule / network interface related command that triggers the connection closure.
{{ pytest: --long-running …
> [1LP][RFR] Update distributed appliance test to use create_vm fixture

- cfme/configure/access_control/__init__.py
- cfme/tests/cloud_infra_common/test_quota_manual.py
- cfme/tests/infrastructure/test_tenant_quota.py
1. Automate `test_quota_with_reconfigure_resize_disks`
1. Fixing `quota` property of `Tenant` entity.
{{ pytest: cfme/tests/infrastructure/test_tenant_quota.py -k "test_quota_with_reconfigure_resize_disks" -vvvv }}
> [1LP][RFR] Automate: test_quota_with_reconfigure_resize_disks

- cfme/tests/services/test_service_performance.py
- cfme/tests/test_db_migrate.py
- cfme/utils/appliance/db.py
- cfme/utils/ssh.py
- scripts/clean_appliance.py
* Add support for resetting the password of AWS credentials when migrating the DB and v2_key is not available. .../cfme-qe-yamls/merge_requests/893 is needed to test this.
* Add guessing of the db dump format based on the file suffix
* Add invalidating the cache to resolve:
```
@property
def _rest_api_server(self):
shref = self.appliance.rest_api.server_info['server_href']
logger.info(f'server_href: {shref}')
results = self.appliance.rest_api.collections.servers.all
logger.info(f'all servers: {results}')
>       server, = (r for r in results if r.href == shref)
E       ValueError: not enough values to unpack (expected 1, got 0)
```
* Add fixing `database.yml` using fixauth when the file was not available.
{{pytest: cfme/tests/test_db_migrate.py::test_db_migrate -v}}
> [1LP][RFR] Update the test_db_migrate.

- cfme/tests/cloud/test_providers.py
- requirements/frozen.txt
{{ pytest: -k "test_add_delete_add_provider" -v }}
> [1LP][RFR]Implemented automated test for test_add_delete_add_provider

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
This is a follow-up to https://github.com/ManageIQ/integration_tests/pull/9540, making some additional changes that were suggested in review.
1.) cleanup of code that loops over vm instances, e.g.,
```
-    for num in range(2):
-        vms[num].cleanup_on_provider()
+    for vm in vms:
+        vm.cleanup_on_provider()
```
2.) De-duplication of the common code shared by the set_retirement_date methods in the VM and VMCollection classes. The parameter validation and form filling is the same in both classes, and the only differences are in:
- The navigation to the Set/Remove Retirement Date view
- The view instantiation / validation after saving or cancelling any retirement date changes.
I've created a RetirementMixin class and moved the set_retirement_date method there. The code that …
> [1LP][RFR] De-duplicate code for VM / VMCollection retirement

- cfme/tests/storage/test_manager.py
There had to be a change with StorageManagerAllView changed from entities to including_entities so test didn't work.
{{ pytest: -k "test_storage_manager_navigation_from_cloudprovider" -v }}
> [1LP][RFR]test_storage_manager_navigation_from_cloudprovider fix

- cfme/cloud/keypairs.py
- cfme/tests/cloud/test_keypairs.py
Implemented test for QE_TEST_COVERAGE on this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1713400
{{ pytest: -k "test_keypair_ownership_association" -v }}
> [1LP][RFR]Added test_keypair_ownership_association

- cfme/tests/storage/test_manager.py
Added test_storage_manager_quadicon_numbers for qe_test_coverage of BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1650086
{{ pytest: -k "test_storage_manager_quadicon_numbers" -v }}
> [1LP][RFR]Added test_storage_manager_quadicon_numbers

- cfme/fixtures/ansible_tower.py
- cfme/infrastructure/config_management/__init__.py
- cfme/tests/services/test_ansible_workflow_servicecatalogs.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
{{ pytest: cfme/tests/services/test_config_provider_servicecatalogs.py cfme/tests/services/test_ansible_workflow_servicecatalogs.py --use-provider complete}}
> [RFR] Parametrize Tower tests on API version

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/tests/cli/test_appliance_update.py
- cfme/utils/appliance/__init__.py
- cfme/utils/appliance/console.py
- cfme/utils/appliance/db.py
- cfme/utils/appliance/services.py
- cfme/utils/ssh_expect.py
- scripts/scap.rb
This is my last PR that makes the restore tests fixed.
- __Enhancement__ .. generalization of the repmgr attribute to support CFME 5.10 as well as 5.11
- __Fixing__ test_appliance_console_restore_db_replicated
- __Fixing__ timeout for the db backup to complete
- __Enhancement__ - close the ssh channel explicitly using with statement
- __Enhancement__ - make the restore_db_replicated more reliable by adding wait instead of just assert
- __Fix__ - the SCAP update test
- __Enhancement__ - convert some calls to use `interaction.answer`
- __Enhancement__ -  use `re.escape` rather then defining `resc`
- __Fix__ - use preupdate appliances in test_update_replicated_webui. I think appliances of the target version were used so no real update was made.
{{py.test: …
> [1LP][RFR] Fix restore tests third part

- cfme/tests/v2v/test_v2v_cancel_migrations.py
The Test case was failing as the cancel never run due to the check we put for disk migration gets 20%, I noticed that the progress bar never shows real time value and after full disk gets migrated the progress bar certainly reached to 100%, which cause the TC failure  as till the time cancel gets triggered the VM gets migrated 100% to the destination. This PR will not look for 20% instead gives a grace time of 6 minutes for migration to proceed and then cancel the migration.
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k "test_cancel_migration_attachments" --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR]Fixing the TC test_cancel_migration_attachments

- cfme/fixtures/appliance.py
- cfme/fixtures/cli.py
- cfme/test_framework/appliance_log_collector.py
Register a pytest_collect_logs hook that when called, the logs will get
collected when --collect-log is specified.
The PR test is in invalid status, but I believe this is not related to the PR changes. It failed to connect to trackerbot.
The tests executed as part of PRT are irrelevant they just show that we get the logs collected. For this it is actually good that the 5.11 test failed. We can see collection happens even in that case.
{{pytest:  cfme/tests/cli/test_appliance_console_db_restore.py::test_appliance_console_restore_db_samba -v --use-provider 'complete' --collect-logs }}
> [1LP][RFR] Make appliance_log_collector able to fetch logs from additional appliances.

- cfme/fixtures/vm.py
If no template parameter provided then use DSL template.
A small enhancement in PR #9850
> [1LP][RFR][NOTEST] Added default template parameter in create_vm fixture.

- cfme/tests/infrastructure/test_vmware_provider.py
- requirements/frozen.txt
- __Adding tests for Customer BZ 1644770__ 
{{pytest: cfme/tests/infrastructure/test_vmware_provider.py -k 'test_vm_remove_from_inventory_orphan or test_delete_vm_archive'  -v}}
> [1LP][RFR]Adding automation for Customer  BZ1644770

- cfme/ansible/repositories.py
- cfme/tests/ansible/test_embedded_ansible_basic.py
{pytest: cfme/tests/ansible/test_embedded_ansible_basic.py -k "test_embedded_ansible_repository_playbook_sub_dir" --long-running -svvvv}
> [1LP][RFR] Added automation coverage for BZ1734446.

- cfme/tests/cli/__init__.py
- cfme/tests/cli/test_appliance_console.py
__adding_test__ Testing the appliance UI after restarting the appliance database.
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_vmdb_httpd -v}}
> [1LP][RFR] CLI-Testing UI after restarting VMDB

- cfme/tests/automate/test_git_import.py
{{ pytest: cfme/tests/automate/test_git_import.py::test_automate_git_domain_removed_from_disk }}
> [1LP][RFR] Fix AttributeError on test_git_import module import

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_default_value_selection --long-running }}
> [1LP][RFR] Automating service dialog default selection test

- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/tests/test_rest_manual.py
- cfme/tests/webui/test_general_ui.py
1. `test_created_on_time_report_field`
1. Mark tests `test_notification_url_parallel_requests` and `test_ui_pinning_after_relog` cases as "manualonly"
2. Improvise `test_reports_generate_custom_conditional_filter_report`
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_created_on_time_report_field"
-vvv }}
> [1LP][RFR] Automate: test_created_on_time_report_field

- cfme/tests/cli/test_appliance_console.py
__adding_test__ to verifying log messages on the failure of DB configuration
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_vmdb_log_negative -v}}
> [1LP][RFR] CLI - Verifying log messages on failure of DB configuration

- cfme/tests/cli/test_appliance_console.py
- cfme/utils/net.py
__Adding tests__ to test the appliance restart scenario via appliance console
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_restart -v}}
> [1LP][RFR]  Testing appliance restart scenario

- cfme/tests/cloud/test_providers.py
{{ pytest: -k "test_add_second_provider" -v }}
> [1LP][RFR]Implement test_add_second_provider

- cfme/tests/cloud/test_providers.py
Added automated test regions_up_to_date for EC2Provider
{{ pytest: -k "test_regions_up_to_date.py" -v }}
> [1LP][RFR] Automated test regions_up_to_date for EC2Provider

- cfme/base/ui.py
- cfme/tests/configure/test_zones.py
- cfme/tests/distributed/test_appliance_manual.py
This PR makes the following changes to zone- and server-related tests:
1.) Rename test_zone_add_dupe to test_zone_add_duplicate.
2.) Move zone name and description generation out of create_zone() and into the individual tests in cfme/tests/configure/test_zones.py:. This might eventually be moved into a parametrized fixture.
3.) Automate some manual tests and remove them from cfme/tests/distributed/test_appliance_manual.py. The new automated tests are in cfme/tests/configure/test_zones.py:
test_distributed_field_zone_description_special and test_distributed_field_zone_name_special -> test_zone_add_punctuation
test_distributed_field_zone_name_whitespace and test_distributed_field_zone_description_leading_whitespace -> test_zone_add_whitespace
The new test test_zone_add_whitespace is marked …
> [1LP][RFR] Zone test automation / parametrization

- cfme/fixtures/rbac.py
- cfme/tests/v2v/test_v2v_migrations_ui.py
{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py -k test_rbac --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere65-nested -qsvv }}
> [1LP][RFR] Fix product features for role used in v2v migration test

- cfme/configure/configuration/region_settings.py
- cfme/tests/configure/test_register_appliance.py
__Fixing__ test_rh_updates
* make it fail when ssh command fails
* version-pick correct repo for 5.10 and 5.11
Also __do better job__ in testing BZ  1673136 and mark the test with automates
I am expecting failure of the satellite tests unitl we get the repos defined in config present in our satellite.
I have slight problems with one test. The  `cfme/tests/configure/test_register_appliance.py/test_rh_registration[sat6-proxy_off]` of CFME 5.10 fails due to CFME failing to reach the state `subscribed`. It passed 16 times in the row on my machine though. I am not 100% but I think this is a bug in CFME or is it that we have our satellite somehow misconfigured. I was opening some bugs about the subscription feature has problems, but AFAIR some were closed as WONTFIX and it starts to be …
> [1LP][RFR] Fix rh updates

- cfme/tests/v2v/test_v2v_migrations_ui.py
- cfme/v2v/infrastructure_mapping.py
PRT results:
510 - PASS
511 - PASS
{{pytest: cfme/tests/v2v/test_v2v_migrations_ui.py -k  test_v2v_with_no_providers --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere65-nested -qsvv }}
> [1LP][RFR] Update v2v inframap view

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/reports/test_reports.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/utils/timeutil.py
1. `test_reports_timezone`
1. Enhance `cfme.utils.timeutil.parsetime` to be compatible with different timezones. This may not work in case the timezone is not found in `pytz` module.
2. Add a new property `report_timezone` to `SavedReport` entity and modify `queued_datetime_in_title` and `datetime_in_tree` accordingly.
{{ pytest: cfme/tests/intelligence/reports/test_reports.py -k "test_reports_timezone" -vvv }}
> [1LP][RFR] Automate: test_reports_timezone

- cfme/intelligence/reports/reports.py
- __Fixing__ 
1. Reporting test cases failing from KeyError
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py -k "test_providers_summary" -vvv }}
> [1LP][RFR] Fix KeyError for reports

- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/ansible/test_embedded_ansible_services.py
{{pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k "test_service_ansible_service_name" --long-running -svvvv }}
> [1LP][RFR] Ansible automate BZ1505929, for Ansible service name different from catalog item.

- cfme/tests/configure/test_config_manual.py
- cfme/tests/configure/test_workers.py
Added as a check if memory threshold changed in advanced setting after change in UI inside `test_set_memory_threshold_in_ui` test case.
EDIT: Added the advanced settings check to all test cases.
Also automated `test_set_memory_threshold_in_advanced_settings` and merged it with this test case
During that, paradoxically a UI bug - blocker was found: https://bugzilla.redhat.com/show_bug.cgi?id=1799443 , so also `test_set_memory_threshold_in_ui` test cases were fixed to recognize the bug.
~All the tests happen on the same page, adding `_view` module scope fixture almost halved the execution time.~
{{ pytest: cfme/tests/configure/test_workers.py::test_set_memory_threshold -v }}
> [1LP][RFR] Automate remaining test_set_memory_threshold test cases & check in advanced settings

- cfme/tests/cli/test_appliance_console.py
__adding_test__ Adding test to apache reload
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_apache_reload_log_rotate -v}}
> [1LP][RFR] apache reload check

- cfme/cloud/provider/ec2.py
- cfme/fixtures/vm.py
This PR makes a couple changes to the create_vm / create_vm_modscope fixtures and adds create_vms / create_vms_modscope, for creating a specified number of vms/instances.
1.)  The vm name creation was split between the _get_vm_name and _create_vm methods. I think it makes more sense to have all of the vm name creation within _get_vm_name, so it's all in one method now.
2.) EC2Provider.deployment_helper now looks in the provider YAML for an 'instance_type' key under the template, and passes any value it finds back to vm.create_on_provider. (I originally had this in the fixture code under _create_vm, but this is really an EC2-specific thing, so I've moved it EC2Provider.) 
3.) Updated create_vm / create_vm_modscope parameter checking code, so that template_type isn't required. (The …
> [1LP][WIPTEST] Add create_vms fixture for multiple VMs, add deploy_args support.

- cfme/tests/infrastructure/test_snapshot.py
- __Updating tests__ to support VirtualCenter6.7 functionality reverting to snapshots created while VM is suspended.
{{ pytest: --long-running --use-provider vsphere67-nested --use-provider vsphere65-nested cfme/tests/infrastructure/test_snapshot.py::test_operations_suspended_vm}}
> [RFR] Add conditional and assert to support VirtualCenter6.7 functionality

- cfme/tests/cli/test_appliance_console.py
__Fixing__  Testcase: **test_appliance_console_ipa** was failing due to timeout error while unconfigure IPA so fixed this issue
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_ipa --long-running -v}}
> [1LP][RFR] - Fixed test_appliance_console_ipa testcase

- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/automate/custom_button/test_infra_objects_ansible.py
> [RFR][NOTEST] Already automated manual test remove

- cfme/services/service_catalogs/ssui.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
- cfme/tests/ssui/test_ssui_service_catalogs.py
{{ pytest: cfme/tests/ssui/test_ssui_service_catalogs.py -k 'test_ssui_disable_notification' --long-running --use-template-cache -sqvvv }}
also removed the test_create_generic_instance  manual test. BZ has been closed as won't fixed and we already have generic object automation test
> [1LP][RFR] Adding SSUI disable notification test

- cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
- cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Testcases which are under **test_vm_instance_analysis.py**  file uses **provider** but **test_ssa_vm_ec2_agent_tracker** not using provider so PRT failing with below error. 
```
2020-02-24 07:16:37,724 [I] [cfme] SPROUT: Called available_cfme_versions with () {} (cfme/test_framework/sprout/client.py:65)
2020-02-24 07:16:38,436 [I] [cfme] Pushed appliance hostname [DummyApplianceHostname] on stack 
Previous stack head was empty (cfme/utils/appliance/__init__.py:2963)
2020-02-24 07:16:49,902 [W] [cfme] provider marker included override kwarg, this is unnecessary (cfme/markers/env_markers/provider.py:482)
2020-02-24 07:16:49,954 [W] [cfme] provider marker included override kwarg, this is unnecessary (cfme/markers/env_markers/provider.py:482)
2020-02-24 07:16:55,677 [E] [cfme] def …
```
> [RFR] - Fixed test collect

- cfme/tests/cloud_infra_common/test_power_control_rest.py
- cfme/tests/intelligence/reports/test_canned_corresponds.py
- cfme/tests/webui/test_general_ui.py
- __Fixing__ 
1. `test_operations_vm_on`
2. `test_datastores_summary`
3. Uncollect `test_power_control_rest.py` and `test_provider_summary_topology` for Config Manager providers.
{{ pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py -k "test_operations_vm_on or test_datastores_summary"  --use-provider=complete  -svvv}}
> [1LP][RFR] Fix Tests

- cfme/tests/services/test_catalog_item.py
Fixed TC:
Flash message string format changed on UI so changed testcase expected flash  message string as per UI
{{pytest: cfme/tests/services/test_catalog_item.py::test_catalog_item_crud --long-running -v}}
> [1LP][RFR] - Fixed  Catalog - flash message string

- cfme/fixtures/appliance.py
- cfme/tests/distributed/test_appliance_replication.py
- cfme/utils/appliance/__init__.py
1.) Add test_replication_connect_to_vm_in_region test, to automate BZ:
Bug 1678142 - [RFE] As a User, I want to open my VMs of a remote region from Global Region in a new browser tab to be able to performs all actions
https://bugzilla.redhat.com/show_bug.cgi?id=1678142
2.) Add a rhevm-specific preconfigured appliance fixture: temp_appliance_preconfig_funcscope_rhevm.
3.) Use the new temp_appliance_preconfig_funcscope_rhevm fixture for the remote (region 0) appliance in db replication tests, and for the primary database-owning appliance in distributed appliance tests. This cuts down the time to run each test by ~5-10 minutes, since now only the global or secondary appliance needs to be configured after checking it out from sprout.
{{ pytest: --long-running …
> [1LP][RFR] Add test_replication_connect_to_vm_in_region

- cfme/common/vm.py
- cfme/tests/cloud_infra_common/test_retirement.py
This PR updates vm retirement tests to use the new create_vm and create_vms fixtures.
Also, the following change in PR 9904 broke VM retirement tests:
```
cfme/utils/timeutil.py:
-    saved_report_title_format = "%a, %d %b %Y %H:%M:%S +0000"
+    saved_report_title_format = "%a, %d %b %Y %H:%M:%S"
```
That's because BaseVM uses this format string for retirement date formatting:
```
cfme/common/vm.py:
RETIRE_DATE_FMT = parsetime.saved_report_title_format
```
The retirement date formatting logic in verify_retirement_date() then fails. This PR makes the following additional changes to fix this:
1.) Update BaseVM.RETIRE_DATE_FMT. Also add BaseVM.RETIRE_DATE_MSG_FMT for formatting retirement dates when they appear in a flash message.
2.) Simplify the logic in verify_retirement_date(). Uses …
> [1LP][RFR] Update vm retirement tests to use create_vm / create_vms

- cfme/automate/import_export.py
- cfme/base/ssui.py
- cfme/base/ui.py
- cfme/common/__init__.py
- cfme/common/vm.py
- cfme/configure/configuration/server_settings.py
- cfme/containers/image.py
- cfme/containers/provider/__init__.py
- cfme/infrastructure/virtual_machines.py
- cfme/intelligence/reports/schedules.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/configure/test_schedule_operations.py
- cfme/tests/physical_infrastructure/ui/test_physical_server_list_buttons.py
- cfme/v2v/infrastructure_mapping.py
- cfme/v2v/migration_plans.py
- requirements/frozen.txt
- widgetastic_manageiq/__init__.py
Use the FlashMessages view, which replaces the widget implementation in widgetastic_patternfly 1.3.0.
Most of the changes are of the form
```
-    flash = FlashMessages("div.import-flash-message")
+    @View.nested
+    class flash(FlashMessages):
+        ROOT = 'div.import-flash-message'
-    flash = FlashMessages('.//div[@id="flash_msg_div"]')
+    flash = View.nested(FlashMessages)
```
and any subsequent method/attribute access is unchanged. Adding some basic PRT with representative test cases that call flash methods.
{{ pytest: -k 'test_vm_filter_without_user_input or test_reports_schedule_crud' cfme/tests/infrastructure/test_advanced_search_vms.py cfme/tests/intelligence/reports/test_crud.py -v }}
> [1LP][RFR] Use FlashMessages view

- cfme/common/vm.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/tests/infrastructure/test_vm_clone.py
- __Updating tests__ in test_snapshot.py to use new create_vm global fixture.
The function test_verify_revert_snapshot fails for rhv providers. This was failing before the update to create_vm and is not caused by it. I am going to begin work on fixing test_verify_revert_snapshot for rhv providers in another PR shortly.
> [1LP][RFR] Update snapshot tests to use create_vm fixture

- cfme/tests/cloud_infra_common/test_genealogy.py
The purpose of this PR is to remove openshift as a provider in test_genealogy.py
> [1LP][RFR] Remove openshift provider in genealogy tests

- cfme/tests/cli/test_appliance_console.py
{ {pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_logfile_config_reboot --long-running -v}}
> [1LP][RFR][NOTEST] - Logfile configuration with new disk

- cfme/tests/ansible/test_embedded_ansible_actions.py
- cfme/tests/ansible/test_embedded_ansible_automate.py
- cfme/tests/ansible/test_embedded_ansible_basic.py
- cfme/tests/ansible/test_embedded_ansible_crud.py
- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/ansible/test_embedded_ansible_services.py
> [1LP][RFR] Change assignee from sbulage to gtalreja in ansible tests

- widgetastic_manageiq/__init__.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-template-cache --provider-limit 2 --use-provider osp13-ims --use-provider vsphere65-nested -qsvv -k test_v2v_infra_map_ui}}
> [1LP][RFR] Fix locator 5.11

- cfme/common/provider_views.py
- cfme/tests/infrastructure/test_providers.py
- __Adding tests__ for BZ  1746449. This covers the comparison of provider templates.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_providers.py::test_compare_provider_templates}}
> [1LP][RFR] Add test_compare_provider_templates to test_providers.py

- cfme/tests/test_appliance.py
I as per my understanding BZ coverage don't mean tester will raise Bugzilla against any stream and developer avoid or fixed in another version it doesn't mean its not Bug. Its Bug and better to have coverage for such scenarios.
> [RFR] BZ coverage for 1712944

- cfme/fixtures/v2v_fixtures.py
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims }}
PRT results:
510 - PASS
511 - Currently failing, but would pass once https://github.com/ManageIQ/integration_tests/pull/9953 is merged
> [1LP][RFR] V2V : Update set_conversion_host_api function

- cfme/fixtures/v2v_fixtures.py
UCI support for RHV would be pushed to 5.11.5.
I'm reverting changes made through PR#9954 while making sure that minimal to no change would be required whenever 5.11.5 lands( with support for RHV UCI hosts).
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims }}
5.10 - PASS
5.11 - FAILED, like expected
> [1LP][RFR] UCI code for RHV shouldn't be executed for <=5.11.4

- cfme/tests/v2v/test_conversion_host_ui.py
"appliance" param is missing while calling  get_conversion_data method.
The above method is defined in cfme/fixtures/v2v_fixtures.py 
~~~~~~~~~~
def get_conversion_data(appliance, target_provider)
~~~~~~~~~~~
> [1LP][RFR]Fixing get_conversion_data calling

- cfme/tests/configure/test_docs.py
Remove test test_info, As this functionality has been removed, there are no alt or image anchor to be tested against and every other functionality is accounted.
{{pytest: cfme/tests/configure/test_docs.py  --long-running }}
> [1LP][RFR] Remove test_info for test_docs.py

- cfme/fixtures/v2v_fixtures.py
Correcting conversion_entity value, the conversion_entity is always 'vms' for Openstack provider and it is true for all cfme version, however for RHV provider it is "hosts" till 5.11.4.X version and "vms" from 5.11.5 version.
At the moment the conversion_entity is set to "hosts" which breaks OSP related all tests, This PR will correct the same.
conversion_entity = (
"hosts"
if target_provider.one_of(RHEVMProvider) and appliance.version < '5.11.5'
else "vms"
)
{{ pytest: cfme/tests/v2v/test_conversion_host_ui.py  -k "test_add_conversion_host_ui_crud" --use-template-cache --provider-limit 2 --use-provider osp13-ims  --use-provider vsphere67-ims }}
The above PRT failing due to issue fixed in this #PR …
> [1LP][RFR] Fixing conversion host api for OSP

- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_dynamic_submit_cancel_button_service --long-running }}
Also removed `test_dialog_editor_modify_field` manual test which is no more required, we already have automation related `test_dialog_editor_modify_field`
> [1LP][RFR] Adding dynamic dialog with custom button test

- cfme/fixtures/cli.py
The CFME releases tests were getting skipped because for some reason they started to not like the
EC2 is not selected for the runs used to test new CFME releases. I think this is the best way to resolve the issue. I don't think the EC2 was favoured to OpenStack for any particular reason. OpenStack is on-premise provider and thus the tests will work in "normal" test selection.
{{ py.test: -v cfme/tests/cli/test_appliance_update.py cfme/tests/cli/test_appliance_console_db_restore.py }}
The report http://10.16.45.124/pr9959-r1145-downstream-510z-SBulVn/artifacts/report.html shows one test failed for reason unrelated to this PR: `test_update_embedded_ansible_webui[5.10.14]`
> [1LP][RFR] Swap EC2 with OpenStackProvider in cfme/fixtures/cli.py

- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/distributed/test_appliance_replication.py
This PR automates the manual test test_verify_httpd_only_running_when_roles_require_it, as test_appliance_httpd_roles.
{{ pytest: -k test_appliance_httpd_roles --long-running cfme/tests/distributed/test_appliance_replication.py }}
> [1LP][RFR] Add test_appliance_httpd_roles

- requirements/frozen.txt
This PR updates widgetastic.patternfly to include the changes in:
Add NoSuchElementException handling back into FlashMessages.
https://github.com/RedHatQE/widgetastic.patternfly/pull/118
This will resolve the test failures caused by NoSuchElementException errors in recent SSUI tests, such as the following:
```
with appliance.context.use(context):
dashboard = Dashboard(appliance)
>           assert dashboard.retired_services() == dashboard.results()
cfme/tests/ssui/test_ssui_dashboard.py:218: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[...]
cfme/base/ssui.py:185: in step
self.obj.login()
.cfme_venv/lib64/python3.7/site-packages/sentaku/context.py:131: in __call__
return bound_method(*k, **kw)
cfme/base/ssui.py:156: in login
login_view.flash.assert_no_error() …
```
> [1LP][RFR] Update widgetastic.patternfly to fix FlashMessages exception handling

- cfme/tests/configure/test_paginator.py
Uncollect Server > Database tests in test_paginator_config_pages for 5.11 and later.
These pages in the web UI have been disabled in 5.11:
Bug 1767645 - [RFE] Hide the Configuration -> Database screen 
https://bugzilla.redhat.com/show_bug.cgi?id=1767645
{{ pytest: -vv -k test_paginator_config_pages cfme/tests/configure/test_paginator.py }}
> [1LP][RFR] Uncollect Server > Database tests in test_paginator_config_pages

- cfme/tests/configure/test_database_ui.py
As of 5.11.1, the Configuration -> Database page is disabled by default:
Bug 1767645 - [RFE] Hide the Configuration -> Database screen
https://bugzilla.redhat.com/show_bug.cgi?id=1767645
This PR removes the test for 5.11.
{{ pytest: cfme/tests/configure/test_database_ui.py -k test_configure_vmdb_last_start_time -vv }}
> [1LP][RFR] Add end version of 5.10 for test_configure_vmdb_last_start_time

- cfme/tests/configure/test_config_manual.py
- cfme/tests/distributed/test_appliance_replication.py
Add test_appliance_replicate_remote_down for BZ coverage of:
Bug 1796681 - Replication tab presenting 502 proxy error when remote site is down
https://bugzilla.redhat.com/show_bug.cgi?id=1796681
and remove outdated manual test test_subscription_region_unavailable.
{{ pytest: --long-running -k test_appliance_replicate_remote_down cfme/tests/distributed/test_appliance_replication.py -v }}
> [1LP][RFR] Add test_appliance_replicate_remote_down

- cfme/services/catalogs/catalog_items/catalog_bundles.py
- cfme/tests/services/test_generic_service_catalogs.py
{{pytest: cfme/tests/services/test_generic_service_catalogs.py::test_copy_catalog_bundle --long-running }}
> [1LP][RFR] Adding copy catalog bundle

- cfme/tests/v2v/test_v2v_cancel_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py  --use-template-cache --provider-limit 2 --use-provider={osp13-ims,rhv43} --use-provider vsphere67-ims }}
The BZ in question applies to UCI migration which has been pushed to 5.11.5 . These tests are currently not running on 5.11.4 because of the BZ blocker. I'd like the blocker to be removed through this PR. There are some failures that I'm currently investigation. I'll submit aditional PRs to address the failures.
> [RFR] Remove UCI blocker BZ for test_v2v_cancel_migrations.py tests

- cfme/tests/configure/test_access_control.py
> [RFR] Changing RBAC FA ownership

- cfme/tests/v2v/test_v2v_migrations_ui.py
- cfme/v2v/infrastructure_mapping.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py --use-template-cache --provider-limit 2 --use-provider={osp13-ims,rhv43} --use-provider vsphere67-ims -k duplicate}}
> [RFR] v2v : Add alert attribute to InfrastructureMappingView

- cfme/test_requirements.py
- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/tests/configure/test_logs.py
- cfme/tests/infrastructure/test_config_management.py
- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_iso_datastore.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/infrastructure/test_publish_vm_to_template.py
- cfme/tests/infrastructure/test_snapshot.py
- cfme/tests/infrastructure/test_vm_delete.py
- cfme/tests/infrastructure/test_vm_engine_relationship.py
- cfme/tests/networks/test_provision_to_virtual_network.py
- cfme/tests/services/test_ansible_workflow_servicecatalogs.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
- cfme/tests/services/test_iso_service_catalogs.py
- conf/polarion_tools.yaml
There is naming clash of centralized control (at the moment also
often called Replication) with HA tests, marked as Replication as well.
I belive these are very different features. So I've:
* Created new polarion marker for the Ha proxy tests.
* Set polarion markers have been set on the tests.
* Set the casecomponent to HAProxy on HA proxy related tests.
> [1LP][RFR] Transfer tests to jhenner.

- cfme/tests/v2v/test_v2v_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations.py --use-template-cache --provider-limit 2 --use-provider=rhv43 --use-provider vsphere67-ims -k test_migrations_different_os_templates}}
-->
511 - PASS
510 - few tests failed because of an Error at teardown while deleting Infra mapping. This failure happens intermittently.
> [RFR] v2v: Fix parametrization of test_migrations_different_os_templates

- cfme/tests/services/test_catalog_item.py
- cfme/tests/services/test_generic_service_catalogs.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_add_bundle_in_bundle --long-running }}
> [1LP][RFR] Automating bundle test #bz 1671522

- cfme/automate/dialogs/dialog_element.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_save_dynamic_multi_drop_down_dialog }}
> [1LP][RFR] Adding service dialog multi drop test

- cfme/tests/services/test_catalog_item.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_catalog_item_duplicate_name --long-running }}
> [1LP][RFR] Adding blockers bz in catalog duplicate test

- cfme/services/service_catalogs/__init__.py
- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_multi_dropdown_dialog_value  }}
> [1LP][RFR] Adding multi_drop down service dialog test

- cfme/tests/services/test_generic_service_catalogs.py
Adding bundle in bundle not supported any more in 5.11 as well
> [1LP][RFR] Removed test test_bundles_in_bundle

- cfme/tests/services/test_dynamicdd_dialogelement.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_dropdown_dialog_descending_values  -vvvv --long-running  }}
> [1LP][RFR] Adding dropdown descending value test

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/tests/cli/test_appliance_update.py
- cfme/tests/distributed/test_appliance_replication.py
The configuration of database replication (global/remote appliances) or distributed (primary/secondary) appliances in cfme/tests/distributed/test_appliance_replication.py has been moved to the replicated_appliances and distributed_appliances fixtures in cfme/fixtures/cli.py.
The existing fixture replicated_appliances_with_providers has uses the new fixture replicated_appliances, and the new fixtures replicated_appliances_preupdate and replicated_appliances_preupdate_with_providers have been added for use by test_appliance_console_restore_db_replicated.
{{ pytest: --long-running -k 'test_appliance_replicate_between_regions or test_external_database_appliance or test_appliance_console_restore_db_replicated or test_update_replicated_webui' cfme/tests/distributed/test_appliance_replication.py …
> [1LP][RFR] Move distributed and replicated appliance configuration to fixtures

- cfme/tests/v2v/test_csv_import.py
{{ pytest: cfme/tests/v2v/test_csv_import.py   -k "test_csv_security_group_flavor"  --use-provider osp13-ims  --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR] Fixing jenkins failure

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console.py
Appliance console menu option's sequence changed recently so modified some testcases according to new appliance menu sequence
Due to this [PR](https://github.com/ManageIQ/manageiq-appliance_console/pull/99) appliance console option changed
{{pytest: ./cfme/tests/cli/test_appliance_console.py -k "test_appliance_console_internal_db or test_appliance_console_dedicated_db or test_appliance_console_external_db or test_appliance_console_external_db_create or test_appliance_console_extend_storage or test_appliance_console_ipa or test_appliance_console_external_auth or test_appliance_console_external_auth_all or test_appliance_console_evm_stop or test_appliance_console_evm_start or test_appliance_console_shutdown or test_appliance_console_restore_db_network_negative or …
> [1LP][RFR] - Fixed TCs

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_not_required_default_value }}
> [1LP][RFR] Automating default non required value drop dialog

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_provision_stack.py
{{pytest: cfme/tests/services/test_provision_stack.py::test_retire_catalog_bundle_service_orchestration_item --long-running   --use-provider ec2west -vvvv }}
It fails on 5.11. we have open bz: 1754543
> [1LP][RFR] Adding stack bundle retire test

- cfme/tests/cli/test_appliance_cli.py
Feature removed in 5.11 so not running on 5.11 build
Reference: https://github.com/ManageIQ/manageiq-appliance_console/commit/79360a844c8319de8879d2af57b9e152c07829a4
{{pytest: ./cfme/tests/cli/test_appliance_cli.py::test_appliance_console_cli_datetime  --long-running -v}}
> [1LP][RFR] datetime testcase- Feature removed in 5.11 so TC not running on 5.11

- cfme/base/ui.py
- cfme/configure/configuration/system_schedules.py
- cfme/tests/cloud/test_providers.py
Added database backup options - openstack_swift and aws_s3.
Added test_provider_compare_ec2_provider_and_backup_regions.
I would like to have OpenstackSwiftProtocolEntities and AWSS3ProtocolEntities in single place, but I don't know what is the good place to be in. Now it is in system_schedules.py an base/ui.py.
{{ pytest: -k "test_provider_compare_ec2_provider_and_backup_regions" -k "test_db_backup_schedule" -v }}
> [1LP][RFR] Test provider compare regions provider and backup

- cfme/tests/automate/test_ansible_tower_automate.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/automate/test_ansible_tower_automate.py::test_retire_ansible_service_bundle  -vvvv }}
> [1LP][RFR] Adding tower bundle retire test

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_provision_stack.py
{{pytest: cfme/tests/services/test_provision_stack.py::test_read_dialog_timeout_ec2_stack  -vvvv }}
> [1LP][RFR] Adding ec2 service stack test

- cfme/tests/cli/test_appliance_console.py
The scap check is implemented elsewhere already. Let's use that implementation.
Please merge cfme-qe-yamls/merge_requests/894 after merging this.
{{ py.test:  cfme/tests/cli/test_appliance_console.py::test_appliance_console_scap  -v }}
> [1LP][RFR] Dedup scap_check_rules.

- cfme/tests/distributed/test_appliance_replication.py
This PR adds BZ test coverage for:
Bug 1629945 - Reports do not run when submitted through a UI which does not have reporting role on.
https://bugzilla.redhat.com/show_bug.cgi?id=1629945
The new test, test_appliance_reporting_role, configures a primary and secondary appliance pair, disables the Reporting role and then queues a report from the primary appliance's web UI, and verifies that the report is run successfully.
{{ pytest: -v --long-running -k test_appliance_reporting_role cfme/tests/distributed/test_appliance_replication.py }}
> [1LP][RFR] Add test_appliance_reporting_role for BZ 1629945

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_myservice.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_myservice.py::test_retire_service_bundle_and_vms --long-running  --use-provider vsphere67-nested}}
removed one rbac test which is already been covered in one service test
> [1LP][RFR] Automating service bundle and vm retire test

- cfme/tests/v2v/test_rest_migrations.py
{{ pytest: cfme/tests/v2v/test_rest_migrations.py  -k "test_rest_mapping_create"  --use-provider={osp13-ims,rhv-ims}  --use-provider vsphere67-ims --provider-limit 2 -v }}
5.11 - Passed
5.10 - Failed due to TimedOutError at fixture function( _start_event_workers_for_osp) which need to address in a separate PR.
> [1LP][RFR] Fixing rest_mapping related TC for OSP

- cfme/tests/services/test_dynamicdd_dialogelement.py
Forgot to remove manual test in this PR which I automated recently https://github.com/ManageIQ/integration_tests/pull/9939
> [1LP][RFR] Removing manual test

- cfme/tests/services/test_service_rbac.py
{{pytest: cfme/tests/services/test_service_rbac.py --long-running }}
> [1LP][RFR] Fix for test_service_rbac

- cfme/tests/v2v/test_v2v_smoke.py
In the smoke test,the transportation method parameter is currently being passed to the wrong fixture. That issue has been fixed through this PR and the parameter is passed to the right fixture so that the test be could run once for each of the transportation methods.
{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims -k test_single_vm_migration_with_ssh_and_vddk }}
-->
510 - PASS
511 - PASS
> [1LP][RFR] Parametrize correct fixture on transformation_method for v2v

- cfme/tests/cloud_infra_common/test_provisioning.py
This adds checking denying of provisioning request. The code was not written in compact way so I did some generalization of the code for checking emails. It is now not waiting for some count of emails but just waits until all expected subjects are present.
For checking different approval actions I used something like strategy design pattern.
Looking at the PR lines stats... removing 98 lines and adding 67 while adding tests ... Is this not awesome?
{{pytest: cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval --use-provider complete --long-running -v}}
There are networking/container issues with prt. thus I had to run the 9d06718600a0e8e60c46440c0b4865a2ced1d09e locally. All passed:
```
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval[virtu …
```
> [RFR] Test provision approval deny

- cfme/dashboard.py
- cfme/tests/test_replication.py
- Verifying the dashboard of remote appliance and global appliance after adding the vm in the provider.
- Provided one more xpath for dashboard UI(widget table)
- Added one function to compare two dictionaries
{{pytest: cfme/tests/test_replication.py::test_replication_global_region_dashboard --long-running -v}}
> [1LP][RFR] New Test: Verifying dashboard of Remote and Global Appliances

- cfme/automate/dialogs/dialog_element.py
- cfme/tests/services/test_dialog_element_in_catalog.py
**Adding new test -** Test to check `Load values on init` option in service dialog when `Dynamix` box enable
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_catalog_load_values_on_init  --long-running -v}}
> [1LP][RFR] - Service Dialog test

- cfme/tests/v2v/test_v2v_cancel_migrations.py
{{ pytest: cfme/tests/v2v/test_v2v_cancel_migrations.py -k "test_cancel_migration_attachments" --use-provider={osp13-ims,rhv-ims}  --use-provider vsphere67-ims --provider-limit 2 -v }}
PRT: Should not block this PR due to fail in 5.10 as the failure is not associated with this PR, we have high priority for 5.11 as build is going to deliver shortly.
5.11: Passed
5.10: Failed due to fixture issue (cfme/fixtures/skip_not_implemented.py:9: ) need to address in a separate PR 
Travis is failing due to : https://github.com/ManageIQ/integration_tests/pull/10029
> [1LP][RFR] updating TC to fix failure

- cfme/tests/cli/test_appliance_console.py
- cfme/tests/cli/test_appliance_update.py
- cfme/utils/appliance/console.py
Fixed SCAP testcase 
{{pytest: ./cfme/tests/cli/test_appliance_console.py::test_appliance_console_scap ./cfme/tests/cli/test_appliance_update.py::test_update_scap_webui  -v}}
> [1LP][RFR] - Fix for SCAP testcase

- cfme/fixtures/pytest_store.py
Rrecent package updates put us on a version of pytest where the attribute can no longer be set.
Following the pytest suggestion, using `_tw` attribute directly, for our case of a TerminalReporter that works outside of a pytest session.
> [1LP][RFR] Update setting of pytest.TerminalReporter.writer attribute

- cfme/tests/services/test_service_catalog_dialog_manual.py
- Adding new test to check is email sent showing in-progress state or not after ordering the catalog
> [1LP][RFR] - Removing duplicate tc

- cfme/networks/provider/__init__.py
- cfme/storage/manager.py
- cfme/tests/cloud/test_providers.py
Added test coverage for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1632750
{{ pytest: -k "test_cloud_provider_dashboard_after_child_provider_remove" -v}}
> [1LP][RFR]Test delete cloud provider dashboard after network provider delete

- cfme/test_requirements.py
- cfme/tests/candu/test_azone_graph.py
- cfme/tests/candu/test_candu_manual.py
- cfme/tests/candu/test_cluster_graph.py
- cfme/tests/candu/test_datastore_graph.py
- cfme/tests/candu/test_gap_collection.py
- cfme/tests/candu/test_graph_groupbytag.py
- cfme/tests/candu/test_host_graph.py
- cfme/tests/candu/test_utilization_metrics.py
- cfme/tests/candu/test_vm_graph.py
> [1LP][RFR][NOTEST] Change assignee from nachandr to gtalreja for candu

- cfme/tests/integration/test_auth_manual.py
- cfme/tests/integration/test_aws_iam_auth_and_roles.py
- cfme/tests/integration/test_cfme_auth.py
- cfme/tests/integration/test_db_auth.py
- cfme/tests/integration/test_external_auth.py
- cfme/tests/integration/test_ldap_auth.py
- cfme/tests/integration/test_ldap_auth_and_roles.py
Re-assigning FA's ownership from jdupuy to dgaikwad
> [1LP][RFR]-Reassigning Auth FA's ownership

- cfme/markers/marker_filters.py
Previously, the filter logic for the tier, requirement, and customer-scenario options was not working as expected. For example, specifying "--tier 1" did not work unless you also included the --requirement filter with a matching requirement. This PR fixes the logic so that each filter is independently applied. Specifically, the fix is to apply the requirement filter *only* if one or more requirements were actually specified.
Example, before fix:
```
$ pytest --collect-only --tier 1 cfme/tests/configure/test_zones.py
[...]
collected 11 items / 11 deselected                                                                                                                                      
[...]
$ pytest --collect-only --tier 1 --requirement Configuration cfme/tests/configure/test_zones.py …
```
> [1LP][RFR] Fix marker_filters logic

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_class.py
- cfme/tests/automate/test_common_methods.py
- cfme/tests/automate/test_domain.py
- cfme/tests/automate/test_domain_priority.py
- cfme/tests/automate/test_file_import.py
- cfme/tests/automate/test_git_import.py
- cfme/tests/automate/test_instance.py
- cfme/tests/automate/test_method.py
- cfme/tests/automate/test_namespace.py
- cfme/tests/automate/test_service_automate.py
- cfme/tests/automate/test_service_dialog.py
- cfme/tests/automate/test_simulation.py
- cfme/tests/automate/test_smoke.py
- cfme/tests/automate/test_vmware_methods.py
> [1LP][RFR] - Updating assignee of automate FA

- .landscape.yml
- cfme/fixtures/xunit_tools.py
- cfme/tests/candu/test_candu_manual.py
- cfme/tests/candu/test_nor_rightsize.py
- cfme/tests/cloud/test_providers.py
- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/intelligence/test_chargeback_manual.py
- cfme/tests/satellite/test_satellite_manual.py
- cfme/tests/services/test_tower_manual.py
- cfme/tests/test_server_manual.py
A few test and fixture files have pylint-related comments in them. This PR removes them, as we are not using pylint. No tests or fixtures should be affected.
> [1LP][RFR][NOTEST] Remove pylint comments

- cfme/tests/automate/test_common_methods.py
Fix for TypeError exceptions in test_vm_retire_extend when setting the retirement date on a VM:
```
>       create_vm.set_retirement_date(retirement_date)
E       TypeError: set_retirement_date() takes 1 positional argument but 2 were given
```
{{ pytest: -vv --long-running --use-provider vsphere67-nested -k test_vm_retire_extend cfme/tests/automate/test_common_methods.py }}
> [1LP][RFR] Fix call to set_retirement_date in test_vm_retire_extend

- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
- cfme/tests/cloud/test_quota.py
- cfme/tests/cloud/test_quota_tagging.py
- cfme/tests/cloud/test_tenant.py
- cfme/tests/cloud/test_tenant_quota.py
- cfme/tests/cloud_infra_common/test_quota_manual.py
- cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
- cfme/tests/configure/test_analysis_profiles.py
- cfme/tests/control/test_alerts.py
- cfme/tests/control/test_bugs.py
- cfme/tests/infrastructure/test_child_tenant.py
- cfme/tests/infrastructure/test_project_quota.py
- cfme/tests/infrastructure/test_quota.py
- cfme/tests/infrastructure/test_quota_tagging.py
- cfme/tests/infrastructure/test_tenant_quota.py
- cfme/tests/intelligence/reports/test_report_chargeback.py
- cfme/tests/test_manual.py
Assigning quota, alert, service_chargeback, and generic_objects tests to me.
> [1LP][RFR][NOTEST] Assign tests to tpapaioa after focus area change

- cfme/tests/services/test_dialog_regex_validation_in_catalog.py
Adding test to check is validation regex text filter working or not
{{pytest: cfme/tests/services/test_dialog_regex_validation_in_catalog.py::test_dialog_regex_validation_button cfme/tests/services/test_dialog_regex_validation_in_catalog.py::test_dialog_element_regex_validation --long-running -v}}
> [1LP][RFR] service dialog regex validation

- cfme/tests/cloud_infra_common/test_provisioning.py
Hopefully made _check_subjects bit more readable.
Improved test documentation
Added related BZs.
Added lovely underscores (:
Local run results (not all tests ran, but I think this is enough to say it still works fine). PRT will fail because of no connectivity into the containers.
```
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval[openstack-13-edit] PASSEDFinishing ...
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval[openstack-13-approve] 
Trying to set up provider env-rhos13
Threads started ...
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval[openstack-13-approve] PASSEDFinishing ...
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_approval[openstack-13-deny] 
Trying to set up provider …
```
> [1LP][RFR] React on review comments of PR10019

- cfme/tests/openstack/cloud/test_instances.py
- cfme/tests/openstack/cloud/test_volume_backup.py
- cfme/tests/openstack/cloud/test_volumes.py
__Fixing__ volume tests. It seems the `storage_manager` attribute was removed without changing the tests. Also the `size` attribute was changed to `volume_size`.
As can be currently seen on trackerbot, all tests executed in this PR were failing like this:
```
>                                         provider=provider)
E       TypeError: create() got an unexpected keyword argument 'storage_manager'
cfme/tests/openstack/cloud/test_volume_backup.py:31: TypeError
TypeError
b"create() got an unexpected keyword argument 'storage_manager'"
```
Many of them started working with these changes.
{{pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_detach_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_volume[openstack-13] …
> [1LP][RFR] Fix OpenStack volume tests

- cfme/tests/infrastructure/test_host_manual.py
This is removal of a manual test only. The manual test has been automated by test_infrastructure_hosts_refresh_multi in test_hosts.py .
> [1LP][RFR] Remove manual test test_host_refresh as it is automated

- cfme/fixtures/provider.py
This PR makes a small fix to the construction of the skip_msg string passed to pytest.skip() when the setup_provider fixture fails to set up the provider. The skip_msg variable was accidentally set to be a tuple instead of a string, resulting in a TypeError:
```
E       TypeError: Skipped expected string as 'msg' parameter, got 'tuple' instead.
E       Perhaps you meant to use a mark?
cfme/fixtures/provider.py:87: TypeError
TypeError
b"Skipped expected string as 'msg' parameter, got 'tuple' instead.\nPerhaps you meant to use a mark?"
```
> [1LP][RFR] Fix typo in skip_msg format when provider setup fails.

- cfme/tests/cloud/test_providers.py
This PR removes the deprecated 'override=True' kwarg passed to pytest.mark.provider for a couple tests. This kwarg is no longer necessary, and was deprecated in https://github.com/ManageIQ/integration_tests/pull/9198 .
{{ pytest: -vv -k 'test_add_delete_add_provider or test_deploy_instance_with_ssh_addition_template' cfme/tests/cloud/test_providers.py }}
> [1LP][RFR] Remove deprecated override kwarg from pytest.mark.provider calls.

- cfme/tests/automate/generic_objects/test_definitions.py
- cfme/tests/automate/generic_objects/test_instances.py
Assigned additional generic-objects-related tests to tpapaioa. Also included a small fix to the breadcrumb location expected in test_generic_object_on_service_breadcrumb.
{{ pytest: -v -k test_generic_object_on_service_breadcrumb cfme/tests/automate/generic_objects/test_instances.py }}
> [1LP][RFR] Assign generic_objects tests to tpapaioa + small fix

- cfme/tests/infrastructure/test_vm_clone.py
- cfme/tests/infrastructure/test_vm_delete.py
- cfme/tests/infrastructure/test_vm_engine_relationship.py
- __Updating tests__ to use a common create_vm fixture instead of local ones to create  vms used in tests. Tasos recently wrote a common create_vm fixture and this PR updates vm tests to use it.
> [1LP][RFR] Remove local vm fixtures so common create_vm is used.

- cfme/fixtures/provider.py
- cfme/markers/env_markers/provider.py
When the provider marker has scope='module' (or anything other than function) set, the provider fixture was not properly scoped. The fixture, and any other fixtures depending on it, would teardown and setup between each test. This PR fixes that behavior with the following changes:
1.) De-duplicate the DataProvider instances created during test collection / parametrization, so that the same instance is always used for the same combination of provider category, type, and version. This is implemented by using a new class method in DataProvider, get_instance(), which stores previously-created instances in a private class-level attribute, _instances. This is a dictionary where the key is the tuple (category, type, version), and the value is the corresponding instance. In a sample test …
> [1LP][RFR] Fix provider fixture scope

- cfme/intelligence/reports/widgets/__init__.py
- cfme/tests/intelligence/reports/test_widgets.py
1. Automate `test_widget_generate_content_via_rest` and remove manual test
1. Add `rest_api_entity` property for BaseDashboardReportWidget.
{{ pytest: cfme/tests/intelligence/reports/test_widgets.py -k "test_widget_generate_content_via_rest"
-vvv }}
> [1LP][RFR] Automate: test_widget_generate_content_via_rest

- cfme/tests/ansible/test_embedded_ansible_actions.py
{{pytest: cfme/tests/ansible/test_embedded_ansible_actions.py --long-running }}
> [1LP][RFR] Fix test_embedded_ansible_actions

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_dynamic_field_update_on_refresh -vvvv --long-running }}
- `test_regex_validation_should_work`  this is also covered in this PR
- removed `test_reconfigure_service_for_dialogs_with_timeout_values`, we already have automation -> `test_reconfigure_service`
- removed few nonrequired tests which no need to test.
- remove `test_should_be_able_to_see_requests_if_our_users...`, we already have related test `test_service_rbac_request`
> [1LP][RFR] Automating dynamic refresh dialog test

- cfme/tests/control/test_actions.py
It is not necessary to run these tests against every version of each provider. From 88 test cases down to 49.
> [NOTEST][RFR] Action tests against one of each provider

- cfme/tests/configure/test_register_appliance.py
The `test_rh_updates` rebuilds some RPMs to make us able to test CFME should be able to update find to some future version.
The repo with the rpms rebuilidng tool had to be rebuilt (yeah... (: ) because the deps on new CFME 5.11 started being not satisfied. I corrected the steps for rebuilding the repo. This will for sure get handy in future. This is not an ideal system, but at the moment I don't know about how to test updates to some future version nicer way without spending money on time travel machine.
The `test_rh_updates` started working after the repo has been updated.
{{ pytest: -v cfme/tests/configure/test_register_appliance.py::test_rh_updates }}
> [1LP][RFR] Correct the steps for rebuilding the repo.

- cfme/tests/ansible/test_embedded_ansible_automate.py
{{ pytest: cfme/tests/ansible/test_embedded_ansible_automate.py -k "test_embedded_ansible_custom_button_localhost or  test_embedded_ansible_custom_button_target_machine or test_embedded_ansible_custom_button_specific_hosts" --long-running }}
> [1LP][RFR] Fix test_embedded_ansible_custom_button

- cfme/fixtures/provider.py
- __Fixing__ Ouput message in _setup_provider_verbose. 
{{ pytest: --use-provider rhv43 --use-provider vsphere67-nested --long-running cfme/tests/infrastructure test_vm_power_control.TestVmDetailsPowerControlPerProvider::test_power_on }}
> [1LP][RFR] Fix bug in format of output in _setup_provider_verbose

- cfme/tests/v2v/test_v2v_manual.py
> [1LP][RFR] Adding test coverage for bugzilla

- cfme/tests/storage/test_volume_types.py
BZ coverage test for https://bugzilla.redhat.com/show_bug.cgi?id=1650082
BZ module is broken as it collects even OpenStack provider for some reason.
> [1LP][RFR]Test storage volume type present

- cfme/tests/integration/test_cfme_auth.py
Adding fix for group creation
{{pytest: ./cfme/tests/integration/test_cfme_auth.py::test_user_group_switching --long-running -v}}
> [1LP][RFR] Fix- Group creation

- cfme/common/provider_views.py
Added fast checks if page content was loaded.
> [1LP][RFR] Add is_displayed for specific provider view entities

- cfme/common/host_views.py
- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_host.py
- __Updating tests__ for infra hosts CRUD to make coverage more intuitive and manageable.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_crud }}
> [1LP][RFR] Rewrite of test_infrastructure_hosts_crud for only single hosts

- cfme/infrastructure/config_management/config_systems/ansible_tower.py
- cfme/infrastructure/config_management/config_systems/satellite.py
- cfme/tests/webui/test_advanced_search.py
_~2 tests failed in 5.10 due to timeout. It seems unrelated to this PR~ _outdated__
Bug found during fixing these tests:
https://bugzilla.redhat.com/show_bug.cgi?id=1777493
_~Edit: Waiting for #9317 to be merged first, then this PR will be changed
check just last commit~_
Merged Ansible and Satellite classes. "Satellite class" to ConfigManagement class was named ConfigManagement, which was a little bit confusing. Removed 2 tests of landing pages of both ConfigMangement instances, as they were not supposed to be tested and were always skipped anyways.
As I touch module-level pytestmark, I let the whole module to be tested by PRT.
1 failed test case in 5.10 -> TestServices.test_filter_crud[myservices-all]  doesn't look to be related to these changes.
> [1LP][RFR] Fix tests: test_advanced_search.py::TestConfigManagement

- cfme/cloud/provider/__init__.py
- cfme/cloud/provider/ec2.py
- cfme/common/provider.py
- cfme/common/vm.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/provider/scvmm.py
- cfme/infrastructure/virtual_machines.py
- cfme/services/requests.py
- cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/infrastructure/test_vm_clone.py
We got some bugs related to nil deference on provisioning request dialog.
This PR is adding checks to existing tests. These checks are doing clicking trough the request tabs to verify they do display fine.
{pytest: cfme/tests/test_foo_file.py -v cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py cfme/tests/infrastructure/test_provisioning_dialog.py cfme/tests/infrastructure/test_vm_clone.py}
cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init[openstack-13] PASSED
The cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py/test_provision_cloud_init[ec2] seems to be failing because Fedora image is not present on the EC2. It can be fixed in yamls.
> [1LP][RFR] Cover provisioning issues

- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/utils/appliance/__init__.py
Another piece to saga about stabilization of the db restore tests.
* There was a PR 9959, but more has to be done to see more tests running in release runs as EC2 is disabled on these. 
* Also, some tests were still quite flaky. The problem is that the API is probably handled by other process/thread then the web-ui and we may get HTTP 503 while the web UI might be already loaded and responding with HTTP 2xx.
I believe this PR, greatly reduces the problem by blocking until the API responds with some OK result. The API client object cached in the appliance had to be invalidated.
The errors currently on the PRT are not related. Related issue is an exception saying HTTP 503.
> [1LP][RFR] Continue swapping EC2 with OpenStack and fix HTTP 503 issues.

- cfme/tests/configure/test_remote_server_tabs.py
Updated test_remote_server_advanced_config to remove the module-level fixtures and use the existing fixture distributed_appliances.
{{ pytest: -v --long-running cfme/tests/configure/test_remote_server_tabs.py }}
> [1LP][RFR] Use distributed_appliances fixture in test_remote_server_advanced_config

- cfme/tests/infrastructure/test_tenant_quota.py
This PR makes some changes to quota tests, including:
1.) Renamed fixtures for readability and clarity:
```
roottenant -> root_tenant
set_roottenant_quota -> set_root_tenant_quota
check_hosts -> migration_destination_host
```
2.) Use create_vm_modscope fixture when provisioning VMs.
3.) Use f-strings instead of format().
One of the tests is failing in PRT, but it appears to be due to an intermittent bug in CFME that I haven't been able to reproduce reliably.
{{ pytest: -v --long-running cfme/tests/infrastructure/test_tenant_quota.py }}
> [1LP][RFR] Quota test fixes

- cfme/automate/dialogs/dialog_element.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_dialog_field_associations }}
> [1LP][RFR] Automating dialog field associations dialog test

- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud_infra_common/test_genealogy.py
> [1LP][RFR] Update test_vm_genealogy_detected via summary on vcenter

- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_service_customer_bz.py
{{pytest: cfme/tests/services/test_service_customer_bz.py::test_dialog_with_dynamic_expression --long-running }}
> [1LP][RFR] Adding dynamic dialog test with ownership

- cfme/v2v/migration_plans.py
{{ pytest: cfme/tests/v2v/test_csv_import.py -k "test_csv_valid_vm" --use-provider rhv-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
vm is_display is failing due to the below line in is_display code
>> len(self.browser.elements(".//div[contains(@class,'spinner')]")) == 0)
So, this line make sure that the vm loading spinner gets over which means vm data gets loaded in vm table.
However, in current upstream build, the background card view has been replaced with list view (**As shown in attached screenshots**), Due to which Now the spinner is available in background as well if multiple plans is in progress.
Now the issue is with is_display code -->  .//div[contains(@class,'spinner')]")) , It consider the background spinner as well in …
> [1LP][RFR] Fixing the vm is_display

- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dynamicdd_dialogelement.py::test_load_service_dialog --long-running }}
removed `test_dd_multiselect_default_element_is_shouldnt_be_blank_when_loaded_by_another_element` test. we already have automation for multiselect dropdown
> [1LP][RFR] Automating service dialog load test

- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py --use-template-cache --provider-limit 2 --use-provider rhv43 --use-provider vsphere67-ims -k test_multi_host_multi_vm_migration}}
510 - PASS
511 - PASS
> [RFR] Fix test_multi_host_multi_vm_migration

- cfme/common/__init__.py
- cfme/common/host_views.py
- cfme/common/provider_views.py
- cfme/infrastructure/host.py
- cfme/infrastructure/provider/__init__.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_providers.py
- __Enhancement__ for a common function to do the navigation, checking of items, and selecting compare item in dropdown for comparison of hosts tests. This is the first phase of development of common compare functionality for entities. I'll be extending to other entity types (and probably implementing the functionality via class methods etc.) in future PRs. Existing Host compare tests have been updated to use compare_hosts.
{{ pytest: --long-running --use-provider rhv43 cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_navigation_after_download_from_compare cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_compare cfme/tests/infrastructure/test_providers.py::test_compare_templates }}
> [1LP][RFR] Add compare_hosts function to handle navigation and checking compare items 

- cfme/v2v/migration_plans.py
- widgetastic_manageiq/__init__.py
As this feature is not yet available with downstream, I have check the functionality of this PR on upstream appliance and it successfully able to select warm migration and able to schedule the cut-over, Please find attached screenshot for the same.
{{ pytest: cfme/tests/v2v/test_v2v_migrations_ui.py -k "test_migration_with_no_conversion" --use-provider rhv-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR] Adding warm migration support

- cfme/fixtures/v2v_fixtures.py
- cfme/tests/v2v/test_v2v_migrations_ui.py
re-ordering fixtures(mapping_data_vm_obj_mini, delete_conversion_hosts) used in test. As for OSP the mapping widget throws error due to a warning window pop's up as shown in attached snap.
It really does not matter for this test if we create mapping before or after deleting the conversion host, what matter's is the migration should start after deletion of conversion host.
Now the order would be like
1. Create Mapping
2. Delete Conversion hosts
3. Start Migration
Expected result---> Migration should fail as appliance has no conversion hosts.
Note: I have increase the wait_for_view from default 10s to 30s as the PRT most of the time failing due to time out as it takes >10s for navigate_to(provider, 'Edit').
{{ pytest: …
> [1LP][RFR] Fixing test migration_with_no_conversion

- cfme/utils/dockerbot/dockerbot.py
- cfme/utils/dockerbot/pytestbase/Dockerfile
- cfme/utils/dockerbot/sel_container.py
- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
- requirements/template_scanned_imports.txt
The structure of the library changed significantly, thus dockerbot needed significant changes
We no longer need to process info from inspect, and the interface for creating an running containers has completely changed.
I moved some of the logging around, and changed the logic to accommodate the docker API changes.
NOTE: 
I stopped short of updating the dockerfile for the pytest container.  It needs to be rewritten to use quickstart, but that is out of scope of trying to update our docker dependency.
The DockerInstance changes can be verified by running `miq-selenium-container`
> [1LP][RFR] Update docker-py 1.10 to docker 4.2

- cfme/tests/control/test_actions.py
{{pytest: ./cfme/tests/control/test_actions.py -k "test_action_stop_virtual_machine_after_starting or test_action_suspend_virtual_machine_after_starting" --long-running -v}}
> [1LP][RFR] added blocker marker

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_simulation.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_auth_manual.py
No test run required just adding BZ coverage
> [1LP][RFR] Adding BZ coverage

- cfme/tests/configure/test_access_control.py
> [1LP][RFR] - Removing duplicate test

- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_providers.py
…ked test test_infrastructure_hosts_navigation_after_download_from_compare
- __Updating tests__ markers so all covered BZs are included in automates and remove outdated blockers
- __Fixing test__ test_infrastructure_hosts_navigation_after_download_from_compare to support recent changes. This test was and is blocked by BZ.
{{ pytest: --long-running --use-provider rhv43 cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_compare }}
> [RFR] Update automates and blocker markers and fix a small bug

- cfme/fixtures/v2v_fixtures.py
Adding *appliance.wait_for_api_available()* after re-starting the evm service to  make sure API should also work.
> [1LP][RFR] Fixing API 500 error

- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_db_auth.py
__adding_test__ Test to login new user and user having password capital case character in the existing testcase and removed `test_authorized_users_can_login`
{{pytest: cfme/tests/integration/test_db_auth.py -k "test_db_user_pwd"  --long-running -v}}
> [1LP][RFR] - Adding test to login new user using upper case password in the existing testcase

- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/candu/test_candu_manual.py
Manual Coverage for this BZ's
https://bugzilla.redhat.com/show_bug.cgi?id=1807928
https://bugzilla.redhat.com/show_bug.cgi?id=1776684
> [1LP][NOTEST][RFR] Add test coverage for Bugzila

- cfme/test_requirements.py
- cfme/tests/candu/test_candu_manual.py
- cfme/tests/storage/test_manager.py
- cfme/tests/storage/test_volume.py
- cfme/tests/storage/test_volume_backup.py
- cfme/tests/storage/test_volume_snapshot.py
- cfme/tests/storage/test_volume_types.py
Signed-off-by: Gaurav Talreja <gtalreja@redhat.com>
1. Own all test cases related to Storage
2. Own 2-tests related to CandU
> [1LP][RFR] Change FA assignee for Storage

- cfme/tests/cli/test_appliance_console.py
__adding_test__ test to check error on appliance console on menu page
{{pytest: cfme/tests/cli/test_appliance_console.py -k "test_appliance_console_menubar" -v}}
> [1LP][RFR] - checking error on appliance console

- cfme/common/host_views.py
- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_host.py
- __Adding tests__ for host edit to support cancel of edit and also navigating away before saving updates. The navigating away case will cover customer BZ 1634794.
{{ pytest: --use-provider complete --long-running cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_crud }}
> [1LP][RFR] Add support for create and nav_away to Host.update() and test_infrastructure_hosts_crud

- cfme/tests/cli/test_appliance_update.py
Merged the manual test with test_yum_update. New test was failing because of warnings about .rpmnew files. But it doesn’t look like a problem, admins should see this warning to check their config files... So this kind of warning is filtered from yum update output.
{{pytest: cfme/tests/cli/test_appliance_update.py::test_update_yum --long-running}}
> [1LP][RFR] automate test_update_yum_no_errors

- cfme/common/vm.py
- cfme/fixtures/service_fixtures.py
- cfme/rest/gen_data.py
- cfme/tests/services/test_myservice.py
1. test_retire_multiple_services
1. Add teardown to `catalog_item` fixture.
2. enhance `services` helper function to take a service_template.
3. Remove unnecessary code from helper functions in gen_data.py.
{{ pytest: cfme/tests/services/test_myservice.py -k "test_retire_multiple_services" --long-running}}
> [1LP][RFR] Automate: test_retire_multiple_services

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_dynamicdd_dialogelement.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_dropdown_refresh_load -svvv }}
automated above one and removed duplicate tests
> [1LP][RFR] Automating dynamic dialog refresh field

- cfme/tests/cloud/test_providers.py
The marker was wrong, missed in code review.
> [1LP][RFR] Fix meta marker

- cfme/tests/infrastructure/test_vm_retirement_rest.py
- cfme/tests/intelligence/reports/test_import_export_reports_widgets.py
- cfme/tests/webui/test_general_ui.py
- __Fixing__ 
1. Tests related to VM retirement
2. Adding `selector` to `test_add_provider_button_accordion` so that it doesn't extra tests.
3. `test_reports_invalid_file` which was failing because error message changed.
- __Removing__
1. Blockers from BZs
2. test_ui_pinning_after_relog and test_ui_notification_icon
{{ pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py cfme/tests/intelligence/reports/test_import_export_reports_widgets.py::test_reports_invalid_file -vvv }}
> [1LP][RFR] Fix VM retirement tests and test cleanup

- cfme/fixtures/nelson.py
- cfme/fixtures/ui_coverage.py
- cfme/fixtures/xunit_tools.py
- cfme/markers/manual.py
- cfme/markers/perf.py
- cfme/markers/polarion.py
Just making things a bit more consistent, even though the parameters are unused.
> [1LP][RFR] Update pytest hook parameters

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/tests/services/test_catalog_item.py
- __Automate tests__ 
1. test_service_select_tenants
1. Add widgets for `additional_tenants`, `currency`, `zone`, `price_per_month`.
2. Add methods to add 'Additional Tenants`.
3. Enhance `CloudInfraCatalogItem.fill_dict` and `NonCloudInfraCatalogItem.fill_dict` to work when no catalog is provided while creating catalog item.
{{ pytest: cfme/tests/services/test_catalog_item.py -k "test_service_select_tenants" }}
> [1LP][RFR] Automate: test_service_select_tenants

- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py -k "test_single_vm_migration_power_state_tags_retirement"  --use-provider osp13-ims  --use-provider vsphere67-ims --provider-limit 2 }}
> [1LP][RFR] Fix the test for OSP

- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_auth_manual.py
__adding_test__ test to create group if at least one category **show_in_console** value is **No**
{{pytest: cfme/tests/configure/test_access_control.py -k "test_create_group_console_no" --long-running -v}}
> [1LP][RFR] Test to create group

- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/distributed/test_appliance_replication.py
Automates the manual `test_server_role_failover[role]` tests as a single test named `test_server_role_failover`.
{{pytest: cfme/tests/distributed/test_appliance_replication.py --long-running -k test_server_role_failover -v }}
> [1LP][RFR] Automate test_server_role_failover

- cfme/tests/intelligence/test_chargeback_manual.py
Parametrized manual chargeback report tests instead of having one test method per resource (cpu, memory, etc.), report period (weekly, monthly, etc.) and so on. Some of these manual tests partially overlap with the automated tests, and will be dealt with in a later PR.
> [1LP][RFR] Manual chargeback test cleanup and parametrization

- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_auth_manual.py
- cfme/tests/services/test_service_rbac.py
- cfme/tests/test_login.py
Changing FA owner of RBAC test cases,
> [1LP][RFR][NOTEST]- changing FA owner

- cfme/fixtures/v2v_fixtures.py
- widgetastic_manageiq/__init__.py
TC is failing due to ITEM_SCHEDULE_BUTTON_LOCATOR button with below error
NoSuchElementException: Message: Could not find an element './div[contains(@Class,"list-view-pf-actions")]//button[text()="Schedule" or text()="Unschedule"]'
This PR will fix the locator issue.
Some time the volume deletion as ceph side failed due to race condition which causes the whole TC  to fail though the cleanup is not under the actual test scope. 
This PR except the exception here for such race condition. 
{{ pytest: cfme/tests/v2v/test_v2v_schedule_migrations.py -k "test_schedule_migration" --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR] Adding exception for volume cleanup and Fixing locator for schedule_migration test

- cfme/tests/v2v/test_v2v_migrations_ui.py
The Test case was failing as the resources flavor and security group are not available to the cluster.
The Test case is to test the custom attribute flavor and security group by providing a new value for these params other than the default one.
*security-group:*
default --> provider.data.security_groups.admin[0]
custom value --> provider.data.security_groups.admin[1] 
*flavor*
default -->  provider.data.flavors[0]
custom value --> provider.data.flavors[1]
As per TC requirement, we are not required to change the cluster, however in TC cluster gets changed from "admin" to "on-qa" , However the above security-group and flavor is a part of "admin" project and not available in on-qa cluster, This was the main reason for TC failure.
This PR fixing …
> [1LP][RFR] Fixing TC v2v_custom_attribute

- cfme/fixtures/provider.py
Updated the pytest_fixture_setup hook for the provider fixture, to look more like pytest's hook. See pytest-dev/pytest@c9a0881 for the relevant pytest commit that introduced resolve_fixture_function(), which I've updated our hook to use as well.
Also, the iteration over the test's markers in this hook only needed the fixture_name key, and not the associated mark value, so I've removed the call to items().
{{ pytest: -vvv --long-running --use-provider vsphere67-nested cfme/tests/cloud_infra_common/test_retirement.py }}
> [1LP][RFR] Use resolve_fixture_function in provider fixture setup

- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_auth_manual.py
{{pytest: cfme/tests/configure/test_access_control.py -k "test_select_edit_group" -v}}
> [1LP][RFR] - Test to check edit option for existing group

- cfme/tests/integration/test_db_auth.py
- cfme/tests/test_login.py
{{pytest: cfme/tests/integration/test_db_auth.py -k "test_db_user_pwd" --long-running -vv}}
> [RFR] - user login with special char password

- cfme/tests/test_appliance.py
Adding customer case coverage
{{ py.test: -v cfme/tests/test_appliance.py::test_appliance_top_output_log --use-provider complete }}
> [RFR] Cover 1749494

- cfme/tests/services/test_dialog_element_in_catalog.py
1. test_dynamic_dialogs_on_service_request
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py -k test_dynamic_dialogs_on_service_request -svvv }}
> [RFR] Automate: test_dynamic_dialogs_on_service_request

- cfme/tests/configure/test_paginator.py
Remove configuration paginator tests for pages that no longer exist in 5.11.
{{ pytest: -vv cfme/tests/configure/test_paginator.py }}
> [1LP][RFR] Remove paginator tests that are no longer valid in 5.11

- cfme/test_framework/sprout/client.py
- cfme/utils/template/base.py
- cfme/utils/template/rhevm.py
- cfme/utils/version.py
- conf/cfme_data.yaml.template
- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
Requires:
- ~~https://github.com/RedHatQE/miq_version/pull/29~~ (Merged, 0.4.0)
- cfme-qe-yamls/merge_requests/926
> [WIPTEST] Update miq_version imports

- cfme/scripting/quickstart/system.py
- quickstart setup check for os version adding fedora 31 and 32 openssl.
- I was trying gh-action and found that ubuntu 18.04 need openssl. I was just separating two PRs as it will proposal.
> [RFR] openssl in quickstart

- cfme/rest/gen_data.py
- cfme/tests/infrastructure/test_vm_rest.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
1. `cfme.rest.gen_data.vm` to take kwargs and a custom name.
2. Automate : test_database_wildcard_should_work_and_be_included_in_the_query
{{ pytest: cfme/tests/infrastructure/test_vm_rest.py -k "test_database_wildcard_should_work_and_be_included_in_the_query" -svvv }}
> [RFR]Automate: test_database_wildcard_should_work_and_be_included_in_the_query

- cfme/tests/cloud/test_cloud_timelines.py
Block tests failing due to https://github.com/ManageIQ/manageiq-providers-amazon/issues/620
{{ pytest: --use-provider ec2west cfme/tests/cloud/test_cloud_timelines.py }}
> [RFR] Block EC2 timelines tests, remove old BZ

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/dashboard.py
- cfme/intelligence/chargeback/__init__.py
- cfme/intelligence/reports/__init__.py
- cfme/intelligence/reports/reports.py
- cfme/intelligence/rss.py
- cfme/intelligence/timelines.py
- cfme/tests/intelligence/reports/test_crud.py
The 'Cloud Intel' navigation option was changed to 'Overview' in 5.11. Now that only 5.11 tests are being run, the version-specific logic for this name change has been removed.
> [1LP][RFR] Remove version logic for Overview navigation name

- widgetastic_manageiq/__init__.py
In 5.11.6, some locators gets changed and migration In_progress is visible as list where as in earlier version it listed as progress-bar
Further, in earlier version in progress-bar, there was no spinner visible, however in 5.11.6, the spinner visible on list.
This PR fix those issue to resolve multiple TC failures.
{{ pytest: cfme/tests/v2v/test_post_migrations.py  -k  "test_migration_post_attribute"  --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 -v }}
> [1LP][RFR] Fixing multiple jenkins failures

- cfme/infrastructure/virtual_machines.py
- cfme/tests/cloud_infra_common/test_genealogy.py
{{ pytest: cfme/tests/cloud_infra_common/test_genealogy.py -k "test_genealogy_comparison" --use-provider vsphere65-nested }}
> [1LP][RFR] Automate genealogy tests

- cfme/intelligence/reports/reports.py
- cfme/tests/intelligence/test_download_report.py
- cfme/tests/networks/test_sdn_downloads.py
- __Fixing__ 
1. `test_download_report` by fixing it for PDF.
- ___Enhancment__
1. Remove references older than 5.10 from `test_sdn_downloads.py` and `SavedReports.download()`.
2. Replace `SavedReportsDetailsView.download` from nested view to a dropdown widget.
3. Modify `SavedReports.download()` to print a logger message for PDF.
{{ pytest: cfme/tests/intelligence/test_download_report.py cfme/tests/networks/test_sdn_downloads.py -svvv}}
> [1LP][RFR] Fix test: test_download_pdf

- cfme/tests/cloud/test_providers.py
- cfme/tests/infrastructure/test_provider_discovery.py
- cfme/tests/infrastructure/test_providers.py
- cfme/tests/services/test_service_catalogs.py
- __Updating tests__
1. Removing reference to fixtures such as `has_no_cloud_providers` and `has_no_infra_providers` and replacing them with `has_no_providers`.
{{ pytest: cfme/tests -k "test_add_cancelled_validation_cloud or test_cloud_provider_add_with_bad_credentials or test_openstack_provider_has_dashboard or test_select_key_pair_none_while_provisioning or test_create_azure_vm_from_azure_image or test_public_images_enable_disable or test_api_port_max_character_validation_infra or test_providers_discovery or test_infra_provider_add_with_bad_credentials or test_infra_provider_crud or test_no_template_catalog_item" --long-running -svvv }}
> [1LP][RFR] Remove references to has_no_cloud_providers and has_no_infra_providers

- cfme/tests/configure/test_ntp_server.py
Made a few changes to the NTP server tests. The main changes are:
- Changed the test finalizers to make sure the server-level NTP servers are set to the ones defined in cfme_data, instead of being cleared out. If the server-level settings are cleared out, then the zone-level defaults are used, and those public NTP server defaults are not the ones we want to use.
- Moved NTP server dictionaries for empty / config / random / max char length values out of the tests and into fixtures.
{{ pytest: -vv cfme/tests/configure/test_ntp_server.py }}
> [1LP][RFR] NTP settings fixes

- cfme/utils/appliance/__init__.py
- cfme/utils/tests/test_providers.py
In `IPAppliance.managed_known_providers()`, the name comparison between known managed providers (taken from yaml data) and the providers present on the appliance consists of two checks:
- Exact name match
or
- Provider name from yaml is contained within the provider name from the appliance db.
```
if ems_name == prov.name:
found_cruds.add(prov)
break
elif prov.name in ems_name:  # config managers append e.g. 'Automation Manager'
found_cruds.add(prov)
break
```
This second comparison is intended to match on child providers, e.g., the network manager that exists for certain provider types. So, if the name of the yaml provider is 'azure_msdn', then it should be considered a match if the iteration over provider names from the db returns 'azure_msdn Network Manager' before getting to the base …
> [1LP][RFR] Fix to managed_known_providers name checking

- cfme/tests/v2v/test_v2v_manual.py
> [RFR] Add manual tests for v2v for bugs fixed in 5.11.5

- cfme/roles.py
- cfme/tests/configure/test_access_control.py
__adding_test__ Test to check `Edit Tags` option is present or not after clicking on **Policy** on VM details page
{{pytest: cfme/tests/configure/test_access_control.py  -k 'test_tags_manual_features' --long-running -v}}
> [1LP][RFR] - test to check "Edit Tags" option

- cfme/tests/cloud_infra_common/test_events.py
This test was always uncollected because the provider filter was incorrect. Fixed the filter to point to the correct `required_flags` instead of `required_fields`.
{{ pytest: -vv cfme/tests/cloud_infra_common/test_events.py }}
> [1LP][RFR] Fix provider filter on test_vm_create

- cfme/scripting/conf.py
When running `miq conf show-credential <provider key>`, a `KeyError` is raised if the provider has an endpoint defined in `cfme_data` with no `credentials` key. This is the case for OpenStack providers,  because the `events` endpoint does not have credentials.
This PR fixes the issue:
```
$ miq conf show-credential <openstack provider key>
default
password: XXXX
username: YYYY
events
No credentials defined for this endpoint.
```
> [1LP][RFR] [NOTEST] Fix KeyError in show-credential script

- cfme/tests/services/test_myservice.py
{{ pytest: cfme/tests/services/test_myservice.py -k "test_retire_multiple_services_on_date" --long-running}}
> [1LP][RFR] Automating retire multiple service on date

- cfme/tests/services/test_generic_service_catalogs.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
- widgetastic_manageiq/__init__.py
1. `test_timepicker_on_service_order` - this test automates `test_timepicker_should_show_date_when_chosen_once` and `test_timepicker_should_pass_correct_timing_on_service_order`
1. Add a new `TimePicker` widget to wt.manageiq which is inspired by wt.pf::DatePicker and used for TimePicker dialog element. Currently it can only pick date and not time.
{{ pytest: cfme/tests/services/test_generic_service_catalogs.py::test_timepicker_on_service_order -svvv }}
> [1LP][RFR]New test: test_timepicker_on_service_order

- cfme/tests/cloud_infra_common/test_power_control_rest.py
Fixed provider parametrization in test_power_control_rest.py so that the following uncollections no longer happen:
```
test_stop_vm_rest[satellite-6.2-small_template-from_detail] - Config Manager providers do not support this feature.
test_start_vm_rest[satellite-6.2-small_template-from_detail] - Config Manager providers do not support this feature.
test_suspend_vm_rest[satellite-6.2-small_template-from_detail] - Config Manager providers do not support this feature.
test_stop_vm_rest[satellite-6.2-small_template-from_collection] - Config Manager providers do not support this feature.
test_start_vm_rest[satellite-6.2-small_template-from_collection] - Config Manager providers do not support this feature.
test_suspend_vm_rest[satellite-6.2-small_template-from_collection] - Config Manager …
```
> [1LP][RFR] Fix provider filters in test_power_control_rest module

- cfme/tests/configure/test_access_control.py
- cfme/tests/integration/test_auth_manual.py
__adding_test__ test to check key pair able to see or not for custom user when tenant as Parent tenant and Child - tenant
{{pytest: cfme/tests/configure/test_access_control.py -k test_aws_keypair_list --long-running -v}}
> [1LP][RFR] - check Key Pair list using aws provider

- cfme/tests/infrastructure/test_snapshot.py
- __Adding test__ to automate manual test test_snapshot_link_after_deleting_snapshot
{{ pytest: cfme/tests/infrastructure/test_snapshot.py::test_snapshot_link_after_delete }}
> [1LP][RFR] Add test_snapshot_link_after_delete

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
- cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_dialog_field_to_static_field  }}
automated -> test_dynamic_dialog_field_to_static_field
removed few tests which are already covered in automation and also a few no need to test.
> [1LP][RFR] Adding new test dynamic dialog load

- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_host_manual.py
- __Adding tests__ for host tagging to replace manual test, test_host_tagging.
version1.2.3.
{{ pytest: cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_tagging }}
> [1LP][RFR] Add test_infrastructure_hosts_tagging

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dialog_dynamic_timepicker_date_format }}
> [1LP][RFR] Adding dynamic dialog time picker test

- cfme/tests/services/test_catalog_item.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
- cfme/tests/test_manual.py
{{pytest: cfme/tests/services/test_config_provider_servicecatalogs.py::test_change_ansible_tower_job_template  -svvvvv --use-provider ansible_tower_34 }}
> [1LP][RFR] Automating Ansible tower catalog change template

- cfme/tests/services/test_dialog_element_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_datepicker_in_service_request }}
- automated test_datepicker_in_service_request
- removed test_specific_dates_and_time_in_timepicker, its already covered on another test
> [1LP][RFR] Adding dialog datepicker on request details page 

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalogs_bundles.py
{{pytest: cfme/tests/services/test_service_catalogs_bundles.py::test_retire_service_and_bundle_vms  --long-running -svvvv }}
> [1LP][RFR] Automating retire bundle with multiple VM test

- cfme/fixtures/artifactor_plugin.py
Fixes issue where browser is started at the end of a test run that doesn't use the browser, if artifactor client is not set up. This probably only happens when running certain tests from the command line, so there's no PRT testing.
> [1LP][RFR] [NOTEST] Only run teardown hooks if artifactor client exists

- cfme/tests/intelligence/chargeback/test_resource_allocation.py
This PR makes several changes to the resource allocation chargeback tests. Important changes of note:
- Replace the GitHub blocker with the downstream BZ blocker now that it has been created.
- Create new `chargeback_vm` fixture to return the name of the chargeback VM from the provider data, instead of looking it up each time in the various fixtures / tests.
- Replace deprecated `pytest.yield_fixture` decorators with `pytest.fixture`.
- Move db query transactions into the transaction context. Previously, subqueries were defined within the context, but the actual queries were not executed within the context. 
- Also delete rows from the `vim_performance_states` table before capturing metrics data. Failure to do so could result in metrics data with the wrong provider id (if the provider …
> [1LP][RFR] Chargeback resource allocation fixes

- cfme/configure/configuration/region_settings.py
- cfme/tests/configure/test_tag.py
- __Adding test__ for importing tags from csv file to cover BZ 1792185.
{{ pytest:  --use-provider vsphere65-nested cfme/tests/configure/test_tag.py::test_import_tag }}
> [1LP][RFR] Create test_import_tag and implement fixtures and functions it needs

- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_snapshot.py
- __Updating tests__ to add automated coverage for test_snapshot_image_copies_system_info manual test. 
{{ pytest: --long-running cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot }}
> [1LP][RFR] Add comparison of OS data after revert to test_verify_revert_snapshot

- cfme/markers/env_markers/provider.py
- cfme/utils/tests/test_providers.py
The 'all' selector for the provider marker doesn't work when more than one provider of the same category, type, and version are selected for parametrization on a test. This PR fixes that behavior by including the selected provider's `key` attribute along with the category, type, and version.
`SHRIVER: updated Jun 23 2020 to include more than just the unit test for ALL`
{{ pytest: -vv --use-provider rhv4 --use-provider vsphere65-nested cfme/utils/tests/test_providers.py cfme/tests/infrastructure/test_providers.py }}
> [1LP][RFR] Fix provider parametrization for 'all' selector

- cfme/intelligence/reports/reports.py
- cfme/services/requests.py
- cfme/tests/cloud_infra_common/test_provisioning.py
- cfme/tests/configure/test_workers.py
- cfme/tests/infrastructure/test_vm_rest.py
- cfme/tests/integration/test_auth_manual.py
- cfme/tests/intelligence/reports/test_reports_manual.py
- cfme/tests/intelligence/test_optimization.py
- __Adding tests__ for feature X to cover cases Y and Z. They were implemented in product
version1.2.3.
1. `test_edit_vm` to add coverage for BZ(1833362).
2.  `test_openid_auth_provider` by adding coverage for BZ(1805914).
3. `test_generate_optimization_report` to add coverage for BZ(1714197) and delete duplicate test `test_optimization_reports`
4. `test_provision_from_template` by adding coverage for BZ(1830305).
5. `test_set_memory_threshold` by adding coverage for BZ(1810773).
- __Fixing tests__:
1. `test_provision_from_template` by fixing `cfme/services/requests.py::find_request()` that caused python3 `RuntimeError: dictionary keys changed during iteration` error.
{{ pytest: cfme/tests/infrastructure/test_vm_rest.py::test_edit_vm …
> [1LP][RFR] Add BZ and enhacement card coverage  

- cfme/tests/cloud/test_targeted_refresh.py
1. `test_ec2_targeted_refresh_floating_ip`
{{ pytest: cfme/tests/cloud/test_targeted_refresh.py::test_ec2_targeted_refresh_floating_ip -svvv }}
> [1LP][RFR] Automate: test_ec2_targeted_refresh_floating_ip

- cfme/tests/candu/test_nor_rightsize.py
Set case importance and manualonly for test_normal_operating_range and test_rightsize_recommendations tests.
> [1LP][RFR][NOTEST] Set caseimportance and manualonly for NOR / Right Sizing tests

- cfme/tests/control/test_compliance.py
1. `test_rest_vm_compliance_subcollection`
{{ pytest: cfme/tests/control/test_compliance.py -k "test_rest_vm_compliance_subcollection" -svvv }}
> [1LP][RFR] New test: test_rest_vm_compliance_subcollection

- cfme/rest/gen_data.py
- cfme/tests/control/test_rest_control.py
1. TestPolicyProfilesRESTAPI
1. Add `policy_profiles` helper function in cfme/rest/gen_data.py to create policy_profile via REST.
{{ pytest: cfme/tests/control/test_rest_control.py -k "TestPolicyProfilesREST" -svvv }}
> [1LP][RFR] Automate policy_profiles test for rest

- cfme/common/provider.py
This PR adds a helper function to `create_rest()` that will create the events endpoint for ceilometer if the OpenStack provider has one defined in `cfme_data`. Previously it was not created, so the event monitor worker threads never started.
{{ pytest: -vv --use-provider env-rhos13 cfme/tests/cloud/test_providers.py }}
> [1LP][RFR] Add ceilometer endpoint to create_rest()

- cfme/common/host_views.py
- cfme/infrastructure/host.py
- cfme/tests/infrastructure/test_host.py
- cfme/tests/infrastructure/test_host_manual.py
- __Adding test__ test_infrastructure_hosts_viewing to cover manual, test_host_viewing
{{ pytest: cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_viewing }}
> [1LP][RFR] Add test_infrastructure_hosts_viewing

- cfme/cloud/instance/azure.py
- cfme/cloud/instance/ec2.py
- cfme/cloud/instance/gce.py
- cfme/cloud/instance/openstack.py
- cfme/tests/cloud_infra_common/test_power_control_manual.py
- cfme/tests/distributed/test_appliance_replication.py
Automate the non-REST variants of `test_power_operations_from_global_region`, by adding all possible providers to existing test 
`test_replication_vm_power_control`, which previously only run against a virtualcenter provider. I've removed the use of the `register_events` fixture, because of various problems, including:
- event listener runs against the default appliance, not against the temp remote region appliance. It still works, since the provider and vm are set up on the default appliance too, but the event listener spams `cfme.log` every second, during the entire time it takes to configure the remote and global appliances.
- The OpenStack providers currently have a huge number of historical events that take over an hour to import into CFME when the provider is created.
{{ pytest: -vv …
> [1LP][RFR] Partial automation of test_power_operations_from_global_region

- cfme/cloud/provider/azure.py
- cfme/configure/configuration/system_schedules.py
Fixes
`
selenium.common.exceptions.NoSuchElementException: Message:     Could not find an element Locator(by='xpath', locator='.//div[contains(@Class, "bootstrap-select")]/button[normalize-space(@data-id)="log_protocol"]/..')
`
{{py.test: -v  --use-provider 'complete' --long-running cfme/tests/configure/test_schedule_operations.py::test_schedule_crud}}
> [1LP][RFR] Fix error caused by varying items on Schedules dialog depending on schedule type.

- cfme/base/__init__.py
- cfme/tests/configure/test_rest_config.py
1. Add `rest_api_entity` property for region.
2. Modify `settings_string` and `region_string` to return the correct value even when region description is not set to default.
1. `test_edit_zone` covering BZ(1805844)
{{ pytest: cfme/tests/configure/test_rest_config.py::test_edit_region -svvv}
> [1LP][RFR] New test:test_edit_zone

- cfme/utils/log.py
The loggers created via `cfme.utils.log.setup_logger` were hardcoded to have the `INFO` log level, ignoring any settings in `conf/env.local.yaml`. The associated file handlers do get created with the level from the yaml, but because the logger's level is fixed at `INFO`,  no `DEBUG` logging is possible. This PR uses the yaml settings when creating the logger too, so that settings like the following in `conf/env.local.yaml` will log debug statements in `cfme.log`.
```
logging:
level: DEBUG
[or]
logging:
cfme:
level: DEBUG
```
> [1LP][RFR] Fix setting logger level from config

- cfme/common/provider.py
- cfme/infrastructure/config_management/__init__.py
- cfme/infrastructure/config_management/ansible_tower.py
- cfme/tests/services/test_rest_services.py
- __Fixing__ 
1. Make `BaseProvider.setup()` work for Config Managers.
1. `test_create_from_template`
{{ pytest: cfme/tests/services/test_rest_services.py -k test_create_from_template --use-provider=complete -svvv }}
> [1LP][RFR] New test: test_create_from_template

- cfme/tests/intelligence/reports/test_metering_report.py
- cfme/tests/intelligence/reports/test_validate_chargeback_report.py
The upstream GH issue for Azure metrics capture, which was previously blocking chargeback tests, has been closed now that a downstream BZ has been created. This PR updates the blocker information for some chargeback / metering tests to point to the new BZ, so that the tests continue to be skipped. All tests in the PRT run should be skipped.
{{ pytest: -v --long-running --use-provider azure cfme/tests/intelligence/reports/test_metering_report.py cfme/tests/intelligence/reports/test_validate_chargeback_report.py }}
> [1LP][RFR] Add BZ blocker for Azure chargeback / metering tests

- cfme/tests/services/test_dialog_regex_validation_in_catalog.py
{{pytest: cfme/tests/services/test_dialog_regex_validation_in_catalog.py::test_dialog_element_regex_validation }}
> [1LP][RFR] Adding dialog text area regex validation test

- cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
- __Updating tests__
1. `TestCustomAttributesRESTAPI` to also test for hosts and setting provider selector to ONE, there is no need to test for every provider.
{{ pytest: cfme/tests/cloud_infra_common/test_custom_attributes_rest.py -k hosts -svvv --long-running }}
> [1LP][RFR] New test: custom_attributes subcollection for hosts

- cfme/tests/infrastructure/test_tenant_quota.py
The `quota_limit` fixture in `test_tenant_quota.py` was failing with a `ValueError` because it was trying to cast a float string into an `int`:
```
2020-06-30 12:14:34,544 [E] [cfme] @pytest.fixture
def quota_limit(root_tenant):
>       in_use_storage = int(root_tenant.quota["storage"]["in_use"].strip(" GB"))
E       ValueError: invalid literal for int() with base 10: '1014.65234375'
cfme/tests/infrastructure/test_tenant_quota.py:144: ValueError (cfme/fixtures/log.py:84)
```
This PR casts these strings to `float` instead.
{{ pytest: -v --use-provider vsphere67-nested -k test_quota_with_reconfigure_resize_disks cfme/tests/infrastructure/test_tenant_quota.py }}
> [1LP][RFR] Fix quota_limit fixture

- cfme/fixtures/depot.py
- cfme/tests/configure/test_log_depot_operation.py
- cfme/utils/appliance/__init__.py
- cfme/utils/net.py
- cfme/utils/ssh.py
There is an incident in our lab preventing the tests to pass as they cannot connect ssh. This happens only with certain sprout vm  provider. This was worked-around.
Test appeared to be wrongly trying to match appliance.server.sid as a zone id. I believe this is not correct. I made the tests passing by using the server's zone every time.
{{ py.test: -sv 'cfme/tests/configure/test_log_depot_operation.py::test_collect_multiple_servers' -v --use-provider 'complete'  --long-running cfme/utils/tests/test_connect_ssh.py cfme/tests/configure/test_proxy.py cfme/tests/cli/test_appliance_console_db_restore.py cfme/tests/infrastructure/test_snapshot.py::test_verify_revert_snapshot }}
There is one test failed with `[Errno 104] Connection reset by peer` which is the same failure I have seen before. Not …
> [RFR] Fix log collection tests.

- cfme/base/__init__.py
- cfme/base/ui.py
- cfme/configure/configuration/server_settings.py
- cfme/tests/configure/test_rest_config.py
1. Add `basic_information` to `ZoneSettingsView.zone`.
2. Add `rest_api_entity` property to Zone.
3. Remove `basic_information_values` method since it's not used anywhere.
1. TestZoneRESTAPI
2. TestServerRESTAPI
{{ pytest: cfme/tests/configure/test_rest_config.py -k "TestServerRESTAPI or TestZoneRESTAPI" -svvv }}
> [1LP][RFR] New test: TestZoneRESTAPI and TestServerRESTAPI

- cfme/tests/infrastructure/test_host.py
- __Updating tests__ in test_host.py to use host fixture where applicable.
{{ pytest: cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_tagging cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_crud  cfme/tests/infrastructure/test_host.py::test_add_ipmi_refresh cfme/tests/infrastructure/test_host.py::test_infrastructure_hosts_icons_states }}
> [RFR]Update applicable tests to use host fixture in test_host.py

- cfme/fixtures/cli.py
- cfme/tests/cloud_infra_common/test_retirement.py
- cfme/tests/distributed/test_appliance_replication.py
When using temp appliance fixtures, `navigate_to` from within the temp appliance's context manager will sometimes use the expected appliance, and sometimes instead it uses the default appliance.
Entering the temp appliance's context manager will push that appliance onto the ApplianceStack, and `navigate_to(provider, 'Details')` works, because `BaseProvider` inherits from `Navigatable`, which returns the current appliance from the stack when you get its `appliance` attribute.
Trying to navigate using an instance of a `BaseEntity`-derived class, on the other hand, will use the default appliance, because `BaseEntity`'s appliance property is always going to be the appliance for which the collection was created.
A few of the PRT tests errored out but are either non-multi-appliance retirement …
> [RFR] Fix navigation for temp appliance tests

- cfme/utils/appliance/implementations/common.py
- cfme/utils/appliance/implementations/ssui.py
- cfme/utils/appliance/implementations/ui.py
This PR resolves two deprecation warnings:
1.) Replace deprecated use of `level="warn"` with `level="warning"` in `CFMENavigateStep`'s `log_message()` method:
```
cfme/tests/cloud_infra_common/test_retirement.py::test_set_retirement_date[ec2-no_warning]
/XXX/cfme/utils/appliance/implementations/ui.py:527: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
getattr(logger, level)(str_msg)
```
2.) Replace deprecated use of `selenium.switch_to_alert()` with `selenium.switch_to.alert()` in `HandleModalsMixin`'s `get_alert()` method:
```
cfme/tests/cloud_infra_common/test_retirement.py::test_set_retirement_date[ec2-no_warning]
/XXX/cfme/utils/appliance/implementations/common.py:38: DeprecationWarning: use driver.switch_to.alert instead
return …
```
> [RFR] Fix deprecation warnings for switch_to_alert() and log_message()

- cfme/utils/appliance/implementations/common.py
In PR https://github.com/ManageIQ/integration_tests/pull/10237 the fix to replace deprecated `switch_to_alert()` with the property method `switch_to.alert` incorrectly used `switch_to.alert()`, which led to errors like the following when a popup / alert is found:
```
try:
>           return self.selenium.switch_to.alert()
E           TypeError: 'Alert' object is not callable
cfme/utils/appliance/implementations/common.py:38: TypeError (cfme/fixtures/log.py:84)
```
This PR makes the fix and includes a PRT test that ran into this problem.
{{ pytest: -v -k test_zone_crud cfme/tests/configure/test_zones.py }}
> [RFR] Fix to switch_to.alert call

- cfme/tests/automate/test_automate_manual.py
- cfme/tests/configure/test_access_control.py
Removing test as they have  below reasons:
**test_vm_naming_number_padding** Have WON'T fix BZ attach
**test_ssui_group_switch** No BZ and large effort needs
> [1LP][RFR][NOTEST] - Removing test

- cfme/fixtures/vm.py
The method called in the VM fixture to process the polarion docblocks assumes that the session cache attributes have already been set
A call to set_cache will make sure that they actually are created, avoiding an AttributeError during collection
```
pytest --collect-only --dummy-appliance -m 'requirement.ansible'
<redacted>
INTERNALERROR>   File "/home/setup/repos/integration_tests/cfme/fixtures/vm.py", line 30, in pytest_collection_finish
INTERNALERROR>     process_json_data(session, session.items)
INTERNALERROR>   File "/home/setup/repos/integration_tests/.cfme_venv/lib64/python3.7/site-packages/pytest_polarion_collect/utils.py", line 351, in process_json_data
INTERNALERROR>     if not (all_items or in_test_dir(str(item.fspath), session._test_dirs_cache)):
INTERNALERROR> AttributeError: …
```
> [1LP][RFR] Fix AttributeError in pytest_polarion_collect

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_dynamic_dropdown_auto_refresh_load }}
> [1LP][RFR] Automating ssui/ui dynamic refresh dialog test

- requirements/frozen.txt
- requirements/frozen_docs.py3.txt
The new version fixes:
```
File "/home/jhenner/work/miq/origin_master/.cfme_venv3/lib64/python3.7/site-packages/wait_for/__init__.py", line 170, in wait_for
logger.debug("Started %(message)r at %(time)", {'message': message, 'time': st_time})
```
> [1LP][WIP] Bump wait_for

- cfme/tests/cloud_infra_common/test_power_control_manual.py
- cfme/tests/distributed/test_appliance_replication.py
This PR automates testing of VM power control via REST from the global appliance in a multi-region configuration.
{{ pytest: --use-provider complete --long-running -k test_replication_vm_power_control cfme/tests/distributed/test_appliance_replication.py }}
> [1LP][RFR] Automate VM power control from global appliance via REST

- cfme/fixtures/vm.py
- cfme/infrastructure/virtual_machines.py
- cfme/tests/infrastructure/test_vm_reconfigure.py
- __Fixing__
1. `InfraVmReconfigureView.is_displayed` to work when reconfiguring multiple VMs.
1. test_reconfigure_vm_vmware_multiple
-__Deleting tests__
1. test_reconfigure_vm_vmware_sockets_multiple
2. test_vm_reconfigure_from_global_region
3. test_reconfigure_add_disk_cold_controller_sas
4. test_reconfigure_add_disk_cold
{{ pytest: cfme/tests/infrastructure/test_vm_reconfigure.py::test_reconfigure_vm_vmware_multiple --use-provider=vsphere67-nested --long-running  -svvv }}
> [RFR] New test: test_reconfigure_vm_vmware_multiple

- cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
We can not rely on get_progress_percent as it won't reflect real-time value on GUI and causing the TC to fail, We had a discussion for the same with eng team, some time back and decided to go with time elapsed process during disk migration. We have followed the same with cancel migration test case also. 
{{ pytest: cfme/tests/v2v/test_v2v_migrations_single_vcenter.py -k "test_migration_restart" --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 }}
> [1LP][RFR] fixing the test_migration_restart TC

- cfme/configure/configuration/system_schedules.py
- cfme/fixtures/automate.py
- cfme/tests/automate/test_automate_manual.py
- cfme/tests/automate/test_method.py
- cfme/tests/configure/test_schedule_operations.py
- widgetastic_manageiq/__init__.py
__adding_test__ Adding test to check scheduler working or not more than one time
{{pytest: cfme/tests/automate/test_method.py::test_automate_task_schedule cfme/tests/configure/test_schedule_operations.py --long-running -v}}
> [1LP][RFR] - Test to check schedule task more than one time

- cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: cfme/tests/ssui/test_ssui_service_catalogs.py::test_ssui_disable_dashboard --long-running -svv }}
> [1LP][RFR] Automating disable ssui dashboard from Role

- cfme/tests/automate/test_service_automate.py
- cfme/tests/configure/test_access_control.py
- Adding BugZilla coverage 
- Removing coverage of **test_service_retire_automate** because BZ closed by marking NOTABUG
> [NOTEST][RFR] adding BZ coverage and cleanup tcs

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/tests/services/test_service_catalogs_multi_region.py
This PR automates several of the manual tests in `test_service_provision_retire_from_global_region`:
- Original list, all manual:
```
<Function test_service_provision_retire_from_global_region[AMAZON-remote-ViaREST]>
<Function test_service_provision_retire_from_global_region[AMAZON-remote-ViaUI]>
<Function test_service_provision_retire_from_global_region[ANSIBLE-remote-ViaREST]>
<Function test_service_provision_retire_from_global_region[ANSIBLE-remote-ViaUI]>
<Function test_service_provision_retire_from_global_region[TOWER-remote-ViaREST]>
<Function test_service_provision_retire_from_global_region[TOWER-remote-ViaUI]>
<Function test_service_provision_retire_from_global_region[AZURE-remote-ViaREST]>
<Function test_service_provision_retire_from_global_region[AZURE-remote-ViaUI]>
<Function …
```
> [1LP][RFR] Automate multi-region service retirement tests

- cfme/fixtures/v2v_fixtures.py
This PR will fix the timeout failure for conversion host configuration.
~~~~~~~~
TimedOutError
b"Could not do 'Waiting for conversion configuration task to be finished'
~~~~~~~~~~
4 minutes is a very marginal limit for the time taken by the ansible-playbook to configure the conversion host. So I have increase the max limit to 10 minutes, though it keeps checking the status at every 3 seconds.
{{ pytest: cfme/tests/v2v/test_conversion_host_ui.py -k "test_add_conversion_host_ui_crud" --use-provider osp13-ims --use-provider vsphere67-ims --provider-limit 2 }}
Note: **Please ignore the PRT result, as in 5.11.7 we hit a major bug in configuring the conversion hosts:
https://bugzilla.redhat.com/show_bug.cgi?id=1857523
I have tested it locally by …
> [1LP][RFR] Fixing conversion host timeout issue

- cfme/tests/cloud_infra_common/test_retirement.py
This PR removes the blocker for https://bugzilla.redhat.com/show_bug.cgi?id=1839770 from `test_vm_retirement_from_global_region`.
PRT errors aren't related to this test.
{{ pytest: -vv -k test_vm_retirement_from_global_region --use-provider complete --long-running cfme/tests/cloud_infra_common/test_retirement.py }}
> [RFR] Unblock test_vm_retirement_from_global_region

- cfme/tests/configure/test_ntp_server.py
Now that a fix is available for https://bugzilla.redhat.com/show_bug.cgi?id=1832278 , this PR removes the workaround in `test_ntp_server_check` that removes the default `pool` config value in `chrony.conf`.
{{ pytest: -vv -k test_ntp_server_check cfme/tests/configure/test_ntp_server.py }}
> [RFR] Remove workaround for BZ 1832278 in test_ntp_server_check

- cfme/tests/test_server_manual.py
This PR removes `test_external_database_appliance` from `cfme/tests/test_server_manual.py`, because it's already automated in `cfme/tests/distributed/test_appliance_replication.py`.
> [RFR][NOTEST] Remove duplicate test_external_database_appliance

- cfme/base/ui.py
- cfme/modeling/base.py
- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/distributed/test_appliance_replication.py
Automate `test_distributed_delete_offline_worker_appliance` as `test_distributed_delete_appliance`.
{{ pytest: -vv -k test_distributed_delete_appliance --long-running cfme/tests/distributed/test_appliance_replication.py }}
> [1LP][RFR] Automate test_distributed_delete_offline_worker_appliance

- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
{{pytest: cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py -k "test_generic_object_button_delete_multiple" -v}}
> [RFR] Added two button fixture and automated manual test

- cfme/common/vm.py
__Fixing__ VM cleanups. `lambda` was used with attribute access where a call was intended. Fixed by just sending the method (attribute) to the `wait_for` instead of making the `lambda`.
{{py.test: -sv cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_additional_volume --long-running --use-provider complete }} 
Without this:
```
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_additional_volume[openstack-13] PASSED                                                                         [100%]
cfme/tests/cloud_infra_common/test_provisioning.py::test_provision_with_additional_volume[openstack-13] ERROR                                                                          [100%]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> …
```
> [1LP][RFR] Fix clenaups of VMs.

- cfme/tests/automate/test_domain.py
- cfme/tests/automate/test_git_import.py
- cfme/tests/test_login.py
Fixed log in negative testcase
{{pytest: cfme/tests/test_login.py::test_bad_password cfme/tests/automate/test_git_import.py::test_git_refresh_with_renamed_yaml cfme/tests/automate/test_domain.py::test_existing_domain_child_override --long-running -v}}
> [1LP][RFR]- fixing test

- cfme/fixtures/ansible_tower.py
If the type of the dropdown values is not defined, the dialog behaves
weirdly. For example it doesn't make the Submit button available if something is
selected. Also when nothing is touched when Ordering the catalog using this
dialog, Submit btn is enabled.. This quite the oposite how it should work.
This is surely a problem of CFME backend -- it shouldn't allow us to not define
a dropdown without a value type defined. But this cannot happen trough
the UI so perhaps not worthy fixing.
There is probably no test that is broken. I checked the catalog ordering by hand after the test prepared everything
`cfme/tests/services/test_config_provider_servicecatalogs.py::test_order_tower_catalog_item[ansible_tower-3.5-template_survey_job-v1]`
Note that …
> Fix dialog dropdown weird behavior.

- cfme/tests/test_db_migrate.py
#10266 didn't include static IDs update.
> [RFR] Update IDs for test_db_migrate

- cfme/tests/cloud/test_cloud_timelines.py
The testcases didn't have `provider` in their fixtures, resulting in un-collection.
> [1LP][RFR] Add missing provider fixture for test_cloud_timelines

- cfme/tests/containers/test_projects_dashboard.py
Using mutable as default arg value is dangerous as it is evaluated once, when function is being created (module loaded).
This value is preserved between each function calls and when modified, the subsequent calls will use the new state of that default object.
```
In [2]: def foo(aaa=[]): 
...:     aaa.append(3) 
...:     return aaa 
...:                                                                                                                                                                                       
In [3]: a=foo()                                                                                                                                                                               
In [4]: a …
```
> [1LP][RFR] Fix dangerous arg value

- cfme/tests/configure/test_access_control.py
**Test to check listed OCP providers and pods when we assigned provider filter to new user**
{{pytest: cfme/tests/configure/test_access_control.py::test_host_clusters_pod_filter   -sss -vvvvv --long-running --use-provider  ocp-311-hawk --provider-limit 2 --use-provider ocp-39-hawk  }}
> [1LP][RFR] Test OCP provider filter on user 

- cfme/common/provider.py
- cfme/containers/provider/__init__.py
- cfme/tests/containers/test_container_provider_crud.py
1. `BaseProvider.create_rest` method to work for Openshift provider.
2. Make `BaseProvider.setup` completely rely on `BaseProvider.create_rest`.
1. `test_container_provider_crud_rest` to test the enhancement.
1. Add `ipaddress` and `hostname` methods from `CloudInfraProviderMixin` to `ContainersProvider` to make `create_rest` work.
{{ pytest: cfme/tests/containers/test_container_provider_crud.py::test_container_provider_crud_rest cfme/tests/cloud_infra_common/test_rest_providers.py::test_create_provider --use-provider={complete,ocp-39-hawk}  }}
> [1LP][RFR] Enhance create_rest for OCP

- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/distributed/test_appliance_replication.py
{{ pytest: -vv --long-running cfme/tests/distributed/test_appliance_replication.py::test_distributed_zone_delete_occupied }}
> [1LP][RFR] Automate test_distributed_zone_delete_occupied

- cfme/tests/infrastructure/test_provisioning_dialog.py
I believe we have no way to provision on ansible tower provider, thus I am removing tests for that using provider filters.
To be used with https://gitlab....cfme-qe-yamls/-/merge_requests/934/diffs
> [RFR] Remove provisioning schedule test running against ansible tower.

- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_dialog_element_in_catalog.py::test_navigate_details_dialog_view }}
- automated test_edit_dialog_1834219
- removed already covered and non-required test
> [1LP][RFR] Automating dialog test details view

- cfme/dashboard.py
- cfme/fixtures/service_fixtures.py
- cfme/services/myservice/ssui.py
- cfme/services/myservice/ui.py
- cfme/tests/intelligence/test_dashboard.py
- cfme/tests/test_replication.py
This PR removes the `Kebab` class definition from `cfme.dashboard` and uses the `widgetastic_patternfly` one. There are also a few small fixes to fixtures / tests that were failing when trying to run PRT.
{{ pytest: -vv --long-running --use-provider complete -k 'test_widgets_operation or test_service_start' cfme/tests/ssui/test_ssui_myservice.py cfme/tests/intelligence/test_dashboard.py }}
> [RFR] Use widgetastic_patternfly Kebab

- cfme/tests/configure/test_workers.py
- cfme/tests/test_server_manual.py
- cfme/utils/log_validator.py
This PR automates `test_verify_purging_of_old_records`. The test updates the appliance's advanced settings so that all of the purging intervals are set to 5 minutes instead of the default of 1 day, then monitors `evm.log` on the appliance for up to 10 minutes and passes if all of the purge timers have run.
{{ pytest: -vv -k test_verify_purging_of_old_records cfme/tests/configure/test_workers.py }}
> [RFR] Automate test_verify_purging_of_old_records

- cfme/tests/services/test_request.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_request.py::test_user_view_service_request_details --long-running -svv }}
- test_user_view_service_request_details
> [1LP][RFR] Automating test user service request details

- cfme/services/myservice/ui.py
- cfme/tests/services/test_service_catalogs_multi_region.py
{{ pytest: -vv --long-running --use-provider complete -k test_service_provision_retire_from_global_region_ansible cfme/tests/services/test_service_catalogs_multi_region.py }}
> [RFR] Automate multi-region ansible tower service retirement

- cfme/configure/configuration/region_settings.py
- cfme/tests/configure/test_config_manual.py
- cfme/tests/test_replication.py
Remove the manual test `test_replication_subscription_crud` and automate replication subscription updates in `test_replication_subscription_update`. Creation and deletion tests already exist.
{{ pytest: -vv --long-running -k test_replication_subscription_update cfme/tests/test_replication.py }}
> [RFR] Automate replication subscription update

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/tests/services/test_catalog_item.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
{{pytest: cfme/tests/services/test_catalog_item.py::test_upload_delete_custom_image_on_bundle --long-running -svvvv }}
> [1LP][RFR] Automating upload/remove image on catalog bundle test

- cfme/services/catalogs/catalog_items/ansible_catalog_items.py
- cfme/tests/ansible/test_embedded_ansible_services.py
Automated BZ
- https://bugzilla.redhat.com/show_bug.cgi?id=1810477
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py::test_ansible_service_check_escalate_privilege --long-running }}
> [1LP][RFR] Add new test for BZ-1810477

- cfme/tests/distributed/test_appliance_manual.py
This PR removes the manual test `test_distributed_zone_in_different_networks`. It doesn't appear to be based on any known BZ or customer case, and general distributed / multi-appliance functionality is already automated in other tests.
> [1LP][RFR][NOTEST] Remove manual test test_distributed_zone_in_different_networks

- cfme/tests/ansible/test_embedded_ansible_manual.py
- cfme/tests/ansible/test_embedded_ansible_services.py
Automated test_embed_tower_order_service_extra_vars, which covers testing of [BZ-1444831](https://bugzilla.redhat.com/show_bug.cgi?id=1444831)
{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py::test_embed_tower_order_service_extra_vars --long-running }}
> [RFR] Automate test_embed_tower_order_service_extra_vars

- cfme/tests/services/test_config_provider_servicecatalogs.py
Adds skip for https://github.com/ManageIQ/manageiq/issues/20382 and https://github.com/ManageIQ/integration_tests/issues/10294
{{ py.test: -sv --use-provider complete --long-running --provider-limit=4 cfme/tests/services/test_config_provider_servicecatalogs.py }}
> [RFR] Add skip for manageiq GH 20382

- cfme/tests/ansible/test_embedded_ansible_automate.py
Automated test for BZ's
- https://bugzilla.redhat.com/show_bug.cgi?id=1734629
- https://bugzilla.redhat.com/show_bug.cgi?id=1734630
{{ pytest: cfme/tests/ansible/test_embedded_ansible_automate.py::test_automate_ansible_playbook_set_stats --long-running }}
> [1LP][RFR] Add test coverage for BZ-1734629 and BZ-1734630

- cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
- cfme/utils/ssh.py
- __Fixing__ cloud-init tests that didn't work as they needed IPv6 connectivity between the test executing machine and the VM on provider. This was solved by tunnelling to the provider host and using any IP reported by provder that is connective from the host.
__Adding__ test for DHCP configuration.
{{py.test: -sv cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init_payload --long-running --use-provider complete }}
> [RFR] fix cloud-init tests

- cfme/tests/configure/test_register_appliance.py
__Adds blocker for__ https://github.com/ManageIQ/manageiq/issues/20390
{{ py.test: -sv 'cfme/tests/configure/test_register_appliance.py::test_rh_registration' --long-running --use-provider 'complete' }}
> [1LP][RFR] Add subscribtion test blocker.

- cfme/common/provider.py
- cfme/common/vm.py
- cfme/fixtures/vm.py
- cfme/tests/infrastructure/test_vm_migrate.py
- cfme/tests/infrastructure/test_vm_ownership.py
- cfme/tests/infrastructure/test_vm_power_control.py
- cfme/tests/infrastructure/test_vm_reconfigure.py
- __Updating tests__ to use a common create_vm fixture instead of local ones.
{{ pytest: --long-running cfme/tests/infrastructure/test_vm_migrate.py::test_vm_migrate cfme/tests/infrastructure/test_vm_ownership.py::test_rename_vm --long-running cfme/tests/infrastructure/test_vm_power_control.py cfme/tests/infrastructure/test_vm_reconfigure.py }}
> [RFR] Remove local VM fixtures and replace usage with global create_vm fixture.

- cfme/services/catalogs/catalog_items/__init__.py
- cfme/services/myservice/ui.py
- cfme/tests/ansible/test_embedded_ansible_services.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/configure/test_access_control.py
- Added test to check provisioned service's standard output of particular user
- Fixed standard_output locator of service
- Written view for "Set Ownership" for ansible catalog item.
- `test_appliance_console_logfile_config_reboot` moved test to manual only because need large effort to automate it.
{{pytest: cfme/tests/configure/test_access_control.py::test_ansible_playbook_stdout cfme/tests/ansible/test_embedded_ansible_services.py::test_ansible_group_id_in_payload  cfme/tests/ansible/test_embedded_ansible_services.py::test_service_ansible_playbook_pass_extra_vars  --long-running -v}}
> [1LP][RFR] - Check STDOUT of provisioned ansible service

- cfme/utils/browser.py
When the chromeOptions was set, we should not throw them away, but keep them. I found this when trying to debug some problem with the selenium and chrome. IIRC it was the parameters set in env.yaml.local which were not honoured.
> [RFR] browser chrome options

- cfme/tests/cloud_infra_common/test_provisioning_manual.py
- cfme/tests/infrastructure/test_iso_provisioning.py
Adding tests/Enhancement: Added test for the provisioning of multiple iso datastores with 2 providers. The test assures that a secondary datastore can be added as long as there is at least 2 distinct providers. Additional markers were introduced to replace the outdated 'pytest_generate_tests()' method. 
{{pytest: cfme/tests/infrastructure/test_iso_provisioning.py -k "test_add_multiple_iso_datastore"}}
> [1LP][RFR] Add multiple_iso_datastore test and minor improvements 

- cfme/utils/appliance/__init__.py
This PR will increase time out for wait_for_ssh method.
https://github.com/ManageIQ/integration_tests/blob/2b861a399464db98b384888dab784c97ee876fa4/cfme/utils/appliance/__init__.py#L1676
Instance creation is async operation in OSP, though command completed successfully, however it takes some time (60 seconds) to boot the OS and make ssh service available to login. The time out of 30 seconds is really not enough here, So this PR is increasing the timeout to 120 sec.
> [1LP][RFR] Increasing timeout interval

- cfme/services/myservice/ssui.py
- cfme/tests/services/test_dialog_element_in_catalog.py
- cfme/tests/services/test_service_catalog_dialog_manual.py
- cfme/tests/ssui/test_ssui_service_catalogs.py
{{pytest: cfme/tests/ssui/test_ssui_service_catalogs.py::test_ssui_ansible_playbook_stdout --long-running -svvvv }}
> [1LP][RFR] Automating ssui Ansible_playbook standard output test

- cfme/services/requests.py
This PR backports a fix from master to 5.10-breakpoint-patched, so that `RequestsView.find_request()` loops over a static list of dictionary keys instead of the dynamic view returned by `dict.keys()` in Python 3. This fixes exceptions like the following:
```
>       for key in cells.keys():
E       RuntimeError: dictionary keys changed during iteration
cfme/services/requests.py:302: RuntimeError (cfme/fixtures/log.py:83)
```
> [RFR] 5.10 Fix find_request to loop over static list of dict keys

- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
There are no plans to fix the generic object button / button group deletion flash issue described in BZ's 1744478 and 1773666 (which are both closed) for 5.10, so I've removed the BZ blockers from the 5.10 branch, and explicitly used the 5.10-specific flash message text.
> [RFR] Fix flash messages for generic object button deletion in 5.10

- cfme/tests/infrastructure/test_provisioning_dialog.py
- cfme/tests/infrastructure/test_vm_clone.py
- __Removing BZ workaround__ as BZ is fixed.
{{ py.test: -v --use-provider complete cfme/tests/infrastructure/test_vm_clone.py::test_template_clone  cfme/tests/infrastructure/test_provisioning_dialog.py::test_power_on_or_off_after_provision  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init --use-provider complete --ignore cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py::test_provision_cloud_init[ec2] }}
The ec2 test failed because of other known issue: RHCFQE-14596
> [1LP][RFR] Remove the workaround for BZ 1797706

- .travis.yml
- cfme/scripting/disable_bytecode.py
- cfme/scripting/quickstart/__init__.py
- cfme/scripting/quickstart/system.py
- requirements/frozen.txt
Travis is failing with a distutils import error.
Couldn't replicate locally, but travis's ubuntu image is running with python 3.7.1.
Updated travis to bionic and cleaned up the config a bit
Explicitly set virtualenv path for quickstart
Ignored/logged site import failure in disable_bytecache, as it should be non-blocking failure.
```
QS $ /home/travis/virtualenv/python3.7.1/bin/python3 -m cfme.scripting.disable_bytecode
Traceback (most recent call last):
File "/home/travis/build/ManageIQ/integration_tests/cfme/scripting/disable_bytecode.py", line 24, in <module>
site_packages = distutils.sysconfig_get_python_lib()
AttributeError: module 'distutils' has no attribute 'sysconfig_get_python_lib'
During handling of the above exception, another exception occurred:
Traceback (most recent call …
```
> [RFR] Fix travis distutils

- cfme/automate/explorer/method.py
- cfme/fixtures/ansible_fixtures.py
- cfme/services/myservice/ui.py
- cfme/services/requests.py
- cfme/tests/ansible/test_embedded_ansible_actions.py
- cfme/tests/ansible/test_embedded_ansible_automate.py
- cfme/tests/ansible/test_embedded_ansible_services.py
- cfme/utils/log_validator.py
Renamed funcscope
Test failures due to the requests having the same name when coming from the same catalog item
The requests should be cleaned up after every test to ensure there's no collision, and that no test has to assume which of the requests are related to the catalog item ordered for that test scope
This should resolve some failures seen in PRT on #10289
There are some tests still failing, but I'd like to scope the PR at the current changes. @Gauravtalreja1 has already been keeping an eye on them, and can follow-up this PR with specific test fixes.
`test_embedded_ansible_services` pass rate increased from 40% to ~72%
> [1LP][RFR] Refactor ansible service fixtures and embedded services tests

- cfme/services/catalogs/catalog_items/ansible_catalog_items.py
- cfme/tests/services/test_service_catalogs_multi_region.py
Automate embedded Ansible service ordering and retirement from the global appliance of a multi-region environment.
{{ pytest: -vv --long-running --use-provider complete -k test_service_provision_retire_from_global_region_embedded_ansible cfme/tests/services/test_service_catalogs_multi_region.py }}
The tests all passed in the PRT tasks's cfme.log, so I don't know why it's showing as failed.
> [RFR] Automate multi-region embedded ansible service retirement

- cfme/utils/appliance/plugin.py
Add annotations to appliance_plugins. This makes Pycharm resolve the types of the plugins, for example `IPAppliance.appliance_console` for example, that helps when writing and understanding the code and surely discovering bugs in the code 
There is a test for the certs in the CFME appliance that used to be blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1712929. BZ is closed as WONTFIX. The test is failing. Not related to the PR.
> [1LP][RFR] Add appliance pugins annotations

- cfme/tests/cli/test_appliance_cli.py
- cfme/tests/cli/test_appliance_console.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/tests/cli/test_appliance_update.py
- cfme/utils/appliance/console.py
The commit messages of the commits are describing why and what is being done. In summary:
* dedup work
* removal of obsolete tests or dead code
* blocker added
I didn't specify what to run. I was removing stuff. The only test that got changed slightly seem to be broken and is blocked now:
http://TRACKERBOT/pr10300-r2911-downstream-511z-SnMcfa/artifacts/report.html#cfme/tests/cli/test_appliance_cli.py/test_appliance_console_cli_ha_crud
the failures seem unrelated. I reran the tests locally and they PASSED. Just for curiosity I reran the PRT as well.
> [1LP][RFR] Sort out DB HA related tests

- cfme/common/datastore_views.py
- cfme/common/host_views.py
- cfme/common/provider.py
- cfme/infrastructure/datastore.py
- cfme/infrastructure/host.py
- cfme/tests/cloud_infra_common/test_relationships.py
- cfme/tests/infrastructure/test_datastore_analysis.py
- cfme/tests/webui/test_general_ui.py
- __Workaround__ https://github.com/ManageIQ/manageiq/issues/20367 by starting the SSA using different navigation path, which __fixes__  cfme/tests/infrastructure/test_datastore_analysis.py tests.
- __Improvement__: moved some items to solve circular dependencies between modules.
There was some openstack related test that failed. Doesn't seem related to my PR.
> [1LP][RFR] Fix datastore SmartState analysis tests

- cfme/infrastructure/config_management/__init__.py
- cfme/tests/infrastructure/test_providers.py
- __Adding tests__ for BZ 1819310
**needs PR !939 to yamls merged**
{{pytest: --use-provider complete --long-running -v cfme/tests/infrastructure/test_providers.py::test_awx_with_special_chars_refreshes}}
> [RFR] Automate BZ 1819310 - The special chars in AWX

- cfme/tests/cloud_infra_common/test_discovery_and_support.py
- cfme/tests/configure/test_config_manual.py
1. test_default_miq_group_is_tenant_group
{{ pytest: cfme/tests/cloud_infra_common/test_discovery_and_support.py::test_default_miq_group_is_tenant_group -svvv }}
> [1LP][RFR]Automate: test_default_miq_group_is_tenant_group

- cfme/tests/configure/test_db_backup_schedule.py
The BZ is fixed in the first 5.11 we have. The last unfixed CFME is 5.10.5.1. When the filling code is disabled, this command succeeds:
```
py.test --use-sprout --sprout-group downstream-510z -sv --use-provider complete 'cfme/tests/configure/test_db_backup_schedule.py' --sprout-user-key jhenner --pdb  --sprout-version 5.10.5.1 
``` 
when enabled, the same cmdline fails with 
```
"[----] E, [2020-09-08T14:40:17.729568 #14300:a40f60] ERROR -- : MIQ(MiqQueue#deliver) Message id: [164], Error: [undefined method `path' for nil:NilClass]"
...
E               cfme.utils.log_validator.FailPatternMatchError: "Pattern 'ERROR': Expected failure pattern found in log."
```
On newer CFME the test passes even with the /tmp almost full (all the code in this PR enablde). This makes me sure the test is …
> [RFR] Implement test for customer BZ 1703278 (backup to /tmp)

- cfme/fixtures/ansible_tower.py
- cfme/tests/automate/test_ansible_tower_automate.py
- cfme/tests/services/test_ansible_workflow_servicecatalogs.py
- cfme/tests/services/test_config_provider_servicecatalogs.py
Make the AWX tests running fine against the tower 3.6 that I've got fom @nachandr and manually prepared to make the tests passing.
Needs GITLAB/cfme-qe/cfme-qe-yamls/-/merge_requests/940
Disabled at the moment: {{pytest: --long-running -v 'cfme/tests/services/test_config_provider_servicecatalogs.py' 'cfme/tests/services/test_ansible_workflow_servicecatalogs.py' --use-provider complete}}
> [RFR] Make AWX 3.6 work fine

- cfme/cloud/provider/openstack.py
- __Fixing__ OpenStack Console test to accommodate new elements in OSP 16 based VM consoles
{{pytest: cfme/tests/cloud_infra_common/test_html5_vm_console.py --use-provider env-rhos16 --use-provider env-rhos13 -k 'test_html5_vm_console' -vvv }}
> [RFR] updating openstack console to use right elements for OSP 16

- cfme/tests/infrastructure/test_providers.py
... just to make the resolution of a possible problem less time consuming.
{{pytest: --use-provider complete --long-running -v cfme/tests/infrastructure/test_providers.py::test_awx_with_special_chars_refreshes}}
> [RFR] Add refresh to the funky characters test fixture

- cfme/fixtures/appliance.py
- cfme/fixtures/cli.py
- cfme/tests/distributed/test_appliance_replication.py
Added module-scoped multi-region appliance fixture `replicated_appliances_modscope`, and replaced the function-scoped with this new module-scoped fixture in the tests in `cfme/tests/distributed/test_appliance_replication.py`. Because the tests previously didn't have to worry about cleanup, I've also added some finalizers to remove provider and other records after each test.
{{ pytest: --long-running --use-provider complete -k 'test_replication_ or test_appliance_replicate_' cfme/tests/distributed/test_appliance_replication.py }}
> [RFR] Add module-scoped replicated_appliances fixture

- cfme/services/myservice/rest.py
- cfme/tests/services/test_service_catalogs_multi_region.py
1. test_service_provision_retire_from_global_region_generic
1. Implement `retire` service for REST API.
{{ pytest: cfme/tests/services/test_service_catalogs_multi_region.py::test_service_provision_retire_from_global_region_generic --long-running -vvv }}
> [RFR]Automate: test_service_provision_retire_from_global_region_generic

- cfme/tests/infrastructure/test_datastore_analysis.py
Removing RHV datastore tests as BZ 20367 is fixed. I am not sure whether the SSA of RHV datastores ever worked but anyway: the button for starting the analysis is now disabled hopefully everywhere (talking about RHV related pages). 
This PR is keeping testing SSA and its starting with both navigation paths I previously discovered on vsphere providers.
{{ py.test: --use-provider complete 'cfme/tests/infrastructure/test_datastore_analysis.py::test_run_datastore_analysis' -v }}
> [RFR] BZ_20367_fixed

- cfme/tests/configure/test_access_control.py
This was missed in the original PR for ansible service test fixture refactoring. The view now uses proper tabs, which do not need to be explicitly clicked.
> [1LP][RFR] Update use of provisioning tab in ansible tower service

- cfme/common/provider.py
- cfme/infrastructure/config_management/__init__.py
- cfme/tests/cloud_infra_common/test_rest_providers.py
- cfme/tests/infrastructure/test_config_management_rest.py
- widgetastic_manageiq/__init__.py
- __Fixing__ 
1. Tests related to config manager rest.
1. Merged test cases for normal providers and config managers.
{{ pytest: cfme/tests/cloud_infra_common/test_rest_providers.py --use-provider=complete -vvvv }}
> [RFR] Refactor provider rest tests

- cfme/fixtures/cli.py
- cfme/tests/cli/test_appliance_console_db_restore.py
- cfme/utils/appliance/console.py
* Adds covering of the customer bug by rebooting the secondary first to make sure it boots into a state that is ready to take over.
https://github.com/ManageIQ/integration_tests/pull/10327/files#diff-3c0b49bb78a46b38be44a0e843f40270R467
* Increase timeout for the appliance_console welcome screen to appear.
* Other changes were just some types definitions and naming to make this modification and the future maintenance of the code easier.
> [RFR] Cover cust. BZ 1856470 - repmgr10 failover fail.

- cfme/tests/infrastructure/test_provisioning_dialog.py
Stop test_provisioning_dialog from collecting providers it shouldn't
> Update provider marker in test_provisioning_dialog

- cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py
This PR marks `test_generic_object_button_execute_playbook` as manual-only, as it has been decided not to automate it.
> [RFR][NOTEST] Mark test_generic_object_button_execute_playbook as manual-only

- cfme/fixtures/ansible_fixtures.py
Test was failing as it was trying to create ansible cred before enabling ansible. 
{{pytest: cfme/tests/automate/custom_button/test_infra_objects_ansible.py -k test_custom_button_ansible_automate_infra_obj[Clusters-virtualcenter-Localhost] -sqvv }}
> [1LP][RFR] fix custom button wait for ansible issue

- cfme/services/myservice/__init__.py
- cfme/services/myservice/ui.py
- cfme/tests/services/test_service_catalogs_multi_region.py
This PR automates multi-region service provisioning and retirement for a catalog containing a catalog bundle. The remaining manual test for multi-region service retirement, for catalogs using orchestration templates, is also marked as `manualonly`, because after internal discussion about the bug described in https://bugzilla.redhat.com/show_bug.cgi?id=1754543 , we decided that the possible workarounds to get orchestration template creation working in automation are not worth the effort. 
{{ pytest: -vv --use-provider complete --long-running -k test_service_provision_retire_from_global_region_bundle cfme/tests/services/test_service_catalogs_multi_region.py }}
> [RFR] Automate test_service_provision_retire_from_global_region_bundle

- cfme/tests/automate/generic_objects/test_definitions.py
- cfme/tests/distributed/test_appliance_manual.py
- cfme/tests/intelligence/test_chargeback_manual.py
Mark some tests that will not be automated as 'manual only'.
> [RFR] [NOTEST] Mark tests as manualonly.

- cfme/tests/services/test_provision_stack.py
- widgetastic_manageiq/__init__.py
Some time ago, the CodeMirror component used for entering yaml templates started failing to get filled by selenium. There are currently two ON_QA bugs related to CodeMirror but even with them "fixed" I either did get indenting wrong (which is significant for yamls) or nothing else than parentheses `{` being input.
This PR set's the content of the CM using Javascript. Perhaps not ideal, but surely good enough to have the tests working.
From first glance the errors on PRT are not related. The tests have not been executed for a while or were executed failing on the CodeMirror. I think most of them belong to @niyazRedhat. Niyaz, can you take a look?
{{ pytest: --use-sprout -s --sprout-group downstream-511z -sv 'cfme/tests/services/test_provision_stack.py'  -v --use-provider 'complete' …
> [RFR] Fix CodeMirror filling.

- cfme/tests/infrastructure/test_iso_provisioning.py
- cfme/tests/services/test_iso_service_catalogs.py
The libvirt of the required version was installed on RHV44. This makes the blocker for 1783355 obsolete. There is though another issue.
The `test_iso_provision_from_template` is also affected by BZ 1888748.
> [1LP][RFR] Replace the fixed blocker for BZ 1783355 with BZ 1888748

- cfme/tests/configure/test_db_backup_schedule.py
I believe the bug is already covered
> [RFR]Add coverage note for BZ 1767895

- cfme/tests/infrastructure/test_vm_migrate.py
- cfme/tests/test_replication.py
- Adding test BZ-1879912 blocker for **test_vm_migrate** test case
- Fixed **test_replication_powertoggle** test case. ( testcase was checking OSP instance on the different provider and we were creating instance on diffrent provider.)
{{ pytest: cfme/tests/test_replication.py::test_replication_powertoggle cfme/tests/infrastructure/test_vm_migrate.py::test_vm_migrate   -svvvv  --long-running  --use-template-cache
}}
> [1LP][RFR ] - Fix testcase 
